#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\APPDATA.ahk" {APPDATA}
#Import export ".\APPSTATISTICS.ahk" {APPSTATISTICS}
#Import export ".\Apis.ahk" {*}
#Import export ".\AppDomainHelper.ahk" {AppDomainHelper}
#Import export ".\ApplicationProcessRecycleInfo.ahk" {ApplicationProcessRecycleInfo}
#Import export ".\ApplicationProcessStatistics.ahk" {ApplicationProcessStatistics}
#Import export ".\ApplicationProcessSummary.ahk" {ApplicationProcessSummary}
#Import export ".\ApplicationSummary.ahk" {ApplicationSummary}
#Import export ".\AutoSvcs_Error_Constants.ahk" {AutoSvcs_Error_Constants}
#Import export ".\ByotServerEx.ahk" {ByotServerEx}
#Import export ".\CLSIDDATA.ahk" {CLSIDDATA}
#Import export ".\CLSIDDATA2.ahk" {CLSIDDATA2}
#Import export ".\COMAdminAccessChecksLevelOptions.ahk" {COMAdminAccessChecksLevelOptions}
#Import export ".\COMAdminActivationOptions.ahk" {COMAdminActivationOptions}
#Import export ".\COMAdminApplicationExportOptions.ahk" {COMAdminApplicationExportOptions}
#Import export ".\COMAdminApplicationInstallOptions.ahk" {COMAdminApplicationInstallOptions}
#Import export ".\COMAdminAuthenticationCapabilitiesOptions.ahk" {COMAdminAuthenticationCapabilitiesOptions}
#Import export ".\COMAdminAuthenticationLevelOptions.ahk" {COMAdminAuthenticationLevelOptions}
#Import export ".\COMAdminCatalog.ahk" {COMAdminCatalog}
#Import export ".\COMAdminCatalogCollection.ahk" {COMAdminCatalogCollection}
#Import export ".\COMAdminCatalogObject.ahk" {COMAdminCatalogObject}
#Import export ".\COMAdminComponentFlags.ahk" {COMAdminComponentFlags}
#Import export ".\COMAdminComponentType.ahk" {COMAdminComponentType}
#Import export ".\COMAdminErrorCodes.ahk" {COMAdminErrorCodes}
#Import export ".\COMAdminFileFlags.ahk" {COMAdminFileFlags}
#Import export ".\COMAdminImpersonationLevelOptions.ahk" {COMAdminImpersonationLevelOptions}
#Import export ".\COMAdminInUse.ahk" {COMAdminInUse}
#Import export ".\COMAdminOS.ahk" {COMAdminOS}
#Import export ".\COMAdminQCMessageAuthenticateOptions.ahk" {COMAdminQCMessageAuthenticateOptions}
#Import export ".\COMAdminServiceOptions.ahk" {COMAdminServiceOptions}
#Import export ".\COMAdminServiceStatusOptions.ahk" {COMAdminServiceStatusOptions}
#Import export ".\COMAdminSynchronizationOptions.ahk" {COMAdminSynchronizationOptions}
#Import export ".\COMAdminThreadingModels.ahk" {COMAdminThreadingModels}
#Import export ".\COMAdminTransactionOptions.ahk" {COMAdminTransactionOptions}
#Import export ".\COMAdminTxIsolationLevelOptions.ahk" {COMAdminTxIsolationLevelOptions}
#Import export ".\COMEvents.ahk" {COMEvents}
#Import export ".\COMPLUS_APPTYPE.ahk" {COMPLUS_APPTYPE}
#Import export ".\COMSVCSEVENTINFO.ahk" {COMSVCSEVENTINFO}
#Import export ".\CRMClerk.ahk" {CRMClerk}
#Import export ".\CRMFLAGS.ahk" {CRMFLAGS}
#Import export ".\CRMREGFLAGS.ahk" {CRMREGFLAGS}
#Import export ".\CRMRecoveryClerk.ahk" {CRMRecoveryClerk}
#Import export ".\CSC_Binding.ahk" {CSC_Binding}
#Import export ".\CSC_COMTIIntrinsicsConfig.ahk" {CSC_COMTIIntrinsicsConfig}
#Import export ".\CSC_IISIntrinsicsConfig.ahk" {CSC_IISIntrinsicsConfig}
#Import export ".\CSC_InheritanceConfig.ahk" {CSC_InheritanceConfig}
#Import export ".\CSC_PartitionConfig.ahk" {CSC_PartitionConfig}
#Import export ".\CSC_SxsConfig.ahk" {CSC_SxsConfig}
#Import export ".\CSC_SynchronizationConfig.ahk" {CSC_SynchronizationConfig}
#Import export ".\CSC_ThreadPool.ahk" {CSC_ThreadPool}
#Import export ".\CSC_TrackerConfig.ahk" {CSC_TrackerConfig}
#Import export ".\CSC_TransactionConfig.ahk" {CSC_TransactionConfig}
#Import export ".\CServiceConfig.ahk" {CServiceConfig}
#Import export ".\ClrAssemblyLocator.ahk" {ClrAssemblyLocator}
#Import export ".\CoMTSLocator.ahk" {CoMTSLocator}
#Import export ".\ComServiceEvents.ahk" {ComServiceEvents}
#Import export ".\ComSystemAppEventData.ahk" {ComSystemAppEventData}
#Import export ".\ComponentHangMonitorInfo.ahk" {ComponentHangMonitorInfo}
#Import export ".\ComponentStatistics.ahk" {ComponentStatistics}
#Import export ".\ComponentSummary.ahk" {ComponentSummary}
#Import export ".\Constants.ahk" {*}
#Import export ".\ContextInfo.ahk" {ContextInfo}
#Import export ".\ContextInfo2.ahk" {ContextInfo2}
#Import export ".\CrmLogRecordRead.ahk" {CrmLogRecordRead}
#Import export ".\CrmTransactionState.ahk" {CrmTransactionState}
#Import export ".\DUMPTYPE.ahk" {DUMPTYPE}
#Import export ".\DispenserManager.ahk" {DispenserManager}
#Import export ".\Dummy30040732.ahk" {Dummy30040732}
#Import export ".\EventServer.ahk" {EventServer}
#Import export ".\GetAppTrackerDataFlags.ahk" {GetAppTrackerDataFlags}
#Import export ".\GetSecurityCallContextAppObject.ahk" {GetSecurityCallContextAppObject}
#Import export ".\HANG_INFO.ahk" {HANG_INFO}
#Import export ".\IAppDomainHelper.ahk" {IAppDomainHelper}
#Import export ".\IAssemblyLocator.ahk" {IAssemblyLocator}
#Import export ".\IAsyncErrorNotify.ahk" {IAsyncErrorNotify}
#Import export ".\ICOMAdminCatalog.ahk" {ICOMAdminCatalog}
#Import export ".\ICOMAdminCatalog2.ahk" {ICOMAdminCatalog2}
#Import export ".\ICOMLBArguments.ahk" {ICOMLBArguments}
#Import export ".\ICatalogCollection.ahk" {ICatalogCollection}
#Import export ".\ICatalogObject.ahk" {ICatalogObject}
#Import export ".\ICheckSxsConfig.ahk" {ICheckSxsConfig}
#Import export ".\IComActivityEvents.ahk" {IComActivityEvents}
#Import export ".\IComApp2Events.ahk" {IComApp2Events}
#Import export ".\IComAppEvents.ahk" {IComAppEvents}
#Import export ".\IComCRMEvents.ahk" {IComCRMEvents}
#Import export ".\IComExceptionEvents.ahk" {IComExceptionEvents}
#Import export ".\IComIdentityEvents.ahk" {IComIdentityEvents}
#Import export ".\IComInstance2Events.ahk" {IComInstance2Events}
#Import export ".\IComInstanceEvents.ahk" {IComInstanceEvents}
#Import export ".\IComLTxEvents.ahk" {IComLTxEvents}
#Import export ".\IComMethod2Events.ahk" {IComMethod2Events}
#Import export ".\IComMethodEvents.ahk" {IComMethodEvents}
#Import export ".\IComMtaThreadPoolKnobs.ahk" {IComMtaThreadPoolKnobs}
#Import export ".\IComObjectConstruction2Events.ahk" {IComObjectConstruction2Events}
#Import export ".\IComObjectConstructionEvents.ahk" {IComObjectConstructionEvents}
#Import export ".\IComObjectEvents.ahk" {IComObjectEvents}
#Import export ".\IComObjectPool2Events.ahk" {IComObjectPool2Events}
#Import export ".\IComObjectPoolEvents.ahk" {IComObjectPoolEvents}
#Import export ".\IComObjectPoolEvents2.ahk" {IComObjectPoolEvents2}
#Import export ".\IComQCEvents.ahk" {IComQCEvents}
#Import export ".\IComResourceEvents.ahk" {IComResourceEvents}
#Import export ".\IComSecurityEvents.ahk" {IComSecurityEvents}
#Import export ".\IComStaThreadPoolKnobs.ahk" {IComStaThreadPoolKnobs}
#Import export ".\IComStaThreadPoolKnobs2.ahk" {IComStaThreadPoolKnobs2}
#Import export ".\IComThreadEvents.ahk" {IComThreadEvents}
#Import export ".\IComTrackingInfoCollection.ahk" {IComTrackingInfoCollection}
#Import export ".\IComTrackingInfoEvents.ahk" {IComTrackingInfoEvents}
#Import export ".\IComTrackingInfoObject.ahk" {IComTrackingInfoObject}
#Import export ".\IComTrackingInfoProperties.ahk" {IComTrackingInfoProperties}
#Import export ".\IComTransaction2Events.ahk" {IComTransaction2Events}
#Import export ".\IComTransactionEvents.ahk" {IComTransactionEvents}
#Import export ".\IComUserEvent.ahk" {IComUserEvent}
#Import export ".\IContextProperties.ahk" {IContextProperties}
#Import export ".\IContextSecurityPerimeter.ahk" {IContextSecurityPerimeter}
#Import export ".\IContextState.ahk" {IContextState}
#Import export ".\ICreateWithLocalTransaction.ahk" {ICreateWithLocalTransaction}
#Import export ".\ICreateWithTipTransactionEx.ahk" {ICreateWithTipTransactionEx}
#Import export ".\ICreateWithTransactionEx.ahk" {ICreateWithTransactionEx}
#Import export ".\ICrmCompensator.ahk" {ICrmCompensator}
#Import export ".\ICrmCompensatorVariants.ahk" {ICrmCompensatorVariants}
#Import export ".\ICrmFormatLogRecords.ahk" {ICrmFormatLogRecords}
#Import export ".\ICrmLogControl.ahk" {ICrmLogControl}
#Import export ".\ICrmMonitor.ahk" {ICrmMonitor}
#Import export ".\ICrmMonitorClerks.ahk" {ICrmMonitorClerks}
#Import export ".\ICrmMonitorLogRecords.ahk" {ICrmMonitorLogRecords}
#Import export ".\IDispenserDriver.ahk" {IDispenserDriver}
#Import export ".\IDispenserManager.ahk" {IDispenserManager}
#Import export ".\IEnumNames.ahk" {IEnumNames}
#Import export ".\IEventServerTrace.ahk" {IEventServerTrace}
#Import export ".\IGetAppTrackerData.ahk" {IGetAppTrackerData}
#Import export ".\IGetContextProperties.ahk" {IGetContextProperties}
#Import export ".\IGetSecurityCallContext.ahk" {IGetSecurityCallContext}
#Import export ".\IHolder.ahk" {IHolder}
#Import export ".\ILBEvents.ahk" {ILBEvents}
#Import export ".\IMTSActivity.ahk" {IMTSActivity}
#Import export ".\IMTSCall.ahk" {IMTSCall}
#Import export ".\IMTSLocator.ahk" {IMTSLocator}
#Import export ".\IManagedActivationEvents.ahk" {IManagedActivationEvents}
#Import export ".\IManagedObjectInfo.ahk" {IManagedObjectInfo}
#Import export ".\IManagedPoolAction.ahk" {IManagedPoolAction}
#Import export ".\IManagedPooledObj.ahk" {IManagedPooledObj}
#Import export ".\IMessageMover.ahk" {IMessageMover}
#Import export ".\IMtsEventInfo.ahk" {IMtsEventInfo}
#Import export ".\IMtsEvents.ahk" {IMtsEvents}
#Import export ".\IMtsGrp.ahk" {IMtsGrp}
#Import export ".\IObjPool.ahk" {IObjPool}
#Import export ".\IObjectConstruct.ahk" {IObjectConstruct}
#Import export ".\IObjectConstructString.ahk" {IObjectConstructString}
#Import export ".\IObjectContext.ahk" {IObjectContext}
#Import export ".\IObjectContextActivity.ahk" {IObjectContextActivity}
#Import export ".\IObjectContextInfo.ahk" {IObjectContextInfo}
#Import export ".\IObjectContextInfo2.ahk" {IObjectContextInfo2}
#Import export ".\IObjectContextTip.ahk" {IObjectContextTip}
#Import export ".\IObjectControl.ahk" {IObjectControl}
#Import export ".\IPlaybackControl.ahk" {IPlaybackControl}
#Import export ".\IPoolManager.ahk" {IPoolManager}
#Import export ".\IProcessInitializer.ahk" {IProcessInitializer}
#Import export ".\ISecurityCallContext.ahk" {ISecurityCallContext}
#Import export ".\ISecurityCallersColl.ahk" {ISecurityCallersColl}
#Import export ".\ISecurityIdentityColl.ahk" {ISecurityIdentityColl}
#Import export ".\ISecurityProperty.ahk" {ISecurityProperty}
#Import export ".\ISelectCOMLBServer.ahk" {ISelectCOMLBServer}
#Import export ".\ISendMethodEvents.ahk" {ISendMethodEvents}
#Import export ".\IServiceActivity.ahk" {IServiceActivity}
#Import export ".\IServiceCall.ahk" {IServiceCall}
#Import export ".\IServiceComTIIntrinsicsConfig.ahk" {IServiceComTIIntrinsicsConfig}
#Import export ".\IServiceIISIntrinsicsConfig.ahk" {IServiceIISIntrinsicsConfig}
#Import export ".\IServiceInheritanceConfig.ahk" {IServiceInheritanceConfig}
#Import export ".\IServicePartitionConfig.ahk" {IServicePartitionConfig}
#Import export ".\IServicePool.ahk" {IServicePool}
#Import export ".\IServicePoolConfig.ahk" {IServicePoolConfig}
#Import export ".\IServiceSxsConfig.ahk" {IServiceSxsConfig}
#Import export ".\IServiceSynchronizationConfig.ahk" {IServiceSynchronizationConfig}
#Import export ".\IServiceSysTxnConfig.ahk" {IServiceSysTxnConfig}
#Import export ".\IServiceThreadPoolConfig.ahk" {IServiceThreadPoolConfig}
#Import export ".\IServiceTrackerConfig.ahk" {IServiceTrackerConfig}
#Import export ".\IServiceTransactionConfig.ahk" {IServiceTransactionConfig}
#Import export ".\IServiceTransactionConfigBase.ahk" {IServiceTransactionConfigBase}
#Import export ".\ISharedProperty.ahk" {ISharedProperty}
#Import export ".\ISharedPropertyGroup.ahk" {ISharedPropertyGroup}
#Import export ".\ISharedPropertyGroupManager.ahk" {ISharedPropertyGroupManager}
#Import export ".\ISystemAppEventData.ahk" {ISystemAppEventData}
#Import export ".\IThreadPoolKnobs.ahk" {IThreadPoolKnobs}
#Import export ".\ITransactionContext.ahk" {ITransactionContext}
#Import export ".\ITransactionContextEx.ahk" {ITransactionContextEx}
#Import export ".\ITransactionProperty.ahk" {ITransactionProperty}
#Import export ".\ITransactionProxy.ahk" {ITransactionProxy}
#Import export ".\ITransactionResourcePool.ahk" {ITransactionResourcePool}
#Import export ".\ITransactionStatus.ahk" {ITransactionStatus}
#Import export ".\ITxProxyHolder.ahk" {ITxProxyHolder}
#Import export ".\LBEvents.ahk" {LBEvents}
#Import export ".\LockModes.ahk" {LockModes}
#Import export ".\MessageMover.ahk" {MessageMover}
#Import export ".\MtsGrp.ahk" {MtsGrp}
#Import export ".\ObjectContext.ahk" {ObjectContext}
#Import export ".\ObjectControl.ahk" {ObjectControl}
#Import export ".\PoolMgr.ahk" {PoolMgr}
#Import export ".\RECYCLE_INFO.ahk" {RECYCLE_INFO}
#Import export ".\ReleaseModes.ahk" {ReleaseModes}
#Import export ".\SecurityCallContext.ahk" {SecurityCallContext}
#Import export ".\SecurityCallers.ahk" {SecurityCallers}
#Import export ".\SecurityIdentity.ahk" {SecurityIdentity}
#Import export ".\SecurityProperty.ahk" {SecurityProperty}
#Import export ".\ServicePool.ahk" {ServicePool}
#Import export ".\ServicePoolConfig.ahk" {ServicePoolConfig}
#Import export ".\SharedProperty.ahk" {SharedProperty}
#Import export ".\SharedPropertyGroup.ahk" {SharedPropertyGroup}
#Import export ".\SharedPropertyGroupManager.ahk" {SharedPropertyGroupManager}
#Import export ".\TRACKING_COLL_TYPE.ahk" {TRACKING_COLL_TYPE}
#Import export ".\TrackerServer.ahk" {TrackerServer}
#Import export ".\TransactionContext.ahk" {TransactionContext}
#Import export ".\TransactionContextEx.ahk" {TransactionContextEx}
#Import export ".\TransactionVote.ahk" {TransactionVote}
