#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Common\__Init.ahk" {*}
#Import export ".\ACCESS_MASKENUM.ahk" {ACCESS_MASKENUM}
#Import export ".\AUTHENTICATION_INFO.ahk" {AUTHENTICATION_INFO}
#Import export ".\AUTH_TYPE.ahk" {AUTH_TYPE}
#Import export ".\Apis.ahk" {*}
#Import export ".\BUCKETCATEGORIZE.ahk" {BUCKETCATEGORIZE}
#Import export ".\CASE_REQUIREMENT.ahk" {CASE_REQUIREMENT}
#Import export ".\CATEGORIZATION.ahk" {CATEGORIZATION}
#Import export ".\CATEGORIZATIONSET.ahk" {CATEGORIZATIONSET}
#Import export ".\CHANNEL_AGENT_FLAGS.ahk" {CHANNEL_AGENT_FLAGS}
#Import export ".\CLUSION_REASON.ahk" {CLUSION_REASON}
#Import export ".\COLUMNSET.ahk" {COLUMNSET}
#Import export ".\CONDITION_CREATION_OPTIONS.ahk" {CONDITION_CREATION_OPTIONS}
#Import export ".\CONTENTRESTRICTION.ahk" {CONTENTRESTRICTION}
#Import export ".\CREATESUBSCRIPTIONFLAGS.ahk" {CREATESUBSCRIPTIONFLAGS}
#Import export ".\CSearchLanguageSupport.ahk" {CSearchLanguageSupport}
#Import export ".\CSearchManager.ahk" {CSearchManager}
#Import export ".\CSearchRoot.ahk" {CSearchRoot}
#Import export ".\CSearchScopeRule.ahk" {CSearchScopeRule}
#Import export ".\CatalogPausedReason.ahk" {CatalogPausedReason}
#Import export ".\CatalogStatus.ahk" {CatalogStatus}
#Import export ".\CompoundCondition.ahk" {CompoundCondition}
#Import export ".\ConditionFactory.ahk" {ConditionFactory}
#Import export ".\Constants.ahk" {*}
#Import export ".\DATE_STRUCT.ahk" {DATE_STRUCT}
#Import export ".\DBACCESSORFLAGSENUM.ahk" {DBACCESSORFLAGSENUM}
#Import export ".\DBASYNCHOPENUM.ahk" {DBASYNCHOPENUM}
#Import export ".\DBASYNCHPHASEENUM.ahk" {DBASYNCHPHASEENUM}
#Import export ".\DBBINDEXT.ahk" {DBBINDEXT}
#Import export ".\DBBINDFLAGENUM.ahk" {DBBINDFLAGENUM}
#Import export ".\DBBINDING.ahk" {DBBINDING}
#Import export ".\DBBINDSTATUSENUM.ahk" {DBBINDSTATUSENUM}
#Import export ".\DBBINDURLFLAGENUM.ahk" {DBBINDURLFLAGENUM}
#Import export ".\DBBINDURLSTATUSENUM.ahk" {DBBINDURLSTATUSENUM}
#Import export ".\DBBOOKMARK.ahk" {DBBOOKMARK}
#Import export ".\DBCOLUMNACCESS.ahk" {DBCOLUMNACCESS}
#Import export ".\DBCOLUMNDESC.ahk" {DBCOLUMNDESC}
#Import export ".\DBCOLUMNDESCFLAGSENUM.ahk" {DBCOLUMNDESCFLAGSENUM}
#Import export ".\DBCOLUMNFLAGS15ENUM.ahk" {DBCOLUMNFLAGS15ENUM}
#Import export ".\DBCOLUMNFLAGSDEPRECATED.ahk" {DBCOLUMNFLAGSDEPRECATED}
#Import export ".\DBCOLUMNFLAGSENUM.ahk" {DBCOLUMNFLAGSENUM}
#Import export ".\DBCOLUMNFLAGSENUM20.ahk" {DBCOLUMNFLAGSENUM20}
#Import export ".\DBCOLUMNFLAGSENUM21.ahk" {DBCOLUMNFLAGSENUM21}
#Import export ".\DBCOLUMNFLAGSENUM26.ahk" {DBCOLUMNFLAGSENUM26}
#Import export ".\DBCOLUMNINFO.ahk" {DBCOLUMNINFO}
#Import export ".\DBCOMMANDPERSISTFLAGENUM.ahk" {DBCOMMANDPERSISTFLAGENUM}
#Import export ".\DBCOMMANDPERSISTFLAGENUM21.ahk" {DBCOMMANDPERSISTFLAGENUM21}
#Import export ".\DBCOMPAREENUM.ahk" {DBCOMPAREENUM}
#Import export ".\DBCOMPAREOPSENUM.ahk" {DBCOMPAREOPSENUM}
#Import export ".\DBCOMPAREOPSENUM20.ahk" {DBCOMPAREOPSENUM20}
#Import export ".\DBCONSTRAINTDESC.ahk" {DBCONSTRAINTDESC}
#Import export ".\DBCONSTRAINTTYPEENUM.ahk" {DBCONSTRAINTTYPEENUM}
#Import export ".\DBCONVERTFLAGSENUM.ahk" {DBCONVERTFLAGSENUM}
#Import export ".\DBCONVERTFLAGSENUM20.ahk" {DBCONVERTFLAGSENUM20}
#Import export ".\DBCOPYFLAGSENUM.ahk" {DBCOPYFLAGSENUM}
#Import export ".\DBCOST.ahk" {DBCOST}
#Import export ".\DBCOSTUNITENUM.ahk" {DBCOSTUNITENUM}
#Import export ".\DBDATACONVERTENUM.ahk" {DBDATACONVERTENUM}
#Import export ".\DBDATE.ahk" {DBDATE}
#Import export ".\DBDATETIM4.ahk" {DBDATETIM4}
#Import export ".\DBDATETIME.ahk" {DBDATETIME}
#Import export ".\DBDEFERRABILITYENUM.ahk" {DBDEFERRABILITYENUM}
#Import export ".\DBDELETEFLAGSENUM.ahk" {DBDELETEFLAGSENUM}
#Import export ".\DBEVENTPHASEENUM.ahk" {DBEVENTPHASEENUM}
#Import export ".\DBEXECLIMITSENUM.ahk" {DBEXECLIMITSENUM}
#Import export ".\DBFAILUREINFO.ahk" {DBFAILUREINFO}
#Import export ".\DBIMPLICITSESSION.ahk" {DBIMPLICITSESSION}
#Import export ".\DBINDEXCOLUMNDESC.ahk" {DBINDEXCOLUMNDESC}
#Import export ".\DBINDEX_COL_ORDERENUM.ahk" {DBINDEX_COL_ORDERENUM}
#Import export ".\DBLITERALENUM.ahk" {DBLITERALENUM}
#Import export ".\DBLITERALENUM20.ahk" {DBLITERALENUM20}
#Import export ".\DBLITERALENUM21.ahk" {DBLITERALENUM21}
#Import export ".\DBLITERALINFO.ahk" {DBLITERALINFO}
#Import export ".\DBMATCHTYPEENUM.ahk" {DBMATCHTYPEENUM}
#Import export ".\DBMEMOWNERENUM.ahk" {DBMEMOWNERENUM}
#Import export ".\DBMONEY.ahk" {DBMONEY}
#Import export ".\DBMOVEFLAGSENUM.ahk" {DBMOVEFLAGSENUM}
#Import export ".\DBOBJECT.ahk" {DBOBJECT}
#Import export ".\DBPARAMBINDINFO.ahk" {DBPARAMBINDINFO}
#Import export ".\DBPARAMFLAGSENUM.ahk" {DBPARAMFLAGSENUM}
#Import export ".\DBPARAMFLAGSENUM20.ahk" {DBPARAMFLAGSENUM20}
#Import export ".\DBPARAMINFO.ahk" {DBPARAMINFO}
#Import export ".\DBPARAMIOENUM.ahk" {DBPARAMIOENUM}
#Import export ".\DBPARAMS.ahk" {DBPARAMS}
#Import export ".\DBPARTENUM.ahk" {DBPARTENUM}
#Import export ".\DBPENDINGSTATUSENUM.ahk" {DBPENDINGSTATUSENUM}
#Import export ".\DBPOSITIONFLAGSENUM.ahk" {DBPOSITIONFLAGSENUM}
#Import export ".\DBPROMPTOPTIONSENUM.ahk" {DBPROMPTOPTIONSENUM}
#Import export ".\DBPROP.ahk" {DBPROP}
#Import export ".\DBPROPENUM.ahk" {DBPROPENUM}
#Import export ".\DBPROPENUM15.ahk" {DBPROPENUM15}
#Import export ".\DBPROPENUM20.ahk" {DBPROPENUM20}
#Import export ".\DBPROPENUM21.ahk" {DBPROPENUM21}
#Import export ".\DBPROPENUM25.ahk" {DBPROPENUM25}
#Import export ".\DBPROPENUM25_DEPRECATED.ahk" {DBPROPENUM25_DEPRECATED}
#Import export ".\DBPROPENUM26.ahk" {DBPROPENUM26}
#Import export ".\DBPROPENUMDEPRECATED.ahk" {DBPROPENUMDEPRECATED}
#Import export ".\DBPROPFLAGSENUM.ahk" {DBPROPFLAGSENUM}
#Import export ".\DBPROPFLAGSENUM21.ahk" {DBPROPFLAGSENUM21}
#Import export ".\DBPROPFLAGSENUM25.ahk" {DBPROPFLAGSENUM25}
#Import export ".\DBPROPFLAGSENUM26.ahk" {DBPROPFLAGSENUM26}
#Import export ".\DBPROPIDSET.ahk" {DBPROPIDSET}
#Import export ".\DBPROPINFO.ahk" {DBPROPINFO}
#Import export ".\DBPROPINFOSET.ahk" {DBPROPINFOSET}
#Import export ".\DBPROPOPTIONSENUM.ahk" {DBPROPOPTIONSENUM}
#Import export ".\DBPROPSET.ahk" {DBPROPSET}
#Import export ".\DBPROPSTATUSENUM.ahk" {DBPROPSTATUSENUM}
#Import export ".\DBPROPSTATUSENUM21.ahk" {DBPROPSTATUSENUM21}
#Import export ".\DBRANGEENUM.ahk" {DBRANGEENUM}
#Import export ".\DBRANGEENUM20.ahk" {DBRANGEENUM20}
#Import export ".\DBREASONENUM.ahk" {DBREASONENUM}
#Import export ".\DBREASONENUM15.ahk" {DBREASONENUM15}
#Import export ".\DBREASONENUM25.ahk" {DBREASONENUM25}
#Import export ".\DBRESOURCEKINDENUM.ahk" {DBRESOURCEKINDENUM}
#Import export ".\DBRESULTFLAGENUM.ahk" {DBRESULTFLAGENUM}
#Import export ".\DBROWCHANGEKINDENUM.ahk" {DBROWCHANGEKINDENUM}
#Import export ".\DBROWSTATUSENUM.ahk" {DBROWSTATUSENUM}
#Import export ".\DBROWSTATUSENUM20.ahk" {DBROWSTATUSENUM20}
#Import export ".\DBROWWATCHCHANGE.ahk" {DBROWWATCHCHANGE}
#Import export ".\DBSEEKENUM.ahk" {DBSEEKENUM}
#Import export ".\DBSORTENUM.ahk" {DBSORTENUM}
#Import export ".\DBSOURCETYPEENUM.ahk" {DBSOURCETYPEENUM}
#Import export ".\DBSOURCETYPEENUM20.ahk" {DBSOURCETYPEENUM20}
#Import export ".\DBSOURCETYPEENUM25.ahk" {DBSOURCETYPEENUM25}
#Import export ".\DBSTATUSENUM.ahk" {DBSTATUSENUM}
#Import export ".\DBSTATUSENUM20.ahk" {DBSTATUSENUM20}
#Import export ".\DBSTATUSENUM21.ahk" {DBSTATUSENUM21}
#Import export ".\DBSTATUSENUM25.ahk" {DBSTATUSENUM25}
#Import export ".\DBSTATUSENUM26.ahk" {DBSTATUSENUM26}
#Import export ".\DBTABLESTATISTICSTYPE26.ahk" {DBTABLESTATISTICSTYPE26}
#Import export ".\DBTIME.ahk" {DBTIME}
#Import export ".\DBTIMESTAMP.ahk" {DBTIMESTAMP}
#Import export ".\DBTYPEENUM.ahk" {DBTYPEENUM}
#Import export ".\DBTYPEENUM15.ahk" {DBTYPEENUM15}
#Import export ".\DBTYPEENUM20.ahk" {DBTYPEENUM20}
#Import export ".\DBUPDELRULEENUM.ahk" {DBUPDELRULEENUM}
#Import export ".\DBVARYBIN.ahk" {DBVARYBIN}
#Import export ".\DBVARYCHAR.ahk" {DBVARYCHAR}
#Import export ".\DBVECTOR.ahk" {DBVECTOR}
#Import export ".\DBWATCHMODEENUM.ahk" {DBWATCHMODEENUM}
#Import export ".\DBWATCHNOTIFYENUM.ahk" {DBWATCHNOTIFYENUM}
#Import export ".\DB_NUMERIC.ahk" {DB_NUMERIC}
#Import export ".\DB_VARNUMERIC.ahk" {DB_VARNUMERIC}
#Import export ".\DCINFO.ahk" {DCINFO}
#Import export ".\DCINFOTYPEENUM.ahk" {DCINFOTYPEENUM}
#Import export ".\DELIVERY_AGENT_FLAGS.ahk" {DELIVERY_AGENT_FLAGS}
#Import export ".\DataLinks.ahk" {DataLinks}
#Import export ".\DataSource.ahk" {DataSource}
#Import export ".\DataSourceListener.ahk" {DataSourceListener}
#Import export ".\DataSourceObject.ahk" {DataSourceObject}
#Import export ".\EBindInfoOptions.ahk" {EBindInfoOptions}
#Import export ".\ERRORINFO.ahk" {ERRORINFO}
#Import export ".\FILTERED_DATA_SOURCES.ahk" {FILTERED_DATA_SOURCES}
#Import export ".\FOLLOW_FLAGS.ahk" {FOLLOW_FLAGS}
#Import export ".\FilterRegistration.ahk" {FilterRegistration}
#Import export ".\HACCESSOR.ahk" {HACCESSOR}
#Import export ".\HITRANGE.ahk" {HITRANGE}
#Import export ".\IAccessor.ahk" {IAccessor}
#Import export ".\IAlterIndex.ahk" {IAlterIndex}
#Import export ".\IAlterTable.ahk" {IAlterTable}
#Import export ".\IBindResource.ahk" {IBindResource}
#Import export ".\IChapteredRowset.ahk" {IChapteredRowset}
#Import export ".\IColumnMapper.ahk" {IColumnMapper}
#Import export ".\IColumnMapperCreator.ahk" {IColumnMapperCreator}
#Import export ".\IColumnsInfo.ahk" {IColumnsInfo}
#Import export ".\IColumnsInfo2.ahk" {IColumnsInfo2}
#Import export ".\IColumnsRowset.ahk" {IColumnsRowset}
#Import export ".\ICommand.ahk" {ICommand}
#Import export ".\ICommandCost.ahk" {ICommandCost}
#Import export ".\ICommandPersist.ahk" {ICommandPersist}
#Import export ".\ICommandPrepare.ahk" {ICommandPrepare}
#Import export ".\ICommandProperties.ahk" {ICommandProperties}
#Import export ".\ICommandStream.ahk" {ICommandStream}
#Import export ".\ICommandText.ahk" {ICommandText}
#Import export ".\ICommandValidate.ahk" {ICommandValidate}
#Import export ".\ICommandWithParameters.ahk" {ICommandWithParameters}
#Import export ".\ICondition.ahk" {ICondition}
#Import export ".\ICondition2.ahk" {ICondition2}
#Import export ".\IConditionFactory.ahk" {IConditionFactory}
#Import export ".\IConditionFactory2.ahk" {IConditionFactory2}
#Import export ".\IConditionGenerator.ahk" {IConditionGenerator}
#Import export ".\IConvertType.ahk" {IConvertType}
#Import export ".\ICreateRow.ahk" {ICreateRow}
#Import export ".\IDBAsynchNotify.ahk" {IDBAsynchNotify}
#Import export ".\IDBAsynchStatus.ahk" {IDBAsynchStatus}
#Import export ".\IDBBinderProperties.ahk" {IDBBinderProperties}
#Import export ".\IDBCreateCommand.ahk" {IDBCreateCommand}
#Import export ".\IDBCreateSession.ahk" {IDBCreateSession}
#Import export ".\IDBDataSourceAdmin.ahk" {IDBDataSourceAdmin}
#Import export ".\IDBInfo.ahk" {IDBInfo}
#Import export ".\IDBInitialize.ahk" {IDBInitialize}
#Import export ".\IDBPromptInitialize.ahk" {IDBPromptInitialize}
#Import export ".\IDBProperties.ahk" {IDBProperties}
#Import export ".\IDBSchemaCommand.ahk" {IDBSchemaCommand}
#Import export ".\IDBSchemaRowset.ahk" {IDBSchemaRowset}
#Import export ".\IDCInfo.ahk" {IDCInfo}
#Import export ".\IDataConvert.ahk" {IDataConvert}
#Import export ".\IDataInitialize.ahk" {IDataInitialize}
#Import export ".\IDataSourceLocator.ahk" {IDataSourceLocator}
#Import export ".\IEntity.ahk" {IEntity}
#Import export ".\IEnumItemProperties.ahk" {IEnumItemProperties}
#Import export ".\IEnumSearchRoots.ahk" {IEnumSearchRoots}
#Import export ".\IEnumSearchScopeRules.ahk" {IEnumSearchScopeRules}
#Import export ".\IEnumSubscription.ahk" {IEnumSubscription}
#Import export ".\IErrorLookup.ahk" {IErrorLookup}
#Import export ".\IErrorRecords.ahk" {IErrorRecords}
#Import export ".\IGetDataSource.ahk" {IGetDataSource}
#Import export ".\IGetRow.ahk" {IGetRow}
#Import export ".\IGetSession.ahk" {IGetSession}
#Import export ".\IGetSourceRow.ahk" {IGetSourceRow}
#Import export ".\IIndexDefinition.ahk" {IIndexDefinition}
#Import export ".\IInterval.ahk" {IInterval}
#Import export ".\ILoadFilter.ahk" {ILoadFilter}
#Import export ".\ILoadFilterWithPrivateComActivation.ahk" {ILoadFilterWithPrivateComActivation}
#Import export ".\IMDDataset.ahk" {IMDDataset}
#Import export ".\IMDFind.ahk" {IMDFind}
#Import export ".\IMDRangeRowset.ahk" {IMDRangeRowset}
#Import export ".\IMetaData.ahk" {IMetaData}
#Import export ".\IMultipleResults.ahk" {IMultipleResults}
#Import export ".\INCREMENTAL_ACCESS_INFO.ahk" {INCREMENTAL_ACCESS_INFO}
#Import export ".\INTERVAL_LIMIT_KIND.ahk" {INTERVAL_LIMIT_KIND}
#Import export ".\INamedEntity.ahk" {INamedEntity}
#Import export ".\INamedEntityCollector.ahk" {INamedEntityCollector}
#Import export ".\IObjectAccessControl.ahk" {IObjectAccessControl}
#Import export ".\IOpLockStatus.ahk" {IOpLockStatus}
#Import export ".\IOpenRowset.ahk" {IOpenRowset}
#Import export ".\IParentRowset.ahk" {IParentRowset}
#Import export ".\IProtocolHandlerSite.ahk" {IProtocolHandlerSite}
#Import export ".\IProvideMoniker.ahk" {IProvideMoniker}
#Import export ".\IQueryParser.ahk" {IQueryParser}
#Import export ".\IQueryParserManager.ahk" {IQueryParserManager}
#Import export ".\IQuerySolution.ahk" {IQuerySolution}
#Import export ".\IReadData.ahk" {IReadData}
#Import export ".\IRegisterProvider.ahk" {IRegisterProvider}
#Import export ".\IRelationship.ahk" {IRelationship}
#Import export ".\IRichChunk.ahk" {IRichChunk}
#Import export ".\IRow.ahk" {IRow}
#Import export ".\IRowChange.ahk" {IRowChange}
#Import export ".\IRowPosition.ahk" {IRowPosition}
#Import export ".\IRowPositionChange.ahk" {IRowPositionChange}
#Import export ".\IRowSchemaChange.ahk" {IRowSchemaChange}
#Import export ".\IRowset.ahk" {IRowset}
#Import export ".\IRowsetAsynch.ahk" {IRowsetAsynch}
#Import export ".\IRowsetBookmark.ahk" {IRowsetBookmark}
#Import export ".\IRowsetChange.ahk" {IRowsetChange}
#Import export ".\IRowsetChangeExtInfo.ahk" {IRowsetChangeExtInfo}
#Import export ".\IRowsetChapterMember.ahk" {IRowsetChapterMember}
#Import export ".\IRowsetCopyRows.ahk" {IRowsetCopyRows}
#Import export ".\IRowsetCurrentIndex.ahk" {IRowsetCurrentIndex}
#Import export ".\IRowsetEvents.ahk" {IRowsetEvents}
#Import export ".\IRowsetExactScroll.ahk" {IRowsetExactScroll}
#Import export ".\IRowsetFastLoad.ahk" {IRowsetFastLoad}
#Import export ".\IRowsetFind.ahk" {IRowsetFind}
#Import export ".\IRowsetIdentity.ahk" {IRowsetIdentity}
#Import export ".\IRowsetIndex.ahk" {IRowsetIndex}
#Import export ".\IRowsetInfo.ahk" {IRowsetInfo}
#Import export ".\IRowsetKeys.ahk" {IRowsetKeys}
#Import export ".\IRowsetLocate.ahk" {IRowsetLocate}
#Import export ".\IRowsetNewRowAfter.ahk" {IRowsetNewRowAfter}
#Import export ".\IRowsetNextRowset.ahk" {IRowsetNextRowset}
#Import export ".\IRowsetNotify.ahk" {IRowsetNotify}
#Import export ".\IRowsetPrioritization.ahk" {IRowsetPrioritization}
#Import export ".\IRowsetQueryStatus.ahk" {IRowsetQueryStatus}
#Import export ".\IRowsetRefresh.ahk" {IRowsetRefresh}
#Import export ".\IRowsetResynch.ahk" {IRowsetResynch}
#Import export ".\IRowsetScroll.ahk" {IRowsetScroll}
#Import export ".\IRowsetUpdate.ahk" {IRowsetUpdate}
#Import export ".\IRowsetView.ahk" {IRowsetView}
#Import export ".\IRowsetWatchAll.ahk" {IRowsetWatchAll}
#Import export ".\IRowsetWatchNotify.ahk" {IRowsetWatchNotify}
#Import export ".\IRowsetWatchRegion.ahk" {IRowsetWatchRegion}
#Import export ".\IRowsetWithParameters.ahk" {IRowsetWithParameters}
#Import export ".\ISQLErrorInfo.ahk" {ISQLErrorInfo}
#Import export ".\ISQLGetDiagField.ahk" {ISQLGetDiagField}
#Import export ".\ISQLRequestDiagFields.ahk" {ISQLRequestDiagFields}
#Import export ".\ISQLServerErrorInfo.ahk" {ISQLServerErrorInfo}
#Import export ".\ISchemaLocalizerSupport.ahk" {ISchemaLocalizerSupport}
#Import export ".\ISchemaLock.ahk" {ISchemaLock}
#Import export ".\ISchemaProvider.ahk" {ISchemaProvider}
#Import export ".\IScopedOperations.ahk" {IScopedOperations}
#Import export ".\ISearchCatalogManager.ahk" {ISearchCatalogManager}
#Import export ".\ISearchCatalogManager2.ahk" {ISearchCatalogManager2}
#Import export ".\ISearchCatalogManager3.ahk" {ISearchCatalogManager3}
#Import export ".\ISearchCrawlScopeManager.ahk" {ISearchCrawlScopeManager}
#Import export ".\ISearchCrawlScopeManager2.ahk" {ISearchCrawlScopeManager2}
#Import export ".\ISearchItemsChangedSink.ahk" {ISearchItemsChangedSink}
#Import export ".\ISearchLanguageSupport.ahk" {ISearchLanguageSupport}
#Import export ".\ISearchManager.ahk" {ISearchManager}
#Import export ".\ISearchManager2.ahk" {ISearchManager2}
#Import export ".\ISearchNotifyInlineSite.ahk" {ISearchNotifyInlineSite}
#Import export ".\ISearchPersistentItemsChangedSink.ahk" {ISearchPersistentItemsChangedSink}
#Import export ".\ISearchProtocol.ahk" {ISearchProtocol}
#Import export ".\ISearchProtocol2.ahk" {ISearchProtocol2}
#Import export ".\ISearchProtocolThreadContext.ahk" {ISearchProtocolThreadContext}
#Import export ".\ISearchQueryHelper.ahk" {ISearchQueryHelper}
#Import export ".\ISearchQueryHits.ahk" {ISearchQueryHits}
#Import export ".\ISearchRoot.ahk" {ISearchRoot}
#Import export ".\ISearchScopeRule.ahk" {ISearchScopeRule}
#Import export ".\ISearchViewChangedSink.ahk" {ISearchViewChangedSink}
#Import export ".\ISecurityInfo.ahk" {ISecurityInfo}
#Import export ".\IService.ahk" {IService}
#Import export ".\ISessionProperties.ahk" {ISessionProperties}
#Import export ".\ISimpleCommandCreator.ahk" {ISimpleCommandCreator}
#Import export ".\ISourcesRowset.ahk" {ISourcesRowset}
#Import export ".\IStemmer.ahk" {IStemmer}
#Import export ".\ISubscriptionItem.ahk" {ISubscriptionItem}
#Import export ".\ISubscriptionMgr.ahk" {ISubscriptionMgr}
#Import export ".\ISubscriptionMgr2.ahk" {ISubscriptionMgr2}
#Import export ".\ITEMPROP.ahk" {ITEMPROP}
#Import export ".\ITEM_INFO.ahk" {ITEM_INFO}
#Import export ".\ITableCreation.ahk" {ITableCreation}
#Import export ".\ITableDefinition.ahk" {ITableDefinition}
#Import export ".\ITableDefinitionWithConstraints.ahk" {ITableDefinitionWithConstraints}
#Import export ".\ITableRename.ahk" {ITableRename}
#Import export ".\ITokenCollection.ahk" {ITokenCollection}
#Import export ".\ITransactionJoin.ahk" {ITransactionJoin}
#Import export ".\ITransactionLocal.ahk" {ITransactionLocal}
#Import export ".\ITransactionObject.ahk" {ITransactionObject}
#Import export ".\ITrusteeAdmin.ahk" {ITrusteeAdmin}
#Import export ".\ITrusteeGroupAdmin.ahk" {ITrusteeGroupAdmin}
#Import export ".\IUMS.ahk" {IUMS}
#Import export ".\IUMSInitialize.ahk" {IUMSInitialize}
#Import export ".\IUrlAccessor.ahk" {IUrlAccessor}
#Import export ".\IUrlAccessor2.ahk" {IUrlAccessor2}
#Import export ".\IUrlAccessor3.ahk" {IUrlAccessor3}
#Import export ".\IUrlAccessor4.ahk" {IUrlAccessor4}
#Import export ".\IViewChapter.ahk" {IViewChapter}
#Import export ".\IViewFilter.ahk" {IViewFilter}
#Import export ".\IViewRowset.ahk" {IViewRowset}
#Import export ".\IViewSort.ahk" {IViewSort}
#Import export ".\IWordBreaker.ahk" {IWordBreaker}
#Import export ".\IWordFormSink.ahk" {IWordFormSink}
#Import export ".\IWordSink.ahk" {IWordSink}
#Import export ".\Interval.ahk" {Interval}
#Import export ".\KAGGETDIAG.ahk" {KAGGETDIAG}
#Import export ".\KAGREQDIAG.ahk" {KAGREQDIAG}
#Import export ".\KAGREQDIAGFLAGSENUM.ahk" {KAGREQDIAGFLAGSENUM}
#Import export ".\LOCKMODEENUM.ahk" {LOCKMODEENUM}
#Import export ".\LeafCondition.ahk" {LeafCondition}
#Import export ".\MDAXISINFO.ahk" {MDAXISINFO}
#Import export ".\MSDAINITIALIZE.ahk" {MSDAINITIALIZE}
#Import export ".\MSDAORA.ahk" {MSDAORA}
#Import export ".\MSDAORA8.ahk" {MSDAORA8}
#Import export ".\MSDAORA8_ERROR.ahk" {MSDAORA8_ERROR}
#Import export ".\MSDAORA_ERROR.ahk" {MSDAORA_ERROR}
#Import export ".\MSDSDBINITPROPENUM.ahk" {MSDSDBINITPROPENUM}
#Import export ".\MSDSSESSIONPROPENUM.ahk" {MSDSSESSIONPROPENUM}
#Import export ".\NAMED_ENTITY_CERTAINTY.ahk" {NAMED_ENTITY_CERTAINTY}
#Import export ".\NATLANGUAGERESTRICTION.ahk" {NATLANGUAGERESTRICTION}
#Import export ".\NODERESTRICTION.ahk" {NODERESTRICTION}
#Import export ".\NOTRESTRICTION.ahk" {NOTRESTRICTION}
#Import export ".\NegationCondition.ahk" {NegationCondition}
#Import export ".\ODBC_VS_ARGS.ahk" {ODBC_VS_ARGS}
#Import export ".\OLEDBSimpleProvider.ahk" {OLEDBSimpleProvider}
#Import export ".\OLEDBSimpleProviderListener.ahk" {OLEDBSimpleProviderListener}
#Import export ".\OSPCOMP.ahk" {OSPCOMP}
#Import export ".\OSPFIND.ahk" {OSPFIND}
#Import export ".\OSPFORMAT.ahk" {OSPFORMAT}
#Import export ".\OSPRW.ahk" {OSPRW}
#Import export ".\OSPXFER.ahk" {OSPXFER}
#Import export ".\PDPO.ahk" {PDPO}
#Import export ".\PFNFILLTEXTBUFFER.ahk" {PFNFILLTEXTBUFFER}
#Import export ".\PRIORITIZE_FLAGS.ahk" {PRIORITIZE_FLAGS}
#Import export ".\PRIORITY_LEVEL.ahk" {PRIORITY_LEVEL}
#Import export ".\PROPERTYRESTRICTION.ahk" {PROPERTYRESTRICTION}
#Import export ".\PROXY_ACCESS.ahk" {PROXY_ACCESS}
#Import export ".\PROXY_INFO.ahk" {PROXY_INFO}
#Import export ".\QUERY_PARSER_MANAGER_OPTION.ahk" {QUERY_PARSER_MANAGER_OPTION}
#Import export ".\QueryParser.ahk" {QueryParser}
#Import export ".\QueryParserManager.ahk" {QueryParserManager}
#Import export ".\RANGECATEGORIZE.ahk" {RANGECATEGORIZE}
#Import export ".\RESTRICTION.ahk" {RESTRICTION}
#Import export ".\RMTPACK.ahk" {RMTPACK}
#Import export ".\ROWSETEVENT_ITEMSTATE.ahk" {ROWSETEVENT_ITEMSTATE}
#Import export ".\ROWSETEVENT_TYPE.ahk" {ROWSETEVENT_TYPE}
#Import export ".\RootBinder.ahk" {RootBinder}
#Import export ".\SEARCH_COLUMN_PROPERTIES.ahk" {SEARCH_COLUMN_PROPERTIES}
#Import export ".\SEARCH_INDEXING_PHASE.ahk" {SEARCH_INDEXING_PHASE}
#Import export ".\SEARCH_ITEM_CHANGE.ahk" {SEARCH_ITEM_CHANGE}
#Import export ".\SEARCH_ITEM_INDEXING_STATUS.ahk" {SEARCH_ITEM_INDEXING_STATUS}
#Import export ".\SEARCH_ITEM_PERSISTENT_CHANGE.ahk" {SEARCH_ITEM_PERSISTENT_CHANGE}
#Import export ".\SEARCH_KIND_OF_CHANGE.ahk" {SEARCH_KIND_OF_CHANGE}
#Import export ".\SEARCH_NOTIFICATION_PRIORITY.ahk" {SEARCH_NOTIFICATION_PRIORITY}
#Import export ".\SEARCH_QUERY_SYNTAX.ahk" {SEARCH_QUERY_SYNTAX}
#Import export ".\SEARCH_TERM_EXPANSION.ahk" {SEARCH_TERM_EXPANSION}
#Import export ".\SEC_OBJECT.ahk" {SEC_OBJECT}
#Import export ".\SEC_OBJECT_ELEMENT.ahk" {SEC_OBJECT_ELEMENT}
#Import export ".\SORTKEY.ahk" {SORTKEY}
#Import export ".\SORTSET.ahk" {SORTSET}
#Import export ".\SQLINTERVAL.ahk" {SQLINTERVAL}
#Import export ".\SQLPERF.ahk" {SQLPERF}
#Import export ".\SQLVARENUM.ahk" {SQLVARENUM}
#Import export ".\SQL_ASYNC_NOTIFICATION_CALLBACK.ahk" {SQL_ASYNC_NOTIFICATION_CALLBACK}
#Import export ".\SQL_DAY_SECOND_STRUCT.ahk" {SQL_DAY_SECOND_STRUCT}
#Import export ".\SQL_INTERVAL_STRUCT.ahk" {SQL_INTERVAL_STRUCT}
#Import export ".\SQL_NUMERIC_STRUCT.ahk" {SQL_NUMERIC_STRUCT}
#Import export ".\SQL_YEAR_MONTH_STRUCT.ahk" {SQL_YEAR_MONTH_STRUCT}
#Import export ".\SSERRORINFO.ahk" {SSERRORINFO}
#Import export ".\SSVARIANT.ahk" {SSVARIANT}
#Import export ".\STRUCTURED_QUERY_MULTIOPTION.ahk" {STRUCTURED_QUERY_MULTIOPTION}
#Import export ".\STRUCTURED_QUERY_PARSE_ERROR.ahk" {STRUCTURED_QUERY_PARSE_ERROR}
#Import export ".\STRUCTURED_QUERY_RESOLVE_OPTION.ahk" {STRUCTURED_QUERY_RESOLVE_OPTION}
#Import export ".\STRUCTURED_QUERY_SINGLE_OPTION.ahk" {STRUCTURED_QUERY_SINGLE_OPTION}
#Import export ".\STRUCTURED_QUERY_SYNTAX.ahk" {STRUCTURED_QUERY_SYNTAX}
#Import export ".\SUBSCRIPTIONINFO.ahk" {SUBSCRIPTIONINFO}
#Import export ".\SUBSCRIPTIONINFOFLAGS.ahk" {SUBSCRIPTIONINFOFLAGS}
#Import export ".\SUBSCRIPTIONITEMINFO.ahk" {SUBSCRIPTIONITEMINFO}
#Import export ".\SUBSCRIPTIONSCHEDULE.ahk" {SUBSCRIPTIONSCHEDULE}
#Import export ".\SUBSCRIPTIONTYPE.ahk" {SUBSCRIPTIONTYPE}
#Import export ".\SubscriptionMgr.ahk" {SubscriptionMgr}
#Import export ".\TEXT_SOURCE.ahk" {TEXT_SOURCE}
#Import export ".\TIMEOUT_INFO.ahk" {TIMEOUT_INFO}
#Import export ".\TIMESTAMP_STRUCT.ahk" {TIMESTAMP_STRUCT}
#Import export ".\TIME_STRUCT.ahk" {TIME_STRUCT}
#Import export ".\VECTORRESTRICTION.ahk" {VECTORRESTRICTION}
#Import export ".\WEBCRAWL_RECURSEFLAGS.ahk" {WEBCRAWL_RECURSEFLAGS}
