#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\Com\IUnknown.ahk

/**
 * Provides methods for creating a language-specific stemmer. The stemmer generates inflected forms of a specified word.
 * @remarks
 * 
 * <h3><a id="When_to_Implement"></a><a id="when_to_implement"></a><a id="WHEN_TO_IMPLEMENT"></a>When to Implement</h3>
 * Implement this interface to create a custom stemmer for a language. Windows Search calls the methods of this interface to generate inflected forms for words identified when building an index.
 * 
 * Stemmer components for Windows Search run in the Local Security context. They should be written to manage buffers and the stack correctly. All string copies must have explicit checks to guard against buffer overruns. You should always verify the allocated size of the buffer and test the size of the data against the size of the buffer.
 * 
 * @see https://docs.microsoft.com/windows/win32/api//indexsrv/nn-indexsrv-istemmer
 * @namespace Windows.Win32.System.Search
 * @version v4.0.30319
 */
class IStemmer extends IUnknown{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IStemmer
     * @type {Guid}
     */
    static IID => Guid("{efbaf140-7f42-11ce-be57-00aa0051fe20}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 3

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["Init", "GenerateWordForms", "GetLicenseToUse"]

    /**
     * Initializes the stemmer.
     * @param {Integer} ulMaxTokenSize Type: <b>ULONG</b>
     * 
     * Maximum number of characters for words that are added to the <a href="https://docs.microsoft.com/windows/desktop/api/indexsrv/nn-indexsrv-iwordformsink">IWordFormSink</a> object. Words that exceed this limit may be truncated.
     * @param {Pointer<BOOL>} pfLicense Type: <b>BOOL</b>
     * 
     * Pointer to an output variable that receives a flag that indicates whether there are license restrictions for this <a href="https://docs.microsoft.com/windows/desktop/api/indexsrv/nn-indexsrv-istemmer">IStemmer</a> implementation. <b>TRUE</b> indicates that the stemmer is restricted to authorized use only. <b>FALSE</b> indicates that this <b>IStemmer</b> implementation can be used freely.
     * @returns {HRESULT} Type: <b>HRESULT</b>
     * 
     * This method can return one of these values.
     * 
     * <table>
     * <tr>
     * <th>Return code</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>S_OK</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * Successful completion.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>LANGUAGE_E_DATABASE_NOT_FOUND</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * One of the components for word breaking cannot be located.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_INVALIDARG</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * Invalid argument. The <i>pfLicense</i> parameter is <b>NULL</b>. 
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_FAIL</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * Unsuccessful completion.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://docs.microsoft.com/windows/win32/api//indexsrv/nf-indexsrv-istemmer-init
     */
    Init(ulMaxTokenSize, pfLicense) {
        pfLicenseMarshal := pfLicense is VarRef ? "int*" : "ptr"

        result := ComCall(3, this, "uint", ulMaxTokenSize, pfLicenseMarshal, pfLicense, "HRESULT")
        return result
    }

    /**
     * Generates alternative forms for a word and puts these forms in the IWordFormSink object.
     * @param {PWSTR} pwcInBuf Type: <b>const WCHAR*</b>
     * 
     * Pointer to a buffer that contains the word to stem. The characters in <i>pwcInBuf</i> are represented in Unicode.
     * @param {Integer} cwc Type: <b>ULONG</b>
     * 
     * Number of characters in <i>pwcInBuf</i>.
     * @param {IWordFormSink} pStemSink Type: <b>IWordFormSink*</b>
     * 
     * Pointer to an <a href="https://docs.microsoft.com/windows/desktop/api/indexsrv/nn-indexsrv-iwordformsink">IWordFormSink</a> object that receives and handles the alternative word forms generated by this method.
     * @returns {HRESULT} Type: <b>HRESULT</b>
     * 
     * This method can return one of these values.
     * 
     * <table>
     * <tr>
     * <th>Return code</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>S_OK</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * Successful completion.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_INVALIDARG</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * Invalid argument. Either <i>pwcInBuf</i> or <i>pWordFormSink</i> is <b>NULL</b>.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://docs.microsoft.com/windows/win32/api//indexsrv/nf-indexsrv-istemmer-generatewordforms
     */
    GenerateWordForms(pwcInBuf, cwc, pStemSink) {
        pwcInBuf := pwcInBuf is String ? StrPtr(pwcInBuf) : pwcInBuf

        result := ComCall(4, this, "ptr", pwcInBuf, "uint", cwc, "ptr", pStemSink, "HRESULT")
        return result
    }

    /**
     * Gets the license information for this IStemmer implementation.
     * @param {Pointer<Pointer<Integer>>} ppwcsLicense Type: <b>const WCHAR**</b>
     * 
     * Pointer to a variable that receives a pointer to the license information for this <a href="https://docs.microsoft.com/windows/desktop/api/indexsrv/nn-indexsrv-istemmer">IStemmer</a> implementation.
     * @returns {HRESULT} Type: <b>HRESULT</b>
     * 
     * If this method succeeds, it returns <b xmlns:loc="http://microsoft.com/wdcml/l10n">S_OK</b>. Otherwise, it returns an <b xmlns:loc="http://microsoft.com/wdcml/l10n">HRESULT</b> error code.
     * @see https://docs.microsoft.com/windows/win32/api//indexsrv/nf-indexsrv-istemmer-getlicensetouse
     */
    GetLicenseToUse(ppwcsLicense) {
        ppwcsLicenseMarshal := ppwcsLicense is VarRef ? "ptr*" : "ptr"

        result := ComCall(5, this, ppwcsLicenseMarshal, ppwcsLicense, "HRESULT")
        return result
    }
}
