#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ABC.ahk" {ABC}
#Import export ".\ABCFLOAT.ahk" {ABCFLOAT}
#Import export ".\ABORTPATH.ahk" {ABORTPATH}
#Import export ".\ARC_DIRECTION.ahk" {ARC_DIRECTION}
#Import export ".\AXESLISTA.ahk" {AXESLISTA}
#Import export ".\AXESLISTW.ahk" {AXESLISTW}
#Import export ".\AXISINFOA.ahk" {AXISINFOA}
#Import export ".\AXISINFOW.ahk" {AXISINFOW}
#Import export ".\Apis.ahk" {*}
#Import export ".\BACKGROUND_MODE.ahk" {BACKGROUND_MODE}
#Import export ".\BITMAP.ahk" {BITMAP}
#Import export ".\BITMAPCOREHEADER.ahk" {BITMAPCOREHEADER}
#Import export ".\BITMAPCOREINFO.ahk" {BITMAPCOREINFO}
#Import export ".\BITMAPFILEHEADER.ahk" {BITMAPFILEHEADER}
#Import export ".\BITMAPINFO.ahk" {BITMAPINFO}
#Import export ".\BITMAPINFOHEADER.ahk" {BITMAPINFOHEADER}
#Import export ".\BITMAPV4HEADER.ahk" {BITMAPV4HEADER}
#Import export ".\BITMAPV5HEADER.ahk" {BITMAPV5HEADER}
#Import export ".\BI_COMPRESSION.ahk" {BI_COMPRESSION}
#Import export ".\BLENDFUNCTION.ahk" {BLENDFUNCTION}
#Import export ".\BRUSH_STYLE.ahk" {BRUSH_STYLE}
#Import export ".\CDS_TYPE.ahk" {CDS_TYPE}
#Import export ".\CFP_ALLOCPROC.ahk" {CFP_ALLOCPROC}
#Import export ".\CFP_FREEPROC.ahk" {CFP_FREEPROC}
#Import export ".\CFP_REALLOCPROC.ahk" {CFP_REALLOCPROC}
#Import export ".\CIEXYZ.ahk" {CIEXYZ}
#Import export ".\CIEXYZTRIPLE.ahk" {CIEXYZTRIPLE}
#Import export ".\COLORADJUSTMENT.ahk" {COLORADJUSTMENT}
#Import export ".\CREATE_FONT_PACKAGE_SUBSET_ENCODING.ahk" {CREATE_FONT_PACKAGE_SUBSET_ENCODING}
#Import export ".\CREATE_FONT_PACKAGE_SUBSET_PLATFORM.ahk" {CREATE_FONT_PACKAGE_SUBSET_PLATFORM}
#Import export ".\CREATE_POLYGON_RGN_MODE.ahk" {CREATE_POLYGON_RGN_MODE}
#Import export ".\Constants.ahk" {*}
#Import export ".\DC_LAYOUT.ahk" {DC_LAYOUT}
#Import export ".\DESIGNVECTOR.ahk" {DESIGNVECTOR}
#Import export ".\DEVMODEA.ahk" {DEVMODEA}
#Import export ".\DEVMODEW.ahk" {DEVMODEW}
#Import export ".\DEVMODE_COLLATE.ahk" {DEVMODE_COLLATE}
#Import export ".\DEVMODE_COLOR.ahk" {DEVMODE_COLOR}
#Import export ".\DEVMODE_DISPLAY_FIXED_OUTPUT.ahk" {DEVMODE_DISPLAY_FIXED_OUTPUT}
#Import export ".\DEVMODE_DISPLAY_ORIENTATION.ahk" {DEVMODE_DISPLAY_ORIENTATION}
#Import export ".\DEVMODE_DUPLEX.ahk" {DEVMODE_DUPLEX}
#Import export ".\DEVMODE_FIELD_FLAGS.ahk" {DEVMODE_FIELD_FLAGS}
#Import export ".\DEVMODE_TRUETYPE_OPTION.ahk" {DEVMODE_TRUETYPE_OPTION}
#Import export ".\DFCS_STATE.ahk" {DFCS_STATE}
#Import export ".\DFC_TYPE.ahk" {DFC_TYPE}
#Import export ".\DIBSECTION.ahk" {DIBSECTION}
#Import export ".\DIB_USAGE.ahk" {DIB_USAGE}
#Import export ".\DISPLAYCONFIG_ADVANCED_COLOR_MODE.ahk" {DISPLAYCONFIG_ADVANCED_COLOR_MODE}
#Import export ".\DISPLAYCONFIG_COLOR_ENCODING.ahk" {DISPLAYCONFIG_COLOR_ENCODING}
#Import export ".\DISPLAY_DEVICEA.ahk" {DISPLAY_DEVICEA}
#Import export ".\DISPLAY_DEVICEW.ahk" {DISPLAY_DEVICEW}
#Import export ".\DISPLAY_DEVICE_STATE_FLAGS.ahk" {DISPLAY_DEVICE_STATE_FLAGS}
#Import export ".\DISP_CHANGE.ahk" {DISP_CHANGE}
#Import export ".\DRAWEDGE_FLAGS.ahk" {DRAWEDGE_FLAGS}
#Import export ".\DRAWSTATEPROC.ahk" {DRAWSTATEPROC}
#Import export ".\DRAWSTATE_FLAGS.ahk" {DRAWSTATE_FLAGS}
#Import export ".\DRAWTEXTPARAMS.ahk" {DRAWTEXTPARAMS}
#Import export ".\DRAW_CAPTION_FLAGS.ahk" {DRAW_CAPTION_FLAGS}
#Import export ".\DRAW_EDGE_FLAGS.ahk" {DRAW_EDGE_FLAGS}
#Import export ".\DRAW_TEXT_FORMAT.ahk" {DRAW_TEXT_FORMAT}
#Import export ".\EMBEDDED_FONT_PRIV_STATUS.ahk" {EMBEDDED_FONT_PRIV_STATUS}
#Import export ".\EMBED_FONT_CHARSET.ahk" {EMBED_FONT_CHARSET}
#Import export ".\EMR.ahk" {EMR}
#Import export ".\EMRALPHABLEND.ahk" {EMRALPHABLEND}
#Import export ".\EMRANGLEARC.ahk" {EMRANGLEARC}
#Import export ".\EMRARC.ahk" {EMRARC}
#Import export ".\EMRBITBLT.ahk" {EMRBITBLT}
#Import export ".\EMRCOLORCORRECTPALETTE.ahk" {EMRCOLORCORRECTPALETTE}
#Import export ".\EMRCOLORMATCHTOTARGET.ahk" {EMRCOLORMATCHTOTARGET}
#Import export ".\EMRCREATEBRUSHINDIRECT.ahk" {EMRCREATEBRUSHINDIRECT}
#Import export ".\EMRCREATEDIBPATTERNBRUSHPT.ahk" {EMRCREATEDIBPATTERNBRUSHPT}
#Import export ".\EMRCREATEMONOBRUSH.ahk" {EMRCREATEMONOBRUSH}
#Import export ".\EMRCREATEPALETTE.ahk" {EMRCREATEPALETTE}
#Import export ".\EMRCREATEPEN.ahk" {EMRCREATEPEN}
#Import export ".\EMRELLIPSE.ahk" {EMRELLIPSE}
#Import export ".\EMREOF.ahk" {EMREOF}
#Import export ".\EMREXCLUDECLIPRECT.ahk" {EMREXCLUDECLIPRECT}
#Import export ".\EMREXTCREATEFONTINDIRECTW.ahk" {EMREXTCREATEFONTINDIRECTW}
#Import export ".\EMREXTCREATEPEN.ahk" {EMREXTCREATEPEN}
#Import export ".\EMREXTESCAPE.ahk" {EMREXTESCAPE}
#Import export ".\EMREXTFLOODFILL.ahk" {EMREXTFLOODFILL}
#Import export ".\EMREXTSELECTCLIPRGN.ahk" {EMREXTSELECTCLIPRGN}
#Import export ".\EMREXTTEXTOUTA.ahk" {EMREXTTEXTOUTA}
#Import export ".\EMRFILLPATH.ahk" {EMRFILLPATH}
#Import export ".\EMRFILLRGN.ahk" {EMRFILLRGN}
#Import export ".\EMRFORMAT.ahk" {EMRFORMAT}
#Import export ".\EMRFRAMERGN.ahk" {EMRFRAMERGN}
#Import export ".\EMRGDICOMMENT.ahk" {EMRGDICOMMENT}
#Import export ".\EMRGLSBOUNDEDRECORD.ahk" {EMRGLSBOUNDEDRECORD}
#Import export ".\EMRGLSRECORD.ahk" {EMRGLSRECORD}
#Import export ".\EMRGRADIENTFILL.ahk" {EMRGRADIENTFILL}
#Import export ".\EMRINVERTRGN.ahk" {EMRINVERTRGN}
#Import export ".\EMRLINETO.ahk" {EMRLINETO}
#Import export ".\EMRMASKBLT.ahk" {EMRMASKBLT}
#Import export ".\EMRMODIFYWORLDTRANSFORM.ahk" {EMRMODIFYWORLDTRANSFORM}
#Import export ".\EMRNAMEDESCAPE.ahk" {EMRNAMEDESCAPE}
#Import export ".\EMROFFSETCLIPRGN.ahk" {EMROFFSETCLIPRGN}
#Import export ".\EMRPLGBLT.ahk" {EMRPLGBLT}
#Import export ".\EMRPOLYDRAW.ahk" {EMRPOLYDRAW}
#Import export ".\EMRPOLYDRAW16.ahk" {EMRPOLYDRAW16}
#Import export ".\EMRPOLYLINE.ahk" {EMRPOLYLINE}
#Import export ".\EMRPOLYLINE16.ahk" {EMRPOLYLINE16}
#Import export ".\EMRPOLYPOLYLINE.ahk" {EMRPOLYPOLYLINE}
#Import export ".\EMRPOLYPOLYLINE16.ahk" {EMRPOLYPOLYLINE16}
#Import export ".\EMRPOLYTEXTOUTA.ahk" {EMRPOLYTEXTOUTA}
#Import export ".\EMRRESIZEPALETTE.ahk" {EMRRESIZEPALETTE}
#Import export ".\EMRRESTOREDC.ahk" {EMRRESTOREDC}
#Import export ".\EMRROUNDRECT.ahk" {EMRROUNDRECT}
#Import export ".\EMRSCALEVIEWPORTEXTEX.ahk" {EMRSCALEVIEWPORTEXTEX}
#Import export ".\EMRSELECTCLIPPATH.ahk" {EMRSELECTCLIPPATH}
#Import export ".\EMRSELECTOBJECT.ahk" {EMRSELECTOBJECT}
#Import export ".\EMRSELECTPALETTE.ahk" {EMRSELECTPALETTE}
#Import export ".\EMRSETARCDIRECTION.ahk" {EMRSETARCDIRECTION}
#Import export ".\EMRSETCOLORADJUSTMENT.ahk" {EMRSETCOLORADJUSTMENT}
#Import export ".\EMRSETCOLORSPACE.ahk" {EMRSETCOLORSPACE}
#Import export ".\EMRSETDIBITSTODEVICE.ahk" {EMRSETDIBITSTODEVICE}
#Import export ".\EMRSETICMPROFILE.ahk" {EMRSETICMPROFILE}
#Import export ".\EMRSETMAPPERFLAGS.ahk" {EMRSETMAPPERFLAGS}
#Import export ".\EMRSETMITERLIMIT.ahk" {EMRSETMITERLIMIT}
#Import export ".\EMRSETPALETTEENTRIES.ahk" {EMRSETPALETTEENTRIES}
#Import export ".\EMRSETPIXELV.ahk" {EMRSETPIXELV}
#Import export ".\EMRSETTEXTCOLOR.ahk" {EMRSETTEXTCOLOR}
#Import export ".\EMRSETVIEWPORTEXTEX.ahk" {EMRSETVIEWPORTEXTEX}
#Import export ".\EMRSETVIEWPORTORGEX.ahk" {EMRSETVIEWPORTORGEX}
#Import export ".\EMRSETWORLDTRANSFORM.ahk" {EMRSETWORLDTRANSFORM}
#Import export ".\EMRSTRETCHBLT.ahk" {EMRSTRETCHBLT}
#Import export ".\EMRSTRETCHDIBITS.ahk" {EMRSTRETCHDIBITS}
#Import export ".\EMRTEXT.ahk" {EMRTEXT}
#Import export ".\EMRTRANSPARENTBLT.ahk" {EMRTRANSPARENTBLT}
#Import export ".\ENHANCED_METAFILE_RECORD_TYPE.ahk" {ENHANCED_METAFILE_RECORD_TYPE}
#Import export ".\ENHMETAHEADER.ahk" {ENHMETAHEADER}
#Import export ".\ENHMETARECORD.ahk" {ENHMETARECORD}
#Import export ".\ENHMFENUMPROC.ahk" {ENHMFENUMPROC}
#Import export ".\ENUMLOGFONTA.ahk" {ENUMLOGFONTA}
#Import export ".\ENUMLOGFONTEXA.ahk" {ENUMLOGFONTEXA}
#Import export ".\ENUMLOGFONTEXDVA.ahk" {ENUMLOGFONTEXDVA}
#Import export ".\ENUMLOGFONTEXDVW.ahk" {ENUMLOGFONTEXDVW}
#Import export ".\ENUMLOGFONTEXW.ahk" {ENUMLOGFONTEXW}
#Import export ".\ENUMLOGFONTW.ahk" {ENUMLOGFONTW}
#Import export ".\ENUM_DISPLAY_SETTINGS_FLAGS.ahk" {ENUM_DISPLAY_SETTINGS_FLAGS}
#Import export ".\ENUM_DISPLAY_SETTINGS_MODE.ahk" {ENUM_DISPLAY_SETTINGS_MODE}
#Import export ".\ETO_OPTIONS.ahk" {ETO_OPTIONS}
#Import export ".\EXTLOGFONTA.ahk" {EXTLOGFONTA}
#Import export ".\EXTLOGFONTW.ahk" {EXTLOGFONTW}
#Import export ".\EXTLOGPEN.ahk" {EXTLOGPEN}
#Import export ".\EXTLOGPEN32.ahk" {EXTLOGPEN32}
#Import export ".\EXT_FLOOD_FILL_TYPE.ahk" {EXT_FLOOD_FILL_TYPE}
#Import export ".\FIXED.ahk" {FIXED}
#Import export ".\FONTENUMPROCA.ahk" {FONTENUMPROCA}
#Import export ".\FONTENUMPROCW.ahk" {FONTENUMPROCW}
#Import export ".\FONT_CHARSET.ahk" {FONT_CHARSET}
#Import export ".\FONT_CLIP_PRECISION.ahk" {FONT_CLIP_PRECISION}
#Import export ".\FONT_FAMILY.ahk" {FONT_FAMILY}
#Import export ".\FONT_LICENSE_PRIVS.ahk" {FONT_LICENSE_PRIVS}
#Import export ".\FONT_OUTPUT_PRECISION.ahk" {FONT_OUTPUT_PRECISION}
#Import export ".\FONT_PITCH.ahk" {FONT_PITCH}
#Import export ".\FONT_QUALITY.ahk" {FONT_QUALITY}
#Import export ".\FONT_RESOURCE_CHARACTERISTICS.ahk" {FONT_RESOURCE_CHARACTERISTICS}
#Import export ".\FONT_WEIGHT.ahk" {FONT_WEIGHT}
#Import export ".\GCP_RESULTSA.ahk" {GCP_RESULTSA}
#Import export ".\GCP_RESULTSW.ahk" {GCP_RESULTSW}
#Import export ".\GDI_REGION_TYPE.ahk" {GDI_REGION_TYPE}
#Import export ".\GET_CHARACTER_PLACEMENT_FLAGS.ahk" {GET_CHARACTER_PLACEMENT_FLAGS}
#Import export ".\GET_DCX_FLAGS.ahk" {GET_DCX_FLAGS}
#Import export ".\GET_DEVICE_CAPS_INDEX.ahk" {GET_DEVICE_CAPS_INDEX}
#Import export ".\GET_GLYPH_OUTLINE_FORMAT.ahk" {GET_GLYPH_OUTLINE_FORMAT}
#Import export ".\GET_STOCK_OBJECT_FLAGS.ahk" {GET_STOCK_OBJECT_FLAGS}
#Import export ".\GLYPHMETRICS.ahk" {GLYPHMETRICS}
#Import export ".\GLYPHSET.ahk" {GLYPHSET}
#Import export ".\GOBJENUMPROC.ahk" {GOBJENUMPROC}
#Import export ".\GRADIENT_FILL.ahk" {GRADIENT_FILL}
#Import export ".\GRADIENT_RECT.ahk" {GRADIENT_RECT}
#Import export ".\GRADIENT_TRIANGLE.ahk" {GRADIENT_TRIANGLE}
#Import export ".\GRAPHICS_MODE.ahk" {GRAPHICS_MODE}
#Import export ".\GRAYSTRINGPROC.ahk" {GRAYSTRINGPROC}
#Import export ".\HANDLETABLE.ahk" {HANDLETABLE}
#Import export ".\HATCH_BRUSH_STYLE.ahk" {HATCH_BRUSH_STYLE}
#Import export ".\HBITMAP.ahk" {HBITMAP}
#Import export ".\HBRUSH.ahk" {HBRUSH}
#Import export ".\HDC.ahk" {HDC}
#Import export ".\HDC_MAP_MODE.ahk" {HDC_MAP_MODE}
#Import export ".\HENHMETAFILE.ahk" {HENHMETAFILE}
#Import export ".\HFONT.ahk" {HFONT}
#Import export ".\HGDIOBJ.ahk" {HGDIOBJ}
#Import export ".\HMETAFILE.ahk" {HMETAFILE}
#Import export ".\HMONITOR.ahk" {HMONITOR}
#Import export ".\HPALETTE.ahk" {HPALETTE}
#Import export ".\HPEN.ahk" {HPEN}
#Import export ".\HRGN.ahk" {HRGN}
#Import export ".\KERNINGPAIR.ahk" {KERNINGPAIR}
#Import export ".\LINEDDAPROC.ahk" {LINEDDAPROC}
#Import export ".\LOGBRUSH.ahk" {LOGBRUSH}
#Import export ".\LOGBRUSH32.ahk" {LOGBRUSH32}
#Import export ".\LOGFONTA.ahk" {LOGFONTA}
#Import export ".\LOGFONTW.ahk" {LOGFONTW}
#Import export ".\LOGPALETTE.ahk" {LOGPALETTE}
#Import export ".\LOGPEN.ahk" {LOGPEN}
#Import export ".\LPFNDEVCAPS.ahk" {LPFNDEVCAPS}
#Import export ".\LPFNDEVMODE.ahk" {LPFNDEVMODE}
#Import export ".\MAT2.ahk" {MAT2}
#Import export ".\METAHEADER.ahk" {METAHEADER}
#Import export ".\METARECORD.ahk" {METARECORD}
#Import export ".\MFENUMPROC.ahk" {MFENUMPROC}
#Import export ".\MODIFY_WORLD_TRANSFORM_MODE.ahk" {MODIFY_WORLD_TRANSFORM_MODE}
#Import export ".\MONITORENUMPROC.ahk" {MONITORENUMPROC}
#Import export ".\MONITORINFO.ahk" {MONITORINFO}
#Import export ".\MONITORINFOEXA.ahk" {MONITORINFOEXA}
#Import export ".\MONITORINFOEXW.ahk" {MONITORINFOEXW}
#Import export ".\MONITOR_FROM_FLAGS.ahk" {MONITOR_FROM_FLAGS}
#Import export ".\NEWTEXTMETRICA.ahk" {NEWTEXTMETRICA}
#Import export ".\NEWTEXTMETRICW.ahk" {NEWTEXTMETRICW}
#Import export ".\OBJ_TYPE.ahk" {OBJ_TYPE}
#Import export ".\OUTLINETEXTMETRICA.ahk" {OUTLINETEXTMETRICA}
#Import export ".\OUTLINETEXTMETRICW.ahk" {OUTLINETEXTMETRICW}
#Import export ".\PAINTSTRUCT.ahk" {PAINTSTRUCT}
#Import export ".\PALETTEENTRY.ahk" {PALETTEENTRY}
#Import export ".\PANOSE.ahk" {PANOSE}
#Import export ".\PAN_ARM_STYLE.ahk" {PAN_ARM_STYLE}
#Import export ".\PAN_CONTRAST.ahk" {PAN_CONTRAST}
#Import export ".\PAN_FAMILY_TYPE.ahk" {PAN_FAMILY_TYPE}
#Import export ".\PAN_LETT_FORM.ahk" {PAN_LETT_FORM}
#Import export ".\PAN_MIDLINE.ahk" {PAN_MIDLINE}
#Import export ".\PAN_PROPORTION.ahk" {PAN_PROPORTION}
#Import export ".\PAN_SERIF_STYLE.ahk" {PAN_SERIF_STYLE}
#Import export ".\PAN_STROKE_VARIATION.ahk" {PAN_STROKE_VARIATION}
#Import export ".\PAN_WEIGHT.ahk" {PAN_WEIGHT}
#Import export ".\PAN_XHEIGHT.ahk" {PAN_XHEIGHT}
#Import export ".\PELARRAY.ahk" {PELARRAY}
#Import export ".\PEN_STYLE.ahk" {PEN_STYLE}
#Import export ".\POINTFX.ahk" {POINTFX}
#Import export ".\POLYTEXTA.ahk" {POLYTEXTA}
#Import export ".\POLYTEXTW.ahk" {POLYTEXTW}
#Import export ".\R2_MODE.ahk" {R2_MODE}
#Import export ".\RASTERIZER_STATUS.ahk" {RASTERIZER_STATUS}
#Import export ".\READEMBEDPROC.ahk" {READEMBEDPROC}
#Import export ".\REDRAW_WINDOW_FLAGS.ahk" {REDRAW_WINDOW_FLAGS}
#Import export ".\RGBQUAD.ahk" {RGBQUAD}
#Import export ".\RGBTRIPLE.ahk" {RGBTRIPLE}
#Import export ".\RGNDATA.ahk" {RGNDATA}
#Import export ".\RGNDATAHEADER.ahk" {RGNDATAHEADER}
#Import export ".\RGN_COMBINE_MODE.ahk" {RGN_COMBINE_MODE}
#Import export ".\ROP_CODE.ahk" {ROP_CODE}
#Import export ".\SET_BOUNDS_RECT_FLAGS.ahk" {SET_BOUNDS_RECT_FLAGS}
#Import export ".\STRETCH_BLT_MODE.ahk" {STRETCH_BLT_MODE}
#Import export ".\SYSTEM_PALETTE_USE.ahk" {SYSTEM_PALETTE_USE}
#Import export ".\SYS_COLOR_INDEX.ahk" {SYS_COLOR_INDEX}
#Import export ".\TEXTMETRICA.ahk" {TEXTMETRICA}
#Import export ".\TEXTMETRICW.ahk" {TEXTMETRICW}
#Import export ".\TEXT_ALIGN_OPTIONS.ahk" {TEXT_ALIGN_OPTIONS}
#Import export ".\TMPF_FLAGS.ahk" {TMPF_FLAGS}
#Import export ".\TRIVERTEX.ahk" {TRIVERTEX}
#Import export ".\TTEMBEDINFO.ahk" {TTEMBEDINFO}
#Import export ".\TTEMBED_FLAGS.ahk" {TTEMBED_FLAGS}
#Import export ".\TTLOADINFO.ahk" {TTLOADINFO}
#Import export ".\TTLOAD_EMBEDDED_FONT_STATUS.ahk" {TTLOAD_EMBEDDED_FONT_STATUS}
#Import export ".\TTPOLYCURVE.ahk" {TTPOLYCURVE}
#Import export ".\TTPOLYGONHEADER.ahk" {TTPOLYGONHEADER}
#Import export ".\TTVALIDATIONTESTSPARAMS.ahk" {TTVALIDATIONTESTSPARAMS}
#Import export ".\TTVALIDATIONTESTSPARAMSEX.ahk" {TTVALIDATIONTESTSPARAMSEX}
#Import export ".\WCRANGE.ahk" {WCRANGE}
#Import export ".\WGLSWAP.ahk" {WGLSWAP}
#Import export ".\WRITEEMBEDPROC.ahk" {WRITEEMBEDPROC}
#Import export ".\XFORM.ahk" {XFORM}
