#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ACCESSTIMEOUT.ahk" {ACCESSTIMEOUT}
#Import export ".\ACC_UTILITY_STATE_FLAGS.ahk" {ACC_UTILITY_STATE_FLAGS}
#Import export ".\ActiveEnd.ahk" {ActiveEnd}
#Import export ".\AnimationStyle.ahk" {AnimationStyle}
#Import export ".\AnnoScope.ahk" {AnnoScope}
#Import export ".\Apis.ahk" {*}
#Import export ".\AsyncContentLoadedState.ahk" {AsyncContentLoadedState}
#Import export ".\AutomationElementMode.ahk" {AutomationElementMode}
#Import export ".\AutomationIdentifierType.ahk" {AutomationIdentifierType}
#Import export ".\BulletStyle.ahk" {BulletStyle}
#Import export ".\CAccPropServices.ahk" {CAccPropServices}
#Import export ".\CUIAutomation.ahk" {CUIAutomation}
#Import export ".\CUIAutomation8.ahk" {CUIAutomation8}
#Import export ".\CUIAutomationClientInfo.ahk" {CUIAutomationClientInfo}
#Import export ".\CUIAutomationClientInfoSource.ahk" {CUIAutomationClientInfoSource}
#Import export ".\CUIAutomationRegistrar.ahk" {CUIAutomationRegistrar}
#Import export ".\CapStyle.ahk" {CapStyle}
#Import export ".\CaretBidiMode.ahk" {CaretBidiMode}
#Import export ".\CaretPosition.ahk" {CaretPosition}
#Import export ".\CoalesceEventsOptions.ahk" {CoalesceEventsOptions}
#Import export ".\ConditionType.ahk" {ConditionType}
#Import export ".\ConnectionRecoveryBehaviorOptions.ahk" {ConnectionRecoveryBehaviorOptions}
#Import export ".\Constants.ahk" {*}
#Import export ".\DockPosition.ahk" {DockPosition}
#Import export ".\EventArgsType.ahk" {EventArgsType}
#Import export ".\ExpandCollapseState.ahk" {ExpandCollapseState}
#Import export ".\ExtendedProperty.ahk" {ExtendedProperty}
#Import export ".\FILTERKEYS.ahk" {FILTERKEYS}
#Import export ".\FillType.ahk" {FillType}
#Import export ".\FlowDirections.ahk" {FlowDirections}
#Import export ".\HIGHCONTRASTA.ahk" {HIGHCONTRASTA}
#Import export ".\HIGHCONTRASTW.ahk" {HIGHCONTRASTW}
#Import export ".\HIGHCONTRASTW_FLAGS.ahk" {HIGHCONTRASTW_FLAGS}
#Import export ".\HUIAEVENT.ahk" {HUIAEVENT}
#Import export ".\HUIANODE.ahk" {HUIANODE}
#Import export ".\HUIAPATTERNOBJECT.ahk" {HUIAPATTERNOBJECT}
#Import export ".\HUIATEXTRANGE.ahk" {HUIATEXTRANGE}
#Import export ".\HWINEVENTHOOK.ahk" {HWINEVENTHOOK}
#Import export ".\HorizontalTextAlignment.ahk" {HorizontalTextAlignment}
#Import export ".\IAccIdentity.ahk" {IAccIdentity}
#Import export ".\IAccPropServer.ahk" {IAccPropServer}
#Import export ".\IAccPropServices.ahk" {IAccPropServices}
#Import export ".\IAccessible.ahk" {IAccessible}
#Import export ".\IAccessibleEx.ahk" {IAccessibleEx}
#Import export ".\IAccessibleHandler.ahk" {IAccessibleHandler}
#Import export ".\IAccessibleHostingElementProviders.ahk" {IAccessibleHostingElementProviders}
#Import export ".\IAccessibleWindowlessSite.ahk" {IAccessibleWindowlessSite}
#Import export ".\IAnnotationProvider.ahk" {IAnnotationProvider}
#Import export ".\ICustomNavigationProvider.ahk" {ICustomNavigationProvider}
#Import export ".\IDockProvider.ahk" {IDockProvider}
#Import export ".\IDragProvider.ahk" {IDragProvider}
#Import export ".\IDropTargetProvider.ahk" {IDropTargetProvider}
#Import export ".\IExpandCollapseProvider.ahk" {IExpandCollapseProvider}
#Import export ".\IGridItemProvider.ahk" {IGridItemProvider}
#Import export ".\IGridProvider.ahk" {IGridProvider}
#Import export ".\IInvokeProvider.ahk" {IInvokeProvider}
#Import export ".\IItemContainerProvider.ahk" {IItemContainerProvider}
#Import export ".\ILegacyIAccessibleProvider.ahk" {ILegacyIAccessibleProvider}
#Import export ".\IMultipleViewProvider.ahk" {IMultipleViewProvider}
#Import export ".\IObjectModelProvider.ahk" {IObjectModelProvider}
#Import export ".\IProxyProviderWinEventHandler.ahk" {IProxyProviderWinEventHandler}
#Import export ".\IProxyProviderWinEventSink.ahk" {IProxyProviderWinEventSink}
#Import export ".\IRangeValueProvider.ahk" {IRangeValueProvider}
#Import export ".\IRawElementProviderAdviseEvents.ahk" {IRawElementProviderAdviseEvents}
#Import export ".\IRawElementProviderFragment.ahk" {IRawElementProviderFragment}
#Import export ".\IRawElementProviderFragmentRoot.ahk" {IRawElementProviderFragmentRoot}
#Import export ".\IRawElementProviderHostingAccessibles.ahk" {IRawElementProviderHostingAccessibles}
#Import export ".\IRawElementProviderHwndOverride.ahk" {IRawElementProviderHwndOverride}
#Import export ".\IRawElementProviderSimple.ahk" {IRawElementProviderSimple}
#Import export ".\IRawElementProviderSimple2.ahk" {IRawElementProviderSimple2}
#Import export ".\IRawElementProviderSimple3.ahk" {IRawElementProviderSimple3}
#Import export ".\IRawElementProviderWindowlessSite.ahk" {IRawElementProviderWindowlessSite}
#Import export ".\IRichEditUiaInformation.ahk" {IRichEditUiaInformation}
#Import export ".\IRicheditWindowlessAccessibility.ahk" {IRicheditWindowlessAccessibility}
#Import export ".\IScrollItemProvider.ahk" {IScrollItemProvider}
#Import export ".\IScrollProvider.ahk" {IScrollProvider}
#Import export ".\ISelectionItemProvider.ahk" {ISelectionItemProvider}
#Import export ".\ISelectionProvider.ahk" {ISelectionProvider}
#Import export ".\ISelectionProvider2.ahk" {ISelectionProvider2}
#Import export ".\ISpreadsheetItemProvider.ahk" {ISpreadsheetItemProvider}
#Import export ".\ISpreadsheetProvider.ahk" {ISpreadsheetProvider}
#Import export ".\IStylesProvider.ahk" {IStylesProvider}
#Import export ".\ISynchronizedInputProvider.ahk" {ISynchronizedInputProvider}
#Import export ".\ITableItemProvider.ahk" {ITableItemProvider}
#Import export ".\ITableProvider.ahk" {ITableProvider}
#Import export ".\ITextChildProvider.ahk" {ITextChildProvider}
#Import export ".\ITextEditProvider.ahk" {ITextEditProvider}
#Import export ".\ITextProvider.ahk" {ITextProvider}
#Import export ".\ITextProvider2.ahk" {ITextProvider2}
#Import export ".\ITextRangeProvider.ahk" {ITextRangeProvider}
#Import export ".\ITextRangeProvider2.ahk" {ITextRangeProvider2}
#Import export ".\IToggleProvider.ahk" {IToggleProvider}
#Import export ".\ITransformProvider.ahk" {ITransformProvider}
#Import export ".\ITransformProvider2.ahk" {ITransformProvider2}
#Import export ".\IUIAutomation.ahk" {IUIAutomation}
#Import export ".\IUIAutomation2.ahk" {IUIAutomation2}
#Import export ".\IUIAutomation3.ahk" {IUIAutomation3}
#Import export ".\IUIAutomation4.ahk" {IUIAutomation4}
#Import export ".\IUIAutomation5.ahk" {IUIAutomation5}
#Import export ".\IUIAutomation6.ahk" {IUIAutomation6}
#Import export ".\IUIAutomationActiveTextPositionChangedEventHandler.ahk" {IUIAutomationActiveTextPositionChangedEventHandler}
#Import export ".\IUIAutomationAndCondition.ahk" {IUIAutomationAndCondition}
#Import export ".\IUIAutomationAnnotationPattern.ahk" {IUIAutomationAnnotationPattern}
#Import export ".\IUIAutomationBoolCondition.ahk" {IUIAutomationBoolCondition}
#Import export ".\IUIAutomationCacheRequest.ahk" {IUIAutomationCacheRequest}
#Import export ".\IUIAutomationChangesEventHandler.ahk" {IUIAutomationChangesEventHandler}
#Import export ".\IUIAutomationClientConnectionCallback.ahk" {IUIAutomationClientConnectionCallback}
#Import export ".\IUIAutomationClientInfo.ahk" {IUIAutomationClientInfo}
#Import export ".\IUIAutomationClientInfoSource.ahk" {IUIAutomationClientInfoSource}
#Import export ".\IUIAutomationCondition.ahk" {IUIAutomationCondition}
#Import export ".\IUIAutomationCustomNavigationPattern.ahk" {IUIAutomationCustomNavigationPattern}
#Import export ".\IUIAutomationDockPattern.ahk" {IUIAutomationDockPattern}
#Import export ".\IUIAutomationDragPattern.ahk" {IUIAutomationDragPattern}
#Import export ".\IUIAutomationDropTargetPattern.ahk" {IUIAutomationDropTargetPattern}
#Import export ".\IUIAutomationElement.ahk" {IUIAutomationElement}
#Import export ".\IUIAutomationElement2.ahk" {IUIAutomationElement2}
#Import export ".\IUIAutomationElement3.ahk" {IUIAutomationElement3}
#Import export ".\IUIAutomationElement4.ahk" {IUIAutomationElement4}
#Import export ".\IUIAutomationElement5.ahk" {IUIAutomationElement5}
#Import export ".\IUIAutomationElement6.ahk" {IUIAutomationElement6}
#Import export ".\IUIAutomationElement7.ahk" {IUIAutomationElement7}
#Import export ".\IUIAutomationElement8.ahk" {IUIAutomationElement8}
#Import export ".\IUIAutomationElement9.ahk" {IUIAutomationElement9}
#Import export ".\IUIAutomationElementArray.ahk" {IUIAutomationElementArray}
#Import export ".\IUIAutomationEventHandler.ahk" {IUIAutomationEventHandler}
#Import export ".\IUIAutomationEventHandlerGroup.ahk" {IUIAutomationEventHandlerGroup}
#Import export ".\IUIAutomationExpandCollapsePattern.ahk" {IUIAutomationExpandCollapsePattern}
#Import export ".\IUIAutomationFocusChangedEventHandler.ahk" {IUIAutomationFocusChangedEventHandler}
#Import export ".\IUIAutomationGridItemPattern.ahk" {IUIAutomationGridItemPattern}
#Import export ".\IUIAutomationGridPattern.ahk" {IUIAutomationGridPattern}
#Import export ".\IUIAutomationInvokePattern.ahk" {IUIAutomationInvokePattern}
#Import export ".\IUIAutomationItemContainerPattern.ahk" {IUIAutomationItemContainerPattern}
#Import export ".\IUIAutomationLegacyIAccessiblePattern.ahk" {IUIAutomationLegacyIAccessiblePattern}
#Import export ".\IUIAutomationMultipleViewPattern.ahk" {IUIAutomationMultipleViewPattern}
#Import export ".\IUIAutomationNotCondition.ahk" {IUIAutomationNotCondition}
#Import export ".\IUIAutomationNotificationEventHandler.ahk" {IUIAutomationNotificationEventHandler}
#Import export ".\IUIAutomationObjectModelPattern.ahk" {IUIAutomationObjectModelPattern}
#Import export ".\IUIAutomationOrCondition.ahk" {IUIAutomationOrCondition}
#Import export ".\IUIAutomationPatternHandler.ahk" {IUIAutomationPatternHandler}
#Import export ".\IUIAutomationPatternInstance.ahk" {IUIAutomationPatternInstance}
#Import export ".\IUIAutomationPropertyChangedEventHandler.ahk" {IUIAutomationPropertyChangedEventHandler}
#Import export ".\IUIAutomationPropertyCondition.ahk" {IUIAutomationPropertyCondition}
#Import export ".\IUIAutomationProxyFactory.ahk" {IUIAutomationProxyFactory}
#Import export ".\IUIAutomationProxyFactoryEntry.ahk" {IUIAutomationProxyFactoryEntry}
#Import export ".\IUIAutomationProxyFactoryMapping.ahk" {IUIAutomationProxyFactoryMapping}
#Import export ".\IUIAutomationRangeValuePattern.ahk" {IUIAutomationRangeValuePattern}
#Import export ".\IUIAutomationRegistrar.ahk" {IUIAutomationRegistrar}
#Import export ".\IUIAutomationScrollItemPattern.ahk" {IUIAutomationScrollItemPattern}
#Import export ".\IUIAutomationScrollPattern.ahk" {IUIAutomationScrollPattern}
#Import export ".\IUIAutomationSelectionItemPattern.ahk" {IUIAutomationSelectionItemPattern}
#Import export ".\IUIAutomationSelectionPattern.ahk" {IUIAutomationSelectionPattern}
#Import export ".\IUIAutomationSelectionPattern2.ahk" {IUIAutomationSelectionPattern2}
#Import export ".\IUIAutomationSpreadsheetItemPattern.ahk" {IUIAutomationSpreadsheetItemPattern}
#Import export ".\IUIAutomationSpreadsheetPattern.ahk" {IUIAutomationSpreadsheetPattern}
#Import export ".\IUIAutomationStructureChangedEventHandler.ahk" {IUIAutomationStructureChangedEventHandler}
#Import export ".\IUIAutomationStylesPattern.ahk" {IUIAutomationStylesPattern}
#Import export ".\IUIAutomationSynchronizedInputPattern.ahk" {IUIAutomationSynchronizedInputPattern}
#Import export ".\IUIAutomationTableItemPattern.ahk" {IUIAutomationTableItemPattern}
#Import export ".\IUIAutomationTablePattern.ahk" {IUIAutomationTablePattern}
#Import export ".\IUIAutomationTextChildPattern.ahk" {IUIAutomationTextChildPattern}
#Import export ".\IUIAutomationTextEditPattern.ahk" {IUIAutomationTextEditPattern}
#Import export ".\IUIAutomationTextEditTextChangedEventHandler.ahk" {IUIAutomationTextEditTextChangedEventHandler}
#Import export ".\IUIAutomationTextPattern.ahk" {IUIAutomationTextPattern}
#Import export ".\IUIAutomationTextPattern2.ahk" {IUIAutomationTextPattern2}
#Import export ".\IUIAutomationTextRange.ahk" {IUIAutomationTextRange}
#Import export ".\IUIAutomationTextRange2.ahk" {IUIAutomationTextRange2}
#Import export ".\IUIAutomationTextRange3.ahk" {IUIAutomationTextRange3}
#Import export ".\IUIAutomationTextRangeArray.ahk" {IUIAutomationTextRangeArray}
#Import export ".\IUIAutomationTogglePattern.ahk" {IUIAutomationTogglePattern}
#Import export ".\IUIAutomationTransformPattern.ahk" {IUIAutomationTransformPattern}
#Import export ".\IUIAutomationTransformPattern2.ahk" {IUIAutomationTransformPattern2}
#Import export ".\IUIAutomationTreeWalker.ahk" {IUIAutomationTreeWalker}
#Import export ".\IUIAutomationValuePattern.ahk" {IUIAutomationValuePattern}
#Import export ".\IUIAutomationVirtualizedItemPattern.ahk" {IUIAutomationVirtualizedItemPattern}
#Import export ".\IUIAutomationWindowPattern.ahk" {IUIAutomationWindowPattern}
#Import export ".\IValueProvider.ahk" {IValueProvider}
#Import export ".\IVirtualizedItemProvider.ahk" {IVirtualizedItemProvider}
#Import export ".\IWindowProvider.ahk" {IWindowProvider}
#Import export ".\LPFNACCESSIBLECHILDREN.ahk" {LPFNACCESSIBLECHILDREN}
#Import export ".\LPFNACCESSIBLEOBJECTFROMPOINT.ahk" {LPFNACCESSIBLEOBJECTFROMPOINT}
#Import export ".\LPFNACCESSIBLEOBJECTFROMWINDOW.ahk" {LPFNACCESSIBLEOBJECTFROMWINDOW}
#Import export ".\LPFNCREATESTDACCESSIBLEOBJECT.ahk" {LPFNCREATESTDACCESSIBLEOBJECT}
#Import export ".\LPFNLRESULTFROMOBJECT.ahk" {LPFNLRESULTFROMOBJECT}
#Import export ".\LPFNOBJECTFROMLRESULT.ahk" {LPFNOBJECTFROMLRESULT}
#Import export ".\LiveSetting.ahk" {LiveSetting}
#Import export ".\MOUSEKEYS.ahk" {MOUSEKEYS}
#Import export ".\MSAAMENUINFO.ahk" {MSAAMENUINFO}
#Import export ".\NavigateDirection.ahk" {NavigateDirection}
#Import export ".\NormalizeState.ahk" {NormalizeState}
#Import export ".\NotificationKind.ahk" {NotificationKind}
#Import export ".\NotificationProcessing.ahk" {NotificationProcessing}
#Import export ".\OrientationType.ahk" {OrientationType}
#Import export ".\OutlineStyles.ahk" {OutlineStyles}
#Import export ".\PropertyConditionFlags.ahk" {PropertyConditionFlags}
#Import export ".\ProviderOptions.ahk" {ProviderOptions}
#Import export ".\ProviderType.ahk" {ProviderType}
#Import export ".\RowOrColumnMajor.ahk" {RowOrColumnMajor}
#Import export ".\SERIALKEYSA.ahk" {SERIALKEYSA}
#Import export ".\SERIALKEYSW.ahk" {SERIALKEYSW}
#Import export ".\SERIALKEYS_FLAGS.ahk" {SERIALKEYS_FLAGS}
#Import export ".\SOUNDSENTRYA.ahk" {SOUNDSENTRYA}
#Import export ".\SOUNDSENTRYW.ahk" {SOUNDSENTRYW}
#Import export ".\SOUNDSENTRY_FLAGS.ahk" {SOUNDSENTRY_FLAGS}
#Import export ".\SOUNDSENTRY_TEXT_EFFECT.ahk" {SOUNDSENTRY_TEXT_EFFECT}
#Import export ".\SOUNDSENTRY_WINDOWS_EFFECT.ahk" {SOUNDSENTRY_WINDOWS_EFFECT}
#Import export ".\SOUND_SENTRY_GRAPHICS_EFFECT.ahk" {SOUND_SENTRY_GRAPHICS_EFFECT}
#Import export ".\STICKYKEYS.ahk" {STICKYKEYS}
#Import export ".\STICKYKEYS_FLAGS.ahk" {STICKYKEYS_FLAGS}
#Import export ".\SayAsInterpretAs.ahk" {SayAsInterpretAs}
#Import export ".\ScrollAmount.ahk" {ScrollAmount}
#Import export ".\StructureChangeType.ahk" {StructureChangeType}
#Import export ".\SupportedTextSelection.ahk" {SupportedTextSelection}
#Import export ".\SynchronizedInputType.ahk" {SynchronizedInputType}
#Import export ".\TOGGLEKEYS.ahk" {TOGGLEKEYS}
#Import export ".\TextDecorationLineStyle.ahk" {TextDecorationLineStyle}
#Import export ".\TextEditChangeType.ahk" {TextEditChangeType}
#Import export ".\TextPatternRangeEndpoint.ahk" {TextPatternRangeEndpoint}
#Import export ".\TextUnit.ahk" {TextUnit}
#Import export ".\ToggleState.ahk" {ToggleState}
#Import export ".\TreeScope.ahk" {TreeScope}
#Import export ".\TreeTraversalOptions.ahk" {TreeTraversalOptions}
#Import export ".\UIA_ANNOTATIONTYPE.ahk" {UIA_ANNOTATIONTYPE}
#Import export ".\UIA_CHANGE_ID.ahk" {UIA_CHANGE_ID}
#Import export ".\UIA_CONTROLTYPE_ID.ahk" {UIA_CONTROLTYPE_ID}
#Import export ".\UIA_EVENT_ID.ahk" {UIA_EVENT_ID}
#Import export ".\UIA_HEADINGLEVEL_ID.ahk" {UIA_HEADINGLEVEL_ID}
#Import export ".\UIA_LANDMARKTYPE_ID.ahk" {UIA_LANDMARKTYPE_ID}
#Import export ".\UIA_METADATA_ID.ahk" {UIA_METADATA_ID}
#Import export ".\UIA_PATTERN_ID.ahk" {UIA_PATTERN_ID}
#Import export ".\UIA_PROPERTY_ID.ahk" {UIA_PROPERTY_ID}
#Import export ".\UIA_STYLE_ID.ahk" {UIA_STYLE_ID}
#Import export ".\UIA_TEXTATTRIBUTE_ID.ahk" {UIA_TEXTATTRIBUTE_ID}
#Import export ".\UIAutomationEventInfo.ahk" {UIAutomationEventInfo}
#Import export ".\UIAutomationMethodInfo.ahk" {UIAutomationMethodInfo}
#Import export ".\UIAutomationParameter.ahk" {UIAutomationParameter}
#Import export ".\UIAutomationPatternInfo.ahk" {UIAutomationPatternInfo}
#Import export ".\UIAutomationPropertyInfo.ahk" {UIAutomationPropertyInfo}
#Import export ".\UIAutomationType.ahk" {UIAutomationType}
#Import export ".\UiaAndOrCondition.ahk" {UiaAndOrCondition}
#Import export ".\UiaAsyncContentLoadedEventArgs.ahk" {UiaAsyncContentLoadedEventArgs}
#Import export ".\UiaCacheRequest.ahk" {UiaCacheRequest}
#Import export ".\UiaChangeInfo.ahk" {UiaChangeInfo}
#Import export ".\UiaChangesEventArgs.ahk" {UiaChangesEventArgs}
#Import export ".\UiaCondition.ahk" {UiaCondition}
#Import export ".\UiaEventArgs.ahk" {UiaEventArgs}
#Import export ".\UiaEventCallback.ahk" {UiaEventCallback}
#Import export ".\UiaFindParams.ahk" {UiaFindParams}
#Import export ".\UiaNotCondition.ahk" {UiaNotCondition}
#Import export ".\UiaPoint.ahk" {UiaPoint}
#Import export ".\UiaPropertyChangedEventArgs.ahk" {UiaPropertyChangedEventArgs}
#Import export ".\UiaPropertyCondition.ahk" {UiaPropertyCondition}
#Import export ".\UiaProviderCallback.ahk" {UiaProviderCallback}
#Import export ".\UiaRect.ahk" {UiaRect}
#Import export ".\UiaStructureChangedEventArgs.ahk" {UiaStructureChangedEventArgs}
#Import export ".\UiaTextEditTextChangedEventArgs.ahk" {UiaTextEditTextChangedEventArgs}
#Import export ".\UiaWindowClosedEventArgs.ahk" {UiaWindowClosedEventArgs}
#Import export ".\VisualEffects.ahk" {VisualEffects}
#Import export ".\WINEVENTPROC.ahk" {WINEVENTPROC}
#Import export ".\WindowInteractionState.ahk" {WindowInteractionState}
#Import export ".\WindowVisualState.ahk" {WindowVisualState}
#Import export ".\ZoomUnit.ahk" {ZoomUnit}
