#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\..\Foundation\BSTR.ahk
#Include ..\..\System\Com\IDispatch.ahk
#Include ..\..\System\Variant\VARIANT.ahk

/**
 * Exposes methods and properties that make a user interface element and its children accessible to client applications.
 * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nn-oleacc-iaccessible
 * @namespace Windows.Win32.UI.Accessibility
 * @version v4.0.30319
 */
class IAccessible extends IDispatch{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IAccessible
     * @type {Guid}
     */
    static IID => Guid("{618736e0-3c3d-11cf-810c-00aa00389b71}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 7

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["get_accParent", "get_accChildCount", "get_accChild", "get_accName", "get_accValue", "get_accDescription", "get_accRole", "get_accState", "get_accHelp", "get_accHelpTopic", "get_accKeyboardShortcut", "get_accFocus", "get_accSelection", "get_accDefaultAction", "accSelect", "accLocation", "accNavigate", "accHitTest", "accDoDefaultAction", "put_accName", "put_accValue"]

    /**
     * @type {IDispatch} 
     */
    accParent {
        get => this.get_accParent()
    }

    /**
     * @type {Integer} 
     */
    accChildCount {
        get => this.get_accChildCount()
    }

    /**
     * @type {VARIANT} 
     */
    accFocus {
        get => this.get_accFocus()
    }

    /**
     * @type {VARIANT} 
     */
    accSelection {
        get => this.get_accSelection()
    }

    /**
     * The IAccessible::get_accParent method retrieves the IDispatch of the object's parent. All objects support this property.
     * @returns {IDispatch} Type: <b>IDispatch**</b>
     * 
     *  Receives the address of the parent object's <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch</a> interface. If no parent exists or if the child cannot access its parent, the variable is set to <b>NULL</b>.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_accparent
     */
    get_accParent() {
        result := ComCall(7, this, "ptr*", &ppdispParent := 0, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return IDispatch(ppdispParent)
    }

    /**
     * The IAccessible::get_accChildCount method retrieves the number of children that belong to this object. All objects must support this property.
     * @remarks
     * The number of children in an object can change. An application tracks the changes to the child count by watching for <a href="https://docs.microsoft.com/windows/desktop/WinAuto/event-constants">EVENT_OBJECT_CREATE</a> and <a href="https://docs.microsoft.com/windows/desktop/WinAuto/event-constants">EVENT_OBJECT_DESTROY</a> events generated by this object.
     * 
     * <b>Note to server developers:  </b>If the object does not have any children, return S_OK and set <i>pcountChildren</i> to zero.
     * @returns {Integer} Type: <b>long*</b>
     * 
     *  Address of a variable that receives the number of children that belong to this object. The children are accessible objects or child elements. If the object has no children, this value is zero.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_accchildcount
     */
    get_accChildCount() {
        result := ComCall(8, this, "int*", &pcountChildren := 0, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pcountChildren
    }

    /**
     * The IAccessible::get_accChild method retrieves an IDispatch for the specified child, if one exists. All objects must support this property.
     * @remarks
     * Servers expose elements as either elements (child IDs) or full objects (<a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> interface pointers). If a child is an element, <b>get_accChild</b> returns S_FALSE, and the parent will provide information for that child. If the child is a full object, <b>get_accChild</b> will return the <b>IAccessible</b> interface pointer and the parent will not provide information about that child. If <b>get_accChild</b> fails because the server application cannot create an accessible object due to a temporary system error (such as an out-of-memory error), the server should return a suitable failure code.
     * 
     * <b>Note to server developers:  </b>If <i>varChildID</i> contains VT_EMPTY, you should return E_INVALIDARG.
     *             
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example code shows an implementation for an object that does not have any children, or whose children are elements rather than objects.
     * 
     * 
     * ```cpp
     * 
     * HRESULT STDMETHODCALLTYPE AccServer::get_accChild( 
     *     VARIANT varChild,
     *     IDispatch **ppdispChild)
     * {
     *     if (varChild.vt != VT_I4)
     *     {
     *         *ppdispChild = NULL;
     *         return E_INVALIDARG;
     *     }
     *     *ppdispChild = NULL;    
     *     return S_FALSE;     
     * };
     * 
     * ```
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Identifies the child whose <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch</a> interface is retrieved. For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {IDispatch} Type: <b>IDispatch**</b>
     * 
     * [out, retval] Receives the address of the child object's <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch</a> interface.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_accchild
     */
    get_accChild(varChild) {
        result := ComCall(9, this, "ptr", varChild, "ptr*", &ppdispChild := 0, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return IDispatch(ppdispChild)
    }

    /**
     * The IAccessible::get_accName method retrieves the name of the specified object. All objects support this property.
     * @remarks
     * Many objects such as icons, menus, check boxes, combo boxes, and other controls have labels that are displayed to users. Any label that is displayed to users is used for the object's name property. For more information, see the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/name-property">Name Property</a>.
     * 
     * <b>Note to server developers:  </b>If you are using menu or button text for the Name property, remove any ampersands (&amp;) marking the keyboard access keys. Provide the access key to the client in response to <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-get_acckeyboardshortcut">IAccessible::get_accKeyboardShortcut</a>.
     * 
     * Localize the string returned from this property.
     * 
     * 
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example shows a possible implementation of this method for a custom list box control that manages its own child elements.
     * 
     * 
     * ```cpp
     * 
     * // m_pStdAccessibleObject is the standard object returned by CreateStdAccessibleObject. 
     * // m_pControl is the control object that provides this accessibility object. It maintains
     * // a zero-based collection of child items. 
     * 
     * HRESULT STDMETHODCALLTYPE AccServer::get_accName( 
     *     VARIANT varChild,
     *     BSTR *pszName)
     * {
     *     if (varChild.vt != VT_I4)
     *     {
     *         *pszName = NULL;
     *         return E_INVALIDARG;
     *     }
     *     // For the control itself, let the standard accessible object return the name 
     *     // assigned by the application. This is either the "caption" property or, if 
     *     // there is no caption, the text of any label. 
     *     if (varChild.lVal == CHILDID_SELF)
     *     {
     *         return m_pStdAccessibleObject->get_accName(varChild, pszName);                  
     *     }
     *     
     *     // Else return the name of the item in the list. 
     *     else
     *     {
     *         CustomListControlItem* pItem = m_pControl->GetItemAt(varChild.lVal - 1);
     *         if (pItem)
     *         {
     *             *pszName = SysAllocString(pItem->GetName());        
     *        
     *         }
     *     }
     *     return S_OK;
     * };
     * 
     * ```
     * 
     * 
     * <h3><a id="Client_Example"></a><a id="client_example"></a><a id="CLIENT_EXAMPLE"></a>Client Example</h3>
     * The following example function displays the accessible name of a control.
     * 
     * 
     * ```cpp
     * 
     * HRESULT PrintName(IAccessible* pAcc, long childId)
     * {
     *     if (pAcc == NULL)
     *     {
     *         return E_INVALIDARG;
     *     }
     *     BSTR bstrName;
     *     VARIANT varChild;
     *     varChild.vt = VT_I4;
     *     varChild.lVal = childId;
     *     HRESULT hr = pAcc->get_accName(varChild, &bstrName);
     *     printf("Name: %S ", bstrName);
     *     SysFreeString(bstrName);
     *     return hr;
     * }
     * 
     * ```
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the retrieved name belongs to the object or one of the object's child elements. This parameter is either CHILDID_SELF (to obtain information about the object) or a child ID (to obtain information about the object's child element). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT structure</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {BSTR} Type: <b>BSTR*</b>
     * 
     * Address of a <b>BSTR</b> that receives a string that contains the specified object's name.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_accname
     */
    get_accName(varChild) {
        pszName := BSTR()
        result := ComCall(10, this, "ptr", varChild, "ptr", pszName, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pszName
    }

    /**
     * The IAccessible::get_accValue method retrieves the value of the specified object. Not all objects have a value.
     * @remarks
     * Numeric values returned from scroll bar and trackbar accessible objects indicate percentages. They are integers between zero (0) and one hundred (100), inclusive, but might also be a limited range for example, between one (1) and sixteen (16). Also, some scroll bar and trackbar objects return strings that correspond to settings such as screen size or Internet security.
     * 
     * <b>Note to server developers:  </b>Localize the string returned from this property.
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the retrieved value information belongs to the object or one of the object's child elements. This parameter is either CHILDID_SELF (to obtain information about the object) or a child ID (to obtain information about the object's child element). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT structure</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {BSTR} Type: <b>BSTR*</b>
     * 
     *  Address of the <b>BSTR</b> that receives a localized string that contains the object's current value.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_accvalue
     */
    get_accValue(varChild) {
        pszValue := BSTR()
        result := ComCall(11, this, "ptr", varChild, "ptr", pszValue, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pszValue
    }

    /**
     * The IAccessible::get_accDescription method retrieves a string that describes the visual appearance of the specified object. Not all objects have a description.
     * @remarks
     * An Microsoft Active Accessibility server can add support for UI Automation by using Direct Annotation, using the <a href="https://docs.microsoft.com/windows/desktop/api/uiautomationcore/nn-uiautomationcore-iaccessibleex">IAccessibleEx</a> interface, or by implementing Microsoft Active Accessibility and UI Automation side-by-side with both implementations handling the [WM_GETOBJECT](/windows/win32/winauto/wm-getobject) message.
     * 
     * This property provides a textual equivalent of the object for the user. The description should be similar to the text supplied with the ALT attribute in HTML, which is the text that is displayed to describe images for people using text-only browsers. However, some controls use this property to store extra information about the control that is not related to a textual equivalent. For more information about this property, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/description-property">Description Property</a>.
     * 
     * <b>Note to server developers:  </b>Localize the string returned from this property.
     *             
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example code shows one possible implementation of this method for a custom list box that maintains its own child elements. The example demonstrates the syntax, but remember that a real text-only list box would probably not need to support this property. For simplicity, the strings in the example are not localized.
     * 
     * 
     * ```cpp
     * 
     * HRESULT STDMETHODCALLTYPE AccServer::get_accDescription( 
     *     VARIANT varChild,
     *     BSTR *pszDescription)
     * {
     *     if (varChild.vt != VT_I4)
     *     {
     *         *pszDescription = NULL;
     *         return E_INVALIDARG;
     *     }
     *     if (varChild.lVal == CHILDID_SELF)
     *     {
     *         *pszDescription = SysAllocString(L"List of contacts.");    
     *             
     *     }
     *     else
     *     {
     *         *pszDescription = SysAllocString(L"A contact.");           
     *             
     *     }
     *     return S_OK;
     * };
     * 
     * ```
     * 
     * 
     * <h3><a id="Client_Example"></a><a id="client_example"></a><a id="CLIENT_EXAMPLE"></a>Client Example</h3>
     * The following example function retrieves the description of the specified accessible object, or a child element, and displays it on the console.
     * 
     * 
     * ```cpp
     * 
     * HRESULT PrintDescription(IAccessible* pAcc, long child)
     * {
     *     VARIANT varObject;
     *     varObject.vt = VT_I4;
     *     varObject.lVal = child;
     *     BSTR bstrDesc;
     *     HRESULT hr = pAcc->get_accDescription(varObject, &bstrDesc);
     *     if (hr == S_OK)
     *     {
     *         printf("Description: %S\n", bstrDesc);
     *         SysFreeString(bstrDesc);
     *     }
     *     return hr;
     * }
     * 
     * ```
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the retrieved description belongs to the object or one of the object's child elements. This parameter is either CHILDID_SELF (to obtain information about the object) or a child ID (to obtain information about the object's child element). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT structure</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {BSTR} Type: <b>BSTR*</b>
     * 
     *  Address of a <b>BSTR</b> that receives a localized string that describes the specified object, or <b>NULL</b> if this object has no description.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_accdescription
     */
    get_accDescription(varChild) {
        pszDescription := BSTR()
        result := ComCall(12, this, "ptr", varChild, "ptr", pszDescription, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pszDescription
    }

    /**
     * The IAccessible::get_accRole method retrieves information that describes the role of the specified object. All objects support this property.
     * @remarks
     * Clients call <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-getroletexta">GetRoleText</a> to retrieve a localized string that describes the object's role.
     * 
     * <b>Note to server developers:  </b>You must use the predefined role constants.
     *             
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example code is a possible implementation of this method for a custom list box that maintains its own list items.
     * 
     * 
     * ```cpp
     * 
     * HRESULT STDMETHODCALLTYPE AccServer::get_accRole( 
     *     VARIANT varChild,
     *     VARIANT *pvarRole)
     * {
     *     if (varChild.vt != VT_I4)
     *     {
     *         pvarRole->vt = VT_EMPTY;
     *         return E_INVALIDARG;
     *     }
     * 
     *     pvarRole->vt = VT_I4;
     * 
     *     if (varChild.lVal == CHILDID_SELF)
     *     {
     *         pvarRole->lVal = ROLE_SYSTEM_LIST;
     *     }
     *     else
     *     {
     *         pvarRole->lVal = ROLE_SYSTEM_LISTITEM;
     *     }
     *     return S_OK;
     * };
     * 
     * ```
     * 
     * 
     * <h3><a id="Client_Example"></a><a id="client_example"></a><a id="CLIENT_EXAMPLE"></a>Client Example</h3>
     * The following example function displays the role of an accessible object or child element.
     * 
     * 
     * ```cpp
     * 
     * HRESULT PrintRole(IAccessible* pAcc, long childId)
     * {
     *     DWORD roleId;
     *     if (pAcc == NULL)
     *     {
     *         return E_INVALIDARG;    
     *     }
     *     VARIANT varChild;
     *     varChild.vt = VT_I4;
     *     varChild.lVal = childId;
     *     VARIANT varResult;
     *     HRESULT hr = pAcc->get_accRole(varChild, &varResult);
     *     if ((hr == S_OK) && (varResult.vt == VT_I4))
     *     {
     *         roleId = varResult.lVal;
     *         UINT   roleLength;
     *         LPTSTR lpszRoleString;
     * 
     *         // Get the length of the string. 
     *         roleLength = GetRoleText(roleId, NULL, 0);
     * 
     *         // Allocate memory for the string. Add one character to 
     *         // the length you got in the previous call to make room 
     *         // for the null character. 
     *         lpszRoleString = (LPTSTR)malloc((roleLength+1) * sizeof(TCHAR));
     *         if (lpszRoleString != NULL)
     *         {
     *             // Get the string. 
     *             GetRoleText(roleId, lpszRoleString, roleLength + 1);
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the retrieved role information belongs to the object or one of the object's child elements. This parameter is either CHILDID_SELF (to obtain information about the object) or a child ID (to obtain information about the object's child element). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {VARIANT} Type: <b>VARIANT*</b>
     * 
     * Address of a <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT</a> that receives an <a href="https://docs.microsoft.com/windows/desktop/WinAuto/object-roles">object role</a> constant. The <b>vt</b> member must be VT_I4. The <b>lVal</b> member receives an object role constant.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_accrole
     */
    get_accRole(varChild) {
        pvarRole := VARIANT()
        result := ComCall(13, this, "ptr", varChild, "ptr", pvarRole, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pvarRole
    }

    /**
     * The IAccessible::get_accState method retrieves the current state of the specified object. All objects support this property.
     * @remarks
     * If predefined state values are returned, clients call <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-getstatetexta">GetStateText</a> to retrieve a localized string that describes the object's state.
     * 
     * The actual state of a child often depends on the state of its ancestors. For example, controls in an application's main window are not focusable when a modal dialog box is open, but the controls may not report this state. To verify the state information of a child object, call <b>get_accState</b> for the parent object.
     * 
     * <b>Note to server developers:  </b>You must use the predefined state constants.
     *             
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example code shows a possible implementation of this method for a custom list box that maintains its own child elements (list items), only one of which can be selected at a time. If the client requests the state of the list box itself, the method passes the call to the standard accessible object that serves the control window. For child items, different flags are returned depending on whether the item is selected or not.
     * 
     * 
     * ```cpp
     * 
     * // m_pStdAccessibleObject is the standard accessible object returned by CreateAccessibleObject. 
     * // m_pControl is the custom control instance that returns this accessible object. 
     * 
     * HRESULT STDMETHODCALLTYPE AccServer::get_accState( 
     *     VARIANT varChild,
     *     VARIANT *pvarState)
     * {
     *     if (varChild.vt != VT_I4)
     *     {
     *         pvarState->vt = VT_EMPTY;
     *         return E_INVALIDARG;
     *     }
     *     if (varChild.lVal == CHILDID_SELF)
     *     {
     *         return m_pStdAccessibleObject->get_accState(varChild, pvarState);
     *     }
     *     else  // For list items. 
     *     {
     *         DWORD flags = STATE_SYSTEM_SELECTABLE;
     *         int index = (int)varChild.lVal - 1;
     *         if (index == m_pControl->GetSelectedIndex())
     *         {
     *             flags |= STATE_SYSTEM_SELECTED;
     *         }
     *         pvarState->vt = VT_I4;
     *         pvarState->lVal = flags; 
     *     }
     *     return S_OK;
     * };
     * 
     * ```
     * 
     * 
     * <h3><a id="Client_Example"></a><a id="client_example"></a><a id="CLIENT_EXAMPLE"></a>Client Example</h3>
     * The following example function displays the states of the specified accessible object or a child element.
     * 
     * 
     * ```cpp
     * 
     * HRESULT PrintState(IAccessible* pAcc, long childId)
     * {
     *     if (pAcc == NULL)
     *     {
     *         return E_INVALIDARG;    
     *     }
     *     VARIANT      varChild;
     *     varChild.vt = VT_I4;
     *     varChild.lVal = childId;
     *     VARIANT varResult;
     *     HRESULT hr = pAcc->get_accState(varChild, &varResult);
     *     long stateBits = 0;
     *     if ((hr == S_OK) && (varResult.vt == VT_I4))
     *     {
     *         printf("State: ");
     *         stateBits = (DWORD)varResult.lVal;
     *         for (DWORD mask = 1; mask <= 0x8000; mask <<= 1)
     *         {
     *             if (mask & stateBits)
     *             {
     * 
     *                 // Get the length of the string. 
     *                 UINT stateLength = GetStateText(mask, NULL, 0);
     * 
     *                 // Allocate memory for the string. Add one character to 
     *                 // the length you got in the previous call to make room 
     *                 // for the null character. 
     *                 LPTSTR lpszStateString = (LPTSTR)malloc(
     *                     (stateLength + 1) * sizeof(TCHAR));
     *                 if (lpszStateString != NULL)
     *                 {
     *                     // Get the string. 
     *                     GetStateText(mask, 
     *                         lpszStateString, stateLength + 1);
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the retrieved state information belongs to the object or of one of the object's child elements. This parameter is either CHILDID_SELF (to obtain information about the object) or a child ID (to obtain information about the object's child element). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {VARIANT} Type: <b>VARIANT*</b>
     * 
     * Address of a <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT structure</a> that receives information that describes the object's state. The <b>vt</b> member is VT_I4, and the <b>lVal</b> member is one or more of the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/object-state-constants">object state constants</a>.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_accstate
     */
    get_accState(varChild) {
        pvarState := VARIANT()
        result := ComCall(14, this, "ptr", varChild, "ptr", pvarState, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pvarState
    }

    /**
     * The IAccessible::get_accHelp method retrieves the Help property string of an object. Not all objects support this property.
     * @remarks
     * None of the predefined and common controls support this property.
     * 
     * <b>Note to server developers:  </b>Localize the string returned from this property.
     * 
     * This property returns a string, whereas <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-get_acchelptopic">IAccessible::get_accHelpTopic</a> provides access to a Help topic in <a href="https://docs.microsoft.com/windows/win32/api/winuser/nf-winuser-winhelpa">WinHelp</a>. Objects are not required to support both <b>IAccessible::get_accHelp</b> and <b>IAccessible::get_accHelpTopic</b>, but they must support at least one. If they easily return a string, they must support <b>IAccessible::get_accHelp</b> ; otherwise they must support <b>IAccessible::get_accHelpTopic</b>. If both are supported, <b>IAccessible::get_accHelpTopic</b> provides more detailed information.
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example code shows one possible implementation of this method for a custom list box. Different text is displayed depending on the status of the contact in the list. For simplicity, the example does not localize the returned string.
     * 
     * 
     * ```cpp
     * 
     * // m_pControl is the custom control that returns this accessible object. 
     * // 'online' is an enumerated value. 
     * 
     * HRESULT STDMETHODCALLTYPE AccServer::get_accHelp( 
     *     VARIANT varChild,
     *     BSTR *pszHelp)
     * {
     *     *pszHelp = NULL;
     *     if (varChild.vt != VT_I4)
     *     {
     *         return E_INVALIDARG;
     *     }
     *     if (varChild.lVal == CHILDID_SELF)
     *     {
     *         *pszHelp = SysAllocString(L"Contact list.");
     *     }
     *     else
     *     {
     *         int index = (int)varChild.lVal - 1;
     *         CustomListControlItem* pItem = m_pControl->GetItemAt(index);
     *         if (pItem == NULL)
     *         {
     *             return E_INVALIDARG;
     *         }
     *         if (pItem->GetStatus() == online)
     *         {
     *             *pszHelp = SysAllocString(L"Online contact.");
     *         }
     *         else 
     *         {
     *             *pszHelp = SysAllocString(L"Offline contact.");
     *         }
     *     }
     *     return S_OK;
     * };
     * 
     * ```
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the retrieved help information belongs to the object or one of the object's child elements. This parameter is either CHILDID_SELF (to obtain information about the object) or a child ID (to obtain information about one of the object's child elements). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {BSTR} Type: <b>BSTR*</b>
     * 
     * Address of a <b>BSTR</b> that receives the localized string containing the help information for the specified object, or <b>NULL</b> if no help information is available.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_acchelp
     */
    get_accHelp(varChild) {
        pszHelp := BSTR()
        result := ComCall(15, this, "ptr", varChild, "ptr", pszHelp, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pszHelp
    }

    /**
     * The IAccessible::get_accHelpTopic method retrieves the full path of the WinHelp file that is associated with the specified object; it also retrieves the identifier of the appropriate topic within that file.
     * @remarks
     * Getting information from a Help file might be time and memory intensive.
     * 
     * <b>Note to server developers:  </b>This property provides access to a Help topic in WinHelp, whereas <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-get_acchelp">IAccessible::get_accHelp</a> returns a string. Objects are not required to support both <b>IAccessible::get_accHelp</b> and <b>IAccessible::get_accHelpTopic</b>, but they must support at least one. If they can easily return a string, they must support <b>IAccessible::get_accHelp</b>; otherwise they must support <b>IAccessible::get_accHelpTopic</b>. If both are supported, <b>IAccessible::get_accHelpTopic</b> provides more detailed information.
     * @param {Pointer<BSTR>} pszHelpFile Type: <b>BSTR*</b>
     * 
     * Address of a <b>BSTR</b> that receives the full path of the WinHelp file that is associated with the specified object.
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the retrieved Help topic belongs to the object or one of the object's child elements. This parameter is either CHILDID_SELF (to obtain a Help topic for the object) or a child ID (to obtain a Help topic for one of the object's child elements). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {Integer} Type: <b>long*</b>
     * 
     * [out, retval] Address of a variable that identifies the Help file topic associated with the specified object. This value is used as the context identifier of the desired topic that passes to the <a href="https://docs.microsoft.com/windows/win32/api/winuser/nf-winuser-winhelpa">WinHelp</a> function. When calling <a href="https://docs.microsoft.com/windows/win32/api/winuser/nf-winuser-winhelpa">WinHelp</a> to display the topic, set the <i>uCommand</i> parameter to HELP_CONTEXT, cast the value pointed to by <i>pidTopic</i> to a <b>DWORD</b>, and pass it as the <i>dwData</i> parameter.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_acchelptopic
     */
    get_accHelpTopic(pszHelpFile, varChild) {
        result := ComCall(16, this, "ptr", pszHelpFile, "ptr", varChild, "int*", &pidTopic := 0, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pidTopic
    }

    /**
     * The IAccessible::get_accKeyboardShortcut method retrieves the specified object's shortcut key or access key, also known as the mnemonic. All objects that have a shortcut key or an access key support this property.
     * @remarks
     * An access key is an underlined character in the text of a menu, menu item, or label of a button or some other control. For example, a user can display a menu by pressing the ALT key while also pressing the indicated underlined key, such as ALT+F to open the <u>F</u>ile menu. To use the access key of a menu item, the menu that contains the item must be active.
     * 
     * Controls such as toolbar buttons and menu items often have an associated shortcut key, also known as a keyboard accelerator. Some menu items may have both an access key and a shortcut key, and some may have only one. For example, a menu item called <u>N</u>ew has an access key N and a shortcut key CTRL+N. The menu does not have to be active for the shortcut key to work.
     * 
     * <b>Note to client developers:  </b><p class="note">If this property returns a single character, you cannot assume it is an access key or a keyboard shortcut. With standard menu items, the access key is returned by <b>IAccessible::get_accKeyboardShortcut</b>, and the shortcut key is returned as part of the menu item name returned from <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-get_accname">IAccessible::get_accName</a>. In general, access keys tend to be defined as ALT + &lt;letter&gt;, and keyboard shortcuts tend to be CTRL + &lt;letter&gt;.
     * 
     * 
     * 
     * <b>Note to server developers:  </b>If the UI element can receive keyboard focus, then you should expose the access key for the element. If the UI element cannot receive keyboard focus (such as toolbar icons), then you should display the shortcut key.
     * 
     * Because shortcut keys are usually determined by the application rather than by the control itself, servers can usually return the value obtained from the standard accessible object for the window.
     * 
     * 
     * 
     * <h3><a id="Client_Example"></a><a id="client_example"></a><a id="CLIENT_EXAMPLE"></a>Client Example</h3>
     * The following example function retrieves the keyboard shortcut for the specified accessible object, or one of its children, and prints it to the console.
     * 
     * 
     * ```cpp
     * 
     * HRESULT PrintShortcut(IAccessible* pAcc, long child)
     * {
     *     if (pAcc == NULL)
     *     {
     *         return E_INVALIDARG;
     *     }
     *     BSTR bstrShortcut;
     *     VARIANT varObj;
     *     varObj.vt = VT_I4;
     *     varObj.lVal = child;
     *     HRESULT hr = pAcc->get_accKeyboardShortcut(varObj, &bstrShortcut);
     *     if (hr == S_OK)
     *     {
     *         printf("Shortcut: %S\n", bstrShortcut);
     *         SysFreeString(bstrShortcut);
     *     }
     *     return hr;
     * }
     * 
     * ```
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the retrieved keyboard shortcut belongs to the object or one of the object's child elements. This parameter is either CHILDID_SELF (to obtain information about the object) or a child ID (to obtain information about the object's child element). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {BSTR} Type: <b>BSTR*</b>
     * 
     *  Address of a <b>BSTR</b> that receives a localized string that identifies the keyboard shortcut, or <b>NULL</b> if no keyboard shortcut is associated with the specified object.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_acckeyboardshortcut
     */
    get_accKeyboardShortcut(varChild) {
        pszKeyboardShortcut := BSTR()
        result := ComCall(17, this, "ptr", varChild, "ptr", pszKeyboardShortcut, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pszKeyboardShortcut
    }

    /**
     * The IAccessible::get_accFocus method retrieves the object that has the keyboard focus. All objects that may receive the keyboard focus must support this property.
     * @remarks
     * The concept of keyboard focus is related to that of an active window. An active window is the foreground window on which the user works. The object with the keyboard focus is either the active window or a child object of the active window.
     * 
     * Only one object or item within a container has the focus at any one time. The object with the keyboard focus is not always the selected object. For more information about the difference between selection and focus, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/selection-and-focus-properties-and-methods">Selection and Focus Properties and Methods</a>.
     * 
     * This method returns either an <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch</a> interface pointer or a child ID for the <i>pvarID</i>. For more information about how to use the <b>IDispatch</b> interface pointer or child ID, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * 
     * As with other <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> methods and functions, clients might receive errors for <b>IAccessible</b> interface pointers because of a user action. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/receiving-errors-for-iaccessible-interface-pointers">Receiving Errors for IAccessible Interface Pointers</a>.
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example code shows a possible implementation of this method for a custom single-selection list box. If the control does not have the focus, VT_EMPTY is returned in the variant by the standard accessible object for the HWND. If the control does have the focus, and an item is selected, the child ID of that item is returned; if there is no selection, CHILDID_SELF is returned.
     * 
     * 
     * ```cpp
     * 
     * // m_pControl is the control object that is served by this implementation. 
     * // m_pStdAccessibleObject is the object returned by CreateStdAccessibleObject. 
     * 
     * HRESULT STDMETHODCALLTYPE AccServer::get_accFocus(VARIANT *pvarChild)
     * {
     *     FAIL_IF_NO_CONTROL;  // Macro that checks for existence of control. 
     * 
     *     HRESULT hr = m_pStdAccessibleObject->get_accFocus(pvarChild);  
     *     if (pvarChild->vt != VT_I4)
     *     {
     *         return hr;
     *     }
     *     else
     *     {
     *         int index = m_pControl->GetSelectedIndex();
     *         if (index <0)
     *         {
     *             pvarChild->lVal = CHILDID_SELF;
     *         }
     *         else
     *         {
     *             // Convert to 1-based index for child ID. 
     *             pvarChild->lVal = index + 1;
     *         }
     *     }
     *     return S_OK;
     * };
     * 
     * 
     * ```
     * @returns {VARIANT} Type: <b>VARIANT*</b>
     * 
     * Address of a <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT structure</a> that receives information about the object that has the focus. The following table describes the information returned in <i>pvarID</i>.
     * 
     * <table>
     * <tr>
     * <th>Value</th>
     * <th>Meaning</th>
     * </tr>
     * <tr>
     * <td width="40%"><a id="VT_EMPTY"></a><a id="vt_empty"></a><dl>
     * <dt><b>VT_EMPTY</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * None. Neither this object nor any of its children has the keyboard focus.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="VT_I4"></a><a id="vt_i4"></a><dl>
     * <dt><b>VT_I4</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * <b>lVal</b> is CHILDID_SELF. The object itself has the keyboard focus.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="VT_I4"></a><a id="vt_i4"></a><dl>
     * <dt><b>VT_I4</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * <b>lVal</b> contains the child ID of the child element that has the keyboard focus.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="VT_DISPATCH"></a><a id="vt_dispatch"></a><dl>
     * <dt><b>VT_DISPATCH</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * <b>pdispVal</b> member is the address of the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch interface</a> for the child object that has the keyboard focus.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_accfocus
     */
    get_accFocus() {
        pvarChild := VARIANT()
        result := ComCall(18, this, "ptr", pvarChild, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pvarChild
    }

    /**
     * The IAccessible::get_accSelection method retrieves the selected children of this object. All objects that support selection must support this property.
     * @remarks
     * This method must support the <a href="https://docs.microsoft.com/windows/win32/api/oaidl/nn-oaidl-ienumvariant">IEnumVARIANT</a> interface.
     * 
     * This method returns either an <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch</a> interface pointer or a child ID for the <i>pvarChildren</i> parameter. For more information about how to use the <b>IDispatch</b> interface pointer or child ID, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * 
     * As with other <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> methods and functions, clients might receive errors for <b>IAccessible</b> interface pointers because of a user action. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/receiving-errors-for-iaccessible-interface-pointers">Receiving Errors for IAccessible Interface Pointers</a>.
     * 
     * <b>Note:  </b>This method retrieves a selected item, not selected text.
     *             
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example code shows a possible implementation of this method for a custom single-selection list box. Its  <b>GetSelectedIndex</b> method returns -1 if no item is selected.
     * 
     * 
     * ```cpp
     * 
     * // m_pControl is the control that returns this accessible object. 
     * 
     * HRESULT STDMETHODCALLTYPE AccServer::get_accSelection(VARIANT *pvarChildren)
     * {
     *     int childID = m_pControl->GetSelectedIndex() + 1; // Convert from 0-based. 
     *     if (childID <= 0)
     *     {
     *         pvarChildren->vt = VT_EMPTY;
     *     }
     *     else 
     *     {
     *         pvarChildren->vt = VT_I4;
     *         pvarChildren->lVal = childID;
     *     }
     *     return S_OK;
     * };
     * 
     * 
     * 
     * 
     * ```
     * @returns {VARIANT} Type: <b>VARIANT*</b>
     * 
     * Address of a <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT structure</a> that receives information about which children are selected. The following table describes the information returned in <i>pvarChildren</i>.
     * 
     * <table>
     * <tr>
     * <th>vt member</th>
     * <th>Value member</th>
     * </tr>
     * <tr>
     * <td width="40%"><a id="VT_EMPTY"></a><a id="vt_empty"></a><dl>
     * <dt><b>VT_EMPTY</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * No children are selected.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="VT_DISPATCH"></a><a id="vt_dispatch"></a><dl>
     * <dt><b>VT_DISPATCH</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * One child object is selected, and the address of its <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch</a> interface is set in the <b>pdispVal</b> member.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="VT_I4"></a><a id="vt_i4"></a><dl>
     * <dt><b>VT_I4</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * <b>lVal</b> contains the child ID of the child element that is selected. If <b>lVal</b> is CHILDID_SELF, this means that the object itself is selected.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="VT_UNKNOWN"></a><a id="vt_unknown"></a><dl>
     * <dt><b>VT_UNKNOWN</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * Multiple child objects are selected, and the <b>punkVal</b> member contains the address of the <a href="https://docs.microsoft.com/windows/desktop/api/unknwn/nn-unknwn-iunknown">IUnknown</a> interface. The client queries this interface for the <a href="https://docs.microsoft.com/windows/win32/api/oaidl/nn-oaidl-ienumvariant">IEnumVARIANT</a> interface, which it uses to enumerate the selected objects.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_accselection
     */
    get_accSelection() {
        pvarChildren := VARIANT()
        result := ComCall(19, this, "ptr", pvarChildren, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pvarChildren
    }

    /**
     * The IAccessible::get_accDefaultAction method retrieves a string that indicates the object's default action. Not all objects have a default action.
     * @remarks
     * The retrieved string describes the action that is performed on an object, not what the object does as a result. For example, a toolbar button that prints a document has a default action of "Press" rather than "Prints the current document."
     * 
     * Do not confuse an object's default action with its value. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/defaultaction-property">DefaultAction Property</a>.
     * 
     * Only controls that perform actions support this method.
     * 
     * <b>Note to server developers:  </b>Localize the string returned from this property.
     *             
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example code shows a possible implementation of this method for a custom list box. For simplicity, the strings are not localized.
     * 
     * 
     * ```cpp
     * 
     * HRESULT STDMETHODCALLTYPE AccServer::get_accDefaultAction( 
     *     VARIANT varChild,
     *     BSTR *pszDefaultAction)
     * {
     *     if (varChild.vt != VT_I4)
     *     {
     *         *pszDefaultAction = NULL;
     *         return E_INVALIDARG;
     *     }
     *     if (varChild.lVal == CHILDID_SELF)
     *     {
     *         *pszDefaultAction = SysAllocString(L"None.");
     *     }
     *     else
     *     {
     *         *pszDefaultAction = SysAllocString(L"Double-click");
     *     }
     *     return S_OK;
     * };
     * 
     * ```
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the retrieved default action is performed by the object or of one of the object's child elements. This parameter is either CHILDID_SELF (to obtain information about the object) or a child ID (to obtain information about the object's child element). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT structure</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {BSTR} Type: <b>BSTR*</b>
     * 
     * Address of a <b>BSTR</b> that receives a localized string that describes the default action for the specified object; if this object has no default action, the value is <b>NULL</b>.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-get_accdefaultaction
     */
    get_accDefaultAction(varChild) {
        pszDefaultAction := BSTR()
        result := ComCall(20, this, "ptr", varChild, "ptr", pszDefaultAction, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pszDefaultAction
    }

    /**
     * The IAccessible::accSelect method modifies the selection or moves the keyboard focus of the specified object. All objects that support selection or receive the keyboard focus must support this method.
     * @remarks
     * Client applications use this method to perform complex selection operations. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/selecting-child-objects">Selecting Child Objects</a>. This method provides the simplest way to programmatically switch the input focus between applications. This applies to applications running on Windows 2000.
     * 
     * <b>Note:  </b>This method is for the selection of items, not text.
     *             
     * 
     * <h3><a id="Client_Example"></a><a id="client_example"></a><a id="CLIENT_EXAMPLE"></a>Client Example</h3>
     * The following example function selects the item at a specified point on the screen. It is assumed that a single selection is wanted.
     * 
     * 
     * ```cpp
     * 
     * HRESULT SelectItemAtPoint(POINT point)
     * {
     *     VARIANT varItem;
     *     IAccessible* pAcc;
     *     HRESULT hr = AccessibleObjectFromPoint(point, &pAcc, &varItem);
     *     if ((hr == S_OK))
     *     {
     *         hr = pAcc->accSelect((SELFLAG_TAKEFOCUS | SELFLAG_TAKESELECTION), varItem);
     *         VariantClear(&varItem);
     *         pAcc->Release();
     *     }
     *     return hr;
     * }
     * 
     * ```
     * @param {Integer} flagsSelect Type: <b>long</b>
     * 
     * Specifies which selection or focus operations are to be performed. This parameter must have a combination of the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/selflag">SELFLAG Constants</a>.
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies the selected object. If the value is CHILDID_SELF, the object itself is selected; if a child ID, one of the object's child elements is selected. For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT structure</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {HRESULT} Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">HRESULT</a></b>
     * 
     * If successful, returns S_OK.
     * 
     * If not successful, returns one of the values in the table that follows, or another standard <a href="https://docs.microsoft.com/windows/desktop/WinAuto/return-values">COM error code</a>.
     * 
     * <table>
     * <tr>
     * <th>Error</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>S_FALSE</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The specified object is not selected.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_INVALIDARG</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * An argument is not valid. This return value means that the specified SELFLAG combination is not valid, or that the SELFLAG value does not make sense for the specified object. For example, the following flags are not allowed on a single-selection list box: <a href="https://docs.microsoft.com/windows/desktop/WinAuto/selflag">SELFLAG_EXTENDSELECTION</a>, <a href="https://docs.microsoft.com/windows/desktop/WinAuto/selflag">SELFLAG_ADDSELECTION</a>, and <a href="https://docs.microsoft.com/windows/desktop/WinAuto/selflag">SELFLAG_REMOVESELECTION</a>.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>DISP_E_MEMBERNOTFOUND</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The object does not support this method.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-accselect
     */
    accSelect(flagsSelect, varChild) {
        result := ComCall(21, this, "int", flagsSelect, "ptr", varChild, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return result
    }

    /**
     * The IAccessible::accLocation method retrieves the specified object's current screen location. All visual objects must support this method. Sound objects do not support this method.
     * @remarks
     * This method retrieves the object's bounding rectangle. If the object has a non-rectangular shape, then this method returns the smallest rectangle that completely encompasses the entire object region. For non-rectangular objects, the coordinates of the object's bounding rectangle could fail if tested with <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-acchittest">IAccessible::accHitTest</a>. Examples of such non-rectangular objects are list view items in large-icon mode where a single item has a rectangle for the icon and another rectangle for the text of the icon. Because <b>accLocation</b> returns a bounding rectangle, not all points in that rectangle will be within the actual bounds of the object. Some points within the bounding rectangle may not be on the object. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/navigation-through-hit-testing-and-screen-location">Navigation Through Hit Testing and Screen Location</a>.
     * 
     * <b>Note:  </b>This method returns width and height. If you want the right and bottom coordinates, calculate them using right = left + width, and bottom = top + height.
     * 
     * 
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example shows a possible implementation of the method for a custom list box whose list items are child elements. For the list box itself, the call is passed to the standard accessible object, which returns the screen coordinates of the window.
     * 
     * 
     * ```cpp
     * 
     * // m_pStdAccessibleObject is the standard accessible object for the control window. 
     * // m_pControl is the object that represents the control. Its GetItemRect method  
     * //   retrieves the screen coordinates of the specified item in a zero-based collection. 
     * // 
     * HRESULT STDMETHODCALLTYPE AccServer::accLocation( 
     *     long *pxLeft,
     *     long *pyTop,
     *     long *pcxWidth,
     *     long *pcyHeight,
     *     VARIANT varChild)
     * {
     *     *pxLeft = 0;
     *     *pyTop = 0;
     *     *pcxWidth = 0;
     *     *pcyHeight = 0;
     *     if (varChild.vt != VT_I4)
     *     {
     *         return E_INVALIDARG;
     *     }
     *     if (varChild.lVal == CHILDID_SELF)
     *     {
     *         return m_pStdAccessibleObject->accLocation(pxLeft, pyTop, pcxWidth, pcyHeight, varChild);
     *     }
     *     else
     *     {
     *         RECT rect;
     *         if (m_pControl->GetItemRect(varChild.lVal - 1, &rect) == FALSE)
     *         {
     *             return E_INVALIDARG;
     *         }
     *         else
     *         {
     *             *pxLeft = rect.left;
     *             *pyTop = rect.top;
     *             *pcxWidth = rect.right - rect.left;
     *             *pcyHeight = rect.bottom - rect.top;
     *             return S_OK;        
     *         }
     *     }
     * };
     * 
     * ```
     * @param {Pointer<Integer>} pxLeft Type: <b>long*</b>
     * 
     * Address, in physical screen coordinates, of the variable that receives the x-coordinate of the upper-left boundary of the object's location.
     * @param {Pointer<Integer>} pyTop Type: <b>long*</b>
     * 
     * Address, in physical screen coordinates, of the variable that receives the y-coordinate of the upper-left boundary of the object's location.
     * @param {Pointer<Integer>} pcxWidth Type: <b>long*</b>
     * 
     * Address, in pixels, of the variable that receives the object's width.
     * @param {Pointer<Integer>} pcyHeight Type: <b>long*</b>
     * 
     * Address, in pixels, of the variable that receives the object's height.
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the location that the server returns should be that of the object or that of one of the object's child elements. This parameter is either CHILDID_SELF (to obtain information about the object) or a child ID (to obtain information about the object's child element). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT structure</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {HRESULT} Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">HRESULT</a></b>
     * 
     * If successful, returns S_OK. Clients must always check that output parameters contain valid values.
     * 
     * If not successful, returns one of the values in the table that follows, or another standard <a href="https://docs.microsoft.com/windows/desktop/WinAuto/return-values">COM error code</a>. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/checking-iaccessible-return-values">Checking IAccessible Return Values</a>.
     * 
     * <table>
     * <tr>
     * <th>Error</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>DISP_E_MEMBERNOTFOUND</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The object does not support this method.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_INVALIDARG</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * An argument is not valid.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-acclocation
     */
    accLocation(pxLeft, pyTop, pcxWidth, pcyHeight, varChild) {
        pxLeftMarshal := pxLeft is VarRef ? "int*" : "ptr"
        pyTopMarshal := pyTop is VarRef ? "int*" : "ptr"
        pcxWidthMarshal := pcxWidth is VarRef ? "int*" : "ptr"
        pcyHeightMarshal := pcyHeight is VarRef ? "int*" : "ptr"

        result := ComCall(22, this, pxLeftMarshal, pxLeft, pyTopMarshal, pyTop, pcxWidthMarshal, pcxWidth, pcyHeightMarshal, pcyHeight, "ptr", varChild, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return result
    }

    /**
     * The IAccessible::accNavigate method traverses to another UI element within a container and retrieves the object. This method is optional.
     * @remarks
     * Navigation, both spatial and logical, is always restricted to the UI elements within a container. With spatial navigation, clients navigate only to a sibling of the starting object (<i>varStart</i>). Depending on the navigational flag used with logical navigation, clients navigate to either a child or to a sibling of the starting object.
     * 
     * The <b>accNavigate</b> method retrieves UI elements that have a defined screen location, and invisible objects that do not have a defined screen location.
     * 
     * This method does not change the selection or focus. To change the focus or to select an object, use <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-accselect">IAccessible::accSelect</a>.
     * 
     * To prevent looping when traversing screen elements, <b>accNavigate</b> returns S_FALSE with VT_EMPTY when you specify <a href="https://docs.microsoft.com/windows/desktop/WinAuto/navigation-constants">NAVDIR_NEXT</a> on the last element, or <a href="https://docs.microsoft.com/windows/desktop/WinAuto/navigation-constants">NAVDIR_PREVIOUS</a> on the first element.
     * 
     * As with other <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> methods and functions, clients might receive errors for <b>IAccessible</b> interface pointers because of a user action. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/receiving-errors-for-iaccessible-interface-pointers">Receiving Errors for IAccessible Interface Pointers</a>.
     * 
     * Some system-defined UI elements such as menus, menu items, and pop-up menus allow navigation to invisible objects. However, other system-defined UI elements do not support this. Servers can choose whether to support navigating to invisible objects and can either skip over or expose them.
     * 
     * Client applications must return post-process return values when using <b>accNavigate</b> to navigate between objects. The goal of the post-processing steps is to give clients an <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> interface pointer and a child ID so that they can use the <b>IAccessible</b> methods and properties for a UI element.
     * 
     * The following tables describe possible scenarios for <b>IAccessible::accNavigate</b>, based on the following criteria:
     * 
     * <ul>
     * <li>A defined starting point (whether you are starting with a full object or a simple element)</li>
     * <li> 
     * The result returned (an <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch</a> or a VT_I4 child ID)</li>
     * <li> 
     * The post-processing that client applications will need to perform to have an <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> interface pointer and a child ID </li>
     * </ul>
     * For these tables, assume that <i>startID</i> and <i>endID</i> are VT_I4 child IDs (simple elements), and <i>pStartAcc</i> and <i>pEndAcc</i> are VT_I4 with CHILDID_SELF (full objects).
     * 
     * This table describes the following NAVDIR_ flags: NEXT, PREVIOUS, LEFT, RIGHT, UP, and DOWN. For more information about navigation flags, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/navigation-constants">Navigation Constants</a>.
     * 
     * <table>
     * <tr>
     * <th>Starting point</th>
     * <th>Result returned</th>
     * <th>Post-processing for the return value</th>
     * </tr>
     * <tr>
     * <td><i>pStartAcc, startID</i></td>
     * <td>VT_I4 <i>endID</i></td>
     * <td>Call <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-get_accchild">get_accChild</a> on <i>pStartAcc</i> passing <i>endID</i>. Follow normal procedures outlined in <b>get_accChild</b>.</td>
     * </tr>
     * <tr>
     * <td><i>pStartAcc, startID</i></td>
     * <td>VT_DISPATCH <i>pEndAcc</i></td>
     * <td> Use the standard procedures for converting an <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch</a> interface pointer to an <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> interface pointer for <i>pEndAcc</i>.  </td>
     * </tr>
     * <tr>
     * <td><i>pStartAcc</i>, CHILDID_SELF</td>
     * <td>VT_I4 <i>endID</i></td>
     * <td>Call <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-get_accparent">get_accParent</a> on <i>pStartAcc</i>, passing CHILDID_SELF to get the <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> interface pointer of the parent for <i>endID</i>. 
     * Then, call <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-get_accchild">get_accChild</a> on that <b>IAccessible</b> interface pointer, passing <i>endID</i>. Follow normal procedures outlined in <b>get_accChild</b>.</td>
     * </tr>
     * <tr>
     * <td><i>pStartAcc</i>, CHILDID_SELF</td>
     * <td>VT_DISPATCH <i>pEndAcc</i></td>
     * <td>Use the standard procedures for converting an <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch</a> interface pointer to an <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> interface pointer for <i>pEndAcc</i>.</td>
     * </tr>
     * </table>
     *  
     * 
     * The following table describes navigation flags <a href="https://docs.microsoft.com/windows/desktop/WinAuto/navigation-constants">NAVDIR_FIRSTCHILD</a> and <a href="https://docs.microsoft.com/windows/desktop/WinAuto/navigation-constants">NAVDIR_LASTCHILD</a>. It does not include entries for navigating to a first or last child when the starting point is a simple element because simple elements cannot have children.
     * 
     * <table>
     * <tr>
     * <th>Starting point</th>
     * <th>Result returned</th>
     * <th>Post-processing for the return value</th>
     * </tr>
     * <tr>
     * <td><i>pStartAcc</i>, CHILDID_SELF</td>
     * <td>VT_I4 <i>endID</i></td>
     * <td>Call <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-get_accchild">get_accChild</a> on <i>pStartAcc</i>, passing endID. Follow normal procedures outlined in <b>get_accChild</b>. </td>
     * </tr>
     * <tr>
     * <td><i>pStartAcc</i>, CHILDID_SELF</td>
     * <td>VT_DISPATCH <i>pEndAcc</i></td>
     * <td>Use the standard procedures for converting an <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch</a> interface pointer to an <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> interface pointer for <i>pEndAcc</i>.</td>
     * </tr>
     * </table>
     *  
     * 
     * For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/object-navigation-properties-and-methods">Object Navigation Properties and Methods</a>.
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example shows a possible implementation of the method for a custom list box whose list items are child elements.
     * 
     * 
     * ```cpp
     * 
     * // m_pControl is the control that returns this accessible object. 
     * // m_pStdAccessibleObject is the standard accessible object for the window 
     * //    that contains the control. 
     * 
     * HRESULT STDMETHODCALLTYPE AccServer::accNavigate( 
     *     long navDir,
     *     VARIANT varStart,
     *     VARIANT *pvarEndUpAt)
     * {
     *     // Default value. 
     *     pvarEndUpAt->vt = VT_EMPTY;
     * 
     *     if (varStart.vt != VT_I4)
     *     {
     *         return E_INVALIDARG;
     *     }
     * 
     *     switch (navDir)
     *     {
     *     case NAVDIR_FIRSTCHILD:
     *         if (varStart.lVal == CHILDID_SELF)
     *         {
     *             pvarEndUpAt->vt = VT_I4;
     *             pvarEndUpAt->lVal = 1;
     *         }
     *         else  // Starting with child. 
     *         {
     *             return S_FALSE;
     *         }
     *         break;
     * 
     *     case NAVDIR_LASTCHILD:
     *         if (varStart.lVal == CHILDID_SELF)
     *         {
     *             pvarEndUpAt->vt = VT_I4;
     *             pvarEndUpAt->lVal = m_pControl->GetCount();
     *         }
     *         else  // Starting with child.           
     *         {
     *             return S_FALSE;
     *         }
     *         break;
     * 
     *     case NAVDIR_NEXT:   
     *     case NAVDIR_DOWN:
     *         if (varStart.lVal != CHILDID_SELF)
     *         {
     *             pvarEndUpAt->vt = VT_I4;
     *             pvarEndUpAt->lVal = varStart.lVal + 1;
     *             // Out of range. 
     *             if (pvarEndUpAt->lVal > m_pControl->GetCount())
     *             {
     *                 pvarEndUpAt->vt = VT_EMPTY;
     *                 return S_FALSE;
     *             }
     *         }
     *         else  // Call through to method on standard object. 
     *         {
     *             return m_pStdAccessibleObject->accNavigate(navDir, varStart, pvarEndUpAt);
     *         }
     *         break;
     * 
     *     case NAVDIR_PREVIOUS:
     *     case NAVDIR_UP:
     *         if (varStart.lVal != CHILDID_SELF)
     *         {
     *             pvarEndUpAt->vt = VT_I4;
     *             pvarEndUpAt->lVal = varStart.lVal - 1;
     *             // Out of range. 
     *             if (pvarEndUpAt->lVal <1)
     *             {
     *                 pvarEndUpAt->vt = VT_EMPTY;
     *                 return S_FALSE;
     *             }
     *         }
     *         else  // Call through to method on standard object. 
     *         {
     *             return m_pStdAccessibleObject->accNavigate(navDir, varStart, pvarEndUpAt);
     *         }
     *         break;
     * 
     *      // Unsupported directions. 
     *     case NAVDIR_LEFT:
     *     case NAVDIR_RIGHT:
     *         if (varStart.lVal == CHILDID_SELF)
     *         {
     *             return m_pStdAccessibleObject->accNavigate(navDir, varStart, pvarEndUpAt);
     *         }
     *         else 
     *         {
     *             pvarEndUpAt->vt = VT_EMPTY;
     *             return S_FALSE;
     *         }
     *         break;
     *     }
     *     return S_OK;
     * };
     * 
     * 
     * ```
     * @param {Integer} navDir Type: <b>long</b>
     * 
     * Specifies the direction to navigate. This direction is in <i>spatial</i> order, such as left or right, or <i>logical</i> order, such as next or previous. This value is one of the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/navigation-constants">navigation constants</a>.
     * @param {VARIANT} varStart Type: <b>VARIANT</b>
     * 
     * Specifies whether the starting object of the navigation is the object itself or one of the object's children. This parameter is either CHILDID_SELF (to start from the object) or a child ID (to start from one of the object's child elements). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {VARIANT} Type: <b>VARIANT*</b>
     * 
     * [out, retval] Address of a <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT</a> structure that receives information about the destination object. The following table describes the information that is returned in <i>pvarEnd</i>.
     * 
     * <table>
     * <tr>
     * <th>vt member</th>
     * <th>Value member</th>
     * </tr>
     * <tr>
     * <td width="40%"><a id="VT_EMPTY"></a><a id="vt_empty"></a><dl>
     * <dt><b>VT_EMPTY</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * None. There was no UI element in the specified direction.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="VT_I4"></a><a id="vt_i4"></a><dl>
     * <dt><b>VT_I4</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * <b>lVal</b> contains the child ID of the UI element.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%"><a id="VT_DISPATCH"></a><a id="vt_dispatch"></a><dl>
     * <dt><b>VT_DISPATCH</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * <b>pdispVal</b> contains the address of the UI element's <a href="https://docs.microsoft.com/windows/desktop/WinAuto/idispatch-interface">IDispatch</a>.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-accnavigate
     */
    accNavigate(navDir, varStart) {
        pvarEndUpAt := VARIANT()
        result := ComCall(23, this, "int", navDir, "ptr", varStart, "ptr", pvarEndUpAt, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pvarEndUpAt
    }

    /**
     * The IAccessible::accHitTest method retrieves the child element or child object that is displayed at a specific point on the screen.
     * @remarks
     * If the tested point is on one of the object's children, and this child supports the <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> interface itself, this method should return an <b>IAccessible</b> interface pointer. However, clients should be prepared to handle an <b>IAccessible</b> interface pointer or a child ID. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * 
     * Because <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-acclocation">accLocation</a> returns a bounding rectangle, not all points in that rectangle will be within the actual bounds of the object. Some points within the bounding rectangle may not be on the object. For non-rectangular objects, such as list view items in large-icon mode where a single item has a rectangle for the icon and another rectangle for the text of the icon, the coordinates of the object's bounding rectangle retrieved by <b>IAccessible::accLocation</b> could fail if tested with <b>accHitTest</b> .
     * 
     * As with other <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nn-oleacc-iaccessible">IAccessible</a> methods and functions, clients might receive errors for <b>IAccessible</b> interface pointers because of a user action. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/receiving-errors-for-iaccessible-interface-pointers">Receiving Errors for IAccessible Interface Pointers</a>.
     * 
     * When this method is used in certain situations, additional usage notes apply. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/navigation-through-hit-testing-and-screen-location">Navigation Through Hit Testing and Screen Location</a>.
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example code shows a possible implementation for a custom list box.
     * 
     * 
     * ```cpp
     * 
     * // m_pControl is the control that returns this accessible object. 
     * // m_hwnd is the HWND of the control window. 
     * //  
     * HRESULT STDMETHODCALLTYPE AccServer::accHitTest( 
     *     long xLeft,
     *     long yTop,
     *     VARIANT *pvarChild) 
     * 
     * {
     *     POINT pt;
     *     pt.x = xLeft;
     *     pt.y = yTop;
     * 
     *     // Not in our window. 
     *     if (WindowFromPoint(pt) != m_hwnd)
     *     {
     *         pvarChild->vt = VT_EMPTY;
     *         return S_FALSE;
     *     }
     * 
     *     else  // In our window; return list item, or self if in blank space. 
     *     {
     *         pvarChild->vt = VT_I4;
     *         ScreenToClient(m_hwnd, &pt);
     *         // IndexFromY returns the 0-based index of the item at that point, 
     *         // or -1 if the point is not on any item.
     *         int index = m_pControl->IndexFromY(pt.y);
     *         if (index >= 0)
     *         {
     *             // Increment, because the child array is 1-based. 
     *             pvarChild->lVal = index + 1;
     *         }
     *         else
     *         {
     *             pvarChild->lVal = CHILDID_SELF;
     * 
     *         }
     *         return S_OK;
     *     }
     * };
     * 
     * ```
     * 
     * 
     * <h3><a id="Client_Example"></a><a id="client_example"></a><a id="CLIENT_EXAMPLE"></a>Client Example</h3>
     * The following example function selects the item at a specified point on the screen within the list represented by <i>pAcc</i>. It is assumed that a single selection is wanted.
     * 
     * 
     * ```cpp
     * 
     * HRESULT SelectItemAtPoint(IAccessible* pAcc, POINT point)
     * {
     *     if (pAcc == NULL)
     *     {
     *         return E_INVALIDARG;
     *     }
     *     VARIANT varChild;
     * 
     *     HRESULT hr = pAcc->accHitTest(point.x, point.y, &varChild);        
     *     if ((hr == S_OK) && (varChild.lVal != CHILDID_SELF))
     *     {
     *         return pAcc->accSelect((SELFLAG_TAKEFOCUS | SELFLAG_TAKESELECTION), varChild);
     *     }
     *     return S_FALSE;
     * }
     * 
     * ```
     * @param {Integer} xLeft Type: <b>long</b>
     * 
     * Specifies the screen coordinates of the point that is hit tested. The x-coordinates increase from left to right. Note that when screen coordinates are used, the origin is the upper-left corner of the screen.
     * @param {Integer} yTop Type: <b>long</b>
     * 
     * Specifies the screen coordinates of the point that is hit tested. The y-coordinates increase from top to bottom. Note that when screen coordinates are used, the origin is the upper-left corner of the screen.
     * @returns {VARIANT} Type: <b>VARIANT*</b>
     * 
     * [out, retval] Address of a <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT</a> that identifies the object displayed at the point specified by <i>xLeft</i> and <i>yTop</i>. The information returned in <i>pvarID</i> depends on the location of the specified point in relation to the object whose <b>accHitTest</b> method is being called.
     * 
     * <table>
     * <tr>
     * <th>Point location</th>
     * <th>vt member</th>
     * <th>Value member</th>
     * </tr>
     * <tr>
     * <td>Outside of the object's boundaries, and either inside or outside of the object's bounding rectangle.</td>
     * <td>VT_EMPTY</td>
     * <td>None.</td>
     * </tr>
     * <tr>
     * <td>Within the object but not within a child element or a child object.</td>
     * <td>VT_I4</td>
     * <td><b>lVal</b> is CHILDID_SELF.</td>
     * </tr>
     * <tr>
     * <td>Within a child element.</td>
     * <td>VT_I4</td>
     * <td><b>lVal</b> contains the child ID.</td>
     * </tr>
     * <tr>
     * <td>Within a child object.</td>
     * <td>VT_DISPATCH</td>
     * <td><i>pdispVal</i> is set to the child object's <a href="https://docs.microsoft.com/windows/win32/api/oaidl/nn-oaidl-idispatch">IDispatch</a> interface pointer</td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-acchittest
     */
    accHitTest(xLeft, yTop) {
        pvarChild := VARIANT()
        result := ComCall(24, this, "int", xLeft, "int", yTop, "ptr", pvarChild, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return pvarChild
    }

    /**
     * The IAccessible::accDoDefaultAction method performs the specified object's default action. Not all objects have a default action.
     * @remarks
     * Clients retrieve a string that describes the object's default action by calling <b>IAccessible::get_accDefaultAction</b>.
     * 
     * <b>Note to client developers:  </b>When used on a menu item in a standard system menu, <b>accDoDefaultAction</b> returns S_OK but fails to perform the action if the character used in the access key (the underlined character in the text of a menu item name, also called a mnemonic) is ?, !, @, or any other character that requires the SHIFT key or another modifier key. This also happens on international keyboards with an access key character that requires the ALT GR key to be pressed. This is not an issue for menus in other applications, such as Microsoft Office or Windows Internet Explorer. For more information about access keys, see <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-iaccessible-get_acckeyboardshortcut">IAccessible::get_accKeyboardShortcut</a>.
     * 
     * Also, while <b>accDoDefaultAction</b> is supposed to return immediately, some implementations block the return. For example, if clicking a link displays a dialog, some implementations will block the return until the dialog is dismissed. Such delays can prevent client applications from processing a dialog box. Servers should avoid implementations that block returns.
     * 
     * 
     * 
     * <h3><a id="Server_Example"></a><a id="server_example"></a><a id="SERVER_EXAMPLE"></a>Server Example</h3>
     * The following example shows a possible implementation for a custom list control whose default action is a double-click a child item. To prevent blocking, the method posts a custom message that, when received by the control window, triggers an action, such as displaying item properties.
     * 
     * 
     * ```cpp
     * 
     * // Assume a previous definition such as this: 
     * // #define CUSTOMLB_DEFERDOUBLECLICK   (WM_USER + 1) 
     * 
     * HRESULT STDMETHODCALLTYPE AccServer::accDoDefaultAction( 
     *     VARIANT varChild) 
     * {
     *     if (varChild.vt != VT_I4)
     *     {
     *         return E_INVALIDARG;
     *     }
     *     if (varChild.lVal != CHILDID_SELF)
     *     {
     *         // It is assumed that the control does its own checking to see which 
     *         // item has the focus when it receives this message.
     *         PostMessage(m_hwnd, CUSTOMLB_DEFERDOUBLECLICK, 0, 0);
     *     }
     *     return S_OK;
     * };
     * 
     * ```
     * 
     * 
     * <h3><a id="Client_Example"></a><a id="client_example"></a><a id="CLIENT_EXAMPLE"></a>Client Example</h3>
     * The following example function performs the default action on a control.
     * 
     * 
     * ```cpp
     * 
     * HRESULT DoAction(IAccessible* pAcc)
     * {
     *         VARIANT varId;
     *         varId.vt = VT_I4;
     *         varId.lVal = CHILDID_SELF;
     *         return pAcc->accDoDefaultAction(varId);
     * }
     * 
     * ```
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the default action belongs to the object or one of the object's child elements. For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @returns {HRESULT} Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">HRESULT</a></b>
     * 
     * If successful, returns S_OK.
     * 
     * If not successful, returns one of the values in the table that follows, or another standard <a href="https://docs.microsoft.com/windows/desktop/WinAuto/return-values">COM error code</a>.
     * 
     * <table>
     * <tr>
     * <th>Error</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>DISP_E_MEMBERNOTFOUND</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The object does not support the method. This value is returned for controls that do not perform actions, such as edit fields.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_INVALIDARG</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * An argument is not valid.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-accdodefaultaction
     */
    accDoDefaultAction(varChild) {
        result := ComCall(25, this, "ptr", varChild, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return result
    }

    /**
     * The IAccessible::put_accName method is no longer supported. Client applications should use a control-specific workaround, such as the SetWindowText function. Servers should return E_NOTIMPL.
     * @param {VARIANT} varChild Not supported.
     * @param {BSTR} szName Not supported.
     * @returns {HRESULT} Not supported.
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-put_accname
     */
    put_accName(varChild, szName) {
        if(szName is String) {
            pin := BSTR.Alloc(szName)
            szName := pin.Value
        }

        result := ComCall(26, this, "ptr", varChild, "ptr", szName, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return result
    }

    /**
     * The IAccessible::put_accValue method sets the value of the specified object. Not all objects have a value.
     * @remarks
     * The <b>IAccessible::put_accValue</b> method is supported for some UI elements (usually edit controls). For UI elements that do not support this method, control-specific methods are used instead. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/appendix-a--supported-user-interface-elements-reference">Supported User Interface Element Reference</a>.
     * @param {VARIANT} varChild Type: <b>VARIANT</b>
     * 
     * Specifies whether the value information being set belongs to the object or one of the object's child elements. This parameter is either CHILDID_SELF (to set information on the object) or a child ID (to set information about the object's child element). For more information about initializing the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/variant-structure">VARIANT structure</a>, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/how-child-ids-are-used-in-parameters">How Child IDs Are Used in Parameters</a>.
     * @param {BSTR} szValue Type: <b>BSTR</b>
     * 
     * A localized string that contains the object's value.
     * @returns {HRESULT} Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">HRESULT</a></b>
     * 
     * If successful, returns S_OK.
     * 
     * If not successful, returns one of the values in the table that follows, or another standard <a href="https://docs.microsoft.com/windows/desktop/WinAuto/return-values">COM error code</a>. Servers return these values, but clients must always check output parameters to ensure that they contain valid values. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/checking-iaccessible-return-values">Checking IAccessible Return Values</a>.
     * 
     * <table>
     * <tr>
     * <th>Error</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>DISP_E_MEMBERNOTFOUND</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The object does not support this property.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_INVALIDARG</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * An argument is not valid.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api//content/oleacc/nf-oleacc-iaccessible-put_accvalue
     */
    put_accValue(varChild, szValue) {
        if(szValue is String) {
            pin := BSTR.Alloc(szValue)
            szValue := pin.Value
        }

        result := ComCall(27, this, "ptr", varChild, "ptr", szValue, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return result
    }
}
