#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\HWINEVENTHOOK.ahk" { HWINEVENTHOOK }
#Import "..\..\Foundation\HWND.ahk" { HWND }

/**
 * An application-defined callback (or hook) function that the system calls in response to events generated by an accessible object.
 * @remarks
 * Within the hook function, the parameters <i>hwnd</i>, <i>idObject</i>, and <i>idChild</i> are used when calling <a href="https://docs.microsoft.com/windows/desktop/api/oleacc/nf-oleacc-accessibleobjectfromevent">AccessibleObjectFromEvent</a>.
 * 
 * Servers generate events by calling <a href="https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-notifywinevent">NotifyWinEvent</a>.
 * 
 * Create multiple callback functions to handle different events. For more information, see <a href="https://docs.microsoft.com/windows/desktop/WinAuto/registering-a-hook-function">Registering a Hook Function</a>.
 * @see https://learn.microsoft.com/windows/win32/api/winuser/nc-winuser-wineventproc
 * @namespace Windows.Win32.UI.Accessibility
 */
export default struct WINEVENTPROC {
    value : IntPtr

    __value {
        set {
            if (value is WINEVENTPROC) {
                this.value := value.value
            }
            else {
                this.value := value
            }
        }
    }

    /**
     * 
     * @param {HWINEVENTHOOK} _hWinEventHook Type: <b>HWINEVENTHOOK</b>
     * 
     * Handle to an event hook function. This value is returned by <a href="https://docs.microsoft.com/windows/desktop/api/winuser/nf-winuser-setwineventhook">SetWinEventHook</a> when the hook function is installed and is specific to each instance of the hook function.
     * @param {Integer} event Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">DWORD</a></b>
     * 
     * Specifies the event that occurred. This value is one of the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/event-constants">event constants</a>.
     * @param {HWND} _hwnd Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">HWND</a></b>
     * 
     * Handle to the window that generates the event, or <b>NULL</b> if no window is associated with the event. For example, the mouse pointer is not associated with a window.
     * @param {Integer} idObject Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">LONG</a></b>
     * 
     * Identifies the object associated with the event. This is one of the <a href="https://docs.microsoft.com/windows/desktop/WinAuto/object-identifiers">object identifiers</a> or a custom object ID.
     * @param {Integer} idChild Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">LONG</a></b>
     * 
     * Identifies whether the event was triggered by an object or a child element of the object. If this value is CHILDID_SELF, the event was triggered by the object; otherwise, this value is the child ID of the element that triggered the event.
     * @param {Integer} idEventThread 
     * @param {Integer} dwmsEventTime Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">DWORD</a></b>
     * 
     * Specifies the time, in milliseconds, that the event was generated.
     * @returns {String} Nothing - always returns an empty string
     */
    Call(_hWinEventHook, event, _hwnd, idObject, idChild, idEventThread, dwmsEventTime) {
        DllCall(this.value, HWINEVENTHOOK, _hWinEventHook, UInt32, event, HWND, _hwnd, Int32, idObject, Int32, idChild, UInt32, idEventThread, UInt32, dwmsEventTime)
    }

    /**
     * A WINEVENTPROC that invokes the given AHK function when called.
     * This callback is owned by the script and cleaned up automatically.
     */
    struct From extends WINEVENTPROC {
        /**
         * Creates a WINEVENTPROC pointer that invokes the given AHK function when called.
         * @param {Func(HWINEVENTHOOK, UInt32, HWND, Int32, Int32, UInt32, UInt32) => IntPtr} fn the function to invoke.
         */
        __New(fn) {
            if (!HasMethod(fn, , 7)) {
                throw MethodError("Object of type " Type(fn) " is not callable with 7 parameters.", -1, fn)
            }
            this.value := CallbackCreate(fn, , [HWINEVENTHOOK, UInt32, HWND, Int32, Int32, UInt32, UInt32, IntPtr])
        }

        __Delete() {
            if (this.value) {
                CallbackFree(this.value)
            }
        }
    }
}
