#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Constants.ahk" {*}
#Import export ".\FindSimilarFileIndexResults.ahk" {FindSimilarFileIndexResults}
#Import export ".\FindSimilarResults.ahk" {FindSimilarResults}
#Import export ".\GeneratorParametersType.ahk" {GeneratorParametersType}
#Import export ".\IFindSimilarResults.ahk" {IFindSimilarResults}
#Import export ".\IRdcComparator.ahk" {IRdcComparator}
#Import export ".\IRdcFileReader.ahk" {IRdcFileReader}
#Import export ".\IRdcFileWriter.ahk" {IRdcFileWriter}
#Import export ".\IRdcGenerator.ahk" {IRdcGenerator}
#Import export ".\IRdcGeneratorFilterMaxParameters.ahk" {IRdcGeneratorFilterMaxParameters}
#Import export ".\IRdcGeneratorParameters.ahk" {IRdcGeneratorParameters}
#Import export ".\IRdcLibrary.ahk" {IRdcLibrary}
#Import export ".\IRdcSignatureReader.ahk" {IRdcSignatureReader}
#Import export ".\IRdcSimilarityGenerator.ahk" {IRdcSimilarityGenerator}
#Import export ".\ISimilarity.ahk" {ISimilarity}
#Import export ".\ISimilarityFileIdTable.ahk" {ISimilarityFileIdTable}
#Import export ".\ISimilarityReportProgress.ahk" {ISimilarityReportProgress}
#Import export ".\ISimilarityTableDumpState.ahk" {ISimilarityTableDumpState}
#Import export ".\ISimilarityTraitsMappedView.ahk" {ISimilarityTraitsMappedView}
#Import export ".\ISimilarityTraitsMapping.ahk" {ISimilarityTraitsMapping}
#Import export ".\ISimilarityTraitsTable.ahk" {ISimilarityTraitsTable}
#Import export ".\RDC_ErrorCode.ahk" {RDC_ErrorCode}
#Import export ".\RdcBufferPointer.ahk" {RdcBufferPointer}
#Import export ".\RdcComparator.ahk" {RdcComparator}
#Import export ".\RdcCreatedTables.ahk" {RdcCreatedTables}
#Import export ".\RdcFileReader.ahk" {RdcFileReader}
#Import export ".\RdcGenerator.ahk" {RdcGenerator}
#Import export ".\RdcGeneratorFilterMaxParameters.ahk" {RdcGeneratorFilterMaxParameters}
#Import export ".\RdcGeneratorParameters.ahk" {RdcGeneratorParameters}
#Import export ".\RdcLibrary.ahk" {RdcLibrary}
#Import export ".\RdcMappingAccessMode.ahk" {RdcMappingAccessMode}
#Import export ".\RdcNeed.ahk" {RdcNeed}
#Import export ".\RdcNeedPointer.ahk" {RdcNeedPointer}
#Import export ".\RdcNeedType.ahk" {RdcNeedType}
#Import export ".\RdcSignature.ahk" {RdcSignature}
#Import export ".\RdcSignaturePointer.ahk" {RdcSignaturePointer}
#Import export ".\RdcSignatureReader.ahk" {RdcSignatureReader}
#Import export ".\RdcSimilarityGenerator.ahk" {RdcSimilarityGenerator}
#Import export ".\Similarity.ahk" {Similarity}
#Import export ".\SimilarityData.ahk" {SimilarityData}
#Import export ".\SimilarityDumpData.ahk" {SimilarityDumpData}
#Import export ".\SimilarityFileId.ahk" {SimilarityFileId}
#Import export ".\SimilarityFileIdTable.ahk" {SimilarityFileIdTable}
#Import export ".\SimilarityMappedViewInfo.ahk" {SimilarityMappedViewInfo}
#Import export ".\SimilarityReportProgress.ahk" {SimilarityReportProgress}
#Import export ".\SimilarityTableDumpState.ahk" {SimilarityTableDumpState}
#Import export ".\SimilarityTraitsMappedView.ahk" {SimilarityTraitsMappedView}
#Import export ".\SimilarityTraitsMapping.ahk" {SimilarityTraitsMapping}
#Import export ".\SimilarityTraitsTable.ahk" {SimilarityTraitsTable}
