#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32Struct.ahk

/**
 * Reports the number of triangles that have been processed and clipped by the runtime's software vertex processing.
 * @remarks
 * Use the debug runtime and software vertex processing to get the number of non-clipped and clipped primitives for a particular scene. Primitives will typically be clipped based on a guard band (if one is present). The clipping guard band is set with parameters such as GuardBandLeft in [**D3DCAPS9**](/windows/desktop/api/D3D9Caps/ns-d3d9caps-d3dcaps9).
 * @see https://learn.microsoft.com/windows/win32/direct3d9/d3ddevinfo-d3dvertexstats
 * @namespace Windows.Win32.Graphics.Direct3D9
 * @version v4.0.30319
 */
class D3DDEVINFO_D3DVERTEXSTATS extends Win32Struct
{
    static sizeof => 8

    static packingSize => 4

    /**
     * Type: **[**DWORD**](../winprog/windows-data-types.md)**
     * 
     * 
     * Total number of triangles that are not clipped in this frame.
     * @type {Integer}
     */
    NumRenderedTriangles {
        get => NumGet(this, 0, "uint")
        set => NumPut("uint", value, this, 0)
    }

    /**
     * Type: **[**DWORD**](../winprog/windows-data-types.md)**
     * 
     * 
     * Number of new triangles generated by clipping.
     * @type {Integer}
     */
    NumExtraClippingTriangles {
        get => NumGet(this, 4, "uint")
        set => NumPut("uint", value, this, 4)
    }
}
