#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Common\__Init.ahk" {*}
#Import export ".\PropertiesSystem\__Init.ahk" {*}
#Import export ".\AASHELLMENUFILENAME.ahk" {AASHELLMENUFILENAME}
#Import export ".\AASHELLMENUITEM.ahk" {AASHELLMENUITEM}
#Import export ".\ACENUMOPTION.ahk" {ACENUMOPTION}
#Import export ".\ACTIVATEOPTIONS.ahk" {ACTIVATEOPTIONS}
#Import export ".\ADJACENT_DISPLAY_EDGES.ahk" {ADJACENT_DISPLAY_EDGES}
#Import export ".\AHE_TYPE.ahk" {AHE_TYPE}
#Import export ".\AHTYPE.ahk" {AHTYPE}
#Import export ".\APPACTIONFLAGS.ahk" {APPACTIONFLAGS}
#Import export ".\APPBARDATA.ahk" {APPBARDATA}
#Import export ".\APPCATEGORYINFO.ahk" {APPCATEGORYINFO}
#Import export ".\APPCATEGORYINFOLIST.ahk" {APPCATEGORYINFOLIST}
#Import export ".\APPDOCLISTTYPE.ahk" {APPDOCLISTTYPE}
#Import export ".\APPINFODATA.ahk" {APPINFODATA}
#Import export ".\APPINFODATAFLAGS.ahk" {APPINFODATAFLAGS}
#Import export ".\APPLET_PROC.ahk" {APPLET_PROC}
#Import export ".\APPLICATION_VIEW_MIN_WIDTH.ahk" {APPLICATION_VIEW_MIN_WIDTH}
#Import export ".\APPLICATION_VIEW_ORIENTATION.ahk" {APPLICATION_VIEW_ORIENTATION}
#Import export ".\APPLICATION_VIEW_SIZE_PREFERENCE.ahk" {APPLICATION_VIEW_SIZE_PREFERENCE}
#Import export ".\APPLICATION_VIEW_STATE.ahk" {APPLICATION_VIEW_STATE}
#Import export ".\ASSOCCLASS.ahk" {ASSOCCLASS}
#Import export ".\ASSOCDATA.ahk" {ASSOCDATA}
#Import export ".\ASSOCENUM.ahk" {ASSOCENUM}
#Import export ".\ASSOCF.ahk" {ASSOCF}
#Import export ".\ASSOCIATIONELEMENT.ahk" {ASSOCIATIONELEMENT}
#Import export ".\ASSOCIATIONLEVEL.ahk" {ASSOCIATIONLEVEL}
#Import export ".\ASSOCIATIONTYPE.ahk" {ASSOCIATIONTYPE}
#Import export ".\ASSOCKEY.ahk" {ASSOCKEY}
#Import export ".\ASSOCSTR.ahk" {ASSOCSTR}
#Import export ".\ASSOC_FILTER.ahk" {ASSOC_FILTER}
#Import export ".\ATTACHMENT_ACTION.ahk" {ATTACHMENT_ACTION}
#Import export ".\ATTACHMENT_PROMPT.ahk" {ATTACHMENT_PROMPT}
#Import export ".\AUTOCOMPLETELISTOPTIONS.ahk" {AUTOCOMPLETELISTOPTIONS}
#Import export ".\AUTOCOMPLETEOPTIONS.ahk" {AUTOCOMPLETEOPTIONS}
#Import export ".\AUTO_SCROLL_DATA.ahk" {AUTO_SCROLL_DATA}
#Import export ".\AccessibilityDockingService.ahk" {AccessibilityDockingService}
#Import export ".\AlphabeticalCategorizer.ahk" {AlphabeticalCategorizer}
#Import export ".\Apis.ahk" {*}
#Import export ".\AppShellVerbHandler.ahk" {AppShellVerbHandler}
#Import export ".\AppStartupLink.ahk" {AppStartupLink}
#Import export ".\AppVisibility.ahk" {AppVisibility}
#Import export ".\ApplicationActivationManager.ahk" {ApplicationActivationManager}
#Import export ".\ApplicationAssociationRegistration.ahk" {ApplicationAssociationRegistration}
#Import export ".\ApplicationAssociationRegistrationUI.ahk" {ApplicationAssociationRegistrationUI}
#Import export ".\ApplicationDesignModeSettings.ahk" {ApplicationDesignModeSettings}
#Import export ".\ApplicationDestinations.ahk" {ApplicationDestinations}
#Import export ".\ApplicationDocumentLists.ahk" {ApplicationDocumentLists}
#Import export ".\AttachmentServices.ahk" {AttachmentServices}
#Import export ".\BANDINFOSFB.ahk" {BANDINFOSFB}
#Import export ".\BANDSITECID.ahk" {BANDSITECID}
#Import export ".\BANDSITEINFO.ahk" {BANDSITEINFO}
#Import export ".\BANNER_NOTIFICATION.ahk" {BANNER_NOTIFICATION}
#Import export ".\BANNER_NOTIFICATION_EVENT.ahk" {BANNER_NOTIFICATION_EVENT}
#Import export ".\BASEBROWSERDATALH.ahk" {BASEBROWSERDATALH}
#Import export ".\BASEBROWSERDATAXP.ahk" {BASEBROWSERDATAXP}
#Import export ".\BFFCALLBACK.ahk" {BFFCALLBACK}
#Import export ".\BNSTATE.ahk" {BNSTATE}
#Import export ".\BROWSEINFOA.ahk" {BROWSEINFOA}
#Import export ".\BROWSEINFOW.ahk" {BROWSEINFOW}
#Import export ".\BrowserNavConstants.ahk" {BrowserNavConstants}
#Import export ".\CABINETSTATE.ahk" {CABINETSTATE}
#Import export ".\CATEGORYINFO_FLAGS.ahk" {CATEGORYINFO_FLAGS}
#Import export ".\CATEGORY_INFO.ahk" {CATEGORY_INFO}
#Import export ".\CATSORT_FLAGS.ahk" {CATSORT_FLAGS}
#Import export ".\CDBURNINGEXTENSIONRET.ahk" {CDBURNINGEXTENSIONRET}
#Import export ".\CDBurn.ahk" {CDBurn}
#Import export ".\CDCONTROLSTATEF.ahk" {CDCONTROLSTATEF}
#Import export ".\CIDA.ahk" {CIDA}
#Import export ".\CIE4ConnectionPoint.ahk" {CIE4ConnectionPoint}
#Import export ".\CMINVOKECOMMANDINFO.ahk" {CMINVOKECOMMANDINFO}
#Import export ".\CMINVOKECOMMANDINFOEX.ahk" {CMINVOKECOMMANDINFOEX}
#Import export ".\CMINVOKECOMMANDINFOEX_REMOTE.ahk" {CMINVOKECOMMANDINFOEX_REMOTE}
#Import export ".\CM_COLUMNINFO.ahk" {CM_COLUMNINFO}
#Import export ".\CM_ENUM_FLAGS.ahk" {CM_ENUM_FLAGS}
#Import export ".\CM_MASK.ahk" {CM_MASK}
#Import export ".\CM_SET_WIDTH_VALUE.ahk" {CM_SET_WIDTH_VALUE}
#Import export ".\CM_STATE.ahk" {CM_STATE}
#Import export ".\CONFIRM_CONFLICT_ITEM.ahk" {CONFIRM_CONFLICT_ITEM}
#Import export ".\CONFIRM_CONFLICT_RESULT_INFO.ahk" {CONFIRM_CONFLICT_RESULT_INFO}
#Import export ".\CPLINFO.ahk" {CPLINFO}
#Import export ".\CPVIEW.ahk" {CPVIEW}
#Import export ".\CREDENTIAL_PROVIDER_ACCOUNT_OPTIONS.ahk" {CREDENTIAL_PROVIDER_ACCOUNT_OPTIONS}
#Import export ".\CREDENTIAL_PROVIDER_CREDENTIAL_FIELD_OPTIONS.ahk" {CREDENTIAL_PROVIDER_CREDENTIAL_FIELD_OPTIONS}
#Import export ".\CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION.ahk" {CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION}
#Import export ".\CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR.ahk" {CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR}
#Import export ".\CREDENTIAL_PROVIDER_FIELD_INTERACTIVE_STATE.ahk" {CREDENTIAL_PROVIDER_FIELD_INTERACTIVE_STATE}
#Import export ".\CREDENTIAL_PROVIDER_FIELD_STATE.ahk" {CREDENTIAL_PROVIDER_FIELD_STATE}
#Import export ".\CREDENTIAL_PROVIDER_FIELD_TYPE.ahk" {CREDENTIAL_PROVIDER_FIELD_TYPE}
#Import export ".\CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE.ahk" {CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE}
#Import export ".\CREDENTIAL_PROVIDER_STATUS_ICON.ahk" {CREDENTIAL_PROVIDER_STATUS_ICON}
#Import export ".\CREDENTIAL_PROVIDER_USAGE_SCENARIO.ahk" {CREDENTIAL_PROVIDER_USAGE_SCENARIO}
#Import export ".\CSFV.ahk" {CSFV}
#Import export ".\CScriptErrorList.ahk" {CScriptErrorList}
#Import export ".\CommandStateChangeConstants.ahk" {CommandStateChangeConstants}
#Import export ".\ConflictFolder.ahk" {ConflictFolder}
#Import export ".\Constants.ahk" {*}
#Import export ".\DATABLOCK_HEADER.ahk" {DATABLOCK_HEADER}
#Import export ".\DATAOBJ_GET_ITEM_FLAGS.ahk" {DATAOBJ_GET_ITEM_FLAGS}
#Import export ".\DEFAULTSAVEFOLDERTYPE.ahk" {DEFAULTSAVEFOLDERTYPE}
#Import export ".\DEFAULT_FOLDER_MENU_RESTRICTIONS.ahk" {DEFAULT_FOLDER_MENU_RESTRICTIONS}
#Import export ".\DEFCONTEXTMENU.ahk" {DEFCONTEXTMENU}
#Import export ".\DEF_SHARE_ID.ahk" {DEF_SHARE_ID}
#Import export ".\DELEGATEITEMID.ahk" {DELEGATEITEMID}
#Import export ".\DESKBANDCID.ahk" {DESKBANDCID}
#Import export ".\DESKBANDINFO.ahk" {DESKBANDINFO}
#Import export ".\DESKTOP_SLIDESHOW_DIRECTION.ahk" {DESKTOP_SLIDESHOW_DIRECTION}
#Import export ".\DESKTOP_SLIDESHOW_OPTIONS.ahk" {DESKTOP_SLIDESHOW_OPTIONS}
#Import export ".\DESKTOP_SLIDESHOW_STATE.ahk" {DESKTOP_SLIDESHOW_STATE}
#Import export ".\DESKTOP_WALLPAPER_POSITION.ahk" {DESKTOP_WALLPAPER_POSITION}
#Import export ".\DETAILSINFO.ahk" {DETAILSINFO}
#Import export ".\DFConstraint.ahk" {DFConstraint}
#Import export ".\DFMICS.ahk" {DFMICS}
#Import export ".\DFM_CMD.ahk" {DFM_CMD}
#Import export ".\DFM_MESSAGE_ID.ahk" {DFM_MESSAGE_ID}
#Import export ".\DISPLAY_DEVICE_TYPE.ahk" {DISPLAY_DEVICE_TYPE}
#Import export ".\DLLGETVERSIONPROC.ahk" {DLLGETVERSIONPROC}
#Import export ".\DLLVERSIONINFO.ahk" {DLLVERSIONINFO}
#Import export ".\DLLVERSIONINFO2.ahk" {DLLVERSIONINFO2}
#Import export ".\DRAGINFOA.ahk" {DRAGINFOA}
#Import export ".\DRAGINFOW.ahk" {DRAGINFOW}
#Import export ".\DROPDESCRIPTION.ahk" {DROPDESCRIPTION}
#Import export ".\DROPFILES.ahk" {DROPFILES}
#Import export ".\DROPIMAGETYPE.ahk" {DROPIMAGETYPE}
#Import export ".\DSH_FLAGS.ahk" {DSH_FLAGS}
#Import export ".\DShellFolderViewEvents.ahk" {DShellFolderViewEvents}
#Import export ".\DShellNameSpaceEvents.ahk" {DShellNameSpaceEvents}
#Import export ".\DShellWindowsEvents.ahk" {DShellWindowsEvents}
#Import export ".\DWebBrowserEvents.ahk" {DWebBrowserEvents}
#Import export ".\DWebBrowserEvents2.ahk" {DWebBrowserEvents2}
#Import export ".\DefFolderMenu.ahk" {DefFolderMenu}
#Import export ".\DesktopGadget.ahk" {DesktopGadget}
#Import export ".\DesktopWallpaper.ahk" {DesktopWallpaper}
#Import export ".\DestinationList.ahk" {DestinationList}
#Import export ".\DestinationListBoth.ahk" {DestinationListBoth}
#Import export ".\DocPropShellExtension.ahk" {DocPropShellExtension}
#Import export ".\DriveSizeCategorizer.ahk" {DriveSizeCategorizer}
#Import export ".\DriveTypeCategorizer.ahk" {DriveTypeCategorizer}
#Import export ".\EC_HOST_UI_MODE.ahk" {EC_HOST_UI_MODE}
#Import export ".\EDGE_GESTURE_KIND.ahk" {EDGE_GESTURE_KIND}
#Import export ".\EXPLORER_BROWSER_FILL_FLAGS.ahk" {EXPLORER_BROWSER_FILL_FLAGS}
#Import export ".\EXPLORER_BROWSER_OPTIONS.ahk" {EXPLORER_BROWSER_OPTIONS}
#Import export ".\EXP_DARWIN_LINK.ahk" {EXP_DARWIN_LINK}
#Import export ".\EXP_PROPERTYSTORAGE.ahk" {EXP_PROPERTYSTORAGE}
#Import export ".\EXP_SPECIAL_FOLDER.ahk" {EXP_SPECIAL_FOLDER}
#Import export ".\EXP_SZ_LINK.ahk" {EXP_SZ_LINK}
#Import export ".\EXTRASEARCH.ahk" {EXTRASEARCH}
#Import export ".\EnumerableObjectCollection.ahk" {EnumerableObjectCollection}
#Import export ".\ExecuteFolder.ahk" {ExecuteFolder}
#Import export ".\ExecuteUnknown.ahk" {ExecuteUnknown}
#Import export ".\ExplorerBrowser.ahk" {ExplorerBrowser}
#Import export ".\FDAP.ahk" {FDAP}
#Import export ".\FDE_OVERWRITE_RESPONSE.ahk" {FDE_OVERWRITE_RESPONSE}
#Import export ".\FDE_SHAREVIOLATION_RESPONSE.ahk" {FDE_SHAREVIOLATION_RESPONSE}
#Import export ".\FD_FLAGS.ahk" {FD_FLAGS}
#Import export ".\FFFP_MODE.ahk" {FFFP_MODE}
#Import export ".\FILEDESCRIPTORA.ahk" {FILEDESCRIPTORA}
#Import export ".\FILEDESCRIPTORW.ahk" {FILEDESCRIPTORW}
#Import export ".\FILEGROUPDESCRIPTORA.ahk" {FILEGROUPDESCRIPTORA}
#Import export ".\FILEGROUPDESCRIPTORW.ahk" {FILEGROUPDESCRIPTORW}
#Import export ".\FILEOPENDIALOGOPTIONS.ahk" {FILEOPENDIALOGOPTIONS}
#Import export ".\FILEOPERATION_FLAGS.ahk" {FILEOPERATION_FLAGS}
#Import export ".\FILETYPEATTRIBUTEFLAGS.ahk" {FILETYPEATTRIBUTEFLAGS}
#Import export ".\FILE_ATTRIBUTES_ARRAY.ahk" {FILE_ATTRIBUTES_ARRAY}
#Import export ".\FILE_OPERATION_FLAGS2.ahk" {FILE_OPERATION_FLAGS2}
#Import export ".\FILE_USAGE_TYPE.ahk" {FILE_USAGE_TYPE}
#Import export ".\FLYOUT_PLACEMENT.ahk" {FLYOUT_PLACEMENT}
#Import export ".\FOLDERFLAGS.ahk" {FOLDERFLAGS}
#Import export ".\FOLDERLOGICALVIEWMODE.ahk" {FOLDERLOGICALVIEWMODE}
#Import export ".\FOLDERSETDATA.ahk" {FOLDERSETDATA}
#Import export ".\FOLDERSETTINGS.ahk" {FOLDERSETTINGS}
#Import export ".\FOLDERVIEWMODE.ahk" {FOLDERVIEWMODE}
#Import export ".\FOLDERVIEWOPTIONS.ahk" {FOLDERVIEWOPTIONS}
#Import export ".\FOLDER_ENUM_MODE.ahk" {FOLDER_ENUM_MODE}
#Import export ".\FSCopyHandler.ahk" {FSCopyHandler}
#Import export ".\FVTEXTTYPE.ahk" {FVTEXTTYPE}
#Import export ".\FileOpenDialog.ahk" {FileOpenDialog}
#Import export ".\FileOperation.ahk" {FileOperation}
#Import export ".\FileSaveDialog.ahk" {FileSaveDialog}
#Import export ".\FileSearchBand.ahk" {FileSearchBand}
#Import export ".\Folder.ahk" {Folder}
#Import export ".\Folder2.ahk" {Folder2}
#Import export ".\Folder3.ahk" {Folder3}
#Import export ".\FolderItem.ahk" {FolderItem}
#Import export ".\FolderItem2.ahk" {FolderItem2}
#Import export ".\FolderItemVerb.ahk" {FolderItemVerb}
#Import export ".\FolderItemVerbs.ahk" {FolderItemVerbs}
#Import export ".\FolderItems.ahk" {FolderItems}
#Import export ".\FolderItems2.ahk" {FolderItems2}
#Import export ".\FolderItems3.ahk" {FolderItems3}
#Import export ".\FolderViewHost.ahk" {FolderViewHost}
#Import export ".\FrameworkInputPane.ahk" {FrameworkInputPane}
#Import export ".\FreeSpaceCategorizer.ahk" {FreeSpaceCategorizer}
#Import export ".\GPFIDL_FLAGS.ahk" {GPFIDL_FLAGS}
#Import export ".\GenericCredentialProvider.ahk" {GenericCredentialProvider}
#Import export ".\HDROP.ahk" {HDROP}
#Import export ".\HELPINFO.ahk" {HELPINFO}
#Import export ".\HELPWININFOA.ahk" {HELPWININFOA}
#Import export ".\HELPWININFOW.ahk" {HELPWININFOW}
#Import export ".\HELP_INFO_TYPE.ahk" {HELP_INFO_TYPE}
#Import export ".\HLBWIF_FLAGS.ahk" {HLBWIF_FLAGS}
#Import export ".\HLBWINFO.ahk" {HLBWINFO}
#Import export ".\HLFNAMEF.ahk" {HLFNAMEF}
#Import export ".\HLID_INFO.ahk" {HLID_INFO}
#Import export ".\HLINKGETREF.ahk" {HLINKGETREF}
#Import export ".\HLINKMISC.ahk" {HLINKMISC}
#Import export ".\HLINKSETF.ahk" {HLINKSETF}
#Import export ".\HLINKWHICHMK.ahk" {HLINKWHICHMK}
#Import export ".\HLITEM.ahk" {HLITEM}
#Import export ".\HLNF.ahk" {HLNF}
#Import export ".\HLQF_INFO.ahk" {HLQF_INFO}
#Import export ".\HLSHORTCUTF.ahk" {HLSHORTCUTF}
#Import export ".\HLSR.ahk" {HLSR}
#Import export ".\HLTBINFO.ahk" {HLTBINFO}
#Import export ".\HLTB_INFO.ahk" {HLTB_INFO}
#Import export ".\HLTRANSLATEF.ahk" {HLTRANSLATEF}
#Import export ".\HOMEGROUPSHARINGCHOICES.ahk" {HOMEGROUPSHARINGCHOICES}
#Import export ".\HPSXA.ahk" {HPSXA}
#Import export ".\HideInputPaneAnimationCoordinator.ahk" {HideInputPaneAnimationCoordinator}
#Import export ".\HomeGroup.ahk" {HomeGroup}
#Import export ".\IACList.ahk" {IACList}
#Import export ".\IACList2.ahk" {IACList2}
#Import export ".\IAccessibilityDockingService.ahk" {IAccessibilityDockingService}
#Import export ".\IAccessibilityDockingServiceCallback.ahk" {IAccessibilityDockingServiceCallback}
#Import export ".\IAccessibleObject.ahk" {IAccessibleObject}
#Import export ".\IActionProgress.ahk" {IActionProgress}
#Import export ".\IActionProgressDialog.ahk" {IActionProgressDialog}
#Import export ".\IAppActivationUIInfo.ahk" {IAppActivationUIInfo}
#Import export ".\IAppPublisher.ahk" {IAppPublisher}
#Import export ".\IAppVisibility.ahk" {IAppVisibility}
#Import export ".\IAppVisibilityEvents.ahk" {IAppVisibilityEvents}
#Import export ".\IApplicationActivationManager.ahk" {IApplicationActivationManager}
#Import export ".\IApplicationAssociationRegistration.ahk" {IApplicationAssociationRegistration}
#Import export ".\IApplicationAssociationRegistrationUI.ahk" {IApplicationAssociationRegistrationUI}
#Import export ".\IApplicationDesignModeSettings.ahk" {IApplicationDesignModeSettings}
#Import export ".\IApplicationDesignModeSettings2.ahk" {IApplicationDesignModeSettings2}
#Import export ".\IApplicationDestinations.ahk" {IApplicationDestinations}
#Import export ".\IApplicationDocumentLists.ahk" {IApplicationDocumentLists}
#Import export ".\IAssocHandler.ahk" {IAssocHandler}
#Import export ".\IAssocHandlerInvoker.ahk" {IAssocHandlerInvoker}
#Import export ".\IAttachmentExecute.ahk" {IAttachmentExecute}
#Import export ".\IAttachmentExecute2.ahk" {IAttachmentExecute2}
#Import export ".\IAutoComplete.ahk" {IAutoComplete}
#Import export ".\IAutoComplete2.ahk" {IAutoComplete2}
#Import export ".\IAutoCompleteDropDown.ahk" {IAutoCompleteDropDown}
#Import export ".\IBandHost.ahk" {IBandHost}
#Import export ".\IBandSite.ahk" {IBandSite}
#Import export ".\IBannerNotificationHandler.ahk" {IBannerNotificationHandler}
#Import export ".\IBanneredBar.ahk" {IBanneredBar}
#Import export ".\IBrowserFrameOptions.ahk" {IBrowserFrameOptions}
#Import export ".\IBrowserService.ahk" {IBrowserService}
#Import export ".\IBrowserService2.ahk" {IBrowserService2}
#Import export ".\IBrowserService3.ahk" {IBrowserService3}
#Import export ".\IBrowserService4.ahk" {IBrowserService4}
#Import export ".\ICDBurn.ahk" {ICDBurn}
#Import export ".\ICDBurnExt.ahk" {ICDBurnExt}
#Import export ".\ICategorizer.ahk" {ICategorizer}
#Import export ".\ICategoryProvider.ahk" {ICategoryProvider}
#Import export ".\IColumnManager.ahk" {IColumnManager}
#Import export ".\IColumnProvider.ahk" {IColumnProvider}
#Import export ".\ICommDlgBrowser.ahk" {ICommDlgBrowser}
#Import export ".\ICommDlgBrowser2.ahk" {ICommDlgBrowser2}
#Import export ".\ICommDlgBrowser3.ahk" {ICommDlgBrowser3}
#Import export ".\IComputerInfoChangeNotify.ahk" {IComputerInfoChangeNotify}
#Import export ".\IConnectableCredentialProviderCredential.ahk" {IConnectableCredentialProviderCredential}
#Import export ".\IContactManagerInterop.ahk" {IContactManagerInterop}
#Import export ".\IContextMenu.ahk" {IContextMenu}
#Import export ".\IContextMenu2.ahk" {IContextMenu2}
#Import export ".\IContextMenu3.ahk" {IContextMenu3}
#Import export ".\IContextMenuCB.ahk" {IContextMenuCB}
#Import export ".\IContextMenuSite.ahk" {IContextMenuSite}
#Import export ".\ICopyHookA.ahk" {ICopyHookA}
#Import export ".\ICopyHookW.ahk" {ICopyHookW}
#Import export ".\ICreateProcessInputs.ahk" {ICreateProcessInputs}
#Import export ".\ICreatingProcess.ahk" {ICreatingProcess}
#Import export ".\ICredentialProvider.ahk" {ICredentialProvider}
#Import export ".\ICredentialProviderCredential.ahk" {ICredentialProviderCredential}
#Import export ".\ICredentialProviderCredential2.ahk" {ICredentialProviderCredential2}
#Import export ".\ICredentialProviderCredentialEvents.ahk" {ICredentialProviderCredentialEvents}
#Import export ".\ICredentialProviderCredentialEvents2.ahk" {ICredentialProviderCredentialEvents2}
#Import export ".\ICredentialProviderCredentialWithFieldOptions.ahk" {ICredentialProviderCredentialWithFieldOptions}
#Import export ".\ICredentialProviderEvents.ahk" {ICredentialProviderEvents}
#Import export ".\ICredentialProviderFilter.ahk" {ICredentialProviderFilter}
#Import export ".\ICredentialProviderSetUserArray.ahk" {ICredentialProviderSetUserArray}
#Import export ".\ICredentialProviderUser.ahk" {ICredentialProviderUser}
#Import export ".\ICredentialProviderUserArray.ahk" {ICredentialProviderUserArray}
#Import export ".\ICurrentItem.ahk" {ICurrentItem}
#Import export ".\ICurrentWorkingDirectory.ahk" {ICurrentWorkingDirectory}
#Import export ".\ICustomDestinationList.ahk" {ICustomDestinationList}
#Import export ".\IDataObjectAsyncCapability.ahk" {IDataObjectAsyncCapability}
#Import export ".\IDataObjectProvider.ahk" {IDataObjectProvider}
#Import export ".\IDataTransferManagerInterop.ahk" {IDataTransferManagerInterop}
#Import export ".\IDefaultExtractIconInit.ahk" {IDefaultExtractIconInit}
#Import export ".\IDefaultFolderMenuInitialize.ahk" {IDefaultFolderMenuInitialize}
#Import export ".\IDelegateFolder.ahk" {IDelegateFolder}
#Import export ".\IDelegateItem.ahk" {IDelegateItem}
#Import export ".\IDeskBand.ahk" {IDeskBand}
#Import export ".\IDeskBand2.ahk" {IDeskBand2}
#Import export ".\IDeskBandInfo.ahk" {IDeskBandInfo}
#Import export ".\IDeskBar.ahk" {IDeskBar}
#Import export ".\IDeskBarClient.ahk" {IDeskBarClient}
#Import export ".\IDesktopGadget.ahk" {IDesktopGadget}
#Import export ".\IDesktopWallpaper.ahk" {IDesktopWallpaper}
#Import export ".\IDestinationStreamFactory.ahk" {IDestinationStreamFactory}
#Import export ".\IDisplayItem.ahk" {IDisplayItem}
#Import export ".\IDocViewSite.ahk" {IDocViewSite}
#Import export ".\IDockingWindow.ahk" {IDockingWindow}
#Import export ".\IDockingWindowFrame.ahk" {IDockingWindowFrame}
#Import export ".\IDockingWindowSite.ahk" {IDockingWindowSite}
#Import export ".\IDragSourceHelper.ahk" {IDragSourceHelper}
#Import export ".\IDragSourceHelper2.ahk" {IDragSourceHelper2}
#Import export ".\IDropTargetHelper.ahk" {IDropTargetHelper}
#Import export ".\IDynamicHWHandler.ahk" {IDynamicHWHandler}
#Import export ".\IENamespaceTreeControl.ahk" {IENamespaceTreeControl}
#Import export ".\IEPDNFLAGS.ahk" {IEPDNFLAGS}
#Import export ".\IESHORTCUTFLAGS.ahk" {IESHORTCUTFLAGS}
#Import export ".\IEnumACString.ahk" {IEnumACString}
#Import export ".\IEnumAssocHandlers.ahk" {IEnumAssocHandlers}
#Import export ".\IEnumExplorerCommand.ahk" {IEnumExplorerCommand}
#Import export ".\IEnumExtraSearch.ahk" {IEnumExtraSearch}
#Import export ".\IEnumFullIDList.ahk" {IEnumFullIDList}
#Import export ".\IEnumHLITEM.ahk" {IEnumHLITEM}
#Import export ".\IEnumIDList.ahk" {IEnumIDList}
#Import export ".\IEnumObjects.ahk" {IEnumObjects}
#Import export ".\IEnumPublishedApps.ahk" {IEnumPublishedApps}
#Import export ".\IEnumReadyCallback.ahk" {IEnumReadyCallback}
#Import export ".\IEnumResources.ahk" {IEnumResources}
#Import export ".\IEnumShellItems.ahk" {IEnumShellItems}
#Import export ".\IEnumSyncMgrConflict.ahk" {IEnumSyncMgrConflict}
#Import export ".\IEnumSyncMgrEvents.ahk" {IEnumSyncMgrEvents}
#Import export ".\IEnumSyncMgrSyncItems.ahk" {IEnumSyncMgrSyncItems}
#Import export ".\IEnumTravelLogEntry.ahk" {IEnumTravelLogEntry}
#Import export ".\IEnumerableView.ahk" {IEnumerableView}
#Import export ".\IExecuteCommand.ahk" {IExecuteCommand}
#Import export ".\IExecuteCommandApplicationHostEnvironment.ahk" {IExecuteCommandApplicationHostEnvironment}
#Import export ".\IExecuteCommandHost.ahk" {IExecuteCommandHost}
#Import export ".\IExpDispSupport.ahk" {IExpDispSupport}
#Import export ".\IExpDispSupportXP.ahk" {IExpDispSupportXP}
#Import export ".\IExplorerBrowser.ahk" {IExplorerBrowser}
#Import export ".\IExplorerBrowserEvents.ahk" {IExplorerBrowserEvents}
#Import export ".\IExplorerCommand.ahk" {IExplorerCommand}
#Import export ".\IExplorerCommandProvider.ahk" {IExplorerCommandProvider}
#Import export ".\IExplorerCommandState.ahk" {IExplorerCommandState}
#Import export ".\IExplorerPaneVisibility.ahk" {IExplorerPaneVisibility}
#Import export ".\IExtensionServices.ahk" {IExtensionServices}
#Import export ".\IExtractIconA.ahk" {IExtractIconA}
#Import export ".\IExtractIconW.ahk" {IExtractIconW}
#Import export ".\IExtractImage.ahk" {IExtractImage}
#Import export ".\IExtractImage2.ahk" {IExtractImage2}
#Import export ".\IFileDialog.ahk" {IFileDialog}
#Import export ".\IFileDialog2.ahk" {IFileDialog2}
#Import export ".\IFileDialogControlEvents.ahk" {IFileDialogControlEvents}
#Import export ".\IFileDialogCustomize.ahk" {IFileDialogCustomize}
#Import export ".\IFileDialogEvents.ahk" {IFileDialogEvents}
#Import export ".\IFileIsInUse.ahk" {IFileIsInUse}
#Import export ".\IFileOpenDialog.ahk" {IFileOpenDialog}
#Import export ".\IFileOperation.ahk" {IFileOperation}
#Import export ".\IFileOperation2.ahk" {IFileOperation2}
#Import export ".\IFileOperationProgressSink.ahk" {IFileOperationProgressSink}
#Import export ".\IFileSaveDialog.ahk" {IFileSaveDialog}
#Import export ".\IFileSearchBand.ahk" {IFileSearchBand}
#Import export ".\IFileSyncMergeHandler.ahk" {IFileSyncMergeHandler}
#Import export ".\IFileSystemBindData.ahk" {IFileSystemBindData}
#Import export ".\IFileSystemBindData2.ahk" {IFileSystemBindData2}
#Import export ".\IFolderBandPriv.ahk" {IFolderBandPriv}
#Import export ".\IFolderFilter.ahk" {IFolderFilter}
#Import export ".\IFolderFilterSite.ahk" {IFolderFilterSite}
#Import export ".\IFolderView.ahk" {IFolderView}
#Import export ".\IFolderView2.ahk" {IFolderView2}
#Import export ".\IFolderViewHost.ahk" {IFolderViewHost}
#Import export ".\IFolderViewOC.ahk" {IFolderViewOC}
#Import export ".\IFolderViewOptions.ahk" {IFolderViewOptions}
#Import export ".\IFolderViewSettings.ahk" {IFolderViewSettings}
#Import export ".\IFrameworkInputPane.ahk" {IFrameworkInputPane}
#Import export ".\IFrameworkInputPaneHandler.ahk" {IFrameworkInputPaneHandler}
#Import export ".\IGetServiceIds.ahk" {IGetServiceIds}
#Import export ".\IHWEventHandler.ahk" {IHWEventHandler}
#Import export ".\IHWEventHandler2.ahk" {IHWEventHandler2}
#Import export ".\IHandlerActivationHost.ahk" {IHandlerActivationHost}
#Import export ".\IHandlerInfo.ahk" {IHandlerInfo}
#Import export ".\IHandlerInfo2.ahk" {IHandlerInfo2}
#Import export ".\IHlink.ahk" {IHlink}
#Import export ".\IHlinkBrowseContext.ahk" {IHlinkBrowseContext}
#Import export ".\IHlinkFrame.ahk" {IHlinkFrame}
#Import export ".\IHlinkSite.ahk" {IHlinkSite}
#Import export ".\IHlinkTarget.ahk" {IHlinkTarget}
#Import export ".\IHomeGroup.ahk" {IHomeGroup}
#Import export ".\IIOCancelInformation.ahk" {IIOCancelInformation}
#Import export ".\IIdentityName.ahk" {IIdentityName}
#Import export ".\IImageRecompress.ahk" {IImageRecompress}
#Import export ".\IInitializeCommand.ahk" {IInitializeCommand}
#Import export ".\IInitializeNetworkFolder.ahk" {IInitializeNetworkFolder}
#Import export ".\IInitializeObject.ahk" {IInitializeObject}
#Import export ".\IInitializeWithBindCtx.ahk" {IInitializeWithBindCtx}
#Import export ".\IInitializeWithItem.ahk" {IInitializeWithItem}
#Import export ".\IInitializeWithPropertyStore.ahk" {IInitializeWithPropertyStore}
#Import export ".\IInitializeWithWindow.ahk" {IInitializeWithWindow}
#Import export ".\IInputObject.ahk" {IInputObject}
#Import export ".\IInputObject2.ahk" {IInputObject2}
#Import export ".\IInputObjectSite.ahk" {IInputObjectSite}
#Import export ".\IInputPaneAnimationCoordinator.ahk" {IInputPaneAnimationCoordinator}
#Import export ".\IInputPanelConfiguration.ahk" {IInputPanelConfiguration}
#Import export ".\IInputPanelInvocationConfiguration.ahk" {IInputPanelInvocationConfiguration}
#Import export ".\IInsertItem.ahk" {IInsertItem}
#Import export ".\IItemNameLimits.ahk" {IItemNameLimits}
#Import export ".\IKnownFolder.ahk" {IKnownFolder}
#Import export ".\IKnownFolderManager.ahk" {IKnownFolderManager}
#Import export ".\ILaunchSourceAppUserModelId.ahk" {ILaunchSourceAppUserModelId}
#Import export ".\ILaunchSourceViewSizePreference.ahk" {ILaunchSourceViewSizePreference}
#Import export ".\ILaunchTargetMonitor.ahk" {ILaunchTargetMonitor}
#Import export ".\ILaunchTargetViewSizePreference.ahk" {ILaunchTargetViewSizePreference}
#Import export ".\ILaunchUIContext.ahk" {ILaunchUIContext}
#Import export ".\ILaunchUIContextProvider.ahk" {ILaunchUIContextProvider}
#Import export ".\IMenuBand.ahk" {IMenuBand}
#Import export ".\IMenuPopup.ahk" {IMenuPopup}
#Import export ".\IModalWindow.ahk" {IModalWindow}
#Import export ".\INameSpaceTreeAccessible.ahk" {INameSpaceTreeAccessible}
#Import export ".\INameSpaceTreeControl.ahk" {INameSpaceTreeControl}
#Import export ".\INameSpaceTreeControl2.ahk" {INameSpaceTreeControl2}
#Import export ".\INameSpaceTreeControlCustomDraw.ahk" {INameSpaceTreeControlCustomDraw}
#Import export ".\INameSpaceTreeControlDropHandler.ahk" {INameSpaceTreeControlDropHandler}
#Import export ".\INameSpaceTreeControlEvents.ahk" {INameSpaceTreeControlEvents}
#Import export ".\INameSpaceTreeControlFolderCapabilities.ahk" {INameSpaceTreeControlFolderCapabilities}
#Import export ".\INamedPropertyBag.ahk" {INamedPropertyBag}
#Import export ".\INamespaceWalk.ahk" {INamespaceWalk}
#Import export ".\INamespaceWalkCB.ahk" {INamespaceWalkCB}
#Import export ".\INamespaceWalkCB2.ahk" {INamespaceWalkCB2}
#Import export ".\INetworkFolderInternal.ahk" {INetworkFolderInternal}
#Import export ".\INewMenuClient.ahk" {INewMenuClient}
#Import export ".\INewShortcutHookA.ahk" {INewShortcutHookA}
#Import export ".\INewShortcutHookW.ahk" {INewShortcutHookW}
#Import export ".\INewWDEvents.ahk" {INewWDEvents}
#Import export ".\INewWindowManager.ahk" {INewWindowManager}
#Import export ".\INotifyReplica.ahk" {INotifyReplica}
#Import export ".\IObjMgr.ahk" {IObjMgr}
#Import export ".\IObjectProvider.ahk" {IObjectProvider}
#Import export ".\IObjectWithAppUserModelID.ahk" {IObjectWithAppUserModelID}
#Import export ".\IObjectWithBackReferences.ahk" {IObjectWithBackReferences}
#Import export ".\IObjectWithCancelEvent.ahk" {IObjectWithCancelEvent}
#Import export ".\IObjectWithFolderEnumMode.ahk" {IObjectWithFolderEnumMode}
#Import export ".\IObjectWithPackageFullName.ahk" {IObjectWithPackageFullName}
#Import export ".\IObjectWithProgID.ahk" {IObjectWithProgID}
#Import export ".\IObjectWithSelection.ahk" {IObjectWithSelection}
#Import export ".\IOpenControlPanel.ahk" {IOpenControlPanel}
#Import export ".\IOpenSearchSource.ahk" {IOpenSearchSource}
#Import export ".\IOperationsProgressDialog.ahk" {IOperationsProgressDialog}
#Import export ".\IPackageDebugSettings.ahk" {IPackageDebugSettings}
#Import export ".\IPackageDebugSettings2.ahk" {IPackageDebugSettings2}
#Import export ".\IPackageExecutionStateChangeNotification.ahk" {IPackageExecutionStateChangeNotification}
#Import export ".\IParentAndItem.ahk" {IParentAndItem}
#Import export ".\IParseAndCreateItem.ahk" {IParseAndCreateItem}
#Import export ".\IPersistFolder.ahk" {IPersistFolder}
#Import export ".\IPersistFolder2.ahk" {IPersistFolder2}
#Import export ".\IPersistFolder3.ahk" {IPersistFolder3}
#Import export ".\IPersistIDList.ahk" {IPersistIDList}
#Import export ".\IPreviewHandler.ahk" {IPreviewHandler}
#Import export ".\IPreviewHandlerFrame.ahk" {IPreviewHandlerFrame}
#Import export ".\IPreviewHandlerVisuals.ahk" {IPreviewHandlerVisuals}
#Import export ".\IPreviewItem.ahk" {IPreviewItem}
#Import export ".\IPreviousVersionsInfo.ahk" {IPreviousVersionsInfo}
#Import export ".\IProfferService.ahk" {IProfferService}
#Import export ".\IProgressDialog.ahk" {IProgressDialog}
#Import export ".\IPropertyKeyStore.ahk" {IPropertyKeyStore}
#Import export ".\IPublishedApp.ahk" {IPublishedApp}
#Import export ".\IPublishedApp2.ahk" {IPublishedApp2}
#Import export ".\IPublishingWizard.ahk" {IPublishingWizard}
#Import export ".\IQueryAssociations.ahk" {IQueryAssociations}
#Import export ".\IQueryCancelAutoPlay.ahk" {IQueryCancelAutoPlay}
#Import export ".\IQueryCodePage.ahk" {IQueryCodePage}
#Import export ".\IQueryContinue.ahk" {IQueryContinue}
#Import export ".\IQueryContinueWithStatus.ahk" {IQueryContinueWithStatus}
#Import export ".\IQueryInfo.ahk" {IQueryInfo}
#Import export ".\IRegTreeItem.ahk" {IRegTreeItem}
#Import export ".\IRelatedItem.ahk" {IRelatedItem}
#Import export ".\IRemoteComputer.ahk" {IRemoteComputer}
#Import export ".\IResolveShellLink.ahk" {IResolveShellLink}
#Import export ".\IResultsFolder.ahk" {IResultsFolder}
#Import export ".\IRunnableTask.ahk" {IRunnableTask}
#Import export ".\IScriptErrorList.ahk" {IScriptErrorList}
#Import export ".\ISearchBoxInfo.ahk" {ISearchBoxInfo}
#Import export ".\ISearchContext.ahk" {ISearchContext}
#Import export ".\ISearchFolderItemFactory.ahk" {ISearchFolderItemFactory}
#Import export ".\ISharedBitmap.ahk" {ISharedBitmap}
#Import export ".\ISharingConfigurationManager.ahk" {ISharingConfigurationManager}
#Import export ".\IShellApp.ahk" {IShellApp}
#Import export ".\IShellBrowser.ahk" {IShellBrowser}
#Import export ".\IShellChangeNotify.ahk" {IShellChangeNotify}
#Import export ".\IShellDetails.ahk" {IShellDetails}
#Import export ".\IShellDispatch.ahk" {IShellDispatch}
#Import export ".\IShellDispatch2.ahk" {IShellDispatch2}
#Import export ".\IShellDispatch3.ahk" {IShellDispatch3}
#Import export ".\IShellDispatch4.ahk" {IShellDispatch4}
#Import export ".\IShellDispatch5.ahk" {IShellDispatch5}
#Import export ".\IShellDispatch6.ahk" {IShellDispatch6}
#Import export ".\IShellExtInit.ahk" {IShellExtInit}
#Import export ".\IShellFavoritesNameSpace.ahk" {IShellFavoritesNameSpace}
#Import export ".\IShellFolder.ahk" {IShellFolder}
#Import export ".\IShellFolder2.ahk" {IShellFolder2}
#Import export ".\IShellFolderBand.ahk" {IShellFolderBand}
#Import export ".\IShellFolderView.ahk" {IShellFolderView}
#Import export ".\IShellFolderViewCB.ahk" {IShellFolderViewCB}
#Import export ".\IShellFolderViewDual.ahk" {IShellFolderViewDual}
#Import export ".\IShellFolderViewDual2.ahk" {IShellFolderViewDual2}
#Import export ".\IShellFolderViewDual3.ahk" {IShellFolderViewDual3}
#Import export ".\IShellIcon.ahk" {IShellIcon}
#Import export ".\IShellIconOverlay.ahk" {IShellIconOverlay}
#Import export ".\IShellIconOverlayIdentifier.ahk" {IShellIconOverlayIdentifier}
#Import export ".\IShellIconOverlayManager.ahk" {IShellIconOverlayManager}
#Import export ".\IShellImageData.ahk" {IShellImageData}
#Import export ".\IShellImageDataAbort.ahk" {IShellImageDataAbort}
#Import export ".\IShellImageDataFactory.ahk" {IShellImageDataFactory}
#Import export ".\IShellItem.ahk" {IShellItem}
#Import export ".\IShellItem2.ahk" {IShellItem2}
#Import export ".\IShellItemArray.ahk" {IShellItemArray}
#Import export ".\IShellItemFilter.ahk" {IShellItemFilter}
#Import export ".\IShellItemImageFactory.ahk" {IShellItemImageFactory}
#Import export ".\IShellItemResources.ahk" {IShellItemResources}
#Import export ".\IShellLibrary.ahk" {IShellLibrary}
#Import export ".\IShellLinkA.ahk" {IShellLinkA}
#Import export ".\IShellLinkDataList.ahk" {IShellLinkDataList}
#Import export ".\IShellLinkDual.ahk" {IShellLinkDual}
#Import export ".\IShellLinkDual2.ahk" {IShellLinkDual2}
#Import export ".\IShellLinkW.ahk" {IShellLinkW}
#Import export ".\IShellMenu.ahk" {IShellMenu}
#Import export ".\IShellMenuCallback.ahk" {IShellMenuCallback}
#Import export ".\IShellNameSpace.ahk" {IShellNameSpace}
#Import export ".\IShellPropSheetExt.ahk" {IShellPropSheetExt}
#Import export ".\IShellRunDll.ahk" {IShellRunDll}
#Import export ".\IShellService.ahk" {IShellService}
#Import export ".\IShellTaskScheduler.ahk" {IShellTaskScheduler}
#Import export ".\IShellUIHelper.ahk" {IShellUIHelper}
#Import export ".\IShellUIHelper2.ahk" {IShellUIHelper2}
#Import export ".\IShellUIHelper3.ahk" {IShellUIHelper3}
#Import export ".\IShellUIHelper4.ahk" {IShellUIHelper4}
#Import export ".\IShellUIHelper5.ahk" {IShellUIHelper5}
#Import export ".\IShellUIHelper6.ahk" {IShellUIHelper6}
#Import export ".\IShellUIHelper7.ahk" {IShellUIHelper7}
#Import export ".\IShellUIHelper8.ahk" {IShellUIHelper8}
#Import export ".\IShellUIHelper9.ahk" {IShellUIHelper9}
#Import export ".\IShellView.ahk" {IShellView}
#Import export ".\IShellView2.ahk" {IShellView2}
#Import export ".\IShellView3.ahk" {IShellView3}
#Import export ".\IShellWindows.ahk" {IShellWindows}
#Import export ".\ISortColumnArray.ahk" {ISortColumnArray}
#Import export ".\IStartMenuPinnedList.ahk" {IStartMenuPinnedList}
#Import export ".\IStaticVerbProvider.ahk" {IStaticVerbProvider}
#Import export ".\IStorageProviderBanners.ahk" {IStorageProviderBanners}
#Import export ".\IStorageProviderCopyHook.ahk" {IStorageProviderCopyHook}
#Import export ".\IStorageProviderHandler.ahk" {IStorageProviderHandler}
#Import export ".\IStorageProviderPropertyHandler.ahk" {IStorageProviderPropertyHandler}
#Import export ".\IStreamAsync.ahk" {IStreamAsync}
#Import export ".\IStreamUnbufferedInfo.ahk" {IStreamUnbufferedInfo}
#Import export ".\ISuspensionDependencyManager.ahk" {ISuspensionDependencyManager}
#Import export ".\ISyncMgrConflict.ahk" {ISyncMgrConflict}
#Import export ".\ISyncMgrConflictFolder.ahk" {ISyncMgrConflictFolder}
#Import export ".\ISyncMgrConflictItems.ahk" {ISyncMgrConflictItems}
#Import export ".\ISyncMgrConflictPresenter.ahk" {ISyncMgrConflictPresenter}
#Import export ".\ISyncMgrConflictResolutionItems.ahk" {ISyncMgrConflictResolutionItems}
#Import export ".\ISyncMgrConflictResolveInfo.ahk" {ISyncMgrConflictResolveInfo}
#Import export ".\ISyncMgrConflictStore.ahk" {ISyncMgrConflictStore}
#Import export ".\ISyncMgrControl.ahk" {ISyncMgrControl}
#Import export ".\ISyncMgrEnumItems.ahk" {ISyncMgrEnumItems}
#Import export ".\ISyncMgrEvent.ahk" {ISyncMgrEvent}
#Import export ".\ISyncMgrEventLinkUIOperation.ahk" {ISyncMgrEventLinkUIOperation}
#Import export ".\ISyncMgrEventStore.ahk" {ISyncMgrEventStore}
#Import export ".\ISyncMgrHandler.ahk" {ISyncMgrHandler}
#Import export ".\ISyncMgrHandlerCollection.ahk" {ISyncMgrHandlerCollection}
#Import export ".\ISyncMgrHandlerInfo.ahk" {ISyncMgrHandlerInfo}
#Import export ".\ISyncMgrRegister.ahk" {ISyncMgrRegister}
#Import export ".\ISyncMgrResolutionHandler.ahk" {ISyncMgrResolutionHandler}
#Import export ".\ISyncMgrScheduleWizardUIOperation.ahk" {ISyncMgrScheduleWizardUIOperation}
#Import export ".\ISyncMgrSessionCreator.ahk" {ISyncMgrSessionCreator}
#Import export ".\ISyncMgrSyncCallback.ahk" {ISyncMgrSyncCallback}
#Import export ".\ISyncMgrSyncItem.ahk" {ISyncMgrSyncItem}
#Import export ".\ISyncMgrSyncItemContainer.ahk" {ISyncMgrSyncItemContainer}
#Import export ".\ISyncMgrSyncItemInfo.ahk" {ISyncMgrSyncItemInfo}
#Import export ".\ISyncMgrSyncResult.ahk" {ISyncMgrSyncResult}
#Import export ".\ISyncMgrSynchronize.ahk" {ISyncMgrSynchronize}
#Import export ".\ISyncMgrSynchronizeCallback.ahk" {ISyncMgrSynchronizeCallback}
#Import export ".\ISyncMgrSynchronizeInvoke.ahk" {ISyncMgrSynchronizeInvoke}
#Import export ".\ISyncMgrUIOperation.ahk" {ISyncMgrUIOperation}
#Import export ".\ITEMSPACING.ahk" {ITEMSPACING}
#Import export ".\ITaskbarList.ahk" {ITaskbarList}
#Import export ".\ITaskbarList2.ahk" {ITaskbarList2}
#Import export ".\ITaskbarList3.ahk" {ITaskbarList3}
#Import export ".\ITaskbarList4.ahk" {ITaskbarList4}
#Import export ".\IThumbnailCache.ahk" {IThumbnailCache}
#Import export ".\IThumbnailCachePrimer.ahk" {IThumbnailCachePrimer}
#Import export ".\IThumbnailCapture.ahk" {IThumbnailCapture}
#Import export ".\IThumbnailHandlerFactory.ahk" {IThumbnailHandlerFactory}
#Import export ".\IThumbnailProvider.ahk" {IThumbnailProvider}
#Import export ".\IThumbnailSettings.ahk" {IThumbnailSettings}
#Import export ".\IThumbnailStreamCache.ahk" {IThumbnailStreamCache}
#Import export ".\ITrackShellMenu.ahk" {ITrackShellMenu}
#Import export ".\ITranscodeImage.ahk" {ITranscodeImage}
#Import export ".\ITransferAdviseSink.ahk" {ITransferAdviseSink}
#Import export ".\ITransferDestination.ahk" {ITransferDestination}
#Import export ".\ITransferMediumItem.ahk" {ITransferMediumItem}
#Import export ".\ITransferSource.ahk" {ITransferSource}
#Import export ".\ITravelEntry.ahk" {ITravelEntry}
#Import export ".\ITravelLog.ahk" {ITravelLog}
#Import export ".\ITravelLogClient.ahk" {ITravelLogClient}
#Import export ".\ITravelLogEntry.ahk" {ITravelLogEntry}
#Import export ".\ITravelLogStg.ahk" {ITravelLogStg}
#Import export ".\ITrayDeskBand.ahk" {ITrayDeskBand}
#Import export ".\IURLSearchHook.ahk" {IURLSearchHook}
#Import export ".\IURLSearchHook2.ahk" {IURLSearchHook2}
#Import export ".\IURL_INVOKECOMMAND_FLAGS.ahk" {IURL_INVOKECOMMAND_FLAGS}
#Import export ".\IURL_SETURL_FLAGS.ahk" {IURL_SETURL_FLAGS}
#Import export ".\IUniformResourceLocatorA.ahk" {IUniformResourceLocatorA}
#Import export ".\IUniformResourceLocatorW.ahk" {IUniformResourceLocatorW}
#Import export ".\IUpdateIDList.ahk" {IUpdateIDList}
#Import export ".\IUseToBrowseItem.ahk" {IUseToBrowseItem}
#Import export ".\IUserAccountChangeCallback.ahk" {IUserAccountChangeCallback}
#Import export ".\IUserNotification.ahk" {IUserNotification}
#Import export ".\IUserNotification2.ahk" {IUserNotification2}
#Import export ".\IUserNotificationCallback.ahk" {IUserNotificationCallback}
#Import export ".\IViewStateIdentityItem.ahk" {IViewStateIdentityItem}
#Import export ".\IVirtualDesktopManager.ahk" {IVirtualDesktopManager}
#Import export ".\IVisualProperties.ahk" {IVisualProperties}
#Import export ".\IWebBrowser.ahk" {IWebBrowser}
#Import export ".\IWebBrowser2.ahk" {IWebBrowser2}
#Import export ".\IWebBrowserApp.ahk" {IWebBrowserApp}
#Import export ".\IWebWizardExtension.ahk" {IWebWizardExtension}
#Import export ".\IWebWizardHost.ahk" {IWebWizardHost}
#Import export ".\IWebWizardHost2.ahk" {IWebWizardHost2}
#Import export ".\IWizardExtension.ahk" {IWizardExtension}
#Import export ".\IWizardSite.ahk" {IWizardSite}
#Import export ".\ImageProperties.ahk" {ImageProperties}
#Import export ".\ImageRecompress.ahk" {ImageRecompress}
#Import export ".\ImageTranscode.ahk" {ImageTranscode}
#Import export ".\InputPanelConfiguration.ahk" {InputPanelConfiguration}
#Import export ".\InternetExplorer.ahk" {InternetExplorer}
#Import export ".\InternetExplorerMedium.ahk" {InternetExplorerMedium}
#Import export ".\InternetPrintOrdering.ahk" {InternetPrintOrdering}
#Import export ".\KF_CATEGORY.ahk" {KF_CATEGORY}
#Import export ".\KNOWNDESTCATEGORY.ahk" {KNOWNDESTCATEGORY}
#Import export ".\KNOWNFOLDER_DEFINITION.ahk" {KNOWNFOLDER_DEFINITION}
#Import export ".\KNOWN_FOLDER_FLAG.ahk" {KNOWN_FOLDER_FLAG}
#Import export ".\KnownFolderManager.ahk" {KnownFolderManager}
#Import export ".\LIBRARYFOLDERFILTER.ahk" {LIBRARYFOLDERFILTER}
#Import export ".\LIBRARYMANAGEDIALOGOPTIONS.ahk" {LIBRARYMANAGEDIALOGOPTIONS}
#Import export ".\LIBRARYOPTIONFLAGS.ahk" {LIBRARYOPTIONFLAGS}
#Import export ".\LIBRARYSAVEFLAGS.ahk" {LIBRARYSAVEFLAGS}
#Import export ".\LPFNDFMCALLBACK.ahk" {LPFNDFMCALLBACK}
#Import export ".\LPFNVIEWCALLBACK.ahk" {LPFNVIEWCALLBACK}
#Import export ".\LocalThumbnailCache.ahk" {LocalThumbnailCache}
#Import export ".\MENUBANDHANDLERCID.ahk" {MENUBANDHANDLERCID}
#Import export ".\MENUPOPUPPOPUPFLAGS.ahk" {MENUPOPUPPOPUPFLAGS}
#Import export ".\MENUPOPUPSELECT.ahk" {MENUPOPUPSELECT}
#Import export ".\MERGE_UPDATE_STATUS.ahk" {MERGE_UPDATE_STATUS}
#Import export ".\MIMEASSOCIATIONDIALOG_IN_FLAGS.ahk" {MIMEASSOCIATIONDIALOG_IN_FLAGS}
#Import export ".\MM_FLAGS.ahk" {MM_FLAGS}
#Import export ".\MONITOR_APP_VISIBILITY.ahk" {MONITOR_APP_VISIBILITY}
#Import export ".\MULTIKEYHELPA.ahk" {MULTIKEYHELPA}
#Import export ".\MULTIKEYHELPW.ahk" {MULTIKEYHELPW}
#Import export ".\MailRecipient.ahk" {MailRecipient}
#Import export ".\MergedCategorizer.ahk" {MergedCategorizer}
#Import export ".\NAMESPACEWALKFLAG.ahk" {NAMESPACEWALKFLAG}
#Import export ".\NATIVE_DISPLAY_ORIENTATION.ahk" {NATIVE_DISPLAY_ORIENTATION}
#Import export ".\NC_ADDRESS.ahk" {NC_ADDRESS}
#Import export ".\NEWCPLINFOA.ahk" {NEWCPLINFOA}
#Import export ".\NEWCPLINFOW.ahk" {NEWCPLINFOW}
#Import export ".\NOTIFYICONDATAA.ahk" {NOTIFYICONDATAA}
#Import export ".\NOTIFYICONDATAW.ahk" {NOTIFYICONDATAW}
#Import export ".\NOTIFYICONIDENTIFIER.ahk" {NOTIFYICONIDENTIFIER}
#Import export ".\NOTIFY_ICON_DATA_FLAGS.ahk" {NOTIFY_ICON_DATA_FLAGS}
#Import export ".\NOTIFY_ICON_INFOTIP_FLAGS.ahk" {NOTIFY_ICON_INFOTIP_FLAGS}
#Import export ".\NOTIFY_ICON_MESSAGE.ahk" {NOTIFY_ICON_MESSAGE}
#Import export ".\NOTIFY_ICON_STATE.ahk" {NOTIFY_ICON_STATE}
#Import export ".\NPCredentialProvider.ahk" {NPCredentialProvider}
#Import export ".\NRESARRAY.ahk" {NRESARRAY}
#Import export ".\NSTCCUSTOMDRAW.ahk" {NSTCCUSTOMDRAW}
#Import export ".\NSTCFOLDERCAPABILITIES.ahk" {NSTCFOLDERCAPABILITIES}
#Import export ".\NSTCGNI.ahk" {NSTCGNI}
#Import export ".\NSTCSTYLE2.ahk" {NSTCSTYLE2}
#Import export ".\NT_CONSOLE_PROPS.ahk" {NT_CONSOLE_PROPS}
#Import export ".\NT_FE_CONSOLE_PROPS.ahk" {NT_FE_CONSOLE_PROPS}
#Import export ".\NWMF.ahk" {NWMF}
#Import export ".\NamespaceTreeControl.ahk" {NamespaceTreeControl}
#Import export ".\NamespaceWalker.ahk" {NamespaceWalker}
#Import export ".\NetworkConnections.ahk" {NetworkConnections}
#Import export ".\NetworkExplorerFolder.ahk" {NetworkExplorerFolder}
#Import export ".\NetworkPlaces.ahk" {NetworkPlaces}
#Import export ".\NewProcessCauseConstants.ahk" {NewProcessCauseConstants}
#Import export ".\OPENASINFO.ahk" {OPENASINFO}
#Import export ".\OPEN_AS_INFO_FLAGS.ahk" {OPEN_AS_INFO_FLAGS}
#Import export ".\OPEN_PRINTER_PROPS_INFOA.ahk" {OPEN_PRINTER_PROPS_INFOA}
#Import export ".\OPEN_PRINTER_PROPS_INFOW.ahk" {OPEN_PRINTER_PROPS_INFOW}
#Import export ".\OS.ahk" {OS}
#Import export ".\OfflineFolderStatus.ahk" {OfflineFolderStatus}
#Import export ".\OnexCredentialProvider.ahk" {OnexCredentialProvider}
#Import export ".\OnexPlapSmartcardCredentialProvider.ahk" {OnexPlapSmartcardCredentialProvider}
#Import export ".\OpenControlPanel.ahk" {OpenControlPanel}
#Import export ".\PACKAGE_EXECUTION_STATE.ahk" {PACKAGE_EXECUTION_STATE}
#Import export ".\PAPPCONSTRAIN_CHANGE_ROUTINE.ahk" {PAPPCONSTRAIN_CHANGE_ROUTINE}
#Import export ".\PAPPCONSTRAIN_REGISTRATION.ahk" {PAPPCONSTRAIN_REGISTRATION}
#Import export ".\PAPPSTATE_CHANGE_ROUTINE.ahk" {PAPPSTATE_CHANGE_ROUTINE}
#Import export ".\PAPPSTATE_REGISTRATION.ahk" {PAPPSTATE_REGISTRATION}
#Import export ".\PARSEDURLA.ahk" {PARSEDURLA}
#Import export ".\PARSEDURLW.ahk" {PARSEDURLW}
#Import export ".\PATHCCH_OPTIONS.ahk" {PATHCCH_OPTIONS}
#Import export ".\PCS_RET.ahk" {PCS_RET}
#Import export ".\PERSIST_FOLDER_TARGET_INFO.ahk" {PERSIST_FOLDER_TARGET_INFO}
#Import export ".\PFNCANSHAREFOLDERW.ahk" {PFNCANSHAREFOLDERW}
#Import export ".\PFNSHOWSHAREFOLDERUIW.ahk" {PFNSHOWSHAREFOLDERUIW}
#Import export ".\PIDISF_FLAGS.ahk" {PIDISF_FLAGS}
#Import export ".\PIDISM_OPTIONS.ahk" {PIDISM_OPTIONS}
#Import export ".\PIDISR_INFO.ahk" {PIDISR_INFO}
#Import export ".\PID_INTSITE.ahk" {PID_INTSITE}
#Import export ".\PID_IS.ahk" {PID_IS}
#Import export ".\PINLogonCredentialProvider.ahk" {PINLogonCredentialProvider}
#Import export ".\PREVIEWHANDLERFRAMEINFO.ahk" {PREVIEWHANDLERFRAMEINFO}
#Import export ".\PRF_FLAGS.ahk" {PRF_FLAGS}
#Import export ".\PROFILEINFOA.ahk" {PROFILEINFOA}
#Import export ".\PROFILEINFOW.ahk" {PROFILEINFOW}
#Import export ".\PUBAPPINFO.ahk" {PUBAPPINFO}
#Import export ".\PUBAPPINFOFLAGS.ahk" {PUBAPPINFOFLAGS}
#Import export ".\PackageDebugSettings.ahk" {PackageDebugSettings}
#Import export ".\PasswordCredentialProvider.ahk" {PasswordCredentialProvider}
#Import export ".\PreviousVersions.ahk" {PreviousVersions}
#Import export ".\PropertiesUI.ahk" {PropertiesUI}
#Import export ".\PublishDropTarget.ahk" {PublishDropTarget}
#Import export ".\PublishingWizard.ahk" {PublishingWizard}
#Import export ".\QCMINFO.ahk" {QCMINFO}
#Import export ".\QCMINFO_IDMAP.ahk" {QCMINFO_IDMAP}
#Import export ".\QCMINFO_IDMAP_PLACEMENT.ahk" {QCMINFO_IDMAP_PLACEMENT}
#Import export ".\QITAB.ahk" {QITAB}
#Import export ".\QITIPF_FLAGS.ahk" {QITIPF_FLAGS}
#Import export ".\QUERY_USER_NOTIFICATION_STATE.ahk" {QUERY_USER_NOTIFICATION_STATE}
#Import export ".\QueryCancelAutoPlay.ahk" {QueryCancelAutoPlay}
#Import export ".\RASProvider.ahk" {RASProvider}
#Import export ".\RESTRICTIONS.ahk" {RESTRICTIONS}
#Import export ".\RefreshConstants.ahk" {RefreshConstants}
#Import export ".\SCALE_CHANGE_FLAGS.ahk" {SCALE_CHANGE_FLAGS}
#Import export ".\SCNRT_STATUS.ahk" {SCNRT_STATUS}
#Import export ".\SECURELOCKCODE.ahk" {SECURELOCKCODE}
#Import export ".\SFBS_FLAGS.ahk" {SFBS_FLAGS}
#Import export ".\SFVM_HELPTOPIC_DATA.ahk" {SFVM_HELPTOPIC_DATA}
#Import export ".\SFVM_MESSAGE_ID.ahk" {SFVM_MESSAGE_ID}
#Import export ".\SFVM_PROPPAGE_DATA.ahk" {SFVM_PROPPAGE_DATA}
#Import export ".\SFVS_SELECT.ahk" {SFVS_SELECT}
#Import export ".\SFV_CREATE.ahk" {SFV_CREATE}
#Import export ".\SFV_SETITEMPOS.ahk" {SFV_SETITEMPOS}
#Import export ".\SHARD.ahk" {SHARD}
#Import export ".\SHARDAPPIDINFO.ahk" {SHARDAPPIDINFO}
#Import export ".\SHARDAPPIDINFOIDLIST.ahk" {SHARDAPPIDINFOIDLIST}
#Import export ".\SHARDAPPIDINFOLINK.ahk" {SHARDAPPIDINFOLINK}
#Import export ".\SHARE_ROLE.ahk" {SHARE_ROLE}
#Import export ".\SHCNE_ID.ahk" {SHCNE_ID}
#Import export ".\SHCNF_FLAGS.ahk" {SHCNF_FLAGS}
#Import export ".\SHCNRF_SOURCE.ahk" {SHCNRF_SOURCE}
#Import export ".\SHCOLUMNDATA.ahk" {SHCOLUMNDATA}
#Import export ".\SHCOLUMNINFO.ahk" {SHCOLUMNINFO}
#Import export ".\SHCOLUMNINIT.ahk" {SHCOLUMNINIT}
#Import export ".\SHCREATEPROCESSINFOW.ahk" {SHCREATEPROCESSINFOW}
#Import export ".\SHChangeDWORDAsIDList.ahk" {SHChangeDWORDAsIDList}
#Import export ".\SHChangeNotifyEntry.ahk" {SHChangeNotifyEntry}
#Import export ".\SHChangeProductKeyAsIDList.ahk" {SHChangeProductKeyAsIDList}
#Import export ".\SHChangeUpdateImageIDList.ahk" {SHChangeUpdateImageIDList}
#Import export ".\SHDESCRIPTIONID.ahk" {SHDESCRIPTIONID}
#Import export ".\SHDID_ID.ahk" {SHDID_ID}
#Import export ".\SHDRAGIMAGE.ahk" {SHDRAGIMAGE}
#Import export ".\SHELLBROWSERSHOWCONTROL.ahk" {SHELLBROWSERSHOWCONTROL}
#Import export ".\SHELLEXECUTEINFOA.ahk" {SHELLEXECUTEINFOA}
#Import export ".\SHELLEXECUTEINFOW.ahk" {SHELLEXECUTEINFOW}
#Import export ".\SHELLFLAGSTATE.ahk" {SHELLFLAGSTATE}
#Import export ".\SHELLSTATEA.ahk" {SHELLSTATEA}
#Import export ".\SHELLSTATEW.ahk" {SHELLSTATEW}
#Import export ".\SHELL_AUTOCOMPLETE_FLAGS.ahk" {SHELL_AUTOCOMPLETE_FLAGS}
#Import export ".\SHELL_ITEM_RESOURCE.ahk" {SHELL_ITEM_RESOURCE}
#Import export ".\SHELL_LINK_DATA_FLAGS.ahk" {SHELL_LINK_DATA_FLAGS}
#Import export ".\SHELL_UI_COMPONENT.ahk" {SHELL_UI_COMPONENT}
#Import export ".\SHFILEINFOA.ahk" {SHFILEINFOA}
#Import export ".\SHFILEINFOW.ahk" {SHFILEINFOW}
#Import export ".\SHFILEOPSTRUCTA.ahk" {SHFILEOPSTRUCTA}
#Import export ".\SHFILEOPSTRUCTW.ahk" {SHFILEOPSTRUCTW}
#Import export ".\SHFMT_ID.ahk" {SHFMT_ID}
#Import export ".\SHFMT_OPT.ahk" {SHFMT_OPT}
#Import export ".\SHFMT_RET.ahk" {SHFMT_RET}
#Import export ".\SHFOLDERCUSTOMSETTINGS.ahk" {SHFOLDERCUSTOMSETTINGS}
#Import export ".\SHGDFIL_FORMAT.ahk" {SHGDFIL_FORMAT}
#Import export ".\SHGDNF.ahk" {SHGDNF}
#Import export ".\SHGFI_FLAGS.ahk" {SHGFI_FLAGS}
#Import export ".\SHGFP_TYPE.ahk" {SHGFP_TYPE}
#Import export ".\SHGLOBALCOUNTER.ahk" {SHGLOBALCOUNTER}
#Import export ".\SHGSI_FLAGS.ahk" {SHGSI_FLAGS}
#Import export ".\SHNAMEMAPPINGA.ahk" {SHNAMEMAPPINGA}
#Import export ".\SHNAMEMAPPINGW.ahk" {SHNAMEMAPPINGW}
#Import export ".\SHOP_TYPE.ahk" {SHOP_TYPE}
#Import export ".\SHQUERYRBINFO.ahk" {SHQUERYRBINFO}
#Import export ".\SHREGDEL_FLAGS.ahk" {SHREGDEL_FLAGS}
#Import export ".\SHREGENUM_FLAGS.ahk" {SHREGENUM_FLAGS}
#Import export ".\SHSTOCKICONID.ahk" {SHSTOCKICONID}
#Import export ".\SHSTOCKICONINFO.ahk" {SHSTOCKICONINFO}
#Import export ".\SIATTRIBFLAGS.ahk" {SIATTRIBFLAGS}
#Import export ".\SIGDN.ahk" {SIGDN}
#Import export ".\SIIGBF.ahk" {SIIGBF}
#Import export ".\SLGP_FLAGS.ahk" {SLGP_FLAGS}
#Import export ".\SLOWAPPINFO.ahk" {SLOWAPPINFO}
#Import export ".\SLR_FLAGS.ahk" {SLR_FLAGS}
#Import export ".\SMCSHCHANGENOTIFYSTRUCT.ahk" {SMCSHCHANGENOTIFYSTRUCT}
#Import export ".\SMDATA.ahk" {SMDATA}
#Import export ".\SMINFO.ahk" {SMINFO}
#Import export ".\SMINFOFLAGS.ahk" {SMINFOFLAGS}
#Import export ".\SMINFOMASK.ahk" {SMINFOMASK}
#Import export ".\SMINFOTYPE.ahk" {SMINFOTYPE}
#Import export ".\SORTCOLUMN.ahk" {SORTCOLUMN}
#Import export ".\SORTDIRECTION.ahk" {SORTDIRECTION}
#Import export ".\SORT_ORDER_TYPE.ahk" {SORT_ORDER_TYPE}
#Import export ".\SPACTION.ahk" {SPACTION}
#Import export ".\SPTEXT.ahk" {SPTEXT}
#Import export ".\SSF_MASK.ahk" {SSF_MASK}
#Import export ".\STGOP.ahk" {STGOP}
#Import export ".\STORAGE_PROVIDER_FILE_FLAGS.ahk" {STORAGE_PROVIDER_FILE_FLAGS}
#Import export ".\STPFLAG.ahk" {STPFLAG}
#Import export ".\SUBCLASSPROC.ahk" {SUBCLASSPROC}
#Import export ".\SV2CVW2_PARAMS.ahk" {SV2CVW2_PARAMS}
#Import export ".\SVUIA_STATUS.ahk" {SVUIA_STATUS}
#Import export ".\SYNCMGRERRORFLAGS.ahk" {SYNCMGRERRORFLAGS}
#Import export ".\SYNCMGRFLAG.ahk" {SYNCMGRFLAG}
#Import export ".\SYNCMGRHANDLERFLAGS.ahk" {SYNCMGRHANDLERFLAGS}
#Import export ".\SYNCMGRHANDLERINFO.ahk" {SYNCMGRHANDLERINFO}
#Import export ".\SYNCMGRINVOKEFLAGS.ahk" {SYNCMGRINVOKEFLAGS}
#Import export ".\SYNCMGRITEM.ahk" {SYNCMGRITEM}
#Import export ".\SYNCMGRITEMFLAGS.ahk" {SYNCMGRITEMFLAGS}
#Import export ".\SYNCMGRITEMSTATE.ahk" {SYNCMGRITEMSTATE}
#Import export ".\SYNCMGRLOGERRORINFO.ahk" {SYNCMGRLOGERRORINFO}
#Import export ".\SYNCMGRLOGLEVEL.ahk" {SYNCMGRLOGLEVEL}
#Import export ".\SYNCMGRPROGRESSITEM.ahk" {SYNCMGRPROGRESSITEM}
#Import export ".\SYNCMGRREGISTERFLAGS.ahk" {SYNCMGRREGISTERFLAGS}
#Import export ".\SYNCMGRSTATUS.ahk" {SYNCMGRSTATUS}
#Import export ".\SYNCMGR_CANCEL_REQUEST.ahk" {SYNCMGR_CANCEL_REQUEST}
#Import export ".\SYNCMGR_CONFLICT_ID_INFO.ahk" {SYNCMGR_CONFLICT_ID_INFO}
#Import export ".\SYNCMGR_CONFLICT_ITEM_TYPE.ahk" {SYNCMGR_CONFLICT_ITEM_TYPE}
#Import export ".\SYNCMGR_CONTROL_FLAGS.ahk" {SYNCMGR_CONTROL_FLAGS}
#Import export ".\SYNCMGR_EVENT_FLAGS.ahk" {SYNCMGR_EVENT_FLAGS}
#Import export ".\SYNCMGR_EVENT_LEVEL.ahk" {SYNCMGR_EVENT_LEVEL}
#Import export ".\SYNCMGR_HANDLER_CAPABILITIES.ahk" {SYNCMGR_HANDLER_CAPABILITIES}
#Import export ".\SYNCMGR_HANDLER_POLICIES.ahk" {SYNCMGR_HANDLER_POLICIES}
#Import export ".\SYNCMGR_HANDLER_TYPE.ahk" {SYNCMGR_HANDLER_TYPE}
#Import export ".\SYNCMGR_ITEM_CAPABILITIES.ahk" {SYNCMGR_ITEM_CAPABILITIES}
#Import export ".\SYNCMGR_ITEM_POLICIES.ahk" {SYNCMGR_ITEM_POLICIES}
#Import export ".\SYNCMGR_PRESENTER_CHOICE.ahk" {SYNCMGR_PRESENTER_CHOICE}
#Import export ".\SYNCMGR_PRESENTER_NEXT_STEP.ahk" {SYNCMGR_PRESENTER_NEXT_STEP}
#Import export ".\SYNCMGR_PROGRESS_STATUS.ahk" {SYNCMGR_PROGRESS_STATUS}
#Import export ".\SYNCMGR_RESOLUTION_ABILITIES.ahk" {SYNCMGR_RESOLUTION_ABILITIES}
#Import export ".\SYNCMGR_RESOLUTION_FEEDBACK.ahk" {SYNCMGR_RESOLUTION_FEEDBACK}
#Import export ".\SYNCMGR_SYNC_CONTROL_FLAGS.ahk" {SYNCMGR_SYNC_CONTROL_FLAGS}
#Import export ".\SYNCMGR_UPDATE_REASON.ahk" {SYNCMGR_UPDATE_REASON}
#Import export ".\ScheduledTasks.ahk" {ScheduledTasks}
#Import export ".\SearchFolderItemFactory.ahk" {SearchFolderItemFactory}
#Import export ".\SecureLockIconConstants.ahk" {SecureLockIconConstants}
#Import export ".\SharedBitmap.ahk" {SharedBitmap}
#Import export ".\SharingConfigurationManager.ahk" {SharingConfigurationManager}
#Import export ".\Shell.ahk" {Shell}
#Import export ".\ShellBrowserWindow.ahk" {ShellBrowserWindow}
#Import export ".\ShellDesktop.ahk" {ShellDesktop}
#Import export ".\ShellDispatchInproc.ahk" {ShellDispatchInproc}
#Import export ".\ShellFSFolder.ahk" {ShellFSFolder}
#Import export ".\ShellFolderItem.ahk" {ShellFolderItem}
#Import export ".\ShellFolderView.ahk" {ShellFolderView}
#Import export ".\ShellFolderViewOC.ahk" {ShellFolderViewOC}
#Import export ".\ShellFolderViewOptions.ahk" {ShellFolderViewOptions}
#Import export ".\ShellImageDataFactory.ahk" {ShellImageDataFactory}
#Import export ".\ShellItem.ahk" {ShellItem}
#Import export ".\ShellLibrary.ahk" {ShellLibrary}
#Import export ".\ShellLink.ahk" {ShellLink}
#Import export ".\ShellLinkObject.ahk" {ShellLinkObject}
#Import export ".\ShellNameSpace.ahk" {ShellNameSpace}
#Import export ".\ShellSpecialFolderConstants.ahk" {ShellSpecialFolderConstants}
#Import export ".\ShellUIHelper.ahk" {ShellUIHelper}
#Import export ".\ShellWindowFindWindowOptions.ahk" {ShellWindowFindWindowOptions}
#Import export ".\ShellWindowTypeConstants.ahk" {ShellWindowTypeConstants}
#Import export ".\ShellWindows.ahk" {ShellWindows}
#Import export ".\ShowInputPaneAnimationCoordinator.ahk" {ShowInputPaneAnimationCoordinator}
#Import export ".\SimpleConflictPresenter.ahk" {SimpleConflictPresenter}
#Import export ".\SizeCategorizer.ahk" {SizeCategorizer}
#Import export ".\SmartcardCredentialProvider.ahk" {SmartcardCredentialProvider}
#Import export ".\SmartcardPinProvider.ahk" {SmartcardPinProvider}
#Import export ".\SmartcardReaderSelectionProvider.ahk" {SmartcardReaderSelectionProvider}
#Import export ".\SmartcardWinRTProvider.ahk" {SmartcardWinRTProvider}
#Import export ".\StartMenuPin.ahk" {StartMenuPin}
#Import export ".\StorageProviderBanners.ahk" {StorageProviderBanners}
#Import export ".\SuspensionDependencyManager.ahk" {SuspensionDependencyManager}
#Import export ".\SyncMgr.ahk" {SyncMgr}
#Import export ".\SyncMgrClient.ahk" {SyncMgrClient}
#Import export ".\SyncMgrControl.ahk" {SyncMgrControl}
#Import export ".\SyncMgrFolder.ahk" {SyncMgrFolder}
#Import export ".\SyncMgrScheduleWizard.ahk" {SyncMgrScheduleWizard}
#Import export ".\SyncResultsFolder.ahk" {SyncResultsFolder}
#Import export ".\SyncSetupFolder.ahk" {SyncSetupFolder}
#Import export ".\TBINFO.ahk" {TBINFO}
#Import export ".\TBPFLAG.ahk" {TBPFLAG}
#Import export ".\THUMBBUTTON.ahk" {THUMBBUTTON}
#Import export ".\THUMBBUTTONFLAGS.ahk" {THUMBBUTTONFLAGS}
#Import export ".\THUMBBUTTONMASK.ahk" {THUMBBUTTONMASK}
#Import export ".\TI_FLAGS.ahk" {TI_FLAGS}
#Import export ".\TLENUMF.ahk" {TLENUMF}
#Import export ".\TOOLBARITEM.ahk" {TOOLBARITEM}
#Import export ".\TRANSLATEURL_IN_FLAGS.ahk" {TRANSLATEURL_IN_FLAGS}
#Import export ".\TaskbarList.ahk" {TaskbarList}
#Import export ".\ThumbnailStreamCache.ahk" {ThumbnailStreamCache}
#Import export ".\ThumbnailStreamCacheOptions.ahk" {ThumbnailStreamCacheOptions}
#Import export ".\TimeCategorizer.ahk" {TimeCategorizer}
#Import export ".\TrackShellMenu.ahk" {TrackShellMenu}
#Import export ".\TrayBandSiteService.ahk" {TrayBandSiteService}
#Import export ".\TrayDeskBand.ahk" {TrayDeskBand}
#Import export ".\UNDOCK_REASON.ahk" {UNDOCK_REASON}
#Import export ".\URLASSOCIATIONDIALOG_IN_FLAGS.ahk" {URLASSOCIATIONDIALOG_IN_FLAGS}
#Import export ".\URLINVOKECOMMANDINFOA.ahk" {URLINVOKECOMMANDINFOA}
#Import export ".\URLINVOKECOMMANDINFOW.ahk" {URLINVOKECOMMANDINFOW}
#Import export ".\URLIS.ahk" {URLIS}
#Import export ".\URL_PART.ahk" {URL_PART}
#Import export ".\URL_SCHEME.ahk" {URL_SCHEME}
#Import export ".\UserNotification.ahk" {UserNotification}
#Import export ".\V1PasswordCredentialProvider.ahk" {V1PasswordCredentialProvider}
#Import export ".\V1SmartcardCredentialProvider.ahk" {V1SmartcardCredentialProvider}
#Import export ".\V1WinBioCredentialProvider.ahk" {V1WinBioCredentialProvider}
#Import export ".\VALIDATEUNC_OPTION.ahk" {VALIDATEUNC_OPTION}
#Import export ".\VPCOLORFLAGS.ahk" {VPCOLORFLAGS}
#Import export ".\VPWATERMARKFLAGS.ahk" {VPWATERMARKFLAGS}
#Import export ".\VaultProvider.ahk" {VaultProvider}
#Import export ".\VirtualDesktopManager.ahk" {VirtualDesktopManager}
#Import export ".\WINDOWDATA.ahk" {WINDOWDATA}
#Import export ".\WTS_ALPHATYPE.ahk" {WTS_ALPHATYPE}
#Import export ".\WTS_CACHEFLAGS.ahk" {WTS_CACHEFLAGS}
#Import export ".\WTS_CONTEXTFLAGS.ahk" {WTS_CONTEXTFLAGS}
#Import export ".\WTS_FLAGS.ahk" {WTS_FLAGS}
#Import export ".\WTS_THUMBNAILID.ahk" {WTS_THUMBNAILID}
#Import export ".\WebBrowser.ahk" {WebBrowser}
#Import export ".\WebBrowser_V1.ahk" {WebBrowser_V1}
#Import export ".\WebWizardHost.ahk" {WebWizardHost}
#Import export ".\WinBioCredentialProvider.ahk" {WinBioCredentialProvider}
#Import export ".\_BROWSERFRAMEOPTIONS.ahk" {_BROWSERFRAMEOPTIONS}
#Import export ".\_CDBE_ACTIONS.ahk" {_CDBE_ACTIONS}
#Import export ".\_EXPCMDFLAGS.ahk" {_EXPCMDFLAGS}
#Import export ".\_EXPCMDSTATE.ahk" {_EXPCMDSTATE}
#Import export ".\_EXPLORERPANESTATE.ahk" {_EXPLORERPANESTATE}
#Import export ".\_EXPPS.ahk" {_EXPPS}
#Import export ".\_KF_DEFINITION_FLAGS.ahk" {_KF_DEFINITION_FLAGS}
#Import export ".\_KF_REDIRECTION_CAPABILITIES.ahk" {_KF_REDIRECTION_CAPABILITIES}
#Import export ".\_KF_REDIRECT_FLAGS.ahk" {_KF_REDIRECT_FLAGS}
#Import export ".\_NMCII_FLAGS.ahk" {_NMCII_FLAGS}
#Import export ".\_NMCSAEI_FLAGS.ahk" {_NMCSAEI_FLAGS}
#Import export ".\_NSTCECLICKTYPE.ahk" {_NSTCECLICKTYPE}
#Import export ".\_NSTCEHITTEST.ahk" {_NSTCEHITTEST}
#Import export ".\_NSTCITEMSTATE.ahk" {_NSTCITEMSTATE}
#Import export ".\_NSTCROOTSTYLE.ahk" {_NSTCROOTSTYLE}
#Import export ".\_NSTCSTYLE.ahk" {_NSTCSTYLE}
#Import export ".\_OPPROGDLGF.ahk" {_OPPROGDLGF}
#Import export ".\_PDMODE.ahk" {_PDMODE}
#Import export ".\_SHCONTF.ahk" {_SHCONTF}
#Import export ".\_SICHINTF.ahk" {_SICHINTF}
#Import export ".\_SPBEGINF.ahk" {_SPBEGINF}
#Import export ".\_SPINITF.ahk" {_SPINITF}
#Import export ".\_SV3CVW3_FLAGS.ahk" {_SV3CVW3_FLAGS}
#Import export ".\_SVGIO.ahk" {_SVGIO}
#Import export ".\_SVSIF.ahk" {_SVSIF}
#Import export ".\_TRANSFER_ADVISE_STATE.ahk" {_TRANSFER_ADVISE_STATE}
#Import export ".\_TRANSFER_SOURCE_FLAGS.ahk" {_TRANSFER_SOURCE_FLAGS}
