#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\Guid.ahk" { Guid }
#Import "..\..\Foundation\HRESULT.ahk" { HRESULT }
#Import "Common\ITEMIDLIST.ahk" { ITEMIDLIST }
#Import ".\IShellItem.ahk" { IShellItem }
#Import "..\..\System\Com\IUnknown.ahk" { IUnknown }

/**
 * Exposes methods that hold items from a data object.
 * @see https://learn.microsoft.com/windows/win32/api/shobjidl/nn-shobjidl-iresultsfolder
 * @namespace Windows.Win32.UI.Shell
 */
export default struct IResultsFolder extends IUnknown {
    /**
     * The interface identifier for IResultsFolder
     * @type {Guid}
     */
    static IID := Guid("{96e5ae6d-6ae1-4b1c-900c-c6480eaa8828}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for IResultsFolder interfaces
    */
    struct Vtbl extends IUnknown.Vtbl {
        AddItem      : IntPtr
        AddIDList    : IntPtr
        RemoveItem   : IntPtr
        RemoveIDList : IntPtr
        RemoveAll    : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := IResultsFolder.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * Adds an item to a results folder.
     * @param {IShellItem} psi Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nn-shobjidl_core-ishellitem">IShellItem</a>*</b>
     * 
     * A pointer to an <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nn-shobjidl_core-ishellitem">IShellItem</a>.
     * @returns {HRESULT} Type: <b>HRESULT</b>
     * 
     * If this method succeeds, it returns <b>S_OK</b>. Otherwise, it returns an <b>HRESULT</b> error code.
     * @see https://learn.microsoft.com/windows/win32/api/shobjidl/nf-shobjidl-iresultsfolder-additem
     */
    AddItem(psi) {
        result := ComCall(3, this, "ptr", psi, "HRESULT")
        return result
    }

    /**
     * Inserts a pointer to an item identifier list (PIDL) into a results folder.
     * @remarks
     * The PIDL received represents the item that was just added and is a unique representation of this item generated by this results folder. It is only valid when used in reference to this results folder and should not be combined with a PIDL to another folder, including the folder this item originally came from.
     * @param {Pointer<ITEMIDLIST>} pidl Type: <b>PCIDLIST_ABSOLUTE</b>
     * 
     * A pointer to the IDList of the given object relative to the Desktop.
     * @returns {Pointer<ITEMIDLIST>} Type: <b>PITEMID_CHILD*</b>
     * 
     * A PIDL consisting of 0 or 1 <a href="https://docs.microsoft.com/windows/desktop/api/shtypes/ns-shtypes-shitemid">SHITEMID</a> structures, relative to a parent folder. This parameter maybe <b>NULL</b>.
     * @see https://learn.microsoft.com/windows/win32/api/shobjidl/nf-shobjidl-iresultsfolder-addidlist
     */
    AddIDList(pidl) {
        result := ComCall(4, this, ITEMIDLIST.Ptr, pidl, "ptr*", &ppidlAdded := 0, "HRESULT")
        return ppidlAdded
    }

    /**
     * Removes an item from a results folder.
     * @param {IShellItem} psi Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nn-shobjidl_core-ishellitem">IShellItem</a>*</b>
     * 
     * A pointer to an <a href="https://docs.microsoft.com/windows/desktop/api/shobjidl_core/nn-shobjidl_core-ishellitem">IShellItem</a>.
     * @returns {HRESULT} Type: <b>HRESULT</b>
     * 
     * If this method succeeds, it returns <b>S_OK</b>. Otherwise, it returns an <b>HRESULT</b> error code.
     * @see https://learn.microsoft.com/windows/win32/api/shobjidl/nf-shobjidl-iresultsfolder-removeitem
     */
    RemoveItem(psi) {
        result := ComCall(5, this, "ptr", psi, "HRESULT")
        return result
    }

    /**
     * Removes a pointer to an item identifier list (PIDL) from a results folder.
     * @param {Pointer<ITEMIDLIST>} pidl Type: <b>PCIDLIST_ABSOLUTE</b>
     * 
     * A PIDL relative to the Desktop.
     * @returns {HRESULT} Type: <b>HRESULT</b>
     * 
     * If this method succeeds, it returns <b>S_OK</b>. Otherwise, it returns an <b>HRESULT</b> error code.
     * @see https://learn.microsoft.com/windows/win32/api/shobjidl/nf-shobjidl-iresultsfolder-removeidlist
     */
    RemoveIDList(pidl) {
        result := ComCall(6, this, ITEMIDLIST.Ptr, pidl, "HRESULT")
        return result
    }

    /**
     * Removes all items from a results folder.
     * @returns {HRESULT} Type: <b>HRESULT</b>
     * 
     * If this method succeeds, it returns <b>S_OK</b>. Otherwise, it returns an <b>HRESULT</b> error code.
     * @see https://learn.microsoft.com/windows/win32/api/shobjidl/nf-shobjidl-iresultsfolder-removeall
     */
    RemoveAll() {
        result := ComCall(7, this, "HRESULT")
        return result
    }

    Query(iid) {
        if (IResultsFolder.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.AddItem := CallbackCreate(GetMethod(implObj, "AddItem"), flags, 2)
        this.vtbl.AddIDList := CallbackCreate(GetMethod(implObj, "AddIDList"), flags, 3)
        this.vtbl.RemoveItem := CallbackCreate(GetMethod(implObj, "RemoveItem"), flags, 2)
        this.vtbl.RemoveIDList := CallbackCreate(GetMethod(implObj, "RemoveIDList"), flags, 2)
        this.vtbl.RemoveAll := CallbackCreate(GetMethod(implObj, "RemoveAll"), flags, 1)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.AddItem)
        CallbackFree(this.vtbl.AddIDList)
        CallbackFree(this.vtbl.RemoveItem)
        CallbackFree(this.vtbl.RemoveIDList)
        CallbackFree(this.vtbl.RemoveAll)
    }
}
