#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Constants.ahk" {*}
#Import export ".\DISPIDSPRG.ahk" {DISPIDSPRG}
#Import export ".\DISPIDSPTSI.ahk" {DISPIDSPTSI}
#Import export ".\DISPID_SpeechAudio.ahk" {DISPID_SpeechAudio}
#Import export ".\DISPID_SpeechAudioBufferInfo.ahk" {DISPID_SpeechAudioBufferInfo}
#Import export ".\DISPID_SpeechAudioFormat.ahk" {DISPID_SpeechAudioFormat}
#Import export ".\DISPID_SpeechAudioStatus.ahk" {DISPID_SpeechAudioStatus}
#Import export ".\DISPID_SpeechBaseStream.ahk" {DISPID_SpeechBaseStream}
#Import export ".\DISPID_SpeechCustomStream.ahk" {DISPID_SpeechCustomStream}
#Import export ".\DISPID_SpeechDataKey.ahk" {DISPID_SpeechDataKey}
#Import export ".\DISPID_SpeechFileStream.ahk" {DISPID_SpeechFileStream}
#Import export ".\DISPID_SpeechGrammarRule.ahk" {DISPID_SpeechGrammarRule}
#Import export ".\DISPID_SpeechGrammarRuleState.ahk" {DISPID_SpeechGrammarRuleState}
#Import export ".\DISPID_SpeechGrammarRuleStateTransition.ahk" {DISPID_SpeechGrammarRuleStateTransition}
#Import export ".\DISPID_SpeechGrammarRuleStateTransitions.ahk" {DISPID_SpeechGrammarRuleStateTransitions}
#Import export ".\DISPID_SpeechGrammarRules.ahk" {DISPID_SpeechGrammarRules}
#Import export ".\DISPID_SpeechLexicon.ahk" {DISPID_SpeechLexicon}
#Import export ".\DISPID_SpeechLexiconProns.ahk" {DISPID_SpeechLexiconProns}
#Import export ".\DISPID_SpeechLexiconPronunciation.ahk" {DISPID_SpeechLexiconPronunciation}
#Import export ".\DISPID_SpeechLexiconWord.ahk" {DISPID_SpeechLexiconWord}
#Import export ".\DISPID_SpeechLexiconWords.ahk" {DISPID_SpeechLexiconWords}
#Import export ".\DISPID_SpeechMMSysAudio.ahk" {DISPID_SpeechMMSysAudio}
#Import export ".\DISPID_SpeechMemoryStream.ahk" {DISPID_SpeechMemoryStream}
#Import export ".\DISPID_SpeechObjectToken.ahk" {DISPID_SpeechObjectToken}
#Import export ".\DISPID_SpeechObjectTokenCategory.ahk" {DISPID_SpeechObjectTokenCategory}
#Import export ".\DISPID_SpeechObjectTokens.ahk" {DISPID_SpeechObjectTokens}
#Import export ".\DISPID_SpeechPhoneConverter.ahk" {DISPID_SpeechPhoneConverter}
#Import export ".\DISPID_SpeechPhraseAlternate.ahk" {DISPID_SpeechPhraseAlternate}
#Import export ".\DISPID_SpeechPhraseAlternates.ahk" {DISPID_SpeechPhraseAlternates}
#Import export ".\DISPID_SpeechPhraseBuilder.ahk" {DISPID_SpeechPhraseBuilder}
#Import export ".\DISPID_SpeechPhraseElement.ahk" {DISPID_SpeechPhraseElement}
#Import export ".\DISPID_SpeechPhraseElements.ahk" {DISPID_SpeechPhraseElements}
#Import export ".\DISPID_SpeechPhraseInfo.ahk" {DISPID_SpeechPhraseInfo}
#Import export ".\DISPID_SpeechPhraseProperties.ahk" {DISPID_SpeechPhraseProperties}
#Import export ".\DISPID_SpeechPhraseProperty.ahk" {DISPID_SpeechPhraseProperty}
#Import export ".\DISPID_SpeechPhraseReplacement.ahk" {DISPID_SpeechPhraseReplacement}
#Import export ".\DISPID_SpeechPhraseReplacements.ahk" {DISPID_SpeechPhraseReplacements}
#Import export ".\DISPID_SpeechPhraseRule.ahk" {DISPID_SpeechPhraseRule}
#Import export ".\DISPID_SpeechPhraseRules.ahk" {DISPID_SpeechPhraseRules}
#Import export ".\DISPID_SpeechRecoContext.ahk" {DISPID_SpeechRecoContext}
#Import export ".\DISPID_SpeechRecoContextEvents.ahk" {DISPID_SpeechRecoContextEvents}
#Import export ".\DISPID_SpeechRecoResult.ahk" {DISPID_SpeechRecoResult}
#Import export ".\DISPID_SpeechRecoResult2.ahk" {DISPID_SpeechRecoResult2}
#Import export ".\DISPID_SpeechRecoResultTimes.ahk" {DISPID_SpeechRecoResultTimes}
#Import export ".\DISPID_SpeechRecognizer.ahk" {DISPID_SpeechRecognizer}
#Import export ".\DISPID_SpeechRecognizerStatus.ahk" {DISPID_SpeechRecognizerStatus}
#Import export ".\DISPID_SpeechVoice.ahk" {DISPID_SpeechVoice}
#Import export ".\DISPID_SpeechVoiceEvent.ahk" {DISPID_SpeechVoiceEvent}
#Import export ".\DISPID_SpeechVoiceStatus.ahk" {DISPID_SpeechVoiceStatus}
#Import export ".\DISPID_SpeechWaveFormatEx.ahk" {DISPID_SpeechWaveFormatEx}
#Import export ".\DISPID_SpeechXMLRecoResult.ahk" {DISPID_SpeechXMLRecoResult}
#Import export ".\IEnumSpObjectTokens.ahk" {IEnumSpObjectTokens}
#Import export ".\ISpAudio.ahk" {ISpAudio}
#Import export ".\ISpCFGInterpreter.ahk" {ISpCFGInterpreter}
#Import export ".\ISpCFGInterpreterSite.ahk" {ISpCFGInterpreterSite}
#Import export ".\ISpContainerLexicon.ahk" {ISpContainerLexicon}
#Import export ".\ISpDataKey.ahk" {ISpDataKey}
#Import export ".\ISpDisplayAlternates.ahk" {ISpDisplayAlternates}
#Import export ".\ISpEnginePronunciation.ahk" {ISpEnginePronunciation}
#Import export ".\ISpErrorLog.ahk" {ISpErrorLog}
#Import export ".\ISpEventSink.ahk" {ISpEventSink}
#Import export ".\ISpEventSource.ahk" {ISpEventSource}
#Import export ".\ISpEventSource2.ahk" {ISpEventSource2}
#Import export ".\ISpGramCompBackend.ahk" {ISpGramCompBackend}
#Import export ".\ISpGrammarBuilder.ahk" {ISpGrammarBuilder}
#Import export ".\ISpGrammarBuilder2.ahk" {ISpGrammarBuilder2}
#Import export ".\ISpGrammarCompiler.ahk" {ISpGrammarCompiler}
#Import export ".\ISpITNProcessor.ahk" {ISpITNProcessor}
#Import export ".\ISpLexicon.ahk" {ISpLexicon}
#Import export ".\ISpMMSysAudio.ahk" {ISpMMSysAudio}
#Import export ".\ISpNotifyCallback.ahk" {ISpNotifyCallback}
#Import export ".\ISpNotifySink.ahk" {ISpNotifySink}
#Import export ".\ISpNotifySource.ahk" {ISpNotifySource}
#Import export ".\ISpNotifyTranslator.ahk" {ISpNotifyTranslator}
#Import export ".\ISpObjectToken.ahk" {ISpObjectToken}
#Import export ".\ISpObjectTokenCategory.ahk" {ISpObjectTokenCategory}
#Import export ".\ISpObjectTokenEnumBuilder.ahk" {ISpObjectTokenEnumBuilder}
#Import export ".\ISpObjectTokenInit.ahk" {ISpObjectTokenInit}
#Import export ".\ISpObjectWithToken.ahk" {ISpObjectWithToken}
#Import export ".\ISpPhoneConverter.ahk" {ISpPhoneConverter}
#Import export ".\ISpPhoneticAlphabetConverter.ahk" {ISpPhoneticAlphabetConverter}
#Import export ".\ISpPhoneticAlphabetSelection.ahk" {ISpPhoneticAlphabetSelection}
#Import export ".\ISpPhrase.ahk" {ISpPhrase}
#Import export ".\ISpPhrase2.ahk" {ISpPhrase2}
#Import export ".\ISpPhraseAlt.ahk" {ISpPhraseAlt}
#Import export ".\ISpPhraseBuilder.ahk" {ISpPhraseBuilder}
#Import export ".\ISpPrivateEngineCallEx.ahk" {ISpPrivateEngineCallEx}
#Import export ".\ISpProperties.ahk" {ISpProperties}
#Import export ".\ISpRecoContext.ahk" {ISpRecoContext}
#Import export ".\ISpRecoContext2.ahk" {ISpRecoContext2}
#Import export ".\ISpRecoGrammar.ahk" {ISpRecoGrammar}
#Import export ".\ISpRecoGrammar2.ahk" {ISpRecoGrammar2}
#Import export ".\ISpRecoResult.ahk" {ISpRecoResult}
#Import export ".\ISpRecoResult2.ahk" {ISpRecoResult2}
#Import export ".\ISpRecognizer.ahk" {ISpRecognizer}
#Import export ".\ISpRecognizer2.ahk" {ISpRecognizer2}
#Import export ".\ISpRegDataKey.ahk" {ISpRegDataKey}
#Import export ".\ISpResourceManager.ahk" {ISpResourceManager}
#Import export ".\ISpSRAlternates.ahk" {ISpSRAlternates}
#Import export ".\ISpSRAlternates2.ahk" {ISpSRAlternates2}
#Import export ".\ISpSREngine.ahk" {ISpSREngine}
#Import export ".\ISpSREngine2.ahk" {ISpSREngine2}
#Import export ".\ISpSREngineSite.ahk" {ISpSREngineSite}
#Import export ".\ISpSREngineSite2.ahk" {ISpSREngineSite2}
#Import export ".\ISpSerializeState.ahk" {ISpSerializeState}
#Import export ".\ISpShortcut.ahk" {ISpShortcut}
#Import export ".\ISpStream.ahk" {ISpStream}
#Import export ".\ISpStreamFormat.ahk" {ISpStreamFormat}
#Import export ".\ISpStreamFormatConverter.ahk" {ISpStreamFormatConverter}
#Import export ".\ISpTTSEngine.ahk" {ISpTTSEngine}
#Import export ".\ISpTTSEngineSite.ahk" {ISpTTSEngineSite}
#Import export ".\ISpTask.ahk" {ISpTask}
#Import export ".\ISpTaskManager.ahk" {ISpTaskManager}
#Import export ".\ISpThreadControl.ahk" {ISpThreadControl}
#Import export ".\ISpThreadTask.ahk" {ISpThreadTask}
#Import export ".\ISpTokenUI.ahk" {ISpTokenUI}
#Import export ".\ISpTranscript.ahk" {ISpTranscript}
#Import export ".\ISpVoice.ahk" {ISpVoice}
#Import export ".\ISpXMLRecoResult.ahk" {ISpXMLRecoResult}
#Import export ".\ISpeechAudio.ahk" {ISpeechAudio}
#Import export ".\ISpeechAudioBufferInfo.ahk" {ISpeechAudioBufferInfo}
#Import export ".\ISpeechAudioFormat.ahk" {ISpeechAudioFormat}
#Import export ".\ISpeechAudioStatus.ahk" {ISpeechAudioStatus}
#Import export ".\ISpeechBaseStream.ahk" {ISpeechBaseStream}
#Import export ".\ISpeechCustomStream.ahk" {ISpeechCustomStream}
#Import export ".\ISpeechDataKey.ahk" {ISpeechDataKey}
#Import export ".\ISpeechFileStream.ahk" {ISpeechFileStream}
#Import export ".\ISpeechGrammarRule.ahk" {ISpeechGrammarRule}
#Import export ".\ISpeechGrammarRuleState.ahk" {ISpeechGrammarRuleState}
#Import export ".\ISpeechGrammarRuleStateTransition.ahk" {ISpeechGrammarRuleStateTransition}
#Import export ".\ISpeechGrammarRuleStateTransitions.ahk" {ISpeechGrammarRuleStateTransitions}
#Import export ".\ISpeechGrammarRules.ahk" {ISpeechGrammarRules}
#Import export ".\ISpeechLexicon.ahk" {ISpeechLexicon}
#Import export ".\ISpeechLexiconPronunciation.ahk" {ISpeechLexiconPronunciation}
#Import export ".\ISpeechLexiconPronunciations.ahk" {ISpeechLexiconPronunciations}
#Import export ".\ISpeechLexiconWord.ahk" {ISpeechLexiconWord}
#Import export ".\ISpeechLexiconWords.ahk" {ISpeechLexiconWords}
#Import export ".\ISpeechMMSysAudio.ahk" {ISpeechMMSysAudio}
#Import export ".\ISpeechMemoryStream.ahk" {ISpeechMemoryStream}
#Import export ".\ISpeechObjectToken.ahk" {ISpeechObjectToken}
#Import export ".\ISpeechObjectTokenCategory.ahk" {ISpeechObjectTokenCategory}
#Import export ".\ISpeechObjectTokens.ahk" {ISpeechObjectTokens}
#Import export ".\ISpeechPhoneConverter.ahk" {ISpeechPhoneConverter}
#Import export ".\ISpeechPhraseAlternate.ahk" {ISpeechPhraseAlternate}
#Import export ".\ISpeechPhraseAlternates.ahk" {ISpeechPhraseAlternates}
#Import export ".\ISpeechPhraseElement.ahk" {ISpeechPhraseElement}
#Import export ".\ISpeechPhraseElements.ahk" {ISpeechPhraseElements}
#Import export ".\ISpeechPhraseInfo.ahk" {ISpeechPhraseInfo}
#Import export ".\ISpeechPhraseInfoBuilder.ahk" {ISpeechPhraseInfoBuilder}
#Import export ".\ISpeechPhraseProperties.ahk" {ISpeechPhraseProperties}
#Import export ".\ISpeechPhraseProperty.ahk" {ISpeechPhraseProperty}
#Import export ".\ISpeechPhraseReplacement.ahk" {ISpeechPhraseReplacement}
#Import export ".\ISpeechPhraseReplacements.ahk" {ISpeechPhraseReplacements}
#Import export ".\ISpeechPhraseRule.ahk" {ISpeechPhraseRule}
#Import export ".\ISpeechPhraseRules.ahk" {ISpeechPhraseRules}
#Import export ".\ISpeechRecoContext.ahk" {ISpeechRecoContext}
#Import export ".\ISpeechRecoGrammar.ahk" {ISpeechRecoGrammar}
#Import export ".\ISpeechRecoResult.ahk" {ISpeechRecoResult}
#Import export ".\ISpeechRecoResult2.ahk" {ISpeechRecoResult2}
#Import export ".\ISpeechRecoResultDispatch.ahk" {ISpeechRecoResultDispatch}
#Import export ".\ISpeechRecoResultTimes.ahk" {ISpeechRecoResultTimes}
#Import export ".\ISpeechRecognizer.ahk" {ISpeechRecognizer}
#Import export ".\ISpeechRecognizerStatus.ahk" {ISpeechRecognizerStatus}
#Import export ".\ISpeechResourceLoader.ahk" {ISpeechResourceLoader}
#Import export ".\ISpeechTextSelectionInformation.ahk" {ISpeechTextSelectionInformation}
#Import export ".\ISpeechVoice.ahk" {ISpeechVoice}
#Import export ".\ISpeechVoiceStatus.ahk" {ISpeechVoiceStatus}
#Import export ".\ISpeechWaveFormatEx.ahk" {ISpeechWaveFormatEx}
#Import export ".\ISpeechXMLRecoResult.ahk" {ISpeechXMLRecoResult}
#Import export ".\PHONETICALPHABET.ahk" {PHONETICALPHABET}
#Import export ".\SPADAPTATIONRELEVANCE.ahk" {SPADAPTATIONRELEVANCE}
#Import export ".\SPADAPTATIONSETTINGS.ahk" {SPADAPTATIONSETTINGS}
#Import export ".\SPAUDIOBUFFERINFO.ahk" {SPAUDIOBUFFERINFO}
#Import export ".\SPAUDIOOPTIONS.ahk" {SPAUDIOOPTIONS}
#Import export ".\SPAUDIOSTATE.ahk" {SPAUDIOSTATE}
#Import export ".\SPAUDIOSTATUS.ahk" {SPAUDIOSTATUS}
#Import export ".\SPBINARYGRAMMAR.ahk" {SPBINARYGRAMMAR}
#Import export ".\SPBOOKMARKOPTIONS.ahk" {SPBOOKMARKOPTIONS}
#Import export ".\SPCFGNOTIFY.ahk" {SPCFGNOTIFY}
#Import export ".\SPCFGRULEATTRIBUTES.ahk" {SPCFGRULEATTRIBUTES}
#Import export ".\SPCOMMITFLAGS.ahk" {SPCOMMITFLAGS}
#Import export ".\SPCONTEXTSTATE.ahk" {SPCONTEXTSTATE}
#Import export ".\SPDATAKEYLOCATION.ahk" {SPDATAKEYLOCATION}
#Import export ".\SPDISPLAYATTRIBUTES.ahk" {SPDISPLAYATTRIBUTES}
#Import export ".\SPDISPLAYPHRASE.ahk" {SPDISPLAYPHRASE}
#Import export ".\SPDISPLAYTOKEN.ahk" {SPDISPLAYTOKEN}
#Import export ".\SPEAKFLAGS.ahk" {SPEAKFLAGS}
#Import export ".\SPENDSRSTREAMFLAGS.ahk" {SPENDSRSTREAMFLAGS}
#Import export ".\SPEVENT.ahk" {SPEVENT}
#Import export ".\SPEVENTENUM.ahk" {SPEVENTENUM}
#Import export ".\SPEVENTEX.ahk" {SPEVENTEX}
#Import export ".\SPEVENTLPARAMTYPE.ahk" {SPEVENTLPARAMTYPE}
#Import export ".\SPEVENTSOURCEINFO.ahk" {SPEVENTSOURCEINFO}
#Import export ".\SPFILEMODE.ahk" {SPFILEMODE}
#Import export ".\SPGRAMMARHANDLE.ahk" {SPGRAMMARHANDLE}
#Import export ".\SPGRAMMAROPTIONS.ahk" {SPGRAMMAROPTIONS}
#Import export ".\SPGRAMMARSTATE.ahk" {SPGRAMMARSTATE}
#Import export ".\SPGRAMMARWORDTYPE.ahk" {SPGRAMMARWORDTYPE}
#Import export ".\SPINTERFERENCE.ahk" {SPINTERFERENCE}
#Import export ".\SPLEXICONTYPE.ahk" {SPLEXICONTYPE}
#Import export ".\SPLOADOPTIONS.ahk" {SPLOADOPTIONS}
#Import export ".\SPMATCHINGMODE.ahk" {SPMATCHINGMODE}
#Import export ".\SPNORMALIZATIONLIST.ahk" {SPNORMALIZATIONLIST}
#Import export ".\SPNOTIFYCALLBACK.ahk" {SPNOTIFYCALLBACK}
#Import export ".\SPPARSEINFO.ahk" {SPPARSEINFO}
#Import export ".\SPPARTOFSPEECH.ahk" {SPPARTOFSPEECH}
#Import export ".\SPPATHENTRY.ahk" {SPPATHENTRY}
#Import export ".\SPPHRASE.ahk" {SPPHRASE}
#Import export ".\SPPHRASEALT.ahk" {SPPHRASEALT}
#Import export ".\SPPHRASEALTREQUEST.ahk" {SPPHRASEALTREQUEST}
#Import export ".\SPPHRASEELEMENT.ahk" {SPPHRASEELEMENT}
#Import export ".\SPPHRASEPROPERTY.ahk" {SPPHRASEPROPERTY}
#Import export ".\SPPHRASEPROPERTYHANDLE.ahk" {SPPHRASEPROPERTYHANDLE}
#Import export ".\SPPHRASEPROPERTYUNIONTYPE.ahk" {SPPHRASEPROPERTYUNIONTYPE}
#Import export ".\SPPHRASEREPLACEMENT.ahk" {SPPHRASEREPLACEMENT}
#Import export ".\SPPHRASERNG.ahk" {SPPHRASERNG}
#Import export ".\SPPHRASERULE.ahk" {SPPHRASERULE}
#Import export ".\SPPHRASERULEHANDLE.ahk" {SPPHRASERULEHANDLE}
#Import export ".\SPPHRASE_50.ahk" {SPPHRASE_50}
#Import export ".\SPPRONUNCIATIONFLAGS.ahk" {SPPRONUNCIATIONFLAGS}
#Import export ".\SPPROPERTYINFO.ahk" {SPPROPERTYINFO}
#Import export ".\SPPROPSRC.ahk" {SPPROPSRC}
#Import export ".\SPRECOCONTEXTHANDLE.ahk" {SPRECOCONTEXTHANDLE}
#Import export ".\SPRECOCONTEXTSTATUS.ahk" {SPRECOCONTEXTSTATUS}
#Import export ".\SPRECOEVENTFLAGS.ahk" {SPRECOEVENTFLAGS}
#Import export ".\SPRECOGNIZERSTATUS.ahk" {SPRECOGNIZERSTATUS}
#Import export ".\SPRECORESULTINFO.ahk" {SPRECORESULTINFO}
#Import export ".\SPRECORESULTINFOEX.ahk" {SPRECORESULTINFOEX}
#Import export ".\SPRECORESULTTIMES.ahk" {SPRECORESULTTIMES}
#Import export ".\SPRECOSTATE.ahk" {SPRECOSTATE}
#Import export ".\SPRESULTTYPE.ahk" {SPRESULTTYPE}
#Import export ".\SPRULE.ahk" {SPRULE}
#Import export ".\SPRULEENTRY.ahk" {SPRULEENTRY}
#Import export ".\SPRULEHANDLE.ahk" {SPRULEHANDLE}
#Import export ".\SPRULEINFOOPT.ahk" {SPRULEINFOOPT}
#Import export ".\SPRULESTATE.ahk" {SPRULESTATE}
#Import export ".\SPRUNSTATE.ahk" {SPRUNSTATE}
#Import export ".\SPSEMANTICERRORINFO.ahk" {SPSEMANTICERRORINFO}
#Import export ".\SPSEMANTICFORMAT.ahk" {SPSEMANTICFORMAT}
#Import export ".\SPSERIALIZEDEVENT.ahk" {SPSERIALIZEDEVENT}
#Import export ".\SPSERIALIZEDEVENT64.ahk" {SPSERIALIZEDEVENT64}
#Import export ".\SPSERIALIZEDPHRASE.ahk" {SPSERIALIZEDPHRASE}
#Import export ".\SPSERIALIZEDRESULT.ahk" {SPSERIALIZEDRESULT}
#Import export ".\SPSHORTCUTPAIR.ahk" {SPSHORTCUTPAIR}
#Import export ".\SPSHORTCUTPAIRLIST.ahk" {SPSHORTCUTPAIRLIST}
#Import export ".\SPSHORTCUTTYPE.ahk" {SPSHORTCUTTYPE}
#Import export ".\SPSTATEHANDLE.ahk" {SPSTATEHANDLE}
#Import export ".\SPSTATEINFO.ahk" {SPSTATEINFO}
#Import export ".\SPSTREAMFORMAT.ahk" {SPSTREAMFORMAT}
#Import export ".\SPSTREAMFORMATTYPE.ahk" {SPSTREAMFORMATTYPE}
#Import export ".\SPTEXTSELECTIONINFO.ahk" {SPTEXTSELECTIONINFO}
#Import export ".\SPTMTHREADINFO.ahk" {SPTMTHREADINFO}
#Import export ".\SPTRANSITIONENTRY.ahk" {SPTRANSITIONENTRY}
#Import export ".\SPTRANSITIONID.ahk" {SPTRANSITIONID}
#Import export ".\SPTRANSITIONPROPERTY.ahk" {SPTRANSITIONPROPERTY}
#Import export ".\SPTRANSITIONTYPE.ahk" {SPTRANSITIONTYPE}
#Import export ".\SPVACTIONS.ahk" {SPVACTIONS}
#Import export ".\SPVALUETYPE.ahk" {SPVALUETYPE}
#Import export ".\SPVCONTEXT.ahk" {SPVCONTEXT}
#Import export ".\SPVESACTIONS.ahk" {SPVESACTIONS}
#Import export ".\SPVFEATURE.ahk" {SPVFEATURE}
#Import export ".\SPVISEMES.ahk" {SPVISEMES}
#Import export ".\SPVLIMITS.ahk" {SPVLIMITS}
#Import export ".\SPVOICESTATUS.ahk" {SPVOICESTATUS}
#Import export ".\SPVPITCH.ahk" {SPVPITCH}
#Import export ".\SPVPRIORITY.ahk" {SPVPRIORITY}
#Import export ".\SPVSKIPTYPE.ahk" {SPVSKIPTYPE}
#Import export ".\SPVSTATE.ahk" {SPVSTATE}
#Import export ".\SPVTEXTFRAG.ahk" {SPVTEXTFRAG}
#Import export ".\SPWORD.ahk" {SPWORD}
#Import export ".\SPWORDENTRY.ahk" {SPWORDENTRY}
#Import export ".\SPWORDHANDLE.ahk" {SPWORDHANDLE}
#Import export ".\SPWORDINFOOPT.ahk" {SPWORDINFOOPT}
#Import export ".\SPWORDLIST.ahk" {SPWORDLIST}
#Import export ".\SPWORDPRONOUNCEABLE.ahk" {SPWORDPRONOUNCEABLE}
#Import export ".\SPWORDPRONUNCIATION.ahk" {SPWORDPRONUNCIATION}
#Import export ".\SPWORDPRONUNCIATIONLIST.ahk" {SPWORDPRONUNCIATIONLIST}
#Import export ".\SPWORDTYPE.ahk" {SPWORDTYPE}
#Import export ".\SPXMLRESULTOPTIONS.ahk" {SPXMLRESULTOPTIONS}
#Import export ".\SpAudioFormat.ahk" {SpAudioFormat}
#Import export ".\SpCompressedLexicon.ahk" {SpCompressedLexicon}
#Import export ".\SpCustomStream.ahk" {SpCustomStream}
#Import export ".\SpDataKey.ahk" {SpDataKey}
#Import export ".\SpFileStream.ahk" {SpFileStream}
#Import export ".\SpGramCompBackend.ahk" {SpGramCompBackend}
#Import export ".\SpGrammarCompiler.ahk" {SpGrammarCompiler}
#Import export ".\SpITNProcessor.ahk" {SpITNProcessor}
#Import export ".\SpInProcRecoContext.ahk" {SpInProcRecoContext}
#Import export ".\SpInprocRecognizer.ahk" {SpInprocRecognizer}
#Import export ".\SpLexicon.ahk" {SpLexicon}
#Import export ".\SpMMAudioEnum.ahk" {SpMMAudioEnum}
#Import export ".\SpMMAudioIn.ahk" {SpMMAudioIn}
#Import export ".\SpMMAudioOut.ahk" {SpMMAudioOut}
#Import export ".\SpMemoryStream.ahk" {SpMemoryStream}
#Import export ".\SpNotifyTranslator.ahk" {SpNotifyTranslator}
#Import export ".\SpNullPhoneConverter.ahk" {SpNullPhoneConverter}
#Import export ".\SpObjectToken.ahk" {SpObjectToken}
#Import export ".\SpObjectTokenCategory.ahk" {SpObjectTokenCategory}
#Import export ".\SpObjectTokenEnum.ahk" {SpObjectTokenEnum}
#Import export ".\SpPhoneConverter.ahk" {SpPhoneConverter}
#Import export ".\SpPhoneticAlphabetConverter.ahk" {SpPhoneticAlphabetConverter}
#Import export ".\SpPhraseBuilder.ahk" {SpPhraseBuilder}
#Import export ".\SpPhraseInfoBuilder.ahk" {SpPhraseInfoBuilder}
#Import export ".\SpResourceManager.ahk" {SpResourceManager}
#Import export ".\SpSharedRecoContext.ahk" {SpSharedRecoContext}
#Import export ".\SpSharedRecognizer.ahk" {SpSharedRecognizer}
#Import export ".\SpShortcut.ahk" {SpShortcut}
#Import export ".\SpStream.ahk" {SpStream}
#Import export ".\SpStreamFormatConverter.ahk" {SpStreamFormatConverter}
#Import export ".\SpTextSelectionInformation.ahk" {SpTextSelectionInformation}
#Import export ".\SpUnCompressedLexicon.ahk" {SpUnCompressedLexicon}
#Import export ".\SpVoice.ahk" {SpVoice}
#Import export ".\SpW3CGrammarCompiler.ahk" {SpW3CGrammarCompiler}
#Import export ".\SpWaveFormatEx.ahk" {SpWaveFormatEx}
#Import export ".\SpeechAudioFormatType.ahk" {SpeechAudioFormatType}
#Import export ".\SpeechAudioState.ahk" {SpeechAudioState}
#Import export ".\SpeechBookmarkOptions.ahk" {SpeechBookmarkOptions}
#Import export ".\SpeechDataKeyLocation.ahk" {SpeechDataKeyLocation}
#Import export ".\SpeechDiscardType.ahk" {SpeechDiscardType}
#Import export ".\SpeechDisplayAttributes.ahk" {SpeechDisplayAttributes}
#Import export ".\SpeechEmulationCompareFlags.ahk" {SpeechEmulationCompareFlags}
#Import export ".\SpeechEngineConfidence.ahk" {SpeechEngineConfidence}
#Import export ".\SpeechFormatType.ahk" {SpeechFormatType}
#Import export ".\SpeechGrammarRuleStateTransitionType.ahk" {SpeechGrammarRuleStateTransitionType}
#Import export ".\SpeechGrammarState.ahk" {SpeechGrammarState}
#Import export ".\SpeechGrammarWordType.ahk" {SpeechGrammarWordType}
#Import export ".\SpeechInterference.ahk" {SpeechInterference}
#Import export ".\SpeechLexiconType.ahk" {SpeechLexiconType}
#Import export ".\SpeechLoadOption.ahk" {SpeechLoadOption}
#Import export ".\SpeechPartOfSpeech.ahk" {SpeechPartOfSpeech}
#Import export ".\SpeechRecoContextState.ahk" {SpeechRecoContextState}
#Import export ".\SpeechRecoEvents.ahk" {SpeechRecoEvents}
#Import export ".\SpeechRecognitionType.ahk" {SpeechRecognitionType}
#Import export ".\SpeechRecognizerState.ahk" {SpeechRecognizerState}
#Import export ".\SpeechRetainedAudioOptions.ahk" {SpeechRetainedAudioOptions}
#Import export ".\SpeechRuleAttributes.ahk" {SpeechRuleAttributes}
#Import export ".\SpeechRuleState.ahk" {SpeechRuleState}
#Import export ".\SpeechRunState.ahk" {SpeechRunState}
#Import export ".\SpeechSpecialTransitionType.ahk" {SpeechSpecialTransitionType}
#Import export ".\SpeechStreamFileMode.ahk" {SpeechStreamFileMode}
#Import export ".\SpeechStreamSeekPositionType.ahk" {SpeechStreamSeekPositionType}
#Import export ".\SpeechTokenContext.ahk" {SpeechTokenContext}
#Import export ".\SpeechTokenShellFolder.ahk" {SpeechTokenShellFolder}
#Import export ".\SpeechVisemeFeature.ahk" {SpeechVisemeFeature}
#Import export ".\SpeechVisemeType.ahk" {SpeechVisemeType}
#Import export ".\SpeechVoiceEvents.ahk" {SpeechVoiceEvents}
#Import export ".\SpeechVoicePriority.ahk" {SpeechVoicePriority}
#Import export ".\SpeechVoiceSpeakFlags.ahk" {SpeechVoiceSpeakFlags}
#Import export ".\SpeechWordPronounceable.ahk" {SpeechWordPronounceable}
#Import export ".\SpeechWordType.ahk" {SpeechWordType}
#Import export ".\_ISpPrivateEngineCall.ahk" {_ISpPrivateEngineCall}
#Import export ".\_ISpeechRecoContextEvents.ahk" {_ISpeechRecoContextEvents}
#Import export ".\_ISpeechVoiceEvents.ahk" {_ISpeechVoiceEvents}
