#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\BSTRBLOB.ahk" {BSTRBLOB}
#Import export ".\CABOOL.ahk" {CABOOL}
#Import export ".\CABSTR.ahk" {CABSTR}
#Import export ".\CABSTRBLOB.ahk" {CABSTRBLOB}
#Import export ".\CAC.ahk" {CAC}
#Import export ".\CACLIPDATA.ahk" {CACLIPDATA}
#Import export ".\CACLSID.ahk" {CACLSID}
#Import export ".\CACY.ahk" {CACY}
#Import export ".\CADATE.ahk" {CADATE}
#Import export ".\CADBL.ahk" {CADBL}
#Import export ".\CAFILETIME.ahk" {CAFILETIME}
#Import export ".\CAFLT.ahk" {CAFLT}
#Import export ".\CAH.ahk" {CAH}
#Import export ".\CAI.ahk" {CAI}
#Import export ".\CAL.ahk" {CAL}
#Import export ".\CALPSTR.ahk" {CALPSTR}
#Import export ".\CALPWSTR.ahk" {CALPWSTR}
#Import export ".\CAPROPVARIANT.ahk" {CAPROPVARIANT}
#Import export ".\CASCODE.ahk" {CASCODE}
#Import export ".\CAUB.ahk" {CAUB}
#Import export ".\CAUH.ahk" {CAUH}
#Import export ".\CAUI.ahk" {CAUI}
#Import export ".\CAUL.ahk" {CAUL}
#Import export ".\CLIPDATA.ahk" {CLIPDATA}
#Import export ".\Constants.ahk" {*}
#Import export ".\IDirectWriterLock.ahk" {IDirectWriterLock}
#Import export ".\IEnumSTATPROPSETSTG.ahk" {IEnumSTATPROPSETSTG}
#Import export ".\IEnumSTATPROPSTG.ahk" {IEnumSTATPROPSTG}
#Import export ".\IEnumSTATSTG.ahk" {IEnumSTATSTG}
#Import export ".\IFillLockBytes.ahk" {IFillLockBytes}
#Import export ".\ILayoutStorage.ahk" {ILayoutStorage}
#Import export ".\ILockBytes.ahk" {ILockBytes}
#Import export ".\IMemoryAllocator.ahk" {IMemoryAllocator}
#Import export ".\IPersistStorage.ahk" {IPersistStorage}
#Import export ".\IPropertyBag.ahk" {IPropertyBag}
#Import export ".\IPropertyBag2.ahk" {IPropertyBag2}
#Import export ".\IPropertySetStorage.ahk" {IPropertySetStorage}
#Import export ".\IPropertyStorage.ahk" {IPropertyStorage}
#Import export ".\IRootStorage.ahk" {IRootStorage}
#Import export ".\IStorage.ahk" {IStorage}
#Import export ".\OLESTREAM.ahk" {OLESTREAM}
#Import export ".\OLESTREAMVTBL.ahk" {OLESTREAMVTBL}
#Import export ".\PIDMSI_STATUS_VALUE.ahk" {PIDMSI_STATUS_VALUE}
#Import export ".\PROPBAG2.ahk" {PROPBAG2}
#Import export ".\PROPSPEC.ahk" {PROPSPEC}
#Import export ".\PROPSPEC_KIND.ahk" {PROPSPEC_KIND}
#Import export ".\PROPVARIANT.ahk" {PROPVARIANT}
#Import export ".\PROPVAR_CHANGE_FLAGS.ahk" {PROPVAR_CHANGE_FLAGS}
#Import export ".\PROPVAR_COMPARE_FLAGS.ahk" {PROPVAR_COMPARE_FLAGS}
#Import export ".\PROPVAR_COMPARE_UNIT.ahk" {PROPVAR_COMPARE_UNIT}
#Import export ".\RemSNB.ahk" {RemSNB}
#Import export ".\SERIALIZEDPROPERTYVALUE.ahk" {SERIALIZEDPROPERTYVALUE}
#Import export ".\STATPROPSETSTG.ahk" {STATPROPSETSTG}
#Import export ".\STATPROPSTG.ahk" {STATPROPSTG}
#Import export ".\STGFMT.ahk" {STGFMT}
#Import export ".\STGMOVE.ahk" {STGMOVE}
#Import export ".\STGOPTIONS.ahk" {STGOPTIONS}
#Import export ".\VERSIONEDSTREAM.ahk" {VERSIONEDSTREAM}
