#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PFN_CARD_CREATE_FILE.ahk" { PFN_CARD_CREATE_FILE }
#Import ".\PFN_CARD_DEAUTHENTICATE_EX.ahk" { PFN_CARD_DEAUTHENTICATE_EX }
#Import ".\PFN_CARD_CONSTRUCT_DH_AGREEMENT.ahk" { PFN_CARD_CONSTRUCT_DH_AGREEMENT }
#Import ".\PFN_CSP_PAD_DATA.ahk" { PFN_CSP_PAD_DATA }
#Import ".\PFN_CARD_AUTHENTICATE_CHALLENGE.ahk" { PFN_CARD_AUTHENTICATE_CHALLENGE }
#Import ".\PFN_CARD_DELETE_CONTEXT.ahk" { PFN_CARD_DELETE_CONTEXT }
#Import ".\PFN_CARD_IMPORT_SESSION_KEY.ahk" { PFN_CARD_IMPORT_SESSION_KEY }
#Import ".\PFN_CARD_AUTHENTICATE_PIN.ahk" { PFN_CARD_AUTHENTICATE_PIN }
#Import ".\PFN_CARD_DESTROY_DH_AGREEMENT.ahk" { PFN_CARD_DESTROY_DH_AGREEMENT }
#Import ".\PFN_MD_ENCRYPT_DATA.ahk" { PFN_MD_ENCRYPT_DATA }
#Import ".\PFN_CSP_CACHE_LOOKUP_FILE.ahk" { PFN_CSP_CACHE_LOOKUP_FILE }
#Import ".\PFN_CARD_CREATE_CONTAINER_EX.ahk" { PFN_CARD_CREATE_CONTAINER_EX }
#Import ".\PFN_CARD_GET_CHALLENGE.ahk" { PFN_CARD_GET_CHALLENGE }
#Import ".\PFN_CARD_GET_ALGORITHM_PROPERTY.ahk" { PFN_CARD_GET_ALGORITHM_PROPERTY }
#Import ".\PFN_CARD_GET_KEY_PROPERTY.ahk" { PFN_CARD_GET_KEY_PROPERTY }
#Import ".\PFN_CARD_GET_SHARED_KEY_HANDLE.ahk" { PFN_CARD_GET_SHARED_KEY_HANDLE }
#Import ".\PFN_CARD_DELETE_DIRECTORY.ahk" { PFN_CARD_DELETE_DIRECTORY }
#Import ".\PFN_CSP_CACHE_DELETE_FILE.ahk" { PFN_CSP_CACHE_DELETE_FILE }
#Import ".\PFN_CARD_WRITE_FILE.ahk" { PFN_CARD_WRITE_FILE }
#Import ".\PFN_CSP_REALLOC.ahk" { PFN_CSP_REALLOC }
#Import ".\PFN_CARD_DERIVE_KEY.ahk" { PFN_CARD_DERIVE_KEY }
#Import ".\PFN_CARD_GET_CONTAINER_PROPERTY.ahk" { PFN_CARD_GET_CONTAINER_PROPERTY }
#Import ".\PFN_CARD_CHANGE_AUTHENTICATOR_EX.ahk" { PFN_CARD_CHANGE_AUTHENTICATOR_EX }
#Import ".\PFN_CARD_GET_CHALLENGE_EX.ahk" { PFN_CARD_GET_CHALLENGE_EX }
#Import ".\PFN_CARD_UNBLOCK_PIN.ahk" { PFN_CARD_UNBLOCK_PIN }
#Import ".\PFN_CARD_DELETE_CONTAINER.ahk" { PFN_CARD_DELETE_CONTAINER }
#Import ".\PFN_CARD_QUERY_CAPABILITIES.ahk" { PFN_CARD_QUERY_CAPABILITIES }
#Import ".\PFN_CARD_GET_CONTAINER_INFO.ahk" { PFN_CARD_GET_CONTAINER_INFO }
#Import ".\PFN_CSP_ALLOC.ahk" { PFN_CSP_ALLOC }
#Import ".\PFN_CARD_GET_PROPERTY.ahk" { PFN_CARD_GET_PROPERTY }
#Import ".\PFN_CSP_CACHE_ADD_FILE.ahk" { PFN_CSP_CACHE_ADD_FILE }
#Import ".\PFN_CARD_CREATE_CONTAINER.ahk" { PFN_CARD_CREATE_CONTAINER }
#Import ".\PFN_CARD_SET_KEY_PROPERTY.ahk" { PFN_CARD_SET_KEY_PROPERTY }
#Import ".\PFN_CSP_GET_DH_AGREEMENT.ahk" { PFN_CSP_GET_DH_AGREEMENT }
#Import ".\PFN_CARD_RSA_DECRYPT.ahk" { PFN_CARD_RSA_DECRYPT }
#Import ".\PFN_CARD_SET_CONTAINER_PROPERTY.ahk" { PFN_CARD_SET_CONTAINER_PROPERTY }
#Import ".\PFN_CARD_DEAUTHENTICATE.ahk" { PFN_CARD_DEAUTHENTICATE }
#Import ".\PFN_CARD_READ_FILE.ahk" { PFN_CARD_READ_FILE }
#Import ".\PFN_CARD_QUERY_KEY_SIZES.ahk" { PFN_CARD_QUERY_KEY_SIZES }
#Import ".\PFN_CARD_CREATE_DIRECTORY.ahk" { PFN_CARD_CREATE_DIRECTORY }
#Import ".\PFN_CARD_AUTHENTICATE_EX.ahk" { PFN_CARD_AUTHENTICATE_EX }
#Import ".\PFN_CARD_SIGN_DATA.ahk" { PFN_CARD_SIGN_DATA }
#Import ".\PFN_CARD_DELETE_FILE.ahk" { PFN_CARD_DELETE_FILE }
#Import ".\PFN_CARD_GET_FILE_INFO.ahk" { PFN_CARD_GET_FILE_INFO }
#Import ".\PFN_CSP_FREE.ahk" { PFN_CSP_FREE }
#Import ".\PFN_CARD_PROCESS_ENCRYPTED_DATA.ahk" { PFN_CARD_PROCESS_ENCRYPTED_DATA }
#Import ".\PFN_CSP_UNPAD_DATA.ahk" { PFN_CSP_UNPAD_DATA }
#Import ".\PFN_CARD_ENUM_FILES.ahk" { PFN_CARD_ENUM_FILES }
#Import ".\PFN_CARD_SET_PROPERTY.ahk" { PFN_CARD_SET_PROPERTY }
#Import "..\..\Foundation\PWSTR.ahk" { PWSTR }
#Import ".\PFN_CARD_DESTROY_KEY.ahk" { PFN_CARD_DESTROY_KEY }
#Import ".\PFN_CARD_CHANGE_AUTHENTICATOR.ahk" { PFN_CARD_CHANGE_AUTHENTICATOR }
#Import ".\PFN_CARD_QUERY_FREE_SPACE.ahk" { PFN_CARD_QUERY_FREE_SPACE }
#Import ".\PFN_MD_IMPORT_SESSION_KEY.ahk" { PFN_MD_IMPORT_SESSION_KEY }

/**
 * @namespace Windows.Win32.Security.Cryptography
 */
export default struct CARD_DATA {
    #StructPack 8

    dwVersion : UInt32

    pbAtr : IntPtr

    cbAtr : UInt32

    pwszCardName : PWSTR

    pfnCspAlloc : PFN_CSP_ALLOC

    pfnCspReAlloc : PFN_CSP_REALLOC

    pfnCspFree : PFN_CSP_FREE

    pfnCspCacheAddFile : PFN_CSP_CACHE_ADD_FILE

    pfnCspCacheLookupFile : PFN_CSP_CACHE_LOOKUP_FILE

    pfnCspCacheDeleteFile : PFN_CSP_CACHE_DELETE_FILE

    pvCacheContext : IntPtr

    pfnCspPadData : PFN_CSP_PAD_DATA

    hSCardCtx : IntPtr

    hScard : IntPtr

    pvVendorSpecific : IntPtr

    pfnCardDeleteContext : PFN_CARD_DELETE_CONTEXT

    pfnCardQueryCapabilities : PFN_CARD_QUERY_CAPABILITIES

    pfnCardDeleteContainer : PFN_CARD_DELETE_CONTAINER

    pfnCardCreateContainer : PFN_CARD_CREATE_CONTAINER

    pfnCardGetContainerInfo : PFN_CARD_GET_CONTAINER_INFO

    pfnCardAuthenticatePin : PFN_CARD_AUTHENTICATE_PIN

    pfnCardGetChallenge : PFN_CARD_GET_CHALLENGE

    pfnCardAuthenticateChallenge : PFN_CARD_AUTHENTICATE_CHALLENGE

    pfnCardUnblockPin : PFN_CARD_UNBLOCK_PIN

    pfnCardChangeAuthenticator : PFN_CARD_CHANGE_AUTHENTICATOR

    pfnCardDeauthenticate : PFN_CARD_DEAUTHENTICATE

    pfnCardCreateDirectory : PFN_CARD_CREATE_DIRECTORY

    pfnCardDeleteDirectory : PFN_CARD_DELETE_DIRECTORY

    pvUnused3 : IntPtr

    pvUnused4 : IntPtr

    pfnCardCreateFile : PFN_CARD_CREATE_FILE

    pfnCardReadFile : PFN_CARD_READ_FILE

    pfnCardWriteFile : PFN_CARD_WRITE_FILE

    pfnCardDeleteFile : PFN_CARD_DELETE_FILE

    pfnCardEnumFiles : PFN_CARD_ENUM_FILES

    pfnCardGetFileInfo : PFN_CARD_GET_FILE_INFO

    pfnCardQueryFreeSpace : PFN_CARD_QUERY_FREE_SPACE

    pfnCardQueryKeySizes : PFN_CARD_QUERY_KEY_SIZES

    pfnCardSignData : PFN_CARD_SIGN_DATA

    pfnCardRSADecrypt : PFN_CARD_RSA_DECRYPT

    pfnCardConstructDHAgreement : PFN_CARD_CONSTRUCT_DH_AGREEMENT

    pfnCardDeriveKey : PFN_CARD_DERIVE_KEY

    pfnCardDestroyDHAgreement : PFN_CARD_DESTROY_DH_AGREEMENT

    pfnCspGetDHAgreement : PFN_CSP_GET_DH_AGREEMENT

    pfnCardGetChallengeEx : PFN_CARD_GET_CHALLENGE_EX

    pfnCardAuthenticateEx : PFN_CARD_AUTHENTICATE_EX

    pfnCardChangeAuthenticatorEx : PFN_CARD_CHANGE_AUTHENTICATOR_EX

    pfnCardDeauthenticateEx : PFN_CARD_DEAUTHENTICATE_EX

    pfnCardGetContainerProperty : PFN_CARD_GET_CONTAINER_PROPERTY

    pfnCardSetContainerProperty : PFN_CARD_SET_CONTAINER_PROPERTY

    pfnCardGetProperty : PFN_CARD_GET_PROPERTY

    pfnCardSetProperty : PFN_CARD_SET_PROPERTY

    pfnCspUnpadData : PFN_CSP_UNPAD_DATA

    pfnMDImportSessionKey : PFN_MD_IMPORT_SESSION_KEY

    pfnMDEncryptData : PFN_MD_ENCRYPT_DATA

    pfnCardImportSessionKey : PFN_CARD_IMPORT_SESSION_KEY

    pfnCardGetSharedKeyHandle : PFN_CARD_GET_SHARED_KEY_HANDLE

    pfnCardGetAlgorithmProperty : PFN_CARD_GET_ALGORITHM_PROPERTY

    pfnCardGetKeyProperty : PFN_CARD_GET_KEY_PROPERTY

    pfnCardSetKeyProperty : PFN_CARD_SET_KEY_PROPERTY

    pfnCardDestroyKey : PFN_CARD_DESTROY_KEY

    pfnCardProcessEncryptedData : PFN_CARD_PROCESS_ENCRYPTED_DATA

    pfnCardCreateContainerEx : PFN_CARD_CREATE_CONTAINER_EX

}
