#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\..\Guid.ahk
#Include ..\..\..\System\Com\IUnknown.ahk

/**
 * This topic applies to Update Rollup 2 for Microsoft Windows XP Media Center Edition 2005 and later.
 * @remarks
 * 
 * To declare the interface identifier (IID) for this interface, use the <b>__uuidof</b> operator: <c>__uuidof(IBDAComparable)</c>.
 * 
 * 
 * @see https://docs.microsoft.com/windows/win32/api//tuner/nn-tuner-ibdacomparable
 * @namespace Windows.Win32.Media.DirectShow.Tv
 * @version v4.0.30319
 */
class IBDAComparable extends IUnknown{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IBDAComparable
     * @type {Guid}
     */
    static IID => Guid("{b34505e0-2f0e-497b-80bc-d43f3b24ed7f}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 3

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["CompareExact", "CompareEquivalent", "HashExact", "HashExactIncremental", "HashEquivalent", "HashEquivalentIncremental"]

    /**
     * This topic applies to Update Rollup 2 for Microsoft Windows XP Media Center Edition 2005 and later.
     * @param {IDispatch} CompareTo Pointer to the <b>IDispatch</b> interface of the object that is to be compared with the object that implements the <b>IBDAComparable</b> interface.
     * @returns {Integer} Pointer to a variable that receives the result of the comparison. If the result is 0, the two objects are the same. If the result is nonzero, the two objects are not the same.
     * @see https://docs.microsoft.com/windows/win32/api//tuner/nf-tuner-ibdacomparable-compareexact
     */
    CompareExact(CompareTo) {
        result := ComCall(3, this, "ptr", CompareTo, "int*", &Result := 0, "HRESULT")
        return Result
    }

    /**
     * The CompareEquivalent method compares two objects to determine whether they contain equivalent tuning information.
     * @param {IDispatch} CompareTo Pointer to the <b>IDispatch</b> interface of the object that is to be compared with the object that implements the <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/tuner/nn-tuner-ibdacomparable">IBDAComparable</a> interface.
     * @param {Integer} dwFlags Specifies whether to alter the default equivalence comparison. Setting this parameter to 0 invokes the default behavior. Setting this parameter to the bitwise OR of one or more <a href="https://docs.microsoft.com/previous-versions/windows/desktop/mstv/bda-comp-flags">BDA_Comp_Flags</a> enumeration values overrides the default behavior.
     * @returns {Integer} Receives the result of the comparison. If the result is 0, the two objects are equivalent. If the result is nonzero, the two objects are not equivalent.
     * @see https://docs.microsoft.com/windows/win32/api//tuner/nf-tuner-ibdacomparable-compareequivalent
     */
    CompareEquivalent(CompareTo, dwFlags) {
        result := ComCall(4, this, "ptr", CompareTo, "uint", dwFlags, "int*", &Result := 0, "HRESULT")
        return Result
    }

    /**
     * This topic applies to Update Rollup 2 for Microsoft Windows XP Media Center Edition 2005 and later.
     * @returns {Integer} Receives the result of the hash operation. This result is the hash code for the tuning properties of the object and its associated objects that are to be included in comparisons with other objects.
     * @see https://docs.microsoft.com/windows/win32/api//tuner/nf-tuner-ibdacomparable-hashexact
     */
    HashExact() {
        result := ComCall(5, this, "int64*", &Result := 0, "HRESULT")
        return Result
    }

    /**
     * This topic applies to Update Rollup 2 for Microsoft Windows XP Media Center Edition 2005 and later.
     * @param {Integer} PartialResult Specifies the intermediate hash code that is to be combined with the hash code that is generated by the method. Typically, this value was generated by a previous call to either <b>HashExactIncremental</b> or <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/tuner/nf-tuner-ibdacomparable-hashexact">HashExact</a>.
     * @returns {Integer} Receives the result of the hash operation. This result is the hash code for the tuning properties of the object and its associated objects that are to be included in comparisons with other objects.
     * @see https://docs.microsoft.com/windows/win32/api//tuner/nf-tuner-ibdacomparable-hashexactincremental
     */
    HashExactIncremental(PartialResult) {
        result := ComCall(6, this, "int64", PartialResult, "int64*", &Result := 0, "HRESULT")
        return Result
    }

    /**
     * This topic applies to Update Rollup 2 for Microsoft Windows XP Media Center Edition 2005 and later.
     * @param {Integer} dwFlags Specifies whether to alter the subset of properties that are to be incorporated by default into the hash code. Setting this parameter to 0 invokes the default behavior. Setting this parameter to the bitwise <b>OR</b> of one or more <a href="https://docs.microsoft.com/previous-versions/windows/desktop/mstv/bda-comp-flags">BDA_Comp_Flags</a> enumeration values overrides the default behavior.
     * @returns {Integer} Pointer to a variable that receives the result of the hash operation. This result is the hash code for the subset of the tuning properties of the object and its associated objects that are to be included in comparisons with other objects.
     * @see https://docs.microsoft.com/windows/win32/api//tuner/nf-tuner-ibdacomparable-hashequivalent
     */
    HashEquivalent(dwFlags) {
        result := ComCall(7, this, "uint", dwFlags, "int64*", &Result := 0, "HRESULT")
        return Result
    }

    /**
     * This topic applies to Update Rollup 2 for Microsoft Windows XP Media Center Edition 2005 and later.
     * @param {Integer} PartialResult Specifies the intermediate hash code that is to be combined with the hash code that is generated by the method. Typically, this value was generated by a previous call to either <b>HashEquivalentIncremental</b> or <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/tuner/nf-tuner-ibdacomparable-hashequivalent">HashEquivalent</a>.
     * @param {Integer} dwFlags Specifies whether to alter the subset of properties that are to be incorporated by default into the hash code. Setting this parameter to 0 invokes the default behavior. Setting this parameter to the bitwise <b>OR</b> of one or more <a href="https://docs.microsoft.com/previous-versions/windows/desktop/mstv/bda-comp-flags">BDA_Comp_Flags</a> enumeration values overrides the default behavior.
     * @returns {Integer} Pointer to a variable that receives the result of the hash operation. This result is the hash code for the subset of the tuning properties of the object and its associated objects that are to be included in comparisons with other objects.
     * @see https://docs.microsoft.com/windows/win32/api//tuner/nf-tuner-ibdacomparable-hashequivalentincremental
     */
    HashEquivalentIncremental(PartialResult, dwFlags) {
        result := ComCall(8, this, "int64", PartialResult, "uint", dwFlags, "int64*", &Result := 0, "HRESULT")
        return Result
    }
}
