#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\..\Guid.ahk
#Include ..\..\..\Foundation\BSTR.ahk
#Include ..\IESEvent.ahk

/**
 * Gets information from an OpenMMI event.
 * @remarks
 * 
 * To declare the interface identifier (IID) for this interface, use the <b>__uuidof</b> operator: <c>__uuidof(IESOpenMmiEvent)</c>.
 * 
 * @see https://docs.microsoft.com/windows/win32/api//tuner/nn-tuner-iesopenmmievent
 * @namespace Windows.Win32.Media.DirectShow.Tv
 * @version v4.0.30319
 */
class IESOpenMmiEvent extends IESEvent{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IESOpenMmiEvent
     * @type {Guid}
     */
    static IID => Guid("{ba4b6526-1a35-4635-8b56-3ec612746a8c}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 8

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["GetDialogNumber", "GetDialogType", "GetDialogData", "GetDialogStringData"]

    /**
     * The GetDialogNumber method returns the dialog number generated by the sending device. The dialog number identifies the dialog to the receiver while the receiver is processing the OpenMMI event.
     * @param {Pointer<Integer>} pDialogRequest Pointer to the value of the dialog request from the operation that generated the <b>OpenMMI</b> request, for example, a call to <a href="https://docs.microsoft.com/windows/desktop/api/bdaiface/nf-bdaiface-ibda_conditionalaccessex-checkentitlementtoken">IBDA::CheckEntitlementToken</a>.
     * @returns {Integer} Gets the number generated by the device that is opening the dialog, which identifies the dialog.
     * @see https://docs.microsoft.com/windows/win32/api//tuner/nf-tuner-iesopenmmievent-getdialognumber
     */
    GetDialogNumber(pDialogRequest) {
        pDialogRequestMarshal := pDialogRequest is VarRef ? "uint*" : "ptr"

        result := ComCall(8, this, pDialogRequestMarshal, pDialogRequest, "uint*", &pDialogNumber := 0, "HRESULT")
        return pDialogNumber
    }

    /**
     * The GetDialogType method gets the GUID representing the experience type of the dialog that is being opened.
     * @returns {Guid} Gets the GUID identifying the experience type of the dialog. If the application does not recognize the experience type, it should set the event as complete  by returning an ERROR_ INVALID_TYPE result.
     * @see https://docs.microsoft.com/windows/win32/api//tuner/nf-tuner-iesopenmmievent-getdialogtype
     */
    GetDialogType() {
        guidDialogType := Guid()
        result := ComCall(9, this, "ptr", guidDialogType, "HRESULT")
        return guidDialogType
    }

    /**
     * Gets the data associated with an OpenMMI event, in byte stream format. This data can be the contents of the dialog that is opened or the Uniform Resource Locator (URL) that contains the dialog.
     * @returns {Pointer<SAFEARRAY>} Pointer to a SAFEARRAY object containing the event data. 
     *           
     *           The caller is responsible for freeing this memory.
     * @see https://docs.microsoft.com/windows/win32/api//tuner/nf-tuner-iesopenmmievent-getdialogdata
     */
    GetDialogData() {
        result := ComCall(10, this, "ptr*", &pbData := 0, "HRESULT")
        return pbData
    }

    /**
     * Gets the data associated with an OpenMMI event, in Unicode string format. This data can be the contents of the dialog that is opened or the Uniform Resource Locator (URL) that contains the dialog.
     * @param {Pointer<BSTR>} pbstrBaseUrl Pointer to a string that receives the URL containing the dialog.
     *           The caller is responsible for freeing this memory.
     * @returns {BSTR} Pointer to the string that receives the dialog contents.
     *           The caller is responsible for freeing the memory.
     * @see https://docs.microsoft.com/windows/win32/api//tuner/nf-tuner-iesopenmmievent-getdialogstringdata
     */
    GetDialogStringData(pbstrBaseUrl) {
        pbstrData := BSTR()
        result := ComCall(11, this, "ptr", pbstrBaseUrl, "ptr", pbstrData, "HRESULT")
        return pbstrData
    }
}
