#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PKSEC_CREATE_CONTEXT_LIST.ahk" { PKSEC_CREATE_CONTEXT_LIST }
#Import ".\PKSEC_DEREFERENCE_LIST_ENTRY.ahk" { PKSEC_DEREFERENCE_LIST_ENTRY }
#Import ".\PKSEC_INSERT_LIST_ENTRY.ahk" { PKSEC_INSERT_LIST_ENTRY }
#Import ".\PKSEC_LOCATE_PKG_BY_ID.ahk" { PKSEC_LOCATE_PKG_BY_ID }
#Import ".\PKSEC_REFERENCE_LIST_ENTRY.ahk" { PKSEC_REFERENCE_LIST_ENTRY }
#Import ".\PKSEC_SERIALIZE_SCHANNEL_AUTH_DATA.ahk" { PKSEC_SERIALIZE_SCHANNEL_AUTH_DATA }
#Import ".\PKSEC_SERIALIZE_WINNT_AUTH_DATA.ahk" { PKSEC_SERIALIZE_WINNT_AUTH_DATA }
#Import ".\PLSA_ALLOCATE_LSA_HEAP.ahk" { PLSA_ALLOCATE_LSA_HEAP }
#Import ".\PLSA_FREE_LSA_HEAP.ahk" { PLSA_FREE_LSA_HEAP }

/**
 * @namespace Windows.Win32.Security.Authentication.Identity
 */
export default struct SECPKG_KERNEL_FUNCTIONS {
    #StructPack 8

    AllocateHeap : PLSA_ALLOCATE_LSA_HEAP

    FreeHeap : PLSA_FREE_LSA_HEAP

    CreateContextList : PKSEC_CREATE_CONTEXT_LIST

    InsertListEntry : PKSEC_INSERT_LIST_ENTRY

    ReferenceListEntry : PKSEC_REFERENCE_LIST_ENTRY

    DereferenceListEntry : PKSEC_DEREFERENCE_LIST_ENTRY

    SerializeWinntAuthData : PKSEC_SERIALIZE_WINNT_AUTH_DATA

    SerializeSchannelAuthData : PKSEC_SERIALIZE_SCHANNEL_AUTH_DATA

    LocatePackageById : PKSEC_LOCATE_PKG_BY_ID

}
