#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import "..\..\..\Foundation\HANDLE.ahk" { HANDLE }
#Import ".\PLSA_REDIRECTED_LOGON_GET_LOGON_CREDS.ahk" { PLSA_REDIRECTED_LOGON_GET_LOGON_CREDS }
#Import ".\PLSA_REDIRECTED_LOGON_GET_SID.ahk" { PLSA_REDIRECTED_LOGON_GET_SID }
#Import ".\PLSA_REDIRECTED_LOGON_CALLBACK.ahk" { PLSA_REDIRECTED_LOGON_CALLBACK }
#Import ".\PLSA_REDIRECTED_LOGON_INIT.ahk" { PLSA_REDIRECTED_LOGON_INIT }
#Import "..\..\..\..\..\Guid.ahk" { Guid }
#Import ".\PLSA_REDIRECTED_LOGON_CLEANUP_CALLBACK.ahk" { PLSA_REDIRECTED_LOGON_CLEANUP_CALLBACK }
#Import ".\PLSA_REDIRECTED_LOGON_GET_SUPP_CREDS.ahk" { PLSA_REDIRECTED_LOGON_GET_SUPP_CREDS }

/**
 * @namespace Windows.Win32.Security.Authentication.Identity
 */
export default struct SECPKG_REDIRECTED_LOGON_BUFFER {
    #StructPack 8

    RedirectedLogonGuid : Guid

    RedirectedLogonHandle : HANDLE

    Init : PLSA_REDIRECTED_LOGON_INIT

    Callback : PLSA_REDIRECTED_LOGON_CALLBACK

    CleanupCallback : PLSA_REDIRECTED_LOGON_CLEANUP_CALLBACK

    GetLogonCreds : PLSA_REDIRECTED_LOGON_GET_LOGON_CREDS

    GetSupplementalCreds : PLSA_REDIRECTED_LOGON_GET_SUPP_CREDS

    GetRedirectedLogonSid : PLSA_REDIRECTED_LOGON_GET_SID

}
