#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\PrintTicket\__Init.ahk" {*}
#Import export ".\ADDJOB_INFO_1A.ahk" {ADDJOB_INFO_1A}
#Import export ".\ADDJOB_INFO_1W.ahk" {ADDJOB_INFO_1W}
#Import export ".\ATTRIBUTE_INFO_1.ahk" {ATTRIBUTE_INFO_1}
#Import export ".\ATTRIBUTE_INFO_2.ahk" {ATTRIBUTE_INFO_2}
#Import export ".\ATTRIBUTE_INFO_3.ahk" {ATTRIBUTE_INFO_3}
#Import export ".\ATTRIBUTE_INFO_4.ahk" {ATTRIBUTE_INFO_4}
#Import export ".\Apis.ahk" {*}
#Import export ".\BIDI_DATA.ahk" {BIDI_DATA}
#Import export ".\BIDI_REQUEST_CONTAINER.ahk" {BIDI_REQUEST_CONTAINER}
#Import export ".\BIDI_REQUEST_DATA.ahk" {BIDI_REQUEST_DATA}
#Import export ".\BIDI_RESPONSE_CONTAINER.ahk" {BIDI_RESPONSE_CONTAINER}
#Import export ".\BIDI_RESPONSE_DATA.ahk" {BIDI_RESPONSE_DATA}
#Import export ".\BIDI_TYPE.ahk" {BIDI_TYPE}
#Import export ".\BINARY_CONTAINER.ahk" {BINARY_CONTAINER}
#Import export ".\BidiRequest.ahk" {BidiRequest}
#Import export ".\BidiRequestContainer.ahk" {BidiRequestContainer}
#Import export ".\BidiSpl.ahk" {BidiSpl}
#Import export ".\BranchOfficeJobData.ahk" {BranchOfficeJobData}
#Import export ".\BranchOfficeJobDataContainer.ahk" {BranchOfficeJobDataContainer}
#Import export ".\BranchOfficeJobDataError.ahk" {BranchOfficeJobDataError}
#Import export ".\BranchOfficeJobDataPipelineFailed.ahk" {BranchOfficeJobDataPipelineFailed}
#Import export ".\BranchOfficeJobDataPrinted.ahk" {BranchOfficeJobDataPrinted}
#Import export ".\BranchOfficeJobDataRendered.ahk" {BranchOfficeJobDataRendered}
#Import export ".\BranchOfficeLogOfflineFileFull.ahk" {BranchOfficeLogOfflineFileFull}
#Import export ".\COMPROPSHEETUI.ahk" {COMPROPSHEETUI}
#Import export ".\CONFIG_INFO_DATA_1.ahk" {CONFIG_INFO_DATA_1}
#Import export ".\CORE_PRINTER_DRIVERA.ahk" {CORE_PRINTER_DRIVERA}
#Import export ".\CORE_PRINTER_DRIVERW.ahk" {CORE_PRINTER_DRIVERW}
#Import export ".\CPSUICBPARAM.ahk" {CPSUICBPARAM}
#Import export ".\CPSUIDATABLOCK.ahk" {CPSUIDATABLOCK}
#Import export ".\CUSTOMSIZEPARAM.ahk" {CUSTOMSIZEPARAM}
#Import export ".\Constants.ahk" {*}
#Import export ".\DATATYPES_INFO_1A.ahk" {DATATYPES_INFO_1A}
#Import export ".\DATATYPES_INFO_1W.ahk" {DATATYPES_INFO_1W}
#Import export ".\DATA_HEADER.ahk" {DATA_HEADER}
#Import export ".\DELETE_PORT_DATA_1.ahk" {DELETE_PORT_DATA_1}
#Import export ".\DEVICEPROPERTYHEADER.ahk" {DEVICEPROPERTYHEADER}
#Import export ".\DEVQUERYPRINT_INFO.ahk" {DEVQUERYPRINT_INFO}
#Import export ".\DLGPAGE.ahk" {DLGPAGE}
#Import export ".\DOCEVENT_CREATEDCPRE.ahk" {DOCEVENT_CREATEDCPRE}
#Import export ".\DOCEVENT_ESCAPE.ahk" {DOCEVENT_ESCAPE}
#Import export ".\DOCEVENT_FILTER.ahk" {DOCEVENT_FILTER}
#Import export ".\DOCUMENTPROPERTYHEADER.ahk" {DOCUMENTPROPERTYHEADER}
#Import export ".\DOC_INFO_1A.ahk" {DOC_INFO_1A}
#Import export ".\DOC_INFO_1W.ahk" {DOC_INFO_1W}
#Import export ".\DOC_INFO_2A.ahk" {DOC_INFO_2A}
#Import export ".\DOC_INFO_2W.ahk" {DOC_INFO_2W}
#Import export ".\DOC_INFO_3A.ahk" {DOC_INFO_3A}
#Import export ".\DOC_INFO_3W.ahk" {DOC_INFO_3W}
#Import export ".\DOC_INFO_INTERNAL.ahk" {DOC_INFO_INTERNAL}
#Import export ".\DRIVER_INFO_1A.ahk" {DRIVER_INFO_1A}
#Import export ".\DRIVER_INFO_1W.ahk" {DRIVER_INFO_1W}
#Import export ".\DRIVER_INFO_2A.ahk" {DRIVER_INFO_2A}
#Import export ".\DRIVER_INFO_2W.ahk" {DRIVER_INFO_2W}
#Import export ".\DRIVER_INFO_3A.ahk" {DRIVER_INFO_3A}
#Import export ".\DRIVER_INFO_3W.ahk" {DRIVER_INFO_3W}
#Import export ".\DRIVER_INFO_4A.ahk" {DRIVER_INFO_4A}
#Import export ".\DRIVER_INFO_4W.ahk" {DRIVER_INFO_4W}
#Import export ".\DRIVER_INFO_5A.ahk" {DRIVER_INFO_5A}
#Import export ".\DRIVER_INFO_5W.ahk" {DRIVER_INFO_5W}
#Import export ".\DRIVER_INFO_6A.ahk" {DRIVER_INFO_6A}
#Import export ".\DRIVER_INFO_6W.ahk" {DRIVER_INFO_6W}
#Import export ".\DRIVER_INFO_8A.ahk" {DRIVER_INFO_8A}
#Import export ".\DRIVER_INFO_8W.ahk" {DRIVER_INFO_8W}
#Import export ".\DRIVER_UPGRADE_INFO_1.ahk" {DRIVER_UPGRADE_INFO_1}
#Import export ".\DRIVER_UPGRADE_INFO_2.ahk" {DRIVER_UPGRADE_INFO_2}
#Import export ".\EATTRIBUTE_DATATYPE.ahk" {EATTRIBUTE_DATATYPE}
#Import export ".\EBranchOfficeJobEventType.ahk" {EBranchOfficeJobEventType}
#Import export ".\EMFPLAYPROC.ahk" {EMFPLAYPROC}
#Import export ".\EPrintPropertyType.ahk" {EPrintPropertyType}
#Import export ".\EPrintXPSJobOperation.ahk" {EPrintXPSJobOperation}
#Import export ".\EPrintXPSJobProgress.ahk" {EPrintXPSJobProgress}
#Import export ".\EXTCHKBOX.ahk" {EXTCHKBOX}
#Import export ".\EXTPUSH.ahk" {EXTPUSH}
#Import export ".\EXTTEXTMETRIC.ahk" {EXTTEXTMETRIC}
#Import export ".\EXpsCompressionOptions.ahk" {EXpsCompressionOptions}
#Import export ".\EXpsFontOptions.ahk" {EXpsFontOptions}
#Import export ".\EXpsFontRestriction.ahk" {EXpsFontRestriction}
#Import export ".\EXpsJobConsumption.ahk" {EXpsJobConsumption}
#Import export ".\FINDPRINTERCHANGENOTIFICATION_HANDLE.ahk" {FINDPRINTERCHANGENOTIFICATION_HANDLE}
#Import export ".\FORM_INFO_1A.ahk" {FORM_INFO_1A}
#Import export ".\FORM_INFO_1W.ahk" {FORM_INFO_1W}
#Import export ".\FORM_INFO_2A.ahk" {FORM_INFO_2A}
#Import export ".\FORM_INFO_2W.ahk" {FORM_INFO_2W}
#Import export ".\GLYPHRUN.ahk" {GLYPHRUN}
#Import export ".\IAsyncGetSendNotificationCookie.ahk" {IAsyncGetSendNotificationCookie}
#Import export ".\IAsyncGetSrvReferralCookie.ahk" {IAsyncGetSrvReferralCookie}
#Import export ".\IBidiAsyncNotifyChannel.ahk" {IBidiAsyncNotifyChannel}
#Import export ".\IBidiRequest.ahk" {IBidiRequest}
#Import export ".\IBidiRequestContainer.ahk" {IBidiRequestContainer}
#Import export ".\IBidiSpl.ahk" {IBidiSpl}
#Import export ".\IBidiSpl2.ahk" {IBidiSpl2}
#Import export ".\IFixedDocument.ahk" {IFixedDocument}
#Import export ".\IFixedDocumentSequence.ahk" {IFixedDocumentSequence}
#Import export ".\IFixedPage.ahk" {IFixedPage}
#Import export ".\IImgCreateErrorInfo.ahk" {IImgCreateErrorInfo}
#Import export ".\IImgErrorInfo.ahk" {IImgErrorInfo}
#Import export ".\IInterFilterCommunicator.ahk" {IInterFilterCommunicator}
#Import export ".\INSERTPSUIPAGE_INFO.ahk" {INSERTPSUIPAGE_INFO}
#Import export ".\INVOC.ahk" {INVOC}
#Import export ".\IPartBase.ahk" {IPartBase}
#Import export ".\IPartColorProfile.ahk" {IPartColorProfile}
#Import export ".\IPartDiscardControl.ahk" {IPartDiscardControl}
#Import export ".\IPartFont.ahk" {IPartFont}
#Import export ".\IPartFont2.ahk" {IPartFont2}
#Import export ".\IPartImage.ahk" {IPartImage}
#Import export ".\IPartPrintTicket.ahk" {IPartPrintTicket}
#Import export ".\IPartResourceDictionary.ahk" {IPartResourceDictionary}
#Import export ".\IPartThumbnail.ahk" {IPartThumbnail}
#Import export ".\IPrintAsyncCookie.ahk" {IPrintAsyncCookie}
#Import export ".\IPrintAsyncNewChannelCookie.ahk" {IPrintAsyncNewChannelCookie}
#Import export ".\IPrintAsyncNotify.ahk" {IPrintAsyncNotify}
#Import export ".\IPrintAsyncNotifyCallback.ahk" {IPrintAsyncNotifyCallback}
#Import export ".\IPrintAsyncNotifyChannel.ahk" {IPrintAsyncNotifyChannel}
#Import export ".\IPrintAsyncNotifyDataObject.ahk" {IPrintAsyncNotifyDataObject}
#Import export ".\IPrintAsyncNotifyRegistration.ahk" {IPrintAsyncNotifyRegistration}
#Import export ".\IPrintAsyncNotifyServerReferral.ahk" {IPrintAsyncNotifyServerReferral}
#Import export ".\IPrintBidiAsyncNotifyRegistration.ahk" {IPrintBidiAsyncNotifyRegistration}
#Import export ".\IPrintClassObjectFactory.ahk" {IPrintClassObjectFactory}
#Import export ".\IPrintCoreHelper.ahk" {IPrintCoreHelper}
#Import export ".\IPrintCoreHelperPS.ahk" {IPrintCoreHelperPS}
#Import export ".\IPrintCoreHelperUni.ahk" {IPrintCoreHelperUni}
#Import export ".\IPrintCoreHelperUni2.ahk" {IPrintCoreHelperUni2}
#Import export ".\IPrintCoreUI2.ahk" {IPrintCoreUI2}
#Import export ".\IPrintJob.ahk" {IPrintJob}
#Import export ".\IPrintJobCollection.ahk" {IPrintJobCollection}
#Import export ".\IPrintOemCommon.ahk" {IPrintOemCommon}
#Import export ".\IPrintOemDriverUI.ahk" {IPrintOemDriverUI}
#Import export ".\IPrintOemUI.ahk" {IPrintOemUI}
#Import export ".\IPrintOemUI2.ahk" {IPrintOemUI2}
#Import export ".\IPrintOemUIMXDC.ahk" {IPrintOemUIMXDC}
#Import export ".\IPrintPipelineFilter.ahk" {IPrintPipelineFilter}
#Import export ".\IPrintPipelineManagerControl.ahk" {IPrintPipelineManagerControl}
#Import export ".\IPrintPipelineProgressReport.ahk" {IPrintPipelineProgressReport}
#Import export ".\IPrintPipelinePropertyBag.ahk" {IPrintPipelinePropertyBag}
#Import export ".\IPrintPreviewDxgiPackageTarget.ahk" {IPrintPreviewDxgiPackageTarget}
#Import export ".\IPrintReadStream.ahk" {IPrintReadStream}
#Import export ".\IPrintReadStreamFactory.ahk" {IPrintReadStreamFactory}
#Import export ".\IPrintSchemaAsyncOperation.ahk" {IPrintSchemaAsyncOperation}
#Import export ".\IPrintSchemaAsyncOperationEvent.ahk" {IPrintSchemaAsyncOperationEvent}
#Import export ".\IPrintSchemaCapabilities.ahk" {IPrintSchemaCapabilities}
#Import export ".\IPrintSchemaCapabilities2.ahk" {IPrintSchemaCapabilities2}
#Import export ".\IPrintSchemaDisplayableElement.ahk" {IPrintSchemaDisplayableElement}
#Import export ".\IPrintSchemaElement.ahk" {IPrintSchemaElement}
#Import export ".\IPrintSchemaFeature.ahk" {IPrintSchemaFeature}
#Import export ".\IPrintSchemaNUpOption.ahk" {IPrintSchemaNUpOption}
#Import export ".\IPrintSchemaOption.ahk" {IPrintSchemaOption}
#Import export ".\IPrintSchemaOptionCollection.ahk" {IPrintSchemaOptionCollection}
#Import export ".\IPrintSchemaPageImageableSize.ahk" {IPrintSchemaPageImageableSize}
#Import export ".\IPrintSchemaPageMediaSizeOption.ahk" {IPrintSchemaPageMediaSizeOption}
#Import export ".\IPrintSchemaParameterDefinition.ahk" {IPrintSchemaParameterDefinition}
#Import export ".\IPrintSchemaParameterInitializer.ahk" {IPrintSchemaParameterInitializer}
#Import export ".\IPrintSchemaTicket.ahk" {IPrintSchemaTicket}
#Import export ".\IPrintSchemaTicket2.ahk" {IPrintSchemaTicket2}
#Import export ".\IPrintTicketProvider.ahk" {IPrintTicketProvider}
#Import export ".\IPrintTicketProvider2.ahk" {IPrintTicketProvider2}
#Import export ".\IPrintUnidiAsyncNotifyRegistration.ahk" {IPrintUnidiAsyncNotifyRegistration}
#Import export ".\IPrintWriteStream.ahk" {IPrintWriteStream}
#Import export ".\IPrintWriteStreamFlush.ahk" {IPrintWriteStreamFlush}
#Import export ".\IPrinterBidiSetRequestCallback.ahk" {IPrinterBidiSetRequestCallback}
#Import export ".\IPrinterExtensionAsyncOperation.ahk" {IPrinterExtensionAsyncOperation}
#Import export ".\IPrinterExtensionContext.ahk" {IPrinterExtensionContext}
#Import export ".\IPrinterExtensionContextCollection.ahk" {IPrinterExtensionContextCollection}
#Import export ".\IPrinterExtensionEvent.ahk" {IPrinterExtensionEvent}
#Import export ".\IPrinterExtensionEventArgs.ahk" {IPrinterExtensionEventArgs}
#Import export ".\IPrinterExtensionManager.ahk" {IPrinterExtensionManager}
#Import export ".\IPrinterExtensionRequest.ahk" {IPrinterExtensionRequest}
#Import export ".\IPrinterPropertyBag.ahk" {IPrinterPropertyBag}
#Import export ".\IPrinterQueue.ahk" {IPrinterQueue}
#Import export ".\IPrinterQueue2.ahk" {IPrinterQueue2}
#Import export ".\IPrinterQueueEvent.ahk" {IPrinterQueueEvent}
#Import export ".\IPrinterQueueView.ahk" {IPrinterQueueView}
#Import export ".\IPrinterQueueViewEvent.ahk" {IPrinterQueueViewEvent}
#Import export ".\IPrinterScriptContext.ahk" {IPrinterScriptContext}
#Import export ".\IPrinterScriptablePropertyBag.ahk" {IPrinterScriptablePropertyBag}
#Import export ".\IPrinterScriptablePropertyBag2.ahk" {IPrinterScriptablePropertyBag2}
#Import export ".\IPrinterScriptableSequentialStream.ahk" {IPrinterScriptableSequentialStream}
#Import export ".\IPrinterScriptableStream.ahk" {IPrinterScriptableStream}
#Import export ".\IXpsDocument.ahk" {IXpsDocument}
#Import export ".\IXpsDocumentConsumer.ahk" {IXpsDocumentConsumer}
#Import export ".\IXpsDocumentProvider.ahk" {IXpsDocumentProvider}
#Import export ".\IXpsPartIterator.ahk" {IXpsPartIterator}
#Import export ".\IXpsRasterizationFactory.ahk" {IXpsRasterizationFactory}
#Import export ".\IXpsRasterizationFactory1.ahk" {IXpsRasterizationFactory1}
#Import export ".\IXpsRasterizationFactory2.ahk" {IXpsRasterizationFactory2}
#Import export ".\IXpsRasterizer.ahk" {IXpsRasterizer}
#Import export ".\IXpsRasterizerNotificationCallback.ahk" {IXpsRasterizerNotificationCallback}
#Import export ".\ImgErrorInfo.ahk" {ImgErrorInfo}
#Import export ".\JOB_INFO_1A.ahk" {JOB_INFO_1A}
#Import export ".\JOB_INFO_1W.ahk" {JOB_INFO_1W}
#Import export ".\JOB_INFO_2A.ahk" {JOB_INFO_2A}
#Import export ".\JOB_INFO_2W.ahk" {JOB_INFO_2W}
#Import export ".\JOB_INFO_3.ahk" {JOB_INFO_3}
#Import export ".\JOB_INFO_4A.ahk" {JOB_INFO_4A}
#Import export ".\JOB_INFO_4W.ahk" {JOB_INFO_4W}
#Import export ".\KERNDATA.ahk" {KERNDATA}
#Import export ".\MAPTABLE.ahk" {MAPTABLE}
#Import export ".\MESSAGEBOX_PARAMS.ahk" {MESSAGEBOX_PARAMS}
#Import export ".\MONITOR.ahk" {MONITOR}
#Import export ".\MONITOR2.ahk" {MONITOR2}
#Import export ".\MONITOREX.ahk" {MONITOREX}
#Import export ".\MONITORINIT.ahk" {MONITORINIT}
#Import export ".\MONITORREG.ahk" {MONITORREG}
#Import export ".\MONITORUI.ahk" {MONITORUI}
#Import export ".\MONITOR_INFO_1A.ahk" {MONITOR_INFO_1A}
#Import export ".\MONITOR_INFO_1W.ahk" {MONITOR_INFO_1W}
#Import export ".\MONITOR_INFO_2A.ahk" {MONITOR_INFO_2A}
#Import export ".\MONITOR_INFO_2W.ahk" {MONITOR_INFO_2W}
#Import export ".\MXDC_ESCAPE_HEADER_T.ahk" {MXDC_ESCAPE_HEADER_T}
#Import export ".\MXDC_GET_FILENAME_DATA_T.ahk" {MXDC_GET_FILENAME_DATA_T}
#Import export ".\MXDC_IMAGE_TYPE_ENUMS.ahk" {MXDC_IMAGE_TYPE_ENUMS}
#Import export ".\MXDC_LANDSCAPE_ROTATION_ENUMS.ahk" {MXDC_LANDSCAPE_ROTATION_ENUMS}
#Import export ".\MXDC_PRINTTICKET_DATA_T.ahk" {MXDC_PRINTTICKET_DATA_T}
#Import export ".\MXDC_PRINTTICKET_ESCAPE_T.ahk" {MXDC_PRINTTICKET_ESCAPE_T}
#Import export ".\MXDC_S0PAGE_DATA_T.ahk" {MXDC_S0PAGE_DATA_T}
#Import export ".\MXDC_S0PAGE_PASSTHROUGH_ESCAPE_T.ahk" {MXDC_S0PAGE_PASSTHROUGH_ESCAPE_T}
#Import export ".\MXDC_S0PAGE_RESOURCE_ESCAPE_T.ahk" {MXDC_S0PAGE_RESOURCE_ESCAPE_T}
#Import export ".\MXDC_S0_PAGE_ENUMS.ahk" {MXDC_S0_PAGE_ENUMS}
#Import export ".\MXDC_XPS_S0PAGE_RESOURCE_T.ahk" {MXDC_XPS_S0PAGE_RESOURCE_T}
#Import export ".\NOTIFICATION_CALLBACK_COMMANDS.ahk" {NOTIFICATION_CALLBACK_COMMANDS}
#Import export ".\NOTIFICATION_CONFIG_1.ahk" {NOTIFICATION_CONFIG_1}
#Import export ".\NOTIFICATION_CONFIG_FLAGS.ahk" {NOTIFICATION_CONFIG_FLAGS}
#Import export ".\OEMCUIPCALLBACK.ahk" {OEMCUIPCALLBACK}
#Import export ".\OEMCUIPPARAM.ahk" {OEMCUIPPARAM}
#Import export ".\OEMDMPARAM.ahk" {OEMDMPARAM}
#Import export ".\OEMFONTINSTPARAM.ahk" {OEMFONTINSTPARAM}
#Import export ".\OEMUIOBJ.ahk" {OEMUIOBJ}
#Import export ".\OEMUIPROCS.ahk" {OEMUIPROCS}
#Import export ".\OEMUIPSPARAM.ahk" {OEMUIPSPARAM}
#Import export ".\OEM_DMEXTRAHEADER.ahk" {OEM_DMEXTRAHEADER}
#Import export ".\OIEXT.ahk" {OIEXT}
#Import export ".\OPTCOMBO.ahk" {OPTCOMBO}
#Import export ".\OPTITEM.ahk" {OPTITEM}
#Import export ".\OPTPARAM.ahk" {OPTPARAM}
#Import export ".\OPTTYPE.ahk" {OPTTYPE}
#Import export ".\PFNCOMPROPSHEET.ahk" {PFNCOMPROPSHEET}
#Import export ".\PFNPROPSHEETUI.ahk" {PFNPROPSHEETUI}
#Import export ".\PFN_DrvGetDriverSetting.ahk" {PFN_DrvGetDriverSetting}
#Import export ".\PFN_DrvUpdateUISetting.ahk" {PFN_DrvUpdateUISetting}
#Import export ".\PFN_DrvUpgradeRegistrySetting.ahk" {PFN_DrvUpgradeRegistrySetting}
#Import export ".\PFN_PRINTING_ADDPORT.ahk" {PFN_PRINTING_ADDPORT}
#Import export ".\PFN_PRINTING_ADDPORT2.ahk" {PFN_PRINTING_ADDPORT2}
#Import export ".\PFN_PRINTING_ADDPORTEX.ahk" {PFN_PRINTING_ADDPORTEX}
#Import export ".\PFN_PRINTING_ADDPORTEX2.ahk" {PFN_PRINTING_ADDPORTEX2}
#Import export ".\PFN_PRINTING_CLOSEPORT.ahk" {PFN_PRINTING_CLOSEPORT}
#Import export ".\PFN_PRINTING_CLOSEPORT2.ahk" {PFN_PRINTING_CLOSEPORT2}
#Import export ".\PFN_PRINTING_CONFIGUREPORT.ahk" {PFN_PRINTING_CONFIGUREPORT}
#Import export ".\PFN_PRINTING_CONFIGUREPORT2.ahk" {PFN_PRINTING_CONFIGUREPORT2}
#Import export ".\PFN_PRINTING_DELETEPORT.ahk" {PFN_PRINTING_DELETEPORT}
#Import export ".\PFN_PRINTING_DELETEPORT2.ahk" {PFN_PRINTING_DELETEPORT2}
#Import export ".\PFN_PRINTING_ENDDOCPORT.ahk" {PFN_PRINTING_ENDDOCPORT}
#Import export ".\PFN_PRINTING_ENDDOCPORT2.ahk" {PFN_PRINTING_ENDDOCPORT2}
#Import export ".\PFN_PRINTING_ENUMPORTS.ahk" {PFN_PRINTING_ENUMPORTS}
#Import export ".\PFN_PRINTING_ENUMPORTS2.ahk" {PFN_PRINTING_ENUMPORTS2}
#Import export ".\PFN_PRINTING_GETPRINTERDATAFROMPORT.ahk" {PFN_PRINTING_GETPRINTERDATAFROMPORT}
#Import export ".\PFN_PRINTING_GETPRINTERDATAFROMPORT2.ahk" {PFN_PRINTING_GETPRINTERDATAFROMPORT2}
#Import export ".\PFN_PRINTING_NOTIFYUNUSEDPORTS2.ahk" {PFN_PRINTING_NOTIFYUNUSEDPORTS2}
#Import export ".\PFN_PRINTING_NOTIFYUSEDPORTS2.ahk" {PFN_PRINTING_NOTIFYUSEDPORTS2}
#Import export ".\PFN_PRINTING_OPENPORT.ahk" {PFN_PRINTING_OPENPORT}
#Import export ".\PFN_PRINTING_OPENPORT2.ahk" {PFN_PRINTING_OPENPORT2}
#Import export ".\PFN_PRINTING_OPENPORTEX.ahk" {PFN_PRINTING_OPENPORTEX}
#Import export ".\PFN_PRINTING_OPENPORTEX2.ahk" {PFN_PRINTING_OPENPORTEX2}
#Import export ".\PFN_PRINTING_POWEREVENT2.ahk" {PFN_PRINTING_POWEREVENT2}
#Import export ".\PFN_PRINTING_READPORT.ahk" {PFN_PRINTING_READPORT}
#Import export ".\PFN_PRINTING_READPORT2.ahk" {PFN_PRINTING_READPORT2}
#Import export ".\PFN_PRINTING_SENDRECVBIDIDATAFROMPORT2.ahk" {PFN_PRINTING_SENDRECVBIDIDATAFROMPORT2}
#Import export ".\PFN_PRINTING_SETPORTTIMEOUTS.ahk" {PFN_PRINTING_SETPORTTIMEOUTS}
#Import export ".\PFN_PRINTING_SETPORTTIMEOUTS2.ahk" {PFN_PRINTING_SETPORTTIMEOUTS2}
#Import export ".\PFN_PRINTING_SHUTDOWN2.ahk" {PFN_PRINTING_SHUTDOWN2}
#Import export ".\PFN_PRINTING_STARTDOCPORT.ahk" {PFN_PRINTING_STARTDOCPORT}
#Import export ".\PFN_PRINTING_STARTDOCPORT2.ahk" {PFN_PRINTING_STARTDOCPORT2}
#Import export ".\PFN_PRINTING_WRITEPORT.ahk" {PFN_PRINTING_WRITEPORT}
#Import export ".\PFN_PRINTING_WRITEPORT2.ahk" {PFN_PRINTING_WRITEPORT2}
#Import export ".\PFN_PRINTING_XCVCLOSEPORT.ahk" {PFN_PRINTING_XCVCLOSEPORT}
#Import export ".\PFN_PRINTING_XCVCLOSEPORT2.ahk" {PFN_PRINTING_XCVCLOSEPORT2}
#Import export ".\PFN_PRINTING_XCVDATAPORT.ahk" {PFN_PRINTING_XCVDATAPORT}
#Import export ".\PFN_PRINTING_XCVDATAPORT2.ahk" {PFN_PRINTING_XCVDATAPORT2}
#Import export ".\PFN_PRINTING_XCVOPENPORT.ahk" {PFN_PRINTING_XCVOPENPORT}
#Import export ".\PFN_PRINTING_XCVOPENPORT2.ahk" {PFN_PRINTING_XCVOPENPORT2}
#Import export ".\PORT_DATA_1.ahk" {PORT_DATA_1}
#Import export ".\PORT_DATA_2.ahk" {PORT_DATA_2}
#Import export ".\PORT_DATA_LIST_1.ahk" {PORT_DATA_LIST_1}
#Import export ".\PORT_INFO_1A.ahk" {PORT_INFO_1A}
#Import export ".\PORT_INFO_1W.ahk" {PORT_INFO_1W}
#Import export ".\PORT_INFO_2A.ahk" {PORT_INFO_2A}
#Import export ".\PORT_INFO_2W.ahk" {PORT_INFO_2W}
#Import export ".\PORT_INFO_3A.ahk" {PORT_INFO_3A}
#Import export ".\PORT_INFO_3W.ahk" {PORT_INFO_3W}
#Import export ".\PRINTER_ACCESS_RIGHTS.ahk" {PRINTER_ACCESS_RIGHTS}
#Import export ".\PRINTER_CONNECTION_INFO_1A.ahk" {PRINTER_CONNECTION_INFO_1A}
#Import export ".\PRINTER_CONNECTION_INFO_1W.ahk" {PRINTER_CONNECTION_INFO_1W}
#Import export ".\PRINTER_DEFAULTSA.ahk" {PRINTER_DEFAULTSA}
#Import export ".\PRINTER_DEFAULTSW.ahk" {PRINTER_DEFAULTSW}
#Import export ".\PRINTER_ENUM_VALUESA.ahk" {PRINTER_ENUM_VALUESA}
#Import export ".\PRINTER_ENUM_VALUESW.ahk" {PRINTER_ENUM_VALUESW}
#Import export ".\PRINTER_EVENT_ATTRIBUTES_INFO.ahk" {PRINTER_EVENT_ATTRIBUTES_INFO}
#Import export ".\PRINTER_HANDLE.ahk" {PRINTER_HANDLE}
#Import export ".\PRINTER_INFO_1A.ahk" {PRINTER_INFO_1A}
#Import export ".\PRINTER_INFO_1W.ahk" {PRINTER_INFO_1W}
#Import export ".\PRINTER_INFO_2A.ahk" {PRINTER_INFO_2A}
#Import export ".\PRINTER_INFO_2W.ahk" {PRINTER_INFO_2W}
#Import export ".\PRINTER_INFO_3.ahk" {PRINTER_INFO_3}
#Import export ".\PRINTER_INFO_4A.ahk" {PRINTER_INFO_4A}
#Import export ".\PRINTER_INFO_4W.ahk" {PRINTER_INFO_4W}
#Import export ".\PRINTER_INFO_5A.ahk" {PRINTER_INFO_5A}
#Import export ".\PRINTER_INFO_5W.ahk" {PRINTER_INFO_5W}
#Import export ".\PRINTER_INFO_6.ahk" {PRINTER_INFO_6}
#Import export ".\PRINTER_INFO_7A.ahk" {PRINTER_INFO_7A}
#Import export ".\PRINTER_INFO_7W.ahk" {PRINTER_INFO_7W}
#Import export ".\PRINTER_INFO_8A.ahk" {PRINTER_INFO_8A}
#Import export ".\PRINTER_INFO_8W.ahk" {PRINTER_INFO_8W}
#Import export ".\PRINTER_INFO_9A.ahk" {PRINTER_INFO_9A}
#Import export ".\PRINTER_INFO_9W.ahk" {PRINTER_INFO_9W}
#Import export ".\PRINTER_NOTIFY_INFO.ahk" {PRINTER_NOTIFY_INFO}
#Import export ".\PRINTER_NOTIFY_INFO_DATA.ahk" {PRINTER_NOTIFY_INFO_DATA}
#Import export ".\PRINTER_NOTIFY_INIT.ahk" {PRINTER_NOTIFY_INIT}
#Import export ".\PRINTER_NOTIFY_OPTIONS.ahk" {PRINTER_NOTIFY_OPTIONS}
#Import export ".\PRINTER_NOTIFY_OPTIONS_TYPE.ahk" {PRINTER_NOTIFY_OPTIONS_TYPE}
#Import export ".\PRINTER_OPTIONSA.ahk" {PRINTER_OPTIONSA}
#Import export ".\PRINTER_OPTIONSW.ahk" {PRINTER_OPTIONSW}
#Import export ".\PRINTER_OPTION_FLAGS.ahk" {PRINTER_OPTION_FLAGS}
#Import export ".\PRINTIFI32.ahk" {PRINTIFI32}
#Import export ".\PRINTPROCESSOROPENDATA.ahk" {PRINTPROCESSOROPENDATA}
#Import export ".\PRINTPROCESSOR_CAPS_1.ahk" {PRINTPROCESSOR_CAPS_1}
#Import export ".\PRINTPROCESSOR_CAPS_2.ahk" {PRINTPROCESSOR_CAPS_2}
#Import export ".\PRINTPROCESSOR_INFO_1A.ahk" {PRINTPROCESSOR_INFO_1A}
#Import export ".\PRINTPROCESSOR_INFO_1W.ahk" {PRINTPROCESSOR_INFO_1W}
#Import export ".\PRINTPROVIDOR.ahk" {PRINTPROVIDOR}
#Import export ".\PRINT_EXECUTION_CONTEXT.ahk" {PRINT_EXECUTION_CONTEXT}
#Import export ".\PRINT_EXECUTION_DATA.ahk" {PRINT_EXECUTION_DATA}
#Import export ".\PRINT_FEATURE_OPTION.ahk" {PRINT_FEATURE_OPTION}
#Import export ".\PROPSHEETUI_GETICON_INFO.ahk" {PROPSHEETUI_GETICON_INFO}
#Import export ".\PROPSHEETUI_INFO.ahk" {PROPSHEETUI_INFO}
#Import export ".\PROPSHEETUI_INFO_HEADER.ahk" {PROPSHEETUI_INFO_HEADER}
#Import export ".\PROVIDOR_INFO_1A.ahk" {PROVIDOR_INFO_1A}
#Import export ".\PROVIDOR_INFO_1W.ahk" {PROVIDOR_INFO_1W}
#Import export ".\PROVIDOR_INFO_2A.ahk" {PROVIDOR_INFO_2A}
#Import export ".\PROVIDOR_INFO_2W.ahk" {PROVIDOR_INFO_2W}
#Import export ".\PSCRIPT5_PRIVATE_DEVMODE.ahk" {PSCRIPT5_PRIVATE_DEVMODE}
#Import export ".\PSPINFO.ahk" {PSPINFO}
#Import export ".\PUBLISHERINFO.ahk" {PUBLISHERINFO}
#Import export ".\PageCountType.ahk" {PageCountType}
#Import export ".\PrintAsyncNotifyConversationStyle.ahk" {PrintAsyncNotifyConversationStyle}
#Import export ".\PrintAsyncNotifyError.ahk" {PrintAsyncNotifyError}
#Import export ".\PrintAsyncNotifyUserFilter.ahk" {PrintAsyncNotifyUserFilter}
#Import export ".\PrintJobStatus.ahk" {PrintJobStatus}
#Import export ".\PrintNamedProperty.ahk" {PrintNamedProperty}
#Import export ".\PrintPropertiesCollection.ahk" {PrintPropertiesCollection}
#Import export ".\PrintPropertyValue.ahk" {PrintPropertyValue}
#Import export ".\PrintSchemaAsyncOperation.ahk" {PrintSchemaAsyncOperation}
#Import export ".\PrintSchemaConstrainedSetting.ahk" {PrintSchemaConstrainedSetting}
#Import export ".\PrintSchemaParameterDataType.ahk" {PrintSchemaParameterDataType}
#Import export ".\PrintSchemaSelectionType.ahk" {PrintSchemaSelectionType}
#Import export ".\PrinterExtensionManager.ahk" {PrinterExtensionManager}
#Import export ".\PrinterQueue.ahk" {PrinterQueue}
#Import export ".\PrinterQueueView.ahk" {PrinterQueueView}
#Import export ".\ROUTER_NOTIFY_CALLBACK.ahk" {ROUTER_NOTIFY_CALLBACK}
#Import export ".\SETRESULT_INFO.ahk" {SETRESULT_INFO}
#Import export ".\SHIMOPTS.ahk" {SHIMOPTS}
#Import export ".\SHOWUIPARAMS.ahk" {SHOWUIPARAMS}
#Import export ".\SIMULATE_CAPS_1.ahk" {SIMULATE_CAPS_1}
#Import export ".\SPLCLIENT_INFO_1.ahk" {SPLCLIENT_INFO_1}
#Import export ".\SPLCLIENT_INFO_2_W2K.ahk" {SPLCLIENT_INFO_2_W2K}
#Import export ".\SPLCLIENT_INFO_2_WINXP.ahk" {SPLCLIENT_INFO_2_WINXP}
#Import export ".\SPLCLIENT_INFO_3_VISTA.ahk" {SPLCLIENT_INFO_3_VISTA}
#Import export ".\SPLCLIENT_INFO_INTERNAL.ahk" {SPLCLIENT_INFO_INTERNAL}
#Import export ".\TRANSDATA.ahk" {TRANSDATA}
#Import export ".\UFF_FILEHEADER.ahk" {UFF_FILEHEADER}
#Import export ".\UFF_FONTDIRECTORY.ahk" {UFF_FONTDIRECTORY}
#Import export ".\UI_TYPE.ahk" {UI_TYPE}
#Import export ".\UNIDRVINFO.ahk" {UNIDRVINFO}
#Import export ".\UNIDRV_PRIVATE_DEVMODE.ahk" {UNIDRV_PRIVATE_DEVMODE}
#Import export ".\UNIFM_HDR.ahk" {UNIFM_HDR}
#Import export ".\UNI_CODEPAGEINFO.ahk" {UNI_CODEPAGEINFO}
#Import export ".\UNI_GLYPHSETDATA.ahk" {UNI_GLYPHSETDATA}
#Import export ".\USERDATA.ahk" {USERDATA}
#Import export ".\WIDTHRUN.ahk" {WIDTHRUN}
#Import export ".\WIDTHTABLE.ahk" {WIDTHTABLE}
#Import export ".\XPSRAS_BACKGROUND_COLOR.ahk" {XPSRAS_BACKGROUND_COLOR}
#Import export ".\XPSRAS_PIXEL_FORMAT.ahk" {XPSRAS_PIXEL_FORMAT}
#Import export ".\XPSRAS_RENDERING_MODE.ahk" {XPSRAS_RENDERING_MODE}
#Import export ".\_CPSUICALLBACK.ahk" {_CPSUICALLBACK}
#Import export ".\_SPLCLIENT_INFO_2_V3.ahk" {_SPLCLIENT_INFO_2_V3}
