#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PFN_PRINTING_ADDPORT2.ahk" { PFN_PRINTING_ADDPORT2 }
#Import ".\PFN_PRINTING_ADDPORTEX2.ahk" { PFN_PRINTING_ADDPORTEX2 }
#Import ".\PFN_PRINTING_CLOSEPORT2.ahk" { PFN_PRINTING_CLOSEPORT2 }
#Import ".\PFN_PRINTING_CONFIGUREPORT2.ahk" { PFN_PRINTING_CONFIGUREPORT2 }
#Import ".\PFN_PRINTING_DELETEPORT2.ahk" { PFN_PRINTING_DELETEPORT2 }
#Import ".\PFN_PRINTING_ENDDOCPORT2.ahk" { PFN_PRINTING_ENDDOCPORT2 }
#Import ".\PFN_PRINTING_ENUMPORTS2.ahk" { PFN_PRINTING_ENUMPORTS2 }
#Import ".\PFN_PRINTING_GETPRINTERDATAFROMPORT2.ahk" { PFN_PRINTING_GETPRINTERDATAFROMPORT2 }
#Import ".\PFN_PRINTING_NOTIFYUNUSEDPORTS2.ahk" { PFN_PRINTING_NOTIFYUNUSEDPORTS2 }
#Import ".\PFN_PRINTING_NOTIFYUSEDPORTS2.ahk" { PFN_PRINTING_NOTIFYUSEDPORTS2 }
#Import ".\PFN_PRINTING_OPENPORT2.ahk" { PFN_PRINTING_OPENPORT2 }
#Import ".\PFN_PRINTING_OPENPORTEX2.ahk" { PFN_PRINTING_OPENPORTEX2 }
#Import ".\PFN_PRINTING_POWEREVENT2.ahk" { PFN_PRINTING_POWEREVENT2 }
#Import ".\PFN_PRINTING_READPORT2.ahk" { PFN_PRINTING_READPORT2 }
#Import ".\PFN_PRINTING_SENDRECVBIDIDATAFROMPORT2.ahk" { PFN_PRINTING_SENDRECVBIDIDATAFROMPORT2 }
#Import ".\PFN_PRINTING_SETPORTTIMEOUTS2.ahk" { PFN_PRINTING_SETPORTTIMEOUTS2 }
#Import ".\PFN_PRINTING_SHUTDOWN2.ahk" { PFN_PRINTING_SHUTDOWN2 }
#Import ".\PFN_PRINTING_STARTDOCPORT2.ahk" { PFN_PRINTING_STARTDOCPORT2 }
#Import ".\PFN_PRINTING_WRITEPORT2.ahk" { PFN_PRINTING_WRITEPORT2 }
#Import ".\PFN_PRINTING_XCVCLOSEPORT2.ahk" { PFN_PRINTING_XCVCLOSEPORT2 }
#Import ".\PFN_PRINTING_XCVDATAPORT2.ahk" { PFN_PRINTING_XCVDATAPORT2 }
#Import ".\PFN_PRINTING_XCVOPENPORT2.ahk" { PFN_PRINTING_XCVOPENPORT2 }

/**
 * @namespace Windows.Win32.Graphics.Printing
 */
export default struct MONITOR2 {
    #StructPack 8

    cbSize : UInt32 := this.Size

    pfnEnumPorts : PFN_PRINTING_ENUMPORTS2

    pfnOpenPort : PFN_PRINTING_OPENPORT2

    pfnOpenPortEx : PFN_PRINTING_OPENPORTEX2

    pfnStartDocPort : PFN_PRINTING_STARTDOCPORT2

    pfnWritePort : PFN_PRINTING_WRITEPORT2

    pfnReadPort : PFN_PRINTING_READPORT2

    pfnEndDocPort : PFN_PRINTING_ENDDOCPORT2

    pfnClosePort : PFN_PRINTING_CLOSEPORT2

    pfnAddPort : PFN_PRINTING_ADDPORT2

    pfnAddPortEx : PFN_PRINTING_ADDPORTEX2

    pfnConfigurePort : PFN_PRINTING_CONFIGUREPORT2

    pfnDeletePort : PFN_PRINTING_DELETEPORT2

    pfnGetPrinterDataFromPort : PFN_PRINTING_GETPRINTERDATAFROMPORT2

    pfnSetPortTimeOuts : PFN_PRINTING_SETPORTTIMEOUTS2

    pfnXcvOpenPort : PFN_PRINTING_XCVOPENPORT2

    pfnXcvDataPort : PFN_PRINTING_XCVDATAPORT2

    pfnXcvClosePort : PFN_PRINTING_XCVCLOSEPORT2

    pfnShutdown : PFN_PRINTING_SHUTDOWN2

    pfnSendRecvBidiDataFromPort : PFN_PRINTING_SENDRECVBIDIDATAFROMPORT2

    pfnNotifyUsedPorts : PFN_PRINTING_NOTIFYUSEDPORTS2

    pfnNotifyUnusedPorts : PFN_PRINTING_NOTIFYUNUSEDPORTS2

    pfnPowerEvent : PFN_PRINTING_POWEREVENT2

}
