#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\DeviceDiscoveryMechanism.ahk" {DeviceDiscoveryMechanism}
#Import export ".\IWSDAddress.ahk" {IWSDAddress}
#Import export ".\IWSDAsyncCallback.ahk" {IWSDAsyncCallback}
#Import export ".\IWSDAsyncResult.ahk" {IWSDAsyncResult}
#Import export ".\IWSDAttachment.ahk" {IWSDAttachment}
#Import export ".\IWSDDeviceHost.ahk" {IWSDDeviceHost}
#Import export ".\IWSDDeviceHostNotify.ahk" {IWSDDeviceHostNotify}
#Import export ".\IWSDDeviceProxy.ahk" {IWSDDeviceProxy}
#Import export ".\IWSDEndpointProxy.ahk" {IWSDEndpointProxy}
#Import export ".\IWSDEventingStatus.ahk" {IWSDEventingStatus}
#Import export ".\IWSDHttpAddress.ahk" {IWSDHttpAddress}
#Import export ".\IWSDHttpAuthParameters.ahk" {IWSDHttpAuthParameters}
#Import export ".\IWSDHttpMessageParameters.ahk" {IWSDHttpMessageParameters}
#Import export ".\IWSDInboundAttachment.ahk" {IWSDInboundAttachment}
#Import export ".\IWSDMessageParameters.ahk" {IWSDMessageParameters}
#Import export ".\IWSDMetadataExchange.ahk" {IWSDMetadataExchange}
#Import export ".\IWSDOutboundAttachment.ahk" {IWSDOutboundAttachment}
#Import export ".\IWSDSSLClientCertificate.ahk" {IWSDSSLClientCertificate}
#Import export ".\IWSDScopeMatchingRule.ahk" {IWSDScopeMatchingRule}
#Import export ".\IWSDServiceMessaging.ahk" {IWSDServiceMessaging}
#Import export ".\IWSDServiceProxy.ahk" {IWSDServiceProxy}
#Import export ".\IWSDServiceProxyEventing.ahk" {IWSDServiceProxyEventing}
#Import export ".\IWSDSignatureProperty.ahk" {IWSDSignatureProperty}
#Import export ".\IWSDTransportAddress.ahk" {IWSDTransportAddress}
#Import export ".\IWSDUdpAddress.ahk" {IWSDUdpAddress}
#Import export ".\IWSDUdpMessageParameters.ahk" {IWSDUdpMessageParameters}
#Import export ".\IWSDXMLContext.ahk" {IWSDXMLContext}
#Import export ".\IWSDiscoveredService.ahk" {IWSDiscoveredService}
#Import export ".\IWSDiscoveryProvider.ahk" {IWSDiscoveryProvider}
#Import export ".\IWSDiscoveryProviderNotify.ahk" {IWSDiscoveryProviderNotify}
#Import export ".\IWSDiscoveryPublisher.ahk" {IWSDiscoveryPublisher}
#Import export ".\IWSDiscoveryPublisherNotify.ahk" {IWSDiscoveryPublisherNotify}
#Import export ".\PWSD_SOAP_MESSAGE_HANDLER.ahk" {PWSD_SOAP_MESSAGE_HANDLER}
#Import export ".\REQUESTBODY_GetStatus.ahk" {REQUESTBODY_GetStatus}
#Import export ".\REQUESTBODY_Renew.ahk" {REQUESTBODY_Renew}
#Import export ".\REQUESTBODY_Subscribe.ahk" {REQUESTBODY_Subscribe}
#Import export ".\REQUESTBODY_Unsubscribe.ahk" {REQUESTBODY_Unsubscribe}
#Import export ".\RESPONSEBODY_GetMetadata.ahk" {RESPONSEBODY_GetMetadata}
#Import export ".\RESPONSEBODY_GetStatus.ahk" {RESPONSEBODY_GetStatus}
#Import export ".\RESPONSEBODY_Renew.ahk" {RESPONSEBODY_Renew}
#Import export ".\RESPONSEBODY_Subscribe.ahk" {RESPONSEBODY_Subscribe}
#Import export ".\RESPONSEBODY_SubscriptionEnd.ahk" {RESPONSEBODY_SubscriptionEnd}
#Import export ".\WSDEventType.ahk" {WSDEventType}
#Import export ".\WSDUdpMessageType.ahk" {WSDUdpMessageType}
#Import export ".\WSDUdpRetransmitParams.ahk" {WSDUdpRetransmitParams}
#Import export ".\WSDXML_ATTRIBUTE.ahk" {WSDXML_ATTRIBUTE}
#Import export ".\WSDXML_ELEMENT.ahk" {WSDXML_ELEMENT}
#Import export ".\WSDXML_ELEMENT_LIST.ahk" {WSDXML_ELEMENT_LIST}
#Import export ".\WSDXML_NAME.ahk" {WSDXML_NAME}
#Import export ".\WSDXML_NAMESPACE.ahk" {WSDXML_NAMESPACE}
#Import export ".\WSDXML_NODE.ahk" {WSDXML_NODE}
#Import export ".\WSDXML_OP.ahk" {WSDXML_OP}
#Import export ".\WSDXML_PREFIX_MAPPING.ahk" {WSDXML_PREFIX_MAPPING}
#Import export ".\WSDXML_TEXT.ahk" {WSDXML_TEXT}
#Import export ".\WSDXML_TYPE.ahk" {WSDXML_TYPE}
#Import export ".\WSD_APP_SEQUENCE.ahk" {WSD_APP_SEQUENCE}
#Import export ".\WSD_BYE.ahk" {WSD_BYE}
#Import export ".\WSD_CONFIG_ADDRESSES.ahk" {WSD_CONFIG_ADDRESSES}
#Import export ".\WSD_CONFIG_PARAM.ahk" {WSD_CONFIG_PARAM}
#Import export ".\WSD_CONFIG_PARAM_TYPE.ahk" {WSD_CONFIG_PARAM_TYPE}
#Import export ".\WSD_DATETIME.ahk" {WSD_DATETIME}
#Import export ".\WSD_DURATION.ahk" {WSD_DURATION}
#Import export ".\WSD_ENDPOINT_REFERENCE.ahk" {WSD_ENDPOINT_REFERENCE}
#Import export ".\WSD_ENDPOINT_REFERENCE_LIST.ahk" {WSD_ENDPOINT_REFERENCE_LIST}
#Import export ".\WSD_EVENT.ahk" {WSD_EVENT}
#Import export ".\WSD_EVENTING_DELIVERY_MODE.ahk" {WSD_EVENTING_DELIVERY_MODE}
#Import export ".\WSD_EVENTING_DELIVERY_MODE_PUSH.ahk" {WSD_EVENTING_DELIVERY_MODE_PUSH}
#Import export ".\WSD_EVENTING_EXPIRES.ahk" {WSD_EVENTING_EXPIRES}
#Import export ".\WSD_EVENTING_FILTER.ahk" {WSD_EVENTING_FILTER}
#Import export ".\WSD_EVENTING_FILTER_ACTION.ahk" {WSD_EVENTING_FILTER_ACTION}
#Import export ".\WSD_HANDLER_CONTEXT.ahk" {WSD_HANDLER_CONTEXT}
#Import export ".\WSD_HEADER_RELATESTO.ahk" {WSD_HEADER_RELATESTO}
#Import export ".\WSD_HELLO.ahk" {WSD_HELLO}
#Import export ".\WSD_HOST_METADATA.ahk" {WSD_HOST_METADATA}
#Import export ".\WSD_LOCALIZED_STRING.ahk" {WSD_LOCALIZED_STRING}
#Import export ".\WSD_LOCALIZED_STRING_LIST.ahk" {WSD_LOCALIZED_STRING_LIST}
#Import export ".\WSD_METADATA_SECTION.ahk" {WSD_METADATA_SECTION}
#Import export ".\WSD_METADATA_SECTION_LIST.ahk" {WSD_METADATA_SECTION_LIST}
#Import export ".\WSD_NAME_LIST.ahk" {WSD_NAME_LIST}
#Import export ".\WSD_OPERATION.ahk" {WSD_OPERATION}
#Import export ".\WSD_PORT_TYPE.ahk" {WSD_PORT_TYPE}
#Import export ".\WSD_PROBE.ahk" {WSD_PROBE}
#Import export ".\WSD_PROBE_MATCH.ahk" {WSD_PROBE_MATCH}
#Import export ".\WSD_PROBE_MATCHES.ahk" {WSD_PROBE_MATCHES}
#Import export ".\WSD_PROBE_MATCH_LIST.ahk" {WSD_PROBE_MATCH_LIST}
#Import export ".\WSD_PROTOCOL_TYPE.ahk" {WSD_PROTOCOL_TYPE}
#Import export ".\WSD_REFERENCE_PARAMETERS.ahk" {WSD_REFERENCE_PARAMETERS}
#Import export ".\WSD_REFERENCE_PROPERTIES.ahk" {WSD_REFERENCE_PROPERTIES}
#Import export ".\WSD_RELATIONSHIP_METADATA.ahk" {WSD_RELATIONSHIP_METADATA}
#Import export ".\WSD_RESOLVE.ahk" {WSD_RESOLVE}
#Import export ".\WSD_RESOLVE_MATCH.ahk" {WSD_RESOLVE_MATCH}
#Import export ".\WSD_RESOLVE_MATCHES.ahk" {WSD_RESOLVE_MATCHES}
#Import export ".\WSD_SCOPES.ahk" {WSD_SCOPES}
#Import export ".\WSD_SECURITY_CERT_VALIDATION.ahk" {WSD_SECURITY_CERT_VALIDATION}
#Import export ".\WSD_SECURITY_CERT_VALIDATION_V1.ahk" {WSD_SECURITY_CERT_VALIDATION_V1}
#Import export ".\WSD_SECURITY_SIGNATURE_VALIDATION.ahk" {WSD_SECURITY_SIGNATURE_VALIDATION}
#Import export ".\WSD_SERVICE_METADATA.ahk" {WSD_SERVICE_METADATA}
#Import export ".\WSD_SERVICE_METADATA_LIST.ahk" {WSD_SERVICE_METADATA_LIST}
#Import export ".\WSD_SOAP_FAULT.ahk" {WSD_SOAP_FAULT}
#Import export ".\WSD_SOAP_FAULT_CODE.ahk" {WSD_SOAP_FAULT_CODE}
#Import export ".\WSD_SOAP_FAULT_REASON.ahk" {WSD_SOAP_FAULT_REASON}
#Import export ".\WSD_SOAP_FAULT_SUBCODE.ahk" {WSD_SOAP_FAULT_SUBCODE}
#Import export ".\WSD_SOAP_HEADER.ahk" {WSD_SOAP_HEADER}
#Import export ".\WSD_SOAP_MESSAGE.ahk" {WSD_SOAP_MESSAGE}
#Import export ".\WSD_STUB_FUNCTION.ahk" {WSD_STUB_FUNCTION}
#Import export ".\WSD_SYNCHRONOUS_RESPONSE_CONTEXT.ahk" {WSD_SYNCHRONOUS_RESPONSE_CONTEXT}
#Import export ".\WSD_THIS_DEVICE_METADATA.ahk" {WSD_THIS_DEVICE_METADATA}
#Import export ".\WSD_THIS_MODEL_METADATA.ahk" {WSD_THIS_MODEL_METADATA}
#Import export ".\WSD_UNKNOWN_LOOKUP.ahk" {WSD_UNKNOWN_LOOKUP}
#Import export ".\WSD_URI_LIST.ahk" {WSD_URI_LIST}
