#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\Guid.ahk" { Guid }
#Import ".\WSDXML_TYPE.ahk" { WSDXML_TYPE }
#Import "..\..\Foundation\PWSTR.ahk" { PWSTR }
#Import "..\..\Foundation\HRESULT.ahk" { HRESULT }
#Import ".\WSDXML_NAME.ahk" { WSDXML_NAME }
#Import "..\..\System\Com\IUnknown.ahk" { IUnknown }
#Import ".\WSDXML_NAMESPACE.ahk" { WSDXML_NAMESPACE }

/**
 * Is a collection of namespaces and types used in a WSDAPI stack.
 * @remarks
 * This interface is used by the XML parser and generator to store and access namespaces, names, and message schema information. Applications can call <a href="https://docs.microsoft.com/windows/desktop/api/wsdxml/nf-wsdxml-iwsdxmlcontext-addnamespace">AddNamespace</a> and <a href="https://docs.microsoft.com/windows/desktop/api/wsdxml/nf-wsdxml-iwsdxmlcontext-addnametonamespace">AddNameToNamespace</a> directly to add and access names in new or existing namespaces. Additionally, <a href="https://docs.microsoft.com/windows/desktop/WsdApi/web-services-for-devices-code-generator">generated code</a> will call <a href="https://docs.microsoft.com/windows/desktop/api/wsdxml/nf-wsdxml-iwsdxmlcontext-setnamespaces">SetNamespaces</a> and <a href="https://docs.microsoft.com/windows/desktop/api/wsdxml/nf-wsdxml-iwsdxmlcontext-settypes">SetTypes</a> to ensure service layer data is properly set up in the XML context.
 * @see https://learn.microsoft.com/windows/win32/api/wsdxml/nn-wsdxml-iwsdxmlcontext
 * @namespace Windows.Win32.Devices.WebServicesOnDevices
 */
export default struct IWSDXMLContext extends IUnknown {
    /**
     * The interface identifier for IWSDXMLContext
     * @type {Guid}
     */
    static IID := Guid("{75d8f3ee-3e5a-43b4-a15a-bcf6887460c0}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for IWSDXMLContext interfaces
    */
    struct Vtbl extends IUnknown.Vtbl {
        AddNamespace       : IntPtr
        AddNameToNamespace : IntPtr
        SetNamespaces      : IntPtr
        SetTypes           : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := IWSDXMLContext.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * Creates an object that represents a namespace in an XML context.
     * @remarks
     * The returned <a href="https://docs.microsoft.com/windows/desktop/api/wsdxmldom/ns-wsdxmldom-wsdxml_namespace">WSDXML_NAMESPACE</a> structure can be used to force an association between the namespace prefix (as specified by <i>pszSuggestedPrefix</i>) and the namespace URI  (as specified by <i>pszUri</i>). Once this association is established, the  XML generator will produce XML with the specified namespace prefix. 
     * 
     * You can call <b>AddNamespace</b> to retrieve the <a href="https://docs.microsoft.com/windows/desktop/api/wsdxmldom/ns-wsdxmldom-wsdxml_namespace">WSDXML_NAMESPACE</a>  structure created when a namespace was automatically generated by a call to <a href="https://docs.microsoft.com/windows/desktop/api/wsdxml/nf-wsdxml-iwsdxmlcontext-addnametonamespace">AddNameToNamespace</a>.
     * @param {PWSTR} pszUri The URI of the namespace.
     * @param {PWSTR} pszSuggestedPrefix The namespace prefix to use when generating XML. If the namespace already exists, <i>pszSuggestedPrefix</i> will overwrite the prefix currently associated with the namespace. The XML context may assign a different namespace prefix. The prefix assigned by the XML context takes precedence over the suggested prefix. The <b>PreferredPrefix</b> member of the structure pointed to by <i>ppNamespace</i> contains the prefix assigned by the XML context.
     * @returns {Pointer<WSDXML_NAMESPACE>} Pointer to the address of the <a href="https://docs.microsoft.com/windows/desktop/api/wsdxmldom/ns-wsdxmldom-wsdxml_namespace">WSDXML_NAMESPACE</a> structure that represents the namespace. You must deallocate <i>ppNamespace</i> by calling <a href="https://docs.microsoft.com/windows/desktop/api/wsdutil/nf-wsdutil-wsdfreelinkedmemory">WSDFreeLinkedMemory</a>. This parameter is optional.
     * @see https://learn.microsoft.com/windows/win32/api/wsdxml/nf-wsdxml-iwsdxmlcontext-addnamespace
     */
    AddNamespace(pszUri, pszSuggestedPrefix) {
        pszUri := pszUri is String ? StrPtr(pszUri) : pszUri
        pszSuggestedPrefix := pszSuggestedPrefix is String ? StrPtr(pszSuggestedPrefix) : pszSuggestedPrefix

        result := ComCall(3, this, "ptr", pszUri, "ptr", pszSuggestedPrefix, "ptr*", &ppNamespace := 0, "HRESULT")
        return ppNamespace
    }

    /**
     * Creates an object that represents a name in a namespace in an XML context.
     * @remarks
     * <b>AddNameToNamespace</b> can be used when creating XML elements for extensible sections. Extensible sections are represented by the <b>any</b> element in a schema. The returned <a href="https://docs.microsoft.com/windows/desktop/api/wsdxmldom/ns-wsdxmldom-wsdxml_name">WSDXML_NAME</a> structure pointed to by <i>ppName</i> can be used to specify the name associated with the extension content. When building a <a href="https://docs.microsoft.com/windows/desktop/api/wsdxmldom/ns-wsdxmldom-wsdxml_element">WSDXML_ELEMENT</a> structure that represents extension content, use the returned <b>WSDXML_NAME</b> structure for the element's  <b>Name</b> member.
     * @param {PWSTR} pszUri The URI of the XML namespace in which this name will be created. If this namespace does not already exist in the XML context, a new namespace structure will be generated automatically.
     * @param {PWSTR} pszName The name to add to the namespace specified by <i>pszUri</i>.
     * @returns {Pointer<WSDXML_NAME>} A <a href="https://docs.microsoft.com/windows/desktop/api/wsdxmldom/ns-wsdxmldom-wsdxml_name">WSDXML_NAME</a> structure for the newly created name. You must deallocate <i>ppName</i> by calling <a href="https://docs.microsoft.com/windows/desktop/api/wsdutil/nf-wsdutil-wsdfreelinkedmemory">WSDFreeLinkedMemory</a>. This parameter is optional.
     * @see https://learn.microsoft.com/windows/win32/api/wsdxml/nf-wsdxml-iwsdxmlcontext-addnametonamespace
     */
    AddNameToNamespace(pszUri, pszName) {
        pszUri := pszUri is String ? StrPtr(pszUri) : pszUri
        pszName := pszName is String ? StrPtr(pszName) : pszName

        result := ComCall(4, this, "ptr", pszUri, "ptr", pszName, "ptr*", &ppName := 0, "HRESULT")
        return ppName
    }

    /**
     * Associates custom namespaces with the XML context object.
     * @param {Pointer<Pointer<WSDXML_NAMESPACE>>} pNamespaces An array of <a href="https://docs.microsoft.com/windows/desktop/api/wsdxmldom/ns-wsdxmldom-wsdxml_namespace">WSDXML_NAMESPACE</a> structures.
     * @param {Integer} wNamespacesCount The number of namespaces in the <i>pNamespaces</i> array.
     * @param {Integer} bLayerNumber The layer number associated with the <a href="https://docs.microsoft.com/windows/desktop/WsdApi/web-services-for-devices-code-generator">generated service code</a>.
     * @returns {HRESULT} Possible return values include, but are not limited to, the following:
     * 
     * <table>
     * <tr>
     * <th>Return code</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>S_OK</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * Method completed successfully.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_INVALIDARG</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * <i>pNamespaces</i> is <b>NULL</b> or  <i>bLayerNumber</i> is greater than or equal to WSD_XMLCONTEXT_NUM_LAYERS (16).
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_OUTOFMEMORY</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * Insufficient memory to complete the operation.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_FAIL</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The method failed.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api/wsdxml/nf-wsdxml-iwsdxmlcontext-setnamespaces
     */
    SetNamespaces(pNamespaces, wNamespacesCount, bLayerNumber) {
        pNamespacesMarshal := pNamespaces is VarRef ? "ptr*" : "ptr"

        result := ComCall(5, this, pNamespacesMarshal, pNamespaces, "ushort", wNamespacesCount, "char", bLayerNumber, "HRESULT")
        return result
    }

    /**
     * Associates custom message types with the XML context object.
     * @param {Pointer<Pointer<WSDXML_TYPE>>} pTypes An array of <a href="https://docs.microsoft.com/windows/desktop/api/wsdxmldom/ns-wsdxmldom-wsdxml_type">WSDXML_TYPE</a> structures that represent the set of messages for the <a href="https://docs.microsoft.com/windows/desktop/WsdApi/web-services-for-devices-code-generator">generated code</a>.
     * @param {Integer} dwTypesCount The number of types in the <i>pTypes</i> array.
     * @param {Integer} bLayerNumber The layer number associated with the <a href="https://docs.microsoft.com/windows/desktop/WsdApi/web-services-for-devices-code-generator">generated service code</a>.
     * @returns {HRESULT} Possible return values include, but are not limited to, the following:
     * 
     * <table>
     * <tr>
     * <th>Return code</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>S_OK</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * Method completed successfully.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_INVALIDARG</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * <i>pTypes</i> is <b>NULL</b> or <i>bLayerNumber</i> is greater than or equal to WSD_XMLCONTEXT_NUM_LAYERS (16).
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_OUTOFMEMORY</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * Insufficient memory to complete the operation.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_FAIL</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The method failed.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api/wsdxml/nf-wsdxml-iwsdxmlcontext-settypes
     */
    SetTypes(pTypes, dwTypesCount, bLayerNumber) {
        pTypesMarshal := pTypes is VarRef ? "ptr*" : "ptr"

        result := ComCall(6, this, pTypesMarshal, pTypes, "uint", dwTypesCount, "char", bLayerNumber, "HRESULT")
        return result
    }

    Query(iid) {
        if (IWSDXMLContext.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.AddNamespace := CallbackCreate(GetMethod(implObj, "AddNamespace"), flags, 4)
        this.vtbl.AddNameToNamespace := CallbackCreate(GetMethod(implObj, "AddNameToNamespace"), flags, 4)
        this.vtbl.SetNamespaces := CallbackCreate(GetMethod(implObj, "SetNamespaces"), flags, 4)
        this.vtbl.SetTypes := CallbackCreate(GetMethod(implObj, "SetTypes"), flags, 4)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.AddNamespace)
        CallbackFree(this.vtbl.AddNameToNamespace)
        CallbackFree(this.vtbl.SetNamespaces)
        CallbackFree(this.vtbl.SetTypes)
    }
}
