#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32Struct.ahk

/**
 * Specifies an XML namespace.
 * @remarks
 * <b>WSDXML_NAMESPACE</b> represents the association between a namespace URI and a list of names belonging to that namespace. Additionally, it provides a <b>PreferredPrefix</b> for the namespace, which gives guidance on the default prefix to use for a specified namespace. In the context of WSDAPI, there are two types of namespaces: static namespaces and dynamic namespaces.
 * 
 * Static namespaces are user provided, well known, and assumed to be complete namespaces, in that all names belonging to the namespace should be in names array. When processing a received XML document, any element or attribute in the document that claims to be in a static namespace but has a name not listed in that namespace is treated as an error. Static namespaces are typically generated pre-compile time, by a tool like WSDCodeGen.
 * 
 * Dynamic namespaces are generated by WSDAPI. These are built when new namespaces are seen in XML documents. With dynamic namespaces, no assumptions can be made about whether a specified name actually belongs to the formal namespace or not, so all names are accepted as being part of the namespace. As such, dynamic namespaces expand the <b>Names</b> array as they process new names in a specified document.
 * @see https://learn.microsoft.com/windows/win32/api/wsdxmldom/ns-wsdxmldom-wsdxml_namespace
 * @namespace Windows.Win32.Devices.WebServicesOnDevices
 * @version v4.0.30319
 */
class WSDXML_NAMESPACE extends Win32Struct
{
    static sizeof => 32

    static packingSize => 8

    /**
     * The URI that identifies the namespace.
     * @type {PWSTR}
     */
    Uri {
        get => NumGet(this, 0, "ptr")
        set => NumPut("ptr", value, this, 0)
    }

    /**
     * The preferred prefix to be used in XML prefix mappings.
     * @type {PWSTR}
     */
    PreferredPrefix {
        get => NumGet(this, 8, "ptr")
        set => NumPut("ptr", value, this, 8)
    }

    /**
     * Reference to an array of <a href="https://docs.microsoft.com/windows/desktop/api/wsdxmldom/ns-wsdxmldom-wsdxml_name">WSDXML_NAME</a> structures that specify the names in the namespace.
     * @type {Pointer<WSDXML_NAME>}
     */
    Names {
        get => NumGet(this, 16, "ptr")
        set => NumPut("ptr", value, this, 16)
    }

    /**
     * The number of names in the <b>Names</b> array.
     * @type {Integer}
     */
    NamesCount {
        get => NumGet(this, 24, "ushort")
        set => NumPut("ushort", value, this, 24)
    }

    /**
     * The encoded reference for the namespace.
     * @type {Integer}
     */
    Encoding {
        get => NumGet(this, 26, "ushort")
        set => NumPut("ushort", value, this, 26)
    }
}
