#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import "..\..\Foundation\PWSTR.ahk" { PWSTR }
#Import ".\WSDXML_NAME.ahk" { WSDXML_NAME }

/**
 * Specifies an XML namespace.
 * @remarks
 * <b>WSDXML_NAMESPACE</b> represents the association between a namespace URI and a list of names belonging to that namespace. Additionally, it provides a <b>PreferredPrefix</b> for the namespace, which gives guidance on the default prefix to use for a specified namespace. In the context of WSDAPI, there are two types of namespaces: static namespaces and dynamic namespaces.
 * 
 * Static namespaces are user provided, well known, and assumed to be complete namespaces, in that all names belonging to the namespace should be in names array. When processing a received XML document, any element or attribute in the document that claims to be in a static namespace but has a name not listed in that namespace is treated as an error. Static namespaces are typically generated pre-compile time, by a tool like WSDCodeGen.
 * 
 * Dynamic namespaces are generated by WSDAPI. These are built when new namespaces are seen in XML documents. With dynamic namespaces, no assumptions can be made about whether a specified name actually belongs to the formal namespace or not, so all names are accepted as being part of the namespace. As such, dynamic namespaces expand the <b>Names</b> array as they process new names in a specified document.
 * @see https://learn.microsoft.com/windows/win32/api/wsdxmldom/ns-wsdxmldom-wsdxml_namespace
 * @namespace Windows.Win32.Devices.WebServicesOnDevices
 */
export default struct WSDXML_NAMESPACE {
    #StructPack 8

    /**
     * The URI that identifies the namespace.
     */
    Uri : PWSTR

    /**
     * The preferred prefix to be used in XML prefix mappings.
     */
    PreferredPrefix : PWSTR

    __Names_ptr : IntPtr
    /**
     * Reference to an array of <a href="https://docs.microsoft.com/windows/desktop/api/wsdxmldom/ns-wsdxmldom-wsdxml_name">WSDXML_NAME</a> structures that specify the names in the namespace.
     */
    Names {
        get => (addr := this.__Names_ptr) ? WSDXML_NAME.At(addr) : unset
        set => this.__Names_ptr := (IsSet(value) && value) ? value.Ptr : 0
    }

    /**
     * The number of names in the <b>Names</b> array.
     */
    NamesCount : UInt16

    /**
     * The encoded reference for the namespace.
     */
    Encoding : UInt16

}
