#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\KEY_INFORMATION_CLASS.ahk" {KEY_INFORMATION_CLASS}
#Import export ".\KEY_SET_INFORMATION_CLASS.ahk" {KEY_SET_INFORMATION_CLASS}
#Import export ".\KEY_VALUE_ENTRY.ahk" {KEY_VALUE_ENTRY}
#Import export ".\KEY_VALUE_INFORMATION_CLASS.ahk" {KEY_VALUE_INFORMATION_CLASS}
#Import export ".\REG_ENUMERATE_KEY_INFORMATION.ahk" {REG_ENUMERATE_KEY_INFORMATION}
#Import export ".\REG_ENUMERATE_VALUE_KEY_INFORMATION.ahk" {REG_ENUMERATE_VALUE_KEY_INFORMATION}
#Import export ".\REG_QUERY_KEY_INFORMATION.ahk" {REG_QUERY_KEY_INFORMATION}
#Import export ".\REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION.ahk" {REG_QUERY_MULTIPLE_VALUE_KEY_INFORMATION}
#Import export ".\REG_QUERY_VALUE_KEY_INFORMATION.ahk" {REG_QUERY_VALUE_KEY_INFORMATION}
#Import export ".\REG_SET_INFORMATION_KEY_INFORMATION.ahk" {REG_SET_INFORMATION_KEY_INFORMATION}
