#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\..\System\Com\IUnknown.ahk

/**
 * The IWMPUserEventSink interface receives event notifications from a custom video presenter.
 * @see https://learn.microsoft.com/windows/win32/api/wmpservices/nn-wmpservices-iwmpusereventsink
 * @namespace Windows.Win32.Media.MediaPlayer
 * @version v4.0.30319
 */
class IWMPUserEventSink extends IUnknown{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IWMPUserEventSink
     * @type {Guid}
     */
    static IID => Guid("{cfccfa72-c343-48c3-a2de-b7a4402e39f2}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 3

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["NotifyUserEvent"]

    /**
     * The NotifyUserEvent method notifies an application of an event generated by a custom video presenter that the application provided to the Enhanced Video Renderer (EVR).
     * @remarks
     * An application that embeds the Windows Media Player control can provide a custom video renderer for the EVR by calling <a href="https://docs.microsoft.com/windows/desktop/api/wmprealestate/nf-wmprealestate-iwmpvideorenderconfig-put_presenteractivate">IWMPVideoRenderConfig::put_presenterActivate</a>. As the custom video renderer runs, it can notify the EVR of events by calling <b>IMediaEventSink::Notify</b>. If the event code supplied by the custom video renderer is greater than or equal to WMPUE_EC_USER, the EVR passes the event notification along to the application by calling <b>NotifyUserEvent</b>.
     * 
     * The definition of WMPUE_EC_USER depends on the definition of EC_USER, which is defined in evcode.h.
     * 
     * <b>Windows Media Player 10 Mobile: </b>This method is not supported.
     * @param {Integer} EventCode An event code that is meaningful only to the application and the custom video renderer. The event code must have a value greater than or equal to WMPUE_EC_USER, which is defined in wmpservices.h.
     * @returns {HRESULT} The method returns an <b>HRESULT</b>. Possible values include, but are not limited to, those in the following table.
     * 
     * <table>
     * <tr>
     * <th>Value
     *                 </th>
     * <th>Description
     *                 </th>
     * </tr>
     * <tr>
     * <td>S_OK</td>
     * <td>The method succeeded.</td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api/wmpservices/nf-wmpservices-iwmpusereventsink-notifyuserevent
     */
    NotifyUserEvent(EventCode) {
        result := ComCall(3, this, "int", EventCode, "HRESULT")
        return result
    }
}
