#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\AddressSpaceRelation.ahk" {AddressSpaceRelation}
#Import export ".\Apis.ahk" {*}
#Import export ".\ArrayDimension.ahk" {ArrayDimension}
#Import export ".\BUSDATA.ahk" {BUSDATA}
#Import export ".\CKCL_DATA.ahk" {CKCL_DATA}
#Import export ".\CKCL_LISTHEAD.ahk" {CKCL_LISTHEAD}
#Import export ".\CPU_INFO.ahk" {CPU_INFO}
#Import export ".\CPU_INFO_v1.ahk" {CPU_INFO_v1}
#Import export ".\CPU_INFO_v2.ahk" {CPU_INFO_v2}
#Import export ".\CallingConventionKind.ahk" {CallingConventionKind}
#Import export ".\Constants.ahk" {*}
#Import export ".\DBGKD_DEBUG_DATA_HEADER32.ahk" {DBGKD_DEBUG_DATA_HEADER32}
#Import export ".\DBGKD_DEBUG_DATA_HEADER64.ahk" {DBGKD_DEBUG_DATA_HEADER64}
#Import export ".\DBGKD_GET_VERSION32.ahk" {DBGKD_GET_VERSION32}
#Import export ".\DBGKD_GET_VERSION64.ahk" {DBGKD_GET_VERSION64}
#Import export ".\DBGKD_MAJOR_TYPES.ahk" {DBGKD_MAJOR_TYPES}
#Import export ".\DBG_THREAD_ATTRIBUTES.ahk" {DBG_THREAD_ATTRIBUTES}
#Import export ".\DEBUG_ANALYSIS_PROCESSOR_INFO.ahk" {DEBUG_ANALYSIS_PROCESSOR_INFO}
#Import export ".\DEBUG_BREAKPOINT_PARAMETERS.ahk" {DEBUG_BREAKPOINT_PARAMETERS}
#Import export ".\DEBUG_CACHED_SYMBOL_INFO.ahk" {DEBUG_CACHED_SYMBOL_INFO}
#Import export ".\DEBUG_CLIENT_CONTEXT.ahk" {DEBUG_CLIENT_CONTEXT}
#Import export ".\DEBUG_CPU_MICROCODE_VERSION.ahk" {DEBUG_CPU_MICROCODE_VERSION}
#Import export ".\DEBUG_CPU_SPEED_INFO.ahk" {DEBUG_CPU_SPEED_INFO}
#Import export ".\DEBUG_CREATE_PROCESS_OPTIONS.ahk" {DEBUG_CREATE_PROCESS_OPTIONS}
#Import export ".\DEBUG_DECODE_ERROR.ahk" {DEBUG_DECODE_ERROR}
#Import export ".\DEBUG_DEVICE_OBJECT_INFO.ahk" {DEBUG_DEVICE_OBJECT_INFO}
#Import export ".\DEBUG_DRIVER_OBJECT_INFO.ahk" {DEBUG_DRIVER_OBJECT_INFO}
#Import export ".\DEBUG_EVENT_CONTEXT.ahk" {DEBUG_EVENT_CONTEXT}
#Import export ".\DEBUG_EXCEPTION_FILTER_PARAMETERS.ahk" {DEBUG_EXCEPTION_FILTER_PARAMETERS}
#Import export ".\DEBUG_FAILURE_TYPE.ahk" {DEBUG_FAILURE_TYPE}
#Import export ".\DEBUG_FLR_PARAM_TYPE.ahk" {DEBUG_FLR_PARAM_TYPE}
#Import export ".\DEBUG_GET_TEXT_COMPLETIONS_IN.ahk" {DEBUG_GET_TEXT_COMPLETIONS_IN}
#Import export ".\DEBUG_GET_TEXT_COMPLETIONS_OUT.ahk" {DEBUG_GET_TEXT_COMPLETIONS_OUT}
#Import export ".\DEBUG_HANDLE_DATA_BASIC.ahk" {DEBUG_HANDLE_DATA_BASIC}
#Import export ".\DEBUG_IRP_INFO.ahk" {DEBUG_IRP_INFO}
#Import export ".\DEBUG_IRP_STACK_INFO.ahk" {DEBUG_IRP_STACK_INFO}
#Import export ".\DEBUG_LAST_EVENT_INFO_BREAKPOINT.ahk" {DEBUG_LAST_EVENT_INFO_BREAKPOINT}
#Import export ".\DEBUG_LAST_EVENT_INFO_EXCEPTION.ahk" {DEBUG_LAST_EVENT_INFO_EXCEPTION}
#Import export ".\DEBUG_LAST_EVENT_INFO_EXIT_PROCESS.ahk" {DEBUG_LAST_EVENT_INFO_EXIT_PROCESS}
#Import export ".\DEBUG_LAST_EVENT_INFO_EXIT_THREAD.ahk" {DEBUG_LAST_EVENT_INFO_EXIT_THREAD}
#Import export ".\DEBUG_LAST_EVENT_INFO_LOAD_MODULE.ahk" {DEBUG_LAST_EVENT_INFO_LOAD_MODULE}
#Import export ".\DEBUG_LAST_EVENT_INFO_SERVICE_EXCEPTION.ahk" {DEBUG_LAST_EVENT_INFO_SERVICE_EXCEPTION}
#Import export ".\DEBUG_LAST_EVENT_INFO_SYSTEM_ERROR.ahk" {DEBUG_LAST_EVENT_INFO_SYSTEM_ERROR}
#Import export ".\DEBUG_LAST_EVENT_INFO_UNLOAD_MODULE.ahk" {DEBUG_LAST_EVENT_INFO_UNLOAD_MODULE}
#Import export ".\DEBUG_MODULE_AND_ID.ahk" {DEBUG_MODULE_AND_ID}
#Import export ".\DEBUG_MODULE_PARAMETERS.ahk" {DEBUG_MODULE_PARAMETERS}
#Import export ".\DEBUG_OFFSET_REGION.ahk" {DEBUG_OFFSET_REGION}
#Import export ".\DEBUG_PNP_TRIAGE_INFO.ahk" {DEBUG_PNP_TRIAGE_INFO}
#Import export ".\DEBUG_POOLTAG_DESCRIPTION.ahk" {DEBUG_POOLTAG_DESCRIPTION}
#Import export ".\DEBUG_POOL_DATA.ahk" {DEBUG_POOL_DATA}
#Import export ".\DEBUG_POOL_REGION.ahk" {DEBUG_POOL_REGION}
#Import export ".\DEBUG_PROCESSOR_IDENTIFICATION_ALL.ahk" {DEBUG_PROCESSOR_IDENTIFICATION_ALL}
#Import export ".\DEBUG_PROCESSOR_IDENTIFICATION_ALPHA.ahk" {DEBUG_PROCESSOR_IDENTIFICATION_ALPHA}
#Import export ".\DEBUG_PROCESSOR_IDENTIFICATION_AMD64.ahk" {DEBUG_PROCESSOR_IDENTIFICATION_AMD64}
#Import export ".\DEBUG_PROCESSOR_IDENTIFICATION_ARM.ahk" {DEBUG_PROCESSOR_IDENTIFICATION_ARM}
#Import export ".\DEBUG_PROCESSOR_IDENTIFICATION_ARM64.ahk" {DEBUG_PROCESSOR_IDENTIFICATION_ARM64}
#Import export ".\DEBUG_PROCESSOR_IDENTIFICATION_IA64.ahk" {DEBUG_PROCESSOR_IDENTIFICATION_IA64}
#Import export ".\DEBUG_PROCESSOR_IDENTIFICATION_X86.ahk" {DEBUG_PROCESSOR_IDENTIFICATION_X86}
#Import export ".\DEBUG_READ_USER_MINIDUMP_STREAM.ahk" {DEBUG_READ_USER_MINIDUMP_STREAM}
#Import export ".\DEBUG_REGISTER_DESCRIPTION.ahk" {DEBUG_REGISTER_DESCRIPTION}
#Import export ".\DEBUG_SMBIOS_INFO.ahk" {DEBUG_SMBIOS_INFO}
#Import export ".\DEBUG_SPECIFIC_FILTER_PARAMETERS.ahk" {DEBUG_SPECIFIC_FILTER_PARAMETERS}
#Import export ".\DEBUG_STACK_FRAME.ahk" {DEBUG_STACK_FRAME}
#Import export ".\DEBUG_STACK_FRAME_EX.ahk" {DEBUG_STACK_FRAME_EX}
#Import export ".\DEBUG_SYMBOL_ENTRY.ahk" {DEBUG_SYMBOL_ENTRY}
#Import export ".\DEBUG_SYMBOL_PARAMETERS.ahk" {DEBUG_SYMBOL_PARAMETERS}
#Import export ".\DEBUG_SYMBOL_SOURCE_ENTRY.ahk" {DEBUG_SYMBOL_SOURCE_ENTRY}
#Import export ".\DEBUG_THREAD_BASIC_INFORMATION.ahk" {DEBUG_THREAD_BASIC_INFORMATION}
#Import export ".\DEBUG_TRIAGE_FOLLOWUP_INFO.ahk" {DEBUG_TRIAGE_FOLLOWUP_INFO}
#Import export ".\DEBUG_TRIAGE_FOLLOWUP_INFO_2.ahk" {DEBUG_TRIAGE_FOLLOWUP_INFO_2}
#Import export ".\DEBUG_TYPED_DATA.ahk" {DEBUG_TYPED_DATA}
#Import export ".\DEBUG_VALUE.ahk" {DEBUG_VALUE}
#Import export ".\DebugBaseEventCallbacks.ahk" {DebugBaseEventCallbacks}
#Import export ".\DebugBaseEventCallbacksWide.ahk" {DebugBaseEventCallbacksWide}
#Import export ".\ENTRY_CALLBACK.ahk" {ENTRY_CALLBACK}
#Import export ".\EXTDLL_ITERATERTLBALANCEDNODES.ahk" {EXTDLL_ITERATERTLBALANCEDNODES}
#Import export ".\EXTDLL_QUERYDATABYTAG.ahk" {EXTDLL_QUERYDATABYTAG}
#Import export ".\EXTDLL_QUERYDATABYTAGEX.ahk" {EXTDLL_QUERYDATABYTAGEX}
#Import export ".\EXTSTACKTRACE.ahk" {EXTSTACKTRACE}
#Import export ".\EXTSTACKTRACE32.ahk" {EXTSTACKTRACE32}
#Import export ".\EXTSTACKTRACE64.ahk" {EXTSTACKTRACE64}
#Import export ".\EXTS_JOB_PROCESS_CALLBACK.ahk" {EXTS_JOB_PROCESS_CALLBACK}
#Import export ".\EXTS_TABLE_ENTRY_CALLBACK.ahk" {EXTS_TABLE_ENTRY_CALLBACK}
#Import export ".\EXT_ANALYSIS_PLUGIN.ahk" {EXT_ANALYSIS_PLUGIN}
#Import export ".\EXT_ANALYZER.ahk" {EXT_ANALYZER}
#Import export ".\EXT_API_VERSION.ahk" {EXT_API_VERSION}
#Import export ".\EXT_CAB_XML_DATA.ahk" {EXT_CAB_XML_DATA}
#Import export ".\EXT_DECODE_ERROR.ahk" {EXT_DECODE_ERROR}
#Import export ".\EXT_FIND_FILE.ahk" {EXT_FIND_FILE}
#Import export ".\EXT_GET_DEBUG_FAILURE_ANALYSIS.ahk" {EXT_GET_DEBUG_FAILURE_ANALYSIS}
#Import export ".\EXT_GET_ENVIRONMENT_VARIABLE.ahk" {EXT_GET_ENVIRONMENT_VARIABLE}
#Import export ".\EXT_GET_FAILURE_ANALYSIS.ahk" {EXT_GET_FAILURE_ANALYSIS}
#Import export ".\EXT_GET_FA_ENTRIES_DATA.ahk" {EXT_GET_FA_ENTRIES_DATA}
#Import export ".\EXT_GET_HANDLE_TRACE.ahk" {EXT_GET_HANDLE_TRACE}
#Import export ".\EXT_MATCH_PATTERN_A.ahk" {EXT_MATCH_PATTERN_A}
#Import export ".\EXT_RELOAD_TRIAGER.ahk" {EXT_RELOAD_TRIAGER}
#Import export ".\EXT_TARGET_INFO.ahk" {EXT_TARGET_INFO}
#Import export ".\EXT_TDOP.ahk" {EXT_TDOP}
#Import export ".\EXT_TRIAGE_FOLLOWUP.ahk" {EXT_TRIAGE_FOLLOWUP}
#Import export ".\EXT_TYPED_DATA.ahk" {EXT_TYPED_DATA}
#Import export ".\EXT_XML_DATA.ahk" {EXT_XML_DATA}
#Import export ".\ErrorClass.ahk" {ErrorClass}
#Import export ".\ExtendedArrayDimension.ahk" {ExtendedArrayDimension}
#Import export ".\ExtendedArrayDimensionFlags.ahk" {ExtendedArrayDimensionFlags}
#Import export ".\FA_ENTRY.ahk" {FA_ENTRY}
#Import export ".\FA_ENTRY_TYPE.ahk" {FA_ENTRY_TYPE}
#Import export ".\FA_EXTENSION_PLUGIN_PHASE.ahk" {FA_EXTENSION_PLUGIN_PHASE}
#Import export ".\FIELD_INFO.ahk" {FIELD_INFO}
#Import export ".\GET_CONTEXT_EX.ahk" {GET_CONTEXT_EX}
#Import export ".\GET_CURRENT_PROCESS_ADDRESS.ahk" {GET_CURRENT_PROCESS_ADDRESS}
#Import export ".\GET_CURRENT_THREAD_ADDRESS.ahk" {GET_CURRENT_THREAD_ADDRESS}
#Import export ".\GET_EXPRESSION_EX.ahk" {GET_EXPRESSION_EX}
#Import export ".\GET_INPUT_LINE.ahk" {GET_INPUT_LINE}
#Import export ".\GET_PEB_ADDRESS.ahk" {GET_PEB_ADDRESS}
#Import export ".\GET_SET_SYMPATH.ahk" {GET_SET_SYMPATH}
#Import export ".\GET_TEB_ADDRESS.ahk" {GET_TEB_ADDRESS}
#Import export ".\IActionEnumerator.ahk" {IActionEnumerator}
#Import export ".\IActionQueryConcept.ahk" {IActionQueryConcept}
#Import export ".\IActionableConcept.ahk" {IActionableConcept}
#Import export ".\ICodeAddressConcept.ahk" {ICodeAddressConcept}
#Import export ".\IComparableConcept.ahk" {IComparableConcept}
#Import export ".\IConstructableConcept.ahk" {IConstructableConcept}
#Import export ".\IDataModelConcept.ahk" {IDataModelConcept}
#Import export ".\IDataModelManager.ahk" {IDataModelManager}
#Import export ".\IDataModelManager2.ahk" {IDataModelManager2}
#Import export ".\IDataModelManager3.ahk" {IDataModelManager3}
#Import export ".\IDataModelManager4.ahk" {IDataModelManager4}
#Import export ".\IDataModelNameBinder.ahk" {IDataModelNameBinder}
#Import export ".\IDataModelScript.ahk" {IDataModelScript}
#Import export ".\IDataModelScript2.ahk" {IDataModelScript2}
#Import export ".\IDataModelScriptClient.ahk" {IDataModelScriptClient}
#Import export ".\IDataModelScriptDebug.ahk" {IDataModelScriptDebug}
#Import export ".\IDataModelScriptDebug2.ahk" {IDataModelScriptDebug2}
#Import export ".\IDataModelScriptDebugBreakpoint.ahk" {IDataModelScriptDebugBreakpoint}
#Import export ".\IDataModelScriptDebugBreakpointEnumerator.ahk" {IDataModelScriptDebugBreakpointEnumerator}
#Import export ".\IDataModelScriptDebugClient.ahk" {IDataModelScriptDebugClient}
#Import export ".\IDataModelScriptDebugStack.ahk" {IDataModelScriptDebugStack}
#Import export ".\IDataModelScriptDebugStackFrame.ahk" {IDataModelScriptDebugStackFrame}
#Import export ".\IDataModelScriptDebugVariableSetEnumerator.ahk" {IDataModelScriptDebugVariableSetEnumerator}
#Import export ".\IDataModelScriptHostContext.ahk" {IDataModelScriptHostContext}
#Import export ".\IDataModelScriptManager.ahk" {IDataModelScriptManager}
#Import export ".\IDataModelScriptProvider.ahk" {IDataModelScriptProvider}
#Import export ".\IDataModelScriptProviderEnumerator.ahk" {IDataModelScriptProviderEnumerator}
#Import export ".\IDataModelScriptTemplate.ahk" {IDataModelScriptTemplate}
#Import export ".\IDataModelScriptTemplateEnumerator.ahk" {IDataModelScriptTemplateEnumerator}
#Import export ".\IDebugAdvanced.ahk" {IDebugAdvanced}
#Import export ".\IDebugAdvanced2.ahk" {IDebugAdvanced2}
#Import export ".\IDebugAdvanced3.ahk" {IDebugAdvanced3}
#Import export ".\IDebugAdvanced4.ahk" {IDebugAdvanced4}
#Import export ".\IDebugBreakpoint.ahk" {IDebugBreakpoint}
#Import export ".\IDebugBreakpoint2.ahk" {IDebugBreakpoint2}
#Import export ".\IDebugBreakpoint3.ahk" {IDebugBreakpoint3}
#Import export ".\IDebugClient.ahk" {IDebugClient}
#Import export ".\IDebugClient2.ahk" {IDebugClient2}
#Import export ".\IDebugClient3.ahk" {IDebugClient3}
#Import export ".\IDebugClient4.ahk" {IDebugClient4}
#Import export ".\IDebugClient5.ahk" {IDebugClient5}
#Import export ".\IDebugClient6.ahk" {IDebugClient6}
#Import export ".\IDebugClient7.ahk" {IDebugClient7}
#Import export ".\IDebugClient8.ahk" {IDebugClient8}
#Import export ".\IDebugClient9.ahk" {IDebugClient9}
#Import export ".\IDebugControl.ahk" {IDebugControl}
#Import export ".\IDebugControl2.ahk" {IDebugControl2}
#Import export ".\IDebugControl3.ahk" {IDebugControl3}
#Import export ".\IDebugControl4.ahk" {IDebugControl4}
#Import export ".\IDebugControl5.ahk" {IDebugControl5}
#Import export ".\IDebugControl6.ahk" {IDebugControl6}
#Import export ".\IDebugControl7.ahk" {IDebugControl7}
#Import export ".\IDebugDataSpaces.ahk" {IDebugDataSpaces}
#Import export ".\IDebugDataSpaces2.ahk" {IDebugDataSpaces2}
#Import export ".\IDebugDataSpaces3.ahk" {IDebugDataSpaces3}
#Import export ".\IDebugDataSpaces4.ahk" {IDebugDataSpaces4}
#Import export ".\IDebugEventCallbacks.ahk" {IDebugEventCallbacks}
#Import export ".\IDebugEventCallbacksWide.ahk" {IDebugEventCallbacksWide}
#Import export ".\IDebugEventContextCallbacks.ahk" {IDebugEventContextCallbacks}
#Import export ".\IDebugFAEntryTags.ahk" {IDebugFAEntryTags}
#Import export ".\IDebugFailureAnalysis.ahk" {IDebugFailureAnalysis}
#Import export ".\IDebugFailureAnalysis2.ahk" {IDebugFailureAnalysis2}
#Import export ".\IDebugFailureAnalysis3.ahk" {IDebugFailureAnalysis3}
#Import export ".\IDebugHost.ahk" {IDebugHost}
#Import export ".\IDebugHostBaseClass.ahk" {IDebugHostBaseClass}
#Import export ".\IDebugHostBaseClass2.ahk" {IDebugHostBaseClass2}
#Import export ".\IDebugHostConstant.ahk" {IDebugHostConstant}
#Import export ".\IDebugHostContext.ahk" {IDebugHostContext}
#Import export ".\IDebugHostContext2.ahk" {IDebugHostContext2}
#Import export ".\IDebugHostContextAlternator.ahk" {IDebugHostContextAlternator}
#Import export ".\IDebugHostContextControl.ahk" {IDebugHostContextControl}
#Import export ".\IDebugHostContextExtensibility.ahk" {IDebugHostContextExtensibility}
#Import export ".\IDebugHostContextExtension.ahk" {IDebugHostContextExtension}
#Import export ".\IDebugHostContextTargetComposition.ahk" {IDebugHostContextTargetComposition}
#Import export ".\IDebugHostData.ahk" {IDebugHostData}
#Import export ".\IDebugHostErrorSink.ahk" {IDebugHostErrorSink}
#Import export ".\IDebugHostEvaluator.ahk" {IDebugHostEvaluator}
#Import export ".\IDebugHostEvaluator2.ahk" {IDebugHostEvaluator2}
#Import export ".\IDebugHostEvaluator3.ahk" {IDebugHostEvaluator3}
#Import export ".\IDebugHostExtensibility.ahk" {IDebugHostExtensibility}
#Import export ".\IDebugHostExtensibility2.ahk" {IDebugHostExtensibility2}
#Import export ".\IDebugHostExtensibility3.ahk" {IDebugHostExtensibility3}
#Import export ".\IDebugHostField.ahk" {IDebugHostField}
#Import export ".\IDebugHostField2.ahk" {IDebugHostField2}
#Import export ".\IDebugHostFunctionIntrospection.ahk" {IDebugHostFunctionIntrospection}
#Import export ".\IDebugHostFunctionIntrospection2.ahk" {IDebugHostFunctionIntrospection2}
#Import export ".\IDebugHostFunctionIntrospection3.ahk" {IDebugHostFunctionIntrospection3}
#Import export ".\IDebugHostFunctionLocalDetails.ahk" {IDebugHostFunctionLocalDetails}
#Import export ".\IDebugHostFunctionLocalDetails2.ahk" {IDebugHostFunctionLocalDetails2}
#Import export ".\IDebugHostFunctionLocalDetailsEnumerator.ahk" {IDebugHostFunctionLocalDetailsEnumerator}
#Import export ".\IDebugHostFunctionLocalStorage.ahk" {IDebugHostFunctionLocalStorage}
#Import export ".\IDebugHostFunctionLocalStorage2.ahk" {IDebugHostFunctionLocalStorage2}
#Import export ".\IDebugHostFunctionLocalStorageEnumerator.ahk" {IDebugHostFunctionLocalStorageEnumerator}
#Import export ".\IDebugHostMemory.ahk" {IDebugHostMemory}
#Import export ".\IDebugHostMemory2.ahk" {IDebugHostMemory2}
#Import export ".\IDebugHostMemory3.ahk" {IDebugHostMemory3}
#Import export ".\IDebugHostMemory4.ahk" {IDebugHostMemory4}
#Import export ".\IDebugHostMemory5.ahk" {IDebugHostMemory5}
#Import export ".\IDebugHostModule.ahk" {IDebugHostModule}
#Import export ".\IDebugHostModule2.ahk" {IDebugHostModule2}
#Import export ".\IDebugHostModule3.ahk" {IDebugHostModule3}
#Import export ".\IDebugHostModule4.ahk" {IDebugHostModule4}
#Import export ".\IDebugHostModule5.ahk" {IDebugHostModule5}
#Import export ".\IDebugHostModuleSignature.ahk" {IDebugHostModuleSignature}
#Import export ".\IDebugHostPublic.ahk" {IDebugHostPublic}
#Import export ".\IDebugHostScriptHost.ahk" {IDebugHostScriptHost}
#Import export ".\IDebugHostStatus.ahk" {IDebugHostStatus}
#Import export ".\IDebugHostStatus2.ahk" {IDebugHostStatus2}
#Import export ".\IDebugHostSymbol.ahk" {IDebugHostSymbol}
#Import export ".\IDebugHostSymbol2.ahk" {IDebugHostSymbol2}
#Import export ".\IDebugHostSymbol3.ahk" {IDebugHostSymbol3}
#Import export ".\IDebugHostSymbolEnumerator.ahk" {IDebugHostSymbolEnumerator}
#Import export ".\IDebugHostSymbolSubstitutionEnumerator.ahk" {IDebugHostSymbolSubstitutionEnumerator}
#Import export ".\IDebugHostSymbols.ahk" {IDebugHostSymbols}
#Import export ".\IDebugHostSymbols2.ahk" {IDebugHostSymbols2}
#Import export ".\IDebugHostSymbolsTargetComposition.ahk" {IDebugHostSymbolsTargetComposition}
#Import export ".\IDebugHostTaggedUnionRangeEnumerator.ahk" {IDebugHostTaggedUnionRangeEnumerator}
#Import export ".\IDebugHostType.ahk" {IDebugHostType}
#Import export ".\IDebugHostType2.ahk" {IDebugHostType2}
#Import export ".\IDebugHostType3.ahk" {IDebugHostType3}
#Import export ".\IDebugHostType4.ahk" {IDebugHostType4}
#Import export ".\IDebugHostType5.ahk" {IDebugHostType5}
#Import export ".\IDebugHostType6.ahk" {IDebugHostType6}
#Import export ".\IDebugHostTypeSignature.ahk" {IDebugHostTypeSignature}
#Import export ".\IDebugInputCallbacks.ahk" {IDebugInputCallbacks}
#Import export ".\IDebugOutputCallbacks.ahk" {IDebugOutputCallbacks}
#Import export ".\IDebugOutputCallbacks2.ahk" {IDebugOutputCallbacks2}
#Import export ".\IDebugOutputCallbacksWide.ahk" {IDebugOutputCallbacksWide}
#Import export ".\IDebugOutputStream.ahk" {IDebugOutputStream}
#Import export ".\IDebugPlmClient.ahk" {IDebugPlmClient}
#Import export ".\IDebugPlmClient2.ahk" {IDebugPlmClient2}
#Import export ".\IDebugPlmClient3.ahk" {IDebugPlmClient3}
#Import export ".\IDebugRegisters.ahk" {IDebugRegisters}
#Import export ".\IDebugRegisters2.ahk" {IDebugRegisters2}
#Import export ".\IDebugServiceManager.ahk" {IDebugServiceManager}
#Import export ".\IDebugSymbolGroup.ahk" {IDebugSymbolGroup}
#Import export ".\IDebugSymbolGroup2.ahk" {IDebugSymbolGroup2}
#Import export ".\IDebugSymbols.ahk" {IDebugSymbols}
#Import export ".\IDebugSymbols2.ahk" {IDebugSymbols2}
#Import export ".\IDebugSymbols3.ahk" {IDebugSymbols3}
#Import export ".\IDebugSymbols4.ahk" {IDebugSymbols4}
#Import export ".\IDebugSymbols5.ahk" {IDebugSymbols5}
#Import export ".\IDebugSystemObjects.ahk" {IDebugSystemObjects}
#Import export ".\IDebugSystemObjects2.ahk" {IDebugSystemObjects2}
#Import export ".\IDebugSystemObjects3.ahk" {IDebugSystemObjects3}
#Import export ".\IDebugSystemObjects4.ahk" {IDebugSystemObjects4}
#Import export ".\IDeconstructableConcept.ahk" {IDeconstructableConcept}
#Import export ".\IDynamicConceptProviderConcept.ahk" {IDynamicConceptProviderConcept}
#Import export ".\IDynamicKeyProviderConcept.ahk" {IDynamicKeyProviderConcept}
#Import export ".\IEquatableConcept.ahk" {IEquatableConcept}
#Import export ".\IFilteredNamespacePropertyToken.ahk" {IFilteredNamespacePropertyToken}
#Import export ".\IHostDataModelAccess.ahk" {IHostDataModelAccess}
#Import export ".\IIndexableConcept.ahk" {IIndexableConcept}
#Import export ".\IIterableConcept.ahk" {IIterableConcept}
#Import export ".\IKeyEnumerator.ahk" {IKeyEnumerator}
#Import export ".\IKeyStore.ahk" {IKeyStore}
#Import export ".\IModelIterator.ahk" {IModelIterator}
#Import export ".\IModelKeyReference.ahk" {IModelKeyReference}
#Import export ".\IModelKeyReference2.ahk" {IModelKeyReference2}
#Import export ".\IModelMethod.ahk" {IModelMethod}
#Import export ".\IModelObject.ahk" {IModelObject}
#Import export ".\IModelObject2.ahk" {IModelObject2}
#Import export ".\IModelPropertyAccessor.ahk" {IModelPropertyAccessor}
#Import export ".\INLINE_FRAME_CONTEXT.ahk" {INLINE_FRAME_CONTEXT}
#Import export ".\INamedModelsEnumerator.ahk" {INamedModelsEnumerator}
#Import export ".\IOSPACE.ahk" {IOSPACE}
#Import export ".\IOSPACE32.ahk" {IOSPACE32}
#Import export ".\IOSPACE64.ahk" {IOSPACE64}
#Import export ".\IOSPACE_EX.ahk" {IOSPACE_EX}
#Import export ".\IOSPACE_EX32.ahk" {IOSPACE_EX32}
#Import export ".\IOSPACE_EX64.ahk" {IOSPACE_EX64}
#Import export ".\IObjectWrapperConcept.ahk" {IObjectWrapperConcept}
#Import export ".\IPreferredRuntimeTypeConcept.ahk" {IPreferredRuntimeTypeConcept}
#Import export ".\IRawEnumerator.ahk" {IRawEnumerator}
#Import export ".\IStringDisplayableConcept.ahk" {IStringDisplayableConcept}
#Import export ".\ISvcExecutionUnit.ahk" {ISvcExecutionUnit}
#Import export ".\ISvcModule.ahk" {ISvcModule}
#Import export ".\ISvcProcess.ahk" {ISvcProcess}
#Import export ".\ISvcSymbolType.ahk" {ISvcSymbolType}
#Import export ".\ISvcThread.ahk" {ISvcThread}
#Import export ".\IntrinsicKind.ahk" {IntrinsicKind}
#Import export ".\KDDEBUGGER_DATA32.ahk" {KDDEBUGGER_DATA32}
#Import export ".\KDDEBUGGER_DATA64.ahk" {KDDEBUGGER_DATA64}
#Import export ".\KDEXTS_LOCK_CALLBACKROUTINE.ahk" {KDEXTS_LOCK_CALLBACKROUTINE}
#Import export ".\KDEXTS_LOCK_INFO.ahk" {KDEXTS_LOCK_INFO}
#Import export ".\KDEXTS_PTE_INFO.ahk" {KDEXTS_PTE_INFO}
#Import export ".\KDEXT_DUMP_HANDLE_CALLBACK.ahk" {KDEXT_DUMP_HANDLE_CALLBACK}
#Import export ".\KDEXT_FILELOCK_OWNER.ahk" {KDEXT_FILELOCK_OWNER}
#Import export ".\KDEXT_HANDLE_INFORMATION.ahk" {KDEXT_HANDLE_INFORMATION}
#Import export ".\KDEXT_PROCESS_FIND_PARAMS.ahk" {KDEXT_PROCESS_FIND_PARAMS}
#Import export ".\KDEXT_THREAD_FIND_PARAMS.ahk" {KDEXT_THREAD_FIND_PARAMS}
#Import export ".\KnownCompiler.ahk" {KnownCompiler}
#Import export ".\LanguageKind.ahk" {LanguageKind}
#Import export ".\LocalKind.ahk" {LocalKind}
#Import export ".\Location.ahk" {Location}
#Import export ".\LocationKind.ahk" {LocationKind}
#Import export ".\ModelObjectKind.ahk" {ModelObjectKind}
#Import export ".\OS_INFO.ahk" {OS_INFO}
#Import export ".\OS_INFO_v1.ahk" {OS_INFO_v1}
#Import export ".\OS_TYPE.ahk" {OS_TYPE}
#Import export ".\PDEBUG_EXTENSION_CALL.ahk" {PDEBUG_EXTENSION_CALL}
#Import export ".\PDEBUG_EXTENSION_CANUNLOAD.ahk" {PDEBUG_EXTENSION_CANUNLOAD}
#Import export ".\PDEBUG_EXTENSION_INITIALIZE.ahk" {PDEBUG_EXTENSION_INITIALIZE}
#Import export ".\PDEBUG_EXTENSION_KNOWN_STRUCT.ahk" {PDEBUG_EXTENSION_KNOWN_STRUCT}
#Import export ".\PDEBUG_EXTENSION_KNOWN_STRUCT_EX.ahk" {PDEBUG_EXTENSION_KNOWN_STRUCT_EX}
#Import export ".\PDEBUG_EXTENSION_NOTIFY.ahk" {PDEBUG_EXTENSION_NOTIFY}
#Import export ".\PDEBUG_EXTENSION_PROVIDE_VALUE.ahk" {PDEBUG_EXTENSION_PROVIDE_VALUE}
#Import export ".\PDEBUG_EXTENSION_QUERY_VALUE_NAMES.ahk" {PDEBUG_EXTENSION_QUERY_VALUE_NAMES}
#Import export ".\PDEBUG_EXTENSION_UNINITIALIZE.ahk" {PDEBUG_EXTENSION_UNINITIALIZE}
#Import export ".\PDEBUG_EXTENSION_UNLOAD.ahk" {PDEBUG_EXTENSION_UNLOAD}
#Import export ".\PDEBUG_STACK_PROVIDER_BEGINTHREADSTACKRECONSTRUCTION.ahk" {PDEBUG_STACK_PROVIDER_BEGINTHREADSTACKRECONSTRUCTION}
#Import export ".\PDEBUG_STACK_PROVIDER_ENDTHREADSTACKRECONSTRUCTION.ahk" {PDEBUG_STACK_PROVIDER_ENDTHREADSTACKRECONSTRUCTION}
#Import export ".\PDEBUG_STACK_PROVIDER_FREESTACKSYMFRAMES.ahk" {PDEBUG_STACK_PROVIDER_FREESTACKSYMFRAMES}
#Import export ".\PDEBUG_STACK_PROVIDER_RECONSTRUCTSTACK.ahk" {PDEBUG_STACK_PROVIDER_RECONSTRUCTSTACK}
#Import export ".\PENUMERATE_HANDLES.ahk" {PENUMERATE_HANDLES}
#Import export ".\PENUMERATE_HASH_TABLE.ahk" {PENUMERATE_HASH_TABLE}
#Import export ".\PENUMERATE_JOB_PROCESSES.ahk" {PENUMERATE_JOB_PROCESSES}
#Import export ".\PENUMERATE_SYSTEM_LOCKS.ahk" {PENUMERATE_SYSTEM_LOCKS}
#Import export ".\PFIND_FILELOCK_OWNERINFO.ahk" {PFIND_FILELOCK_OWNERINFO}
#Import export ".\PFIND_MATCHING_PROCESS.ahk" {PFIND_MATCHING_PROCESS}
#Import export ".\PFIND_MATCHING_THREAD.ahk" {PFIND_MATCHING_THREAD}
#Import export ".\PGET_CPU_MICROCODE_VERSION.ahk" {PGET_CPU_MICROCODE_VERSION}
#Import export ".\PGET_CPU_PSPEED_INFO.ahk" {PGET_CPU_PSPEED_INFO}
#Import export ".\PGET_DEVICE_OBJECT_INFO.ahk" {PGET_DEVICE_OBJECT_INFO}
#Import export ".\PGET_DRIVER_OBJECT_INFO.ahk" {PGET_DRIVER_OBJECT_INFO}
#Import export ".\PGET_FULL_IMAGE_NAME.ahk" {PGET_FULL_IMAGE_NAME}
#Import export ".\PGET_IRP_INFO.ahk" {PGET_IRP_INFO}
#Import export ".\PGET_PNP_TRIAGE_INFO.ahk" {PGET_PNP_TRIAGE_INFO}
#Import export ".\PGET_POOL_DATA.ahk" {PGET_POOL_DATA}
#Import export ".\PGET_POOL_REGION.ahk" {PGET_POOL_REGION}
#Import export ".\PGET_POOL_TAG_DESCRIPTION.ahk" {PGET_POOL_TAG_DESCRIPTION}
#Import export ".\PGET_PROCESS_COMMIT.ahk" {PGET_PROCESS_COMMIT}
#Import export ".\PGET_SMBIOS_INFO.ahk" {PGET_SMBIOS_INFO}
#Import export ".\PHYSICAL.ahk" {PHYSICAL}
#Import export ".\PHYSICAL_TO_VIRTUAL.ahk" {PHYSICAL_TO_VIRTUAL}
#Import export ".\PHYSICAL_WITH_FLAGS.ahk" {PHYSICAL_WITH_FLAGS}
#Import export ".\PKDEXTS_GET_PTE_INFO.ahk" {PKDEXTS_GET_PTE_INFO}
#Import export ".\POINTER_SEARCH_PHYSICAL.ahk" {POINTER_SEARCH_PHYSICAL}
#Import export ".\POOL_HEADER_FIELD_NAME.ahk" {POOL_HEADER_FIELD_NAME}
#Import export ".\POOL_HEADER_SIZE_64.ahk" {POOL_HEADER_SIZE_64}
#Import export ".\PROCESSORINFO.ahk" {PROCESSORINFO}
#Import export ".\PROCESS_COMMIT_USAGE.ahk" {PROCESS_COMMIT_USAGE}
#Import export ".\PROCESS_NAME_ENTRY.ahk" {PROCESS_NAME_ENTRY}
#Import export ".\PSYM_DUMP_FIELD_CALLBACK.ahk" {PSYM_DUMP_FIELD_CALLBACK}
#Import export ".\PWINDBG_CHECK_CONTROL_C.ahk" {PWINDBG_CHECK_CONTROL_C}
#Import export ".\PWINDBG_CHECK_VERSION.ahk" {PWINDBG_CHECK_VERSION}
#Import export ".\PWINDBG_DISASM.ahk" {PWINDBG_DISASM}
#Import export ".\PWINDBG_DISASM32.ahk" {PWINDBG_DISASM32}
#Import export ".\PWINDBG_DISASM64.ahk" {PWINDBG_DISASM64}
#Import export ".\PWINDBG_EXTENSION_API_VERSION.ahk" {PWINDBG_EXTENSION_API_VERSION}
#Import export ".\PWINDBG_EXTENSION_DLL_INIT.ahk" {PWINDBG_EXTENSION_DLL_INIT}
#Import export ".\PWINDBG_EXTENSION_DLL_INIT32.ahk" {PWINDBG_EXTENSION_DLL_INIT32}
#Import export ".\PWINDBG_EXTENSION_DLL_INIT64.ahk" {PWINDBG_EXTENSION_DLL_INIT64}
#Import export ".\PWINDBG_EXTENSION_ROUTINE.ahk" {PWINDBG_EXTENSION_ROUTINE}
#Import export ".\PWINDBG_EXTENSION_ROUTINE32.ahk" {PWINDBG_EXTENSION_ROUTINE32}
#Import export ".\PWINDBG_EXTENSION_ROUTINE64.ahk" {PWINDBG_EXTENSION_ROUTINE64}
#Import export ".\PWINDBG_GET_EXPRESSION.ahk" {PWINDBG_GET_EXPRESSION}
#Import export ".\PWINDBG_GET_EXPRESSION32.ahk" {PWINDBG_GET_EXPRESSION32}
#Import export ".\PWINDBG_GET_EXPRESSION64.ahk" {PWINDBG_GET_EXPRESSION64}
#Import export ".\PWINDBG_GET_SYMBOL.ahk" {PWINDBG_GET_SYMBOL}
#Import export ".\PWINDBG_GET_SYMBOL32.ahk" {PWINDBG_GET_SYMBOL32}
#Import export ".\PWINDBG_GET_SYMBOL64.ahk" {PWINDBG_GET_SYMBOL64}
#Import export ".\PWINDBG_GET_THREAD_CONTEXT_ROUTINE.ahk" {PWINDBG_GET_THREAD_CONTEXT_ROUTINE}
#Import export ".\PWINDBG_IOCTL_ROUTINE.ahk" {PWINDBG_IOCTL_ROUTINE}
#Import export ".\PWINDBG_OLDKD_EXTENSION_ROUTINE.ahk" {PWINDBG_OLDKD_EXTENSION_ROUTINE}
#Import export ".\PWINDBG_OLDKD_READ_PHYSICAL_MEMORY.ahk" {PWINDBG_OLDKD_READ_PHYSICAL_MEMORY}
#Import export ".\PWINDBG_OLDKD_WRITE_PHYSICAL_MEMORY.ahk" {PWINDBG_OLDKD_WRITE_PHYSICAL_MEMORY}
#Import export ".\PWINDBG_OLD_EXTENSION_ROUTINE.ahk" {PWINDBG_OLD_EXTENSION_ROUTINE}
#Import export ".\PWINDBG_OUTPUT_ROUTINE.ahk" {PWINDBG_OUTPUT_ROUTINE}
#Import export ".\PWINDBG_READ_PROCESS_MEMORY_ROUTINE.ahk" {PWINDBG_READ_PROCESS_MEMORY_ROUTINE}
#Import export ".\PWINDBG_READ_PROCESS_MEMORY_ROUTINE32.ahk" {PWINDBG_READ_PROCESS_MEMORY_ROUTINE32}
#Import export ".\PWINDBG_READ_PROCESS_MEMORY_ROUTINE64.ahk" {PWINDBG_READ_PROCESS_MEMORY_ROUTINE64}
#Import export ".\PWINDBG_SET_THREAD_CONTEXT_ROUTINE.ahk" {PWINDBG_SET_THREAD_CONTEXT_ROUTINE}
#Import export ".\PWINDBG_STACKTRACE_ROUTINE.ahk" {PWINDBG_STACKTRACE_ROUTINE}
#Import export ".\PWINDBG_STACKTRACE_ROUTINE32.ahk" {PWINDBG_STACKTRACE_ROUTINE32}
#Import export ".\PWINDBG_STACKTRACE_ROUTINE64.ahk" {PWINDBG_STACKTRACE_ROUTINE64}
#Import export ".\PWINDBG_WRITE_PROCESS_MEMORY_ROUTINE.ahk" {PWINDBG_WRITE_PROCESS_MEMORY_ROUTINE}
#Import export ".\PWINDBG_WRITE_PROCESS_MEMORY_ROUTINE32.ahk" {PWINDBG_WRITE_PROCESS_MEMORY_ROUTINE32}
#Import export ".\PWINDBG_WRITE_PROCESS_MEMORY_ROUTINE64.ahk" {PWINDBG_WRITE_PROCESS_MEMORY_ROUTINE64}
#Import export ".\PointerKind.ahk" {PointerKind}
#Import export ".\PreferredFormat.ahk" {PreferredFormat}
#Import export ".\READCONTROLSPACE.ahk" {READCONTROLSPACE}
#Import export ".\READCONTROLSPACE32.ahk" {READCONTROLSPACE32}
#Import export ".\READCONTROLSPACE64.ahk" {READCONTROLSPACE64}
#Import export ".\READ_WRITE_MSR.ahk" {READ_WRITE_MSR}
#Import export ".\RawSearchFlags.ahk" {RawSearchFlags}
#Import export ".\SEARCHMEMORY.ahk" {SEARCHMEMORY}
#Import export ".\STACK_SRC_INFO.ahk" {STACK_SRC_INFO}
#Import export ".\STACK_SYM_FRAME_INFO.ahk" {STACK_SYM_FRAME_INFO}
#Import export ".\SYMBOL_INFO_EX.ahk" {SYMBOL_INFO_EX}
#Import export ".\SYM_DUMP_PARAM.ahk" {SYM_DUMP_PARAM}
#Import export ".\ScriptChangeKind.ahk" {ScriptChangeKind}
#Import export ".\ScriptDebugEvent.ahk" {ScriptDebugEvent}
#Import export ".\ScriptDebugEventFilter.ahk" {ScriptDebugEventFilter}
#Import export ".\ScriptDebugEventInformation.ahk" {ScriptDebugEventInformation}
#Import export ".\ScriptDebugPosition.ahk" {ScriptDebugPosition}
#Import export ".\ScriptDebugState.ahk" {ScriptDebugState}
#Import export ".\ScriptExecutionKind.ahk" {ScriptExecutionKind}
#Import export ".\SignatureComparison.ahk" {SignatureComparison}
#Import export ".\StorageKind.ahk" {StorageKind}
#Import export ".\SymbolKind.ahk" {SymbolKind}
#Import export ".\SymbolSearchOptions.ahk" {SymbolSearchOptions}
#Import export ".\TANALYZE_RETURN.ahk" {TANALYZE_RETURN}
#Import export ".\TARGET_DEBUG_INFO.ahk" {TARGET_DEBUG_INFO}
#Import export ".\TARGET_DEBUG_INFO_v1.ahk" {TARGET_DEBUG_INFO_v1}
#Import export ".\TARGET_DEBUG_INFO_v2.ahk" {TARGET_DEBUG_INFO_v2}
#Import export ".\TRANSLATE_VIRTUAL_TO_PHYSICAL.ahk" {TRANSLATE_VIRTUAL_TO_PHYSICAL}
#Import export ".\TypeKind.ahk" {TypeKind}
#Import export ".\UDTKind.ahk" {UDTKind}
#Import export ".\VIRTUAL_TO_PHYSICAL.ahk" {VIRTUAL_TO_PHYSICAL}
#Import export ".\VarArgsKind.ahk" {VarArgsKind}
#Import export ".\WDBGEXTS_CLR_DATA_INTERFACE.ahk" {WDBGEXTS_CLR_DATA_INTERFACE}
#Import export ".\WDBGEXTS_DISASSEMBLE_BUFFER.ahk" {WDBGEXTS_DISASSEMBLE_BUFFER}
#Import export ".\WDBGEXTS_MODULE_IN_RANGE.ahk" {WDBGEXTS_MODULE_IN_RANGE}
#Import export ".\WDBGEXTS_QUERY_INTERFACE.ahk" {WDBGEXTS_QUERY_INTERFACE}
#Import export ".\WDBGEXTS_THREAD_OS_INFO.ahk" {WDBGEXTS_THREAD_OS_INFO}
#Import export ".\WINDBG_EXTENSION_APIS.ahk" {WINDBG_EXTENSION_APIS}
#Import export ".\WINDBG_EXTENSION_APIS32.ahk" {WINDBG_EXTENSION_APIS32}
#Import export ".\WINDBG_EXTENSION_APIS64.ahk" {WINDBG_EXTENSION_APIS64}
#Import export ".\WINDBG_OLDKD_EXTENSION_APIS.ahk" {WINDBG_OLDKD_EXTENSION_APIS}
#Import export ".\WINDBG_OLD_EXTENSION_APIS.ahk" {WINDBG_OLD_EXTENSION_APIS}
#Import export ".\WrappedObjectPreference.ahk" {WrappedObjectPreference}
#Import export ".\XML_DRIVER_NODE_INFO.ahk" {XML_DRIVER_NODE_INFO}
#Import export ".\fnDebugFailureAnalysisCreateInstance.ahk" {fnDebugFailureAnalysisCreateInstance}
