#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_ALL.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_ALL }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_X86.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_X86 }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_ARM64.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_ARM64 }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_IA64.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_IA64 }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_ARM.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_ARM }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_AMD64.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_AMD64 }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_ALPHA.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_ALPHA }
#Import "..\..\..\..\Foundation\CHAR.ahk" { CHAR }

/**
 * @namespace Windows.Win32.System.Diagnostics.Debug.Extensions
 */
export default struct CPU_INFO_v2 {
    #StructPack 4

    Type : UInt32

    NumCPUs : UInt32

    CurrentProc : UInt32

    ProcInfo : DEBUG_PROCESSOR_IDENTIFICATION_ALL[1280]

    Mhz : UInt32

}
