#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_ALL.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_ALL }
#Import ".\OS_INFO.ahk" { OS_INFO }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_X86.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_X86 }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_ARM64.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_ARM64 }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_IA64.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_IA64 }
#Import ".\CPU_INFO_v2.ahk" { CPU_INFO_v2 }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_ARM.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_ARM }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_AMD64.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_AMD64 }
#Import ".\DEBUG_PROCESSOR_IDENTIFICATION_ALPHA.ahk" { DEBUG_PROCESSOR_IDENTIFICATION_ALPHA }
#Import "..\..\..\..\Foundation\CHAR.ahk" { CHAR }

/**
 * @namespace Windows.Win32.System.Diagnostics.Debug.Extensions
 */
export default struct TARGET_DEBUG_INFO_v2 {
    #StructPack 8

    SizeOfStruct : UInt32

    EntryDate : Int64

    DebugeeClass : UInt32

    SysUpTime : Int64

    AppUpTime : Int64

    CrashTime : Int64

    OsInfo : OS_INFO

    Cpu : CPU_INFO_v2

    DumpFile : CHAR[260]

}
