#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PWINDBG_CHECK_CONTROL_C.ahk" { PWINDBG_CHECK_CONTROL_C }
#Import ".\PWINDBG_GET_SYMBOL32.ahk" { PWINDBG_GET_SYMBOL32 }
#Import ".\PWINDBG_OUTPUT_ROUTINE.ahk" { PWINDBG_OUTPUT_ROUTINE }
#Import ".\PWINDBG_WRITE_PROCESS_MEMORY_ROUTINE32.ahk" { PWINDBG_WRITE_PROCESS_MEMORY_ROUTINE32 }
#Import ".\PWINDBG_GET_EXPRESSION32.ahk" { PWINDBG_GET_EXPRESSION32 }
#Import ".\PWINDBG_OLDKD_WRITE_PHYSICAL_MEMORY.ahk" { PWINDBG_OLDKD_WRITE_PHYSICAL_MEMORY }
#Import ".\PWINDBG_OLDKD_READ_PHYSICAL_MEMORY.ahk" { PWINDBG_OLDKD_READ_PHYSICAL_MEMORY }
#Import ".\PWINDBG_DISASM32.ahk" { PWINDBG_DISASM32 }
#Import ".\PWINDBG_READ_PROCESS_MEMORY_ROUTINE32.ahk" { PWINDBG_READ_PROCESS_MEMORY_ROUTINE32 }

/**
 * @namespace Windows.Win32.System.Diagnostics.Debug.Extensions
 */
export default struct WINDBG_OLDKD_EXTENSION_APIS {
    #StructPack 8

    nSize : UInt32

    lpOutputRoutine : PWINDBG_OUTPUT_ROUTINE

    lpGetExpressionRoutine : PWINDBG_GET_EXPRESSION32

    lpGetSymbolRoutine : PWINDBG_GET_SYMBOL32

    lpDisasmRoutine : PWINDBG_DISASM32

    lpCheckControlCRoutine : PWINDBG_CHECK_CONTROL_C

    lpReadVirtualMemRoutine : PWINDBG_READ_PROCESS_MEMORY_ROUTINE32

    lpWriteVirtualMemRoutine : PWINDBG_WRITE_PROCESS_MEMORY_ROUTINE32

    lpReadPhysicalMemRoutine : PWINDBG_OLDKD_READ_PHYSICAL_MEMORY

    lpWritePhysicalMemRoutine : PWINDBG_OLDKD_WRITE_PHYSICAL_MEMORY

}
