#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\FOREIGN_STATUS.ahk" {FOREIGN_STATUS}
#Import export ".\IMSMQApplication.ahk" {IMSMQApplication}
#Import export ".\IMSMQApplication2.ahk" {IMSMQApplication2}
#Import export ".\IMSMQApplication3.ahk" {IMSMQApplication3}
#Import export ".\IMSMQCollection.ahk" {IMSMQCollection}
#Import export ".\IMSMQCoordinatedTransactionDispenser.ahk" {IMSMQCoordinatedTransactionDispenser}
#Import export ".\IMSMQCoordinatedTransactionDispenser2.ahk" {IMSMQCoordinatedTransactionDispenser2}
#Import export ".\IMSMQCoordinatedTransactionDispenser3.ahk" {IMSMQCoordinatedTransactionDispenser3}
#Import export ".\IMSMQDestination.ahk" {IMSMQDestination}
#Import export ".\IMSMQEvent.ahk" {IMSMQEvent}
#Import export ".\IMSMQEvent2.ahk" {IMSMQEvent2}
#Import export ".\IMSMQEvent3.ahk" {IMSMQEvent3}
#Import export ".\IMSMQManagement.ahk" {IMSMQManagement}
#Import export ".\IMSMQMessage.ahk" {IMSMQMessage}
#Import export ".\IMSMQMessage2.ahk" {IMSMQMessage2}
#Import export ".\IMSMQMessage3.ahk" {IMSMQMessage3}
#Import export ".\IMSMQMessage4.ahk" {IMSMQMessage4}
#Import export ".\IMSMQOutgoingQueueManagement.ahk" {IMSMQOutgoingQueueManagement}
#Import export ".\IMSMQPrivateDestination.ahk" {IMSMQPrivateDestination}
#Import export ".\IMSMQPrivateEvent.ahk" {IMSMQPrivateEvent}
#Import export ".\IMSMQQuery.ahk" {IMSMQQuery}
#Import export ".\IMSMQQuery2.ahk" {IMSMQQuery2}
#Import export ".\IMSMQQuery3.ahk" {IMSMQQuery3}
#Import export ".\IMSMQQuery4.ahk" {IMSMQQuery4}
#Import export ".\IMSMQQueue.ahk" {IMSMQQueue}
#Import export ".\IMSMQQueue2.ahk" {IMSMQQueue2}
#Import export ".\IMSMQQueue3.ahk" {IMSMQQueue3}
#Import export ".\IMSMQQueue4.ahk" {IMSMQQueue4}
#Import export ".\IMSMQQueueInfo.ahk" {IMSMQQueueInfo}
#Import export ".\IMSMQQueueInfo2.ahk" {IMSMQQueueInfo2}
#Import export ".\IMSMQQueueInfo3.ahk" {IMSMQQueueInfo3}
#Import export ".\IMSMQQueueInfo4.ahk" {IMSMQQueueInfo4}
#Import export ".\IMSMQQueueInfos.ahk" {IMSMQQueueInfos}
#Import export ".\IMSMQQueueInfos2.ahk" {IMSMQQueueInfos2}
#Import export ".\IMSMQQueueInfos3.ahk" {IMSMQQueueInfos3}
#Import export ".\IMSMQQueueInfos4.ahk" {IMSMQQueueInfos4}
#Import export ".\IMSMQQueueManagement.ahk" {IMSMQQueueManagement}
#Import export ".\IMSMQTransaction.ahk" {IMSMQTransaction}
#Import export ".\IMSMQTransaction2.ahk" {IMSMQTransaction2}
#Import export ".\IMSMQTransaction3.ahk" {IMSMQTransaction3}
#Import export ".\IMSMQTransactionDispenser.ahk" {IMSMQTransactionDispenser}
#Import export ".\IMSMQTransactionDispenser2.ahk" {IMSMQTransactionDispenser2}
#Import export ".\IMSMQTransactionDispenser3.ahk" {IMSMQTransactionDispenser3}
#Import export ".\MQACCESS.ahk" {MQACCESS}
#Import export ".\MQAUTHENTICATE.ahk" {MQAUTHENTICATE}
#Import export ".\MQCALG.ahk" {MQCALG}
#Import export ".\MQCERT_REGISTER.ahk" {MQCERT_REGISTER}
#Import export ".\MQCOLUMNSET.ahk" {MQCOLUMNSET}
#Import export ".\MQConnectionState.ahk" {MQConnectionState}
#Import export ".\MQDEFAULT.ahk" {MQDEFAULT}
#Import export ".\MQERROR.ahk" {MQERROR}
#Import export ".\MQJOURNAL.ahk" {MQJOURNAL}
#Import export ".\MQMAX.ahk" {MQMAX}
#Import export ".\MQMGMTPROPS.ahk" {MQMGMTPROPS}
#Import export ".\MQMSGACKNOWLEDGEMENT.ahk" {MQMSGACKNOWLEDGEMENT}
#Import export ".\MQMSGAUTHENTICATION.ahk" {MQMSGAUTHENTICATION}
#Import export ".\MQMSGAUTHLEVEL.ahk" {MQMSGAUTHLEVEL}
#Import export ".\MQMSGCLASS.ahk" {MQMSGCLASS}
#Import export ".\MQMSGCURSOR.ahk" {MQMSGCURSOR}
#Import export ".\MQMSGDELIVERY.ahk" {MQMSGDELIVERY}
#Import export ".\MQMSGIDSIZE.ahk" {MQMSGIDSIZE}
#Import export ".\MQMSGJOURNAL.ahk" {MQMSGJOURNAL}
#Import export ".\MQMSGMAX.ahk" {MQMSGMAX}
#Import export ".\MQMSGPRIVLEVEL.ahk" {MQMSGPRIVLEVEL}
#Import export ".\MQMSGPROPS.ahk" {MQMSGPROPS}
#Import export ".\MQMSGSENDERIDTYPE.ahk" {MQMSGSENDERIDTYPE}
#Import export ".\MQMSGTRACE.ahk" {MQMSGTRACE}
#Import export ".\MQPRIORITY.ahk" {MQPRIORITY}
#Import export ".\MQPRIVATEPROPS.ahk" {MQPRIVATEPROPS}
#Import export ".\MQPRIVLEVEL.ahk" {MQPRIVLEVEL}
#Import export ".\MQPROPERTYRESTRICTION.ahk" {MQPROPERTYRESTRICTION}
#Import export ".\MQQMPROPS.ahk" {MQQMPROPS}
#Import export ".\MQQUEUEACCESSMASK.ahk" {MQQUEUEACCESSMASK}
#Import export ".\MQQUEUEPROPS.ahk" {MQQUEUEPROPS}
#Import export ".\MQRESTRICTION.ahk" {MQRESTRICTION}
#Import export ".\MQSHARE.ahk" {MQSHARE}
#Import export ".\MQSORTKEY.ahk" {MQSORTKEY}
#Import export ".\MQSORTSET.ahk" {MQSORTSET}
#Import export ".\MQTRANSACTION.ahk" {MQTRANSACTION}
#Import export ".\MQTRANSACTIONAL.ahk" {MQTRANSACTIONAL}
#Import export ".\MQWARNING.ahk" {MQWARNING}
#Import export ".\MSMQApplication.ahk" {MSMQApplication}
#Import export ".\MSMQCollection.ahk" {MSMQCollection}
#Import export ".\MSMQCoordinatedTransactionDispenser.ahk" {MSMQCoordinatedTransactionDispenser}
#Import export ".\MSMQDestination.ahk" {MSMQDestination}
#Import export ".\MSMQEvent.ahk" {MSMQEvent}
#Import export ".\MSMQManagement.ahk" {MSMQManagement}
#Import export ".\MSMQMessage.ahk" {MSMQMessage}
#Import export ".\MSMQOutgoingQueueManagement.ahk" {MSMQOutgoingQueueManagement}
#Import export ".\MSMQQuery.ahk" {MSMQQuery}
#Import export ".\MSMQQueue.ahk" {MSMQQueue}
#Import export ".\MSMQQueueInfo.ahk" {MSMQQueueInfo}
#Import export ".\MSMQQueueInfos.ahk" {MSMQQueueInfos}
#Import export ".\MSMQQueueManagement.ahk" {MSMQQueueManagement}
#Import export ".\MSMQTransaction.ahk" {MSMQTransaction}
#Import export ".\MSMQTransactionDispenser.ahk" {MSMQTransactionDispenser}
#Import export ".\PMQRECEIVECALLBACK.ahk" {PMQRECEIVECALLBACK}
#Import export ".\QUEUE_STATE.ahk" {QUEUE_STATE}
#Import export ".\QUEUE_TYPE.ahk" {QUEUE_TYPE}
#Import export ".\RELOPS.ahk" {RELOPS}
#Import export ".\SEQUENCE_INFO.ahk" {SEQUENCE_INFO}
#Import export ".\XACT_STATUS.ahk" {XACT_STATUS}
#Import export ".\_DMSMQEventEvents.ahk" {_DMSMQEventEvents}
