#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\BlockRange.ahk" {BlockRange}
#Import export ".\BlockRangeList.ahk" {BlockRangeList}
#Import export ".\BootOptions.ahk" {BootOptions}
#Import export ".\Constants.ahk" {*}
#Import export ".\DDiscFormat2DataEvents.ahk" {DDiscFormat2DataEvents}
#Import export ".\DDiscFormat2EraseEvents.ahk" {DDiscFormat2EraseEvents}
#Import export ".\DDiscFormat2RawCDEvents.ahk" {DDiscFormat2RawCDEvents}
#Import export ".\DDiscFormat2TrackAtOnceEvents.ahk" {DDiscFormat2TrackAtOnceEvents}
#Import export ".\DDiscMaster2Events.ahk" {DDiscMaster2Events}
#Import export ".\DFileSystemImageEvents.ahk" {DFileSystemImageEvents}
#Import export ".\DFileSystemImageImportEvents.ahk" {DFileSystemImageImportEvents}
#Import export ".\DISC_RECORDER_STATE_FLAGS.ahk" {DISC_RECORDER_STATE_FLAGS}
#Import export ".\DWriteEngine2Events.ahk" {DWriteEngine2Events}
#Import export ".\EmulationType.ahk" {EmulationType}
#Import export ".\EnumFsiItems.ahk" {EnumFsiItems}
#Import export ".\EnumProgressItems.ahk" {EnumProgressItems}
#Import export ".\FileSystemImageResult.ahk" {FileSystemImageResult}
#Import export ".\FsiDirectoryItem.ahk" {FsiDirectoryItem}
#Import export ".\FsiFileItem.ahk" {FsiFileItem}
#Import export ".\FsiFileSystems.ahk" {FsiFileSystems}
#Import export ".\FsiItemType.ahk" {FsiItemType}
#Import export ".\FsiNamedStreams.ahk" {FsiNamedStreams}
#Import export ".\FsiStream.ahk" {FsiStream}
#Import export ".\IBlockRange.ahk" {IBlockRange}
#Import export ".\IBlockRangeList.ahk" {IBlockRangeList}
#Import export ".\IBootOptions.ahk" {IBootOptions}
#Import export ".\IBurnVerification.ahk" {IBurnVerification}
#Import export ".\IDiscFormat2.ahk" {IDiscFormat2}
#Import export ".\IDiscFormat2Data.ahk" {IDiscFormat2Data}
#Import export ".\IDiscFormat2DataEventArgs.ahk" {IDiscFormat2DataEventArgs}
#Import export ".\IDiscFormat2Erase.ahk" {IDiscFormat2Erase}
#Import export ".\IDiscFormat2RawCD.ahk" {IDiscFormat2RawCD}
#Import export ".\IDiscFormat2RawCDEventArgs.ahk" {IDiscFormat2RawCDEventArgs}
#Import export ".\IDiscFormat2TrackAtOnce.ahk" {IDiscFormat2TrackAtOnce}
#Import export ".\IDiscFormat2TrackAtOnceEventArgs.ahk" {IDiscFormat2TrackAtOnceEventArgs}
#Import export ".\IDiscMaster.ahk" {IDiscMaster}
#Import export ".\IDiscMaster2.ahk" {IDiscMaster2}
#Import export ".\IDiscMasterProgressEvents.ahk" {IDiscMasterProgressEvents}
#Import export ".\IDiscRecorder.ahk" {IDiscRecorder}
#Import export ".\IDiscRecorder2.ahk" {IDiscRecorder2}
#Import export ".\IDiscRecorder2Ex.ahk" {IDiscRecorder2Ex}
#Import export ".\IEnumDiscMasterFormats.ahk" {IEnumDiscMasterFormats}
#Import export ".\IEnumDiscRecorders.ahk" {IEnumDiscRecorders}
#Import export ".\IEnumFsiItems.ahk" {IEnumFsiItems}
#Import export ".\IEnumProgressItems.ahk" {IEnumProgressItems}
#Import export ".\IFileSystemImage.ahk" {IFileSystemImage}
#Import export ".\IFileSystemImage2.ahk" {IFileSystemImage2}
#Import export ".\IFileSystemImage3.ahk" {IFileSystemImage3}
#Import export ".\IFileSystemImageResult.ahk" {IFileSystemImageResult}
#Import export ".\IFileSystemImageResult2.ahk" {IFileSystemImageResult2}
#Import export ".\IFsiDirectoryItem.ahk" {IFsiDirectoryItem}
#Import export ".\IFsiDirectoryItem2.ahk" {IFsiDirectoryItem2}
#Import export ".\IFsiFileItem.ahk" {IFsiFileItem}
#Import export ".\IFsiFileItem2.ahk" {IFsiFileItem2}
#Import export ".\IFsiItem.ahk" {IFsiItem}
#Import export ".\IFsiNamedStreams.ahk" {IFsiNamedStreams}
#Import export ".\IIsoImageManager.ahk" {IIsoImageManager}
#Import export ".\IJolietDiscMaster.ahk" {IJolietDiscMaster}
#Import export ".\IMAPI_BURN_VERIFICATION_LEVEL.ahk" {IMAPI_BURN_VERIFICATION_LEVEL}
#Import export ".\IMAPI_CD_SECTOR_TYPE.ahk" {IMAPI_CD_SECTOR_TYPE}
#Import export ".\IMAPI_CD_TRACK_DIGITAL_COPY_SETTING.ahk" {IMAPI_CD_TRACK_DIGITAL_COPY_SETTING}
#Import export ".\IMAPI_FEATURE_PAGE_TYPE.ahk" {IMAPI_FEATURE_PAGE_TYPE}
#Import export ".\IMAPI_FORMAT2_DATA_MEDIA_STATE.ahk" {IMAPI_FORMAT2_DATA_MEDIA_STATE}
#Import export ".\IMAPI_FORMAT2_DATA_WRITE_ACTION.ahk" {IMAPI_FORMAT2_DATA_WRITE_ACTION}
#Import export ".\IMAPI_FORMAT2_RAW_CD_DATA_SECTOR_TYPE.ahk" {IMAPI_FORMAT2_RAW_CD_DATA_SECTOR_TYPE}
#Import export ".\IMAPI_FORMAT2_RAW_CD_WRITE_ACTION.ahk" {IMAPI_FORMAT2_RAW_CD_WRITE_ACTION}
#Import export ".\IMAPI_FORMAT2_TAO_WRITE_ACTION.ahk" {IMAPI_FORMAT2_TAO_WRITE_ACTION}
#Import export ".\IMAPI_MEDIA_PHYSICAL_TYPE.ahk" {IMAPI_MEDIA_PHYSICAL_TYPE}
#Import export ".\IMAPI_MEDIA_WRITE_PROTECT_STATE.ahk" {IMAPI_MEDIA_WRITE_PROTECT_STATE}
#Import export ".\IMAPI_MODE_PAGE_REQUEST_TYPE.ahk" {IMAPI_MODE_PAGE_REQUEST_TYPE}
#Import export ".\IMAPI_MODE_PAGE_TYPE.ahk" {IMAPI_MODE_PAGE_TYPE}
#Import export ".\IMAPI_PROFILE_TYPE.ahk" {IMAPI_PROFILE_TYPE}
#Import export ".\IMAPI_READ_TRACK_ADDRESS_TYPE.ahk" {IMAPI_READ_TRACK_ADDRESS_TYPE}
#Import export ".\IMMPID_CPV_ENUM.ahk" {IMMPID_CPV_ENUM}
#Import export ".\IMMPID_MPV_ENUM.ahk" {IMMPID_MPV_ENUM}
#Import export ".\IMMPID_MP_ENUM.ahk" {IMMPID_MP_ENUM}
#Import export ".\IMMPID_NMP_ENUM.ahk" {IMMPID_NMP_ENUM}
#Import export ".\IMMPID_RPV_ENUM.ahk" {IMMPID_RPV_ENUM}
#Import export ".\IMMPID_RP_ENUM.ahk" {IMMPID_RP_ENUM}
#Import export ".\IMMP_MPV_STORE_DRIVER_HANDLE.ahk" {IMMP_MPV_STORE_DRIVER_HANDLE}
#Import export ".\IMultisession.ahk" {IMultisession}
#Import export ".\IMultisessionRandomWrite.ahk" {IMultisessionRandomWrite}
#Import export ".\IMultisessionSequential.ahk" {IMultisessionSequential}
#Import export ".\IMultisessionSequential2.ahk" {IMultisessionSequential2}
#Import export ".\IProgressItem.ahk" {IProgressItem}
#Import export ".\IProgressItems.ahk" {IProgressItems}
#Import export ".\IRawCDImageCreator.ahk" {IRawCDImageCreator}
#Import export ".\IRawCDImageTrackInfo.ahk" {IRawCDImageTrackInfo}
#Import export ".\IRedbookDiscMaster.ahk" {IRedbookDiscMaster}
#Import export ".\IStreamConcatenate.ahk" {IStreamConcatenate}
#Import export ".\IStreamInterleave.ahk" {IStreamInterleave}
#Import export ".\IStreamPseudoRandomBased.ahk" {IStreamPseudoRandomBased}
#Import export ".\IWriteEngine2.ahk" {IWriteEngine2}
#Import export ".\IWriteEngine2EventArgs.ahk" {IWriteEngine2EventArgs}
#Import export ".\IWriteSpeedDescriptor.ahk" {IWriteSpeedDescriptor}
#Import export ".\LPMSGSESS.ahk" {LPMSGSESS}
#Import export ".\MEDIA_FLAGS.ahk" {MEDIA_FLAGS}
#Import export ".\MEDIA_TYPES.ahk" {MEDIA_TYPES}
#Import export ".\MSDiscMasterObj.ahk" {MSDiscMasterObj}
#Import export ".\MSDiscRecorderObj.ahk" {MSDiscRecorderObj}
#Import export ".\MSEnumDiscRecordersObj.ahk" {MSEnumDiscRecordersObj}
#Import export ".\MSGCALLRELEASE.ahk" {MSGCALLRELEASE}
#Import export ".\MsftDiscFormat2Data.ahk" {MsftDiscFormat2Data}
#Import export ".\MsftDiscFormat2Erase.ahk" {MsftDiscFormat2Erase}
#Import export ".\MsftDiscFormat2RawCD.ahk" {MsftDiscFormat2RawCD}
#Import export ".\MsftDiscFormat2TrackAtOnce.ahk" {MsftDiscFormat2TrackAtOnce}
#Import export ".\MsftDiscMaster2.ahk" {MsftDiscMaster2}
#Import export ".\MsftDiscRecorder2.ahk" {MsftDiscRecorder2}
#Import export ".\MsftFileSystemImage.ahk" {MsftFileSystemImage}
#Import export ".\MsftIsoImageManager.ahk" {MsftIsoImageManager}
#Import export ".\MsftMultisessionRandomWrite.ahk" {MsftMultisessionRandomWrite}
#Import export ".\MsftMultisessionSequential.ahk" {MsftMultisessionSequential}
#Import export ".\MsftRawCDImageCreator.ahk" {MsftRawCDImageCreator}
#Import export ".\MsftStreamConcatenate.ahk" {MsftStreamConcatenate}
#Import export ".\MsftStreamInterleave.ahk" {MsftStreamInterleave}
#Import export ".\MsftStreamPrng001.ahk" {MsftStreamPrng001}
#Import export ".\MsftStreamZero.ahk" {MsftStreamZero}
#Import export ".\MsftWriteEngine2.ahk" {MsftWriteEngine2}
#Import export ".\MsftWriteSpeedDescriptor.ahk" {MsftWriteSpeedDescriptor}
#Import export ".\PlatformId.ahk" {PlatformId}
#Import export ".\ProgressItem.ahk" {ProgressItem}
#Import export ".\ProgressItems.ahk" {ProgressItems}
#Import export ".\RECORDER_TYPES.ahk" {RECORDER_TYPES}
#Import export ".\SPropAttrArray.ahk" {SPropAttrArray}
#Import export ".\tagIMMPID_CPV_STRUCT.ahk" {tagIMMPID_CPV_STRUCT}
#Import export ".\tagIMMPID_GUIDLIST_ITEM.ahk" {tagIMMPID_GUIDLIST_ITEM}
#Import export ".\tagIMMPID_MPV_STRUCT.ahk" {tagIMMPID_MPV_STRUCT}
#Import export ".\tagIMMPID_MP_STRUCT.ahk" {tagIMMPID_MP_STRUCT}
#Import export ".\tagIMMPID_NMP_STRUCT.ahk" {tagIMMPID_NMP_STRUCT}
#Import export ".\tagIMMPID_RPV_STRUCT.ahk" {tagIMMPID_RPV_STRUCT}
#Import export ".\tagIMMPID_RP_STRUCT.ahk" {tagIMMPID_RP_STRUCT}
