#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\DXCoreAdapterEngineIndex.ahk" {DXCoreAdapterEngineIndex}
#Import export ".\DXCoreAdapterMemoryBudget.ahk" {DXCoreAdapterMemoryBudget}
#Import export ".\DXCoreAdapterMemoryBudgetNodeSegmentGroup.ahk" {DXCoreAdapterMemoryBudgetNodeSegmentGroup}
#Import export ".\DXCoreAdapterPreference.ahk" {DXCoreAdapterPreference}
#Import export ".\DXCoreAdapterProcessSetQueryInput.ahk" {DXCoreAdapterProcessSetQueryInput}
#Import export ".\DXCoreAdapterProcessSetQueryOutput.ahk" {DXCoreAdapterProcessSetQueryOutput}
#Import export ".\DXCoreAdapterProperty.ahk" {DXCoreAdapterProperty}
#Import export ".\DXCoreAdapterState.ahk" {DXCoreAdapterState}
#Import export ".\DXCoreEngineNamePropertyInput.ahk" {DXCoreEngineNamePropertyInput}
#Import export ".\DXCoreEngineNamePropertyOutput.ahk" {DXCoreEngineNamePropertyOutput}
#Import export ".\DXCoreEngineQueryInput.ahk" {DXCoreEngineQueryInput}
#Import export ".\DXCoreEngineQueryOutput.ahk" {DXCoreEngineQueryOutput}
#Import export ".\DXCoreFrequencyQueryOutput.ahk" {DXCoreFrequencyQueryOutput}
#Import export ".\DXCoreHardwareID.ahk" {DXCoreHardwareID}
#Import export ".\DXCoreHardwareIDParts.ahk" {DXCoreHardwareIDParts}
#Import export ".\DXCoreHardwareTypeFilterFlags.ahk" {DXCoreHardwareTypeFilterFlags}
#Import export ".\DXCoreMemoryQueryInput.ahk" {DXCoreMemoryQueryInput}
#Import export ".\DXCoreMemoryType.ahk" {DXCoreMemoryType}
#Import export ".\DXCoreMemoryUsage.ahk" {DXCoreMemoryUsage}
#Import export ".\DXCoreNotificationType.ahk" {DXCoreNotificationType}
#Import export ".\DXCoreProcessMemoryQueryInput.ahk" {DXCoreProcessMemoryQueryInput}
#Import export ".\DXCoreProcessMemoryQueryOutput.ahk" {DXCoreProcessMemoryQueryOutput}
#Import export ".\DXCoreRuntimeFilterFlags.ahk" {DXCoreRuntimeFilterFlags}
#Import export ".\DXCoreSegmentGroup.ahk" {DXCoreSegmentGroup}
#Import export ".\DXCoreWorkload.ahk" {DXCoreWorkload}
#Import export ".\IDXCoreAdapter.ahk" {IDXCoreAdapter}
#Import export ".\IDXCoreAdapter1.ahk" {IDXCoreAdapter1}
#Import export ".\IDXCoreAdapterFactory.ahk" {IDXCoreAdapterFactory}
#Import export ".\IDXCoreAdapterFactory1.ahk" {IDXCoreAdapterFactory1}
#Import export ".\IDXCoreAdapterList.ahk" {IDXCoreAdapterList}
#Import export ".\PFN_DXCORE_NOTIFICATION_CALLBACK.ahk" {PFN_DXCORE_NOTIFICATION_CALLBACK}
