#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\COR_DEBUG_IL_TO_NATIVE_MAP.ahk" {COR_DEBUG_IL_TO_NATIVE_MAP}
#Import export ".\COR_IL_MAP.ahk" {COR_IL_MAP}
#Import export ".\COR_PRF_ASSEMBLY_REFERENCE_INFO.ahk" {COR_PRF_ASSEMBLY_REFERENCE_INFO}
#Import export ".\COR_PRF_CLAUSE_TYPE.ahk" {COR_PRF_CLAUSE_TYPE}
#Import export ".\COR_PRF_CODEGEN_FLAGS.ahk" {COR_PRF_CODEGEN_FLAGS}
#Import export ".\COR_PRF_CODE_INFO.ahk" {COR_PRF_CODE_INFO}
#Import export ".\COR_PRF_EVENTPIPE_LEVEL.ahk" {COR_PRF_EVENTPIPE_LEVEL}
#Import export ".\COR_PRF_EVENTPIPE_PARAM_DESC.ahk" {COR_PRF_EVENTPIPE_PARAM_DESC}
#Import export ".\COR_PRF_EVENTPIPE_PARAM_TYPE.ahk" {COR_PRF_EVENTPIPE_PARAM_TYPE}
#Import export ".\COR_PRF_EVENTPIPE_PROVIDER_CONFIG.ahk" {COR_PRF_EVENTPIPE_PROVIDER_CONFIG}
#Import export ".\COR_PRF_EVENT_DATA.ahk" {COR_PRF_EVENT_DATA}
#Import export ".\COR_PRF_EX_CLAUSE_INFO.ahk" {COR_PRF_EX_CLAUSE_INFO}
#Import export ".\COR_PRF_FILTER_DATA.ahk" {COR_PRF_FILTER_DATA}
#Import export ".\COR_PRF_FINALIZER_FLAGS.ahk" {COR_PRF_FINALIZER_FLAGS}
#Import export ".\COR_PRF_FUNCTION.ahk" {COR_PRF_FUNCTION}
#Import export ".\COR_PRF_FUNCTION_ARGUMENT_INFO.ahk" {COR_PRF_FUNCTION_ARGUMENT_INFO}
#Import export ".\COR_PRF_FUNCTION_ARGUMENT_RANGE.ahk" {COR_PRF_FUNCTION_ARGUMENT_RANGE}
#Import export ".\COR_PRF_GC_GENERATION.ahk" {COR_PRF_GC_GENERATION}
#Import export ".\COR_PRF_GC_GENERATION_RANGE.ahk" {COR_PRF_GC_GENERATION_RANGE}
#Import export ".\COR_PRF_GC_REASON.ahk" {COR_PRF_GC_REASON}
#Import export ".\COR_PRF_GC_ROOT_FLAGS.ahk" {COR_PRF_GC_ROOT_FLAGS}
#Import export ".\COR_PRF_GC_ROOT_KIND.ahk" {COR_PRF_GC_ROOT_KIND}
#Import export ".\COR_PRF_HANDLE_TYPE.ahk" {COR_PRF_HANDLE_TYPE}
#Import export ".\COR_PRF_HIGH_MONITOR.ahk" {COR_PRF_HIGH_MONITOR}
#Import export ".\COR_PRF_JIT_CACHE.ahk" {COR_PRF_JIT_CACHE}
#Import export ".\COR_PRF_METHOD.ahk" {COR_PRF_METHOD}
#Import export ".\COR_PRF_MISC.ahk" {COR_PRF_MISC}
#Import export ".\COR_PRF_MODULE_FLAGS.ahk" {COR_PRF_MODULE_FLAGS}
#Import export ".\COR_PRF_MONITOR.ahk" {COR_PRF_MONITOR}
#Import export ".\COR_PRF_NONGC_HEAP_RANGE.ahk" {COR_PRF_NONGC_HEAP_RANGE}
#Import export ".\COR_PRF_REJIT_FLAGS.ahk" {COR_PRF_REJIT_FLAGS}
#Import export ".\COR_PRF_RUNTIME_TYPE.ahk" {COR_PRF_RUNTIME_TYPE}
#Import export ".\COR_PRF_SNAPSHOT_INFO.ahk" {COR_PRF_SNAPSHOT_INFO}
#Import export ".\COR_PRF_STATIC_TYPE.ahk" {COR_PRF_STATIC_TYPE}
#Import export ".\COR_PRF_SUSPEND_REASON.ahk" {COR_PRF_SUSPEND_REASON}
#Import export ".\COR_PRF_TRANSITION_REASON.ahk" {COR_PRF_TRANSITION_REASON}
#Import export ".\CorDebugIlToNativeMappingTypes.ahk" {CorDebugIlToNativeMappingTypes}
#Import export ".\EventPipeProviderCallback.ahk" {EventPipeProviderCallback}
#Import export ".\FunctionEnter.ahk" {FunctionEnter}
#Import export ".\FunctionEnter2.ahk" {FunctionEnter2}
#Import export ".\FunctionEnter3.ahk" {FunctionEnter3}
#Import export ".\FunctionEnter3WithInfo.ahk" {FunctionEnter3WithInfo}
#Import export ".\FunctionIDMapper.ahk" {FunctionIDMapper}
#Import export ".\FunctionIDMapper2.ahk" {FunctionIDMapper2}
#Import export ".\FunctionIDOrClientID.ahk" {FunctionIDOrClientID}
#Import export ".\FunctionLeave.ahk" {FunctionLeave}
#Import export ".\FunctionLeave2.ahk" {FunctionLeave2}
#Import export ".\FunctionLeave3.ahk" {FunctionLeave3}
#Import export ".\FunctionLeave3WithInfo.ahk" {FunctionLeave3WithInfo}
#Import export ".\FunctionTailcall.ahk" {FunctionTailcall}
#Import export ".\FunctionTailcall2.ahk" {FunctionTailcall2}
#Import export ".\FunctionTailcall3.ahk" {FunctionTailcall3}
#Import export ".\FunctionTailcall3WithInfo.ahk" {FunctionTailcall3WithInfo}
#Import export ".\ICorProfilerAssemblyReferenceProvider.ahk" {ICorProfilerAssemblyReferenceProvider}
#Import export ".\ICorProfilerCallback.ahk" {ICorProfilerCallback}
#Import export ".\ICorProfilerCallback10.ahk" {ICorProfilerCallback10}
#Import export ".\ICorProfilerCallback11.ahk" {ICorProfilerCallback11}
#Import export ".\ICorProfilerCallback2.ahk" {ICorProfilerCallback2}
#Import export ".\ICorProfilerCallback3.ahk" {ICorProfilerCallback3}
#Import export ".\ICorProfilerCallback4.ahk" {ICorProfilerCallback4}
#Import export ".\ICorProfilerCallback5.ahk" {ICorProfilerCallback5}
#Import export ".\ICorProfilerCallback6.ahk" {ICorProfilerCallback6}
#Import export ".\ICorProfilerCallback7.ahk" {ICorProfilerCallback7}
#Import export ".\ICorProfilerCallback8.ahk" {ICorProfilerCallback8}
#Import export ".\ICorProfilerCallback9.ahk" {ICorProfilerCallback9}
#Import export ".\ICorProfilerFunctionControl.ahk" {ICorProfilerFunctionControl}
#Import export ".\ICorProfilerFunctionEnum.ahk" {ICorProfilerFunctionEnum}
#Import export ".\ICorProfilerInfo.ahk" {ICorProfilerInfo}
#Import export ".\ICorProfilerInfo10.ahk" {ICorProfilerInfo10}
#Import export ".\ICorProfilerInfo11.ahk" {ICorProfilerInfo11}
#Import export ".\ICorProfilerInfo12.ahk" {ICorProfilerInfo12}
#Import export ".\ICorProfilerInfo13.ahk" {ICorProfilerInfo13}
#Import export ".\ICorProfilerInfo14.ahk" {ICorProfilerInfo14}
#Import export ".\ICorProfilerInfo2.ahk" {ICorProfilerInfo2}
#Import export ".\ICorProfilerInfo3.ahk" {ICorProfilerInfo3}
#Import export ".\ICorProfilerInfo4.ahk" {ICorProfilerInfo4}
#Import export ".\ICorProfilerInfo5.ahk" {ICorProfilerInfo5}
#Import export ".\ICorProfilerInfo6.ahk" {ICorProfilerInfo6}
#Import export ".\ICorProfilerInfo7.ahk" {ICorProfilerInfo7}
#Import export ".\ICorProfilerInfo8.ahk" {ICorProfilerInfo8}
#Import export ".\ICorProfilerInfo9.ahk" {ICorProfilerInfo9}
#Import export ".\ICorProfilerMethodEnum.ahk" {ICorProfilerMethodEnum}
#Import export ".\ICorProfilerModuleEnum.ahk" {ICorProfilerModuleEnum}
#Import export ".\ICorProfilerObjectEnum.ahk" {ICorProfilerObjectEnum}
#Import export ".\ICorProfilerThreadEnum.ahk" {ICorProfilerThreadEnum}
#Import export ".\IMethodMalloc.ahk" {IMethodMalloc}
#Import export ".\ObjectReferenceCallback.ahk" {ObjectReferenceCallback}
#Import export ".\StackSnapshotCallback.ahk" {StackSnapshotCallback}
