#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\BATTERY_DEVTYPE.ahk" {BATTERY_DEVTYPE}
#Import export ".\BATTERY_LEVEL.ahk" {BATTERY_LEVEL}
#Import export ".\BATTERY_TYPE.ahk" {BATTERY_TYPE}
#Import export ".\Constants.ahk" {*}
#Import export ".\XINPUT_BATTERY_INFORMATION.ahk" {XINPUT_BATTERY_INFORMATION}
#Import export ".\XINPUT_CAPABILITIES.ahk" {XINPUT_CAPABILITIES}
#Import export ".\XINPUT_CAPABILITIES_FLAGS.ahk" {XINPUT_CAPABILITIES_FLAGS}
#Import export ".\XINPUT_DEVSUBTYPE.ahk" {XINPUT_DEVSUBTYPE}
#Import export ".\XINPUT_DEVTYPE.ahk" {XINPUT_DEVTYPE}
#Import export ".\XINPUT_FLAG.ahk" {XINPUT_FLAG}
#Import export ".\XINPUT_GAMEPAD.ahk" {XINPUT_GAMEPAD}
#Import export ".\XINPUT_GAMEPAD_BUTTON_FLAGS.ahk" {XINPUT_GAMEPAD_BUTTON_FLAGS}
#Import export ".\XINPUT_KEYSTROKE.ahk" {XINPUT_KEYSTROKE}
#Import export ".\XINPUT_KEYSTROKE_FLAGS.ahk" {XINPUT_KEYSTROKE_FLAGS}
#Import export ".\XINPUT_STATE.ahk" {XINPUT_STATE}
#Import export ".\XINPUT_VIBRATION.ahk" {XINPUT_VIBRATION}
#Import export ".\XINPUT_VIRTUAL_KEY.ahk" {XINPUT_VIRTUAL_KEY}
