#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\AAAccountingData.ahk" {AAAccountingData}
#Import export ".\AAAccountingDataType.ahk" {AAAccountingDataType}
#Import export ".\AAAuthSchemes.ahk" {AAAuthSchemes}
#Import export ".\AATrustClassID.ahk" {AATrustClassID}
#Import export ".\ADsTSUserEx.ahk" {ADsTSUserEx}
#Import export ".\AE_CURRENT_POSITION.ahk" {AE_CURRENT_POSITION}
#Import export ".\AE_POSITION_FLAGS.ahk" {AE_POSITION_FLAGS}
#Import export ".\Apis.ahk" {*}
#Import export ".\BITMAP_RENDERER_STATISTICS.ahk" {BITMAP_RENDERER_STATISTICS}
#Import export ".\CHANNEL_DEF.ahk" {CHANNEL_DEF}
#Import export ".\CHANNEL_ENTRY_POINTS.ahk" {CHANNEL_ENTRY_POINTS}
#Import export ".\CHANNEL_PDU_HEADER.ahk" {CHANNEL_PDU_HEADER}
#Import export ".\CLIENT_DISPLAY.ahk" {CLIENT_DISPLAY}
#Import export ".\CLIENT_MESSAGE_TYPE.ahk" {CLIENT_MESSAGE_TYPE}
#Import export ".\CONNECTION_CHANGE_NOTIFICATION.ahk" {CONNECTION_CHANGE_NOTIFICATION}
#Import export ".\Constants.ahk" {*}
#Import export ".\IADsTSUserEx.ahk" {IADsTSUserEx}
#Import export ".\IAudioDeviceEndpoint.ahk" {IAudioDeviceEndpoint}
#Import export ".\IAudioEndpoint.ahk" {IAudioEndpoint}
#Import export ".\IAudioEndpointControl.ahk" {IAudioEndpointControl}
#Import export ".\IAudioEndpointRT.ahk" {IAudioEndpointRT}
#Import export ".\IAudioInputEndpointRT.ahk" {IAudioInputEndpointRT}
#Import export ".\IAudioOutputEndpointRT.ahk" {IAudioOutputEndpointRT}
#Import export ".\IRemoteDesktopClient.ahk" {IRemoteDesktopClient}
#Import export ".\IRemoteDesktopClientActions.ahk" {IRemoteDesktopClientActions}
#Import export ".\IRemoteDesktopClientSettings.ahk" {IRemoteDesktopClientSettings}
#Import export ".\IRemoteDesktopClientTouchPointer.ahk" {IRemoteDesktopClientTouchPointer}
#Import export ".\IRemoteSystemAdditionalInfoProvider.ahk" {IRemoteSystemAdditionalInfoProvider}
#Import export ".\ITSGAccountingEngine.ahk" {ITSGAccountingEngine}
#Import export ".\ITSGAuthenticateUserSink.ahk" {ITSGAuthenticateUserSink}
#Import export ".\ITSGAuthenticationEngine.ahk" {ITSGAuthenticationEngine}
#Import export ".\ITSGAuthorizeConnectionSink.ahk" {ITSGAuthorizeConnectionSink}
#Import export ".\ITSGAuthorizeResourceSink.ahk" {ITSGAuthorizeResourceSink}
#Import export ".\ITSGPolicyEngine.ahk" {ITSGPolicyEngine}
#Import export ".\ITsSbBaseNotifySink.ahk" {ITsSbBaseNotifySink}
#Import export ".\ITsSbClientConnection.ahk" {ITsSbClientConnection}
#Import export ".\ITsSbClientConnectionPropertySet.ahk" {ITsSbClientConnectionPropertySet}
#Import export ".\ITsSbEnvironment.ahk" {ITsSbEnvironment}
#Import export ".\ITsSbEnvironmentPropertySet.ahk" {ITsSbEnvironmentPropertySet}
#Import export ".\ITsSbFilterPluginStore.ahk" {ITsSbFilterPluginStore}
#Import export ".\ITsSbGenericNotifySink.ahk" {ITsSbGenericNotifySink}
#Import export ".\ITsSbGlobalStore.ahk" {ITsSbGlobalStore}
#Import export ".\ITsSbLoadBalanceResult.ahk" {ITsSbLoadBalanceResult}
#Import export ".\ITsSbLoadBalancing.ahk" {ITsSbLoadBalancing}
#Import export ".\ITsSbLoadBalancingNotifySink.ahk" {ITsSbLoadBalancingNotifySink}
#Import export ".\ITsSbOrchestration.ahk" {ITsSbOrchestration}
#Import export ".\ITsSbOrchestrationNotifySink.ahk" {ITsSbOrchestrationNotifySink}
#Import export ".\ITsSbPlacement.ahk" {ITsSbPlacement}
#Import export ".\ITsSbPlacementNotifySink.ahk" {ITsSbPlacementNotifySink}
#Import export ".\ITsSbPlugin.ahk" {ITsSbPlugin}
#Import export ".\ITsSbPluginNotifySink.ahk" {ITsSbPluginNotifySink}
#Import export ".\ITsSbPluginPropertySet.ahk" {ITsSbPluginPropertySet}
#Import export ".\ITsSbPropertySet.ahk" {ITsSbPropertySet}
#Import export ".\ITsSbProvider.ahk" {ITsSbProvider}
#Import export ".\ITsSbProvisioning.ahk" {ITsSbProvisioning}
#Import export ".\ITsSbProvisioningPluginNotifySink.ahk" {ITsSbProvisioningPluginNotifySink}
#Import export ".\ITsSbResourceNotification.ahk" {ITsSbResourceNotification}
#Import export ".\ITsSbResourceNotificationEx.ahk" {ITsSbResourceNotificationEx}
#Import export ".\ITsSbResourcePlugin.ahk" {ITsSbResourcePlugin}
#Import export ".\ITsSbResourcePluginStore.ahk" {ITsSbResourcePluginStore}
#Import export ".\ITsSbServiceNotification.ahk" {ITsSbServiceNotification}
#Import export ".\ITsSbSession.ahk" {ITsSbSession}
#Import export ".\ITsSbTarget.ahk" {ITsSbTarget}
#Import export ".\ITsSbTargetPropertySet.ahk" {ITsSbTargetPropertySet}
#Import export ".\ITsSbTaskInfo.ahk" {ITsSbTaskInfo}
#Import export ".\ITsSbTaskPlugin.ahk" {ITsSbTaskPlugin}
#Import export ".\ITsSbTaskPluginNotifySink.ahk" {ITsSbTaskPluginNotifySink}
#Import export ".\IWRdsEnhancedFastReconnectArbitrator.ahk" {IWRdsEnhancedFastReconnectArbitrator}
#Import export ".\IWRdsGraphicsChannel.ahk" {IWRdsGraphicsChannel}
#Import export ".\IWRdsGraphicsChannelEvents.ahk" {IWRdsGraphicsChannelEvents}
#Import export ".\IWRdsGraphicsChannelManager.ahk" {IWRdsGraphicsChannelManager}
#Import export ".\IWRdsProtocolConnection.ahk" {IWRdsProtocolConnection}
#Import export ".\IWRdsProtocolConnection2.ahk" {IWRdsProtocolConnection2}
#Import export ".\IWRdsProtocolConnectionCallback.ahk" {IWRdsProtocolConnectionCallback}
#Import export ".\IWRdsProtocolConnectionSettings.ahk" {IWRdsProtocolConnectionSettings}
#Import export ".\IWRdsProtocolLicenseConnection.ahk" {IWRdsProtocolLicenseConnection}
#Import export ".\IWRdsProtocolListener.ahk" {IWRdsProtocolListener}
#Import export ".\IWRdsProtocolListenerCallback.ahk" {IWRdsProtocolListenerCallback}
#Import export ".\IWRdsProtocolLogonErrorRedirector.ahk" {IWRdsProtocolLogonErrorRedirector}
#Import export ".\IWRdsProtocolManager.ahk" {IWRdsProtocolManager}
#Import export ".\IWRdsProtocolSettings.ahk" {IWRdsProtocolSettings}
#Import export ".\IWRdsProtocolShadowCallback.ahk" {IWRdsProtocolShadowCallback}
#Import export ".\IWRdsProtocolShadowConnection.ahk" {IWRdsProtocolShadowConnection}
#Import export ".\IWRdsWddmIddProps.ahk" {IWRdsWddmIddProps}
#Import export ".\IWRdsWddmIddProps1.ahk" {IWRdsWddmIddProps1}
#Import export ".\IWTSBitmapRenderService.ahk" {IWTSBitmapRenderService}
#Import export ".\IWTSBitmapRenderer.ahk" {IWTSBitmapRenderer}
#Import export ".\IWTSBitmapRendererCallback.ahk" {IWTSBitmapRendererCallback}
#Import export ".\IWTSListener.ahk" {IWTSListener}
#Import export ".\IWTSListenerCallback.ahk" {IWTSListenerCallback}
#Import export ".\IWTSPlugin.ahk" {IWTSPlugin}
#Import export ".\IWTSPluginServiceProvider.ahk" {IWTSPluginServiceProvider}
#Import export ".\IWTSProtocolConnection.ahk" {IWTSProtocolConnection}
#Import export ".\IWTSProtocolConnectionCallback.ahk" {IWTSProtocolConnectionCallback}
#Import export ".\IWTSProtocolLicenseConnection.ahk" {IWTSProtocolLicenseConnection}
#Import export ".\IWTSProtocolListener.ahk" {IWTSProtocolListener}
#Import export ".\IWTSProtocolListenerCallback.ahk" {IWTSProtocolListenerCallback}
#Import export ".\IWTSProtocolLogonErrorRedirector.ahk" {IWTSProtocolLogonErrorRedirector}
#Import export ".\IWTSProtocolManager.ahk" {IWTSProtocolManager}
#Import export ".\IWTSProtocolShadowCallback.ahk" {IWTSProtocolShadowCallback}
#Import export ".\IWTSProtocolShadowConnection.ahk" {IWTSProtocolShadowConnection}
#Import export ".\IWTSSBPlugin.ahk" {IWTSSBPlugin}
#Import export ".\IWTSVirtualChannel.ahk" {IWTSVirtualChannel}
#Import export ".\IWTSVirtualChannelCallback.ahk" {IWTSVirtualChannelCallback}
#Import export ".\IWTSVirtualChannelManager.ahk" {IWTSVirtualChannelManager}
#Import export ".\IWorkspace.ahk" {IWorkspace}
#Import export ".\IWorkspace2.ahk" {IWorkspace2}
#Import export ".\IWorkspace3.ahk" {IWorkspace3}
#Import export ".\IWorkspaceClientExt.ahk" {IWorkspaceClientExt}
#Import export ".\IWorkspaceRegistration.ahk" {IWorkspaceRegistration}
#Import export ".\IWorkspaceRegistration2.ahk" {IWorkspaceRegistration2}
#Import export ".\IWorkspaceReportMessage.ahk" {IWorkspaceReportMessage}
#Import export ".\IWorkspaceResTypeRegistry.ahk" {IWorkspaceResTypeRegistry}
#Import export ".\IWorkspaceScriptable.ahk" {IWorkspaceScriptable}
#Import export ".\IWorkspaceScriptable2.ahk" {IWorkspaceScriptable2}
#Import export ".\IWorkspaceScriptable3.ahk" {IWorkspaceScriptable3}
#Import export ".\ItsPubPlugin.ahk" {ItsPubPlugin}
#Import export ".\ItsPubPlugin2.ahk" {ItsPubPlugin2}
#Import export ".\KeyCombinationType.ahk" {KeyCombinationType}
#Import export ".\PCHANNEL_INIT_EVENT_FN.ahk" {PCHANNEL_INIT_EVENT_FN}
#Import export ".\PCHANNEL_OPEN_EVENT_FN.ahk" {PCHANNEL_OPEN_EVENT_FN}
#Import export ".\PLUGIN_TYPE.ahk" {PLUGIN_TYPE}
#Import export ".\PRODUCT_INFOA.ahk" {PRODUCT_INFOA}
#Import export ".\PRODUCT_INFOW.ahk" {PRODUCT_INFOW}
#Import export ".\PVIRTUALCHANNELCLOSE.ahk" {PVIRTUALCHANNELCLOSE}
#Import export ".\PVIRTUALCHANNELENTRY.ahk" {PVIRTUALCHANNELENTRY}
#Import export ".\PVIRTUALCHANNELINIT.ahk" {PVIRTUALCHANNELINIT}
#Import export ".\PVIRTUALCHANNELOPEN.ahk" {PVIRTUALCHANNELOPEN}
#Import export ".\PVIRTUALCHANNELWRITE.ahk" {PVIRTUALCHANNELWRITE}
#Import export ".\PasswordEncodingType.ahk" {PasswordEncodingType}
#Import export ".\PolicyAttributeType.ahk" {PolicyAttributeType}
#Import export ".\RDV_TASK_STATUS.ahk" {RDV_TASK_STATUS}
#Import export ".\RD_FARM_TYPE.ahk" {RD_FARM_TYPE}
#Import export ".\RFX_GFX_MONITOR_INFO.ahk" {RFX_GFX_MONITOR_INFO}
#Import export ".\RFX_GFX_MSG_CLIENT_DESKTOP_INFO_REQUEST.ahk" {RFX_GFX_MSG_CLIENT_DESKTOP_INFO_REQUEST}
#Import export ".\RFX_GFX_MSG_CLIENT_DESKTOP_INFO_RESPONSE.ahk" {RFX_GFX_MSG_CLIENT_DESKTOP_INFO_RESPONSE}
#Import export ".\RFX_GFX_MSG_DESKTOP_CONFIG_CHANGE_CONFIRM.ahk" {RFX_GFX_MSG_DESKTOP_CONFIG_CHANGE_CONFIRM}
#Import export ".\RFX_GFX_MSG_DESKTOP_CONFIG_CHANGE_NOTIFY.ahk" {RFX_GFX_MSG_DESKTOP_CONFIG_CHANGE_NOTIFY}
#Import export ".\RFX_GFX_MSG_DESKTOP_INPUT_RESET.ahk" {RFX_GFX_MSG_DESKTOP_INPUT_RESET}
#Import export ".\RFX_GFX_MSG_DESKTOP_RESEND_REQUEST.ahk" {RFX_GFX_MSG_DESKTOP_RESEND_REQUEST}
#Import export ".\RFX_GFX_MSG_DISCONNECT_NOTIFY.ahk" {RFX_GFX_MSG_DISCONNECT_NOTIFY}
#Import export ".\RFX_GFX_MSG_HEADER.ahk" {RFX_GFX_MSG_HEADER}
#Import export ".\RFX_GFX_MSG_RDP_DATA.ahk" {RFX_GFX_MSG_RDP_DATA}
#Import export ".\RFX_GFX_RECT.ahk" {RFX_GFX_RECT}
#Import export ".\RemoteActionType.ahk" {RemoteActionType}
#Import export ".\SESSION_TIMEOUT_ACTION_TYPE.ahk" {SESSION_TIMEOUT_ACTION_TYPE}
#Import export ".\SnapshotEncodingType.ahk" {SnapshotEncodingType}
#Import export ".\SnapshotFormatType.ahk" {SnapshotFormatType}
#Import export ".\TARGET_CHANGE_TYPE.ahk" {TARGET_CHANGE_TYPE}
#Import export ".\TARGET_OWNER.ahk" {TARGET_OWNER}
#Import export ".\TARGET_PATCH_STATE.ahk" {TARGET_PATCH_STATE}
#Import export ".\TARGET_STATE.ahk" {TARGET_STATE}
#Import export ".\TARGET_TYPE.ahk" {TARGET_TYPE}
#Import export ".\TSPUB_PLUGIN_PD_ASSIGNMENT_TYPE.ahk" {TSPUB_PLUGIN_PD_ASSIGNMENT_TYPE}
#Import export ".\TSPUB_PLUGIN_PD_RESOLUTION_TYPE.ahk" {TSPUB_PLUGIN_PD_RESOLUTION_TYPE}
#Import export ".\TSSB_NOTIFICATION_TYPE.ahk" {TSSB_NOTIFICATION_TYPE}
#Import export ".\TSSD_AddrV46Type.ahk" {TSSD_AddrV46Type}
#Import export ".\TSSD_ConnectionPoint.ahk" {TSSD_ConnectionPoint}
#Import export ".\TSSESSION_STATE.ahk" {TSSESSION_STATE}
#Import export ".\TSUserExInterfaces.ahk" {TSUserExInterfaces}
#Import export ".\TS_SB_SORT_BY.ahk" {TS_SB_SORT_BY}
#Import export ".\VM_HOST_NOTIFY_STATUS.ahk" {VM_HOST_NOTIFY_STATUS}
#Import export ".\VM_NOTIFY_ENTRY.ahk" {VM_NOTIFY_ENTRY}
#Import export ".\VM_NOTIFY_INFO.ahk" {VM_NOTIFY_INFO}
#Import export ".\VM_NOTIFY_STATUS.ahk" {VM_NOTIFY_STATUS}
#Import export ".\VM_PATCH_INFO.ahk" {VM_PATCH_INFO}
#Import export ".\WRDS_CONNECTION_SETTING.ahk" {WRDS_CONNECTION_SETTING}
#Import export ".\WRDS_CONNECTION_SETTINGS.ahk" {WRDS_CONNECTION_SETTINGS}
#Import export ".\WRDS_CONNECTION_SETTINGS_1.ahk" {WRDS_CONNECTION_SETTINGS_1}
#Import export ".\WRDS_CONNECTION_SETTING_LEVEL.ahk" {WRDS_CONNECTION_SETTING_LEVEL}
#Import export ".\WRDS_DYNAMIC_TIME_ZONE_INFORMATION.ahk" {WRDS_DYNAMIC_TIME_ZONE_INFORMATION}
#Import export ".\WRDS_LISTENER_SETTING.ahk" {WRDS_LISTENER_SETTING}
#Import export ".\WRDS_LISTENER_SETTINGS.ahk" {WRDS_LISTENER_SETTINGS}
#Import export ".\WRDS_LISTENER_SETTINGS_1.ahk" {WRDS_LISTENER_SETTINGS_1}
#Import export ".\WRDS_LISTENER_SETTING_LEVEL.ahk" {WRDS_LISTENER_SETTING_LEVEL}
#Import export ".\WRDS_SETTING.ahk" {WRDS_SETTING}
#Import export ".\WRDS_SETTINGS.ahk" {WRDS_SETTINGS}
#Import export ".\WRDS_SETTINGS_1.ahk" {WRDS_SETTINGS_1}
#Import export ".\WRDS_SETTING_LEVEL.ahk" {WRDS_SETTING_LEVEL}
#Import export ".\WRDS_SETTING_STATUS.ahk" {WRDS_SETTING_STATUS}
#Import export ".\WRDS_SETTING_TYPE.ahk" {WRDS_SETTING_TYPE}
#Import export ".\WRdsGraphicsChannelType.ahk" {WRdsGraphicsChannelType}
#Import export ".\WTSCLIENTA.ahk" {WTSCLIENTA}
#Import export ".\WTSCLIENTW.ahk" {WTSCLIENTW}
#Import export ".\WTSCONFIGINFOA.ahk" {WTSCONFIGINFOA}
#Import export ".\WTSCONFIGINFOW.ahk" {WTSCONFIGINFOW}
#Import export ".\WTSINFOA.ahk" {WTSINFOA}
#Import export ".\WTSINFOEXA.ahk" {WTSINFOEXA}
#Import export ".\WTSINFOEXW.ahk" {WTSINFOEXW}
#Import export ".\WTSINFOEX_LEVEL1_A.ahk" {WTSINFOEX_LEVEL1_A}
#Import export ".\WTSINFOEX_LEVEL1_W.ahk" {WTSINFOEX_LEVEL1_W}
#Import export ".\WTSINFOEX_LEVEL_A.ahk" {WTSINFOEX_LEVEL_A}
#Import export ".\WTSINFOEX_LEVEL_W.ahk" {WTSINFOEX_LEVEL_W}
#Import export ".\WTSINFOW.ahk" {WTSINFOW}
#Import export ".\WTSLISTENERCONFIGA.ahk" {WTSLISTENERCONFIGA}
#Import export ".\WTSLISTENERCONFIGW.ahk" {WTSLISTENERCONFIGW}
#Import export ".\WTSSBX_ADDRESS_FAMILY.ahk" {WTSSBX_ADDRESS_FAMILY}
#Import export ".\WTSSBX_IP_ADDRESS.ahk" {WTSSBX_IP_ADDRESS}
#Import export ".\WTSSBX_MACHINE_CONNECT_INFO.ahk" {WTSSBX_MACHINE_CONNECT_INFO}
#Import export ".\WTSSBX_MACHINE_DRAIN.ahk" {WTSSBX_MACHINE_DRAIN}
#Import export ".\WTSSBX_MACHINE_INFO.ahk" {WTSSBX_MACHINE_INFO}
#Import export ".\WTSSBX_MACHINE_SESSION_MODE.ahk" {WTSSBX_MACHINE_SESSION_MODE}
#Import export ".\WTSSBX_MACHINE_STATE.ahk" {WTSSBX_MACHINE_STATE}
#Import export ".\WTSSBX_NOTIFICATION_TYPE.ahk" {WTSSBX_NOTIFICATION_TYPE}
#Import export ".\WTSSBX_SESSION_INFO.ahk" {WTSSBX_SESSION_INFO}
#Import export ".\WTSSBX_SESSION_STATE.ahk" {WTSSBX_SESSION_STATE}
#Import export ".\WTSSESSION_NOTIFICATION.ahk" {WTSSESSION_NOTIFICATION}
#Import export ".\WTSUSERCONFIGA.ahk" {WTSUSERCONFIGA}
#Import export ".\WTSUSERCONFIGW.ahk" {WTSUSERCONFIGW}
#Import export ".\WTS_CACHE_STATS.ahk" {WTS_CACHE_STATS}
#Import export ".\WTS_CACHE_STATS_UN.ahk" {WTS_CACHE_STATS_UN}
#Import export ".\WTS_CERT_TYPE.ahk" {WTS_CERT_TYPE}
#Import export ".\WTS_CLIENT_ADDRESS.ahk" {WTS_CLIENT_ADDRESS}
#Import export ".\WTS_CLIENT_DATA.ahk" {WTS_CLIENT_DATA}
#Import export ".\WTS_CLIENT_DISPLAY.ahk" {WTS_CLIENT_DISPLAY}
#Import export ".\WTS_CLOUD_AUTH_HANDLE.ahk" {WTS_CLOUD_AUTH_HANDLE}
#Import export ".\WTS_CONFIG_CLASS.ahk" {WTS_CONFIG_CLASS}
#Import export ".\WTS_CONFIG_SOURCE.ahk" {WTS_CONFIG_SOURCE}
#Import export ".\WTS_CONNECTSTATE_CLASS.ahk" {WTS_CONNECTSTATE_CLASS}
#Import export ".\WTS_DISPLAY_IOCTL.ahk" {WTS_DISPLAY_IOCTL}
#Import export ".\WTS_INFO_CLASS.ahk" {WTS_INFO_CLASS}
#Import export ".\WTS_LICENSE_CAPABILITIES.ahk" {WTS_LICENSE_CAPABILITIES}
#Import export ".\WTS_LOGON_ERROR_REDIRECTOR_RESPONSE.ahk" {WTS_LOGON_ERROR_REDIRECTOR_RESPONSE}
#Import export ".\WTS_POLICY_DATA.ahk" {WTS_POLICY_DATA}
#Import export ".\WTS_PROCESS_INFOA.ahk" {WTS_PROCESS_INFOA}
#Import export ".\WTS_PROCESS_INFOW.ahk" {WTS_PROCESS_INFOW}
#Import export ".\WTS_PROCESS_INFO_EXA.ahk" {WTS_PROCESS_INFO_EXA}
#Import export ".\WTS_PROCESS_INFO_EXW.ahk" {WTS_PROCESS_INFO_EXW}
#Import export ".\WTS_PROPERTY_VALUE.ahk" {WTS_PROPERTY_VALUE}
#Import export ".\WTS_PROTOCOL_CACHE.ahk" {WTS_PROTOCOL_CACHE}
#Import export ".\WTS_PROTOCOL_COUNTERS.ahk" {WTS_PROTOCOL_COUNTERS}
#Import export ".\WTS_PROTOCOL_STATUS.ahk" {WTS_PROTOCOL_STATUS}
#Import export ".\WTS_RCM_DRAIN_STATE.ahk" {WTS_RCM_DRAIN_STATE}
#Import export ".\WTS_RCM_SERVICE_STATE.ahk" {WTS_RCM_SERVICE_STATE}
#Import export ".\WTS_SECURITY_FLAGS.ahk" {WTS_SECURITY_FLAGS}
#Import export ".\WTS_SERIALIZED_USER_CREDENTIAL.ahk" {WTS_SERIALIZED_USER_CREDENTIAL}
#Import export ".\WTS_SERVER_INFOA.ahk" {WTS_SERVER_INFOA}
#Import export ".\WTS_SERVER_INFOW.ahk" {WTS_SERVER_INFOW}
#Import export ".\WTS_SERVICE_STATE.ahk" {WTS_SERVICE_STATE}
#Import export ".\WTS_SESSION_ADDRESS.ahk" {WTS_SESSION_ADDRESS}
#Import export ".\WTS_SESSION_ID.ahk" {WTS_SESSION_ID}
#Import export ".\WTS_SESSION_INFOA.ahk" {WTS_SESSION_INFOA}
#Import export ".\WTS_SESSION_INFOW.ahk" {WTS_SESSION_INFOW}
#Import export ".\WTS_SESSION_INFO_1A.ahk" {WTS_SESSION_INFO_1A}
#Import export ".\WTS_SESSION_INFO_1W.ahk" {WTS_SESSION_INFO_1W}
#Import export ".\WTS_SMALL_RECT.ahk" {WTS_SMALL_RECT}
#Import export ".\WTS_SOCKADDR.ahk" {WTS_SOCKADDR}
#Import export ".\WTS_SYSTEMTIME.ahk" {WTS_SYSTEMTIME}
#Import export ".\WTS_TIME_ZONE_INFORMATION.ahk" {WTS_TIME_ZONE_INFORMATION}
#Import export ".\WTS_TYPE_CLASS.ahk" {WTS_TYPE_CLASS}
#Import export ".\WTS_USER_CREDENTIAL.ahk" {WTS_USER_CREDENTIAL}
#Import export ".\WTS_USER_DATA.ahk" {WTS_USER_DATA}
#Import export ".\WTS_VALIDATION_INFORMATIONA.ahk" {WTS_VALIDATION_INFORMATIONA}
#Import export ".\WTS_VALIDATION_INFORMATIONW.ahk" {WTS_VALIDATION_INFORMATIONW}
#Import export ".\WTS_VIRTUAL_CLASS.ahk" {WTS_VIRTUAL_CLASS}
#Import export ".\Workspace.ahk" {Workspace}
#Import export ".\_ITSWkspEvents.ahk" {_ITSWkspEvents}
#Import export ".\pluginResource.ahk" {pluginResource}
#Import export ".\pluginResource2.ahk" {pluginResource2}
#Import export ".\pluginResource2FileAssociation.ahk" {pluginResource2FileAssociation}
