#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\Guid.ahk" { Guid }
#Import ".\AE_CURRENT_POSITION.ahk" { AE_CURRENT_POSITION }
#Import "..\..\Media\Audio\Apo\APO_CONNECTION_PROPERTY.ahk" { APO_CONNECTION_PROPERTY }
#Import "..\Com\IUnknown.ahk" { IUnknown }

/**
 * Gets the output buffer for each processing pass.
 * @remarks
 * <b>IAudioOutputEndpointRT</b> methods can be called 
 *      from a real-time processing thread. The implementation of the methods of this interface must not block, access 
 *      paged memory, or call any blocking system routines.
 * 
 * The Remote Desktop Services AudioEndpoint API is for use in Remote Desktop scenarios; it is not for client 
 *     applications.
 * @see https://learn.microsoft.com/windows/win32/api/audioengineendpoint/nn-audioengineendpoint-iaudiooutputendpointrt
 * @namespace Windows.Win32.System.RemoteDesktop
 */
export default struct IAudioOutputEndpointRT extends IUnknown {
    /**
     * The interface identifier for IAudioOutputEndpointRT
     * @type {Guid}
     */
    static IID := Guid("{8fa906e4-c31c-4e31-932e-19a66385e9aa}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for IAudioOutputEndpointRT interfaces
    */
    struct Vtbl extends IUnknown.Vtbl {
        GetOutputDataPointer     : IntPtr
        ReleaseOutputDataPointer : IntPtr
        PulseEndpoint            : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := IAudioOutputEndpointRT.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * Returns a pointer to the output buffer in which data will be written by the audio engine.
     * @remarks
     * This method returns a pointer to a buffer in which the audio engine writes data.
     *     The data is not valid until the <a href="https://docs.microsoft.com/windows/desktop/api/audioengineendpoint/nf-audioengineendpoint-iaudiooutputendpointrt-releaseoutputdatapointer">IAudioOutputEndpointRT::ReleaseOutputDataPointer</a> method is called.
     *     The returned pointer must be frame-aligned.
     * 
     * The frame count passed in <b>u32FrameCount</b>  must be less than or equal to the maximum number of frames supported by the endpoint. To get the maximum frame count that the endpoint can support, the audio engine calls the <a href="https://docs.microsoft.com/windows/desktop/api/audioengineendpoint/nf-audioengineendpoint-iaudioendpoint-getframesperpacket">IAudioEndpoint::GetFramesPerPacket</a> method.
     * 
     * This method can be called from a real-time processing thread. The
     *     implementation of this method must not block, access
     *     paged memory, or call any blocking system routines.
     * 
     * The Remote Desktop Services AudioEndpoint API is for use in Remote Desktop scenarios; it is not for client applications.
     * @param {Integer} u32FrameCount The number of frames in the output buffer pointed to by the data pointer that is returned by this method. The endpoint must not
     *     cache this information because this can be changed by the audio engine depending on its processing requirements. For more information, see Remarks.
     * @param {Pointer<AE_CURRENT_POSITION>} pAeTimeStamp A pointer to an <a href="https://docs.microsoft.com/windows/desktop/api/audioengineendpoint/ns-audioengineendpoint-ae_current_position">AE_CURRENT_POSITION</a> structure that specifies the time stamp of the data that is rendered. This parameter is optional.
     * @returns {Pointer} A pointer to the buffer to which data will be written.
     * @see https://learn.microsoft.com/windows/win32/api/audioengineendpoint/nf-audioengineendpoint-iaudiooutputendpointrt-getoutputdatapointer
     */
    GetOutputDataPointer(u32FrameCount, pAeTimeStamp) {
        result := ComCall(3, this, "uint", u32FrameCount, AE_CURRENT_POSITION.Ptr, pAeTimeStamp, IntPtr)
        return result
    }

    /**
     * Releases the pointer to the output buffer.
     * @remarks
     * <b>ReleaseOutputDataPointer</b> notifies the endpoint that the audio engine has completed the task of writing data in the output buffer and no longer requires the data pointer. This method also relays information such as the time that corresponds to the audio samples in the
     *     output buffer, the number of frames generated by the audio engine, and whether the buffer
     *     is full of valid data or silence data.
     *     Based on this information, an endpoint that represents a looped buffer and is attached to the output of the
     *     audio engine can advance its
     *     write position in the buffer.
     *     A value of zero in the <i>u32FrameCount</i> parameter of the <a href="https://docs.microsoft.com/windows/desktop/api/audioengineendpoint/nf-audioengineendpoint-iaudiooutputendpointrt-getoutputdatapointer">GetOutputDataPointer</a> method indicates that the audio engine did not write any valid data in the output buffer. The <i>u32FrameCount</i> parameter value must be less than or equal to the frame count specified in <b>GetOutputDataPointer</b>. The endpoint must not
     *     assume that all data requested by <b>GetOutputDataPointer</b> was actually generated.
     * 
     * This method can be called from a real-time processing thread. The
     *     implementation of this method must not block, access
     *     paged memory, or call any blocking system routines.
     * 
     * The Remote Desktop Services AudioEndpoint API is for use in Remote Desktop scenarios; it is not for client applications.
     * @param {Pointer<APO_CONNECTION_PROPERTY>} pConnectionProperty A pointer to an  <a href="https://docs.microsoft.com/windows/desktop/api/audioapotypes/ns-audioapotypes-apo_connection_property">APO_CONNECTION_PROPERTY</a> structure. The values in the structure must not be changed. The caller sets the members as follows:
     * 
     * <ul>
     * <li><b>pBuffer</b> is set to the pointer to the output data buffer returned by the <a href="https://docs.microsoft.com/windows/desktop/api/audioengineendpoint/nf-audioengineendpoint-iaudiooutputendpointrt-getoutputdatapointer">IAudioOutputEndpointRT::GetOutputDataPointer</a> method.</li>
     * <li><b>u32ValidFrameCount</b> is set to the actual number of frames that have been generated by the audio engine. The value might not be the same as the frame count passed in the <i>u32FrameCount</i> parameter of the <a href="https://docs.microsoft.com/windows/desktop/api/audioengineendpoint/nf-audioengineendpoint-iaudiooutputendpointrt-getoutputdatapointer">GetOutputDataPointer</a> method.</li>
     * <li><b>u32BufferFlags</b> is set to <b>BUFFER_VALID</b> if the output buffer pointed to by the <b>pBuffer</b> member contains valid data. <b>u32BufferFlags</b> is set to <b>BUFFER_SILENT</b> if the output buffer contains only silent data. The data in the buffer does not actually need to be silence, but the buffer specified in the <b>pBuffer</b> member must be capable of holding all the frames of silence contained in the  <b>u32ValidFrameCount</b> member. 
     * Therefore, if <b>BUFFER_SILENT</b> is specified, the endpoint should write silence in the
     *     output buffer.</li>
     * </ul>
     * @returns {String} Nothing - always returns an empty string
     * @see https://learn.microsoft.com/windows/win32/api/audioengineendpoint/nf-audioengineendpoint-iaudiooutputendpointrt-releaseoutputdatapointer
     */
    ReleaseOutputDataPointer(pConnectionProperty) {
        ComCall(4, this, APO_CONNECTION_PROPERTY.Ptr, pConnectionProperty)
    }

    /**
     * Is reserved. (IAudioOutputEndpointRT.PulseEndpoint)
     * @remarks
     * This method can be called from a real-time processing thread. The
     *     implementation of this method must not block, access paged memory, or call any blocking system routines.
     * 
     * The Remote Desktop Services AudioEndpoint API is for use in Remote Desktop scenarios; it is not for client applications.
     * @returns {String} Nothing - always returns an empty string
     * @see https://learn.microsoft.com/windows/win32/api/audioengineendpoint/nf-audioengineendpoint-iaudiooutputendpointrt-pulseendpoint
     */
    PulseEndpoint() {
        ComCall(5, this)
    }

    Query(iid) {
        if (IAudioOutputEndpointRT.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.GetOutputDataPointer := CallbackCreate(GetMethod(implObj, "GetOutputDataPointer"), flags, 3)
        this.vtbl.ReleaseOutputDataPointer := CallbackCreate(GetMethod(implObj, "ReleaseOutputDataPointer"), flags, 2)
        this.vtbl.PulseEndpoint := CallbackCreate(GetMethod(implObj, "PulseEndpoint"), flags, 1)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.GetOutputDataPointer)
        CallbackFree(this.vtbl.ReleaseOutputDataPointer)
        CallbackFree(this.vtbl.PulseEndpoint)
    }
}
