#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ACTIVATEFLAGS.ahk" {ACTIVATEFLAGS}
#Import export ".\ACTIVEOBJECT_FLAGS.ahk" {ACTIVEOBJECT_FLAGS}
#Import export ".\ARRAYDESC.ahk" {ARRAYDESC}
#Import export ".\Apis.ahk" {*}
#Import export ".\BINDSPEED.ahk" {BINDSPEED}
#Import export ".\BUSY_DIALOG_FLAGS.ahk" {BUSY_DIALOG_FLAGS}
#Import export ".\CADWORD.ahk" {CADWORD}
#Import export ".\CALPOLESTR.ahk" {CALPOLESTR}
#Import export ".\CAUUID.ahk" {CAUUID}
#Import export ".\CHANGEKIND.ahk" {CHANGEKIND}
#Import export ".\CHANGE_ICON_FLAGS.ahk" {CHANGE_ICON_FLAGS}
#Import export ".\CHANGE_SOURCE_FLAGS.ahk" {CHANGE_SOURCE_FLAGS}
#Import export ".\CLEANLOCALSTORAGE.ahk" {CLEANLOCALSTORAGE}
#Import export ".\CLIPBOARD_FORMAT.ahk" {CLIPBOARD_FORMAT}
#Import export ".\CONTROLINFO.ahk" {CONTROLINFO}
#Import export ".\CTRLINFO.ahk" {CTRLINFO}
#Import export ".\Constants.ahk" {*}
#Import export ".\DISCARDCACHE.ahk" {DISCARDCACHE}
#Import export ".\DOCMISC.ahk" {DOCMISC}
#Import export ".\DROPEFFECT.ahk" {DROPEFFECT}
#Import export ".\DVASPECTINFO.ahk" {DVASPECTINFO}
#Import export ".\DVASPECTINFOFLAG.ahk" {DVASPECTINFOFLAG}
#Import export ".\DVEXTENTINFO.ahk" {DVEXTENTINFO}
#Import export ".\DVEXTENTMODE.ahk" {DVEXTENTMODE}
#Import export ".\EDIT_LINKS_FLAGS.ahk" {EDIT_LINKS_FLAGS}
#Import export ".\EMBDHLP_FLAGS.ahk" {EMBDHLP_FLAGS}
#Import export ".\ENUM_CONTROLS_WHICH_FLAGS.ahk" {ENUM_CONTROLS_WHICH_FLAGS}
#Import export ".\FDEX_PROP_FLAGS.ahk" {FDEX_PROP_FLAGS}
#Import export ".\FONTDESC.ahk" {FONTDESC}
#Import export ".\GUIDKIND.ahk" {GUIDKIND}
#Import export ".\HITRESULT.ahk" {HITRESULT}
#Import export ".\IAdviseSinkEx.ahk" {IAdviseSinkEx}
#Import export ".\ICanHandleException.ahk" {ICanHandleException}
#Import export ".\IClassFactory2.ahk" {IClassFactory2}
#Import export ".\IContinue.ahk" {IContinue}
#Import export ".\IContinueCallback.ahk" {IContinueCallback}
#Import export ".\ICreateErrorInfo.ahk" {ICreateErrorInfo}
#Import export ".\ICreateTypeInfo.ahk" {ICreateTypeInfo}
#Import export ".\ICreateTypeInfo2.ahk" {ICreateTypeInfo2}
#Import export ".\ICreateTypeLib.ahk" {ICreateTypeLib}
#Import export ".\ICreateTypeLib2.ahk" {ICreateTypeLib2}
#Import export ".\IDispError.ahk" {IDispError}
#Import export ".\IDispatchEx.ahk" {IDispatchEx}
#Import export ".\IDropSource.ahk" {IDropSource}
#Import export ".\IDropSourceNotify.ahk" {IDropSourceNotify}
#Import export ".\IDropTarget.ahk" {IDropTarget}
#Import export ".\IEnterpriseDropTarget.ahk" {IEnterpriseDropTarget}
#Import export ".\IEnumOLEVERB.ahk" {IEnumOLEVERB}
#Import export ".\IEnumOleDocumentViews.ahk" {IEnumOleDocumentViews}
#Import export ".\IEnumOleUndoUnits.ahk" {IEnumOleUndoUnits}
#Import export ".\IEnumVARIANT.ahk" {IEnumVARIANT}
#Import export ".\IFont.ahk" {IFont}
#Import export ".\IFontDisp.ahk" {IFontDisp}
#Import export ".\IFontEventsDisp.ahk" {IFontEventsDisp}
#Import export ".\IGNOREMIME.ahk" {IGNOREMIME}
#Import export ".\IGetOleObject.ahk" {IGetOleObject}
#Import export ".\IGetVBAObject.ahk" {IGetVBAObject}
#Import export ".\INSERT_OBJECT_FLAGS.ahk" {INSERT_OBJECT_FLAGS}
#Import export ".\INTERFACEDATA.ahk" {INTERFACEDATA}
#Import export ".\IObjectIdentity.ahk" {IObjectIdentity}
#Import export ".\IObjectWithSite.ahk" {IObjectWithSite}
#Import export ".\IOleAdviseHolder.ahk" {IOleAdviseHolder}
#Import export ".\IOleCache.ahk" {IOleCache}
#Import export ".\IOleCache2.ahk" {IOleCache2}
#Import export ".\IOleCacheControl.ahk" {IOleCacheControl}
#Import export ".\IOleClientSite.ahk" {IOleClientSite}
#Import export ".\IOleCommandTarget.ahk" {IOleCommandTarget}
#Import export ".\IOleContainer.ahk" {IOleContainer}
#Import export ".\IOleControl.ahk" {IOleControl}
#Import export ".\IOleControlSite.ahk" {IOleControlSite}
#Import export ".\IOleDocument.ahk" {IOleDocument}
#Import export ".\IOleDocumentSite.ahk" {IOleDocumentSite}
#Import export ".\IOleDocumentView.ahk" {IOleDocumentView}
#Import export ".\IOleInPlaceActiveObject.ahk" {IOleInPlaceActiveObject}
#Import export ".\IOleInPlaceFrame.ahk" {IOleInPlaceFrame}
#Import export ".\IOleInPlaceObject.ahk" {IOleInPlaceObject}
#Import export ".\IOleInPlaceObjectWindowless.ahk" {IOleInPlaceObjectWindowless}
#Import export ".\IOleInPlaceSite.ahk" {IOleInPlaceSite}
#Import export ".\IOleInPlaceSiteEx.ahk" {IOleInPlaceSiteEx}
#Import export ".\IOleInPlaceSiteWindowless.ahk" {IOleInPlaceSiteWindowless}
#Import export ".\IOleInPlaceUIWindow.ahk" {IOleInPlaceUIWindow}
#Import export ".\IOleItemContainer.ahk" {IOleItemContainer}
#Import export ".\IOleLink.ahk" {IOleLink}
#Import export ".\IOleObject.ahk" {IOleObject}
#Import export ".\IOleParentUndoUnit.ahk" {IOleParentUndoUnit}
#Import export ".\IOleUILinkContainerA.ahk" {IOleUILinkContainerA}
#Import export ".\IOleUILinkContainerW.ahk" {IOleUILinkContainerW}
#Import export ".\IOleUILinkInfoA.ahk" {IOleUILinkInfoA}
#Import export ".\IOleUILinkInfoW.ahk" {IOleUILinkInfoW}
#Import export ".\IOleUIObjInfoA.ahk" {IOleUIObjInfoA}
#Import export ".\IOleUIObjInfoW.ahk" {IOleUIObjInfoW}
#Import export ".\IOleUndoManager.ahk" {IOleUndoManager}
#Import export ".\IOleUndoUnit.ahk" {IOleUndoUnit}
#Import export ".\IOleWindow.ahk" {IOleWindow}
#Import export ".\IParseDisplayName.ahk" {IParseDisplayName}
#Import export ".\IPerPropertyBrowsing.ahk" {IPerPropertyBrowsing}
#Import export ".\IPersistPropertyBag.ahk" {IPersistPropertyBag}
#Import export ".\IPersistPropertyBag2.ahk" {IPersistPropertyBag2}
#Import export ".\IPicture.ahk" {IPicture}
#Import export ".\IPicture2.ahk" {IPicture2}
#Import export ".\IPictureDisp.ahk" {IPictureDisp}
#Import export ".\IPointerInactive.ahk" {IPointerInactive}
#Import export ".\IPrint.ahk" {IPrint}
#Import export ".\IPropertyNotifySink.ahk" {IPropertyNotifySink}
#Import export ".\IPropertyPage.ahk" {IPropertyPage}
#Import export ".\IPropertyPage2.ahk" {IPropertyPage2}
#Import export ".\IPropertyPageSite.ahk" {IPropertyPageSite}
#Import export ".\IProtectFocus.ahk" {IProtectFocus}
#Import export ".\IProtectedModeMenuServices.ahk" {IProtectedModeMenuServices}
#Import export ".\IProvideClassInfo.ahk" {IProvideClassInfo}
#Import export ".\IProvideClassInfo2.ahk" {IProvideClassInfo2}
#Import export ".\IProvideMultipleClassInfo.ahk" {IProvideMultipleClassInfo}
#Import export ".\IProvideRuntimeContext.ahk" {IProvideRuntimeContext}
#Import export ".\IQuickActivate.ahk" {IQuickActivate}
#Import export ".\IRecordInfo.ahk" {IRecordInfo}
#Import export ".\ISimpleFrameSite.ahk" {ISimpleFrameSite}
#Import export ".\ISpecifyPropertyPages.ahk" {ISpecifyPropertyPages}
#Import export ".\ITypeChangeEvents.ahk" {ITypeChangeEvents}
#Import export ".\ITypeFactory.ahk" {ITypeFactory}
#Import export ".\ITypeMarshal.ahk" {ITypeMarshal}
#Import export ".\IVBFormat.ahk" {IVBFormat}
#Import export ".\IVBGetControl.ahk" {IVBGetControl}
#Import export ".\IVariantChangeType.ahk" {IVariantChangeType}
#Import export ".\IViewObject.ahk" {IViewObject}
#Import export ".\IViewObject2.ahk" {IViewObject2}
#Import export ".\IViewObjectEx.ahk" {IViewObjectEx}
#Import export ".\IZoomEvents.ahk" {IZoomEvents}
#Import export ".\KEYMODIFIERS.ahk" {KEYMODIFIERS}
#Import export ".\LIBFLAGS.ahk" {LIBFLAGS}
#Import export ".\LICINFO.ahk" {LICINFO}
#Import export ".\LOAD_PICTURE_FLAGS.ahk" {LOAD_PICTURE_FLAGS}
#Import export ".\LPFNOLEUIHOOK.ahk" {LPFNOLEUIHOOK}
#Import export ".\MEDIAPLAYBACK_STATE.ahk" {MEDIAPLAYBACK_STATE}
#Import export ".\METHODDATA.ahk" {METHODDATA}
#Import export ".\MULTICLASSINFO_FLAGS.ahk" {MULTICLASSINFO_FLAGS}
#Import export ".\NUMPARSE.ahk" {NUMPARSE}
#Import export ".\NUMPARSE_FLAGS.ahk" {NUMPARSE_FLAGS}
#Import export ".\OBJECTDESCRIPTOR.ahk" {OBJECTDESCRIPTOR}
#Import export ".\OBJECT_PROPERTIES_FLAGS.ahk" {OBJECT_PROPERTIES_FLAGS}
#Import export ".\OCPFIPARAMS.ahk" {OCPFIPARAMS}
#Import export ".\OLECLOSE.ahk" {OLECLOSE}
#Import export ".\OLECMD.ahk" {OLECMD}
#Import export ".\OLECMDEXECOPT.ahk" {OLECMDEXECOPT}
#Import export ".\OLECMDF.ahk" {OLECMDF}
#Import export ".\OLECMDID.ahk" {OLECMDID}
#Import export ".\OLECMDID_BROWSERSTATEFLAG.ahk" {OLECMDID_BROWSERSTATEFLAG}
#Import export ".\OLECMDID_OPTICAL_ZOOMFLAG.ahk" {OLECMDID_OPTICAL_ZOOMFLAG}
#Import export ".\OLECMDID_PAGEACTIONFLAG.ahk" {OLECMDID_PAGEACTIONFLAG}
#Import export ".\OLECMDID_REFRESHFLAG.ahk" {OLECMDID_REFRESHFLAG}
#Import export ".\OLECMDID_VIEWPORT_MODE_FLAG.ahk" {OLECMDID_VIEWPORT_MODE_FLAG}
#Import export ".\OLECMDID_WINDOWSTATE_FLAG.ahk" {OLECMDID_WINDOWSTATE_FLAG}
#Import export ".\OLECMDTEXT.ahk" {OLECMDTEXT}
#Import export ".\OLECMDTEXTF.ahk" {OLECMDTEXTF}
#Import export ".\OLECONTF.ahk" {OLECONTF}
#Import export ".\OLECREATE.ahk" {OLECREATE}
#Import export ".\OLEDCFLAGS.ahk" {OLEDCFLAGS}
#Import export ".\OLEGETMONIKER.ahk" {OLEGETMONIKER}
#Import export ".\OLEINPLACEFRAMEINFO.ahk" {OLEINPLACEFRAMEINFO}
#Import export ".\OLEIVERB.ahk" {OLEIVERB}
#Import export ".\OLELINKBIND.ahk" {OLELINKBIND}
#Import export ".\OLEMENUGROUPWIDTHS.ahk" {OLEMENUGROUPWIDTHS}
#Import export ".\OLEMISC.ahk" {OLEMISC}
#Import export ".\OLERENDER.ahk" {OLERENDER}
#Import export ".\OLESTREAMQUERYCONVERTOLELINKCALLBACK.ahk" {OLESTREAMQUERYCONVERTOLELINKCALLBACK}
#Import export ".\OLEUIBUSYA.ahk" {OLEUIBUSYA}
#Import export ".\OLEUIBUSYW.ahk" {OLEUIBUSYW}
#Import export ".\OLEUICHANGEICONA.ahk" {OLEUICHANGEICONA}
#Import export ".\OLEUICHANGEICONW.ahk" {OLEUICHANGEICONW}
#Import export ".\OLEUICHANGESOURCEA.ahk" {OLEUICHANGESOURCEA}
#Import export ".\OLEUICHANGESOURCEW.ahk" {OLEUICHANGESOURCEW}
#Import export ".\OLEUICONVERTA.ahk" {OLEUICONVERTA}
#Import export ".\OLEUICONVERTW.ahk" {OLEUICONVERTW}
#Import export ".\OLEUIEDITLINKSA.ahk" {OLEUIEDITLINKSA}
#Import export ".\OLEUIEDITLINKSW.ahk" {OLEUIEDITLINKSW}
#Import export ".\OLEUIGNRLPROPSA.ahk" {OLEUIGNRLPROPSA}
#Import export ".\OLEUIGNRLPROPSW.ahk" {OLEUIGNRLPROPSW}
#Import export ".\OLEUIINSERTOBJECTA.ahk" {OLEUIINSERTOBJECTA}
#Import export ".\OLEUIINSERTOBJECTW.ahk" {OLEUIINSERTOBJECTW}
#Import export ".\OLEUILINKPROPSA.ahk" {OLEUILINKPROPSA}
#Import export ".\OLEUILINKPROPSW.ahk" {OLEUILINKPROPSW}
#Import export ".\OLEUIOBJECTPROPSA.ahk" {OLEUIOBJECTPROPSA}
#Import export ".\OLEUIOBJECTPROPSW.ahk" {OLEUIOBJECTPROPSW}
#Import export ".\OLEUIPASTEENTRYA.ahk" {OLEUIPASTEENTRYA}
#Import export ".\OLEUIPASTEENTRYW.ahk" {OLEUIPASTEENTRYW}
#Import export ".\OLEUIPASTEFLAG.ahk" {OLEUIPASTEFLAG}
#Import export ".\OLEUIPASTESPECIALA.ahk" {OLEUIPASTESPECIALA}
#Import export ".\OLEUIPASTESPECIALW.ahk" {OLEUIPASTESPECIALW}
#Import export ".\OLEUIVIEWPROPSA.ahk" {OLEUIVIEWPROPSA}
#Import export ".\OLEUIVIEWPROPSW.ahk" {OLEUIVIEWPROPSW}
#Import export ".\OLEUPDATE.ahk" {OLEUPDATE}
#Import export ".\OLEVERB.ahk" {OLEVERB}
#Import export ".\OLEVERBATTRIB.ahk" {OLEVERBATTRIB}
#Import export ".\OLEWHICHMK.ahk" {OLEWHICHMK}
#Import export ".\OLE_HANDLE.ahk" {OLE_HANDLE}
#Import export ".\OLE_TRISTATE.ahk" {OLE_TRISTATE}
#Import export ".\PAGEACTION_UI.ahk" {PAGEACTION_UI}
#Import export ".\PAGERANGE.ahk" {PAGERANGE}
#Import export ".\PAGESET.ahk" {PAGESET}
#Import export ".\PARAMDATA.ahk" {PARAMDATA}
#Import export ".\PARAMDESC.ahk" {PARAMDESC}
#Import export ".\PARAMDESCEX.ahk" {PARAMDESCEX}
#Import export ".\PARAMFLAGS.ahk" {PARAMFLAGS}
#Import export ".\PASTE_SPECIAL_FLAGS.ahk" {PASTE_SPECIAL_FLAGS}
#Import export ".\PICTDESC.ahk" {PICTDESC}
#Import export ".\PICTUREATTRIBUTES.ahk" {PICTUREATTRIBUTES}
#Import export ".\PICTYPE.ahk" {PICTYPE}
#Import export ".\POINTERINACTIVE.ahk" {POINTERINACTIVE}
#Import export ".\POINTF.ahk" {POINTF}
#Import export ".\PRINTFLAG.ahk" {PRINTFLAG}
#Import export ".\PROPBAG2_TYPE.ahk" {PROPBAG2_TYPE}
#Import export ".\PROPPAGEINFO.ahk" {PROPPAGEINFO}
#Import export ".\PROPPAGESTATUS.ahk" {PROPPAGESTATUS}
#Import export ".\QACONTAINER.ahk" {QACONTAINER}
#Import export ".\QACONTAINERFLAGS.ahk" {QACONTAINERFLAGS}
#Import export ".\QACONTROL.ahk" {QACONTROL}
#Import export ".\READYSTATE.ahk" {READYSTATE}
#Import export ".\REGKIND.ahk" {REGKIND}
#Import export ".\SAFEARRAYUNION.ahk" {SAFEARRAYUNION}
#Import export ".\SAFEARR_BRECORD.ahk" {SAFEARR_BRECORD}
#Import export ".\SAFEARR_BSTR.ahk" {SAFEARR_BSTR}
#Import export ".\SAFEARR_DISPATCH.ahk" {SAFEARR_DISPATCH}
#Import export ".\SAFEARR_HAVEIID.ahk" {SAFEARR_HAVEIID}
#Import export ".\SAFEARR_UNKNOWN.ahk" {SAFEARR_UNKNOWN}
#Import export ".\SAFEARR_VARIANT.ahk" {SAFEARR_VARIANT}
#Import export ".\SF_TYPE.ahk" {SF_TYPE}
#Import export ".\TYPEFLAGS.ahk" {TYPEFLAGS}
#Import export ".\UASFLAGS.ahk" {UASFLAGS}
#Import export ".\UDATE.ahk" {UDATE}
#Import export ".\UI_CONVERT_FLAGS.ahk" {UI_CONVERT_FLAGS}
#Import export ".\UPDFCACHE_FLAGS.ahk" {UPDFCACHE_FLAGS}
#Import export ".\USERCLASSTYPE.ahk" {USERCLASSTYPE}
#Import export ".\VARCMP.ahk" {VARCMP}
#Import export ".\VARFORMAT_FIRST_DAY.ahk" {VARFORMAT_FIRST_DAY}
#Import export ".\VARFORMAT_FIRST_WEEK.ahk" {VARFORMAT_FIRST_WEEK}
#Import export ".\VARFORMAT_GROUP.ahk" {VARFORMAT_GROUP}
#Import export ".\VARFORMAT_LEADING_DIGIT.ahk" {VARFORMAT_LEADING_DIGIT}
#Import export ".\VARFORMAT_NAMED_FORMAT.ahk" {VARFORMAT_NAMED_FORMAT}
#Import export ".\VARFORMAT_PARENTHESES.ahk" {VARFORMAT_PARENTHESES}
#Import export ".\VIEWSTATUS.ahk" {VIEWSTATUS}
#Import export ".\VIEW_OBJECT_PROPERTIES_FLAGS.ahk" {VIEW_OBJECT_PROPERTIES_FLAGS}
#Import export ".\WPCSETTING.ahk" {WPCSETTING}
#Import export ".\XFORMCOORDS.ahk" {XFORMCOORDS}
#Import export ".\_wireBRECORD.ahk" {_wireBRECORD}
#Import export ".\_wireSAFEARRAY.ahk" {_wireSAFEARRAY}
#Import export ".\_wireVARIANT.ahk" {_wireVARIANT}
