#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\Com\IUnknown.ahk

/**
 * Enables objects and their containers to dispatch commands to each other. For example, an object's toolbars may contain buttons for commands such as Print, Print Preview, Save, New, and Zoom.
 * @see https://docs.microsoft.com/windows/win32/api//docobj/nn-docobj-iolecommandtarget
 * @namespace Windows.Win32.System.Ole
 * @version v4.0.30319
 */
class IOleCommandTarget extends IUnknown{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IOleCommandTarget
     * @type {Guid}
     */
    static IID => Guid("{b722bccb-4e68-101b-a2bc-00aa00404770}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 3

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["QueryStatus", "Exec"]

    /**
     * Queries the object for the status of one or more commands generated by user interface events.
     * @param {Pointer<Guid>} pguidCmdGroup The unique identifier of the command group; can be <b>NULL</b> to specify the standard group. All the commands that are passed in the <i>prgCmds</i> array must belong to the group specified by <i>pguidCmdGroup</i>.
     * @param {Integer} cCmds The number of commands in the <i>prgCmds</i> array.
     * @param {Pointer<OLECMD>} prgCmds A caller-allocated array of <a href="https://docs.microsoft.com/windows/desktop/api/docobj/ns-docobj-olecmd">OLECMD</a> structures that indicate the commands for which the caller needs status information. This method fills the <b>cmdf</b> member of each structure with values taken from the <a href="https://docs.microsoft.com/windows/desktop/api/docobj/ne-docobj-olecmdf">OLECMDF</a> enumeration.
     * @param {Pointer<OLECMDTEXT>} pCmdText A pointer to an <a href="https://docs.microsoft.com/windows/desktop/api/docobj/ns-docobj-olecmdtext">OLECMDTEXT</a> structure in which to return name and/or status information of a single command. This parameter can be <b>NULL</b> to indicate that the caller does not need this information.
     * @returns {HRESULT} This method returns S_OK on success. Other possible return values include the following.
     * 
     * <table>
     * <tr>
     * <th>Return code</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_FAIL</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The operation failed.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_UNEXPECTED</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * An unexpected error has occurred.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_POINTER</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The <i>prgCmds</i> argument is <b>NULL</b>.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>OLECMDERR_E_UNKNOWNGROUP</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The <i>pguidCmdGroup</i> parameter is not <b>NULL</b> but does not specify a recognized command group.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://docs.microsoft.com/windows/win32/api//docobj/nf-docobj-iolecommandtarget-querystatus
     */
    QueryStatus(pguidCmdGroup, cCmds, prgCmds, pCmdText) {
        result := ComCall(3, this, "ptr", pguidCmdGroup, "uint", cCmds, "ptr", prgCmds, "ptr", pCmdText, "HRESULT")
        return result
    }

    /**
     * Executes the specified command or displays help for the command.
     * @param {Pointer<Guid>} pguidCmdGroup The unique identifier of the command group; can be <b>NULL</b> to specify the standard group.
     * @param {Integer} nCmdID The command to be executed. This command must belong to the group specified with <i>pguidCmdGroup</i>.
     * @param {Integer} nCmdexecopt Specifies how the object should execute the command. Possible values are taken from the <a href="https://docs.microsoft.com/windows/desktop/api/docobj/ne-docobj-olecmdexecopt">OLECMDEXECOPT</a> and <a href="https://docs.microsoft.com/windows/desktop/api/docobj/ne-docobj-olecmdid_windowstate_flag">OLECMDID_WINDOWSTATE_FLAG</a> enumerations.
     * @param {Pointer<VARIANT>} pvaIn A pointer to a <a href="https://docs.microsoft.com/windows/win32/api/oaidl/ns-oaidl-variant">VARIANTARG</a> structure containing input arguments. This parameter can be <b>NULL</b>.
     * @param {Pointer<VARIANT>} pvaOut Pointer to a VARIANTARG structure to receive command output. This parameter can be <b>NULL</b>.
     * @returns {HRESULT} This method returns S_OK on success. Other possible return values include the following.
     * 
     * <table>
     * <tr>
     * <th>Return code</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>OLECMDERR_E_UNKNOWNGROUP</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The <i>pguidCmdGroup</i> parameter is not <b>NULL</b> but does not specify a recognized command group.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>OLECMDERR_E_NOTSUPPORTED</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The <i>nCmdID</i> parameter is not a valid command in the group identified by <i>pguidCmdGroup</i>.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>OLECMDERR_E_DISABLED</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The command identified by <i>nCmdID</i> is currently disabled and cannot be executed.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>OLECMDERR_E_NOHELP</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The caller has asked for help on the command identified by <i>nCmdID</i>, but no help is available.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>OLECMDERR_E_CANCELED</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The user canceled the execution of the command.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://docs.microsoft.com/windows/win32/api//docobj/nf-docobj-iolecommandtarget-exec
     */
    Exec(pguidCmdGroup, nCmdID, nCmdexecopt, pvaIn, pvaOut) {
        result := ComCall(4, this, "ptr", pguidCmdGroup, "uint", nCmdID, "uint", nCmdexecopt, "ptr", pvaIn, "ptr", pvaOut, "HRESULT")
        return result
    }
}
