#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32Struct.ahk

/**
 * Indicates the number of menu items in each of the six menu groups of a menu shared between a container and an object server during an in-place editing session. This is the mechanism for building a shared menu.
 * @remarks
 * 
 * A container application and an object server use this structure to build a shared menu. The object server initializes to zeros the array elements in an <b>OLEMENUGROUPWIDTHS</b> structure and passes a pointer to it along with a menu handle to the container in a call to <a href="https://docs.microsoft.com/windows/desktop/api/oleidl/nf-oleidl-ioleinplaceframe-insertmenus">IOleInPlaceFrame::InsertMenus</a>. The container adds its menu items to the menu, and fills in the structure with the number of items in each of its groups (indexes 0, 2, and 4). The server then uses the group width values returned by the container to insert its menu items in the appropriate position in the menu. The server fills in the structure with the number of items in each of its groups (indexes 1, 3, and 5), and then passes the structure to OLE in a call to the <a href="https://docs.microsoft.com/windows/desktop/api/ole2/nf-ole2-olecreatemenudescriptor">OleCreateMenuDescriptor</a> function. This enables OLE to intercept the container's menu messages and redirect the messages generated by the server's menus.
 * 
 * 
 * @see https://docs.microsoft.com/windows/win32/api//oleidl/ns-oleidl-olemenugroupwidths
 * @namespace Windows.Win32.System.Ole
 * @version v4.0.30319
 */
class OLEMENUGROUPWIDTHS extends Win32Struct
{
    static sizeof => 24

    static packingSize => 4

    /**
     * An array whose elements contain the number of menu items in each of the six menu groups of a shared in-place editing menu. Each menu group can have any number of menu items. The container uses elements 0, 2, and 4 to indicate the number of menu items in its <b>File</b>, <b>View</b>, and <b>Window</b> menu groups. The object server uses elements 1, 3, and 5 to indicate the number of menu items in its <b>Edit</b>, <b>Object</b>, and <b>Help</b> menu groups.
     * @type {Array<Int32>}
     */
    width{
        get {
            if(!this.HasProp("__widthProxyArray"))
                this.__widthProxyArray := Win32FixedArray(this.ptr + 0, 6, Primitive, "int")
            return this.__widthProxyArray
        }
    }
}
