#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\AsyncIBackgroundCopyCallback.ahk" {AsyncIBackgroundCopyCallback}
#Import export ".\BG_AUTH_CREDENTIALS.ahk" {BG_AUTH_CREDENTIALS}
#Import export ".\BG_AUTH_CREDENTIALS_UNION.ahk" {BG_AUTH_CREDENTIALS_UNION}
#Import export ".\BG_AUTH_SCHEME.ahk" {BG_AUTH_SCHEME}
#Import export ".\BG_AUTH_TARGET.ahk" {BG_AUTH_TARGET}
#Import export ".\BG_BASIC_CREDENTIALS.ahk" {BG_BASIC_CREDENTIALS}
#Import export ".\BG_CERT_STORE_LOCATION.ahk" {BG_CERT_STORE_LOCATION}
#Import export ".\BG_ERROR_CONTEXT.ahk" {BG_ERROR_CONTEXT}
#Import export ".\BG_FILE_INFO.ahk" {BG_FILE_INFO}
#Import export ".\BG_FILE_PROGRESS.ahk" {BG_FILE_PROGRESS}
#Import export ".\BG_FILE_RANGE.ahk" {BG_FILE_RANGE}
#Import export ".\BG_JOB_PRIORITY.ahk" {BG_JOB_PRIORITY}
#Import export ".\BG_JOB_PROGRESS.ahk" {BG_JOB_PROGRESS}
#Import export ".\BG_JOB_PROXY_USAGE.ahk" {BG_JOB_PROXY_USAGE}
#Import export ".\BG_JOB_REPLY_PROGRESS.ahk" {BG_JOB_REPLY_PROGRESS}
#Import export ".\BG_JOB_STATE.ahk" {BG_JOB_STATE}
#Import export ".\BG_JOB_TIMES.ahk" {BG_JOB_TIMES}
#Import export ".\BG_JOB_TYPE.ahk" {BG_JOB_TYPE}
#Import export ".\BG_TOKEN.ahk" {BG_TOKEN}
#Import export ".\BITSExtensionSetupFactory.ahk" {BITSExtensionSetupFactory}
#Import export ".\BITS_FILE_PROPERTY_ID.ahk" {BITS_FILE_PROPERTY_ID}
#Import export ".\BITS_FILE_PROPERTY_VALUE.ahk" {BITS_FILE_PROPERTY_VALUE}
#Import export ".\BITS_JOB_PROPERTY_ID.ahk" {BITS_JOB_PROPERTY_ID}
#Import export ".\BITS_JOB_PROPERTY_VALUE.ahk" {BITS_JOB_PROPERTY_VALUE}
#Import export ".\BITS_JOB_TRANSFER_POLICY.ahk" {BITS_JOB_TRANSFER_POLICY}
#Import export ".\BackgroundCopyManager.ahk" {BackgroundCopyManager}
#Import export ".\BackgroundCopyManager10_1.ahk" {BackgroundCopyManager10_1}
#Import export ".\BackgroundCopyManager10_2.ahk" {BackgroundCopyManager10_2}
#Import export ".\BackgroundCopyManager10_3.ahk" {BackgroundCopyManager10_3}
#Import export ".\BackgroundCopyManager1_5.ahk" {BackgroundCopyManager1_5}
#Import export ".\BackgroundCopyManager2_0.ahk" {BackgroundCopyManager2_0}
#Import export ".\BackgroundCopyManager2_5.ahk" {BackgroundCopyManager2_5}
#Import export ".\BackgroundCopyManager3_0.ahk" {BackgroundCopyManager3_0}
#Import export ".\BackgroundCopyManager4_0.ahk" {BackgroundCopyManager4_0}
#Import export ".\BackgroundCopyManager5_0.ahk" {BackgroundCopyManager5_0}
#Import export ".\BackgroundCopyQMgr.ahk" {BackgroundCopyQMgr}
#Import export ".\Constants.ahk" {*}
#Import export ".\FILESETINFO.ahk" {FILESETINFO}
#Import export ".\GROUPPROP.ahk" {GROUPPROP}
#Import export ".\IBITSExtensionSetup.ahk" {IBITSExtensionSetup}
#Import export ".\IBITSExtensionSetupFactory.ahk" {IBITSExtensionSetupFactory}
#Import export ".\IBackgroundCopyCallback.ahk" {IBackgroundCopyCallback}
#Import export ".\IBackgroundCopyCallback1.ahk" {IBackgroundCopyCallback1}
#Import export ".\IBackgroundCopyCallback2.ahk" {IBackgroundCopyCallback2}
#Import export ".\IBackgroundCopyCallback3.ahk" {IBackgroundCopyCallback3}
#Import export ".\IBackgroundCopyError.ahk" {IBackgroundCopyError}
#Import export ".\IBackgroundCopyFile.ahk" {IBackgroundCopyFile}
#Import export ".\IBackgroundCopyFile2.ahk" {IBackgroundCopyFile2}
#Import export ".\IBackgroundCopyFile3.ahk" {IBackgroundCopyFile3}
#Import export ".\IBackgroundCopyFile4.ahk" {IBackgroundCopyFile4}
#Import export ".\IBackgroundCopyFile5.ahk" {IBackgroundCopyFile5}
#Import export ".\IBackgroundCopyFile6.ahk" {IBackgroundCopyFile6}
#Import export ".\IBackgroundCopyGroup.ahk" {IBackgroundCopyGroup}
#Import export ".\IBackgroundCopyJob.ahk" {IBackgroundCopyJob}
#Import export ".\IBackgroundCopyJob1.ahk" {IBackgroundCopyJob1}
#Import export ".\IBackgroundCopyJob2.ahk" {IBackgroundCopyJob2}
#Import export ".\IBackgroundCopyJob3.ahk" {IBackgroundCopyJob3}
#Import export ".\IBackgroundCopyJob4.ahk" {IBackgroundCopyJob4}
#Import export ".\IBackgroundCopyJob5.ahk" {IBackgroundCopyJob5}
#Import export ".\IBackgroundCopyJobHttpOptions.ahk" {IBackgroundCopyJobHttpOptions}
#Import export ".\IBackgroundCopyJobHttpOptions2.ahk" {IBackgroundCopyJobHttpOptions2}
#Import export ".\IBackgroundCopyJobHttpOptions3.ahk" {IBackgroundCopyJobHttpOptions3}
#Import export ".\IBackgroundCopyManager.ahk" {IBackgroundCopyManager}
#Import export ".\IBackgroundCopyQMgr.ahk" {IBackgroundCopyQMgr}
#Import export ".\IBackgroundCopyServerCertificateValidationCallback.ahk" {IBackgroundCopyServerCertificateValidationCallback}
#Import export ".\IBitsPeer.ahk" {IBitsPeer}
#Import export ".\IBitsPeerCacheAdministration.ahk" {IBitsPeerCacheAdministration}
#Import export ".\IBitsPeerCacheRecord.ahk" {IBitsPeerCacheRecord}
#Import export ".\IBitsTokenOptions.ahk" {IBitsTokenOptions}
#Import export ".\IEnumBackgroundCopyFiles.ahk" {IEnumBackgroundCopyFiles}
#Import export ".\IEnumBackgroundCopyGroups.ahk" {IEnumBackgroundCopyGroups}
#Import export ".\IEnumBackgroundCopyJobs.ahk" {IEnumBackgroundCopyJobs}
#Import export ".\IEnumBackgroundCopyJobs1.ahk" {IEnumBackgroundCopyJobs1}
#Import export ".\IEnumBitsPeerCacheRecords.ahk" {IEnumBitsPeerCacheRecords}
#Import export ".\IEnumBitsPeers.ahk" {IEnumBitsPeers}
