#Requires AutoHotkey v2.0 64-bit

#Include ..\..\Win32\System\WinRT\Apis.ahk
#Include ..\..\Win32\System\WinRT\HSTRING.ahk
#Include ..\..\Win32\System\WinRT\IInspectable.ahk
#Include .\ISpeechSynthesisStream.ahk
#Include ..\..\Storage\Streams\IContentTypeProvider.ahk
#Include ..\..\Storage\Streams\IRandomAccessStream.ahk
#Include ..\..\Storage\Streams\IOutputStream.ahk
#Include ..\..\Foundation\IClosable.ahk
#Include ..\..\Storage\Streams\IInputStream.ahk
#Include ..\Core\ITimedMetadataTrackProvider.ahk
#Include ..\..\..\Guid.ahk

/**
 * Supports reading and writing audio data generated by the speech synthesis engine (voice) to/from a random access stream.
 * @remarks
 * 
 * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream
 * @namespace Windows.Media.SpeechSynthesis
 * @version WindowsRuntime 1.4
 */
class SpeechSynthesisStream extends IInspectable {
;@region Static Properties
    /**
     * The default interface of is Windows Runtime class. At the ABI level, the class is really
     * just a pointer to this interface
     * @type {Class}
     */
    static WinRTDefaultInterface => ISpeechSynthesisStream

    /**
     * The IID of this class's default interface. This allows it to be cast using IUnknown::As like any
     * Windows Runtime interface
     * @type {Guid}
     */
    static IID => ISpeechSynthesisStream.IID

;@endregion Static Properties

;@region Instance Properties
    /**
     * Gets the collection of timeline markers associated with the [SpeechSynthesisStream](speechsynthesisstream.md).
     * 
     * > [!NOTE] 
     * > SpeechSynthesisStream.Markers is deprecated. We recommend using the [MediaPlayerElement](../windows.ui.xaml.controls/mediaplayerelement.md) and [MediaPlaybackItem](../windows.media.playback/mediaplaybackitem.md) objects instead (in conjunction with the [IncludeSentenceBoundaryMetadata](speechsynthesizeroptions_includesentenceboundarymetadata.md) and [IncludeWordBoundaryMetadata](speechsynthesizeroptions_includewordboundarymetadata.md) properties of a [SpeechSynthesizerOptions](speechsynthesizeroptions.md) object).
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.markers
     * @type {IVectorView<IMediaMarker>} 
     */
    Markers {
        get => this.get_Markers()
    }

    /**
     * Gets the MIME type of the content of [SpeechSynthesisStream](speechsynthesisstream.md).
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.contenttype
     * @type {HSTRING} 
     */
    ContentType {
        get => this.get_ContentType()
    }

    /**
     * Gets or sets the size of the [SpeechSynthesisStream](speechsynthesisstream.md).
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.size
     * @type {Integer} 
     */
    Size {
        get => this.get_Size()
        set => this.put_Size(value)
    }

    /**
     * Gets the current position within the [SpeechSynthesisStream](speechsynthesisstream.md).
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.position
     * @type {Integer} 
     */
    Position {
        get => this.get_Position()
    }

    /**
     * Gets whether [SpeechSynthesisStream](speechsynthesisstream.md) can be read from.
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.canread
     * @type {Boolean} 
     */
    CanRead {
        get => this.get_CanRead()
    }

    /**
     * Gets a value that indicates whether [SpeechSynthesisStream](speechsynthesisstream.md) can be written to.
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.canwrite
     * @type {Boolean} 
     */
    CanWrite {
        get => this.get_CanWrite()
    }

    /**
     * Gets the collection of optional word and sentence boundaries in the speech synthesis stream as specified by the [SpeechSynthesizer.Options](speechsynthesizer_options.md) property.
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.timedmetadatatracks
     * @type {IVectorView<TimedMetadataTrack>} 
     */
    TimedMetadataTracks {
        get => this.get_TimedMetadataTracks()
    }

;@endregion Instance Properties

;@region Instance Methods
    __New(ptr) {
        super.__New(ptr)
    }

    __Delete() {
        this.Close()

        super.__Delete()
    }

    /**
     * 
     * @returns {IVectorView<IMediaMarker>} 
     */
    get_Markers() {
        if (!this.HasProp("__ISpeechSynthesisStream")) {
            if ((queryResult := this.QueryInterface(ISpeechSynthesisStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__ISpeechSynthesisStream := ISpeechSynthesisStream(outPtr)
        }

        return this.__ISpeechSynthesisStream.get_Markers()
    }

    /**
     * 
     * @returns {HSTRING} 
     */
    get_ContentType() {
        if (!this.HasProp("__IContentTypeProvider")) {
            if ((queryResult := this.QueryInterface(IContentTypeProvider.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IContentTypeProvider := IContentTypeProvider(outPtr)
        }

        return this.__IContentTypeProvider.get_ContentType()
    }

    /**
     * 
     * @returns {Integer} 
     */
    get_Size() {
        if (!this.HasProp("__IRandomAccessStream")) {
            if ((queryResult := this.QueryInterface(IRandomAccessStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IRandomAccessStream := IRandomAccessStream(outPtr)
        }

        return this.__IRandomAccessStream.get_Size()
    }

    /**
     * 
     * @param {Integer} value 
     * @returns {HRESULT} 
     */
    put_Size(value) {
        if (!this.HasProp("__IRandomAccessStream")) {
            if ((queryResult := this.QueryInterface(IRandomAccessStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IRandomAccessStream := IRandomAccessStream(outPtr)
        }

        return this.__IRandomAccessStream.put_Size(value)
    }

    /**
     * Retrieves an input stream at a specified location in [SpeechSynthesisStream](speechsynthesisstream.md).
     * @param {Integer} position The location in the stream at which to begin.
     * @returns {IInputStream} 
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.getinputstreamat
     */
    GetInputStreamAt(position) {
        if (!this.HasProp("__IRandomAccessStream")) {
            if ((queryResult := this.QueryInterface(IRandomAccessStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IRandomAccessStream := IRandomAccessStream(outPtr)
        }

        return this.__IRandomAccessStream.GetInputStreamAt(position)
    }

    /**
     * Retrieves an output stream at a specified location in [SpeechSynthesisStream](speechsynthesisstream.md).
     * @param {Integer} position The location in the stream at which to begin.
     * @returns {IOutputStream} 
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.getoutputstreamat
     */
    GetOutputStreamAt(position) {
        if (!this.HasProp("__IRandomAccessStream")) {
            if ((queryResult := this.QueryInterface(IRandomAccessStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IRandomAccessStream := IRandomAccessStream(outPtr)
        }

        return this.__IRandomAccessStream.GetOutputStreamAt(position)
    }

    /**
     * 
     * @returns {Integer} 
     */
    get_Position() {
        if (!this.HasProp("__IRandomAccessStream")) {
            if ((queryResult := this.QueryInterface(IRandomAccessStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IRandomAccessStream := IRandomAccessStream(outPtr)
        }

        return this.__IRandomAccessStream.get_Position()
    }

    /**
     * Goes to the specified position within [SpeechSynthesisStream](speechsynthesisstream.md).
     * @param {Integer} position The desired position within the stream.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.seek
     */
    Seek(position) {
        if (!this.HasProp("__IRandomAccessStream")) {
            if ((queryResult := this.QueryInterface(IRandomAccessStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IRandomAccessStream := IRandomAccessStream(outPtr)
        }

        return this.__IRandomAccessStream.Seek(position)
    }

    /**
     * Creates a copy of [SpeechSynthesisStream](speechsynthesisstream.md) that references the same bytes as the original stream.
     * @returns {IRandomAccessStream} 
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.clonestream
     */
    CloneStream() {
        if (!this.HasProp("__IRandomAccessStream")) {
            if ((queryResult := this.QueryInterface(IRandomAccessStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IRandomAccessStream := IRandomAccessStream(outPtr)
        }

        return this.__IRandomAccessStream.CloneStream()
    }

    /**
     * 
     * @returns {Boolean} 
     */
    get_CanRead() {
        if (!this.HasProp("__IRandomAccessStream")) {
            if ((queryResult := this.QueryInterface(IRandomAccessStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IRandomAccessStream := IRandomAccessStream(outPtr)
        }

        return this.__IRandomAccessStream.get_CanRead()
    }

    /**
     * 
     * @returns {Boolean} 
     */
    get_CanWrite() {
        if (!this.HasProp("__IRandomAccessStream")) {
            if ((queryResult := this.QueryInterface(IRandomAccessStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IRandomAccessStream := IRandomAccessStream(outPtr)
        }

        return this.__IRandomAccessStream.get_CanWrite()
    }

    /**
     * Writes data asynchronously in a sequential stream.
     * @param {IBuffer} buffer_ The buffer into which the asynchronous writer operation places the bytes to write.
     * @returns {IAsyncOperationWithProgress<Integer, Integer>} 
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.writeasync
     */
    WriteAsync(buffer_) {
        if (!this.HasProp("__IOutputStream")) {
            if ((queryResult := this.QueryInterface(IOutputStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IOutputStream := IOutputStream(outPtr)
        }

        return this.__IOutputStream.WriteAsync(buffer_)
    }

    /**
     * Flushes data asynchronously in a sequential stream.
     * @returns {IAsyncOperation<Boolean>} 
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.flushasync
     */
    FlushAsync() {
        if (!this.HasProp("__IOutputStream")) {
            if ((queryResult := this.QueryInterface(IOutputStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IOutputStream := IOutputStream(outPtr)
        }

        return this.__IOutputStream.FlushAsync()
    }

    /**
     * Releases system resources that are exposed by [SpeechSynthesisStream](speechsynthesisstream.md).
     * @remarks
     * All outstanding asynchronous operations must complete before calling Close.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.close
     */
    Close() {
        if (!this.HasProp("__IClosable")) {
            if ((queryResult := this.QueryInterface(IClosable.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IClosable := IClosable(outPtr)
        }

        return this.__IClosable.Close()
    }

    /**
     * Reads data asynchronously in a sequential stream.
     * @param {IBuffer} buffer_ The buffer into which the asynchronous read operation places the bytes that are read.
     * @param {Integer} count The number of bytes to read that is less than or equal to the Capacity value.
     * @param {Integer} options Specifies the type of the asynchronous read operation.
     * @returns {IAsyncOperationWithProgress<IBuffer, Integer>} 
     * @see https://learn.microsoft.com/uwp/api/windows.media.speechsynthesis.speechsynthesisstream.readasync
     */
    ReadAsync(buffer_, count, options) {
        if (!this.HasProp("__IInputStream")) {
            if ((queryResult := this.QueryInterface(IInputStream.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IInputStream := IInputStream(outPtr)
        }

        return this.__IInputStream.ReadAsync(buffer_, count, options)
    }

    /**
     * 
     * @returns {IVectorView<TimedMetadataTrack>} 
     */
    get_TimedMetadataTracks() {
        if (!this.HasProp("__ITimedMetadataTrackProvider")) {
            if ((queryResult := this.QueryInterface(ITimedMetadataTrackProvider.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__ITimedMetadataTrackProvider := ITimedMetadataTrackProvider(outPtr)
        }

        return this.__ITimedMetadataTrackProvider.get_TimedMetadataTracks()
    }

;@endregion Instance Methods
}
