#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\GAMESTATS_OPEN_RESULT.ahk" {GAMESTATS_OPEN_RESULT}
#Import export ".\GAMESTATS_OPEN_TYPE.ahk" {GAMESTATS_OPEN_TYPE}
#Import export ".\GAME_INSTALL_SCOPE.ahk" {GAME_INSTALL_SCOPE}
#Import export ".\GAMING_DEVICE_DEVICE_ID.ahk" {GAMING_DEVICE_DEVICE_ID}
#Import export ".\GAMING_DEVICE_MODEL_INFORMATION.ahk" {GAMING_DEVICE_MODEL_INFORMATION}
#Import export ".\GAMING_DEVICE_VENDOR_ID.ahk" {GAMING_DEVICE_VENDOR_ID}
#Import export ".\GameExplorer.ahk" {GameExplorer}
#Import export ".\GameStatistics.ahk" {GameStatistics}
#Import export ".\GameUICompletionRoutine.ahk" {GameUICompletionRoutine}
#Import export ".\IGameExplorer.ahk" {IGameExplorer}
#Import export ".\IGameExplorer2.ahk" {IGameExplorer2}
#Import export ".\IGameStatistics.ahk" {IGameStatistics}
#Import export ".\IGameStatisticsMgr.ahk" {IGameStatisticsMgr}
#Import export ".\IXblIdpAuthManager.ahk" {IXblIdpAuthManager}
#Import export ".\IXblIdpAuthManager2.ahk" {IXblIdpAuthManager2}
#Import export ".\IXblIdpAuthTokenResult.ahk" {IXblIdpAuthTokenResult}
#Import export ".\IXblIdpAuthTokenResult2.ahk" {IXblIdpAuthTokenResult2}
#Import export ".\KnownGamingPrivileges.ahk" {KnownGamingPrivileges}
#Import export ".\PlayerPickerUICompletionRoutine.ahk" {PlayerPickerUICompletionRoutine}
#Import export ".\XBL_IDP_AUTH_TOKEN_STATUS.ahk" {XBL_IDP_AUTH_TOKEN_STATUS}
#Import export ".\XblIdpAuthManager.ahk" {XblIdpAuthManager}
#Import export ".\XblIdpAuthTokenResult.ahk" {XblIdpAuthTokenResult}
