#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\DXC_CP.ahk" {DXC_CP}
#Import export ".\DXC_OUT_KIND.ahk" {DXC_OUT_KIND}
#Import export ".\DxcArgPair.ahk" {DxcArgPair}
#Import export ".\DxcBuffer.ahk" {DxcBuffer}
#Import export ".\DxcCreateInstance2Proc.ahk" {DxcCreateInstance2Proc}
#Import export ".\DxcCreateInstanceProc.ahk" {DxcCreateInstanceProc}
#Import export ".\DxcDefine.ahk" {DxcDefine}
#Import export ".\DxcShaderHash.ahk" {DxcShaderHash}
#Import export ".\IDxcAssembler.ahk" {IDxcAssembler}
#Import export ".\IDxcBlob.ahk" {IDxcBlob}
#Import export ".\IDxcBlobEncoding.ahk" {IDxcBlobEncoding}
#Import export ".\IDxcBlobUtf16.ahk" {IDxcBlobUtf16}
#Import export ".\IDxcBlobUtf8.ahk" {IDxcBlobUtf8}
#Import export ".\IDxcCompiler.ahk" {IDxcCompiler}
#Import export ".\IDxcCompiler2.ahk" {IDxcCompiler2}
#Import export ".\IDxcCompiler3.ahk" {IDxcCompiler3}
#Import export ".\IDxcCompilerArgs.ahk" {IDxcCompilerArgs}
#Import export ".\IDxcContainerBuilder.ahk" {IDxcContainerBuilder}
#Import export ".\IDxcContainerReflection.ahk" {IDxcContainerReflection}
#Import export ".\IDxcExtraOutputs.ahk" {IDxcExtraOutputs}
#Import export ".\IDxcIncludeHandler.ahk" {IDxcIncludeHandler}
#Import export ".\IDxcLibrary.ahk" {IDxcLibrary}
#Import export ".\IDxcLinker.ahk" {IDxcLinker}
#Import export ".\IDxcOperationResult.ahk" {IDxcOperationResult}
#Import export ".\IDxcOptimizer.ahk" {IDxcOptimizer}
#Import export ".\IDxcOptimizerPass.ahk" {IDxcOptimizerPass}
#Import export ".\IDxcPdbUtils.ahk" {IDxcPdbUtils}
#Import export ".\IDxcPdbUtils2.ahk" {IDxcPdbUtils2}
#Import export ".\IDxcResult.ahk" {IDxcResult}
#Import export ".\IDxcUtils.ahk" {IDxcUtils}
#Import export ".\IDxcValidator.ahk" {IDxcValidator}
#Import export ".\IDxcValidator2.ahk" {IDxcValidator2}
#Import export ".\IDxcVersionInfo.ahk" {IDxcVersionInfo}
#Import export ".\IDxcVersionInfo2.ahk" {IDxcVersionInfo2}
#Import export ".\IDxcVersionInfo3.ahk" {IDxcVersionInfo3}
