#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\HDV_PCI_READ_CONFIG_SPACE.ahk" { HDV_PCI_READ_CONFIG_SPACE }
#Import ".\HDV_PCI_DEVICE_SET_CONFIGURATION.ahk" { HDV_PCI_DEVICE_SET_CONFIGURATION }
#Import ".\HDV_PCI_WRITE_INTERCEPTED_MEMORY.ahk" { HDV_PCI_WRITE_INTERCEPTED_MEMORY }
#Import ".\HDV_PCI_DEVICE_GET_DETAILS.ahk" { HDV_PCI_DEVICE_GET_DETAILS }
#Import ".\HDV_PCI_READ_INTERCEPTED_MEMORY.ahk" { HDV_PCI_READ_INTERCEPTED_MEMORY }
#Import ".\HDV_PCI_WRITE_CONFIG_SPACE.ahk" { HDV_PCI_WRITE_CONFIG_SPACE }
#Import ".\HDV_PCI_DEVICE_TEARDOWN.ahk" { HDV_PCI_DEVICE_TEARDOWN }
#Import ".\HDV_PCI_DEVICE_START.ahk" { HDV_PCI_DEVICE_START }
#Import ".\HDV_PCI_DEVICE_INITIALIZE.ahk" { HDV_PCI_DEVICE_INITIALIZE }
#Import ".\HDV_PCI_INTERFACE_VERSION.ahk" { HDV_PCI_INTERFACE_VERSION }
#Import ".\HDV_PCI_DEVICE_STOP.ahk" { HDV_PCI_DEVICE_STOP }

/**
 * @namespace Windows.Win32.System.Hypervisor
 */
export default struct HDV_PCI_DEVICE_INTERFACE {
    #StructPack 8

    Version : HDV_PCI_INTERFACE_VERSION

    Initialize : HDV_PCI_DEVICE_INITIALIZE

    Teardown : HDV_PCI_DEVICE_TEARDOWN

    SetConfiguration : HDV_PCI_DEVICE_SET_CONFIGURATION

    GetDetails : HDV_PCI_DEVICE_GET_DETAILS

    Start : HDV_PCI_DEVICE_START

    Stop : HDV_PCI_DEVICE_STOP

    ReadConfigSpace : HDV_PCI_READ_CONFIG_SPACE

    WriteConfigSpace : HDV_PCI_WRITE_CONFIG_SPACE

    ReadInterceptedMemory : HDV_PCI_READ_INTERCEPTED_MEMORY

    WriteInterceptedMemory : HDV_PCI_WRITE_INTERCEPTED_MEMORY

}
