#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\WHV_EMULATOR_GET_VIRTUAL_PROCESSOR_REGISTERS_CALLBACK.ahk" { WHV_EMULATOR_GET_VIRTUAL_PROCESSOR_REGISTERS_CALLBACK }
#Import ".\WHV_EMULATOR_IO_PORT_CALLBACK.ahk" { WHV_EMULATOR_IO_PORT_CALLBACK }
#Import ".\WHV_EMULATOR_MEMORY_CALLBACK.ahk" { WHV_EMULATOR_MEMORY_CALLBACK }
#Import ".\WHV_EMULATOR_SET_VIRTUAL_PROCESSOR_REGISTERS_CALLBACK.ahk" { WHV_EMULATOR_SET_VIRTUAL_PROCESSOR_REGISTERS_CALLBACK }
#Import ".\WHV_EMULATOR_TRANSLATE_GVA_PAGE_CALLBACK.ahk" { WHV_EMULATOR_TRANSLATE_GVA_PAGE_CALLBACK }

/**
 * @namespace Windows.Win32.System.Hypervisor
 */
export default struct WHV_EMULATOR_CALLBACKS {
    #StructPack 8

    Size : UInt32

    Reserved : UInt32

    WHvEmulatorIoPortCallback : WHV_EMULATOR_IO_PORT_CALLBACK

    WHvEmulatorMemoryCallback : WHV_EMULATOR_MEMORY_CALLBACK

    WHvEmulatorGetVirtualProcessorRegisters : WHV_EMULATOR_GET_VIRTUAL_PROCESSOR_REGISTERS_CALLBACK

    WHvEmulatorSetVirtualProcessorRegisters : WHV_EMULATOR_SET_VIRTUAL_PROCESSOR_REGISTERS_CALLBACK

    WHvEmulatorTranslateGvaPage : WHV_EMULATOR_TRANSLATE_GVA_PAGE_CALLBACK

}
