#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\CompositionSwapchain\__Init.ahk" {*}
#Import export ".\DXCore\__Init.ahk" {*}
#Import export ".\Direct2D\__Init.ahk" {*}
#Import export ".\Direct3D\__Init.ahk" {*}
#Import export ".\Direct3D10\__Init.ahk" {*}
#Import export ".\Direct3D11\__Init.ahk" {*}
#Import export ".\Direct3D11on12\__Init.ahk" {*}
#Import export ".\Direct3D12\__Init.ahk" {*}
#Import export ".\Direct3D9\__Init.ahk" {*}
#Import export ".\Direct3D9on12\__Init.ahk" {*}
#Import export ".\DirectComposition\__Init.ahk" {*}
#Import export ".\DirectDraw\__Init.ahk" {*}
#Import export ".\DirectManipulation\__Init.ahk" {*}
#Import export ".\DirectWrite\__Init.ahk" {*}
#Import export ".\Dwm\__Init.ahk" {*}
#Import export ".\Dxgi\__Init.ahk" {*}
#Import export ".\Gdi\__Init.ahk" {*}
#Import export ".\GdiPlus\__Init.ahk" {*}
#Import export ".\Hlsl\__Init.ahk" {*}
#Import export ".\Imaging\__Init.ahk" {*}
#Import export ".\OpenGL\__Init.ahk" {*}
#Import export ".\Printing\__Init.ahk" {*}
