#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PFLT_CALLBACK_DATA_QUEUE_PEEK_NEXT_IO.ahk" { PFLT_CALLBACK_DATA_QUEUE_PEEK_NEXT_IO }
#Import ".\PFLT_CALLBACK_DATA_QUEUE_RELEASE.ahk" { PFLT_CALLBACK_DATA_QUEUE_RELEASE }
#Import ".\PFLT_CALLBACK_DATA_QUEUE_COMPLETE_CANCELED_IO.ahk" { PFLT_CALLBACK_DATA_QUEUE_COMPLETE_CANCELED_IO }
#Import ".\PFLT_INSTANCE.ahk" { PFLT_INSTANCE }
#Import ".\FLT_CALLBACK_DATA_QUEUE_FLAGS.ahk" { FLT_CALLBACK_DATA_QUEUE_FLAGS }
#Import ".\PFLT_CALLBACK_DATA_QUEUE_ACQUIRE.ahk" { PFLT_CALLBACK_DATA_QUEUE_ACQUIRE }
#Import ".\PFLT_CALLBACK_DATA_QUEUE_REMOVE_IO.ahk" { PFLT_CALLBACK_DATA_QUEUE_REMOVE_IO }
#Import ".\PFLT_CALLBACK_DATA_QUEUE_INSERT_IO.ahk" { PFLT_CALLBACK_DATA_QUEUE_INSERT_IO }

/**
 * @namespace Windows.Wdk.Storage.FileSystem.Minifilters
 */
export default struct FLT_CALLBACK_DATA_QUEUE {
    #StructPack 8

    Csq : IntPtr

    Flags : FLT_CALLBACK_DATA_QUEUE_FLAGS

    Instance : PFLT_INSTANCE

    InsertIo : PFLT_CALLBACK_DATA_QUEUE_INSERT_IO

    RemoveIo : PFLT_CALLBACK_DATA_QUEUE_REMOVE_IO

    PeekNextIo : PFLT_CALLBACK_DATA_QUEUE_PEEK_NEXT_IO

    Acquire : PFLT_CALLBACK_DATA_QUEUE_ACQUIRE

    Release : PFLT_CALLBACK_DATA_QUEUE_RELEASE

    CompleteCanceledIo : PFLT_CALLBACK_DATA_QUEUE_COMPLETE_CANCELED_IO

}
