#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PFLT_NORMALIZE_CONTEXT_CLEANUP.ahk" { PFLT_NORMALIZE_CONTEXT_CLEANUP }
#Import ".\PFLT_FILTER_UNLOAD_CALLBACK.ahk" { PFLT_FILTER_UNLOAD_CALLBACK }
#Import ".\PFLT_INSTANCE_QUERY_TEARDOWN_CALLBACK.ahk" { PFLT_INSTANCE_QUERY_TEARDOWN_CALLBACK }
#Import ".\FLT_CONTEXT_REGISTRATION.ahk" { FLT_CONTEXT_REGISTRATION }
#Import ".\PFLT_INSTANCE_TEARDOWN_CALLBACK.ahk" { PFLT_INSTANCE_TEARDOWN_CALLBACK }
#Import ".\FLT_OPERATION_REGISTRATION.ahk" { FLT_OPERATION_REGISTRATION }
#Import ".\PFLT_TRANSACTION_NOTIFICATION_CALLBACK.ahk" { PFLT_TRANSACTION_NOTIFICATION_CALLBACK }
#Import ".\PFLT_NORMALIZE_NAME_COMPONENT.ahk" { PFLT_NORMALIZE_NAME_COMPONENT }
#Import ".\PFLT_NORMALIZE_NAME_COMPONENT_EX.ahk" { PFLT_NORMALIZE_NAME_COMPONENT_EX }
#Import ".\PFLT_INSTANCE_SETUP_CALLBACK.ahk" { PFLT_INSTANCE_SETUP_CALLBACK }
#Import ".\PFLT_SECTION_CONFLICT_NOTIFICATION_CALLBACK.ahk" { PFLT_SECTION_CONFLICT_NOTIFICATION_CALLBACK }
#Import ".\PFLT_GENERATE_FILE_NAME.ahk" { PFLT_GENERATE_FILE_NAME }

/**
 * @namespace Windows.Wdk.Storage.FileSystem.Minifilters
 */
export default struct FLT_REGISTRATION {
    #StructPack 8

    Size : UInt16

    Version : UInt16

    Flags : UInt32

    ContextRegistration : FLT_CONTEXT_REGISTRATION.Ptr

    OperationRegistration : FLT_OPERATION_REGISTRATION.Ptr

    FilterUnloadCallback : PFLT_FILTER_UNLOAD_CALLBACK

    InstanceSetupCallback : PFLT_INSTANCE_SETUP_CALLBACK

    InstanceQueryTeardownCallback : PFLT_INSTANCE_QUERY_TEARDOWN_CALLBACK

    InstanceTeardownStartCallback : PFLT_INSTANCE_TEARDOWN_CALLBACK

    InstanceTeardownCompleteCallback : PFLT_INSTANCE_TEARDOWN_CALLBACK

    GenerateFileNameCallback : PFLT_GENERATE_FILE_NAME

    NormalizeNameComponentCallback : PFLT_NORMALIZE_NAME_COMPONENT

    NormalizeContextCleanupCallback : PFLT_NORMALIZE_CONTEXT_CLEANUP

    TransactionNotificationCallback : PFLT_TRANSACTION_NOTIFICATION_CALLBACK

    NormalizeNameComponentExCallback : PFLT_NORMALIZE_NAME_COMPONENT_EX

    SectionNotificationCallback : PFLT_SECTION_CONFLICT_NOTIFICATION_CALLBACK

}
