#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\DNS_AAAA_DATA.ahk" {DNS_AAAA_DATA}
#Import export ".\DNS_ADDR.ahk" {DNS_ADDR}
#Import export ".\DNS_ADDR_ARRAY.ahk" {DNS_ADDR_ARRAY}
#Import export ".\DNS_APPLICATION_SETTINGS.ahk" {DNS_APPLICATION_SETTINGS}
#Import export ".\DNS_ATMA_DATA.ahk" {DNS_ATMA_DATA}
#Import export ".\DNS_A_DATA.ahk" {DNS_A_DATA}
#Import export ".\DNS_CHARSET.ahk" {DNS_CHARSET}
#Import export ".\DNS_CONFIG_TYPE.ahk" {DNS_CONFIG_TYPE}
#Import export ".\DNS_CONNECTION_IFINDEX_ENTRY.ahk" {DNS_CONNECTION_IFINDEX_ENTRY}
#Import export ".\DNS_CONNECTION_IFINDEX_LIST.ahk" {DNS_CONNECTION_IFINDEX_LIST}
#Import export ".\DNS_CONNECTION_NAME.ahk" {DNS_CONNECTION_NAME}
#Import export ".\DNS_CONNECTION_NAME_LIST.ahk" {DNS_CONNECTION_NAME_LIST}
#Import export ".\DNS_CONNECTION_POLICY_ENTRY.ahk" {DNS_CONNECTION_POLICY_ENTRY}
#Import export ".\DNS_CONNECTION_POLICY_ENTRY_LIST.ahk" {DNS_CONNECTION_POLICY_ENTRY_LIST}
#Import export ".\DNS_CONNECTION_POLICY_TAG.ahk" {DNS_CONNECTION_POLICY_TAG}
#Import export ".\DNS_CONNECTION_PROXY_ELEMENT.ahk" {DNS_CONNECTION_PROXY_ELEMENT}
#Import export ".\DNS_CONNECTION_PROXY_INFO.ahk" {DNS_CONNECTION_PROXY_INFO}
#Import export ".\DNS_CONNECTION_PROXY_INFO_EX.ahk" {DNS_CONNECTION_PROXY_INFO_EX}
#Import export ".\DNS_CONNECTION_PROXY_INFO_SWITCH.ahk" {DNS_CONNECTION_PROXY_INFO_SWITCH}
#Import export ".\DNS_CONNECTION_PROXY_LIST.ahk" {DNS_CONNECTION_PROXY_LIST}
#Import export ".\DNS_CONNECTION_PROXY_TYPE.ahk" {DNS_CONNECTION_PROXY_TYPE}
#Import export ".\DNS_CUSTOM_SERVER.ahk" {DNS_CUSTOM_SERVER}
#Import export ".\DNS_DHCID_DATA.ahk" {DNS_DHCID_DATA}
#Import export ".\DNS_DS_DATA.ahk" {DNS_DS_DATA}
#Import export ".\DNS_FREE_TYPE.ahk" {DNS_FREE_TYPE}
#Import export ".\DNS_HEADER.ahk" {DNS_HEADER}
#Import export ".\DNS_HEADER_EXT.ahk" {DNS_HEADER_EXT}
#Import export ".\DNS_KEY_DATA.ahk" {DNS_KEY_DATA}
#Import export ".\DNS_LOC_DATA.ahk" {DNS_LOC_DATA}
#Import export ".\DNS_MESSAGE_BUFFER.ahk" {DNS_MESSAGE_BUFFER}
#Import export ".\DNS_MINFO_DATAA.ahk" {DNS_MINFO_DATAA}
#Import export ".\DNS_MINFO_DATAW.ahk" {DNS_MINFO_DATAW}
#Import export ".\DNS_MX_DATAA.ahk" {DNS_MX_DATAA}
#Import export ".\DNS_MX_DATAW.ahk" {DNS_MX_DATAW}
#Import export ".\DNS_NAME_FORMAT.ahk" {DNS_NAME_FORMAT}
#Import export ".\DNS_NAPTR_DATAA.ahk" {DNS_NAPTR_DATAA}
#Import export ".\DNS_NAPTR_DATAW.ahk" {DNS_NAPTR_DATAW}
#Import export ".\DNS_NSEC3PARAM_DATA.ahk" {DNS_NSEC3PARAM_DATA}
#Import export ".\DNS_NSEC3_DATA.ahk" {DNS_NSEC3_DATA}
#Import export ".\DNS_NSEC_DATAA.ahk" {DNS_NSEC_DATAA}
#Import export ".\DNS_NSEC_DATAW.ahk" {DNS_NSEC_DATAW}
#Import export ".\DNS_NULL_DATA.ahk" {DNS_NULL_DATA}
#Import export ".\DNS_NXT_DATAA.ahk" {DNS_NXT_DATAA}
#Import export ".\DNS_NXT_DATAW.ahk" {DNS_NXT_DATAW}
#Import export ".\DNS_OPT_DATA.ahk" {DNS_OPT_DATA}
#Import export ".\DNS_PROXY_COMPLETION_ROUTINE.ahk" {DNS_PROXY_COMPLETION_ROUTINE}
#Import export ".\DNS_PROXY_INFORMATION.ahk" {DNS_PROXY_INFORMATION}
#Import export ".\DNS_PROXY_INFORMATION_TYPE.ahk" {DNS_PROXY_INFORMATION_TYPE}
#Import export ".\DNS_PTR_DATAA.ahk" {DNS_PTR_DATAA}
#Import export ".\DNS_PTR_DATAW.ahk" {DNS_PTR_DATAW}
#Import export ".\DNS_QUERY_CANCEL.ahk" {DNS_QUERY_CANCEL}
#Import export ".\DNS_QUERY_OPTIONS.ahk" {DNS_QUERY_OPTIONS}
#Import export ".\DNS_QUERY_RAW_CANCEL.ahk" {DNS_QUERY_RAW_CANCEL}
#Import export ".\DNS_QUERY_RAW_COMPLETION_ROUTINE.ahk" {DNS_QUERY_RAW_COMPLETION_ROUTINE}
#Import export ".\DNS_QUERY_RAW_REQUEST.ahk" {DNS_QUERY_RAW_REQUEST}
#Import export ".\DNS_QUERY_RAW_RESULT.ahk" {DNS_QUERY_RAW_RESULT}
#Import export ".\DNS_QUERY_REQUEST.ahk" {DNS_QUERY_REQUEST}
#Import export ".\DNS_QUERY_REQUEST3.ahk" {DNS_QUERY_REQUEST3}
#Import export ".\DNS_QUERY_RESULT.ahk" {DNS_QUERY_RESULT}
#Import export ".\DNS_RECORDA.ahk" {DNS_RECORDA}
#Import export ".\DNS_RECORDW.ahk" {DNS_RECORDW}
#Import export ".\DNS_RECORD_FLAGS.ahk" {DNS_RECORD_FLAGS}
#Import export ".\DNS_RECORD_OPTW.ahk" {DNS_RECORD_OPTW}
#Import export ".\DNS_RRSET.ahk" {DNS_RRSET}
#Import export ".\DNS_SECTION.ahk" {DNS_SECTION}
#Import export ".\DNS_SERVICE_BROWSE_REQUEST.ahk" {DNS_SERVICE_BROWSE_REQUEST}
#Import export ".\DNS_SERVICE_CANCEL.ahk" {DNS_SERVICE_CANCEL}
#Import export ".\DNS_SERVICE_INSTANCE.ahk" {DNS_SERVICE_INSTANCE}
#Import export ".\DNS_SERVICE_REGISTER_REQUEST.ahk" {DNS_SERVICE_REGISTER_REQUEST}
#Import export ".\DNS_SERVICE_RESOLVE_REQUEST.ahk" {DNS_SERVICE_RESOLVE_REQUEST}
#Import export ".\DNS_SIG_DATAA.ahk" {DNS_SIG_DATAA}
#Import export ".\DNS_SIG_DATAW.ahk" {DNS_SIG_DATAW}
#Import export ".\DNS_SOA_DATAA.ahk" {DNS_SOA_DATAA}
#Import export ".\DNS_SOA_DATAW.ahk" {DNS_SOA_DATAW}
#Import export ".\DNS_SRV_DATAA.ahk" {DNS_SRV_DATAA}
#Import export ".\DNS_SRV_DATAW.ahk" {DNS_SRV_DATAW}
#Import export ".\DNS_SVCB_DATA.ahk" {DNS_SVCB_DATA}
#Import export ".\DNS_SVCB_PARAM.ahk" {DNS_SVCB_PARAM}
#Import export ".\DNS_SVCB_PARAM_ALPN.ahk" {DNS_SVCB_PARAM_ALPN}
#Import export ".\DNS_SVCB_PARAM_ALPN_ID.ahk" {DNS_SVCB_PARAM_ALPN_ID}
#Import export ".\DNS_SVCB_PARAM_IPV4.ahk" {DNS_SVCB_PARAM_IPV4}
#Import export ".\DNS_SVCB_PARAM_IPV6.ahk" {DNS_SVCB_PARAM_IPV6}
#Import export ".\DNS_SVCB_PARAM_MANDATORY.ahk" {DNS_SVCB_PARAM_MANDATORY}
#Import export ".\DNS_SVCB_PARAM_TYPE.ahk" {DNS_SVCB_PARAM_TYPE}
#Import export ".\DNS_SVCB_PARAM_UNKNOWN.ahk" {DNS_SVCB_PARAM_UNKNOWN}
#Import export ".\DNS_TKEY_DATAA.ahk" {DNS_TKEY_DATAA}
#Import export ".\DNS_TKEY_DATAW.ahk" {DNS_TKEY_DATAW}
#Import export ".\DNS_TLSA_DATA.ahk" {DNS_TLSA_DATA}
#Import export ".\DNS_TSIG_DATAA.ahk" {DNS_TSIG_DATAA}
#Import export ".\DNS_TSIG_DATAW.ahk" {DNS_TSIG_DATAW}
#Import export ".\DNS_TXT_DATAA.ahk" {DNS_TXT_DATAA}
#Import export ".\DNS_TXT_DATAW.ahk" {DNS_TXT_DATAW}
#Import export ".\DNS_UNKNOWN_DATA.ahk" {DNS_UNKNOWN_DATA}
#Import export ".\DNS_WINSR_DATAA.ahk" {DNS_WINSR_DATAA}
#Import export ".\DNS_WINSR_DATAW.ahk" {DNS_WINSR_DATAW}
#Import export ".\DNS_WINS_DATA.ahk" {DNS_WINS_DATA}
#Import export ".\DNS_WIRE_QUESTION.ahk" {DNS_WIRE_QUESTION}
#Import export ".\DNS_WIRE_RECORD.ahk" {DNS_WIRE_RECORD}
#Import export ".\DNS_WKS_DATA.ahk" {DNS_WKS_DATA}
#Import export ".\IP4_ARRAY.ahk" {IP4_ARRAY}
#Import export ".\IP6_ADDRESS.ahk" {IP6_ADDRESS}
#Import export ".\MDNS_QUERY_HANDLE.ahk" {MDNS_QUERY_HANDLE}
#Import export ".\MDNS_QUERY_REQUEST.ahk" {MDNS_QUERY_REQUEST}
#Import export ".\PDNS_QUERY_COMPLETION_ROUTINE.ahk" {PDNS_QUERY_COMPLETION_ROUTINE}
#Import export ".\PDNS_SERVICE_BROWSE_CALLBACK.ahk" {PDNS_SERVICE_BROWSE_CALLBACK}
#Import export ".\PDNS_SERVICE_REGISTER_COMPLETE.ahk" {PDNS_SERVICE_REGISTER_COMPLETE}
#Import export ".\PDNS_SERVICE_RESOLVE_COMPLETE.ahk" {PDNS_SERVICE_RESOLVE_COMPLETE}
#Import export ".\PMDNS_QUERY_CALLBACK.ahk" {PMDNS_QUERY_CALLBACK}
#Import export ".\_DnsRecordOptA.ahk" {_DnsRecordOptA}
