#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\AM_WMT_EVENT_DATA.ahk" {AM_WMT_EVENT_DATA}
#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\DRM_COPY_OPL.ahk" {DRM_COPY_OPL}
#Import export ".\DRM_MINIMUM_OUTPUT_PROTECTION_LEVELS.ahk" {DRM_MINIMUM_OUTPUT_PROTECTION_LEVELS}
#Import export ".\DRM_OPL_OUTPUT_IDS.ahk" {DRM_OPL_OUTPUT_IDS}
#Import export ".\DRM_OUTPUT_PROTECTION.ahk" {DRM_OUTPUT_PROTECTION}
#Import export ".\DRM_PLAY_OPL.ahk" {DRM_PLAY_OPL}
#Import export ".\DRM_VAL16.ahk" {DRM_VAL16}
#Import export ".\DRM_VIDEO_OUTPUT_PROTECTION_IDS.ahk" {DRM_VIDEO_OUTPUT_PROTECTION_IDS}
#Import export ".\INSNetSourceCreator.ahk" {INSNetSourceCreator}
#Import export ".\INSSBuffer.ahk" {INSSBuffer}
#Import export ".\INSSBuffer2.ahk" {INSSBuffer2}
#Import export ".\INSSBuffer3.ahk" {INSSBuffer3}
#Import export ".\INSSBuffer4.ahk" {INSSBuffer4}
#Import export ".\IWMAddressAccess.ahk" {IWMAddressAccess}
#Import export ".\IWMAddressAccess2.ahk" {IWMAddressAccess2}
#Import export ".\IWMAuthorizer.ahk" {IWMAuthorizer}
#Import export ".\IWMBackupRestoreProps.ahk" {IWMBackupRestoreProps}
#Import export ".\IWMBandwidthSharing.ahk" {IWMBandwidthSharing}
#Import export ".\IWMClientConnections.ahk" {IWMClientConnections}
#Import export ".\IWMClientConnections2.ahk" {IWMClientConnections2}
#Import export ".\IWMCodecInfo.ahk" {IWMCodecInfo}
#Import export ".\IWMCodecInfo2.ahk" {IWMCodecInfo2}
#Import export ".\IWMCodecInfo3.ahk" {IWMCodecInfo3}
#Import export ".\IWMCredentialCallback.ahk" {IWMCredentialCallback}
#Import export ".\IWMDRMEditor.ahk" {IWMDRMEditor}
#Import export ".\IWMDRMMessageParser.ahk" {IWMDRMMessageParser}
#Import export ".\IWMDRMReader.ahk" {IWMDRMReader}
#Import export ".\IWMDRMReader2.ahk" {IWMDRMReader2}
#Import export ".\IWMDRMReader3.ahk" {IWMDRMReader3}
#Import export ".\IWMDRMTranscryptionManager.ahk" {IWMDRMTranscryptionManager}
#Import export ".\IWMDRMTranscryptor.ahk" {IWMDRMTranscryptor}
#Import export ".\IWMDRMTranscryptor2.ahk" {IWMDRMTranscryptor2}
#Import export ".\IWMDRMWriter.ahk" {IWMDRMWriter}
#Import export ".\IWMDRMWriter2.ahk" {IWMDRMWriter2}
#Import export ".\IWMDRMWriter3.ahk" {IWMDRMWriter3}
#Import export ".\IWMDeviceRegistration.ahk" {IWMDeviceRegistration}
#Import export ".\IWMGetSecureChannel.ahk" {IWMGetSecureChannel}
#Import export ".\IWMHeaderInfo.ahk" {IWMHeaderInfo}
#Import export ".\IWMHeaderInfo2.ahk" {IWMHeaderInfo2}
#Import export ".\IWMHeaderInfo3.ahk" {IWMHeaderInfo3}
#Import export ".\IWMIStreamProps.ahk" {IWMIStreamProps}
#Import export ".\IWMImageInfo.ahk" {IWMImageInfo}
#Import export ".\IWMIndexer.ahk" {IWMIndexer}
#Import export ".\IWMIndexer2.ahk" {IWMIndexer2}
#Import export ".\IWMInputMediaProps.ahk" {IWMInputMediaProps}
#Import export ".\IWMLanguageList.ahk" {IWMLanguageList}
#Import export ".\IWMLicenseBackup.ahk" {IWMLicenseBackup}
#Import export ".\IWMLicenseRestore.ahk" {IWMLicenseRestore}
#Import export ".\IWMLicenseRevocationAgent.ahk" {IWMLicenseRevocationAgent}
#Import export ".\IWMMediaProps.ahk" {IWMMediaProps}
#Import export ".\IWMMetadataEditor.ahk" {IWMMetadataEditor}
#Import export ".\IWMMetadataEditor2.ahk" {IWMMetadataEditor2}
#Import export ".\IWMMutualExclusion.ahk" {IWMMutualExclusion}
#Import export ".\IWMMutualExclusion2.ahk" {IWMMutualExclusion2}
#Import export ".\IWMOutputMediaProps.ahk" {IWMOutputMediaProps}
#Import export ".\IWMPacketSize.ahk" {IWMPacketSize}
#Import export ".\IWMPacketSize2.ahk" {IWMPacketSize2}
#Import export ".\IWMPlayerHook.ahk" {IWMPlayerHook}
#Import export ".\IWMPlayerTimestampHook.ahk" {IWMPlayerTimestampHook}
#Import export ".\IWMProfile.ahk" {IWMProfile}
#Import export ".\IWMProfile2.ahk" {IWMProfile2}
#Import export ".\IWMProfile3.ahk" {IWMProfile3}
#Import export ".\IWMProfileManager.ahk" {IWMProfileManager}
#Import export ".\IWMProfileManager2.ahk" {IWMProfileManager2}
#Import export ".\IWMProfileManagerLanguage.ahk" {IWMProfileManagerLanguage}
#Import export ".\IWMPropertyVault.ahk" {IWMPropertyVault}
#Import export ".\IWMProximityDetection.ahk" {IWMProximityDetection}
#Import export ".\IWMReader.ahk" {IWMReader}
#Import export ".\IWMReaderAccelerator.ahk" {IWMReaderAccelerator}
#Import export ".\IWMReaderAdvanced.ahk" {IWMReaderAdvanced}
#Import export ".\IWMReaderAdvanced2.ahk" {IWMReaderAdvanced2}
#Import export ".\IWMReaderAdvanced3.ahk" {IWMReaderAdvanced3}
#Import export ".\IWMReaderAdvanced4.ahk" {IWMReaderAdvanced4}
#Import export ".\IWMReaderAdvanced5.ahk" {IWMReaderAdvanced5}
#Import export ".\IWMReaderAdvanced6.ahk" {IWMReaderAdvanced6}
#Import export ".\IWMReaderAllocatorEx.ahk" {IWMReaderAllocatorEx}
#Import export ".\IWMReaderCallback.ahk" {IWMReaderCallback}
#Import export ".\IWMReaderCallbackAdvanced.ahk" {IWMReaderCallbackAdvanced}
#Import export ".\IWMReaderNetworkConfig.ahk" {IWMReaderNetworkConfig}
#Import export ".\IWMReaderNetworkConfig2.ahk" {IWMReaderNetworkConfig2}
#Import export ".\IWMReaderPlaylistBurn.ahk" {IWMReaderPlaylistBurn}
#Import export ".\IWMReaderStreamClock.ahk" {IWMReaderStreamClock}
#Import export ".\IWMReaderTimecode.ahk" {IWMReaderTimecode}
#Import export ".\IWMReaderTypeNegotiation.ahk" {IWMReaderTypeNegotiation}
#Import export ".\IWMRegisterCallback.ahk" {IWMRegisterCallback}
#Import export ".\IWMRegisteredDevice.ahk" {IWMRegisteredDevice}
#Import export ".\IWMSBufferAllocator.ahk" {IWMSBufferAllocator}
#Import export ".\IWMSInternalAdminNetSource.ahk" {IWMSInternalAdminNetSource}
#Import export ".\IWMSInternalAdminNetSource2.ahk" {IWMSInternalAdminNetSource2}
#Import export ".\IWMSInternalAdminNetSource3.ahk" {IWMSInternalAdminNetSource3}
#Import export ".\IWMSecureChannel.ahk" {IWMSecureChannel}
#Import export ".\IWMStatusCallback.ahk" {IWMStatusCallback}
#Import export ".\IWMStreamConfig.ahk" {IWMStreamConfig}
#Import export ".\IWMStreamConfig2.ahk" {IWMStreamConfig2}
#Import export ".\IWMStreamConfig3.ahk" {IWMStreamConfig3}
#Import export ".\IWMStreamList.ahk" {IWMStreamList}
#Import export ".\IWMStreamPrioritization.ahk" {IWMStreamPrioritization}
#Import export ".\IWMSyncReader.ahk" {IWMSyncReader}
#Import export ".\IWMSyncReader2.ahk" {IWMSyncReader2}
#Import export ".\IWMVideoMediaProps.ahk" {IWMVideoMediaProps}
#Import export ".\IWMWatermarkInfo.ahk" {IWMWatermarkInfo}
#Import export ".\IWMWriter.ahk" {IWMWriter}
#Import export ".\IWMWriterAdvanced.ahk" {IWMWriterAdvanced}
#Import export ".\IWMWriterAdvanced2.ahk" {IWMWriterAdvanced2}
#Import export ".\IWMWriterAdvanced3.ahk" {IWMWriterAdvanced3}
#Import export ".\IWMWriterFileSink.ahk" {IWMWriterFileSink}
#Import export ".\IWMWriterFileSink2.ahk" {IWMWriterFileSink2}
#Import export ".\IWMWriterFileSink3.ahk" {IWMWriterFileSink3}
#Import export ".\IWMWriterNetworkSink.ahk" {IWMWriterNetworkSink}
#Import export ".\IWMWriterPostView.ahk" {IWMWriterPostView}
#Import export ".\IWMWriterPostViewCallback.ahk" {IWMWriterPostViewCallback}
#Import export ".\IWMWriterPreprocess.ahk" {IWMWriterPreprocess}
#Import export ".\IWMWriterPushSink.ahk" {IWMWriterPushSink}
#Import export ".\IWMWriterSink.ahk" {IWMWriterSink}
#Import export ".\NETSOURCE_URLCREDPOLICY_SETTINGS.ahk" {NETSOURCE_URLCREDPOLICY_SETTINGS}
#Import export ".\WEBSTREAM_SAMPLE_TYPE.ahk" {WEBSTREAM_SAMPLE_TYPE}
#Import export ".\WMDRM_IMPORT_INIT_STRUCT.ahk" {WMDRM_IMPORT_INIT_STRUCT}
#Import export ".\WMMPEG2VIDEOINFO.ahk" {WMMPEG2VIDEOINFO}
#Import export ".\WMSCRIPTFORMAT.ahk" {WMSCRIPTFORMAT}
#Import export ".\WMT_ATTR_DATATYPE.ahk" {WMT_ATTR_DATATYPE}
#Import export ".\WMT_ATTR_IMAGETYPE.ahk" {WMT_ATTR_IMAGETYPE}
#Import export ".\WMT_BUFFER_SEGMENT.ahk" {WMT_BUFFER_SEGMENT}
#Import export ".\WMT_CODEC_INFO_TYPE.ahk" {WMT_CODEC_INFO_TYPE}
#Import export ".\WMT_COLORSPACEINFO_EXTENSION_DATA.ahk" {WMT_COLORSPACEINFO_EXTENSION_DATA}
#Import export ".\WMT_CREDENTIAL_FLAGS.ahk" {WMT_CREDENTIAL_FLAGS}
#Import export ".\WMT_DRMLA_TRUST.ahk" {WMT_DRMLA_TRUST}
#Import export ".\WMT_FILESINK_DATA_UNIT.ahk" {WMT_FILESINK_DATA_UNIT}
#Import export ".\WMT_FILESINK_MODE.ahk" {WMT_FILESINK_MODE}
#Import export ".\WMT_IMAGE_TYPE.ahk" {WMT_IMAGE_TYPE}
#Import export ".\WMT_INDEXER_TYPE.ahk" {WMT_INDEXER_TYPE}
#Import export ".\WMT_INDEX_TYPE.ahk" {WMT_INDEX_TYPE}
#Import export ".\WMT_MUSICSPEECH_CLASS_MODE.ahk" {WMT_MUSICSPEECH_CLASS_MODE}
#Import export ".\WMT_NET_PROTOCOL.ahk" {WMT_NET_PROTOCOL}
#Import export ".\WMT_OFFSET_FORMAT.ahk" {WMT_OFFSET_FORMAT}
#Import export ".\WMT_PAYLOAD_FRAGMENT.ahk" {WMT_PAYLOAD_FRAGMENT}
#Import export ".\WMT_PLAY_MODE.ahk" {WMT_PLAY_MODE}
#Import export ".\WMT_PROXY_SETTINGS.ahk" {WMT_PROXY_SETTINGS}
#Import export ".\WMT_RIGHTS.ahk" {WMT_RIGHTS}
#Import export ".\WMT_STATUS.ahk" {WMT_STATUS}
#Import export ".\WMT_STORAGE_FORMAT.ahk" {WMT_STORAGE_FORMAT}
#Import export ".\WMT_STREAM_SELECTION.ahk" {WMT_STREAM_SELECTION}
#Import export ".\WMT_TIMECODE_EXTENSION_DATA.ahk" {WMT_TIMECODE_EXTENSION_DATA}
#Import export ".\WMT_TIMECODE_FRAMERATE.ahk" {WMT_TIMECODE_FRAMERATE}
#Import export ".\WMT_TRANSPORT_TYPE.ahk" {WMT_TRANSPORT_TYPE}
#Import export ".\WMT_VERSION.ahk" {WMT_VERSION}
#Import export ".\WMT_VIDEOIMAGE_SAMPLE.ahk" {WMT_VIDEOIMAGE_SAMPLE}
#Import export ".\WMT_VIDEOIMAGE_SAMPLE2.ahk" {WMT_VIDEOIMAGE_SAMPLE2}
#Import export ".\WMT_WATERMARK_ENTRY.ahk" {WMT_WATERMARK_ENTRY}
#Import export ".\WMT_WATERMARK_ENTRY_TYPE.ahk" {WMT_WATERMARK_ENTRY_TYPE}
#Import export ".\WMT_WEBSTREAM_FORMAT.ahk" {WMT_WEBSTREAM_FORMAT}
#Import export ".\WMT_WEBSTREAM_SAMPLE_HEADER.ahk" {WMT_WEBSTREAM_SAMPLE_HEADER}
#Import export ".\WMVIDEOINFOHEADER.ahk" {WMVIDEOINFOHEADER}
#Import export ".\WMVIDEOINFOHEADER2.ahk" {WMVIDEOINFOHEADER2}
#Import export ".\WM_ADDRESS_ACCESSENTRY.ahk" {WM_ADDRESS_ACCESSENTRY}
#Import export ".\WM_AETYPE.ahk" {WM_AETYPE}
#Import export ".\WM_CLIENT_PROPERTIES.ahk" {WM_CLIENT_PROPERTIES}
#Import export ".\WM_CLIENT_PROPERTIES_EX.ahk" {WM_CLIENT_PROPERTIES_EX}
#Import export ".\WM_DM_INTERLACED_TYPE.ahk" {WM_DM_INTERLACED_TYPE}
#Import export ".\WM_DM_IT_FIRST_FRAME_COHERENCY.ahk" {WM_DM_IT_FIRST_FRAME_COHERENCY}
#Import export ".\WM_LEAKY_BUCKET_PAIR.ahk" {WM_LEAKY_BUCKET_PAIR}
#Import export ".\WM_MEDIA_TYPE.ahk" {WM_MEDIA_TYPE}
#Import export ".\WM_PICTURE.ahk" {WM_PICTURE}
#Import export ".\WM_PLAYBACK_DRC_LEVEL.ahk" {WM_PLAYBACK_DRC_LEVEL}
#Import export ".\WM_PORT_NUMBER_RANGE.ahk" {WM_PORT_NUMBER_RANGE}
#Import export ".\WM_READER_CLIENTINFO.ahk" {WM_READER_CLIENTINFO}
#Import export ".\WM_READER_STATISTICS.ahk" {WM_READER_STATISTICS}
#Import export ".\WM_SFEX_TYPE.ahk" {WM_SFEX_TYPE}
#Import export ".\WM_SF_TYPE.ahk" {WM_SF_TYPE}
#Import export ".\WM_STREAM_PRIORITY_RECORD.ahk" {WM_STREAM_PRIORITY_RECORD}
#Import export ".\WM_STREAM_TYPE_INFO.ahk" {WM_STREAM_TYPE_INFO}
#Import export ".\WM_SYNCHRONISED_LYRICS.ahk" {WM_SYNCHRONISED_LYRICS}
#Import export ".\WM_USER_TEXT.ahk" {WM_USER_TEXT}
#Import export ".\WM_USER_WEB_URL.ahk" {WM_USER_WEB_URL}
#Import export ".\WM_WRITER_STATISTICS.ahk" {WM_WRITER_STATISTICS}
#Import export ".\WM_WRITER_STATISTICS_EX.ahk" {WM_WRITER_STATISTICS_EX}
#Import export ".\_AM_ASFWRITERCONFIG_PARAM.ahk" {_AM_ASFWRITERCONFIG_PARAM}
