#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\..\System\Com\IUnknown.ahk

/**
 * The IWMDRMWriter interface provides support for applying DRM protection to content in ASF files.
 * @see https://learn.microsoft.com/windows/win32/api/wmsdkidl/nn-wmsdkidl-iwmdrmwriter
 * @namespace Windows.Win32.Media.WindowsMediaFormat
 * @version v4.0.30319
 */
class IWMDRMWriter extends IUnknown{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IWMDRMWriter
     * @type {Guid}
     */
    static IID => Guid("{d6ea5dd0-12a0-43f4-90ab-a3fd451e6a07}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 3

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["GenerateKeySeed", "GenerateKeyID", "GenerateSigningKeyPair", "SetDRMAttribute"]

    /**
     * The GenerateKeySeed method generates a DRM key seed.
     * @remarks
     * This method is used infrequently because the same key seed should be used for multiple files. You can use the same key seed for every file created by an application, or distributed from the same server, or you can use it for some subset of files.
     * @param {PWSTR} pwszKeySeed Pointer to a wide-character <b>null</b>-terminated string containing the key seed. Set to <b>NULL</b> to retrieve the size of the string, which is returned in <i>pcwchLength</i>.
     * @param {Pointer<Integer>} pcwchLength Pointer to a <b>DWORD</b> containing the size, in wide characters, of <i>pwszKeySeed</i>. This size includes the terminating <b>null</b> character.
     * @returns {HRESULT} If the method succeeds, it returns S_OK. If it fails, it returns an <b>HRESULT</b> error code.
     * @see https://learn.microsoft.com/windows/win32/api/wmsdkidl/nf-wmsdkidl-iwmdrmwriter-generatekeyseed
     */
    GenerateKeySeed(pwszKeySeed, pcwchLength) {
        pwszKeySeed := pwszKeySeed is String ? StrPtr(pwszKeySeed) : pwszKeySeed

        pcwchLengthMarshal := pcwchLength is VarRef ? "uint*" : "ptr"

        result := ComCall(3, this, "ptr", pwszKeySeed, pcwchLengthMarshal, pcwchLength, "HRESULT")
        return result
    }

    /**
     * The GenerateKeyID method generates a DRM key ID.
     * @remarks
     * Each file should have its own key ID.
     * @param {PWSTR} pwszKeyID Pointer to a wide-character <b>null</b>-terminated string containing the key identifier. Set to <b>NULL</b> to retrieve the size of the string, which is returned in <i>pcwchLength</i>.
     * @param {Pointer<Integer>} pcwchLength Pointer to a <b>DWORD</b> containing the size, in wide characters, of <i>pwszKeyID</i>. This size includes the terminating <b>null</b> character.
     * @returns {HRESULT} If the method succeeds, it returns S_OK. If it fails, it returns an <b>HRESULT</b> error code.
     * @see https://learn.microsoft.com/windows/win32/api/wmsdkidl/nf-wmsdkidl-iwmdrmwriter-generatekeyid
     */
    GenerateKeyID(pwszKeyID, pcwchLength) {
        pwszKeyID := pwszKeyID is String ? StrPtr(pwszKeyID) : pwszKeyID

        pcwchLengthMarshal := pcwchLength is VarRef ? "uint*" : "ptr"

        result := ComCall(4, this, "ptr", pwszKeyID, pcwchLengthMarshal, pcwchLength, "HRESULT")
        return result
    }

    /**
     * The GenerateSigningKeyPair method generates a public and private key pair that are used to sign the DRM header object.
     * @remarks
     * Do not confuse the signature that is applied to the ASF header object, using these keys, with the signature that is applied to the DRM header object by using the <a href="https://docs.microsoft.com/windows/desktop/wmformat/drm-lasignatureprivkey">DRM_LASignaturePrivKey</a> and other properties that make up the digital signature object in the file.
     * 
     * The keys generated by this method are the basis for revocation lists, so the number of different key pairs you use will be based on your particular business needs. In general, the same key pair should be used for some set of content that forms a logical group and that shares the same revocation list.
     * @param {PWSTR} pwszPrivKey Pointer to a wide-character <b>null</b>-terminated string containing the private key. Set to <b>NULL</b> to retrieve the size of the string, which is returned in <i>pcwchPrivKeyLength</i>. Use this key to set the <a href="https://docs.microsoft.com/windows/desktop/wmformat/drm-headersignprivkey">DRM_HeaderSignPrivKey</a> property.
     * @param {Pointer<Integer>} pcwchPrivKeyLength Pointer to a <b>DWORD</b> containing the size, in wide characters, of <i>pwszPrivKey</i>. This size includes the terminating <b>null</b> character.
     * @param {PWSTR} pwszPubKey Pointer to a wide-character <b>null</b>-terminated string containing the public key. Set to <b>NULL</b> to retrieve the size of the string, which is returned in <i>pcwchPubKeyLength</i>. This key is shared only with the license server; it enables the license server to verify the signature of the DRM header object when users attempt to obtain a content license for a file.
     * @param {Pointer<Integer>} pcwchPubKeyLength Pointer to a <b>DWORD</b> containing the size, in wide characters, of <i>pwsPubKey</i>. This size includes the terminating <b>null</b> character.
     * @returns {HRESULT} If the method succeeds, it returns S_OK. If it fails, it returns an <b>HRESULT</b> error code.
     * @see https://learn.microsoft.com/windows/win32/api/wmsdkidl/nf-wmsdkidl-iwmdrmwriter-generatesigningkeypair
     */
    GenerateSigningKeyPair(pwszPrivKey, pcwchPrivKeyLength, pwszPubKey, pcwchPubKeyLength) {
        pwszPrivKey := pwszPrivKey is String ? StrPtr(pwszPrivKey) : pwszPrivKey
        pwszPubKey := pwszPubKey is String ? StrPtr(pwszPubKey) : pwszPubKey

        pcwchPrivKeyLengthMarshal := pcwchPrivKeyLength is VarRef ? "uint*" : "ptr"
        pcwchPubKeyLengthMarshal := pcwchPubKeyLength is VarRef ? "uint*" : "ptr"

        result := ComCall(5, this, "ptr", pwszPrivKey, pcwchPrivKeyLengthMarshal, pcwchPrivKeyLength, "ptr", pwszPubKey, pcwchPubKeyLengthMarshal, pcwchPubKeyLength, "HRESULT")
        return result
    }

    /**
     * The SetDRMAttribute method sets DRM-header attributes as well as other DRM run-time properties.
     * @remarks
     * This method is somewhat misnamed because it is used to set not only writable DRM file attributes (See <a href="https://docs.microsoft.com/windows/desktop/wmformat/drm-attribute-list">DRM Attribute List</a>), but also certain DRM properties that are used by the DRM run-time components but are not written to the DRM header in the file. (See <a href="https://docs.microsoft.com/windows/desktop/wmformat/drm-properties">DRM Properties</a>.)
     * 
     * The properties <b>Use_Advanced_DRM</b> and <b>Use_DRM</b> may be specified before a profile is set. No other properties can be set before a profile is set. The following code snippet shows how to call this function, using the <a href="https://docs.microsoft.com/windows/desktop/wmformat/drm-contentid">DRM_ContentID</a> property as an example. Assume that <i>pDRMWriter</i> is a <b>IWMDRMWriter</b> interface pointer, and <i>wszContentID</i> is an array of type <b>WCHAR</b>.
     * 
     * 
     * ```cpp
     * 
     * hr = pDRMWriter->SetDRMAttribute( 0, g_wszWMDRM_ContentID, 
     *         WMT_TYPE_STRING, (BYTE *)wszContentID, 
     *         ( wcslen( wszContentID ) + 1 ) * sizeof( WCHAR ) );
     * 
     * ```
     * @param {Integer} wStreamNum <b>WORD</b> containing the stream number to which the attribute applies.
     * @param {PWSTR} pszName Pointer to a null-terminated string containing the attribute name. See Remarks for supported attributes.
     * @param {Integer} Type A value from the <a href="https://docs.microsoft.com/windows/desktop/api/wmsdkidl/ne-wmsdkidl-wmt_attr_datatype">WMT_ATTR_DATATYPE</a> enumeration type specifying the data type of the attribute data.
     * @param {Pointer<Integer>} pValue Pointer to an array of bytes containing the attribute data.
     * @param {Integer} cbLength The size, in bytes, of the attribute data pointed to by <i>pValue</i>.
     * @returns {HRESULT} If the method succeeds, it returns S_OK. If it fails, it returns an <b>HRESULT</b> error code.
     * @see https://learn.microsoft.com/windows/win32/api/wmsdkidl/nf-wmsdkidl-iwmdrmwriter-setdrmattribute
     */
    SetDRMAttribute(wStreamNum, pszName, Type, pValue, cbLength) {
        pszName := pszName is String ? StrPtr(pszName) : pszName

        pValueMarshal := pValue is VarRef ? "char*" : "ptr"

        result := ComCall(6, this, "ushort", wStreamNum, "ptr", pszName, "int", Type, pValueMarshal, pValue, "ushort", cbLength, "HRESULT")
        return result
    }
}
