#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\..\System\Com\IUnknown.ahk

/**
 * The IWMLicenseRevocationAgent interface handles messages from a DRM license server that involve license revocation.IWMLicenseRevocationAgent is the primary interface of the license revocation agent object.
 * @remarks
 * License revocation enables a license issuer to remove licenses from a computer.
 * @see https://learn.microsoft.com/windows/win32/api//content/wmsdkidl/nn-wmsdkidl-iwmlicenserevocationagent
 * @namespace Windows.Win32.Media.WindowsMediaFormat
 * @version v4.0.30319
 */
class IWMLicenseRevocationAgent extends IUnknown{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IWMLicenseRevocationAgent
     * @type {Guid}
     */
    static IID => Guid("{6967f2c9-4e26-4b57-8894-799880f7ac7b}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 3

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["GetLRBChallenge", "ProcessLRB"]

    /**
     * The GetLRBChallenge method generates a response to a license revocation challenge message. Your application must send the response to the license server.
     * @remarks
     * The license server generates the challenge as the result of user interaction. This process is typically managed by a Web component. The challenge response generated by calling this method must be sent back to the license server.
     * 
     * After the challenge and response have been processed, the license server sends a signed license revocation blob, which includes instructions about the licenses to remove. You can perform the license revocation by calling the <a href="https://docs.microsoft.com/windows/desktop/api/wmsdkidl/nf-wmsdkidl-iwmlicenserevocationagent-processlrb">ProcessLRB</a> method.
     * @param {Pointer<Integer>} pMachineID Address of the machine identifier in memory. The format of the machine identifier is determined by the service that issued the license.
     * @param {Integer} dwMachineIDLength Size of the machine identifier in bytes.
     * @param {Pointer<Integer>} pChallenge Address of the challenge message in memory. This message is generated by a component created by the license issuer.
     * @param {Integer} dwChallengeLength Size of the challenge message in bytes.
     * @param {Pointer<Integer>} pChallengeOutput Address of a buffer that receives the challenge response message.
     * @param {Pointer<Integer>} pdwChallengeOutputLength Address of a variable that receives the size of the challenge response message in bytes.
     * @returns {HRESULT} The method returns an <b>HRESULT</b>. Possible values include, but are not limited to, those in the following table.
     * 
     * <table>
     * <tr>
     * <th>Return code</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>S_OK</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The method succeeded.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api//content/wmsdkidl/nf-wmsdkidl-iwmlicenserevocationagent-getlrbchallenge
     */
    GetLRBChallenge(pMachineID, dwMachineIDLength, pChallenge, dwChallengeLength, pChallengeOutput, pdwChallengeOutputLength) {
        pMachineIDMarshal := pMachineID is VarRef ? "char*" : "ptr"
        pChallengeMarshal := pChallenge is VarRef ? "char*" : "ptr"
        pChallengeOutputMarshal := pChallengeOutput is VarRef ? "char*" : "ptr"
        pdwChallengeOutputLengthMarshal := pdwChallengeOutputLength is VarRef ? "uint*" : "ptr"

        result := ComCall(3, this, pMachineIDMarshal, pMachineID, "uint", dwMachineIDLength, pChallengeMarshal, pChallenge, "uint", dwChallengeLength, pChallengeOutputMarshal, pChallengeOutput, pdwChallengeOutputLengthMarshal, pdwChallengeOutputLength, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return result
    }

    /**
     * The ProcessLRB method removes licenses from the license store on the client computer.
     * @remarks
     * The license server sends the signed license revocation blob after receiving a response to its initial challenge message. For more information, see <a href="https://docs.microsoft.com/windows/desktop/api/wmsdkidl/nf-wmsdkidl-iwmlicenserevocationagent-getlrbchallenge">GetLRBChallenge</a>.
     * @param {Pointer<Integer>} pSignedLRB Address of the signed license revocation blob in memory. This blob is sent to your application by the license server.
     * @param {Integer} dwSignedLRBLength Size of the license revocation blob in bytes.
     * @param {Pointer<Integer>} pSignedACK Address of a buffer that receives the signed acknowledgment of license revocation. Your application must send the acknowledgment to the license server.
     * @param {Pointer<Integer>} pdwSignedACKLength Size of the acknowledgment in bytes.
     * @returns {HRESULT} The method returns an <b>HRESULT</b>. Possible values include, but are not limited to, those in the following table.
     * 
     * <table>
     * <tr>
     * <th>Return code</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>S_OK</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The method succeeded.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://learn.microsoft.com/windows/win32/api//content/wmsdkidl/nf-wmsdkidl-iwmlicenserevocationagent-processlrb
     */
    ProcessLRB(pSignedLRB, dwSignedLRBLength, pSignedACK, pdwSignedACKLength) {
        pSignedLRBMarshal := pSignedLRB is VarRef ? "char*" : "ptr"
        pSignedACKMarshal := pSignedACK is VarRef ? "char*" : "ptr"
        pdwSignedACKLengthMarshal := pdwSignedACKLength is VarRef ? "uint*" : "ptr"

        result := ComCall(4, this, pSignedLRBMarshal, pSignedLRB, "uint", dwSignedLRBLength, pSignedACKMarshal, pSignedACK, pdwSignedACKLengthMarshal, pdwSignedACKLength, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return result
    }
}
