#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import "..\..\Foundation\LPARAM.ahk" { LPARAM }
#Import "..\..\Foundation\PWSTR.ahk" { PWSTR }

/**
 * The WM_READER_CLIENTINFO structure describes the client reader (player) accessing the media stream.
 * @remarks
 * In earlier versions of this SDK, the <b>pReserved</b> member was named <b>wszHostUniquePID</b>. The application used this member to specify an ID to send to the server. In the current version, the reader object automatically generates a GUID for the ID, so this structure member is obsolete. It is present only to provide binary compatibility with earlier versions of the SDK.
 * 
 * The GUID generated by the reader object represents a unique user on a particular computer. The reader object stores this value in the registry. If the registry entry does not exist, the SDK dynamically creates it. For more information, see <a href="https://docs.microsoft.com/windows/desktop/api/wmsdkidl/nf-wmsdkidl-iwmreaderadvanced2-setlogclientid">IWMReaderAdvanced2::SetLogClientID</a>.
 * @see https://learn.microsoft.com/windows/win32/api/wmsdkidl/ns-wmsdkidl-wm_reader_clientinfo
 * @namespace Windows.Win32.Media.WindowsMediaFormat
 */
export default struct WM_READER_CLIENTINFO {
    #StructPack 8

    /**
     * Size of the structure in bytes.
     */
    cbSize : UInt32 := this.Size

    /**
     * Two-letter or three-letter language code.
     */
    wszLang : PWSTR

    /**
     * The browser's user-agent string.
     */
    wszBrowserUserAgent : PWSTR

    /**
     * Web page that contains the <a href="https://docs.microsoft.com/windows/desktop/wmformat/wmformat-glossary">plug-in</a>.
     */
    wszBrowserWebPage : PWSTR

    /**
     * Reserved.
     */
    qwReserved : Int64

    /**
     * Unused. See Remarks.
     */
    pReserved : LPARAM.Ptr

    /**
     * Host application's .exe file; for example, Iexplore.exe.
     */
    wszHostExe : PWSTR

    /**
     * Version number of the host application. The value is four unsigned <b>WORD</b> values packed into a 64-bit integer. When the client information is logged, each <b>WORD</b> value is unpacked and translated into its decimal equivalent. For example, if the value is 0x0001000200030004, the version number is logged as "1.2.3.4".
     */
    qwHostVersion : Int64

    /**
     * String identifying the player application. For example, "WMPlayer/9.0.0.0" identifies version 9 of the Windows Media Player.
     */
    wszPlayerUserAgent : PWSTR

}
