#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ADRENTRY.ahk" {ADRENTRY}
#Import export ".\ADRLIST.ahk" {ADRLIST}
#Import export ".\ADRPARM.ahk" {ADRPARM}
#Import export ".\Apis.ahk" {*}
#Import export ".\CALLERRELEASE.ahk" {CALLERRELEASE}
#Import export ".\Constants.ahk" {*}
#Import export ".\DTBLBUTTON.ahk" {DTBLBUTTON}
#Import export ".\DTBLCHECKBOX.ahk" {DTBLCHECKBOX}
#Import export ".\DTBLCOMBOBOX.ahk" {DTBLCOMBOBOX}
#Import export ".\DTBLDDLBX.ahk" {DTBLDDLBX}
#Import export ".\DTBLEDIT.ahk" {DTBLEDIT}
#Import export ".\DTBLGROUPBOX.ahk" {DTBLGROUPBOX}
#Import export ".\DTBLLABEL.ahk" {DTBLLABEL}
#Import export ".\DTBLLBX.ahk" {DTBLLBX}
#Import export ".\DTBLMVDDLBX.ahk" {DTBLMVDDLBX}
#Import export ".\DTBLMVLISTBOX.ahk" {DTBLMVLISTBOX}
#Import export ".\DTBLPAGE.ahk" {DTBLPAGE}
#Import export ".\DTBLRADIOBUTTON.ahk" {DTBLRADIOBUTTON}
#Import export ".\DTCTL.ahk" {DTCTL}
#Import export ".\DTPAGE.ahk" {DTPAGE}
#Import export ".\ENTRYID.ahk" {ENTRYID}
#Import export ".\ERROR_NOTIFICATION.ahk" {ERROR_NOTIFICATION}
#Import export ".\EXTENDED_NOTIFICATION.ahk" {EXTENDED_NOTIFICATION}
#Import export ".\FLATENTRY.ahk" {FLATENTRY}
#Import export ".\FLATENTRYLIST.ahk" {FLATENTRYLIST}
#Import export ".\FLATMTSIDLIST.ahk" {FLATMTSIDLIST}
#Import export ".\FlagList.ahk" {FlagList}
#Import export ".\Gender.ahk" {Gender}
#Import export ".\IABContainer.ahk" {IABContainer}
#Import export ".\IAddrBook.ahk" {IAddrBook}
#Import export ".\IAttach.ahk" {IAttach}
#Import export ".\IDistList.ahk" {IDistList}
#Import export ".\IMAPIAdviseSink.ahk" {IMAPIAdviseSink}
#Import export ".\IMAPIContainer.ahk" {IMAPIContainer}
#Import export ".\IMAPIControl.ahk" {IMAPIControl}
#Import export ".\IMAPIFolder.ahk" {IMAPIFolder}
#Import export ".\IMAPIProgress.ahk" {IMAPIProgress}
#Import export ".\IMAPIProp.ahk" {IMAPIProp}
#Import export ".\IMAPIStatus.ahk" {IMAPIStatus}
#Import export ".\IMAPITable.ahk" {IMAPITable}
#Import export ".\IMailUser.ahk" {IMailUser}
#Import export ".\IMessage.ahk" {IMessage}
#Import export ".\IMsgStore.ahk" {IMsgStore}
#Import export ".\IProfSect.ahk" {IProfSect}
#Import export ".\IPropData.ahk" {IPropData}
#Import export ".\IProviderAdmin.ahk" {IProviderAdmin}
#Import export ".\ITableData.ahk" {ITableData}
#Import export ".\IWABExtInit.ahk" {IWABExtInit}
#Import export ".\IWABObject.ahk" {IWABObject}
#Import export ".\LPALLOCATEBUFFER.ahk" {LPALLOCATEBUFFER}
#Import export ".\LPALLOCATEMORE.ahk" {LPALLOCATEMORE}
#Import export ".\LPCREATECONVERSATIONINDEX.ahk" {LPCREATECONVERSATIONINDEX}
#Import export ".\LPDISPATCHNOTIFICATIONS.ahk" {LPDISPATCHNOTIFICATIONS}
#Import export ".\LPFNABSDI.ahk" {LPFNABSDI}
#Import export ".\LPFNBUTTON.ahk" {LPFNBUTTON}
#Import export ".\LPFNDISMISS.ahk" {LPFNDISMISS}
#Import export ".\LPFREEBUFFER.ahk" {LPFREEBUFFER}
#Import export ".\LPNOTIFCALLBACK.ahk" {LPNOTIFCALLBACK}
#Import export ".\LPOPENSTREAMONFILE.ahk" {LPOPENSTREAMONFILE}
#Import export ".\LPWABACTIONITEM.ahk" {LPWABACTIONITEM}
#Import export ".\LPWABALLOCATEBUFFER.ahk" {LPWABALLOCATEBUFFER}
#Import export ".\LPWABALLOCATEMORE.ahk" {LPWABALLOCATEMORE}
#Import export ".\LPWABFREEBUFFER.ahk" {LPWABFREEBUFFER}
#Import export ".\LPWABOPEN.ahk" {LPWABOPEN}
#Import export ".\LPWABOPENEX.ahk" {LPWABOPENEX}
#Import export ".\MAPIERROR.ahk" {MAPIERROR}
#Import export ".\MAPINAMEID.ahk" {MAPINAMEID}
#Import export ".\MAPIUID.ahk" {MAPIUID}
#Import export ".\MTSID.ahk" {MTSID}
#Import export ".\NEWMAIL_NOTIFICATION.ahk" {NEWMAIL_NOTIFICATION}
#Import export ".\NOTIFICATION.ahk" {NOTIFICATION}
#Import export ".\NOTIFKEY.ahk" {NOTIFKEY}
#Import export ".\OBJECT_NOTIFICATION.ahk" {OBJECT_NOTIFICATION}
#Import export ".\PFNIDLE.ahk" {PFNIDLE}
#Import export ".\SAndRestriction.ahk" {SAndRestriction}
#Import export ".\SAppTimeArray.ahk" {SAppTimeArray}
#Import export ".\SBinary.ahk" {SBinary}
#Import export ".\SBinaryArray.ahk" {SBinaryArray}
#Import export ".\SBitMaskRestriction.ahk" {SBitMaskRestriction}
#Import export ".\SCommentRestriction.ahk" {SCommentRestriction}
#Import export ".\SComparePropsRestriction.ahk" {SComparePropsRestriction}
#Import export ".\SContentRestriction.ahk" {SContentRestriction}
#Import export ".\SCurrencyArray.ahk" {SCurrencyArray}
#Import export ".\SDateTimeArray.ahk" {SDateTimeArray}
#Import export ".\SDoubleArray.ahk" {SDoubleArray}
#Import export ".\SExistRestriction.ahk" {SExistRestriction}
#Import export ".\SGuidArray.ahk" {SGuidArray}
#Import export ".\SLPSTRArray.ahk" {SLPSTRArray}
#Import export ".\SLargeIntegerArray.ahk" {SLargeIntegerArray}
#Import export ".\SLongArray.ahk" {SLongArray}
#Import export ".\SNotRestriction.ahk" {SNotRestriction}
#Import export ".\SOrRestriction.ahk" {SOrRestriction}
#Import export ".\SPropProblem.ahk" {SPropProblem}
#Import export ".\SPropProblemArray.ahk" {SPropProblemArray}
#Import export ".\SPropTagArray.ahk" {SPropTagArray}
#Import export ".\SPropValue.ahk" {SPropValue}
#Import export ".\SPropertyRestriction.ahk" {SPropertyRestriction}
#Import export ".\SRealArray.ahk" {SRealArray}
#Import export ".\SRestriction.ahk" {SRestriction}
#Import export ".\SRow.ahk" {SRow}
#Import export ".\SRowSet.ahk" {SRowSet}
#Import export ".\SShortArray.ahk" {SShortArray}
#Import export ".\SSizeRestriction.ahk" {SSizeRestriction}
#Import export ".\SSortOrder.ahk" {SSortOrder}
#Import export ".\SSortOrderSet.ahk" {SSortOrderSet}
#Import export ".\SSubRestriction.ahk" {SSubRestriction}
#Import export ".\STATUS_OBJECT_NOTIFICATION.ahk" {STATUS_OBJECT_NOTIFICATION}
#Import export ".\SWStringArray.ahk" {SWStringArray}
#Import export ".\TABLE_NOTIFICATION.ahk" {TABLE_NOTIFICATION}
#Import export ".\WABEXTDISPLAY.ahk" {WABEXTDISPLAY}
#Import export ".\WABIMPORTPARAM.ahk" {WABIMPORTPARAM}
#Import export ".\WAB_PARAM.ahk" {WAB_PARAM}
#Import export ".\__UPV.ahk" {__UPV}
