#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\Win32Enum.ahk

/**
 * Provides flags that listeners use to filter tracing events.
 * @remarks
 * The CausalitySource flags describe which architectural layer of the app is producing causality information.
 * @see https://learn.microsoft.com/uwp/api/windows.foundation.diagnostics.causalitysource
 * @namespace Windows.Foundation.Diagnostics
 * @version WindowsRuntime 1.4
 */
class CausalitySource extends Win32Enum{

    /**
     * Indicates causality information generated by app-defined asynchronous operations.
     * @type {Integer (Int32)}
     */
    static Application => 0

    /**
     * Indicates causality information generated by language projections or asynchronous infrastructure libraries.
     * @type {Integer (Int32)}
     */
    static Library => 1

    /**
     * Indicates causality information generated by Windows.
     * @type {Integer (Int32)}
     */
    static System => 2
}
