#Requires AutoHotkey v2.0 64-bit

#Include ..\..\Win32\System\WinRT\Apis.ahk
#Include ..\..\Win32\System\WinRT\HSTRING.ahk
#Include ..\..\Win32\System\WinRT\IInspectable.ahk
#Include .\IFileLoggingSession.ahk
#Include ..\IClosable.ahk
#Include .\IFileLoggingSessionFactory.ahk
#Include ..\TypedEventHandler.ahk
#Include .\LogFileGeneratedEventArgs.ahk
#Include ..\..\..\Guid.ahk
#Include ..\..\..\WinRTEventHandler.ahk

/**
 * Represents the destination of logged messages from [LoggingChannel](loggingchannel.md) instances.
 * @remarks
 * Use the **FileLoggingSession** class to log messages and data to a file continuously as your app runs. You can view the log files by using the Windows Performance Toolkit (WPT) and other utilities like tracerpt.exe.
 * 
 * Add [LoggingChannel](loggingchannel.md) instances to a **FileLoggingSession**, and call **FileLoggingSession** instance methods to remove channels, dispose, and perform other operations. The number of channels is not currently limited.
 * 
 * > [!NOTE]
 * > In **Windows Server 2012 R2** and **Windows 8.1**, each app is limited to 4 active channels, and channels must have unique names.
 * 
 * The **FileLoggingSession** class sends logged messages to disk files when a buffer is filled or when the user calls [CloseAndSaveToFileAsync](fileloggingsession_closeandsavetofileasync_867561099.md). The **FileLoggingSession** class uses sequential logging, which means that all messages are sent to a disk file, and a sequential history of messages is retained. This is distinct from the [LoggingSession](loggingsession.md) class, which sends logged messages to disk on-demand, i.e. when the app detects a problem and saves the in-memory messages for analysis.
 * 
 * Use the **FileLoggingSession** class when you know that all messages need to be saved, usually over a long period of time, and when the app can't be burdened with on-demand saving steps. Like the [LoggingSession](loggingsession.md) class, [LoggingChannel](loggingchannel.md) instances are added to a **FileLoggingSession** instance, and the **FileLoggingSession** instance has methods to remove channels and dispose. **FileLoggingSession** instances are initialized with a delegate to a new file callback, which notifies the app when a log file rollover has occurred. The feature invokes the delegate when the current internal log file has reached capacity and a new file is being created for continued sequential logging. The delegate callback can also be called at suspend boundaries, or when the **FileLoggingSession** is disposed.
 * 
 * When the [LogFileGenerated](fileloggingsession_logfilegenerated.md) event is invoked, the app receives an [StorageFile](../windows.storage/storagefile.md) that represents the now-closed log file. The app can forward the log file for processing in an application-defined way. After this, the session continues logging to a newly created and now-open current log file. When this log file reaches capacity, the callback delegate is invoked again for the new file, and the process repeats.
 * 
 * When you are done logging events, call [CloseAndSaveToFileAsync](fileloggingsession_closeandsavetofileasync_867561099.md) in order to get the last log file since the last log file may be still open if it has not yet reached capacity. You can also use [CloseAndSaveToFileAsync](fileloggingsession_closeandsavetofileasync_867561099.md) to close the session and get access to the last log file. Note that if the last log file was empty, or if all log files have already been reported by the [LogFileGenerated](fileloggingsession_logfilegenerated.md) method, the [CloseAndSaveToFileAsync](fileloggingsession_closeandsavetofileasync_867561099.md) method will return null.
 * 
 * The log files are created in the **ApplicationData\Logs** folder.
 * 
 * The name of each log file is based on the name of the session plus an index. The index is reset each time a new session is created. Each time a log file reaches maximum size, it is closed, the index is incremented, and a new log file is opened using the new index. (As a consequence, each time you restart an app, it will begin overwriting the log files generated by the previous instance of the app.)
 * 
 * You can add a handler for the [LogFileGenerated](fileloggingsession_logfilegenerated.md) event so that your app is notified each time a log file is closed.
 * 
 * If you do not use the [LogFileGenerated](fileloggingsession_logfilegenerated.md) event or the [CloseAndSaveToFileAsync](fileloggingsession_closeandsavetofileasync_867561099.md) method, the **FileLoggingSession** will not delete stale log files (though a new session may overwrite files generated by a previous session). Your app is responsible for locating and cleaning up the log files as needed.
 * 
 * Before a log file is provided to an app via the [LogFileGenerated](fileloggingsession_logfilegenerated.md) event or the [CloseAndSaveToFileAsync](fileloggingsession_closeandsavetofileasync_867561099.md) method, it is renamed to a special log file name. The same log file name is always used, so new logs will overwrite older logs. In this way, the [LogFileGenerated](fileloggingsession_logfilegenerated.md) event and [CloseAndSaveToFileAsync](fileloggingsession_closeandsavetofileasync_867561099.md) methods help prevent stale log files from wasting space in the ApplicationData folder.
 * 
 * **FileLoggingSession** will close the current log file and start a new log file when the current log file reaches 256KB.
 * @see https://learn.microsoft.com/uwp/api/windows.foundation.diagnostics.fileloggingsession
 * @namespace Windows.Foundation.Diagnostics
 * @version WindowsRuntime 1.4
 */
class FileLoggingSession extends IInspectable {
;@region Static Properties
    /**
     * The default interface of is Windows Runtime class. At the ABI level, the class is really
     * just a pointer to this interface
     * @type {Class}
     */
    static WinRTDefaultInterface => IFileLoggingSession

    /**
     * The IID of this class's default interface. This allows it to be cast using IUnknown::As like any
     * Windows Runtime interface
     * @type {Guid}
     */
    static IID => IFileLoggingSession.IID

;@endregion Static Properties

;@region Static Methods
    /**
     * Initializes a new instance of the [FileLoggingSession](fileloggingsession.md) class.
     * @param {HSTRING} name The name of the logging session.
     * @returns {FileLoggingSession} 
     * @see https://learn.microsoft.com/uwp/api/windows.foundation.diagnostics.fileloggingsession.#ctor
     */
    static Create(name) {
        if (!FileLoggingSession.HasProp("__IFileLoggingSessionFactory")) {
            activatableClassId := HSTRING.Create("Windows.Foundation.Diagnostics.FileLoggingSession")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IFileLoggingSessionFactory.IID)
            FileLoggingSession.__IFileLoggingSessionFactory := IFileLoggingSessionFactory(factoryPtr)
        }

        return FileLoggingSession.__IFileLoggingSessionFactory.Create(name)
    }

;@endregion Static Methods

;@region Instance Properties
    /**
     * Gets the name of the logging session.
     * @see https://learn.microsoft.com/uwp/api/windows.foundation.diagnostics.fileloggingsession.name
     * @type {HSTRING} 
     */
    Name {
        get => this.get_Name()
    }

    /**
     * Raised when a log file is saved.
     * @remarks
     * If no handler is registered for this event, log files will accumulate in the ApplicationData folder.
     * 
     * This event is raised when the session rolls over from one log file to the next. If the file needs to be preserved, your handler must move the file to a new location before returning. The FileLoggingSession might delete or overwrite the file anytime after your handler has returned.
     * 
     * When you register a handler for this event, if log files had been saved while there was no handler registered for this event, your newly-added handler will immediately be invoked once for each of the previously-saved log files.
     * 
     * Your handler must do any processing necessary to preserve the file.
     * 
     * This event is not raised for the last log file because the last log file does not roll over. Use [CloseAndSaveToFileAsync](fileloggingsession_closeandsavetofileasync_867561099.md) to access the last log file.
     * @type {TypedEventHandler<IFileLoggingSession, LogFileGeneratedEventArgs>}
    */
    OnLogFileGenerated {
        get {
            if(!this.HasProp("__OnLogFileGenerated")){
                this.__OnLogFileGenerated := WinRTEventHandler(
                    TypedEventHandler,
                    Guid("{0c6563b0-9d8b-5b60-994b-dee1174d1efb}"),
                    IFileLoggingSession,
                    LogFileGeneratedEventArgs
                )
                this.__OnLogFileGeneratedToken := this.add_LogFileGenerated(this.__OnLogFileGenerated.iface)
            }
            return this.__OnLogFileGenerated
        }
    }

;@endregion Instance Properties

;@region Instance Methods
    __New(ptr) {
        super.__New(ptr)
    }

    __Delete() {
        if(this.HasProp("__OnLogFileGeneratedToken")) {
            this.remove_LogFileGenerated(this.__OnLogFileGeneratedToken)
            this.__OnLogFileGenerated.iface.Dispose()
        }

        this.Close()

        super.__Delete()
    }

    /**
     * 
     * @returns {HSTRING} 
     */
    get_Name() {
        if (!this.HasProp("__IFileLoggingSession")) {
            if ((queryResult := this.QueryInterface(IFileLoggingSession.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IFileLoggingSession := IFileLoggingSession(outPtr)
        }

        return this.__IFileLoggingSession.get_Name()
    }

    /**
     * Adds a logging channel to the current logging session.
     * @remarks
     * The logging level is set to **LoggingLevel.Verbose**. The **LoggingChannel ** will accept all events.
     * 
     * Adding a channel to a session more than once updates the level.
     * @param {ILoggingChannel} loggingChannel_ The logging channel to add.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.foundation.diagnostics.fileloggingsession.addloggingchannel
     */
    AddLoggingChannel(loggingChannel_) {
        if (!this.HasProp("__IFileLoggingSession")) {
            if ((queryResult := this.QueryInterface(IFileLoggingSession.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IFileLoggingSession := IFileLoggingSession(outPtr)
        }

        return this.__IFileLoggingSession.AddLoggingChannel(loggingChannel_)
    }

    /**
     * Adds a logging channel to the current logging session. The logging channel only accepts events that have a logging level at or above the specified logging level.
     * @remarks
     * *maxLevel* specifies the which events from the channel the session will accept and which are ignored. It does not change the level of the channel itself.
     * @param {ILoggingChannel} loggingChannel_ The logging channel to add.
     * @param {Integer} maxLevel The *minimum* logging level that an event must have to be accepted by the session.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.foundation.diagnostics.fileloggingsession.addloggingchannel
     */
    AddLoggingChannelWithLevel(loggingChannel_, maxLevel) {
        if (!this.HasProp("__IFileLoggingSession")) {
            if ((queryResult := this.QueryInterface(IFileLoggingSession.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IFileLoggingSession := IFileLoggingSession(outPtr)
        }

        return this.__IFileLoggingSession.AddLoggingChannelWithLevel(loggingChannel_, maxLevel)
    }

    /**
     * Removes the specified logging channel from the current logging session.
     * @param {ILoggingChannel} loggingChannel_ The logging channel to remove.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.foundation.diagnostics.fileloggingsession.removeloggingchannel
     */
    RemoveLoggingChannel(loggingChannel_) {
        if (!this.HasProp("__IFileLoggingSession")) {
            if ((queryResult := this.QueryInterface(IFileLoggingSession.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IFileLoggingSession := IFileLoggingSession(outPtr)
        }

        return this.__IFileLoggingSession.RemoveLoggingChannel(loggingChannel_)
    }

    /**
     * Ends the current logging session and saves it to a file.
     * @remarks
     * FileLoggingSession.CloseAndSaveToFileAsync closes the current logging session. If there is a handler for the [LogFileGenerated](fileloggingsession_logfilegenerated.md) method, and it has been called but not returned, the function waits for the handler to return. If there is any data in the current log file that has not already been reported with the [LogFileGenerated](fileloggingsession_logfilegenerated.md) event, the function returns a [StorageFile](../windows.storage/storagefile.md) representing that file.
     * 
     * Otherwise, the function returns **NULL**. This can happen if the current log file is empty, or if all log files have already been reported via the [LogFileGenerated](fileloggingsession_logfilegenerated.md) event. Note that CloseAndSaveToFileAsync might return **NULL** even if data was recorded and even if there is no [LogFileGenerated](fileloggingsession_logfilegenerated.md) event. This can happen if the log file became full and was closed, and a new log file was opened immediately before CloseAndSaveToFileAsync was called.
     * 
     * This function is equivalent to [FileLoggingSession.Close](fileloggingsession_close_811482585.md).
     * @returns {IAsyncOperation<StorageFile>} 
     * @see https://learn.microsoft.com/uwp/api/windows.foundation.diagnostics.fileloggingsession.closeandsavetofileasync
     */
    CloseAndSaveToFileAsync() {
        if (!this.HasProp("__IFileLoggingSession")) {
            if ((queryResult := this.QueryInterface(IFileLoggingSession.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IFileLoggingSession := IFileLoggingSession(outPtr)
        }

        return this.__IFileLoggingSession.CloseAndSaveToFileAsync()
    }

    /**
     * 
     * @param {TypedEventHandler<IFileLoggingSession, LogFileGeneratedEventArgs>} handler 
     * @returns {EventRegistrationToken} 
     */
    add_LogFileGenerated(handler) {
        if (!this.HasProp("__IFileLoggingSession")) {
            if ((queryResult := this.QueryInterface(IFileLoggingSession.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IFileLoggingSession := IFileLoggingSession(outPtr)
        }

        return this.__IFileLoggingSession.add_LogFileGenerated(handler)
    }

    /**
     * 
     * @param {EventRegistrationToken} token 
     * @returns {HRESULT} 
     */
    remove_LogFileGenerated(token) {
        if (!this.HasProp("__IFileLoggingSession")) {
            if ((queryResult := this.QueryInterface(IFileLoggingSession.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IFileLoggingSession := IFileLoggingSession(outPtr)
        }

        return this.__IFileLoggingSession.remove_LogFileGenerated(token)
    }

    /**
     * Ends the current logging session.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.foundation.diagnostics.fileloggingsession.close
     */
    Close() {
        if (!this.HasProp("__IClosable")) {
            if ((queryResult := this.QueryInterface(IClosable.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IClosable := IClosable(outPtr)
        }

        return this.__IClosable.Close()
    }

;@endregion Instance Methods
}
