#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\..\..\Win32\System\WinRT\IInspectable.ahk

/**
 * Provides methods that enable the XAML parser to communicate with generated binding code.
 * @remarks
 * This interface is for use in code that is generated by the XAML compiler.
 * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.idatatemplatecomponent
 * @namespace Windows.UI.Xaml.Markup
 * @version WindowsRuntime 1.4
 */
class IDataTemplateComponent extends IInspectable{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IDataTemplateComponent
     * @type {Guid}
     */
    static IID => Guid("{08429dc8-8ab0-4747-aa9a-feadfc8da8e1}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 6

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["Recycle", "ProcessBindings"]

    /**
     * Disassociates item containers from their data items and saves the containers so they can be reused later for other data items.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.idatatemplatecomponent.recycle
     */
    Recycle() {
        result := ComCall(6, this, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return result
    }

    /**
     * Updates the compiled data bindings.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} item The data item.
     * @param {Integer} itemIndex The index of the data item.
     * @param {Integer} phase The number of times ProcessBindings has been called.
     * @param {Pointer<Int32>} nextPhase The phase on the next call to ProcessBindings.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.idatatemplatecomponent.processbindings
     */
    ProcessBindings(item, itemIndex, phase, nextPhase) {
        result := ComCall(7, this, "ptr", item, "int", itemIndex, "int", phase, "ptr", nextPhase, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return result
    }
}
