#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\..\..\Win32\System\WinRT\IInspectable.ahk

/**
 * Provides methods that enable a debugger to disable generated binding code.
 * @remarks
 * This interface is for use in code that is generated by the XAML compiler.
 * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.ixamlbindscopediagnostics
 * @namespace Windows.UI.Xaml.Markup
 * @version WindowsRuntime 1.4
 */
class IXamlBindScopeDiagnostics extends IInspectable{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IXamlBindScopeDiagnostics
     * @type {Guid}
     */
    static IID => Guid("{f264a29d-bded-43aa-a5b0-26ac21a81eb8}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 6

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["Disable"]

    /**
     * Disables a binding while running in a debugger.
     * @param {Integer} lineNumber The line number of the x:Bind in the XAML source file.
     * @param {Integer} columnNumber The column number of the x:Bind in the XAML source file.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.ixamlbindscopediagnostics.disable
     */
    Disable(lineNumber, columnNumber) {
        result := ComCall(6, this, "int", lineNumber, "int", columnNumber, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return result
    }
}
