#Requires AutoHotkey v2.0 64-bit

#Include ..\..\..\Win32\System\WinRT\Apis.ahk
#Include ..\..\..\Win32\System\WinRT\HSTRING.ahk
#Include ..\..\..\Win32\System\WinRT\IInspectable.ahk
#Include .\IXamlBindingHelper.ahk
#Include .\IXamlBindingHelperStatics.ahk
#Include ..\..\..\..\Guid.ahk

/**
 * Provides helper methods for data binding.
 * @remarks
 * This class is for use in code that is generated by the XAML compiler.
 * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper
 * @namespace Windows.UI.Xaml.Markup
 * @version WindowsRuntime 1.4
 */
class XamlBindingHelper extends IInspectable {
;@region Static Properties
    /**
     * The default interface of is Windows Runtime class. At the ABI level, the class is really
     * just a pointer to this interface
     * @type {Class}
     */
    static WinRTDefaultInterface => IXamlBindingHelper

    /**
     * The IID of this class's default interface. This allows it to be cast using IUnknown::As like any
     * Windows Runtime interface
     * @type {Guid}
     */
    static IID => IXamlBindingHelper.IID

    /**
     * Identifies the [DataTemplateComponent](xamlbindinghelper_datatemplatecomponent.md) attached property.
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.datatemplatecomponentproperty
     * @type {DependencyProperty} 
     */
    static DataTemplateComponentProperty {
        get => XamlBindingHelper.get_DataTemplateComponentProperty()
    }

;@endregion Static Properties

;@region Static Methods
    /**
     * 
     * @returns {DependencyProperty} 
     */
    static get_DataTemplateComponentProperty() {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.get_DataTemplateComponentProperty()
    }

    /**
     * Gets the value of the [DataTemplateComponent](xamlbindinghelper_datatemplatecomponent.md) XAML attached property for a target element.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {DependencyObject} element The object from which the property value is read.
     * @returns {IDataTemplateComponent} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.getdatatemplatecomponent
     */
    static GetDataTemplateComponent(element) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.GetDataTemplateComponent(element)
    }

    /**
     * Sets the value of the [DataTemplateComponent](xamlbindinghelper_datatemplatecomponent.md) XAML attached property for a target element.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {DependencyObject} element The object to which the property value is written.
     * @param {IDataTemplateComponent} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setdatatemplatecomponent
     */
    static SetDataTemplateComponent(element, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetDataTemplateComponent(element, value)
    }

    /**
     * Suspends rendering of the specified element.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {UIElement} target The element for which to suspend rendering.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.suspendrendering
     */
    static SuspendRendering(target) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SuspendRendering(target)
    }

    /**
     * Resumes rendering of the specified element.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {UIElement} target The element for which to resume rendering.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.resumerendering
     */
    static ResumeRendering(target) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.ResumeRendering(target)
    }

    /**
     * Converts a value from a source type to a target type.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {TypeName} type The type to convert the value from.
     * @param {IInspectable} value The value to convert.
     * @returns {IInspectable} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.convertvalue
     */
    static ConvertValue(type, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.ConvertValue(type, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [String](/dotnet/api/system.string?view=dotnet-uwp-10.0&preserve-view=true) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {HSTRING} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromstring
     */
    static SetPropertyFromString(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromString(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Boolean](/dotnet/api/system.boolean?view=dotnet-uwp-10.0&preserve-view=true) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {Boolean} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromboolean
     */
    static SetPropertyFromBoolean(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromBoolean(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Char](/dotnet/api/system.char?view=dotnet-uwp-10.0&preserve-view=true) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {Integer} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromchar16
     */
    static SetPropertyFromChar16(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromChar16(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [DateTime](../windows.foundation/datetime.md) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {DateTime} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromdatetime
     */
    static SetPropertyFromDateTime(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromDateTime(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Double](/dotnet/api/system.double?view=dotnet-uwp-10.0&preserve-view=true) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {Float} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromdouble
     */
    static SetPropertyFromDouble(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromDouble(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Int32](/dotnet/api/system.int32?view=dotnet-uwp-10.0&preserve-view=true) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {Integer} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromint32
     */
    static SetPropertyFromInt32(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromInt32(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [UInt32](/dotnet/api/system.uint32?view=dotnet-uwp-10.0&preserve-view=true) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {Integer} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromuint32
     */
    static SetPropertyFromUInt32(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromUInt32(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Int64](/dotnet/api/system.int64?view=dotnet-uwp-10.0&preserve-view=true) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {Integer} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromint64
     */
    static SetPropertyFromInt64(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromInt64(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [UInt64](/dotnet/api/system.uint64?view=dotnet-uwp-10.0&preserve-view=true) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {Integer} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromuint64
     */
    static SetPropertyFromUInt64(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromUInt64(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Single](/dotnet/api/system.single?view=dotnet-uwp-10.0&preserve-view=true) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {Float} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromsingle
     */
    static SetPropertyFromSingle(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromSingle(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Point](../windows.foundation/point.md) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {POINT} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfrompoint
     */
    static SetPropertyFromPoint(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromPoint(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Rect](../windows.foundation/rect.md) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {RECT} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromrect
     */
    static SetPropertyFromRect(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromRect(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Size](../windows.foundation/size.md) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {SIZE} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromsize
     */
    static SetPropertyFromSize(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromSize(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [TimeSpan](../windows.foundation/timespan.md) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {TimeSpan} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromtimespan
     */
    static SetPropertyFromTimeSpan(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromTimeSpan(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Byte](/dotnet/api/system.byte?view=dotnet-uwp-10.0&preserve-view=true) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {Integer} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfrombyte
     */
    static SetPropertyFromByte(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromByte(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Uri](../windows.foundation/uri.md) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {Uri} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromuri
     */
    static SetPropertyFromUri(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromUri(dependencyObject_, propertyToSet, value)
    }

    /**
     * Sets a [DependencyProperty](../windows.ui.xaml/dependencyproperty.md) from a [Object](/dotnet/api/system.object?view=dotnet-uwp-10.0&preserve-view=true) value.
     * @remarks
     * This method is for use in code that is generated by the XAML compiler.
     * @param {IInspectable} dependencyObject_ The object to which the property being set belongs.
     * @param {DependencyProperty} propertyToSet The property to which the value is written.
     * @param {IInspectable} value The value to set.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlbindinghelper.setpropertyfromobject
     */
    static SetPropertyFromObject(dependencyObject_, propertyToSet, value) {
        if (!XamlBindingHelper.HasProp("__IXamlBindingHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlBindingHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlBindingHelperStatics.IID)
            XamlBindingHelper.__IXamlBindingHelperStatics := IXamlBindingHelperStatics(factoryPtr)
        }

        return XamlBindingHelper.__IXamlBindingHelperStatics.SetPropertyFromObject(dependencyObject_, propertyToSet, value)
    }

;@endregion Static Methods

;@region Instance Methods
    __New(ptr) {
        super.__New(ptr)
    }

;@endregion Instance Methods
}
