#Requires AutoHotkey v2.0 64-bit

#Include ..\..\..\Win32\System\WinRT\Apis.ahk
#Include ..\..\..\Win32\System\WinRT\HSTRING.ahk
#Include ..\..\..\Win32\System\WinRT\IInspectable.ahk
#Include .\IXamlMarkupHelper.ahk
#Include .\IXamlMarkupHelperStatics.ahk
#Include ..\..\..\..\Guid.ahk

/**
 * Provides helper methods for the XAML compiler.
 * @remarks
 * This class is for use in code that is generated by the XAML compiler.
 * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlmarkuphelper
 * @namespace Windows.UI.Xaml.Markup
 * @version WindowsRuntime 1.4
 */
class XamlMarkupHelper extends IInspectable {
;@region Static Properties
    /**
     * The default interface of is Windows Runtime class. At the ABI level, the class is really
     * just a pointer to this interface
     * @type {Class}
     */
    static WinRTDefaultInterface => IXamlMarkupHelper

    /**
     * The IID of this class's default interface. This allows it to be cast using IUnknown::As like any
     * Windows Runtime interface
     * @type {Guid}
     */
    static IID => IXamlMarkupHelper.IID

;@endregion Static Properties

;@region Static Methods
    /**
     * Unloads an element from the XAML visual tree that was loaded by [x:Load](/windows/uwp/xaml-platform/x-load-attribute).
     * @remarks
     * This method supports functionality provided by the [x:Load attribute](/windows/uwp/xaml-platform/x-load-attribute). Calling this method with an element that is not marked with the `x:Load` attribute will cause an error.
     * 
     * For more information and examples, see [Unloading elements](/windows/uwp/xaml-platform/x-load-attribute#unloading-elements) in the [x:Load attribute](/windows/uwp/xaml-platform/x-load-attribute) page.
     * @param {DependencyObject} element The element to unload.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.xaml.markup.xamlmarkuphelper.unloadobject
     */
    static UnloadObject(element) {
        if (!XamlMarkupHelper.HasProp("__IXamlMarkupHelperStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Xaml.Markup.XamlMarkupHelper")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, IXamlMarkupHelperStatics.IID)
            XamlMarkupHelper.__IXamlMarkupHelperStatics := IXamlMarkupHelperStatics(factoryPtr)
        }

        return XamlMarkupHelper.__IXamlMarkupHelperStatics.UnloadObject(element)
    }

;@endregion Static Methods

;@region Instance Methods
    __New(ptr) {
        super.__New(ptr)
    }

;@endregion Instance Methods
}
