#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import "..\..\Foundation\WCHAR.ahk" { WCHAR }

/**
 * @namespace Windows.Win32.Media.DeviceManager
 */
export default struct WMDMDetermineMaxPropStringLen {
    #StructPack 2

    sz001 : WCHAR[27]

    static __New() {
        DefineProp(this.Prototype, 'sz002', { type: WCHAR[31], offset: 0 })
        DefineProp(this.Prototype, 'sz003', { type: WCHAR[14], offset: 0 })
        DefineProp(this.Prototype, 'sz004', { type: WCHAR[16], offset: 0 })
        DefineProp(this.Prototype, 'sz005', { type: WCHAR[22], offset: 0 })
        DefineProp(this.Prototype, 'sz006', { type: WCHAR[14], offset: 0 })
        DefineProp(this.Prototype, 'sz007', { type: WCHAR[20], offset: 0 })
        DefineProp(this.Prototype, 'sz008', { type: WCHAR[20], offset: 0 })
        DefineProp(this.Prototype, 'sz009', { type: WCHAR[22], offset: 0 })
        DefineProp(this.Prototype, 'sz010', { type: WCHAR[11], offset: 0 })
        DefineProp(this.Prototype, 'sz011', { type: WCHAR[12], offset: 0 })
        DefineProp(this.Prototype, 'sz012', { type: WCHAR[17], offset: 0 })
        DefineProp(this.Prototype, 'sz013', { type: WCHAR[17], offset: 0 })
        DefineProp(this.Prototype, 'sz014', { type: WCHAR[16], offset: 0 })
        DefineProp(this.Prototype, 'sz015', { type: WCHAR[17], offset: 0 })
        DefineProp(this.Prototype, 'sz016', { type: WCHAR[11], offset: 0 })
        DefineProp(this.Prototype, 'sz017', { type: WCHAR[11], offset: 0 })
        DefineProp(this.Prototype, 'sz018', { type: WCHAR[15], offset: 0 })
        DefineProp(this.Prototype, 'sz019', { type: WCHAR[22], offset: 0 })
        DefineProp(this.Prototype, 'sz020', { type: WCHAR[20], offset: 0 })
        DefineProp(this.Prototype, 'sz021', { type: WCHAR[22], offset: 0 })
        DefineProp(this.Prototype, 'sz022', { type: WCHAR[21], offset: 0 })
        DefineProp(this.Prototype, 'sz023', { type: WCHAR[24], offset: 0 })
        DefineProp(this.Prototype, 'sz024', { type: WCHAR[20], offset: 0 })
        DefineProp(this.Prototype, 'sz025', { type: WCHAR[10], offset: 0 })
        DefineProp(this.Prototype, 'sz026', { type: WCHAR[14], offset: 0 })
        DefineProp(this.Prototype, 'sz027', { type: WCHAR[11], offset: 0 })
        DefineProp(this.Prototype, 'sz028', { type: WCHAR[11], offset: 0 })
        DefineProp(this.Prototype, 'sz029', { type: WCHAR[13], offset: 0 })
        DefineProp(this.Prototype, 'sz030', { type: WCHAR[17], offset: 0 })
        DefineProp(this.Prototype, 'sz031', { type: WCHAR[16], offset: 0 })
        DefineProp(this.Prototype, 'sz032', { type: WCHAR[17], offset: 0 })
        DefineProp(this.Prototype, 'sz033', { type: WCHAR[20], offset: 0 })
        DefineProp(this.Prototype, 'sz034', { type: WCHAR[19], offset: 0 })
        DefineProp(this.Prototype, 'sz035', { type: WCHAR[18], offset: 0 })
        DefineProp(this.Prototype, 'sz036', { type: WCHAR[18], offset: 0 })
        DefineProp(this.Prototype, 'sz037', { type: WCHAR[15], offset: 0 })
        DefineProp(this.Prototype, 'sz041', { type: WCHAR[14], offset: 0 })
        DefineProp(this.Prototype, 'sz043', { type: WCHAR[22], offset: 0 })
        DefineProp(this.Prototype, 'sz044', { type: WCHAR[16], offset: 0 })
        DefineProp(this.Prototype, 'sz045', { type: WCHAR[20], offset: 0 })
        DefineProp(this.Prototype, 'sz046', { type: WCHAR[14], offset: 0 })
        DefineProp(this.Prototype, 'sz047', { type: WCHAR[14], offset: 0 })
        DefineProp(this.Prototype, 'sz048', { type: WCHAR[12], offset: 0 })
        DefineProp(this.Prototype, 'sz049', { type: WCHAR[25], offset: 0 })
        DefineProp(this.Prototype, 'sz050', { type: WCHAR[26], offset: 0 })
        DefineProp(this.Prototype, 'sz051', { type: WCHAR[25], offset: 0 })
        DefineProp(this.Prototype, 'sz052', { type: WCHAR[16], offset: 0 })
        DefineProp(this.Prototype, 'sz053', { type: WCHAR[24], offset: 0 })
        DefineProp(this.Prototype, 'sz054', { type: WCHAR[15], offset: 0 })
        DefineProp(this.Prototype, 'sz055', { type: WCHAR[21], offset: 0 })
        DefineProp(this.Prototype, 'sz056', { type: WCHAR[16], offset: 0 })
        DefineProp(this.Prototype, 'sz057', { type: WCHAR[22], offset: 0 })
        DefineProp(this.Prototype, 'sz058', { type: WCHAR[14], offset: 0 })
        DefineProp(this.Prototype, 'sz059', { type: WCHAR[25], offset: 0 })
        DefineProp(this.Prototype, 'sz060', { type: WCHAR[18], offset: 0 })
        DefineProp(this.Prototype, 'sz061', { type: WCHAR[22], offset: 0 })
        DefineProp(this.Prototype, 'sz062', { type: WCHAR[26], offset: 0 })
        DefineProp(this.Prototype, 'sz063', { type: WCHAR[36], offset: 0 })
        DefineProp(this.Prototype, 'sz064', { type: WCHAR[23], offset: 0 })
        DefineProp(this.Prototype, 'sz065', { type: WCHAR[12], offset: 0 })
        DefineProp(this.Prototype, 'sz066', { type: WCHAR[24], offset: 0 })
        DefineProp(this.Prototype, 'sz067', { type: WCHAR[11], offset: 0 })
        DefineProp(this.Prototype, 'sz068', { type: WCHAR[12], offset: 0 })
        DefineProp(this.Prototype, 'sz069', { type: WCHAR[14], offset: 0 })
        DefineProp(this.Prototype, 'sz070', { type: WCHAR[20], offset: 0 })
        DefineProp(this.Prototype, 'sz071', { type: WCHAR[15], offset: 0 })
        DefineProp(this.Prototype, 'sz072', { type: WCHAR[14], offset: 0 })
        DefineProp(this.Prototype, 'sz073', { type: WCHAR[31], offset: 0 })
        DefineProp(this.Prototype, 'sz074', { type: WCHAR[24], offset: 0 })
        DefineProp(this.Prototype, 'sz075', { type: WCHAR[22], offset: 0 })
        DefineProp(this.Prototype, 'sz076', { type: WCHAR[24], offset: 0 })
        DefineProp(this.Prototype, 'sz077', { type: WCHAR[21], offset: 0 })
        DefineProp(this.Prototype, 'sz078', { type: WCHAR[27], offset: 0 })
        DefineProp(this.Prototype, 'sz079', { type: WCHAR[27], offset: 0 })
        DefineProp(this.Prototype, 'sz080', { type: WCHAR[20], offset: 0 })
        DefineProp(this.Prototype, 'sz081', { type: WCHAR[33], offset: 0 })
        DefineProp(this.Prototype, 'sz082', { type: WCHAR[21], offset: 0 })
        DefineProp(this.Prototype, 'sz083', { type: WCHAR[32], offset: 0 })
        DefineProp(this.Prototype, 'sz084', { type: WCHAR[26], offset: 0 })
        DefineProp(this.Prototype, 'sz085', { type: WCHAR[18], offset: 0 })
        DefineProp(this.Prototype, 'sz086', { type: WCHAR[30], offset: 0 })
        this.DeleteProp("__New")
    }
}
