#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\CLUSTER_SHARED_VOLUME_RENAME_INPUT_TYPE.ahk" { CLUSTER_SHARED_VOLUME_RENAME_INPUT_TYPE }
#Import ".\CLUSTER_SHARED_VOLUME_RENAME_INPUT_GUID_NAME.ahk" { CLUSTER_SHARED_VOLUME_RENAME_INPUT_GUID_NAME }
#Import ".\CLUSTER_SHARED_VOLUME_RENAME_INPUT_VOLUME.ahk" { CLUSTER_SHARED_VOLUME_RENAME_INPUT_VOLUME }
#Import "..\..\Foundation\WCHAR.ahk" { WCHAR }

/**
 * @namespace Windows.Win32.Networking.Clustering
 */
export default struct CLUSTER_SHARED_VOLUME_RENAME_GUID_INPUT {
    #StructPack 8

    Base : CLUSTER_SHARED_VOLUME_RENAME_INPUT_VOLUME

    Base2 : CLUSTER_SHARED_VOLUME_RENAME_INPUT_GUID_NAME

}
