#Requires AutoHotkey v2.0 64-bit

#Include ..\..\..\..\Win32\System\WinRT\Apis.ahk
#Include ..\..\..\..\Win32\System\WinRT\HSTRING.ahk
#Include ..\..\..\..\Win32\System\WinRT\IInspectable.ahk
#Include .\IInkAnalysisResult.ahk
#Include ..\..\..\..\..\Guid.ahk

/**
 * Provides access to the results generated by the ink analysis process.
 * @remarks
 * 
 * @see https://learn.microsoft.com/uwp/api/windows.ui.input.inking.analysis.inkanalysisresult
 * @namespace Windows.UI.Input.Inking.Analysis
 * @version WindowsRuntime 1.4
 */
class InkAnalysisResult extends IInspectable {
;@region Static Properties
    /**
     * The default interface of is Windows Runtime class. At the ABI level, the class is really
     * just a pointer to this interface
     * @type {Class}
     */
    static WinRTDefaultInterface => IInkAnalysisResult

    /**
     * The IID of this class's default interface. This allows it to be cast using IUnknown::As like any
     * Windows Runtime interface
     * @type {Guid}
     */
    static IID => IInkAnalysisResult.IID

;@endregion Static Properties

;@region Instance Properties
    /**
     * Gets the [status](inkanalysisstatus.md) of the ink analysis operation, such as whether any changes were applied.
     * @see https://learn.microsoft.com/uwp/api/windows.ui.input.inking.analysis.inkanalysisresult.status
     * @type {Integer} 
     */
    Status {
        get => this.get_Status()
    }

;@endregion Instance Properties

;@region Instance Methods
    __New(ptr) {
        super.__New(ptr)
    }

    /**
     * 
     * @returns {Integer} 
     */
    get_Status() {
        if (!this.HasProp("__IInkAnalysisResult")) {
            if ((queryResult := this.QueryInterface(IInkAnalysisResult.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IInkAnalysisResult := IInkAnalysisResult(outPtr)
        }

        return this.__IInkAnalysisResult.get_Status()
    }

;@endregion Instance Methods
}
