#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\DDHAL_DDCALLBACKS.ahk" { DDHAL_DDCALLBACKS }
#Import ".\DDHAL_DDCOLORCONTROLCALLBACKS.ahk" { DDHAL_DDCOLORCONTROLCALLBACKS }
#Import ".\DDHAL_DDEXEBUFCALLBACKS.ahk" { DDHAL_DDEXEBUFCALLBACKS }
#Import ".\DDHAL_DDKERNELCALLBACKS.ahk" { DDHAL_DDKERNELCALLBACKS }
#Import ".\DDHAL_DDMISCELLANEOUSCALLBACKS.ahk" { DDHAL_DDMISCELLANEOUSCALLBACKS }
#Import ".\DDHAL_DDMOTIONCOMPCALLBACKS.ahk" { DDHAL_DDMOTIONCOMPCALLBACKS }
#Import ".\DDHAL_DDPALETTECALLBACKS.ahk" { DDHAL_DDPALETTECALLBACKS }
#Import ".\DDHAL_DDSURFACECALLBACKS.ahk" { DDHAL_DDSURFACECALLBACKS }
#Import ".\DDHAL_DDVIDEOPORTCALLBACKS.ahk" { DDHAL_DDVIDEOPORTCALLBACKS }
#Import ".\LPDDHALCOLORCB_COLORCONTROL.ahk" { LPDDHALCOLORCB_COLORCONTROL }
#Import ".\LPDDHALEXEBUFCB_CANCREATEEXEBUF.ahk" { LPDDHALEXEBUFCB_CANCREATEEXEBUF }
#Import ".\LPDDHALEXEBUFCB_CREATEEXEBUF.ahk" { LPDDHALEXEBUFCB_CREATEEXEBUF }
#Import ".\LPDDHALEXEBUFCB_DESTROYEXEBUF.ahk" { LPDDHALEXEBUFCB_DESTROYEXEBUF }
#Import ".\LPDDHALEXEBUFCB_LOCKEXEBUF.ahk" { LPDDHALEXEBUFCB_LOCKEXEBUF }
#Import ".\LPDDHALEXEBUFCB_UNLOCKEXEBUF.ahk" { LPDDHALEXEBUFCB_UNLOCKEXEBUF }
#Import ".\LPDDHALKERNELCB_SYNCSURFACE.ahk" { LPDDHALKERNELCB_SYNCSURFACE }
#Import ".\LPDDHALKERNELCB_SYNCVIDEOPORT.ahk" { LPDDHALKERNELCB_SYNCVIDEOPORT }
#Import ".\LPDDHALMOCOMPCB_BEGINFRAME.ahk" { LPDDHALMOCOMPCB_BEGINFRAME }
#Import ".\LPDDHALMOCOMPCB_CREATE.ahk" { LPDDHALMOCOMPCB_CREATE }
#Import ".\LPDDHALMOCOMPCB_DESTROY.ahk" { LPDDHALMOCOMPCB_DESTROY }
#Import ".\LPDDHALMOCOMPCB_ENDFRAME.ahk" { LPDDHALMOCOMPCB_ENDFRAME }
#Import ".\LPDDHALMOCOMPCB_GETCOMPBUFFINFO.ahk" { LPDDHALMOCOMPCB_GETCOMPBUFFINFO }
#Import ".\LPDDHALMOCOMPCB_GETFORMATS.ahk" { LPDDHALMOCOMPCB_GETFORMATS }
#Import ".\LPDDHALMOCOMPCB_GETGUIDS.ahk" { LPDDHALMOCOMPCB_GETGUIDS }
#Import ".\LPDDHALMOCOMPCB_GETINTERNALINFO.ahk" { LPDDHALMOCOMPCB_GETINTERNALINFO }
#Import ".\LPDDHALMOCOMPCB_QUERYSTATUS.ahk" { LPDDHALMOCOMPCB_QUERYSTATUS }
#Import ".\LPDDHALMOCOMPCB_RENDER.ahk" { LPDDHALMOCOMPCB_RENDER }
#Import ".\LPDDHALPALCB_DESTROYPALETTE.ahk" { LPDDHALPALCB_DESTROYPALETTE }
#Import ".\LPDDHALPALCB_SETENTRIES.ahk" { LPDDHALPALCB_SETENTRIES }
#Import ".\LPDDHALSURFCB_ADDATTACHEDSURFACE.ahk" { LPDDHALSURFCB_ADDATTACHEDSURFACE }
#Import ".\LPDDHALSURFCB_BLT.ahk" { LPDDHALSURFCB_BLT }
#Import ".\LPDDHALSURFCB_DESTROYSURFACE.ahk" { LPDDHALSURFCB_DESTROYSURFACE }
#Import ".\LPDDHALSURFCB_FLIP.ahk" { LPDDHALSURFCB_FLIP }
#Import ".\LPDDHALSURFCB_GETBLTSTATUS.ahk" { LPDDHALSURFCB_GETBLTSTATUS }
#Import ".\LPDDHALSURFCB_GETFLIPSTATUS.ahk" { LPDDHALSURFCB_GETFLIPSTATUS }
#Import ".\LPDDHALSURFCB_LOCK.ahk" { LPDDHALSURFCB_LOCK }
#Import ".\LPDDHALSURFCB_SETCLIPLIST.ahk" { LPDDHALSURFCB_SETCLIPLIST }
#Import ".\LPDDHALSURFCB_SETCOLORKEY.ahk" { LPDDHALSURFCB_SETCOLORKEY }
#Import ".\LPDDHALSURFCB_SETOVERLAYPOSITION.ahk" { LPDDHALSURFCB_SETOVERLAYPOSITION }
#Import ".\LPDDHALSURFCB_SETPALETTE.ahk" { LPDDHALSURFCB_SETPALETTE }
#Import ".\LPDDHALSURFCB_UNLOCK.ahk" { LPDDHALSURFCB_UNLOCK }
#Import ".\LPDDHALSURFCB_UPDATEOVERLAY.ahk" { LPDDHALSURFCB_UPDATEOVERLAY }
#Import ".\LPDDHALVPORTCB_CANCREATEVIDEOPORT.ahk" { LPDDHALVPORTCB_CANCREATEVIDEOPORT }
#Import ".\LPDDHALVPORTCB_COLORCONTROL.ahk" { LPDDHALVPORTCB_COLORCONTROL }
#Import ".\LPDDHALVPORTCB_CREATEVIDEOPORT.ahk" { LPDDHALVPORTCB_CREATEVIDEOPORT }
#Import ".\LPDDHALVPORTCB_DESTROYVPORT.ahk" { LPDDHALVPORTCB_DESTROYVPORT }
#Import ".\LPDDHALVPORTCB_FLIP.ahk" { LPDDHALVPORTCB_FLIP }
#Import ".\LPDDHALVPORTCB_GETBANDWIDTH.ahk" { LPDDHALVPORTCB_GETBANDWIDTH }
#Import ".\LPDDHALVPORTCB_GETFIELD.ahk" { LPDDHALVPORTCB_GETFIELD }
#Import ".\LPDDHALVPORTCB_GETFLIPSTATUS.ahk" { LPDDHALVPORTCB_GETFLIPSTATUS }
#Import ".\LPDDHALVPORTCB_GETINPUTFORMATS.ahk" { LPDDHALVPORTCB_GETINPUTFORMATS }
#Import ".\LPDDHALVPORTCB_GETLINE.ahk" { LPDDHALVPORTCB_GETLINE }
#Import ".\LPDDHALVPORTCB_GETOUTPUTFORMATS.ahk" { LPDDHALVPORTCB_GETOUTPUTFORMATS }
#Import ".\LPDDHALVPORTCB_GETSIGNALSTATUS.ahk" { LPDDHALVPORTCB_GETSIGNALSTATUS }
#Import ".\LPDDHALVPORTCB_GETVPORTCONNECT.ahk" { LPDDHALVPORTCB_GETVPORTCONNECT }
#Import ".\LPDDHALVPORTCB_UPDATE.ahk" { LPDDHALVPORTCB_UPDATE }
#Import ".\LPDDHALVPORTCB_WAITFORSYNC.ahk" { LPDDHALVPORTCB_WAITFORSYNC }
#Import ".\LPDDHAL_CANCREATESURFACE.ahk" { LPDDHAL_CANCREATESURFACE }
#Import ".\LPDDHAL_CREATEPALETTE.ahk" { LPDDHAL_CREATEPALETTE }
#Import ".\LPDDHAL_CREATESURFACE.ahk" { LPDDHAL_CREATESURFACE }
#Import ".\LPDDHAL_DESTROYDRIVER.ahk" { LPDDHAL_DESTROYDRIVER }
#Import ".\LPDDHAL_FLIPTOGDISURFACE.ahk" { LPDDHAL_FLIPTOGDISURFACE }
#Import ".\LPDDHAL_GETAVAILDRIVERMEMORY.ahk" { LPDDHAL_GETAVAILDRIVERMEMORY }
#Import ".\LPDDHAL_GETHEAPALIGNMENT.ahk" { LPDDHAL_GETHEAPALIGNMENT }
#Import ".\LPDDHAL_GETSCANLINE.ahk" { LPDDHAL_GETSCANLINE }
#Import ".\LPDDHAL_SETCOLORKEY.ahk" { LPDDHAL_SETCOLORKEY }
#Import ".\LPDDHAL_SETEXCLUSIVEMODE.ahk" { LPDDHAL_SETEXCLUSIVEMODE }
#Import ".\LPDDHAL_SETMODE.ahk" { LPDDHAL_SETMODE }
#Import ".\LPDDHAL_UPDATENONLOCALHEAP.ahk" { LPDDHAL_UPDATENONLOCALHEAP }
#Import ".\LPDDHAL_WAITFORVERTICALBLANK.ahk" { LPDDHAL_WAITFORVERTICALBLANK }

/**
 * @namespace Windows.Win32.Graphics.DirectDraw
 */
export default struct DDHAL_CALLBACKS {
    #StructPack 8

    cbDDCallbacks : DDHAL_DDCALLBACKS

    cbDDSurfaceCallbacks : DDHAL_DDSURFACECALLBACKS

    cbDDPaletteCallbacks : DDHAL_DDPALETTECALLBACKS

    HALDD : DDHAL_DDCALLBACKS

    HALDDSurface : DDHAL_DDSURFACECALLBACKS

    HALDDPalette : DDHAL_DDPALETTECALLBACKS

    HELDD : DDHAL_DDCALLBACKS

    HELDDSurface : DDHAL_DDSURFACECALLBACKS

    HELDDPalette : DDHAL_DDPALETTECALLBACKS

    cbDDExeBufCallbacks : DDHAL_DDEXEBUFCALLBACKS

    HALDDExeBuf : DDHAL_DDEXEBUFCALLBACKS

    HELDDExeBuf : DDHAL_DDEXEBUFCALLBACKS

    cbDDVideoPortCallbacks : DDHAL_DDVIDEOPORTCALLBACKS

    HALDDVideoPort : DDHAL_DDVIDEOPORTCALLBACKS

    cbDDColorControlCallbacks : DDHAL_DDCOLORCONTROLCALLBACKS

    HALDDColorControl : DDHAL_DDCOLORCONTROLCALLBACKS

    cbDDMiscellaneousCallbacks : DDHAL_DDMISCELLANEOUSCALLBACKS

    HALDDMiscellaneous : DDHAL_DDMISCELLANEOUSCALLBACKS

    cbDDKernelCallbacks : DDHAL_DDKERNELCALLBACKS

    HALDDKernel : DDHAL_DDKERNELCALLBACKS

    cbDDMotionCompCallbacks : DDHAL_DDMOTIONCOMPCALLBACKS

    HALDDMotionComp : DDHAL_DDMOTIONCOMPCALLBACKS

}
