#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\LPDDHALSURFCB_ADDATTACHEDSURFACE.ahk" { LPDDHALSURFCB_ADDATTACHEDSURFACE }
#Import ".\LPDDHALSURFCB_BLT.ahk" { LPDDHALSURFCB_BLT }
#Import ".\LPDDHALSURFCB_DESTROYSURFACE.ahk" { LPDDHALSURFCB_DESTROYSURFACE }
#Import ".\LPDDHALSURFCB_FLIP.ahk" { LPDDHALSURFCB_FLIP }
#Import ".\LPDDHALSURFCB_GETBLTSTATUS.ahk" { LPDDHALSURFCB_GETBLTSTATUS }
#Import ".\LPDDHALSURFCB_GETFLIPSTATUS.ahk" { LPDDHALSURFCB_GETFLIPSTATUS }
#Import ".\LPDDHALSURFCB_LOCK.ahk" { LPDDHALSURFCB_LOCK }
#Import ".\LPDDHALSURFCB_SETCLIPLIST.ahk" { LPDDHALSURFCB_SETCLIPLIST }
#Import ".\LPDDHALSURFCB_SETCOLORKEY.ahk" { LPDDHALSURFCB_SETCOLORKEY }
#Import ".\LPDDHALSURFCB_SETOVERLAYPOSITION.ahk" { LPDDHALSURFCB_SETOVERLAYPOSITION }
#Import ".\LPDDHALSURFCB_SETPALETTE.ahk" { LPDDHALSURFCB_SETPALETTE }
#Import ".\LPDDHALSURFCB_UNLOCK.ahk" { LPDDHALSURFCB_UNLOCK }
#Import ".\LPDDHALSURFCB_UPDATEOVERLAY.ahk" { LPDDHALSURFCB_UPDATEOVERLAY }

/**
 * @namespace Windows.Win32.Graphics.DirectDraw
 */
export default struct DDHAL_DDSURFACECALLBACKS {
    #StructPack 8

    dwSize : UInt32

    dwFlags : UInt32

    DestroySurface : LPDDHALSURFCB_DESTROYSURFACE

    Flip : LPDDHALSURFCB_FLIP

    SetClipList : LPDDHALSURFCB_SETCLIPLIST

    Lock : LPDDHALSURFCB_LOCK

    Unlock : LPDDHALSURFCB_UNLOCK

    Blt : LPDDHALSURFCB_BLT

    SetColorKey : LPDDHALSURFCB_SETCOLORKEY

    AddAttachedSurface : LPDDHALSURFCB_ADDATTACHEDSURFACE

    GetBltStatus : LPDDHALSURFCB_GETBLTSTATUS

    GetFlipStatus : LPDDHALSURFCB_GETFLIPSTATUS

    UpdateOverlay : LPDDHALSURFCB_UPDATEOVERLAY

    SetOverlayPosition : LPDDHALSURFCB_SETOVERLAYPOSITION

    reserved4 : IntPtr

    SetPalette : LPDDHALSURFCB_SETPALETTE

}
