#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\LPDDHAL_GETHEAPALIGNMENT.ahk" { LPDDHAL_GETHEAPALIGNMENT }
#Import ".\LPDDHAL_GETAVAILDRIVERMEMORY.ahk" { LPDDHAL_GETAVAILDRIVERMEMORY }
#Import ".\LPDDHAL_UPDATENONLOCALHEAP.ahk" { LPDDHAL_UPDATENONLOCALHEAP }
#Import ".\LPDDHALSURFCB_GETBLTSTATUS.ahk" { LPDDHALSURFCB_GETBLTSTATUS }

/**
 * @namespace Windows.Win32.Graphics.DirectDraw
 */
export default struct DDHAL_DDMISCELLANEOUSCALLBACKS {
    #StructPack 8

    dwSize : UInt32

    dwFlags : UInt32

    GetAvailDriverMemory : LPDDHAL_GETAVAILDRIVERMEMORY

    UpdateNonLocalHeap : LPDDHAL_UPDATENONLOCALHEAP

    GetHeapAlignment : LPDDHAL_GETHEAPALIGNMENT

    GetSysmemBltStatus : LPDDHALSURFCB_GETBLTSTATUS

}
