#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\LPDDHAL_CANCREATESURFACE.ahk" { LPDDHAL_CANCREATESURFACE }
#Import ".\LPDDHAL_CREATEPALETTE.ahk" { LPDDHAL_CREATEPALETTE }
#Import ".\LPDDHAL_CREATESURFACE.ahk" { LPDDHAL_CREATESURFACE }
#Import ".\LPDDHAL_DESTROYDRIVER.ahk" { LPDDHAL_DESTROYDRIVER }
#Import ".\LPDDHAL_FLIPTOGDISURFACE.ahk" { LPDDHAL_FLIPTOGDISURFACE }
#Import ".\LPDDHAL_GETSCANLINE.ahk" { LPDDHAL_GETSCANLINE }
#Import ".\LPDDHAL_SETCOLORKEY.ahk" { LPDDHAL_SETCOLORKEY }
#Import ".\LPDDHAL_SETEXCLUSIVEMODE.ahk" { LPDDHAL_SETEXCLUSIVEMODE }
#Import ".\LPDDHAL_SETMODE.ahk" { LPDDHAL_SETMODE }
#Import ".\LPDDHAL_WAITFORVERTICALBLANK.ahk" { LPDDHAL_WAITFORVERTICALBLANK }

/**
 * @namespace Windows.Win32.Graphics.DirectDraw
 */
export default struct DDHAL_DDCALLBACKS {
    #StructPack 8

    dwSize : UInt32

    dwFlags : UInt32

    DestroyDriver : LPDDHAL_DESTROYDRIVER

    CreateSurface : LPDDHAL_CREATESURFACE

    SetColorKey : LPDDHAL_SETCOLORKEY

    SetMode : LPDDHAL_SETMODE

    WaitForVerticalBlank : LPDDHAL_WAITFORVERTICALBLANK

    CanCreateSurface : LPDDHAL_CANCREATESURFACE

    CreatePalette : LPDDHAL_CREATEPALETTE

    GetScanLine : LPDDHAL_GETSCANLINE

    SetExclusiveMode : LPDDHAL_SETEXCLUSIVEMODE

    FlipToGDISurface : LPDDHAL_FLIPTOGDISURFACE

}
