#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\LPDDHALMOCOMPCB_QUERYSTATUS.ahk" { LPDDHALMOCOMPCB_QUERYSTATUS }
#Import ".\LPDDHALMOCOMPCB_RENDER.ahk" { LPDDHALMOCOMPCB_RENDER }
#Import ".\LPDDHALMOCOMPCB_BEGINFRAME.ahk" { LPDDHALMOCOMPCB_BEGINFRAME }
#Import ".\LPDDHALMOCOMPCB_ENDFRAME.ahk" { LPDDHALMOCOMPCB_ENDFRAME }
#Import ".\LPDDHALMOCOMPCB_GETGUIDS.ahk" { LPDDHALMOCOMPCB_GETGUIDS }
#Import ".\LPDDHALMOCOMPCB_DESTROY.ahk" { LPDDHALMOCOMPCB_DESTROY }
#Import ".\LPDDHALMOCOMPCB_GETCOMPBUFFINFO.ahk" { LPDDHALMOCOMPCB_GETCOMPBUFFINFO }
#Import ".\LPDDHALMOCOMPCB_CREATE.ahk" { LPDDHALMOCOMPCB_CREATE }
#Import ".\LPDDHALMOCOMPCB_GETINTERNALINFO.ahk" { LPDDHALMOCOMPCB_GETINTERNALINFO }
#Import ".\LPDDHALMOCOMPCB_GETFORMATS.ahk" { LPDDHALMOCOMPCB_GETFORMATS }

/**
 * @namespace Windows.Win32.Graphics.DirectDraw
 */
export default struct DDHAL_DDMOTIONCOMPCALLBACKS {
    #StructPack 8

    dwSize : UInt32

    dwFlags : UInt32

    GetMoCompGuids : LPDDHALMOCOMPCB_GETGUIDS

    GetMoCompFormats : LPDDHALMOCOMPCB_GETFORMATS

    CreateMoComp : LPDDHALMOCOMPCB_CREATE

    GetMoCompBuffInfo : LPDDHALMOCOMPCB_GETCOMPBUFFINFO

    GetInternalMoCompInfo : LPDDHALMOCOMPCB_GETINTERNALINFO

    BeginMoCompFrame : LPDDHALMOCOMPCB_BEGINFRAME

    EndMoCompFrame : LPDDHALMOCOMPCB_ENDFRAME

    RenderMoComp : LPDDHALMOCOMPCB_RENDER

    QueryMoCompStatus : LPDDHALMOCOMPCB_QUERYSTATUS

    DestroyMoComp : LPDDHALMOCOMPCB_DESTROY

}
