#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\LPDDHALVPORTCB_WAITFORSYNC.ahk" { LPDDHALVPORTCB_WAITFORSYNC }
#Import ".\LPDDHALVPORTCB_CANCREATEVIDEOPORT.ahk" { LPDDHALVPORTCB_CANCREATEVIDEOPORT }
#Import ".\LPDDHALVPORTCB_GETSIGNALSTATUS.ahk" { LPDDHALVPORTCB_GETSIGNALSTATUS }
#Import ".\LPDDHALVPORTCB_GETINPUTFORMATS.ahk" { LPDDHALVPORTCB_GETINPUTFORMATS }
#Import ".\LPDDHALVPORTCB_GETOUTPUTFORMATS.ahk" { LPDDHALVPORTCB_GETOUTPUTFORMATS }
#Import ".\LPDDHALVPORTCB_GETLINE.ahk" { LPDDHALVPORTCB_GETLINE }
#Import ".\LPDDHALVPORTCB_GETVPORTCONNECT.ahk" { LPDDHALVPORTCB_GETVPORTCONNECT }
#Import ".\LPDDHALVPORTCB_GETFLIPSTATUS.ahk" { LPDDHALVPORTCB_GETFLIPSTATUS }
#Import ".\LPDDHALVPORTCB_DESTROYVPORT.ahk" { LPDDHALVPORTCB_DESTROYVPORT }
#Import ".\LPDDHALVPORTCB_CREATEVIDEOPORT.ahk" { LPDDHALVPORTCB_CREATEVIDEOPORT }
#Import ".\LPDDHALVPORTCB_GETBANDWIDTH.ahk" { LPDDHALVPORTCB_GETBANDWIDTH }
#Import ".\LPDDHALVPORTCB_GETFIELD.ahk" { LPDDHALVPORTCB_GETFIELD }
#Import ".\LPDDHALVPORTCB_FLIP.ahk" { LPDDHALVPORTCB_FLIP }
#Import ".\LPDDHALVPORTCB_COLORCONTROL.ahk" { LPDDHALVPORTCB_COLORCONTROL }
#Import ".\LPDDHALVPORTCB_UPDATE.ahk" { LPDDHALVPORTCB_UPDATE }

/**
 * @namespace Windows.Win32.Graphics.DirectDraw
 */
export default struct DDHAL_DDVIDEOPORTCALLBACKS {
    #StructPack 8

    dwSize : UInt32

    dwFlags : UInt32

    CanCreateVideoPort : LPDDHALVPORTCB_CANCREATEVIDEOPORT

    CreateVideoPort : LPDDHALVPORTCB_CREATEVIDEOPORT

    FlipVideoPort : LPDDHALVPORTCB_FLIP

    GetVideoPortBandwidth : LPDDHALVPORTCB_GETBANDWIDTH

    GetVideoPortInputFormats : LPDDHALVPORTCB_GETINPUTFORMATS

    GetVideoPortOutputFormats : LPDDHALVPORTCB_GETOUTPUTFORMATS

    lpReserved1 : IntPtr

    GetVideoPortField : LPDDHALVPORTCB_GETFIELD

    GetVideoPortLine : LPDDHALVPORTCB_GETLINE

    GetVideoPortConnectInfo : LPDDHALVPORTCB_GETVPORTCONNECT

    DestroyVideoPort : LPDDHALVPORTCB_DESTROYVPORT

    GetVideoPortFlipStatus : LPDDHALVPORTCB_GETFLIPSTATUS

    UpdateVideoPort : LPDDHALVPORTCB_UPDATE

    WaitForVideoPortSync : LPDDHALVPORTCB_WAITFORSYNC

    GetVideoSignalStatus : LPDDHALVPORTCB_GETSIGNALSTATUS

    ColorControl : LPDDHALVPORTCB_COLORCONTROL

}
