#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\DDHAL_DDKERNELCALLBACKS.ahk" { DDHAL_DDKERNELCALLBACKS }
#Import ".\DDHAL_DDCALLBACKS.ahk" { DDHAL_DDCALLBACKS }
#Import ".\DDHAL_DDVIDEOPORTCALLBACKS.ahk" { DDHAL_DDVIDEOPORTCALLBACKS }
#Import ".\DDHAL_DDSURFACECALLBACKS.ahk" { DDHAL_DDSURFACECALLBACKS }
#Import ".\DDHAL_DDCOLORCONTROLCALLBACKS.ahk" { DDHAL_DDCOLORCONTROLCALLBACKS }
#Import ".\DDHAL_DDMOTIONCOMPCALLBACKS.ahk" { DDHAL_DDMOTIONCOMPCALLBACKS }
#Import ".\DDHAL_DDMISCELLANEOUSCALLBACKS.ahk" { DDHAL_DDMISCELLANEOUSCALLBACKS }
#Import ".\DDHAL_DDEXEBUFCALLBACKS.ahk" { DDHAL_DDEXEBUFCALLBACKS }
#Import ".\DDHAL_DDPALETTECALLBACKS.ahk" { DDHAL_DDPALETTECALLBACKS }

/**
 * @namespace Windows.Win32.Graphics.DirectDraw
 */
export default struct DDHAL_CALLBACKS {
    #StructPack 8

    cbDDCallbacks : DDHAL_DDCALLBACKS

    cbDDSurfaceCallbacks : DDHAL_DDSURFACECALLBACKS

    cbDDPaletteCallbacks : DDHAL_DDPALETTECALLBACKS

    HALDD : DDHAL_DDCALLBACKS

    HALDDSurface : DDHAL_DDSURFACECALLBACKS

    HALDDPalette : DDHAL_DDPALETTECALLBACKS

    HELDD : DDHAL_DDCALLBACKS

    HELDDSurface : DDHAL_DDSURFACECALLBACKS

    HELDDPalette : DDHAL_DDPALETTECALLBACKS

    cbDDExeBufCallbacks : DDHAL_DDEXEBUFCALLBACKS

    HALDDExeBuf : DDHAL_DDEXEBUFCALLBACKS

    HELDDExeBuf : DDHAL_DDEXEBUFCALLBACKS

    cbDDVideoPortCallbacks : DDHAL_DDVIDEOPORTCALLBACKS

    HALDDVideoPort : DDHAL_DDVIDEOPORTCALLBACKS

    cbDDColorControlCallbacks : DDHAL_DDCOLORCONTROLCALLBACKS

    HALDDColorControl : DDHAL_DDCOLORCONTROLCALLBACKS

    cbDDMiscellaneousCallbacks : DDHAL_DDMISCELLANEOUSCALLBACKS

    HALDDMiscellaneous : DDHAL_DDMISCELLANEOUSCALLBACKS

    cbDDKernelCallbacks : DDHAL_DDKERNELCALLBACKS

    HALDDKernel : DDHAL_DDKERNELCALLBACKS

    cbDDMotionCompCallbacks : DDHAL_DDMOTIONCOMPCALLBACKS

    HALDDMotionComp : DDHAL_DDMOTIONCOMPCALLBACKS

}
