#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\LPDDHALEXEBUFCB_CANCREATEEXEBUF.ahk" { LPDDHALEXEBUFCB_CANCREATEEXEBUF }
#Import ".\LPDDHALEXEBUFCB_CREATEEXEBUF.ahk" { LPDDHALEXEBUFCB_CREATEEXEBUF }
#Import ".\LPDDHALEXEBUFCB_DESTROYEXEBUF.ahk" { LPDDHALEXEBUFCB_DESTROYEXEBUF }
#Import ".\LPDDHALEXEBUFCB_LOCKEXEBUF.ahk" { LPDDHALEXEBUFCB_LOCKEXEBUF }
#Import ".\LPDDHALEXEBUFCB_UNLOCKEXEBUF.ahk" { LPDDHALEXEBUFCB_UNLOCKEXEBUF }

/**
 * @namespace Windows.Win32.Graphics.DirectDraw
 */
export default struct DDHAL_DDEXEBUFCALLBACKS {
    #StructPack 8

    dwSize : UInt32

    dwFlags : UInt32

    CanCreateExecuteBuffer : LPDDHALEXEBUFCB_CANCREATEEXEBUF

    CreateExecuteBuffer : LPDDHALEXEBUFCB_CREATEEXEBUF

    DestroyExecuteBuffer : LPDDHALEXEBUFCB_DESTROYEXEBUF

    LockExecuteBuffer : LPDDHALEXEBUFCB_LOCKEXEBUF

    UnlockExecuteBuffer : LPDDHALEXEBUFCB_UNLOCKEXEBUF

}
