#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PDXVA2SW_CREATEVIDEOPROCESSDEVICE.ahk" { PDXVA2SW_CREATEVIDEOPROCESSDEVICE }
#Import ".\PDXVA2SW_DESTROYVIDEOPROCESSDEVICE.ahk" { PDXVA2SW_DESTROYVIDEOPROCESSDEVICE }
#Import ".\PDXVA2SW_GETFILTERPROPERTYRANGE.ahk" { PDXVA2SW_GETFILTERPROPERTYRANGE }
#Import ".\PDXVA2SW_GETPROCAMPRANGE.ahk" { PDXVA2SW_GETPROCAMPRANGE }
#Import ".\PDXVA2SW_GETVIDEOPROCESSORCAPS.ahk" { PDXVA2SW_GETVIDEOPROCESSORCAPS }
#Import ".\PDXVA2SW_GETVIDEOPROCESSORRENDERTARGETCOUNT.ahk" { PDXVA2SW_GETVIDEOPROCESSORRENDERTARGETCOUNT }
#Import ".\PDXVA2SW_GETVIDEOPROCESSORRENDERTARGETS.ahk" { PDXVA2SW_GETVIDEOPROCESSORRENDERTARGETS }
#Import ".\PDXVA2SW_GETVIDEOPROCESSORSUBSTREAMFORMATCOUNT.ahk" { PDXVA2SW_GETVIDEOPROCESSORSUBSTREAMFORMATCOUNT }
#Import ".\PDXVA2SW_GETVIDEOPROCESSORSUBSTREAMFORMATS.ahk" { PDXVA2SW_GETVIDEOPROCESSORSUBSTREAMFORMATS }
#Import ".\PDXVA2SW_VIDEOPROCESSBEGINFRAME.ahk" { PDXVA2SW_VIDEOPROCESSBEGINFRAME }
#Import ".\PDXVA2SW_VIDEOPROCESSBLT.ahk" { PDXVA2SW_VIDEOPROCESSBLT }
#Import ".\PDXVA2SW_VIDEOPROCESSENDFRAME.ahk" { PDXVA2SW_VIDEOPROCESSENDFRAME }
#Import ".\PDXVA2SW_VIDEOPROCESSSETRENDERTARGET.ahk" { PDXVA2SW_VIDEOPROCESSSETRENDERTARGET }

/**
 * @namespace Windows.Win32.Media.DirectShow
 */
export default struct DXVA2SW_CALLBACKS {
    #StructPack 8

    Size : UInt32

    GetVideoProcessorRenderTargetCount : PDXVA2SW_GETVIDEOPROCESSORRENDERTARGETCOUNT

    GetVideoProcessorRenderTargets : PDXVA2SW_GETVIDEOPROCESSORRENDERTARGETS

    GetVideoProcessorCaps : PDXVA2SW_GETVIDEOPROCESSORCAPS

    GetVideoProcessorSubStreamFormatCount : PDXVA2SW_GETVIDEOPROCESSORSUBSTREAMFORMATCOUNT

    GetVideoProcessorSubStreamFormats : PDXVA2SW_GETVIDEOPROCESSORSUBSTREAMFORMATS

    GetProcAmpRange : PDXVA2SW_GETPROCAMPRANGE

    GetFilterPropertyRange : PDXVA2SW_GETFILTERPROPERTYRANGE

    CreateVideoProcessDevice : PDXVA2SW_CREATEVIDEOPROCESSDEVICE

    DestroyVideoProcessDevice : PDXVA2SW_DESTROYVIDEOPROCESSDEVICE

    VideoProcessBeginFrame : PDXVA2SW_VIDEOPROCESSBEGINFRAME

    VideoProcessEndFrame : PDXVA2SW_VIDEOPROCESSENDFRAME

    VideoProcessSetRenderTarget : PDXVA2SW_VIDEOPROCESSSETRENDERTARGET

    VideoProcessBlt : PDXVA2SW_VIDEOPROCESSBLT

}
