#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Metadata\__Init.ahk" {*}
#Import export ".\APP_LOCAL_DEVICE_ID.ahk" {APP_LOCAL_DEVICE_ID}
#Import export ".\Apis.ahk" {*}
#Import export ".\BOOL.ahk" {BOOL}
#Import export ".\BOOLEAN.ahk" {BOOLEAN}
#Import export ".\BSTR.ahk" {BSTR}
#Import export ".\CHAR.ahk" {CHAR}
#Import export ".\COLORREF.ahk" {COLORREF}
#Import export ".\Constants.ahk" {*}
#Import export ".\DECIMAL.ahk" {DECIMAL}
#Import export ".\DEVPROPKEY.ahk" {DEVPROPKEY}
#Import export ".\DUPLICATE_HANDLE_OPTIONS.ahk" {DUPLICATE_HANDLE_OPTIONS}
#Import export ".\FARPROC.ahk" {FARPROC}
#Import export ".\FILETIME.ahk" {FILETIME}
#Import export ".\FLOAT128.ahk" {FLOAT128}
#Import export ".\GENERIC_ACCESS_RIGHTS.ahk" {GENERIC_ACCESS_RIGHTS}
#Import export ".\HANDLE.ahk" {HANDLE}
#Import export ".\HANDLE_FLAGS.ahk" {HANDLE_FLAGS}
#Import export ".\HANDLE_PTR.ahk" {HANDLE_PTR}
#Import export ".\HGLOBAL.ahk" {HGLOBAL}
#Import export ".\HINSTANCE.ahk" {HINSTANCE}
#Import export ".\HLOCAL.ahk" {HLOCAL}
#Import export ".\HLSURF.ahk" {HLSURF}
#Import export ".\HMODULE.ahk" {HMODULE}
#Import export ".\HRESULT.ahk" {HRESULT}
#Import export ".\HRSRC.ahk" {HRSRC}
#Import export ".\HSPRITE.ahk" {HSPRITE}
#Import export ".\HSTR.ahk" {HSTR}
#Import export ".\HTASK.ahk" {HTASK}
#Import export ".\HUMPD.ahk" {HUMPD}
#Import export ".\HWND.ahk" {HWND}
#Import export ".\LPARAM.ahk" {LPARAM}
#Import export ".\LRESULT.ahk" {LRESULT}
#Import export ".\LUID.ahk" {LUID}
#Import export ".\NEARPROC.ahk" {NEARPROC}
#Import export ".\NTSTATUS.ahk" {NTSTATUS}
#Import export ".\NTSTATUS_FACILITY_CODE.ahk" {NTSTATUS_FACILITY_CODE}
#Import export ".\NTSTATUS_SEVERITY_CODE.ahk" {NTSTATUS_SEVERITY_CODE}
#Import export ".\OBJECT_ATTRIBUTE_FLAGS.ahk" {OBJECT_ATTRIBUTE_FLAGS}
#Import export ".\PAPCFUNC.ahk" {PAPCFUNC}
#Import export ".\POINT.ahk" {POINT}
#Import export ".\POINTL.ahk" {POINTL}
#Import export ".\POINTS.ahk" {POINTS}
#Import export ".\PROC.ahk" {PROC}
#Import export ".\PROPERTYKEY.ahk" {PROPERTYKEY}
#Import export ".\PSTR.ahk" {PSTR}
#Import export ".\PWSTR.ahk" {PWSTR}
#Import export ".\RECT.ahk" {RECT}
#Import export ".\RECTL.ahk" {RECTL}
#Import export ".\SHANDLE_PTR.ahk" {SHANDLE_PTR}
#Import export ".\SIZE.ahk" {SIZE}
#Import export ".\SYSTEMTIME.ahk" {SYSTEMTIME}
#Import export ".\UNICODE_STRING.ahk" {UNICODE_STRING}
#Import export ".\VARIANT_BOOL.ahk" {VARIANT_BOOL}
#Import export ".\WAIT_EVENT.ahk" {WAIT_EVENT}
#Import export ".\WCHAR.ahk" {WCHAR}
#Import export ".\WIN32_ERROR.ahk" {WIN32_ERROR}
#Import export ".\WPARAM.ahk" {WPARAM}
