#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\..\Win32Struct.ahk

/**
 * Contains information about a simulated message generated by an input device other than a keyboard or mouse.
 * @see https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-hardwareinput
 * @namespace Windows.Win32.UI.Input.KeyboardAndMouse
 * @version v4.0.30319
 */
class HARDWAREINPUT extends Win32Struct
{
    static sizeof => 8

    static packingSize => 4

    /**
     * Type: <b>DWORD</b>
     * 
     * The message generated by the input hardware.
     * @type {Integer}
     */
    uMsg {
        get => NumGet(this, 0, "uint")
        set => NumPut("uint", value, this, 0)
    }

    /**
     * Type: <b>WORD</b>
     * 
     * The low-order word of the <i>lParam </i> parameter for <b>uMsg</b>.
     * @type {Integer}
     */
    wParamL {
        get => NumGet(this, 4, "ushort")
        set => NumPut("ushort", value, this, 4)
    }

    /**
     * Type: <b>WORD</b>
     * 
     * The high-order word of the <i>lParam </i> parameter for <b>uMsg</b>.
     * @type {Integer}
     */
    wParamH {
        get => NumGet(this, 6, "ushort")
        set => NumPut("ushort", value, this, 6)
    }
}
