#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\FAXROUTE_ENABLE.ahk" {FAXROUTE_ENABLE}
#Import export ".\FAX_ACCESS_RIGHTS_ENUM.ahk" {FAX_ACCESS_RIGHTS_ENUM}
#Import export ".\FAX_ACCESS_RIGHTS_ENUM_2.ahk" {FAX_ACCESS_RIGHTS_ENUM_2}
#Import export ".\FAX_ACCOUNT_EVENTS_TYPE_ENUM.ahk" {FAX_ACCOUNT_EVENTS_TYPE_ENUM}
#Import export ".\FAX_CONFIGURATIONA.ahk" {FAX_CONFIGURATIONA}
#Import export ".\FAX_CONFIGURATIONW.ahk" {FAX_CONFIGURATIONW}
#Import export ".\FAX_CONTEXT_INFOA.ahk" {FAX_CONTEXT_INFOA}
#Import export ".\FAX_CONTEXT_INFOW.ahk" {FAX_CONTEXT_INFOW}
#Import export ".\FAX_COVERPAGE_INFOA.ahk" {FAX_COVERPAGE_INFOA}
#Import export ".\FAX_COVERPAGE_INFOW.ahk" {FAX_COVERPAGE_INFOW}
#Import export ".\FAX_COVERPAGE_TYPE_ENUM.ahk" {FAX_COVERPAGE_TYPE_ENUM}
#Import export ".\FAX_DEVICE_RECEIVE_MODE_ENUM.ahk" {FAX_DEVICE_RECEIVE_MODE_ENUM}
#Import export ".\FAX_DEVICE_STATUSA.ahk" {FAX_DEVICE_STATUSA}
#Import export ".\FAX_DEVICE_STATUSW.ahk" {FAX_DEVICE_STATUSW}
#Import export ".\FAX_DEV_STATUS.ahk" {FAX_DEV_STATUS}
#Import export ".\FAX_ENUM_DELIVERY_REPORT_TYPES.ahk" {FAX_ENUM_DELIVERY_REPORT_TYPES}
#Import export ".\FAX_ENUM_DEVICE_ID_SOURCE.ahk" {FAX_ENUM_DEVICE_ID_SOURCE}
#Import export ".\FAX_ENUM_JOB_COMMANDS.ahk" {FAX_ENUM_JOB_COMMANDS}
#Import export ".\FAX_ENUM_JOB_SEND_ATTRIBUTES.ahk" {FAX_ENUM_JOB_SEND_ATTRIBUTES}
#Import export ".\FAX_ENUM_LOG_CATEGORIES.ahk" {FAX_ENUM_LOG_CATEGORIES}
#Import export ".\FAX_ENUM_LOG_LEVELS.ahk" {FAX_ENUM_LOG_LEVELS}
#Import export ".\FAX_ENUM_PORT_OPEN_TYPE.ahk" {FAX_ENUM_PORT_OPEN_TYPE}
#Import export ".\FAX_EVENTA.ahk" {FAX_EVENTA}
#Import export ".\FAX_EVENTW.ahk" {FAX_EVENTW}
#Import export ".\FAX_GLOBAL_ROUTING_INFOA.ahk" {FAX_GLOBAL_ROUTING_INFOA}
#Import export ".\FAX_GLOBAL_ROUTING_INFOW.ahk" {FAX_GLOBAL_ROUTING_INFOW}
#Import export ".\FAX_GROUP_STATUS_ENUM.ahk" {FAX_GROUP_STATUS_ENUM}
#Import export ".\FAX_JOB_ENTRYA.ahk" {FAX_JOB_ENTRYA}
#Import export ".\FAX_JOB_ENTRYW.ahk" {FAX_JOB_ENTRYW}
#Import export ".\FAX_JOB_EXTENDED_STATUS_ENUM.ahk" {FAX_JOB_EXTENDED_STATUS_ENUM}
#Import export ".\FAX_JOB_OPERATIONS_ENUM.ahk" {FAX_JOB_OPERATIONS_ENUM}
#Import export ".\FAX_JOB_PARAMA.ahk" {FAX_JOB_PARAMA}
#Import export ".\FAX_JOB_PARAMW.ahk" {FAX_JOB_PARAMW}
#Import export ".\FAX_JOB_STATUS_ENUM.ahk" {FAX_JOB_STATUS_ENUM}
#Import export ".\FAX_JOB_TYPE_ENUM.ahk" {FAX_JOB_TYPE_ENUM}
#Import export ".\FAX_LOG_CATEGORYA.ahk" {FAX_LOG_CATEGORYA}
#Import export ".\FAX_LOG_CATEGORYW.ahk" {FAX_LOG_CATEGORYW}
#Import export ".\FAX_LOG_LEVEL_ENUM.ahk" {FAX_LOG_LEVEL_ENUM}
#Import export ".\FAX_PORT_INFOA.ahk" {FAX_PORT_INFOA}
#Import export ".\FAX_PORT_INFOW.ahk" {FAX_PORT_INFOW}
#Import export ".\FAX_PRINT_INFOA.ahk" {FAX_PRINT_INFOA}
#Import export ".\FAX_PRINT_INFOW.ahk" {FAX_PRINT_INFOW}
#Import export ".\FAX_PRIORITY_TYPE_ENUM.ahk" {FAX_PRIORITY_TYPE_ENUM}
#Import export ".\FAX_PROVIDER_STATUS_ENUM.ahk" {FAX_PROVIDER_STATUS_ENUM}
#Import export ".\FAX_RECEIPT_TYPE_ENUM.ahk" {FAX_RECEIPT_TYPE_ENUM}
#Import export ".\FAX_RECEIVE.ahk" {FAX_RECEIVE}
#Import export ".\FAX_ROUTE.ahk" {FAX_ROUTE}
#Import export ".\FAX_ROUTE_CALLBACKROUTINES.ahk" {FAX_ROUTE_CALLBACKROUTINES}
#Import export ".\FAX_ROUTING_METHODA.ahk" {FAX_ROUTING_METHODA}
#Import export ".\FAX_ROUTING_METHODW.ahk" {FAX_ROUTING_METHODW}
#Import export ".\FAX_ROUTING_RULE_CODE_ENUM.ahk" {FAX_ROUTING_RULE_CODE_ENUM}
#Import export ".\FAX_RULE_STATUS_ENUM.ahk" {FAX_RULE_STATUS_ENUM}
#Import export ".\FAX_SCHEDULE_TYPE_ENUM.ahk" {FAX_SCHEDULE_TYPE_ENUM}
#Import export ".\FAX_SEND.ahk" {FAX_SEND}
#Import export ".\FAX_SERVER_APIVERSION_ENUM.ahk" {FAX_SERVER_APIVERSION_ENUM}
#Import export ".\FAX_SERVER_EVENTS_TYPE_ENUM.ahk" {FAX_SERVER_EVENTS_TYPE_ENUM}
#Import export ".\FAX_SMTP_AUTHENTICATION_TYPE_ENUM.ahk" {FAX_SMTP_AUTHENTICATION_TYPE_ENUM}
#Import export ".\FAX_TIME.ahk" {FAX_TIME}
#Import export ".\FaxAccount.ahk" {FaxAccount}
#Import export ".\FaxAccountFolders.ahk" {FaxAccountFolders}
#Import export ".\FaxAccountIncomingArchive.ahk" {FaxAccountIncomingArchive}
#Import export ".\FaxAccountIncomingQueue.ahk" {FaxAccountIncomingQueue}
#Import export ".\FaxAccountOutgoingArchive.ahk" {FaxAccountOutgoingArchive}
#Import export ".\FaxAccountOutgoingQueue.ahk" {FaxAccountOutgoingQueue}
#Import export ".\FaxAccountSet.ahk" {FaxAccountSet}
#Import export ".\FaxAccounts.ahk" {FaxAccounts}
#Import export ".\FaxActivity.ahk" {FaxActivity}
#Import export ".\FaxActivityLogging.ahk" {FaxActivityLogging}
#Import export ".\FaxConfiguration.ahk" {FaxConfiguration}
#Import export ".\FaxDevice.ahk" {FaxDevice}
#Import export ".\FaxDeviceIds.ahk" {FaxDeviceIds}
#Import export ".\FaxDeviceProvider.ahk" {FaxDeviceProvider}
#Import export ".\FaxDeviceProviders.ahk" {FaxDeviceProviders}
#Import export ".\FaxDevices.ahk" {FaxDevices}
#Import export ".\FaxDocument.ahk" {FaxDocument}
#Import export ".\FaxEventLogging.ahk" {FaxEventLogging}
#Import export ".\FaxFolders.ahk" {FaxFolders}
#Import export ".\FaxInboundRouting.ahk" {FaxInboundRouting}
#Import export ".\FaxInboundRoutingExtension.ahk" {FaxInboundRoutingExtension}
#Import export ".\FaxInboundRoutingExtensions.ahk" {FaxInboundRoutingExtensions}
#Import export ".\FaxInboundRoutingMethod.ahk" {FaxInboundRoutingMethod}
#Import export ".\FaxInboundRoutingMethods.ahk" {FaxInboundRoutingMethods}
#Import export ".\FaxIncomingArchive.ahk" {FaxIncomingArchive}
#Import export ".\FaxIncomingJob.ahk" {FaxIncomingJob}
#Import export ".\FaxIncomingJobs.ahk" {FaxIncomingJobs}
#Import export ".\FaxIncomingMessage.ahk" {FaxIncomingMessage}
#Import export ".\FaxIncomingMessageIterator.ahk" {FaxIncomingMessageIterator}
#Import export ".\FaxIncomingQueue.ahk" {FaxIncomingQueue}
#Import export ".\FaxJobStatus.ahk" {FaxJobStatus}
#Import export ".\FaxLoggingOptions.ahk" {FaxLoggingOptions}
#Import export ".\FaxOutboundRouting.ahk" {FaxOutboundRouting}
#Import export ".\FaxOutboundRoutingGroup.ahk" {FaxOutboundRoutingGroup}
#Import export ".\FaxOutboundRoutingGroups.ahk" {FaxOutboundRoutingGroups}
#Import export ".\FaxOutboundRoutingRule.ahk" {FaxOutboundRoutingRule}
#Import export ".\FaxOutboundRoutingRules.ahk" {FaxOutboundRoutingRules}
#Import export ".\FaxOutgoingArchive.ahk" {FaxOutgoingArchive}
#Import export ".\FaxOutgoingJob.ahk" {FaxOutgoingJob}
#Import export ".\FaxOutgoingJobs.ahk" {FaxOutgoingJobs}
#Import export ".\FaxOutgoingMessage.ahk" {FaxOutgoingMessage}
#Import export ".\FaxOutgoingMessageIterator.ahk" {FaxOutgoingMessageIterator}
#Import export ".\FaxOutgoingQueue.ahk" {FaxOutgoingQueue}
#Import export ".\FaxReceiptOptions.ahk" {FaxReceiptOptions}
#Import export ".\FaxRecipient.ahk" {FaxRecipient}
#Import export ".\FaxRecipients.ahk" {FaxRecipients}
#Import export ".\FaxSecurity.ahk" {FaxSecurity}
#Import export ".\FaxSecurity2.ahk" {FaxSecurity2}
#Import export ".\FaxSender.ahk" {FaxSender}
#Import export ".\FaxServer.ahk" {FaxServer}
#Import export ".\IFaxAccount.ahk" {IFaxAccount}
#Import export ".\IFaxAccountFolders.ahk" {IFaxAccountFolders}
#Import export ".\IFaxAccountIncomingArchive.ahk" {IFaxAccountIncomingArchive}
#Import export ".\IFaxAccountIncomingQueue.ahk" {IFaxAccountIncomingQueue}
#Import export ".\IFaxAccountNotify.ahk" {IFaxAccountNotify}
#Import export ".\IFaxAccountOutgoingArchive.ahk" {IFaxAccountOutgoingArchive}
#Import export ".\IFaxAccountOutgoingQueue.ahk" {IFaxAccountOutgoingQueue}
#Import export ".\IFaxAccountSet.ahk" {IFaxAccountSet}
#Import export ".\IFaxAccounts.ahk" {IFaxAccounts}
#Import export ".\IFaxActivity.ahk" {IFaxActivity}
#Import export ".\IFaxActivityLogging.ahk" {IFaxActivityLogging}
#Import export ".\IFaxConfiguration.ahk" {IFaxConfiguration}
#Import export ".\IFaxDevice.ahk" {IFaxDevice}
#Import export ".\IFaxDeviceIds.ahk" {IFaxDeviceIds}
#Import export ".\IFaxDeviceProvider.ahk" {IFaxDeviceProvider}
#Import export ".\IFaxDeviceProviders.ahk" {IFaxDeviceProviders}
#Import export ".\IFaxDevices.ahk" {IFaxDevices}
#Import export ".\IFaxDocument.ahk" {IFaxDocument}
#Import export ".\IFaxDocument2.ahk" {IFaxDocument2}
#Import export ".\IFaxEventLogging.ahk" {IFaxEventLogging}
#Import export ".\IFaxFolders.ahk" {IFaxFolders}
#Import export ".\IFaxInboundRouting.ahk" {IFaxInboundRouting}
#Import export ".\IFaxInboundRoutingExtension.ahk" {IFaxInboundRoutingExtension}
#Import export ".\IFaxInboundRoutingExtensions.ahk" {IFaxInboundRoutingExtensions}
#Import export ".\IFaxInboundRoutingMethod.ahk" {IFaxInboundRoutingMethod}
#Import export ".\IFaxInboundRoutingMethods.ahk" {IFaxInboundRoutingMethods}
#Import export ".\IFaxIncomingArchive.ahk" {IFaxIncomingArchive}
#Import export ".\IFaxIncomingJob.ahk" {IFaxIncomingJob}
#Import export ".\IFaxIncomingJobs.ahk" {IFaxIncomingJobs}
#Import export ".\IFaxIncomingMessage.ahk" {IFaxIncomingMessage}
#Import export ".\IFaxIncomingMessage2.ahk" {IFaxIncomingMessage2}
#Import export ".\IFaxIncomingMessageIterator.ahk" {IFaxIncomingMessageIterator}
#Import export ".\IFaxIncomingQueue.ahk" {IFaxIncomingQueue}
#Import export ".\IFaxJobStatus.ahk" {IFaxJobStatus}
#Import export ".\IFaxLoggingOptions.ahk" {IFaxLoggingOptions}
#Import export ".\IFaxOutboundRouting.ahk" {IFaxOutboundRouting}
#Import export ".\IFaxOutboundRoutingGroup.ahk" {IFaxOutboundRoutingGroup}
#Import export ".\IFaxOutboundRoutingGroups.ahk" {IFaxOutboundRoutingGroups}
#Import export ".\IFaxOutboundRoutingRule.ahk" {IFaxOutboundRoutingRule}
#Import export ".\IFaxOutboundRoutingRules.ahk" {IFaxOutboundRoutingRules}
#Import export ".\IFaxOutgoingArchive.ahk" {IFaxOutgoingArchive}
#Import export ".\IFaxOutgoingJob.ahk" {IFaxOutgoingJob}
#Import export ".\IFaxOutgoingJob2.ahk" {IFaxOutgoingJob2}
#Import export ".\IFaxOutgoingJobs.ahk" {IFaxOutgoingJobs}
#Import export ".\IFaxOutgoingMessage.ahk" {IFaxOutgoingMessage}
#Import export ".\IFaxOutgoingMessage2.ahk" {IFaxOutgoingMessage2}
#Import export ".\IFaxOutgoingMessageIterator.ahk" {IFaxOutgoingMessageIterator}
#Import export ".\IFaxOutgoingQueue.ahk" {IFaxOutgoingQueue}
#Import export ".\IFaxReceiptOptions.ahk" {IFaxReceiptOptions}
#Import export ".\IFaxRecipient.ahk" {IFaxRecipient}
#Import export ".\IFaxRecipients.ahk" {IFaxRecipients}
#Import export ".\IFaxSecurity.ahk" {IFaxSecurity}
#Import export ".\IFaxSecurity2.ahk" {IFaxSecurity2}
#Import export ".\IFaxSender.ahk" {IFaxSender}
#Import export ".\IFaxServer.ahk" {IFaxServer}
#Import export ".\IFaxServer2.ahk" {IFaxServer2}
#Import export ".\IFaxServerNotify.ahk" {IFaxServerNotify}
#Import export ".\IFaxServerNotify2.ahk" {IFaxServerNotify2}
#Import export ".\IStiDevice.ahk" {IStiDevice}
#Import export ".\IStiDeviceControl.ahk" {IStiDeviceControl}
#Import export ".\IStiUSD.ahk" {IStiUSD}
#Import export ".\IStillImageW.ahk" {IStillImageW}
#Import export ".\PFAXABORT.ahk" {PFAXABORT}
#Import export ".\PFAXACCESSCHECK.ahk" {PFAXACCESSCHECK}
#Import export ".\PFAXCLOSE.ahk" {PFAXCLOSE}
#Import export ".\PFAXCOMPLETEJOBPARAMSA.ahk" {PFAXCOMPLETEJOBPARAMSA}
#Import export ".\PFAXCOMPLETEJOBPARAMSW.ahk" {PFAXCOMPLETEJOBPARAMSW}
#Import export ".\PFAXCONNECTFAXSERVERA.ahk" {PFAXCONNECTFAXSERVERA}
#Import export ".\PFAXCONNECTFAXSERVERW.ahk" {PFAXCONNECTFAXSERVERW}
#Import export ".\PFAXDEVABORTOPERATION.ahk" {PFAXDEVABORTOPERATION}
#Import export ".\PFAXDEVCONFIGURE.ahk" {PFAXDEVCONFIGURE}
#Import export ".\PFAXDEVENDJOB.ahk" {PFAXDEVENDJOB}
#Import export ".\PFAXDEVINITIALIZE.ahk" {PFAXDEVINITIALIZE}
#Import export ".\PFAXDEVRECEIVE.ahk" {PFAXDEVRECEIVE}
#Import export ".\PFAXDEVREPORTSTATUS.ahk" {PFAXDEVREPORTSTATUS}
#Import export ".\PFAXDEVSEND.ahk" {PFAXDEVSEND}
#Import export ".\PFAXDEVSHUTDOWN.ahk" {PFAXDEVSHUTDOWN}
#Import export ".\PFAXDEVSTARTJOB.ahk" {PFAXDEVSTARTJOB}
#Import export ".\PFAXDEVVIRTUALDEVICECREATION.ahk" {PFAXDEVVIRTUALDEVICECREATION}
#Import export ".\PFAXENABLEROUTINGMETHODA.ahk" {PFAXENABLEROUTINGMETHODA}
#Import export ".\PFAXENABLEROUTINGMETHODW.ahk" {PFAXENABLEROUTINGMETHODW}
#Import export ".\PFAXENUMGLOBALROUTINGINFOA.ahk" {PFAXENUMGLOBALROUTINGINFOA}
#Import export ".\PFAXENUMGLOBALROUTINGINFOW.ahk" {PFAXENUMGLOBALROUTINGINFOW}
#Import export ".\PFAXENUMJOBSA.ahk" {PFAXENUMJOBSA}
#Import export ".\PFAXENUMJOBSW.ahk" {PFAXENUMJOBSW}
#Import export ".\PFAXENUMPORTSA.ahk" {PFAXENUMPORTSA}
#Import export ".\PFAXENUMPORTSW.ahk" {PFAXENUMPORTSW}
#Import export ".\PFAXENUMROUTINGMETHODSA.ahk" {PFAXENUMROUTINGMETHODSA}
#Import export ".\PFAXENUMROUTINGMETHODSW.ahk" {PFAXENUMROUTINGMETHODSW}
#Import export ".\PFAXFREEBUFFER.ahk" {PFAXFREEBUFFER}
#Import export ".\PFAXGETCONFIGURATIONA.ahk" {PFAXGETCONFIGURATIONA}
#Import export ".\PFAXGETCONFIGURATIONW.ahk" {PFAXGETCONFIGURATIONW}
#Import export ".\PFAXGETDEVICESTATUSA.ahk" {PFAXGETDEVICESTATUSA}
#Import export ".\PFAXGETDEVICESTATUSW.ahk" {PFAXGETDEVICESTATUSW}
#Import export ".\PFAXGETJOBA.ahk" {PFAXGETJOBA}
#Import export ".\PFAXGETJOBW.ahk" {PFAXGETJOBW}
#Import export ".\PFAXGETLOGGINGCATEGORIESA.ahk" {PFAXGETLOGGINGCATEGORIESA}
#Import export ".\PFAXGETLOGGINGCATEGORIESW.ahk" {PFAXGETLOGGINGCATEGORIESW}
#Import export ".\PFAXGETPAGEDATA.ahk" {PFAXGETPAGEDATA}
#Import export ".\PFAXGETPORTA.ahk" {PFAXGETPORTA}
#Import export ".\PFAXGETPORTW.ahk" {PFAXGETPORTW}
#Import export ".\PFAXGETROUTINGINFOA.ahk" {PFAXGETROUTINGINFOA}
#Import export ".\PFAXGETROUTINGINFOW.ahk" {PFAXGETROUTINGINFOW}
#Import export ".\PFAXINITIALIZEEVENTQUEUE.ahk" {PFAXINITIALIZEEVENTQUEUE}
#Import export ".\PFAXOPENPORT.ahk" {PFAXOPENPORT}
#Import export ".\PFAXPRINTCOVERPAGEA.ahk" {PFAXPRINTCOVERPAGEA}
#Import export ".\PFAXPRINTCOVERPAGEW.ahk" {PFAXPRINTCOVERPAGEW}
#Import export ".\PFAXREGISTERROUTINGEXTENSIONW.ahk" {PFAXREGISTERROUTINGEXTENSIONW}
#Import export ".\PFAXREGISTERSERVICEPROVIDERW.ahk" {PFAXREGISTERSERVICEPROVIDERW}
#Import export ".\PFAXROUTEADDFILE.ahk" {PFAXROUTEADDFILE}
#Import export ".\PFAXROUTEDELETEFILE.ahk" {PFAXROUTEDELETEFILE}
#Import export ".\PFAXROUTEDEVICECHANGENOTIFICATION.ahk" {PFAXROUTEDEVICECHANGENOTIFICATION}
#Import export ".\PFAXROUTEDEVICEENABLE.ahk" {PFAXROUTEDEVICEENABLE}
#Import export ".\PFAXROUTEENUMFILE.ahk" {PFAXROUTEENUMFILE}
#Import export ".\PFAXROUTEENUMFILES.ahk" {PFAXROUTEENUMFILES}
#Import export ".\PFAXROUTEGETFILE.ahk" {PFAXROUTEGETFILE}
#Import export ".\PFAXROUTEGETROUTINGINFO.ahk" {PFAXROUTEGETROUTINGINFO}
#Import export ".\PFAXROUTEINITIALIZE.ahk" {PFAXROUTEINITIALIZE}
#Import export ".\PFAXROUTEMETHOD.ahk" {PFAXROUTEMETHOD}
#Import export ".\PFAXROUTEMODIFYROUTINGDATA.ahk" {PFAXROUTEMODIFYROUTINGDATA}
#Import export ".\PFAXROUTESETROUTINGINFO.ahk" {PFAXROUTESETROUTINGINFO}
#Import export ".\PFAXSENDDOCUMENTA.ahk" {PFAXSENDDOCUMENTA}
#Import export ".\PFAXSENDDOCUMENTFORBROADCASTA.ahk" {PFAXSENDDOCUMENTFORBROADCASTA}
#Import export ".\PFAXSENDDOCUMENTFORBROADCASTW.ahk" {PFAXSENDDOCUMENTFORBROADCASTW}
#Import export ".\PFAXSENDDOCUMENTW.ahk" {PFAXSENDDOCUMENTW}
#Import export ".\PFAXSETCONFIGURATIONA.ahk" {PFAXSETCONFIGURATIONA}
#Import export ".\PFAXSETCONFIGURATIONW.ahk" {PFAXSETCONFIGURATIONW}
#Import export ".\PFAXSETGLOBALROUTINGINFOA.ahk" {PFAXSETGLOBALROUTINGINFOA}
#Import export ".\PFAXSETGLOBALROUTINGINFOW.ahk" {PFAXSETGLOBALROUTINGINFOW}
#Import export ".\PFAXSETJOBA.ahk" {PFAXSETJOBA}
#Import export ".\PFAXSETJOBW.ahk" {PFAXSETJOBW}
#Import export ".\PFAXSETLOGGINGCATEGORIESA.ahk" {PFAXSETLOGGINGCATEGORIESA}
#Import export ".\PFAXSETLOGGINGCATEGORIESW.ahk" {PFAXSETLOGGINGCATEGORIESW}
#Import export ".\PFAXSETPORTA.ahk" {PFAXSETPORTA}
#Import export ".\PFAXSETPORTW.ahk" {PFAXSETPORTW}
#Import export ".\PFAXSETROUTINGINFOA.ahk" {PFAXSETROUTINGINFOA}
#Import export ".\PFAXSETROUTINGINFOW.ahk" {PFAXSETROUTINGINFOW}
#Import export ".\PFAXSTARTPRINTJOBA.ahk" {PFAXSTARTPRINTJOBA}
#Import export ".\PFAXSTARTPRINTJOBW.ahk" {PFAXSTARTPRINTJOBW}
#Import export ".\PFAXUNREGISTERSERVICEPROVIDERW.ahk" {PFAXUNREGISTERSERVICEPROVIDERW}
#Import export ".\PFAX_EXT_CONFIG_CHANGE.ahk" {PFAX_EXT_CONFIG_CHANGE}
#Import export ".\PFAX_EXT_FREE_BUFFER.ahk" {PFAX_EXT_FREE_BUFFER}
#Import export ".\PFAX_EXT_GET_DATA.ahk" {PFAX_EXT_GET_DATA}
#Import export ".\PFAX_EXT_INITIALIZE_CONFIG.ahk" {PFAX_EXT_INITIALIZE_CONFIG}
#Import export ".\PFAX_EXT_REGISTER_FOR_EVENTS.ahk" {PFAX_EXT_REGISTER_FOR_EVENTS}
#Import export ".\PFAX_EXT_SET_DATA.ahk" {PFAX_EXT_SET_DATA}
#Import export ".\PFAX_EXT_UNREGISTER_FOR_EVENTS.ahk" {PFAX_EXT_UNREGISTER_FOR_EVENTS}
#Import export ".\PFAX_LINECALLBACK.ahk" {PFAX_LINECALLBACK}
#Import export ".\PFAX_RECIPIENT_CALLBACKA.ahk" {PFAX_RECIPIENT_CALLBACKA}
#Import export ".\PFAX_RECIPIENT_CALLBACKW.ahk" {PFAX_RECIPIENT_CALLBACKW}
#Import export ".\PFAX_ROUTING_INSTALLATION_CALLBACKW.ahk" {PFAX_ROUTING_INSTALLATION_CALLBACKW}
#Import export ".\PFAX_SEND_CALLBACK.ahk" {PFAX_SEND_CALLBACK}
#Import export ".\PFAX_SERVICE_CALLBACK.ahk" {PFAX_SERVICE_CALLBACK}
#Import export ".\STINOTIFY.ahk" {STINOTIFY}
#Import export ".\STISUBSCRIBE.ahk" {STISUBSCRIBE}
#Import export ".\STI_DEVICE_INFORMATIONW.ahk" {STI_DEVICE_INFORMATIONW}
#Import export ".\STI_DEVICE_MJ_TYPE.ahk" {STI_DEVICE_MJ_TYPE}
#Import export ".\STI_DEVICE_STATUS.ahk" {STI_DEVICE_STATUS}
#Import export ".\STI_DEV_CAPS.ahk" {STI_DEV_CAPS}
#Import export ".\STI_DIAG.ahk" {STI_DIAG}
#Import export ".\STI_USD_CAPS.ahk" {STI_USD_CAPS}
#Import export ".\STI_WIA_DEVICE_INFORMATIONW.ahk" {STI_WIA_DEVICE_INFORMATIONW}
#Import export ".\SendToMode.ahk" {SendToMode}
#Import export ".\_ERROR_INFOW.ahk" {_ERROR_INFOW}
