#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\Guid.ahk" { Guid }
#Import "..\..\Foundation\HRESULT.ahk" { HRESULT }
#Import "..\Com\IUnknown.ahk" { IUnknown }
#Import ".\IExtendControlbar.ahk" { IExtendControlbar }
#Import ".\MMC_CONTROL_TYPE.ahk" { MMC_CONTROL_TYPE }

/**
 * The IControlbar interface provides a way to create toolbars and other controls.
 * @see https://learn.microsoft.com/windows/win32/api/mmc/nn-mmc-icontrolbar
 * @namespace Windows.Win32.System.Mmc
 */
export default struct IControlbar extends IUnknown {
    /**
     * The interface identifier for IControlbar
     * @type {Guid}
     */
    static IID := Guid("{69fb811e-6c1c-11d0-a2cb-00c04fd909dd}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for IControlbar interfaces
    */
    struct Vtbl extends IUnknown.Vtbl {
        Create : IntPtr
        Attach : IntPtr
        Detach : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := IControlbar.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * The IControlbar::Create method creates and returns the control requested by the snap-in.
     * @remarks
     * The <b>IControlbar::Create</b> method increments the reference count on the control bar object it creates, so the snap-in is not required to call the AddRef method on the interface.
     * 
     * Although COMBOBOXBAR is included in Mmc.idl in connection with the nType parameter, it is not implemented.
     * @param {MMC_CONTROL_TYPE} nType A value that specifies the type of control to be associated; taken from the 
     * <a href="https://docs.microsoft.com/windows/desktop/api/mmc/ne-mmc-mmc_control_type">MMC_CONTROL_TYPE</a> enumeration.
     * @param {IExtendControlbar} pExtendControlbar A pointer to the snap-in's 
     * <a href="https://docs.microsoft.com/windows/desktop/api/mmc/nn-mmc-iextendcontrolbar">IExtendControlbar</a> interface that is to be associated with the control (toolbar or menu button) that will be created. Notifications generated by the new control will be sent to 
     * <a href="https://docs.microsoft.com/windows/desktop/api/mmc/nf-mmc-iextendcontrolbar-controlbarnotify">IExtendControlBar::ControlbarNotify</a>.
     * @returns {IUnknown} A pointer to the address of the IUnknown interface of the control that was created.
     * @see https://learn.microsoft.com/windows/win32/api/mmc/nf-mmc-icontrolbar-create
     */
    Create(nType, pExtendControlbar) {
        result := ComCall(3, this, MMC_CONTROL_TYPE, nType, "ptr", pExtendControlbar, "ptr*", &ppUnknown := 0, "HRESULT")
        return IUnknown(ppUnknown)
    }

    /**
     * The IControlbar::Attach method allows the snap-in to associate a control with a control bar.
     * @remarks
     * Although COMBOBOXBAR appears in Mmc.idl in connection with the nType parameter, it is not implemented.
     * @param {MMC_CONTROL_TYPE} nType A value that specifies the type of control to be associated with the control bar, taken from the 
     * <a href="https://docs.microsoft.com/windows/desktop/api/mmc/ne-mmc-mmc_control_type">MMC_CONTROL_TYPE</a> enumeration.
     * @param {IUnknown} lpUnknown A pointer to the IUnknown interface on the control object to be inserted.
     * @returns {HRESULT} This method can return one of these values.
     * @see https://learn.microsoft.com/windows/win32/api/mmc/nf-mmc-icontrolbar-attach
     */
    Attach(nType, lpUnknown) {
        result := ComCall(4, this, MMC_CONTROL_TYPE, nType, "ptr", lpUnknown, "HRESULT")
        return result
    }

    /**
     * The IControlbar::Detach method breaks the association between a control and the control bar. This command removes or detaches the control from the control bar on which it is displayed.
     * @param {IUnknown} lpUnknown A pointer to the 
     * <a href="https://docs.microsoft.com/windows/desktop/api/unknwn/nn-unknwn-iunknown">IUnknown</a> interface on the control object that represents the control removed.
     * @returns {HRESULT} This method can return one of these values.
     * @see https://learn.microsoft.com/windows/win32/api/mmc/nf-mmc-icontrolbar-detach
     */
    Detach(lpUnknown) {
        result := ComCall(5, this, "ptr", lpUnknown, "HRESULT")
        return result
    }

    Query(iid) {
        if (IControlbar.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.Create := CallbackCreate(GetMethod(implObj, "Create"), flags, 4)
        this.vtbl.Attach := CallbackCreate(GetMethod(implObj, "Attach"), flags, 3)
        this.vtbl.Detach := CallbackCreate(GetMethod(implObj, "Detach"), flags, 2)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.Create)
        CallbackFree(this.vtbl.Attach)
        CallbackFree(this.vtbl.Detach)
    }
}
