#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Constants.ahk" {*}
#Import export ".\IWPCGamesSettings.ahk" {IWPCGamesSettings}
#Import export ".\IWPCProviderConfig.ahk" {IWPCProviderConfig}
#Import export ".\IWPCProviderState.ahk" {IWPCProviderState}
#Import export ".\IWPCProviderSupport.ahk" {IWPCProviderSupport}
#Import export ".\IWPCSettings.ahk" {IWPCSettings}
#Import export ".\IWPCWebSettings.ahk" {IWPCWebSettings}
#Import export ".\IWindowsParentalControls.ahk" {IWindowsParentalControls}
#Import export ".\IWindowsParentalControlsCore.ahk" {IWindowsParentalControlsCore}
#Import export ".\WPCFLAG_IM_FEATURE.ahk" {WPCFLAG_IM_FEATURE}
#Import export ".\WPCFLAG_IM_LEAVE.ahk" {WPCFLAG_IM_LEAVE}
#Import export ".\WPCFLAG_ISBLOCKED.ahk" {WPCFLAG_ISBLOCKED}
#Import export ".\WPCFLAG_LOGOFF_TYPE.ahk" {WPCFLAG_LOGOFF_TYPE}
#Import export ".\WPCFLAG_OVERRIDE.ahk" {WPCFLAG_OVERRIDE}
#Import export ".\WPCFLAG_RESTRICTION.ahk" {WPCFLAG_RESTRICTION}
#Import export ".\WPCFLAG_VISIBILITY.ahk" {WPCFLAG_VISIBILITY}
#Import export ".\WPCFLAG_WEB_SETTING.ahk" {WPCFLAG_WEB_SETTING}
#Import export ".\WPC_ARGS_APPLICATIONEVENT.ahk" {WPC_ARGS_APPLICATIONEVENT}
#Import export ".\WPC_ARGS_APPOVERRIDEEVENT.ahk" {WPC_ARGS_APPOVERRIDEEVENT}
#Import export ".\WPC_ARGS_COMPUTERUSAGEEVENT.ahk" {WPC_ARGS_COMPUTERUSAGEEVENT}
#Import export ".\WPC_ARGS_CONTENTUSAGEEVENT.ahk" {WPC_ARGS_CONTENTUSAGEEVENT}
#Import export ".\WPC_ARGS_CONVERSATIONINITEVENT.ahk" {WPC_ARGS_CONVERSATIONINITEVENT}
#Import export ".\WPC_ARGS_CONVERSATIONJOINEVENT.ahk" {WPC_ARGS_CONVERSATIONJOINEVENT}
#Import export ".\WPC_ARGS_CONVERSATIONLEAVEEVENT.ahk" {WPC_ARGS_CONVERSATIONLEAVEEVENT}
#Import export ".\WPC_ARGS_CUSTOMEVENT.ahk" {WPC_ARGS_CUSTOMEVENT}
#Import export ".\WPC_ARGS_EMAILCONTACTEVENT.ahk" {WPC_ARGS_EMAILCONTACTEVENT}
#Import export ".\WPC_ARGS_EMAILRECEIEVEDEVENT.ahk" {WPC_ARGS_EMAILRECEIEVEDEVENT}
#Import export ".\WPC_ARGS_EMAILSENTEVENT.ahk" {WPC_ARGS_EMAILSENTEVENT}
#Import export ".\WPC_ARGS_FILEDOWNLOADEVENT.ahk" {WPC_ARGS_FILEDOWNLOADEVENT}
#Import export ".\WPC_ARGS_GAMESTARTEVENT.ahk" {WPC_ARGS_GAMESTARTEVENT}
#Import export ".\WPC_ARGS_IMCONTACTEVENT.ahk" {WPC_ARGS_IMCONTACTEVENT}
#Import export ".\WPC_ARGS_IMFEATUREEVENT.ahk" {WPC_ARGS_IMFEATUREEVENT}
#Import export ".\WPC_ARGS_MEDIADOWNLOADEVENT.ahk" {WPC_ARGS_MEDIADOWNLOADEVENT}
#Import export ".\WPC_ARGS_MEDIAPLAYBACKEVENT.ahk" {WPC_ARGS_MEDIAPLAYBACKEVENT}
#Import export ".\WPC_ARGS_SAFERAPPBLOCKED.ahk" {WPC_ARGS_SAFERAPPBLOCKED}
#Import export ".\WPC_ARGS_SETTINGSCHANGEEVENT.ahk" {WPC_ARGS_SETTINGSCHANGEEVENT}
#Import export ".\WPC_ARGS_URLVISITEVENT.ahk" {WPC_ARGS_URLVISITEVENT}
#Import export ".\WPC_ARGS_WEBOVERRIDEEVENT.ahk" {WPC_ARGS_WEBOVERRIDEEVENT}
#Import export ".\WPC_ARGS_WEBSITEVISITEVENT.ahk" {WPC_ARGS_WEBSITEVISITEVENT}
#Import export ".\WPC_MEDIA_EXPLICIT.ahk" {WPC_MEDIA_EXPLICIT}
#Import export ".\WPC_MEDIA_TYPE.ahk" {WPC_MEDIA_TYPE}
#Import export ".\WPC_SETTINGS.ahk" {WPC_SETTINGS}
#Import export ".\WindowsParentalControls.ahk" {WindowsParentalControls}
#Import export ".\WpcProviderSupport.ahk" {WpcProviderSupport}
#Import export ".\WpcSettingsProvider.ahk" {WpcSettingsProvider}
