#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import "..\..\Foundation\PWSTR.ahk" { PWSTR }
#Import ".\DHCP_IPV6_ADDRESS.ahk" { DHCP_IPV6_ADDRESS }

/**
 * Contains information about an IPv6 subnet.
 * @see https://learn.microsoft.com/windows/win32/api/dhcpsapi/ns-dhcpsapi-dhcp_subnet_info_v6
 * @namespace Windows.Win32.NetworkManagement.Dhcp
 */
export default struct DHCP_SUBNET_INFO_V6 {
    #StructPack 8

    /**
     * <a href="https://docs.microsoft.com/windows/desktop/api/dhcpsapi/ns-dhcpsapi-dhcp_ipv6_address">DHCP_IPV6_ADDRESS</a> structure containing the IPv6 prefix.
     */
    SubnetAddress : DHCP_IPV6_ADDRESS

    /**
     * <b>ULONG</b> value that specifies the length of the IPv6 prefix.
     */
    Prefix : UInt32

    /**
     * <b>USHORT</b> value that specifies the preference for the IPv6 prefix.
     */
    Preference : UInt16

    /**
     * Pointer to a null-terminated Unicode string that contains the name of the IPv6 prefix.
     */
    SubnetName : PWSTR

    /**
     * Pointer to a null-terminated Unicode string that contains an optional comment for the IPv6 prefix.
     */
    SubnetComment : PWSTR

    /**
     * An enumeration of the <a href="https://docs.microsoft.com/windows/desktop/api/dhcpsapi/ne-dhcpsapi-dhcp_subnet_state">DHCP_SUBNET_STATE</a> that indicates the current state of the IPv6 prefix.
     */
    State : UInt32

    /**
     * A <b>DWORD</b> value that serves as the unique identifier for the IPv6 prefix. This value is generated by the DHCPv6 server.
     */
    ScopeId : UInt32

}
