#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\D3D10_ASYNC_GETDATA_FLAG.ahk" {D3D10_ASYNC_GETDATA_FLAG}
#Import export ".\D3D10_BIND_FLAG.ahk" {D3D10_BIND_FLAG}
#Import export ".\D3D10_BLEND.ahk" {D3D10_BLEND}
#Import export ".\D3D10_BLEND_DESC.ahk" {D3D10_BLEND_DESC}
#Import export ".\D3D10_BLEND_DESC1.ahk" {D3D10_BLEND_DESC1}
#Import export ".\D3D10_BLEND_OP.ahk" {D3D10_BLEND_OP}
#Import export ".\D3D10_BOX.ahk" {D3D10_BOX}
#Import export ".\D3D10_BUFFER_DESC.ahk" {D3D10_BUFFER_DESC}
#Import export ".\D3D10_BUFFER_RTV.ahk" {D3D10_BUFFER_RTV}
#Import export ".\D3D10_BUFFER_SRV.ahk" {D3D10_BUFFER_SRV}
#Import export ".\D3D10_CLEAR_FLAG.ahk" {D3D10_CLEAR_FLAG}
#Import export ".\D3D10_COLOR_WRITE_ENABLE.ahk" {D3D10_COLOR_WRITE_ENABLE}
#Import export ".\D3D10_COMPARISON_FUNC.ahk" {D3D10_COMPARISON_FUNC}
#Import export ".\D3D10_COUNTER.ahk" {D3D10_COUNTER}
#Import export ".\D3D10_COUNTER_DESC.ahk" {D3D10_COUNTER_DESC}
#Import export ".\D3D10_COUNTER_INFO.ahk" {D3D10_COUNTER_INFO}
#Import export ".\D3D10_COUNTER_TYPE.ahk" {D3D10_COUNTER_TYPE}
#Import export ".\D3D10_CPU_ACCESS_FLAG.ahk" {D3D10_CPU_ACCESS_FLAG}
#Import export ".\D3D10_CREATE_DEVICE_FLAG.ahk" {D3D10_CREATE_DEVICE_FLAG}
#Import export ".\D3D10_CULL_MODE.ahk" {D3D10_CULL_MODE}
#Import export ".\D3D10_DEPTH_STENCILOP_DESC.ahk" {D3D10_DEPTH_STENCILOP_DESC}
#Import export ".\D3D10_DEPTH_STENCIL_DESC.ahk" {D3D10_DEPTH_STENCIL_DESC}
#Import export ".\D3D10_DEPTH_STENCIL_VIEW_DESC.ahk" {D3D10_DEPTH_STENCIL_VIEW_DESC}
#Import export ".\D3D10_DEPTH_WRITE_MASK.ahk" {D3D10_DEPTH_WRITE_MASK}
#Import export ".\D3D10_DEVICE_STATE_TYPES.ahk" {D3D10_DEVICE_STATE_TYPES}
#Import export ".\D3D10_DRIVER_TYPE.ahk" {D3D10_DRIVER_TYPE}
#Import export ".\D3D10_DSV_DIMENSION.ahk" {D3D10_DSV_DIMENSION}
#Import export ".\D3D10_EFFECT_DESC.ahk" {D3D10_EFFECT_DESC}
#Import export ".\D3D10_EFFECT_SHADER_DESC.ahk" {D3D10_EFFECT_SHADER_DESC}
#Import export ".\D3D10_EFFECT_TYPE_DESC.ahk" {D3D10_EFFECT_TYPE_DESC}
#Import export ".\D3D10_EFFECT_VARIABLE_DESC.ahk" {D3D10_EFFECT_VARIABLE_DESC}
#Import export ".\D3D10_FEATURE_LEVEL1.ahk" {D3D10_FEATURE_LEVEL1}
#Import export ".\D3D10_FILL_MODE.ahk" {D3D10_FILL_MODE}
#Import export ".\D3D10_FILTER.ahk" {D3D10_FILTER}
#Import export ".\D3D10_FILTER_TYPE.ahk" {D3D10_FILTER_TYPE}
#Import export ".\D3D10_FORMAT_SUPPORT.ahk" {D3D10_FORMAT_SUPPORT}
#Import export ".\D3D10_INFO_QUEUE_FILTER.ahk" {D3D10_INFO_QUEUE_FILTER}
#Import export ".\D3D10_INFO_QUEUE_FILTER_DESC.ahk" {D3D10_INFO_QUEUE_FILTER_DESC}
#Import export ".\D3D10_INPUT_CLASSIFICATION.ahk" {D3D10_INPUT_CLASSIFICATION}
#Import export ".\D3D10_INPUT_ELEMENT_DESC.ahk" {D3D10_INPUT_ELEMENT_DESC}
#Import export ".\D3D10_MAP.ahk" {D3D10_MAP}
#Import export ".\D3D10_MAPPED_TEXTURE2D.ahk" {D3D10_MAPPED_TEXTURE2D}
#Import export ".\D3D10_MAPPED_TEXTURE3D.ahk" {D3D10_MAPPED_TEXTURE3D}
#Import export ".\D3D10_MAP_FLAG.ahk" {D3D10_MAP_FLAG}
#Import export ".\D3D10_MESSAGE.ahk" {D3D10_MESSAGE}
#Import export ".\D3D10_MESSAGE_CATEGORY.ahk" {D3D10_MESSAGE_CATEGORY}
#Import export ".\D3D10_MESSAGE_ID.ahk" {D3D10_MESSAGE_ID}
#Import export ".\D3D10_MESSAGE_SEVERITY.ahk" {D3D10_MESSAGE_SEVERITY}
#Import export ".\D3D10_PASS_DESC.ahk" {D3D10_PASS_DESC}
#Import export ".\D3D10_PASS_SHADER_DESC.ahk" {D3D10_PASS_SHADER_DESC}
#Import export ".\D3D10_QUERY.ahk" {D3D10_QUERY}
#Import export ".\D3D10_QUERY_DATA_PIPELINE_STATISTICS.ahk" {D3D10_QUERY_DATA_PIPELINE_STATISTICS}
#Import export ".\D3D10_QUERY_DATA_SO_STATISTICS.ahk" {D3D10_QUERY_DATA_SO_STATISTICS}
#Import export ".\D3D10_QUERY_DATA_TIMESTAMP_DISJOINT.ahk" {D3D10_QUERY_DATA_TIMESTAMP_DISJOINT}
#Import export ".\D3D10_QUERY_DESC.ahk" {D3D10_QUERY_DESC}
#Import export ".\D3D10_QUERY_MISC_FLAG.ahk" {D3D10_QUERY_MISC_FLAG}
#Import export ".\D3D10_RAISE_FLAG.ahk" {D3D10_RAISE_FLAG}
#Import export ".\D3D10_RASTERIZER_DESC.ahk" {D3D10_RASTERIZER_DESC}
#Import export ".\D3D10_RENDER_TARGET_BLEND_DESC1.ahk" {D3D10_RENDER_TARGET_BLEND_DESC1}
#Import export ".\D3D10_RENDER_TARGET_VIEW_DESC.ahk" {D3D10_RENDER_TARGET_VIEW_DESC}
#Import export ".\D3D10_RESOURCE_DIMENSION.ahk" {D3D10_RESOURCE_DIMENSION}
#Import export ".\D3D10_RESOURCE_MISC_FLAG.ahk" {D3D10_RESOURCE_MISC_FLAG}
#Import export ".\D3D10_RTV_DIMENSION.ahk" {D3D10_RTV_DIMENSION}
#Import export ".\D3D10_SAMPLER_DESC.ahk" {D3D10_SAMPLER_DESC}
#Import export ".\D3D10_SHADER_BUFFER_DESC.ahk" {D3D10_SHADER_BUFFER_DESC}
#Import export ".\D3D10_SHADER_DEBUG_FILE_INFO.ahk" {D3D10_SHADER_DEBUG_FILE_INFO}
#Import export ".\D3D10_SHADER_DEBUG_INFO.ahk" {D3D10_SHADER_DEBUG_INFO}
#Import export ".\D3D10_SHADER_DEBUG_INPUT_INFO.ahk" {D3D10_SHADER_DEBUG_INPUT_INFO}
#Import export ".\D3D10_SHADER_DEBUG_INST_INFO.ahk" {D3D10_SHADER_DEBUG_INST_INFO}
#Import export ".\D3D10_SHADER_DEBUG_OUTPUTREG_INFO.ahk" {D3D10_SHADER_DEBUG_OUTPUTREG_INFO}
#Import export ".\D3D10_SHADER_DEBUG_OUTPUTVAR.ahk" {D3D10_SHADER_DEBUG_OUTPUTVAR}
#Import export ".\D3D10_SHADER_DEBUG_REGTYPE.ahk" {D3D10_SHADER_DEBUG_REGTYPE}
#Import export ".\D3D10_SHADER_DEBUG_SCOPETYPE.ahk" {D3D10_SHADER_DEBUG_SCOPETYPE}
#Import export ".\D3D10_SHADER_DEBUG_SCOPEVAR_INFO.ahk" {D3D10_SHADER_DEBUG_SCOPEVAR_INFO}
#Import export ".\D3D10_SHADER_DEBUG_SCOPE_INFO.ahk" {D3D10_SHADER_DEBUG_SCOPE_INFO}
#Import export ".\D3D10_SHADER_DEBUG_TOKEN_INFO.ahk" {D3D10_SHADER_DEBUG_TOKEN_INFO}
#Import export ".\D3D10_SHADER_DEBUG_VARTYPE.ahk" {D3D10_SHADER_DEBUG_VARTYPE}
#Import export ".\D3D10_SHADER_DEBUG_VAR_INFO.ahk" {D3D10_SHADER_DEBUG_VAR_INFO}
#Import export ".\D3D10_SHADER_DESC.ahk" {D3D10_SHADER_DESC}
#Import export ".\D3D10_SHADER_INPUT_BIND_DESC.ahk" {D3D10_SHADER_INPUT_BIND_DESC}
#Import export ".\D3D10_SHADER_RESOURCE_VIEW_DESC.ahk" {D3D10_SHADER_RESOURCE_VIEW_DESC}
#Import export ".\D3D10_SHADER_RESOURCE_VIEW_DESC1.ahk" {D3D10_SHADER_RESOURCE_VIEW_DESC1}
#Import export ".\D3D10_SHADER_TYPE_DESC.ahk" {D3D10_SHADER_TYPE_DESC}
#Import export ".\D3D10_SHADER_VARIABLE_DESC.ahk" {D3D10_SHADER_VARIABLE_DESC}
#Import export ".\D3D10_SIGNATURE_PARAMETER_DESC.ahk" {D3D10_SIGNATURE_PARAMETER_DESC}
#Import export ".\D3D10_SO_DECLARATION_ENTRY.ahk" {D3D10_SO_DECLARATION_ENTRY}
#Import export ".\D3D10_STANDARD_MULTISAMPLE_QUALITY_LEVELS.ahk" {D3D10_STANDARD_MULTISAMPLE_QUALITY_LEVELS}
#Import export ".\D3D10_STATE_BLOCK_MASK.ahk" {D3D10_STATE_BLOCK_MASK}
#Import export ".\D3D10_STENCIL_OP.ahk" {D3D10_STENCIL_OP}
#Import export ".\D3D10_SUBRESOURCE_DATA.ahk" {D3D10_SUBRESOURCE_DATA}
#Import export ".\D3D10_TECHNIQUE_DESC.ahk" {D3D10_TECHNIQUE_DESC}
#Import export ".\D3D10_TEX1D_ARRAY_DSV.ahk" {D3D10_TEX1D_ARRAY_DSV}
#Import export ".\D3D10_TEX1D_ARRAY_RTV.ahk" {D3D10_TEX1D_ARRAY_RTV}
#Import export ".\D3D10_TEX1D_ARRAY_SRV.ahk" {D3D10_TEX1D_ARRAY_SRV}
#Import export ".\D3D10_TEX1D_DSV.ahk" {D3D10_TEX1D_DSV}
#Import export ".\D3D10_TEX1D_RTV.ahk" {D3D10_TEX1D_RTV}
#Import export ".\D3D10_TEX1D_SRV.ahk" {D3D10_TEX1D_SRV}
#Import export ".\D3D10_TEX2DMS_ARRAY_DSV.ahk" {D3D10_TEX2DMS_ARRAY_DSV}
#Import export ".\D3D10_TEX2DMS_ARRAY_RTV.ahk" {D3D10_TEX2DMS_ARRAY_RTV}
#Import export ".\D3D10_TEX2DMS_ARRAY_SRV.ahk" {D3D10_TEX2DMS_ARRAY_SRV}
#Import export ".\D3D10_TEX2DMS_DSV.ahk" {D3D10_TEX2DMS_DSV}
#Import export ".\D3D10_TEX2DMS_RTV.ahk" {D3D10_TEX2DMS_RTV}
#Import export ".\D3D10_TEX2DMS_SRV.ahk" {D3D10_TEX2DMS_SRV}
#Import export ".\D3D10_TEX2D_ARRAY_DSV.ahk" {D3D10_TEX2D_ARRAY_DSV}
#Import export ".\D3D10_TEX2D_ARRAY_RTV.ahk" {D3D10_TEX2D_ARRAY_RTV}
#Import export ".\D3D10_TEX2D_ARRAY_SRV.ahk" {D3D10_TEX2D_ARRAY_SRV}
#Import export ".\D3D10_TEX2D_DSV.ahk" {D3D10_TEX2D_DSV}
#Import export ".\D3D10_TEX2D_RTV.ahk" {D3D10_TEX2D_RTV}
#Import export ".\D3D10_TEX2D_SRV.ahk" {D3D10_TEX2D_SRV}
#Import export ".\D3D10_TEX3D_RTV.ahk" {D3D10_TEX3D_RTV}
#Import export ".\D3D10_TEX3D_SRV.ahk" {D3D10_TEX3D_SRV}
#Import export ".\D3D10_TEXCUBE_ARRAY_SRV1.ahk" {D3D10_TEXCUBE_ARRAY_SRV1}
#Import export ".\D3D10_TEXCUBE_SRV.ahk" {D3D10_TEXCUBE_SRV}
#Import export ".\D3D10_TEXTURE1D_DESC.ahk" {D3D10_TEXTURE1D_DESC}
#Import export ".\D3D10_TEXTURE2D_DESC.ahk" {D3D10_TEXTURE2D_DESC}
#Import export ".\D3D10_TEXTURE3D_DESC.ahk" {D3D10_TEXTURE3D_DESC}
#Import export ".\D3D10_TEXTURECUBE_FACE.ahk" {D3D10_TEXTURECUBE_FACE}
#Import export ".\D3D10_TEXTURE_ADDRESS_MODE.ahk" {D3D10_TEXTURE_ADDRESS_MODE}
#Import export ".\D3D10_USAGE.ahk" {D3D10_USAGE}
#Import export ".\D3D10_VIEWPORT.ahk" {D3D10_VIEWPORT}
#Import export ".\ID3D10Asynchronous.ahk" {ID3D10Asynchronous}
#Import export ".\ID3D10BlendState.ahk" {ID3D10BlendState}
#Import export ".\ID3D10BlendState1.ahk" {ID3D10BlendState1}
#Import export ".\ID3D10Buffer.ahk" {ID3D10Buffer}
#Import export ".\ID3D10Counter.ahk" {ID3D10Counter}
#Import export ".\ID3D10Debug.ahk" {ID3D10Debug}
#Import export ".\ID3D10DepthStencilState.ahk" {ID3D10DepthStencilState}
#Import export ".\ID3D10DepthStencilView.ahk" {ID3D10DepthStencilView}
#Import export ".\ID3D10Device.ahk" {ID3D10Device}
#Import export ".\ID3D10Device1.ahk" {ID3D10Device1}
#Import export ".\ID3D10DeviceChild.ahk" {ID3D10DeviceChild}
#Import export ".\ID3D10Effect.ahk" {ID3D10Effect}
#Import export ".\ID3D10EffectBlendVariable.ahk" {ID3D10EffectBlendVariable}
#Import export ".\ID3D10EffectConstantBuffer.ahk" {ID3D10EffectConstantBuffer}
#Import export ".\ID3D10EffectDepthStencilVariable.ahk" {ID3D10EffectDepthStencilVariable}
#Import export ".\ID3D10EffectDepthStencilViewVariable.ahk" {ID3D10EffectDepthStencilViewVariable}
#Import export ".\ID3D10EffectMatrixVariable.ahk" {ID3D10EffectMatrixVariable}
#Import export ".\ID3D10EffectPass.ahk" {ID3D10EffectPass}
#Import export ".\ID3D10EffectPool.ahk" {ID3D10EffectPool}
#Import export ".\ID3D10EffectRasterizerVariable.ahk" {ID3D10EffectRasterizerVariable}
#Import export ".\ID3D10EffectRenderTargetViewVariable.ahk" {ID3D10EffectRenderTargetViewVariable}
#Import export ".\ID3D10EffectSamplerVariable.ahk" {ID3D10EffectSamplerVariable}
#Import export ".\ID3D10EffectScalarVariable.ahk" {ID3D10EffectScalarVariable}
#Import export ".\ID3D10EffectShaderResourceVariable.ahk" {ID3D10EffectShaderResourceVariable}
#Import export ".\ID3D10EffectShaderVariable.ahk" {ID3D10EffectShaderVariable}
#Import export ".\ID3D10EffectStringVariable.ahk" {ID3D10EffectStringVariable}
#Import export ".\ID3D10EffectTechnique.ahk" {ID3D10EffectTechnique}
#Import export ".\ID3D10EffectType.ahk" {ID3D10EffectType}
#Import export ".\ID3D10EffectVariable.ahk" {ID3D10EffectVariable}
#Import export ".\ID3D10EffectVectorVariable.ahk" {ID3D10EffectVectorVariable}
#Import export ".\ID3D10GeometryShader.ahk" {ID3D10GeometryShader}
#Import export ".\ID3D10InfoQueue.ahk" {ID3D10InfoQueue}
#Import export ".\ID3D10InputLayout.ahk" {ID3D10InputLayout}
#Import export ".\ID3D10Multithread.ahk" {ID3D10Multithread}
#Import export ".\ID3D10PixelShader.ahk" {ID3D10PixelShader}
#Import export ".\ID3D10Predicate.ahk" {ID3D10Predicate}
#Import export ".\ID3D10Query.ahk" {ID3D10Query}
#Import export ".\ID3D10RasterizerState.ahk" {ID3D10RasterizerState}
#Import export ".\ID3D10RenderTargetView.ahk" {ID3D10RenderTargetView}
#Import export ".\ID3D10Resource.ahk" {ID3D10Resource}
#Import export ".\ID3D10SamplerState.ahk" {ID3D10SamplerState}
#Import export ".\ID3D10ShaderReflection.ahk" {ID3D10ShaderReflection}
#Import export ".\ID3D10ShaderReflection1.ahk" {ID3D10ShaderReflection1}
#Import export ".\ID3D10ShaderReflectionConstantBuffer.ahk" {ID3D10ShaderReflectionConstantBuffer}
#Import export ".\ID3D10ShaderReflectionType.ahk" {ID3D10ShaderReflectionType}
#Import export ".\ID3D10ShaderReflectionVariable.ahk" {ID3D10ShaderReflectionVariable}
#Import export ".\ID3D10ShaderResourceView.ahk" {ID3D10ShaderResourceView}
#Import export ".\ID3D10ShaderResourceView1.ahk" {ID3D10ShaderResourceView1}
#Import export ".\ID3D10StateBlock.ahk" {ID3D10StateBlock}
#Import export ".\ID3D10SwitchToRef.ahk" {ID3D10SwitchToRef}
#Import export ".\ID3D10Texture1D.ahk" {ID3D10Texture1D}
#Import export ".\ID3D10Texture2D.ahk" {ID3D10Texture2D}
#Import export ".\ID3D10Texture3D.ahk" {ID3D10Texture3D}
#Import export ".\ID3D10VertexShader.ahk" {ID3D10VertexShader}
#Import export ".\ID3D10View.ahk" {ID3D10View}
#Import export ".\PFN_D3D10_CREATE_DEVICE1.ahk" {PFN_D3D10_CREATE_DEVICE1}
#Import export ".\PFN_D3D10_CREATE_DEVICE_AND_SWAP_CHAIN1.ahk" {PFN_D3D10_CREATE_DEVICE_AND_SWAP_CHAIN1}
