#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32Enum.ahk

/**
 * Debug messages for setting up an info-queue filter (see D3D10_INFO_QUEUE_FILTER); use these messages to allow or deny message categories to pass through the storage and retrieval filters.
 * @see https://learn.microsoft.com/windows/win32/api/d3d10sdklayers/ne-d3d10sdklayers-d3d10_message_id
 * @namespace Windows.Win32.Graphics.Direct3D10
 */
class D3D10_MESSAGE_ID extends Win32Enum {

    /**
     * Native name: D3D10_MESSAGE_ID_UNKNOWN
     * @type {Integer (Int32)}
     */
    static UNKNOWN => 0

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_HAZARD
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETVERTEXBUFFERS_HAZARD => 1

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_HAZARD
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETINDEXBUFFER_HAZARD => 2

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_VSSETSHADERRESOURCES_HAZARD
     * @type {Integer (Int32)}
     */
    static DEVICE_VSSETSHADERRESOURCES_HAZARD => 3

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_VSSETCONSTANTBUFFERS_HAZARD
     * @type {Integer (Int32)}
     */
    static DEVICE_VSSETCONSTANTBUFFERS_HAZARD => 4

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_GSSETSHADERRESOURCES_HAZARD
     * @type {Integer (Int32)}
     */
    static DEVICE_GSSETSHADERRESOURCES_HAZARD => 5

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_GSSETCONSTANTBUFFERS_HAZARD
     * @type {Integer (Int32)}
     */
    static DEVICE_GSSETCONSTANTBUFFERS_HAZARD => 6

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_PSSETSHADERRESOURCES_HAZARD
     * @type {Integer (Int32)}
     */
    static DEVICE_PSSETSHADERRESOURCES_HAZARD => 7

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_PSSETCONSTANTBUFFERS_HAZARD
     * @type {Integer (Int32)}
     */
    static DEVICE_PSSETCONSTANTBUFFERS_HAZARD => 8

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_OMSETRENDERTARGETS_HAZARD
     * @type {Integer (Int32)}
     */
    static DEVICE_OMSETRENDERTARGETS_HAZARD => 9

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_SOSETTARGETS_HAZARD
     * @type {Integer (Int32)}
     */
    static DEVICE_SOSETTARGETS_HAZARD => 10

    /**
     * Native name: D3D10_MESSAGE_ID_STRING_FROM_APPLICATION
     * @type {Integer (Int32)}
     */
    static STRING_FROM_APPLICATION => 11

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_THIS
     * @type {Integer (Int32)}
     */
    static CORRUPTED_THIS => 12

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER1
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER1 => 13

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER2
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER2 => 14

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER3
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER3 => 15

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER4
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER4 => 16

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER5
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER5 => 17

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER6
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER6 => 18

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER7
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER7 => 19

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER8
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER8 => 20

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER9
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER9 => 21

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER10
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER10 => 22

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER11
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER11 => 23

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER12
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER12 => 24

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER13
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER13 => 25

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER14
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER14 => 26

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_PARAMETER15
     * @type {Integer (Int32)}
     */
    static CORRUPTED_PARAMETER15 => 27

    /**
     * Native name: D3D10_MESSAGE_ID_CORRUPTED_MULTITHREADING
     * @type {Integer (Int32)}
     */
    static CORRUPTED_MULTITHREADING => 28

    /**
     * Native name: D3D10_MESSAGE_ID_MESSAGE_REPORTING_OUTOFMEMORY
     * @type {Integer (Int32)}
     */
    static MESSAGE_REPORTING_OUTOFMEMORY => 29

    /**
     * Native name: D3D10_MESSAGE_ID_IASETINPUTLAYOUT_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static IASETINPUTLAYOUT_UNBINDDELETINGOBJECT => 30

    /**
     * Native name: D3D10_MESSAGE_ID_IASETVERTEXBUFFERS_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static IASETVERTEXBUFFERS_UNBINDDELETINGOBJECT => 31

    /**
     * Native name: D3D10_MESSAGE_ID_IASETINDEXBUFFER_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static IASETINDEXBUFFER_UNBINDDELETINGOBJECT => 32

    /**
     * Native name: D3D10_MESSAGE_ID_VSSETSHADER_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static VSSETSHADER_UNBINDDELETINGOBJECT => 33

    /**
     * Native name: D3D10_MESSAGE_ID_VSSETSHADERRESOURCES_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static VSSETSHADERRESOURCES_UNBINDDELETINGOBJECT => 34

    /**
     * Native name: D3D10_MESSAGE_ID_VSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static VSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT => 35

    /**
     * Native name: D3D10_MESSAGE_ID_VSSETSAMPLERS_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static VSSETSAMPLERS_UNBINDDELETINGOBJECT => 36

    /**
     * Native name: D3D10_MESSAGE_ID_GSSETSHADER_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static GSSETSHADER_UNBINDDELETINGOBJECT => 37

    /**
     * Native name: D3D10_MESSAGE_ID_GSSETSHADERRESOURCES_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static GSSETSHADERRESOURCES_UNBINDDELETINGOBJECT => 38

    /**
     * Native name: D3D10_MESSAGE_ID_GSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static GSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT => 39

    /**
     * Native name: D3D10_MESSAGE_ID_GSSETSAMPLERS_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static GSSETSAMPLERS_UNBINDDELETINGOBJECT => 40

    /**
     * Native name: D3D10_MESSAGE_ID_SOSETTARGETS_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static SOSETTARGETS_UNBINDDELETINGOBJECT => 41

    /**
     * Native name: D3D10_MESSAGE_ID_PSSETSHADER_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static PSSETSHADER_UNBINDDELETINGOBJECT => 42

    /**
     * Native name: D3D10_MESSAGE_ID_PSSETSHADERRESOURCES_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static PSSETSHADERRESOURCES_UNBINDDELETINGOBJECT => 43

    /**
     * Native name: D3D10_MESSAGE_ID_PSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static PSSETCONSTANTBUFFERS_UNBINDDELETINGOBJECT => 44

    /**
     * Native name: D3D10_MESSAGE_ID_PSSETSAMPLERS_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static PSSETSAMPLERS_UNBINDDELETINGOBJECT => 45

    /**
     * Native name: D3D10_MESSAGE_ID_RSSETSTATE_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static RSSETSTATE_UNBINDDELETINGOBJECT => 46

    /**
     * Native name: D3D10_MESSAGE_ID_OMSETBLENDSTATE_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static OMSETBLENDSTATE_UNBINDDELETINGOBJECT => 47

    /**
     * Native name: D3D10_MESSAGE_ID_OMSETDEPTHSTENCILSTATE_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static OMSETDEPTHSTENCILSTATE_UNBINDDELETINGOBJECT => 48

    /**
     * Native name: D3D10_MESSAGE_ID_OMSETRENDERTARGETS_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static OMSETRENDERTARGETS_UNBINDDELETINGOBJECT => 49

    /**
     * Native name: D3D10_MESSAGE_ID_SETPREDICATION_UNBINDDELETINGOBJECT
     * @type {Integer (Int32)}
     */
    static SETPREDICATION_UNBINDDELETINGOBJECT => 50

    /**
     * Native name: D3D10_MESSAGE_ID_GETPRIVATEDATA_MOREDATA
     * @type {Integer (Int32)}
     */
    static GETPRIVATEDATA_MOREDATA => 51

    /**
     * Native name: D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDFREEDATA
     * @type {Integer (Int32)}
     */
    static SETPRIVATEDATA_INVALIDFREEDATA => 52

    /**
     * Native name: D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDIUNKNOWN
     * @type {Integer (Int32)}
     */
    static SETPRIVATEDATA_INVALIDIUNKNOWN => 53

    /**
     * Native name: D3D10_MESSAGE_ID_SETPRIVATEDATA_INVALIDFLAGS
     * @type {Integer (Int32)}
     */
    static SETPRIVATEDATA_INVALIDFLAGS => 54

    /**
     * Native name: D3D10_MESSAGE_ID_SETPRIVATEDATA_CHANGINGPARAMS
     * @type {Integer (Int32)}
     */
    static SETPRIVATEDATA_CHANGINGPARAMS => 55

    /**
     * Native name: D3D10_MESSAGE_ID_SETPRIVATEDATA_OUTOFMEMORY
     * @type {Integer (Int32)}
     */
    static SETPRIVATEDATA_OUTOFMEMORY => 56

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_UNRECOGNIZEDFORMAT => 57

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDSAMPLES
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_INVALIDSAMPLES => 58

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDUSAGE
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_UNRECOGNIZEDUSAGE => 59

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDBINDFLAGS
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_UNRECOGNIZEDBINDFLAGS => 60

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDCPUACCESSFLAGS
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_UNRECOGNIZEDCPUACCESSFLAGS => 61

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_UNRECOGNIZEDMISCFLAGS
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_UNRECOGNIZEDMISCFLAGS => 62

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDCPUACCESSFLAGS
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_INVALIDCPUACCESSFLAGS => 63

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDBINDFLAGS
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_INVALIDBINDFLAGS => 64

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDINITIALDATA
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_INVALIDINITIALDATA => 65

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDDIMENSIONS
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_INVALIDDIMENSIONS => 66

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDMIPLEVELS
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_INVALIDMIPLEVELS => 67

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDMISCFLAGS
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_INVALIDMISCFLAGS => 68

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDARG_RETURN
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_INVALIDARG_RETURN => 69

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_OUTOFMEMORY_RETURN
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_OUTOFMEMORY_RETURN => 70

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_NULLDESC
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_NULLDESC => 71

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_INVALIDCONSTANTBUFFERBINDINGS
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_INVALIDCONSTANTBUFFERBINDINGS => 72

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBUFFER_LARGEALLOCATION
     * @type {Integer (Int32)}
     */
    static CREATEBUFFER_LARGEALLOCATION => 73

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_UNRECOGNIZEDFORMAT => 74

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_UNSUPPORTEDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_UNSUPPORTEDFORMAT => 75

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDSAMPLES
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_INVALIDSAMPLES => 76

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDUSAGE
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_UNRECOGNIZEDUSAGE => 77

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDBINDFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_UNRECOGNIZEDBINDFLAGS => 78

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDCPUACCESSFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_UNRECOGNIZEDCPUACCESSFLAGS => 79

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_UNRECOGNIZEDMISCFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_UNRECOGNIZEDMISCFLAGS => 80

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDCPUACCESSFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_INVALIDCPUACCESSFLAGS => 81

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDBINDFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_INVALIDBINDFLAGS => 82

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDINITIALDATA
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_INVALIDINITIALDATA => 83

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDDIMENSIONS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_INVALIDDIMENSIONS => 84

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDMIPLEVELS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_INVALIDMIPLEVELS => 85

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDMISCFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_INVALIDMISCFLAGS => 86

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_INVALIDARG_RETURN
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_INVALIDARG_RETURN => 87

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_OUTOFMEMORY_RETURN
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_OUTOFMEMORY_RETURN => 88

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_NULLDESC
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_NULLDESC => 89

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE1D_LARGEALLOCATION
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE1D_LARGEALLOCATION => 90

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_UNRECOGNIZEDFORMAT => 91

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_UNSUPPORTEDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_UNSUPPORTEDFORMAT => 92

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDSAMPLES
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_INVALIDSAMPLES => 93

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDUSAGE
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_UNRECOGNIZEDUSAGE => 94

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDBINDFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_UNRECOGNIZEDBINDFLAGS => 95

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDCPUACCESSFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_UNRECOGNIZEDCPUACCESSFLAGS => 96

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_UNRECOGNIZEDMISCFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_UNRECOGNIZEDMISCFLAGS => 97

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDCPUACCESSFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_INVALIDCPUACCESSFLAGS => 98

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDBINDFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_INVALIDBINDFLAGS => 99

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDINITIALDATA
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_INVALIDINITIALDATA => 100

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDDIMENSIONS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_INVALIDDIMENSIONS => 101

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDMIPLEVELS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_INVALIDMIPLEVELS => 102

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDMISCFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_INVALIDMISCFLAGS => 103

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_INVALIDARG_RETURN
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_INVALIDARG_RETURN => 104

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_OUTOFMEMORY_RETURN
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_OUTOFMEMORY_RETURN => 105

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_NULLDESC
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_NULLDESC => 106

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE2D_LARGEALLOCATION
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE2D_LARGEALLOCATION => 107

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_UNRECOGNIZEDFORMAT => 108

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_UNSUPPORTEDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_UNSUPPORTEDFORMAT => 109

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDSAMPLES
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_INVALIDSAMPLES => 110

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDUSAGE
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_UNRECOGNIZEDUSAGE => 111

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDBINDFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_UNRECOGNIZEDBINDFLAGS => 112

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDCPUACCESSFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_UNRECOGNIZEDCPUACCESSFLAGS => 113

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_UNRECOGNIZEDMISCFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_UNRECOGNIZEDMISCFLAGS => 114

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDCPUACCESSFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_INVALIDCPUACCESSFLAGS => 115

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDBINDFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_INVALIDBINDFLAGS => 116

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDINITIALDATA
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_INVALIDINITIALDATA => 117

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDDIMENSIONS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_INVALIDDIMENSIONS => 118

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDMIPLEVELS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_INVALIDMIPLEVELS => 119

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDMISCFLAGS
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_INVALIDMISCFLAGS => 120

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_INVALIDARG_RETURN
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_INVALIDARG_RETURN => 121

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_OUTOFMEMORY_RETURN
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_OUTOFMEMORY_RETURN => 122

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_NULLDESC
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_NULLDESC => 123

    /**
     * Native name: D3D10_MESSAGE_ID_CREATETEXTURE3D_LARGEALLOCATION
     * @type {Integer (Int32)}
     */
    static CREATETEXTURE3D_LARGEALLOCATION => 124

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_UNRECOGNIZEDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATESHADERRESOURCEVIEW_UNRECOGNIZEDFORMAT => 125

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDDESC
     * @type {Integer (Int32)}
     */
    static CREATESHADERRESOURCEVIEW_INVALIDDESC => 126

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATESHADERRESOURCEVIEW_INVALIDFORMAT => 127

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDDIMENSIONS
     * @type {Integer (Int32)}
     */
    static CREATESHADERRESOURCEVIEW_INVALIDDIMENSIONS => 128

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDRESOURCE
     * @type {Integer (Int32)}
     */
    static CREATESHADERRESOURCEVIEW_INVALIDRESOURCE => 129

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_TOOMANYOBJECTS
     * @type {Integer (Int32)}
     */
    static CREATESHADERRESOURCEVIEW_TOOMANYOBJECTS => 130

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_INVALIDARG_RETURN
     * @type {Integer (Int32)}
     */
    static CREATESHADERRESOURCEVIEW_INVALIDARG_RETURN => 131

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_OUTOFMEMORY_RETURN
     * @type {Integer (Int32)}
     */
    static CREATESHADERRESOURCEVIEW_OUTOFMEMORY_RETURN => 132

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_UNRECOGNIZEDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATERENDERTARGETVIEW_UNRECOGNIZEDFORMAT => 133

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_UNSUPPORTEDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATERENDERTARGETVIEW_UNSUPPORTEDFORMAT => 134

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDDESC
     * @type {Integer (Int32)}
     */
    static CREATERENDERTARGETVIEW_INVALIDDESC => 135

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATERENDERTARGETVIEW_INVALIDFORMAT => 136

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDDIMENSIONS
     * @type {Integer (Int32)}
     */
    static CREATERENDERTARGETVIEW_INVALIDDIMENSIONS => 137

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDRESOURCE
     * @type {Integer (Int32)}
     */
    static CREATERENDERTARGETVIEW_INVALIDRESOURCE => 138

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_TOOMANYOBJECTS
     * @type {Integer (Int32)}
     */
    static CREATERENDERTARGETVIEW_TOOMANYOBJECTS => 139

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_INVALIDARG_RETURN
     * @type {Integer (Int32)}
     */
    static CREATERENDERTARGETVIEW_INVALIDARG_RETURN => 140

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERENDERTARGETVIEW_OUTOFMEMORY_RETURN
     * @type {Integer (Int32)}
     */
    static CREATERENDERTARGETVIEW_OUTOFMEMORY_RETURN => 141

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_UNRECOGNIZEDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILVIEW_UNRECOGNIZEDFORMAT => 142

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDDESC
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILVIEW_INVALIDDESC => 143

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILVIEW_INVALIDFORMAT => 144

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDDIMENSIONS
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILVIEW_INVALIDDIMENSIONS => 145

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDRESOURCE
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILVIEW_INVALIDRESOURCE => 146

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_TOOMANYOBJECTS
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILVIEW_TOOMANYOBJECTS => 147

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_INVALIDARG_RETURN
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILVIEW_INVALIDARG_RETURN => 148

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILVIEW_OUTOFMEMORY_RETURN
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILVIEW_OUTOFMEMORY_RETURN => 149

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_OUTOFMEMORY
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_OUTOFMEMORY => 150

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_TOOMANYELEMENTS
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_TOOMANYELEMENTS => 151

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDFORMAT
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_INVALIDFORMAT => 152

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INCOMPATIBLEFORMAT
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_INCOMPATIBLEFORMAT => 153

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSLOT
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_INVALIDSLOT => 154

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDINPUTSLOTCLASS
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_INVALIDINPUTSLOTCLASS => 155

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_STEPRATESLOTCLASSMISMATCH
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_STEPRATESLOTCLASSMISMATCH => 156

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSLOTCLASSCHANGE
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_INVALIDSLOTCLASSCHANGE => 157

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDSTEPRATECHANGE
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_INVALIDSTEPRATECHANGE => 158

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_INVALIDALIGNMENT
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_INVALIDALIGNMENT => 159

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_DUPLICATESEMANTIC
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_DUPLICATESEMANTIC => 160

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_UNPARSEABLEINPUTSIGNATURE => 161

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_NULLSEMANTIC
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_NULLSEMANTIC => 162

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_MISSINGELEMENT
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_MISSINGELEMENT => 163

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_NULLDESC
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_NULLDESC => 164

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEVERTEXSHADER_OUTOFMEMORY
     * @type {Integer (Int32)}
     */
    static CREATEVERTEXSHADER_OUTOFMEMORY => 165

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEVERTEXSHADER_INVALIDSHADERBYTECODE
     * @type {Integer (Int32)}
     */
    static CREATEVERTEXSHADER_INVALIDSHADERBYTECODE => 166

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEVERTEXSHADER_INVALIDSHADERTYPE
     * @type {Integer (Int32)}
     */
    static CREATEVERTEXSHADER_INVALIDSHADERTYPE => 167

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_OUTOFMEMORY
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADER_OUTOFMEMORY => 168

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_INVALIDSHADERBYTECODE
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADER_INVALIDSHADERBYTECODE => 169

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADER_INVALIDSHADERTYPE
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADER_INVALIDSHADERTYPE => 170

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTOFMEMORY
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTOFMEMORY => 171

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERBYTECODE
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERBYTECODE => 172

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERTYPE
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSHADERTYPE => 173

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMENTRIES
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDNUMENTRIES => 174

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSTREAMSTRIDEUNUSED
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSTREAMSTRIDEUNUSED => 175

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDDECL
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_UNEXPECTEDDECL => 176

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_EXPECTEDDECL
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_EXPECTEDDECL => 177

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSLOT0EXPECTED
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_OUTPUTSLOT0EXPECTED => 178

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSLOT
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSLOT => 179

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_ONLYONEELEMENTPERSLOT
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_ONLYONEELEMENTPERSLOT => 180

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDCOMPONENTCOUNT
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDCOMPONENTCOUNT => 181

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTARTCOMPONENTANDCOMPONENTCOUNT
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDSTARTCOMPONENTANDCOMPONENTCOUNT => 182

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDGAPDEFINITION
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDGAPDEFINITION => 183

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_REPEATEDOUTPUT
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_REPEATEDOUTPUT => 184

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSTREAMSTRIDE
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_INVALIDOUTPUTSTREAMSTRIDE => 185

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGSEMANTIC
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGSEMANTIC => 186

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MASKMISMATCH
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MASKMISMATCH => 187

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_CANTHAVEONLYGAPS
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_CANTHAVEONLYGAPS => 188

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DECLTOOCOMPLEX
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_DECLTOOCOMPLEX => 189

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGOUTPUTSIGNATURE
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_MISSINGOUTPUTSIGNATURE => 190

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEPIXELSHADER_OUTOFMEMORY
     * @type {Integer (Int32)}
     */
    static CREATEPIXELSHADER_OUTOFMEMORY => 191

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEPIXELSHADER_INVALIDSHADERBYTECODE
     * @type {Integer (Int32)}
     */
    static CREATEPIXELSHADER_INVALIDSHADERBYTECODE => 192

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEPIXELSHADER_INVALIDSHADERTYPE
     * @type {Integer (Int32)}
     */
    static CREATEPIXELSHADER_INVALIDSHADERTYPE => 193

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDFILLMODE
     * @type {Integer (Int32)}
     */
    static CREATERASTERIZERSTATE_INVALIDFILLMODE => 194

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDCULLMODE
     * @type {Integer (Int32)}
     */
    static CREATERASTERIZERSTATE_INVALIDCULLMODE => 195

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDDEPTHBIASCLAMP
     * @type {Integer (Int32)}
     */
    static CREATERASTERIZERSTATE_INVALIDDEPTHBIASCLAMP => 196

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_INVALIDSLOPESCALEDDEPTHBIAS
     * @type {Integer (Int32)}
     */
    static CREATERASTERIZERSTATE_INVALIDSLOPESCALEDDEPTHBIAS => 197

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_TOOMANYOBJECTS
     * @type {Integer (Int32)}
     */
    static CREATERASTERIZERSTATE_TOOMANYOBJECTS => 198

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_NULLDESC
     * @type {Integer (Int32)}
     */
    static CREATERASTERIZERSTATE_NULLDESC => 199

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDDEPTHWRITEMASK
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_INVALIDDEPTHWRITEMASK => 200

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDDEPTHFUNC
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_INVALIDDEPTHFUNC => 201

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFAILOP
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFAILOP => 202

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILZFAILOP
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILZFAILOP => 203

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILPASSOP
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILPASSOP => 204

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFUNC
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_INVALIDFRONTFACESTENCILFUNC => 205

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFAILOP
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFAILOP => 206

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILZFAILOP
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILZFAILOP => 207

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILPASSOP
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILPASSOP => 208

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFUNC
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_INVALIDBACKFACESTENCILFUNC => 209

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_TOOMANYOBJECTS
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_TOOMANYOBJECTS => 210

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_NULLDESC
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_NULLDESC => 211

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDSRCBLEND
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_INVALIDSRCBLEND => 212

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDDESTBLEND
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_INVALIDDESTBLEND => 213

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDBLENDOP
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_INVALIDBLENDOP => 214

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDSRCBLENDALPHA
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_INVALIDSRCBLENDALPHA => 215

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDDESTBLENDALPHA
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_INVALIDDESTBLENDALPHA => 216

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDBLENDOPALPHA
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_INVALIDBLENDOPALPHA => 217

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_INVALIDRENDERTARGETWRITEMASK
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_INVALIDRENDERTARGETWRITEMASK => 218

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_TOOMANYOBJECTS
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_TOOMANYOBJECTS => 219

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_NULLDESC
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_NULLDESC => 220

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDFILTER
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_INVALIDFILTER => 221

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSU
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_INVALIDADDRESSU => 222

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSV
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_INVALIDADDRESSV => 223

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDADDRESSW
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_INVALIDADDRESSW => 224

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMIPLODBIAS
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_INVALIDMIPLODBIAS => 225

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMAXANISOTROPY
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_INVALIDMAXANISOTROPY => 226

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDCOMPARISONFUNC
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_INVALIDCOMPARISONFUNC => 227

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMINLOD
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_INVALIDMINLOD => 228

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_INVALIDMAXLOD
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_INVALIDMAXLOD => 229

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_TOOMANYOBJECTS
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_TOOMANYOBJECTS => 230

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_NULLDESC
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_NULLDESC => 231

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_INVALIDQUERY
     * @type {Integer (Int32)}
     */
    static CREATEQUERYORPREDICATE_INVALIDQUERY => 232

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_INVALIDMISCFLAGS
     * @type {Integer (Int32)}
     */
    static CREATEQUERYORPREDICATE_INVALIDMISCFLAGS => 233

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_UNEXPECTEDMISCFLAG
     * @type {Integer (Int32)}
     */
    static CREATEQUERYORPREDICATE_UNEXPECTEDMISCFLAG => 234

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEQUERYORPREDICATE_NULLDESC
     * @type {Integer (Int32)}
     */
    static CREATEQUERYORPREDICATE_NULLDESC => 235

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNRECOGNIZED
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNRECOGNIZED => 236

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNDEFINED
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETPRIMITIVETOPOLOGY_TOPOLOGY_UNDEFINED => 237

    /**
     * Native name: D3D10_MESSAGE_ID_IASETVERTEXBUFFERS_INVALIDBUFFER
     * @type {Integer (Int32)}
     */
    static IASETVERTEXBUFFERS_INVALIDBUFFER => 238

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_OFFSET_TOO_LARGE
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETVERTEXBUFFERS_OFFSET_TOO_LARGE => 239

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_BUFFERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETVERTEXBUFFERS_BUFFERS_EMPTY => 240

    /**
     * Native name: D3D10_MESSAGE_ID_IASETINDEXBUFFER_INVALIDBUFFER
     * @type {Integer (Int32)}
     */
    static IASETINDEXBUFFER_INVALIDBUFFER => 241

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_FORMAT_INVALID
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETINDEXBUFFER_FORMAT_INVALID => 242

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_OFFSET_TOO_LARGE
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETINDEXBUFFER_OFFSET_TOO_LARGE => 243

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETINDEXBUFFER_OFFSET_UNALIGNED
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETINDEXBUFFER_OFFSET_UNALIGNED => 244

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_VSSETSHADERRESOURCES_VIEWS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_VSSETSHADERRESOURCES_VIEWS_EMPTY => 245

    /**
     * Native name: D3D10_MESSAGE_ID_VSSETCONSTANTBUFFERS_INVALIDBUFFER
     * @type {Integer (Int32)}
     */
    static VSSETCONSTANTBUFFERS_INVALIDBUFFER => 246

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_VSSETCONSTANTBUFFERS_BUFFERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_VSSETCONSTANTBUFFERS_BUFFERS_EMPTY => 247

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_VSSETSAMPLERS_SAMPLERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_VSSETSAMPLERS_SAMPLERS_EMPTY => 248

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_GSSETSHADERRESOURCES_VIEWS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_GSSETSHADERRESOURCES_VIEWS_EMPTY => 249

    /**
     * Native name: D3D10_MESSAGE_ID_GSSETCONSTANTBUFFERS_INVALIDBUFFER
     * @type {Integer (Int32)}
     */
    static GSSETCONSTANTBUFFERS_INVALIDBUFFER => 250

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_GSSETCONSTANTBUFFERS_BUFFERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_GSSETCONSTANTBUFFERS_BUFFERS_EMPTY => 251

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_GSSETSAMPLERS_SAMPLERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_GSSETSAMPLERS_SAMPLERS_EMPTY => 252

    /**
     * Native name: D3D10_MESSAGE_ID_SOSETTARGETS_INVALIDBUFFER
     * @type {Integer (Int32)}
     */
    static SOSETTARGETS_INVALIDBUFFER => 253

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_SOSETTARGETS_OFFSET_UNALIGNED
     * @type {Integer (Int32)}
     */
    static DEVICE_SOSETTARGETS_OFFSET_UNALIGNED => 254

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_PSSETSHADERRESOURCES_VIEWS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_PSSETSHADERRESOURCES_VIEWS_EMPTY => 255

    /**
     * Native name: D3D10_MESSAGE_ID_PSSETCONSTANTBUFFERS_INVALIDBUFFER
     * @type {Integer (Int32)}
     */
    static PSSETCONSTANTBUFFERS_INVALIDBUFFER => 256

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_PSSETCONSTANTBUFFERS_BUFFERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_PSSETCONSTANTBUFFERS_BUFFERS_EMPTY => 257

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_PSSETSAMPLERS_SAMPLERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_PSSETSAMPLERS_SAMPLERS_EMPTY => 258

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_INVALIDVIEWPORT
     * @type {Integer (Int32)}
     */
    static DEVICE_RSSETVIEWPORTS_INVALIDVIEWPORT => 259

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_INVALIDSCISSOR
     * @type {Integer (Int32)}
     */
    static DEVICE_RSSETSCISSORRECTS_INVALIDSCISSOR => 260

    /**
     * Native name: D3D10_MESSAGE_ID_CLEARRENDERTARGETVIEW_DENORMFLUSH
     * @type {Integer (Int32)}
     */
    static CLEARRENDERTARGETVIEW_DENORMFLUSH => 261

    /**
     * Native name: D3D10_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_DENORMFLUSH
     * @type {Integer (Int32)}
     */
    static CLEARDEPTHSTENCILVIEW_DENORMFLUSH => 262

    /**
     * Native name: D3D10_MESSAGE_ID_CLEARDEPTHSTENCILVIEW_INVALID
     * @type {Integer (Int32)}
     */
    static CLEARDEPTHSTENCILVIEW_INVALID => 263

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IAGETVERTEXBUFFERS_BUFFERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_IAGETVERTEXBUFFERS_BUFFERS_EMPTY => 264

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_VSGETSHADERRESOURCES_VIEWS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_VSGETSHADERRESOURCES_VIEWS_EMPTY => 265

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_VSGETCONSTANTBUFFERS_BUFFERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_VSGETCONSTANTBUFFERS_BUFFERS_EMPTY => 266

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_VSGETSAMPLERS_SAMPLERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_VSGETSAMPLERS_SAMPLERS_EMPTY => 267

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_GSGETSHADERRESOURCES_VIEWS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_GSGETSHADERRESOURCES_VIEWS_EMPTY => 268

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_GSGETCONSTANTBUFFERS_BUFFERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_GSGETCONSTANTBUFFERS_BUFFERS_EMPTY => 269

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_GSGETSAMPLERS_SAMPLERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_GSGETSAMPLERS_SAMPLERS_EMPTY => 270

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_SOGETTARGETS_BUFFERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_SOGETTARGETS_BUFFERS_EMPTY => 271

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_PSGETSHADERRESOURCES_VIEWS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_PSGETSHADERRESOURCES_VIEWS_EMPTY => 272

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_PSGETCONSTANTBUFFERS_BUFFERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_PSGETCONSTANTBUFFERS_BUFFERS_EMPTY => 273

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_PSGETSAMPLERS_SAMPLERS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_PSGETSAMPLERS_SAMPLERS_EMPTY => 274

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RSGETVIEWPORTS_VIEWPORTS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_RSGETVIEWPORTS_VIEWPORTS_EMPTY => 275

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RSGETSCISSORRECTS_RECTS_EMPTY
     * @type {Integer (Int32)}
     */
    static DEVICE_RSGETSCISSORRECTS_RECTS_EMPTY => 276

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_GENERATEMIPS_RESOURCE_INVALID
     * @type {Integer (Int32)}
     */
    static DEVICE_GENERATEMIPS_RESOURCE_INVALID => 277

    /**
     * Native name: D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDDESTINATIONSUBRESOURCE
     * @type {Integer (Int32)}
     */
    static COPYSUBRESOURCEREGION_INVALIDDESTINATIONSUBRESOURCE => 278

    /**
     * Native name: D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCESUBRESOURCE
     * @type {Integer (Int32)}
     */
    static COPYSUBRESOURCEREGION_INVALIDSOURCESUBRESOURCE => 279

    /**
     * Native name: D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCEBOX
     * @type {Integer (Int32)}
     */
    static COPYSUBRESOURCEREGION_INVALIDSOURCEBOX => 280

    /**
     * Native name: D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCE
     * @type {Integer (Int32)}
     */
    static COPYSUBRESOURCEREGION_INVALIDSOURCE => 281

    /**
     * Native name: D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDDESTINATIONSTATE
     * @type {Integer (Int32)}
     */
    static COPYSUBRESOURCEREGION_INVALIDDESTINATIONSTATE => 282

    /**
     * Native name: D3D10_MESSAGE_ID_COPYSUBRESOURCEREGION_INVALIDSOURCESTATE
     * @type {Integer (Int32)}
     */
    static COPYSUBRESOURCEREGION_INVALIDSOURCESTATE => 283

    /**
     * Native name: D3D10_MESSAGE_ID_COPYRESOURCE_INVALIDSOURCE
     * @type {Integer (Int32)}
     */
    static COPYRESOURCE_INVALIDSOURCE => 284

    /**
     * Native name: D3D10_MESSAGE_ID_COPYRESOURCE_INVALIDDESTINATIONSTATE
     * @type {Integer (Int32)}
     */
    static COPYRESOURCE_INVALIDDESTINATIONSTATE => 285

    /**
     * Native name: D3D10_MESSAGE_ID_COPYRESOURCE_INVALIDSOURCESTATE
     * @type {Integer (Int32)}
     */
    static COPYRESOURCE_INVALIDSOURCESTATE => 286

    /**
     * Native name: D3D10_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONSUBRESOURCE
     * @type {Integer (Int32)}
     */
    static UPDATESUBRESOURCE_INVALIDDESTINATIONSUBRESOURCE => 287

    /**
     * Native name: D3D10_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONBOX
     * @type {Integer (Int32)}
     */
    static UPDATESUBRESOURCE_INVALIDDESTINATIONBOX => 288

    /**
     * Native name: D3D10_MESSAGE_ID_UPDATESUBRESOURCE_INVALIDDESTINATIONSTATE
     * @type {Integer (Int32)}
     */
    static UPDATESUBRESOURCE_INVALIDDESTINATIONSTATE => 289

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_DESTINATION_INVALID
     * @type {Integer (Int32)}
     */
    static DEVICE_RESOLVESUBRESOURCE_DESTINATION_INVALID => 290

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_DESTINATION_SUBRESOURCE_INVALID
     * @type {Integer (Int32)}
     */
    static DEVICE_RESOLVESUBRESOURCE_DESTINATION_SUBRESOURCE_INVALID => 291

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_SOURCE_INVALID
     * @type {Integer (Int32)}
     */
    static DEVICE_RESOLVESUBRESOURCE_SOURCE_INVALID => 292

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_SOURCE_SUBRESOURCE_INVALID
     * @type {Integer (Int32)}
     */
    static DEVICE_RESOLVESUBRESOURCE_SOURCE_SUBRESOURCE_INVALID => 293

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RESOLVESUBRESOURCE_FORMAT_INVALID
     * @type {Integer (Int32)}
     */
    static DEVICE_RESOLVESUBRESOURCE_FORMAT_INVALID => 294

    /**
     * Native name: D3D10_MESSAGE_ID_BUFFER_MAP_INVALIDMAPTYPE
     * @type {Integer (Int32)}
     */
    static BUFFER_MAP_INVALIDMAPTYPE => 295

    /**
     * Native name: D3D10_MESSAGE_ID_BUFFER_MAP_INVALIDFLAGS
     * @type {Integer (Int32)}
     */
    static BUFFER_MAP_INVALIDFLAGS => 296

    /**
     * Native name: D3D10_MESSAGE_ID_BUFFER_MAP_ALREADYMAPPED
     * @type {Integer (Int32)}
     */
    static BUFFER_MAP_ALREADYMAPPED => 297

    /**
     * Native name: D3D10_MESSAGE_ID_BUFFER_MAP_DEVICEREMOVED_RETURN
     * @type {Integer (Int32)}
     */
    static BUFFER_MAP_DEVICEREMOVED_RETURN => 298

    /**
     * Native name: D3D10_MESSAGE_ID_BUFFER_UNMAP_NOTMAPPED
     * @type {Integer (Int32)}
     */
    static BUFFER_UNMAP_NOTMAPPED => 299

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE1D_MAP_INVALIDMAPTYPE
     * @type {Integer (Int32)}
     */
    static TEXTURE1D_MAP_INVALIDMAPTYPE => 300

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE1D_MAP_INVALIDSUBRESOURCE
     * @type {Integer (Int32)}
     */
    static TEXTURE1D_MAP_INVALIDSUBRESOURCE => 301

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE1D_MAP_INVALIDFLAGS
     * @type {Integer (Int32)}
     */
    static TEXTURE1D_MAP_INVALIDFLAGS => 302

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE1D_MAP_ALREADYMAPPED
     * @type {Integer (Int32)}
     */
    static TEXTURE1D_MAP_ALREADYMAPPED => 303

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE1D_MAP_DEVICEREMOVED_RETURN
     * @type {Integer (Int32)}
     */
    static TEXTURE1D_MAP_DEVICEREMOVED_RETURN => 304

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE1D_UNMAP_INVALIDSUBRESOURCE
     * @type {Integer (Int32)}
     */
    static TEXTURE1D_UNMAP_INVALIDSUBRESOURCE => 305

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE1D_UNMAP_NOTMAPPED
     * @type {Integer (Int32)}
     */
    static TEXTURE1D_UNMAP_NOTMAPPED => 306

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE2D_MAP_INVALIDMAPTYPE
     * @type {Integer (Int32)}
     */
    static TEXTURE2D_MAP_INVALIDMAPTYPE => 307

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE2D_MAP_INVALIDSUBRESOURCE
     * @type {Integer (Int32)}
     */
    static TEXTURE2D_MAP_INVALIDSUBRESOURCE => 308

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE2D_MAP_INVALIDFLAGS
     * @type {Integer (Int32)}
     */
    static TEXTURE2D_MAP_INVALIDFLAGS => 309

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE2D_MAP_ALREADYMAPPED
     * @type {Integer (Int32)}
     */
    static TEXTURE2D_MAP_ALREADYMAPPED => 310

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE2D_MAP_DEVICEREMOVED_RETURN
     * @type {Integer (Int32)}
     */
    static TEXTURE2D_MAP_DEVICEREMOVED_RETURN => 311

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE2D_UNMAP_INVALIDSUBRESOURCE
     * @type {Integer (Int32)}
     */
    static TEXTURE2D_UNMAP_INVALIDSUBRESOURCE => 312

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE2D_UNMAP_NOTMAPPED
     * @type {Integer (Int32)}
     */
    static TEXTURE2D_UNMAP_NOTMAPPED => 313

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE3D_MAP_INVALIDMAPTYPE
     * @type {Integer (Int32)}
     */
    static TEXTURE3D_MAP_INVALIDMAPTYPE => 314

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE3D_MAP_INVALIDSUBRESOURCE
     * @type {Integer (Int32)}
     */
    static TEXTURE3D_MAP_INVALIDSUBRESOURCE => 315

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE3D_MAP_INVALIDFLAGS
     * @type {Integer (Int32)}
     */
    static TEXTURE3D_MAP_INVALIDFLAGS => 316

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE3D_MAP_ALREADYMAPPED
     * @type {Integer (Int32)}
     */
    static TEXTURE3D_MAP_ALREADYMAPPED => 317

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE3D_MAP_DEVICEREMOVED_RETURN
     * @type {Integer (Int32)}
     */
    static TEXTURE3D_MAP_DEVICEREMOVED_RETURN => 318

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE3D_UNMAP_INVALIDSUBRESOURCE
     * @type {Integer (Int32)}
     */
    static TEXTURE3D_UNMAP_INVALIDSUBRESOURCE => 319

    /**
     * Native name: D3D10_MESSAGE_ID_TEXTURE3D_UNMAP_NOTMAPPED
     * @type {Integer (Int32)}
     */
    static TEXTURE3D_UNMAP_NOTMAPPED => 320

    /**
     * Native name: D3D10_MESSAGE_ID_CHECKFORMATSUPPORT_FORMAT_DEPRECATED
     * @type {Integer (Int32)}
     */
    static CHECKFORMATSUPPORT_FORMAT_DEPRECATED => 321

    /**
     * Native name: D3D10_MESSAGE_ID_CHECKMULTISAMPLEQUALITYLEVELS_FORMAT_DEPRECATED
     * @type {Integer (Int32)}
     */
    static CHECKMULTISAMPLEQUALITYLEVELS_FORMAT_DEPRECATED => 322

    /**
     * Native name: D3D10_MESSAGE_ID_SETEXCEPTIONMODE_UNRECOGNIZEDFLAGS
     * @type {Integer (Int32)}
     */
    static SETEXCEPTIONMODE_UNRECOGNIZEDFLAGS => 323

    /**
     * Native name: D3D10_MESSAGE_ID_SETEXCEPTIONMODE_INVALIDARG_RETURN
     * @type {Integer (Int32)}
     */
    static SETEXCEPTIONMODE_INVALIDARG_RETURN => 324

    /**
     * Native name: D3D10_MESSAGE_ID_SETEXCEPTIONMODE_DEVICEREMOVED_RETURN
     * @type {Integer (Int32)}
     */
    static SETEXCEPTIONMODE_DEVICEREMOVED_RETURN => 325

    /**
     * Native name: D3D10_MESSAGE_ID_REF_SIMULATING_INFINITELY_FAST_HARDWARE
     * @type {Integer (Int32)}
     */
    static REF_SIMULATING_INFINITELY_FAST_HARDWARE => 326

    /**
     * Native name: D3D10_MESSAGE_ID_REF_THREADING_MODE
     * @type {Integer (Int32)}
     */
    static REF_THREADING_MODE => 327

    /**
     * Native name: D3D10_MESSAGE_ID_REF_UMDRIVER_EXCEPTION
     * @type {Integer (Int32)}
     */
    static REF_UMDRIVER_EXCEPTION => 328

    /**
     * Native name: D3D10_MESSAGE_ID_REF_KMDRIVER_EXCEPTION
     * @type {Integer (Int32)}
     */
    static REF_KMDRIVER_EXCEPTION => 329

    /**
     * Native name: D3D10_MESSAGE_ID_REF_HARDWARE_EXCEPTION
     * @type {Integer (Int32)}
     */
    static REF_HARDWARE_EXCEPTION => 330

    /**
     * Native name: D3D10_MESSAGE_ID_REF_ACCESSING_INDEXABLE_TEMP_OUT_OF_RANGE
     * @type {Integer (Int32)}
     */
    static REF_ACCESSING_INDEXABLE_TEMP_OUT_OF_RANGE => 331

    /**
     * Native name: D3D10_MESSAGE_ID_REF_PROBLEM_PARSING_SHADER
     * @type {Integer (Int32)}
     */
    static REF_PROBLEM_PARSING_SHADER => 332

    /**
     * Native name: D3D10_MESSAGE_ID_REF_OUT_OF_MEMORY
     * @type {Integer (Int32)}
     */
    static REF_OUT_OF_MEMORY => 333

    /**
     * Native name: D3D10_MESSAGE_ID_REF_INFO
     * @type {Integer (Int32)}
     */
    static REF_INFO => 334

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEXPOS_OVERFLOW
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_VERTEXPOS_OVERFLOW => 335

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAWINDEXED_INDEXPOS_OVERFLOW
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAWINDEXED_INDEXPOS_OVERFLOW => 336

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAWINSTANCED_VERTEXPOS_OVERFLOW
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAWINSTANCED_VERTEXPOS_OVERFLOW => 337

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAWINSTANCED_INSTANCEPOS_OVERFLOW
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAWINSTANCED_INSTANCEPOS_OVERFLOW => 338

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAWINDEXEDINSTANCED_INSTANCEPOS_OVERFLOW
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAWINDEXEDINSTANCED_INSTANCEPOS_OVERFLOW => 339

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAWINDEXEDINSTANCED_INDEXPOS_OVERFLOW
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAWINDEXEDINSTANCED_INDEXPOS_OVERFLOW => 340

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_SHADER_NOT_SET
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_VERTEX_SHADER_NOT_SET => 341

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND
     * @type {Integer (Int32)}
     */
    static DEVICE_SHADER_LINKAGE_SEMANTICNAME_NOT_FOUND => 342

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_REGISTERINDEX
     * @type {Integer (Int32)}
     */
    static DEVICE_SHADER_LINKAGE_REGISTERINDEX => 343

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_COMPONENTTYPE
     * @type {Integer (Int32)}
     */
    static DEVICE_SHADER_LINKAGE_COMPONENTTYPE => 344

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_REGISTERMASK
     * @type {Integer (Int32)}
     */
    static DEVICE_SHADER_LINKAGE_REGISTERMASK => 345

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_SYSTEMVALUE
     * @type {Integer (Int32)}
     */
    static DEVICE_SHADER_LINKAGE_SYSTEMVALUE => 346

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_SHADER_LINKAGE_NEVERWRITTEN_ALWAYSREADS
     * @type {Integer (Int32)}
     */
    static DEVICE_SHADER_LINKAGE_NEVERWRITTEN_ALWAYSREADS => 347

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_NOT_SET
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_VERTEX_BUFFER_NOT_SET => 348

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_INPUTLAYOUT_NOT_SET
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_INPUTLAYOUT_NOT_SET => 349

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_CONSTANT_BUFFER_NOT_SET
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_CONSTANT_BUFFER_NOT_SET => 350

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_CONSTANT_BUFFER_TOO_SMALL
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_CONSTANT_BUFFER_TOO_SMALL => 351

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_SAMPLER_NOT_SET
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_SAMPLER_NOT_SET => 352

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_SHADERRESOURCEVIEW_NOT_SET
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_SHADERRESOURCEVIEW_NOT_SET => 353

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_VIEW_DIMENSION_MISMATCH
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_VIEW_DIMENSION_MISMATCH => 354

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_STRIDE_TOO_SMALL
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_VERTEX_BUFFER_STRIDE_TOO_SMALL => 355

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_BUFFER_TOO_SMALL
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_VERTEX_BUFFER_TOO_SMALL => 356

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_NOT_SET
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_INDEX_BUFFER_NOT_SET => 357

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_FORMAT_INVALID
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_INDEX_BUFFER_FORMAT_INVALID => 358

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_BUFFER_TOO_SMALL
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_INDEX_BUFFER_TOO_SMALL => 359

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_GS_INPUT_PRIMITIVE_MISMATCH
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_GS_INPUT_PRIMITIVE_MISMATCH => 360

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_RETURN_TYPE_MISMATCH
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_RESOURCE_RETURN_TYPE_MISMATCH => 361

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_POSITION_NOT_PRESENT
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_POSITION_NOT_PRESENT => 362

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_OUTPUT_STREAM_NOT_SET
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_OUTPUT_STREAM_NOT_SET => 363

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_BOUND_RESOURCE_MAPPED
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_BOUND_RESOURCE_MAPPED => 364

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_INVALID_PRIMITIVETOPOLOGY
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_INVALID_PRIMITIVETOPOLOGY => 365

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_OFFSET_UNALIGNED
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_VERTEX_OFFSET_UNALIGNED => 366

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_VERTEX_STRIDE_UNALIGNED
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_VERTEX_STRIDE_UNALIGNED => 367

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_INDEX_OFFSET_UNALIGNED
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_INDEX_OFFSET_UNALIGNED => 368

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_OUTPUT_STREAM_OFFSET_UNALIGNED
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_OUTPUT_STREAM_OFFSET_UNALIGNED => 369

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_LD_UNSUPPORTED
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_RESOURCE_FORMAT_LD_UNSUPPORTED => 370

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_SAMPLE_UNSUPPORTED
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_RESOURCE_FORMAT_SAMPLE_UNSUPPORTED => 371

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_SAMPLE_C_UNSUPPORTED
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_RESOURCE_FORMAT_SAMPLE_C_UNSUPPORTED => 372

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_MULTISAMPLE_UNSUPPORTED
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_RESOURCE_MULTISAMPLE_UNSUPPORTED => 373

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_SO_TARGETS_BOUND_WITHOUT_SOURCE
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_SO_TARGETS_BOUND_WITHOUT_SOURCE => 374

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_SO_STRIDE_LARGER_THAN_BUFFER
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_SO_STRIDE_LARGER_THAN_BUFFER => 375

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_OM_RENDER_TARGET_DOES_NOT_SUPPORT_BLENDING
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_OM_RENDER_TARGET_DOES_NOT_SUPPORT_BLENDING => 376

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_OM_DUAL_SOURCE_BLENDING_CAN_ONLY_HAVE_RENDER_TARGET_0
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_OM_DUAL_SOURCE_BLENDING_CAN_ONLY_HAVE_RENDER_TARGET_0 => 377

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_AT_FAULT
     * @type {Integer (Int32)}
     */
    static DEVICE_REMOVAL_PROCESS_AT_FAULT => 378

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_POSSIBLY_AT_FAULT
     * @type {Integer (Int32)}
     */
    static DEVICE_REMOVAL_PROCESS_POSSIBLY_AT_FAULT => 379

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_REMOVAL_PROCESS_NOT_AT_FAULT
     * @type {Integer (Int32)}
     */
    static DEVICE_REMOVAL_PROCESS_NOT_AT_FAULT => 380

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_INVALIDARG_RETURN
     * @type {Integer (Int32)}
     */
    static DEVICE_OPEN_SHARED_RESOURCE_INVALIDARG_RETURN => 381

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_OUTOFMEMORY_RETURN
     * @type {Integer (Int32)}
     */
    static DEVICE_OPEN_SHARED_RESOURCE_OUTOFMEMORY_RETURN => 382

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_OPEN_SHARED_RESOURCE_BADINTERFACE_RETURN
     * @type {Integer (Int32)}
     */
    static DEVICE_OPEN_SHARED_RESOURCE_BADINTERFACE_RETURN => 383

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_VIEWPORT_NOT_SET
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_VIEWPORT_NOT_SET => 384

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_TRAILING_DIGIT_IN_SEMANTIC
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_TRAILING_DIGIT_IN_SEMANTIC => 385

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_TRAILING_DIGIT_IN_SEMANTIC
     * @type {Integer (Int32)}
     */
    static CREATEGEOMETRYSHADERWITHSTREAMOUTPUT_TRAILING_DIGIT_IN_SEMANTIC => 386

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_DENORMFLUSH
     * @type {Integer (Int32)}
     */
    static DEVICE_RSSETVIEWPORTS_DENORMFLUSH => 387

    /**
     * Native name: D3D10_MESSAGE_ID_OMSETRENDERTARGETS_INVALIDVIEW
     * @type {Integer (Int32)}
     */
    static OMSETRENDERTARGETS_INVALIDVIEW => 388

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_SETTEXTFILTERSIZE_INVALIDDIMENSIONS
     * @type {Integer (Int32)}
     */
    static DEVICE_SETTEXTFILTERSIZE_INVALIDDIMENSIONS => 389

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_SAMPLER_MISMATCH
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_SAMPLER_MISMATCH => 390

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_TYPE_MISMATCH
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_TYPE_MISMATCH => 391

    /**
     * Native name: D3D10_MESSAGE_ID_BLENDSTATE_GETDESC_LEGACY
     * @type {Integer (Int32)}
     */
    static BLENDSTATE_GETDESC_LEGACY => 392

    /**
     * Native name: D3D10_MESSAGE_ID_SHADERRESOURCEVIEW_GETDESC_LEGACY
     * @type {Integer (Int32)}
     */
    static SHADERRESOURCEVIEW_GETDESC_LEGACY => 393

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEQUERY_OUTOFMEMORY_RETURN
     * @type {Integer (Int32)}
     */
    static CREATEQUERY_OUTOFMEMORY_RETURN => 394

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEPREDICATE_OUTOFMEMORY_RETURN
     * @type {Integer (Int32)}
     */
    static CREATEPREDICATE_OUTOFMEMORY_RETURN => 395

    /**
     * Native name: D3D10_MESSAGE_ID_CREATECOUNTER_OUTOFRANGE_COUNTER
     * @type {Integer (Int32)}
     */
    static CREATECOUNTER_OUTOFRANGE_COUNTER => 396

    /**
     * Native name: D3D10_MESSAGE_ID_CREATECOUNTER_SIMULTANEOUS_ACTIVE_COUNTERS_EXHAUSTED
     * @type {Integer (Int32)}
     */
    static CREATECOUNTER_SIMULTANEOUS_ACTIVE_COUNTERS_EXHAUSTED => 397

    /**
     * Native name: D3D10_MESSAGE_ID_CREATECOUNTER_UNSUPPORTED_WELLKNOWN_COUNTER
     * @type {Integer (Int32)}
     */
    static CREATECOUNTER_UNSUPPORTED_WELLKNOWN_COUNTER => 398

    /**
     * Native name: D3D10_MESSAGE_ID_CREATECOUNTER_OUTOFMEMORY_RETURN
     * @type {Integer (Int32)}
     */
    static CREATECOUNTER_OUTOFMEMORY_RETURN => 399

    /**
     * Native name: D3D10_MESSAGE_ID_CREATECOUNTER_NONEXCLUSIVE_RETURN
     * @type {Integer (Int32)}
     */
    static CREATECOUNTER_NONEXCLUSIVE_RETURN => 400

    /**
     * Native name: D3D10_MESSAGE_ID_CREATECOUNTER_NULLDESC
     * @type {Integer (Int32)}
     */
    static CREATECOUNTER_NULLDESC => 401

    /**
     * Native name: D3D10_MESSAGE_ID_CHECKCOUNTER_OUTOFRANGE_COUNTER
     * @type {Integer (Int32)}
     */
    static CHECKCOUNTER_OUTOFRANGE_COUNTER => 402

    /**
     * Native name: D3D10_MESSAGE_ID_CHECKCOUNTER_UNSUPPORTED_WELLKNOWN_COUNTER
     * @type {Integer (Int32)}
     */
    static CHECKCOUNTER_UNSUPPORTED_WELLKNOWN_COUNTER => 403

    /**
     * Native name: D3D10_MESSAGE_ID_SETPREDICATION_INVALID_PREDICATE_STATE
     * @type {Integer (Int32)}
     */
    static SETPREDICATION_INVALID_PREDICATE_STATE => 404

    /**
     * Native name: D3D10_MESSAGE_ID_QUERY_BEGIN_UNSUPPORTED
     * @type {Integer (Int32)}
     */
    static QUERY_BEGIN_UNSUPPORTED => 405

    /**
     * Native name: D3D10_MESSAGE_ID_PREDICATE_BEGIN_DURING_PREDICATION
     * @type {Integer (Int32)}
     */
    static PREDICATE_BEGIN_DURING_PREDICATION => 406

    /**
     * Native name: D3D10_MESSAGE_ID_QUERY_BEGIN_DUPLICATE
     * @type {Integer (Int32)}
     */
    static QUERY_BEGIN_DUPLICATE => 407

    /**
     * Native name: D3D10_MESSAGE_ID_QUERY_BEGIN_ABANDONING_PREVIOUS_RESULTS
     * @type {Integer (Int32)}
     */
    static QUERY_BEGIN_ABANDONING_PREVIOUS_RESULTS => 408

    /**
     * Native name: D3D10_MESSAGE_ID_PREDICATE_END_DURING_PREDICATION
     * @type {Integer (Int32)}
     */
    static PREDICATE_END_DURING_PREDICATION => 409

    /**
     * Native name: D3D10_MESSAGE_ID_QUERY_END_ABANDONING_PREVIOUS_RESULTS
     * @type {Integer (Int32)}
     */
    static QUERY_END_ABANDONING_PREVIOUS_RESULTS => 410

    /**
     * Native name: D3D10_MESSAGE_ID_QUERY_END_WITHOUT_BEGIN
     * @type {Integer (Int32)}
     */
    static QUERY_END_WITHOUT_BEGIN => 411

    /**
     * Native name: D3D10_MESSAGE_ID_QUERY_GETDATA_INVALID_DATASIZE
     * @type {Integer (Int32)}
     */
    static QUERY_GETDATA_INVALID_DATASIZE => 412

    /**
     * Native name: D3D10_MESSAGE_ID_QUERY_GETDATA_INVALID_FLAGS
     * @type {Integer (Int32)}
     */
    static QUERY_GETDATA_INVALID_FLAGS => 413

    /**
     * Native name: D3D10_MESSAGE_ID_QUERY_GETDATA_INVALID_CALL
     * @type {Integer (Int32)}
     */
    static QUERY_GETDATA_INVALID_CALL => 414

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_PS_OUTPUT_TYPE_MISMATCH
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_PS_OUTPUT_TYPE_MISMATCH => 415

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_FORMAT_GATHER_UNSUPPORTED
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_RESOURCE_FORMAT_GATHER_UNSUPPORTED => 416

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_INVALID_USE_OF_CENTER_MULTISAMPLE_PATTERN
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_INVALID_USE_OF_CENTER_MULTISAMPLE_PATTERN => 417

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_STRIDE_TOO_LARGE
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETVERTEXBUFFERS_STRIDE_TOO_LARGE => 418

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETVERTEXBUFFERS_INVALIDRANGE
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETVERTEXBUFFERS_INVALIDRANGE => 419

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_EMPTY_LAYOUT
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_EMPTY_LAYOUT => 420

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_DRAW_RESOURCE_SAMPLE_COUNT_MISMATCH
     * @type {Integer (Int32)}
     */
    static DEVICE_DRAW_RESOURCE_SAMPLE_COUNT_MISMATCH => 421

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_OBJECT_SUMMARY
     * @type {Integer (Int32)}
     */
    static LIVE_OBJECT_SUMMARY => 422

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_BUFFER
     * @type {Integer (Int32)}
     */
    static LIVE_BUFFER => 423

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_TEXTURE1D
     * @type {Integer (Int32)}
     */
    static LIVE_TEXTURE1D => 424

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_TEXTURE2D
     * @type {Integer (Int32)}
     */
    static LIVE_TEXTURE2D => 425

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_TEXTURE3D
     * @type {Integer (Int32)}
     */
    static LIVE_TEXTURE3D => 426

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_SHADERRESOURCEVIEW
     * @type {Integer (Int32)}
     */
    static LIVE_SHADERRESOURCEVIEW => 427

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_RENDERTARGETVIEW
     * @type {Integer (Int32)}
     */
    static LIVE_RENDERTARGETVIEW => 428

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_DEPTHSTENCILVIEW
     * @type {Integer (Int32)}
     */
    static LIVE_DEPTHSTENCILVIEW => 429

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_VERTEXSHADER
     * @type {Integer (Int32)}
     */
    static LIVE_VERTEXSHADER => 430

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_GEOMETRYSHADER
     * @type {Integer (Int32)}
     */
    static LIVE_GEOMETRYSHADER => 431

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_PIXELSHADER
     * @type {Integer (Int32)}
     */
    static LIVE_PIXELSHADER => 432

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_INPUTLAYOUT
     * @type {Integer (Int32)}
     */
    static LIVE_INPUTLAYOUT => 433

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_SAMPLER
     * @type {Integer (Int32)}
     */
    static LIVE_SAMPLER => 434

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_BLENDSTATE
     * @type {Integer (Int32)}
     */
    static LIVE_BLENDSTATE => 435

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_DEPTHSTENCILSTATE
     * @type {Integer (Int32)}
     */
    static LIVE_DEPTHSTENCILSTATE => 436

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_RASTERIZERSTATE
     * @type {Integer (Int32)}
     */
    static LIVE_RASTERIZERSTATE => 437

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_QUERY
     * @type {Integer (Int32)}
     */
    static LIVE_QUERY => 438

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_PREDICATE
     * @type {Integer (Int32)}
     */
    static LIVE_PREDICATE => 439

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_COUNTER
     * @type {Integer (Int32)}
     */
    static LIVE_COUNTER => 440

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_DEVICE
     * @type {Integer (Int32)}
     */
    static LIVE_DEVICE => 441

    /**
     * Native name: D3D10_MESSAGE_ID_LIVE_SWAPCHAIN
     * @type {Integer (Int32)}
     */
    static LIVE_SWAPCHAIN => 442

    /**
     * Native name: D3D10_MESSAGE_ID_D3D10_MESSAGES_END
     * @type {Integer (Int32)}
     */
    static D3D10_MESSAGES_END => 443

    /**
     * Native name: D3D10_MESSAGE_ID_D3D10L9_MESSAGES_START
     * @type {Integer (Int32)}
     */
    static D3D10L9_MESSAGES_START => 1048576

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEDEPTHSTENCILSTATE_STENCIL_NO_TWO_SIDED
     * @type {Integer (Int32)}
     */
    static CREATEDEPTHSTENCILSTATE_STENCIL_NO_TWO_SIDED => 1048577

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_DepthBiasClamp_NOT_SUPPORTED
     * @type {Integer (Int32)}
     */
    static CREATERASTERIZERSTATE_DepthBiasClamp_NOT_SUPPORTED => 1048578

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_NO_COMPARISON_SUPPORT
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_NO_COMPARISON_SUPPORT => 1048579

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_EXCESSIVE_ANISOTROPY
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_EXCESSIVE_ANISOTROPY => 1048580

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_BORDER_OUT_OF_RANGE
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_BORDER_OUT_OF_RANGE => 1048581

    /**
     * Native name: D3D10_MESSAGE_ID_VSSETSAMPLERS_NOT_SUPPORTED
     * @type {Integer (Int32)}
     */
    static VSSETSAMPLERS_NOT_SUPPORTED => 1048582

    /**
     * Native name: D3D10_MESSAGE_ID_VSSETSAMPLERS_TOO_MANY_SAMPLERS
     * @type {Integer (Int32)}
     */
    static VSSETSAMPLERS_TOO_MANY_SAMPLERS => 1048583

    /**
     * Native name: D3D10_MESSAGE_ID_PSSETSAMPLERS_TOO_MANY_SAMPLERS
     * @type {Integer (Int32)}
     */
    static PSSETSAMPLERS_TOO_MANY_SAMPLERS => 1048584

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_NO_ARRAYS
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_NO_ARRAYS => 1048585

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_NO_VB_AND_IB_BIND
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_NO_VB_AND_IB_BIND => 1048586

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_NO_TEXTURE_1D
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_NO_TEXTURE_1D => 1048587

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_DIMENSION_OUT_OF_RANGE
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_DIMENSION_OUT_OF_RANGE => 1048588

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_NOT_BINDABLE_AS_SHADER_RESOURCE
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_NOT_BINDABLE_AS_SHADER_RESOURCE => 1048589

    /**
     * Native name: D3D10_MESSAGE_ID_OMSETRENDERTARGETS_TOO_MANY_RENDER_TARGETS
     * @type {Integer (Int32)}
     */
    static OMSETRENDERTARGETS_TOO_MANY_RENDER_TARGETS => 1048590

    /**
     * Native name: D3D10_MESSAGE_ID_OMSETRENDERTARGETS_NO_DIFFERING_BIT_DEPTHS
     * @type {Integer (Int32)}
     */
    static OMSETRENDERTARGETS_NO_DIFFERING_BIT_DEPTHS => 1048591

    /**
     * Native name: D3D10_MESSAGE_ID_IASETVERTEXBUFFERS_BAD_BUFFER_INDEX
     * @type {Integer (Int32)}
     */
    static IASETVERTEXBUFFERS_BAD_BUFFER_INDEX => 1048592

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RSSETVIEWPORTS_TOO_MANY_VIEWPORTS
     * @type {Integer (Int32)}
     */
    static DEVICE_RSSETVIEWPORTS_TOO_MANY_VIEWPORTS => 1048593

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_IASETPRIMITIVETOPOLOGY_ADJACENCY_UNSUPPORTED
     * @type {Integer (Int32)}
     */
    static DEVICE_IASETPRIMITIVETOPOLOGY_ADJACENCY_UNSUPPORTED => 1048594

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_TOO_MANY_SCISSORS
     * @type {Integer (Int32)}
     */
    static DEVICE_RSSETSCISSORRECTS_TOO_MANY_SCISSORS => 1048595

    /**
     * Native name: D3D10_MESSAGE_ID_COPYRESOURCE_ONLY_TEXTURE_2D_WITHIN_GPU_MEMORY
     * @type {Integer (Int32)}
     */
    static COPYRESOURCE_ONLY_TEXTURE_2D_WITHIN_GPU_MEMORY => 1048596

    /**
     * Native name: D3D10_MESSAGE_ID_COPYRESOURCE_NO_TEXTURE_3D_READBACK
     * @type {Integer (Int32)}
     */
    static COPYRESOURCE_NO_TEXTURE_3D_READBACK => 1048597

    /**
     * Native name: D3D10_MESSAGE_ID_COPYRESOURCE_NO_TEXTURE_ONLY_READBACK
     * @type {Integer (Int32)}
     */
    static COPYRESOURCE_NO_TEXTURE_ONLY_READBACK => 1048598

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEINPUTLAYOUT_UNSUPPORTED_FORMAT
     * @type {Integer (Int32)}
     */
    static CREATEINPUTLAYOUT_UNSUPPORTED_FORMAT => 1048599

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_ALPHA_TO_COVERAGE
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_NO_ALPHA_TO_COVERAGE => 1048600

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERASTERIZERSTATE_DepthClipEnable_MUST_BE_TRUE
     * @type {Integer (Int32)}
     */
    static CREATERASTERIZERSTATE_DepthClipEnable_MUST_BE_TRUE => 1048601

    /**
     * Native name: D3D10_MESSAGE_ID_DRAWINDEXED_STARTINDEXLOCATION_MUST_BE_POSITIVE
     * @type {Integer (Int32)}
     */
    static DRAWINDEXED_STARTINDEXLOCATION_MUST_BE_POSITIVE => 1048602

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_MUST_USE_LOWEST_LOD
     * @type {Integer (Int32)}
     */
    static CREATESHADERRESOURCEVIEW_MUST_USE_LOWEST_LOD => 1048603

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_MINLOD_MUST_NOT_BE_FRACTIONAL
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_MINLOD_MUST_NOT_BE_FRACTIONAL => 1048604

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_MAXLOD_MUST_BE_FLT_MAX
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_MAXLOD_MUST_BE_FLT_MAX => 1048605

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_FIRSTARRAYSLICE_MUST_BE_ZERO
     * @type {Integer (Int32)}
     */
    static CREATESHADERRESOURCEVIEW_FIRSTARRAYSLICE_MUST_BE_ZERO => 1048606

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESHADERRESOURCEVIEW_CUBES_MUST_HAVE_6_SIDES
     * @type {Integer (Int32)}
     */
    static CREATESHADERRESOURCEVIEW_CUBES_MUST_HAVE_6_SIDES => 1048607

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_NOT_BINDABLE_AS_RENDER_TARGET
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_NOT_BINDABLE_AS_RENDER_TARGET => 1048608

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_NO_DWORD_INDEX_BUFFER
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_NO_DWORD_INDEX_BUFFER => 1048609

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_MSAA_PRECLUDES_SHADER_RESOURCE
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_MSAA_PRECLUDES_SHADER_RESOURCE => 1048610

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_PRESENTATION_PRECLUDES_SHADER_RESOURCE
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_PRESENTATION_PRECLUDES_SHADER_RESOURCE => 1048611

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_INDEPENDENT_BLEND_ENABLE
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_NO_INDEPENDENT_BLEND_ENABLE => 1048612

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_INDEPENDENT_WRITE_MASKS
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_NO_INDEPENDENT_WRITE_MASKS => 1048613

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_NO_STREAM_OUT
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_NO_STREAM_OUT => 1048614

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_ONLY_VB_IB_FOR_BUFFERS
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_ONLY_VB_IB_FOR_BUFFERS => 1048615

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_NO_AUTOGEN_FOR_VOLUMES
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_NO_AUTOGEN_FOR_VOLUMES => 1048616

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_DXGI_FORMAT_R8G8B8A8_CANNOT_BE_SHARED
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_DXGI_FORMAT_R8G8B8A8_CANNOT_BE_SHARED => 1048617

    /**
     * Native name: D3D10_MESSAGE_ID_VSSHADERRESOURCES_NOT_SUPPORTED
     * @type {Integer (Int32)}
     */
    static VSSHADERRESOURCES_NOT_SUPPORTED => 1048618

    /**
     * Native name: D3D10_MESSAGE_ID_GEOMETRY_SHADER_NOT_SUPPORTED
     * @type {Integer (Int32)}
     */
    static GEOMETRY_SHADER_NOT_SUPPORTED => 1048619

    /**
     * Native name: D3D10_MESSAGE_ID_STREAM_OUT_NOT_SUPPORTED
     * @type {Integer (Int32)}
     */
    static STREAM_OUT_NOT_SUPPORTED => 1048620

    /**
     * Native name: D3D10_MESSAGE_ID_TEXT_FILTER_NOT_SUPPORTED
     * @type {Integer (Int32)}
     */
    static TEXT_FILTER_NOT_SUPPORTED => 1048621

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_SEPARATE_ALPHA_BLEND
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_NO_SEPARATE_ALPHA_BLEND => 1048622

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_NO_MRT_BLEND
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_NO_MRT_BLEND => 1048623

    /**
     * Native name: D3D10_MESSAGE_ID_CREATEBLENDSTATE_OPERATION_NOT_SUPPORTED
     * @type {Integer (Int32)}
     */
    static CREATEBLENDSTATE_OPERATION_NOT_SUPPORTED => 1048624

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_NO_MIRRORONCE
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_NO_MIRRORONCE => 1048625

    /**
     * Native name: D3D10_MESSAGE_ID_DRAWINSTANCED_NOT_SUPPORTED
     * @type {Integer (Int32)}
     */
    static DRAWINSTANCED_NOT_SUPPORTED => 1048626

    /**
     * Native name: D3D10_MESSAGE_ID_DRAWINDEXEDINSTANCED_NOT_SUPPORTED_BELOW_9_3
     * @type {Integer (Int32)}
     */
    static DRAWINDEXEDINSTANCED_NOT_SUPPORTED_BELOW_9_3 => 1048627

    /**
     * Native name: D3D10_MESSAGE_ID_DRAWINDEXED_POINTLIST_UNSUPPORTED
     * @type {Integer (Int32)}
     */
    static DRAWINDEXED_POINTLIST_UNSUPPORTED => 1048628

    /**
     * Native name: D3D10_MESSAGE_ID_SETBLENDSTATE_SAMPLE_MASK_CANNOT_BE_ZERO
     * @type {Integer (Int32)}
     */
    static SETBLENDSTATE_SAMPLE_MASK_CANNOT_BE_ZERO => 1048629

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_DIMENSION_EXCEEDS_FEATURE_LEVEL_DEFINITION
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_DIMENSION_EXCEEDS_FEATURE_LEVEL_DEFINITION => 1048630

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_ONLY_SINGLE_MIP_LEVEL_DEPTH_STENCIL_SUPPORTED
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_ONLY_SINGLE_MIP_LEVEL_DEPTH_STENCIL_SUPPORTED => 1048631

    /**
     * Native name: D3D10_MESSAGE_ID_DEVICE_RSSETSCISSORRECTS_NEGATIVESCISSOR
     * @type {Integer (Int32)}
     */
    static DEVICE_RSSETSCISSORRECTS_NEGATIVESCISSOR => 1048632

    /**
     * Native name: D3D10_MESSAGE_ID_SLOT_ZERO_MUST_BE_D3D10_INPUT_PER_VERTEX_DATA
     * @type {Integer (Int32)}
     */
    static SLOT_ZERO_MUST_BE_D3D10_INPUT_PER_VERTEX_DATA => 1048633

    /**
     * Native name: D3D10_MESSAGE_ID_CREATERESOURCE_NON_POW_2_MIPMAP
     * @type {Integer (Int32)}
     */
    static CREATERESOURCE_NON_POW_2_MIPMAP => 1048634

    /**
     * Native name: D3D10_MESSAGE_ID_CREATESAMPLERSTATE_BORDER_NOT_SUPPORTED
     * @type {Integer (Int32)}
     */
    static CREATESAMPLERSTATE_BORDER_NOT_SUPPORTED => 1048635

    /**
     * Native name: D3D10_MESSAGE_ID_OMSETRENDERTARGETS_NO_SRGB_MRT
     * @type {Integer (Int32)}
     */
    static OMSETRENDERTARGETS_NO_SRGB_MRT => 1048636

    /**
     * Native name: D3D10_MESSAGE_ID_COPYRESOURCE_NO_3D_MISMATCHED_UPDATES
     * @type {Integer (Int32)}
     */
    static COPYRESOURCE_NO_3D_MISMATCHED_UPDATES => 1048637

    /**
     * Native name: D3D10_MESSAGE_ID_D3D10L9_MESSAGES_END
     * @type {Integer (Int32)}
     */
    static D3D10L9_MESSAGES_END => 1048638
}
