#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\CPOINT.ahk" {CPOINT}
#Import export ".\Constants.ahk" {*}
#Import export ".\DIACTIONA.ahk" {DIACTIONA}
#Import export ".\DIACTIONFORMATA.ahk" {DIACTIONFORMATA}
#Import export ".\DIACTIONFORMATW.ahk" {DIACTIONFORMATW}
#Import export ".\DIACTIONW.ahk" {DIACTIONW}
#Import export ".\DICOLORSET.ahk" {DICOLORSET}
#Import export ".\DICONDITION.ahk" {DICONDITION}
#Import export ".\DICONFIGUREDEVICESPARAMSA.ahk" {DICONFIGUREDEVICESPARAMSA}
#Import export ".\DICONFIGUREDEVICESPARAMSW.ahk" {DICONFIGUREDEVICESPARAMSW}
#Import export ".\DICONSTANTFORCE.ahk" {DICONSTANTFORCE}
#Import export ".\DICUSTOMFORCE.ahk" {DICUSTOMFORCE}
#Import export ".\DIDATAFORMAT.ahk" {DIDATAFORMAT}
#Import export ".\DIDEVCAPS.ahk" {DIDEVCAPS}
#Import export ".\DIDEVCAPS_DX3.ahk" {DIDEVCAPS_DX3}
#Import export ".\DIDEVICEIMAGEINFOA.ahk" {DIDEVICEIMAGEINFOA}
#Import export ".\DIDEVICEIMAGEINFOHEADERA.ahk" {DIDEVICEIMAGEINFOHEADERA}
#Import export ".\DIDEVICEIMAGEINFOHEADERW.ahk" {DIDEVICEIMAGEINFOHEADERW}
#Import export ".\DIDEVICEIMAGEINFOW.ahk" {DIDEVICEIMAGEINFOW}
#Import export ".\DIDEVICEINSTANCEA.ahk" {DIDEVICEINSTANCEA}
#Import export ".\DIDEVICEINSTANCEW.ahk" {DIDEVICEINSTANCEW}
#Import export ".\DIDEVICEINSTANCE_DX3A.ahk" {DIDEVICEINSTANCE_DX3A}
#Import export ".\DIDEVICEINSTANCE_DX3W.ahk" {DIDEVICEINSTANCE_DX3W}
#Import export ".\DIDEVICEOBJECTDATA.ahk" {DIDEVICEOBJECTDATA}
#Import export ".\DIDEVICEOBJECTDATA_DX3.ahk" {DIDEVICEOBJECTDATA_DX3}
#Import export ".\DIDEVICEOBJECTINSTANCEA.ahk" {DIDEVICEOBJECTINSTANCEA}
#Import export ".\DIDEVICEOBJECTINSTANCEW.ahk" {DIDEVICEOBJECTINSTANCEW}
#Import export ".\DIDEVICEOBJECTINSTANCE_DX3A.ahk" {DIDEVICEOBJECTINSTANCE_DX3A}
#Import export ".\DIDEVICEOBJECTINSTANCE_DX3W.ahk" {DIDEVICEOBJECTINSTANCE_DX3W}
#Import export ".\DIDEVICESTATE.ahk" {DIDEVICESTATE}
#Import export ".\DIDRIVERVERSIONS.ahk" {DIDRIVERVERSIONS}
#Import export ".\DIEFFECT.ahk" {DIEFFECT}
#Import export ".\DIEFFECTATTRIBUTES.ahk" {DIEFFECTATTRIBUTES}
#Import export ".\DIEFFECTINFOA.ahk" {DIEFFECTINFOA}
#Import export ".\DIEFFECTINFOW.ahk" {DIEFFECTINFOW}
#Import export ".\DIEFFECT_DX5.ahk" {DIEFFECT_DX5}
#Import export ".\DIEFFESCAPE.ahk" {DIEFFESCAPE}
#Import export ".\DIENVELOPE.ahk" {DIENVELOPE}
#Import export ".\DIFFDEVICEATTRIBUTES.ahk" {DIFFDEVICEATTRIBUTES}
#Import export ".\DIFFOBJECTATTRIBUTES.ahk" {DIFFOBJECTATTRIBUTES}
#Import export ".\DIFILEEFFECT.ahk" {DIFILEEFFECT}
#Import export ".\DIHIDFFINITINFO.ahk" {DIHIDFFINITINFO}
#Import export ".\DIJOYCONFIG.ahk" {DIJOYCONFIG}
#Import export ".\DIJOYCONFIG_DX5.ahk" {DIJOYCONFIG_DX5}
#Import export ".\DIJOYSTATE.ahk" {DIJOYSTATE}
#Import export ".\DIJOYSTATE2.ahk" {DIJOYSTATE2}
#Import export ".\DIJOYTYPEINFO.ahk" {DIJOYTYPEINFO}
#Import export ".\DIJOYTYPEINFO_DX5.ahk" {DIJOYTYPEINFO_DX5}
#Import export ".\DIJOYTYPEINFO_DX6.ahk" {DIJOYTYPEINFO_DX6}
#Import export ".\DIJOYUSERVALUES.ahk" {DIJOYUSERVALUES}
#Import export ".\DIMOUSESTATE.ahk" {DIMOUSESTATE}
#Import export ".\DIMOUSESTATE2.ahk" {DIMOUSESTATE2}
#Import export ".\DIOBJECTATTRIBUTES.ahk" {DIOBJECTATTRIBUTES}
#Import export ".\DIOBJECTCALIBRATION.ahk" {DIOBJECTCALIBRATION}
#Import export ".\DIOBJECTDATAFORMAT.ahk" {DIOBJECTDATAFORMAT}
#Import export ".\DIPERIODIC.ahk" {DIPERIODIC}
#Import export ".\DIPOVCALIBRATION.ahk" {DIPOVCALIBRATION}
#Import export ".\DIPROPCAL.ahk" {DIPROPCAL}
#Import export ".\DIPROPCALPOV.ahk" {DIPROPCALPOV}
#Import export ".\DIPROPCPOINTS.ahk" {DIPROPCPOINTS}
#Import export ".\DIPROPDWORD.ahk" {DIPROPDWORD}
#Import export ".\DIPROPGUIDANDPATH.ahk" {DIPROPGUIDANDPATH}
#Import export ".\DIPROPHEADER.ahk" {DIPROPHEADER}
#Import export ".\DIPROPPOINTER.ahk" {DIPROPPOINTER}
#Import export ".\DIPROPRANGE.ahk" {DIPROPRANGE}
#Import export ".\DIPROPSTRING.ahk" {DIPROPSTRING}
#Import export ".\DIRAMPFORCE.ahk" {DIRAMPFORCE}
#Import export ".\GPIOBUTTONS_BUTTON_TYPE.ahk" {GPIOBUTTONS_BUTTON_TYPE}
#Import export ".\HIDD_ATTRIBUTES.ahk" {HIDD_ATTRIBUTES}
#Import export ".\HIDD_CONFIGURATION.ahk" {HIDD_CONFIGURATION}
#Import export ".\HIDP_BUTTON_ARRAY_DATA.ahk" {HIDP_BUTTON_ARRAY_DATA}
#Import export ".\HIDP_BUTTON_CAPS.ahk" {HIDP_BUTTON_CAPS}
#Import export ".\HIDP_CAPS.ahk" {HIDP_CAPS}
#Import export ".\HIDP_DATA.ahk" {HIDP_DATA}
#Import export ".\HIDP_EXTENDED_ATTRIBUTES.ahk" {HIDP_EXTENDED_ATTRIBUTES}
#Import export ".\HIDP_KEYBOARD_DIRECTION.ahk" {HIDP_KEYBOARD_DIRECTION}
#Import export ".\HIDP_KEYBOARD_MODIFIER_STATE.ahk" {HIDP_KEYBOARD_MODIFIER_STATE}
#Import export ".\HIDP_LINK_COLLECTION_NODE.ahk" {HIDP_LINK_COLLECTION_NODE}
#Import export ".\HIDP_REPORT_TYPE.ahk" {HIDP_REPORT_TYPE}
#Import export ".\HIDP_UNKNOWN_TOKEN.ahk" {HIDP_UNKNOWN_TOKEN}
#Import export ".\HIDP_VALUE_CAPS.ahk" {HIDP_VALUE_CAPS}
#Import export ".\HID_COLLECTION_INFORMATION.ahk" {HID_COLLECTION_INFORMATION}
#Import export ".\HID_DRIVER_CONFIG.ahk" {HID_DRIVER_CONFIG}
#Import export ".\HID_XFER_PACKET.ahk" {HID_XFER_PACKET}
#Import export ".\IDirectInput2A.ahk" {IDirectInput2A}
#Import export ".\IDirectInput2W.ahk" {IDirectInput2W}
#Import export ".\IDirectInput7A.ahk" {IDirectInput7A}
#Import export ".\IDirectInput7W.ahk" {IDirectInput7W}
#Import export ".\IDirectInput8A.ahk" {IDirectInput8A}
#Import export ".\IDirectInput8W.ahk" {IDirectInput8W}
#Import export ".\IDirectInputA.ahk" {IDirectInputA}
#Import export ".\IDirectInputDevice2A.ahk" {IDirectInputDevice2A}
#Import export ".\IDirectInputDevice2W.ahk" {IDirectInputDevice2W}
#Import export ".\IDirectInputDevice7A.ahk" {IDirectInputDevice7A}
#Import export ".\IDirectInputDevice7W.ahk" {IDirectInputDevice7W}
#Import export ".\IDirectInputDevice8A.ahk" {IDirectInputDevice8A}
#Import export ".\IDirectInputDevice8W.ahk" {IDirectInputDevice8W}
#Import export ".\IDirectInputDeviceA.ahk" {IDirectInputDeviceA}
#Import export ".\IDirectInputDeviceW.ahk" {IDirectInputDeviceW}
#Import export ".\IDirectInputEffect.ahk" {IDirectInputEffect}
#Import export ".\IDirectInputEffectDriver.ahk" {IDirectInputEffectDriver}
#Import export ".\IDirectInputJoyConfig.ahk" {IDirectInputJoyConfig}
#Import export ".\IDirectInputJoyConfig8.ahk" {IDirectInputJoyConfig8}
#Import export ".\IDirectInputW.ahk" {IDirectInputW}
#Import export ".\INDICATOR_LIST.ahk" {INDICATOR_LIST}
#Import export ".\INPUT_BUTTON_ENABLE_INFO.ahk" {INPUT_BUTTON_ENABLE_INFO}
#Import export ".\JOYCALIBRATE.ahk" {JOYCALIBRATE}
#Import export ".\JOYPOS.ahk" {JOYPOS}
#Import export ".\JOYRANGE.ahk" {JOYRANGE}
#Import export ".\JOYREGHWCONFIG.ahk" {JOYREGHWCONFIG}
#Import export ".\JOYREGHWSETTINGS.ahk" {JOYREGHWSETTINGS}
#Import export ".\JOYREGHWVALUES.ahk" {JOYREGHWVALUES}
#Import export ".\JOYREGUSERVALUES.ahk" {JOYREGUSERVALUES}
#Import export ".\KEYBOARD_ATTRIBUTES.ahk" {KEYBOARD_ATTRIBUTES}
#Import export ".\KEYBOARD_EXTENDED_ATTRIBUTES.ahk" {KEYBOARD_EXTENDED_ATTRIBUTES}
#Import export ".\KEYBOARD_ID.ahk" {KEYBOARD_ID}
#Import export ".\KEYBOARD_IME_STATUS.ahk" {KEYBOARD_IME_STATUS}
#Import export ".\KEYBOARD_INDICATOR_PARAMETERS.ahk" {KEYBOARD_INDICATOR_PARAMETERS}
#Import export ".\KEYBOARD_INDICATOR_TRANSLATION.ahk" {KEYBOARD_INDICATOR_TRANSLATION}
#Import export ".\KEYBOARD_INPUT_DATA.ahk" {KEYBOARD_INPUT_DATA}
#Import export ".\KEYBOARD_TYPEMATIC_PARAMETERS.ahk" {KEYBOARD_TYPEMATIC_PARAMETERS}
#Import export ".\KEYBOARD_UNIT_ID_PARAMETER.ahk" {KEYBOARD_UNIT_ID_PARAMETER}
#Import export ".\LPDICONFIGUREDEVICESCALLBACK.ahk" {LPDICONFIGUREDEVICESCALLBACK}
#Import export ".\LPDIENUMCREATEDEFFECTOBJECTSCALLBACK.ahk" {LPDIENUMCREATEDEFFECTOBJECTSCALLBACK}
#Import export ".\LPDIENUMDEVICEOBJECTSCALLBACKA.ahk" {LPDIENUMDEVICEOBJECTSCALLBACKA}
#Import export ".\LPDIENUMDEVICEOBJECTSCALLBACKW.ahk" {LPDIENUMDEVICEOBJECTSCALLBACKW}
#Import export ".\LPDIENUMDEVICESBYSEMANTICSCBA.ahk" {LPDIENUMDEVICESBYSEMANTICSCBA}
#Import export ".\LPDIENUMDEVICESBYSEMANTICSCBW.ahk" {LPDIENUMDEVICESBYSEMANTICSCBW}
#Import export ".\LPDIENUMDEVICESCALLBACKA.ahk" {LPDIENUMDEVICESCALLBACKA}
#Import export ".\LPDIENUMDEVICESCALLBACKW.ahk" {LPDIENUMDEVICESCALLBACKW}
#Import export ".\LPDIENUMEFFECTSCALLBACKA.ahk" {LPDIENUMEFFECTSCALLBACKA}
#Import export ".\LPDIENUMEFFECTSCALLBACKW.ahk" {LPDIENUMEFFECTSCALLBACKW}
#Import export ".\LPDIENUMEFFECTSINFILECALLBACK.ahk" {LPDIENUMEFFECTSINFILECALLBACK}
#Import export ".\LPDIJOYTYPECALLBACK.ahk" {LPDIJOYTYPECALLBACK}
#Import export ".\LPFNSHOWJOYCPL.ahk" {LPFNSHOWJOYCPL}
#Import export ".\MOUSE_ATTRIBUTES.ahk" {MOUSE_ATTRIBUTES}
#Import export ".\MOUSE_INPUT_DATA.ahk" {MOUSE_INPUT_DATA}
#Import export ".\MOUSE_UNIT_ID_PARAMETER.ahk" {MOUSE_UNIT_ID_PARAMETER}
#Import export ".\PFN_HidP_GetVersionInternal.ahk" {PFN_HidP_GetVersionInternal}
#Import export ".\PHIDP_INSERT_SCANCODES.ahk" {PHIDP_INSERT_SCANCODES}
#Import export ".\PHIDP_PREPARSED_DATA.ahk" {PHIDP_PREPARSED_DATA}
#Import export ".\USAGE_AND_PAGE.ahk" {USAGE_AND_PAGE}
