#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Common\__Init.ahk" {*}
#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\D2D1_2DAFFINETRANSFORM_PROP.ahk" {D2D1_2DAFFINETRANSFORM_PROP}
#Import export ".\D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE.ahk" {D2D1_3DPERSPECTIVETRANSFORM_INTERPOLATION_MODE}
#Import export ".\D2D1_3DPERSPECTIVETRANSFORM_PROP.ahk" {D2D1_3DPERSPECTIVETRANSFORM_PROP}
#Import export ".\D2D1_3DTRANSFORM_INTERPOLATION_MODE.ahk" {D2D1_3DTRANSFORM_INTERPOLATION_MODE}
#Import export ".\D2D1_3DTRANSFORM_PROP.ahk" {D2D1_3DTRANSFORM_PROP}
#Import export ".\D2D1_ANTIALIAS_MODE.ahk" {D2D1_ANTIALIAS_MODE}
#Import export ".\D2D1_ARC_SEGMENT.ahk" {D2D1_ARC_SEGMENT}
#Import export ".\D2D1_ARC_SIZE.ahk" {D2D1_ARC_SIZE}
#Import export ".\D2D1_ARITHMETICCOMPOSITE_PROP.ahk" {D2D1_ARITHMETICCOMPOSITE_PROP}
#Import export ".\D2D1_ATLAS_PROP.ahk" {D2D1_ATLAS_PROP}
#Import export ".\D2D1_BITMAPSOURCE_ALPHA_MODE.ahk" {D2D1_BITMAPSOURCE_ALPHA_MODE}
#Import export ".\D2D1_BITMAPSOURCE_INTERPOLATION_MODE.ahk" {D2D1_BITMAPSOURCE_INTERPOLATION_MODE}
#Import export ".\D2D1_BITMAPSOURCE_ORIENTATION.ahk" {D2D1_BITMAPSOURCE_ORIENTATION}
#Import export ".\D2D1_BITMAPSOURCE_PROP.ahk" {D2D1_BITMAPSOURCE_PROP}
#Import export ".\D2D1_BITMAP_BRUSH_PROPERTIES.ahk" {D2D1_BITMAP_BRUSH_PROPERTIES}
#Import export ".\D2D1_BITMAP_BRUSH_PROPERTIES1.ahk" {D2D1_BITMAP_BRUSH_PROPERTIES1}
#Import export ".\D2D1_BITMAP_INTERPOLATION_MODE.ahk" {D2D1_BITMAP_INTERPOLATION_MODE}
#Import export ".\D2D1_BITMAP_OPTIONS.ahk" {D2D1_BITMAP_OPTIONS}
#Import export ".\D2D1_BITMAP_PROPERTIES.ahk" {D2D1_BITMAP_PROPERTIES}
#Import export ".\D2D1_BITMAP_PROPERTIES1.ahk" {D2D1_BITMAP_PROPERTIES1}
#Import export ".\D2D1_BLEND.ahk" {D2D1_BLEND}
#Import export ".\D2D1_BLEND_DESCRIPTION.ahk" {D2D1_BLEND_DESCRIPTION}
#Import export ".\D2D1_BLEND_OPERATION.ahk" {D2D1_BLEND_OPERATION}
#Import export ".\D2D1_BLEND_PROP.ahk" {D2D1_BLEND_PROP}
#Import export ".\D2D1_BORDER_EDGE_MODE.ahk" {D2D1_BORDER_EDGE_MODE}
#Import export ".\D2D1_BORDER_PROP.ahk" {D2D1_BORDER_PROP}
#Import export ".\D2D1_BRIGHTNESS_PROP.ahk" {D2D1_BRIGHTNESS_PROP}
#Import export ".\D2D1_BRUSH_PROPERTIES.ahk" {D2D1_BRUSH_PROPERTIES}
#Import export ".\D2D1_BUFFER_PRECISION.ahk" {D2D1_BUFFER_PRECISION}
#Import export ".\D2D1_CAP_STYLE.ahk" {D2D1_CAP_STYLE}
#Import export ".\D2D1_CHANGE_TYPE.ahk" {D2D1_CHANGE_TYPE}
#Import export ".\D2D1_CHANNEL_DEPTH.ahk" {D2D1_CHANNEL_DEPTH}
#Import export ".\D2D1_CHANNEL_SELECTOR.ahk" {D2D1_CHANNEL_SELECTOR}
#Import export ".\D2D1_CHROMAKEY_PROP.ahk" {D2D1_CHROMAKEY_PROP}
#Import export ".\D2D1_COLORMANAGEMENT_ALPHA_MODE.ahk" {D2D1_COLORMANAGEMENT_ALPHA_MODE}
#Import export ".\D2D1_COLORMANAGEMENT_PROP.ahk" {D2D1_COLORMANAGEMENT_PROP}
#Import export ".\D2D1_COLORMANAGEMENT_QUALITY.ahk" {D2D1_COLORMANAGEMENT_QUALITY}
#Import export ".\D2D1_COLORMANAGEMENT_RENDERING_INTENT.ahk" {D2D1_COLORMANAGEMENT_RENDERING_INTENT}
#Import export ".\D2D1_COLORMATRIX_PROP.ahk" {D2D1_COLORMATRIX_PROP}
#Import export ".\D2D1_COLOR_BITMAP_GLYPH_SNAP_OPTION.ahk" {D2D1_COLOR_BITMAP_GLYPH_SNAP_OPTION}
#Import export ".\D2D1_COLOR_CONTEXT_TYPE.ahk" {D2D1_COLOR_CONTEXT_TYPE}
#Import export ".\D2D1_COLOR_INTERPOLATION_MODE.ahk" {D2D1_COLOR_INTERPOLATION_MODE}
#Import export ".\D2D1_COLOR_SPACE.ahk" {D2D1_COLOR_SPACE}
#Import export ".\D2D1_COMBINE_MODE.ahk" {D2D1_COMBINE_MODE}
#Import export ".\D2D1_COMPATIBLE_RENDER_TARGET_OPTIONS.ahk" {D2D1_COMPATIBLE_RENDER_TARGET_OPTIONS}
#Import export ".\D2D1_COMPOSITE_PROP.ahk" {D2D1_COMPOSITE_PROP}
#Import export ".\D2D1_CONTRAST_PROP.ahk" {D2D1_CONTRAST_PROP}
#Import export ".\D2D1_CONVOLVEMATRIX_PROP.ahk" {D2D1_CONVOLVEMATRIX_PROP}
#Import export ".\D2D1_CONVOLVEMATRIX_SCALE_MODE.ahk" {D2D1_CONVOLVEMATRIX_SCALE_MODE}
#Import export ".\D2D1_CREATION_PROPERTIES.ahk" {D2D1_CREATION_PROPERTIES}
#Import export ".\D2D1_CROP_PROP.ahk" {D2D1_CROP_PROP}
#Import export ".\D2D1_CROSSFADE_PROP.ahk" {D2D1_CROSSFADE_PROP}
#Import export ".\D2D1_CUSTOM_VERTEX_BUFFER_PROPERTIES.ahk" {D2D1_CUSTOM_VERTEX_BUFFER_PROPERTIES}
#Import export ".\D2D1_DASH_STYLE.ahk" {D2D1_DASH_STYLE}
#Import export ".\D2D1_DC_INITIALIZE_MODE.ahk" {D2D1_DC_INITIALIZE_MODE}
#Import export ".\D2D1_DEBUG_LEVEL.ahk" {D2D1_DEBUG_LEVEL}
#Import export ".\D2D1_DEVICE_CONTEXT_OPTIONS.ahk" {D2D1_DEVICE_CONTEXT_OPTIONS}
#Import export ".\D2D1_DIRECTIONALBLUR_OPTIMIZATION.ahk" {D2D1_DIRECTIONALBLUR_OPTIMIZATION}
#Import export ".\D2D1_DIRECTIONALBLUR_PROP.ahk" {D2D1_DIRECTIONALBLUR_PROP}
#Import export ".\D2D1_DISCRETETRANSFER_PROP.ahk" {D2D1_DISCRETETRANSFER_PROP}
#Import export ".\D2D1_DISPLACEMENTMAP_PROP.ahk" {D2D1_DISPLACEMENTMAP_PROP}
#Import export ".\D2D1_DISTANTDIFFUSE_PROP.ahk" {D2D1_DISTANTDIFFUSE_PROP}
#Import export ".\D2D1_DISTANTDIFFUSE_SCALE_MODE.ahk" {D2D1_DISTANTDIFFUSE_SCALE_MODE}
#Import export ".\D2D1_DISTANTSPECULAR_PROP.ahk" {D2D1_DISTANTSPECULAR_PROP}
#Import export ".\D2D1_DISTANTSPECULAR_SCALE_MODE.ahk" {D2D1_DISTANTSPECULAR_SCALE_MODE}
#Import export ".\D2D1_DPICOMPENSATION_INTERPOLATION_MODE.ahk" {D2D1_DPICOMPENSATION_INTERPOLATION_MODE}
#Import export ".\D2D1_DPICOMPENSATION_PROP.ahk" {D2D1_DPICOMPENSATION_PROP}
#Import export ".\D2D1_DRAWING_STATE_DESCRIPTION.ahk" {D2D1_DRAWING_STATE_DESCRIPTION}
#Import export ".\D2D1_DRAWING_STATE_DESCRIPTION1.ahk" {D2D1_DRAWING_STATE_DESCRIPTION1}
#Import export ".\D2D1_DRAW_TEXT_OPTIONS.ahk" {D2D1_DRAW_TEXT_OPTIONS}
#Import export ".\D2D1_EDGEDETECTION_MODE.ahk" {D2D1_EDGEDETECTION_MODE}
#Import export ".\D2D1_EDGEDETECTION_PROP.ahk" {D2D1_EDGEDETECTION_PROP}
#Import export ".\D2D1_EFFECT_INPUT_DESCRIPTION.ahk" {D2D1_EFFECT_INPUT_DESCRIPTION}
#Import export ".\D2D1_ELLIPSE.ahk" {D2D1_ELLIPSE}
#Import export ".\D2D1_EMBOSS_PROP.ahk" {D2D1_EMBOSS_PROP}
#Import export ".\D2D1_EXPOSURE_PROP.ahk" {D2D1_EXPOSURE_PROP}
#Import export ".\D2D1_EXTEND_MODE.ahk" {D2D1_EXTEND_MODE}
#Import export ".\D2D1_FACTORY_OPTIONS.ahk" {D2D1_FACTORY_OPTIONS}
#Import export ".\D2D1_FACTORY_TYPE.ahk" {D2D1_FACTORY_TYPE}
#Import export ".\D2D1_FEATURE.ahk" {D2D1_FEATURE}
#Import export ".\D2D1_FEATURE_DATA_D3D10_X_HARDWARE_OPTIONS.ahk" {D2D1_FEATURE_DATA_D3D10_X_HARDWARE_OPTIONS}
#Import export ".\D2D1_FEATURE_DATA_DOUBLES.ahk" {D2D1_FEATURE_DATA_DOUBLES}
#Import export ".\D2D1_FEATURE_LEVEL.ahk" {D2D1_FEATURE_LEVEL}
#Import export ".\D2D1_FILTER.ahk" {D2D1_FILTER}
#Import export ".\D2D1_FLOOD_PROP.ahk" {D2D1_FLOOD_PROP}
#Import export ".\D2D1_GAMMA.ahk" {D2D1_GAMMA}
#Import export ".\D2D1_GAMMA1.ahk" {D2D1_GAMMA1}
#Import export ".\D2D1_GAMMATRANSFER_PROP.ahk" {D2D1_GAMMATRANSFER_PROP}
#Import export ".\D2D1_GAUSSIANBLUR_OPTIMIZATION.ahk" {D2D1_GAUSSIANBLUR_OPTIMIZATION}
#Import export ".\D2D1_GAUSSIANBLUR_PROP.ahk" {D2D1_GAUSSIANBLUR_PROP}
#Import export ".\D2D1_GEOMETRY_RELATION.ahk" {D2D1_GEOMETRY_RELATION}
#Import export ".\D2D1_GEOMETRY_SIMPLIFICATION_OPTION.ahk" {D2D1_GEOMETRY_SIMPLIFICATION_OPTION}
#Import export ".\D2D1_GRADIENT_MESH_PATCH.ahk" {D2D1_GRADIENT_MESH_PATCH}
#Import export ".\D2D1_HDRTONEMAP_DISPLAY_MODE.ahk" {D2D1_HDRTONEMAP_DISPLAY_MODE}
#Import export ".\D2D1_HDRTONEMAP_PROP.ahk" {D2D1_HDRTONEMAP_PROP}
#Import export ".\D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA.ahk" {D2D1_HIGHLIGHTSANDSHADOWS_INPUT_GAMMA}
#Import export ".\D2D1_HIGHLIGHTSANDSHADOWS_PROP.ahk" {D2D1_HIGHLIGHTSANDSHADOWS_PROP}
#Import export ".\D2D1_HISTOGRAM_PROP.ahk" {D2D1_HISTOGRAM_PROP}
#Import export ".\D2D1_HUEROTATION_PROP.ahk" {D2D1_HUEROTATION_PROP}
#Import export ".\D2D1_HUETORGB_INPUT_COLOR_SPACE.ahk" {D2D1_HUETORGB_INPUT_COLOR_SPACE}
#Import export ".\D2D1_HUETORGB_PROP.ahk" {D2D1_HUETORGB_PROP}
#Import export ".\D2D1_HWND_RENDER_TARGET_PROPERTIES.ahk" {D2D1_HWND_RENDER_TARGET_PROPERTIES}
#Import export ".\D2D1_IMAGE_BRUSH_PROPERTIES.ahk" {D2D1_IMAGE_BRUSH_PROPERTIES}
#Import export ".\D2D1_IMAGE_SOURCE_FROM_DXGI_OPTIONS.ahk" {D2D1_IMAGE_SOURCE_FROM_DXGI_OPTIONS}
#Import export ".\D2D1_IMAGE_SOURCE_LOADING_OPTIONS.ahk" {D2D1_IMAGE_SOURCE_LOADING_OPTIONS}
#Import export ".\D2D1_INK_BEZIER_SEGMENT.ahk" {D2D1_INK_BEZIER_SEGMENT}
#Import export ".\D2D1_INK_NIB_SHAPE.ahk" {D2D1_INK_NIB_SHAPE}
#Import export ".\D2D1_INK_POINT.ahk" {D2D1_INK_POINT}
#Import export ".\D2D1_INK_STYLE_PROPERTIES.ahk" {D2D1_INK_STYLE_PROPERTIES}
#Import export ".\D2D1_INPUT_DESCRIPTION.ahk" {D2D1_INPUT_DESCRIPTION}
#Import export ".\D2D1_INPUT_ELEMENT_DESC.ahk" {D2D1_INPUT_ELEMENT_DESC}
#Import export ".\D2D1_INTERPOLATION_MODE.ahk" {D2D1_INTERPOLATION_MODE}
#Import export ".\D2D1_INTERPOLATION_MODE_DEFINITION.ahk" {D2D1_INTERPOLATION_MODE_DEFINITION}
#Import export ".\D2D1_LAYER_OPTIONS.ahk" {D2D1_LAYER_OPTIONS}
#Import export ".\D2D1_LAYER_OPTIONS1.ahk" {D2D1_LAYER_OPTIONS1}
#Import export ".\D2D1_LAYER_PARAMETERS.ahk" {D2D1_LAYER_PARAMETERS}
#Import export ".\D2D1_LAYER_PARAMETERS1.ahk" {D2D1_LAYER_PARAMETERS1}
#Import export ".\D2D1_LINEARTRANSFER_PROP.ahk" {D2D1_LINEARTRANSFER_PROP}
#Import export ".\D2D1_LINEAR_GRADIENT_BRUSH_PROPERTIES.ahk" {D2D1_LINEAR_GRADIENT_BRUSH_PROPERTIES}
#Import export ".\D2D1_LINE_JOIN.ahk" {D2D1_LINE_JOIN}
#Import export ".\D2D1_LOOKUPTABLE3D_PROP.ahk" {D2D1_LOOKUPTABLE3D_PROP}
#Import export ".\D2D1_MAPPED_RECT.ahk" {D2D1_MAPPED_RECT}
#Import export ".\D2D1_MAP_OPTIONS.ahk" {D2D1_MAP_OPTIONS}
#Import export ".\D2D1_MORPHOLOGY_MODE.ahk" {D2D1_MORPHOLOGY_MODE}
#Import export ".\D2D1_MORPHOLOGY_PROP.ahk" {D2D1_MORPHOLOGY_PROP}
#Import export ".\D2D1_OPACITYMETADATA_PROP.ahk" {D2D1_OPACITYMETADATA_PROP}
#Import export ".\D2D1_OPACITY_MASK_CONTENT.ahk" {D2D1_OPACITY_MASK_CONTENT}
#Import export ".\D2D1_OPACITY_PROP.ahk" {D2D1_OPACITY_PROP}
#Import export ".\D2D1_ORIENTATION.ahk" {D2D1_ORIENTATION}
#Import export ".\D2D1_PATCH_EDGE_MODE.ahk" {D2D1_PATCH_EDGE_MODE}
#Import export ".\D2D1_PIXEL_OPTIONS.ahk" {D2D1_PIXEL_OPTIONS}
#Import export ".\D2D1_POINTDIFFUSE_PROP.ahk" {D2D1_POINTDIFFUSE_PROP}
#Import export ".\D2D1_POINTDIFFUSE_SCALE_MODE.ahk" {D2D1_POINTDIFFUSE_SCALE_MODE}
#Import export ".\D2D1_POINTSPECULAR_PROP.ahk" {D2D1_POINTSPECULAR_PROP}
#Import export ".\D2D1_POINTSPECULAR_SCALE_MODE.ahk" {D2D1_POINTSPECULAR_SCALE_MODE}
#Import export ".\D2D1_POINT_DESCRIPTION.ahk" {D2D1_POINT_DESCRIPTION}
#Import export ".\D2D1_POSTERIZE_PROP.ahk" {D2D1_POSTERIZE_PROP}
#Import export ".\D2D1_PRESENT_OPTIONS.ahk" {D2D1_PRESENT_OPTIONS}
#Import export ".\D2D1_PRIMITIVE_BLEND.ahk" {D2D1_PRIMITIVE_BLEND}
#Import export ".\D2D1_PRINT_CONTROL_PROPERTIES.ahk" {D2D1_PRINT_CONTROL_PROPERTIES}
#Import export ".\D2D1_PRINT_FONT_SUBSET_MODE.ahk" {D2D1_PRINT_FONT_SUBSET_MODE}
#Import export ".\D2D1_PROPERTY.ahk" {D2D1_PROPERTY}
#Import export ".\D2D1_PROPERTY_BINDING.ahk" {D2D1_PROPERTY_BINDING}
#Import export ".\D2D1_PROPERTY_TYPE.ahk" {D2D1_PROPERTY_TYPE}
#Import export ".\D2D1_QUADRATIC_BEZIER_SEGMENT.ahk" {D2D1_QUADRATIC_BEZIER_SEGMENT}
#Import export ".\D2D1_RADIAL_GRADIENT_BRUSH_PROPERTIES.ahk" {D2D1_RADIAL_GRADIENT_BRUSH_PROPERTIES}
#Import export ".\D2D1_RENDERING_CONTROLS.ahk" {D2D1_RENDERING_CONTROLS}
#Import export ".\D2D1_RENDERING_PRIORITY.ahk" {D2D1_RENDERING_PRIORITY}
#Import export ".\D2D1_RENDER_TARGET_PROPERTIES.ahk" {D2D1_RENDER_TARGET_PROPERTIES}
#Import export ".\D2D1_RENDER_TARGET_TYPE.ahk" {D2D1_RENDER_TARGET_TYPE}
#Import export ".\D2D1_RENDER_TARGET_USAGE.ahk" {D2D1_RENDER_TARGET_USAGE}
#Import export ".\D2D1_RESOURCE_TEXTURE_PROPERTIES.ahk" {D2D1_RESOURCE_TEXTURE_PROPERTIES}
#Import export ".\D2D1_RGBTOHUE_OUTPUT_COLOR_SPACE.ahk" {D2D1_RGBTOHUE_OUTPUT_COLOR_SPACE}
#Import export ".\D2D1_RGBTOHUE_PROP.ahk" {D2D1_RGBTOHUE_PROP}
#Import export ".\D2D1_ROUNDED_RECT.ahk" {D2D1_ROUNDED_RECT}
#Import export ".\D2D1_SATURATION_PROP.ahk" {D2D1_SATURATION_PROP}
#Import export ".\D2D1_SCALE_INTERPOLATION_MODE.ahk" {D2D1_SCALE_INTERPOLATION_MODE}
#Import export ".\D2D1_SCALE_PROP.ahk" {D2D1_SCALE_PROP}
#Import export ".\D2D1_SEPIA_PROP.ahk" {D2D1_SEPIA_PROP}
#Import export ".\D2D1_SHADOW_OPTIMIZATION.ahk" {D2D1_SHADOW_OPTIMIZATION}
#Import export ".\D2D1_SHADOW_PROP.ahk" {D2D1_SHADOW_PROP}
#Import export ".\D2D1_SHARPEN_PROP.ahk" {D2D1_SHARPEN_PROP}
#Import export ".\D2D1_SIMPLE_COLOR_PROFILE.ahk" {D2D1_SIMPLE_COLOR_PROFILE}
#Import export ".\D2D1_SPOTDIFFUSE_PROP.ahk" {D2D1_SPOTDIFFUSE_PROP}
#Import export ".\D2D1_SPOTDIFFUSE_SCALE_MODE.ahk" {D2D1_SPOTDIFFUSE_SCALE_MODE}
#Import export ".\D2D1_SPOTSPECULAR_PROP.ahk" {D2D1_SPOTSPECULAR_PROP}
#Import export ".\D2D1_SPOTSPECULAR_SCALE_MODE.ahk" {D2D1_SPOTSPECULAR_SCALE_MODE}
#Import export ".\D2D1_SPRITE_OPTIONS.ahk" {D2D1_SPRITE_OPTIONS}
#Import export ".\D2D1_STRAIGHTEN_PROP.ahk" {D2D1_STRAIGHTEN_PROP}
#Import export ".\D2D1_STRAIGHTEN_SCALE_MODE.ahk" {D2D1_STRAIGHTEN_SCALE_MODE}
#Import export ".\D2D1_STROKE_STYLE_PROPERTIES.ahk" {D2D1_STROKE_STYLE_PROPERTIES}
#Import export ".\D2D1_STROKE_STYLE_PROPERTIES1.ahk" {D2D1_STROKE_STYLE_PROPERTIES1}
#Import export ".\D2D1_STROKE_TRANSFORM_TYPE.ahk" {D2D1_STROKE_TRANSFORM_TYPE}
#Import export ".\D2D1_SUBPROPERTY.ahk" {D2D1_SUBPROPERTY}
#Import export ".\D2D1_SVG_ASPECT_ALIGN.ahk" {D2D1_SVG_ASPECT_ALIGN}
#Import export ".\D2D1_SVG_ASPECT_SCALING.ahk" {D2D1_SVG_ASPECT_SCALING}
#Import export ".\D2D1_SVG_ATTRIBUTE_POD_TYPE.ahk" {D2D1_SVG_ATTRIBUTE_POD_TYPE}
#Import export ".\D2D1_SVG_ATTRIBUTE_STRING_TYPE.ahk" {D2D1_SVG_ATTRIBUTE_STRING_TYPE}
#Import export ".\D2D1_SVG_DISPLAY.ahk" {D2D1_SVG_DISPLAY}
#Import export ".\D2D1_SVG_LENGTH.ahk" {D2D1_SVG_LENGTH}
#Import export ".\D2D1_SVG_LENGTH_UNITS.ahk" {D2D1_SVG_LENGTH_UNITS}
#Import export ".\D2D1_SVG_LINE_CAP.ahk" {D2D1_SVG_LINE_CAP}
#Import export ".\D2D1_SVG_LINE_JOIN.ahk" {D2D1_SVG_LINE_JOIN}
#Import export ".\D2D1_SVG_OVERFLOW.ahk" {D2D1_SVG_OVERFLOW}
#Import export ".\D2D1_SVG_PAINT_TYPE.ahk" {D2D1_SVG_PAINT_TYPE}
#Import export ".\D2D1_SVG_PATH_COMMAND.ahk" {D2D1_SVG_PATH_COMMAND}
#Import export ".\D2D1_SVG_PRESERVE_ASPECT_RATIO.ahk" {D2D1_SVG_PRESERVE_ASPECT_RATIO}
#Import export ".\D2D1_SVG_UNIT_TYPE.ahk" {D2D1_SVG_UNIT_TYPE}
#Import export ".\D2D1_SVG_VIEWBOX.ahk" {D2D1_SVG_VIEWBOX}
#Import export ".\D2D1_SVG_VISIBILITY.ahk" {D2D1_SVG_VISIBILITY}
#Import export ".\D2D1_SWEEP_DIRECTION.ahk" {D2D1_SWEEP_DIRECTION}
#Import export ".\D2D1_TABLETRANSFER_PROP.ahk" {D2D1_TABLETRANSFER_PROP}
#Import export ".\D2D1_TEMPERATUREANDTINT_PROP.ahk" {D2D1_TEMPERATUREANDTINT_PROP}
#Import export ".\D2D1_TEXT_ANTIALIAS_MODE.ahk" {D2D1_TEXT_ANTIALIAS_MODE}
#Import export ".\D2D1_THREADING_MODE.ahk" {D2D1_THREADING_MODE}
#Import export ".\D2D1_TILE_PROP.ahk" {D2D1_TILE_PROP}
#Import export ".\D2D1_TINT_PROP.ahk" {D2D1_TINT_PROP}
#Import export ".\D2D1_TRANSFORMED_IMAGE_SOURCE_OPTIONS.ahk" {D2D1_TRANSFORMED_IMAGE_SOURCE_OPTIONS}
#Import export ".\D2D1_TRANSFORMED_IMAGE_SOURCE_PROPERTIES.ahk" {D2D1_TRANSFORMED_IMAGE_SOURCE_PROPERTIES}
#Import export ".\D2D1_TRIANGLE.ahk" {D2D1_TRIANGLE}
#Import export ".\D2D1_TURBULENCE_PROP.ahk" {D2D1_TURBULENCE_PROP}
#Import export ".\D2D1_UNIT_MODE.ahk" {D2D1_UNIT_MODE}
#Import export ".\D2D1_VERTEX_BUFFER_PROPERTIES.ahk" {D2D1_VERTEX_BUFFER_PROPERTIES}
#Import export ".\D2D1_VERTEX_OPTIONS.ahk" {D2D1_VERTEX_OPTIONS}
#Import export ".\D2D1_VERTEX_RANGE.ahk" {D2D1_VERTEX_RANGE}
#Import export ".\D2D1_VERTEX_USAGE.ahk" {D2D1_VERTEX_USAGE}
#Import export ".\D2D1_VIGNETTE_PROP.ahk" {D2D1_VIGNETTE_PROP}
#Import export ".\D2D1_WHITELEVELADJUSTMENT_PROP.ahk" {D2D1_WHITELEVELADJUSTMENT_PROP}
#Import export ".\D2D1_WINDOW_STATE.ahk" {D2D1_WINDOW_STATE}
#Import export ".\D2D1_YCBCR_CHROMA_SUBSAMPLING.ahk" {D2D1_YCBCR_CHROMA_SUBSAMPLING}
#Import export ".\D2D1_YCBCR_INTERPOLATION_MODE.ahk" {D2D1_YCBCR_INTERPOLATION_MODE}
#Import export ".\D2D1_YCBCR_PROP.ahk" {D2D1_YCBCR_PROP}
#Import export ".\ID2D1AnalysisTransform.ahk" {ID2D1AnalysisTransform}
#Import export ".\ID2D1Bitmap.ahk" {ID2D1Bitmap}
#Import export ".\ID2D1Bitmap1.ahk" {ID2D1Bitmap1}
#Import export ".\ID2D1BitmapBrush.ahk" {ID2D1BitmapBrush}
#Import export ".\ID2D1BitmapBrush1.ahk" {ID2D1BitmapBrush1}
#Import export ".\ID2D1BitmapRenderTarget.ahk" {ID2D1BitmapRenderTarget}
#Import export ".\ID2D1BlendTransform.ahk" {ID2D1BlendTransform}
#Import export ".\ID2D1BorderTransform.ahk" {ID2D1BorderTransform}
#Import export ".\ID2D1BoundsAdjustmentTransform.ahk" {ID2D1BoundsAdjustmentTransform}
#Import export ".\ID2D1Brush.ahk" {ID2D1Brush}
#Import export ".\ID2D1ColorContext.ahk" {ID2D1ColorContext}
#Import export ".\ID2D1ColorContext1.ahk" {ID2D1ColorContext1}
#Import export ".\ID2D1CommandList.ahk" {ID2D1CommandList}
#Import export ".\ID2D1CommandSink.ahk" {ID2D1CommandSink}
#Import export ".\ID2D1CommandSink1.ahk" {ID2D1CommandSink1}
#Import export ".\ID2D1CommandSink2.ahk" {ID2D1CommandSink2}
#Import export ".\ID2D1CommandSink3.ahk" {ID2D1CommandSink3}
#Import export ".\ID2D1CommandSink4.ahk" {ID2D1CommandSink4}
#Import export ".\ID2D1CommandSink5.ahk" {ID2D1CommandSink5}
#Import export ".\ID2D1ComputeInfo.ahk" {ID2D1ComputeInfo}
#Import export ".\ID2D1ComputeTransform.ahk" {ID2D1ComputeTransform}
#Import export ".\ID2D1ConcreteTransform.ahk" {ID2D1ConcreteTransform}
#Import export ".\ID2D1DCRenderTarget.ahk" {ID2D1DCRenderTarget}
#Import export ".\ID2D1Device.ahk" {ID2D1Device}
#Import export ".\ID2D1Device1.ahk" {ID2D1Device1}
#Import export ".\ID2D1Device2.ahk" {ID2D1Device2}
#Import export ".\ID2D1Device3.ahk" {ID2D1Device3}
#Import export ".\ID2D1Device4.ahk" {ID2D1Device4}
#Import export ".\ID2D1Device5.ahk" {ID2D1Device5}
#Import export ".\ID2D1Device6.ahk" {ID2D1Device6}
#Import export ".\ID2D1Device7.ahk" {ID2D1Device7}
#Import export ".\ID2D1DeviceContext.ahk" {ID2D1DeviceContext}
#Import export ".\ID2D1DeviceContext1.ahk" {ID2D1DeviceContext1}
#Import export ".\ID2D1DeviceContext2.ahk" {ID2D1DeviceContext2}
#Import export ".\ID2D1DeviceContext3.ahk" {ID2D1DeviceContext3}
#Import export ".\ID2D1DeviceContext4.ahk" {ID2D1DeviceContext4}
#Import export ".\ID2D1DeviceContext5.ahk" {ID2D1DeviceContext5}
#Import export ".\ID2D1DeviceContext6.ahk" {ID2D1DeviceContext6}
#Import export ".\ID2D1DeviceContext7.ahk" {ID2D1DeviceContext7}
#Import export ".\ID2D1DrawInfo.ahk" {ID2D1DrawInfo}
#Import export ".\ID2D1DrawTransform.ahk" {ID2D1DrawTransform}
#Import export ".\ID2D1DrawingStateBlock.ahk" {ID2D1DrawingStateBlock}
#Import export ".\ID2D1DrawingStateBlock1.ahk" {ID2D1DrawingStateBlock1}
#Import export ".\ID2D1Effect.ahk" {ID2D1Effect}
#Import export ".\ID2D1EffectContext.ahk" {ID2D1EffectContext}
#Import export ".\ID2D1EffectContext1.ahk" {ID2D1EffectContext1}
#Import export ".\ID2D1EffectContext2.ahk" {ID2D1EffectContext2}
#Import export ".\ID2D1EffectImpl.ahk" {ID2D1EffectImpl}
#Import export ".\ID2D1EllipseGeometry.ahk" {ID2D1EllipseGeometry}
#Import export ".\ID2D1Factory.ahk" {ID2D1Factory}
#Import export ".\ID2D1Factory1.ahk" {ID2D1Factory1}
#Import export ".\ID2D1Factory2.ahk" {ID2D1Factory2}
#Import export ".\ID2D1Factory3.ahk" {ID2D1Factory3}
#Import export ".\ID2D1Factory4.ahk" {ID2D1Factory4}
#Import export ".\ID2D1Factory5.ahk" {ID2D1Factory5}
#Import export ".\ID2D1Factory6.ahk" {ID2D1Factory6}
#Import export ".\ID2D1Factory7.ahk" {ID2D1Factory7}
#Import export ".\ID2D1Factory8.ahk" {ID2D1Factory8}
#Import export ".\ID2D1GdiInteropRenderTarget.ahk" {ID2D1GdiInteropRenderTarget}
#Import export ".\ID2D1GdiMetafile.ahk" {ID2D1GdiMetafile}
#Import export ".\ID2D1GdiMetafile1.ahk" {ID2D1GdiMetafile1}
#Import export ".\ID2D1GdiMetafileSink.ahk" {ID2D1GdiMetafileSink}
#Import export ".\ID2D1GdiMetafileSink1.ahk" {ID2D1GdiMetafileSink1}
#Import export ".\ID2D1Geometry.ahk" {ID2D1Geometry}
#Import export ".\ID2D1GeometryGroup.ahk" {ID2D1GeometryGroup}
#Import export ".\ID2D1GeometryRealization.ahk" {ID2D1GeometryRealization}
#Import export ".\ID2D1GeometrySink.ahk" {ID2D1GeometrySink}
#Import export ".\ID2D1GradientMesh.ahk" {ID2D1GradientMesh}
#Import export ".\ID2D1GradientStopCollection.ahk" {ID2D1GradientStopCollection}
#Import export ".\ID2D1GradientStopCollection1.ahk" {ID2D1GradientStopCollection1}
#Import export ".\ID2D1HwndRenderTarget.ahk" {ID2D1HwndRenderTarget}
#Import export ".\ID2D1Image.ahk" {ID2D1Image}
#Import export ".\ID2D1ImageBrush.ahk" {ID2D1ImageBrush}
#Import export ".\ID2D1ImageSource.ahk" {ID2D1ImageSource}
#Import export ".\ID2D1ImageSourceFromWic.ahk" {ID2D1ImageSourceFromWic}
#Import export ".\ID2D1Ink.ahk" {ID2D1Ink}
#Import export ".\ID2D1InkStyle.ahk" {ID2D1InkStyle}
#Import export ".\ID2D1Layer.ahk" {ID2D1Layer}
#Import export ".\ID2D1LinearGradientBrush.ahk" {ID2D1LinearGradientBrush}
#Import export ".\ID2D1LookupTable3D.ahk" {ID2D1LookupTable3D}
#Import export ".\ID2D1Mesh.ahk" {ID2D1Mesh}
#Import export ".\ID2D1Multithread.ahk" {ID2D1Multithread}
#Import export ".\ID2D1OffsetTransform.ahk" {ID2D1OffsetTransform}
#Import export ".\ID2D1PathGeometry.ahk" {ID2D1PathGeometry}
#Import export ".\ID2D1PathGeometry1.ahk" {ID2D1PathGeometry1}
#Import export ".\ID2D1PrintControl.ahk" {ID2D1PrintControl}
#Import export ".\ID2D1Properties.ahk" {ID2D1Properties}
#Import export ".\ID2D1RadialGradientBrush.ahk" {ID2D1RadialGradientBrush}
#Import export ".\ID2D1RectangleGeometry.ahk" {ID2D1RectangleGeometry}
#Import export ".\ID2D1RenderInfo.ahk" {ID2D1RenderInfo}
#Import export ".\ID2D1RenderTarget.ahk" {ID2D1RenderTarget}
#Import export ".\ID2D1Resource.ahk" {ID2D1Resource}
#Import export ".\ID2D1ResourceTexture.ahk" {ID2D1ResourceTexture}
#Import export ".\ID2D1RoundedRectangleGeometry.ahk" {ID2D1RoundedRectangleGeometry}
#Import export ".\ID2D1SolidColorBrush.ahk" {ID2D1SolidColorBrush}
#Import export ".\ID2D1SourceTransform.ahk" {ID2D1SourceTransform}
#Import export ".\ID2D1SpriteBatch.ahk" {ID2D1SpriteBatch}
#Import export ".\ID2D1StrokeStyle.ahk" {ID2D1StrokeStyle}
#Import export ".\ID2D1StrokeStyle1.ahk" {ID2D1StrokeStyle1}
#Import export ".\ID2D1SvgAttribute.ahk" {ID2D1SvgAttribute}
#Import export ".\ID2D1SvgDocument.ahk" {ID2D1SvgDocument}
#Import export ".\ID2D1SvgElement.ahk" {ID2D1SvgElement}
#Import export ".\ID2D1SvgGlyphStyle.ahk" {ID2D1SvgGlyphStyle}
#Import export ".\ID2D1SvgPaint.ahk" {ID2D1SvgPaint}
#Import export ".\ID2D1SvgPathData.ahk" {ID2D1SvgPathData}
#Import export ".\ID2D1SvgPointCollection.ahk" {ID2D1SvgPointCollection}
#Import export ".\ID2D1SvgStrokeDashArray.ahk" {ID2D1SvgStrokeDashArray}
#Import export ".\ID2D1TessellationSink.ahk" {ID2D1TessellationSink}
#Import export ".\ID2D1Transform.ahk" {ID2D1Transform}
#Import export ".\ID2D1TransformGraph.ahk" {ID2D1TransformGraph}
#Import export ".\ID2D1TransformNode.ahk" {ID2D1TransformNode}
#Import export ".\ID2D1TransformedGeometry.ahk" {ID2D1TransformedGeometry}
#Import export ".\ID2D1TransformedImageSource.ahk" {ID2D1TransformedImageSource}
#Import export ".\ID2D1VertexBuffer.ahk" {ID2D1VertexBuffer}
#Import export ".\PD2D1_EFFECT_FACTORY.ahk" {PD2D1_EFFECT_FACTORY}
#Import export ".\PD2D1_PROPERTY_GET_FUNCTION.ahk" {PD2D1_PROPERTY_GET_FUNCTION}
#Import export ".\PD2D1_PROPERTY_SET_FUNCTION.ahk" {PD2D1_PROPERTY_SET_FUNCTION}
