#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ASSEMBLYMETADATA.ahk" {ASSEMBLYMETADATA}
#Import export ".\Apis.ahk" {*}
#Import export ".\COINITICOR.ahk" {COINITICOR}
#Import export ".\COINITIEE.ahk" {COINITIEE}
#Import export ".\COR_FIELD_OFFSET.ahk" {COR_FIELD_OFFSET}
#Import export ".\COR_NATIVE_LINK.ahk" {COR_NATIVE_LINK}
#Import export ".\COR_SECATTR.ahk" {COR_SECATTR}
#Import export ".\COUNINITIEE.ahk" {COUNINITIEE}
#Import export ".\CVStruct.ahk" {CVStruct}
#Import export ".\CeeSectionAttr.ahk" {CeeSectionAttr}
#Import export ".\CeeSectionRelocExtra.ahk" {CeeSectionRelocExtra}
#Import export ".\CeeSectionRelocType.ahk" {CeeSectionRelocType}
#Import export ".\CompilationRelaxationsEnum.ahk" {CompilationRelaxationsEnum}
#Import export ".\Constants.ahk" {*}
#Import export ".\CorArgType.ahk" {CorArgType}
#Import export ".\CorAssemblyFlags.ahk" {CorAssemblyFlags}
#Import export ".\CorAttributeTargets.ahk" {CorAttributeTargets}
#Import export ".\CorCallingConvention.ahk" {CorCallingConvention}
#Import export ".\CorCheckDuplicatesFor.ahk" {CorCheckDuplicatesFor}
#Import export ".\CorDeclSecurity.ahk" {CorDeclSecurity}
#Import export ".\CorElementType.ahk" {CorElementType}
#Import export ".\CorErrorIfEmitOutOfOrder.ahk" {CorErrorIfEmitOutOfOrder}
#Import export ".\CorEventAttr.ahk" {CorEventAttr}
#Import export ".\CorExceptionFlag.ahk" {CorExceptionFlag}
#Import export ".\CorFieldAttr.ahk" {CorFieldAttr}
#Import export ".\CorFileFlags.ahk" {CorFileFlags}
#Import export ".\CorFileMapping.ahk" {CorFileMapping}
#Import export ".\CorGenericParamAttr.ahk" {CorGenericParamAttr}
#Import export ".\CorILMethodFlags.ahk" {CorILMethodFlags}
#Import export ".\CorILMethodSect.ahk" {CorILMethodSect}
#Import export ".\CorImportOptions.ahk" {CorImportOptions}
#Import export ".\CorLinkerOptions.ahk" {CorLinkerOptions}
#Import export ".\CorLocalRefPreservation.ahk" {CorLocalRefPreservation}
#Import export ".\CorManifestResourceFlags.ahk" {CorManifestResourceFlags}
#Import export ".\CorMethodAttr.ahk" {CorMethodAttr}
#Import export ".\CorMethodImpl.ahk" {CorMethodImpl}
#Import export ".\CorMethodSemanticsAttr.ahk" {CorMethodSemanticsAttr}
#Import export ".\CorNativeLinkFlags.ahk" {CorNativeLinkFlags}
#Import export ".\CorNativeLinkType.ahk" {CorNativeLinkType}
#Import export ".\CorNativeType.ahk" {CorNativeType}
#Import export ".\CorNotificationForTokenMovement.ahk" {CorNotificationForTokenMovement}
#Import export ".\CorOpenFlags.ahk" {CorOpenFlags}
#Import export ".\CorPEKind.ahk" {CorPEKind}
#Import export ".\CorParamAttr.ahk" {CorParamAttr}
#Import export ".\CorPinvokeMap.ahk" {CorPinvokeMap}
#Import export ".\CorPropertyAttr.ahk" {CorPropertyAttr}
#Import export ".\CorRefToDefCheck.ahk" {CorRefToDefCheck}
#Import export ".\CorRegFlags.ahk" {CorRegFlags}
#Import export ".\CorSaveSize.ahk" {CorSaveSize}
#Import export ".\CorSerializationType.ahk" {CorSerializationType}
#Import export ".\CorSetENC.ahk" {CorSetENC}
#Import export ".\CorThreadSafetyOptions.ahk" {CorThreadSafetyOptions}
#Import export ".\CorTokenType.ahk" {CorTokenType}
#Import export ".\CorTypeAttr.ahk" {CorTypeAttr}
#Import export ".\CorUnmanagedCallingConvention.ahk" {CorUnmanagedCallingConvention}
#Import export ".\CorValidatorModuleType.ahk" {CorValidatorModuleType}
#Import export ".\ICeeGen.ahk" {ICeeGen}
#Import export ".\IHostFilter.ahk" {IHostFilter}
#Import export ".\IMAGE_COR_ILMETHOD.ahk" {IMAGE_COR_ILMETHOD}
#Import export ".\IMAGE_COR_ILMETHOD_FAT.ahk" {IMAGE_COR_ILMETHOD_FAT}
#Import export ".\IMAGE_COR_ILMETHOD_SECT_EH.ahk" {IMAGE_COR_ILMETHOD_SECT_EH}
#Import export ".\IMAGE_COR_ILMETHOD_SECT_EH_CLAUSE_FAT.ahk" {IMAGE_COR_ILMETHOD_SECT_EH_CLAUSE_FAT}
#Import export ".\IMAGE_COR_ILMETHOD_SECT_EH_CLAUSE_SMALL.ahk" {IMAGE_COR_ILMETHOD_SECT_EH_CLAUSE_SMALL}
#Import export ".\IMAGE_COR_ILMETHOD_SECT_EH_FAT.ahk" {IMAGE_COR_ILMETHOD_SECT_EH_FAT}
#Import export ".\IMAGE_COR_ILMETHOD_SECT_EH_SMALL.ahk" {IMAGE_COR_ILMETHOD_SECT_EH_SMALL}
#Import export ".\IMAGE_COR_ILMETHOD_SECT_FAT.ahk" {IMAGE_COR_ILMETHOD_SECT_FAT}
#Import export ".\IMAGE_COR_ILMETHOD_SECT_SMALL.ahk" {IMAGE_COR_ILMETHOD_SECT_SMALL}
#Import export ".\IMAGE_COR_ILMETHOD_TINY.ahk" {IMAGE_COR_ILMETHOD_TINY}
#Import export ".\IMAGE_COR_VTABLEFIXUP.ahk" {IMAGE_COR_VTABLEFIXUP}
#Import export ".\IMapToken.ahk" {IMapToken}
#Import export ".\IMetaDataAssemblyEmit.ahk" {IMetaDataAssemblyEmit}
#Import export ".\IMetaDataAssemblyImport.ahk" {IMetaDataAssemblyImport}
#Import export ".\IMetaDataDispenser.ahk" {IMetaDataDispenser}
#Import export ".\IMetaDataDispenserEx.ahk" {IMetaDataDispenserEx}
#Import export ".\IMetaDataEmit.ahk" {IMetaDataEmit}
#Import export ".\IMetaDataEmit2.ahk" {IMetaDataEmit2}
#Import export ".\IMetaDataError.ahk" {IMetaDataError}
#Import export ".\IMetaDataFilter.ahk" {IMetaDataFilter}
#Import export ".\IMetaDataImport.ahk" {IMetaDataImport}
#Import export ".\IMetaDataImport2.ahk" {IMetaDataImport2}
#Import export ".\IMetaDataInfo.ahk" {IMetaDataInfo}
#Import export ".\IMetaDataTables.ahk" {IMetaDataTables}
#Import export ".\IMetaDataTables2.ahk" {IMetaDataTables2}
#Import export ".\IMetaDataValidate.ahk" {IMetaDataValidate}
#Import export ".\IMetaDataWinMDImport.ahk" {IMetaDataWinMDImport}
#Import export ".\IRoMetaDataLocator.ahk" {IRoMetaDataLocator}
#Import export ".\IRoSimpleMetaDataBuilder.ahk" {IRoSimpleMetaDataBuilder}
#Import export ".\LoadHintEnum.ahk" {LoadHintEnum}
#Import export ".\MergeFlags.ahk" {MergeFlags}
#Import export ".\NGenHintEnum.ahk" {NGenHintEnum}
#Import export ".\NativeTypeArrayFlags.ahk" {NativeTypeArrayFlags}
#Import export ".\OSINFO.ahk" {OSINFO}
#Import export ".\ROPARAMIIDHANDLE.ahk" {ROPARAMIIDHANDLE}
#Import export ".\ReplacesGeneralNumericDefines.ahk" {ReplacesGeneralNumericDefines}
