#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\SECURE_ELEMENT_PROTO_ROUTING_INFO.ahk" { SECURE_ELEMENT_PROTO_ROUTING_INFO }
#Import ".\SECURE_ELEMENT_ROUTING_TABLE_ENTRY.ahk" { SECURE_ELEMENT_ROUTING_TABLE_ENTRY }
#Import ".\SECURE_ELEMENT_ROUTING_TYPE.ahk" { SECURE_ELEMENT_ROUTING_TYPE }
#Import ".\SECURE_ELEMENT_AID_ROUTING_INFO.ahk" { SECURE_ELEMENT_AID_ROUTING_INFO }
#Import ".\SECURE_ELEMENT_TECH_ROUTING_INFO.ahk" { SECURE_ELEMENT_TECH_ROUTING_INFO }
#Import "..\..\..\..\Guid.ahk" { Guid }

/**
 * @namespace Windows.Win32.Devices.Nfc
 */
export default struct SECURE_ELEMENT_ROUTING_TABLE {
    #StructPack 4

    NumberOfEntries : UInt32

    TableEntries : SECURE_ELEMENT_ROUTING_TABLE_ENTRY[1]

}
