#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ACTCTXA.ahk" {ACTCTXA}
#Import export ".\ACTCTXW.ahk" {ACTCTXW}
#Import export ".\ACTCTX_COMPATIBILITY_ELEMENT_TYPE.ahk" {ACTCTX_COMPATIBILITY_ELEMENT_TYPE}
#Import export ".\ACTCTX_REQUESTED_RUN_LEVEL.ahk" {ACTCTX_REQUESTED_RUN_LEVEL}
#Import export ".\ACTCTX_SECTION_KEYED_DATA.ahk" {ACTCTX_SECTION_KEYED_DATA}
#Import export ".\ACTIVATION_CONTEXT_ASSEMBLY_DETAILED_INFORMATION.ahk" {ACTIVATION_CONTEXT_ASSEMBLY_DETAILED_INFORMATION}
#Import export ".\ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION.ahk" {ACTIVATION_CONTEXT_COMPATIBILITY_INFORMATION}
#Import export ".\ACTIVATION_CONTEXT_DETAILED_INFORMATION.ahk" {ACTIVATION_CONTEXT_DETAILED_INFORMATION}
#Import export ".\ACTIVATION_CONTEXT_QUERY_INDEX.ahk" {ACTIVATION_CONTEXT_QUERY_INDEX}
#Import export ".\ACTIVATION_CONTEXT_RUN_LEVEL_INFORMATION.ahk" {ACTIVATION_CONTEXT_RUN_LEVEL_INFORMATION}
#Import export ".\ADVERTISEFLAGS.ahk" {ADVERTISEFLAGS}
#Import export ".\ASM_BIND_FLAGS.ahk" {ASM_BIND_FLAGS}
#Import export ".\ASM_CMP_FLAGS.ahk" {ASM_CMP_FLAGS}
#Import export ".\ASM_DISPLAY_FLAGS.ahk" {ASM_DISPLAY_FLAGS}
#Import export ".\ASM_NAME.ahk" {ASM_NAME}
#Import export ".\ASSEMBLY_FILE_DETAILED_INFORMATION.ahk" {ASSEMBLY_FILE_DETAILED_INFORMATION}
#Import export ".\ASSEMBLY_INFO.ahk" {ASSEMBLY_INFO}
#Import export ".\Apis.ahk" {*}
#Import export ".\COMPATIBILITY_CONTEXT_ELEMENT.ahk" {COMPATIBILITY_CONTEXT_ELEMENT}
#Import export ".\CREATE_ASM_NAME_OBJ_FLAGS.ahk" {CREATE_ASM_NAME_OBJ_FLAGS}
#Import export ".\Constants.ahk" {*}
#Import export ".\DELTA_HASH.ahk" {DELTA_HASH}
#Import export ".\DELTA_HEADER_INFO.ahk" {DELTA_HEADER_INFO}
#Import export ".\DELTA_INPUT.ahk" {DELTA_INPUT}
#Import export ".\DELTA_OUTPUT.ahk" {DELTA_OUTPUT}
#Import export ".\FUSION_INSTALL_REFERENCE.ahk" {FUSION_INSTALL_REFERENCE}
#Import export ".\IASSEMBLYCACHE_UNINSTALL_DISPOSITION.ahk" {IASSEMBLYCACHE_UNINSTALL_DISPOSITION}
#Import export ".\IAssemblyCache.ahk" {IAssemblyCache}
#Import export ".\IAssemblyCacheItem.ahk" {IAssemblyCacheItem}
#Import export ".\IAssemblyName.ahk" {IAssemblyName}
#Import export ".\IEnumMsmDependency.ahk" {IEnumMsmDependency}
#Import export ".\IEnumMsmError.ahk" {IEnumMsmError}
#Import export ".\IEnumMsmString.ahk" {IEnumMsmString}
#Import export ".\IMsmDependencies.ahk" {IMsmDependencies}
#Import export ".\IMsmDependency.ahk" {IMsmDependency}
#Import export ".\IMsmError.ahk" {IMsmError}
#Import export ".\IMsmErrors.ahk" {IMsmErrors}
#Import export ".\IMsmGetFiles.ahk" {IMsmGetFiles}
#Import export ".\IMsmMerge.ahk" {IMsmMerge}
#Import export ".\IMsmStrings.ahk" {IMsmStrings}
#Import export ".\INSTALLFEATUREATTRIBUTE.ahk" {INSTALLFEATUREATTRIBUTE}
#Import export ".\INSTALLLEVEL.ahk" {INSTALLLEVEL}
#Import export ".\INSTALLLOGATTRIBUTES.ahk" {INSTALLLOGATTRIBUTES}
#Import export ".\INSTALLLOGMODE.ahk" {INSTALLLOGMODE}
#Import export ".\INSTALLMESSAGE.ahk" {INSTALLMESSAGE}
#Import export ".\INSTALLMODE.ahk" {INSTALLMODE}
#Import export ".\INSTALLSTATE.ahk" {INSTALLSTATE}
#Import export ".\INSTALLTYPE.ahk" {INSTALLTYPE}
#Import export ".\INSTALLUILEVEL.ahk" {INSTALLUILEVEL}
#Import export ".\INSTALLUI_HANDLERA.ahk" {INSTALLUI_HANDLERA}
#Import export ".\INSTALLUI_HANDLERW.ahk" {INSTALLUI_HANDLERW}
#Import export ".\IPMApplicationInfo.ahk" {IPMApplicationInfo}
#Import export ".\IPMApplicationInfoEnumerator.ahk" {IPMApplicationInfoEnumerator}
#Import export ".\IPMBackgroundServiceAgentInfo.ahk" {IPMBackgroundServiceAgentInfo}
#Import export ".\IPMBackgroundServiceAgentInfoEnumerator.ahk" {IPMBackgroundServiceAgentInfoEnumerator}
#Import export ".\IPMBackgroundWorkerInfo.ahk" {IPMBackgroundWorkerInfo}
#Import export ".\IPMBackgroundWorkerInfoEnumerator.ahk" {IPMBackgroundWorkerInfoEnumerator}
#Import export ".\IPMDeploymentManager.ahk" {IPMDeploymentManager}
#Import export ".\IPMEnumerationManager.ahk" {IPMEnumerationManager}
#Import export ".\IPMExtensionCachedFileUpdaterInfo.ahk" {IPMExtensionCachedFileUpdaterInfo}
#Import export ".\IPMExtensionContractInfo.ahk" {IPMExtensionContractInfo}
#Import export ".\IPMExtensionFileExtensionInfo.ahk" {IPMExtensionFileExtensionInfo}
#Import export ".\IPMExtensionFileOpenPickerInfo.ahk" {IPMExtensionFileOpenPickerInfo}
#Import export ".\IPMExtensionFileSavePickerInfo.ahk" {IPMExtensionFileSavePickerInfo}
#Import export ".\IPMExtensionInfo.ahk" {IPMExtensionInfo}
#Import export ".\IPMExtensionInfoEnumerator.ahk" {IPMExtensionInfoEnumerator}
#Import export ".\IPMExtensionProtocolInfo.ahk" {IPMExtensionProtocolInfo}
#Import export ".\IPMExtensionShareTargetInfo.ahk" {IPMExtensionShareTargetInfo}
#Import export ".\IPMLiveTileJobInfo.ahk" {IPMLiveTileJobInfo}
#Import export ".\IPMLiveTileJobInfoEnumerator.ahk" {IPMLiveTileJobInfoEnumerator}
#Import export ".\IPMTaskInfo.ahk" {IPMTaskInfo}
#Import export ".\IPMTaskInfoEnumerator.ahk" {IPMTaskInfoEnumerator}
#Import export ".\IPMTileInfo.ahk" {IPMTileInfo}
#Import export ".\IPMTileInfoEnumerator.ahk" {IPMTileInfoEnumerator}
#Import export ".\IPMTilePropertyEnumerator.ahk" {IPMTilePropertyEnumerator}
#Import export ".\IPMTilePropertyInfo.ahk" {IPMTilePropertyInfo}
#Import export ".\IValidate.ahk" {IValidate}
#Import export ".\LPDISPLAYVAL.ahk" {LPDISPLAYVAL}
#Import export ".\LPEVALCOMCALLBACK.ahk" {LPEVALCOMCALLBACK}
#Import export ".\MSIADVERTISEOPTIONFLAGS.ahk" {MSIADVERTISEOPTIONFLAGS}
#Import export ".\MSIARCHITECTUREFLAGS.ahk" {MSIARCHITECTUREFLAGS}
#Import export ".\MSIASSEMBLYINFO.ahk" {MSIASSEMBLYINFO}
#Import export ".\MSICODE.ahk" {MSICODE}
#Import export ".\MSICOLINFO.ahk" {MSICOLINFO}
#Import export ".\MSICONDITION.ahk" {MSICONDITION}
#Import export ".\MSICOSTTREE.ahk" {MSICOSTTREE}
#Import export ".\MSIDBERROR.ahk" {MSIDBERROR}
#Import export ".\MSIDBSTATE.ahk" {MSIDBSTATE}
#Import export ".\MSIFILEHASHINFO.ahk" {MSIFILEHASHINFO}
#Import export ".\MSIHANDLE.ahk" {MSIHANDLE}
#Import export ".\MSIINSTALLCONTEXT.ahk" {MSIINSTALLCONTEXT}
#Import export ".\MSIMODIFY.ahk" {MSIMODIFY}
#Import export ".\MSIOPENPACKAGEFLAGS.ahk" {MSIOPENPACKAGEFLAGS}
#Import export ".\MSIPATCHDATATYPE.ahk" {MSIPATCHDATATYPE}
#Import export ".\MSIPATCHSEQUENCEINFOA.ahk" {MSIPATCHSEQUENCEINFOA}
#Import export ".\MSIPATCHSEQUENCEINFOW.ahk" {MSIPATCHSEQUENCEINFOW}
#Import export ".\MSIPATCHSTATE.ahk" {MSIPATCHSTATE}
#Import export ".\MSIRUNMODE.ahk" {MSIRUNMODE}
#Import export ".\MSISOURCETYPE.ahk" {MSISOURCETYPE}
#Import export ".\MSITRANSACTION.ahk" {MSITRANSACTION}
#Import export ".\MSITRANSACTIONSTATE.ahk" {MSITRANSACTIONSTATE}
#Import export ".\MSITRANSFORM_ERROR.ahk" {MSITRANSFORM_ERROR}
#Import export ".\MSITRANSFORM_VALIDATE.ahk" {MSITRANSFORM_VALIDATE}
#Import export ".\MsmMerge.ahk" {MsmMerge}
#Import export ".\PACKMAN_RUNTIME.ahk" {PACKMAN_RUNTIME}
#Import export ".\PATCH_IGNORE_RANGE.ahk" {PATCH_IGNORE_RANGE}
#Import export ".\PATCH_INTERLEAVE_MAP.ahk" {PATCH_INTERLEAVE_MAP}
#Import export ".\PATCH_OLD_FILE_INFO.ahk" {PATCH_OLD_FILE_INFO}
#Import export ".\PATCH_OLD_FILE_INFO_A.ahk" {PATCH_OLD_FILE_INFO_A}
#Import export ".\PATCH_OLD_FILE_INFO_H.ahk" {PATCH_OLD_FILE_INFO_H}
#Import export ".\PATCH_OLD_FILE_INFO_W.ahk" {PATCH_OLD_FILE_INFO_W}
#Import export ".\PATCH_OPTION_DATA.ahk" {PATCH_OPTION_DATA}
#Import export ".\PATCH_RETAIN_RANGE.ahk" {PATCH_RETAIN_RANGE}
#Import export ".\PINSTALLUI_HANDLER_RECORD.ahk" {PINSTALLUI_HANDLER_RECORD}
#Import export ".\PMSIHANDLE.ahk" {PMSIHANDLE}
#Import export ".\PMSvc.ahk" {PMSvc}
#Import export ".\PM_ACTIVATION_POLICY.ahk" {PM_ACTIVATION_POLICY}
#Import export ".\PM_APPLICATION_HUBTYPE.ahk" {PM_APPLICATION_HUBTYPE}
#Import export ".\PM_APPLICATION_INSTALL_TYPE.ahk" {PM_APPLICATION_INSTALL_TYPE}
#Import export ".\PM_APPLICATION_STATE.ahk" {PM_APPLICATION_STATE}
#Import export ".\PM_APPTASKTYPE.ahk" {PM_APPTASKTYPE}
#Import export ".\PM_APP_GENRE.ahk" {PM_APP_GENRE}
#Import export ".\PM_BSATASKID.ahk" {PM_BSATASKID}
#Import export ".\PM_BWTASKID.ahk" {PM_BWTASKID}
#Import export ".\PM_ENUM_APP_FILTER.ahk" {PM_ENUM_APP_FILTER}
#Import export ".\PM_ENUM_BSA_FILTER.ahk" {PM_ENUM_BSA_FILTER}
#Import export ".\PM_ENUM_BW_FILTER.ahk" {PM_ENUM_BW_FILTER}
#Import export ".\PM_ENUM_EXTENSION_FILTER.ahk" {PM_ENUM_EXTENSION_FILTER}
#Import export ".\PM_ENUM_FILTER.ahk" {PM_ENUM_FILTER}
#Import export ".\PM_ENUM_TASK_FILTER.ahk" {PM_ENUM_TASK_FILTER}
#Import export ".\PM_ENUM_TILE_FILTER.ahk" {PM_ENUM_TILE_FILTER}
#Import export ".\PM_EXTENSIONCONSUMER.ahk" {PM_EXTENSIONCONSUMER}
#Import export ".\PM_INSTALLINFO.ahk" {PM_INSTALLINFO}
#Import export ".\PM_INVOCATIONINFO.ahk" {PM_INVOCATIONINFO}
#Import export ".\PM_LIVETILE_RECURRENCE_TYPE.ahk" {PM_LIVETILE_RECURRENCE_TYPE}
#Import export ".\PM_LOGO_SIZE.ahk" {PM_LOGO_SIZE}
#Import export ".\PM_STARTAPPBLOB.ahk" {PM_STARTAPPBLOB}
#Import export ".\PM_STARTTILEBLOB.ahk" {PM_STARTTILEBLOB}
#Import export ".\PM_STARTTILE_TYPE.ahk" {PM_STARTTILE_TYPE}
#Import export ".\PM_TASK_TRANSITION.ahk" {PM_TASK_TRANSITION}
#Import export ".\PM_TASK_TYPE.ahk" {PM_TASK_TYPE}
#Import export ".\PM_TILE_HUBTYPE.ahk" {PM_TILE_HUBTYPE}
#Import export ".\PM_TILE_SIZE.ahk" {PM_TILE_SIZE}
#Import export ".\PM_UPDATEINFO.ahk" {PM_UPDATEINFO}
#Import export ".\PM_UPDATEINFO_LEGACY.ahk" {PM_UPDATEINFO_LEGACY}
#Import export ".\PPATCH_PROGRESS_CALLBACK.ahk" {PPATCH_PROGRESS_CALLBACK}
#Import export ".\PPATCH_SYMLOAD_CALLBACK.ahk" {PPATCH_SYMLOAD_CALLBACK}
#Import export ".\PROTECTED_FILE_DATA.ahk" {PROTECTED_FILE_DATA}
#Import export ".\QUERYASMINFO_FLAGS.ahk" {QUERYASMINFO_FLAGS}
#Import export ".\REINSTALLMODE.ahk" {REINSTALLMODE}
#Import export ".\RESULTTYPES.ahk" {RESULTTYPES}
#Import export ".\SCRIPTFLAGS.ahk" {SCRIPTFLAGS}
#Import export ".\STATUSTYPES.ahk" {STATUSTYPES}
#Import export ".\TILE_TEMPLATE_TYPE.ahk" {TILE_TEMPLATE_TYPE}
#Import export ".\USERINFOSTATE.ahk" {USERINFOSTATE}
#Import export ".\msidbAssemblyAttributes.ahk" {msidbAssemblyAttributes}
#Import export ".\msidbClassAttributes.ahk" {msidbClassAttributes}
#Import export ".\msidbComponentAttributes.ahk" {msidbComponentAttributes}
#Import export ".\msidbControlAttributes.ahk" {msidbControlAttributes}
#Import export ".\msidbCustomActionType.ahk" {msidbCustomActionType}
#Import export ".\msidbDialogAttributes.ahk" {msidbDialogAttributes}
#Import export ".\msidbEmbeddedUIAttributes.ahk" {msidbEmbeddedUIAttributes}
#Import export ".\msidbFeatureAttributes.ahk" {msidbFeatureAttributes}
#Import export ".\msidbFileAttributes.ahk" {msidbFileAttributes}
#Import export ".\msidbIniFileAction.ahk" {msidbIniFileAction}
#Import export ".\msidbLocatorType.ahk" {msidbLocatorType}
#Import export ".\msidbMoveFileOptions.ahk" {msidbMoveFileOptions}
#Import export ".\msidbODBCDataSourceRegistration.ahk" {msidbODBCDataSourceRegistration}
#Import export ".\msidbPatchAttributes.ahk" {msidbPatchAttributes}
#Import export ".\msidbRegistryRoot.ahk" {msidbRegistryRoot}
#Import export ".\msidbRemoveFileInstallMode.ahk" {msidbRemoveFileInstallMode}
#Import export ".\msidbServiceConfigEvent.ahk" {msidbServiceConfigEvent}
#Import export ".\msidbServiceControlEvent.ahk" {msidbServiceControlEvent}
#Import export ".\msidbServiceInstallErrorControl.ahk" {msidbServiceInstallErrorControl}
#Import export ".\msidbSumInfoSourceType.ahk" {msidbSumInfoSourceType}
#Import export ".\msidbTextStyleStyleBits.ahk" {msidbTextStyleStyleBits}
#Import export ".\msidbUpgradeAttributes.ahk" {msidbUpgradeAttributes}
#Import export ".\msifiFastInstallBits.ahk" {msifiFastInstallBits}
#Import export ".\msirbRebootReason.ahk" {msirbRebootReason}
#Import export ".\msirbRebootType.ahk" {msirbRebootType}
#Import export ".\msmErrorType.ahk" {msmErrorType}
