#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\DOT11EXTIHV_ADAPTER_RESET.ahk" { DOT11EXTIHV_ADAPTER_RESET }
#Import ".\DOT11EXTIHV_CONTROL.ahk" { DOT11EXTIHV_CONTROL }
#Import ".\DOT11EXTIHV_CREATE_DISCOVERY_PROFILES.ahk" { DOT11EXTIHV_CREATE_DISCOVERY_PROFILES }
#Import ".\DOT11EXTIHV_DEINIT_ADAPTER.ahk" { DOT11EXTIHV_DEINIT_ADAPTER }
#Import ".\DOT11EXTIHV_DEINIT_SERVICE.ahk" { DOT11EXTIHV_DEINIT_SERVICE }
#Import ".\DOT11EXTIHV_INIT_ADAPTER.ahk" { DOT11EXTIHV_INIT_ADAPTER }
#Import ".\DOT11EXTIHV_IS_UI_REQUEST_PENDING.ahk" { DOT11EXTIHV_IS_UI_REQUEST_PENDING }
#Import ".\DOT11EXTIHV_ONEX_INDICATE_RESULT.ahk" { DOT11EXTIHV_ONEX_INDICATE_RESULT }
#Import ".\DOT11EXTIHV_PERFORM_CAPABILITY_MATCH.ahk" { DOT11EXTIHV_PERFORM_CAPABILITY_MATCH }
#Import ".\DOT11EXTIHV_PERFORM_POST_ASSOCIATE.ahk" { DOT11EXTIHV_PERFORM_POST_ASSOCIATE }
#Import ".\DOT11EXTIHV_PERFORM_PRE_ASSOCIATE.ahk" { DOT11EXTIHV_PERFORM_PRE_ASSOCIATE }
#Import ".\DOT11EXTIHV_PROCESS_SESSION_CHANGE.ahk" { DOT11EXTIHV_PROCESS_SESSION_CHANGE }
#Import ".\DOT11EXTIHV_PROCESS_UI_RESPONSE.ahk" { DOT11EXTIHV_PROCESS_UI_RESPONSE }
#Import ".\DOT11EXTIHV_QUERY_UI_REQUEST.ahk" { DOT11EXTIHV_QUERY_UI_REQUEST }
#Import ".\DOT11EXTIHV_RECEIVE_INDICATION.ahk" { DOT11EXTIHV_RECEIVE_INDICATION }
#Import ".\DOT11EXTIHV_RECEIVE_PACKET.ahk" { DOT11EXTIHV_RECEIVE_PACKET }
#Import ".\DOT11EXTIHV_SEND_PACKET_COMPLETION.ahk" { DOT11EXTIHV_SEND_PACKET_COMPLETION }
#Import ".\DOT11EXTIHV_STOP_POST_ASSOCIATE.ahk" { DOT11EXTIHV_STOP_POST_ASSOCIATE }
#Import ".\DOT11EXTIHV_VALIDATE_PROFILE.ahk" { DOT11EXTIHV_VALIDATE_PROFILE }

/**
 * @namespace Windows.Win32.NetworkManagement.WiFi
 */
export default struct DOT11EXT_IHV_HANDLERS {
    #StructPack 8

    Dot11ExtIhvDeinitService : DOT11EXTIHV_DEINIT_SERVICE

    Dot11ExtIhvInitAdapter : DOT11EXTIHV_INIT_ADAPTER

    Dot11ExtIhvDeinitAdapter : DOT11EXTIHV_DEINIT_ADAPTER

    Dot11ExtIhvPerformPreAssociate : DOT11EXTIHV_PERFORM_PRE_ASSOCIATE

    Dot11ExtIhvAdapterReset : DOT11EXTIHV_ADAPTER_RESET

    Dot11ExtIhvPerformPostAssociate : DOT11EXTIHV_PERFORM_POST_ASSOCIATE

    Dot11ExtIhvStopPostAssociate : DOT11EXTIHV_STOP_POST_ASSOCIATE

    Dot11ExtIhvValidateProfile : DOT11EXTIHV_VALIDATE_PROFILE

    Dot11ExtIhvPerformCapabilityMatch : DOT11EXTIHV_PERFORM_CAPABILITY_MATCH

    Dot11ExtIhvCreateDiscoveryProfiles : DOT11EXTIHV_CREATE_DISCOVERY_PROFILES

    Dot11ExtIhvProcessSessionChange : DOT11EXTIHV_PROCESS_SESSION_CHANGE

    Dot11ExtIhvReceiveIndication : DOT11EXTIHV_RECEIVE_INDICATION

    Dot11ExtIhvReceivePacket : DOT11EXTIHV_RECEIVE_PACKET

    Dot11ExtIhvSendPacketCompletion : DOT11EXTIHV_SEND_PACKET_COMPLETION

    Dot11ExtIhvIsUIRequestPending : DOT11EXTIHV_IS_UI_REQUEST_PENDING

    Dot11ExtIhvProcessUIResponse : DOT11EXTIHV_PROCESS_UI_RESPONSE

    Dot11ExtIhvQueryUIRequest : DOT11EXTIHV_QUERY_UI_REQUEST

    Dot11ExtIhvOnexIndicateResult : DOT11EXTIHV_ONEX_INDICATE_RESULT

    Dot11ExtIhvControl : DOT11EXTIHV_CONTROL

}
