#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\LPD3DHAL_CLEARCB.ahk" { LPD3DHAL_CLEARCB }
#Import ".\LPD3DHAL_DRAWPRIMITIVESCB.ahk" { LPD3DHAL_DRAWPRIMITIVESCB }
#Import ".\LPD3DHAL_DRAWONEINDEXEDPRIMITIVECB.ahk" { LPD3DHAL_DRAWONEINDEXEDPRIMITIVECB }
#Import ".\LPD3DHAL_DRAWONEPRIMITIVECB.ahk" { LPD3DHAL_DRAWONEPRIMITIVECB }
#Import ".\LPD3DHAL_SETRENDERTARGETCB.ahk" { LPD3DHAL_SETRENDERTARGETCB }

/**
 * @namespace Windows.Wdk.Graphics.Direct3D
 */
export default struct D3DHAL_CALLBACKS2 {
    #StructPack 8

    dwSize : UInt32

    dwFlags : UInt32

    SetRenderTarget : LPD3DHAL_SETRENDERTARGETCB

    Clear : LPD3DHAL_CLEARCB

    DrawOnePrimitive : LPD3DHAL_DRAWONEPRIMITIVECB

    DrawOneIndexedPrimitive : LPD3DHAL_DRAWONEINDEXEDPRIMITIVECB

    DrawPrimitives : LPD3DHAL_DRAWPRIMITIVESCB

}
