#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3DKMDT_GRAPHICS_PREEMPTION_GRANULARITY.ahk" { D3DKMDT_GRAPHICS_PREEMPTION_GRANULARITY }
#Import ".\D3DKMDT_COMPUTE_PREEMPTION_GRANULARITY.ahk" { D3DKMDT_COMPUTE_PREEMPTION_GRANULARITY }

/**
 * @namespace Windows.Wdk.Graphics.Direct3D
 */
export default struct D3DKMDT_PREEMPTION_CAPS {
    #StructPack 4

    GraphicsPreemptionGranularity : D3DKMDT_GRAPHICS_PREEMPTION_GRANULARITY

    ComputePreemptionGranularity : D3DKMDT_COMPUTE_PREEMPTION_GRANULARITY

}
