#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3DDDI_ROTATION.ahk" { D3DDDI_ROTATION }
#Import ".\DXGKMT_MULTIPLANE_OVERLAY_STEREO_FLIP_MODE.ahk" { DXGKMT_MULTIPLANE_OVERLAY_STEREO_FLIP_MODE }
#Import ".\D3DKMT_MULTIPLANE_OVERLAY_STEREO_FORMAT.ahk" { D3DKMT_MULTIPLANE_OVERLAY_STEREO_FORMAT }
#Import ".\D3DKMT_MULTIPLANE_OVERLAY_BLEND.ahk" { D3DKMT_MULTIPLANE_OVERLAY_BLEND }
#Import "..\..\..\Win32\Foundation\RECT.ahk" { RECT }
#Import "..\..\..\Win32\Foundation\BOOL.ahk" { BOOL }
#Import ".\DXGKMT_MULTIPLANE_OVERLAY_STRETCH_QUALITY.ahk" { DXGKMT_MULTIPLANE_OVERLAY_STRETCH_QUALITY }
#Import ".\D3DKMT_MULTIPLANE_OVERLAY_VIDEO_FRAME_FORMAT.ahk" { D3DKMT_MULTIPLANE_OVERLAY_VIDEO_FRAME_FORMAT }

/**
 * @namespace Windows.Wdk.Graphics.Direct3D
 */
export default struct D3DKMT_MULTIPLANE_OVERLAY_ATTRIBUTES {
    #StructPack 8

    Flags : UInt32

    SrcRect : IntPtr

    DstRect : IntPtr

    ClipRect : IntPtr

    Rotation : D3DDDI_ROTATION

    Blend : D3DKMT_MULTIPLANE_OVERLAY_BLEND

    DirtyRectCount : UInt32

    pDirtyRects : RECT.Ptr

    VideoFrameFormat : D3DKMT_MULTIPLANE_OVERLAY_VIDEO_FRAME_FORMAT

    YCbCrFlags : UInt32

    StereoFormat : D3DKMT_MULTIPLANE_OVERLAY_STEREO_FORMAT

    StereoLeftViewFrame0 : BOOL

    StereoBaseViewFrame0 : BOOL

    StereoFlipMode : DXGKMT_MULTIPLANE_OVERLAY_STEREO_FLIP_MODE

    StretchQuality : DXGKMT_MULTIPLANE_OVERLAY_STRETCH_QUALITY

}
