#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\CPU_ARCHITECTURE.ahk" {CPU_ARCHITECTURE}
#Import export ".\Constants.ahk" {*}
#Import export ".\IWdsTransportCacheable.ahk" {IWdsTransportCacheable}
#Import export ".\IWdsTransportClient.ahk" {IWdsTransportClient}
#Import export ".\IWdsTransportCollection.ahk" {IWdsTransportCollection}
#Import export ".\IWdsTransportConfigurationManager.ahk" {IWdsTransportConfigurationManager}
#Import export ".\IWdsTransportConfigurationManager2.ahk" {IWdsTransportConfigurationManager2}
#Import export ".\IWdsTransportContent.ahk" {IWdsTransportContent}
#Import export ".\IWdsTransportContentProvider.ahk" {IWdsTransportContentProvider}
#Import export ".\IWdsTransportDiagnosticsPolicy.ahk" {IWdsTransportDiagnosticsPolicy}
#Import export ".\IWdsTransportManager.ahk" {IWdsTransportManager}
#Import export ".\IWdsTransportMulticastSessionPolicy.ahk" {IWdsTransportMulticastSessionPolicy}
#Import export ".\IWdsTransportNamespace.ahk" {IWdsTransportNamespace}
#Import export ".\IWdsTransportNamespaceAutoCast.ahk" {IWdsTransportNamespaceAutoCast}
#Import export ".\IWdsTransportNamespaceManager.ahk" {IWdsTransportNamespaceManager}
#Import export ".\IWdsTransportNamespaceScheduledCast.ahk" {IWdsTransportNamespaceScheduledCast}
#Import export ".\IWdsTransportNamespaceScheduledCastAutoStart.ahk" {IWdsTransportNamespaceScheduledCastAutoStart}
#Import export ".\IWdsTransportNamespaceScheduledCastManualStart.ahk" {IWdsTransportNamespaceScheduledCastManualStart}
#Import export ".\IWdsTransportServer.ahk" {IWdsTransportServer}
#Import export ".\IWdsTransportServer2.ahk" {IWdsTransportServer2}
#Import export ".\IWdsTransportServicePolicy.ahk" {IWdsTransportServicePolicy}
#Import export ".\IWdsTransportServicePolicy2.ahk" {IWdsTransportServicePolicy2}
#Import export ".\IWdsTransportSession.ahk" {IWdsTransportSession}
#Import export ".\IWdsTransportSetupManager.ahk" {IWdsTransportSetupManager}
#Import export ".\IWdsTransportSetupManager2.ahk" {IWdsTransportSetupManager2}
#Import export ".\IWdsTransportTftpClient.ahk" {IWdsTransportTftpClient}
#Import export ".\IWdsTransportTftpManager.ahk" {IWdsTransportTftpManager}
#Import export ".\PFN_WDS_CLI_CALLBACK_MESSAGE_ID.ahk" {PFN_WDS_CLI_CALLBACK_MESSAGE_ID}
#Import export ".\PFN_WdsCliCallback.ahk" {PFN_WdsCliCallback}
#Import export ".\PFN_WdsCliTraceFunction.ahk" {PFN_WdsCliTraceFunction}
#Import export ".\PFN_WdsTransportClientReceiveContents.ahk" {PFN_WdsTransportClientReceiveContents}
#Import export ".\PFN_WdsTransportClientReceiveMetadata.ahk" {PFN_WdsTransportClientReceiveMetadata}
#Import export ".\PFN_WdsTransportClientSessionComplete.ahk" {PFN_WdsTransportClientSessionComplete}
#Import export ".\PFN_WdsTransportClientSessionNegotiate.ahk" {PFN_WdsTransportClientSessionNegotiate}
#Import export ".\PFN_WdsTransportClientSessionStart.ahk" {PFN_WdsTransportClientSessionStart}
#Import export ".\PFN_WdsTransportClientSessionStartEx.ahk" {PFN_WdsTransportClientSessionStartEx}
#Import export ".\PXE_ADDRESS.ahk" {PXE_ADDRESS}
#Import export ".\PXE_DHCPV6_MESSAGE.ahk" {PXE_DHCPV6_MESSAGE}
#Import export ".\PXE_DHCPV6_MESSAGE_HEADER.ahk" {PXE_DHCPV6_MESSAGE_HEADER}
#Import export ".\PXE_DHCPV6_NESTED_RELAY_MESSAGE.ahk" {PXE_DHCPV6_NESTED_RELAY_MESSAGE}
#Import export ".\PXE_DHCPV6_OPTION.ahk" {PXE_DHCPV6_OPTION}
#Import export ".\PXE_DHCPV6_RELAY_MESSAGE.ahk" {PXE_DHCPV6_RELAY_MESSAGE}
#Import export ".\PXE_DHCP_MESSAGE.ahk" {PXE_DHCP_MESSAGE}
#Import export ".\PXE_DHCP_OPTION.ahk" {PXE_DHCP_OPTION}
#Import export ".\PXE_PROVIDER.ahk" {PXE_PROVIDER}
#Import export ".\TRANSPORTCLIENT_CALLBACK_ID.ahk" {TRANSPORTCLIENT_CALLBACK_ID}
#Import export ".\TRANSPORTCLIENT_SESSION_INFO.ahk" {TRANSPORTCLIENT_SESSION_INFO}
#Import export ".\TRANSPORTPROVIDER_CALLBACK_ID.ahk" {TRANSPORTPROVIDER_CALLBACK_ID}
#Import export ".\WDSTRANSPORT_DIAGNOSTICS_COMPONENT_FLAGS.ahk" {WDSTRANSPORT_DIAGNOSTICS_COMPONENT_FLAGS}
#Import export ".\WDSTRANSPORT_DISCONNECT_TYPE.ahk" {WDSTRANSPORT_DISCONNECT_TYPE}
#Import export ".\WDSTRANSPORT_FEATURE_FLAGS.ahk" {WDSTRANSPORT_FEATURE_FLAGS}
#Import export ".\WDSTRANSPORT_IP_ADDRESS_SOURCE_TYPE.ahk" {WDSTRANSPORT_IP_ADDRESS_SOURCE_TYPE}
#Import export ".\WDSTRANSPORT_IP_ADDRESS_TYPE.ahk" {WDSTRANSPORT_IP_ADDRESS_TYPE}
#Import export ".\WDSTRANSPORT_NAMESPACE_TYPE.ahk" {WDSTRANSPORT_NAMESPACE_TYPE}
#Import export ".\WDSTRANSPORT_NETWORK_PROFILE_TYPE.ahk" {WDSTRANSPORT_NETWORK_PROFILE_TYPE}
#Import export ".\WDSTRANSPORT_PROTOCOL_FLAGS.ahk" {WDSTRANSPORT_PROTOCOL_FLAGS}
#Import export ".\WDSTRANSPORT_SERVICE_NOTIFICATION.ahk" {WDSTRANSPORT_SERVICE_NOTIFICATION}
#Import export ".\WDSTRANSPORT_SLOW_CLIENT_HANDLING_TYPE.ahk" {WDSTRANSPORT_SLOW_CLIENT_HANDLING_TYPE}
#Import export ".\WDSTRANSPORT_TFTP_CAPABILITY.ahk" {WDSTRANSPORT_TFTP_CAPABILITY}
#Import export ".\WDSTRANSPORT_UDP_PORT_POLICY.ahk" {WDSTRANSPORT_UDP_PORT_POLICY}
#Import export ".\WDS_CLI_CRED.ahk" {WDS_CLI_CRED}
#Import export ".\WDS_CLI_FIRMWARE_TYPE.ahk" {WDS_CLI_FIRMWARE_TYPE}
#Import export ".\WDS_CLI_IMAGE_PARAM_TYPE.ahk" {WDS_CLI_IMAGE_PARAM_TYPE}
#Import export ".\WDS_CLI_IMAGE_TYPE.ahk" {WDS_CLI_IMAGE_TYPE}
#Import export ".\WDS_TRANSPORTCLIENT_CALLBACKS.ahk" {WDS_TRANSPORTCLIENT_CALLBACKS}
#Import export ".\WDS_TRANSPORTCLIENT_REQUEST.ahk" {WDS_TRANSPORTCLIENT_REQUEST}
#Import export ".\WDS_TRANSPORTCLIENT_REQUEST_AUTH_LEVEL.ahk" {WDS_TRANSPORTCLIENT_REQUEST_AUTH_LEVEL}
#Import export ".\WDS_TRANSPORTPROVIDER_INIT_PARAMS.ahk" {WDS_TRANSPORTPROVIDER_INIT_PARAMS}
#Import export ".\WDS_TRANSPORTPROVIDER_SETTINGS.ahk" {WDS_TRANSPORTPROVIDER_SETTINGS}
#Import export ".\WdsTransportCacheable.ahk" {WdsTransportCacheable}
#Import export ".\WdsTransportClient.ahk" {WdsTransportClient}
#Import export ".\WdsTransportCollection.ahk" {WdsTransportCollection}
#Import export ".\WdsTransportConfigurationManager.ahk" {WdsTransportConfigurationManager}
#Import export ".\WdsTransportContent.ahk" {WdsTransportContent}
#Import export ".\WdsTransportContentProvider.ahk" {WdsTransportContentProvider}
#Import export ".\WdsTransportDiagnosticsPolicy.ahk" {WdsTransportDiagnosticsPolicy}
#Import export ".\WdsTransportManager.ahk" {WdsTransportManager}
#Import export ".\WdsTransportMulticastSessionPolicy.ahk" {WdsTransportMulticastSessionPolicy}
#Import export ".\WdsTransportNamespace.ahk" {WdsTransportNamespace}
#Import export ".\WdsTransportNamespaceAutoCast.ahk" {WdsTransportNamespaceAutoCast}
#Import export ".\WdsTransportNamespaceManager.ahk" {WdsTransportNamespaceManager}
#Import export ".\WdsTransportNamespaceScheduledCast.ahk" {WdsTransportNamespaceScheduledCast}
#Import export ".\WdsTransportNamespaceScheduledCastAutoStart.ahk" {WdsTransportNamespaceScheduledCastAutoStart}
#Import export ".\WdsTransportNamespaceScheduledCastManualStart.ahk" {WdsTransportNamespaceScheduledCastManualStart}
#Import export ".\WdsTransportServer.ahk" {WdsTransportServer}
#Import export ".\WdsTransportServicePolicy.ahk" {WdsTransportServicePolicy}
#Import export ".\WdsTransportSession.ahk" {WdsTransportSession}
#Import export ".\WdsTransportSetupManager.ahk" {WdsTransportSetupManager}
#Import export ".\WdsTransportTftpClient.ahk" {WdsTransportTftpClient}
#Import export ".\WdsTransportTftpManager.ahk" {WdsTransportTftpManager}
