#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import "..\..\..\Guid.ahk" { Guid }
#Import ".\PIBIO_FRAMEWORK_ALLOCATE_MEMORY_FN.ahk" { PIBIO_FRAMEWORK_ALLOCATE_MEMORY_FN }
#Import ".\PIBIO_FRAMEWORK_FREE_MEMORY_FN.ahk" { PIBIO_FRAMEWORK_FREE_MEMORY_FN }
#Import ".\PIBIO_FRAMEWORK_GET_PROPERTY_FN.ahk" { PIBIO_FRAMEWORK_GET_PROPERTY_FN }
#Import ".\PIBIO_FRAMEWORK_LOCK_AND_VALIDATE_SECURE_BUFFER_FN.ahk" { PIBIO_FRAMEWORK_LOCK_AND_VALIDATE_SECURE_BUFFER_FN }
#Import ".\PIBIO_FRAMEWORK_RELEASE_SECURE_BUFFER_FN.ahk" { PIBIO_FRAMEWORK_RELEASE_SECURE_BUFFER_FN }
#Import ".\PIBIO_FRAMEWORK_SET_UNIT_STATUS_FN.ahk" { PIBIO_FRAMEWORK_SET_UNIT_STATUS_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_CACHE_CLEAR_FN.ahk" { PIBIO_FRAMEWORK_VSM_CACHE_CLEAR_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_CACHE_EXPORT_BEGIN_FN.ahk" { PIBIO_FRAMEWORK_VSM_CACHE_EXPORT_BEGIN_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_CACHE_EXPORT_END_FN.ahk" { PIBIO_FRAMEWORK_VSM_CACHE_EXPORT_END_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_CACHE_EXPORT_NEXT_FN.ahk" { PIBIO_FRAMEWORK_VSM_CACHE_EXPORT_NEXT_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_CACHE_IMPORT_BEGIN_FN.ahk" { PIBIO_FRAMEWORK_VSM_CACHE_IMPORT_BEGIN_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_CACHE_IMPORT_END_FN.ahk" { PIBIO_FRAMEWORK_VSM_CACHE_IMPORT_END_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_CACHE_IMPORT_NEXT_FN.ahk" { PIBIO_FRAMEWORK_VSM_CACHE_IMPORT_NEXT_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_DECRYPT_SAMPLE_FN.ahk" { PIBIO_FRAMEWORK_VSM_DECRYPT_SAMPLE_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_QUERY_AUTHORIZED_ENROLLMENTS_FN.ahk" { PIBIO_FRAMEWORK_VSM_QUERY_AUTHORIZED_ENROLLMENTS_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_STORAGE_RESERVED_1_FN.ahk" { PIBIO_FRAMEWORK_VSM_STORAGE_RESERVED_1_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_STORAGE_RESERVED_2_FN.ahk" { PIBIO_FRAMEWORK_VSM_STORAGE_RESERVED_2_FN }
#Import ".\PIBIO_FRAMEWORK_VSM_STORAGE_RESERVED_3_FN.ahk" { PIBIO_FRAMEWORK_VSM_STORAGE_RESERVED_3_FN }
#Import ".\PIBIO_SENSOR_ACTIVATE_FN.ahk" { PIBIO_SENSOR_ACTIVATE_FN }
#Import ".\PIBIO_SENSOR_ASYNC_IMPORT_RAW_BUFFER_FN.ahk" { PIBIO_SENSOR_ASYNC_IMPORT_RAW_BUFFER_FN }
#Import ".\PIBIO_SENSOR_ASYNC_IMPORT_SECURE_BUFFER_FN.ahk" { PIBIO_SENSOR_ASYNC_IMPORT_SECURE_BUFFER_FN }
#Import ".\PIBIO_SENSOR_ATTACH_FN.ahk" { PIBIO_SENSOR_ATTACH_FN }
#Import ".\PIBIO_SENSOR_CLEAR_CONTEXT_FN.ahk" { PIBIO_SENSOR_CLEAR_CONTEXT_FN }
#Import ".\PIBIO_SENSOR_DEACTIVATE_FN.ahk" { PIBIO_SENSOR_DEACTIVATE_FN }
#Import ".\PIBIO_SENSOR_DETACH_FN.ahk" { PIBIO_SENSOR_DETACH_FN }
#Import ".\PIBIO_SENSOR_NOTIFY_POWER_CHANGE_FN.ahk" { PIBIO_SENSOR_NOTIFY_POWER_CHANGE_FN }
#Import ".\PIBIO_SENSOR_PIPELINE_CLEANUP_FN.ahk" { PIBIO_SENSOR_PIPELINE_CLEANUP_FN }
#Import ".\PIBIO_SENSOR_PIPELINE_INIT_FN.ahk" { PIBIO_SENSOR_PIPELINE_INIT_FN }
#Import ".\PIBIO_SENSOR_PUSH_DATA_TO_ENGINE_FN.ahk" { PIBIO_SENSOR_PUSH_DATA_TO_ENGINE_FN }
#Import ".\PIBIO_STORAGE_ACTIVATE_FN.ahk" { PIBIO_STORAGE_ACTIVATE_FN }
#Import ".\PIBIO_STORAGE_ATTACH_FN.ahk" { PIBIO_STORAGE_ATTACH_FN }
#Import ".\PIBIO_STORAGE_CLEAR_CONTEXT_FN.ahk" { PIBIO_STORAGE_CLEAR_CONTEXT_FN }
#Import ".\PIBIO_STORAGE_CLOSE_DATABASE_FN.ahk" { PIBIO_STORAGE_CLOSE_DATABASE_FN }
#Import ".\PIBIO_STORAGE_CREATE_DATABASE_FN.ahk" { PIBIO_STORAGE_CREATE_DATABASE_FN }
#Import ".\PIBIO_STORAGE_DEACTIVATE_FN.ahk" { PIBIO_STORAGE_DEACTIVATE_FN }
#Import ".\PIBIO_STORAGE_DELETE_RECORD_FN.ahk" { PIBIO_STORAGE_DELETE_RECORD_FN }
#Import ".\PIBIO_STORAGE_DETACH_FN.ahk" { PIBIO_STORAGE_DETACH_FN }
#Import ".\PIBIO_STORAGE_NOTIFY_POWER_CHANGE_FN.ahk" { PIBIO_STORAGE_NOTIFY_POWER_CHANGE_FN }
#Import ".\PIBIO_STORAGE_OPEN_DATABASE_FN.ahk" { PIBIO_STORAGE_OPEN_DATABASE_FN }
#Import ".\PIBIO_STORAGE_PIPELINE_CLEANUP_FN.ahk" { PIBIO_STORAGE_PIPELINE_CLEANUP_FN }
#Import ".\PIBIO_STORAGE_PIPELINE_INIT_FN.ahk" { PIBIO_STORAGE_PIPELINE_INIT_FN }
#Import ".\PIBIO_STORAGE_QUERY_EXTENDED_INFO_FN.ahk" { PIBIO_STORAGE_QUERY_EXTENDED_INFO_FN }
#Import ".\PIBIO_STORAGE_RESERVED_1_FN.ahk" { PIBIO_STORAGE_RESERVED_1_FN }
#Import ".\PIBIO_STORAGE_RESERVED_2_FN.ahk" { PIBIO_STORAGE_RESERVED_2_FN }
#Import ".\WINBIO_ADAPTER_INTERFACE_VERSION.ahk" { WINBIO_ADAPTER_INTERFACE_VERSION }

/**
 * @namespace Windows.Win32.Devices.BiometricFramework
 */
export default struct WINBIO_FRAMEWORK_INTERFACE {
    #StructPack 8

    Version : WINBIO_ADAPTER_INTERFACE_VERSION

    Type : UInt32

    Size : IntPtr

    AdapterId : Guid

    SetUnitStatus : PIBIO_FRAMEWORK_SET_UNIT_STATUS_FN

    VsmStorageAttach : PIBIO_STORAGE_ATTACH_FN

    VsmStorageDetach : PIBIO_STORAGE_DETACH_FN

    VsmStorageClearContext : PIBIO_STORAGE_CLEAR_CONTEXT_FN

    VsmStorageCreateDatabase : PIBIO_STORAGE_CREATE_DATABASE_FN

    VsmStorageOpenDatabase : PIBIO_STORAGE_OPEN_DATABASE_FN

    VsmStorageCloseDatabase : PIBIO_STORAGE_CLOSE_DATABASE_FN

    VsmStorageDeleteRecord : PIBIO_STORAGE_DELETE_RECORD_FN

    VsmStorageNotifyPowerChange : PIBIO_STORAGE_NOTIFY_POWER_CHANGE_FN

    VsmStoragePipelineInit : PIBIO_STORAGE_PIPELINE_INIT_FN

    VsmStoragePipelineCleanup : PIBIO_STORAGE_PIPELINE_CLEANUP_FN

    VsmStorageActivate : PIBIO_STORAGE_ACTIVATE_FN

    VsmStorageDeactivate : PIBIO_STORAGE_DEACTIVATE_FN

    VsmStorageQueryExtendedInfo : PIBIO_STORAGE_QUERY_EXTENDED_INFO_FN

    VsmStorageCacheClear : PIBIO_FRAMEWORK_VSM_CACHE_CLEAR_FN

    VsmStorageCacheImportBegin : PIBIO_FRAMEWORK_VSM_CACHE_IMPORT_BEGIN_FN

    VsmStorageCacheImportNext : PIBIO_FRAMEWORK_VSM_CACHE_IMPORT_NEXT_FN

    VsmStorageCacheImportEnd : PIBIO_FRAMEWORK_VSM_CACHE_IMPORT_END_FN

    VsmStorageCacheExportBegin : PIBIO_FRAMEWORK_VSM_CACHE_EXPORT_BEGIN_FN

    VsmStorageCacheExportNext : PIBIO_FRAMEWORK_VSM_CACHE_EXPORT_NEXT_FN

    VsmStorageCacheExportEnd : PIBIO_FRAMEWORK_VSM_CACHE_EXPORT_END_FN

    VsmSensorAttach : PIBIO_SENSOR_ATTACH_FN

    VsmSensorDetach : PIBIO_SENSOR_DETACH_FN

    VsmSensorClearContext : PIBIO_SENSOR_CLEAR_CONTEXT_FN

    VsmSensorPushDataToEngine : PIBIO_SENSOR_PUSH_DATA_TO_ENGINE_FN

    VsmSensorNotifyPowerChange : PIBIO_SENSOR_NOTIFY_POWER_CHANGE_FN

    VsmSensorPipelineInit : PIBIO_SENSOR_PIPELINE_INIT_FN

    VsmSensorPipelineCleanup : PIBIO_SENSOR_PIPELINE_CLEANUP_FN

    VsmSensorActivate : PIBIO_SENSOR_ACTIVATE_FN

    VsmSensorDeactivate : PIBIO_SENSOR_DEACTIVATE_FN

    VsmSensorAsyncImportRawBuffer : PIBIO_SENSOR_ASYNC_IMPORT_RAW_BUFFER_FN

    VsmSensorAsyncImportSecureBuffer : PIBIO_SENSOR_ASYNC_IMPORT_SECURE_BUFFER_FN

    Reserved1 : PIBIO_FRAMEWORK_VSM_STORAGE_RESERVED_1_FN

    Reserved2 : PIBIO_FRAMEWORK_VSM_STORAGE_RESERVED_2_FN

    Reserved3 : PIBIO_FRAMEWORK_VSM_STORAGE_RESERVED_3_FN

    Reserved4 : PIBIO_STORAGE_RESERVED_1_FN

    Reserved5 : PIBIO_STORAGE_RESERVED_2_FN

    AllocateMemory : PIBIO_FRAMEWORK_ALLOCATE_MEMORY_FN

    FreeMemory : PIBIO_FRAMEWORK_FREE_MEMORY_FN

    GetProperty : PIBIO_FRAMEWORK_GET_PROPERTY_FN

    LockAndValidateSecureBuffer : PIBIO_FRAMEWORK_LOCK_AND_VALIDATE_SECURE_BUFFER_FN

    ReleaseSecureBuffer : PIBIO_FRAMEWORK_RELEASE_SECURE_BUFFER_FN

    QueryAuthorizedEnrollments : PIBIO_FRAMEWORK_VSM_QUERY_AUTHORIZED_ENROLLMENTS_FN

    DecryptSample : PIBIO_FRAMEWORK_VSM_DECRYPT_SAMPLE_FN

}
