#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Constants.ahk" {*}
#Import export ".\IDesktopWindowXamlSourceNative.ahk" {IDesktopWindowXamlSourceNative}
#Import export ".\IDesktopWindowXamlSourceNative2.ahk" {IDesktopWindowXamlSourceNative2}
#Import export ".\IFindReferenceTargetsCallback.ahk" {IFindReferenceTargetsCallback}
#Import export ".\IReferenceTracker.ahk" {IReferenceTracker}
#Import export ".\IReferenceTrackerExtension.ahk" {IReferenceTrackerExtension}
#Import export ".\IReferenceTrackerHost.ahk" {IReferenceTrackerHost}
#Import export ".\IReferenceTrackerManager.ahk" {IReferenceTrackerManager}
#Import export ".\IReferenceTrackerTarget.ahk" {IReferenceTrackerTarget}
#Import export ".\ISurfaceImageSourceManagerNative.ahk" {ISurfaceImageSourceManagerNative}
#Import export ".\ISurfaceImageSourceNative.ahk" {ISurfaceImageSourceNative}
#Import export ".\ISurfaceImageSourceNativeWithD2D.ahk" {ISurfaceImageSourceNativeWithD2D}
#Import export ".\ISwapChainBackgroundPanelNative.ahk" {ISwapChainBackgroundPanelNative}
#Import export ".\ISwapChainPanelNative.ahk" {ISwapChainPanelNative}
#Import export ".\ISwapChainPanelNative2.ahk" {ISwapChainPanelNative2}
#Import export ".\ITrackerOwner.ahk" {ITrackerOwner}
#Import export ".\IVirtualSurfaceImageSourceNative.ahk" {IVirtualSurfaceImageSourceNative}
#Import export ".\IVirtualSurfaceUpdatesCallbackNative.ahk" {IVirtualSurfaceUpdatesCallbackNative}
#Import export ".\TrackerHandle.ahk" {TrackerHandle}
#Import export ".\XAML_REFERENCETRACKER_DISCONNECT.ahk" {XAML_REFERENCETRACKER_DISCONNECT}
