#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\WHEA_ERROR_SOURCE_CORRECT_DEVICE_DRIVER.ahk" { WHEA_ERROR_SOURCE_CORRECT_DEVICE_DRIVER }
#Import ".\WHEA_ERROR_SOURCE_INITIALIZE_DEVICE_DRIVER.ahk" { WHEA_ERROR_SOURCE_INITIALIZE_DEVICE_DRIVER }
#Import ".\WHEA_ERROR_SOURCE_UNINITIALIZE_DEVICE_DRIVER.ahk" { WHEA_ERROR_SOURCE_UNINITIALIZE_DEVICE_DRIVER }

/**
 * @namespace Windows.Win32.System.Diagnostics.Debug
 */
export default struct WHEA_ERROR_SOURCE_CONFIGURATION_DD {
    #StructPack 8

    Initialize : WHEA_ERROR_SOURCE_INITIALIZE_DEVICE_DRIVER

    Uninitialize : WHEA_ERROR_SOURCE_UNINITIALIZE_DEVICE_DRIVER

    Correct : WHEA_ERROR_SOURCE_CORRECT_DEVICE_DRIVER

}
