#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_KEY.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_KEY }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_RANDOM_DATA.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_RANDOM_DATA }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_INTERRUPT_THREAD.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_INTERRUPT_THREAD }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_DECOMMIT_PAGES.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_DECOMMIT_PAGES }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_TERMINATE_THREAD.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_TERMINATE_THREAD }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_VERIFY_REPORT.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_VERIFY_REPORT }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_RETURN_FROM_EXCEPTION.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_RETURN_FROM_EXCEPTION }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_COMMIT_PAGES.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_COMMIT_PAGES }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_REPORT.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_REPORT }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_CREATE_THREAD.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_CREATE_THREAD }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_GET_ENCLAVE_INFORMATION.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_GET_ENCLAVE_INFORMATION }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_PROTECT_PAGES.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_PROTECT_PAGES }
#Import ".\VBS_BASIC_ENCLAVE_BASIC_CALL_RETURN_FROM_ENCLAVE.ahk" { VBS_BASIC_ENCLAVE_BASIC_CALL_RETURN_FROM_ENCLAVE }

/**
 * @namespace Windows.Win32.System.Environment
 */
export default struct VBS_BASIC_ENCLAVE_SYSCALL_PAGE {
    #StructPack 8

    ReturnFromEnclave : VBS_BASIC_ENCLAVE_BASIC_CALL_RETURN_FROM_ENCLAVE

    ReturnFromException : VBS_BASIC_ENCLAVE_BASIC_CALL_RETURN_FROM_EXCEPTION

    TerminateThread : VBS_BASIC_ENCLAVE_BASIC_CALL_TERMINATE_THREAD

    InterruptThread : VBS_BASIC_ENCLAVE_BASIC_CALL_INTERRUPT_THREAD

    CommitPages : VBS_BASIC_ENCLAVE_BASIC_CALL_COMMIT_PAGES

    DecommitPages : VBS_BASIC_ENCLAVE_BASIC_CALL_DECOMMIT_PAGES

    ProtectPages : VBS_BASIC_ENCLAVE_BASIC_CALL_PROTECT_PAGES

    CreateThread : VBS_BASIC_ENCLAVE_BASIC_CALL_CREATE_THREAD

    GetEnclaveInformation : VBS_BASIC_ENCLAVE_BASIC_CALL_GET_ENCLAVE_INFORMATION

    GenerateKey : VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_KEY

    GenerateReport : VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_REPORT

    VerifyReport : VBS_BASIC_ENCLAVE_BASIC_CALL_VERIFY_REPORT

    GenerateRandomData : VBS_BASIC_ENCLAVE_BASIC_CALL_GENERATE_RANDOM_DATA

}
