#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32Struct.ahk
#Include .\ENCLAVE_IDENTITY.ahk

/**
 * Describes the format of the signed statement contained in a report generated by calling the EnclaveGetAttestationReport function.
 * @remarks
 * The signed statement in an enclave attestation report consist of the following items:
  * 
  * <ul>
  * <li>
  * A <b>VBS_ENCLAVE_REPORT</b> structure the describes the format of the signed statement.
  * 
  * </li>
  * <li>
  * Zero or more variable data blocks that consist of the following items:
  * 
  * <ul>
  * <li>A <a href="https://docs.microsoft.com/windows/desktop/api/ntenclv/ns-ntenclv-vbs_enclave_report_vardata_header">VBS_ENCLAVE_REPORT_VARDATA_HEADER</a> structure that describes the format of the variable data block.</li>
  * <li>Data described by the <a href="https://docs.microsoft.com/windows/desktop/api/ntenclv/ns-ntenclv-vbs_enclave_report_vardata_header">VBS_ENCLAVE_REPORT_VARDATA_HEADER</a> structure.</li>
  * </ul>
  * </li>
  * </ul>
 * @see https://learn.microsoft.com/windows/win32/api/ntenclv/ns-ntenclv-vbs_enclave_report
 * @namespace Windows.Win32.System.Environment
 * @version v4.0.30319
 */
class VBS_ENCLAVE_REPORT extends Win32Struct
{
    static sizeof => 224

    static packingSize => 8

    /**
     * The total size of the signed statement in the report, including the sizes of the <b>VBS_ENCLAVE_REPORT</b> structure and of all the variable data blocks, in bytes.
     * @type {Integer}
     */
    ReportSize {
        get => NumGet(this, 0, "uint")
        set => NumPut("uint", value, this, 0)
    }

    /**
     * The version of the report format.  The only currently available version is  <b>VBS_ENCLAVE_REPORT_VERSION_CURRENT</b>, which equals 1.
     * @type {Integer}
     */
    ReportVersion {
        get => NumGet(this, 4, "uint")
        set => NumPut("uint", value, this, 4)
    }

    /**
     * The 64 bytes that were provided in <i>EnclaveData</i> parameter of the <a href="https://docs.microsoft.com/windows/desktop/api/winenclaveapi/nf-winenclaveapi-enclavegetattestationreport">EnclaveGetAttestationReport</a> function.
     * @type {Array<Byte>}
     */
    EnclaveData{
        get {
            if(!this.HasProp("__EnclaveDataProxyArray"))
                this.__EnclaveDataProxyArray := Win32FixedArray(this.ptr + 8, 64, Primitive, "char")
            return this.__EnclaveDataProxyArray
        }
    }

    /**
     * An <a href="https://docs.microsoft.com/windows/desktop/api/ntenclv/ns-ntenclv-enclave_identity">ENCLAVE_IDENTITY</a> structure that describes the identity of the primary module of the enclave.
     * @type {ENCLAVE_IDENTITY}
     */
    EnclaveIdentity{
        get {
            if(!this.HasProp("__EnclaveIdentity"))
                this.__EnclaveIdentity := ENCLAVE_IDENTITY(this.ptr + 72)
            return this.__EnclaveIdentity
        }
    }
}
