#Requires AutoHotkey v2.1-alpha.26+ 64-bit

/**
 * Describes the contents of a report generated by calling the EnclaveGetAttestationReport function.
 * @remarks
 * The report that <a href="https://docs.microsoft.com/windows/desktop/api/winenclaveapi/nf-winenclaveapi-enclavegetattestationreport">EnclaveGetAttestationReport</a> generates consists of the following items:
 * 
 * <ul>
 * <li>
 * A <b>VBS_ENCLAVE_REPORT_PKG_HEADER</b> structure
 * 
 * </li>
 * <li>
 * A signed statement that consist of the following items:
 * 
 * <ul>
 * <li>
 * A <a href="https://docs.microsoft.com/windows/desktop/api/ntenclv/ns-ntenclv-vbs_enclave_report">VBS_ENCLAVE_REPORT</a> structure
 * 
 * </li>
 * <li>
 * Zero or more variable data blocks that consist of the following items:
 * 
 * <ul>
 * <li>A <a href="https://docs.microsoft.com/windows/desktop/api/ntenclv/ns-ntenclv-vbs_enclave_report_vardata_header">VBS_ENCLAVE_REPORT_VARDATA_HEADER</a> structure</li>
 * <li>Data described by the <a href="https://docs.microsoft.com/windows/desktop/api/ntenclv/ns-ntenclv-vbs_enclave_report_vardata_header">VBS_ENCLAVE_REPORT_VARDATA_HEADER</a> structure</li>
 * </ul>
 * </li>
 * </ul>
 * </li>
 * <li>A signature</li>
 * </ul>
 * @see https://learn.microsoft.com/windows/win32/api/ntenclv/ns-ntenclv-vbs_enclave_report_pkg_header
 * @namespace Windows.Win32.System.Environment
 */
export default struct VBS_ENCLAVE_REPORT_PKG_HEADER {
    #StructPack 4

    /**
     * The sum of the sizes of the  <b>VBS_ENCLAVE_REPORT_PKG_HEADER</b> structure, the signed statement, and the signature contained in a report generated by calling the <a href="https://docs.microsoft.com/windows/desktop/api/winenclaveapi/nf-winenclaveapi-enclavegetattestationreport">EnclaveGetAttestationReport</a> function, in bytes.
     */
    PackageSize : UInt32

    /**
     * The version of the <b>VBS_ENCLAVE_REPORT_PKG_HEADER</b> structure in a report generated by calling the <a href="https://docs.microsoft.com/windows/desktop/api/winenclaveapi/nf-winenclaveapi-enclavegetattestationreport">EnclaveGetAttestationReport</a> function. The only version currently supported is <b>VBS_ENCLAVE_REPORT_PKG_HEADER_VERSION_CURRENT</b>, which equals 1.
     */
    Version : UInt32

    /**
     * The scheme used for the signature in a report generated by calling the <a href="https://docs.microsoft.com/windows/desktop/api/winenclaveapi/nf-winenclaveapi-enclavegetattestationreport">EnclaveGetAttestationReport</a> function.
     */
    SignatureScheme : UInt32

    /**
     * The size of the signed data contained in a report generated by calling the <a href="https://docs.microsoft.com/windows/desktop/api/winenclaveapi/nf-winenclaveapi-enclavegetattestationreport">EnclaveGetAttestationReport</a> function, in bytes.
     */
    SignedStatementSize : UInt32

    /**
     * The size of the signature contained in a report generated by calling the <a href="https://docs.microsoft.com/windows/desktop/api/winenclaveapi/nf-winenclaveapi-enclavegetattestationreport">EnclaveGetAttestationReport</a> function, in bytes.
     */
    SignatureSize : UInt32

    /**
     * Reserved.
     */
    Reserved : UInt32

}
