#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\DS3DBUFFER.ahk" {DS3DBUFFER}
#Import export ".\DS3DLISTENER.ahk" {DS3DLISTENER}
#Import export ".\DSBCAPS.ahk" {DSBCAPS}
#Import export ".\DSBPOSITIONNOTIFY.ahk" {DSBPOSITIONNOTIFY}
#Import export ".\DSBUFFERDESC.ahk" {DSBUFFERDESC}
#Import export ".\DSBUFFERDESC1.ahk" {DSBUFFERDESC1}
#Import export ".\DSCAPS.ahk" {DSCAPS}
#Import export ".\DSCBCAPS.ahk" {DSCBCAPS}
#Import export ".\DSCBUFFERDESC.ahk" {DSCBUFFERDESC}
#Import export ".\DSCBUFFERDESC1.ahk" {DSCBUFFERDESC1}
#Import export ".\DSCCAPS.ahk" {DSCCAPS}
#Import export ".\DSCEFFECTDESC.ahk" {DSCEFFECTDESC}
#Import export ".\DSCFXAec.ahk" {DSCFXAec}
#Import export ".\DSCFXNoiseSuppress.ahk" {DSCFXNoiseSuppress}
#Import export ".\DSEFFECTDESC.ahk" {DSEFFECTDESC}
#Import export ".\DSFXChorus.ahk" {DSFXChorus}
#Import export ".\DSFXCompressor.ahk" {DSFXCompressor}
#Import export ".\DSFXDistortion.ahk" {DSFXDistortion}
#Import export ".\DSFXEcho.ahk" {DSFXEcho}
#Import export ".\DSFXFlanger.ahk" {DSFXFlanger}
#Import export ".\DSFXGargle.ahk" {DSFXGargle}
#Import export ".\DSFXI3DL2Reverb.ahk" {DSFXI3DL2Reverb}
#Import export ".\DSFXParamEq.ahk" {DSFXParamEq}
#Import export ".\DSFXWavesReverb.ahk" {DSFXWavesReverb}
#Import export ".\IDirectSound.ahk" {IDirectSound}
#Import export ".\IDirectSound3DBuffer.ahk" {IDirectSound3DBuffer}
#Import export ".\IDirectSound3DListener.ahk" {IDirectSound3DListener}
#Import export ".\IDirectSound8.ahk" {IDirectSound8}
#Import export ".\IDirectSoundBuffer.ahk" {IDirectSoundBuffer}
#Import export ".\IDirectSoundBuffer8.ahk" {IDirectSoundBuffer8}
#Import export ".\IDirectSoundCapture.ahk" {IDirectSoundCapture}
#Import export ".\IDirectSoundCaptureBuffer.ahk" {IDirectSoundCaptureBuffer}
#Import export ".\IDirectSoundCaptureBuffer8.ahk" {IDirectSoundCaptureBuffer8}
#Import export ".\IDirectSoundCaptureFXAec.ahk" {IDirectSoundCaptureFXAec}
#Import export ".\IDirectSoundCaptureFXNoiseSuppress.ahk" {IDirectSoundCaptureFXNoiseSuppress}
#Import export ".\IDirectSoundFXChorus.ahk" {IDirectSoundFXChorus}
#Import export ".\IDirectSoundFXCompressor.ahk" {IDirectSoundFXCompressor}
#Import export ".\IDirectSoundFXDistortion.ahk" {IDirectSoundFXDistortion}
#Import export ".\IDirectSoundFXEcho.ahk" {IDirectSoundFXEcho}
#Import export ".\IDirectSoundFXFlanger.ahk" {IDirectSoundFXFlanger}
#Import export ".\IDirectSoundFXGargle.ahk" {IDirectSoundFXGargle}
#Import export ".\IDirectSoundFXI3DL2Reverb.ahk" {IDirectSoundFXI3DL2Reverb}
#Import export ".\IDirectSoundFXParamEq.ahk" {IDirectSoundFXParamEq}
#Import export ".\IDirectSoundFXWavesReverb.ahk" {IDirectSoundFXWavesReverb}
#Import export ".\IDirectSoundFullDuplex.ahk" {IDirectSoundFullDuplex}
#Import export ".\IDirectSoundNotify.ahk" {IDirectSoundNotify}
#Import export ".\LPDSENUMCALLBACKA.ahk" {LPDSENUMCALLBACKA}
#Import export ".\LPDSENUMCALLBACKW.ahk" {LPDSENUMCALLBACKW}
