#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32Struct.ahk

/**
 * Contains the result data generated by EAPHost during an authentication session that is then passed to an EAP method.
 * @see https://learn.microsoft.com/windows/win32/api/eaphostpeertypes/ns-eaphostpeertypes-eaphostpeermethodresult
 * @namespace Windows.Win32.Security.ExtensibleAuthenticationProtocol
 * @version v4.0.30319
 */
class EapHostPeerMethodResult extends Win32Struct
{
    static sizeof => 72

    static packingSize => 8

    /**
     * If <b>TRUE</b>, the supplicant was successfully authenticated; if <b>FALSE</b>, it was not.
     * @type {BOOL}
     */
    fIsSuccess {
        get => NumGet(this, 0, "int")
        set => NumPut("int", value, this, 0)
    }

    /**
     * Contains a reason code if the supplicant could not be authenticated.
     * @type {Integer}
     */
    dwFailureReasonCode {
        get => NumGet(this, 4, "uint")
        set => NumPut("uint", value, this, 4)
    }

    /**
     * If <b>TRUE</b>, the connection data specified in <b>pConnectionData</b> data must be persisted to disk; otherwise, it does not need to be saved.
     * @type {BOOL}
     */
    fSaveConnectionData {
        get => NumGet(this, 8, "int")
        set => NumPut("int", value, this, 8)
    }

    /**
     * The size, in bytes, of <b>pConnectionData</b>.
     * @type {Integer}
     */
    dwSizeofConnectionData {
        get => NumGet(this, 12, "uint")
        set => NumPut("uint", value, this, 12)
    }

    /**
     * A pointer to a byte buffer that contains information on the connection over which the EAP authentication session is held.
     * @type {Pointer<Integer>}
     */
    pConnectionData {
        get => NumGet(this, 16, "ptr")
        set => NumPut("ptr", value, this, 16)
    }

    /**
     * If <b>TRUE</b>, the user data specified in <b>pUserData</b> data must be persisted to disk; otherwise, it does not need to be saved.
     * @type {BOOL}
     */
    fSaveUserData {
        get => NumGet(this, 24, "int")
        set => NumPut("int", value, this, 24)
    }

    /**
     * The size, in bytes, of <b>pUserData</b>.
     * @type {Integer}
     */
    dwSizeofUserData {
        get => NumGet(this, 28, "uint")
        set => NumPut("uint", value, this, 28)
    }

    /**
     * A pointer to a  byte buffer that contains information on the supplicant user that requested the EAP authentication session.
     * @type {Pointer<Integer>}
     */
    pUserData {
        get => NumGet(this, 32, "ptr")
        set => NumPut("ptr", value, this, 32)
    }

    /**
     * Pointer to an <a href="https://docs.microsoft.com/windows/desktop/api/eaptypes/ns-eaptypes-eap_attributes">EAP_ATTRIBUTES</a> array structure that contains attributes of the authentication session.
     * @type {Pointer<EAP_ATTRIBUTES>}
     */
    pAttribArray {
        get => NumGet(this, 40, "ptr")
        set => NumPut("ptr", value, this, 40)
    }

    /**
     * An <a href="https://docs.microsoft.com/windows/desktop/api/eaphostpeertypes/ne-eaphostpeertypes-isolation_state">ISOLATION_STATE</a> link value that indicates the isolation state of the authentication session connection.
     * @type {Integer}
     */
    isolationState {
        get => NumGet(this, 48, "int")
        set => NumPut("int", value, this, 48)
    }

    /**
     * A pointer to an <a href="https://docs.microsoft.com/windows/desktop/api/eaptypes/ns-eaptypes-eap_method_info">EAP_METHOD_INFO</a> structure that contains information about the EAP method that performed authentication for the supplicant.
     * @type {Pointer<EAP_METHOD_INFO>}
     */
    pEapMethodInfo {
        get => NumGet(this, 56, "ptr")
        set => NumPut("ptr", value, this, 56)
    }

    /**
     * A pointer to the <a href="https://docs.microsoft.com/windows/desktop/api/eaptypes/ns-eaptypes-eap_error">EAP_ERROR</a> structure that contains any errors raised by EAPHost during  the execution of this function call. After consuming the error data, this memory must be freed by calling <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/eappapis/nf-eappapis-eaphostpeerfreeeaperror">EapHostPeerFreeEapError</a>.
     * @type {Pointer<EAP_ERROR>}
     */
    pEapError {
        get => NumGet(this, 64, "ptr")
        set => NumPut("ptr", value, this, 64)
    }
}
