#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\AllJoyn\__Init.ahk" {*}
#Import export ".\Beep\__Init.ahk" {*}
#Import export ".\BiometricFramework\__Init.ahk" {*}
#Import export ".\Bluetooth\__Init.ahk" {*}
#Import export ".\Cdrom\__Init.ahk" {*}
#Import export ".\Communication\__Init.ahk" {*}
#Import export ".\DeviceAccess\__Init.ahk" {*}
#Import export ".\DeviceAndDriverInstallation\__Init.ahk" {*}
#Import export ".\DeviceQuery\__Init.ahk" {*}
#Import export ".\Display\__Init.ahk" {*}
#Import export ".\Dvd\__Init.ahk" {*}
#Import export ".\Enumeration\__Init.ahk" {*}
#Import export ".\Fax\__Init.ahk" {*}
#Import export ".\FunctionDiscovery\__Init.ahk" {*}
#Import export ".\Geolocation\__Init.ahk" {*}
#Import export ".\HumanInterfaceDevice\__Init.ahk" {*}
#Import export ".\ImageAcquisition\__Init.ahk" {*}
#Import export ".\Nfc\__Init.ahk" {*}
#Import export ".\Nfp\__Init.ahk" {*}
#Import export ".\PortableDevices\__Init.ahk" {*}
#Import export ".\Properties\__Init.ahk" {*}
#Import export ".\Pwm\__Init.ahk" {*}
#Import export ".\Sensors\__Init.ahk" {*}
#Import export ".\SerialCommunication\__Init.ahk" {*}
#Import export ".\Tapi\__Init.ahk" {*}
#Import export ".\Usb\__Init.ahk" {*}
#Import export ".\WebServicesOnDevices\__Init.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\IEEE1394_API_REQUEST.ahk" {IEEE1394_API_REQUEST}
#Import export ".\IEEE1394_VDEV_PNP_REQUEST.ahk" {IEEE1394_VDEV_PNP_REQUEST}
