#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apo\__Init.ahk" {*}
#Import export ".\DirectMusic\__Init.ahk" {*}
#Import export ".\DirectSound\__Init.ahk" {*}
#Import export ".\Endpoints\__Init.ahk" {*}
#Import export ".\XAudio2\__Init.ahk" {*}
#Import export ".\ACMDRIVERDETAILSA.ahk" {ACMDRIVERDETAILSA}
#Import export ".\ACMDRIVERDETAILSW.ahk" {ACMDRIVERDETAILSW}
#Import export ".\ACMDRIVERENUMCB.ahk" {ACMDRIVERENUMCB}
#Import export ".\ACMDRVFORMATSUGGEST.ahk" {ACMDRVFORMATSUGGEST}
#Import export ".\ACMDRVOPENDESCA.ahk" {ACMDRVOPENDESCA}
#Import export ".\ACMDRVOPENDESCW.ahk" {ACMDRVOPENDESCW}
#Import export ".\ACMDRVSTREAMHEADER.ahk" {ACMDRVSTREAMHEADER}
#Import export ".\ACMDRVSTREAMINSTANCE.ahk" {ACMDRVSTREAMINSTANCE}
#Import export ".\ACMDRVSTREAMSIZE.ahk" {ACMDRVSTREAMSIZE}
#Import export ".\ACMFILTERCHOOSEA.ahk" {ACMFILTERCHOOSEA}
#Import export ".\ACMFILTERCHOOSEHOOKPROCA.ahk" {ACMFILTERCHOOSEHOOKPROCA}
#Import export ".\ACMFILTERCHOOSEHOOKPROCW.ahk" {ACMFILTERCHOOSEHOOKPROCW}
#Import export ".\ACMFILTERCHOOSEW.ahk" {ACMFILTERCHOOSEW}
#Import export ".\ACMFILTERDETAILSA.ahk" {ACMFILTERDETAILSA}
#Import export ".\ACMFILTERDETAILSW.ahk" {ACMFILTERDETAILSW}
#Import export ".\ACMFILTERENUMCBA.ahk" {ACMFILTERENUMCBA}
#Import export ".\ACMFILTERENUMCBW.ahk" {ACMFILTERENUMCBW}
#Import export ".\ACMFILTERTAGDETAILSA.ahk" {ACMFILTERTAGDETAILSA}
#Import export ".\ACMFILTERTAGDETAILSW.ahk" {ACMFILTERTAGDETAILSW}
#Import export ".\ACMFILTERTAGENUMCBA.ahk" {ACMFILTERTAGENUMCBA}
#Import export ".\ACMFILTERTAGENUMCBW.ahk" {ACMFILTERTAGENUMCBW}
#Import export ".\ACMFORMATCHOOSEA.ahk" {ACMFORMATCHOOSEA}
#Import export ".\ACMFORMATCHOOSEHOOKPROCA.ahk" {ACMFORMATCHOOSEHOOKPROCA}
#Import export ".\ACMFORMATCHOOSEHOOKPROCW.ahk" {ACMFORMATCHOOSEHOOKPROCW}
#Import export ".\ACMFORMATCHOOSEW.ahk" {ACMFORMATCHOOSEW}
#Import export ".\ACMFORMATDETAILSA.ahk" {ACMFORMATDETAILSA}
#Import export ".\ACMFORMATENUMCBA.ahk" {ACMFORMATENUMCBA}
#Import export ".\ACMFORMATENUMCBW.ahk" {ACMFORMATENUMCBW}
#Import export ".\ACMFORMATTAGDETAILSA.ahk" {ACMFORMATTAGDETAILSA}
#Import export ".\ACMFORMATTAGDETAILSW.ahk" {ACMFORMATTAGDETAILSW}
#Import export ".\ACMFORMATTAGENUMCBA.ahk" {ACMFORMATTAGENUMCBA}
#Import export ".\ACMFORMATTAGENUMCBW.ahk" {ACMFORMATTAGENUMCBW}
#Import export ".\ACMSTREAMHEADER.ahk" {ACMSTREAMHEADER}
#Import export ".\AMBISONICS_CHANNEL_ORDERING.ahk" {AMBISONICS_CHANNEL_ORDERING}
#Import export ".\AMBISONICS_NORMALIZATION.ahk" {AMBISONICS_NORMALIZATION}
#Import export ".\AMBISONICS_PARAMS.ahk" {AMBISONICS_PARAMS}
#Import export ".\AMBISONICS_TYPE.ahk" {AMBISONICS_TYPE}
#Import export ".\AUDCLNT_SHAREMODE.ahk" {AUDCLNT_SHAREMODE}
#Import export ".\AUDCLNT_STREAMOPTIONS.ahk" {AUDCLNT_STREAMOPTIONS}
#Import export ".\AUDIOCLIENT_ACTIVATION_PARAMS.ahk" {AUDIOCLIENT_ACTIVATION_PARAMS}
#Import export ".\AUDIOCLIENT_ACTIVATION_TYPE.ahk" {AUDIOCLIENT_ACTIVATION_TYPE}
#Import export ".\AUDIOCLIENT_PROCESS_LOOPBACK_PARAMS.ahk" {AUDIOCLIENT_PROCESS_LOOPBACK_PARAMS}
#Import export ".\AUDIO_DUCKING_OPTIONS.ahk" {AUDIO_DUCKING_OPTIONS}
#Import export ".\AUDIO_EFFECT.ahk" {AUDIO_EFFECT}
#Import export ".\AUDIO_EFFECT_STATE.ahk" {AUDIO_EFFECT_STATE}
#Import export ".\AUDIO_STREAM_CATEGORY.ahk" {AUDIO_STREAM_CATEGORY}
#Import export ".\AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE.ahk" {AUDIO_SYSTEMEFFECTS_PROPERTYSTORE_TYPE}
#Import export ".\AUDIO_VOLUME_NOTIFICATION_DATA.ahk" {AUDIO_VOLUME_NOTIFICATION_DATA}
#Import export ".\AUXCAPS2A.ahk" {AUXCAPS2A}
#Import export ".\AUXCAPS2W.ahk" {AUXCAPS2W}
#Import export ".\AUXCAPSA.ahk" {AUXCAPSA}
#Import export ".\AUXCAPSW.ahk" {AUXCAPSW}
#Import export ".\Apis.ahk" {*}
#Import export ".\AudioClient3ActivationParams.ahk" {AudioClient3ActivationParams}
#Import export ".\AudioClientProperties.ahk" {AudioClientProperties}
#Import export ".\AudioExtensionParams.ahk" {AudioExtensionParams}
#Import export ".\AudioObjectType.ahk" {AudioObjectType}
#Import export ".\AudioSessionDisconnectReason.ahk" {AudioSessionDisconnectReason}
#Import export ".\AudioSessionState.ahk" {AudioSessionState}
#Import export ".\AudioStateMonitorSoundLevel.ahk" {AudioStateMonitorSoundLevel}
#Import export ".\ConnectorType.ahk" {ConnectorType}
#Import export ".\Constants.ahk" {*}
#Import export ".\DEVICE_STATE.ahk" {DEVICE_STATE}
#Import export ".\DIRECTX_AUDIO_ACTIVATION_PARAMS.ahk" {DIRECTX_AUDIO_ACTIVATION_PARAMS}
#Import export ".\DataFlow.ahk" {DataFlow}
#Import export ".\DeviceTopology.ahk" {DeviceTopology}
#Import export ".\ECHOWAVEFILTER.ahk" {ECHOWAVEFILTER}
#Import export ".\EDataFlow.ahk" {EDataFlow}
#Import export ".\ERole.ahk" {ERole}
#Import export ".\EndpointFormFactor.ahk" {EndpointFormFactor}
#Import export ".\HACMDRIVER.ahk" {HACMDRIVER}
#Import export ".\HACMDRIVERID.ahk" {HACMDRIVERID}
#Import export ".\HACMOBJ.ahk" {HACMOBJ}
#Import export ".\HACMSTREAM.ahk" {HACMSTREAM}
#Import export ".\HMIDI.ahk" {HMIDI}
#Import export ".\HMIDIIN.ahk" {HMIDIIN}
#Import export ".\HMIDIOUT.ahk" {HMIDIOUT}
#Import export ".\HMIDISTRM.ahk" {HMIDISTRM}
#Import export ".\HMIXER.ahk" {HMIXER}
#Import export ".\HMIXEROBJ.ahk" {HMIXEROBJ}
#Import export ".\HWAVE.ahk" {HWAVE}
#Import export ".\HWAVEIN.ahk" {HWAVEIN}
#Import export ".\HWAVEOUT.ahk" {HWAVEOUT}
#Import export ".\IAcousticEchoCancellationControl.ahk" {IAcousticEchoCancellationControl}
#Import export ".\IActivateAudioInterfaceAsyncOperation.ahk" {IActivateAudioInterfaceAsyncOperation}
#Import export ".\IActivateAudioInterfaceCompletionHandler.ahk" {IActivateAudioInterfaceCompletionHandler}
#Import export ".\IAudioAmbisonicsControl.ahk" {IAudioAmbisonicsControl}
#Import export ".\IAudioAutoGainControl.ahk" {IAudioAutoGainControl}
#Import export ".\IAudioBass.ahk" {IAudioBass}
#Import export ".\IAudioCaptureClient.ahk" {IAudioCaptureClient}
#Import export ".\IAudioChannelConfig.ahk" {IAudioChannelConfig}
#Import export ".\IAudioClient.ahk" {IAudioClient}
#Import export ".\IAudioClient2.ahk" {IAudioClient2}
#Import export ".\IAudioClient3.ahk" {IAudioClient3}
#Import export ".\IAudioClientDuckingControl.ahk" {IAudioClientDuckingControl}
#Import export ".\IAudioClock.ahk" {IAudioClock}
#Import export ".\IAudioClock2.ahk" {IAudioClock2}
#Import export ".\IAudioClockAdjustment.ahk" {IAudioClockAdjustment}
#Import export ".\IAudioEffectsChangedNotificationClient.ahk" {IAudioEffectsChangedNotificationClient}
#Import export ".\IAudioEffectsManager.ahk" {IAudioEffectsManager}
#Import export ".\IAudioFormatEnumerator.ahk" {IAudioFormatEnumerator}
#Import export ".\IAudioInputSelector.ahk" {IAudioInputSelector}
#Import export ".\IAudioLoudness.ahk" {IAudioLoudness}
#Import export ".\IAudioMidrange.ahk" {IAudioMidrange}
#Import export ".\IAudioMute.ahk" {IAudioMute}
#Import export ".\IAudioOutputSelector.ahk" {IAudioOutputSelector}
#Import export ".\IAudioPeakMeter.ahk" {IAudioPeakMeter}
#Import export ".\IAudioRenderClient.ahk" {IAudioRenderClient}
#Import export ".\IAudioSessionControl.ahk" {IAudioSessionControl}
#Import export ".\IAudioSessionControl2.ahk" {IAudioSessionControl2}
#Import export ".\IAudioSessionEnumerator.ahk" {IAudioSessionEnumerator}
#Import export ".\IAudioSessionEvents.ahk" {IAudioSessionEvents}
#Import export ".\IAudioSessionManager.ahk" {IAudioSessionManager}
#Import export ".\IAudioSessionManager2.ahk" {IAudioSessionManager2}
#Import export ".\IAudioSessionNotification.ahk" {IAudioSessionNotification}
#Import export ".\IAudioStateMonitor.ahk" {IAudioStateMonitor}
#Import export ".\IAudioStreamVolume.ahk" {IAudioStreamVolume}
#Import export ".\IAudioSystemEffectsPropertyChangeNotificationClient.ahk" {IAudioSystemEffectsPropertyChangeNotificationClient}
#Import export ".\IAudioSystemEffectsPropertyStore.ahk" {IAudioSystemEffectsPropertyStore}
#Import export ".\IAudioTreble.ahk" {IAudioTreble}
#Import export ".\IAudioViewManagerService.ahk" {IAudioViewManagerService}
#Import export ".\IAudioVolumeDuckNotification.ahk" {IAudioVolumeDuckNotification}
#Import export ".\IAudioVolumeLevel.ahk" {IAudioVolumeLevel}
#Import export ".\IChannelAudioVolume.ahk" {IChannelAudioVolume}
#Import export ".\IConnector.ahk" {IConnector}
#Import export ".\IControlChangeNotify.ahk" {IControlChangeNotify}
#Import export ".\IControlInterface.ahk" {IControlInterface}
#Import export ".\IDeviceSpecificProperty.ahk" {IDeviceSpecificProperty}
#Import export ".\IDeviceTopology.ahk" {IDeviceTopology}
#Import export ".\IMMDevice.ahk" {IMMDevice}
#Import export ".\IMMDeviceActivator.ahk" {IMMDeviceActivator}
#Import export ".\IMMDeviceCollection.ahk" {IMMDeviceCollection}
#Import export ".\IMMDeviceEnumerator.ahk" {IMMDeviceEnumerator}
#Import export ".\IMMEndpoint.ahk" {IMMEndpoint}
#Import export ".\IMMNotificationClient.ahk" {IMMNotificationClient}
#Import export ".\IMessageFilter.ahk" {IMessageFilter}
#Import export ".\IPart.ahk" {IPart}
#Import export ".\IPartsList.ahk" {IPartsList}
#Import export ".\IPerChannelDbLevel.ahk" {IPerChannelDbLevel}
#Import export ".\ISimpleAudioVolume.ahk" {ISimpleAudioVolume}
#Import export ".\ISpatialAudioClient.ahk" {ISpatialAudioClient}
#Import export ".\ISpatialAudioClient2.ahk" {ISpatialAudioClient2}
#Import export ".\ISpatialAudioMetadataClient.ahk" {ISpatialAudioMetadataClient}
#Import export ".\ISpatialAudioMetadataCopier.ahk" {ISpatialAudioMetadataCopier}
#Import export ".\ISpatialAudioMetadataItems.ahk" {ISpatialAudioMetadataItems}
#Import export ".\ISpatialAudioMetadataItemsBuffer.ahk" {ISpatialAudioMetadataItemsBuffer}
#Import export ".\ISpatialAudioMetadataReader.ahk" {ISpatialAudioMetadataReader}
#Import export ".\ISpatialAudioMetadataWriter.ahk" {ISpatialAudioMetadataWriter}
#Import export ".\ISpatialAudioObject.ahk" {ISpatialAudioObject}
#Import export ".\ISpatialAudioObjectBase.ahk" {ISpatialAudioObjectBase}
#Import export ".\ISpatialAudioObjectForHrtf.ahk" {ISpatialAudioObjectForHrtf}
#Import export ".\ISpatialAudioObjectForMetadataCommands.ahk" {ISpatialAudioObjectForMetadataCommands}
#Import export ".\ISpatialAudioObjectForMetadataItems.ahk" {ISpatialAudioObjectForMetadataItems}
#Import export ".\ISpatialAudioObjectRenderStream.ahk" {ISpatialAudioObjectRenderStream}
#Import export ".\ISpatialAudioObjectRenderStreamBase.ahk" {ISpatialAudioObjectRenderStreamBase}
#Import export ".\ISpatialAudioObjectRenderStreamForHrtf.ahk" {ISpatialAudioObjectRenderStreamForHrtf}
#Import export ".\ISpatialAudioObjectRenderStreamForMetadata.ahk" {ISpatialAudioObjectRenderStreamForMetadata}
#Import export ".\ISpatialAudioObjectRenderStreamNotify.ahk" {ISpatialAudioObjectRenderStreamNotify}
#Import export ".\ISubunit.ahk" {ISubunit}
#Import export ".\LPACMDRIVERPROC.ahk" {LPACMDRIVERPROC}
#Import export ".\LPMIDICALLBACK.ahk" {LPMIDICALLBACK}
#Import export ".\LPWAVECALLBACK.ahk" {LPWAVECALLBACK}
#Import export ".\MIDIEVENT.ahk" {MIDIEVENT}
#Import export ".\MIDIHDR.ahk" {MIDIHDR}
#Import export ".\MIDIINCAPS2A.ahk" {MIDIINCAPS2A}
#Import export ".\MIDIINCAPS2W.ahk" {MIDIINCAPS2W}
#Import export ".\MIDIINCAPSA.ahk" {MIDIINCAPSA}
#Import export ".\MIDIINCAPSW.ahk" {MIDIINCAPSW}
#Import export ".\MIDIOUTCAPS2A.ahk" {MIDIOUTCAPS2A}
#Import export ".\MIDIOUTCAPS2W.ahk" {MIDIOUTCAPS2W}
#Import export ".\MIDIOUTCAPSA.ahk" {MIDIOUTCAPSA}
#Import export ".\MIDIOUTCAPSW.ahk" {MIDIOUTCAPSW}
#Import export ".\MIDIPROPTEMPO.ahk" {MIDIPROPTEMPO}
#Import export ".\MIDIPROPTIMEDIV.ahk" {MIDIPROPTIMEDIV}
#Import export ".\MIDISTRMBUFFVER.ahk" {MIDISTRMBUFFVER}
#Import export ".\MIDI_WAVE_OPEN_TYPE.ahk" {MIDI_WAVE_OPEN_TYPE}
#Import export ".\MIXERCAPS2A.ahk" {MIXERCAPS2A}
#Import export ".\MIXERCAPS2W.ahk" {MIXERCAPS2W}
#Import export ".\MIXERCAPSA.ahk" {MIXERCAPSA}
#Import export ".\MIXERCAPSW.ahk" {MIXERCAPSW}
#Import export ".\MIXERCONTROLA.ahk" {MIXERCONTROLA}
#Import export ".\MIXERCONTROLDETAILS.ahk" {MIXERCONTROLDETAILS}
#Import export ".\MIXERCONTROLDETAILS_BOOLEAN.ahk" {MIXERCONTROLDETAILS_BOOLEAN}
#Import export ".\MIXERCONTROLDETAILS_LISTTEXTA.ahk" {MIXERCONTROLDETAILS_LISTTEXTA}
#Import export ".\MIXERCONTROLDETAILS_LISTTEXTW.ahk" {MIXERCONTROLDETAILS_LISTTEXTW}
#Import export ".\MIXERCONTROLDETAILS_SIGNED.ahk" {MIXERCONTROLDETAILS_SIGNED}
#Import export ".\MIXERCONTROLDETAILS_UNSIGNED.ahk" {MIXERCONTROLDETAILS_UNSIGNED}
#Import export ".\MIXERCONTROLW.ahk" {MIXERCONTROLW}
#Import export ".\MIXERLINEA.ahk" {MIXERLINEA}
#Import export ".\MIXERLINECONTROLSA.ahk" {MIXERLINECONTROLSA}
#Import export ".\MIXERLINECONTROLSW.ahk" {MIXERLINECONTROLSW}
#Import export ".\MIXERLINEW.ahk" {MIXERLINEW}
#Import export ".\MIXERLINE_COMPONENTTYPE.ahk" {MIXERLINE_COMPONENTTYPE}
#Import export ".\MMDeviceEnumerator.ahk" {MMDeviceEnumerator}
#Import export ".\PAudioStateMonitorCallback.ahk" {PAudioStateMonitorCallback}
#Import export ".\PCMWAVEFORMAT.ahk" {PCMWAVEFORMAT}
#Import export ".\PROCESS_LOOPBACK_MODE.ahk" {PROCESS_LOOPBACK_MODE}
#Import export ".\PartType.ahk" {PartType}
#Import export ".\SND_FLAGS.ahk" {SND_FLAGS}
#Import export ".\SPATIAL_AUDIO_STREAM_OPTIONS.ahk" {SPATIAL_AUDIO_STREAM_OPTIONS}
#Import export ".\SpatialAudioClientActivationParams.ahk" {SpatialAudioClientActivationParams}
#Import export ".\SpatialAudioHrtfActivationParams.ahk" {SpatialAudioHrtfActivationParams}
#Import export ".\SpatialAudioHrtfActivationParams2.ahk" {SpatialAudioHrtfActivationParams2}
#Import export ".\SpatialAudioHrtfDirectivity.ahk" {SpatialAudioHrtfDirectivity}
#Import export ".\SpatialAudioHrtfDirectivityCardioid.ahk" {SpatialAudioHrtfDirectivityCardioid}
#Import export ".\SpatialAudioHrtfDirectivityCone.ahk" {SpatialAudioHrtfDirectivityCone}
#Import export ".\SpatialAudioHrtfDirectivityType.ahk" {SpatialAudioHrtfDirectivityType}
#Import export ".\SpatialAudioHrtfDirectivityUnion.ahk" {SpatialAudioHrtfDirectivityUnion}
#Import export ".\SpatialAudioHrtfDistanceDecay.ahk" {SpatialAudioHrtfDistanceDecay}
#Import export ".\SpatialAudioHrtfDistanceDecayType.ahk" {SpatialAudioHrtfDistanceDecayType}
#Import export ".\SpatialAudioHrtfEnvironmentType.ahk" {SpatialAudioHrtfEnvironmentType}
#Import export ".\SpatialAudioMetadataCopyMode.ahk" {SpatialAudioMetadataCopyMode}
#Import export ".\SpatialAudioMetadataItemsInfo.ahk" {SpatialAudioMetadataItemsInfo}
#Import export ".\SpatialAudioMetadataWriterOverflowMode.ahk" {SpatialAudioMetadataWriterOverflowMode}
#Import export ".\SpatialAudioObjectRenderStreamActivationParams.ahk" {SpatialAudioObjectRenderStreamActivationParams}
#Import export ".\SpatialAudioObjectRenderStreamActivationParams2.ahk" {SpatialAudioObjectRenderStreamActivationParams2}
#Import export ".\SpatialAudioObjectRenderStreamForMetadataActivationParams.ahk" {SpatialAudioObjectRenderStreamForMetadataActivationParams}
#Import export ".\SpatialAudioObjectRenderStreamForMetadataActivationParams2.ahk" {SpatialAudioObjectRenderStreamForMetadataActivationParams2}
#Import export ".\VOLUMEWAVEFILTER.ahk" {VOLUMEWAVEFILTER}
#Import export ".\WAVEFILTER.ahk" {WAVEFILTER}
#Import export ".\WAVEFORMAT.ahk" {WAVEFORMAT}
#Import export ".\WAVEFORMATEX.ahk" {WAVEFORMATEX}
#Import export ".\WAVEFORMATEXTENSIBLE.ahk" {WAVEFORMATEXTENSIBLE}
#Import export ".\WAVEHDR.ahk" {WAVEHDR}
#Import export ".\WAVEINCAPS2A.ahk" {WAVEINCAPS2A}
#Import export ".\WAVEINCAPS2W.ahk" {WAVEINCAPS2W}
#Import export ".\WAVEINCAPSA.ahk" {WAVEINCAPSA}
#Import export ".\WAVEINCAPSW.ahk" {WAVEINCAPSW}
#Import export ".\WAVEOUTCAPS2A.ahk" {WAVEOUTCAPS2A}
#Import export ".\WAVEOUTCAPS2W.ahk" {WAVEOUTCAPS2W}
#Import export ".\WAVEOUTCAPSA.ahk" {WAVEOUTCAPSA}
#Import export ".\WAVEOUTCAPSW.ahk" {WAVEOUTCAPSW}
#Import export ".\_AUDCLNT_BUFFERFLAGS.ahk" {_AUDCLNT_BUFFERFLAGS}
#Import export ".\tACMFORMATDETAILSW.ahk" {tACMFORMATDETAILSW}
