#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Accessibility\__Init.ahk" {*}
#Import export ".\Animation\__Init.ahk" {*}
#Import export ".\ColorSystem\__Init.ahk" {*}
#Import export ".\Controls\__Init.ahk" {*}
#Import export ".\HiDpi\__Init.ahk" {*}
#Import export ".\Input\__Init.ahk" {*}
#Import export ".\InteractionContext\__Init.ahk" {*}
#Import export ".\LegacyWindowsEnvironmentFeatures\__Init.ahk" {*}
#Import export ".\Magnification\__Init.ahk" {*}
#Import export ".\Notifications\__Init.ahk" {*}
#Import export ".\Ribbon\__Init.ahk" {*}
#Import export ".\Shell\__Init.ahk" {*}
#Import export ".\TabletPC\__Init.ahk" {*}
#Import export ".\TextServices\__Init.ahk" {*}
#Import export ".\WindowsAndMessaging\__Init.ahk" {*}
#Import export ".\Wpf\__Init.ahk" {*}
#Import export ".\Xaml\__Init.ahk" {*}
