#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Constants.ahk" {*}
#Import export ".\IUIAnimationInterpolator.ahk" {IUIAnimationInterpolator}
#Import export ".\IUIAnimationInterpolator2.ahk" {IUIAnimationInterpolator2}
#Import export ".\IUIAnimationLoopIterationChangeHandler2.ahk" {IUIAnimationLoopIterationChangeHandler2}
#Import export ".\IUIAnimationManager.ahk" {IUIAnimationManager}
#Import export ".\IUIAnimationManager2.ahk" {IUIAnimationManager2}
#Import export ".\IUIAnimationManagerEventHandler.ahk" {IUIAnimationManagerEventHandler}
#Import export ".\IUIAnimationManagerEventHandler2.ahk" {IUIAnimationManagerEventHandler2}
#Import export ".\IUIAnimationPrimitiveInterpolation.ahk" {IUIAnimationPrimitiveInterpolation}
#Import export ".\IUIAnimationPriorityComparison.ahk" {IUIAnimationPriorityComparison}
#Import export ".\IUIAnimationPriorityComparison2.ahk" {IUIAnimationPriorityComparison2}
#Import export ".\IUIAnimationStoryboard.ahk" {IUIAnimationStoryboard}
#Import export ".\IUIAnimationStoryboard2.ahk" {IUIAnimationStoryboard2}
#Import export ".\IUIAnimationStoryboardEventHandler.ahk" {IUIAnimationStoryboardEventHandler}
#Import export ".\IUIAnimationStoryboardEventHandler2.ahk" {IUIAnimationStoryboardEventHandler2}
#Import export ".\IUIAnimationTimer.ahk" {IUIAnimationTimer}
#Import export ".\IUIAnimationTimerClientEventHandler.ahk" {IUIAnimationTimerClientEventHandler}
#Import export ".\IUIAnimationTimerEventHandler.ahk" {IUIAnimationTimerEventHandler}
#Import export ".\IUIAnimationTimerUpdateHandler.ahk" {IUIAnimationTimerUpdateHandler}
#Import export ".\IUIAnimationTransition.ahk" {IUIAnimationTransition}
#Import export ".\IUIAnimationTransition2.ahk" {IUIAnimationTransition2}
#Import export ".\IUIAnimationTransitionFactory.ahk" {IUIAnimationTransitionFactory}
#Import export ".\IUIAnimationTransitionFactory2.ahk" {IUIAnimationTransitionFactory2}
#Import export ".\IUIAnimationTransitionLibrary.ahk" {IUIAnimationTransitionLibrary}
#Import export ".\IUIAnimationTransitionLibrary2.ahk" {IUIAnimationTransitionLibrary2}
#Import export ".\IUIAnimationVariable.ahk" {IUIAnimationVariable}
#Import export ".\IUIAnimationVariable2.ahk" {IUIAnimationVariable2}
#Import export ".\IUIAnimationVariableChangeHandler.ahk" {IUIAnimationVariableChangeHandler}
#Import export ".\IUIAnimationVariableChangeHandler2.ahk" {IUIAnimationVariableChangeHandler2}
#Import export ".\IUIAnimationVariableCurveChangeHandler2.ahk" {IUIAnimationVariableCurveChangeHandler2}
#Import export ".\IUIAnimationVariableIntegerChangeHandler.ahk" {IUIAnimationVariableIntegerChangeHandler}
#Import export ".\IUIAnimationVariableIntegerChangeHandler2.ahk" {IUIAnimationVariableIntegerChangeHandler2}
#Import export ".\UIAnimationManager.ahk" {UIAnimationManager}
#Import export ".\UIAnimationManager2.ahk" {UIAnimationManager2}
#Import export ".\UIAnimationTimer.ahk" {UIAnimationTimer}
#Import export ".\UIAnimationTransitionFactory.ahk" {UIAnimationTransitionFactory}
#Import export ".\UIAnimationTransitionFactory2.ahk" {UIAnimationTransitionFactory2}
#Import export ".\UIAnimationTransitionLibrary.ahk" {UIAnimationTransitionLibrary}
#Import export ".\UIAnimationTransitionLibrary2.ahk" {UIAnimationTransitionLibrary2}
#Import export ".\UI_ANIMATION_DEPENDENCIES.ahk" {UI_ANIMATION_DEPENDENCIES}
#Import export ".\UI_ANIMATION_IDLE_BEHAVIOR.ahk" {UI_ANIMATION_IDLE_BEHAVIOR}
#Import export ".\UI_ANIMATION_KEYFRAME.ahk" {UI_ANIMATION_KEYFRAME}
#Import export ".\UI_ANIMATION_MANAGER_STATUS.ahk" {UI_ANIMATION_MANAGER_STATUS}
#Import export ".\UI_ANIMATION_MODE.ahk" {UI_ANIMATION_MODE}
#Import export ".\UI_ANIMATION_PRIORITY_EFFECT.ahk" {UI_ANIMATION_PRIORITY_EFFECT}
#Import export ".\UI_ANIMATION_REPEAT_MODE.ahk" {UI_ANIMATION_REPEAT_MODE}
#Import export ".\UI_ANIMATION_ROUNDING_MODE.ahk" {UI_ANIMATION_ROUNDING_MODE}
#Import export ".\UI_ANIMATION_SCHEDULING_RESULT.ahk" {UI_ANIMATION_SCHEDULING_RESULT}
#Import export ".\UI_ANIMATION_SLOPE.ahk" {UI_ANIMATION_SLOPE}
#Import export ".\UI_ANIMATION_STORYBOARD_STATUS.ahk" {UI_ANIMATION_STORYBOARD_STATUS}
#Import export ".\UI_ANIMATION_TIMER_CLIENT_STATUS.ahk" {UI_ANIMATION_TIMER_CLIENT_STATUS}
#Import export ".\UI_ANIMATION_UPDATE_RESULT.ahk" {UI_ANIMATION_UPDATE_RESULT}
