#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Printing\__Init.ahk" {*}
#Import export ".\ABORTPROC.ahk" {ABORTPROC}
#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\DOCINFOA.ahk" {DOCINFOA}
#Import export ".\DOCINFOW.ahk" {DOCINFOW}
#Import export ".\DRAWPATRECT.ahk" {DRAWPATRECT}
#Import export ".\IXpsDocumentPackageTarget.ahk" {IXpsDocumentPackageTarget}
#Import export ".\IXpsDocumentPackageTarget3D.ahk" {IXpsDocumentPackageTarget3D}
#Import export ".\IXpsOMBrush.ahk" {IXpsOMBrush}
#Import export ".\IXpsOMCanvas.ahk" {IXpsOMCanvas}
#Import export ".\IXpsOMColorProfileResource.ahk" {IXpsOMColorProfileResource}
#Import export ".\IXpsOMColorProfileResourceCollection.ahk" {IXpsOMColorProfileResourceCollection}
#Import export ".\IXpsOMCoreProperties.ahk" {IXpsOMCoreProperties}
#Import export ".\IXpsOMDashCollection.ahk" {IXpsOMDashCollection}
#Import export ".\IXpsOMDictionary.ahk" {IXpsOMDictionary}
#Import export ".\IXpsOMDocument.ahk" {IXpsOMDocument}
#Import export ".\IXpsOMDocumentCollection.ahk" {IXpsOMDocumentCollection}
#Import export ".\IXpsOMDocumentSequence.ahk" {IXpsOMDocumentSequence}
#Import export ".\IXpsOMDocumentStructureResource.ahk" {IXpsOMDocumentStructureResource}
#Import export ".\IXpsOMFontResource.ahk" {IXpsOMFontResource}
#Import export ".\IXpsOMFontResourceCollection.ahk" {IXpsOMFontResourceCollection}
#Import export ".\IXpsOMGeometry.ahk" {IXpsOMGeometry}
#Import export ".\IXpsOMGeometryFigure.ahk" {IXpsOMGeometryFigure}
#Import export ".\IXpsOMGeometryFigureCollection.ahk" {IXpsOMGeometryFigureCollection}
#Import export ".\IXpsOMGlyphs.ahk" {IXpsOMGlyphs}
#Import export ".\IXpsOMGlyphsEditor.ahk" {IXpsOMGlyphsEditor}
#Import export ".\IXpsOMGradientBrush.ahk" {IXpsOMGradientBrush}
#Import export ".\IXpsOMGradientStop.ahk" {IXpsOMGradientStop}
#Import export ".\IXpsOMGradientStopCollection.ahk" {IXpsOMGradientStopCollection}
#Import export ".\IXpsOMImageBrush.ahk" {IXpsOMImageBrush}
#Import export ".\IXpsOMImageResource.ahk" {IXpsOMImageResource}
#Import export ".\IXpsOMImageResourceCollection.ahk" {IXpsOMImageResourceCollection}
#Import export ".\IXpsOMLinearGradientBrush.ahk" {IXpsOMLinearGradientBrush}
#Import export ".\IXpsOMMatrixTransform.ahk" {IXpsOMMatrixTransform}
#Import export ".\IXpsOMNameCollection.ahk" {IXpsOMNameCollection}
#Import export ".\IXpsOMObjectFactory.ahk" {IXpsOMObjectFactory}
#Import export ".\IXpsOMObjectFactory1.ahk" {IXpsOMObjectFactory1}
#Import export ".\IXpsOMPackage.ahk" {IXpsOMPackage}
#Import export ".\IXpsOMPackage1.ahk" {IXpsOMPackage1}
#Import export ".\IXpsOMPackageTarget.ahk" {IXpsOMPackageTarget}
#Import export ".\IXpsOMPackageWriter.ahk" {IXpsOMPackageWriter}
#Import export ".\IXpsOMPackageWriter3D.ahk" {IXpsOMPackageWriter3D}
#Import export ".\IXpsOMPage.ahk" {IXpsOMPage}
#Import export ".\IXpsOMPage1.ahk" {IXpsOMPage1}
#Import export ".\IXpsOMPageReference.ahk" {IXpsOMPageReference}
#Import export ".\IXpsOMPageReferenceCollection.ahk" {IXpsOMPageReferenceCollection}
#Import export ".\IXpsOMPart.ahk" {IXpsOMPart}
#Import export ".\IXpsOMPartResources.ahk" {IXpsOMPartResources}
#Import export ".\IXpsOMPartUriCollection.ahk" {IXpsOMPartUriCollection}
#Import export ".\IXpsOMPath.ahk" {IXpsOMPath}
#Import export ".\IXpsOMPrintTicketResource.ahk" {IXpsOMPrintTicketResource}
#Import export ".\IXpsOMRadialGradientBrush.ahk" {IXpsOMRadialGradientBrush}
#Import export ".\IXpsOMRemoteDictionaryResource.ahk" {IXpsOMRemoteDictionaryResource}
#Import export ".\IXpsOMRemoteDictionaryResource1.ahk" {IXpsOMRemoteDictionaryResource1}
#Import export ".\IXpsOMRemoteDictionaryResourceCollection.ahk" {IXpsOMRemoteDictionaryResourceCollection}
#Import export ".\IXpsOMResource.ahk" {IXpsOMResource}
#Import export ".\IXpsOMShareable.ahk" {IXpsOMShareable}
#Import export ".\IXpsOMSignatureBlockResource.ahk" {IXpsOMSignatureBlockResource}
#Import export ".\IXpsOMSignatureBlockResourceCollection.ahk" {IXpsOMSignatureBlockResourceCollection}
#Import export ".\IXpsOMSolidColorBrush.ahk" {IXpsOMSolidColorBrush}
#Import export ".\IXpsOMStoryFragmentsResource.ahk" {IXpsOMStoryFragmentsResource}
#Import export ".\IXpsOMThumbnailGenerator.ahk" {IXpsOMThumbnailGenerator}
#Import export ".\IXpsOMTileBrush.ahk" {IXpsOMTileBrush}
#Import export ".\IXpsOMVisual.ahk" {IXpsOMVisual}
#Import export ".\IXpsOMVisualBrush.ahk" {IXpsOMVisualBrush}
#Import export ".\IXpsOMVisualCollection.ahk" {IXpsOMVisualCollection}
#Import export ".\IXpsSignature.ahk" {IXpsSignature}
#Import export ".\IXpsSignatureBlock.ahk" {IXpsSignatureBlock}
#Import export ".\IXpsSignatureBlockCollection.ahk" {IXpsSignatureBlockCollection}
#Import export ".\IXpsSignatureCollection.ahk" {IXpsSignatureCollection}
#Import export ".\IXpsSignatureManager.ahk" {IXpsSignatureManager}
#Import export ".\IXpsSignatureRequest.ahk" {IXpsSignatureRequest}
#Import export ".\IXpsSignatureRequestCollection.ahk" {IXpsSignatureRequestCollection}
#Import export ".\IXpsSigningOptions.ahk" {IXpsSigningOptions}
#Import export ".\PRINTER_DEVICE_CAPABILITIES.ahk" {PRINTER_DEVICE_CAPABILITIES}
#Import export ".\PRINT_WINDOW_FLAGS.ahk" {PRINT_WINDOW_FLAGS}
#Import export ".\PSFEATURE_CUSTPAPER.ahk" {PSFEATURE_CUSTPAPER}
#Import export ".\PSFEATURE_OUTPUT.ahk" {PSFEATURE_OUTPUT}
#Import export ".\PSINJECTDATA.ahk" {PSINJECTDATA}
#Import export ".\PSINJECT_POINT.ahk" {PSINJECT_POINT}
#Import export ".\XPS_COLOR.ahk" {XPS_COLOR}
#Import export ".\XPS_COLOR_INTERPOLATION.ahk" {XPS_COLOR_INTERPOLATION}
#Import export ".\XPS_COLOR_TYPE.ahk" {XPS_COLOR_TYPE}
#Import export ".\XPS_DASH.ahk" {XPS_DASH}
#Import export ".\XPS_DASH_CAP.ahk" {XPS_DASH_CAP}
#Import export ".\XPS_DOCUMENT_TYPE.ahk" {XPS_DOCUMENT_TYPE}
#Import export ".\XPS_FILL_RULE.ahk" {XPS_FILL_RULE}
#Import export ".\XPS_FONT_EMBEDDING.ahk" {XPS_FONT_EMBEDDING}
#Import export ".\XPS_GLYPH_INDEX.ahk" {XPS_GLYPH_INDEX}
#Import export ".\XPS_GLYPH_MAPPING.ahk" {XPS_GLYPH_MAPPING}
#Import export ".\XPS_IMAGE_TYPE.ahk" {XPS_IMAGE_TYPE}
#Import export ".\XPS_INTERLEAVING.ahk" {XPS_INTERLEAVING}
#Import export ".\XPS_LINE_CAP.ahk" {XPS_LINE_CAP}
#Import export ".\XPS_LINE_JOIN.ahk" {XPS_LINE_JOIN}
#Import export ".\XPS_MATRIX.ahk" {XPS_MATRIX}
#Import export ".\XPS_OBJECT_TYPE.ahk" {XPS_OBJECT_TYPE}
#Import export ".\XPS_POINT.ahk" {XPS_POINT}
#Import export ".\XPS_RECT.ahk" {XPS_RECT}
#Import export ".\XPS_SEGMENT_STROKE_PATTERN.ahk" {XPS_SEGMENT_STROKE_PATTERN}
#Import export ".\XPS_SEGMENT_TYPE.ahk" {XPS_SEGMENT_TYPE}
#Import export ".\XPS_SIGNATURE_STATUS.ahk" {XPS_SIGNATURE_STATUS}
#Import export ".\XPS_SIGN_FLAGS.ahk" {XPS_SIGN_FLAGS}
#Import export ".\XPS_SIGN_POLICY.ahk" {XPS_SIGN_POLICY}
#Import export ".\XPS_SIZE.ahk" {XPS_SIZE}
#Import export ".\XPS_SPREAD_METHOD.ahk" {XPS_SPREAD_METHOD}
#Import export ".\XPS_STYLE_SIMULATION.ahk" {XPS_STYLE_SIMULATION}
#Import export ".\XPS_THUMBNAIL_SIZE.ahk" {XPS_THUMBNAIL_SIZE}
#Import export ".\XPS_TILE_MODE.ahk" {XPS_TILE_MODE}
#Import export ".\XpsOMObjectFactory.ahk" {XpsOMObjectFactory}
#Import export ".\XpsOMThumbnailGenerator.ahk" {XpsOMThumbnailGenerator}
#Import export ".\XpsSignatureManager.ahk" {XpsSignatureManager}
