#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\CDROM_PERFORMANCE_TYPE.ahk" { CDROM_PERFORMANCE_TYPE }
#Import ".\CDROM_PERFORMANCE_REQUEST_TYPE.ahk" { CDROM_PERFORMANCE_REQUEST_TYPE }
#Import ".\CDROM_PERFORMANCE_EXCEPTION_TYPE.ahk" { CDROM_PERFORMANCE_EXCEPTION_TYPE }
#Import ".\CDROM_PERFORMANCE_TOLERANCE_TYPE.ahk" { CDROM_PERFORMANCE_TOLERANCE_TYPE }

/**
 * @namespace Windows.Win32.Devices.Cdrom
 */
export default struct CDROM_PERFORMANCE_REQUEST {
    #StructPack 4

    RequestType : CDROM_PERFORMANCE_REQUEST_TYPE

    PerformanceType : CDROM_PERFORMANCE_TYPE

    Exceptions : CDROM_PERFORMANCE_EXCEPTION_TYPE

    Tolerance : CDROM_PERFORMANCE_TOLERANCE_TYPE

    StaringLba : UInt32

}
