#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\GameInputArcadeStickButtons.ahk" {GameInputArcadeStickButtons}
#Import export ".\GameInputArcadeStickInfo.ahk" {GameInputArcadeStickInfo}
#Import export ".\GameInputArcadeStickState.ahk" {GameInputArcadeStickState}
#Import export ".\GameInputBatteryState.ahk" {GameInputBatteryState}
#Import export ".\GameInputBatteryStatus.ahk" {GameInputBatteryStatus}
#Import export ".\GameInputControllerAxisInfo.ahk" {GameInputControllerAxisInfo}
#Import export ".\GameInputControllerButtonInfo.ahk" {GameInputControllerButtonInfo}
#Import export ".\GameInputControllerSwitchInfo.ahk" {GameInputControllerSwitchInfo}
#Import export ".\GameInputDeviceCallback.ahk" {GameInputDeviceCallback}
#Import export ".\GameInputDeviceCapabilities.ahk" {GameInputDeviceCapabilities}
#Import export ".\GameInputDeviceFamily.ahk" {GameInputDeviceFamily}
#Import export ".\GameInputDeviceInfo.ahk" {GameInputDeviceInfo}
#Import export ".\GameInputDeviceStatus.ahk" {GameInputDeviceStatus}
#Import export ".\GameInputEnumerationKind.ahk" {GameInputEnumerationKind}
#Import export ".\GameInputFeedbackAxes.ahk" {GameInputFeedbackAxes}
#Import export ".\GameInputFeedbackEffectState.ahk" {GameInputFeedbackEffectState}
#Import export ".\GameInputFlightStickButtons.ahk" {GameInputFlightStickButtons}
#Import export ".\GameInputFlightStickInfo.ahk" {GameInputFlightStickInfo}
#Import export ".\GameInputFlightStickState.ahk" {GameInputFlightStickState}
#Import export ".\GameInputFocusPolicy.ahk" {GameInputFocusPolicy}
#Import export ".\GameInputForceFeedbackConditionParams.ahk" {GameInputForceFeedbackConditionParams}
#Import export ".\GameInputForceFeedbackConstantParams.ahk" {GameInputForceFeedbackConstantParams}
#Import export ".\GameInputForceFeedbackEffectKind.ahk" {GameInputForceFeedbackEffectKind}
#Import export ".\GameInputForceFeedbackEnvelope.ahk" {GameInputForceFeedbackEnvelope}
#Import export ".\GameInputForceFeedbackMagnitude.ahk" {GameInputForceFeedbackMagnitude}
#Import export ".\GameInputForceFeedbackMotorInfo.ahk" {GameInputForceFeedbackMotorInfo}
#Import export ".\GameInputForceFeedbackParams.ahk" {GameInputForceFeedbackParams}
#Import export ".\GameInputForceFeedbackPeriodicParams.ahk" {GameInputForceFeedbackPeriodicParams}
#Import export ".\GameInputForceFeedbackRampParams.ahk" {GameInputForceFeedbackRampParams}
#Import export ".\GameInputGamepadButtons.ahk" {GameInputGamepadButtons}
#Import export ".\GameInputGamepadInfo.ahk" {GameInputGamepadInfo}
#Import export ".\GameInputGamepadState.ahk" {GameInputGamepadState}
#Import export ".\GameInputHapticFeedbackMotorInfo.ahk" {GameInputHapticFeedbackMotorInfo}
#Import export ".\GameInputHapticFeedbackParams.ahk" {GameInputHapticFeedbackParams}
#Import export ".\GameInputHapticWaveformInfo.ahk" {GameInputHapticWaveformInfo}
#Import export ".\GameInputKeyState.ahk" {GameInputKeyState}
#Import export ".\GameInputKeyboardInfo.ahk" {GameInputKeyboardInfo}
#Import export ".\GameInputKeyboardKind.ahk" {GameInputKeyboardKind}
#Import export ".\GameInputKeyboardLayoutCallback.ahk" {GameInputKeyboardLayoutCallback}
#Import export ".\GameInputKind.ahk" {GameInputKind}
#Import export ".\GameInputLabel.ahk" {GameInputLabel}
#Import export ".\GameInputLocation.ahk" {GameInputLocation}
#Import export ".\GameInputMotionAccuracy.ahk" {GameInputMotionAccuracy}
#Import export ".\GameInputMotionInfo.ahk" {GameInputMotionInfo}
#Import export ".\GameInputMotionState.ahk" {GameInputMotionState}
#Import export ".\GameInputMouseButtons.ahk" {GameInputMouseButtons}
#Import export ".\GameInputMouseInfo.ahk" {GameInputMouseInfo}
#Import export ".\GameInputMouseState.ahk" {GameInputMouseState}
#Import export ".\GameInputRacingWheelButtons.ahk" {GameInputRacingWheelButtons}
#Import export ".\GameInputRacingWheelInfo.ahk" {GameInputRacingWheelInfo}
#Import export ".\GameInputRacingWheelState.ahk" {GameInputRacingWheelState}
#Import export ".\GameInputRawDeviceItemCollectionInfo.ahk" {GameInputRawDeviceItemCollectionInfo}
#Import export ".\GameInputRawDeviceItemCollectionKind.ahk" {GameInputRawDeviceItemCollectionKind}
#Import export ".\GameInputRawDevicePhysicalUnitKind.ahk" {GameInputRawDevicePhysicalUnitKind}
#Import export ".\GameInputRawDeviceReportInfo.ahk" {GameInputRawDeviceReportInfo}
#Import export ".\GameInputRawDeviceReportItemFlags.ahk" {GameInputRawDeviceReportItemFlags}
#Import export ".\GameInputRawDeviceReportItemInfo.ahk" {GameInputRawDeviceReportItemInfo}
#Import export ".\GameInputRawDeviceReportKind.ahk" {GameInputRawDeviceReportKind}
#Import export ".\GameInputReadingCallback.ahk" {GameInputReadingCallback}
#Import export ".\GameInputRumbleMotors.ahk" {GameInputRumbleMotors}
#Import export ".\GameInputRumbleParams.ahk" {GameInputRumbleParams}
#Import export ".\GameInputString.ahk" {GameInputString}
#Import export ".\GameInputSwitchKind.ahk" {GameInputSwitchKind}
#Import export ".\GameInputSwitchPosition.ahk" {GameInputSwitchPosition}
#Import export ".\GameInputSystemButtonCallback.ahk" {GameInputSystemButtonCallback}
#Import export ".\GameInputSystemButtons.ahk" {GameInputSystemButtons}
#Import export ".\GameInputTouchSensorInfo.ahk" {GameInputTouchSensorInfo}
#Import export ".\GameInputTouchShape.ahk" {GameInputTouchShape}
#Import export ".\GameInputTouchState.ahk" {GameInputTouchState}
#Import export ".\GameInputUiNavigationButtons.ahk" {GameInputUiNavigationButtons}
#Import export ".\GameInputUiNavigationInfo.ahk" {GameInputUiNavigationInfo}
#Import export ".\GameInputUiNavigationState.ahk" {GameInputUiNavigationState}
#Import export ".\GameInputUsage.ahk" {GameInputUsage}
#Import export ".\GameInputVersion.ahk" {GameInputVersion}
#Import export ".\IGameInput.ahk" {IGameInput}
#Import export ".\IGameInputDevice.ahk" {IGameInputDevice}
#Import export ".\IGameInputDispatcher.ahk" {IGameInputDispatcher}
#Import export ".\IGameInputForceFeedbackEffect.ahk" {IGameInputForceFeedbackEffect}
#Import export ".\IGameInputRawDeviceReport.ahk" {IGameInputRawDeviceReport}
#Import export ".\IGameInputReading.ahk" {IGameInputReading}
