#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\UI\__Init.ahk" {*}
#Import export ".\ACCESS_MODE.ahk" {ACCESS_MODE}
#Import export ".\ACTRL_ACCESSA.ahk" {ACTRL_ACCESSA}
#Import export ".\ACTRL_ACCESSW.ahk" {ACTRL_ACCESSW}
#Import export ".\ACTRL_ACCESS_ENTRYA.ahk" {ACTRL_ACCESS_ENTRYA}
#Import export ".\ACTRL_ACCESS_ENTRYW.ahk" {ACTRL_ACCESS_ENTRYW}
#Import export ".\ACTRL_ACCESS_ENTRY_ACCESS_FLAGS.ahk" {ACTRL_ACCESS_ENTRY_ACCESS_FLAGS}
#Import export ".\ACTRL_ACCESS_ENTRY_LISTA.ahk" {ACTRL_ACCESS_ENTRY_LISTA}
#Import export ".\ACTRL_ACCESS_ENTRY_LISTW.ahk" {ACTRL_ACCESS_ENTRY_LISTW}
#Import export ".\ACTRL_ACCESS_INFOA.ahk" {ACTRL_ACCESS_INFOA}
#Import export ".\ACTRL_ACCESS_INFOW.ahk" {ACTRL_ACCESS_INFOW}
#Import export ".\ACTRL_CONTROL_INFOA.ahk" {ACTRL_CONTROL_INFOA}
#Import export ".\ACTRL_CONTROL_INFOW.ahk" {ACTRL_CONTROL_INFOW}
#Import export ".\ACTRL_OVERLAPPED.ahk" {ACTRL_OVERLAPPED}
#Import export ".\ACTRL_PROPERTY_ENTRYA.ahk" {ACTRL_PROPERTY_ENTRYA}
#Import export ".\ACTRL_PROPERTY_ENTRYW.ahk" {ACTRL_PROPERTY_ENTRYW}
#Import export ".\AUDIT_IP_ADDRESS.ahk" {AUDIT_IP_ADDRESS}
#Import export ".\AUDIT_OBJECT_TYPE.ahk" {AUDIT_OBJECT_TYPE}
#Import export ".\AUDIT_OBJECT_TYPES.ahk" {AUDIT_OBJECT_TYPES}
#Import export ".\AUDIT_PARAM.ahk" {AUDIT_PARAM}
#Import export ".\AUDIT_PARAMS.ahk" {AUDIT_PARAMS}
#Import export ".\AUDIT_PARAM_TYPE.ahk" {AUDIT_PARAM_TYPE}
#Import export ".\AUTHZ_ACCESS_CHECK_FLAGS.ahk" {AUTHZ_ACCESS_CHECK_FLAGS}
#Import export ".\AUTHZ_ACCESS_CHECK_RESULTS_HANDLE.ahk" {AUTHZ_ACCESS_CHECK_RESULTS_HANDLE}
#Import export ".\AUTHZ_ACCESS_REPLY.ahk" {AUTHZ_ACCESS_REPLY}
#Import export ".\AUTHZ_ACCESS_REQUEST.ahk" {AUTHZ_ACCESS_REQUEST}
#Import export ".\AUTHZ_AUDIT_EVENT_HANDLE.ahk" {AUTHZ_AUDIT_EVENT_HANDLE}
#Import export ".\AUTHZ_AUDIT_EVENT_INFORMATION_CLASS.ahk" {AUTHZ_AUDIT_EVENT_INFORMATION_CLASS}
#Import export ".\AUTHZ_AUDIT_EVENT_TYPE_HANDLE.ahk" {AUTHZ_AUDIT_EVENT_TYPE_HANDLE}
#Import export ".\AUTHZ_AUDIT_EVENT_TYPE_LEGACY.ahk" {AUTHZ_AUDIT_EVENT_TYPE_LEGACY}
#Import export ".\AUTHZ_AUDIT_EVENT_TYPE_OLD.ahk" {AUTHZ_AUDIT_EVENT_TYPE_OLD}
#Import export ".\AUTHZ_AUDIT_EVENT_TYPE_UNION.ahk" {AUTHZ_AUDIT_EVENT_TYPE_UNION}
#Import export ".\AUTHZ_CAP_CHANGE_SUBSCRIPTION_HANDLE.ahk" {AUTHZ_CAP_CHANGE_SUBSCRIPTION_HANDLE}
#Import export ".\AUTHZ_CLIENT_CONTEXT_HANDLE.ahk" {AUTHZ_CLIENT_CONTEXT_HANDLE}
#Import export ".\AUTHZ_CONTEXT_INFORMATION_CLASS.ahk" {AUTHZ_CONTEXT_INFORMATION_CLASS}
#Import export ".\AUTHZ_GENERATE_RESULTS.ahk" {AUTHZ_GENERATE_RESULTS}
#Import export ".\AUTHZ_INITIALIZE_OBJECT_ACCESS_AUDIT_EVENT_FLAGS.ahk" {AUTHZ_INITIALIZE_OBJECT_ACCESS_AUDIT_EVENT_FLAGS}
#Import export ".\AUTHZ_INIT_INFO.ahk" {AUTHZ_INIT_INFO}
#Import export ".\AUTHZ_REGISTRATION_OBJECT_TYPE_NAME_OFFSET.ahk" {AUTHZ_REGISTRATION_OBJECT_TYPE_NAME_OFFSET}
#Import export ".\AUTHZ_RESOURCE_MANAGER_FLAGS.ahk" {AUTHZ_RESOURCE_MANAGER_FLAGS}
#Import export ".\AUTHZ_RESOURCE_MANAGER_HANDLE.ahk" {AUTHZ_RESOURCE_MANAGER_HANDLE}
#Import export ".\AUTHZ_RPC_INIT_INFO_CLIENT.ahk" {AUTHZ_RPC_INIT_INFO_CLIENT}
#Import export ".\AUTHZ_SECURITY_ATTRIBUTES_INFORMATION.ahk" {AUTHZ_SECURITY_ATTRIBUTES_INFORMATION}
#Import export ".\AUTHZ_SECURITY_ATTRIBUTE_FLAGS.ahk" {AUTHZ_SECURITY_ATTRIBUTE_FLAGS}
#Import export ".\AUTHZ_SECURITY_ATTRIBUTE_FQBN_VALUE.ahk" {AUTHZ_SECURITY_ATTRIBUTE_FQBN_VALUE}
#Import export ".\AUTHZ_SECURITY_ATTRIBUTE_OCTET_STRING_VALUE.ahk" {AUTHZ_SECURITY_ATTRIBUTE_OCTET_STRING_VALUE}
#Import export ".\AUTHZ_SECURITY_ATTRIBUTE_OPERATION.ahk" {AUTHZ_SECURITY_ATTRIBUTE_OPERATION}
#Import export ".\AUTHZ_SECURITY_ATTRIBUTE_V1.ahk" {AUTHZ_SECURITY_ATTRIBUTE_V1}
#Import export ".\AUTHZ_SECURITY_EVENT_PROVIDER_HANDLE.ahk" {AUTHZ_SECURITY_EVENT_PROVIDER_HANDLE}
#Import export ".\AUTHZ_SID_OPERATION.ahk" {AUTHZ_SID_OPERATION}
#Import export ".\AUTHZ_SOURCE_SCHEMA_REGISTRATION.ahk" {AUTHZ_SOURCE_SCHEMA_REGISTRATION}
#Import export ".\AZ_PROP_CONSTANTS.ahk" {AZ_PROP_CONSTANTS}
#Import export ".\Apis.ahk" {*}
#Import export ".\AzAuthorizationStore.ahk" {AzAuthorizationStore}
#Import export ".\AzBizRuleContext.ahk" {AzBizRuleContext}
#Import export ".\AzPrincipalLocator.ahk" {AzPrincipalLocator}
#Import export ".\Constants.ahk" {*}
#Import export ".\EXPLICIT_ACCESS_A.ahk" {EXPLICIT_ACCESS_A}
#Import export ".\EXPLICIT_ACCESS_W.ahk" {EXPLICIT_ACCESS_W}
#Import export ".\FN_OBJECT_MGR_FUNCTS.ahk" {FN_OBJECT_MGR_FUNCTS}
#Import export ".\FN_PROGRESS.ahk" {FN_PROGRESS}
#Import export ".\IAzApplication.ahk" {IAzApplication}
#Import export ".\IAzApplication2.ahk" {IAzApplication2}
#Import export ".\IAzApplication3.ahk" {IAzApplication3}
#Import export ".\IAzApplicationGroup.ahk" {IAzApplicationGroup}
#Import export ".\IAzApplicationGroup2.ahk" {IAzApplicationGroup2}
#Import export ".\IAzApplicationGroups.ahk" {IAzApplicationGroups}
#Import export ".\IAzApplications.ahk" {IAzApplications}
#Import export ".\IAzAuthorizationStore.ahk" {IAzAuthorizationStore}
#Import export ".\IAzAuthorizationStore2.ahk" {IAzAuthorizationStore2}
#Import export ".\IAzAuthorizationStore3.ahk" {IAzAuthorizationStore3}
#Import export ".\IAzBizRuleContext.ahk" {IAzBizRuleContext}
#Import export ".\IAzBizRuleInterfaces.ahk" {IAzBizRuleInterfaces}
#Import export ".\IAzBizRuleParameters.ahk" {IAzBizRuleParameters}
#Import export ".\IAzClientContext.ahk" {IAzClientContext}
#Import export ".\IAzClientContext2.ahk" {IAzClientContext2}
#Import export ".\IAzClientContext3.ahk" {IAzClientContext3}
#Import export ".\IAzNameResolver.ahk" {IAzNameResolver}
#Import export ".\IAzObjectPicker.ahk" {IAzObjectPicker}
#Import export ".\IAzOperation.ahk" {IAzOperation}
#Import export ".\IAzOperation2.ahk" {IAzOperation2}
#Import export ".\IAzOperations.ahk" {IAzOperations}
#Import export ".\IAzPrincipalLocator.ahk" {IAzPrincipalLocator}
#Import export ".\IAzRole.ahk" {IAzRole}
#Import export ".\IAzRoleAssignment.ahk" {IAzRoleAssignment}
#Import export ".\IAzRoleAssignments.ahk" {IAzRoleAssignments}
#Import export ".\IAzRoleDefinition.ahk" {IAzRoleDefinition}
#Import export ".\IAzRoleDefinitions.ahk" {IAzRoleDefinitions}
#Import export ".\IAzRoles.ahk" {IAzRoles}
#Import export ".\IAzScope.ahk" {IAzScope}
#Import export ".\IAzScope2.ahk" {IAzScope2}
#Import export ".\IAzScopes.ahk" {IAzScopes}
#Import export ".\IAzTask.ahk" {IAzTask}
#Import export ".\IAzTask2.ahk" {IAzTask2}
#Import export ".\IAzTasks.ahk" {IAzTasks}
#Import export ".\INHERITED_FROMA.ahk" {INHERITED_FROMA}
#Import export ".\INHERITED_FROMW.ahk" {INHERITED_FROMW}
#Import export ".\MULTIPLE_TRUSTEE_OPERATION.ahk" {MULTIPLE_TRUSTEE_OPERATION}
#Import export ".\OBJECTS_AND_NAME_A.ahk" {OBJECTS_AND_NAME_A}
#Import export ".\OBJECTS_AND_NAME_W.ahk" {OBJECTS_AND_NAME_W}
#Import export ".\OBJECTS_AND_SID.ahk" {OBJECTS_AND_SID}
#Import export ".\PFN_AUTHZ_COMPUTE_DYNAMIC_GROUPS.ahk" {PFN_AUTHZ_COMPUTE_DYNAMIC_GROUPS}
#Import export ".\PFN_AUTHZ_DYNAMIC_ACCESS_CHECK.ahk" {PFN_AUTHZ_DYNAMIC_ACCESS_CHECK}
#Import export ".\PFN_AUTHZ_FREE_CENTRAL_ACCESS_POLICY.ahk" {PFN_AUTHZ_FREE_CENTRAL_ACCESS_POLICY}
#Import export ".\PFN_AUTHZ_FREE_DYNAMIC_GROUPS.ahk" {PFN_AUTHZ_FREE_DYNAMIC_GROUPS}
#Import export ".\PFN_AUTHZ_GET_CENTRAL_ACCESS_POLICY.ahk" {PFN_AUTHZ_GET_CENTRAL_ACCESS_POLICY}
#Import export ".\PROG_INVOKE_SETTING.ahk" {PROG_INVOKE_SETTING}
#Import export ".\SE_OBJECT_TYPE.ahk" {SE_OBJECT_TYPE}
#Import export ".\TREE_SEC_INFO.ahk" {TREE_SEC_INFO}
#Import export ".\TRUSTEE_A.ahk" {TRUSTEE_A}
#Import export ".\TRUSTEE_ACCESSA.ahk" {TRUSTEE_ACCESSA}
#Import export ".\TRUSTEE_ACCESSW.ahk" {TRUSTEE_ACCESSW}
#Import export ".\TRUSTEE_FORM.ahk" {TRUSTEE_FORM}
#Import export ".\TRUSTEE_TYPE.ahk" {TRUSTEE_TYPE}
#Import export ".\TRUSTEE_W.ahk" {TRUSTEE_W}
