#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\Com\IUnknown.ahk

/**
 * Use the IWbemEventProvider interface to initiate communication with an event provider. Windows Management calls the provider's implementation of this interface when a consumer has indicated interest in receiving events generated by the provider.
 * @see https://docs.microsoft.com/windows/win32/api//wbemprov/nn-wbemprov-iwbemeventprovider
 * @namespace Windows.Win32.System.Wmi
 * @version v4.0.30319
 */
class IWbemEventProvider extends IUnknown{
    /**
     * The interface identifier for IWbemEventProvider
     * @type {Guid}
     */
    static IID => Guid("{e245105b-b06e-11d0-ad61-00c04fd8fdff}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 3

    /**
     * 
     * @param {Pointer<IWbemObjectSink>} pSink 
     * @param {Integer} lFlags 
     * @returns {HRESULT} 
     */
    ProvideEvents(pSink, lFlags) {
        result := ComCall(3, this, "ptr", pSink, "int", lFlags, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }
}
