#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\Guid.ahk" { Guid }
#Import "..\..\Foundation\PWSTR.ahk" { PWSTR }
#Import "..\..\Foundation\HRESULT.ahk" { HRESULT }
#Import "..\Com\IUnknown.ahk" { IUnknown }

/**
 * Provides an entry point through which a WMI Query Language (WQL) query can be parsed.
 * @see https://learn.microsoft.com/windows/win32/api/wmiutils/nn-wmiutils-iwbemquery
 * @namespace Windows.Win32.System.Wmi
 */
export default struct IWbemQuery extends IUnknown {
    /**
     * The interface identifier for IWbemQuery
     * @type {Guid}
     */
    static IID := Guid("{81166f58-dd98-11d3-a120-00105a1f515a}")

    /**
     * The class identifier for WbemQuery
     * @type {Guid}
     */
    static CLSID := Guid("{eac8a024-21e2-4523-ad73-a71a0aa2f56a}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for IWbemQuery interfaces
    */
    struct Vtbl extends IUnknown.Vtbl {
        Empty                : IntPtr
        SetLanguageFeatures  : IntPtr
        TestLanguageFeatures : IntPtr
        Parse                : IntPtr
        GetAnalysis          : IntPtr
        FreeMemory           : IntPtr
        GetQueryInfo         : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := IWbemQuery.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * The IWbemQuery::Empty method frees the memory that the parser is holding.
     * @returns {HRESULT} This method returns an <b>HRESULT</b> indicating the status of the method call.
     * @see https://learn.microsoft.com/windows/win32/api/wmiutils/nf-wmiutils-iwbemquery-empty
     */
    Empty() {
        result := ComCall(3, this, "HRESULT")
        return result
    }

    /**
     * Provides an entry point through which a WMI Query Language (WQL) query can be parsed.
     * @param {Integer} uFlags 
     * @param {Integer} uArraySize 
     * @param {Pointer<Integer>} puFeatures 
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/windows/win32/api/wmiutils/nn-wmiutils-iwbemquery
     */
    SetLanguageFeatures(uFlags, uArraySize, puFeatures) {
        puFeaturesMarshal := puFeatures is VarRef ? "uint*" : "ptr"

        result := ComCall(4, this, "uint", uFlags, "uint", uArraySize, puFeaturesMarshal, puFeatures, "HRESULT")
        return result
    }

    /**
     * Provides an entry point through which a WMI Query Language (WQL) query can be parsed.
     * @param {Integer} uFlags 
     * @param {Pointer<Integer>} uArraySize 
     * @returns {Integer} 
     * @see https://learn.microsoft.com/windows/win32/api/wmiutils/nn-wmiutils-iwbemquery
     */
    TestLanguageFeatures(uFlags, uArraySize) {
        uArraySizeMarshal := uArraySize is VarRef ? "uint*" : "ptr"

        result := ComCall(5, this, "uint", uFlags, uArraySizeMarshal, uArraySize, "uint*", &puFeatures := 0, "HRESULT")
        return puFeatures
    }

    /**
     * Parses a query string.
     * @param {PWSTR} pszLang Language of the query. Must be either "WQL" or "SQL" (case-sensitive). Any other value will result in the method failing and <b>WBEM_E_INVALID_PARAMETER</b> being returned.
     * @param {PWSTR} pszQuery Valid WQL or SQL WMI query.
     * @param {Integer} uFlags Reserved for future use. Must be 0 (zero).
     * @returns {HRESULT} This method returns an <b>HRESULT</b> indicating the status of the method call.
     * @see https://learn.microsoft.com/windows/win32/api/wmiutils/nf-wmiutils-iwbemquery-parse
     */
    Parse(pszLang, pszQuery, uFlags) {
        pszLang := pszLang is String ? StrPtr(pszLang) : pszLang
        pszQuery := pszQuery is String ? StrPtr(pszQuery) : pszQuery

        result := ComCall(6, this, "ptr", pszLang, "ptr", pszQuery, "uint", uFlags, "HRESULT")
        return result
    }

    /**
     * Gets the results of a successful query parse.
     * @param {Integer} uAnalysisType Type of analysis to get.
     * @param {Integer} uFlags Reserved for future use.
     * @returns {Pointer<Void>} Pointer to the analysis generated by a call to 
     * <b>IWbemQuery::GetAnalysis</b>. It is important to free up this memory by calling 
     * <a href="https://docs.microsoft.com/windows/desktop/api/wmiutils/nf-wmiutils-iwbemquery-freememory">IWbemQuery::FreeMemory</a>.
     * @see https://learn.microsoft.com/windows/win32/api/wmiutils/nf-wmiutils-iwbemquery-getanalysis
     */
    GetAnalysis(uAnalysisType, uFlags) {
        result := ComCall(7, this, "uint", uAnalysisType, "uint", uFlags, "ptr*", &pAnalysis := 0, "HRESULT")
        return pAnalysis
    }

    /**
     * The IWbemQuery::FreeMemory method frees the memory that the parser returns to a caller in a previous call to GetAnalysis.
     * @param {Pointer<Void>} pMem Pointer to the memory to be freed.
     * @returns {HRESULT} This method returns an <b>HRESULT</b> indicating the status of the method call.
     * @see https://learn.microsoft.com/windows/win32/api/wmiutils/nf-wmiutils-iwbemquery-freememory
     */
    FreeMemory(pMem) {
        pMemMarshal := pMem is VarRef ? "ptr" : "ptr"

        result := ComCall(8, this, pMemMarshal, pMem, "HRESULT")
        return result
    }

    /**
     * Provides an entry point through which a WMI Query Language (WQL) query can be parsed.
     * @param {Integer} uAnalysisType 
     * @param {Integer} uInfoId 
     * @param {Integer} uBufSize 
     * @returns {Void} 
     * @see https://learn.microsoft.com/windows/win32/api/wmiutils/nn-wmiutils-iwbemquery
     */
    GetQueryInfo(uAnalysisType, uInfoId, uBufSize) {
        result := ComCall(9, this, "uint", uAnalysisType, "uint", uInfoId, "uint", uBufSize, "ptr", &pDestBuf := 0, "HRESULT")
        return pDestBuf
    }

    Query(iid) {
        if (IWbemQuery.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.Empty := CallbackCreate(GetMethod(implObj, "Empty"), flags, 1)
        this.vtbl.SetLanguageFeatures := CallbackCreate(GetMethod(implObj, "SetLanguageFeatures"), flags, 4)
        this.vtbl.TestLanguageFeatures := CallbackCreate(GetMethod(implObj, "TestLanguageFeatures"), flags, 4)
        this.vtbl.Parse := CallbackCreate(GetMethod(implObj, "Parse"), flags, 4)
        this.vtbl.GetAnalysis := CallbackCreate(GetMethod(implObj, "GetAnalysis"), flags, 4)
        this.vtbl.FreeMemory := CallbackCreate(GetMethod(implObj, "FreeMemory"), flags, 2)
        this.vtbl.GetQueryInfo := CallbackCreate(GetMethod(implObj, "GetQueryInfo"), flags, 5)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.Empty)
        CallbackFree(this.vtbl.SetLanguageFeatures)
        CallbackFree(this.vtbl.TestLanguageFeatures)
        CallbackFree(this.vtbl.Parse)
        CallbackFree(this.vtbl.GetAnalysis)
        CallbackFree(this.vtbl.FreeMemory)
        CallbackFree(this.vtbl.GetQueryInfo)
    }
}
