#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\Guid.ahk" { Guid }
#Import "..\..\Foundation\HRESULT.ahk" { HRESULT }
#Import "..\Com\IUnknown.ahk" { IUnknown }
#Import ".\IWbemObjectSink.ahk" { IWbemObjectSink }

/**
 * Use the IWbemEventProvider interface to initiate communication with an event provider. Windows Management calls the provider's implementation of this interface when a consumer has indicated interest in receiving events generated by the provider.
 * @see https://learn.microsoft.com/windows/win32/api/wbemprov/nn-wbemprov-iwbemeventprovider
 * @namespace Windows.Win32.System.Wmi
 */
export default struct IWbemEventProvider extends IUnknown {
    /**
     * The interface identifier for IWbemEventProvider
     * @type {Guid}
     */
    static IID := Guid("{e245105b-b06e-11d0-ad61-00c04fd8fdff}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for IWbemEventProvider interfaces
    */
    struct Vtbl extends IUnknown.Vtbl {
        ProvideEvents : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := IWbemEventProvider.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * Windows Management calls the IWbemEventProvider::ProvideEvents method to signal an event provider to begin delivery of its events.
     * @remarks
     * Windows Management calls this method to activate the provider. Windows Management gives an 
     * <a href="https://docs.microsoft.com/windows/desktop/WmiSdk/iwbemobjectsink">IWbemObjectSink</a> pointer to the event provider. The provider must call the <b>AddRef</b> method using this pointer to increment the reference count, and then return from the call.
     * 
     * Typically, the provider will create an independent thread, and deliver the events as they occur to the provided sink interface.
     * 
     * The provider is not permitted to block this call for more than a few seconds, but it must return as quickly as possible to Windows Management.
     * @param {IWbemObjectSink} pSink Pointer to the object sink to which the provider will deliver its events. In an event provider implementation, you should use the 
     * <a href="https://docs.microsoft.com/windows/desktop/api/wbemcli/nf-wbemcli-iwbemobjectsink-indicate">IWbemObjectSink::Indicate</a> method to send events through <i>pSink</i>. This is in contrast to other providers that may use the 
     * <a href="https://docs.microsoft.com/windows/desktop/api/wbemcli/nf-wbemcli-iwbemobjectsink-setstatus">SetStatus</a> method: The 
     * <b>ProvideEvents</b> method should use only 
     * <b>Indicate</b> to update a sink.
     * @param {Integer} lFlags Reserved. This parameter must be 0.
     * @returns {HRESULT} This method returns an <b>HRESULT</b> indicating the status of the method call. The following list lists the value contained within an <b>HRESULT</b>.
     * @see https://learn.microsoft.com/windows/win32/api/wbemprov/nf-wbemprov-iwbemeventprovider-provideevents
     */
    ProvideEvents(pSink, lFlags) {
        result := ComCall(3, this, "ptr", pSink, "int", lFlags, "HRESULT")
        return result
    }

    Query(iid) {
        if (IWbemEventProvider.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.ProvideEvents := CallbackCreate(GetMethod(implObj, "ProvideEvents"), flags, 3)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.ProvideEvents)
    }
}
