#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\Com\IUnknown.ahk

/**
 * Use the IWbemEventProvider interface to initiate communication with an event provider. Windows Management calls the provider's implementation of this interface when a consumer has indicated interest in receiving events generated by the provider.
 * @see https://learn.microsoft.com/windows/win32/api//content/wbemprov/nn-wbemprov-iwbemeventprovider
 * @namespace Windows.Win32.System.Wmi
 * @version v4.0.30319
 */
class IWbemEventProvider extends IUnknown{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IWbemEventProvider
     * @type {Guid}
     */
    static IID => Guid("{e245105b-b06e-11d0-ad61-00c04fd8fdff}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 3

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["ProvideEvents"]

    /**
     * Windows Management calls the IWbemEventProvider::ProvideEvents method to signal an event provider to begin delivery of its events.
     * @remarks
     * Windows Management calls this method to activate the provider. Windows Management gives an 
     * <a href="https://docs.microsoft.com/windows/desktop/WmiSdk/iwbemobjectsink">IWbemObjectSink</a> pointer to the event provider. The provider must call the <b>AddRef</b> method using this pointer to increment the reference count, and then return from the call.
     * 
     * Typically, the provider will create an independent thread, and deliver the events as they occur to the provided sink interface.
     * 
     * The provider is not permitted to block this call for more than a few seconds, but it must return as quickly as possible to Windows Management.
     * @param {IWbemObjectSink} pSink Pointer to the object sink to which the provider will deliver its events. In an event provider implementation, you should use the 
     * <a href="https://docs.microsoft.com/windows/desktop/api/wbemcli/nf-wbemcli-iwbemobjectsink-indicate">IWbemObjectSink::Indicate</a> method to send events through <i>pSink</i>. This is in contrast to other providers that may use the 
     * <a href="https://docs.microsoft.com/windows/desktop/api/wbemcli/nf-wbemcli-iwbemobjectsink-setstatus">SetStatus</a> method: The 
     * <b>ProvideEvents</b> method should use only 
     * <b>Indicate</b> to update a sink.
     * @param {Integer} lFlags Reserved. This parameter must be 0.
     * @returns {HRESULT} This method returns an <b>HRESULT</b> indicating the status of the method call. The following list lists the value contained within an <b>HRESULT</b>.
     * @see https://learn.microsoft.com/windows/win32/api//content/wbemprov/nf-wbemprov-iwbemeventprovider-provideevents
     */
    ProvideEvents(pSink, lFlags) {
        result := ComCall(3, this, "ptr", pSink, "int", lFlags, "int")
        if(result != 0) {
            throw OSError(A_LastError || result)
        }

        return result
    }
}
