#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\D2D\__Init.ahk" {*}
#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\IWICBitmap.ahk" {IWICBitmap}
#Import export ".\IWICBitmapClipper.ahk" {IWICBitmapClipper}
#Import export ".\IWICBitmapCodecInfo.ahk" {IWICBitmapCodecInfo}
#Import export ".\IWICBitmapCodecProgressNotification.ahk" {IWICBitmapCodecProgressNotification}
#Import export ".\IWICBitmapDecoder.ahk" {IWICBitmapDecoder}
#Import export ".\IWICBitmapDecoderInfo.ahk" {IWICBitmapDecoderInfo}
#Import export ".\IWICBitmapEncoder.ahk" {IWICBitmapEncoder}
#Import export ".\IWICBitmapEncoderInfo.ahk" {IWICBitmapEncoderInfo}
#Import export ".\IWICBitmapFlipRotator.ahk" {IWICBitmapFlipRotator}
#Import export ".\IWICBitmapFrameChainReader.ahk" {IWICBitmapFrameChainReader}
#Import export ".\IWICBitmapFrameChainWriter.ahk" {IWICBitmapFrameChainWriter}
#Import export ".\IWICBitmapFrameDecode.ahk" {IWICBitmapFrameDecode}
#Import export ".\IWICBitmapFrameEncode.ahk" {IWICBitmapFrameEncode}
#Import export ".\IWICBitmapLock.ahk" {IWICBitmapLock}
#Import export ".\IWICBitmapScaler.ahk" {IWICBitmapScaler}
#Import export ".\IWICBitmapSource.ahk" {IWICBitmapSource}
#Import export ".\IWICBitmapSourceTransform.ahk" {IWICBitmapSourceTransform}
#Import export ".\IWICBitmapSourceTransform2.ahk" {IWICBitmapSourceTransform2}
#Import export ".\IWICBitmapToneMapper.ahk" {IWICBitmapToneMapper}
#Import export ".\IWICColorContext.ahk" {IWICColorContext}
#Import export ".\IWICColorTransform.ahk" {IWICColorTransform}
#Import export ".\IWICComponentFactory.ahk" {IWICComponentFactory}
#Import export ".\IWICComponentInfo.ahk" {IWICComponentInfo}
#Import export ".\IWICD3DTextureSource.ahk" {IWICD3DTextureSource}
#Import export ".\IWICDdsDecoder.ahk" {IWICDdsDecoder}
#Import export ".\IWICDdsEncoder.ahk" {IWICDdsEncoder}
#Import export ".\IWICDdsFrameDecode.ahk" {IWICDdsFrameDecode}
#Import export ".\IWICDevelopRaw.ahk" {IWICDevelopRaw}
#Import export ".\IWICDevelopRawNotificationCallback.ahk" {IWICDevelopRawNotificationCallback}
#Import export ".\IWICDisplayAdaptationControl.ahk" {IWICDisplayAdaptationControl}
#Import export ".\IWICDisplayAdaptationControl2.ahk" {IWICDisplayAdaptationControl2}
#Import export ".\IWICEnumMetadataItem.ahk" {IWICEnumMetadataItem}
#Import export ".\IWICFastMetadataEncoder.ahk" {IWICFastMetadataEncoder}
#Import export ".\IWICFormatConverter.ahk" {IWICFormatConverter}
#Import export ".\IWICFormatConverterInfo.ahk" {IWICFormatConverterInfo}
#Import export ".\IWICImagingFactory.ahk" {IWICImagingFactory}
#Import export ".\IWICJpegFrameDecode.ahk" {IWICJpegFrameDecode}
#Import export ".\IWICJpegFrameEncode.ahk" {IWICJpegFrameEncode}
#Import export ".\IWICMetadataBlockReader.ahk" {IWICMetadataBlockReader}
#Import export ".\IWICMetadataBlockWriter.ahk" {IWICMetadataBlockWriter}
#Import export ".\IWICMetadataHandlerInfo.ahk" {IWICMetadataHandlerInfo}
#Import export ".\IWICMetadataQueryReader.ahk" {IWICMetadataQueryReader}
#Import export ".\IWICMetadataQueryWriter.ahk" {IWICMetadataQueryWriter}
#Import export ".\IWICMetadataReader.ahk" {IWICMetadataReader}
#Import export ".\IWICMetadataReaderInfo.ahk" {IWICMetadataReaderInfo}
#Import export ".\IWICMetadataWriter.ahk" {IWICMetadataWriter}
#Import export ".\IWICMetadataWriterInfo.ahk" {IWICMetadataWriterInfo}
#Import export ".\IWICPalette.ahk" {IWICPalette}
#Import export ".\IWICPersistStream.ahk" {IWICPersistStream}
#Import export ".\IWICPixelFormatInfo.ahk" {IWICPixelFormatInfo}
#Import export ".\IWICPixelFormatInfo2.ahk" {IWICPixelFormatInfo2}
#Import export ".\IWICPlanarBitmapFrameEncode.ahk" {IWICPlanarBitmapFrameEncode}
#Import export ".\IWICPlanarBitmapSourceTransform.ahk" {IWICPlanarBitmapSourceTransform}
#Import export ".\IWICPlanarFormatConverter.ahk" {IWICPlanarFormatConverter}
#Import export ".\IWICProgressCallback.ahk" {IWICProgressCallback}
#Import export ".\IWICProgressiveLevelControl.ahk" {IWICProgressiveLevelControl}
#Import export ".\IWICStream.ahk" {IWICStream}
#Import export ".\IWICStreamProvider.ahk" {IWICStreamProvider}
#Import export ".\PFNProgressNotification.ahk" {PFNProgressNotification}
#Import export ".\WIC8BIMIptcDigestProperties.ahk" {WIC8BIMIptcDigestProperties}
#Import export ".\WIC8BIMIptcProperties.ahk" {WIC8BIMIptcProperties}
#Import export ".\WIC8BIMResolutionInfoProperties.ahk" {WIC8BIMResolutionInfoProperties}
#Import export ".\WICBitmapAlphaChannelOption.ahk" {WICBitmapAlphaChannelOption}
#Import export ".\WICBitmapChainType.ahk" {WICBitmapChainType}
#Import export ".\WICBitmapCreateCacheOption.ahk" {WICBitmapCreateCacheOption}
#Import export ".\WICBitmapDecoderCapabilities.ahk" {WICBitmapDecoderCapabilities}
#Import export ".\WICBitmapDitherType.ahk" {WICBitmapDitherType}
#Import export ".\WICBitmapEncoderCacheOption.ahk" {WICBitmapEncoderCacheOption}
#Import export ".\WICBitmapInterpolationMode.ahk" {WICBitmapInterpolationMode}
#Import export ".\WICBitmapLockFlags.ahk" {WICBitmapLockFlags}
#Import export ".\WICBitmapPaletteType.ahk" {WICBitmapPaletteType}
#Import export ".\WICBitmapPattern.ahk" {WICBitmapPattern}
#Import export ".\WICBitmapPlane.ahk" {WICBitmapPlane}
#Import export ".\WICBitmapPlaneDescription.ahk" {WICBitmapPlaneDescription}
#Import export ".\WICBitmapToneMappingMode.ahk" {WICBitmapToneMappingMode}
#Import export ".\WICBitmapTransformOptions.ahk" {WICBitmapTransformOptions}
#Import export ".\WICColorContextType.ahk" {WICColorContextType}
#Import export ".\WICComponentEnumerateOptions.ahk" {WICComponentEnumerateOptions}
#Import export ".\WICComponentSigning.ahk" {WICComponentSigning}
#Import export ".\WICComponentType.ahk" {WICComponentType}
#Import export ".\WICDdsAlphaMode.ahk" {WICDdsAlphaMode}
#Import export ".\WICDdsDimension.ahk" {WICDdsDimension}
#Import export ".\WICDdsFormatInfo.ahk" {WICDdsFormatInfo}
#Import export ".\WICDdsParameters.ahk" {WICDdsParameters}
#Import export ".\WICDecodeOptions.ahk" {WICDecodeOptions}
#Import export ".\WICGainMapProperties.ahk" {WICGainMapProperties}
#Import export ".\WICGifApplicationExtensionProperties.ahk" {WICGifApplicationExtensionProperties}
#Import export ".\WICGifCommentExtensionProperties.ahk" {WICGifCommentExtensionProperties}
#Import export ".\WICGifGraphicControlExtensionProperties.ahk" {WICGifGraphicControlExtensionProperties}
#Import export ".\WICGifImageDescriptorProperties.ahk" {WICGifImageDescriptorProperties}
#Import export ".\WICGifLogicalScreenDescriptorProperties.ahk" {WICGifLogicalScreenDescriptorProperties}
#Import export ".\WICHeifCompressionOption.ahk" {WICHeifCompressionOption}
#Import export ".\WICHeifHdrProperties.ahk" {WICHeifHdrProperties}
#Import export ".\WICHeifProperties.ahk" {WICHeifProperties}
#Import export ".\WICImageParameters.ahk" {WICImageParameters}
#Import export ".\WICJpegChrominanceProperties.ahk" {WICJpegChrominanceProperties}
#Import export ".\WICJpegCommentProperties.ahk" {WICJpegCommentProperties}
#Import export ".\WICJpegFrameHeader.ahk" {WICJpegFrameHeader}
#Import export ".\WICJpegIndexingOptions.ahk" {WICJpegIndexingOptions}
#Import export ".\WICJpegLuminanceProperties.ahk" {WICJpegLuminanceProperties}
#Import export ".\WICJpegScanHeader.ahk" {WICJpegScanHeader}
#Import export ".\WICJpegScanType.ahk" {WICJpegScanType}
#Import export ".\WICJpegTransferMatrix.ahk" {WICJpegTransferMatrix}
#Import export ".\WICJpegXLAnimFrameProperties.ahk" {WICJpegXLAnimFrameProperties}
#Import export ".\WICJpegXLAnimProperties.ahk" {WICJpegXLAnimProperties}
#Import export ".\WICJpegYCrCbSubsamplingOption.ahk" {WICJpegYCrCbSubsamplingOption}
#Import export ".\WICMetadataCreationOptions.ahk" {WICMetadataCreationOptions}
#Import export ".\WICMetadataHeader.ahk" {WICMetadataHeader}
#Import export ".\WICMetadataPattern.ahk" {WICMetadataPattern}
#Import export ".\WICNamedWhitePoint.ahk" {WICNamedWhitePoint}
#Import export ".\WICPersistOptions.ahk" {WICPersistOptions}
#Import export ".\WICPixelFormatNumericRepresentation.ahk" {WICPixelFormatNumericRepresentation}
#Import export ".\WICPlanarOptions.ahk" {WICPlanarOptions}
#Import export ".\WICPngBkgdProperties.ahk" {WICPngBkgdProperties}
#Import export ".\WICPngChrmProperties.ahk" {WICPngChrmProperties}
#Import export ".\WICPngFilterOption.ahk" {WICPngFilterOption}
#Import export ".\WICPngGamaProperties.ahk" {WICPngGamaProperties}
#Import export ".\WICPngHistProperties.ahk" {WICPngHistProperties}
#Import export ".\WICPngIccpProperties.ahk" {WICPngIccpProperties}
#Import export ".\WICPngItxtProperties.ahk" {WICPngItxtProperties}
#Import export ".\WICPngSrgbProperties.ahk" {WICPngSrgbProperties}
#Import export ".\WICPngTimeProperties.ahk" {WICPngTimeProperties}
#Import export ".\WICProgressNotification.ahk" {WICProgressNotification}
#Import export ".\WICProgressOperation.ahk" {WICProgressOperation}
#Import export ".\WICRawCapabilities.ahk" {WICRawCapabilities}
#Import export ".\WICRawCapabilitiesInfo.ahk" {WICRawCapabilitiesInfo}
#Import export ".\WICRawParameterSet.ahk" {WICRawParameterSet}
#Import export ".\WICRawRenderMode.ahk" {WICRawRenderMode}
#Import export ".\WICRawRotationCapabilities.ahk" {WICRawRotationCapabilities}
#Import export ".\WICRawToneCurve.ahk" {WICRawToneCurve}
#Import export ".\WICRawToneCurvePoint.ahk" {WICRawToneCurvePoint}
#Import export ".\WICRect.ahk" {WICRect}
#Import export ".\WICSectionAccessLevel.ahk" {WICSectionAccessLevel}
#Import export ".\WICTiffCompressionOption.ahk" {WICTiffCompressionOption}
#Import export ".\WICWebpAnimProperties.ahk" {WICWebpAnimProperties}
#Import export ".\WICWebpAnmfProperties.ahk" {WICWebpAnmfProperties}
