#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\LPMAPIADDRESS.ahk" {LPMAPIADDRESS}
#Import export ".\LPMAPIDELETEMAIL.ahk" {LPMAPIDELETEMAIL}
#Import export ".\LPMAPIDETAILS.ahk" {LPMAPIDETAILS}
#Import export ".\LPMAPIFINDNEXT.ahk" {LPMAPIFINDNEXT}
#Import export ".\LPMAPIFREEBUFFER.ahk" {LPMAPIFREEBUFFER}
#Import export ".\LPMAPILOGOFF.ahk" {LPMAPILOGOFF}
#Import export ".\LPMAPILOGON.ahk" {LPMAPILOGON}
#Import export ".\LPMAPIREADMAIL.ahk" {LPMAPIREADMAIL}
#Import export ".\LPMAPIRESOLVENAME.ahk" {LPMAPIRESOLVENAME}
#Import export ".\LPMAPISAVEMAIL.ahk" {LPMAPISAVEMAIL}
#Import export ".\LPMAPISENDDOCUMENTS.ahk" {LPMAPISENDDOCUMENTS}
#Import export ".\LPMAPISENDMAIL.ahk" {LPMAPISENDMAIL}
#Import export ".\LPMAPISENDMAILW.ahk" {LPMAPISENDMAILW}
#Import export ".\MapiFileDesc.ahk" {MapiFileDesc}
#Import export ".\MapiFileDescW.ahk" {MapiFileDescW}
#Import export ".\MapiFileTagExt.ahk" {MapiFileTagExt}
#Import export ".\MapiMessage.ahk" {MapiMessage}
#Import export ".\MapiMessageW.ahk" {MapiMessageW}
#Import export ".\MapiRecipDesc.ahk" {MapiRecipDesc}
#Import export ".\MapiRecipDescW.ahk" {MapiRecipDescW}
