#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\CONNECTION.ahk" {CONNECTION}
#Import export ".\CONNECTIONLIST.ahk" {CONNECTIONLIST}
#Import export ".\Constants.ahk" {*}
#Import export ".\DIRECTSOUNDDEVICE_DATAFLOW.ahk" {DIRECTSOUNDDEVICE_DATAFLOW}
#Import export ".\DIRECTSOUNDDEVICE_TYPE.ahk" {DIRECTSOUNDDEVICE_TYPE}
#Import export ".\DLSHEADER.ahk" {DLSHEADER}
#Import export ".\DLSID.ahk" {DLSID}
#Import export ".\DLSVERSION.ahk" {DLSVERSION}
#Import export ".\DMUS_ARTICPARAMS.ahk" {DMUS_ARTICPARAMS}
#Import export ".\DMUS_ARTICULATION.ahk" {DMUS_ARTICULATION}
#Import export ".\DMUS_ARTICULATION2.ahk" {DMUS_ARTICULATION2}
#Import export ".\DMUS_BUFFERDESC.ahk" {DMUS_BUFFERDESC}
#Import export ".\DMUS_CLOCKINFO7.ahk" {DMUS_CLOCKINFO7}
#Import export ".\DMUS_CLOCKINFO8.ahk" {DMUS_CLOCKINFO8}
#Import export ".\DMUS_CLOCKTYPE.ahk" {DMUS_CLOCKTYPE}
#Import export ".\DMUS_COPYRIGHT.ahk" {DMUS_COPYRIGHT}
#Import export ".\DMUS_DOWNLOADINFO.ahk" {DMUS_DOWNLOADINFO}
#Import export ".\DMUS_EVENTHEADER.ahk" {DMUS_EVENTHEADER}
#Import export ".\DMUS_EXTENSIONCHUNK.ahk" {DMUS_EXTENSIONCHUNK}
#Import export ".\DMUS_INSTRUMENT.ahk" {DMUS_INSTRUMENT}
#Import export ".\DMUS_LFOPARAMS.ahk" {DMUS_LFOPARAMS}
#Import export ".\DMUS_MSCPARAMS.ahk" {DMUS_MSCPARAMS}
#Import export ".\DMUS_NOTERANGE.ahk" {DMUS_NOTERANGE}
#Import export ".\DMUS_OFFSETTABLE.ahk" {DMUS_OFFSETTABLE}
#Import export ".\DMUS_PEGPARAMS.ahk" {DMUS_PEGPARAMS}
#Import export ".\DMUS_PORTCAPS.ahk" {DMUS_PORTCAPS}
#Import export ".\DMUS_PORTPARAMS7.ahk" {DMUS_PORTPARAMS7}
#Import export ".\DMUS_PORTPARAMS8.ahk" {DMUS_PORTPARAMS8}
#Import export ".\DMUS_REGION.ahk" {DMUS_REGION}
#Import export ".\DMUS_SYNTHSTATS.ahk" {DMUS_SYNTHSTATS}
#Import export ".\DMUS_SYNTHSTATS8.ahk" {DMUS_SYNTHSTATS8}
#Import export ".\DMUS_VEGPARAMS.ahk" {DMUS_VEGPARAMS}
#Import export ".\DMUS_VOICE_STATE.ahk" {DMUS_VOICE_STATE}
#Import export ".\DMUS_WAVE.ahk" {DMUS_WAVE}
#Import export ".\DMUS_WAVEARTDL.ahk" {DMUS_WAVEARTDL}
#Import export ".\DMUS_WAVEDATA.ahk" {DMUS_WAVEDATA}
#Import export ".\DMUS_WAVEDL.ahk" {DMUS_WAVEDL}
#Import export ".\DMUS_WAVES_REVERB_PARAMS.ahk" {DMUS_WAVES_REVERB_PARAMS}
#Import export ".\DSPROPERTY_DIRECTSOUNDDEVICE.ahk" {DSPROPERTY_DIRECTSOUNDDEVICE}
#Import export ".\DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_1_DATA.ahk" {DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_1_DATA}
#Import export ".\DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_A_DATA.ahk" {DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_A_DATA}
#Import export ".\DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_W_DATA.ahk" {DSPROPERTY_DIRECTSOUNDDEVICE_DESCRIPTION_W_DATA}
#Import export ".\DSPROPERTY_DIRECTSOUNDDEVICE_ENUMERATE_1_DATA.ahk" {DSPROPERTY_DIRECTSOUNDDEVICE_ENUMERATE_1_DATA}
#Import export ".\DSPROPERTY_DIRECTSOUNDDEVICE_ENUMERATE_A_DATA.ahk" {DSPROPERTY_DIRECTSOUNDDEVICE_ENUMERATE_A_DATA}
#Import export ".\DSPROPERTY_DIRECTSOUNDDEVICE_ENUMERATE_W_DATA.ahk" {DSPROPERTY_DIRECTSOUNDDEVICE_ENUMERATE_W_DATA}
#Import export ".\DSPROPERTY_DIRECTSOUNDDEVICE_WAVEDEVICEMAPPING_A_DATA.ahk" {DSPROPERTY_DIRECTSOUNDDEVICE_WAVEDEVICEMAPPING_A_DATA}
#Import export ".\DSPROPERTY_DIRECTSOUNDDEVICE_WAVEDEVICEMAPPING_W_DATA.ahk" {DSPROPERTY_DIRECTSOUNDDEVICE_WAVEDEVICEMAPPING_W_DATA}
#Import export ".\DVAudInfo.ahk" {DVAudInfo}
#Import export ".\IDirectMusic.ahk" {IDirectMusic}
#Import export ".\IDirectMusic8.ahk" {IDirectMusic8}
#Import export ".\IDirectMusicBuffer.ahk" {IDirectMusicBuffer}
#Import export ".\IDirectMusicCollection.ahk" {IDirectMusicCollection}
#Import export ".\IDirectMusicDownload.ahk" {IDirectMusicDownload}
#Import export ".\IDirectMusicDownloadedInstrument.ahk" {IDirectMusicDownloadedInstrument}
#Import export ".\IDirectMusicInstrument.ahk" {IDirectMusicInstrument}
#Import export ".\IDirectMusicPort.ahk" {IDirectMusicPort}
#Import export ".\IDirectMusicPortDownload.ahk" {IDirectMusicPortDownload}
#Import export ".\IDirectMusicSynth.ahk" {IDirectMusicSynth}
#Import export ".\IDirectMusicSynth8.ahk" {IDirectMusicSynth8}
#Import export ".\IDirectMusicSynthSink.ahk" {IDirectMusicSynthSink}
#Import export ".\IDirectMusicThru.ahk" {IDirectMusicThru}
#Import export ".\INSTHEADER.ahk" {INSTHEADER}
#Import export ".\LPFNDIRECTSOUNDDEVICEENUMERATECALLBACK1.ahk" {LPFNDIRECTSOUNDDEVICEENUMERATECALLBACK1}
#Import export ".\LPFNDIRECTSOUNDDEVICEENUMERATECALLBACKA.ahk" {LPFNDIRECTSOUNDDEVICEENUMERATECALLBACKA}
#Import export ".\LPFNDIRECTSOUNDDEVICEENUMERATECALLBACKW.ahk" {LPFNDIRECTSOUNDDEVICEENUMERATECALLBACKW}
#Import export ".\MDEVICECAPSEX.ahk" {MDEVICECAPSEX}
#Import export ".\MIDILOCALE.ahk" {MIDILOCALE}
#Import export ".\MIDIOPENDESC.ahk" {MIDIOPENDESC}
#Import export ".\POOLCUE.ahk" {POOLCUE}
#Import export ".\POOLTABLE.ahk" {POOLTABLE}
#Import export ".\RGNHEADER.ahk" {RGNHEADER}
#Import export ".\RGNRANGE.ahk" {RGNRANGE}
#Import export ".\WAVELINK.ahk" {WAVELINK}
#Import export ".\WLOOP.ahk" {WLOOP}
#Import export ".\WSMPL.ahk" {WSMPL}
