#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ANCHOR_CHANGE_HISTORY_FLAGS.ahk" {ANCHOR_CHANGE_HISTORY_FLAGS}
#Import export ".\AccClientDocMgr.ahk" {AccClientDocMgr}
#Import export ".\AccDictionary.ahk" {AccDictionary}
#Import export ".\AccServerDocMgr.ahk" {AccServerDocMgr}
#Import export ".\AccStore.ahk" {AccStore}
#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\DocWrap.ahk" {DocWrap}
#Import export ".\GET_TEXT_AND_PROPERTY_UPDATES_FLAGS.ahk" {GET_TEXT_AND_PROPERTY_UPDATES_FLAGS}
#Import export ".\IAccClientDocMgr.ahk" {IAccClientDocMgr}
#Import export ".\IAccDictionary.ahk" {IAccDictionary}
#Import export ".\IAccServerDocMgr.ahk" {IAccServerDocMgr}
#Import export ".\IAccStore.ahk" {IAccStore}
#Import export ".\IAnchor.ahk" {IAnchor}
#Import export ".\IClonableWrapper.ahk" {IClonableWrapper}
#Import export ".\ICoCreateLocally.ahk" {ICoCreateLocally}
#Import export ".\ICoCreatedLocally.ahk" {ICoCreatedLocally}
#Import export ".\IDocWrap.ahk" {IDocWrap}
#Import export ".\IEnumITfCompositionView.ahk" {IEnumITfCompositionView}
#Import export ".\IEnumSpeechCommands.ahk" {IEnumSpeechCommands}
#Import export ".\IEnumTfCandidates.ahk" {IEnumTfCandidates}
#Import export ".\IEnumTfContextViews.ahk" {IEnumTfContextViews}
#Import export ".\IEnumTfContexts.ahk" {IEnumTfContexts}
#Import export ".\IEnumTfDisplayAttributeInfo.ahk" {IEnumTfDisplayAttributeInfo}
#Import export ".\IEnumTfDocumentMgrs.ahk" {IEnumTfDocumentMgrs}
#Import export ".\IEnumTfFunctionProviders.ahk" {IEnumTfFunctionProviders}
#Import export ".\IEnumTfInputProcessorProfiles.ahk" {IEnumTfInputProcessorProfiles}
#Import export ".\IEnumTfLangBarItems.ahk" {IEnumTfLangBarItems}
#Import export ".\IEnumTfLanguageProfiles.ahk" {IEnumTfLanguageProfiles}
#Import export ".\IEnumTfLatticeElements.ahk" {IEnumTfLatticeElements}
#Import export ".\IEnumTfProperties.ahk" {IEnumTfProperties}
#Import export ".\IEnumTfPropertyValue.ahk" {IEnumTfPropertyValue}
#Import export ".\IEnumTfRanges.ahk" {IEnumTfRanges}
#Import export ".\IEnumTfUIElements.ahk" {IEnumTfUIElements}
#Import export ".\IInternalDocWrap.ahk" {IInternalDocWrap}
#Import export ".\INSERT_TEXT_AT_SELECTION_FLAGS.ahk" {INSERT_TEXT_AT_SELECTION_FLAGS}
#Import export ".\ISpeechCommandProvider.ahk" {ISpeechCommandProvider}
#Import export ".\ITextStoreACP.ahk" {ITextStoreACP}
#Import export ".\ITextStoreACP2.ahk" {ITextStoreACP2}
#Import export ".\ITextStoreACPEx.ahk" {ITextStoreACPEx}
#Import export ".\ITextStoreACPServices.ahk" {ITextStoreACPServices}
#Import export ".\ITextStoreACPSink.ahk" {ITextStoreACPSink}
#Import export ".\ITextStoreACPSinkEx.ahk" {ITextStoreACPSinkEx}
#Import export ".\ITextStoreAnchor.ahk" {ITextStoreAnchor}
#Import export ".\ITextStoreAnchorEx.ahk" {ITextStoreAnchorEx}
#Import export ".\ITextStoreAnchorSink.ahk" {ITextStoreAnchorSink}
#Import export ".\ITextStoreSinkAnchorEx.ahk" {ITextStoreSinkAnchorEx}
#Import export ".\ITfActiveLanguageProfileNotifySink.ahk" {ITfActiveLanguageProfileNotifySink}
#Import export ".\ITfCandidateList.ahk" {ITfCandidateList}
#Import export ".\ITfCandidateListUIElement.ahk" {ITfCandidateListUIElement}
#Import export ".\ITfCandidateListUIElementBehavior.ahk" {ITfCandidateListUIElementBehavior}
#Import export ".\ITfCandidateString.ahk" {ITfCandidateString}
#Import export ".\ITfCategoryMgr.ahk" {ITfCategoryMgr}
#Import export ".\ITfCleanupContextDurationSink.ahk" {ITfCleanupContextDurationSink}
#Import export ".\ITfCleanupContextSink.ahk" {ITfCleanupContextSink}
#Import export ".\ITfClientId.ahk" {ITfClientId}
#Import export ".\ITfCompartment.ahk" {ITfCompartment}
#Import export ".\ITfCompartmentEventSink.ahk" {ITfCompartmentEventSink}
#Import export ".\ITfCompartmentMgr.ahk" {ITfCompartmentMgr}
#Import export ".\ITfComposition.ahk" {ITfComposition}
#Import export ".\ITfCompositionSink.ahk" {ITfCompositionSink}
#Import export ".\ITfCompositionView.ahk" {ITfCompositionView}
#Import export ".\ITfConfigureSystemKeystrokeFeed.ahk" {ITfConfigureSystemKeystrokeFeed}
#Import export ".\ITfContext.ahk" {ITfContext}
#Import export ".\ITfContextComposition.ahk" {ITfContextComposition}
#Import export ".\ITfContextKeyEventSink.ahk" {ITfContextKeyEventSink}
#Import export ".\ITfContextOwner.ahk" {ITfContextOwner}
#Import export ".\ITfContextOwnerCompositionServices.ahk" {ITfContextOwnerCompositionServices}
#Import export ".\ITfContextOwnerCompositionSink.ahk" {ITfContextOwnerCompositionSink}
#Import export ".\ITfContextOwnerServices.ahk" {ITfContextOwnerServices}
#Import export ".\ITfContextView.ahk" {ITfContextView}
#Import export ".\ITfCreatePropertyStore.ahk" {ITfCreatePropertyStore}
#Import export ".\ITfDisplayAttributeInfo.ahk" {ITfDisplayAttributeInfo}
#Import export ".\ITfDisplayAttributeMgr.ahk" {ITfDisplayAttributeMgr}
#Import export ".\ITfDisplayAttributeNotifySink.ahk" {ITfDisplayAttributeNotifySink}
#Import export ".\ITfDisplayAttributeProvider.ahk" {ITfDisplayAttributeProvider}
#Import export ".\ITfDocumentMgr.ahk" {ITfDocumentMgr}
#Import export ".\ITfEditRecord.ahk" {ITfEditRecord}
#Import export ".\ITfEditSession.ahk" {ITfEditSession}
#Import export ".\ITfEditTransactionSink.ahk" {ITfEditTransactionSink}
#Import export ".\ITfFnAdviseText.ahk" {ITfFnAdviseText}
#Import export ".\ITfFnBalloon.ahk" {ITfFnBalloon}
#Import export ".\ITfFnConfigure.ahk" {ITfFnConfigure}
#Import export ".\ITfFnConfigureRegisterEudc.ahk" {ITfFnConfigureRegisterEudc}
#Import export ".\ITfFnConfigureRegisterWord.ahk" {ITfFnConfigureRegisterWord}
#Import export ".\ITfFnCustomSpeechCommand.ahk" {ITfFnCustomSpeechCommand}
#Import export ".\ITfFnGetLinguisticAlternates.ahk" {ITfFnGetLinguisticAlternates}
#Import export ".\ITfFnGetPreferredTouchKeyboardLayout.ahk" {ITfFnGetPreferredTouchKeyboardLayout}
#Import export ".\ITfFnGetSAPIObject.ahk" {ITfFnGetSAPIObject}
#Import export ".\ITfFnLMInternal.ahk" {ITfFnLMInternal}
#Import export ".\ITfFnLMProcessor.ahk" {ITfFnLMProcessor}
#Import export ".\ITfFnLangProfileUtil.ahk" {ITfFnLangProfileUtil}
#Import export ".\ITfFnPlayBack.ahk" {ITfFnPlayBack}
#Import export ".\ITfFnPropertyUIStatus.ahk" {ITfFnPropertyUIStatus}
#Import export ".\ITfFnReconversion.ahk" {ITfFnReconversion}
#Import export ".\ITfFnSearchCandidateProvider.ahk" {ITfFnSearchCandidateProvider}
#Import export ".\ITfFnShowHelp.ahk" {ITfFnShowHelp}
#Import export ".\ITfFunction.ahk" {ITfFunction}
#Import export ".\ITfFunctionProvider.ahk" {ITfFunctionProvider}
#Import export ".\ITfInputProcessorProfileActivationSink.ahk" {ITfInputProcessorProfileActivationSink}
#Import export ".\ITfInputProcessorProfileMgr.ahk" {ITfInputProcessorProfileMgr}
#Import export ".\ITfInputProcessorProfileSubstituteLayout.ahk" {ITfInputProcessorProfileSubstituteLayout}
#Import export ".\ITfInputProcessorProfiles.ahk" {ITfInputProcessorProfiles}
#Import export ".\ITfInputProcessorProfilesEx.ahk" {ITfInputProcessorProfilesEx}
#Import export ".\ITfInputScope.ahk" {ITfInputScope}
#Import export ".\ITfInputScope2.ahk" {ITfInputScope2}
#Import export ".\ITfInsertAtSelection.ahk" {ITfInsertAtSelection}
#Import export ".\ITfIntegratableCandidateListUIElement.ahk" {ITfIntegratableCandidateListUIElement}
#Import export ".\ITfKeyEventSink.ahk" {ITfKeyEventSink}
#Import export ".\ITfKeyTraceEventSink.ahk" {ITfKeyTraceEventSink}
#Import export ".\ITfKeystrokeMgr.ahk" {ITfKeystrokeMgr}
#Import export ".\ITfLMLattice.ahk" {ITfLMLattice}
#Import export ".\ITfLangBarEventSink.ahk" {ITfLangBarEventSink}
#Import export ".\ITfLangBarItem.ahk" {ITfLangBarItem}
#Import export ".\ITfLangBarItemBalloon.ahk" {ITfLangBarItemBalloon}
#Import export ".\ITfLangBarItemBitmap.ahk" {ITfLangBarItemBitmap}
#Import export ".\ITfLangBarItemBitmapButton.ahk" {ITfLangBarItemBitmapButton}
#Import export ".\ITfLangBarItemButton.ahk" {ITfLangBarItemButton}
#Import export ".\ITfLangBarItemMgr.ahk" {ITfLangBarItemMgr}
#Import export ".\ITfLangBarItemSink.ahk" {ITfLangBarItemSink}
#Import export ".\ITfLangBarMgr.ahk" {ITfLangBarMgr}
#Import export ".\ITfLanguageProfileNotifySink.ahk" {ITfLanguageProfileNotifySink}
#Import export ".\ITfMSAAControl.ahk" {ITfMSAAControl}
#Import export ".\ITfMenu.ahk" {ITfMenu}
#Import export ".\ITfMessagePump.ahk" {ITfMessagePump}
#Import export ".\ITfMouseSink.ahk" {ITfMouseSink}
#Import export ".\ITfMouseTracker.ahk" {ITfMouseTracker}
#Import export ".\ITfMouseTrackerACP.ahk" {ITfMouseTrackerACP}
#Import export ".\ITfPersistentPropertyLoaderACP.ahk" {ITfPersistentPropertyLoaderACP}
#Import export ".\ITfPreservedKeyNotifySink.ahk" {ITfPreservedKeyNotifySink}
#Import export ".\ITfProperty.ahk" {ITfProperty}
#Import export ".\ITfPropertyStore.ahk" {ITfPropertyStore}
#Import export ".\ITfQueryEmbedded.ahk" {ITfQueryEmbedded}
#Import export ".\ITfRange.ahk" {ITfRange}
#Import export ".\ITfRangeACP.ahk" {ITfRangeACP}
#Import export ".\ITfRangeBackup.ahk" {ITfRangeBackup}
#Import export ".\ITfReadOnlyProperty.ahk" {ITfReadOnlyProperty}
#Import export ".\ITfReadingInformationUIElement.ahk" {ITfReadingInformationUIElement}
#Import export ".\ITfReverseConversion.ahk" {ITfReverseConversion}
#Import export ".\ITfReverseConversionList.ahk" {ITfReverseConversionList}
#Import export ".\ITfReverseConversionMgr.ahk" {ITfReverseConversionMgr}
#Import export ".\ITfSource.ahk" {ITfSource}
#Import export ".\ITfSourceSingle.ahk" {ITfSourceSingle}
#Import export ".\ITfSpeechUIServer.ahk" {ITfSpeechUIServer}
#Import export ".\ITfStatusSink.ahk" {ITfStatusSink}
#Import export ".\ITfSystemDeviceTypeLangBarItem.ahk" {ITfSystemDeviceTypeLangBarItem}
#Import export ".\ITfSystemLangBarItem.ahk" {ITfSystemLangBarItem}
#Import export ".\ITfSystemLangBarItemSink.ahk" {ITfSystemLangBarItemSink}
#Import export ".\ITfSystemLangBarItemText.ahk" {ITfSystemLangBarItemText}
#Import export ".\ITfTextEditSink.ahk" {ITfTextEditSink}
#Import export ".\ITfTextInputProcessor.ahk" {ITfTextInputProcessor}
#Import export ".\ITfTextInputProcessorEx.ahk" {ITfTextInputProcessorEx}
#Import export ".\ITfTextLayoutSink.ahk" {ITfTextLayoutSink}
#Import export ".\ITfThreadFocusSink.ahk" {ITfThreadFocusSink}
#Import export ".\ITfThreadMgr.ahk" {ITfThreadMgr}
#Import export ".\ITfThreadMgr2.ahk" {ITfThreadMgr2}
#Import export ".\ITfThreadMgrEventSink.ahk" {ITfThreadMgrEventSink}
#Import export ".\ITfThreadMgrEx.ahk" {ITfThreadMgrEx}
#Import export ".\ITfToolTipUIElement.ahk" {ITfToolTipUIElement}
#Import export ".\ITfTransitoryExtensionSink.ahk" {ITfTransitoryExtensionSink}
#Import export ".\ITfTransitoryExtensionUIElement.ahk" {ITfTransitoryExtensionUIElement}
#Import export ".\ITfUIElement.ahk" {ITfUIElement}
#Import export ".\ITfUIElementMgr.ahk" {ITfUIElementMgr}
#Import export ".\ITfUIElementSink.ahk" {ITfUIElementSink}
#Import export ".\IUIManagerEventSink.ahk" {IUIManagerEventSink}
#Import export ".\IVersionInfo.ahk" {IVersionInfo}
#Import export ".\InputScope.ahk" {InputScope}
#Import export ".\LANG_BAR_ITEM_ICON_MODE_FLAGS.ahk" {LANG_BAR_ITEM_ICON_MODE_FLAGS}
#Import export ".\MSAAControl.ahk" {MSAAControl}
#Import export ".\TEXT_STORE_CHANGE_FLAGS.ahk" {TEXT_STORE_CHANGE_FLAGS}
#Import export ".\TEXT_STORE_LOCK_FLAGS.ahk" {TEXT_STORE_LOCK_FLAGS}
#Import export ".\TEXT_STORE_TEXT_CHANGE_FLAGS.ahk" {TEXT_STORE_TEXT_CHANGE_FLAGS}
#Import export ".\TF_CONTEXT_EDIT_CONTEXT_FLAGS.ahk" {TF_CONTEXT_EDIT_CONTEXT_FLAGS}
#Import export ".\TF_DA_ATTR_INFO.ahk" {TF_DA_ATTR_INFO}
#Import export ".\TF_DA_COLOR.ahk" {TF_DA_COLOR}
#Import export ".\TF_DA_COLORTYPE.ahk" {TF_DA_COLORTYPE}
#Import export ".\TF_DA_LINESTYLE.ahk" {TF_DA_LINESTYLE}
#Import export ".\TF_DISPLAYATTRIBUTE.ahk" {TF_DISPLAYATTRIBUTE}
#Import export ".\TF_HALTCOND.ahk" {TF_HALTCOND}
#Import export ".\TF_INPUTPROCESSORPROFILE.ahk" {TF_INPUTPROCESSORPROFILE}
#Import export ".\TF_LANGBARITEMINFO.ahk" {TF_LANGBARITEMINFO}
#Import export ".\TF_LANGUAGEPROFILE.ahk" {TF_LANGUAGEPROFILE}
#Import export ".\TF_LBBALLOONINFO.ahk" {TF_LBBALLOONINFO}
#Import export ".\TF_LMLATTELEMENT.ahk" {TF_LMLATTELEMENT}
#Import export ".\TF_PERSISTENT_PROPERTY_HEADER_ACP.ahk" {TF_PERSISTENT_PROPERTY_HEADER_ACP}
#Import export ".\TF_PRESERVEDKEY.ahk" {TF_PRESERVEDKEY}
#Import export ".\TF_PROPERTYVAL.ahk" {TF_PROPERTYVAL}
#Import export ".\TF_SELECTION.ahk" {TF_SELECTION}
#Import export ".\TF_SELECTIONSTYLE.ahk" {TF_SELECTIONSTYLE}
#Import export ".\TKBLayoutType.ahk" {TKBLayoutType}
#Import export ".\TS_ATTRVAL.ahk" {TS_ATTRVAL}
#Import export ".\TS_RUNINFO.ahk" {TS_RUNINFO}
#Import export ".\TS_SELECTIONSTYLE.ahk" {TS_SELECTIONSTYLE}
#Import export ".\TS_SELECTION_ACP.ahk" {TS_SELECTION_ACP}
#Import export ".\TS_SELECTION_ANCHOR.ahk" {TS_SELECTION_ANCHOR}
#Import export ".\TS_STATUS.ahk" {TS_STATUS}
#Import export ".\TS_TEXTCHANGE.ahk" {TS_TEXTCHANGE}
#Import export ".\TfActiveSelEnd.ahk" {TfActiveSelEnd}
#Import export ".\TfAnchor.ahk" {TfAnchor}
#Import export ".\TfCandidateResult.ahk" {TfCandidateResult}
#Import export ".\TfGravity.ahk" {TfGravity}
#Import export ".\TfIntegratableCandidateListSelectionStyle.ahk" {TfIntegratableCandidateListSelectionStyle}
#Import export ".\TfLBBalloonStyle.ahk" {TfLBBalloonStyle}
#Import export ".\TfLBIClick.ahk" {TfLBIClick}
#Import export ".\TfLayoutCode.ahk" {TfLayoutCode}
#Import export ".\TfSapiObject.ahk" {TfSapiObject}
#Import export ".\TfShiftDir.ahk" {TfShiftDir}
#Import export ".\TsActiveSelEnd.ahk" {TsActiveSelEnd}
#Import export ".\TsGravity.ahk" {TsGravity}
#Import export ".\TsLayoutCode.ahk" {TsLayoutCode}
#Import export ".\TsRunType.ahk" {TsRunType}
#Import export ".\TsShiftDir.ahk" {TsShiftDir}
