#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\KSPROPERTY_NETWORKCAMERACONTROL_NTPINFO_TYPE.ahk" { KSPROPERTY_NETWORKCAMERACONTROL_NTPINFO_TYPE }

/**
 * @namespace Windows.Win32.Media.KernelStreaming
 */
export default struct KSPROPERTY_NETWORKCAMERACONTROL_NTPINFO_HEADER {
    #StructPack 4

    Size : UInt32

    Type : KSPROPERTY_NETWORKCAMERACONTROL_NTPINFO_TYPE

}
