#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\VBICODECFILTERING_STATISTICS_NABTS_PIN.ahk" { VBICODECFILTERING_STATISTICS_NABTS_PIN }
#Import "..\..\..\..\Guid.ahk" { Guid }
#Import ".\VBICODECFILTERING_STATISTICS_COMMON_PIN.ahk" { VBICODECFILTERING_STATISTICS_COMMON_PIN }
#Import ".\KSIDENTIFIER.ahk" { KSIDENTIFIER }

/**
 * @namespace Windows.Win32.Media.KernelStreaming
 */
export default struct KSPROPERTY_VBICODECFILTERING_STATISTICS_NABTS_PIN_S {
    #StructPack 8

    Property : KSIDENTIFIER

    Statistics : VBICODECFILTERING_STATISTICS_NABTS_PIN

}
