#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\APOInitBaseStruct.ahk" {APOInitBaseStruct}
#Import export ".\APOInitSystemEffects.ahk" {APOInitSystemEffects}
#Import export ".\APOInitSystemEffects2.ahk" {APOInitSystemEffects2}
#Import export ".\APOInitSystemEffects3.ahk" {APOInitSystemEffects3}
#Import export ".\APO_BUFFER_FLAGS.ahk" {APO_BUFFER_FLAGS}
#Import export ".\APO_CONNECTION_BUFFER_TYPE.ahk" {APO_CONNECTION_BUFFER_TYPE}
#Import export ".\APO_CONNECTION_DESCRIPTOR.ahk" {APO_CONNECTION_DESCRIPTOR}
#Import export ".\APO_CONNECTION_PROPERTY.ahk" {APO_CONNECTION_PROPERTY}
#Import export ".\APO_CONNECTION_PROPERTY_V2.ahk" {APO_CONNECTION_PROPERTY_V2}
#Import export ".\APO_FLAG.ahk" {APO_FLAG}
#Import export ".\APO_LOG_LEVEL.ahk" {APO_LOG_LEVEL}
#Import export ".\APO_NOTIFICATION.ahk" {APO_NOTIFICATION}
#Import export ".\APO_NOTIFICATION_DESCRIPTOR.ahk" {APO_NOTIFICATION_DESCRIPTOR}
#Import export ".\APO_NOTIFICATION_TYPE.ahk" {APO_NOTIFICATION_TYPE}
#Import export ".\APO_REFERENCE_STREAM_PROPERTIES.ahk" {APO_REFERENCE_STREAM_PROPERTIES}
#Import export ".\APO_REG_PROPERTIES.ahk" {APO_REG_PROPERTIES}
#Import export ".\AUDIO_ENDPOINT_PROPERTY_CHANGE_APO_NOTIFICATION_DESCRIPTOR.ahk" {AUDIO_ENDPOINT_PROPERTY_CHANGE_APO_NOTIFICATION_DESCRIPTOR}
#Import export ".\AUDIO_ENDPOINT_PROPERTY_CHANGE_NOTIFICATION.ahk" {AUDIO_ENDPOINT_PROPERTY_CHANGE_NOTIFICATION}
#Import export ".\AUDIO_ENDPOINT_VOLUME_APO_NOTIFICATION_DESCRIPTOR.ahk" {AUDIO_ENDPOINT_VOLUME_APO_NOTIFICATION_DESCRIPTOR}
#Import export ".\AUDIO_ENDPOINT_VOLUME_CHANGE_NOTIFICATION.ahk" {AUDIO_ENDPOINT_VOLUME_CHANGE_NOTIFICATION}
#Import export ".\AUDIO_ENDPOINT_VOLUME_CHANGE_NOTIFICATION2.ahk" {AUDIO_ENDPOINT_VOLUME_CHANGE_NOTIFICATION2}
#Import export ".\AUDIO_ENVIRONMENT_STATE_CHANGE_NOTIFICATION.ahk" {AUDIO_ENVIRONMENT_STATE_CHANGE_NOTIFICATION}
#Import export ".\AUDIO_FLOW_TYPE.ahk" {AUDIO_FLOW_TYPE}
#Import export ".\AUDIO_MICROPHONE_BOOST_APO_NOTIFICATION_DESCRIPTOR.ahk" {AUDIO_MICROPHONE_BOOST_APO_NOTIFICATION_DESCRIPTOR}
#Import export ".\AUDIO_MICROPHONE_BOOST_NOTIFICATION.ahk" {AUDIO_MICROPHONE_BOOST_NOTIFICATION}
#Import export ".\AUDIO_SYSTEMEFFECT.ahk" {AUDIO_SYSTEMEFFECT}
#Import export ".\AUDIO_SYSTEMEFFECTS_PROPERTY_CHANGE_APO_NOTIFICATION_DESCRIPTOR.ahk" {AUDIO_SYSTEMEFFECTS_PROPERTY_CHANGE_APO_NOTIFICATION_DESCRIPTOR}
#Import export ".\AUDIO_SYSTEMEFFECTS_PROPERTY_CHANGE_NOTIFICATION.ahk" {AUDIO_SYSTEMEFFECTS_PROPERTY_CHANGE_NOTIFICATION}
#Import export ".\AUDIO_SYSTEMEFFECT_STATE.ahk" {AUDIO_SYSTEMEFFECT_STATE}
#Import export ".\AUDIO_VOLUME_NOTIFICATION_DATA2.ahk" {AUDIO_VOLUME_NOTIFICATION_DATA2}
#Import export ".\AcousticEchoCanceller_Reference_Input.ahk" {AcousticEchoCanceller_Reference_Input}
#Import export ".\AudioFXExtensionParams.ahk" {AudioFXExtensionParams}
#Import export ".\Constants.ahk" {*}
#Import export ".\DEVICE_ORIENTATION_TYPE.ahk" {DEVICE_ORIENTATION_TYPE}
#Import export ".\EAudioConstriction.ahk" {EAudioConstriction}
#Import export ".\FNAPONOTIFICATIONCALLBACK.ahk" {FNAPONOTIFICATIONCALLBACK}
#Import export ".\IApoAcousticEchoCancellation.ahk" {IApoAcousticEchoCancellation}
#Import export ".\IApoAcousticEchoCancellation2.ahk" {IApoAcousticEchoCancellation2}
#Import export ".\IApoAuxiliaryInputConfiguration.ahk" {IApoAuxiliaryInputConfiguration}
#Import export ".\IApoAuxiliaryInputRT.ahk" {IApoAuxiliaryInputRT}
#Import export ".\IAudioDeviceModulesClient.ahk" {IAudioDeviceModulesClient}
#Import export ".\IAudioMediaType.ahk" {IAudioMediaType}
#Import export ".\IAudioProcessingObject.ahk" {IAudioProcessingObject}
#Import export ".\IAudioProcessingObjectConfiguration.ahk" {IAudioProcessingObjectConfiguration}
#Import export ".\IAudioProcessingObjectLoggingService.ahk" {IAudioProcessingObjectLoggingService}
#Import export ".\IAudioProcessingObjectNotifications.ahk" {IAudioProcessingObjectNotifications}
#Import export ".\IAudioProcessingObjectNotifications2.ahk" {IAudioProcessingObjectNotifications2}
#Import export ".\IAudioProcessingObjectPreferredFormatSupport.ahk" {IAudioProcessingObjectPreferredFormatSupport}
#Import export ".\IAudioProcessingObjectRT.ahk" {IAudioProcessingObjectRT}
#Import export ".\IAudioProcessingObjectRTQueueService.ahk" {IAudioProcessingObjectRTQueueService}
#Import export ".\IAudioProcessingObjectVBR.ahk" {IAudioProcessingObjectVBR}
#Import export ".\IAudioSystemEffects.ahk" {IAudioSystemEffects}
#Import export ".\IAudioSystemEffects2.ahk" {IAudioSystemEffects2}
#Import export ".\IAudioSystemEffects3.ahk" {IAudioSystemEffects3}
#Import export ".\IAudioSystemEffectsCustomFormats.ahk" {IAudioSystemEffectsCustomFormats}
#Import export ".\UNCOMPRESSEDAUDIOFORMAT.ahk" {UNCOMPRESSEDAUDIOFORMAT}
