#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\..\Guid.ahk" { Guid }
#Import ".\IAudioMediaType.ahk" { IAudioMediaType }
#Import "..\..\..\Foundation\HRESULT.ahk" { HRESULT }
#Import ".\APO_CONNECTION_DESCRIPTOR.ahk" { APO_CONNECTION_DESCRIPTOR }
#Import "..\..\..\System\Com\IUnknown.ahk" { IUnknown }

/**
 * Provides methods that APOs can implement so that the audio engine can add and remove auxiliary input streams.
 * @see https://learn.microsoft.com/windows/win32/api/audioenginebaseapo/nn-audioenginebaseapo-iapoauxiliaryinputconfiguration
 * @namespace Windows.Win32.Media.Audio.Apo
 */
export default struct IApoAuxiliaryInputConfiguration extends IUnknown {
    /**
     * The interface identifier for IApoAuxiliaryInputConfiguration
     * @type {Guid}
     */
    static IID := Guid("{4ceb0aab-fa19-48ed-a857-87771ae1b768}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for IApoAuxiliaryInputConfiguration interfaces
    */
    struct Vtbl extends IUnknown.Vtbl {
        AddAuxiliaryInput      : IntPtr
        RemoveAuxiliaryInput   : IntPtr
        IsInputFormatSupported : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := IApoAuxiliaryInputConfiguration.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * Adds an auxiliary input to the APO, and provides initialization parameters.
     * @remarks
     * The initialization data is variable length and takes the following form. See [IAudioProcessingObject::Initialize](nf-audioenginebaseapo-iaudioprocessingobject-initialize.md) for information on using the initialization data.
     * 
     * ```cpp
     * struct MyAPOInitializationData
     * {
     *     APOInitBaseStruct    APOInit;
     *     // add additional fields here...
     * };
     * ```
     * 
     * This method will only be called only when the APO is not locked for processing. This method will not be called from a real-time processing thread.
     * @param {Integer} dwInputId Identifier for the input. This is a unique identifier generated by the system. The APO can use this identifier to differentiate between multiple auxiliary inputs.
     * @param {Integer} cbDataSize The size of the initialization data, in bytes.
     * @param {Pointer<Integer>} pbyData Initialization data specific to this APO.
     * @param {Pointer<APO_CONNECTION_DESCRIPTOR>} pInputConnection Connection descriptor for this auxiliary input connection.
     * @returns {HRESULT} HRESULT 
     * 
     * | HRESULT | Description | 
     * |---------------|--------------|
     * | APOERR_NUM_CONNECTIONS_INVALID | The APO does not expect the auxiliary input. |
     * @see https://learn.microsoft.com/windows/win32/api/audioenginebaseapo/nf-audioenginebaseapo-iapoauxiliaryinputconfiguration-addauxiliaryinput
     */
    AddAuxiliaryInput(dwInputId, cbDataSize, pbyData, pInputConnection) {
        pbyDataMarshal := pbyData is VarRef ? "char*" : "ptr"

        result := ComCall(3, this, "uint", dwInputId, "uint", cbDataSize, pbyDataMarshal, pbyData, APO_CONNECTION_DESCRIPTOR.Ptr, pInputConnection, "HRESULT")
        return result
    }

    /**
     * Removes an auxiliary input from the APO.
     * @remarks
     * This method will only be called only when the APO is not locked for processing. This method will not be called from a real-time processing thread.
     * @param {Integer} dwInputId Identifier for the input. This is a unique identifier generated by the system. The APO can use this identifier to differentiate between multiple auxiliary inputs.
     * @returns {HRESULT} HRESULT
     * @see https://learn.microsoft.com/windows/win32/api/audioenginebaseapo/nf-audioenginebaseapo-iapoauxiliaryinputconfiguration-removeauxiliaryinput
     */
    RemoveAuxiliaryInput(dwInputId) {
        result := ComCall(4, this, "uint", dwInputId, "HRESULT")
        return result
    }

    /**
     * Verifies that a specific auxiliary input format is supported by the APO.
     * @remarks
     * If the APO can accept the requested format, it should add a reference to the requested format, return this as the supported output format, and return S_OK.
     * 
     * If the APO cannot accept the requested format it may suggest an alternate requested format.  In this case it should create and return the suggested format, and return S_FALSE.
     * 
     * The returned supported format should be 'closest' to the requested format, meaning that the format should have the same values for the following properties, specified in priority order.
     * 
     * - sample format
     * - bit depth
     * - number of channels
     * - sample rate 
     * 
     * The suggested format may only be different from the requested format if S_FALSE is returned. When returning any failure, the suggested format should be left untouched.
     * 
     * This API may be called at any time. The returned results will depend on the internal state of the APO which may
     * be manipulated by external user-interfaces.  Once the APO is locked for processing, however, this format cannot and will not changed.
     * 
     * This method may not be called from a real-time processing thread.
     * @param {IAudioMediaType} pRequestedInputFormat The input format that is to be verified.
     * @returns {IAudioMediaType} The APO populates this parameter with the supported input format closest to the format passed in to the method.
     * @see https://learn.microsoft.com/windows/win32/api/audioenginebaseapo/nf-audioenginebaseapo-iapoauxiliaryinputconfiguration-isinputformatsupported
     */
    IsInputFormatSupported(pRequestedInputFormat) {
        result := ComCall(5, this, "ptr", pRequestedInputFormat, "ptr*", &ppSupportedInputFormat := 0, "HRESULT")
        return IAudioMediaType(ppSupportedInputFormat)
    }

    Query(iid) {
        if (IApoAuxiliaryInputConfiguration.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.AddAuxiliaryInput := CallbackCreate(GetMethod(implObj, "AddAuxiliaryInput"), flags, 5)
        this.vtbl.RemoveAuxiliaryInput := CallbackCreate(GetMethod(implObj, "RemoveAuxiliaryInput"), flags, 2)
        this.vtbl.IsInputFormatSupported := CallbackCreate(GetMethod(implObj, "IsInputFormatSupported"), flags, 3)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.AddAuxiliaryInput)
        CallbackFree(this.vtbl.RemoveAuxiliaryInput)
        CallbackFree(this.vtbl.IsInputFormatSupported)
    }
}
