#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\..\Guid.ahk" { Guid }
#Import ".\APO_CONNECTION_PROPERTY.ahk" { APO_CONNECTION_PROPERTY }
#Import "..\..\..\System\Com\IUnknown.ahk" { IUnknown }

/**
 * The realtime-safe interface used to drive the auxiliary inputs of an APO.
 * @remarks
 * This method may be called from a real-time processing thread. The implementation 
 * of these methods must not block, touch paged memory, or call any blocking system routines.
 * @see https://learn.microsoft.com/windows/win32/api/audioenginebaseapo/nn-audioenginebaseapo-iapoauxiliaryinputrt
 * @namespace Windows.Win32.Media.Audio.Apo
 */
export default struct IApoAuxiliaryInputRT extends IUnknown {
    /**
     * The interface identifier for IApoAuxiliaryInputRT
     * @type {Guid}
     */
    static IID := Guid("{f851809c-c177-49a0-b1b2-b66f017943ab}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for IApoAuxiliaryInputRT interfaces
    */
    struct Vtbl extends IUnknown.Vtbl {
        AcceptInput : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := IApoAuxiliaryInputRT.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * Provides input to the APO on one of its auxiliary inputs.
     * @remarks
     * This method may be called from a real-time processing thread. The implementation of this method does not and should not block, touch paged memory, or call any blocking system routines.
     * 
     * The cadence of the input endpoint may not match the cadence of the render endpoint, and therefore the cadence with which input is provided to the auxiliary input may not match the cadence with which [IAudioProcessingObjectRT::APOProcess](nf-audioenginebaseapo-iaudioprocessingobjectrt-apoprocess.md) is called on the primary input. The APO must implement appropriate non-blocking buffering to ensure that this call does not block.
     * 
     * The [APO_CONNECTION_PROPERTY_V2](/windows/win32/api/audioapotypes/ns-audioapotypes-apo_connection_property_v2) includes a timestamp that can be used to synchronize the primary and secondary streams. If the **u32Signature** field of the [APO_CONNECTION_PROPERTY](/windows/win32/api/audioapotypes/ns-audioapotypes-apo_connection_property) structure passed into **IAudioProcessingObjectRT::APOProcess** is equal to **APO_CONNECTION_PROPERTY_V2_SIGNATURE**, the structure can be safely typecast to a **APO_CONNECTION_PROPERTY_V2**.
     * @param {Integer} dwInputId Identifier for the input. This is a unique identifier generated by the system. The APO can use this identifier to differentiate between multiple auxiliary inputs.
     * @param {Pointer<APO_CONNECTION_PROPERTY>} pInputConnection The input connection property structure.
     * @returns {String} Nothing - always returns an empty string
     * @see https://learn.microsoft.com/windows/win32/api/audioenginebaseapo/nf-audioenginebaseapo-iapoauxiliaryinputrt-acceptinput
     */
    AcceptInput(dwInputId, pInputConnection) {
        ComCall(3, this, "uint", dwInputId, APO_CONNECTION_PROPERTY.Ptr, pInputConnection)
    }

    Query(iid) {
        if (IApoAuxiliaryInputRT.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.AcceptInput := CallbackCreate(GetMethod(implObj, "AcceptInput"), flags, 3)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.AcceptInput)
    }
}
