#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\AdSyncTask.ahk" {AdSyncTask}
#Import export ".\AdrClientDisplayFlags.ahk" {AdrClientDisplayFlags}
#Import export ".\AdrClientErrorType.ahk" {AdrClientErrorType}
#Import export ".\AdrClientFlags.ahk" {AdrClientFlags}
#Import export ".\AdrEmailFlags.ahk" {AdrEmailFlags}
#Import export ".\Constants.ahk" {*}
#Import export ".\DIFsrmClassificationEvents.ahk" {DIFsrmClassificationEvents}
#Import export ".\FsrmAccessDeniedRemediationClient.ahk" {FsrmAccessDeniedRemediationClient}
#Import export ".\FsrmAccountType.ahk" {FsrmAccountType}
#Import export ".\FsrmActionType.ahk" {FsrmActionType}
#Import export ".\FsrmClassificationLoggingFlags.ahk" {FsrmClassificationLoggingFlags}
#Import export ".\FsrmClassificationManager.ahk" {FsrmClassificationManager}
#Import export ".\FsrmCollectionState.ahk" {FsrmCollectionState}
#Import export ".\FsrmCommitOptions.ahk" {FsrmCommitOptions}
#Import export ".\FsrmEnumOptions.ahk" {FsrmEnumOptions}
#Import export ".\FsrmEventType.ahk" {FsrmEventType}
#Import export ".\FsrmExecutionOption.ahk" {FsrmExecutionOption}
#Import export ".\FsrmExportImport.ahk" {FsrmExportImport}
#Import export ".\FsrmFileConditionType.ahk" {FsrmFileConditionType}
#Import export ".\FsrmFileGroupManager.ahk" {FsrmFileGroupManager}
#Import export ".\FsrmFileManagementJobManager.ahk" {FsrmFileManagementJobManager}
#Import export ".\FsrmFileManagementLoggingFlags.ahk" {FsrmFileManagementLoggingFlags}
#Import export ".\FsrmFileManagementType.ahk" {FsrmFileManagementType}
#Import export ".\FsrmFileScreenFlags.ahk" {FsrmFileScreenFlags}
#Import export ".\FsrmFileScreenManager.ahk" {FsrmFileScreenManager}
#Import export ".\FsrmFileScreenTemplateManager.ahk" {FsrmFileScreenTemplateManager}
#Import export ".\FsrmFileStreamingInterfaceType.ahk" {FsrmFileStreamingInterfaceType}
#Import export ".\FsrmFileStreamingMode.ahk" {FsrmFileStreamingMode}
#Import export ".\FsrmFileSystemPropertyId.ahk" {FsrmFileSystemPropertyId}
#Import export ".\FsrmGetFilePropertyOptions.ahk" {FsrmGetFilePropertyOptions}
#Import export ".\FsrmPathMapper.ahk" {FsrmPathMapper}
#Import export ".\FsrmPipelineModuleConnector.ahk" {FsrmPipelineModuleConnector}
#Import export ".\FsrmPipelineModuleType.ahk" {FsrmPipelineModuleType}
#Import export ".\FsrmPropertyBagField.ahk" {FsrmPropertyBagField}
#Import export ".\FsrmPropertyBagFlags.ahk" {FsrmPropertyBagFlags}
#Import export ".\FsrmPropertyConditionType.ahk" {FsrmPropertyConditionType}
#Import export ".\FsrmPropertyDefinitionAppliesTo.ahk" {FsrmPropertyDefinitionAppliesTo}
#Import export ".\FsrmPropertyDefinitionFlags.ahk" {FsrmPropertyDefinitionFlags}
#Import export ".\FsrmPropertyDefinitionType.ahk" {FsrmPropertyDefinitionType}
#Import export ".\FsrmPropertyFlags.ahk" {FsrmPropertyFlags}
#Import export ".\FsrmPropertyValueType.ahk" {FsrmPropertyValueType}
#Import export ".\FsrmQuotaFlags.ahk" {FsrmQuotaFlags}
#Import export ".\FsrmQuotaManager.ahk" {FsrmQuotaManager}
#Import export ".\FsrmQuotaTemplateManager.ahk" {FsrmQuotaTemplateManager}
#Import export ".\FsrmReportFilter.ahk" {FsrmReportFilter}
#Import export ".\FsrmReportFormat.ahk" {FsrmReportFormat}
#Import export ".\FsrmReportGenerationContext.ahk" {FsrmReportGenerationContext}
#Import export ".\FsrmReportLimit.ahk" {FsrmReportLimit}
#Import export ".\FsrmReportManager.ahk" {FsrmReportManager}
#Import export ".\FsrmReportRunningStatus.ahk" {FsrmReportRunningStatus}
#Import export ".\FsrmReportScheduler.ahk" {FsrmReportScheduler}
#Import export ".\FsrmReportType.ahk" {FsrmReportType}
#Import export ".\FsrmRuleFlags.ahk" {FsrmRuleFlags}
#Import export ".\FsrmRuleType.ahk" {FsrmRuleType}
#Import export ".\FsrmSetting.ahk" {FsrmSetting}
#Import export ".\FsrmStorageModuleCaps.ahk" {FsrmStorageModuleCaps}
#Import export ".\FsrmStorageModuleType.ahk" {FsrmStorageModuleType}
#Import export ".\FsrmTemplateApplyOptions.ahk" {FsrmTemplateApplyOptions}
#Import export ".\IFsrmAccessDeniedRemediationClient.ahk" {IFsrmAccessDeniedRemediationClient}
#Import export ".\IFsrmAction.ahk" {IFsrmAction}
#Import export ".\IFsrmActionCommand.ahk" {IFsrmActionCommand}
#Import export ".\IFsrmActionEmail.ahk" {IFsrmActionEmail}
#Import export ".\IFsrmActionEmail2.ahk" {IFsrmActionEmail2}
#Import export ".\IFsrmActionEventLog.ahk" {IFsrmActionEventLog}
#Import export ".\IFsrmActionReport.ahk" {IFsrmActionReport}
#Import export ".\IFsrmAutoApplyQuota.ahk" {IFsrmAutoApplyQuota}
#Import export ".\IFsrmClassificationManager.ahk" {IFsrmClassificationManager}
#Import export ".\IFsrmClassificationManager2.ahk" {IFsrmClassificationManager2}
#Import export ".\IFsrmClassificationRule.ahk" {IFsrmClassificationRule}
#Import export ".\IFsrmClassifierModuleDefinition.ahk" {IFsrmClassifierModuleDefinition}
#Import export ".\IFsrmClassifierModuleImplementation.ahk" {IFsrmClassifierModuleImplementation}
#Import export ".\IFsrmCollection.ahk" {IFsrmCollection}
#Import export ".\IFsrmCommittableCollection.ahk" {IFsrmCommittableCollection}
#Import export ".\IFsrmDerivedObjectsResult.ahk" {IFsrmDerivedObjectsResult}
#Import export ".\IFsrmExportImport.ahk" {IFsrmExportImport}
#Import export ".\IFsrmFileCondition.ahk" {IFsrmFileCondition}
#Import export ".\IFsrmFileConditionProperty.ahk" {IFsrmFileConditionProperty}
#Import export ".\IFsrmFileGroup.ahk" {IFsrmFileGroup}
#Import export ".\IFsrmFileGroupImported.ahk" {IFsrmFileGroupImported}
#Import export ".\IFsrmFileGroupManager.ahk" {IFsrmFileGroupManager}
#Import export ".\IFsrmFileManagementJob.ahk" {IFsrmFileManagementJob}
#Import export ".\IFsrmFileManagementJobManager.ahk" {IFsrmFileManagementJobManager}
#Import export ".\IFsrmFileScreen.ahk" {IFsrmFileScreen}
#Import export ".\IFsrmFileScreenBase.ahk" {IFsrmFileScreenBase}
#Import export ".\IFsrmFileScreenException.ahk" {IFsrmFileScreenException}
#Import export ".\IFsrmFileScreenManager.ahk" {IFsrmFileScreenManager}
#Import export ".\IFsrmFileScreenTemplate.ahk" {IFsrmFileScreenTemplate}
#Import export ".\IFsrmFileScreenTemplateImported.ahk" {IFsrmFileScreenTemplateImported}
#Import export ".\IFsrmFileScreenTemplateManager.ahk" {IFsrmFileScreenTemplateManager}
#Import export ".\IFsrmMutableCollection.ahk" {IFsrmMutableCollection}
#Import export ".\IFsrmObject.ahk" {IFsrmObject}
#Import export ".\IFsrmPathMapper.ahk" {IFsrmPathMapper}
#Import export ".\IFsrmPipelineModuleConnector.ahk" {IFsrmPipelineModuleConnector}
#Import export ".\IFsrmPipelineModuleDefinition.ahk" {IFsrmPipelineModuleDefinition}
#Import export ".\IFsrmPipelineModuleImplementation.ahk" {IFsrmPipelineModuleImplementation}
#Import export ".\IFsrmProperty.ahk" {IFsrmProperty}
#Import export ".\IFsrmPropertyBag.ahk" {IFsrmPropertyBag}
#Import export ".\IFsrmPropertyBag2.ahk" {IFsrmPropertyBag2}
#Import export ".\IFsrmPropertyCondition.ahk" {IFsrmPropertyCondition}
#Import export ".\IFsrmPropertyDefinition.ahk" {IFsrmPropertyDefinition}
#Import export ".\IFsrmPropertyDefinition2.ahk" {IFsrmPropertyDefinition2}
#Import export ".\IFsrmPropertyDefinitionValue.ahk" {IFsrmPropertyDefinitionValue}
#Import export ".\IFsrmQuota.ahk" {IFsrmQuota}
#Import export ".\IFsrmQuotaBase.ahk" {IFsrmQuotaBase}
#Import export ".\IFsrmQuotaManager.ahk" {IFsrmQuotaManager}
#Import export ".\IFsrmQuotaManagerEx.ahk" {IFsrmQuotaManagerEx}
#Import export ".\IFsrmQuotaObject.ahk" {IFsrmQuotaObject}
#Import export ".\IFsrmQuotaTemplate.ahk" {IFsrmQuotaTemplate}
#Import export ".\IFsrmQuotaTemplateImported.ahk" {IFsrmQuotaTemplateImported}
#Import export ".\IFsrmQuotaTemplateManager.ahk" {IFsrmQuotaTemplateManager}
#Import export ".\IFsrmReport.ahk" {IFsrmReport}
#Import export ".\IFsrmReportJob.ahk" {IFsrmReportJob}
#Import export ".\IFsrmReportManager.ahk" {IFsrmReportManager}
#Import export ".\IFsrmReportScheduler.ahk" {IFsrmReportScheduler}
#Import export ".\IFsrmRule.ahk" {IFsrmRule}
#Import export ".\IFsrmSetting.ahk" {IFsrmSetting}
#Import export ".\IFsrmStorageModuleDefinition.ahk" {IFsrmStorageModuleDefinition}
#Import export ".\IFsrmStorageModuleImplementation.ahk" {IFsrmStorageModuleImplementation}
