#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\AutoCorrectProc.ahk" {AutoCorrectProc}
#Import export ".\BIDIOPTIONS.ahk" {BIDIOPTIONS}
#Import export ".\CARET_FLAGS.ahk" {CARET_FLAGS}
#Import export ".\CARET_INFO.ahk" {CARET_INFO}
#Import export ".\CFE_EFFECTS.ahk" {CFE_EFFECTS}
#Import export ".\CFM_MASK.ahk" {CFM_MASK}
#Import export ".\CHANGENOTIFY.ahk" {CHANGENOTIFY}
#Import export ".\CHANGETYPE.ahk" {CHANGETYPE}
#Import export ".\CHARFORMAT2A.ahk" {CHARFORMAT2A}
#Import export ".\CHARFORMAT2W.ahk" {CHARFORMAT2W}
#Import export ".\CHARFORMATA.ahk" {CHARFORMATA}
#Import export ".\CHARFORMATW.ahk" {CHARFORMATW}
#Import export ".\CHARRANGE.ahk" {CHARRANGE}
#Import export ".\CLIPBOARDFORMAT.ahk" {CLIPBOARDFORMAT}
#Import export ".\COMPCOLOR.ahk" {COMPCOLOR}
#Import export ".\Constants.ahk" {*}
#Import export ".\EDITSTREAM.ahk" {EDITSTREAM}
#Import export ".\EDITSTREAMCALLBACK.ahk" {EDITSTREAMCALLBACK}
#Import export ".\EDITWORDBREAKPROCEX.ahk" {EDITWORDBREAKPROCEX}
#Import export ".\ENCORRECTTEXT.ahk" {ENCORRECTTEXT}
#Import export ".\ENDCOMPOSITIONNOTIFY.ahk" {ENDCOMPOSITIONNOTIFY}
#Import export ".\ENDCOMPOSITIONNOTIFY_CODE.ahk" {ENDCOMPOSITIONNOTIFY_CODE}
#Import export ".\ENDROPFILES.ahk" {ENDROPFILES}
#Import export ".\ENLINK.ahk" {ENLINK}
#Import export ".\ENLOWFIRTF.ahk" {ENLOWFIRTF}
#Import export ".\ENOLEOPFAILED.ahk" {ENOLEOPFAILED}
#Import export ".\ENPROTECTED.ahk" {ENPROTECTED}
#Import export ".\ENSAVECLIPBOARD.ahk" {ENSAVECLIPBOARD}
#Import export ".\FINDTEXTA.ahk" {FINDTEXTA}
#Import export ".\FINDTEXTEXA.ahk" {FINDTEXTEXA}
#Import export ".\FINDTEXTEXW.ahk" {FINDTEXTEXW}
#Import export ".\FINDTEXTW.ahk" {FINDTEXTW}
#Import export ".\FORMATRANGE.ahk" {FORMATRANGE}
#Import export ".\GETCONTEXTMENUEX.ahk" {GETCONTEXTMENUEX}
#Import export ".\GETTEXTEX.ahk" {GETTEXTEX}
#Import export ".\GETTEXTEX_FLAGS.ahk" {GETTEXTEX_FLAGS}
#Import export ".\GETTEXTLENGTHEX.ahk" {GETTEXTLENGTHEX}
#Import export ".\GETTEXTLENGTHEX_FLAGS.ahk" {GETTEXTLENGTHEX_FLAGS}
#Import export ".\GROUPTYPINGCHANGE.ahk" {GROUPTYPINGCHANGE}
#Import export ".\HYPHENATEINFO.ahk" {HYPHENATEINFO}
#Import export ".\HYPHRESULT.ahk" {HYPHRESULT}
#Import export ".\IMECOMPTEXT.ahk" {IMECOMPTEXT}
#Import export ".\IMECOMPTEXT_FLAGS.ahk" {IMECOMPTEXT_FLAGS}
#Import export ".\IRichEditOle.ahk" {IRichEditOle}
#Import export ".\IRichEditOleCallback.ahk" {IRichEditOleCallback}
#Import export ".\IRicheditUiaOverrides.ahk" {IRicheditUiaOverrides}
#Import export ".\ITextDisplays.ahk" {ITextDisplays}
#Import export ".\ITextDocument.ahk" {ITextDocument}
#Import export ".\ITextDocument2.ahk" {ITextDocument2}
#Import export ".\ITextDocument2Old.ahk" {ITextDocument2Old}
#Import export ".\ITextFont.ahk" {ITextFont}
#Import export ".\ITextFont2.ahk" {ITextFont2}
#Import export ".\ITextHost.ahk" {ITextHost}
#Import export ".\ITextHost2.ahk" {ITextHost2}
#Import export ".\ITextPara.ahk" {ITextPara}
#Import export ".\ITextPara2.ahk" {ITextPara2}
#Import export ".\ITextRange.ahk" {ITextRange}
#Import export ".\ITextRange2.ahk" {ITextRange2}
#Import export ".\ITextRow.ahk" {ITextRow}
#Import export ".\ITextSelection.ahk" {ITextSelection}
#Import export ".\ITextSelection2.ahk" {ITextSelection2}
#Import export ".\ITextServices.ahk" {ITextServices}
#Import export ".\ITextServices2.ahk" {ITextServices2}
#Import export ".\ITextStory.ahk" {ITextStory}
#Import export ".\ITextStoryRanges.ahk" {ITextStoryRanges}
#Import export ".\ITextStoryRanges2.ahk" {ITextStoryRanges2}
#Import export ".\ITextStrings.ahk" {ITextStrings}
#Import export ".\KHYPH.ahk" {KHYPH}
#Import export ".\MANCODE.ahk" {MANCODE}
#Import export ".\MSGFILTER.ahk" {MSGFILTER}
#Import export ".\OBJECTPOSITIONS.ahk" {OBJECTPOSITIONS}
#Import export ".\OBJECTTYPE.ahk" {OBJECTTYPE}
#Import export ".\PARAFORMAT.ahk" {PARAFORMAT}
#Import export ".\PARAFORMAT2.ahk" {PARAFORMAT2}
#Import export ".\PARAFORMAT_ALIGNMENT.ahk" {PARAFORMAT_ALIGNMENT}
#Import export ".\PARAFORMAT_BORDERS.ahk" {PARAFORMAT_BORDERS}
#Import export ".\PARAFORMAT_MASK.ahk" {PARAFORMAT_MASK}
#Import export ".\PARAFORMAT_NUMBERING.ahk" {PARAFORMAT_NUMBERING}
#Import export ".\PARAFORMAT_NUMBERING_STYLE.ahk" {PARAFORMAT_NUMBERING_STYLE}
#Import export ".\PARAFORMAT_SHADING_STYLE.ahk" {PARAFORMAT_SHADING_STYLE}
#Import export ".\PCreateTextServices.ahk" {PCreateTextServices}
#Import export ".\PShutdownTextServices.ahk" {PShutdownTextServices}
#Import export ".\PUNCTUATION.ahk" {PUNCTUATION}
#Import export ".\REOBJECT.ahk" {REOBJECT}
#Import export ".\REOBJECT_FLAGS.ahk" {REOBJECT_FLAGS}
#Import export ".\REPASTESPECIAL.ahk" {REPASTESPECIAL}
#Import export ".\REQRESIZE.ahk" {REQRESIZE}
#Import export ".\RICHEDIT_IMAGE_PARAMETERS.ahk" {RICHEDIT_IMAGE_PARAMETERS}
#Import export ".\RICH_EDIT_GET_CONTEXT_MENU_SEL_TYPE.ahk" {RICH_EDIT_GET_CONTEXT_MENU_SEL_TYPE}
#Import export ".\RICH_EDIT_GET_OBJECT_FLAGS.ahk" {RICH_EDIT_GET_OBJECT_FLAGS}
#Import export ".\SELCHANGE.ahk" {SELCHANGE}
#Import export ".\SETTEXTEX.ahk" {SETTEXTEX}
#Import export ".\TABLECELLPARMS.ahk" {TABLECELLPARMS}
#Import export ".\TABLEROWPARMS.ahk" {TABLEROWPARMS}
#Import export ".\TEXTMODE.ahk" {TEXTMODE}
#Import export ".\TEXTRANGEA.ahk" {TEXTRANGEA}
#Import export ".\TEXTRANGEW.ahk" {TEXTRANGEW}
#Import export ".\TXTBACKSTYLE.ahk" {TXTBACKSTYLE}
#Import export ".\TXTHITRESULT.ahk" {TXTHITRESULT}
#Import export ".\TXTNATURALSIZE.ahk" {TXTNATURALSIZE}
#Import export ".\TXTVIEW.ahk" {TXTVIEW}
#Import export ".\UNDONAMEID.ahk" {UNDONAMEID}
#Import export ".\tomConstants.ahk" {tomConstants}
