#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ADSI_DIALECT_ENUM.ahk" {ADSI_DIALECT_ENUM}
#Import export ".\ADSPROPERROR.ahk" {ADSPROPERROR}
#Import export ".\ADSPROPINITPARAMS.ahk" {ADSPROPINITPARAMS}
#Import export ".\ADSTYPE.ahk" {ADSTYPE}
#Import export ".\ADSVALUE.ahk" {ADSVALUE}
#Import export ".\ADS_ACEFLAG_ENUM.ahk" {ADS_ACEFLAG_ENUM}
#Import export ".\ADS_ACETYPE_ENUM.ahk" {ADS_ACETYPE_ENUM}
#Import export ".\ADS_ATTR_DEF.ahk" {ADS_ATTR_DEF}
#Import export ".\ADS_ATTR_INFO.ahk" {ADS_ATTR_INFO}
#Import export ".\ADS_AUTHENTICATION_ENUM.ahk" {ADS_AUTHENTICATION_ENUM}
#Import export ".\ADS_BACKLINK.ahk" {ADS_BACKLINK}
#Import export ".\ADS_CASEIGNORE_LIST.ahk" {ADS_CASEIGNORE_LIST}
#Import export ".\ADS_CHASE_REFERRALS_ENUM.ahk" {ADS_CHASE_REFERRALS_ENUM}
#Import export ".\ADS_CLASS_DEF.ahk" {ADS_CLASS_DEF}
#Import export ".\ADS_DEREFENUM.ahk" {ADS_DEREFENUM}
#Import export ".\ADS_DISPLAY_ENUM.ahk" {ADS_DISPLAY_ENUM}
#Import export ".\ADS_DN_WITH_BINARY.ahk" {ADS_DN_WITH_BINARY}
#Import export ".\ADS_DN_WITH_STRING.ahk" {ADS_DN_WITH_STRING}
#Import export ".\ADS_EMAIL.ahk" {ADS_EMAIL}
#Import export ".\ADS_ESCAPE_MODE_ENUM.ahk" {ADS_ESCAPE_MODE_ENUM}
#Import export ".\ADS_FAXNUMBER.ahk" {ADS_FAXNUMBER}
#Import export ".\ADS_FLAGTYPE_ENUM.ahk" {ADS_FLAGTYPE_ENUM}
#Import export ".\ADS_FORMAT_ENUM.ahk" {ADS_FORMAT_ENUM}
#Import export ".\ADS_GROUP_TYPE_ENUM.ahk" {ADS_GROUP_TYPE_ENUM}
#Import export ".\ADS_HOLD.ahk" {ADS_HOLD}
#Import export ".\ADS_NAME_INITTYPE_ENUM.ahk" {ADS_NAME_INITTYPE_ENUM}
#Import export ".\ADS_NAME_TYPE_ENUM.ahk" {ADS_NAME_TYPE_ENUM}
#Import export ".\ADS_NETADDRESS.ahk" {ADS_NETADDRESS}
#Import export ".\ADS_NT_SECURITY_DESCRIPTOR.ahk" {ADS_NT_SECURITY_DESCRIPTOR}
#Import export ".\ADS_OBJECT_INFO.ahk" {ADS_OBJECT_INFO}
#Import export ".\ADS_OCTET_LIST.ahk" {ADS_OCTET_LIST}
#Import export ".\ADS_OCTET_STRING.ahk" {ADS_OCTET_STRING}
#Import export ".\ADS_OPTION_ENUM.ahk" {ADS_OPTION_ENUM}
#Import export ".\ADS_PASSWORD_ENCODING_ENUM.ahk" {ADS_PASSWORD_ENCODING_ENUM}
#Import export ".\ADS_PATH.ahk" {ADS_PATH}
#Import export ".\ADS_PATHTYPE_ENUM.ahk" {ADS_PATHTYPE_ENUM}
#Import export ".\ADS_POSTALADDRESS.ahk" {ADS_POSTALADDRESS}
#Import export ".\ADS_PREFERENCES_ENUM.ahk" {ADS_PREFERENCES_ENUM}
#Import export ".\ADS_PROPERTY_OPERATION_ENUM.ahk" {ADS_PROPERTY_OPERATION_ENUM}
#Import export ".\ADS_PROV_SPECIFIC.ahk" {ADS_PROV_SPECIFIC}
#Import export ".\ADS_REPLICAPOINTER.ahk" {ADS_REPLICAPOINTER}
#Import export ".\ADS_RIGHTS_ENUM.ahk" {ADS_RIGHTS_ENUM}
#Import export ".\ADS_SCOPEENUM.ahk" {ADS_SCOPEENUM}
#Import export ".\ADS_SD_CONTROL_ENUM.ahk" {ADS_SD_CONTROL_ENUM}
#Import export ".\ADS_SD_FORMAT_ENUM.ahk" {ADS_SD_FORMAT_ENUM}
#Import export ".\ADS_SD_REVISION_ENUM.ahk" {ADS_SD_REVISION_ENUM}
#Import export ".\ADS_SEARCHPREF_ENUM.ahk" {ADS_SEARCHPREF_ENUM}
#Import export ".\ADS_SEARCHPREF_INFO.ahk" {ADS_SEARCHPREF_INFO}
#Import export ".\ADS_SEARCH_COLUMN.ahk" {ADS_SEARCH_COLUMN}
#Import export ".\ADS_SEARCH_HANDLE.ahk" {ADS_SEARCH_HANDLE}
#Import export ".\ADS_SECURITY_INFO_ENUM.ahk" {ADS_SECURITY_INFO_ENUM}
#Import export ".\ADS_SETTYPE_ENUM.ahk" {ADS_SETTYPE_ENUM}
#Import export ".\ADS_SORTKEY.ahk" {ADS_SORTKEY}
#Import export ".\ADS_STATUSENUM.ahk" {ADS_STATUSENUM}
#Import export ".\ADS_SYSTEMFLAG_ENUM.ahk" {ADS_SYSTEMFLAG_ENUM}
#Import export ".\ADS_TIMESTAMP.ahk" {ADS_TIMESTAMP}
#Import export ".\ADS_TYPEDNAME.ahk" {ADS_TYPEDNAME}
#Import export ".\ADS_USER_FLAG_ENUM.ahk" {ADS_USER_FLAG_ENUM}
#Import export ".\ADS_VLV.ahk" {ADS_VLV}
#Import export ".\ADSystemInfo.ahk" {ADSystemInfo}
#Import export ".\ADsSecurityUtility.ahk" {ADsSecurityUtility}
#Import export ".\AccessControlEntry.ahk" {AccessControlEntry}
#Import export ".\AccessControlList.ahk" {AccessControlList}
#Import export ".\Apis.ahk" {*}
#Import export ".\BackLink.ahk" {BackLink}
#Import export ".\CQFORM.ahk" {CQFORM}
#Import export ".\CQPAGE.ahk" {CQPAGE}
#Import export ".\CaseIgnoreList.ahk" {CaseIgnoreList}
#Import export ".\Constants.ahk" {*}
#Import export ".\DNWithBinary.ahk" {DNWithBinary}
#Import export ".\DNWithString.ahk" {DNWithString}
#Import export ".\DOMAINDESC.ahk" {DOMAINDESC}
#Import export ".\DOMAIN_CONTROLLER_INFOA.ahk" {DOMAIN_CONTROLLER_INFOA}
#Import export ".\DOMAIN_CONTROLLER_INFOW.ahk" {DOMAIN_CONTROLLER_INFOW}
#Import export ".\DOMAIN_TREE.ahk" {DOMAIN_TREE}
#Import export ".\DSA_NEWOBJ_DISPINFO.ahk" {DSA_NEWOBJ_DISPINFO}
#Import export ".\DSBITEMA.ahk" {DSBITEMA}
#Import export ".\DSBITEMW.ahk" {DSBITEMW}
#Import export ".\DSBROWSEINFOA.ahk" {DSBROWSEINFOA}
#Import export ".\DSBROWSEINFOW.ahk" {DSBROWSEINFOW}
#Import export ".\DSCLASSCREATIONINFO.ahk" {DSCLASSCREATIONINFO}
#Import export ".\DSCOLUMN.ahk" {DSCOLUMN}
#Import export ".\DSDISPLAYSPECOPTIONS.ahk" {DSDISPLAYSPECOPTIONS}
#Import export ".\DSOBJECT.ahk" {DSOBJECT}
#Import export ".\DSOBJECTNAMES.ahk" {DSOBJECTNAMES}
#Import export ".\DSOP_FILTER_FLAGS.ahk" {DSOP_FILTER_FLAGS}
#Import export ".\DSOP_INIT_INFO.ahk" {DSOP_INIT_INFO}
#Import export ".\DSOP_SCOPE_INIT_INFO.ahk" {DSOP_SCOPE_INIT_INFO}
#Import export ".\DSOP_UPLEVEL_FILTER_FLAGS.ahk" {DSOP_UPLEVEL_FILTER_FLAGS}
#Import export ".\DSPROPERTYPAGEINFO.ahk" {DSPROPERTYPAGEINFO}
#Import export ".\DSQUERYCLASSLIST.ahk" {DSQUERYCLASSLIST}
#Import export ".\DSQUERYINITPARAMS.ahk" {DSQUERYINITPARAMS}
#Import export ".\DSQUERYPARAMS.ahk" {DSQUERYPARAMS}
#Import export ".\DSROLE_MACHINE_ROLE.ahk" {DSROLE_MACHINE_ROLE}
#Import export ".\DSROLE_OPERATION_STATE.ahk" {DSROLE_OPERATION_STATE}
#Import export ".\DSROLE_OPERATION_STATE_INFO.ahk" {DSROLE_OPERATION_STATE_INFO}
#Import export ".\DSROLE_PRIMARY_DOMAIN_INFO_BASIC.ahk" {DSROLE_PRIMARY_DOMAIN_INFO_BASIC}
#Import export ".\DSROLE_PRIMARY_DOMAIN_INFO_LEVEL.ahk" {DSROLE_PRIMARY_DOMAIN_INFO_LEVEL}
#Import export ".\DSROLE_SERVER_STATE.ahk" {DSROLE_SERVER_STATE}
#Import export ".\DSROLE_UPGRADE_STATUS_INFO.ahk" {DSROLE_UPGRADE_STATUS_INFO}
#Import export ".\DS_DOMAIN_CONTROLLER_INFO_1A.ahk" {DS_DOMAIN_CONTROLLER_INFO_1A}
#Import export ".\DS_DOMAIN_CONTROLLER_INFO_1W.ahk" {DS_DOMAIN_CONTROLLER_INFO_1W}
#Import export ".\DS_DOMAIN_CONTROLLER_INFO_2A.ahk" {DS_DOMAIN_CONTROLLER_INFO_2A}
#Import export ".\DS_DOMAIN_CONTROLLER_INFO_2W.ahk" {DS_DOMAIN_CONTROLLER_INFO_2W}
#Import export ".\DS_DOMAIN_CONTROLLER_INFO_3A.ahk" {DS_DOMAIN_CONTROLLER_INFO_3A}
#Import export ".\DS_DOMAIN_CONTROLLER_INFO_3W.ahk" {DS_DOMAIN_CONTROLLER_INFO_3W}
#Import export ".\DS_DOMAIN_TRUSTSA.ahk" {DS_DOMAIN_TRUSTSA}
#Import export ".\DS_DOMAIN_TRUSTSW.ahk" {DS_DOMAIN_TRUSTSW}
#Import export ".\DS_KCC_TASKID.ahk" {DS_KCC_TASKID}
#Import export ".\DS_MANGLE_FOR.ahk" {DS_MANGLE_FOR}
#Import export ".\DS_NAME_ERROR.ahk" {DS_NAME_ERROR}
#Import export ".\DS_NAME_FLAGS.ahk" {DS_NAME_FLAGS}
#Import export ".\DS_NAME_FORMAT.ahk" {DS_NAME_FORMAT}
#Import export ".\DS_NAME_RESULTA.ahk" {DS_NAME_RESULTA}
#Import export ".\DS_NAME_RESULTW.ahk" {DS_NAME_RESULTW}
#Import export ".\DS_NAME_RESULT_ITEMA.ahk" {DS_NAME_RESULT_ITEMA}
#Import export ".\DS_NAME_RESULT_ITEMW.ahk" {DS_NAME_RESULT_ITEMW}
#Import export ".\DS_REPL_ATTR_META_DATA.ahk" {DS_REPL_ATTR_META_DATA}
#Import export ".\DS_REPL_ATTR_META_DATA_2.ahk" {DS_REPL_ATTR_META_DATA_2}
#Import export ".\DS_REPL_ATTR_META_DATA_BLOB.ahk" {DS_REPL_ATTR_META_DATA_BLOB}
#Import export ".\DS_REPL_ATTR_VALUE_META_DATA.ahk" {DS_REPL_ATTR_VALUE_META_DATA}
#Import export ".\DS_REPL_ATTR_VALUE_META_DATA_2.ahk" {DS_REPL_ATTR_VALUE_META_DATA_2}
#Import export ".\DS_REPL_ATTR_VALUE_META_DATA_EXT.ahk" {DS_REPL_ATTR_VALUE_META_DATA_EXT}
#Import export ".\DS_REPL_CURSOR.ahk" {DS_REPL_CURSOR}
#Import export ".\DS_REPL_CURSORS.ahk" {DS_REPL_CURSORS}
#Import export ".\DS_REPL_CURSORS_2.ahk" {DS_REPL_CURSORS_2}
#Import export ".\DS_REPL_CURSORS_3W.ahk" {DS_REPL_CURSORS_3W}
#Import export ".\DS_REPL_CURSOR_2.ahk" {DS_REPL_CURSOR_2}
#Import export ".\DS_REPL_CURSOR_3W.ahk" {DS_REPL_CURSOR_3W}
#Import export ".\DS_REPL_CURSOR_BLOB.ahk" {DS_REPL_CURSOR_BLOB}
#Import export ".\DS_REPL_INFO_TYPE.ahk" {DS_REPL_INFO_TYPE}
#Import export ".\DS_REPL_KCC_DSA_FAILURESW.ahk" {DS_REPL_KCC_DSA_FAILURESW}
#Import export ".\DS_REPL_KCC_DSA_FAILUREW.ahk" {DS_REPL_KCC_DSA_FAILUREW}
#Import export ".\DS_REPL_KCC_DSA_FAILUREW_BLOB.ahk" {DS_REPL_KCC_DSA_FAILUREW_BLOB}
#Import export ".\DS_REPL_NEIGHBORSW.ahk" {DS_REPL_NEIGHBORSW}
#Import export ".\DS_REPL_NEIGHBORW.ahk" {DS_REPL_NEIGHBORW}
#Import export ".\DS_REPL_NEIGHBORW_BLOB.ahk" {DS_REPL_NEIGHBORW_BLOB}
#Import export ".\DS_REPL_OBJ_META_DATA.ahk" {DS_REPL_OBJ_META_DATA}
#Import export ".\DS_REPL_OBJ_META_DATA_2.ahk" {DS_REPL_OBJ_META_DATA_2}
#Import export ".\DS_REPL_OPW.ahk" {DS_REPL_OPW}
#Import export ".\DS_REPL_OPW_BLOB.ahk" {DS_REPL_OPW_BLOB}
#Import export ".\DS_REPL_OP_TYPE.ahk" {DS_REPL_OP_TYPE}
#Import export ".\DS_REPL_PENDING_OPSW.ahk" {DS_REPL_PENDING_OPSW}
#Import export ".\DS_REPL_QUEUE_STATISTICSW.ahk" {DS_REPL_QUEUE_STATISTICSW}
#Import export ".\DS_REPL_VALUE_META_DATA.ahk" {DS_REPL_VALUE_META_DATA}
#Import export ".\DS_REPL_VALUE_META_DATA_2.ahk" {DS_REPL_VALUE_META_DATA_2}
#Import export ".\DS_REPL_VALUE_META_DATA_BLOB.ahk" {DS_REPL_VALUE_META_DATA_BLOB}
#Import export ".\DS_REPL_VALUE_META_DATA_BLOB_EXT.ahk" {DS_REPL_VALUE_META_DATA_BLOB_EXT}
#Import export ".\DS_REPL_VALUE_META_DATA_EXT.ahk" {DS_REPL_VALUE_META_DATA_EXT}
#Import export ".\DS_REPSYNCALL_ERRINFOA.ahk" {DS_REPSYNCALL_ERRINFOA}
#Import export ".\DS_REPSYNCALL_ERRINFOW.ahk" {DS_REPSYNCALL_ERRINFOW}
#Import export ".\DS_REPSYNCALL_ERROR.ahk" {DS_REPSYNCALL_ERROR}
#Import export ".\DS_REPSYNCALL_EVENT.ahk" {DS_REPSYNCALL_EVENT}
#Import export ".\DS_REPSYNCALL_SYNCA.ahk" {DS_REPSYNCALL_SYNCA}
#Import export ".\DS_REPSYNCALL_SYNCW.ahk" {DS_REPSYNCALL_SYNCW}
#Import export ".\DS_REPSYNCALL_UPDATEA.ahk" {DS_REPSYNCALL_UPDATEA}
#Import export ".\DS_REPSYNCALL_UPDATEW.ahk" {DS_REPSYNCALL_UPDATEW}
#Import export ".\DS_SCHEMA_GUID_MAPA.ahk" {DS_SCHEMA_GUID_MAPA}
#Import export ".\DS_SCHEMA_GUID_MAPW.ahk" {DS_SCHEMA_GUID_MAPW}
#Import export ".\DS_SELECTION.ahk" {DS_SELECTION}
#Import export ".\DS_SELECTION_LIST.ahk" {DS_SELECTION_LIST}
#Import export ".\DS_SITE_COST_INFO.ahk" {DS_SITE_COST_INFO}
#Import export ".\DS_SPN_NAME_TYPE.ahk" {DS_SPN_NAME_TYPE}
#Import export ".\DS_SPN_WRITE_OP.ahk" {DS_SPN_WRITE_OP}
#Import export ".\Email.ahk" {Email}
#Import export ".\FaxNumber.ahk" {FaxNumber}
#Import export ".\Hold.ahk" {Hold}
#Import export ".\IADs.ahk" {IADs}
#Import export ".\IADsADSystemInfo.ahk" {IADsADSystemInfo}
#Import export ".\IADsAccessControlEntry.ahk" {IADsAccessControlEntry}
#Import export ".\IADsAccessControlList.ahk" {IADsAccessControlList}
#Import export ".\IADsAcl.ahk" {IADsAcl}
#Import export ".\IADsAggregatee.ahk" {IADsAggregatee}
#Import export ".\IADsAggregator.ahk" {IADsAggregator}
#Import export ".\IADsBackLink.ahk" {IADsBackLink}
#Import export ".\IADsCaseIgnoreList.ahk" {IADsCaseIgnoreList}
#Import export ".\IADsClass.ahk" {IADsClass}
#Import export ".\IADsCollection.ahk" {IADsCollection}
#Import export ".\IADsComputer.ahk" {IADsComputer}
#Import export ".\IADsComputerOperations.ahk" {IADsComputerOperations}
#Import export ".\IADsContainer.ahk" {IADsContainer}
#Import export ".\IADsDNWithBinary.ahk" {IADsDNWithBinary}
#Import export ".\IADsDNWithString.ahk" {IADsDNWithString}
#Import export ".\IADsDeleteOps.ahk" {IADsDeleteOps}
#Import export ".\IADsDomain.ahk" {IADsDomain}
#Import export ".\IADsEmail.ahk" {IADsEmail}
#Import export ".\IADsExtension.ahk" {IADsExtension}
#Import export ".\IADsFaxNumber.ahk" {IADsFaxNumber}
#Import export ".\IADsFileService.ahk" {IADsFileService}
#Import export ".\IADsFileServiceOperations.ahk" {IADsFileServiceOperations}
#Import export ".\IADsFileShare.ahk" {IADsFileShare}
#Import export ".\IADsGroup.ahk" {IADsGroup}
#Import export ".\IADsHold.ahk" {IADsHold}
#Import export ".\IADsLargeInteger.ahk" {IADsLargeInteger}
#Import export ".\IADsLocality.ahk" {IADsLocality}
#Import export ".\IADsMembers.ahk" {IADsMembers}
#Import export ".\IADsNameTranslate.ahk" {IADsNameTranslate}
#Import export ".\IADsNamespaces.ahk" {IADsNamespaces}
#Import export ".\IADsNetAddress.ahk" {IADsNetAddress}
#Import export ".\IADsO.ahk" {IADsO}
#Import export ".\IADsOU.ahk" {IADsOU}
#Import export ".\IADsObjectOptions.ahk" {IADsObjectOptions}
#Import export ".\IADsOctetList.ahk" {IADsOctetList}
#Import export ".\IADsOpenDSObject.ahk" {IADsOpenDSObject}
#Import export ".\IADsPath.ahk" {IADsPath}
#Import export ".\IADsPathname.ahk" {IADsPathname}
#Import export ".\IADsPostalAddress.ahk" {IADsPostalAddress}
#Import export ".\IADsPrintJob.ahk" {IADsPrintJob}
#Import export ".\IADsPrintJobOperations.ahk" {IADsPrintJobOperations}
#Import export ".\IADsPrintQueue.ahk" {IADsPrintQueue}
#Import export ".\IADsPrintQueueOperations.ahk" {IADsPrintQueueOperations}
#Import export ".\IADsProperty.ahk" {IADsProperty}
#Import export ".\IADsPropertyEntry.ahk" {IADsPropertyEntry}
#Import export ".\IADsPropertyList.ahk" {IADsPropertyList}
#Import export ".\IADsPropertyValue.ahk" {IADsPropertyValue}
#Import export ".\IADsPropertyValue2.ahk" {IADsPropertyValue2}
#Import export ".\IADsReplicaPointer.ahk" {IADsReplicaPointer}
#Import export ".\IADsResource.ahk" {IADsResource}
#Import export ".\IADsSecurityDescriptor.ahk" {IADsSecurityDescriptor}
#Import export ".\IADsSecurityUtility.ahk" {IADsSecurityUtility}
#Import export ".\IADsService.ahk" {IADsService}
#Import export ".\IADsServiceOperations.ahk" {IADsServiceOperations}
#Import export ".\IADsSession.ahk" {IADsSession}
#Import export ".\IADsSyntax.ahk" {IADsSyntax}
#Import export ".\IADsTimestamp.ahk" {IADsTimestamp}
#Import export ".\IADsTypedName.ahk" {IADsTypedName}
#Import export ".\IADsUser.ahk" {IADsUser}
#Import export ".\IADsWinNTSystemInfo.ahk" {IADsWinNTSystemInfo}
#Import export ".\ICommonQuery.ahk" {ICommonQuery}
#Import export ".\IDirectoryObject.ahk" {IDirectoryObject}
#Import export ".\IDirectorySchemaMgmt.ahk" {IDirectorySchemaMgmt}
#Import export ".\IDirectorySearch.ahk" {IDirectorySearch}
#Import export ".\IDsAdminCreateObj.ahk" {IDsAdminCreateObj}
#Import export ".\IDsAdminNewObj.ahk" {IDsAdminNewObj}
#Import export ".\IDsAdminNewObjExt.ahk" {IDsAdminNewObjExt}
#Import export ".\IDsAdminNewObjPrimarySite.ahk" {IDsAdminNewObjPrimarySite}
#Import export ".\IDsAdminNotifyHandler.ahk" {IDsAdminNotifyHandler}
#Import export ".\IDsBrowseDomainTree.ahk" {IDsBrowseDomainTree}
#Import export ".\IDsDisplaySpecifier.ahk" {IDsDisplaySpecifier}
#Import export ".\IDsObjectPicker.ahk" {IDsObjectPicker}
#Import export ".\IDsObjectPickerCredentials.ahk" {IDsObjectPickerCredentials}
#Import export ".\IPersistQuery.ahk" {IPersistQuery}
#Import export ".\IPrivateDispatch.ahk" {IPrivateDispatch}
#Import export ".\IPrivateUnknown.ahk" {IPrivateUnknown}
#Import export ".\IQueryForm.ahk" {IQueryForm}
#Import export ".\LPCQADDFORMSPROC.ahk" {LPCQADDFORMSPROC}
#Import export ".\LPCQADDPAGESPROC.ahk" {LPCQADDPAGESPROC}
#Import export ".\LPCQPAGEPROC.ahk" {LPCQPAGEPROC}
#Import export ".\LPDSENUMATTRIBUTES.ahk" {LPDSENUMATTRIBUTES}
#Import export ".\LargeInteger.ahk" {LargeInteger}
#Import export ".\NameTranslate.ahk" {NameTranslate}
#Import export ".\NetAddress.ahk" {NetAddress}
#Import export ".\OPENQUERYWINDOW.ahk" {OPENQUERYWINDOW}
#Import export ".\OctetList.ahk" {OctetList}
#Import export ".\Path.ahk" {Path}
#Import export ".\Pathname.ahk" {Pathname}
#Import export ".\PostalAddress.ahk" {PostalAddress}
#Import export ".\PropertyEntry.ahk" {PropertyEntry}
#Import export ".\PropertyValue.ahk" {PropertyValue}
#Import export ".\ReplicaPointer.ahk" {ReplicaPointer}
#Import export ".\SCHEDULE.ahk" {SCHEDULE}
#Import export ".\SCHEDULE_HEADER.ahk" {SCHEDULE_HEADER}
#Import export ".\SecurityDescriptor.ahk" {SecurityDescriptor}
#Import export ".\Timestamp.ahk" {Timestamp}
#Import export ".\TypedName.ahk" {TypedName}
#Import export ".\WinNTSystemInfo.ahk" {WinNTSystemInfo}
