#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\AR_STATE.ahk" {AR_STATE}
#Import export ".\Adapter.ahk" {Adapter}
#Import export ".\Adapters.ahk" {Adapters}
#Import export ".\Apis.ahk" {*}
#Import export ".\BACKLIGHT_OPTIMIZATION_LEVEL.ahk" {BACKLIGHT_OPTIMIZATION_LEVEL}
#Import export ".\BACKLIGHT_REDUCTION_GAMMA_RAMP.ahk" {BACKLIGHT_REDUCTION_GAMMA_RAMP}
#Import export ".\BANK_POSITION.ahk" {BANK_POSITION}
#Import export ".\BLENDOBJ.ahk" {BLENDOBJ}
#Import export ".\BRIGHTNESS_INTERFACE_VERSION.ahk" {BRIGHTNESS_INTERFACE_VERSION}
#Import export ".\BRIGHTNESS_LEVEL.ahk" {BRIGHTNESS_LEVEL}
#Import export ".\BRIGHTNESS_NIT_RANGE.ahk" {BRIGHTNESS_NIT_RANGE}
#Import export ".\BRIGHTNESS_NIT_RANGES.ahk" {BRIGHTNESS_NIT_RANGES}
#Import export ".\BRUSHOBJ.ahk" {BRUSHOBJ}
#Import export ".\BlackScreenDiagnosticsCalloutParam.ahk" {BlackScreenDiagnosticsCalloutParam}
#Import export ".\CDDDXGK_REDIRBITMAPPRESENTINFO.ahk" {CDDDXGK_REDIRBITMAPPRESENTINFO}
#Import export ".\CHAR_IMAGE_INFO.ahk" {CHAR_IMAGE_INFO}
#Import export ".\CHROMATICITY_COORDINATE.ahk" {CHROMATICITY_COORDINATE}
#Import export ".\CIECHROMA.ahk" {CIECHROMA}
#Import export ".\CLIPLINE.ahk" {CLIPLINE}
#Import export ".\CLIPOBJ.ahk" {CLIPOBJ}
#Import export ".\COLORINFO.ahk" {COLORINFO}
#Import export ".\COLORSPACE_SCALAR_MULTIPLIER_CAPS.ahk" {COLORSPACE_SCALAR_MULTIPLIER_CAPS}
#Import export ".\COLORSPACE_TRANSFORM.ahk" {COLORSPACE_TRANSFORM}
#Import export ".\COLORSPACE_TRANSFORM_1DLUT_CAP.ahk" {COLORSPACE_TRANSFORM_1DLUT_CAP}
#Import export ".\COLORSPACE_TRANSFORM_3x4.ahk" {COLORSPACE_TRANSFORM_3x4}
#Import export ".\COLORSPACE_TRANSFORM_DATA_CAP.ahk" {COLORSPACE_TRANSFORM_DATA_CAP}
#Import export ".\COLORSPACE_TRANSFORM_DATA_TYPE.ahk" {COLORSPACE_TRANSFORM_DATA_TYPE}
#Import export ".\COLORSPACE_TRANSFORM_MATRIX_CAP.ahk" {COLORSPACE_TRANSFORM_MATRIX_CAP}
#Import export ".\COLORSPACE_TRANSFORM_MATRIX_V2.ahk" {COLORSPACE_TRANSFORM_MATRIX_V2}
#Import export ".\COLORSPACE_TRANSFORM_SET_INPUT.ahk" {COLORSPACE_TRANSFORM_SET_INPUT}
#Import export ".\COLORSPACE_TRANSFORM_STAGE_CONTROL.ahk" {COLORSPACE_TRANSFORM_STAGE_CONTROL}
#Import export ".\COLORSPACE_TRANSFORM_TARGET_CAPS.ahk" {COLORSPACE_TRANSFORM_TARGET_CAPS}
#Import export ".\COLORSPACE_TRANSFORM_TARGET_CAPS_VERSION.ahk" {COLORSPACE_TRANSFORM_TARGET_CAPS_VERSION}
#Import export ".\COLORSPACE_TRANSFORM_TYPE.ahk" {COLORSPACE_TRANSFORM_TYPE}
#Import export ".\Constants.ahk" {*}
#Import export ".\DEVHTADJDATA.ahk" {DEVHTADJDATA}
#Import export ".\DEVHTINFO.ahk" {DEVHTINFO}
#Import export ".\DEVINFO.ahk" {DEVINFO}
#Import export ".\DHPDEV.ahk" {DHPDEV}
#Import export ".\DHSURF.ahk" {DHSURF}
#Import export ".\DISPLAYCONFIG_2DREGION.ahk" {DISPLAYCONFIG_2DREGION}
#Import export ".\DISPLAYCONFIG_ADAPTER_NAME.ahk" {DISPLAYCONFIG_ADAPTER_NAME}
#Import export ".\DISPLAYCONFIG_DESKTOP_IMAGE_INFO.ahk" {DISPLAYCONFIG_DESKTOP_IMAGE_INFO}
#Import export ".\DISPLAYCONFIG_DEVICE_INFO_HEADER.ahk" {DISPLAYCONFIG_DEVICE_INFO_HEADER}
#Import export ".\DISPLAYCONFIG_DEVICE_INFO_TYPE.ahk" {DISPLAYCONFIG_DEVICE_INFO_TYPE}
#Import export ".\DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO.ahk" {DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO}
#Import export ".\DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO_2.ahk" {DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO_2}
#Import export ".\DISPLAYCONFIG_GET_MONITOR_SPECIALIZATION.ahk" {DISPLAYCONFIG_GET_MONITOR_SPECIALIZATION}
#Import export ".\DISPLAYCONFIG_MODE_INFO.ahk" {DISPLAYCONFIG_MODE_INFO}
#Import export ".\DISPLAYCONFIG_MODE_INFO_TYPE.ahk" {DISPLAYCONFIG_MODE_INFO_TYPE}
#Import export ".\DISPLAYCONFIG_PATH_INFO.ahk" {DISPLAYCONFIG_PATH_INFO}
#Import export ".\DISPLAYCONFIG_PATH_SOURCE_INFO.ahk" {DISPLAYCONFIG_PATH_SOURCE_INFO}
#Import export ".\DISPLAYCONFIG_PATH_TARGET_INFO.ahk" {DISPLAYCONFIG_PATH_TARGET_INFO}
#Import export ".\DISPLAYCONFIG_PIXELFORMAT.ahk" {DISPLAYCONFIG_PIXELFORMAT}
#Import export ".\DISPLAYCONFIG_RATIONAL.ahk" {DISPLAYCONFIG_RATIONAL}
#Import export ".\DISPLAYCONFIG_ROTATION.ahk" {DISPLAYCONFIG_ROTATION}
#Import export ".\DISPLAYCONFIG_SCALING.ahk" {DISPLAYCONFIG_SCALING}
#Import export ".\DISPLAYCONFIG_SCANLINE_ORDERING.ahk" {DISPLAYCONFIG_SCANLINE_ORDERING}
#Import export ".\DISPLAYCONFIG_SDR_WHITE_LEVEL.ahk" {DISPLAYCONFIG_SDR_WHITE_LEVEL}
#Import export ".\DISPLAYCONFIG_SET_ADVANCED_COLOR_STATE.ahk" {DISPLAYCONFIG_SET_ADVANCED_COLOR_STATE}
#Import export ".\DISPLAYCONFIG_SET_HDR_STATE.ahk" {DISPLAYCONFIG_SET_HDR_STATE}
#Import export ".\DISPLAYCONFIG_SET_MONITOR_SPECIALIZATION.ahk" {DISPLAYCONFIG_SET_MONITOR_SPECIALIZATION}
#Import export ".\DISPLAYCONFIG_SET_TARGET_PERSISTENCE.ahk" {DISPLAYCONFIG_SET_TARGET_PERSISTENCE}
#Import export ".\DISPLAYCONFIG_SET_WCG_STATE.ahk" {DISPLAYCONFIG_SET_WCG_STATE}
#Import export ".\DISPLAYCONFIG_SOURCE_DEVICE_NAME.ahk" {DISPLAYCONFIG_SOURCE_DEVICE_NAME}
#Import export ".\DISPLAYCONFIG_SOURCE_MODE.ahk" {DISPLAYCONFIG_SOURCE_MODE}
#Import export ".\DISPLAYCONFIG_SUPPORT_VIRTUAL_RESOLUTION.ahk" {DISPLAYCONFIG_SUPPORT_VIRTUAL_RESOLUTION}
#Import export ".\DISPLAYCONFIG_TARGET_BASE_TYPE.ahk" {DISPLAYCONFIG_TARGET_BASE_TYPE}
#Import export ".\DISPLAYCONFIG_TARGET_DEVICE_NAME.ahk" {DISPLAYCONFIG_TARGET_DEVICE_NAME}
#Import export ".\DISPLAYCONFIG_TARGET_DEVICE_NAME_FLAGS.ahk" {DISPLAYCONFIG_TARGET_DEVICE_NAME_FLAGS}
#Import export ".\DISPLAYCONFIG_TARGET_MODE.ahk" {DISPLAYCONFIG_TARGET_MODE}
#Import export ".\DISPLAYCONFIG_TARGET_PREFERRED_MODE.ahk" {DISPLAYCONFIG_TARGET_PREFERRED_MODE}
#Import export ".\DISPLAYCONFIG_TOPOLOGY_ID.ahk" {DISPLAYCONFIG_TOPOLOGY_ID}
#Import export ".\DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY.ahk" {DISPLAYCONFIG_VIDEO_OUTPUT_TECHNOLOGY}
#Import export ".\DISPLAYCONFIG_VIDEO_SIGNAL_INFO.ahk" {DISPLAYCONFIG_VIDEO_SIGNAL_INFO}
#Import export ".\DISPLAY_BRIGHTNESS.ahk" {DISPLAY_BRIGHTNESS}
#Import export ".\DRH_APIBITMAPDATA.ahk" {DRH_APIBITMAPDATA}
#Import export ".\DRIVEROBJ.ahk" {DRIVEROBJ}
#Import export ".\DRVENABLEDATA.ahk" {DRVENABLEDATA}
#Import export ".\DRVFN.ahk" {DRVFN}
#Import export ".\DSI_CONTROL_TRANSMISSION_MODE.ahk" {DSI_CONTROL_TRANSMISSION_MODE}
#Import export ".\DXGK_WIN32K_PARAM_DATA.ahk" {DXGK_WIN32K_PARAM_DATA}
#Import export ".\DisplayMode.ahk" {DisplayMode}
#Import export ".\DisplayModes.ahk" {DisplayModes}
#Import export ".\EMFINFO.ahk" {EMFINFO}
#Import export ".\ENGSAFESEMAPHORE.ahk" {ENGSAFESEMAPHORE}
#Import export ".\ENG_DEVICE_ATTRIBUTE.ahk" {ENG_DEVICE_ATTRIBUTE}
#Import export ".\ENG_EVENT.ahk" {ENG_EVENT}
#Import export ".\ENG_SYSTEM_ATTRIBUTE.ahk" {ENG_SYSTEM_ATTRIBUTE}
#Import export ".\ENG_TIME_FIELDS.ahk" {ENG_TIME_FIELDS}
#Import export ".\ENUMRECTS.ahk" {ENUMRECTS}
#Import export ".\FD_DEVICEMETRICS.ahk" {FD_DEVICEMETRICS}
#Import export ".\FD_GLYPHATTR.ahk" {FD_GLYPHATTR}
#Import export ".\FD_GLYPHSET.ahk" {FD_GLYPHSET}
#Import export ".\FD_KERNINGPAIR.ahk" {FD_KERNINGPAIR}
#Import export ".\FD_LIGATURE.ahk" {FD_LIGATURE}
#Import export ".\FD_XFORM.ahk" {FD_XFORM}
#Import export ".\FLOATOBJ_XFORM.ahk" {FLOATOBJ_XFORM}
#Import export ".\FLOAT_LONG.ahk" {FLOAT_LONG}
#Import export ".\FONTDIFF.ahk" {FONTDIFF}
#Import export ".\FONTINFO.ahk" {FONTINFO}
#Import export ".\FONTOBJ.ahk" {FONTOBJ}
#Import export ".\FONTSIM.ahk" {FONTSIM}
#Import export ".\FONT_IMAGE_INFO.ahk" {FONT_IMAGE_INFO}
#Import export ".\FREEOBJPROC.ahk" {FREEOBJPROC}
#Import export ".\FSCNTL_SCREEN_INFO.ahk" {FSCNTL_SCREEN_INFO}
#Import export ".\FSVIDEO_COPY_FRAME_BUFFER.ahk" {FSVIDEO_COPY_FRAME_BUFFER}
#Import export ".\FSVIDEO_CURSOR_POSITION.ahk" {FSVIDEO_CURSOR_POSITION}
#Import export ".\FSVIDEO_MODE_INFORMATION.ahk" {FSVIDEO_MODE_INFORMATION}
#Import export ".\FSVIDEO_REVERSE_MOUSE_POINTER.ahk" {FSVIDEO_REVERSE_MOUSE_POINTER}
#Import export ".\FSVIDEO_SCREEN_INFORMATION.ahk" {FSVIDEO_SCREEN_INFORMATION}
#Import export ".\FSVIDEO_WRITE_TO_FRAME_BUFFER.ahk" {FSVIDEO_WRITE_TO_FRAME_BUFFER}
#Import export ".\GAMMARAMP.ahk" {GAMMARAMP}
#Import export ".\GAMMA_RAMP_DXGI_1.ahk" {GAMMA_RAMP_DXGI_1}
#Import export ".\GAMMA_RAMP_RGB.ahk" {GAMMA_RAMP_RGB}
#Import export ".\GAMMA_RAMP_RGB256x3x16.ahk" {GAMMA_RAMP_RGB256x3x16}
#Import export ".\GDIINFO.ahk" {GDIINFO}
#Import export ".\GLYPHBITS.ahk" {GLYPHBITS}
#Import export ".\GLYPHDATA.ahk" {GLYPHDATA}
#Import export ".\GLYPHDEF.ahk" {GLYPHDEF}
#Import export ".\GLYPHPOS.ahk" {GLYPHPOS}
#Import export ".\HBM.ahk" {HBM}
#Import export ".\HDEV.ahk" {HDEV}
#Import export ".\HDRVOBJ.ahk" {HDRVOBJ}
#Import export ".\HFASTMUTEX.ahk" {HFASTMUTEX}
#Import export ".\HSEMAPHORE.ahk" {HSEMAPHORE}
#Import export ".\HSURF.ahk" {HSURF}
#Import export ".\ICloneViewHelper.ahk" {ICloneViewHelper}
#Import export ".\IFIEXTRA.ahk" {IFIEXTRA}
#Import export ".\IFIMETRICS.ahk" {IFIMETRICS}
#Import export ".\INDIRECT_DISPLAY_INFO.ahk" {INDIRECT_DISPLAY_INFO}
#Import export ".\IViewHelper.ahk" {IViewHelper}
#Import export ".\LIGATURE.ahk" {LIGATURE}
#Import export ".\LINEATTRS.ahk" {LINEATTRS}
#Import export ".\MC_COLOR_TEMPERATURE.ahk" {MC_COLOR_TEMPERATURE}
#Import export ".\MC_DISPLAY_TECHNOLOGY_TYPE.ahk" {MC_DISPLAY_TECHNOLOGY_TYPE}
#Import export ".\MC_DRIVE_TYPE.ahk" {MC_DRIVE_TYPE}
#Import export ".\MC_GAIN_TYPE.ahk" {MC_GAIN_TYPE}
#Import export ".\MC_POSITION_TYPE.ahk" {MC_POSITION_TYPE}
#Import export ".\MC_SIZE_TYPE.ahk" {MC_SIZE_TYPE}
#Import export ".\MC_TIMING_REPORT.ahk" {MC_TIMING_REPORT}
#Import export ".\MC_VCP_CODE_TYPE.ahk" {MC_VCP_CODE_TYPE}
#Import export ".\MIPI_DSI_CAPS.ahk" {MIPI_DSI_CAPS}
#Import export ".\MIPI_DSI_PACKET.ahk" {MIPI_DSI_PACKET}
#Import export ".\MIPI_DSI_RESET.ahk" {MIPI_DSI_RESET}
#Import export ".\MIPI_DSI_TRANSMISSION.ahk" {MIPI_DSI_TRANSMISSION}
#Import export ".\ORIENTATION_PREFERENCE.ahk" {ORIENTATION_PREFERENCE}
#Import export ".\OUTPUT_COLOR_ENCODING.ahk" {OUTPUT_COLOR_ENCODING}
#Import export ".\OUTPUT_WIRE_COLOR_SPACE_TYPE.ahk" {OUTPUT_WIRE_COLOR_SPACE_TYPE}
#Import export ".\OUTPUT_WIRE_FORMAT.ahk" {OUTPUT_WIRE_FORMAT}
#Import export ".\PALOBJ.ahk" {PALOBJ}
#Import export ".\PANEL_BRIGHTNESS_SENSOR_DATA.ahk" {PANEL_BRIGHTNESS_SENSOR_DATA}
#Import export ".\PANEL_GET_BACKLIGHT_REDUCTION.ahk" {PANEL_GET_BACKLIGHT_REDUCTION}
#Import export ".\PANEL_GET_BRIGHTNESS.ahk" {PANEL_GET_BRIGHTNESS}
#Import export ".\PANEL_QUERY_BRIGHTNESS_CAPS.ahk" {PANEL_QUERY_BRIGHTNESS_CAPS}
#Import export ".\PANEL_QUERY_BRIGHTNESS_RANGES.ahk" {PANEL_QUERY_BRIGHTNESS_RANGES}
#Import export ".\PANEL_SET_BACKLIGHT_OPTIMIZATION.ahk" {PANEL_SET_BACKLIGHT_OPTIMIZATION}
#Import export ".\PANEL_SET_BRIGHTNESS.ahk" {PANEL_SET_BRIGHTNESS}
#Import export ".\PANEL_SET_BRIGHTNESS_STATE.ahk" {PANEL_SET_BRIGHTNESS_STATE}
#Import export ".\PATHDATA.ahk" {PATHDATA}
#Import export ".\PATHOBJ.ahk" {PATHOBJ}
#Import export ".\PERBANDINFO.ahk" {PERBANDINFO}
#Import export ".\PFN.ahk" {PFN}
#Import export ".\PFN_DrvAccumulateD3DDirtyRect.ahk" {PFN_DrvAccumulateD3DDirtyRect}
#Import export ".\PFN_DrvAlphaBlend.ahk" {PFN_DrvAlphaBlend}
#Import export ".\PFN_DrvAssertMode.ahk" {PFN_DrvAssertMode}
#Import export ".\PFN_DrvAssociateSharedSurface.ahk" {PFN_DrvAssociateSharedSurface}
#Import export ".\PFN_DrvBitBlt.ahk" {PFN_DrvBitBlt}
#Import export ".\PFN_DrvCompletePDEV.ahk" {PFN_DrvCompletePDEV}
#Import export ".\PFN_DrvCopyBits.ahk" {PFN_DrvCopyBits}
#Import export ".\PFN_DrvCreateDeviceBitmap.ahk" {PFN_DrvCreateDeviceBitmap}
#Import export ".\PFN_DrvCreateDeviceBitmapEx.ahk" {PFN_DrvCreateDeviceBitmapEx}
#Import export ".\PFN_DrvDeleteDeviceBitmap.ahk" {PFN_DrvDeleteDeviceBitmap}
#Import export ".\PFN_DrvDeleteDeviceBitmapEx.ahk" {PFN_DrvDeleteDeviceBitmapEx}
#Import export ".\PFN_DrvDeriveSurface.ahk" {PFN_DrvDeriveSurface}
#Import export ".\PFN_DrvDescribePixelFormat.ahk" {PFN_DrvDescribePixelFormat}
#Import export ".\PFN_DrvDestroyFont.ahk" {PFN_DrvDestroyFont}
#Import export ".\PFN_DrvDisableDirectDraw.ahk" {PFN_DrvDisableDirectDraw}
#Import export ".\PFN_DrvDisableDriver.ahk" {PFN_DrvDisableDriver}
#Import export ".\PFN_DrvDisablePDEV.ahk" {PFN_DrvDisablePDEV}
#Import export ".\PFN_DrvDisableSurface.ahk" {PFN_DrvDisableSurface}
#Import export ".\PFN_DrvDitherColor.ahk" {PFN_DrvDitherColor}
#Import export ".\PFN_DrvDrawEscape.ahk" {PFN_DrvDrawEscape}
#Import export ".\PFN_DrvEnableDirectDraw.ahk" {PFN_DrvEnableDirectDraw}
#Import export ".\PFN_DrvEnableDriver.ahk" {PFN_DrvEnableDriver}
#Import export ".\PFN_DrvEnablePDEV.ahk" {PFN_DrvEnablePDEV}
#Import export ".\PFN_DrvEnableSurface.ahk" {PFN_DrvEnableSurface}
#Import export ".\PFN_DrvEndDoc.ahk" {PFN_DrvEndDoc}
#Import export ".\PFN_DrvEndDxInterop.ahk" {PFN_DrvEndDxInterop}
#Import export ".\PFN_DrvEscape.ahk" {PFN_DrvEscape}
#Import export ".\PFN_DrvFillPath.ahk" {PFN_DrvFillPath}
#Import export ".\PFN_DrvFontManagement.ahk" {PFN_DrvFontManagement}
#Import export ".\PFN_DrvFree.ahk" {PFN_DrvFree}
#Import export ".\PFN_DrvGetDirectDrawInfo.ahk" {PFN_DrvGetDirectDrawInfo}
#Import export ".\PFN_DrvGetGlyphMode.ahk" {PFN_DrvGetGlyphMode}
#Import export ".\PFN_DrvGetModes.ahk" {PFN_DrvGetModes}
#Import export ".\PFN_DrvGetTrueTypeFile.ahk" {PFN_DrvGetTrueTypeFile}
#Import export ".\PFN_DrvGradientFill.ahk" {PFN_DrvGradientFill}
#Import export ".\PFN_DrvIcmCheckBitmapBits.ahk" {PFN_DrvIcmCheckBitmapBits}
#Import export ".\PFN_DrvIcmCreateColorTransform.ahk" {PFN_DrvIcmCreateColorTransform}
#Import export ".\PFN_DrvIcmDeleteColorTransform.ahk" {PFN_DrvIcmDeleteColorTransform}
#Import export ".\PFN_DrvIcmSetDeviceGammaRamp.ahk" {PFN_DrvIcmSetDeviceGammaRamp}
#Import export ".\PFN_DrvLineTo.ahk" {PFN_DrvLineTo}
#Import export ".\PFN_DrvLoadFontFile.ahk" {PFN_DrvLoadFontFile}
#Import export ".\PFN_DrvLockDisplayArea.ahk" {PFN_DrvLockDisplayArea}
#Import export ".\PFN_DrvMovePointer.ahk" {PFN_DrvMovePointer}
#Import export ".\PFN_DrvNextBand.ahk" {PFN_DrvNextBand}
#Import export ".\PFN_DrvNotify.ahk" {PFN_DrvNotify}
#Import export ".\PFN_DrvPaint.ahk" {PFN_DrvPaint}
#Import export ".\PFN_DrvPlgBlt.ahk" {PFN_DrvPlgBlt}
#Import export ".\PFN_DrvQueryAdvanceWidths.ahk" {PFN_DrvQueryAdvanceWidths}
#Import export ".\PFN_DrvQueryDeviceSupport.ahk" {PFN_DrvQueryDeviceSupport}
#Import export ".\PFN_DrvQueryFont.ahk" {PFN_DrvQueryFont}
#Import export ".\PFN_DrvQueryFontCaps.ahk" {PFN_DrvQueryFontCaps}
#Import export ".\PFN_DrvQueryFontData.ahk" {PFN_DrvQueryFontData}
#Import export ".\PFN_DrvQueryFontFile.ahk" {PFN_DrvQueryFontFile}
#Import export ".\PFN_DrvQueryFontTree.ahk" {PFN_DrvQueryFontTree}
#Import export ".\PFN_DrvQueryGlyphAttrs.ahk" {PFN_DrvQueryGlyphAttrs}
#Import export ".\PFN_DrvQueryPerBandInfo.ahk" {PFN_DrvQueryPerBandInfo}
#Import export ".\PFN_DrvQuerySpoolType.ahk" {PFN_DrvQuerySpoolType}
#Import export ".\PFN_DrvQueryTrueTypeOutline.ahk" {PFN_DrvQueryTrueTypeOutline}
#Import export ".\PFN_DrvQueryTrueTypeSection.ahk" {PFN_DrvQueryTrueTypeSection}
#Import export ".\PFN_DrvQueryTrueTypeTable.ahk" {PFN_DrvQueryTrueTypeTable}
#Import export ".\PFN_DrvRealizeBrush.ahk" {PFN_DrvRealizeBrush}
#Import export ".\PFN_DrvRenderHint.ahk" {PFN_DrvRenderHint}
#Import export ".\PFN_DrvResetDevice.ahk" {PFN_DrvResetDevice}
#Import export ".\PFN_DrvResetPDEV.ahk" {PFN_DrvResetPDEV}
#Import export ".\PFN_DrvSaveScreenBits.ahk" {PFN_DrvSaveScreenBits}
#Import export ".\PFN_DrvSendPage.ahk" {PFN_DrvSendPage}
#Import export ".\PFN_DrvSetPalette.ahk" {PFN_DrvSetPalette}
#Import export ".\PFN_DrvSetPixelFormat.ahk" {PFN_DrvSetPixelFormat}
#Import export ".\PFN_DrvSetPointerShape.ahk" {PFN_DrvSetPointerShape}
#Import export ".\PFN_DrvStartBanding.ahk" {PFN_DrvStartBanding}
#Import export ".\PFN_DrvStartDoc.ahk" {PFN_DrvStartDoc}
#Import export ".\PFN_DrvStartDxInterop.ahk" {PFN_DrvStartDxInterop}
#Import export ".\PFN_DrvStartPage.ahk" {PFN_DrvStartPage}
#Import export ".\PFN_DrvStretchBlt.ahk" {PFN_DrvStretchBlt}
#Import export ".\PFN_DrvStretchBltROP.ahk" {PFN_DrvStretchBltROP}
#Import export ".\PFN_DrvStrokeAndFillPath.ahk" {PFN_DrvStrokeAndFillPath}
#Import export ".\PFN_DrvStrokePath.ahk" {PFN_DrvStrokePath}
#Import export ".\PFN_DrvSurfaceComplete.ahk" {PFN_DrvSurfaceComplete}
#Import export ".\PFN_DrvSwapBuffers.ahk" {PFN_DrvSwapBuffers}
#Import export ".\PFN_DrvSynchronize.ahk" {PFN_DrvSynchronize}
#Import export ".\PFN_DrvSynchronizeRedirectionBitmaps.ahk" {PFN_DrvSynchronizeRedirectionBitmaps}
#Import export ".\PFN_DrvSynchronizeSurface.ahk" {PFN_DrvSynchronizeSurface}
#Import export ".\PFN_DrvTextOut.ahk" {PFN_DrvTextOut}
#Import export ".\PFN_DrvTransparentBlt.ahk" {PFN_DrvTransparentBlt}
#Import export ".\PFN_DrvUnloadFontFile.ahk" {PFN_DrvUnloadFontFile}
#Import export ".\PFN_DrvUnlockDisplayArea.ahk" {PFN_DrvUnlockDisplayArea}
#Import export ".\PHYSICAL_MONITOR.ahk" {PHYSICAL_MONITOR}
#Import export ".\POINTE.ahk" {POINTE}
#Import export ".\POINTFIX.ahk" {POINTFIX}
#Import export ".\POINTQF.ahk" {POINTQF}
#Import export ".\PVIDEO_WIN32K_CALLOUT.ahk" {PVIDEO_WIN32K_CALLOUT}
#Import export ".\QUERY_DISPLAY_CONFIG_FLAGS.ahk" {QUERY_DISPLAY_CONFIG_FLAGS}
#Import export ".\RECTFX.ahk" {RECTFX}
#Import export ".\RUN.ahk" {RUN}
#Import export ".\SET_ACTIVE_COLOR_PROFILE_NAME.ahk" {SET_ACTIVE_COLOR_PROFILE_NAME}
#Import export ".\SET_DISPLAY_CONFIG_FLAGS.ahk" {SET_DISPLAY_CONFIG_FLAGS}
#Import export ".\SORTCOMP.ahk" {SORTCOMP}
#Import export ".\STROBJ.ahk" {STROBJ}
#Import export ".\SURFOBJ.ahk" {SURFOBJ}
#Import export ".\Sources.ahk" {Sources}
#Import export ".\TYPE1_FONT.ahk" {TYPE1_FONT}
#Import export ".\VGA_CHAR.ahk" {VGA_CHAR}
#Import export ".\VIDEOPARAMETERS.ahk" {VIDEOPARAMETERS}
#Import export ".\VIDEO_BANK_SELECT.ahk" {VIDEO_BANK_SELECT}
#Import export ".\VIDEO_BANK_TYPE.ahk" {VIDEO_BANK_TYPE}
#Import export ".\VIDEO_BRIGHTNESS_POLICY.ahk" {VIDEO_BRIGHTNESS_POLICY}
#Import export ".\VIDEO_CLUT.ahk" {VIDEO_CLUT}
#Import export ".\VIDEO_CLUTDATA.ahk" {VIDEO_CLUTDATA}
#Import export ".\VIDEO_COLOR_CAPABILITIES.ahk" {VIDEO_COLOR_CAPABILITIES}
#Import export ".\VIDEO_COLOR_LUT_DATA.ahk" {VIDEO_COLOR_LUT_DATA}
#Import export ".\VIDEO_CURSOR_ATTRIBUTES.ahk" {VIDEO_CURSOR_ATTRIBUTES}
#Import export ".\VIDEO_CURSOR_POSITION.ahk" {VIDEO_CURSOR_POSITION}
#Import export ".\VIDEO_DEVICE_SESSION_STATUS.ahk" {VIDEO_DEVICE_SESSION_STATUS}
#Import export ".\VIDEO_HARDWARE_STATE.ahk" {VIDEO_HARDWARE_STATE}
#Import export ".\VIDEO_HARDWARE_STATE_HEADER.ahk" {VIDEO_HARDWARE_STATE_HEADER}
#Import export ".\VIDEO_LOAD_FONT_INFORMATION.ahk" {VIDEO_LOAD_FONT_INFORMATION}
#Import export ".\VIDEO_LUT_RGB256WORDS.ahk" {VIDEO_LUT_RGB256WORDS}
#Import export ".\VIDEO_MEMORY.ahk" {VIDEO_MEMORY}
#Import export ".\VIDEO_MEMORY_INFORMATION.ahk" {VIDEO_MEMORY_INFORMATION}
#Import export ".\VIDEO_MODE.ahk" {VIDEO_MODE}
#Import export ".\VIDEO_MODE_INFORMATION.ahk" {VIDEO_MODE_INFORMATION}
#Import export ".\VIDEO_MONITOR_DESCRIPTOR.ahk" {VIDEO_MONITOR_DESCRIPTOR}
#Import export ".\VIDEO_NUM_MODES.ahk" {VIDEO_NUM_MODES}
#Import export ".\VIDEO_PALETTE_DATA.ahk" {VIDEO_PALETTE_DATA}
#Import export ".\VIDEO_PERFORMANCE_COUNTER.ahk" {VIDEO_PERFORMANCE_COUNTER}
#Import export ".\VIDEO_POINTER_ATTRIBUTES.ahk" {VIDEO_POINTER_ATTRIBUTES}
#Import export ".\VIDEO_POINTER_CAPABILITIES.ahk" {VIDEO_POINTER_CAPABILITIES}
#Import export ".\VIDEO_POINTER_POSITION.ahk" {VIDEO_POINTER_POSITION}
#Import export ".\VIDEO_POWER_MANAGEMENT.ahk" {VIDEO_POWER_MANAGEMENT}
#Import export ".\VIDEO_POWER_STATE.ahk" {VIDEO_POWER_STATE}
#Import export ".\VIDEO_PUBLIC_ACCESS_RANGES.ahk" {VIDEO_PUBLIC_ACCESS_RANGES}
#Import export ".\VIDEO_QUERY_PERFORMANCE_COUNTER.ahk" {VIDEO_QUERY_PERFORMANCE_COUNTER}
#Import export ".\VIDEO_REGISTER_VDM.ahk" {VIDEO_REGISTER_VDM}
#Import export ".\VIDEO_SHARE_MEMORY.ahk" {VIDEO_SHARE_MEMORY}
#Import export ".\VIDEO_SHARE_MEMORY_INFORMATION.ahk" {VIDEO_SHARE_MEMORY_INFORMATION}
#Import export ".\VIDEO_VDM.ahk" {VIDEO_VDM}
#Import export ".\VIDEO_WIN32K_CALLBACKS.ahk" {VIDEO_WIN32K_CALLBACKS}
#Import export ".\VIDEO_WIN32K_CALLBACKS_PARAMS.ahk" {VIDEO_WIN32K_CALLBACKS_PARAMS}
#Import export ".\VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE.ahk" {VIDEO_WIN32K_CALLBACKS_PARAMS_TYPE}
#Import export ".\WCRUN.ahk" {WCRUN}
#Import export ".\WNDOBJ.ahk" {WNDOBJ}
#Import export ".\WNDOBJCHANGEPROC.ahk" {WNDOBJCHANGEPROC}
#Import export ".\XFORML.ahk" {XFORML}
#Import export ".\XFORMOBJ.ahk" {XFORMOBJ}
#Import export ".\XLATEOBJ.ahk" {XLATEOBJ}
