#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\GAMMA_RAMP_RGB.ahk" { GAMMA_RAMP_RGB }
#Import ".\COLORSPACE_TRANSFORM_STAGE_CONTROL.ahk" { COLORSPACE_TRANSFORM_STAGE_CONTROL }
#Import ".\COLORSPACE_TRANSFORM.ahk" { COLORSPACE_TRANSFORM }
#Import ".\COLORSPACE_TRANSFORM_MATRIX_V2.ahk" { COLORSPACE_TRANSFORM_MATRIX_V2 }
#Import ".\GAMMA_RAMP_RGB256x3x16.ahk" { GAMMA_RAMP_RGB256x3x16 }
#Import ".\OUTPUT_WIRE_FORMAT.ahk" { OUTPUT_WIRE_FORMAT }
#Import ".\OUTPUT_COLOR_ENCODING.ahk" { OUTPUT_COLOR_ENCODING }
#Import ".\GAMMA_RAMP_DXGI_1.ahk" { GAMMA_RAMP_DXGI_1 }
#Import ".\COLORSPACE_TRANSFORM_TYPE.ahk" { COLORSPACE_TRANSFORM_TYPE }
#Import ".\COLORSPACE_TRANSFORM_3x4.ahk" { COLORSPACE_TRANSFORM_3x4 }
#Import ".\OUTPUT_WIRE_COLOR_SPACE_TYPE.ahk" { OUTPUT_WIRE_COLOR_SPACE_TYPE }

/**
 * @namespace Windows.Win32.Devices.Display
 */
export default struct COLORSPACE_TRANSFORM_SET_INPUT {
    #StructPack 4

    OutputWireColorSpaceExpected : OUTPUT_WIRE_COLOR_SPACE_TYPE

    OutputWireFormatExpected : OUTPUT_WIRE_FORMAT

    ColorSpaceTransform : COLORSPACE_TRANSFORM

}
