#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\COLORSPACE_TRANSFORM_1DLUT_CAP.ahk" { COLORSPACE_TRANSFORM_1DLUT_CAP }
#Import ".\COLORSPACE_TRANSFORM_MATRIX_CAP.ahk" { COLORSPACE_TRANSFORM_MATRIX_CAP }
#Import ".\COLORSPACE_TRANSFORM_DATA_TYPE.ahk" { COLORSPACE_TRANSFORM_DATA_TYPE }
#Import ".\COLORSPACE_TRANSFORM_TARGET_CAPS_VERSION.ahk" { COLORSPACE_TRANSFORM_TARGET_CAPS_VERSION }
#Import ".\COLORSPACE_TRANSFORM_DATA_CAP.ahk" { COLORSPACE_TRANSFORM_DATA_CAP }

/**
 * @namespace Windows.Win32.Devices.Display
 */
export default struct COLORSPACE_TRANSFORM_TARGET_CAPS {
    #StructPack 4

    Version : COLORSPACE_TRANSFORM_TARGET_CAPS_VERSION

    LookupTable1DDegammaCap : COLORSPACE_TRANSFORM_1DLUT_CAP

    ColorMatrix3x3Cap : COLORSPACE_TRANSFORM_MATRIX_CAP

    LookupTable1DRegammaCap : COLORSPACE_TRANSFORM_1DLUT_CAP

}
