#Requires AutoHotkey v2.0 64-bit

#Include ..\..\Win32\System\WinRT\Apis.ahk
#Include ..\..\Win32\System\WinRT\HSTRING.ahk
#Include .\AttachableInputObject.ahk
#Include .\ISystemButtonEventController.ahk
#Include .\ISystemButtonEventControllerStatics.ahk
#Include ..\..\Foundation\TypedEventHandler.ahk
#Include .\SystemButtonEventController.ahk
#Include .\SystemFunctionButtonEventArgs.ahk
#Include .\SystemFunctionLockChangedEventArgs.ahk
#Include .\SystemFunctionLockIndicatorChangedEventArgs.ahk
#Include ..\..\..\Guid.ahk
#Include ..\..\..\WinRTEventHandler.ahk

/**
 * Enables the ability to handle events generated by hardware system buttons (such as the Function buttons).
 * @remarks
 * This API is intended for use by Accessibility tools as a low level hook for intercepting events from hardware system buttons.
 * 
 * [SystemButtonEventController](systembuttoneventcontroller.md) event registration applies system wide and is first-come, first-served. If an application or service sets a SystemButtonEventController event Handled property to true, applications or services that registered after that app or service for the same event notification will not receive the notification.
 * @see https://learn.microsoft.com/uwp/api/windows.ui.input.systembuttoneventcontroller
 * @namespace Windows.UI.Input
 * @version WindowsRuntime 1.4
 */
class SystemButtonEventController extends AttachableInputObject {
;@region Static Properties
    /**
     * The default interface of is Windows Runtime class. At the ABI level, the class is really
     * just a pointer to this interface
     * @type {Class}
     */
    static WinRTDefaultInterface => ISystemButtonEventController

    /**
     * The IID of this class's default interface. This allows it to be cast using IUnknown::As like any
     * Windows Runtime interface
     * @type {Guid}
     */
    static IID => ISystemButtonEventController.IID

;@endregion Static Properties

;@region Static Methods
    /**
     * Creates a [SystemButtonEventController](systembuttoneventcontroller.md) object on the specified dispatcher queue.
     * 
     * All events are fired on the queue thread.
     * @remarks
     * This API is intended for use by Accessibility tools as a low level hook for intercepting events from hardware system buttons.
     * 
     * [SystemButtonEventController](systembuttoneventcontroller.md) event registration applies system wide and is first-come, first-served. If an application or service sets a SystemButtonEventController event Handled property to true, applications or services that registered after that app or service for the same event notification will not receive the notification.
     * @param {DispatcherQueue} queue The [DispatcherQueue](../windows.system/dispatcherqueue.md) for managing prioritized tasks that execute in a serial fashion on a thread.
     * @returns {SystemButtonEventController} 
     * @see https://learn.microsoft.com/uwp/api/windows.ui.input.systembuttoneventcontroller.createfordispatcherqueue
     */
    static CreateForDispatcherQueue(queue) {
        if (!SystemButtonEventController.HasProp("__ISystemButtonEventControllerStatics")) {
            activatableClassId := HSTRING.Create("Windows.UI.Input.SystemButtonEventController")
            factoryPtr := WinRT.RoGetActivationFactory(activatableClassId, ISystemButtonEventControllerStatics.IID)
            SystemButtonEventController.__ISystemButtonEventControllerStatics := ISystemButtonEventControllerStatics(factoryPtr)
        }

        return SystemButtonEventController.__ISystemButtonEventControllerStatics.CreateForDispatcherQueue(queue)
    }

;@endregion Static Methods

;@region Instance Methods
    __New(ptr) {
        super.__New(ptr)
    }

    __Delete() {
        if(this.HasProp("__OnSystemFunctionButtonPressedToken")) {
            this.remove_SystemFunctionButtonPressed(this.__OnSystemFunctionButtonPressedToken)
            this.__OnSystemFunctionButtonPressed.iface.Dispose()
        }

        if(this.HasProp("__OnSystemFunctionButtonReleasedToken")) {
            this.remove_SystemFunctionButtonReleased(this.__OnSystemFunctionButtonReleasedToken)
            this.__OnSystemFunctionButtonReleased.iface.Dispose()
        }

        if(this.HasProp("__OnSystemFunctionLockChangedToken")) {
            this.remove_SystemFunctionLockChanged(this.__OnSystemFunctionLockChangedToken)
            this.__OnSystemFunctionLockChanged.iface.Dispose()
        }

        if(this.HasProp("__OnSystemFunctionLockIndicatorChangedToken")) {
            this.remove_SystemFunctionLockIndicatorChanged(this.__OnSystemFunctionLockIndicatorChangedToken)
            this.__OnSystemFunctionLockIndicatorChanged.iface.Dispose()
        }

        super.__Delete()
    }

    /**
     * 
     * @param {TypedEventHandler<SystemButtonEventController, SystemFunctionButtonEventArgs>} handler 
     * @returns {EventRegistrationToken} 
     */
    add_SystemFunctionButtonPressed(handler) {
        if (!this.HasProp("__ISystemButtonEventController")) {
            if ((queryResult := this.QueryInterface(ISystemButtonEventController.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__ISystemButtonEventController := ISystemButtonEventController(outPtr)
        }

        return this.__ISystemButtonEventController.add_SystemFunctionButtonPressed(handler)
    }

    /**
     * 
     * @param {EventRegistrationToken} token 
     * @returns {HRESULT} 
     */
    remove_SystemFunctionButtonPressed(token) {
        if (!this.HasProp("__ISystemButtonEventController")) {
            if ((queryResult := this.QueryInterface(ISystemButtonEventController.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__ISystemButtonEventController := ISystemButtonEventController(outPtr)
        }

        return this.__ISystemButtonEventController.remove_SystemFunctionButtonPressed(token)
    }

    /**
     * 
     * @param {TypedEventHandler<SystemButtonEventController, SystemFunctionButtonEventArgs>} handler 
     * @returns {EventRegistrationToken} 
     */
    add_SystemFunctionButtonReleased(handler) {
        if (!this.HasProp("__ISystemButtonEventController")) {
            if ((queryResult := this.QueryInterface(ISystemButtonEventController.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__ISystemButtonEventController := ISystemButtonEventController(outPtr)
        }

        return this.__ISystemButtonEventController.add_SystemFunctionButtonReleased(handler)
    }

    /**
     * 
     * @param {EventRegistrationToken} token 
     * @returns {HRESULT} 
     */
    remove_SystemFunctionButtonReleased(token) {
        if (!this.HasProp("__ISystemButtonEventController")) {
            if ((queryResult := this.QueryInterface(ISystemButtonEventController.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__ISystemButtonEventController := ISystemButtonEventController(outPtr)
        }

        return this.__ISystemButtonEventController.remove_SystemFunctionButtonReleased(token)
    }

    /**
     * 
     * @param {TypedEventHandler<SystemButtonEventController, SystemFunctionLockChangedEventArgs>} handler 
     * @returns {EventRegistrationToken} 
     */
    add_SystemFunctionLockChanged(handler) {
        if (!this.HasProp("__ISystemButtonEventController")) {
            if ((queryResult := this.QueryInterface(ISystemButtonEventController.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__ISystemButtonEventController := ISystemButtonEventController(outPtr)
        }

        return this.__ISystemButtonEventController.add_SystemFunctionLockChanged(handler)
    }

    /**
     * 
     * @param {EventRegistrationToken} token 
     * @returns {HRESULT} 
     */
    remove_SystemFunctionLockChanged(token) {
        if (!this.HasProp("__ISystemButtonEventController")) {
            if ((queryResult := this.QueryInterface(ISystemButtonEventController.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__ISystemButtonEventController := ISystemButtonEventController(outPtr)
        }

        return this.__ISystemButtonEventController.remove_SystemFunctionLockChanged(token)
    }

    /**
     * 
     * @param {TypedEventHandler<SystemButtonEventController, SystemFunctionLockIndicatorChangedEventArgs>} handler 
     * @returns {EventRegistrationToken} 
     */
    add_SystemFunctionLockIndicatorChanged(handler) {
        if (!this.HasProp("__ISystemButtonEventController")) {
            if ((queryResult := this.QueryInterface(ISystemButtonEventController.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__ISystemButtonEventController := ISystemButtonEventController(outPtr)
        }

        return this.__ISystemButtonEventController.add_SystemFunctionLockIndicatorChanged(handler)
    }

    /**
     * 
     * @param {EventRegistrationToken} token 
     * @returns {HRESULT} 
     */
    remove_SystemFunctionLockIndicatorChanged(token) {
        if (!this.HasProp("__ISystemButtonEventController")) {
            if ((queryResult := this.QueryInterface(ISystemButtonEventController.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__ISystemButtonEventController := ISystemButtonEventController(outPtr)
        }

        return this.__ISystemButtonEventController.remove_SystemFunctionLockIndicatorChanged(token)
    }

;@endregion Instance Methods
}
