#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ALLOC_CONSOLE_MODE.ahk" {ALLOC_CONSOLE_MODE}
#Import export ".\ALLOC_CONSOLE_OPTIONS.ahk" {ALLOC_CONSOLE_OPTIONS}
#Import export ".\ALLOC_CONSOLE_RESULT.ahk" {ALLOC_CONSOLE_RESULT}
#Import export ".\APPKEY.ahk" {APPKEY}
#Import export ".\Apis.ahk" {*}
#Import export ".\CHAR_INFO.ahk" {CHAR_INFO}
#Import export ".\CONSOLECONTROL.ahk" {CONSOLECONTROL}
#Import export ".\CONSOLEENDTASK.ahk" {CONSOLEENDTASK}
#Import export ".\CONSOLESETFOREGROUND.ahk" {CONSOLESETFOREGROUND}
#Import export ".\CONSOLEWINDOWOWNER.ahk" {CONSOLEWINDOWOWNER}
#Import export ".\CONSOLE_CARET_INFO.ahk" {CONSOLE_CARET_INFO}
#Import export ".\CONSOLE_CHARACTER_ATTRIBUTES.ahk" {CONSOLE_CHARACTER_ATTRIBUTES}
#Import export ".\CONSOLE_CURSOR_INFO.ahk" {CONSOLE_CURSOR_INFO}
#Import export ".\CONSOLE_FONT_INFO.ahk" {CONSOLE_FONT_INFO}
#Import export ".\CONSOLE_FONT_INFOEX.ahk" {CONSOLE_FONT_INFOEX}
#Import export ".\CONSOLE_GRAPHICS_BUFFER_INFO.ahk" {CONSOLE_GRAPHICS_BUFFER_INFO}
#Import export ".\CONSOLE_HISTORY_INFO.ahk" {CONSOLE_HISTORY_INFO}
#Import export ".\CONSOLE_MODE.ahk" {CONSOLE_MODE}
#Import export ".\CONSOLE_PROCESS_INFO.ahk" {CONSOLE_PROCESS_INFO}
#Import export ".\CONSOLE_READCONSOLE_CONTROL.ahk" {CONSOLE_READCONSOLE_CONTROL}
#Import export ".\CONSOLE_SCREEN_BUFFER_INFO.ahk" {CONSOLE_SCREEN_BUFFER_INFO}
#Import export ".\CONSOLE_SCREEN_BUFFER_INFOEX.ahk" {CONSOLE_SCREEN_BUFFER_INFOEX}
#Import export ".\CONSOLE_SELECTION_INFO.ahk" {CONSOLE_SELECTION_INFO}
#Import export ".\COORD.ahk" {COORD}
#Import export ".\Constants.ahk" {*}
#Import export ".\ExtKeyDef.ahk" {ExtKeyDef}
#Import export ".\ExtKeyDefBuf.ahk" {ExtKeyDefBuf}
#Import export ".\ExtKeySubst.ahk" {ExtKeySubst}
#Import export ".\FOCUS_EVENT_RECORD.ahk" {FOCUS_EVENT_RECORD}
#Import export ".\HPCON.ahk" {HPCON}
#Import export ".\INPUT_RECORD.ahk" {INPUT_RECORD}
#Import export ".\KEY_EVENT_RECORD.ahk" {KEY_EVENT_RECORD}
#Import export ".\MENU_EVENT_RECORD.ahk" {MENU_EVENT_RECORD}
#Import export ".\MOUSE_EVENT_RECORD.ahk" {MOUSE_EVENT_RECORD}
#Import export ".\PHANDLER_ROUTINE.ahk" {PHANDLER_ROUTINE}
#Import export ".\SMALL_RECT.ahk" {SMALL_RECT}
#Import export ".\STD_HANDLE.ahk" {STD_HANDLE}
#Import export ".\WINDOW_BUFFER_SIZE_RECORD.ahk" {WINDOW_BUFFER_SIZE_RECORD}
