#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import "..\..\Foundation\CHAR.ahk" { CHAR }
#Import "..\..\Foundation\BOOL.ahk" { BOOL }

/**
 * Describes a keyboard input event in a console INPUT\_RECORD structure.
 * @remarks
 * Enhanced keys for the IBM® 101- and 102-key keyboards are the INS, DEL, HOME, END, PAGE UP, PAGE DOWN, and direction keys in the clusters to the left of the keypad; and the divide (/) and ENTER keys in the keypad.
 * 
 * Keyboard input events are generated when any key, including control keys, is pressed or released. However, the ALT key when pressed and released without combining with another character, has special meaning to the system and is not passed through to the application. Also, the CTRL+C key combination is not passed through if the input handle is in processed mode (**ENABLE\_PROCESSED\_INPUT**).
 * @see https://learn.microsoft.com/windows/console/key-event-record-str
 * @namespace Windows.Win32.System.Console
 */
export default struct KEY_EVENT_RECORD {
    #StructPack 4


    struct _uChar {
        UnicodeChar : Int8

        static __New() {
            DefineProp(this.Prototype, 'AsciiChar', { type: CHAR, offset: 0 })
            this.DeleteProp("__New")
        }
    }

    /**
     * If the key is pressed, this member is **TRUE**. Otherwise, this member is **FALSE** (the key is released).
     */
    bKeyDown : BOOL

    /**
     * The repeat count, which indicates that a key is being held down. For example, when a key is held down, you might get five events with this member equal to 1, one event with this member equal to 5, or multiple events with this member greater than or equal to 1.
     */
    wRepeatCount : UInt16

    /**
     * A [virtual-key code](/windows/win32/inputdev/virtual-key-codes) that identifies the given key in a device-independent manner.
     */
    wVirtualKeyCode : UInt16

    /**
     * The virtual scan code of the given key that represents the device-dependent value generated by the keyboard hardware.
     */
    wVirtualScanCode : UInt16

    /**
     * A union of the following members.
     */
    uChar : KEY_EVENT_RECORD._uChar

    /**
     * The state of the control keys. This member can be one or more of the following values.
     * 
     * | Value | Meaning |
     * |-|-|
     * | **CAPSLOCK_ON** 0x0080 | The CAPS LOCK light is on. |
     * | **ENHANCED_KEY** 0x0100 | The key is enhanced. See [remarks](key-event-record-str.md#remarks). |
     * | **LEFT_ALT_PRESSED** 0x0002 | The left ALT key is pressed. |
     * | **LEFT_CTRL_PRESSED** 0x0008 | The left CTRL key is pressed. |
     * | **NUMLOCK_ON** 0x0020 | The NUM LOCK light is on. |
     * | **RIGHT_ALT_PRESSED** 0x0001 | The right ALT key is pressed. |
     * | **RIGHT_CTRL_PRESSED** 0x0004 | The right CTRL key is pressed. |
     * | **SCROLLLOCK_ON** 0x0040 | The SCROLL LOCK light is on. |
     * | **SHIFT_PRESSED** 0x0010 | The SHIFT key is pressed. |
     */
    dwControlKeyState : UInt32

}
