#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\FW_DYNAMIC_KEYWORD_ADDRESS0.ahk" {FW_DYNAMIC_KEYWORD_ADDRESS0}
#Import export ".\FW_DYNAMIC_KEYWORD_ADDRESS_DATA0.ahk" {FW_DYNAMIC_KEYWORD_ADDRESS_DATA0}
#Import export ".\FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS.ahk" {FW_DYNAMIC_KEYWORD_ADDRESS_ENUM_FLAGS}
#Import export ".\FW_DYNAMIC_KEYWORD_ADDRESS_FLAGS.ahk" {FW_DYNAMIC_KEYWORD_ADDRESS_FLAGS}
#Import export ".\FW_DYNAMIC_KEYWORD_ORIGIN_TYPE.ahk" {FW_DYNAMIC_KEYWORD_ORIGIN_TYPE}
#Import export ".\ICS_TARGETTYPE.ahk" {ICS_TARGETTYPE}
#Import export ".\IDynamicPortMapping.ahk" {IDynamicPortMapping}
#Import export ".\IDynamicPortMappingCollection.ahk" {IDynamicPortMappingCollection}
#Import export ".\IEnumNetConnection.ahk" {IEnumNetConnection}
#Import export ".\IEnumNetSharingEveryConnection.ahk" {IEnumNetSharingEveryConnection}
#Import export ".\IEnumNetSharingPortMapping.ahk" {IEnumNetSharingPortMapping}
#Import export ".\IEnumNetSharingPrivateConnection.ahk" {IEnumNetSharingPrivateConnection}
#Import export ".\IEnumNetSharingPublicConnection.ahk" {IEnumNetSharingPublicConnection}
#Import export ".\INATEventManager.ahk" {INATEventManager}
#Import export ".\INATExternalIPAddressCallback.ahk" {INATExternalIPAddressCallback}
#Import export ".\INATNumberOfEntriesCallback.ahk" {INATNumberOfEntriesCallback}
#Import export ".\INET_FIREWALL_AC_BINARIES.ahk" {INET_FIREWALL_AC_BINARIES}
#Import export ".\INET_FIREWALL_AC_CAPABILITIES.ahk" {INET_FIREWALL_AC_CAPABILITIES}
#Import export ".\INET_FIREWALL_AC_CHANGE.ahk" {INET_FIREWALL_AC_CHANGE}
#Import export ".\INET_FIREWALL_AC_CHANGE_TYPE.ahk" {INET_FIREWALL_AC_CHANGE_TYPE}
#Import export ".\INET_FIREWALL_AC_CREATION_TYPE.ahk" {INET_FIREWALL_AC_CREATION_TYPE}
#Import export ".\INET_FIREWALL_APP_CONTAINER.ahk" {INET_FIREWALL_APP_CONTAINER}
#Import export ".\INetConnection.ahk" {INetConnection}
#Import export ".\INetConnectionConnectUi.ahk" {INetConnectionConnectUi}
#Import export ".\INetConnectionManager.ahk" {INetConnectionManager}
#Import export ".\INetConnectionProps.ahk" {INetConnectionProps}
#Import export ".\INetFwAuthorizedApplication.ahk" {INetFwAuthorizedApplication}
#Import export ".\INetFwAuthorizedApplications.ahk" {INetFwAuthorizedApplications}
#Import export ".\INetFwIcmpSettings.ahk" {INetFwIcmpSettings}
#Import export ".\INetFwMgr.ahk" {INetFwMgr}
#Import export ".\INetFwOpenPort.ahk" {INetFwOpenPort}
#Import export ".\INetFwOpenPorts.ahk" {INetFwOpenPorts}
#Import export ".\INetFwPolicy.ahk" {INetFwPolicy}
#Import export ".\INetFwPolicy2.ahk" {INetFwPolicy2}
#Import export ".\INetFwProduct.ahk" {INetFwProduct}
#Import export ".\INetFwProducts.ahk" {INetFwProducts}
#Import export ".\INetFwProfile.ahk" {INetFwProfile}
#Import export ".\INetFwRemoteAdminSettings.ahk" {INetFwRemoteAdminSettings}
#Import export ".\INetFwRule.ahk" {INetFwRule}
#Import export ".\INetFwRule2.ahk" {INetFwRule2}
#Import export ".\INetFwRule3.ahk" {INetFwRule3}
#Import export ".\INetFwRules.ahk" {INetFwRules}
#Import export ".\INetFwService.ahk" {INetFwService}
#Import export ".\INetFwServiceRestriction.ahk" {INetFwServiceRestriction}
#Import export ".\INetFwServices.ahk" {INetFwServices}
#Import export ".\INetSharingConfiguration.ahk" {INetSharingConfiguration}
#Import export ".\INetSharingEveryConnectionCollection.ahk" {INetSharingEveryConnectionCollection}
#Import export ".\INetSharingManager.ahk" {INetSharingManager}
#Import export ".\INetSharingPortMapping.ahk" {INetSharingPortMapping}
#Import export ".\INetSharingPortMappingCollection.ahk" {INetSharingPortMappingCollection}
#Import export ".\INetSharingPortMappingProps.ahk" {INetSharingPortMappingProps}
#Import export ".\INetSharingPrivateConnectionCollection.ahk" {INetSharingPrivateConnectionCollection}
#Import export ".\INetSharingPublicConnectionCollection.ahk" {INetSharingPublicConnectionCollection}
#Import export ".\IStaticPortMapping.ahk" {IStaticPortMapping}
#Import export ".\IStaticPortMappingCollection.ahk" {IStaticPortMappingCollection}
#Import export ".\IUPnPNAT.ahk" {IUPnPNAT}
#Import export ".\NETCONMGR_ENUM_FLAGS.ahk" {NETCONMGR_ENUM_FLAGS}
#Import export ".\NETCONUI_CONNECT_FLAGS.ahk" {NETCONUI_CONNECT_FLAGS}
#Import export ".\NETCON_CHARACTERISTIC_FLAGS.ahk" {NETCON_CHARACTERISTIC_FLAGS}
#Import export ".\NETCON_MEDIATYPE.ahk" {NETCON_MEDIATYPE}
#Import export ".\NETCON_PROPERTIES.ahk" {NETCON_PROPERTIES}
#Import export ".\NETCON_STATUS.ahk" {NETCON_STATUS}
#Import export ".\NETCON_TYPE.ahk" {NETCON_TYPE}
#Import export ".\NETISO_ERROR_TYPE.ahk" {NETISO_ERROR_TYPE}
#Import export ".\NETISO_FLAG.ahk" {NETISO_FLAG}
#Import export ".\NET_FW_ACTION.ahk" {NET_FW_ACTION}
#Import export ".\NET_FW_AUTHENTICATE_TYPE.ahk" {NET_FW_AUTHENTICATE_TYPE}
#Import export ".\NET_FW_EDGE_TRAVERSAL_TYPE.ahk" {NET_FW_EDGE_TRAVERSAL_TYPE}
#Import export ".\NET_FW_IP_PROTOCOL.ahk" {NET_FW_IP_PROTOCOL}
#Import export ".\NET_FW_IP_VERSION.ahk" {NET_FW_IP_VERSION}
#Import export ".\NET_FW_MODIFY_STATE.ahk" {NET_FW_MODIFY_STATE}
#Import export ".\NET_FW_POLICY_TYPE.ahk" {NET_FW_POLICY_TYPE}
#Import export ".\NET_FW_PROFILE_TYPE.ahk" {NET_FW_PROFILE_TYPE}
#Import export ".\NET_FW_PROFILE_TYPE2.ahk" {NET_FW_PROFILE_TYPE2}
#Import export ".\NET_FW_RULE_CATEGORY.ahk" {NET_FW_RULE_CATEGORY}
#Import export ".\NET_FW_RULE_DIRECTION.ahk" {NET_FW_RULE_DIRECTION}
#Import export ".\NET_FW_SCOPE.ahk" {NET_FW_SCOPE}
#Import export ".\NET_FW_SERVICE_TYPE.ahk" {NET_FW_SERVICE_TYPE}
#Import export ".\NetFwAuthorizedApplication.ahk" {NetFwAuthorizedApplication}
#Import export ".\NetFwMgr.ahk" {NetFwMgr}
#Import export ".\NetFwOpenPort.ahk" {NetFwOpenPort}
#Import export ".\NetFwPolicy2.ahk" {NetFwPolicy2}
#Import export ".\NetFwProduct.ahk" {NetFwProduct}
#Import export ".\NetFwProducts.ahk" {NetFwProducts}
#Import export ".\NetFwRule.ahk" {NetFwRule}
#Import export ".\NetSharingManager.ahk" {NetSharingManager}
#Import export ".\PAC_CHANGES_CALLBACK_FN.ahk" {PAC_CHANGES_CALLBACK_FN}
#Import export ".\PFN_FWADDDYNAMICKEYWORDADDRESS0.ahk" {PFN_FWADDDYNAMICKEYWORDADDRESS0}
#Import export ".\PFN_FWDELETEDYNAMICKEYWORDADDRESS0.ahk" {PFN_FWDELETEDYNAMICKEYWORDADDRESS0}
#Import export ".\PFN_FWENUMDYNAMICKEYWORDADDRESSBYID0.ahk" {PFN_FWENUMDYNAMICKEYWORDADDRESSBYID0}
#Import export ".\PFN_FWENUMDYNAMICKEYWORDADDRESSESBYTYPE0.ahk" {PFN_FWENUMDYNAMICKEYWORDADDRESSESBYTYPE0}
#Import export ".\PFN_FWFREEDYNAMICKEYWORDADDRESSDATA0.ahk" {PFN_FWFREEDYNAMICKEYWORDADDRESSDATA0}
#Import export ".\PFN_FWUPDATEDYNAMICKEYWORDADDRESS0.ahk" {PFN_FWUPDATEDYNAMICKEYWORDADDRESS0}
#Import export ".\PNETISO_EDP_ID_CALLBACK_FN.ahk" {PNETISO_EDP_ID_CALLBACK_FN}
#Import export ".\SHARINGCONNECTIONTYPE.ahk" {SHARINGCONNECTIONTYPE}
#Import export ".\SHARINGCONNECTION_ENUM_FLAGS.ahk" {SHARINGCONNECTION_ENUM_FLAGS}
#Import export ".\UPnPNAT.ahk" {UPnPNAT}
