#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\HTTP_CERT_CONFIG_ENTRY.ahk" { HTTP_CERT_CONFIG_ENTRY }
#Import ".\HTTP_PERFORMANCE_PARAM.ahk" { HTTP_PERFORMANCE_PARAM }
#Import ".\HTTP2_SETTINGS_LIMITS_PARAM.ahk" { HTTP2_SETTINGS_LIMITS_PARAM }
#Import ".\HTTP_ERROR_HEADERS_PARAM.ahk" { HTTP_ERROR_HEADERS_PARAM }
#Import ".\HTTP_UNKNOWN_HEADER.ahk" { HTTP_UNKNOWN_HEADER }
#Import "..\WinSock\ADDRESS_FAMILY.ahk" { ADDRESS_FAMILY }
#Import ".\HTTP_PERFORMANCE_PARAM_TYPE.ahk" { HTTP_PERFORMANCE_PARAM_TYPE }
#Import ".\HTTP2_WINDOW_SIZE_PARAM.ahk" { HTTP2_WINDOW_SIZE_PARAM }
#Import ".\HTTP_SERVICE_CONFIG_SSL_KEY_EX.ahk" { HTTP_SERVICE_CONFIG_SSL_KEY_EX }
#Import "..\WinSock\SOCKADDR_STORAGE.ahk" { SOCKADDR_STORAGE }
#Import ".\HTTP_CERT_CONFIG_PARAM.ahk" { HTTP_CERT_CONFIG_PARAM }
#Import ".\HTTP_SERVICE_CONFIG_SSL_PARAM_EX.ahk" { HTTP_SERVICE_CONFIG_SSL_PARAM_EX }
#Import ".\HTTP_SSL_SERVICE_CONFIG_EX_PARAM_TYPE.ahk" { HTTP_SSL_SERVICE_CONFIG_EX_PARAM_TYPE }
#Import ".\HTTP_TLS_SESSION_TICKET_KEYS_PARAM.ahk" { HTTP_TLS_SESSION_TICKET_KEYS_PARAM }
#Import ".\HTTP_TLS_RESTRICTIONS_PARAM.ahk" { HTTP_TLS_RESTRICTIONS_PARAM }
#Import "..\..\Foundation\CHAR.ahk" { CHAR }

/**
 * @namespace Windows.Win32.Networking.HttpServer
 */
export default struct HTTP_SERVICE_CONFIG_SSL_SET_EX {
    #StructPack 8

    KeyDesc : HTTP_SERVICE_CONFIG_SSL_KEY_EX

    ParamDesc : HTTP_SERVICE_CONFIG_SSL_PARAM_EX

}
