#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ACTIVITY_STATE.ahk" {ACTIVITY_STATE}
#Import export ".\ACTIVITY_STATE_COUNT.ahk" {ACTIVITY_STATE_COUNT}
#Import export ".\AXIS.ahk" {AXIS}
#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\ELEVATION_CHANGE_MODE.ahk" {ELEVATION_CHANGE_MODE}
#Import export ".\HUMAN_PRESENCE_DETECTION_TYPE.ahk" {HUMAN_PRESENCE_DETECTION_TYPE}
#Import export ".\HUMAN_PRESENCE_DETECTION_TYPE_COUNT.ahk" {HUMAN_PRESENCE_DETECTION_TYPE_COUNT}
#Import export ".\ILocationPermissions.ahk" {ILocationPermissions}
#Import export ".\ISensor.ahk" {ISensor}
#Import export ".\ISensorCollection.ahk" {ISensorCollection}
#Import export ".\ISensorDataReport.ahk" {ISensorDataReport}
#Import export ".\ISensorEvents.ahk" {ISensorEvents}
#Import export ".\ISensorManager.ahk" {ISensorManager}
#Import export ".\ISensorManagerEvents.ahk" {ISensorManagerEvents}
#Import export ".\LOCATION_DESIRED_ACCURACY.ahk" {LOCATION_DESIRED_ACCURACY}
#Import export ".\LOCATION_POSITION_SOURCE.ahk" {LOCATION_POSITION_SOURCE}
#Import export ".\MAGNETOMETER_ACCURACY.ahk" {MAGNETOMETER_ACCURACY}
#Import export ".\MATRIX3X3.ahk" {MATRIX3X3}
#Import export ".\MagnetometerAccuracy.ahk" {MagnetometerAccuracy}
#Import export ".\PEDOMETER_STEP_TYPE.ahk" {PEDOMETER_STEP_TYPE}
#Import export ".\PEDOMETER_STEP_TYPE_COUNT.ahk" {PEDOMETER_STEP_TYPE_COUNT}
#Import export ".\PROXIMITY_SENSOR_CAPABILITIES.ahk" {PROXIMITY_SENSOR_CAPABILITIES}
#Import export ".\PROXIMITY_TYPE.ahk" {PROXIMITY_TYPE}
#Import export ".\QUATERNION.ahk" {QUATERNION}
#Import export ".\SENSOR_COLLECTION_LIST.ahk" {SENSOR_COLLECTION_LIST}
#Import export ".\SENSOR_CONNECTION_TYPES.ahk" {SENSOR_CONNECTION_TYPES}
#Import export ".\SENSOR_PROPERTY_LIST.ahk" {SENSOR_PROPERTY_LIST}
#Import export ".\SENSOR_STATE.ahk" {SENSOR_STATE}
#Import export ".\SENSOR_VALUE_PAIR.ahk" {SENSOR_VALUE_PAIR}
#Import export ".\SIMPLE_DEVICE_ORIENTATION.ahk" {SIMPLE_DEVICE_ORIENTATION}
#Import export ".\Sensor.ahk" {Sensor}
#Import export ".\SensorCollection.ahk" {SensorCollection}
#Import export ".\SensorConnectionType.ahk" {SensorConnectionType}
#Import export ".\SensorDataReport.ahk" {SensorDataReport}
#Import export ".\SensorManager.ahk" {SensorManager}
#Import export ".\SensorState.ahk" {SensorState}
#Import export ".\SimpleDeviceOrientation.ahk" {SimpleDeviceOrientation}
#Import export ".\VEC3D.ahk" {VEC3D}
