#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\Guid.ahk" { Guid }
#Import "..\..\Foundation\BSTR.ahk" { BSTR }
#Import ".\CTRL_LEVEL.ahk" { CTRL_LEVEL }
#Import "..\Com\IDispatch.ahk" { IDispatch }
#Import "..\..\Foundation\HRESULT.ahk" { HRESULT }
#Import ".\IRDPSRAPIVirtualChannelManager.ahk" { IRDPSRAPIVirtualChannelManager }
#Import "..\..\Foundation\VARIANT_BOOL.ahk" { VARIANT_BOOL }
#Import ".\IRDPSRAPIApplicationFilter.ahk" { IRDPSRAPIApplicationFilter }
#Import ".\IRDPSRAPIAttendeeManager.ahk" { IRDPSRAPIAttendeeManager }
#Import ".\IRDPSRAPISessionProperties.ahk" { IRDPSRAPISessionProperties }
#Import ".\IRDPSRAPIInvitationManager.ahk" { IRDPSRAPIInvitationManager }

/**
 * The ActiveX interface that is used on the viewer side.
 * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nn-rdpencomapi-irdpsrapiviewer
 * @namespace Windows.Win32.System.DesktopSharing
 */
export default struct IRDPSRAPIViewer extends IDispatch {
    /**
     * The interface identifier for IRDPSRAPIViewer
     * @type {Guid}
     */
    static IID := Guid("{c6bfcd38-8ce9-404d-8ae8-f31d00c65cb5}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for IRDPSRAPIViewer interfaces
    */
    struct Vtbl extends IDispatch.Vtbl {
        Connect                     : IntPtr
        Disconnect                  : IntPtr
        get_Attendees               : IntPtr
        get_Invitations             : IntPtr
        get_ApplicationFilter       : IntPtr
        get_VirtualChannelManager   : IntPtr
        put_SmartSizing             : IntPtr
        get_SmartSizing             : IntPtr
        RequestControl              : IntPtr
        put_DisconnectedText        : IntPtr
        get_DisconnectedText        : IntPtr
        RequestColorDepthChange     : IntPtr
        get_Properties              : IntPtr
        StartReverseConnectListener : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := IRDPSRAPIViewer.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * @type {IRDPSRAPIAttendeeManager} 
     */
    Attendees {
        get => this.get_Attendees()
    }

    /**
     * @type {IRDPSRAPIInvitationManager} 
     */
    Invitations {
        get => this.get_Invitations()
    }

    /**
     * @type {IRDPSRAPIApplicationFilter} 
     */
    ApplicationFilter {
        get => this.get_ApplicationFilter()
    }

    /**
     * @type {IRDPSRAPIVirtualChannelManager} 
     */
    VirtualChannelManager {
        get => this.get_VirtualChannelManager()
    }

    /**
     * @type {VARIANT_BOOL} 
     */
    SmartSizing {
        get => this.get_SmartSizing()
        set => this.put_SmartSizing(value)
    }

    /**
     * @type {BSTR} 
     */
    DisconnectedText {
        get => this.get_DisconnectedText()
        set => this.put_DisconnectedText(value)
    }

    /**
     * @type {IRDPSRAPISessionProperties} 
     */
    Properties {
        get => this.get_Properties()
    }

    /**
     * Starts the actual connection to the sharer.
     * @remarks
     * The connection string contained in the <i>bstrConnectionString</i> parameter is generated by the sharer and obtained by the viewer by completing the following steps:
     * 
     * <ol>
     * <li>The sharer obtains an instance of the <a href="https://docs.microsoft.com/windows/desktop/api/rdpencomapi/nn-rdpencomapi-irdpsrapiinvitationmanager">IRDPSRAPIInvitationManager</a> interface from the <a href="https://docs.microsoft.com/windows/desktop/api/rdpencomapi/nf-rdpencomapi-irdpsrapisharingsession-get_invitations">IRDPSRAPISharingSession::Invitations</a> property.</li>
     * <li>The sharer obtains an instance of the <a href="https://docs.microsoft.com/windows/desktop/api/rdpencomapi/nn-rdpencomapi-irdpsrapiinvitation">IRDPSRAPIInvitation</a> interface by calling the <a href="https://docs.microsoft.com/windows/desktop/api/rdpencomapi/nf-rdpencomapi-irdpsrapiinvitationmanager-createinvitation">IRDPSRAPIInvitationManager::CreateInvitation</a> method.</li>
     * <li>The sharer obtains the connection string from the <a href="https://docs.microsoft.com/windows/desktop/api/rdpencomapi/nf-rdpencomapi-irdpsrapiinvitation-get_connectionstring">IRDPSRAPIInvitation::ConnectionString</a> property.</li>
     * <li>The sharer sends the connection string to the viewer in an application-defined method, such as storing the connection string in a file and sharing the file with the viewer.</li>
     * </ol>
     * For increased security, applications can associate passwords with an invitation on the sharer side. Such passwords are usually distributed to viewers through some mechanism other than the one that is used to send the connection string. This is to prevent network "sniffing" types of attacks. If an invitation has a password associated with it, the password must be passed in through this API. Otherwise, the attendee will be disconnected.
     * 
     * The <i>bstrName</i> string that is set in this property is sent to the sharer after the connection is started. The property is a friendly name that the sharer application can choose to display. The property is useful when an invitation is used to authenticate multiple attendees because it allows the sharer and the other viewers to identify who is participating in a Windows Desktop Sharing session.
     * @param {BSTR} bstrConnectionString Type: <b>BSTR</b>
     * 
     * The connection string used to connect to the sharer and authenticate the viewer.
     * @param {BSTR} bstrName Type: <b>BSTR</b>
     * 
     * Name for the viewer. The name is sent to the sharer and other viewers. The string is limited to 255 characters.
     * @param {BSTR} bstrPassword Type: <b>BSTR</b>
     * 
     * Password used for authentication. The password is sent out-of-band from the sharer.
     * @returns {HRESULT} Type: <b>HRESULT</b>
     * 
     * If the method succeeds, the return value is <b>S_OK</b>. Otherwise, the return value is an error code.
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-connect
     */
    Connect(bstrConnectionString, bstrName, bstrPassword) {
        bstrConnectionString := bstrConnectionString is String ? BSTR.Alloc(bstrConnectionString).Value : bstrConnectionString
        bstrName := bstrName is String ? BSTR.Alloc(bstrName).Value : bstrName
        bstrPassword := bstrPassword is String ? BSTR.Alloc(bstrPassword).Value : bstrPassword

        result := ComCall(7, this, BSTR, bstrConnectionString, BSTR, bstrName, BSTR, bstrPassword, "HRESULT")
        return result
    }

    /**
     * Initiates a disconnect of the viewer from the sharer.
     * @returns {HRESULT} If the method succeeds, the return value is <b>S_OK</b>. Otherwise, the return value is an error code.
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-disconnect
     */
    Disconnect() {
        result := ComCall(8, this, "HRESULT")
        return result
    }

    /**
     * Returns an object implementing the IRDPSRAPIAttendeeManager interface. (IRDPSRAPIViewer.get_Attendees)
     * @returns {IRDPSRAPIAttendeeManager} 
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-get_attendees
     */
    get_Attendees() {
        result := ComCall(9, this, "ptr*", &ppVal := 0, "HRESULT")
        return IRDPSRAPIAttendeeManager(ppVal)
    }

    /**
     * Returns an object implementing the IRDPSRAPIInvitationManager interface. (IRDPSRAPIViewer.get_Invitations)
     * @returns {IRDPSRAPIInvitationManager} 
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-get_invitations
     */
    get_Invitations() {
        result := ComCall(10, this, "ptr*", &ppVal := 0, "HRESULT")
        return IRDPSRAPIInvitationManager(ppVal)
    }

    /**
     * Returns an object implementing the IRDPSRAPIApplicationFilter interface. (IRDPSRAPIViewer.get_ApplicationFilter)
     * @returns {IRDPSRAPIApplicationFilter} 
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-get_applicationfilter
     */
    get_ApplicationFilter() {
        result := ComCall(11, this, "ptr*", &ppVal := 0, "HRESULT")
        return IRDPSRAPIApplicationFilter(ppVal)
    }

    /**
     * Returns an object implementing the IRDPSRAPIVirtualChannelManager interface.
     * @returns {IRDPSRAPIVirtualChannelManager} 
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-get_virtualchannelmanager
     */
    get_VirtualChannelManager() {
        result := ComCall(12, this, "ptr*", &ppVal := 0, "HRESULT")
        return IRDPSRAPIVirtualChannelManager(ppVal)
    }

    /**
     * Gets or sets the smart sizing property of the viewer ActiveX control. (Put)
     * @param {VARIANT_BOOL} vbSmartSizing 
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-put_smartsizing
     */
    put_SmartSizing(vbSmartSizing) {
        result := ComCall(13, this, VARIANT_BOOL, vbSmartSizing, "HRESULT")
        return result
    }

    /**
     * Gets or sets the smart sizing property of the viewer ActiveX control. (Get)
     * @returns {VARIANT_BOOL} 
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-get_smartsizing
     */
    get_SmartSizing() {
        result := ComCall(14, this, VARIANT_BOOL.Ptr, &pvbSmartSizing := 0, "HRESULT")
        return pvbSmartSizing
    }

    /**
     * Requests the sharer to change the control level of the viewer.
     * @param {CTRL_LEVEL} CtrlLevel Type: <b>CTRL_LEVEL</b>
     * 
     * One of the values of the <a href="https://docs.microsoft.com/windows/win32/api/rdpencomapi/ne-rdpencomapi-ctrl_level">CTRL_LEVEL</a> enumeration.
     * @returns {HRESULT} Type: <b>HRESULT</b>
     * 
     * If the method succeeds, the return value is <b>S_OK</b>. Otherwise, the return value is an error code.
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-requestcontrol
     */
    RequestControl(CtrlLevel) {
        result := ComCall(15, this, CTRL_LEVEL, CtrlLevel, "HRESULT")
        return result
    }

    /**
     * Retrieves or sets the text that appears centered in the control before a connection is terminated. (Put)
     * @remarks
     * Setting <b>DisconnectedText</b> is optional. If it is not specified, the control appears blank before a connection is established.
     * 
     * The <b>DisconnectedText</b> property can be set only if the control is not in the connected state. The method returns <b>E_FAIL</b> if it is called after the control is connected.
     * @param {BSTR} bstrDisconnectedText 
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-put_disconnectedtext
     */
    put_DisconnectedText(bstrDisconnectedText) {
        bstrDisconnectedText := bstrDisconnectedText is String ? BSTR.Alloc(bstrDisconnectedText).Value : bstrDisconnectedText

        result := ComCall(16, this, BSTR, bstrDisconnectedText, "HRESULT")
        return result
    }

    /**
     * Retrieves or sets the text that appears centered in the control before a connection is terminated. (Get)
     * @remarks
     * Setting <b>DisconnectedText</b> is optional. If it is not specified, the control appears blank before a connection is established.
     * 
     * The <b>DisconnectedText</b> property can be set only if the control is not in the connected state. The method returns <b>E_FAIL</b> if it is called after the control is connected.
     * @returns {BSTR} 
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-get_disconnectedtext
     */
    get_DisconnectedText() {
        pbstrDisconnectedText := BSTR.Owned()
        result := ComCall(17, this, BSTR.Ptr, pbstrDisconnectedText, "HRESULT")
        return pbstrDisconnectedText
    }

    /**
     * Requests a color depth change on the sharer Winlogon user session.
     * @param {Integer} Bpp Type: <b>long</b>
     * 
     * Specifies  the color depth of the session in bits per pixel.  Possible values are 16 and 24. If you specify a value of 8, the color depth is set to 16 bits per pixel.
     * 
     * <b>Windows Server 2008 and Windows Vista:  </b>Possible values are 8, 16, and 24.
     * @returns {HRESULT} Type: <b>HRESULT</b>
     * 
     * If the method succeeds, the return value is <b>S_OK</b>. Otherwise, the return value is an error code.
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-requestcolordepthchange
     */
    RequestColorDepthChange(Bpp) {
        result := ComCall(18, this, "int", Bpp, "HRESULT")
        return result
    }

    /**
     * Returns an object implementing the IRDPSRAPISessionProperties interface.
     * @returns {IRDPSRAPISessionProperties} 
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-get_properties
     */
    get_Properties() {
        result := ComCall(19, this, "ptr*", &ppVal := 0, "HRESULT")
        return IRDPSRAPISessionProperties(ppVal)
    }

    /**
     * Initiates a listener for accepting reverse connections from the sharer to the viewer, or obtains the connection string that the sharer uses to reverse connect to the viewer.
     * @remarks
     * This method is used to perform two separate operations:
     * 
     * <ul>
     * <li>The first is to allow the viewer to obtain the connection string that the sharer uses to reverse connect to the viewer. To do so, the <i>bstrConnectionString</i>, <i>bstrUserName</i>, and <i>bstrPassword</i> parameters must all be <b>NULL</b>. The viewer then sends this connection string to the sharer in an application-defined method, such as storing the connection string in a file and sharing the file with the sharer.</li>
     * <li>The second operation is to initiate a listener that will watch for reverse connect attempts from the sharer. For this operation, the <i>pbstrReverseConnectString</i> parameter must be <b>NULL</b>.</li>
     * </ul>
     * The normal sequence of events for this procedure is as follows:
     * 
     * <ol>
     * <li>The viewer obtains its connection string by calling the <b>StartReverseConnectListener</b> method, passing <b>NULL</b> for the <i>bstrConnectionString</i>, <i>bstrUserName</i>, and <i>bstrPassword</i> parameters.</li>
     * <li>The viewer initiates a reverse connect listener by calling the <b>StartReverseConnectListener</b> method, passing <b>NULL</b> for the <i>pbstrReverseConnectString</i> parameter and valid values for the <i>bstrConnectionString</i>, <i>bstrUserName</i>, and <i>bstrPassword</i> parameters.</li>
     * <li>The viewer sends the connection string obtained in step 1 to the sharer.</li>
     * </ol>
     * @param {BSTR} bstrConnectionString Type: <b>BSTR</b>
     * 
     * The connection string that the sharer will use to start the listener.
     * @param {BSTR} bstrUserName Type: <b>BSTR</b>
     * 
     * The user name to use for authentication.
     * @param {BSTR} bstrPassword Type: <b>BSTR</b>
     * 
     * The password to use for authentication.
     * @returns {BSTR} Type: <b>BSTR*</b>
     * 
     * A pointer to a <b>BSTR</b> that receives the connection string that the sharer can use to reverse connect to the viewer by using the <a href="https://docs.microsoft.com/windows/desktop/api/rdpencomapi/nf-rdpencomapi-irdpsrapisharingsession-connecttoclient">IRDPSRAPISharingSession::ConnectToClient</a> method.
     * @see https://learn.microsoft.com/windows/win32/api/rdpencomapi/nf-rdpencomapi-irdpsrapiviewer-startreverseconnectlistener
     */
    StartReverseConnectListener(bstrConnectionString, bstrUserName, bstrPassword) {
        bstrConnectionString := bstrConnectionString is String ? BSTR.Alloc(bstrConnectionString).Value : bstrConnectionString
        bstrUserName := bstrUserName is String ? BSTR.Alloc(bstrUserName).Value : bstrUserName
        bstrPassword := bstrPassword is String ? BSTR.Alloc(bstrPassword).Value : bstrPassword

        pbstrReverseConnectString := BSTR.Owned()
        result := ComCall(20, this, BSTR, bstrConnectionString, BSTR, bstrUserName, BSTR, bstrPassword, BSTR.Ptr, pbstrReverseConnectString, "HRESULT")
        return pbstrReverseConnectString
    }

    Query(iid) {
        if (IRDPSRAPIViewer.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.Connect := CallbackCreate(GetMethod(implObj, "Connect"), flags, 4)
        this.vtbl.Disconnect := CallbackCreate(GetMethod(implObj, "Disconnect"), flags, 1)
        this.vtbl.get_Attendees := CallbackCreate(GetMethod(implObj, "get_Attendees"), flags, 2)
        this.vtbl.get_Invitations := CallbackCreate(GetMethod(implObj, "get_Invitations"), flags, 2)
        this.vtbl.get_ApplicationFilter := CallbackCreate(GetMethod(implObj, "get_ApplicationFilter"), flags, 2)
        this.vtbl.get_VirtualChannelManager := CallbackCreate(GetMethod(implObj, "get_VirtualChannelManager"), flags, 2)
        this.vtbl.put_SmartSizing := CallbackCreate(GetMethod(implObj, "put_SmartSizing"), flags, 2)
        this.vtbl.get_SmartSizing := CallbackCreate(GetMethod(implObj, "get_SmartSizing"), flags, 2)
        this.vtbl.RequestControl := CallbackCreate(GetMethod(implObj, "RequestControl"), flags, 2)
        this.vtbl.put_DisconnectedText := CallbackCreate(GetMethod(implObj, "put_DisconnectedText"), flags, 2)
        this.vtbl.get_DisconnectedText := CallbackCreate(GetMethod(implObj, "get_DisconnectedText"), flags, 2)
        this.vtbl.RequestColorDepthChange := CallbackCreate(GetMethod(implObj, "RequestColorDepthChange"), flags, 2)
        this.vtbl.get_Properties := CallbackCreate(GetMethod(implObj, "get_Properties"), flags, 2)
        this.vtbl.StartReverseConnectListener := CallbackCreate(GetMethod(implObj, "StartReverseConnectListener"), flags, 5)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.Connect)
        CallbackFree(this.vtbl.Disconnect)
        CallbackFree(this.vtbl.get_Attendees)
        CallbackFree(this.vtbl.get_Invitations)
        CallbackFree(this.vtbl.get_ApplicationFilter)
        CallbackFree(this.vtbl.get_VirtualChannelManager)
        CallbackFree(this.vtbl.put_SmartSizing)
        CallbackFree(this.vtbl.get_SmartSizing)
        CallbackFree(this.vtbl.RequestControl)
        CallbackFree(this.vtbl.put_DisconnectedText)
        CallbackFree(this.vtbl.get_DisconnectedText)
        CallbackFree(this.vtbl.RequestColorDepthChange)
        CallbackFree(this.vtbl.get_Properties)
        CallbackFree(this.vtbl.StartReverseConnectListener)
    }
}
