#Requires AutoHotkey v2.1-alpha.26+ 64-bit

/**
 * Specifies the type of signature permitted when signing a certificate request.
 * @see https://learn.microsoft.com/windows/win32/api/certenroll/ne-certenroll-pkcs10allowedsignaturetypes
 * @namespace Windows.Win32.Security.Cryptography.Certificates
 */
export default struct Pkcs10AllowedSignatureTypes {
    value : Int32

    __value {
        get => this.value
        set => this.value := value
    }

    __New(value := 0) {
        this.value := value
    }

    /**
     * Signatures generated by using <a href="https://docs.microsoft.com/windows/desktop/SecGloss/c-gly">cryptographic keys</a> are allowed.
     * @type {Integer (Int32)}
     */
    static AllowedKeySignature => 1

    /**
     * Null signatures are allowed. A null signature is a SHA-1 <a href="https://docs.microsoft.com/windows/desktop/SecGloss/h-gly">hash</a>.
     * @type {Integer (Int32)}
     */
    static AllowedNullSignature => 2
}
