#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\CompositionFrameDisplayInstance.ahk" {CompositionFrameDisplayInstance}
#Import export ".\CompositionFrameInstanceKind.ahk" {CompositionFrameInstanceKind}
#Import export ".\ICompositionFramePresentStatistics.ahk" {ICompositionFramePresentStatistics}
#Import export ".\IIndependentFlipFramePresentStatistics.ahk" {IIndependentFlipFramePresentStatistics}
#Import export ".\IPresentStatistics.ahk" {IPresentStatistics}
#Import export ".\IPresentStatusPresentStatistics.ahk" {IPresentStatusPresentStatistics}
#Import export ".\IPresentationBuffer.ahk" {IPresentationBuffer}
#Import export ".\IPresentationContent.ahk" {IPresentationContent}
#Import export ".\IPresentationFactory.ahk" {IPresentationFactory}
#Import export ".\IPresentationFactory_SupportHdrAware.ahk" {IPresentationFactory_SupportHdrAware}
#Import export ".\IPresentationManager.ahk" {IPresentationManager}
#Import export ".\IPresentationSurface.ahk" {IPresentationSurface}
#Import export ".\IPresentationSurface2.ahk" {IPresentationSurface2}
#Import export ".\PresentStatisticsKind.ahk" {PresentStatisticsKind}
#Import export ".\PresentStatus.ahk" {PresentStatus}
#Import export ".\PresentationTransform.ahk" {PresentationTransform}
#Import export ".\SystemInterruptTime.ahk" {SystemInterruptTime}
