#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\BMFORMAT.ahk" {BMFORMAT}
#Import export ".\BlackInformation.ahk" {BlackInformation}
#Import export ".\CMYKCOLOR.ahk" {CMYKCOLOR}
#Import export ".\COLOR.ahk" {COLOR}
#Import export ".\COLORDATATYPE.ahk" {COLORDATATYPE}
#Import export ".\COLORMATCHSETUPA.ahk" {COLORMATCHSETUPA}
#Import export ".\COLORMATCHSETUPW.ahk" {COLORMATCHSETUPW}
#Import export ".\COLORPROFILESUBTYPE.ahk" {COLORPROFILESUBTYPE}
#Import export ".\COLORPROFILETYPE.ahk" {COLORPROFILETYPE}
#Import export ".\COLORTYPE.ahk" {COLORTYPE}
#Import export ".\COLOR_MATCH_TO_TARGET_ACTION.ahk" {COLOR_MATCH_TO_TARGET_ACTION}
#Import export ".\Constants.ahk" {*}
#Import export ".\EMRCREATECOLORSPACE.ahk" {EMRCREATECOLORSPACE}
#Import export ".\EMRCREATECOLORSPACEW.ahk" {EMRCREATECOLORSPACEW}
#Import export ".\ENUMTYPEA.ahk" {ENUMTYPEA}
#Import export ".\ENUMTYPEW.ahk" {ENUMTYPEW}
#Import export ".\GENERIC3CHANNEL.ahk" {GENERIC3CHANNEL}
#Import export ".\GRAYCOLOR.ahk" {GRAYCOLOR}
#Import export ".\GamutBoundaryDescription.ahk" {GamutBoundaryDescription}
#Import export ".\GamutShell.ahk" {GamutShell}
#Import export ".\GamutShellTriangle.ahk" {GamutShellTriangle}
#Import export ".\HCOLORSPACE.ahk" {HCOLORSPACE}
#Import export ".\HiFiCOLOR.ahk" {HiFiCOLOR}
#Import export ".\ICMENUMPROCA.ahk" {ICMENUMPROCA}
#Import export ".\ICMENUMPROCW.ahk" {ICMENUMPROCW}
#Import export ".\ICM_COMMAND.ahk" {ICM_COMMAND}
#Import export ".\ICM_MODE.ahk" {ICM_MODE}
#Import export ".\IDeviceModelPlugIn.ahk" {IDeviceModelPlugIn}
#Import export ".\IGamutMapModelPlugIn.ahk" {IGamutMapModelPlugIn}
#Import export ".\JChColorF.ahk" {JChColorF}
#Import export ".\JabColorF.ahk" {JabColorF}
#Import export ".\LCSCSTYPE.ahk" {LCSCSTYPE}
#Import export ".\LOGCOLORSPACEA.ahk" {LOGCOLORSPACEA}
#Import export ".\LOGCOLORSPACEW.ahk" {LOGCOLORSPACEW}
#Import export ".\LPBMCALLBACKFN.ahk" {LPBMCALLBACKFN}
#Import export ".\LabCOLOR.ahk" {LabCOLOR}
#Import export ".\NAMEDCOLOR.ahk" {NAMEDCOLOR}
#Import export ".\NAMED_PROFILE_INFO.ahk" {NAMED_PROFILE_INFO}
#Import export ".\PCMSCALLBACKA.ahk" {PCMSCALLBACKA}
#Import export ".\PCMSCALLBACKW.ahk" {PCMSCALLBACKW}
#Import export ".\PROFILE.ahk" {PROFILE}
#Import export ".\PROFILEHEADER.ahk" {PROFILEHEADER}
#Import export ".\PrimaryJabColors.ahk" {PrimaryJabColors}
#Import export ".\PrimaryXYZColors.ahk" {PrimaryXYZColors}
#Import export ".\RGBCOLOR.ahk" {RGBCOLOR}
#Import export ".\WCS_DEVICE_CAPABILITIES_TYPE.ahk" {WCS_DEVICE_CAPABILITIES_TYPE}
#Import export ".\WCS_DEVICE_MHC2_CAPABILITIES.ahk" {WCS_DEVICE_MHC2_CAPABILITIES}
#Import export ".\WCS_DEVICE_VCGT_CAPABILITIES.ahk" {WCS_DEVICE_VCGT_CAPABILITIES}
#Import export ".\WCS_PROFILE_MANAGEMENT_SCOPE.ahk" {WCS_PROFILE_MANAGEMENT_SCOPE}
#Import export ".\XYZCOLOR.ahk" {XYZCOLOR}
#Import export ".\XYZColorF.ahk" {XYZColorF}
#Import export ".\YxyCOLOR.ahk" {YxyCOLOR}
