#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\HCS_CREATE_OPTIONS.ahk" {HCS_CREATE_OPTIONS}
#Import export ".\HCS_CREATE_OPTIONS_1.ahk" {HCS_CREATE_OPTIONS_1}
#Import export ".\HCS_EVENT.ahk" {HCS_EVENT}
#Import export ".\HCS_EVENT_CALLBACK.ahk" {HCS_EVENT_CALLBACK}
#Import export ".\HCS_EVENT_OPTIONS.ahk" {HCS_EVENT_OPTIONS}
#Import export ".\HCS_EVENT_TYPE.ahk" {HCS_EVENT_TYPE}
#Import export ".\HCS_NOTIFICATIONS.ahk" {HCS_NOTIFICATIONS}
#Import export ".\HCS_NOTIFICATION_CALLBACK.ahk" {HCS_NOTIFICATION_CALLBACK}
#Import export ".\HCS_NOTIFICATION_FLAGS.ahk" {HCS_NOTIFICATION_FLAGS}
#Import export ".\HCS_OPERATION.ahk" {HCS_OPERATION}
#Import export ".\HCS_OPERATION_COMPLETION.ahk" {HCS_OPERATION_COMPLETION}
#Import export ".\HCS_OPERATION_OPTIONS.ahk" {HCS_OPERATION_OPTIONS}
#Import export ".\HCS_OPERATION_TYPE.ahk" {HCS_OPERATION_TYPE}
#Import export ".\HCS_PROCESS.ahk" {HCS_PROCESS}
#Import export ".\HCS_PROCESS_INFORMATION.ahk" {HCS_PROCESS_INFORMATION}
#Import export ".\HCS_RESOURCE_TYPE.ahk" {HCS_RESOURCE_TYPE}
#Import export ".\HCS_SYSTEM.ahk" {HCS_SYSTEM}
