#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_NODE_OVERRIDES_TYPE.ahk" { D3D12_NODE_OVERRIDES_TYPE }
#Import ".\D3D12_THREAD_LAUNCH_OVERRIDES.ahk" { D3D12_THREAD_LAUNCH_OVERRIDES }
#Import "..\..\Foundation\PWSTR.ahk" { PWSTR }
#Import ".\D3D12_COMMON_COMPUTE_NODE_OVERRIDES.ahk" { D3D12_COMMON_COMPUTE_NODE_OVERRIDES }
#Import ".\D3D12_COALESCING_LAUNCH_OVERRIDES.ahk" { D3D12_COALESCING_LAUNCH_OVERRIDES }
#Import ".\D3D12_SHADER_NODE.ahk" { D3D12_SHADER_NODE }
#Import ".\D3D12_BROADCASTING_LAUNCH_OVERRIDES.ahk" { D3D12_BROADCASTING_LAUNCH_OVERRIDES }
#Import ".\D3D12_NODE_TYPE.ahk" { D3D12_NODE_TYPE }

/**
 * @namespace Windows.Win32.Graphics.Direct3D12
 */
export default struct D3D12_NODE {
    #StructPack 8

    NodeType : D3D12_NODE_TYPE

    Shader : D3D12_SHADER_NODE

}
