#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_GPU_VIRTUAL_ADDRESS_RANGE.ahk" { D3D12_GPU_VIRTUAL_ADDRESS_RANGE }
#Import ".\D3D12_PROGRAM_IDENTIFIER.ahk" { D3D12_PROGRAM_IDENTIFIER }
#Import ".\D3D12_SET_WORK_GRAPH_FLAGS.ahk" { D3D12_SET_WORK_GRAPH_FLAGS }
#Import ".\D3D12_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE.ahk" { D3D12_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE }

/**
 * @namespace Windows.Win32.Graphics.Direct3D12
 */
export default struct D3D12_SET_WORK_GRAPH_DESC {
    #StructPack 8

    ProgramIdentifier : D3D12_PROGRAM_IDENTIFIER

    Flags : D3D12_SET_WORK_GRAPH_FLAGS

    BackingMemory : D3D12_GPU_VIRTUAL_ADDRESS_RANGE

    NodeLocalRootArgumentsTable : D3D12_GPU_VIRTUAL_ADDRESS_RANGE_AND_STRIDE

}
