#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_GPU_VIRTUAL_ADDRESS_AND_STRIDE.ahk" { D3D12_GPU_VIRTUAL_ADDRESS_AND_STRIDE }
#Import ".\D3D12_RAYTRACING_OPACITY_MICROMAP_HISTOGRAM_ENTRY.ahk" { D3D12_RAYTRACING_OPACITY_MICROMAP_HISTOGRAM_ENTRY }

/**
 * @namespace Windows.Win32.Graphics.Direct3D12
 */
export default struct D3D12_RAYTRACING_OPACITY_MICROMAP_ARRAY_DESC {
    #StructPack 8

    NumOmmHistogramEntries : UInt32

    pOmmHistogram : D3D12_RAYTRACING_OPACITY_MICROMAP_HISTOGRAM_ENTRY.Ptr

    InputBuffer : Int64

    PerOmmDescs : D3D12_GPU_VIRTUAL_ADDRESS_AND_STRIDE

}
