#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_RAYTRACING_GEOMETRY_OMM_LINKAGE_DESC.ahk" { D3D12_RAYTRACING_GEOMETRY_OMM_LINKAGE_DESC }
#Import ".\D3D12_RAYTRACING_GEOMETRY_TRIANGLES_DESC.ahk" { D3D12_RAYTRACING_GEOMETRY_TRIANGLES_DESC }

/**
 * @namespace Windows.Win32.Graphics.Direct3D12
 */
export default struct D3D12_RAYTRACING_GEOMETRY_OMM_TRIANGLES_DESC {
    #StructPack 8

    pTriangles : D3D12_RAYTRACING_GEOMETRY_TRIANGLES_DESC.Ptr

    pOmmLinkage : D3D12_RAYTRACING_GEOMETRY_OMM_LINKAGE_DESC.Ptr

}
