#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Common\__Init.ahk" {*}
#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\DXGI_ADAPTER_DESC.ahk" {DXGI_ADAPTER_DESC}
#Import export ".\DXGI_ADAPTER_DESC1.ahk" {DXGI_ADAPTER_DESC1}
#Import export ".\DXGI_ADAPTER_DESC2.ahk" {DXGI_ADAPTER_DESC2}
#Import export ".\DXGI_ADAPTER_DESC3.ahk" {DXGI_ADAPTER_DESC3}
#Import export ".\DXGI_ADAPTER_FLAG.ahk" {DXGI_ADAPTER_FLAG}
#Import export ".\DXGI_ADAPTER_FLAG3.ahk" {DXGI_ADAPTER_FLAG3}
#Import export ".\DXGI_COMPUTE_PREEMPTION_GRANULARITY.ahk" {DXGI_COMPUTE_PREEMPTION_GRANULARITY}
#Import export ".\DXGI_CREATE_FACTORY_FLAGS.ahk" {DXGI_CREATE_FACTORY_FLAGS}
#Import export ".\DXGI_DEBUG_RLO_FLAGS.ahk" {DXGI_DEBUG_RLO_FLAGS}
#Import export ".\DXGI_DECODE_SWAP_CHAIN_DESC.ahk" {DXGI_DECODE_SWAP_CHAIN_DESC}
#Import export ".\DXGI_DISPLAY_COLOR_SPACE.ahk" {DXGI_DISPLAY_COLOR_SPACE}
#Import export ".\DXGI_ENUM_MODES.ahk" {DXGI_ENUM_MODES}
#Import export ".\DXGI_FEATURE.ahk" {DXGI_FEATURE}
#Import export ".\DXGI_FRAME_PRESENTATION_MODE.ahk" {DXGI_FRAME_PRESENTATION_MODE}
#Import export ".\DXGI_FRAME_STATISTICS.ahk" {DXGI_FRAME_STATISTICS}
#Import export ".\DXGI_FRAME_STATISTICS_MEDIA.ahk" {DXGI_FRAME_STATISTICS_MEDIA}
#Import export ".\DXGI_GPU_PREFERENCE.ahk" {DXGI_GPU_PREFERENCE}
#Import export ".\DXGI_GRAPHICS_PREEMPTION_GRANULARITY.ahk" {DXGI_GRAPHICS_PREEMPTION_GRANULARITY}
#Import export ".\DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAGS.ahk" {DXGI_HARDWARE_COMPOSITION_SUPPORT_FLAGS}
#Import export ".\DXGI_HDR_METADATA_HDR10.ahk" {DXGI_HDR_METADATA_HDR10}
#Import export ".\DXGI_HDR_METADATA_HDR10PLUS.ahk" {DXGI_HDR_METADATA_HDR10PLUS}
#Import export ".\DXGI_HDR_METADATA_TYPE.ahk" {DXGI_HDR_METADATA_TYPE}
#Import export ".\DXGI_INFO_QUEUE_FILTER.ahk" {DXGI_INFO_QUEUE_FILTER}
#Import export ".\DXGI_INFO_QUEUE_FILTER_DESC.ahk" {DXGI_INFO_QUEUE_FILTER_DESC}
#Import export ".\DXGI_INFO_QUEUE_MESSAGE.ahk" {DXGI_INFO_QUEUE_MESSAGE}
#Import export ".\DXGI_INFO_QUEUE_MESSAGE_CATEGORY.ahk" {DXGI_INFO_QUEUE_MESSAGE_CATEGORY}
#Import export ".\DXGI_INFO_QUEUE_MESSAGE_SEVERITY.ahk" {DXGI_INFO_QUEUE_MESSAGE_SEVERITY}
#Import export ".\DXGI_MAPPED_RECT.ahk" {DXGI_MAPPED_RECT}
#Import export ".\DXGI_MAP_FLAGS.ahk" {DXGI_MAP_FLAGS}
#Import export ".\DXGI_MATRIX_3X2_F.ahk" {DXGI_MATRIX_3X2_F}
#Import export ".\DXGI_MEMORY_SEGMENT_GROUP.ahk" {DXGI_MEMORY_SEGMENT_GROUP}
#Import export ".\DXGI_MODE_DESC1.ahk" {DXGI_MODE_DESC1}
#Import export ".\DXGI_MULTIPLANE_OVERLAY_YCbCr_FLAGS.ahk" {DXGI_MULTIPLANE_OVERLAY_YCbCr_FLAGS}
#Import export ".\DXGI_MWA_FLAGS.ahk" {DXGI_MWA_FLAGS}
#Import export ".\DXGI_Message_Id.ahk" {DXGI_Message_Id}
#Import export ".\DXGI_OFFER_RESOURCE_FLAGS.ahk" {DXGI_OFFER_RESOURCE_FLAGS}
#Import export ".\DXGI_OFFER_RESOURCE_PRIORITY.ahk" {DXGI_OFFER_RESOURCE_PRIORITY}
#Import export ".\DXGI_OUTDUPL_DESC.ahk" {DXGI_OUTDUPL_DESC}
#Import export ".\DXGI_OUTDUPL_FLAG.ahk" {DXGI_OUTDUPL_FLAG}
#Import export ".\DXGI_OUTDUPL_FRAME_INFO.ahk" {DXGI_OUTDUPL_FRAME_INFO}
#Import export ".\DXGI_OUTDUPL_MOVE_RECT.ahk" {DXGI_OUTDUPL_MOVE_RECT}
#Import export ".\DXGI_OUTDUPL_POINTER_POSITION.ahk" {DXGI_OUTDUPL_POINTER_POSITION}
#Import export ".\DXGI_OUTDUPL_POINTER_SHAPE_INFO.ahk" {DXGI_OUTDUPL_POINTER_SHAPE_INFO}
#Import export ".\DXGI_OUTDUPL_POINTER_SHAPE_TYPE.ahk" {DXGI_OUTDUPL_POINTER_SHAPE_TYPE}
#Import export ".\DXGI_OUTPUT_DESC.ahk" {DXGI_OUTPUT_DESC}
#Import export ".\DXGI_OUTPUT_DESC1.ahk" {DXGI_OUTPUT_DESC1}
#Import export ".\DXGI_OVERLAY_COLOR_SPACE_SUPPORT_FLAG.ahk" {DXGI_OVERLAY_COLOR_SPACE_SUPPORT_FLAG}
#Import export ".\DXGI_OVERLAY_SUPPORT_FLAG.ahk" {DXGI_OVERLAY_SUPPORT_FLAG}
#Import export ".\DXGI_PRESENT.ahk" {DXGI_PRESENT}
#Import export ".\DXGI_PRESENT_PARAMETERS.ahk" {DXGI_PRESENT_PARAMETERS}
#Import export ".\DXGI_QUERY_VIDEO_MEMORY_INFO.ahk" {DXGI_QUERY_VIDEO_MEMORY_INFO}
#Import export ".\DXGI_RECLAIM_RESOURCE_RESULTS.ahk" {DXGI_RECLAIM_RESOURCE_RESULTS}
#Import export ".\DXGI_RESIDENCY.ahk" {DXGI_RESIDENCY}
#Import export ".\DXGI_RESOURCE_PRIORITY.ahk" {DXGI_RESOURCE_PRIORITY}
#Import export ".\DXGI_RGBA.ahk" {DXGI_RGBA}
#Import export ".\DXGI_SCALING.ahk" {DXGI_SCALING}
#Import export ".\DXGI_SHARED_RESOURCE.ahk" {DXGI_SHARED_RESOURCE}
#Import export ".\DXGI_SHARED_RESOURCE_RW.ahk" {DXGI_SHARED_RESOURCE_RW}
#Import export ".\DXGI_SURFACE_DESC.ahk" {DXGI_SURFACE_DESC}
#Import export ".\DXGI_SWAP_CHAIN_COLOR_SPACE_SUPPORT_FLAG.ahk" {DXGI_SWAP_CHAIN_COLOR_SPACE_SUPPORT_FLAG}
#Import export ".\DXGI_SWAP_CHAIN_DESC.ahk" {DXGI_SWAP_CHAIN_DESC}
#Import export ".\DXGI_SWAP_CHAIN_DESC1.ahk" {DXGI_SWAP_CHAIN_DESC1}
#Import export ".\DXGI_SWAP_CHAIN_FLAG.ahk" {DXGI_SWAP_CHAIN_FLAG}
#Import export ".\DXGI_SWAP_CHAIN_FULLSCREEN_DESC.ahk" {DXGI_SWAP_CHAIN_FULLSCREEN_DESC}
#Import export ".\DXGI_SWAP_EFFECT.ahk" {DXGI_SWAP_EFFECT}
#Import export ".\DXGI_USAGE.ahk" {DXGI_USAGE}
#Import export ".\IDXGIAdapter.ahk" {IDXGIAdapter}
#Import export ".\IDXGIAdapter1.ahk" {IDXGIAdapter1}
#Import export ".\IDXGIAdapter2.ahk" {IDXGIAdapter2}
#Import export ".\IDXGIAdapter3.ahk" {IDXGIAdapter3}
#Import export ".\IDXGIAdapter4.ahk" {IDXGIAdapter4}
#Import export ".\IDXGIDebug.ahk" {IDXGIDebug}
#Import export ".\IDXGIDebug1.ahk" {IDXGIDebug1}
#Import export ".\IDXGIDecodeSwapChain.ahk" {IDXGIDecodeSwapChain}
#Import export ".\IDXGIDevice.ahk" {IDXGIDevice}
#Import export ".\IDXGIDevice1.ahk" {IDXGIDevice1}
#Import export ".\IDXGIDevice2.ahk" {IDXGIDevice2}
#Import export ".\IDXGIDevice3.ahk" {IDXGIDevice3}
#Import export ".\IDXGIDevice4.ahk" {IDXGIDevice4}
#Import export ".\IDXGIDeviceSubObject.ahk" {IDXGIDeviceSubObject}
#Import export ".\IDXGIDisplayControl.ahk" {IDXGIDisplayControl}
#Import export ".\IDXGIFactory.ahk" {IDXGIFactory}
#Import export ".\IDXGIFactory1.ahk" {IDXGIFactory1}
#Import export ".\IDXGIFactory2.ahk" {IDXGIFactory2}
#Import export ".\IDXGIFactory3.ahk" {IDXGIFactory3}
#Import export ".\IDXGIFactory4.ahk" {IDXGIFactory4}
#Import export ".\IDXGIFactory5.ahk" {IDXGIFactory5}
#Import export ".\IDXGIFactory6.ahk" {IDXGIFactory6}
#Import export ".\IDXGIFactory7.ahk" {IDXGIFactory7}
#Import export ".\IDXGIFactoryMedia.ahk" {IDXGIFactoryMedia}
#Import export ".\IDXGIInfoQueue.ahk" {IDXGIInfoQueue}
#Import export ".\IDXGIKeyedMutex.ahk" {IDXGIKeyedMutex}
#Import export ".\IDXGIObject.ahk" {IDXGIObject}
#Import export ".\IDXGIOutput.ahk" {IDXGIOutput}
#Import export ".\IDXGIOutput1.ahk" {IDXGIOutput1}
#Import export ".\IDXGIOutput2.ahk" {IDXGIOutput2}
#Import export ".\IDXGIOutput3.ahk" {IDXGIOutput3}
#Import export ".\IDXGIOutput4.ahk" {IDXGIOutput4}
#Import export ".\IDXGIOutput5.ahk" {IDXGIOutput5}
#Import export ".\IDXGIOutput6.ahk" {IDXGIOutput6}
#Import export ".\IDXGIOutputDuplication.ahk" {IDXGIOutputDuplication}
#Import export ".\IDXGIResource.ahk" {IDXGIResource}
#Import export ".\IDXGIResource1.ahk" {IDXGIResource1}
#Import export ".\IDXGISurface.ahk" {IDXGISurface}
#Import export ".\IDXGISurface1.ahk" {IDXGISurface1}
#Import export ".\IDXGISurface2.ahk" {IDXGISurface2}
#Import export ".\IDXGISwapChain.ahk" {IDXGISwapChain}
#Import export ".\IDXGISwapChain1.ahk" {IDXGISwapChain1}
#Import export ".\IDXGISwapChain2.ahk" {IDXGISwapChain2}
#Import export ".\IDXGISwapChain3.ahk" {IDXGISwapChain3}
#Import export ".\IDXGISwapChain4.ahk" {IDXGISwapChain4}
#Import export ".\IDXGISwapChainMedia.ahk" {IDXGISwapChainMedia}
#Import export ".\IDXGraphicsAnalysis.ahk" {IDXGraphicsAnalysis}
