#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\GESTURECONFIG.ahk" {GESTURECONFIG}
#Import export ".\GESTURECONFIG_ID.ahk" {GESTURECONFIG_ID}
#Import export ".\GESTUREINFO.ahk" {GESTUREINFO}
#Import export ".\GESTURENOTIFYSTRUCT.ahk" {GESTURENOTIFYSTRUCT}
#Import export ".\HGESTUREINFO.ahk" {HGESTUREINFO}
#Import export ".\HTOUCHINPUT.ahk" {HTOUCHINPUT}
#Import export ".\IInertiaProcessor.ahk" {IInertiaProcessor}
#Import export ".\IManipulationProcessor.ahk" {IManipulationProcessor}
#Import export ".\InertiaProcessor.ahk" {InertiaProcessor}
#Import export ".\MANIPULATION_PROCESSOR_MANIPULATIONS.ahk" {MANIPULATION_PROCESSOR_MANIPULATIONS}
#Import export ".\ManipulationProcessor.ahk" {ManipulationProcessor}
#Import export ".\REGISTER_TOUCH_WINDOW_FLAGS.ahk" {REGISTER_TOUCH_WINDOW_FLAGS}
#Import export ".\TOUCHEVENTF_FLAGS.ahk" {TOUCHEVENTF_FLAGS}
#Import export ".\TOUCHINPUT.ahk" {TOUCHINPUT}
#Import export ".\TOUCHINPUTMASKF_MASK.ahk" {TOUCHINPUTMASKF_MASK}
#Import export ".\_IManipulationEvents.ahk" {_IManipulationEvents}
