#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PINTERFACE_REFERENCE.ahk" { PINTERFACE_REFERENCE }
#Import ".\PGPE_CLEAR_STATUS2.ahk" { PGPE_CLEAR_STATUS2 }
#Import ".\PGPE_DISCONNECT_VECTOR2.ahk" { PGPE_DISCONNECT_VECTOR2 }
#Import ".\PGPE_ENABLE_EVENT2.ahk" { PGPE_ENABLE_EVENT2 }
#Import ".\PINTERFACE_DEREFERENCE.ahk" { PINTERFACE_DEREFERENCE }
#Import ".\PUNREGISTER_FOR_DEVICE_NOTIFICATIONS2.ahk" { PUNREGISTER_FOR_DEVICE_NOTIFICATIONS2 }
#Import ".\PGPE_CONNECT_VECTOR2.ahk" { PGPE_CONNECT_VECTOR2 }
#Import ".\PREGISTER_FOR_DEVICE_NOTIFICATIONS2.ahk" { PREGISTER_FOR_DEVICE_NOTIFICATIONS2 }
#Import ".\PGPE_DISABLE_EVENT2.ahk" { PGPE_DISABLE_EVENT2 }

/**
 * @namespace Windows.Wdk.System.SystemServices
 */
export default struct ACPI_INTERFACE_STANDARD2 {
    #StructPack 8

    Size : UInt16

    Version : UInt16

    Context : IntPtr

    InterfaceReference : PINTERFACE_REFERENCE

    InterfaceDereference : PINTERFACE_DEREFERENCE

    GpeConnectVector : PGPE_CONNECT_VECTOR2

    GpeDisconnectVector : PGPE_DISCONNECT_VECTOR2

    GpeEnableEvent : PGPE_ENABLE_EVENT2

    GpeDisableEvent : PGPE_DISABLE_EVENT2

    GpeClearStatus : PGPE_CLEAR_STATUS2

    RegisterForDeviceNotifications : PREGISTER_FOR_DEVICE_NOTIFICATIONS2

    UnregisterForDeviceNotifications : PUNREGISTER_FOR_DEVICE_NOTIFICATIONS2

}
