#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PIOMMU_DOMAIN_ATTACH_DEVICE.ahk" { PIOMMU_DOMAIN_ATTACH_DEVICE }
#Import ".\PIOMMU_DOMAIN_CONFIGURE.ahk" { PIOMMU_DOMAIN_CONFIGURE }
#Import ".\PIOMMU_DOMAIN_CREATE.ahk" { PIOMMU_DOMAIN_CREATE }
#Import ".\PIOMMU_DOMAIN_DELETE.ahk" { PIOMMU_DOMAIN_DELETE }
#Import ".\PIOMMU_DOMAIN_DETACH_DEVICE.ahk" { PIOMMU_DOMAIN_DETACH_DEVICE }
#Import ".\PIOMMU_FLUSH_DOMAIN.ahk" { PIOMMU_FLUSH_DOMAIN }
#Import ".\PIOMMU_FLUSH_DOMAIN_VA_LIST.ahk" { PIOMMU_FLUSH_DOMAIN_VA_LIST }
#Import ".\PIOMMU_MAP_IDENTITY_RANGE.ahk" { PIOMMU_MAP_IDENTITY_RANGE }
#Import ".\PIOMMU_MAP_LOGICAL_RANGE.ahk" { PIOMMU_MAP_LOGICAL_RANGE }
#Import ".\PIOMMU_QUERY_INPUT_MAPPINGS.ahk" { PIOMMU_QUERY_INPUT_MAPPINGS }
#Import ".\PIOMMU_SET_DEVICE_FAULT_REPORTING.ahk" { PIOMMU_SET_DEVICE_FAULT_REPORTING }
#Import ".\PIOMMU_UNMAP_IDENTITY_RANGE.ahk" { PIOMMU_UNMAP_IDENTITY_RANGE }
#Import ".\PIOMMU_UNMAP_LOGICAL_RANGE.ahk" { PIOMMU_UNMAP_LOGICAL_RANGE }

/**
 * @namespace Windows.Wdk.System.SystemServices
 */
export default struct DMA_IOMMU_INTERFACE {
    #StructPack 8

    Version : UInt32

    CreateDomain : PIOMMU_DOMAIN_CREATE

    DeleteDomain : PIOMMU_DOMAIN_DELETE

    AttachDevice : PIOMMU_DOMAIN_ATTACH_DEVICE

    DetachDevice : PIOMMU_DOMAIN_DETACH_DEVICE

    FlushDomain : PIOMMU_FLUSH_DOMAIN

    FlushDomainByVaList : PIOMMU_FLUSH_DOMAIN_VA_LIST

    QueryInputMappings : PIOMMU_QUERY_INPUT_MAPPINGS

    MapLogicalRange : PIOMMU_MAP_LOGICAL_RANGE

    UnmapLogicalRange : PIOMMU_UNMAP_LOGICAL_RANGE

    MapIdentityRange : PIOMMU_MAP_IDENTITY_RANGE

    UnmapIdentityRange : PIOMMU_UNMAP_IDENTITY_RANGE

    SetDeviceFaultReporting : PIOMMU_SET_DEVICE_FAULT_REPORTING

    ConfigureDomain : PIOMMU_DOMAIN_CONFIGURE

}
