#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PHALMCAINTERFACELOCK.ahk" { PHALMCAINTERFACELOCK }
#Import ".\PHALMCAINTERFACEREADREGISTER.ahk" { PHALMCAINTERFACEREADREGISTER }
#Import ".\PHALMCAINTERFACEUNLOCK.ahk" { PHALMCAINTERFACEUNLOCK }

/**
 * @namespace Windows.Wdk.System.SystemServices
 */
export default struct HAL_MCA_INTERFACE {
    #StructPack 8

    Lock : PHALMCAINTERFACELOCK

    Unlock : PHALMCAINTERFACEUNLOCK

    ReadRegister : PHALMCAINTERFACEREADREGISTER

}
