#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PNPEM_CONTROL_QUERY_CONTROL.ahk" { PNPEM_CONTROL_QUERY_CONTROL }
#Import ".\PNPEM_CONTROL_ENABLE_DISABLE.ahk" { PNPEM_CONTROL_ENABLE_DISABLE }
#Import ".\PNPEM_CONTROL_SET_STANDARD_CONTROL.ahk" { PNPEM_CONTROL_SET_STANDARD_CONTROL }
#Import ".\PNPEM_CONTROL_QUERY_STANDARD_CAPABILITIES.ahk" { PNPEM_CONTROL_QUERY_STANDARD_CAPABILITIES }
#Import ".\PINTERFACE_DEREFERENCE.ahk" { PINTERFACE_DEREFERENCE }
#Import ".\PINTERFACE_REFERENCE.ahk" { PINTERFACE_REFERENCE }

/**
 * @namespace Windows.Wdk.System.SystemServices
 */
export default struct NPEM_CONTROL_INTERFACE {
    #StructPack 8

    Size : UInt16

    Version : UInt16

    Context : IntPtr

    InterfaceReference : PINTERFACE_REFERENCE

    InterfaceDereference : PINTERFACE_DEREFERENCE

    SetNpemSupportState : PNPEM_CONTROL_ENABLE_DISABLE

    QueryStandardCapabilities : PNPEM_CONTROL_QUERY_STANDARD_CAPABILITIES

    SetStandardControl : PNPEM_CONTROL_SET_STANDARD_CONTROL

    QueryNpemControl : PNPEM_CONTROL_QUERY_CONTROL

}
