#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PENABLE_VIRTUALIZATION.ahk" { PENABLE_VIRTUALIZATION }
#Import ".\PGET_VIRTUAL_DEVICE_DATA.ahk" { PGET_VIRTUAL_DEVICE_DATA }
#Import ".\PGET_VIRTUAL_DEVICE_LOCATION.ahk" { PGET_VIRTUAL_DEVICE_LOCATION }
#Import ".\PGET_VIRTUAL_DEVICE_RESOURCES.ahk" { PGET_VIRTUAL_DEVICE_RESOURCES }
#Import ".\PGET_VIRTUAL_FUNCTION_PROBED_BARS.ahk" { PGET_VIRTUAL_FUNCTION_PROBED_BARS }
#Import ".\PINTERFACE_DEREFERENCE.ahk" { PINTERFACE_DEREFERENCE }
#Import ".\PINTERFACE_REFERENCE.ahk" { PINTERFACE_REFERENCE }
#Import ".\PSET_VIRTUAL_DEVICE_DATA.ahk" { PSET_VIRTUAL_DEVICE_DATA }

/**
 * @namespace Windows.Wdk.System.SystemServices
 */
export default struct PCI_VIRTUALIZATION_INTERFACE {
    #StructPack 8

    Size : UInt16

    Version : UInt16

    Context : IntPtr

    InterfaceReference : PINTERFACE_REFERENCE

    InterfaceDereference : PINTERFACE_DEREFERENCE

    SetVirtualFunctionData : PSET_VIRTUAL_DEVICE_DATA

    GetVirtualFunctionData : PGET_VIRTUAL_DEVICE_DATA

    GetLocation : PGET_VIRTUAL_DEVICE_LOCATION

    GetResources : PGET_VIRTUAL_DEVICE_RESOURCES

    EnableVirtualization : PENABLE_VIRTUALIZATION

    GetVirtualFunctionProbedBars : PGET_VIRTUAL_FUNCTION_PROBED_BARS

}
