#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PREPLACE_SWAP.ahk" { PREPLACE_SWAP }
#Import ".\PREPLACE_INITIATE_HARDWARE_MIRROR.ahk" { PREPLACE_INITIATE_HARDWARE_MIRROR }
#Import ".\PREPLACE_MIRROR_PHYSICAL_MEMORY.ahk" { PREPLACE_MIRROR_PHYSICAL_MEMORY }
#Import ".\PREPLACE_SET_PROCESSOR_ID.ahk" { PREPLACE_SET_PROCESSOR_ID }
#Import ".\PREPLACE_END.ahk" { PREPLACE_END }
#Import ".\PREPLACE_MIRROR_PLATFORM_MEMORY.ahk" { PREPLACE_MIRROR_PLATFORM_MEMORY }
#Import ".\PREPLACE_BEGIN.ahk" { PREPLACE_BEGIN }
#Import ".\PREPLACE_UNLOAD.ahk" { PREPLACE_UNLOAD }
#Import ".\PREPLACE_ENABLE_DISABLE_HARDWARE_QUIESCE.ahk" { PREPLACE_ENABLE_DISABLE_HARDWARE_QUIESCE }
#Import ".\PREPLACE_GET_MEMORY_DESTINATION.ahk" { PREPLACE_GET_MEMORY_DESTINATION }

/**
 * @namespace Windows.Wdk.System.SystemServices
 */
export default struct PNP_REPLACE_DRIVER_INTERFACE {
    #StructPack 8

    Size : UInt32

    Version : UInt32

    Flags : UInt32

    Unload : PREPLACE_UNLOAD

    BeginReplace : PREPLACE_BEGIN

    EndReplace : PREPLACE_END

    MirrorPhysicalMemory : PREPLACE_MIRROR_PHYSICAL_MEMORY

    SetProcessorId : PREPLACE_SET_PROCESSOR_ID

    Swap : PREPLACE_SWAP

    InitiateHardwareMirror : PREPLACE_INITIATE_HARDWARE_MIRROR

    MirrorPlatformMemory : PREPLACE_MIRROR_PLATFORM_MEMORY

    GetMemoryDestination : PREPLACE_GET_MEMORY_DESTINATION

    EnableDisableHardwareQuiesce : PREPLACE_ENABLE_DISABLE_HARDWARE_QUIESCE

}
