#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\PPO_FX_DIRECTED_POWER_DOWN_CALLBACK.ahk" { PPO_FX_DIRECTED_POWER_DOWN_CALLBACK }
#Import ".\PPO_FX_COMPONENT_IDLE_CONDITION_CALLBACK.ahk" { PPO_FX_COMPONENT_IDLE_CONDITION_CALLBACK }
#Import ".\PPO_FX_POWER_CONTROL_CALLBACK.ahk" { PPO_FX_POWER_CONTROL_CALLBACK }
#Import ".\PPO_FX_COMPONENT_IDLE_STATE_CALLBACK.ahk" { PPO_FX_COMPONENT_IDLE_STATE_CALLBACK }
#Import ".\PPO_FX_COMPONENT_ACTIVE_CONDITION_CALLBACK.ahk" { PPO_FX_COMPONENT_ACTIVE_CONDITION_CALLBACK }
#Import ".\PPO_FX_DEVICE_POWER_NOT_REQUIRED_CALLBACK.ahk" { PPO_FX_DEVICE_POWER_NOT_REQUIRED_CALLBACK }
#Import ".\PPO_FX_DEVICE_POWER_REQUIRED_CALLBACK.ahk" { PPO_FX_DEVICE_POWER_REQUIRED_CALLBACK }
#Import ".\PPO_FX_DIRECTED_POWER_UP_CALLBACK.ahk" { PPO_FX_DIRECTED_POWER_UP_CALLBACK }

/**
 * @namespace Windows.Wdk.System.SystemServices
 */
export default struct PO_FX_DEVICE_V3 {
    #StructPack 8

    Version : UInt32

    Flags : Int64

    ComponentActiveConditionCallback : PPO_FX_COMPONENT_ACTIVE_CONDITION_CALLBACK

    ComponentIdleConditionCallback : PPO_FX_COMPONENT_IDLE_CONDITION_CALLBACK

    ComponentIdleStateCallback : PPO_FX_COMPONENT_IDLE_STATE_CALLBACK

    DevicePowerRequiredCallback : PPO_FX_DEVICE_POWER_REQUIRED_CALLBACK

    DevicePowerNotRequiredCallback : PPO_FX_DEVICE_POWER_NOT_REQUIRED_CALLBACK

    PowerControlCallback : PPO_FX_POWER_CONTROL_CALLBACK

    DirectedPowerUpCallback : PPO_FX_DIRECTED_POWER_UP_CALLBACK

    DirectedPowerDownCallback : PPO_FX_DIRECTED_POWER_DOWN_CALLBACK

    DirectedFxTimeoutInSeconds : UInt32

    DeviceContext : IntPtr

    ComponentCount : UInt32

    Components : IntPtr[1]

}
