#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\WHEA_ERROR_SOURCE_UNINITIALIZE.ahk" { WHEA_ERROR_SOURCE_UNINITIALIZE }
#Import ".\WHEA_ERROR_SOURCE_CORRECT.ahk" { WHEA_ERROR_SOURCE_CORRECT }
#Import ".\WHEA_ERROR_SOURCE_RECOVER.ahk" { WHEA_ERROR_SOURCE_RECOVER }
#Import ".\WHEA_ERROR_SOURCE_CREATE_RECORD.ahk" { WHEA_ERROR_SOURCE_CREATE_RECORD }
#Import ".\WHEA_ERROR_SOURCE_INITIALIZE.ahk" { WHEA_ERROR_SOURCE_INITIALIZE }

/**
 * @namespace Windows.Wdk.System.SystemServices
 */
export default struct WHEA_ERROR_SOURCE_CONFIGURATION {
    #StructPack 8

    Flags : UInt32

    Correct : WHEA_ERROR_SOURCE_CORRECT

    Initialize : WHEA_ERROR_SOURCE_INITIALIZE

    CreateRecord : WHEA_ERROR_SOURCE_CREATE_RECORD

    Recover : WHEA_ERROR_SOURCE_RECOVER

    Uninitialize : WHEA_ERROR_SOURCE_UNINITIALIZE

    Reserved : IntPtr

}
