#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\CallObj\__Init.ahk" {*}
#Import export ".\ChannelCredentials\__Init.ahk" {*}
#Import export ".\Events\__Init.ahk" {*}
#Import export ".\Marshal\__Init.ahk" {*}
#Import export ".\StructuredStorage\__Init.ahk" {*}
#Import export ".\UI\__Init.ahk" {*}
#Import export ".\Urlmon\__Init.ahk" {*}
#Import export ".\ADVANCED_FEATURE_FLAGS.ahk" {ADVANCED_FEATURE_FLAGS}
#Import export ".\ADVF.ahk" {ADVF}
#Import export ".\APTTYPE.ahk" {APTTYPE}
#Import export ".\APTTYPEQUALIFIER.ahk" {APTTYPEQUALIFIER}
#Import export ".\AUTHENTICATEINFO.ahk" {AUTHENTICATEINFO}
#Import export ".\Apis.ahk" {*}
#Import export ".\ApplicationType.ahk" {ApplicationType}
#Import export ".\AsyncIAdviseSink.ahk" {AsyncIAdviseSink}
#Import export ".\AsyncIAdviseSink2.ahk" {AsyncIAdviseSink2}
#Import export ".\AsyncIMultiQI.ahk" {AsyncIMultiQI}
#Import export ".\AsyncIPipeByte.ahk" {AsyncIPipeByte}
#Import export ".\AsyncIPipeDouble.ahk" {AsyncIPipeDouble}
#Import export ".\AsyncIPipeLong.ahk" {AsyncIPipeLong}
#Import export ".\AsyncIUnknown.ahk" {AsyncIUnknown}
#Import export ".\BINDINFO.ahk" {BINDINFO}
#Import export ".\BINDINFOF.ahk" {BINDINFOF}
#Import export ".\BINDPTR.ahk" {BINDPTR}
#Import export ".\BIND_FLAGS.ahk" {BIND_FLAGS}
#Import export ".\BIND_OPTS.ahk" {BIND_OPTS}
#Import export ".\BIND_OPTS2.ahk" {BIND_OPTS2}
#Import export ".\BIND_OPTS3.ahk" {BIND_OPTS3}
#Import export ".\BLOB.ahk" {BLOB}
#Import export ".\BYTE_BLOB.ahk" {BYTE_BLOB}
#Import export ".\BYTE_SIZEDARR.ahk" {BYTE_SIZEDARR}
#Import export ".\CALLCONV.ahk" {CALLCONV}
#Import export ".\CALLTYPE.ahk" {CALLTYPE}
#Import export ".\CATEGORYINFO.ahk" {CATEGORYINFO}
#Import export ".\CLSCTX.ahk" {CLSCTX}
#Import export ".\COAUTHIDENTITY.ahk" {COAUTHIDENTITY}
#Import export ".\COAUTHINFO.ahk" {COAUTHINFO}
#Import export ".\COINIT.ahk" {COINIT}
#Import export ".\COINITBASE.ahk" {COINITBASE}
#Import export ".\COMSD.ahk" {COMSD}
#Import export ".\CONNECTDATA.ahk" {CONNECTDATA}
#Import export ".\COSERVERINFO.ahk" {COSERVERINFO}
#Import export ".\COWAIT_FLAGS.ahk" {COWAIT_FLAGS}
#Import export ".\CO_DEVICE_CATALOG_COOKIE.ahk" {CO_DEVICE_CATALOG_COOKIE}
#Import export ".\CO_MARSHALING_CONTEXT_ATTRIBUTES.ahk" {CO_MARSHALING_CONTEXT_ATTRIBUTES}
#Import export ".\CO_MTA_USAGE_COOKIE.ahk" {CO_MTA_USAGE_COOKIE}
#Import export ".\CSPLATFORM.ahk" {CSPLATFORM}
#Import export ".\CUSTDATA.ahk" {CUSTDATA}
#Import export ".\CUSTDATAITEM.ahk" {CUSTDATAITEM}
#Import export ".\CWMO_FLAGS.ahk" {CWMO_FLAGS}
#Import export ".\CY.ahk" {CY}
#Import export ".\ComCallData.ahk" {ComCallData}
#Import export ".\Constants.ahk" {*}
#Import export ".\ContextProperty.ahk" {ContextProperty}
#Import export ".\DATADIR.ahk" {DATADIR}
#Import export ".\DCOM_CALL_STATE.ahk" {DCOM_CALL_STATE}
#Import export ".\DESCKIND.ahk" {DESCKIND}
#Import export ".\DISPATCH_FLAGS.ahk" {DISPATCH_FLAGS}
#Import export ".\DISPPARAMS.ahk" {DISPPARAMS}
#Import export ".\DVASPECT.ahk" {DVASPECT}
#Import export ".\DVTARGETDEVICE.ahk" {DVTARGETDEVICE}
#Import export ".\DWORD_BLOB.ahk" {DWORD_BLOB}
#Import export ".\DWORD_SIZEDARR.ahk" {DWORD_SIZEDARR}
#Import export ".\ELEMDESC.ahk" {ELEMDESC}
#Import export ".\EOLE_AUTHENTICATION_CAPABILITIES.ahk" {EOLE_AUTHENTICATION_CAPABILITIES}
#Import export ".\EXCEPINFO.ahk" {EXCEPINFO}
#Import export ".\EXTCONN.ahk" {EXTCONN}
#Import export ".\FLAGGED_BYTE_BLOB.ahk" {FLAGGED_BYTE_BLOB}
#Import export ".\FLAGGED_WORD_BLOB.ahk" {FLAGGED_WORD_BLOB}
#Import export ".\FLAG_STGMEDIUM.ahk" {FLAG_STGMEDIUM}
#Import export ".\FORMATETC.ahk" {FORMATETC}
#Import export ".\FUNCDESC.ahk" {FUNCDESC}
#Import export ".\FUNCFLAGS.ahk" {FUNCFLAGS}
#Import export ".\FUNCKIND.ahk" {FUNCKIND}
#Import export ".\GDI_OBJECT.ahk" {GDI_OBJECT}
#Import export ".\GLOBALOPT_EH_VALUES.ahk" {GLOBALOPT_EH_VALUES}
#Import export ".\GLOBALOPT_PROPERTIES.ahk" {GLOBALOPT_PROPERTIES}
#Import export ".\GLOBALOPT_RO_FLAGS.ahk" {GLOBALOPT_RO_FLAGS}
#Import export ".\GLOBALOPT_RPCTP_VALUES.ahk" {GLOBALOPT_RPCTP_VALUES}
#Import export ".\GLOBALOPT_UNMARSHALING_POLICY_VALUES.ahk" {GLOBALOPT_UNMARSHALING_POLICY_VALUES}
#Import export ".\HYPER_SIZEDARR.ahk" {HYPER_SIZEDARR}
#Import export ".\IActivationFilter.ahk" {IActivationFilter}
#Import export ".\IAddrExclusionControl.ahk" {IAddrExclusionControl}
#Import export ".\IAddrTrackingControl.ahk" {IAddrTrackingControl}
#Import export ".\IAdviseSink.ahk" {IAdviseSink}
#Import export ".\IAdviseSink2.ahk" {IAdviseSink2}
#Import export ".\IAgileObject.ahk" {IAgileObject}
#Import export ".\IAsyncManager.ahk" {IAsyncManager}
#Import export ".\IAsyncRpcChannelBuffer.ahk" {IAsyncRpcChannelBuffer}
#Import export ".\IAuthenticate.ahk" {IAuthenticate}
#Import export ".\IAuthenticateEx.ahk" {IAuthenticateEx}
#Import export ".\IBindCtx.ahk" {IBindCtx}
#Import export ".\IBindHost.ahk" {IBindHost}
#Import export ".\IBindStatusCallback.ahk" {IBindStatusCallback}
#Import export ".\IBindStatusCallbackEx.ahk" {IBindStatusCallbackEx}
#Import export ".\IBinding.ahk" {IBinding}
#Import export ".\IBlockingLock.ahk" {IBlockingLock}
#Import export ".\ICallFactory.ahk" {ICallFactory}
#Import export ".\ICancelMethodCalls.ahk" {ICancelMethodCalls}
#Import export ".\ICatInformation.ahk" {ICatInformation}
#Import export ".\ICatRegister.ahk" {ICatRegister}
#Import export ".\IChannelHook.ahk" {IChannelHook}
#Import export ".\IClassActivator.ahk" {IClassActivator}
#Import export ".\IClassFactory.ahk" {IClassFactory}
#Import export ".\IClientSecurity.ahk" {IClientSecurity}
#Import export ".\IComThreadingInfo.ahk" {IComThreadingInfo}
#Import export ".\IConnectionPoint.ahk" {IConnectionPoint}
#Import export ".\IConnectionPointContainer.ahk" {IConnectionPointContainer}
#Import export ".\IContext.ahk" {IContext}
#Import export ".\IContextCallback.ahk" {IContextCallback}
#Import export ".\IDLDESC.ahk" {IDLDESC}
#Import export ".\IDLFLAGS.ahk" {IDLFLAGS}
#Import export ".\IDataAdviseHolder.ahk" {IDataAdviseHolder}
#Import export ".\IDataObject.ahk" {IDataObject}
#Import export ".\IDispatch.ahk" {IDispatch}
#Import export ".\IEnumCATEGORYINFO.ahk" {IEnumCATEGORYINFO}
#Import export ".\IEnumConnectionPoints.ahk" {IEnumConnectionPoints}
#Import export ".\IEnumConnections.ahk" {IEnumConnections}
#Import export ".\IEnumContextProps.ahk" {IEnumContextProps}
#Import export ".\IEnumFORMATETC.ahk" {IEnumFORMATETC}
#Import export ".\IEnumGUID.ahk" {IEnumGUID}
#Import export ".\IEnumMoniker.ahk" {IEnumMoniker}
#Import export ".\IEnumSTATDATA.ahk" {IEnumSTATDATA}
#Import export ".\IEnumString.ahk" {IEnumString}
#Import export ".\IEnumUnknown.ahk" {IEnumUnknown}
#Import export ".\IErrorInfo.ahk" {IErrorInfo}
#Import export ".\IErrorLog.ahk" {IErrorLog}
#Import export ".\IExternalConnection.ahk" {IExternalConnection}
#Import export ".\IFastRundown.ahk" {IFastRundown}
#Import export ".\IForegroundTransfer.ahk" {IForegroundTransfer}
#Import export ".\IGlobalInterfaceTable.ahk" {IGlobalInterfaceTable}
#Import export ".\IGlobalOptions.ahk" {IGlobalOptions}
#Import export ".\IInitializeSpy.ahk" {IInitializeSpy}
#Import export ".\IInternalUnknown.ahk" {IInternalUnknown}
#Import export ".\IMPLTYPEFLAGS.ahk" {IMPLTYPEFLAGS}
#Import export ".\IMachineGlobalObjectTable.ahk" {IMachineGlobalObjectTable}
#Import export ".\IMalloc.ahk" {IMalloc}
#Import export ".\IMallocSpy.ahk" {IMallocSpy}
#Import export ".\IMoniker.ahk" {IMoniker}
#Import export ".\IMultiQI.ahk" {IMultiQI}
#Import export ".\INTERFACEINFO.ahk" {INTERFACEINFO}
#Import export ".\INVOKEKIND.ahk" {INVOKEKIND}
#Import export ".\INoMarshal.ahk" {INoMarshal}
#Import export ".\IOplockStorage.ahk" {IOplockStorage}
#Import export ".\IPSFactoryBuffer.ahk" {IPSFactoryBuffer}
#Import export ".\IPackagedComSyntaxSupport.ahk" {IPackagedComSyntaxSupport}
#Import export ".\IPersist.ahk" {IPersist}
#Import export ".\IPersistFile.ahk" {IPersistFile}
#Import export ".\IPersistMemory.ahk" {IPersistMemory}
#Import export ".\IPersistStream.ahk" {IPersistStream}
#Import export ".\IPersistStreamInit.ahk" {IPersistStreamInit}
#Import export ".\IPipeByte.ahk" {IPipeByte}
#Import export ".\IPipeDouble.ahk" {IPipeDouble}
#Import export ".\IPipeLong.ahk" {IPipeLong}
#Import export ".\IProcessInitControl.ahk" {IProcessInitControl}
#Import export ".\IProcessLock.ahk" {IProcessLock}
#Import export ".\IProgressNotify.ahk" {IProgressNotify}
#Import export ".\IROTData.ahk" {IROTData}
#Import export ".\IReleaseMarshalBuffers.ahk" {IReleaseMarshalBuffers}
#Import export ".\IRpcChannelBuffer.ahk" {IRpcChannelBuffer}
#Import export ".\IRpcChannelBuffer2.ahk" {IRpcChannelBuffer2}
#Import export ".\IRpcChannelBuffer3.ahk" {IRpcChannelBuffer3}
#Import export ".\IRpcHelper.ahk" {IRpcHelper}
#Import export ".\IRpcOptions.ahk" {IRpcOptions}
#Import export ".\IRpcProxyBuffer.ahk" {IRpcProxyBuffer}
#Import export ".\IRpcStubBuffer.ahk" {IRpcStubBuffer}
#Import export ".\IRpcSyntaxNegotiate.ahk" {IRpcSyntaxNegotiate}
#Import export ".\IRunnableObject.ahk" {IRunnableObject}
#Import export ".\IRunningObjectTable.ahk" {IRunningObjectTable}
#Import export ".\ISequentialStream.ahk" {ISequentialStream}
#Import export ".\IServerSecurity.ahk" {IServerSecurity}
#Import export ".\IServiceProvider.ahk" {IServiceProvider}
#Import export ".\IStdMarshalInfo.ahk" {IStdMarshalInfo}
#Import export ".\IStream.ahk" {IStream}
#Import export ".\ISupportActivateAsActivatorPackaged.ahk" {ISupportActivateAsActivatorPackaged}
#Import export ".\ISupportActivationFromPackage.ahk" {ISupportActivationFromPackage}
#Import export ".\ISupportAllowLowerTrustActivation.ahk" {ISupportAllowLowerTrustActivation}
#Import export ".\ISupportCoAddComDependencyOnPackage.ahk" {ISupportCoAddComDependencyOnPackage}
#Import export ".\ISupportDoNotElevateServerActivation.ahk" {ISupportDoNotElevateServerActivation}
#Import export ".\ISupportErrorInfo.ahk" {ISupportErrorInfo}
#Import export ".\ISupportPackagedComElevationEnabledClasses.ahk" {ISupportPackagedComElevationEnabledClasses}
#Import export ".\ISupportPackagedComRegistrationVisibility.ahk" {ISupportPackagedComRegistrationVisibility}
#Import export ".\ISupportServerMustBeEqualOrGreaterPrivilegeActivation.ahk" {ISupportServerMustBeEqualOrGreaterPrivilegeActivation}
#Import export ".\ISurrogate.ahk" {ISurrogate}
#Import export ".\ISurrogateService.ahk" {ISurrogateService}
#Import export ".\ISynchronize.ahk" {ISynchronize}
#Import export ".\ISynchronizeContainer.ahk" {ISynchronizeContainer}
#Import export ".\ISynchronizeEvent.ahk" {ISynchronizeEvent}
#Import export ".\ISynchronizeHandle.ahk" {ISynchronizeHandle}
#Import export ".\ISynchronizeMutex.ahk" {ISynchronizeMutex}
#Import export ".\ITimeAndNoticeControl.ahk" {ITimeAndNoticeControl}
#Import export ".\ITypeComp.ahk" {ITypeComp}
#Import export ".\ITypeInfo.ahk" {ITypeInfo}
#Import export ".\ITypeInfo2.ahk" {ITypeInfo2}
#Import export ".\ITypeLib.ahk" {ITypeLib}
#Import export ".\ITypeLib2.ahk" {ITypeLib2}
#Import export ".\ITypeLibRegistration.ahk" {ITypeLibRegistration}
#Import export ".\ITypeLibRegistrationReader.ahk" {ITypeLibRegistrationReader}
#Import export ".\IUnknown.ahk" {IUnknown}
#Import export ".\IUri.ahk" {IUri}
#Import export ".\IUriBuilder.ahk" {IUriBuilder}
#Import export ".\IUrlMon.ahk" {IUrlMon}
#Import export ".\IWaitMultiple.ahk" {IWaitMultiple}
#Import export ".\LOCKTYPE.ahk" {LOCKTYPE}
#Import export ".\LPEXCEPFINO_DEFERRED_FILLIN.ahk" {LPEXCEPFINO_DEFERRED_FILLIN}
#Import export ".\LPFNCANUNLOADNOW.ahk" {LPFNCANUNLOADNOW}
#Import export ".\LPFNGETCLASSOBJECT.ahk" {LPFNGETCLASSOBJECT}
#Import export ".\MEMCTX.ahk" {MEMCTX}
#Import export ".\MKRREDUCE.ahk" {MKRREDUCE}
#Import export ".\MKSYS.ahk" {MKSYS}
#Import export ".\MSHCTX.ahk" {MSHCTX}
#Import export ".\MSHLFLAGS.ahk" {MSHLFLAGS}
#Import export ".\MULTI_QI.ahk" {MULTI_QI}
#Import export ".\MachineGlobalObjectTableRegistrationToken.ahk" {MachineGlobalObjectTableRegistrationToken}
#Import export ".\PENDINGMSG.ahk" {PENDINGMSG}
#Import export ".\PENDINGTYPE.ahk" {PENDINGTYPE}
#Import export ".\PFNCONTEXTCALL.ahk" {PFNCONTEXTCALL}
#Import export ".\QUERYCONTEXT.ahk" {QUERYCONTEXT}
#Import export ".\REGCLS.ahk" {REGCLS}
#Import export ".\ROT_FLAGS.ahk" {ROT_FLAGS}
#Import export ".\RPCOLEMESSAGE.ahk" {RPCOLEMESSAGE}
#Import export ".\RPCOPT_PROPERTIES.ahk" {RPCOPT_PROPERTIES}
#Import export ".\RPCOPT_SERVER_LOCALITY_VALUES.ahk" {RPCOPT_SERVER_LOCALITY_VALUES}
#Import export ".\RPC_C_AUTHN_LEVEL.ahk" {RPC_C_AUTHN_LEVEL}
#Import export ".\RPC_C_IMP_LEVEL.ahk" {RPC_C_IMP_LEVEL}
#Import export ".\RemSTGMEDIUM.ahk" {RemSTGMEDIUM}
#Import export ".\SAFEARRAY.ahk" {SAFEARRAY}
#Import export ".\SAFEARRAYBOUND.ahk" {SAFEARRAYBOUND}
#Import export ".\SChannelHookCallInfo.ahk" {SChannelHookCallInfo}
#Import export ".\SERVERCALL.ahk" {SERVERCALL}
#Import export ".\SOLE_AUTHENTICATION_INFO.ahk" {SOLE_AUTHENTICATION_INFO}
#Import export ".\SOLE_AUTHENTICATION_LIST.ahk" {SOLE_AUTHENTICATION_LIST}
#Import export ".\SOLE_AUTHENTICATION_SERVICE.ahk" {SOLE_AUTHENTICATION_SERVICE}
#Import export ".\STATDATA.ahk" {STATDATA}
#Import export ".\STATFLAG.ahk" {STATFLAG}
#Import export ".\STATSTG.ahk" {STATSTG}
#Import export ".\STGC.ahk" {STGC}
#Import export ".\STGM.ahk" {STGM}
#Import export ".\STGMEDIUM.ahk" {STGMEDIUM}
#Import export ".\STGTY.ahk" {STGTY}
#Import export ".\STREAM_SEEK.ahk" {STREAM_SEEK}
#Import export ".\SYSKIND.ahk" {SYSKIND}
#Import export ".\ShutdownType.ahk" {ShutdownType}
#Import export ".\StorageLayout.ahk" {StorageLayout}
#Import export ".\THDTYPE.ahk" {THDTYPE}
#Import export ".\TLIBATTR.ahk" {TLIBATTR}
#Import export ".\TYMED.ahk" {TYMED}
#Import export ".\TYPEATTR.ahk" {TYPEATTR}
#Import export ".\TYPEDESC.ahk" {TYPEDESC}
#Import export ".\TYPEKIND.ahk" {TYPEKIND}
#Import export ".\TYSPEC.ahk" {TYSPEC}
#Import export ".\URI_CREATE_FLAGS.ahk" {URI_CREATE_FLAGS}
#Import export ".\Uri_PROPERTY.ahk" {Uri_PROPERTY}
#Import export ".\VARDESC.ahk" {VARDESC}
#Import export ".\VARFLAGS.ahk" {VARFLAGS}
#Import export ".\VARKIND.ahk" {VARKIND}
#Import export ".\WORD_BLOB.ahk" {WORD_BLOB}
#Import export ".\WORD_SIZEDARR.ahk" {WORD_SIZEDARR}
#Import export ".\uCLSSPEC.ahk" {uCLSSPEC}
#Import export ".\userFLAG_STGMEDIUM.ahk" {userFLAG_STGMEDIUM}
#Import export ".\userSTGMEDIUM.ahk" {userSTGMEDIUM}
