#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32Struct.ahk
#Include ..\..\Foundation\PWSTR.ahk

/**
 * Represents a message generated by a resource indexer. For more info, and scenario-based walkthroughs of how to use these APIs, see Package resource indexing (PRI) APIs and custom build systems.
 * @see https://learn.microsoft.com/windows/win32/menurc/mrmresourceindexermessage
 * @namespace Windows.Win32.UI.WindowsAndMessaging
 * @version v4.0.30319
 */
class MrmResourceIndexerMessage extends Win32Struct
{
    static sizeof => 16

    static packingSize => 8

    /**
     * Type: **[**MrmResourceIndexerMessageSeverity**](mrmresourceindexermessageseverity.md)**
     * 
     * 
     * A value indicating the severity of the message.
     * @type {Integer}
     */
    severity {
        get => NumGet(this, 0, "int")
        set => NumPut("int", value, this, 0)
    }

    /**
     * Type: **ULONG**
     * 
     * 
     * A unique identifier for the message.
     * @type {Integer}
     */
    id {
        get => NumGet(this, 4, "uint")
        set => NumPut("uint", value, this, 4)
    }

    /**
     * Type: **PCWSTR**
     * 
     * 
     * The text of the message. Do not free this pointer; the memory is owned by the operating system.
     * @type {PWSTR}
     */
    text{
        get {
            if(!this.HasProp("__text"))
                this.__text := PWSTR(this.ptr + 8)
            return this.__text
        }
    }
}
