#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\DWRITE_AUTOMATIC_FONT_AXES.ahk" {DWRITE_AUTOMATIC_FONT_AXES}
#Import export ".\DWRITE_BASELINE.ahk" {DWRITE_BASELINE}
#Import export ".\DWRITE_BITMAP_DATA_BGRA32.ahk" {DWRITE_BITMAP_DATA_BGRA32}
#Import export ".\DWRITE_BREAK_CONDITION.ahk" {DWRITE_BREAK_CONDITION}
#Import export ".\DWRITE_CARET_METRICS.ahk" {DWRITE_CARET_METRICS}
#Import export ".\DWRITE_CLUSTER_METRICS.ahk" {DWRITE_CLUSTER_METRICS}
#Import export ".\DWRITE_COLOR_COMPOSITE_MODE.ahk" {DWRITE_COLOR_COMPOSITE_MODE}
#Import export ".\DWRITE_COLOR_F.ahk" {DWRITE_COLOR_F}
#Import export ".\DWRITE_COLOR_GLYPH_RUN.ahk" {DWRITE_COLOR_GLYPH_RUN}
#Import export ".\DWRITE_COLOR_GLYPH_RUN1.ahk" {DWRITE_COLOR_GLYPH_RUN1}
#Import export ".\DWRITE_CONTAINER_TYPE.ahk" {DWRITE_CONTAINER_TYPE}
#Import export ".\DWRITE_FACTORY_TYPE.ahk" {DWRITE_FACTORY_TYPE}
#Import export ".\DWRITE_FILE_FRAGMENT.ahk" {DWRITE_FILE_FRAGMENT}
#Import export ".\DWRITE_FLOW_DIRECTION.ahk" {DWRITE_FLOW_DIRECTION}
#Import export ".\DWRITE_FONT_AXIS_ATTRIBUTES.ahk" {DWRITE_FONT_AXIS_ATTRIBUTES}
#Import export ".\DWRITE_FONT_AXIS_RANGE.ahk" {DWRITE_FONT_AXIS_RANGE}
#Import export ".\DWRITE_FONT_AXIS_TAG.ahk" {DWRITE_FONT_AXIS_TAG}
#Import export ".\DWRITE_FONT_AXIS_VALUE.ahk" {DWRITE_FONT_AXIS_VALUE}
#Import export ".\DWRITE_FONT_FACE_TYPE.ahk" {DWRITE_FONT_FACE_TYPE}
#Import export ".\DWRITE_FONT_FAMILY_MODEL.ahk" {DWRITE_FONT_FAMILY_MODEL}
#Import export ".\DWRITE_FONT_FEATURE.ahk" {DWRITE_FONT_FEATURE}
#Import export ".\DWRITE_FONT_FEATURE_TAG.ahk" {DWRITE_FONT_FEATURE_TAG}
#Import export ".\DWRITE_FONT_FILE_TYPE.ahk" {DWRITE_FONT_FILE_TYPE}
#Import export ".\DWRITE_FONT_LINE_GAP_USAGE.ahk" {DWRITE_FONT_LINE_GAP_USAGE}
#Import export ".\DWRITE_FONT_METRICS.ahk" {DWRITE_FONT_METRICS}
#Import export ".\DWRITE_FONT_METRICS1.ahk" {DWRITE_FONT_METRICS1}
#Import export ".\DWRITE_FONT_PROPERTY.ahk" {DWRITE_FONT_PROPERTY}
#Import export ".\DWRITE_FONT_PROPERTY_ID.ahk" {DWRITE_FONT_PROPERTY_ID}
#Import export ".\DWRITE_FONT_SIMULATIONS.ahk" {DWRITE_FONT_SIMULATIONS}
#Import export ".\DWRITE_FONT_SOURCE_TYPE.ahk" {DWRITE_FONT_SOURCE_TYPE}
#Import export ".\DWRITE_FONT_STRETCH.ahk" {DWRITE_FONT_STRETCH}
#Import export ".\DWRITE_FONT_STYLE.ahk" {DWRITE_FONT_STYLE}
#Import export ".\DWRITE_FONT_WEIGHT.ahk" {DWRITE_FONT_WEIGHT}
#Import export ".\DWRITE_GLYPH_IMAGE_DATA.ahk" {DWRITE_GLYPH_IMAGE_DATA}
#Import export ".\DWRITE_GLYPH_IMAGE_FORMATS.ahk" {DWRITE_GLYPH_IMAGE_FORMATS}
#Import export ".\DWRITE_GLYPH_METRICS.ahk" {DWRITE_GLYPH_METRICS}
#Import export ".\DWRITE_GLYPH_OFFSET.ahk" {DWRITE_GLYPH_OFFSET}
#Import export ".\DWRITE_GLYPH_ORIENTATION_ANGLE.ahk" {DWRITE_GLYPH_ORIENTATION_ANGLE}
#Import export ".\DWRITE_GLYPH_RUN.ahk" {DWRITE_GLYPH_RUN}
#Import export ".\DWRITE_GLYPH_RUN_DESCRIPTION.ahk" {DWRITE_GLYPH_RUN_DESCRIPTION}
#Import export ".\DWRITE_GRID_FIT_MODE.ahk" {DWRITE_GRID_FIT_MODE}
#Import export ".\DWRITE_HIT_TEST_METRICS.ahk" {DWRITE_HIT_TEST_METRICS}
#Import export ".\DWRITE_INFORMATIONAL_STRING_ID.ahk" {DWRITE_INFORMATIONAL_STRING_ID}
#Import export ".\DWRITE_INLINE_OBJECT_METRICS.ahk" {DWRITE_INLINE_OBJECT_METRICS}
#Import export ".\DWRITE_JUSTIFICATION_OPPORTUNITY.ahk" {DWRITE_JUSTIFICATION_OPPORTUNITY}
#Import export ".\DWRITE_LINE_BREAKPOINT.ahk" {DWRITE_LINE_BREAKPOINT}
#Import export ".\DWRITE_LINE_METRICS.ahk" {DWRITE_LINE_METRICS}
#Import export ".\DWRITE_LINE_METRICS1.ahk" {DWRITE_LINE_METRICS1}
#Import export ".\DWRITE_LINE_SPACING.ahk" {DWRITE_LINE_SPACING}
#Import export ".\DWRITE_LINE_SPACING_METHOD.ahk" {DWRITE_LINE_SPACING_METHOD}
#Import export ".\DWRITE_LOCALITY.ahk" {DWRITE_LOCALITY}
#Import export ".\DWRITE_MATRIX.ahk" {DWRITE_MATRIX}
#Import export ".\DWRITE_MEASURING_MODE.ahk" {DWRITE_MEASURING_MODE}
#Import export ".\DWRITE_NUMBER_SUBSTITUTION_METHOD.ahk" {DWRITE_NUMBER_SUBSTITUTION_METHOD}
#Import export ".\DWRITE_OPTICAL_ALIGNMENT.ahk" {DWRITE_OPTICAL_ALIGNMENT}
#Import export ".\DWRITE_OUTLINE_THRESHOLD.ahk" {DWRITE_OUTLINE_THRESHOLD}
#Import export ".\DWRITE_OVERHANG_METRICS.ahk" {DWRITE_OVERHANG_METRICS}
#Import export ".\DWRITE_PAINT_ATTRIBUTES.ahk" {DWRITE_PAINT_ATTRIBUTES}
#Import export ".\DWRITE_PAINT_COLOR.ahk" {DWRITE_PAINT_COLOR}
#Import export ".\DWRITE_PAINT_ELEMENT.ahk" {DWRITE_PAINT_ELEMENT}
#Import export ".\DWRITE_PAINT_FEATURE_LEVEL.ahk" {DWRITE_PAINT_FEATURE_LEVEL}
#Import export ".\DWRITE_PAINT_TYPE.ahk" {DWRITE_PAINT_TYPE}
#Import export ".\DWRITE_PANOSE.ahk" {DWRITE_PANOSE}
#Import export ".\DWRITE_PANOSE_ARM_STYLE.ahk" {DWRITE_PANOSE_ARM_STYLE}
#Import export ".\DWRITE_PANOSE_ASPECT.ahk" {DWRITE_PANOSE_ASPECT}
#Import export ".\DWRITE_PANOSE_ASPECT_RATIO.ahk" {DWRITE_PANOSE_ASPECT_RATIO}
#Import export ".\DWRITE_PANOSE_CHARACTER_RANGES.ahk" {DWRITE_PANOSE_CHARACTER_RANGES}
#Import export ".\DWRITE_PANOSE_CONTRAST.ahk" {DWRITE_PANOSE_CONTRAST}
#Import export ".\DWRITE_PANOSE_DECORATIVE_CLASS.ahk" {DWRITE_PANOSE_DECORATIVE_CLASS}
#Import export ".\DWRITE_PANOSE_DECORATIVE_TOPOLOGY.ahk" {DWRITE_PANOSE_DECORATIVE_TOPOLOGY}
#Import export ".\DWRITE_PANOSE_FAMILY.ahk" {DWRITE_PANOSE_FAMILY}
#Import export ".\DWRITE_PANOSE_FILL.ahk" {DWRITE_PANOSE_FILL}
#Import export ".\DWRITE_PANOSE_FINIALS.ahk" {DWRITE_PANOSE_FINIALS}
#Import export ".\DWRITE_PANOSE_LETTERFORM.ahk" {DWRITE_PANOSE_LETTERFORM}
#Import export ".\DWRITE_PANOSE_LINING.ahk" {DWRITE_PANOSE_LINING}
#Import export ".\DWRITE_PANOSE_MIDLINE.ahk" {DWRITE_PANOSE_MIDLINE}
#Import export ".\DWRITE_PANOSE_PROPORTION.ahk" {DWRITE_PANOSE_PROPORTION}
#Import export ".\DWRITE_PANOSE_SCRIPT_FORM.ahk" {DWRITE_PANOSE_SCRIPT_FORM}
#Import export ".\DWRITE_PANOSE_SCRIPT_TOPOLOGY.ahk" {DWRITE_PANOSE_SCRIPT_TOPOLOGY}
#Import export ".\DWRITE_PANOSE_SERIF_STYLE.ahk" {DWRITE_PANOSE_SERIF_STYLE}
#Import export ".\DWRITE_PANOSE_SPACING.ahk" {DWRITE_PANOSE_SPACING}
#Import export ".\DWRITE_PANOSE_STROKE_VARIATION.ahk" {DWRITE_PANOSE_STROKE_VARIATION}
#Import export ".\DWRITE_PANOSE_SYMBOL_ASPECT_RATIO.ahk" {DWRITE_PANOSE_SYMBOL_ASPECT_RATIO}
#Import export ".\DWRITE_PANOSE_SYMBOL_KIND.ahk" {DWRITE_PANOSE_SYMBOL_KIND}
#Import export ".\DWRITE_PANOSE_TOOL_KIND.ahk" {DWRITE_PANOSE_TOOL_KIND}
#Import export ".\DWRITE_PANOSE_WEIGHT.ahk" {DWRITE_PANOSE_WEIGHT}
#Import export ".\DWRITE_PANOSE_XASCENT.ahk" {DWRITE_PANOSE_XASCENT}
#Import export ".\DWRITE_PANOSE_XHEIGHT.ahk" {DWRITE_PANOSE_XHEIGHT}
#Import export ".\DWRITE_PARAGRAPH_ALIGNMENT.ahk" {DWRITE_PARAGRAPH_ALIGNMENT}
#Import export ".\DWRITE_PIXEL_GEOMETRY.ahk" {DWRITE_PIXEL_GEOMETRY}
#Import export ".\DWRITE_READING_DIRECTION.ahk" {DWRITE_READING_DIRECTION}
#Import export ".\DWRITE_RENDERING_MODE.ahk" {DWRITE_RENDERING_MODE}
#Import export ".\DWRITE_RENDERING_MODE1.ahk" {DWRITE_RENDERING_MODE1}
#Import export ".\DWRITE_SCRIPT_ANALYSIS.ahk" {DWRITE_SCRIPT_ANALYSIS}
#Import export ".\DWRITE_SCRIPT_PROPERTIES.ahk" {DWRITE_SCRIPT_PROPERTIES}
#Import export ".\DWRITE_SCRIPT_SHAPES.ahk" {DWRITE_SCRIPT_SHAPES}
#Import export ".\DWRITE_SHAPING_GLYPH_PROPERTIES.ahk" {DWRITE_SHAPING_GLYPH_PROPERTIES}
#Import export ".\DWRITE_SHAPING_TEXT_PROPERTIES.ahk" {DWRITE_SHAPING_TEXT_PROPERTIES}
#Import export ".\DWRITE_STRIKETHROUGH.ahk" {DWRITE_STRIKETHROUGH}
#Import export ".\DWRITE_TEXTURE_TYPE.ahk" {DWRITE_TEXTURE_TYPE}
#Import export ".\DWRITE_TEXT_ALIGNMENT.ahk" {DWRITE_TEXT_ALIGNMENT}
#Import export ".\DWRITE_TEXT_ANTIALIAS_MODE.ahk" {DWRITE_TEXT_ANTIALIAS_MODE}
#Import export ".\DWRITE_TEXT_METRICS.ahk" {DWRITE_TEXT_METRICS}
#Import export ".\DWRITE_TEXT_METRICS1.ahk" {DWRITE_TEXT_METRICS1}
#Import export ".\DWRITE_TEXT_RANGE.ahk" {DWRITE_TEXT_RANGE}
#Import export ".\DWRITE_TRIMMING.ahk" {DWRITE_TRIMMING}
#Import export ".\DWRITE_TRIMMING_GRANULARITY.ahk" {DWRITE_TRIMMING_GRANULARITY}
#Import export ".\DWRITE_TYPOGRAPHIC_FEATURES.ahk" {DWRITE_TYPOGRAPHIC_FEATURES}
#Import export ".\DWRITE_UNDERLINE.ahk" {DWRITE_UNDERLINE}
#Import export ".\DWRITE_UNICODE_RANGE.ahk" {DWRITE_UNICODE_RANGE}
#Import export ".\DWRITE_VERTICAL_GLYPH_ORIENTATION.ahk" {DWRITE_VERTICAL_GLYPH_ORIENTATION}
#Import export ".\DWRITE_WORD_WRAPPING.ahk" {DWRITE_WORD_WRAPPING}
#Import export ".\IDWriteAsyncResult.ahk" {IDWriteAsyncResult}
#Import export ".\IDWriteBitmapRenderTarget.ahk" {IDWriteBitmapRenderTarget}
#Import export ".\IDWriteBitmapRenderTarget1.ahk" {IDWriteBitmapRenderTarget1}
#Import export ".\IDWriteBitmapRenderTarget2.ahk" {IDWriteBitmapRenderTarget2}
#Import export ".\IDWriteBitmapRenderTarget3.ahk" {IDWriteBitmapRenderTarget3}
#Import export ".\IDWriteColorGlyphRunEnumerator.ahk" {IDWriteColorGlyphRunEnumerator}
#Import export ".\IDWriteColorGlyphRunEnumerator1.ahk" {IDWriteColorGlyphRunEnumerator1}
#Import export ".\IDWriteFactory.ahk" {IDWriteFactory}
#Import export ".\IDWriteFactory1.ahk" {IDWriteFactory1}
#Import export ".\IDWriteFactory2.ahk" {IDWriteFactory2}
#Import export ".\IDWriteFactory3.ahk" {IDWriteFactory3}
#Import export ".\IDWriteFactory4.ahk" {IDWriteFactory4}
#Import export ".\IDWriteFactory5.ahk" {IDWriteFactory5}
#Import export ".\IDWriteFactory6.ahk" {IDWriteFactory6}
#Import export ".\IDWriteFactory7.ahk" {IDWriteFactory7}
#Import export ".\IDWriteFactory8.ahk" {IDWriteFactory8}
#Import export ".\IDWriteFont.ahk" {IDWriteFont}
#Import export ".\IDWriteFont1.ahk" {IDWriteFont1}
#Import export ".\IDWriteFont2.ahk" {IDWriteFont2}
#Import export ".\IDWriteFont3.ahk" {IDWriteFont3}
#Import export ".\IDWriteFontCollection.ahk" {IDWriteFontCollection}
#Import export ".\IDWriteFontCollection1.ahk" {IDWriteFontCollection1}
#Import export ".\IDWriteFontCollection2.ahk" {IDWriteFontCollection2}
#Import export ".\IDWriteFontCollection3.ahk" {IDWriteFontCollection3}
#Import export ".\IDWriteFontCollectionLoader.ahk" {IDWriteFontCollectionLoader}
#Import export ".\IDWriteFontDownloadListener.ahk" {IDWriteFontDownloadListener}
#Import export ".\IDWriteFontDownloadQueue.ahk" {IDWriteFontDownloadQueue}
#Import export ".\IDWriteFontFace.ahk" {IDWriteFontFace}
#Import export ".\IDWriteFontFace1.ahk" {IDWriteFontFace1}
#Import export ".\IDWriteFontFace2.ahk" {IDWriteFontFace2}
#Import export ".\IDWriteFontFace3.ahk" {IDWriteFontFace3}
#Import export ".\IDWriteFontFace4.ahk" {IDWriteFontFace4}
#Import export ".\IDWriteFontFace5.ahk" {IDWriteFontFace5}
#Import export ".\IDWriteFontFace6.ahk" {IDWriteFontFace6}
#Import export ".\IDWriteFontFace7.ahk" {IDWriteFontFace7}
#Import export ".\IDWriteFontFaceReference.ahk" {IDWriteFontFaceReference}
#Import export ".\IDWriteFontFaceReference1.ahk" {IDWriteFontFaceReference1}
#Import export ".\IDWriteFontFallback.ahk" {IDWriteFontFallback}
#Import export ".\IDWriteFontFallback1.ahk" {IDWriteFontFallback1}
#Import export ".\IDWriteFontFallbackBuilder.ahk" {IDWriteFontFallbackBuilder}
#Import export ".\IDWriteFontFamily.ahk" {IDWriteFontFamily}
#Import export ".\IDWriteFontFamily1.ahk" {IDWriteFontFamily1}
#Import export ".\IDWriteFontFamily2.ahk" {IDWriteFontFamily2}
#Import export ".\IDWriteFontFile.ahk" {IDWriteFontFile}
#Import export ".\IDWriteFontFileEnumerator.ahk" {IDWriteFontFileEnumerator}
#Import export ".\IDWriteFontFileLoader.ahk" {IDWriteFontFileLoader}
#Import export ".\IDWriteFontFileStream.ahk" {IDWriteFontFileStream}
#Import export ".\IDWriteFontList.ahk" {IDWriteFontList}
#Import export ".\IDWriteFontList1.ahk" {IDWriteFontList1}
#Import export ".\IDWriteFontList2.ahk" {IDWriteFontList2}
#Import export ".\IDWriteFontResource.ahk" {IDWriteFontResource}
#Import export ".\IDWriteFontSet.ahk" {IDWriteFontSet}
#Import export ".\IDWriteFontSet1.ahk" {IDWriteFontSet1}
#Import export ".\IDWriteFontSet2.ahk" {IDWriteFontSet2}
#Import export ".\IDWriteFontSet3.ahk" {IDWriteFontSet3}
#Import export ".\IDWriteFontSet4.ahk" {IDWriteFontSet4}
#Import export ".\IDWriteFontSetBuilder.ahk" {IDWriteFontSetBuilder}
#Import export ".\IDWriteFontSetBuilder1.ahk" {IDWriteFontSetBuilder1}
#Import export ".\IDWriteFontSetBuilder2.ahk" {IDWriteFontSetBuilder2}
#Import export ".\IDWriteGdiInterop.ahk" {IDWriteGdiInterop}
#Import export ".\IDWriteGdiInterop1.ahk" {IDWriteGdiInterop1}
#Import export ".\IDWriteGlyphRunAnalysis.ahk" {IDWriteGlyphRunAnalysis}
#Import export ".\IDWriteInMemoryFontFileLoader.ahk" {IDWriteInMemoryFontFileLoader}
#Import export ".\IDWriteInlineObject.ahk" {IDWriteInlineObject}
#Import export ".\IDWriteLocalFontFileLoader.ahk" {IDWriteLocalFontFileLoader}
#Import export ".\IDWriteLocalizedStrings.ahk" {IDWriteLocalizedStrings}
#Import export ".\IDWriteNumberSubstitution.ahk" {IDWriteNumberSubstitution}
#Import export ".\IDWritePaintReader.ahk" {IDWritePaintReader}
#Import export ".\IDWritePixelSnapping.ahk" {IDWritePixelSnapping}
#Import export ".\IDWriteRemoteFontFileLoader.ahk" {IDWriteRemoteFontFileLoader}
#Import export ".\IDWriteRemoteFontFileStream.ahk" {IDWriteRemoteFontFileStream}
#Import export ".\IDWriteRenderingParams.ahk" {IDWriteRenderingParams}
#Import export ".\IDWriteRenderingParams1.ahk" {IDWriteRenderingParams1}
#Import export ".\IDWriteRenderingParams2.ahk" {IDWriteRenderingParams2}
#Import export ".\IDWriteRenderingParams3.ahk" {IDWriteRenderingParams3}
#Import export ".\IDWriteStringList.ahk" {IDWriteStringList}
#Import export ".\IDWriteTextAnalysisSink.ahk" {IDWriteTextAnalysisSink}
#Import export ".\IDWriteTextAnalysisSink1.ahk" {IDWriteTextAnalysisSink1}
#Import export ".\IDWriteTextAnalysisSource.ahk" {IDWriteTextAnalysisSource}
#Import export ".\IDWriteTextAnalysisSource1.ahk" {IDWriteTextAnalysisSource1}
#Import export ".\IDWriteTextAnalyzer.ahk" {IDWriteTextAnalyzer}
#Import export ".\IDWriteTextAnalyzer1.ahk" {IDWriteTextAnalyzer1}
#Import export ".\IDWriteTextAnalyzer2.ahk" {IDWriteTextAnalyzer2}
#Import export ".\IDWriteTextFormat.ahk" {IDWriteTextFormat}
#Import export ".\IDWriteTextFormat1.ahk" {IDWriteTextFormat1}
#Import export ".\IDWriteTextFormat2.ahk" {IDWriteTextFormat2}
#Import export ".\IDWriteTextFormat3.ahk" {IDWriteTextFormat3}
#Import export ".\IDWriteTextLayout.ahk" {IDWriteTextLayout}
#Import export ".\IDWriteTextLayout1.ahk" {IDWriteTextLayout1}
#Import export ".\IDWriteTextLayout2.ahk" {IDWriteTextLayout2}
#Import export ".\IDWriteTextLayout3.ahk" {IDWriteTextLayout3}
#Import export ".\IDWriteTextLayout4.ahk" {IDWriteTextLayout4}
#Import export ".\IDWriteTextRenderer.ahk" {IDWriteTextRenderer}
#Import export ".\IDWriteTextRenderer1.ahk" {IDWriteTextRenderer1}
#Import export ".\IDWriteTypography.ahk" {IDWriteTypography}
