#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\IVssAdmin.ahk" {IVssAdmin}
#Import export ".\IVssAdminEx.ahk" {IVssAdminEx}
#Import export ".\IVssAsync.ahk" {IVssAsync}
#Import export ".\IVssBackupComponents.ahk" {IVssBackupComponents}
#Import export ".\IVssBackupComponentsEx.ahk" {IVssBackupComponentsEx}
#Import export ".\IVssBackupComponentsEx2.ahk" {IVssBackupComponentsEx2}
#Import export ".\IVssBackupComponentsEx3.ahk" {IVssBackupComponentsEx3}
#Import export ".\IVssBackupComponentsEx4.ahk" {IVssBackupComponentsEx4}
#Import export ".\IVssComponent.ahk" {IVssComponent}
#Import export ".\IVssComponentEx.ahk" {IVssComponentEx}
#Import export ".\IVssComponentEx2.ahk" {IVssComponentEx2}
#Import export ".\IVssCreateExpressWriterMetadata.ahk" {IVssCreateExpressWriterMetadata}
#Import export ".\IVssCreateWriterMetadata.ahk" {IVssCreateWriterMetadata}
#Import export ".\IVssDifferentialSoftwareSnapshotMgmt.ahk" {IVssDifferentialSoftwareSnapshotMgmt}
#Import export ".\IVssDifferentialSoftwareSnapshotMgmt2.ahk" {IVssDifferentialSoftwareSnapshotMgmt2}
#Import export ".\IVssDifferentialSoftwareSnapshotMgmt3.ahk" {IVssDifferentialSoftwareSnapshotMgmt3}
#Import export ".\IVssEnumMgmtObject.ahk" {IVssEnumMgmtObject}
#Import export ".\IVssEnumObject.ahk" {IVssEnumObject}
#Import export ".\IVssExamineWriterMetadata.ahk" {IVssExamineWriterMetadata}
#Import export ".\IVssExamineWriterMetadataEx.ahk" {IVssExamineWriterMetadataEx}
#Import export ".\IVssExamineWriterMetadataEx2.ahk" {IVssExamineWriterMetadataEx2}
#Import export ".\IVssExpressWriter.ahk" {IVssExpressWriter}
#Import export ".\IVssFileShareSnapshotProvider.ahk" {IVssFileShareSnapshotProvider}
#Import export ".\IVssHardwareSnapshotProvider.ahk" {IVssHardwareSnapshotProvider}
#Import export ".\IVssHardwareSnapshotProviderEx.ahk" {IVssHardwareSnapshotProviderEx}
#Import export ".\IVssProviderCreateSnapshotSet.ahk" {IVssProviderCreateSnapshotSet}
#Import export ".\IVssProviderNotifications.ahk" {IVssProviderNotifications}
#Import export ".\IVssSnapshotMgmt.ahk" {IVssSnapshotMgmt}
#Import export ".\IVssSnapshotMgmt2.ahk" {IVssSnapshotMgmt2}
#Import export ".\IVssSoftwareSnapshotProvider.ahk" {IVssSoftwareSnapshotProvider}
#Import export ".\IVssWMComponent.ahk" {IVssWMComponent}
#Import export ".\IVssWMDependency.ahk" {IVssWMDependency}
#Import export ".\IVssWMFiledesc.ahk" {IVssWMFiledesc}
#Import export ".\IVssWriterComponents.ahk" {IVssWriterComponents}
#Import export ".\IVssWriterComponentsExt.ahk" {IVssWriterComponentsExt}
#Import export ".\VSSCoordinator.ahk" {VSSCoordinator}
#Import export ".\VSS_ALTERNATE_WRITER_STATE.ahk" {VSS_ALTERNATE_WRITER_STATE}
#Import export ".\VSS_APPLICATION_LEVEL.ahk" {VSS_APPLICATION_LEVEL}
#Import export ".\VSS_BACKUP_SCHEMA.ahk" {VSS_BACKUP_SCHEMA}
#Import export ".\VSS_BACKUP_TYPE.ahk" {VSS_BACKUP_TYPE}
#Import export ".\VSS_COMPONENTINFO.ahk" {VSS_COMPONENTINFO}
#Import export ".\VSS_COMPONENT_FLAGS.ahk" {VSS_COMPONENT_FLAGS}
#Import export ".\VSS_COMPONENT_TYPE.ahk" {VSS_COMPONENT_TYPE}
#Import export ".\VSS_DIFF_AREA_PROP.ahk" {VSS_DIFF_AREA_PROP}
#Import export ".\VSS_DIFF_VOLUME_PROP.ahk" {VSS_DIFF_VOLUME_PROP}
#Import export ".\VSS_FILE_RESTORE_STATUS.ahk" {VSS_FILE_RESTORE_STATUS}
#Import export ".\VSS_FILE_SPEC_BACKUP_TYPE.ahk" {VSS_FILE_SPEC_BACKUP_TYPE}
#Import export ".\VSS_HARDWARE_OPTIONS.ahk" {VSS_HARDWARE_OPTIONS}
#Import export ".\VSS_MGMT_OBJECT_PROP.ahk" {VSS_MGMT_OBJECT_PROP}
#Import export ".\VSS_MGMT_OBJECT_TYPE.ahk" {VSS_MGMT_OBJECT_TYPE}
#Import export ".\VSS_MGMT_OBJECT_UNION.ahk" {VSS_MGMT_OBJECT_UNION}
#Import export ".\VSS_OBJECT_PROP.ahk" {VSS_OBJECT_PROP}
#Import export ".\VSS_OBJECT_TYPE.ahk" {VSS_OBJECT_TYPE}
#Import export ".\VSS_OBJECT_UNION.ahk" {VSS_OBJECT_UNION}
#Import export ".\VSS_PROTECTION_FAULT.ahk" {VSS_PROTECTION_FAULT}
#Import export ".\VSS_PROTECTION_LEVEL.ahk" {VSS_PROTECTION_LEVEL}
#Import export ".\VSS_PROVIDER_CAPABILITIES.ahk" {VSS_PROVIDER_CAPABILITIES}
#Import export ".\VSS_PROVIDER_PROP.ahk" {VSS_PROVIDER_PROP}
#Import export ".\VSS_PROVIDER_TYPE.ahk" {VSS_PROVIDER_TYPE}
#Import export ".\VSS_RECOVERY_OPTIONS.ahk" {VSS_RECOVERY_OPTIONS}
#Import export ".\VSS_RESTOREMETHOD_ENUM.ahk" {VSS_RESTOREMETHOD_ENUM}
#Import export ".\VSS_RESTORE_TARGET.ahk" {VSS_RESTORE_TARGET}
#Import export ".\VSS_RESTORE_TYPE.ahk" {VSS_RESTORE_TYPE}
#Import export ".\VSS_ROLLFORWARD_TYPE.ahk" {VSS_ROLLFORWARD_TYPE}
#Import export ".\VSS_SNAPSHOT_COMPATIBILITY.ahk" {VSS_SNAPSHOT_COMPATIBILITY}
#Import export ".\VSS_SNAPSHOT_CONTEXT.ahk" {VSS_SNAPSHOT_CONTEXT}
#Import export ".\VSS_SNAPSHOT_PROP.ahk" {VSS_SNAPSHOT_PROP}
#Import export ".\VSS_SNAPSHOT_PROPERTY_ID.ahk" {VSS_SNAPSHOT_PROPERTY_ID}
#Import export ".\VSS_SNAPSHOT_STATE.ahk" {VSS_SNAPSHOT_STATE}
#Import export ".\VSS_SOURCE_TYPE.ahk" {VSS_SOURCE_TYPE}
#Import export ".\VSS_SUBSCRIBE_MASK.ahk" {VSS_SUBSCRIBE_MASK}
#Import export ".\VSS_USAGE_TYPE.ahk" {VSS_USAGE_TYPE}
#Import export ".\VSS_VOLUME_PROP.ahk" {VSS_VOLUME_PROP}
#Import export ".\VSS_VOLUME_PROTECTION_INFO.ahk" {VSS_VOLUME_PROTECTION_INFO}
#Import export ".\VSS_VOLUME_SNAPSHOT_ATTRIBUTES.ahk" {VSS_VOLUME_SNAPSHOT_ATTRIBUTES}
#Import export ".\VSS_WRITERRESTORE_ENUM.ahk" {VSS_WRITERRESTORE_ENUM}
#Import export ".\VSS_WRITER_STATE.ahk" {VSS_WRITER_STATE}
#Import export ".\VssSnapshotMgmt.ahk" {VssSnapshotMgmt}
