#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\..\System\Com\IUnknown.ahk

/**
 * Contains methods that allow applications to query and manage shadow copy storage areas generated by the system shadow copy provider.
 * @see https://docs.microsoft.com/windows/win32/api//vsmgmt/nn-vsmgmt-ivssdifferentialsoftwaresnapshotmgmt
 * @namespace Windows.Win32.Storage.Vss
 * @version v4.0.30319
 */
class IVssDifferentialSoftwareSnapshotMgmt extends IUnknown{
    /**
     * The interface identifier for IVssDifferentialSoftwareSnapshotMgmt
     * @type {Guid}
     */
    static IID => Guid("{214a0f28-b737-4026-b847-4f9e37d79529}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 3

    /**
     * 
     * @param {Pointer<UInt16>} pwszVolumeName 
     * @param {Pointer<UInt16>} pwszDiffAreaVolumeName 
     * @param {Integer} llMaximumDiffSpace 
     * @returns {HRESULT} 
     */
    AddDiffArea(pwszVolumeName, pwszDiffAreaVolumeName, llMaximumDiffSpace) {
        result := ComCall(3, this, "ushort*", pwszVolumeName, "ushort*", pwszDiffAreaVolumeName, "int64", llMaximumDiffSpace, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<UInt16>} pwszVolumeName 
     * @param {Pointer<UInt16>} pwszDiffAreaVolumeName 
     * @param {Integer} llMaximumDiffSpace 
     * @returns {HRESULT} 
     */
    ChangeDiffAreaMaximumSize(pwszVolumeName, pwszDiffAreaVolumeName, llMaximumDiffSpace) {
        result := ComCall(4, this, "ushort*", pwszVolumeName, "ushort*", pwszDiffAreaVolumeName, "int64", llMaximumDiffSpace, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<UInt16>} pwszOriginalVolumeName 
     * @param {Pointer<IVssEnumMgmtObject>} ppEnum 
     * @returns {HRESULT} 
     */
    QueryVolumesSupportedForDiffAreas(pwszOriginalVolumeName, ppEnum) {
        result := ComCall(5, this, "ushort*", pwszOriginalVolumeName, "ptr", ppEnum, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<UInt16>} pwszVolumeName 
     * @param {Pointer<IVssEnumMgmtObject>} ppEnum 
     * @returns {HRESULT} 
     */
    QueryDiffAreasForVolume(pwszVolumeName, ppEnum) {
        result := ComCall(6, this, "ushort*", pwszVolumeName, "ptr", ppEnum, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<UInt16>} pwszVolumeName 
     * @param {Pointer<IVssEnumMgmtObject>} ppEnum 
     * @returns {HRESULT} 
     */
    QueryDiffAreasOnVolume(pwszVolumeName, ppEnum) {
        result := ComCall(7, this, "ushort*", pwszVolumeName, "ptr", ppEnum, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<Guid>} SnapshotId 
     * @param {Pointer<IVssEnumMgmtObject>} ppEnum 
     * @returns {HRESULT} 
     */
    QueryDiffAreasForSnapshot(SnapshotId, ppEnum) {
        result := ComCall(8, this, "ptr", SnapshotId, "ptr", ppEnum, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }
}
