#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include .\IVssDifferentialSoftwareSnapshotMgmt.ahk

/**
 * Defines additional methods that allow applications to query and manage shadow copy storage areas generated by the system shadow copy provider.
 * @see https://docs.microsoft.com/windows/win32/api//vsmgmt/nn-vsmgmt-ivssdifferentialsoftwaresnapshotmgmt2
 * @namespace Windows.Win32.Storage.Vss
 * @version v4.0.30319
 */
class IVssDifferentialSoftwareSnapshotMgmt2 extends IVssDifferentialSoftwareSnapshotMgmt{
    /**
     * The interface identifier for IVssDifferentialSoftwareSnapshotMgmt2
     * @type {Guid}
     */
    static IID => Guid("{949d7353-675f-4275-8969-f044c6277815}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 9

    /**
     * 
     * @param {Pointer<UInt16>} pwszVolumeName 
     * @param {Pointer<UInt16>} pwszDiffAreaVolumeName 
     * @param {Integer} llMaximumDiffSpace 
     * @param {BOOL} bVolatile 
     * @returns {HRESULT} 
     */
    ChangeDiffAreaMaximumSizeEx(pwszVolumeName, pwszDiffAreaVolumeName, llMaximumDiffSpace, bVolatile) {
        result := ComCall(9, this, "ushort*", pwszVolumeName, "ushort*", pwszDiffAreaVolumeName, "int64", llMaximumDiffSpace, "int", bVolatile, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<UInt16>} pwszVolumeName 
     * @param {Pointer<UInt16>} pwszDiffAreaVolumeName 
     * @param {Pointer<UInt16>} pwszNewDiffAreaVolumeName 
     * @returns {HRESULT} 
     */
    MigrateDiffAreas(pwszVolumeName, pwszDiffAreaVolumeName, pwszNewDiffAreaVolumeName) {
        result := ComCall(10, this, "ushort*", pwszVolumeName, "ushort*", pwszDiffAreaVolumeName, "ushort*", pwszNewDiffAreaVolumeName, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<UInt16>} pwszVolumeName 
     * @param {Pointer<UInt16>} pwszDiffAreaVolumeName 
     * @param {Pointer<IVssAsync>} ppAsync 
     * @returns {HRESULT} 
     */
    QueryMigrationStatus(pwszVolumeName, pwszDiffAreaVolumeName, ppAsync) {
        result := ComCall(11, this, "ushort*", pwszVolumeName, "ushort*", pwszDiffAreaVolumeName, "ptr", ppAsync, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<Guid>} idSnapshot 
     * @param {Integer} priority 
     * @returns {HRESULT} 
     */
    SetSnapshotPriority(idSnapshot, priority) {
        result := ComCall(12, this, "ptr", idSnapshot, "char", priority, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }
}
