#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\APPX_BUNDLE_FOOTPRINT_FILE_TYPE.ahk" {APPX_BUNDLE_FOOTPRINT_FILE_TYPE}
#Import export ".\APPX_BUNDLE_PAYLOAD_PACKAGE_TYPE.ahk" {APPX_BUNDLE_PAYLOAD_PACKAGE_TYPE}
#Import export ".\APPX_CAPABILITIES.ahk" {APPX_CAPABILITIES}
#Import export ".\APPX_CAPABILITY_CLASS_TYPE.ahk" {APPX_CAPABILITY_CLASS_TYPE}
#Import export ".\APPX_COMPRESSION_OPTION.ahk" {APPX_COMPRESSION_OPTION}
#Import export ".\APPX_ENCRYPTED_EXEMPTIONS.ahk" {APPX_ENCRYPTED_EXEMPTIONS}
#Import export ".\APPX_ENCRYPTED_PACKAGE_OPTIONS.ahk" {APPX_ENCRYPTED_PACKAGE_OPTIONS}
#Import export ".\APPX_ENCRYPTED_PACKAGE_SETTINGS.ahk" {APPX_ENCRYPTED_PACKAGE_SETTINGS}
#Import export ".\APPX_ENCRYPTED_PACKAGE_SETTINGS2.ahk" {APPX_ENCRYPTED_PACKAGE_SETTINGS2}
#Import export ".\APPX_FOOTPRINT_FILE_TYPE.ahk" {APPX_FOOTPRINT_FILE_TYPE}
#Import export ".\APPX_KEY_INFO.ahk" {APPX_KEY_INFO}
#Import export ".\APPX_PACKAGE_ARCHITECTURE.ahk" {APPX_PACKAGE_ARCHITECTURE}
#Import export ".\APPX_PACKAGE_ARCHITECTURE2.ahk" {APPX_PACKAGE_ARCHITECTURE2}
#Import export ".\APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTIONS.ahk" {APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_MANIFEST_OPTIONS}
#Import export ".\APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_OPTION.ahk" {APPX_PACKAGE_EDITOR_UPDATE_PACKAGE_OPTION}
#Import export ".\APPX_PACKAGE_SETTINGS.ahk" {APPX_PACKAGE_SETTINGS}
#Import export ".\APPX_PACKAGE_WRITER_PAYLOAD_STREAM.ahk" {APPX_PACKAGE_WRITER_PAYLOAD_STREAM}
#Import export ".\APPX_PACKAGING_CONTEXT_CHANGE_TYPE.ahk" {APPX_PACKAGING_CONTEXT_CHANGE_TYPE}
#Import export ".\AddPackageDependencyOptions.ahk" {AddPackageDependencyOptions}
#Import export ".\AddPackageDependencyOptions2.ahk" {AddPackageDependencyOptions2}
#Import export ".\Apis.ahk" {*}
#Import export ".\AppPolicyClrCompat.ahk" {AppPolicyClrCompat}
#Import export ".\AppPolicyCreateFileAccess.ahk" {AppPolicyCreateFileAccess}
#Import export ".\AppPolicyLifecycleManagement.ahk" {AppPolicyLifecycleManagement}
#Import export ".\AppPolicyMediaFoundationCodecLoading.ahk" {AppPolicyMediaFoundationCodecLoading}
#Import export ".\AppPolicyProcessTerminationMethod.ahk" {AppPolicyProcessTerminationMethod}
#Import export ".\AppPolicyShowDeveloperDiagnostic.ahk" {AppPolicyShowDeveloperDiagnostic}
#Import export ".\AppPolicyThreadInitializationType.ahk" {AppPolicyThreadInitializationType}
#Import export ".\AppPolicyWindowingModel.ahk" {AppPolicyWindowingModel}
#Import export ".\AppxBundleFactory.ahk" {AppxBundleFactory}
#Import export ".\AppxEncryptionFactory.ahk" {AppxEncryptionFactory}
#Import export ".\AppxFactory.ahk" {AppxFactory}
#Import export ".\AppxPackageEditor.ahk" {AppxPackageEditor}
#Import export ".\AppxPackagingDiagnosticEventSinkManager.ahk" {AppxPackagingDiagnosticEventSinkManager}
#Import export ".\AppxPackagingServiceProvider.ahk" {AppxPackagingServiceProvider}
#Import export ".\Constants.ahk" {*}
#Import export ".\CreatePackageDependencyOptions.ahk" {CreatePackageDependencyOptions}
#Import export ".\DX_FEATURE_LEVEL.ahk" {DX_FEATURE_LEVEL}
#Import export ".\FindPackageDependencyCriteria.ahk" {FindPackageDependencyCriteria}
#Import export ".\IAppxAppInstallerReader.ahk" {IAppxAppInstallerReader}
#Import export ".\IAppxBlockMapBlock.ahk" {IAppxBlockMapBlock}
#Import export ".\IAppxBlockMapBlocksEnumerator.ahk" {IAppxBlockMapBlocksEnumerator}
#Import export ".\IAppxBlockMapFile.ahk" {IAppxBlockMapFile}
#Import export ".\IAppxBlockMapFile2.ahk" {IAppxBlockMapFile2}
#Import export ".\IAppxBlockMapFilesEnumerator.ahk" {IAppxBlockMapFilesEnumerator}
#Import export ".\IAppxBlockMapReader.ahk" {IAppxBlockMapReader}
#Import export ".\IAppxBundleFactory.ahk" {IAppxBundleFactory}
#Import export ".\IAppxBundleFactory2.ahk" {IAppxBundleFactory2}
#Import export ".\IAppxBundleFactory3.ahk" {IAppxBundleFactory3}
#Import export ".\IAppxBundleManifestOptionalBundleInfo.ahk" {IAppxBundleManifestOptionalBundleInfo}
#Import export ".\IAppxBundleManifestOptionalBundleInfoEnumerator.ahk" {IAppxBundleManifestOptionalBundleInfoEnumerator}
#Import export ".\IAppxBundleManifestPackageInfo.ahk" {IAppxBundleManifestPackageInfo}
#Import export ".\IAppxBundleManifestPackageInfo2.ahk" {IAppxBundleManifestPackageInfo2}
#Import export ".\IAppxBundleManifestPackageInfo3.ahk" {IAppxBundleManifestPackageInfo3}
#Import export ".\IAppxBundleManifestPackageInfo4.ahk" {IAppxBundleManifestPackageInfo4}
#Import export ".\IAppxBundleManifestPackageInfoEnumerator.ahk" {IAppxBundleManifestPackageInfoEnumerator}
#Import export ".\IAppxBundleManifestReader.ahk" {IAppxBundleManifestReader}
#Import export ".\IAppxBundleManifestReader2.ahk" {IAppxBundleManifestReader2}
#Import export ".\IAppxBundleReader.ahk" {IAppxBundleReader}
#Import export ".\IAppxBundleReader2.ahk" {IAppxBundleReader2}
#Import export ".\IAppxBundleWriter.ahk" {IAppxBundleWriter}
#Import export ".\IAppxBundleWriter2.ahk" {IAppxBundleWriter2}
#Import export ".\IAppxBundleWriter3.ahk" {IAppxBundleWriter3}
#Import export ".\IAppxBundleWriter4.ahk" {IAppxBundleWriter4}
#Import export ".\IAppxContentGroup.ahk" {IAppxContentGroup}
#Import export ".\IAppxContentGroupFilesEnumerator.ahk" {IAppxContentGroupFilesEnumerator}
#Import export ".\IAppxContentGroupMapReader.ahk" {IAppxContentGroupMapReader}
#Import export ".\IAppxContentGroupMapWriter.ahk" {IAppxContentGroupMapWriter}
#Import export ".\IAppxContentGroupsEnumerator.ahk" {IAppxContentGroupsEnumerator}
#Import export ".\IAppxDigestProvider.ahk" {IAppxDigestProvider}
#Import export ".\IAppxEncryptedBundleWriter.ahk" {IAppxEncryptedBundleWriter}
#Import export ".\IAppxEncryptedBundleWriter2.ahk" {IAppxEncryptedBundleWriter2}
#Import export ".\IAppxEncryptedBundleWriter3.ahk" {IAppxEncryptedBundleWriter3}
#Import export ".\IAppxEncryptedPackageWriter.ahk" {IAppxEncryptedPackageWriter}
#Import export ".\IAppxEncryptedPackageWriter2.ahk" {IAppxEncryptedPackageWriter2}
#Import export ".\IAppxEncryptionFactory.ahk" {IAppxEncryptionFactory}
#Import export ".\IAppxEncryptionFactory2.ahk" {IAppxEncryptionFactory2}
#Import export ".\IAppxEncryptionFactory3.ahk" {IAppxEncryptionFactory3}
#Import export ".\IAppxEncryptionFactory4.ahk" {IAppxEncryptionFactory4}
#Import export ".\IAppxEncryptionFactory5.ahk" {IAppxEncryptionFactory5}
#Import export ".\IAppxFactory.ahk" {IAppxFactory}
#Import export ".\IAppxFactory2.ahk" {IAppxFactory2}
#Import export ".\IAppxFactory3.ahk" {IAppxFactory3}
#Import export ".\IAppxFactory4.ahk" {IAppxFactory4}
#Import export ".\IAppxFile.ahk" {IAppxFile}
#Import export ".\IAppxFile2.ahk" {IAppxFile2}
#Import export ".\IAppxFilesEnumerator.ahk" {IAppxFilesEnumerator}
#Import export ".\IAppxManifestApplication.ahk" {IAppxManifestApplication}
#Import export ".\IAppxManifestApplicationsEnumerator.ahk" {IAppxManifestApplicationsEnumerator}
#Import export ".\IAppxManifestCapabilitiesEnumerator.ahk" {IAppxManifestCapabilitiesEnumerator}
#Import export ".\IAppxManifestDeviceCapabilitiesEnumerator.ahk" {IAppxManifestDeviceCapabilitiesEnumerator}
#Import export ".\IAppxManifestDriverConstraint.ahk" {IAppxManifestDriverConstraint}
#Import export ".\IAppxManifestDriverConstraintsEnumerator.ahk" {IAppxManifestDriverConstraintsEnumerator}
#Import export ".\IAppxManifestDriverDependenciesEnumerator.ahk" {IAppxManifestDriverDependenciesEnumerator}
#Import export ".\IAppxManifestDriverDependency.ahk" {IAppxManifestDriverDependency}
#Import export ".\IAppxManifestHostRuntimeDependenciesEnumerator.ahk" {IAppxManifestHostRuntimeDependenciesEnumerator}
#Import export ".\IAppxManifestHostRuntimeDependency.ahk" {IAppxManifestHostRuntimeDependency}
#Import export ".\IAppxManifestHostRuntimeDependency2.ahk" {IAppxManifestHostRuntimeDependency2}
#Import export ".\IAppxManifestMainPackageDependenciesEnumerator.ahk" {IAppxManifestMainPackageDependenciesEnumerator}
#Import export ".\IAppxManifestMainPackageDependency.ahk" {IAppxManifestMainPackageDependency}
#Import export ".\IAppxManifestOSPackageDependenciesEnumerator.ahk" {IAppxManifestOSPackageDependenciesEnumerator}
#Import export ".\IAppxManifestOSPackageDependency.ahk" {IAppxManifestOSPackageDependency}
#Import export ".\IAppxManifestOptionalPackageInfo.ahk" {IAppxManifestOptionalPackageInfo}
#Import export ".\IAppxManifestPackageDependenciesEnumerator.ahk" {IAppxManifestPackageDependenciesEnumerator}
#Import export ".\IAppxManifestPackageDependency.ahk" {IAppxManifestPackageDependency}
#Import export ".\IAppxManifestPackageDependency2.ahk" {IAppxManifestPackageDependency2}
#Import export ".\IAppxManifestPackageDependency3.ahk" {IAppxManifestPackageDependency3}
#Import export ".\IAppxManifestPackageId.ahk" {IAppxManifestPackageId}
#Import export ".\IAppxManifestPackageId2.ahk" {IAppxManifestPackageId2}
#Import export ".\IAppxManifestProperties.ahk" {IAppxManifestProperties}
#Import export ".\IAppxManifestQualifiedResource.ahk" {IAppxManifestQualifiedResource}
#Import export ".\IAppxManifestQualifiedResourcesEnumerator.ahk" {IAppxManifestQualifiedResourcesEnumerator}
#Import export ".\IAppxManifestReader.ahk" {IAppxManifestReader}
#Import export ".\IAppxManifestReader2.ahk" {IAppxManifestReader2}
#Import export ".\IAppxManifestReader3.ahk" {IAppxManifestReader3}
#Import export ".\IAppxManifestReader4.ahk" {IAppxManifestReader4}
#Import export ".\IAppxManifestReader5.ahk" {IAppxManifestReader5}
#Import export ".\IAppxManifestReader6.ahk" {IAppxManifestReader6}
#Import export ".\IAppxManifestReader7.ahk" {IAppxManifestReader7}
#Import export ".\IAppxManifestResourcesEnumerator.ahk" {IAppxManifestResourcesEnumerator}
#Import export ".\IAppxManifestTargetDeviceFamiliesEnumerator.ahk" {IAppxManifestTargetDeviceFamiliesEnumerator}
#Import export ".\IAppxManifestTargetDeviceFamily.ahk" {IAppxManifestTargetDeviceFamily}
#Import export ".\IAppxPackageEditor.ahk" {IAppxPackageEditor}
#Import export ".\IAppxPackageReader.ahk" {IAppxPackageReader}
#Import export ".\IAppxPackageWriter.ahk" {IAppxPackageWriter}
#Import export ".\IAppxPackageWriter2.ahk" {IAppxPackageWriter2}
#Import export ".\IAppxPackageWriter3.ahk" {IAppxPackageWriter3}
#Import export ".\IAppxPackagingDiagnosticEventSink.ahk" {IAppxPackagingDiagnosticEventSink}
#Import export ".\IAppxPackagingDiagnosticEventSinkManager.ahk" {IAppxPackagingDiagnosticEventSinkManager}
#Import export ".\IAppxSourceContentGroupMapReader.ahk" {IAppxSourceContentGroupMapReader}
#Import export ".\PACKAGEDEPENDENCY_CONTEXT.ahk" {PACKAGEDEPENDENCY_CONTEXT}
#Import export ".\PACKAGE_ID.ahk" {PACKAGE_ID}
#Import export ".\PACKAGE_INFO.ahk" {PACKAGE_INFO}
#Import export ".\PACKAGE_VERSION.ahk" {PACKAGE_VERSION}
#Import export ".\PACKAGE_VIRTUALIZATION_CONTEXT_HANDLE.ahk" {PACKAGE_VIRTUALIZATION_CONTEXT_HANDLE}
#Import export ".\PackageDependencyLifetimeKind.ahk" {PackageDependencyLifetimeKind}
#Import export ".\PackageDependencyProcessorArchitectures.ahk" {PackageDependencyProcessorArchitectures}
#Import export ".\PackageInfo3Type.ahk" {PackageInfo3Type}
#Import export ".\PackageOrigin.ahk" {PackageOrigin}
#Import export ".\PackagePathType.ahk" {PackagePathType}
#Import export ".\_PACKAGE_INFO_REFERENCE.ahk" {_PACKAGE_INFO_REFERENCE}
