#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\HardwareCounterProfiling\__Init.ahk" {*}
#Import export ".\Apis.ahk" {*}
#Import export ".\AppearPropPage.ahk" {AppearPropPage}
#Import export ".\AutoPathFormat.ahk" {AutoPathFormat}
#Import export ".\BootTraceSession.ahk" {BootTraceSession}
#Import export ".\BootTraceSessionCollection.ahk" {BootTraceSessionCollection}
#Import export ".\ClockType.ahk" {ClockType}
#Import export ".\CommitMode.ahk" {CommitMode}
#Import export ".\Constants.ahk" {*}
#Import export ".\CounterItem.ahk" {CounterItem}
#Import export ".\CounterItem2.ahk" {CounterItem2}
#Import export ".\CounterPathCallBack.ahk" {CounterPathCallBack}
#Import export ".\CounterPropPage.ahk" {CounterPropPage}
#Import export ".\Counters.ahk" {Counters}
#Import export ".\DICounterItem.ahk" {DICounterItem}
#Import export ".\DILogFileItem.ahk" {DILogFileItem}
#Import export ".\DISystemMonitor.ahk" {DISystemMonitor}
#Import export ".\DISystemMonitorEvents.ahk" {DISystemMonitorEvents}
#Import export ".\DISystemMonitorInternal.ahk" {DISystemMonitorInternal}
#Import export ".\DataCollectorSet.ahk" {DataCollectorSet}
#Import export ".\DataCollectorSetCollection.ahk" {DataCollectorSetCollection}
#Import export ".\DataCollectorSetStatus.ahk" {DataCollectorSetStatus}
#Import export ".\DataCollectorType.ahk" {DataCollectorType}
#Import export ".\DataManagerSteps.ahk" {DataManagerSteps}
#Import export ".\DataSourceTypeConstants.ahk" {DataSourceTypeConstants}
#Import export ".\DisplayTypeConstants.ahk" {DisplayTypeConstants}
#Import export ".\FileFormat.ahk" {FileFormat}
#Import export ".\FolderActionSteps.ahk" {FolderActionSteps}
#Import export ".\GeneralPropPage.ahk" {GeneralPropPage}
#Import export ".\GraphPropPage.ahk" {GraphPropPage}
#Import export ".\IAlertDataCollector.ahk" {IAlertDataCollector}
#Import export ".\IApiTracingDataCollector.ahk" {IApiTracingDataCollector}
#Import export ".\IConfigurationDataCollector.ahk" {IConfigurationDataCollector}
#Import export ".\ICounterItem.ahk" {ICounterItem}
#Import export ".\ICounterItem2.ahk" {ICounterItem2}
#Import export ".\ICounters.ahk" {ICounters}
#Import export ".\IDataCollector.ahk" {IDataCollector}
#Import export ".\IDataCollectorCollection.ahk" {IDataCollectorCollection}
#Import export ".\IDataCollectorSet.ahk" {IDataCollectorSet}
#Import export ".\IDataCollectorSetCollection.ahk" {IDataCollectorSetCollection}
#Import export ".\IDataManager.ahk" {IDataManager}
#Import export ".\IFolderAction.ahk" {IFolderAction}
#Import export ".\IFolderActionCollection.ahk" {IFolderActionCollection}
#Import export ".\ILogFileItem.ahk" {ILogFileItem}
#Import export ".\ILogFiles.ahk" {ILogFiles}
#Import export ".\IPerformanceCounterDataCollector.ahk" {IPerformanceCounterDataCollector}
#Import export ".\ISchedule.ahk" {ISchedule}
#Import export ".\IScheduleCollection.ahk" {IScheduleCollection}
#Import export ".\ISystemMonitor.ahk" {ISystemMonitor}
#Import export ".\ISystemMonitor2.ahk" {ISystemMonitor2}
#Import export ".\ISystemMonitorEvents.ahk" {ISystemMonitorEvents}
#Import export ".\ITraceDataCollector.ahk" {ITraceDataCollector}
#Import export ".\ITraceDataProvider.ahk" {ITraceDataProvider}
#Import export ".\ITraceDataProviderCollection.ahk" {ITraceDataProviderCollection}
#Import export ".\IValueMap.ahk" {IValueMap}
#Import export ".\IValueMapItem.ahk" {IValueMapItem}
#Import export ".\LegacyDataCollectorSet.ahk" {LegacyDataCollectorSet}
#Import export ".\LegacyDataCollectorSetCollection.ahk" {LegacyDataCollectorSetCollection}
#Import export ".\LegacyTraceSession.ahk" {LegacyTraceSession}
#Import export ".\LegacyTraceSessionCollection.ahk" {LegacyTraceSessionCollection}
#Import export ".\LogFileItem.ahk" {LogFileItem}
#Import export ".\LogFiles.ahk" {LogFiles}
#Import export ".\PDH_BROWSE_DLG_CONFIG_A.ahk" {PDH_BROWSE_DLG_CONFIG_A}
#Import export ".\PDH_BROWSE_DLG_CONFIG_HA.ahk" {PDH_BROWSE_DLG_CONFIG_HA}
#Import export ".\PDH_BROWSE_DLG_CONFIG_HW.ahk" {PDH_BROWSE_DLG_CONFIG_HW}
#Import export ".\PDH_BROWSE_DLG_CONFIG_W.ahk" {PDH_BROWSE_DLG_CONFIG_W}
#Import export ".\PDH_COUNTER_INFO_A.ahk" {PDH_COUNTER_INFO_A}
#Import export ".\PDH_COUNTER_INFO_W.ahk" {PDH_COUNTER_INFO_W}
#Import export ".\PDH_COUNTER_PATH_ELEMENTS_A.ahk" {PDH_COUNTER_PATH_ELEMENTS_A}
#Import export ".\PDH_COUNTER_PATH_ELEMENTS_W.ahk" {PDH_COUNTER_PATH_ELEMENTS_W}
#Import export ".\PDH_DATA_ITEM_PATH_ELEMENTS_A.ahk" {PDH_DATA_ITEM_PATH_ELEMENTS_A}
#Import export ".\PDH_DATA_ITEM_PATH_ELEMENTS_W.ahk" {PDH_DATA_ITEM_PATH_ELEMENTS_W}
#Import export ".\PDH_DLL_VERSION.ahk" {PDH_DLL_VERSION}
#Import export ".\PDH_FMT.ahk" {PDH_FMT}
#Import export ".\PDH_FMT_COUNTERVALUE.ahk" {PDH_FMT_COUNTERVALUE}
#Import export ".\PDH_FMT_COUNTERVALUE_ITEM_A.ahk" {PDH_FMT_COUNTERVALUE_ITEM_A}
#Import export ".\PDH_FMT_COUNTERVALUE_ITEM_W.ahk" {PDH_FMT_COUNTERVALUE_ITEM_W}
#Import export ".\PDH_HCOUNTER.ahk" {PDH_HCOUNTER}
#Import export ".\PDH_HLOG.ahk" {PDH_HLOG}
#Import export ".\PDH_HQUERY.ahk" {PDH_HQUERY}
#Import export ".\PDH_LOG.ahk" {PDH_LOG}
#Import export ".\PDH_LOG_SERVICE_QUERY_INFO_A.ahk" {PDH_LOG_SERVICE_QUERY_INFO_A}
#Import export ".\PDH_LOG_SERVICE_QUERY_INFO_W.ahk" {PDH_LOG_SERVICE_QUERY_INFO_W}
#Import export ".\PDH_LOG_TYPE.ahk" {PDH_LOG_TYPE}
#Import export ".\PDH_PATH_FLAGS.ahk" {PDH_PATH_FLAGS}
#Import export ".\PDH_RAW_COUNTER.ahk" {PDH_RAW_COUNTER}
#Import export ".\PDH_RAW_COUNTER_ITEM_A.ahk" {PDH_RAW_COUNTER_ITEM_A}
#Import export ".\PDH_RAW_COUNTER_ITEM_W.ahk" {PDH_RAW_COUNTER_ITEM_W}
#Import export ".\PDH_RAW_LOG_RECORD.ahk" {PDH_RAW_LOG_RECORD}
#Import export ".\PDH_SELECT_DATA_SOURCE_FLAGS.ahk" {PDH_SELECT_DATA_SOURCE_FLAGS}
#Import export ".\PDH_STATISTICS.ahk" {PDH_STATISTICS}
#Import export ".\PDH_TIME_INFO.ahk" {PDH_TIME_INFO}
#Import export ".\PERFLIBREQUEST.ahk" {PERFLIBREQUEST}
#Import export ".\PERF_COUNTERSET_INFO.ahk" {PERF_COUNTERSET_INFO}
#Import export ".\PERF_COUNTERSET_INSTANCE.ahk" {PERF_COUNTERSET_INSTANCE}
#Import export ".\PERF_COUNTERSET_REG_INFO.ahk" {PERF_COUNTERSET_REG_INFO}
#Import export ".\PERF_COUNTER_AGGREGATE_FUNC.ahk" {PERF_COUNTER_AGGREGATE_FUNC}
#Import export ".\PERF_COUNTER_BLOCK.ahk" {PERF_COUNTER_BLOCK}
#Import export ".\PERF_COUNTER_DATA.ahk" {PERF_COUNTER_DATA}
#Import export ".\PERF_COUNTER_DEFINITION.ahk" {PERF_COUNTER_DEFINITION}
#Import export ".\PERF_COUNTER_HEADER.ahk" {PERF_COUNTER_HEADER}
#Import export ".\PERF_COUNTER_IDENTIFIER.ahk" {PERF_COUNTER_IDENTIFIER}
#Import export ".\PERF_COUNTER_IDENTITY.ahk" {PERF_COUNTER_IDENTITY}
#Import export ".\PERF_COUNTER_INFO.ahk" {PERF_COUNTER_INFO}
#Import export ".\PERF_COUNTER_REG_INFO.ahk" {PERF_COUNTER_REG_INFO}
#Import export ".\PERF_DATA_BLOCK.ahk" {PERF_DATA_BLOCK}
#Import export ".\PERF_DATA_HEADER.ahk" {PERF_DATA_HEADER}
#Import export ".\PERF_DETAIL.ahk" {PERF_DETAIL}
#Import export ".\PERF_INSTANCE_DEFINITION.ahk" {PERF_INSTANCE_DEFINITION}
#Import export ".\PERF_INSTANCE_HEADER.ahk" {PERF_INSTANCE_HEADER}
#Import export ".\PERF_MEM_ALLOC.ahk" {PERF_MEM_ALLOC}
#Import export ".\PERF_MEM_FREE.ahk" {PERF_MEM_FREE}
#Import export ".\PERF_MULTI_COUNTERS.ahk" {PERF_MULTI_COUNTERS}
#Import export ".\PERF_MULTI_INSTANCES.ahk" {PERF_MULTI_INSTANCES}
#Import export ".\PERF_OBJECT_TYPE.ahk" {PERF_OBJECT_TYPE}
#Import export ".\PERF_PROVIDER_CONTEXT.ahk" {PERF_PROVIDER_CONTEXT}
#Import export ".\PERF_STRING_BUFFER_HEADER.ahk" {PERF_STRING_BUFFER_HEADER}
#Import export ".\PERF_STRING_COUNTER_HEADER.ahk" {PERF_STRING_COUNTER_HEADER}
#Import export ".\PLA_CABEXTRACT_CALLBACK.ahk" {PLA_CABEXTRACT_CALLBACK}
#Import export ".\PM_CLOSE_PROC.ahk" {PM_CLOSE_PROC}
#Import export ".\PM_COLLECT_PROC.ahk" {PM_COLLECT_PROC}
#Import export ".\PM_OPEN_PROC.ahk" {PM_OPEN_PROC}
#Import export ".\PerfCounterDataType.ahk" {PerfCounterDataType}
#Import export ".\PerfRegInfoType.ahk" {PerfRegInfoType}
#Import export ".\REAL_TIME_DATA_SOURCE_ID_FLAGS.ahk" {REAL_TIME_DATA_SOURCE_ID_FLAGS}
#Import export ".\ReportValueTypeConstants.ahk" {ReportValueTypeConstants}
#Import export ".\ResourcePolicy.ahk" {ResourcePolicy}
#Import export ".\ServerDataCollectorSet.ahk" {ServerDataCollectorSet}
#Import export ".\ServerDataCollectorSetCollection.ahk" {ServerDataCollectorSetCollection}
#Import export ".\SourcePropPage.ahk" {SourcePropPage}
#Import export ".\StreamMode.ahk" {StreamMode}
#Import export ".\SysmonBatchReason.ahk" {SysmonBatchReason}
#Import export ".\SysmonDataType.ahk" {SysmonDataType}
#Import export ".\SysmonFileType.ahk" {SysmonFileType}
#Import export ".\SystemDataCollectorSet.ahk" {SystemDataCollectorSet}
#Import export ".\SystemDataCollectorSetCollection.ahk" {SystemDataCollectorSetCollection}
#Import export ".\SystemMonitor.ahk" {SystemMonitor}
#Import export ".\SystemMonitor2.ahk" {SystemMonitor2}
#Import export ".\TraceDataProvider.ahk" {TraceDataProvider}
#Import export ".\TraceDataProviderCollection.ahk" {TraceDataProviderCollection}
#Import export ".\TraceSession.ahk" {TraceSession}
#Import export ".\TraceSessionCollection.ahk" {TraceSessionCollection}
#Import export ".\ValueMapType.ahk" {ValueMapType}
#Import export ".\WeekDays.ahk" {WeekDays}
#Import export ".\_ICounterItemUnion.ahk" {_ICounterItemUnion}
#Import export ".\_ISystemMonitorUnion.ahk" {_ISystemMonitorUnion}
