#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\..\Foundation\BSTR.ahk
#Include ..\Com\IDispatch.ahk

/**
 * Manages data generated by the data collectors, including report generation, data retention policy, and data transfer.To get this interface, access the IDataCollectorSet::DataManager property.
 * @remarks
 * 
  * For an example that shows the XML that you can use to initialize this object if you call the <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/pla/nf-pla-idatacollectorset-setxml">IDataCollectorSet::SetXml</a> method, see the Remarks section of <a href="https://docs.microsoft.com/previous-versions/windows/desktop/api/pla/nn-pla-idatacollectorset">IDataCollectorSet</a>.  When you specify the XML to create the object, you can specify only the elements for the properties that you want to set. If you do not specify a property, PLA provides a default value. When you retrieve the XML for the set, the XML includes all elements.
  * 
 * @see https://docs.microsoft.com/windows/win32/api//pla/nn-pla-idatamanager
 * @namespace Windows.Win32.System.Performance
 * @version v4.0.30319
 */
class IDataManager extends IDispatch{
    /**
     * The interface identifier for IDataManager
     * @type {Guid}
     */
    static IID => Guid("{03837541-098b-11d8-9414-505054503030}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 7

    /**
     * 
     * @param {Pointer<VARIANT_BOOL>} pfEnabled 
     * @returns {HRESULT} 
     */
    get_Enabled(pfEnabled) {
        result := ComCall(7, this, "ptr", pfEnabled, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {VARIANT_BOOL} fEnabled 
     * @returns {HRESULT} 
     */
    put_Enabled(fEnabled) {
        result := ComCall(8, this, "short", fEnabled, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<VARIANT_BOOL>} pfCheck 
     * @returns {HRESULT} 
     */
    get_CheckBeforeRunning(pfCheck) {
        result := ComCall(9, this, "ptr", pfCheck, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {VARIANT_BOOL} fCheck 
     * @returns {HRESULT} 
     */
    put_CheckBeforeRunning(fCheck) {
        result := ComCall(10, this, "short", fCheck, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<UInt32>} MinFreeDisk 
     * @returns {HRESULT} 
     */
    get_MinFreeDisk(MinFreeDisk) {
        result := ComCall(11, this, "uint*", MinFreeDisk, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Integer} MinFreeDisk 
     * @returns {HRESULT} 
     */
    put_MinFreeDisk(MinFreeDisk) {
        result := ComCall(12, this, "uint", MinFreeDisk, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<UInt32>} pulMaxSize 
     * @returns {HRESULT} 
     */
    get_MaxSize(pulMaxSize) {
        result := ComCall(13, this, "uint*", pulMaxSize, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Integer} ulMaxSize 
     * @returns {HRESULT} 
     */
    put_MaxSize(ulMaxSize) {
        result := ComCall(14, this, "uint", ulMaxSize, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<UInt32>} pulMaxFolderCount 
     * @returns {HRESULT} 
     */
    get_MaxFolderCount(pulMaxFolderCount) {
        result := ComCall(15, this, "uint*", pulMaxFolderCount, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Integer} ulMaxFolderCount 
     * @returns {HRESULT} 
     */
    put_MaxFolderCount(ulMaxFolderCount) {
        result := ComCall(16, this, "uint", ulMaxFolderCount, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<Int32>} pPolicy 
     * @returns {HRESULT} 
     */
    get_ResourcePolicy(pPolicy) {
        result := ComCall(17, this, "int*", pPolicy, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Integer} Policy 
     * @returns {HRESULT} 
     */
    put_ResourcePolicy(Policy) {
        result := ComCall(18, this, "int", Policy, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<IFolderActionCollection>} Actions 
     * @returns {HRESULT} 
     */
    get_FolderActions(Actions) {
        result := ComCall(19, this, "ptr", Actions, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<BSTR>} ReportSchema 
     * @returns {HRESULT} 
     */
    get_ReportSchema(ReportSchema) {
        result := ComCall(20, this, "ptr", ReportSchema, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {BSTR} ReportSchema 
     * @returns {HRESULT} 
     */
    put_ReportSchema(ReportSchema) {
        ReportSchema := ReportSchema is String ? BSTR.Alloc(ReportSchema).Value : ReportSchema

        result := ComCall(21, this, "ptr", ReportSchema, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<BSTR>} pbstrFilename 
     * @returns {HRESULT} 
     */
    get_ReportFileName(pbstrFilename) {
        result := ComCall(22, this, "ptr", pbstrFilename, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {BSTR} pbstrFilename 
     * @returns {HRESULT} 
     */
    put_ReportFileName(pbstrFilename) {
        pbstrFilename := pbstrFilename is String ? BSTR.Alloc(pbstrFilename).Value : pbstrFilename

        result := ComCall(23, this, "ptr", pbstrFilename, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<BSTR>} Filename 
     * @returns {HRESULT} 
     */
    get_RuleTargetFileName(Filename) {
        result := ComCall(24, this, "ptr", Filename, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {BSTR} Filename 
     * @returns {HRESULT} 
     */
    put_RuleTargetFileName(Filename) {
        Filename := Filename is String ? BSTR.Alloc(Filename).Value : Filename

        result := ComCall(25, this, "ptr", Filename, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<BSTR>} pbstrFilename 
     * @returns {HRESULT} 
     */
    get_EventsFileName(pbstrFilename) {
        result := ComCall(26, this, "ptr", pbstrFilename, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {BSTR} pbstrFilename 
     * @returns {HRESULT} 
     */
    put_EventsFileName(pbstrFilename) {
        pbstrFilename := pbstrFilename is String ? BSTR.Alloc(pbstrFilename).Value : pbstrFilename

        result := ComCall(27, this, "ptr", pbstrFilename, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Pointer<BSTR>} pbstrXml 
     * @returns {HRESULT} 
     */
    get_Rules(pbstrXml) {
        result := ComCall(28, this, "ptr", pbstrXml, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {BSTR} bstrXml 
     * @returns {HRESULT} 
     */
    put_Rules(bstrXml) {
        bstrXml := bstrXml is String ? BSTR.Alloc(bstrXml).Value : bstrXml

        result := ComCall(29, this, "ptr", bstrXml, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {Integer} Steps 
     * @param {BSTR} bstrFolder 
     * @param {Pointer<IValueMap>} Errors 
     * @returns {HRESULT} 
     */
    Run(Steps, bstrFolder, Errors) {
        bstrFolder := bstrFolder is String ? BSTR.Alloc(bstrFolder).Value : bstrFolder

        result := ComCall(30, this, "int", Steps, "ptr", bstrFolder, "ptr", Errors, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }

    /**
     * 
     * @param {BSTR} CabFilename 
     * @param {BSTR} DestinationPath 
     * @returns {HRESULT} 
     */
    Extract(CabFilename, DestinationPath) {
        CabFilename := CabFilename is String ? BSTR.Alloc(CabFilename).Value : CabFilename
        DestinationPath := DestinationPath is String ? BSTR.Alloc(DestinationPath).Value : DestinationPath

        result := ComCall(31, this, "ptr", CabFilename, "ptr", DestinationPath, "int")
        if(result != 0)
            throw OSError(result)

        return result
    }
}
