#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\GameInput\__Init.ahk" {*}
#Import export ".\Ime\__Init.ahk" {*}
#Import export ".\Ink\__Init.ahk" {*}
#Import export ".\KeyboardAndMouse\__Init.ahk" {*}
#Import export ".\Pointer\__Init.ahk" {*}
#Import export ".\Radial\__Init.ahk" {*}
#Import export ".\Touch\__Init.ahk" {*}
#Import export ".\XboxController\__Init.ahk" {*}
#Import export ".\Apis.ahk" {*}
#Import export ".\HRAWINPUT.ahk" {HRAWINPUT}
#Import export ".\INPUT_MESSAGE_DEVICE_TYPE.ahk" {INPUT_MESSAGE_DEVICE_TYPE}
#Import export ".\INPUT_MESSAGE_ORIGIN_ID.ahk" {INPUT_MESSAGE_ORIGIN_ID}
#Import export ".\INPUT_MESSAGE_SOURCE.ahk" {INPUT_MESSAGE_SOURCE}
#Import export ".\MOUSE_STATE.ahk" {MOUSE_STATE}
#Import export ".\RAWHID.ahk" {RAWHID}
#Import export ".\RAWINPUT.ahk" {RAWINPUT}
#Import export ".\RAWINPUTDEVICE.ahk" {RAWINPUTDEVICE}
#Import export ".\RAWINPUTDEVICELIST.ahk" {RAWINPUTDEVICELIST}
#Import export ".\RAWINPUTDEVICE_FLAGS.ahk" {RAWINPUTDEVICE_FLAGS}
#Import export ".\RAWINPUTHEADER.ahk" {RAWINPUTHEADER}
#Import export ".\RAWKEYBOARD.ahk" {RAWKEYBOARD}
#Import export ".\RAWMOUSE.ahk" {RAWMOUSE}
#Import export ".\RAW_INPUT_DATA_COMMAND_FLAGS.ahk" {RAW_INPUT_DATA_COMMAND_FLAGS}
#Import export ".\RAW_INPUT_DEVICE_INFO_COMMAND.ahk" {RAW_INPUT_DEVICE_INFO_COMMAND}
#Import export ".\RID_DEVICE_INFO.ahk" {RID_DEVICE_INFO}
#Import export ".\RID_DEVICE_INFO_HID.ahk" {RID_DEVICE_INFO_HID}
#Import export ".\RID_DEVICE_INFO_KEYBOARD.ahk" {RID_DEVICE_INFO_KEYBOARD}
#Import export ".\RID_DEVICE_INFO_MOUSE.ahk" {RID_DEVICE_INFO_MOUSE}
#Import export ".\RID_DEVICE_INFO_TYPE.ahk" {RID_DEVICE_INFO_TYPE}
