#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\AudioReverb.ahk" {AudioReverb}
#Import export ".\AudioVolumeMeter.ahk" {AudioVolumeMeter}
#Import export ".\Constants.ahk" {*}
#Import export ".\FXECHO_INITDATA.ahk" {FXECHO_INITDATA}
#Import export ".\FXECHO_PARAMETERS.ahk" {FXECHO_PARAMETERS}
#Import export ".\FXEQ.ahk" {FXEQ}
#Import export ".\FXEQ_PARAMETERS.ahk" {FXEQ_PARAMETERS}
#Import export ".\FXEcho.ahk" {FXEcho}
#Import export ".\FXMASTERINGLIMITER_PARAMETERS.ahk" {FXMASTERINGLIMITER_PARAMETERS}
#Import export ".\FXMasteringLimiter.ahk" {FXMasteringLimiter}
#Import export ".\FXREVERB_PARAMETERS.ahk" {FXREVERB_PARAMETERS}
#Import export ".\FXReverb.ahk" {FXReverb}
#Import export ".\HrtfApoInit.ahk" {HrtfApoInit}
#Import export ".\HrtfDirectivity.ahk" {HrtfDirectivity}
#Import export ".\HrtfDirectivityCardioid.ahk" {HrtfDirectivityCardioid}
#Import export ".\HrtfDirectivityCone.ahk" {HrtfDirectivityCone}
#Import export ".\HrtfDirectivityType.ahk" {HrtfDirectivityType}
#Import export ".\HrtfDistanceDecay.ahk" {HrtfDistanceDecay}
#Import export ".\HrtfDistanceDecayType.ahk" {HrtfDistanceDecayType}
#Import export ".\HrtfEnvironment.ahk" {HrtfEnvironment}
#Import export ".\HrtfOrientation.ahk" {HrtfOrientation}
#Import export ".\HrtfPosition.ahk" {HrtfPosition}
#Import export ".\IXAPO.ahk" {IXAPO}
#Import export ".\IXAPOHrtfParameters.ahk" {IXAPOHrtfParameters}
#Import export ".\IXAPOParameters.ahk" {IXAPOParameters}
#Import export ".\IXAudio2.ahk" {IXAudio2}
#Import export ".\IXAudio2EngineCallback.ahk" {IXAudio2EngineCallback}
#Import export ".\IXAudio2Extension.ahk" {IXAudio2Extension}
#Import export ".\IXAudio2MasteringVoice.ahk" {IXAudio2MasteringVoice}
#Import export ".\IXAudio2SourceVoice.ahk" {IXAudio2SourceVoice}
#Import export ".\IXAudio2SubmixVoice.ahk" {IXAudio2SubmixVoice}
#Import export ".\IXAudio2Voice.ahk" {IXAudio2Voice}
#Import export ".\IXAudio2VoiceCallback.ahk" {IXAudio2VoiceCallback}
#Import export ".\XAPO_BUFFER_FLAGS.ahk" {XAPO_BUFFER_FLAGS}
#Import export ".\XAPO_LOCKFORPROCESS_PARAMETERS.ahk" {XAPO_LOCKFORPROCESS_PARAMETERS}
#Import export ".\XAPO_PROCESS_BUFFER_PARAMETERS.ahk" {XAPO_PROCESS_BUFFER_PARAMETERS}
#Import export ".\XAPO_REGISTRATION_PROPERTIES.ahk" {XAPO_REGISTRATION_PROPERTIES}
#Import export ".\XAUDIO2FX_REVERB_I3DL2_PARAMETERS.ahk" {XAUDIO2FX_REVERB_I3DL2_PARAMETERS}
#Import export ".\XAUDIO2FX_REVERB_PARAMETERS.ahk" {XAUDIO2FX_REVERB_PARAMETERS}
#Import export ".\XAUDIO2FX_VOLUMEMETER_LEVELS.ahk" {XAUDIO2FX_VOLUMEMETER_LEVELS}
#Import export ".\XAUDIO2_BUFFER.ahk" {XAUDIO2_BUFFER}
#Import export ".\XAUDIO2_BUFFER_WMA.ahk" {XAUDIO2_BUFFER_WMA}
#Import export ".\XAUDIO2_DEBUG_CONFIGURATION.ahk" {XAUDIO2_DEBUG_CONFIGURATION}
#Import export ".\XAUDIO2_EFFECT_CHAIN.ahk" {XAUDIO2_EFFECT_CHAIN}
#Import export ".\XAUDIO2_EFFECT_DESCRIPTOR.ahk" {XAUDIO2_EFFECT_DESCRIPTOR}
#Import export ".\XAUDIO2_FILTER_PARAMETERS.ahk" {XAUDIO2_FILTER_PARAMETERS}
#Import export ".\XAUDIO2_FILTER_TYPE.ahk" {XAUDIO2_FILTER_TYPE}
#Import export ".\XAUDIO2_PERFORMANCE_DATA.ahk" {XAUDIO2_PERFORMANCE_DATA}
#Import export ".\XAUDIO2_SEND_DESCRIPTOR.ahk" {XAUDIO2_SEND_DESCRIPTOR}
#Import export ".\XAUDIO2_VOICE_DETAILS.ahk" {XAUDIO2_VOICE_DETAILS}
#Import export ".\XAUDIO2_VOICE_SENDS.ahk" {XAUDIO2_VOICE_SENDS}
#Import export ".\XAUDIO2_VOICE_STATE.ahk" {XAUDIO2_VOICE_STATE}
