#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\WS_XML_WRITER_OUTPUT.ahk" { WS_XML_WRITER_OUTPUT }
#Import ".\WS_XML_WRITER_OUTPUT_TYPE.ahk" { WS_XML_WRITER_OUTPUT_TYPE }

/**
 * Specifies that the generated bytes should be sent to callback.
 * @see https://learn.microsoft.com/windows/win32/api/webservices/ns-webservices-ws_xml_writer_stream_output
 * @namespace Windows.Win32.Networking.WindowsWebServices
 */
export default struct WS_XML_WRITER_STREAM_OUTPUT {
    #StructPack 8

    /**
     * The base type for all types that derive from <a href="https://docs.microsoft.com/windows/desktop/api/webservices/ns-webservices-ws_xml_writer_output">WS_XML_WRITER_OUTPUT</a>.
     */
    output : WS_XML_WRITER_OUTPUT

    /**
     * A callback that will get invoked when <a href="https://docs.microsoft.com/windows/desktop/api/webservices/nf-webservices-wsflushwriter">WsFlushWriter</a> is called.  This may not be <b>NULL</b>.
     */
    writeCallback : IntPtr

    /**
     * User-defined data that will be passed to the writeCallback.
     */
    writeCallbackState : IntPtr

}
