#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE.ahk" {D2D1_2DAFFINETRANSFORM_INTERPOLATION_MODE}
#Import export ".\D2D1_ALPHA_MODE.ahk" {D2D1_ALPHA_MODE}
#Import export ".\D2D1_BEZIER_SEGMENT.ahk" {D2D1_BEZIER_SEGMENT}
#Import export ".\D2D1_BLEND_MODE.ahk" {D2D1_BLEND_MODE}
#Import export ".\D2D1_BORDER_MODE.ahk" {D2D1_BORDER_MODE}
#Import export ".\D2D1_COLORMATRIX_ALPHA_MODE.ahk" {D2D1_COLORMATRIX_ALPHA_MODE}
#Import export ".\D2D1_COLOR_F.ahk" {D2D1_COLOR_F}
#Import export ".\D2D1_COMPOSITE_MODE.ahk" {D2D1_COMPOSITE_MODE}
#Import export ".\D2D1_FIGURE_BEGIN.ahk" {D2D1_FIGURE_BEGIN}
#Import export ".\D2D1_FIGURE_END.ahk" {D2D1_FIGURE_END}
#Import export ".\D2D1_FILL_MODE.ahk" {D2D1_FILL_MODE}
#Import export ".\D2D1_GRADIENT_STOP.ahk" {D2D1_GRADIENT_STOP}
#Import export ".\D2D1_PATH_SEGMENT.ahk" {D2D1_PATH_SEGMENT}
#Import export ".\D2D1_PIXEL_FORMAT.ahk" {D2D1_PIXEL_FORMAT}
#Import export ".\D2D1_TURBULENCE_NOISE.ahk" {D2D1_TURBULENCE_NOISE}
#Import export ".\D2D_COLOR_F.ahk" {D2D_COLOR_F}
#Import export ".\D2D_MATRIX_3X2_F.ahk" {D2D_MATRIX_3X2_F}
#Import export ".\D2D_MATRIX_4X3_F.ahk" {D2D_MATRIX_4X3_F}
#Import export ".\D2D_MATRIX_4X4_F.ahk" {D2D_MATRIX_4X4_F}
#Import export ".\D2D_MATRIX_5X4_F.ahk" {D2D_MATRIX_5X4_F}
#Import export ".\D2D_POINT_2F.ahk" {D2D_POINT_2F}
#Import export ".\D2D_POINT_2U.ahk" {D2D_POINT_2U}
#Import export ".\D2D_RECT_F.ahk" {D2D_RECT_F}
#Import export ".\D2D_RECT_U.ahk" {D2D_RECT_U}
#Import export ".\D2D_SIZE_F.ahk" {D2D_SIZE_F}
#Import export ".\D2D_SIZE_U.ahk" {D2D_SIZE_U}
#Import export ".\D2D_VECTOR_2F.ahk" {D2D_VECTOR_2F}
#Import export ".\D2D_VECTOR_3F.ahk" {D2D_VECTOR_3F}
#Import export ".\D2D_VECTOR_4F.ahk" {D2D_VECTOR_4F}
#Import export ".\ID2D1SimplifiedGeometrySink.ahk" {ID2D1SimplifiedGeometrySink}
