#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ACDGROUP_EVENT.ahk" {ACDGROUP_EVENT}
#Import export ".\ACDQUEUE_EVENT.ahk" {ACDQUEUE_EVENT}
#Import export ".\ADDRALIAS.ahk" {ADDRALIAS}
#Import export ".\ADDRESS_CAPABILITY.ahk" {ADDRESS_CAPABILITY}
#Import export ".\ADDRESS_CAPABILITY_STRING.ahk" {ADDRESS_CAPABILITY_STRING}
#Import export ".\ADDRESS_EVENT.ahk" {ADDRESS_EVENT}
#Import export ".\ADDRESS_STATE.ahk" {ADDRESS_STATE}
#Import export ".\AGENTHANDLER_EVENT.ahk" {AGENTHANDLER_EVENT}
#Import export ".\AGENT_EVENT.ahk" {AGENT_EVENT}
#Import export ".\AGENT_SESSION_EVENT.ahk" {AGENT_SESSION_EVENT}
#Import export ".\AGENT_SESSION_STATE.ahk" {AGENT_SESSION_STATE}
#Import export ".\AGENT_STATE.ahk" {AGENT_STATE}
#Import export ".\ASYNC_COMPLETION.ahk" {ASYNC_COMPLETION}
#Import export ".\Apis.ahk" {*}
#Import export ".\CALLHUB_EVENT.ahk" {CALLHUB_EVENT}
#Import export ".\CALLHUB_STATE.ahk" {CALLHUB_STATE}
#Import export ".\CALLINFOCHANGE_CAUSE.ahk" {CALLINFOCHANGE_CAUSE}
#Import export ".\CALLINFO_BUFFER.ahk" {CALLINFO_BUFFER}
#Import export ".\CALLINFO_LONG.ahk" {CALLINFO_LONG}
#Import export ".\CALLINFO_STRING.ahk" {CALLINFO_STRING}
#Import export ".\CALL_MEDIA_EVENT.ahk" {CALL_MEDIA_EVENT}
#Import export ".\CALL_MEDIA_EVENT_CAUSE.ahk" {CALL_MEDIA_EVENT_CAUSE}
#Import export ".\CALL_NOTIFICATION_EVENT.ahk" {CALL_NOTIFICATION_EVENT}
#Import export ".\CALL_PRIVILEGE.ahk" {CALL_PRIVILEGE}
#Import export ".\CALL_STATE.ahk" {CALL_STATE}
#Import export ".\CALL_STATE_EVENT_CAUSE.ahk" {CALL_STATE_EVENT_CAUSE}
#Import export ".\Constants.ahk" {*}
#Import export ".\DIRECTORY_OBJECT_TYPE.ahk" {DIRECTORY_OBJECT_TYPE}
#Import export ".\DIRECTORY_TYPE.ahk" {DIRECTORY_TYPE}
#Import export ".\DISCONNECT_CODE.ahk" {DISCONNECT_CODE}
#Import export ".\DTR.ahk" {DTR}
#Import export ".\DispatchMapper.ahk" {DispatchMapper}
#Import export ".\FINISH_MODE.ahk" {FINISH_MODE}
#Import export ".\FT_STATE_EVENT_CAUSE.ahk" {FT_STATE_EVENT_CAUSE}
#Import export ".\FULLDUPLEX_SUPPORT.ahk" {FULLDUPLEX_SUPPORT}
#Import export ".\HDRVCALL.ahk" {HDRVCALL}
#Import export ".\HDRVDIALOGINSTANCE.ahk" {HDRVDIALOGINSTANCE}
#Import export ".\HDRVLINE.ahk" {HDRVLINE}
#Import export ".\HDRVMSPLINE.ahk" {HDRVMSPLINE}
#Import export ".\HDRVPHONE.ahk" {HDRVPHONE}
#Import export ".\HPROVIDER.ahk" {HPROVIDER}
#Import export ".\HTAPICALL.ahk" {HTAPICALL}
#Import export ".\HTAPILINE.ahk" {HTAPILINE}
#Import export ".\HTAPIPHONE.ahk" {HTAPIPHONE}
#Import export ".\IEnumACDGroup.ahk" {IEnumACDGroup}
#Import export ".\IEnumAddress.ahk" {IEnumAddress}
#Import export ".\IEnumAgent.ahk" {IEnumAgent}
#Import export ".\IEnumAgentHandler.ahk" {IEnumAgentHandler}
#Import export ".\IEnumAgentSession.ahk" {IEnumAgentSession}
#Import export ".\IEnumBstr.ahk" {IEnumBstr}
#Import export ".\IEnumCall.ahk" {IEnumCall}
#Import export ".\IEnumCallHub.ahk" {IEnumCallHub}
#Import export ".\IEnumCallingCard.ahk" {IEnumCallingCard}
#Import export ".\IEnumDialableAddrs.ahk" {IEnumDialableAddrs}
#Import export ".\IEnumDirectory.ahk" {IEnumDirectory}
#Import export ".\IEnumDirectoryObject.ahk" {IEnumDirectoryObject}
#Import export ".\IEnumLocation.ahk" {IEnumLocation}
#Import export ".\IEnumMcastScope.ahk" {IEnumMcastScope}
#Import export ".\IEnumPhone.ahk" {IEnumPhone}
#Import export ".\IEnumPluggableSuperclassInfo.ahk" {IEnumPluggableSuperclassInfo}
#Import export ".\IEnumPluggableTerminalClassInfo.ahk" {IEnumPluggableTerminalClassInfo}
#Import export ".\IEnumQueue.ahk" {IEnumQueue}
#Import export ".\IEnumStream.ahk" {IEnumStream}
#Import export ".\IEnumSubStream.ahk" {IEnumSubStream}
#Import export ".\IEnumTerminal.ahk" {IEnumTerminal}
#Import export ".\IEnumTerminalClass.ahk" {IEnumTerminalClass}
#Import export ".\IMcastAddressAllocation.ahk" {IMcastAddressAllocation}
#Import export ".\IMcastLeaseInfo.ahk" {IMcastLeaseInfo}
#Import export ".\IMcastScope.ahk" {IMcastScope}
#Import export ".\ITACDGroup.ahk" {ITACDGroup}
#Import export ".\ITACDGroupEvent.ahk" {ITACDGroupEvent}
#Import export ".\ITAMMediaFormat.ahk" {ITAMMediaFormat}
#Import export ".\ITASRTerminalEvent.ahk" {ITASRTerminalEvent}
#Import export ".\ITAddress.ahk" {ITAddress}
#Import export ".\ITAddress2.ahk" {ITAddress2}
#Import export ".\ITAddressCapabilities.ahk" {ITAddressCapabilities}
#Import export ".\ITAddressDeviceSpecificEvent.ahk" {ITAddressDeviceSpecificEvent}
#Import export ".\ITAddressEvent.ahk" {ITAddressEvent}
#Import export ".\ITAddressTranslation.ahk" {ITAddressTranslation}
#Import export ".\ITAddressTranslationInfo.ahk" {ITAddressTranslationInfo}
#Import export ".\ITAgent.ahk" {ITAgent}
#Import export ".\ITAgentEvent.ahk" {ITAgentEvent}
#Import export ".\ITAgentHandler.ahk" {ITAgentHandler}
#Import export ".\ITAgentHandlerEvent.ahk" {ITAgentHandlerEvent}
#Import export ".\ITAgentSession.ahk" {ITAgentSession}
#Import export ".\ITAgentSessionEvent.ahk" {ITAgentSessionEvent}
#Import export ".\ITAllocatorProperties.ahk" {ITAllocatorProperties}
#Import export ".\ITAutomatedPhoneControl.ahk" {ITAutomatedPhoneControl}
#Import export ".\ITBasicAudioTerminal.ahk" {ITBasicAudioTerminal}
#Import export ".\ITBasicCallControl.ahk" {ITBasicCallControl}
#Import export ".\ITBasicCallControl2.ahk" {ITBasicCallControl2}
#Import export ".\ITCallHub.ahk" {ITCallHub}
#Import export ".\ITCallHubEvent.ahk" {ITCallHubEvent}
#Import export ".\ITCallInfo.ahk" {ITCallInfo}
#Import export ".\ITCallInfo2.ahk" {ITCallInfo2}
#Import export ".\ITCallInfoChangeEvent.ahk" {ITCallInfoChangeEvent}
#Import export ".\ITCallMediaEvent.ahk" {ITCallMediaEvent}
#Import export ".\ITCallNotificationEvent.ahk" {ITCallNotificationEvent}
#Import export ".\ITCallStateEvent.ahk" {ITCallStateEvent}
#Import export ".\ITCallingCard.ahk" {ITCallingCard}
#Import export ".\ITCollection.ahk" {ITCollection}
#Import export ".\ITCollection2.ahk" {ITCollection2}
#Import export ".\ITCustomTone.ahk" {ITCustomTone}
#Import export ".\ITDetectTone.ahk" {ITDetectTone}
#Import export ".\ITDigitDetectionEvent.ahk" {ITDigitDetectionEvent}
#Import export ".\ITDigitGenerationEvent.ahk" {ITDigitGenerationEvent}
#Import export ".\ITDigitsGatheredEvent.ahk" {ITDigitsGatheredEvent}
#Import export ".\ITDirectory.ahk" {ITDirectory}
#Import export ".\ITDirectoryObject.ahk" {ITDirectoryObject}
#Import export ".\ITDirectoryObjectConference.ahk" {ITDirectoryObjectConference}
#Import export ".\ITDirectoryObjectUser.ahk" {ITDirectoryObjectUser}
#Import export ".\ITDispatchMapper.ahk" {ITDispatchMapper}
#Import export ".\ITFileTerminalEvent.ahk" {ITFileTerminalEvent}
#Import export ".\ITFileTrack.ahk" {ITFileTrack}
#Import export ".\ITForwardInformation.ahk" {ITForwardInformation}
#Import export ".\ITForwardInformation2.ahk" {ITForwardInformation2}
#Import export ".\ITILSConfig.ahk" {ITILSConfig}
#Import export ".\ITLegacyAddressMediaControl.ahk" {ITLegacyAddressMediaControl}
#Import export ".\ITLegacyAddressMediaControl2.ahk" {ITLegacyAddressMediaControl2}
#Import export ".\ITLegacyCallMediaControl.ahk" {ITLegacyCallMediaControl}
#Import export ".\ITLegacyCallMediaControl2.ahk" {ITLegacyCallMediaControl2}
#Import export ".\ITLegacyWaveSupport.ahk" {ITLegacyWaveSupport}
#Import export ".\ITLocationInfo.ahk" {ITLocationInfo}
#Import export ".\ITMSPAddress.ahk" {ITMSPAddress}
#Import export ".\ITMediaControl.ahk" {ITMediaControl}
#Import export ".\ITMediaPlayback.ahk" {ITMediaPlayback}
#Import export ".\ITMediaRecord.ahk" {ITMediaRecord}
#Import export ".\ITMediaSupport.ahk" {ITMediaSupport}
#Import export ".\ITMultiTrackTerminal.ahk" {ITMultiTrackTerminal}
#Import export ".\ITPhone.ahk" {ITPhone}
#Import export ".\ITPhoneDeviceSpecificEvent.ahk" {ITPhoneDeviceSpecificEvent}
#Import export ".\ITPhoneEvent.ahk" {ITPhoneEvent}
#Import export ".\ITPluggableTerminalClassInfo.ahk" {ITPluggableTerminalClassInfo}
#Import export ".\ITPluggableTerminalEventSink.ahk" {ITPluggableTerminalEventSink}
#Import export ".\ITPluggableTerminalEventSinkRegistration.ahk" {ITPluggableTerminalEventSinkRegistration}
#Import export ".\ITPluggableTerminalSuperclassInfo.ahk" {ITPluggableTerminalSuperclassInfo}
#Import export ".\ITPrivateEvent.ahk" {ITPrivateEvent}
#Import export ".\ITQOSEvent.ahk" {ITQOSEvent}
#Import export ".\ITQueue.ahk" {ITQueue}
#Import export ".\ITQueueEvent.ahk" {ITQueueEvent}
#Import export ".\ITRendezvous.ahk" {ITRendezvous}
#Import export ".\ITRequest.ahk" {ITRequest}
#Import export ".\ITRequestEvent.ahk" {ITRequestEvent}
#Import export ".\ITScriptableAudioFormat.ahk" {ITScriptableAudioFormat}
#Import export ".\ITStaticAudioTerminal.ahk" {ITStaticAudioTerminal}
#Import export ".\ITStream.ahk" {ITStream}
#Import export ".\ITStreamControl.ahk" {ITStreamControl}
#Import export ".\ITSubStream.ahk" {ITSubStream}
#Import export ".\ITSubStreamControl.ahk" {ITSubStreamControl}
#Import export ".\ITTAPI.ahk" {ITTAPI}
#Import export ".\ITTAPI2.ahk" {ITTAPI2}
#Import export ".\ITTAPICallCenter.ahk" {ITTAPICallCenter}
#Import export ".\ITTAPIDispatchEventNotification.ahk" {ITTAPIDispatchEventNotification}
#Import export ".\ITTAPIEventNotification.ahk" {ITTAPIEventNotification}
#Import export ".\ITTAPIObjectEvent.ahk" {ITTAPIObjectEvent}
#Import export ".\ITTAPIObjectEvent2.ahk" {ITTAPIObjectEvent2}
#Import export ".\ITTTSTerminalEvent.ahk" {ITTTSTerminalEvent}
#Import export ".\ITTerminal.ahk" {ITTerminal}
#Import export ".\ITTerminalSupport.ahk" {ITTerminalSupport}
#Import export ".\ITTerminalSupport2.ahk" {ITTerminalSupport2}
#Import export ".\ITToneDetectionEvent.ahk" {ITToneDetectionEvent}
#Import export ".\ITToneTerminalEvent.ahk" {ITToneTerminalEvent}
#Import export ".\ITnef.ahk" {ITnef}
#Import export ".\LINEADDRESSCAPS.ahk" {LINEADDRESSCAPS}
#Import export ".\LINEADDRESSSTATUS.ahk" {LINEADDRESSSTATUS}
#Import export ".\LINEAGENTACTIVITYENTRY.ahk" {LINEAGENTACTIVITYENTRY}
#Import export ".\LINEAGENTACTIVITYLIST.ahk" {LINEAGENTACTIVITYLIST}
#Import export ".\LINEAGENTCAPS.ahk" {LINEAGENTCAPS}
#Import export ".\LINEAGENTENTRY.ahk" {LINEAGENTENTRY}
#Import export ".\LINEAGENTGROUPENTRY.ahk" {LINEAGENTGROUPENTRY}
#Import export ".\LINEAGENTGROUPLIST.ahk" {LINEAGENTGROUPLIST}
#Import export ".\LINEAGENTINFO.ahk" {LINEAGENTINFO}
#Import export ".\LINEAGENTLIST.ahk" {LINEAGENTLIST}
#Import export ".\LINEAGENTSESSIONENTRY.ahk" {LINEAGENTSESSIONENTRY}
#Import export ".\LINEAGENTSESSIONINFO.ahk" {LINEAGENTSESSIONINFO}
#Import export ".\LINEAGENTSESSIONLIST.ahk" {LINEAGENTSESSIONLIST}
#Import export ".\LINEAGENTSTATUS.ahk" {LINEAGENTSTATUS}
#Import export ".\LINEAPPINFO.ahk" {LINEAPPINFO}
#Import export ".\LINECALLBACK.ahk" {LINECALLBACK}
#Import export ".\LINECALLINFO.ahk" {LINECALLINFO}
#Import export ".\LINECALLLIST.ahk" {LINECALLLIST}
#Import export ".\LINECALLPARAMS.ahk" {LINECALLPARAMS}
#Import export ".\LINECALLSTATUS.ahk" {LINECALLSTATUS}
#Import export ".\LINECALLTREATMENTENTRY.ahk" {LINECALLTREATMENTENTRY}
#Import export ".\LINECARDENTRY.ahk" {LINECARDENTRY}
#Import export ".\LINECOUNTRYENTRY.ahk" {LINECOUNTRYENTRY}
#Import export ".\LINECOUNTRYLIST.ahk" {LINECOUNTRYLIST}
#Import export ".\LINEDEVCAPS.ahk" {LINEDEVCAPS}
#Import export ".\LINEDEVSTATUS.ahk" {LINEDEVSTATUS}
#Import export ".\LINEDIALPARAMS.ahk" {LINEDIALPARAMS}
#Import export ".\LINEEVENT.ahk" {LINEEVENT}
#Import export ".\LINEEXTENSIONID.ahk" {LINEEXTENSIONID}
#Import export ".\LINEFORWARD.ahk" {LINEFORWARD}
#Import export ".\LINEFORWARDLIST.ahk" {LINEFORWARDLIST}
#Import export ".\LINEGENERATETONE.ahk" {LINEGENERATETONE}
#Import export ".\LINEINITIALIZEEXPARAMS.ahk" {LINEINITIALIZEEXPARAMS}
#Import export ".\LINELOCATIONENTRY.ahk" {LINELOCATIONENTRY}
#Import export ".\LINEMEDIACONTROLCALLSTATE.ahk" {LINEMEDIACONTROLCALLSTATE}
#Import export ".\LINEMEDIACONTROLDIGIT.ahk" {LINEMEDIACONTROLDIGIT}
#Import export ".\LINEMEDIACONTROLMEDIA.ahk" {LINEMEDIACONTROLMEDIA}
#Import export ".\LINEMEDIACONTROLTONE.ahk" {LINEMEDIACONTROLTONE}
#Import export ".\LINEMESSAGE.ahk" {LINEMESSAGE}
#Import export ".\LINEMONITORTONE.ahk" {LINEMONITORTONE}
#Import export ".\LINEPROVIDERENTRY.ahk" {LINEPROVIDERENTRY}
#Import export ".\LINEPROVIDERLIST.ahk" {LINEPROVIDERLIST}
#Import export ".\LINEPROXYREQUEST.ahk" {LINEPROXYREQUEST}
#Import export ".\LINEPROXYREQUESTLIST.ahk" {LINEPROXYREQUESTLIST}
#Import export ".\LINEQUEUEENTRY.ahk" {LINEQUEUEENTRY}
#Import export ".\LINEQUEUEINFO.ahk" {LINEQUEUEINFO}
#Import export ".\LINEQUEUELIST.ahk" {LINEQUEUELIST}
#Import export ".\LINEREQMAKECALL.ahk" {LINEREQMAKECALL}
#Import export ".\LINEREQMAKECALLW.ahk" {LINEREQMAKECALLW}
#Import export ".\LINEREQMEDIACALL.ahk" {LINEREQMEDIACALL}
#Import export ".\LINEREQMEDIACALLW.ahk" {LINEREQMEDIACALLW}
#Import export ".\LINETERMCAPS.ahk" {LINETERMCAPS}
#Import export ".\LINETRANSLATECAPS.ahk" {LINETRANSLATECAPS}
#Import export ".\LINETRANSLATEOUTPUT.ahk" {LINETRANSLATEOUTPUT}
#Import export ".\LPGETTNEFSTREAMCODEPAGE.ahk" {LPGETTNEFSTREAMCODEPAGE}
#Import export ".\LPOPENTNEFSTREAM.ahk" {LPOPENTNEFSTREAM}
#Import export ".\LPOPENTNEFSTREAMEX.ahk" {LPOPENTNEFSTREAMEX}
#Import export ".\MSP_ADDRESS_EVENT.ahk" {MSP_ADDRESS_EVENT}
#Import export ".\MSP_CALL_EVENT.ahk" {MSP_CALL_EVENT}
#Import export ".\MSP_CALL_EVENT_CAUSE.ahk" {MSP_CALL_EVENT_CAUSE}
#Import export ".\MSP_EVENT.ahk" {MSP_EVENT}
#Import export ".\MSP_EVENT_INFO.ahk" {MSP_EVENT_INFO}
#Import export ".\McastAddressAllocation.ahk" {McastAddressAllocation}
#Import export ".\NSID.ahk" {NSID}
#Import export ".\PHONEBUTTONINFO.ahk" {PHONEBUTTONINFO}
#Import export ".\PHONECALLBACK.ahk" {PHONECALLBACK}
#Import export ".\PHONECAPS.ahk" {PHONECAPS}
#Import export ".\PHONECAPS_BUFFER.ahk" {PHONECAPS_BUFFER}
#Import export ".\PHONECAPS_LONG.ahk" {PHONECAPS_LONG}
#Import export ".\PHONECAPS_STRING.ahk" {PHONECAPS_STRING}
#Import export ".\PHONEEVENT.ahk" {PHONEEVENT}
#Import export ".\PHONEEXTENSIONID.ahk" {PHONEEXTENSIONID}
#Import export ".\PHONEINITIALIZEEXPARAMS.ahk" {PHONEINITIALIZEEXPARAMS}
#Import export ".\PHONEMESSAGE.ahk" {PHONEMESSAGE}
#Import export ".\PHONESTATUS.ahk" {PHONESTATUS}
#Import export ".\PHONE_BUTTON_FUNCTION.ahk" {PHONE_BUTTON_FUNCTION}
#Import export ".\PHONE_BUTTON_MODE.ahk" {PHONE_BUTTON_MODE}
#Import export ".\PHONE_BUTTON_STATE.ahk" {PHONE_BUTTON_STATE}
#Import export ".\PHONE_EVENT.ahk" {PHONE_EVENT}
#Import export ".\PHONE_HOOK_SWITCH_DEVICE.ahk" {PHONE_HOOK_SWITCH_DEVICE}
#Import export ".\PHONE_HOOK_SWITCH_STATE.ahk" {PHONE_HOOK_SWITCH_STATE}
#Import export ".\PHONE_LAMP_MODE.ahk" {PHONE_LAMP_MODE}
#Import export ".\PHONE_PRIVILEGE.ahk" {PHONE_PRIVILEGE}
#Import export ".\PHONE_TONE.ahk" {PHONE_TONE}
#Import export ".\QOS_EVENT.ahk" {QOS_EVENT}
#Import export ".\QOS_SERVICE_LEVEL.ahk" {QOS_SERVICE_LEVEL}
#Import export ".\RENDDATA.ahk" {RENDDATA}
#Import export ".\RND_ADVERTISING_SCOPE.ahk" {RND_ADVERTISING_SCOPE}
#Import export ".\Rendezvous.ahk" {Rendezvous}
#Import export ".\RequestMakeCall.ahk" {RequestMakeCall}
#Import export ".\STnefProblem.ahk" {STnefProblem}
#Import export ".\STnefProblemArray.ahk" {STnefProblemArray}
#Import export ".\TAPI.ahk" {TAPI}
#Import export ".\TAPIOBJECT_EVENT.ahk" {TAPIOBJECT_EVENT}
#Import export ".\TAPI_CUSTOMTONE.ahk" {TAPI_CUSTOMTONE}
#Import export ".\TAPI_DETECTTONE.ahk" {TAPI_DETECTTONE}
#Import export ".\TAPI_EVENT.ahk" {TAPI_EVENT}
#Import export ".\TAPI_GATHERTERM.ahk" {TAPI_GATHERTERM}
#Import export ".\TAPI_OBJECT_TYPE.ahk" {TAPI_OBJECT_TYPE}
#Import export ".\TAPI_TONEMODE.ahk" {TAPI_TONEMODE}
#Import export ".\TERMINAL_DIRECTION.ahk" {TERMINAL_DIRECTION}
#Import export ".\TERMINAL_MEDIA_STATE.ahk" {TERMINAL_MEDIA_STATE}
#Import export ".\TERMINAL_STATE.ahk" {TERMINAL_STATE}
#Import export ".\TERMINAL_TYPE.ahk" {TERMINAL_TYPE}
#Import export ".\TRP.ahk" {TRP}
#Import export ".\TUISPICREATEDIALOGINSTANCEPARAMS.ahk" {TUISPICREATEDIALOGINSTANCEPARAMS}
#Import export ".\TUISPIDLLCALLBACK.ahk" {TUISPIDLLCALLBACK}
#Import export ".\VARSTRING.ahk" {VARSTRING}
