#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include .\ITAddress.ahk
#Include .\ITCallInfo.ahk
#Include .\ITCallHub.ahk
#Include ..\..\System\Com\IDispatch.ahk

/**
 * The ITPrivateEvent interface exposes methods that allows an application to process events generated by a private object.
 * @see https://docs.microsoft.com/windows/win32/api//tapi3if/nn-tapi3if-itprivateevent
 * @namespace Windows.Win32.Devices.Tapi
 * @version v4.0.30319
 */
class ITPrivateEvent extends IDispatch{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for ITPrivateEvent
     * @type {Guid}
     */
    static IID => Guid("{0e269cd0-10d4-4121-9c22-9c85d625650d}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 7

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["get_Address", "get_Call", "get_CallHub", "get_EventCode", "get_EventInterface"]

    /**
     * @type {ITAddress} 
     */
    Address {
        get => this.get_Address()
    }

    /**
     * @type {ITCallInfo} 
     */
    Call {
        get => this.get_Call()
    }

    /**
     * @type {ITCallHub} 
     */
    CallHub {
        get => this.get_CallHub()
    }

    /**
     * @type {Integer} 
     */
    EventCode {
        get => this.get_EventCode()
    }

    /**
     * @type {IDispatch} 
     */
    EventInterface {
        get => this.get_EventInterface()
    }

    /**
     * The get_Address method gets the ITAddress interface pointer to the private object involved in the event.
     * @returns {ITAddress} Pointer to an 
     * <a href="https://docs.microsoft.com/windows/desktop/api/tapi3if/nn-tapi3if-itaddress">ITAddress</a> interface.
     * @see https://docs.microsoft.com/windows/win32/api//tapi3if/nf-tapi3if-itprivateevent-get_address
     */
    get_Address() {
        result := ComCall(7, this, "ptr*", &ppAddress := 0, "HRESULT")
        return ITAddress(ppAddress)
    }

    /**
     * The get_Call method returns a pointer to the ITCallInfo interface of the call on which the event occurred.
     * @returns {ITCallInfo} Pointer to the 
     * <a href="https://docs.microsoft.com/windows/desktop/api/tapi3if/nn-tapi3if-itcallinfo">ITCallInfo</a> interface.
     * @see https://docs.microsoft.com/windows/win32/api//tapi3if/nf-tapi3if-itprivateevent-get_call
     */
    get_Call() {
        result := ComCall(8, this, "ptr*", &ppCallInfo := 0, "HRESULT")
        return ITCallInfo(ppCallInfo)
    }

    /**
     * The get_CallHub method returns a pointer to the ITCallHub interface on which the event occurred.
     * @returns {ITCallHub} Pointer to 
     * <a href="https://docs.microsoft.com/windows/desktop/api/tapi3if/nn-tapi3if-itcallhub">ITCallHub</a> interface.
     * @see https://docs.microsoft.com/windows/win32/api//tapi3if/nf-tapi3if-itprivateevent-get_callhub
     */
    get_CallHub() {
        result := ComCall(9, this, "ptr*", &ppCallHub := 0, "HRESULT")
        return ITCallHub(ppCallHub)
    }

    /**
     * The get_EventCode method returns a pointer to a provider-specific event descriptor.
     * @returns {Integer} Pointer to the provider-specific event descriptor.
     * @see https://docs.microsoft.com/windows/win32/api//tapi3if/nf-tapi3if-itprivateevent-get_eventcode
     */
    get_EventCode() {
        result := ComCall(10, this, "int*", &plEventCode := 0, "HRESULT")
        return plEventCode
    }

    /**
     * The get_EventInterface method returns a pointer to the IDispatch interface of the private object's event handler.
     * @returns {IDispatch} Pointer to the <b>IDispatch</b> interface of the private object's event handler.
     * @see https://docs.microsoft.com/windows/win32/api//tapi3if/nf-tapi3if-itprivateevent-get_eventinterface
     */
    get_EventInterface() {
        result := ComCall(11, this, "ptr*", &pEventInterface := 0, "HRESULT")
        return IDispatch(pEventInterface)
    }
}
