#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\Guid.ahk" { Guid }
#Import ".\ITAddress.ahk" { ITAddress }
#Import "..\..\System\Com\IDispatch.ahk" { IDispatch }
#Import ".\ITCallHub.ahk" { ITCallHub }
#Import "..\..\Foundation\HRESULT.ahk" { HRESULT }
#Import ".\ITCallInfo.ahk" { ITCallInfo }

/**
 * The ITPrivateEvent interface exposes methods that allows an application to process events generated by a private object.
 * @see https://learn.microsoft.com/windows/win32/api/tapi3if/nn-tapi3if-itprivateevent
 * @namespace Windows.Win32.Devices.Tapi
 */
export default struct ITPrivateEvent extends IDispatch {
    /**
     * The interface identifier for ITPrivateEvent
     * @type {Guid}
     */
    static IID := Guid("{0e269cd0-10d4-4121-9c22-9c85d625650d}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for ITPrivateEvent interfaces
    */
    struct Vtbl extends IDispatch.Vtbl {
        get_Address        : IntPtr
        get_Call           : IntPtr
        get_CallHub        : IntPtr
        get_EventCode      : IntPtr
        get_EventInterface : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := ITPrivateEvent.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * @type {ITAddress} 
     */
    Address {
        get => this.get_Address()
    }

    /**
     * @type {ITCallInfo} 
     */
    Call {
        get => this.get_Call()
    }

    /**
     * @type {ITCallHub} 
     */
    CallHub {
        get => this.get_CallHub()
    }

    /**
     * @type {Integer} 
     */
    EventCode {
        get => this.get_EventCode()
    }

    /**
     * @type {IDispatch} 
     */
    EventInterface {
        get => this.get_EventInterface()
    }

    /**
     * The get_Address method gets the ITAddress interface pointer to the private object involved in the event.
     * @returns {ITAddress} Pointer to an 
     * <a href="https://docs.microsoft.com/windows/desktop/api/tapi3if/nn-tapi3if-itaddress">ITAddress</a> interface.
     * @see https://learn.microsoft.com/windows/win32/api/tapi3if/nf-tapi3if-itprivateevent-get_address
     */
    get_Address() {
        result := ComCall(7, this, "ptr*", &ppAddress := 0, "HRESULT")
        return ITAddress(ppAddress)
    }

    /**
     * The get_Call method returns a pointer to the ITCallInfo interface of the call on which the event occurred. (ITPrivateEvent.get_Call)
     * @returns {ITCallInfo} Pointer to the 
     * <a href="https://docs.microsoft.com/windows/desktop/api/tapi3if/nn-tapi3if-itcallinfo">ITCallInfo</a> interface.
     * @see https://learn.microsoft.com/windows/win32/api/tapi3if/nf-tapi3if-itprivateevent-get_call
     */
    get_Call() {
        result := ComCall(8, this, "ptr*", &ppCallInfo := 0, "HRESULT")
        return ITCallInfo(ppCallInfo)
    }

    /**
     * The get_CallHub method returns a pointer to the ITCallHub interface on which the event occurred. (ITPrivateEvent.get_CallHub)
     * @returns {ITCallHub} Pointer to 
     * <a href="https://docs.microsoft.com/windows/desktop/api/tapi3if/nn-tapi3if-itcallhub">ITCallHub</a> interface.
     * @see https://learn.microsoft.com/windows/win32/api/tapi3if/nf-tapi3if-itprivateevent-get_callhub
     */
    get_CallHub() {
        result := ComCall(9, this, "ptr*", &ppCallHub := 0, "HRESULT")
        return ITCallHub(ppCallHub)
    }

    /**
     * The get_EventCode method returns a pointer to a provider-specific event descriptor.
     * @returns {Integer} Pointer to the provider-specific event descriptor.
     * @see https://learn.microsoft.com/windows/win32/api/tapi3if/nf-tapi3if-itprivateevent-get_eventcode
     */
    get_EventCode() {
        result := ComCall(10, this, "int*", &plEventCode := 0, "HRESULT")
        return plEventCode
    }

    /**
     * The get_EventInterface method returns a pointer to the IDispatch interface of the private object's event handler.
     * @returns {IDispatch} Pointer to the <b>IDispatch</b> interface of the private object's event handler.
     * @see https://learn.microsoft.com/windows/win32/api/tapi3if/nf-tapi3if-itprivateevent-get_eventinterface
     */
    get_EventInterface() {
        result := ComCall(11, this, "ptr*", &pEventInterface := 0, "HRESULT")
        return IDispatch(pEventInterface)
    }

    Query(iid) {
        if (ITPrivateEvent.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.get_Address := CallbackCreate(GetMethod(implObj, "get_Address"), flags, 2)
        this.vtbl.get_Call := CallbackCreate(GetMethod(implObj, "get_Call"), flags, 2)
        this.vtbl.get_CallHub := CallbackCreate(GetMethod(implObj, "get_CallHub"), flags, 2)
        this.vtbl.get_EventCode := CallbackCreate(GetMethod(implObj, "get_EventCode"), flags, 2)
        this.vtbl.get_EventInterface := CallbackCreate(GetMethod(implObj, "get_EventInterface"), flags, 2)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.get_Address)
        CallbackFree(this.vtbl.get_Call)
        CallbackFree(this.vtbl.get_CallHub)
        CallbackFree(this.vtbl.get_EventCode)
        CallbackFree(this.vtbl.get_EventInterface)
    }
}
