#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Audio\__Init.ahk" {*}
#Import export ".\DeviceManager\__Init.ahk" {*}
#Import export ".\DirectShow\__Init.ahk" {*}
#Import export ".\DxMediaObjects\__Init.ahk" {*}
#Import export ".\KernelStreaming\__Init.ahk" {*}
#Import export ".\LibrarySharingServices\__Init.ahk" {*}
#Import export ".\MediaFoundation\__Init.ahk" {*}
#Import export ".\MediaPlayer\__Init.ahk" {*}
#Import export ".\Multimedia\__Init.ahk" {*}
#Import export ".\PictureAcquisition\__Init.ahk" {*}
#Import export ".\Speech\__Init.ahk" {*}
#Import export ".\Streaming\__Init.ahk" {*}
#Import export ".\WindowsMediaFormat\__Init.ahk" {*}
#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\IReferenceClock.ahk" {IReferenceClock}
#Import export ".\IReferenceClock2.ahk" {IReferenceClock2}
#Import export ".\IReferenceClockTimerControl.ahk" {IReferenceClockTimerControl}
#Import export ".\LPDRVCALLBACK.ahk" {LPDRVCALLBACK}
#Import export ".\LPTIMECALLBACK.ahk" {LPTIMECALLBACK}
#Import export ".\MMTIME.ahk" {MMTIME}
#Import export ".\TIMECAPS.ahk" {TIMECAPS}
#Import export ".\TIMECODE.ahk" {TIMECODE}
#Import export ".\TIMECODE_SAMPLE.ahk" {TIMECODE_SAMPLE}
#Import export ".\TIMECODE_SAMPLE_FLAGS.ahk" {TIMECODE_SAMPLE_FLAGS}
