#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\CAccessiblityWinSAT.ahk" {CAccessiblityWinSAT}
#Import export ".\CInitiateWinSAT.ahk" {CInitiateWinSAT}
#Import export ".\CProvideWinSATVisuals.ahk" {CProvideWinSATVisuals}
#Import export ".\CQueryAllWinSAT.ahk" {CQueryAllWinSAT}
#Import export ".\CQueryOEMWinSATCustomization.ahk" {CQueryOEMWinSATCustomization}
#Import export ".\CQueryWinSAT.ahk" {CQueryWinSAT}
#Import export ".\IAccessibleWinSAT.ahk" {IAccessibleWinSAT}
#Import export ".\IInitiateWinSATAssessment.ahk" {IInitiateWinSATAssessment}
#Import export ".\IProvideWinSATAssessmentInfo.ahk" {IProvideWinSATAssessmentInfo}
#Import export ".\IProvideWinSATResultsInfo.ahk" {IProvideWinSATResultsInfo}
#Import export ".\IProvideWinSATVisuals.ahk" {IProvideWinSATVisuals}
#Import export ".\IQueryAllWinSATAssessments.ahk" {IQueryAllWinSATAssessments}
#Import export ".\IQueryOEMWinSATCustomization.ahk" {IQueryOEMWinSATCustomization}
#Import export ".\IQueryRecentWinSATAssessment.ahk" {IQueryRecentWinSATAssessment}
#Import export ".\IWinSATInitiateEvents.ahk" {IWinSATInitiateEvents}
#Import export ".\WINSAT_ASSESSMENT_STATE.ahk" {WINSAT_ASSESSMENT_STATE}
#Import export ".\WINSAT_ASSESSMENT_TYPE.ahk" {WINSAT_ASSESSMENT_TYPE}
#Import export ".\WINSAT_BITMAP_SIZE.ahk" {WINSAT_BITMAP_SIZE}
#Import export ".\WINSAT_OEM_CUSTOMIZATION_STATE.ahk" {WINSAT_OEM_CUSTOMIZATION_STATE}
