#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ADDURL_FLAG.ahk" {ADDURL_FLAG}
#Import export ".\AnchorClick.ahk" {AnchorClick}
#Import export ".\Apis.ahk" {*}
#Import export ".\CDeviceRect.ahk" {CDeviceRect}
#Import export ".\CDownloadBehavior.ahk" {CDownloadBehavior}
#Import export ".\CHeaderFooter.ahk" {CHeaderFooter}
#Import export ".\CLayoutRect.ahk" {CLayoutRect}
#Import export ".\CPersistDataPeer.ahk" {CPersistDataPeer}
#Import export ".\CPersistHistory.ahk" {CPersistHistory}
#Import export ".\CPersistShortcut.ahk" {CPersistShortcut}
#Import export ".\CPersistSnapshot.ahk" {CPersistSnapshot}
#Import export ".\CPersistUserData.ahk" {CPersistUserData}
#Import export ".\CoDitherToRGB8.ahk" {CoDitherToRGB8}
#Import export ".\CoMapMIMEToCLSID.ahk" {CoMapMIMEToCLSID}
#Import export ".\CoSniffStream.ahk" {CoSniffStream}
#Import export ".\Constants.ahk" {*}
#Import export ".\ExtensionValidationContexts.ahk" {ExtensionValidationContexts}
#Import export ".\ExtensionValidationResults.ahk" {ExtensionValidationResults}
#Import export ".\FINDFRAME_FLAGS.ahk" {FINDFRAME_FLAGS}
#Import export ".\FRAMEOPTIONS_FLAGS.ahk" {FRAMEOPTIONS_FLAGS}
#Import export ".\HomePage.ahk" {HomePage}
#Import export ".\HomePageSetting.ahk" {HomePageSetting}
#Import export ".\IActiveXUIHandlerSite.ahk" {IActiveXUIHandlerSite}
#Import export ".\IActiveXUIHandlerSite2.ahk" {IActiveXUIHandlerSite2}
#Import export ".\IActiveXUIHandlerSite3.ahk" {IActiveXUIHandlerSite3}
#Import export ".\IAnchorClick.ahk" {IAnchorClick}
#Import export ".\IAudioSessionSite.ahk" {IAudioSessionSite}
#Import export ".\ICaretPositionProvider.ahk" {ICaretPositionProvider}
#Import export ".\IDeviceRect.ahk" {IDeviceRect}
#Import export ".\IDithererImpl.ahk" {IDithererImpl}
#Import export ".\IDocObjectService.ahk" {IDocObjectService}
#Import export ".\IDownloadBehavior.ahk" {IDownloadBehavior}
#Import export ".\IDownloadManager.ahk" {IDownloadManager}
#Import export ".\IELAUNCHOPTION_FLAGS.ahk" {IELAUNCHOPTION_FLAGS}
#Import export ".\IELAUNCHURLINFO.ahk" {IELAUNCHURLINFO}
#Import export ".\IEWebDriverManager.ahk" {IEWebDriverManager}
#Import export ".\IEnumManagerFrames.ahk" {IEnumManagerFrames}
#Import export ".\IEnumOpenServiceActivity.ahk" {IEnumOpenServiceActivity}
#Import export ".\IEnumOpenServiceActivityCategory.ahk" {IEnumOpenServiceActivityCategory}
#Import export ".\IEnumSTATURL.ahk" {IEnumSTATURL}
#Import export ".\IExtensionValidation.ahk" {IExtensionValidation}
#Import export ".\IHTMLPersistData.ahk" {IHTMLPersistData}
#Import export ".\IHTMLPersistDataOM.ahk" {IHTMLPersistDataOM}
#Import export ".\IHTMLUserDataOM.ahk" {IHTMLUserDataOM}
#Import export ".\IHeaderFooter.ahk" {IHeaderFooter}
#Import export ".\IHeaderFooter2.ahk" {IHeaderFooter2}
#Import export ".\IHomePage.ahk" {IHomePage}
#Import export ".\IHomePageSetting.ahk" {IHomePageSetting}
#Import export ".\IIEWebDriverManager.ahk" {IIEWebDriverManager}
#Import export ".\IIEWebDriverSite.ahk" {IIEWebDriverSite}
#Import export ".\IImageDecodeEventSink.ahk" {IImageDecodeEventSink}
#Import export ".\IImageDecodeEventSink2.ahk" {IImageDecodeEventSink2}
#Import export ".\IImageDecodeFilter.ahk" {IImageDecodeFilter}
#Import export ".\IIntelliForms.ahk" {IIntelliForms}
#Import export ".\IInternetExplorerManager.ahk" {IInternetExplorerManager}
#Import export ".\IInternetExplorerManager2.ahk" {IInternetExplorerManager2}
#Import export ".\ILayoutRect.ahk" {ILayoutRect}
#Import export ".\IMapMIMEToCLSID.ahk" {IMapMIMEToCLSID}
#Import export ".\IMediaActivityNotifySite.ahk" {IMediaActivityNotifySite}
#Import export ".\INTERNETEXPLORERCONFIGURATION.ahk" {INTERNETEXPLORERCONFIGURATION}
#Import export ".\IOpenService.ahk" {IOpenService}
#Import export ".\IOpenServiceActivity.ahk" {IOpenServiceActivity}
#Import export ".\IOpenServiceActivityCategory.ahk" {IOpenServiceActivityCategory}
#Import export ".\IOpenServiceActivityInput.ahk" {IOpenServiceActivityInput}
#Import export ".\IOpenServiceActivityManager.ahk" {IOpenServiceActivityManager}
#Import export ".\IOpenServiceActivityOutputContext.ahk" {IOpenServiceActivityOutputContext}
#Import export ".\IOpenServiceManager.ahk" {IOpenServiceManager}
#Import export ".\IPeerFactory.ahk" {IPeerFactory}
#Import export ".\IPersistHistory.ahk" {IPersistHistory}
#Import export ".\IPrintTaskRequestFactory.ahk" {IPrintTaskRequestFactory}
#Import export ".\IPrintTaskRequestHandler.ahk" {IPrintTaskRequestHandler}
#Import export ".\IScrollableContextMenu.ahk" {IScrollableContextMenu}
#Import export ".\IScrollableContextMenu2.ahk" {IScrollableContextMenu2}
#Import export ".\ISniffStream.ahk" {ISniffStream}
#Import export ".\ISurfacePresenterFlip.ahk" {ISurfacePresenterFlip}
#Import export ".\ISurfacePresenterFlip2.ahk" {ISurfacePresenterFlip2}
#Import export ".\ISurfacePresenterFlipBuffer.ahk" {ISurfacePresenterFlipBuffer}
#Import export ".\ITargetContainer.ahk" {ITargetContainer}
#Import export ".\ITargetEmbedding.ahk" {ITargetEmbedding}
#Import export ".\ITargetFrame.ahk" {ITargetFrame}
#Import export ".\ITargetFrame2.ahk" {ITargetFrame2}
#Import export ".\ITargetFramePriv.ahk" {ITargetFramePriv}
#Import export ".\ITargetFramePriv2.ahk" {ITargetFramePriv2}
#Import export ".\ITargetNotify.ahk" {ITargetNotify}
#Import export ".\ITargetNotify2.ahk" {ITargetNotify2}
#Import export ".\ITimer.ahk" {ITimer}
#Import export ".\ITimerEx.ahk" {ITimerEx}
#Import export ".\ITimerService.ahk" {ITimerService}
#Import export ".\ITimerSink.ahk" {ITimerSink}
#Import export ".\ITridentTouchInput.ahk" {ITridentTouchInput}
#Import export ".\ITridentTouchInputSite.ahk" {ITridentTouchInputSite}
#Import export ".\IUrlHistoryNotify.ahk" {IUrlHistoryNotify}
#Import export ".\IUrlHistoryStg.ahk" {IUrlHistoryStg}
#Import export ".\IUrlHistoryStg2.ahk" {IUrlHistoryStg2}
#Import export ".\IViewObjectPresentFlip.ahk" {IViewObjectPresentFlip}
#Import export ".\IViewObjectPresentFlip2.ahk" {IViewObjectPresentFlip2}
#Import export ".\IViewObjectPresentFlipSite.ahk" {IViewObjectPresentFlipSite}
#Import export ".\IViewObjectPresentFlipSite2.ahk" {IViewObjectPresentFlipSite2}
#Import export ".\IWebBrowserEventsService.ahk" {IWebBrowserEventsService}
#Import export ".\IWebBrowserEventsUrlService.ahk" {IWebBrowserEventsUrlService}
#Import export ".\IntelliForms.ahk" {IntelliForms}
#Import export ".\InternetExplorerManager.ahk" {InternetExplorerManager}
#Import export ".\Iwfolders.ahk" {Iwfolders}
#Import export ".\MEDIA_ACTIVITY_NOTIFY_TYPE.ahk" {MEDIA_ACTIVITY_NOTIFY_TYPE}
#Import export ".\NAVIGATEDATA.ahk" {NAVIGATEDATA}
#Import export ".\NAVIGATEFRAME_FLAGS.ahk" {NAVIGATEFRAME_FLAGS}
#Import export ".\OpenServiceActivityContentType.ahk" {OpenServiceActivityContentType}
#Import export ".\OpenServiceActivityManager.ahk" {OpenServiceActivityManager}
#Import export ".\OpenServiceErrors.ahk" {OpenServiceErrors}
#Import export ".\OpenServiceManager.ahk" {OpenServiceManager}
#Import export ".\PeerFactory.ahk" {PeerFactory}
#Import export ".\SCROLLABLECONTEXTMENU_PLACEMENT.ahk" {SCROLLABLECONTEXTMENU_PLACEMENT}
#Import export ".\STATURL.ahk" {STATURL}
#Import export ".\wfolders.ahk" {wfolders}
