#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\NVME_RESERVATION_REPORT_STATUS_HEADER.ahk" { NVME_RESERVATION_REPORT_STATUS_HEADER }
#Import ".\NVME_REGISTERED_CONTROLLER_EXTENDED_DATA.ahk" { NVME_REGISTERED_CONTROLLER_EXTENDED_DATA }

/**
 * @namespace Windows.Win32.Storage.Nvme
 */
export default struct NVME_RESERVATION_REPORT_STATUS_EXTENDED_DATA_STRUCTURE {
    #StructPack 8

    Header : NVME_RESERVATION_REPORT_STATUS_HEADER

    Reserved1 : Int8[40]

    RegisteredControllersExtendedData : NVME_REGISTERED_CONTROLLER_EXTENDED_DATA[1]

}
