#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\NVME_RESERVATION_REPORT_STATUS_HEADER.ahk" { NVME_RESERVATION_REPORT_STATUS_HEADER }
#Import ".\NVME_REGISTERED_CONTROLLER_DATA.ahk" { NVME_REGISTERED_CONTROLLER_DATA }

/**
 * @namespace Windows.Win32.Storage.Nvme
 */
export default struct NVME_RESERVATION_REPORT_STATUS_DATA_STRUCTURE {
    #StructPack 8

    Header : NVME_RESERVATION_REPORT_STATUS_HEADER

    RegisteredControllersData : NVME_REGISTERED_CONTROLLER_DATA[1]

}
