#Requires AutoHotkey v2.0 64-bit

#Include ..\..\..\Win32\System\WinRT\Apis.ahk
#Include ..\..\..\Win32\System\WinRT\HSTRING.ahk
#Include ..\..\..\Win32\System\WinRT\IInspectable.ahk
#Include .\IPrintWorkflowJobStartingEventArgs.ahk
#Include .\IPrintWorkflowJobStartingEventArgs2.ahk
#Include ..\..\..\..\Guid.ahk

/**
 * Provides info for the [JobStarting](printworkflowjobbackgroundsession_jobstarting.md) event.
 * @remarks
 * For more information, see [Print support app design guide](/windows-hardware/drivers/devapps/print-support-app-design-guide).
 * @see https://learn.microsoft.com/uwp/api/windows.graphics.printing.workflow.printworkflowjobstartingeventargs
 * @namespace Windows.Graphics.Printing.Workflow
 * @version WindowsRuntime 1.4
 */
class PrintWorkflowJobStartingEventArgs extends IInspectable {
;@region Static Properties
    /**
     * The default interface of is Windows Runtime class. At the ABI level, the class is really
     * just a pointer to this interface
     * @type {Class}
     */
    static WinRTDefaultInterface => IPrintWorkflowJobStartingEventArgs

    /**
     * The IID of this class's default interface. This allows it to be cast using IUnknown::As like any
     * Windows Runtime interface
     * @type {Guid}
     */
    static IID => IPrintWorkflowJobStartingEventArgs.IID

;@endregion Static Properties

;@region Instance Properties
    /**
     * Gets printer job and session related information for the current printer job operation.
     * @see https://learn.microsoft.com/uwp/api/windows.graphics.printing.workflow.printworkflowjobstartingeventargs.configuration
     * @type {PrintWorkflowConfiguration} 
     */
    Configuration {
        get => this.get_Configuration()
    }

    /**
     * Gets the Internet Printing Protocol (IPP) printer device for the current printer job.
     * @see https://learn.microsoft.com/uwp/api/windows.graphics.printing.workflow.printworkflowjobstartingeventargs.printer
     * @type {IppPrintDevice} 
     */
    Printer {
        get => this.get_Printer()
    }

    /**
     * Gets a value that specifies whether Internet Printing Protocol (IPP) compression is enabled for the current printer job operation.
     * @remarks
     * If an app implements its own compression, it can use this property to detect if the system IPP compression is enabled. If IPP compression is enabled, the app can call [DisableIppCompressionForJob](printworkflowjobstartingeventargs_disableippcompressionforjob_1896220985.md) to disable IPP compression.
     * @see https://learn.microsoft.com/uwp/api/windows.graphics.printing.workflow.printworkflowjobstartingeventargs.isippcompressionenabled
     * @type {Boolean} 
     */
    IsIppCompressionEnabled {
        get => this.get_IsIppCompressionEnabled()
    }

    /**
     * Gets or sets a value that specifies whether the system fax dialing UI should be skipped for the current printer job operation.
     * @remarks
     * If the printer associated with the current printer job operation is a non-fax printer, setting this property has no effect.
     * @see https://learn.microsoft.com/uwp/api/windows.graphics.printing.workflow.printworkflowjobstartingeventargs.skipsystemfaxui
     * @type {Boolean} 
     */
    SkipSystemFaxUI {
        get => this.get_SkipSystemFaxUI()
        set => this.put_SkipSystemFaxUI(value)
    }

;@endregion Instance Properties

;@region Instance Methods
    __New(ptr) {
        super.__New(ptr)
    }

    /**
     * 
     * @returns {PrintWorkflowConfiguration} 
     */
    get_Configuration() {
        if (!this.HasProp("__IPrintWorkflowJobStartingEventArgs")) {
            if ((queryResult := this.QueryInterface(IPrintWorkflowJobStartingEventArgs.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IPrintWorkflowJobStartingEventArgs := IPrintWorkflowJobStartingEventArgs(outPtr)
        }

        return this.__IPrintWorkflowJobStartingEventArgs.get_Configuration()
    }

    /**
     * 
     * @returns {IppPrintDevice} 
     */
    get_Printer() {
        if (!this.HasProp("__IPrintWorkflowJobStartingEventArgs")) {
            if ((queryResult := this.QueryInterface(IPrintWorkflowJobStartingEventArgs.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IPrintWorkflowJobStartingEventArgs := IPrintWorkflowJobStartingEventArgs(outPtr)
        }

        return this.__IPrintWorkflowJobStartingEventArgs.get_Printer()
    }

    /**
     * Skips the render filter processing for the current printer job.
     * @remarks
     * If your print support workflow app skips system rendering, the OS will not convert the XPS document into the page description language (PDL) format that is required by the printer. Instead, the XPS generated by the printing application will be directly given to your print support workflow ap, which is then responsible for converting XPS to PDL format.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.graphics.printing.workflow.printworkflowjobstartingeventargs.setskipsystemrendering
     */
    SetSkipSystemRendering() {
        if (!this.HasProp("__IPrintWorkflowJobStartingEventArgs")) {
            if ((queryResult := this.QueryInterface(IPrintWorkflowJobStartingEventArgs.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IPrintWorkflowJobStartingEventArgs := IPrintWorkflowJobStartingEventArgs(outPtr)
        }

        return this.__IPrintWorkflowJobStartingEventArgs.SetSkipSystemRendering()
    }

    /**
     * Requests that the print job operation be delayed and gets a deferral object that will be invoked upon completion of the deferred action.
     * @remarks
     * The print job operation is delayed until the app calls the [Deferral.Complete](/uwp/api/windows.foundation.deferral.complete) method.
     * @returns {Deferral} 
     * @see https://learn.microsoft.com/uwp/api/windows.graphics.printing.workflow.printworkflowjobstartingeventargs.getdeferral
     */
    GetDeferral() {
        if (!this.HasProp("__IPrintWorkflowJobStartingEventArgs")) {
            if ((queryResult := this.QueryInterface(IPrintWorkflowJobStartingEventArgs.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IPrintWorkflowJobStartingEventArgs := IPrintWorkflowJobStartingEventArgs(outPtr)
        }

        return this.__IPrintWorkflowJobStartingEventArgs.GetDeferral()
    }

    /**
     * 
     * @returns {Boolean} 
     */
    get_IsIppCompressionEnabled() {
        if (!this.HasProp("__IPrintWorkflowJobStartingEventArgs2")) {
            if ((queryResult := this.QueryInterface(IPrintWorkflowJobStartingEventArgs2.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IPrintWorkflowJobStartingEventArgs2 := IPrintWorkflowJobStartingEventArgs2(outPtr)
        }

        return this.__IPrintWorkflowJobStartingEventArgs2.get_IsIppCompressionEnabled()
    }

    /**
     * Disables IPP compression for the current printer job operation.
     * @remarks
     * Determine if IPP compression is enabled for the current printer job operation by checking the value of the [IsIppCompressionEnabled](printworkflowjobstartingeventargs_isippcompressionenabled.md) property.
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/uwp/api/windows.graphics.printing.workflow.printworkflowjobstartingeventargs.disableippcompressionforjob
     */
    DisableIppCompressionForJob() {
        if (!this.HasProp("__IPrintWorkflowJobStartingEventArgs2")) {
            if ((queryResult := this.QueryInterface(IPrintWorkflowJobStartingEventArgs2.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IPrintWorkflowJobStartingEventArgs2 := IPrintWorkflowJobStartingEventArgs2(outPtr)
        }

        return this.__IPrintWorkflowJobStartingEventArgs2.DisableIppCompressionForJob()
    }

    /**
     * 
     * @returns {Boolean} 
     */
    get_SkipSystemFaxUI() {
        if (!this.HasProp("__IPrintWorkflowJobStartingEventArgs2")) {
            if ((queryResult := this.QueryInterface(IPrintWorkflowJobStartingEventArgs2.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IPrintWorkflowJobStartingEventArgs2 := IPrintWorkflowJobStartingEventArgs2(outPtr)
        }

        return this.__IPrintWorkflowJobStartingEventArgs2.get_SkipSystemFaxUI()
    }

    /**
     * 
     * @param {Boolean} value 
     * @returns {HRESULT} 
     */
    put_SkipSystemFaxUI(value) {
        if (!this.HasProp("__IPrintWorkflowJobStartingEventArgs2")) {
            if ((queryResult := this.QueryInterface(IPrintWorkflowJobStartingEventArgs2.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IPrintWorkflowJobStartingEventArgs2 := IPrintWorkflowJobStartingEventArgs2(outPtr)
        }

        return this.__IPrintWorkflowJobStartingEventArgs2.put_SkipSystemFaxUI(value)
    }

;@endregion Instance Methods
}
