#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include ..\..\UI\Shell\PropertiesSystem\IPropertyStore.ahk
#Include ..\..\System\Com\IServiceProvider.ahk

/**
 * A function instance is created as the result of calling one of the IFunctionDiscovery methods; client program do not create these objects themselves.
 * @see https://docs.microsoft.com/windows/win32/api//functiondiscoveryapi/nn-functiondiscoveryapi-ifunctioninstance
 * @namespace Windows.Win32.Devices.FunctionDiscovery
 * @version v4.0.30319
 */
class IFunctionInstance extends IServiceProvider{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IFunctionInstance
     * @type {Guid}
     */
    static IID => Guid("{33591c10-0bed-4f02-b0ab-1530d5533ee9}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 4

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["GetID", "GetProviderInstanceID", "OpenPropertyStore", "GetCategory"]

    /**
     * Gets the identifier string for the function instance.
     * @returns {Pointer<Integer>} The function instance identifier string. There is no upper limit on the size of this string. 
     * 
     * This string is a composed string generated by Function Discovery. It has the provider instance identifier string  as a substring. For more information about provider identifiers, see <a href="https://docs.microsoft.com/windows/desktop/api/functiondiscoveryapi/nf-functiondiscoveryapi-ifunctioninstance-getproviderinstanceid">IFunctionInstance::GetProviderInstanceID</a>.
     * 
     * For function instances returned by a built-in provider, this identifier is guaranteed to uniquely identify a resource on a system, even if the resource is disconnected and reconnected. For function instances returned by custom providers, the function instance identifier is unique if the provider has a unique provider identifier. 
     * 
     * This identifier should not be manipulated or manufactured programmatically. The string should only be used to retrieve function instances and for comparison purposes. 
     * 
     * Be sure to free this buffer using <a href="https://docs.microsoft.com/windows/desktop/api/combaseapi/nf-combaseapi-cotaskmemfree">CoTaskMemFree</a>.
     * @see https://docs.microsoft.com/windows/win32/api//functiondiscoveryapi/nf-functiondiscoveryapi-ifunctioninstance-getid
     */
    GetID() {
        result := ComCall(4, this, "ptr*", &ppszCoMemIdentity := 0, "HRESULT")
        return ppszCoMemIdentity
    }

    /**
     * Gets the identifier string for the provider instance.
     * @returns {Pointer<Integer>} The provider instance identifier string. For root devices, this string has the same value as PKEY_PNPX_GlobalIdentity.
     * 
     * Be sure to free this buffer using <a href="https://docs.microsoft.com/windows/desktop/api/combaseapi/nf-combaseapi-cotaskmemfree">CoTaskMemFree</a>.
     * @see https://docs.microsoft.com/windows/win32/api//functiondiscoveryapi/nf-functiondiscoveryapi-ifunctioninstance-getproviderinstanceid
     */
    GetProviderInstanceID() {
        result := ComCall(5, this, "ptr*", &ppszCoMemProviderInstanceIdentity := 0, "HRESULT")
        return ppszCoMemProviderInstanceIdentity
    }

    /**
     * Opens the property store for the function instance.
     * @param {Integer} dwStgAccess The access mode to be assigned to the open stream.  For this method, the following access modes are supported:
     * 
     * <a id="STGM_READ"></a>
     * <a id="stgm_read"></a>
     * @returns {IPropertyStore} A pointer to an <a href="https://docs.microsoft.com/windows/desktop/api/propsys/nn-propsys-ipropertystore">IPropertyStore</a> interface pointer.
     * @see https://docs.microsoft.com/windows/win32/api//functiondiscoveryapi/nf-functiondiscoveryapi-ifunctioninstance-openpropertystore
     */
    OpenPropertyStore(dwStgAccess) {
        result := ComCall(6, this, "uint", dwStgAccess, "ptr*", &ppIPropertyStore := 0, "HRESULT")
        return IPropertyStore(ppIPropertyStore)
    }

    /**
     * Gets the category and subcategory strings for the function instance.
     * @param {Pointer<Pointer<Integer>>} ppszCoMemCategory The null-terminated identifier string of the category. See <a href="https://docs.microsoft.com/previous-versions/windows/desktop/fundisc/category-definitions">Category Definitions</a>.
     * 
     * Be sure to free this buffer using <a href="https://docs.microsoft.com/windows/desktop/api/combaseapi/nf-combaseapi-cotaskmemfree">CoTaskMemFree</a>.
     * @param {Pointer<Pointer<Integer>>} ppszCoMemSubCategory The null-terminated identifier string of the subcategory. See <a href="https://docs.microsoft.com/previous-versions/windows/desktop/fundisc/subcategory-definitions">Subcategory Definitions</a>.
     * @returns {HRESULT} Possible return values include, but are not limited to, the following.
     * 
     * <table>
     * <tr>
     * <th>Return code</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>S_OK</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The method completed successfully.
     * 
     * </td>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>E_OUTOFMEMORY</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The method is unable to allocate the memory required to perform this operation.
     * 
     * </td>
     * </tr>
     * </table>
     * @see https://docs.microsoft.com/windows/win32/api//functiondiscoveryapi/nf-functiondiscoveryapi-ifunctioninstance-getcategory
     */
    GetCategory(ppszCoMemCategory, ppszCoMemSubCategory) {
        ppszCoMemCategoryMarshal := ppszCoMemCategory is VarRef ? "ptr*" : "ptr"
        ppszCoMemSubCategoryMarshal := ppszCoMemSubCategory is VarRef ? "ptr*" : "ptr"

        result := ComCall(7, this, ppszCoMemCategoryMarshal, ppszCoMemCategory, ppszCoMemSubCategoryMarshal, ppszCoMemSubCategory, "HRESULT")
        return result
    }
}
