#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32Enum.ahk

/**
 * Defines constants that specify options for applying a [DisplayState](displaystate.md) to the system.
 * @remarks
 * 
 * @see https://learn.microsoft.com/uwp/api/windows.devices.display.core.displaystateapplyoptions
 * @namespace Windows.Devices.Display.Core
 * @version WindowsRuntime 1.4
 */
class DisplayStateApplyOptions extends Win32BitflagEnum{

    /**
     * Indicates no option.
     * @type {Integer (UInt32)}
     */
    static None => 0

    /**
     * Indicates that the apply operation should fail with [SystemStateChanged](displaystateoperationstatus.md) if the system display state has changed since the [DisplayState](displaystate.md) object was created. This is useful for improving reliability of an apply operation because, if it fails for this reason, then it's often better to just redo the entire operation in case the system state change resulted in different availability of modes or monitors.
     * @type {Integer (UInt32)}
     */
    static FailIfStateChanged => 1

    /**
     * Indicates that all modes should be re-applied to all display drivers, even if they haven't changed.
     * @type {Integer (UInt32)}
     */
    static ForceReapply => 2

    /**
     * Indicates that all mode list caches should be regenerated by the system.
     * @type {Integer (UInt32)}
     */
    static ForceModeEnumeration => 4
}
