#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\APPLICATION_NODE_EVENT_FILTER.ahk" {APPLICATION_NODE_EVENT_FILTER}
#Import export ".\AsyncIDebugApplicationNodeEvents.ahk" {AsyncIDebugApplicationNodeEvents}
#Import export ".\BREAKPOINT_STATE.ahk" {BREAKPOINT_STATE}
#Import export ".\BREAKREASON.ahk" {BREAKREASON}
#Import export ".\BREAKRESUMEACTION.ahk" {BREAKRESUMEACTION}
#Import export ".\CDebugDocumentHelper.ahk" {CDebugDocumentHelper}
#Import export ".\Constants.ahk" {*}
#Import export ".\DEBUG_EVENT_INFO_TYPE.ahk" {DEBUG_EVENT_INFO_TYPE}
#Import export ".\DEBUG_STACKFRAME_TYPE.ahk" {DEBUG_STACKFRAME_TYPE}
#Import export ".\DOCUMENTNAMETYPE.ahk" {DOCUMENTNAMETYPE}
#Import export ".\DebugHelper.ahk" {DebugHelper}
#Import export ".\DebugStackFrameDescriptor.ahk" {DebugStackFrameDescriptor}
#Import export ".\DebugStackFrameDescriptor64.ahk" {DebugStackFrameDescriptor64}
#Import export ".\DefaultDebugSessionProvider.ahk" {DefaultDebugSessionProvider}
#Import export ".\ERRORRESUMEACTION.ahk" {ERRORRESUMEACTION}
#Import export ".\IActiveScript.ahk" {IActiveScript}
#Import export ".\IActiveScriptAuthor.ahk" {IActiveScriptAuthor}
#Import export ".\IActiveScriptAuthorProcedure.ahk" {IActiveScriptAuthorProcedure}
#Import export ".\IActiveScriptDebug32.ahk" {IActiveScriptDebug32}
#Import export ".\IActiveScriptDebug64.ahk" {IActiveScriptDebug64}
#Import export ".\IActiveScriptEncode.ahk" {IActiveScriptEncode}
#Import export ".\IActiveScriptError.ahk" {IActiveScriptError}
#Import export ".\IActiveScriptError64.ahk" {IActiveScriptError64}
#Import export ".\IActiveScriptErrorDebug.ahk" {IActiveScriptErrorDebug}
#Import export ".\IActiveScriptErrorDebug110.ahk" {IActiveScriptErrorDebug110}
#Import export ".\IActiveScriptGarbageCollector.ahk" {IActiveScriptGarbageCollector}
#Import export ".\IActiveScriptHostEncode.ahk" {IActiveScriptHostEncode}
#Import export ".\IActiveScriptParse32.ahk" {IActiveScriptParse32}
#Import export ".\IActiveScriptParse64.ahk" {IActiveScriptParse64}
#Import export ".\IActiveScriptParseProcedure2_32.ahk" {IActiveScriptParseProcedure2_32}
#Import export ".\IActiveScriptParseProcedure2_64.ahk" {IActiveScriptParseProcedure2_64}
#Import export ".\IActiveScriptParseProcedure32.ahk" {IActiveScriptParseProcedure32}
#Import export ".\IActiveScriptParseProcedure64.ahk" {IActiveScriptParseProcedure64}
#Import export ".\IActiveScriptParseProcedureOld32.ahk" {IActiveScriptParseProcedureOld32}
#Import export ".\IActiveScriptParseProcedureOld64.ahk" {IActiveScriptParseProcedureOld64}
#Import export ".\IActiveScriptProfilerCallback.ahk" {IActiveScriptProfilerCallback}
#Import export ".\IActiveScriptProfilerCallback2.ahk" {IActiveScriptProfilerCallback2}
#Import export ".\IActiveScriptProfilerCallback3.ahk" {IActiveScriptProfilerCallback3}
#Import export ".\IActiveScriptProfilerControl.ahk" {IActiveScriptProfilerControl}
#Import export ".\IActiveScriptProfilerControl2.ahk" {IActiveScriptProfilerControl2}
#Import export ".\IActiveScriptProfilerControl3.ahk" {IActiveScriptProfilerControl3}
#Import export ".\IActiveScriptProfilerControl4.ahk" {IActiveScriptProfilerControl4}
#Import export ".\IActiveScriptProfilerControl5.ahk" {IActiveScriptProfilerControl5}
#Import export ".\IActiveScriptProfilerHeapEnum.ahk" {IActiveScriptProfilerHeapEnum}
#Import export ".\IActiveScriptProperty.ahk" {IActiveScriptProperty}
#Import export ".\IActiveScriptSIPInfo.ahk" {IActiveScriptSIPInfo}
#Import export ".\IActiveScriptSite.ahk" {IActiveScriptSite}
#Import export ".\IActiveScriptSiteDebug32.ahk" {IActiveScriptSiteDebug32}
#Import export ".\IActiveScriptSiteDebug64.ahk" {IActiveScriptSiteDebug64}
#Import export ".\IActiveScriptSiteDebugEx.ahk" {IActiveScriptSiteDebugEx}
#Import export ".\IActiveScriptSiteInterruptPoll.ahk" {IActiveScriptSiteInterruptPoll}
#Import export ".\IActiveScriptSiteTraceInfo.ahk" {IActiveScriptSiteTraceInfo}
#Import export ".\IActiveScriptSiteUIControl.ahk" {IActiveScriptSiteUIControl}
#Import export ".\IActiveScriptSiteWindow.ahk" {IActiveScriptSiteWindow}
#Import export ".\IActiveScriptStats.ahk" {IActiveScriptStats}
#Import export ".\IActiveScriptStringCompare.ahk" {IActiveScriptStringCompare}
#Import export ".\IActiveScriptTraceInfo.ahk" {IActiveScriptTraceInfo}
#Import export ".\IActiveScriptWinRTErrorDebug.ahk" {IActiveScriptWinRTErrorDebug}
#Import export ".\IApplicationDebugger.ahk" {IApplicationDebugger}
#Import export ".\IApplicationDebuggerUI.ahk" {IApplicationDebuggerUI}
#Import export ".\IBindEventHandler.ahk" {IBindEventHandler}
#Import export ".\IDebugApplication11032.ahk" {IDebugApplication11032}
#Import export ".\IDebugApplication11064.ahk" {IDebugApplication11064}
#Import export ".\IDebugApplication32.ahk" {IDebugApplication32}
#Import export ".\IDebugApplication64.ahk" {IDebugApplication64}
#Import export ".\IDebugApplicationNode.ahk" {IDebugApplicationNode}
#Import export ".\IDebugApplicationNode100.ahk" {IDebugApplicationNode100}
#Import export ".\IDebugApplicationNodeEvents.ahk" {IDebugApplicationNodeEvents}
#Import export ".\IDebugApplicationThread.ahk" {IDebugApplicationThread}
#Import export ".\IDebugApplicationThread11032.ahk" {IDebugApplicationThread11032}
#Import export ".\IDebugApplicationThread11064.ahk" {IDebugApplicationThread11064}
#Import export ".\IDebugApplicationThread64.ahk" {IDebugApplicationThread64}
#Import export ".\IDebugApplicationThreadEvents110.ahk" {IDebugApplicationThreadEvents110}
#Import export ".\IDebugAsyncOperation.ahk" {IDebugAsyncOperation}
#Import export ".\IDebugAsyncOperationCallBack.ahk" {IDebugAsyncOperationCallBack}
#Import export ".\IDebugCodeContext.ahk" {IDebugCodeContext}
#Import export ".\IDebugCookie.ahk" {IDebugCookie}
#Import export ".\IDebugDocument.ahk" {IDebugDocument}
#Import export ".\IDebugDocumentContext.ahk" {IDebugDocumentContext}
#Import export ".\IDebugDocumentHelper32.ahk" {IDebugDocumentHelper32}
#Import export ".\IDebugDocumentHelper64.ahk" {IDebugDocumentHelper64}
#Import export ".\IDebugDocumentHost.ahk" {IDebugDocumentHost}
#Import export ".\IDebugDocumentInfo.ahk" {IDebugDocumentInfo}
#Import export ".\IDebugDocumentProvider.ahk" {IDebugDocumentProvider}
#Import export ".\IDebugDocumentText.ahk" {IDebugDocumentText}
#Import export ".\IDebugDocumentTextAuthor.ahk" {IDebugDocumentTextAuthor}
#Import export ".\IDebugDocumentTextEvents.ahk" {IDebugDocumentTextEvents}
#Import export ".\IDebugDocumentTextExternalAuthor.ahk" {IDebugDocumentTextExternalAuthor}
#Import export ".\IDebugExpression.ahk" {IDebugExpression}
#Import export ".\IDebugExpressionCallBack.ahk" {IDebugExpressionCallBack}
#Import export ".\IDebugExpressionContext.ahk" {IDebugExpressionContext}
#Import export ".\IDebugFormatter.ahk" {IDebugFormatter}
#Import export ".\IDebugHelper.ahk" {IDebugHelper}
#Import export ".\IDebugSessionProvider.ahk" {IDebugSessionProvider}
#Import export ".\IDebugStackFrame.ahk" {IDebugStackFrame}
#Import export ".\IDebugStackFrame110.ahk" {IDebugStackFrame110}
#Import export ".\IDebugStackFrameSniffer.ahk" {IDebugStackFrameSniffer}
#Import export ".\IDebugStackFrameSnifferEx32.ahk" {IDebugStackFrameSnifferEx32}
#Import export ".\IDebugStackFrameSnifferEx64.ahk" {IDebugStackFrameSnifferEx64}
#Import export ".\IDebugSyncOperation.ahk" {IDebugSyncOperation}
#Import export ".\IDebugThreadCall32.ahk" {IDebugThreadCall32}
#Import export ".\IDebugThreadCall64.ahk" {IDebugThreadCall64}
#Import export ".\IEnumDebugApplicationNodes.ahk" {IEnumDebugApplicationNodes}
#Import export ".\IEnumDebugCodeContexts.ahk" {IEnumDebugCodeContexts}
#Import export ".\IEnumDebugExpressionContexts.ahk" {IEnumDebugExpressionContexts}
#Import export ".\IEnumDebugStackFrames.ahk" {IEnumDebugStackFrames}
#Import export ".\IEnumDebugStackFrames64.ahk" {IEnumDebugStackFrames64}
#Import export ".\IEnumJsStackFrames.ahk" {IEnumJsStackFrames}
#Import export ".\IEnumRemoteDebugApplicationThreads.ahk" {IEnumRemoteDebugApplicationThreads}
#Import export ".\IEnumRemoteDebugApplications.ahk" {IEnumRemoteDebugApplications}
#Import export ".\IJsDebug.ahk" {IJsDebug}
#Import export ".\IJsDebugBreakPoint.ahk" {IJsDebugBreakPoint}
#Import export ".\IJsDebugDataTarget.ahk" {IJsDebugDataTarget}
#Import export ".\IJsDebugFrame.ahk" {IJsDebugFrame}
#Import export ".\IJsDebugProcess.ahk" {IJsDebugProcess}
#Import export ".\IJsDebugProperty.ahk" {IJsDebugProperty}
#Import export ".\IJsDebugStackWalker.ahk" {IJsDebugStackWalker}
#Import export ".\IJsEnumDebugProperty.ahk" {IJsEnumDebugProperty}
#Import export ".\IMachineDebugManager.ahk" {IMachineDebugManager}
#Import export ".\IMachineDebugManagerCookie.ahk" {IMachineDebugManagerCookie}
#Import export ".\IMachineDebugManagerEvents.ahk" {IMachineDebugManagerEvents}
#Import export ".\IProcessDebugManager32.ahk" {IProcessDebugManager32}
#Import export ".\IProcessDebugManager64.ahk" {IProcessDebugManager64}
#Import export ".\IProvideExpressionContexts.ahk" {IProvideExpressionContexts}
#Import export ".\IRemoteDebugApplication.ahk" {IRemoteDebugApplication}
#Import export ".\IRemoteDebugApplication110.ahk" {IRemoteDebugApplication110}
#Import export ".\IRemoteDebugApplicationEvents.ahk" {IRemoteDebugApplicationEvents}
#Import export ".\IRemoteDebugApplicationThread.ahk" {IRemoteDebugApplicationThread}
#Import export ".\IRemoteDebugCriticalErrorEvent110.ahk" {IRemoteDebugCriticalErrorEvent110}
#Import export ".\IRemoteDebugInfoEvent110.ahk" {IRemoteDebugInfoEvent110}
#Import export ".\IScriptEntry.ahk" {IScriptEntry}
#Import export ".\IScriptInvocationContext.ahk" {IScriptInvocationContext}
#Import export ".\IScriptNode.ahk" {IScriptNode}
#Import export ".\IScriptScriptlet.ahk" {IScriptScriptlet}
#Import export ".\ISimpleConnectionPoint.ahk" {ISimpleConnectionPoint}
#Import export ".\ITridentEventSink.ahk" {ITridentEventSink}
#Import export ".\IWebAppDiagnosticsObjectInitialization.ahk" {IWebAppDiagnosticsObjectInitialization}
#Import export ".\IWebAppDiagnosticsSetup.ahk" {IWebAppDiagnosticsSetup}
#Import export ".\JS_NATIVE_FRAME.ahk" {JS_NATIVE_FRAME}
#Import export ".\JS_PROPERTY_ATTRIBUTES.ahk" {JS_PROPERTY_ATTRIBUTES}
#Import export ".\JS_PROPERTY_MEMBERS.ahk" {JS_PROPERTY_MEMBERS}
#Import export ".\JsDebugPropertyInfo.ahk" {JsDebugPropertyInfo}
#Import export ".\JsDebugReadMemoryFlags.ahk" {JsDebugReadMemoryFlags}
#Import export ".\MachineDebugManager_DEBUG.ahk" {MachineDebugManager_DEBUG}
#Import export ".\MachineDebugManager_RETAIL.ahk" {MachineDebugManager_RETAIL}
#Import export ".\PROFILER_EVENT_MASK.ahk" {PROFILER_EVENT_MASK}
#Import export ".\PROFILER_HEAP_ENUM_FLAGS.ahk" {PROFILER_HEAP_ENUM_FLAGS}
#Import export ".\PROFILER_HEAP_OBJECT.ahk" {PROFILER_HEAP_OBJECT}
#Import export ".\PROFILER_HEAP_OBJECT_FLAGS.ahk" {PROFILER_HEAP_OBJECT_FLAGS}
#Import export ".\PROFILER_HEAP_OBJECT_OPTIONAL_INFO.ahk" {PROFILER_HEAP_OBJECT_OPTIONAL_INFO}
#Import export ".\PROFILER_HEAP_OBJECT_OPTIONAL_INFO_TYPE.ahk" {PROFILER_HEAP_OBJECT_OPTIONAL_INFO_TYPE}
#Import export ".\PROFILER_HEAP_OBJECT_RELATIONSHIP.ahk" {PROFILER_HEAP_OBJECT_RELATIONSHIP}
#Import export ".\PROFILER_HEAP_OBJECT_RELATIONSHIP_FLAGS.ahk" {PROFILER_HEAP_OBJECT_RELATIONSHIP_FLAGS}
#Import export ".\PROFILER_HEAP_OBJECT_RELATIONSHIP_LIST.ahk" {PROFILER_HEAP_OBJECT_RELATIONSHIP_LIST}
#Import export ".\PROFILER_HEAP_OBJECT_SCOPE_LIST.ahk" {PROFILER_HEAP_OBJECT_SCOPE_LIST}
#Import export ".\PROFILER_HEAP_SUMMARY.ahk" {PROFILER_HEAP_SUMMARY}
#Import export ".\PROFILER_HEAP_SUMMARY_VERSION.ahk" {PROFILER_HEAP_SUMMARY_VERSION}
#Import export ".\PROFILER_PROPERTY_TYPE_SUBSTRING_INFO.ahk" {PROFILER_PROPERTY_TYPE_SUBSTRING_INFO}
#Import export ".\PROFILER_RELATIONSHIP_INFO.ahk" {PROFILER_RELATIONSHIP_INFO}
#Import export ".\PROFILER_SCRIPT_TYPE.ahk" {PROFILER_SCRIPT_TYPE}
#Import export ".\ProcessDebugManager.ahk" {ProcessDebugManager}
#Import export ".\SCRIPTGCTYPE.ahk" {SCRIPTGCTYPE}
#Import export ".\SCRIPTLANGUAGEVERSION.ahk" {SCRIPTLANGUAGEVERSION}
#Import export ".\SCRIPTSTATE.ahk" {SCRIPTSTATE}
#Import export ".\SCRIPTTHREADSTATE.ahk" {SCRIPTTHREADSTATE}
#Import export ".\SCRIPTTRACEINFO.ahk" {SCRIPTTRACEINFO}
#Import export ".\SCRIPTUICHANDLING.ahk" {SCRIPTUICHANDLING}
#Import export ".\SCRIPTUICITEM.ahk" {SCRIPTUICITEM}
#Import export ".\SCRIPT_DEBUGGER_OPTIONS.ahk" {SCRIPT_DEBUGGER_OPTIONS}
#Import export ".\SCRIPT_ERROR_DEBUG_EXCEPTION_THROWN_KIND.ahk" {SCRIPT_ERROR_DEBUG_EXCEPTION_THROWN_KIND}
#Import export ".\SCRIPT_INVOCATION_CONTEXT_TYPE.ahk" {SCRIPT_INVOCATION_CONTEXT_TYPE}
#Import export ".\TEXT_DOCUMENT_ARRAY.ahk" {TEXT_DOCUMENT_ARRAY}
