#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\AllJoyn\__Init.ahk" {*}
#Import export ".\Composition\__Init.ahk" {*}
#Import export ".\CoreInputView\__Init.ahk" {*}
#Import export ".\Direct3D11\__Init.ahk" {*}
#Import export ".\Display\__Init.ahk" {*}
#Import export ".\Graphics\__Init.ahk" {*}
#Import export ".\Holographic\__Init.ahk" {*}
#Import export ".\Isolation\__Init.ahk" {*}
#Import export ".\ML\__Init.ahk" {*}
#Import export ".\Media\__Init.ahk" {*}
#Import export ".\Metadata\__Init.ahk" {*}
#Import export ".\Pdf\__Init.ahk" {*}
#Import export ".\Printing\__Init.ahk" {*}
#Import export ".\Shell\__Init.ahk" {*}
#Import export ".\Storage\__Init.ahk" {*}
#Import export ".\Xaml\__Init.ahk" {*}
#Import export ".\ACTIVATIONTYPE.ahk" {ACTIVATIONTYPE}
#Import export ".\APARTMENT_SHUTDOWN_REGISTRATION_COOKIE.ahk" {APARTMENT_SHUTDOWN_REGISTRATION_COOKIE}
#Import export ".\AgileReferenceOptions.ahk" {AgileReferenceOptions}
#Import export ".\Apis.ahk" {*}
#Import export ".\BSOS_OPTIONS.ahk" {BSOS_OPTIONS}
#Import export ".\CASTING_CONNECTION_ERROR_STATUS.ahk" {CASTING_CONNECTION_ERROR_STATUS}
#Import export ".\CASTING_CONNECTION_STATE.ahk" {CASTING_CONNECTION_STATE}
#Import export ".\Constants.ahk" {*}
#Import export ".\DISPATCHERQUEUE_THREAD_APARTMENTTYPE.ahk" {DISPATCHERQUEUE_THREAD_APARTMENTTYPE}
#Import export ".\DISPATCHERQUEUE_THREAD_TYPE.ahk" {DISPATCHERQUEUE_THREAD_TYPE}
#Import export ".\DispatcherQueueOptions.ahk" {DispatcherQueueOptions}
#Import export ".\EventRegistrationToken.ahk" {EventRegistrationToken}
#Import export ".\HSTRING.ahk" {HSTRING}
#Import export ".\HSTRING_BUFFER.ahk" {HSTRING_BUFFER}
#Import export ".\HSTRING_HEADER.ahk" {HSTRING_HEADER}
#Import export ".\IAccountsSettingsPaneInterop.ahk" {IAccountsSettingsPaneInterop}
#Import export ".\IActivationFactory.ahk" {IActivationFactory}
#Import export ".\IAgileReference.ahk" {IAgileReference}
#Import export ".\IApartmentShutdown.ahk" {IApartmentShutdown}
#Import export ".\IAppServiceConnectionExtendedExecution.ahk" {IAppServiceConnectionExtendedExecution}
#Import export ".\IBufferByteAccess.ahk" {IBufferByteAccess}
#Import export ".\ICastingController.ahk" {ICastingController}
#Import export ".\ICastingEventHandler.ahk" {ICastingEventHandler}
#Import export ".\ICastingSourceInfo.ahk" {ICastingSourceInfo}
#Import export ".\ICoreInputInterop.ahk" {ICoreInputInterop}
#Import export ".\ICoreInputInterop2.ahk" {ICoreInputInterop2}
#Import export ".\ICoreWindowAdapterInterop.ahk" {ICoreWindowAdapterInterop}
#Import export ".\ICoreWindowComponentInterop.ahk" {ICoreWindowComponentInterop}
#Import export ".\ICoreWindowInterop.ahk" {ICoreWindowInterop}
#Import export ".\ICorrelationVectorInformation.ahk" {ICorrelationVectorInformation}
#Import export ".\ICorrelationVectorSource.ahk" {ICorrelationVectorSource}
#Import export ".\IDragDropManagerInterop.ahk" {IDragDropManagerInterop}
#Import export ".\IHolographicSpaceInterop.ahk" {IHolographicSpaceInterop}
#Import export ".\IInputPaneInterop.ahk" {IInputPaneInterop}
#Import export ".\IInspectable.ahk" {IInspectable}
#Import export ".\ILanguageExceptionErrorInfo.ahk" {ILanguageExceptionErrorInfo}
#Import export ".\ILanguageExceptionErrorInfo2.ahk" {ILanguageExceptionErrorInfo2}
#Import export ".\ILanguageExceptionStackBackTrace.ahk" {ILanguageExceptionStackBackTrace}
#Import export ".\ILanguageExceptionTransform.ahk" {ILanguageExceptionTransform}
#Import export ".\IMemoryBufferByteAccess.ahk" {IMemoryBufferByteAccess}
#Import export ".\IMessageDispatcher.ahk" {IMessageDispatcher}
#Import export ".\IPlayToManagerInterop.ahk" {IPlayToManagerInterop}
#Import export ".\IRestrictedErrorInfo.ahk" {IRestrictedErrorInfo}
#Import export ".\IShareWindowCommandEventArgsInterop.ahk" {IShareWindowCommandEventArgsInterop}
#Import export ".\IShareWindowCommandSourceInterop.ahk" {IShareWindowCommandSourceInterop}
#Import export ".\ISpatialInteractionManagerInterop.ahk" {ISpatialInteractionManagerInterop}
#Import export ".\ISystemMediaTransportControlsInterop.ahk" {ISystemMediaTransportControlsInterop}
#Import export ".\IUIViewSettingsInterop.ahk" {IUIViewSettingsInterop}
#Import export ".\IUserActivityInterop.ahk" {IUserActivityInterop}
#Import export ".\IUserActivityRequestManagerInterop.ahk" {IUserActivityRequestManagerInterop}
#Import export ".\IUserActivitySourceHostInterop.ahk" {IUserActivitySourceHostInterop}
#Import export ".\IUserConsentVerifierInterop.ahk" {IUserConsentVerifierInterop}
#Import export ".\IWeakReference.ahk" {IWeakReference}
#Import export ".\IWeakReferenceSource.ahk" {IWeakReferenceSource}
#Import export ".\IWebAuthenticationCoreManagerInterop.ahk" {IWebAuthenticationCoreManagerInterop}
#Import export ".\PFNGETACTIVATIONFACTORY.ahk" {PFNGETACTIVATIONFACTORY}
#Import export ".\PINSPECT_HSTRING_CALLBACK.ahk" {PINSPECT_HSTRING_CALLBACK}
#Import export ".\PINSPECT_HSTRING_CALLBACK2.ahk" {PINSPECT_HSTRING_CALLBACK2}
#Import export ".\PINSPECT_MEMORY_CALLBACK.ahk" {PINSPECT_MEMORY_CALLBACK}
#Import export ".\RO_ERROR_REPORTING_FLAGS.ahk" {RO_ERROR_REPORTING_FLAGS}
#Import export ".\RO_INIT_TYPE.ahk" {RO_INIT_TYPE}
#Import export ".\RO_REGISTRATION_COOKIE.ahk" {RO_REGISTRATION_COOKIE}
#Import export ".\ServerInformation.ahk" {ServerInformation}
#Import export ".\TrustLevel.ahk" {TrustLevel}
