#Requires AutoHotkey v2.0 64-bit

#Include ..\..\Win32\System\WinRT\Apis.ahk
#Include ..\..\Win32\System\WinRT\HSTRING.ahk
#Include ..\..\Win32\System\WinRT\IInspectable.ahk
#Include .\IAdvancedCapturedPhoto.ahk
#Include .\IAdvancedCapturedPhoto2.ahk
#Include ..\..\..\Guid.ahk

/**
 * Represents a photo captured using system-provided computational photography techniques provided by the [AdvancedPhotoCapture](advancedphotocapture.md) class.
 * @remarks
 * Get an instance of this class by calling [AdvancedPhotoCapture.CaptureAsync](advancedphotocapture_captureasync_2078018041.md).
 * 
 * For how-to guidance for using [AdvancedPhotoCapture](advancedphotocapture.md), see [High dynamic range (HDR) and low-light photo capture](/windows/apps/develop/camera/hdr-low-light-photo-capture).
 * @see https://learn.microsoft.com/uwp/api/windows.media.capture.advancedcapturedphoto
 * @namespace Windows.Media.Capture
 * @version WindowsRuntime 1.4
 */
class AdvancedCapturedPhoto extends IInspectable {
;@region Static Properties
    /**
     * The default interface of is Windows Runtime class. At the ABI level, the class is really
     * just a pointer to this interface
     * @type {Class}
     */
    static WinRTDefaultInterface => IAdvancedCapturedPhoto

    /**
     * The IID of this class's default interface. This allows it to be cast using IUnknown::As like any
     * Windows Runtime interface
     * @type {Guid}
     */
    static IID => IAdvancedCapturedPhoto.IID

;@endregion Static Properties

;@region Instance Properties
    /**
     * Gets the captured frame containing the result of the advanced photo capture.
     * @see https://learn.microsoft.com/uwp/api/windows.media.capture.advancedcapturedphoto.frame
     * @type {CapturedFrame} 
     */
    Frame {
        get => this.get_Frame()
    }

    /**
     * Gets a value indicating the advanced capture mode with which the photo was captured.
     * @see https://learn.microsoft.com/uwp/api/windows.media.capture.advancedcapturedphoto.mode
     * @type {Integer} 
     */
    Mode {
        get => this.get_Mode()
    }

    /**
     * Gets the app-defined context object associated with the advanced photo capture operation, if one was provided in the call to [AdvancedPhotoCapture.CaptureAsync(Object)](advancedphotocapture_captureasync_651770772.md).
     * @remarks
     * One overload of [AdvancedPhotoCapture.CaptureAsync](/uwp/api/windows.media.capture.advancedphotocapture.captureasync) allows you to provide an app-defined object that conveys context information.
     * @see https://learn.microsoft.com/uwp/api/windows.media.capture.advancedcapturedphoto.context
     * @type {IInspectable} 
     */
    Context {
        get => this.get_Context()
    }

    /**
     * Gets a reference to a [Rect](../windows.foundation/rect.md) that expresses the dimensions of the [Frame](advancedcapturedphoto_frame.md) generated by the advanced photo capture operation, relative to the reference photo passed into the [OptionalReferencePhotoCaptured](advancedphotocapture_optionalreferencephotocaptured.md) event.
     * @remarks
     * Due to the image processing involved, a frame captured with [AdvancedPhotoCapture](advancedphotocapture.md) may be smaller than the preview photo that is passed into the [OptionalReferencePhotoCaptured](advancedphotocapture_optionalreferencephotocaptured.md) event. This property allows you to crop the preview frame so that it matches the dimensions of the processed frame.
     * 
     * 
     * 
     * > [!NOTE]
     * > Not all capture devices support providing a reference photo for advanced photo capture or determining the dimensions of the reference photo, so this property may be null. Be sure to check for a null reference before using the value of this property.
     * @see https://learn.microsoft.com/uwp/api/windows.media.capture.advancedcapturedphoto.frameboundsrelativetoreferencephoto
     * @type {IReference<RECT>} 
     */
    FrameBoundsRelativeToReferencePhoto {
        get => this.get_FrameBoundsRelativeToReferencePhoto()
    }

;@endregion Instance Properties

;@region Instance Methods
    __New(ptr) {
        super.__New(ptr)
    }

    /**
     * 
     * @returns {CapturedFrame} 
     */
    get_Frame() {
        if (!this.HasProp("__IAdvancedCapturedPhoto")) {
            if ((queryResult := this.QueryInterface(IAdvancedCapturedPhoto.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IAdvancedCapturedPhoto := IAdvancedCapturedPhoto(outPtr)
        }

        return this.__IAdvancedCapturedPhoto.get_Frame()
    }

    /**
     * 
     * @returns {Integer} 
     */
    get_Mode() {
        if (!this.HasProp("__IAdvancedCapturedPhoto")) {
            if ((queryResult := this.QueryInterface(IAdvancedCapturedPhoto.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IAdvancedCapturedPhoto := IAdvancedCapturedPhoto(outPtr)
        }

        return this.__IAdvancedCapturedPhoto.get_Mode()
    }

    /**
     * 
     * @returns {IInspectable} 
     */
    get_Context() {
        if (!this.HasProp("__IAdvancedCapturedPhoto")) {
            if ((queryResult := this.QueryInterface(IAdvancedCapturedPhoto.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IAdvancedCapturedPhoto := IAdvancedCapturedPhoto(outPtr)
        }

        return this.__IAdvancedCapturedPhoto.get_Context()
    }

    /**
     * 
     * @returns {IReference<RECT>} 
     */
    get_FrameBoundsRelativeToReferencePhoto() {
        if (!this.HasProp("__IAdvancedCapturedPhoto2")) {
            if ((queryResult := this.QueryInterface(IAdvancedCapturedPhoto2.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IAdvancedCapturedPhoto2 := IAdvancedCapturedPhoto2(outPtr)
        }

        return this.__IAdvancedCapturedPhoto2.get_FrameBoundsRelativeToReferencePhoto()
    }

;@endregion Instance Methods
}
