#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\CLEAR_COMM_ERROR_FLAGS.ahk" {CLEAR_COMM_ERROR_FLAGS}
#Import export ".\COMMCONFIG.ahk" {COMMCONFIG}
#Import export ".\COMMPROP.ahk" {COMMPROP}
#Import export ".\COMMPROP_STOP_PARITY.ahk" {COMMPROP_STOP_PARITY}
#Import export ".\COMMTIMEOUTS.ahk" {COMMTIMEOUTS}
#Import export ".\COMM_EVENT_MASK.ahk" {COMM_EVENT_MASK}
#Import export ".\COMSTAT.ahk" {COMSTAT}
#Import export ".\Constants.ahk" {*}
#Import export ".\DCB.ahk" {DCB}
#Import export ".\DCB_PARITY.ahk" {DCB_PARITY}
#Import export ".\DCB_STOP_BITS.ahk" {DCB_STOP_BITS}
#Import export ".\ESCAPE_COMM_FUNCTION.ahk" {ESCAPE_COMM_FUNCTION}
#Import export ".\MODEMDEVCAPS.ahk" {MODEMDEVCAPS}
#Import export ".\MODEMDEVCAPS_DIAL_OPTIONS.ahk" {MODEMDEVCAPS_DIAL_OPTIONS}
#Import export ".\MODEMDEVCAPS_SPEAKER_MODE.ahk" {MODEMDEVCAPS_SPEAKER_MODE}
#Import export ".\MODEMDEVCAPS_SPEAKER_VOLUME.ahk" {MODEMDEVCAPS_SPEAKER_VOLUME}
#Import export ".\MODEMSETTINGS.ahk" {MODEMSETTINGS}
#Import export ".\MODEMSETTINGS_SPEAKER_MODE.ahk" {MODEMSETTINGS_SPEAKER_MODE}
#Import export ".\MODEM_SPEAKER_VOLUME.ahk" {MODEM_SPEAKER_VOLUME}
#Import export ".\MODEM_STATUS_FLAGS.ahk" {MODEM_STATUS_FLAGS}
#Import export ".\PURGE_COMM_FLAGS.ahk" {PURGE_COMM_FLAGS}
