#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\ALT_BREAKS.ahk" {ALT_BREAKS}
#Import export ".\Apis.ahk" {*}
#Import export ".\AppearanceConstants.ahk" {AppearanceConstants}
#Import export ".\BorderStyleConstants.ahk" {BorderStyleConstants}
#Import export ".\CHARACTER_RANGE.ahk" {CHARACTER_RANGE}
#Import export ".\CONFIDENCE_LEVEL.ahk" {CONFIDENCE_LEVEL}
#Import export ".\Constants.ahk" {*}
#Import export ".\CorrectionMode.ahk" {CorrectionMode}
#Import export ".\CorrectionPosition.ahk" {CorrectionPosition}
#Import export ".\DISPID_Ink.ahk" {DISPID_Ink}
#Import export ".\DISPID_InkCollector.ahk" {DISPID_InkCollector}
#Import export ".\DISPID_InkCollectorEvent.ahk" {DISPID_InkCollectorEvent}
#Import export ".\DISPID_InkCursor.ahk" {DISPID_InkCursor}
#Import export ".\DISPID_InkCursorButton.ahk" {DISPID_InkCursorButton}
#Import export ".\DISPID_InkCursorButtons.ahk" {DISPID_InkCursorButtons}
#Import export ".\DISPID_InkCursors.ahk" {DISPID_InkCursors}
#Import export ".\DISPID_InkCustomStrokes.ahk" {DISPID_InkCustomStrokes}
#Import export ".\DISPID_InkDivider.ahk" {DISPID_InkDivider}
#Import export ".\DISPID_InkDivisionResult.ahk" {DISPID_InkDivisionResult}
#Import export ".\DISPID_InkDivisionUnit.ahk" {DISPID_InkDivisionUnit}
#Import export ".\DISPID_InkDivisionUnits.ahk" {DISPID_InkDivisionUnits}
#Import export ".\DISPID_InkDrawingAttributes.ahk" {DISPID_InkDrawingAttributes}
#Import export ".\DISPID_InkEdit.ahk" {DISPID_InkEdit}
#Import export ".\DISPID_InkEditEvents.ahk" {DISPID_InkEditEvents}
#Import export ".\DISPID_InkEvent.ahk" {DISPID_InkEvent}
#Import export ".\DISPID_InkExtendedProperties.ahk" {DISPID_InkExtendedProperties}
#Import export ".\DISPID_InkExtendedProperty.ahk" {DISPID_InkExtendedProperty}
#Import export ".\DISPID_InkGesture.ahk" {DISPID_InkGesture}
#Import export ".\DISPID_InkRecoAlternate.ahk" {DISPID_InkRecoAlternate}
#Import export ".\DISPID_InkRecoContext.ahk" {DISPID_InkRecoContext}
#Import export ".\DISPID_InkRecoContext2.ahk" {DISPID_InkRecoContext2}
#Import export ".\DISPID_InkRecognitionAlternates.ahk" {DISPID_InkRecognitionAlternates}
#Import export ".\DISPID_InkRecognitionEvent.ahk" {DISPID_InkRecognitionEvent}
#Import export ".\DISPID_InkRecognitionResult.ahk" {DISPID_InkRecognitionResult}
#Import export ".\DISPID_InkRecognizer.ahk" {DISPID_InkRecognizer}
#Import export ".\DISPID_InkRecognizer2.ahk" {DISPID_InkRecognizer2}
#Import export ".\DISPID_InkRecognizerGuide.ahk" {DISPID_InkRecognizerGuide}
#Import export ".\DISPID_InkRecognizers.ahk" {DISPID_InkRecognizers}
#Import export ".\DISPID_InkRectangle.ahk" {DISPID_InkRectangle}
#Import export ".\DISPID_InkRenderer.ahk" {DISPID_InkRenderer}
#Import export ".\DISPID_InkStrokeDisp.ahk" {DISPID_InkStrokeDisp}
#Import export ".\DISPID_InkStrokes.ahk" {DISPID_InkStrokes}
#Import export ".\DISPID_InkTablet.ahk" {DISPID_InkTablet}
#Import export ".\DISPID_InkTablet2.ahk" {DISPID_InkTablet2}
#Import export ".\DISPID_InkTablet3.ahk" {DISPID_InkTablet3}
#Import export ".\DISPID_InkTablets.ahk" {DISPID_InkTablets}
#Import export ".\DISPID_InkTransform.ahk" {DISPID_InkTransform}
#Import export ".\DISPID_InkWordList.ahk" {DISPID_InkWordList}
#Import export ".\DISPID_InkWordList2.ahk" {DISPID_InkWordList2}
#Import export ".\DISPID_MathInputControlEvents.ahk" {DISPID_MathInputControlEvents}
#Import export ".\DISPID_PenInputPanel.ahk" {DISPID_PenInputPanel}
#Import export ".\DISPID_PenInputPanelEvents.ahk" {DISPID_PenInputPanelEvents}
#Import export ".\DISPID_StrokeEvent.ahk" {DISPID_StrokeEvent}
#Import export ".\DYNAMIC_RENDERER_CACHED_DATA.ahk" {DYNAMIC_RENDERER_CACHED_DATA}
#Import export ".\DynamicRenderer.ahk" {DynamicRenderer}
#Import export ".\EventMask.ahk" {EventMask}
#Import export ".\FLICKACTION_COMMANDCODE.ahk" {FLICKACTION_COMMANDCODE}
#Import export ".\FLICKDIRECTION.ahk" {FLICKDIRECTION}
#Import export ".\FLICKMODE.ahk" {FLICKMODE}
#Import export ".\FLICK_DATA.ahk" {FLICK_DATA}
#Import export ".\FLICK_POINT.ahk" {FLICK_POINT}
#Import export ".\GESTURE_DATA.ahk" {GESTURE_DATA}
#Import export ".\GET_DANDIDATE_FLAGS.ahk" {GET_DANDIDATE_FLAGS}
#Import export ".\GestureRecognizer.ahk" {GestureRecognizer}
#Import export ".\HRECOALT.ahk" {HRECOALT}
#Import export ".\HRECOCONTEXT.ahk" {HRECOCONTEXT}
#Import export ".\HRECOGNIZER.ahk" {HRECOGNIZER}
#Import export ".\HRECOLATTICE.ahk" {HRECOLATTICE}
#Import export ".\HRECOWORDLIST.ahk" {HRECOWORDLIST}
#Import export ".\HandwrittenTextInsertion.ahk" {HandwrittenTextInsertion}
#Import export ".\IDynamicRenderer.ahk" {IDynamicRenderer}
#Import export ".\IEC_GESTUREINFO.ahk" {IEC_GESTUREINFO}
#Import export ".\IEC_RECOGNITIONRESULTINFO.ahk" {IEC_RECOGNITIONRESULTINFO}
#Import export ".\IEC_STROKEINFO.ahk" {IEC_STROKEINFO}
#Import export ".\IGestureRecognizer.ahk" {IGestureRecognizer}
#Import export ".\IHandwrittenTextInsertion.ahk" {IHandwrittenTextInsertion}
#Import export ".\IInk.ahk" {IInk}
#Import export ".\IInkCollector.ahk" {IInkCollector}
#Import export ".\IInkCursor.ahk" {IInkCursor}
#Import export ".\IInkCursorButton.ahk" {IInkCursorButton}
#Import export ".\IInkCursorButtons.ahk" {IInkCursorButtons}
#Import export ".\IInkCursors.ahk" {IInkCursors}
#Import export ".\IInkCustomStrokes.ahk" {IInkCustomStrokes}
#Import export ".\IInkDisp.ahk" {IInkDisp}
#Import export ".\IInkDivider.ahk" {IInkDivider}
#Import export ".\IInkDivisionResult.ahk" {IInkDivisionResult}
#Import export ".\IInkDivisionUnit.ahk" {IInkDivisionUnit}
#Import export ".\IInkDivisionUnits.ahk" {IInkDivisionUnits}
#Import export ".\IInkDrawingAttributes.ahk" {IInkDrawingAttributes}
#Import export ".\IInkEdit.ahk" {IInkEdit}
#Import export ".\IInkExtendedProperties.ahk" {IInkExtendedProperties}
#Import export ".\IInkExtendedProperty.ahk" {IInkExtendedProperty}
#Import export ".\IInkGesture.ahk" {IInkGesture}
#Import export ".\IInkLineInfo.ahk" {IInkLineInfo}
#Import export ".\IInkOverlay.ahk" {IInkOverlay}
#Import export ".\IInkPicture.ahk" {IInkPicture}
#Import export ".\IInkRecognitionAlternate.ahk" {IInkRecognitionAlternate}
#Import export ".\IInkRecognitionAlternates.ahk" {IInkRecognitionAlternates}
#Import export ".\IInkRecognitionResult.ahk" {IInkRecognitionResult}
#Import export ".\IInkRecognizer.ahk" {IInkRecognizer}
#Import export ".\IInkRecognizer2.ahk" {IInkRecognizer2}
#Import export ".\IInkRecognizerContext.ahk" {IInkRecognizerContext}
#Import export ".\IInkRecognizerContext2.ahk" {IInkRecognizerContext2}
#Import export ".\IInkRecognizerGuide.ahk" {IInkRecognizerGuide}
#Import export ".\IInkRecognizers.ahk" {IInkRecognizers}
#Import export ".\IInkRectangle.ahk" {IInkRectangle}
#Import export ".\IInkRenderer.ahk" {IInkRenderer}
#Import export ".\IInkStrokeDisp.ahk" {IInkStrokeDisp}
#Import export ".\IInkStrokes.ahk" {IInkStrokes}
#Import export ".\IInkTablet.ahk" {IInkTablet}
#Import export ".\IInkTablet2.ahk" {IInkTablet2}
#Import export ".\IInkTablet3.ahk" {IInkTablet3}
#Import export ".\IInkTablets.ahk" {IInkTablets}
#Import export ".\IInkTransform.ahk" {IInkTransform}
#Import export ".\IInkWordList.ahk" {IInkWordList}
#Import export ".\IInkWordList2.ahk" {IInkWordList2}
#Import export ".\IInputPanelWindowHandle.ahk" {IInputPanelWindowHandle}
#Import export ".\IMathInputControl.ahk" {IMathInputControl}
#Import export ".\INKMETRIC.ahk" {INKMETRIC}
#Import export ".\INK_METRIC_FLAGS.ahk" {INK_METRIC_FLAGS}
#Import export ".\IPenInputPanel.ahk" {IPenInputPanel}
#Import export ".\IRealTimeStylus.ahk" {IRealTimeStylus}
#Import export ".\IRealTimeStylus2.ahk" {IRealTimeStylus2}
#Import export ".\IRealTimeStylus3.ahk" {IRealTimeStylus3}
#Import export ".\IRealTimeStylusSynchronization.ahk" {IRealTimeStylusSynchronization}
#Import export ".\ISketchInk.ahk" {ISketchInk}
#Import export ".\IStrokeBuilder.ahk" {IStrokeBuilder}
#Import export ".\IStylusAsyncPlugin.ahk" {IStylusAsyncPlugin}
#Import export ".\IStylusPlugin.ahk" {IStylusPlugin}
#Import export ".\IStylusSyncPlugin.ahk" {IStylusSyncPlugin}
#Import export ".\ITextInputPanel.ahk" {ITextInputPanel}
#Import export ".\ITextInputPanelEventSink.ahk" {ITextInputPanelEventSink}
#Import export ".\ITextInputPanelRunInfo.ahk" {ITextInputPanelRunInfo}
#Import export ".\ITipAutoCompleteClient.ahk" {ITipAutoCompleteClient}
#Import export ".\ITipAutoCompleteProvider.ahk" {ITipAutoCompleteProvider}
#Import export ".\InPlaceDirection.ahk" {InPlaceDirection}
#Import export ".\InPlaceState.ahk" {InPlaceState}
#Import export ".\Ink.ahk" {Ink}
#Import export ".\InkApplicationGesture.ahk" {InkApplicationGesture}
#Import export ".\InkBoundingBoxMode.ahk" {InkBoundingBoxMode}
#Import export ".\InkClipboardFormats.ahk" {InkClipboardFormats}
#Import export ".\InkClipboardModes.ahk" {InkClipboardModes}
#Import export ".\InkCollectionMode.ahk" {InkCollectionMode}
#Import export ".\InkCollector.ahk" {InkCollector}
#Import export ".\InkCollectorEventInterest.ahk" {InkCollectorEventInterest}
#Import export ".\InkCursorButtonState.ahk" {InkCursorButtonState}
#Import export ".\InkDisp.ahk" {InkDisp}
#Import export ".\InkDisplayMode.ahk" {InkDisplayMode}
#Import export ".\InkDivider.ahk" {InkDivider}
#Import export ".\InkDivisionType.ahk" {InkDivisionType}
#Import export ".\InkDrawingAttributes.ahk" {InkDrawingAttributes}
#Import export ".\InkEdit.ahk" {InkEdit}
#Import export ".\InkEditStatus.ahk" {InkEditStatus}
#Import export ".\InkExtractFlags.ahk" {InkExtractFlags}
#Import export ".\InkInsertMode.ahk" {InkInsertMode}
#Import export ".\InkMode.ahk" {InkMode}
#Import export ".\InkMouseButton.ahk" {InkMouseButton}
#Import export ".\InkMousePointer.ahk" {InkMousePointer}
#Import export ".\InkOverlay.ahk" {InkOverlay}
#Import export ".\InkOverlayAttachMode.ahk" {InkOverlayAttachMode}
#Import export ".\InkOverlayEditingMode.ahk" {InkOverlayEditingMode}
#Import export ".\InkOverlayEraserMode.ahk" {InkOverlayEraserMode}
#Import export ".\InkPenTip.ahk" {InkPenTip}
#Import export ".\InkPersistenceCompressionMode.ahk" {InkPersistenceCompressionMode}
#Import export ".\InkPersistenceFormat.ahk" {InkPersistenceFormat}
#Import export ".\InkPicture.ahk" {InkPicture}
#Import export ".\InkPictureSizeMode.ahk" {InkPictureSizeMode}
#Import export ".\InkRasterOperation.ahk" {InkRasterOperation}
#Import export ".\InkRecoGuide.ahk" {InkRecoGuide}
#Import export ".\InkRecognitionAlternatesSelection.ahk" {InkRecognitionAlternatesSelection}
#Import export ".\InkRecognitionConfidence.ahk" {InkRecognitionConfidence}
#Import export ".\InkRecognitionModes.ahk" {InkRecognitionModes}
#Import export ".\InkRecognitionStatus.ahk" {InkRecognitionStatus}
#Import export ".\InkRecognizerCapabilities.ahk" {InkRecognizerCapabilities}
#Import export ".\InkRecognizerCharacterAutoCompletionMode.ahk" {InkRecognizerCharacterAutoCompletionMode}
#Import export ".\InkRecognizerContext.ahk" {InkRecognizerContext}
#Import export ".\InkRecognizerGuide.ahk" {InkRecognizerGuide}
#Import export ".\InkRecognizers.ahk" {InkRecognizers}
#Import export ".\InkRectangle.ahk" {InkRectangle}
#Import export ".\InkRenderer.ahk" {InkRenderer}
#Import export ".\InkSelectionConstants.ahk" {InkSelectionConstants}
#Import export ".\InkShiftKeyModifierFlags.ahk" {InkShiftKeyModifierFlags}
#Import export ".\InkStrokes.ahk" {InkStrokes}
#Import export ".\InkSystemGesture.ahk" {InkSystemGesture}
#Import export ".\InkTablets.ahk" {InkTablets}
#Import export ".\InkTransform.ahk" {InkTransform}
#Import export ".\InkWordList.ahk" {InkWordList}
#Import export ".\InteractionMode.ahk" {InteractionMode}
#Import export ".\KEYMODIFIER.ahk" {KEYMODIFIER}
#Import export ".\LATTICE_METRICS.ahk" {LATTICE_METRICS}
#Import export ".\LINE_METRICS.ahk" {LINE_METRICS}
#Import export ".\LINE_SEGMENT.ahk" {LINE_SEGMENT}
#Import export ".\MICUIELEMENT.ahk" {MICUIELEMENT}
#Import export ".\MICUIELEMENTSTATE.ahk" {MICUIELEMENTSTATE}
#Import export ".\MathInputControl.ahk" {MathInputControl}
#Import export ".\MouseButton.ahk" {MouseButton}
#Import export ".\PACKET_DESCRIPTION.ahk" {PACKET_DESCRIPTION}
#Import export ".\PACKET_PROPERTY.ahk" {PACKET_PROPERTY}
#Import export ".\PROPERTY_METRICS.ahk" {PROPERTY_METRICS}
#Import export ".\PROPERTY_UNITS.ahk" {PROPERTY_UNITS}
#Import export ".\PanelInputArea.ahk" {PanelInputArea}
#Import export ".\PanelType.ahk" {PanelType}
#Import export ".\PenInputPanel.ahk" {PenInputPanel}
#Import export ".\PenInputPanel_Internal.ahk" {PenInputPanel_Internal}
#Import export ".\PfnRecoCallback.ahk" {PfnRecoCallback}
#Import export ".\RECO_ATTRS.ahk" {RECO_ATTRS}
#Import export ".\RECO_GUIDE.ahk" {RECO_GUIDE}
#Import export ".\RECO_LATTICE.ahk" {RECO_LATTICE}
#Import export ".\RECO_LATTICE_COLUMN.ahk" {RECO_LATTICE_COLUMN}
#Import export ".\RECO_LATTICE_ELEMENT.ahk" {RECO_LATTICE_ELEMENT}
#Import export ".\RECO_LATTICE_PROPERTIES.ahk" {RECO_LATTICE_PROPERTIES}
#Import export ".\RECO_LATTICE_PROPERTY.ahk" {RECO_LATTICE_PROPERTY}
#Import export ".\RECO_RANGE.ahk" {RECO_RANGE}
#Import export ".\RECO_TYPE.ahk" {RECO_TYPE}
#Import export ".\RealTimeStylus.ahk" {RealTimeStylus}
#Import export ".\RealTimeStylusDataInterest.ahk" {RealTimeStylusDataInterest}
#Import export ".\RealTimeStylusLockType.ahk" {RealTimeStylusLockType}
#Import export ".\SCROLLDIRECTION.ahk" {SCROLLDIRECTION}
#Import export ".\STROKE_RANGE.ahk" {STROKE_RANGE}
#Import export ".\SYSTEM_EVENT_DATA.ahk" {SYSTEM_EVENT_DATA}
#Import export ".\ScrollBarsConstants.ahk" {ScrollBarsConstants}
#Import export ".\SelAlignmentConstants.ahk" {SelAlignmentConstants}
#Import export ".\SelectionHitResult.ahk" {SelectionHitResult}
#Import export ".\SketchInk.ahk" {SketchInk}
#Import export ".\StrokeBuilder.ahk" {StrokeBuilder}
#Import export ".\StylusInfo.ahk" {StylusInfo}
#Import export ".\StylusQueue.ahk" {StylusQueue}
#Import export ".\TabletDeviceKind.ahk" {TabletDeviceKind}
#Import export ".\TabletHardwareCapabilities.ahk" {TabletHardwareCapabilities}
#Import export ".\TabletPropertyMetricUnit.ahk" {TabletPropertyMetricUnit}
#Import export ".\TextInputPanel.ahk" {TextInputPanel}
#Import export ".\TipAutoCompleteClient.ahk" {TipAutoCompleteClient}
#Import export ".\VisualState.ahk" {VisualState}
#Import export ".\_IInkCollectorEvents.ahk" {_IInkCollectorEvents}
#Import export ".\_IInkEditEvents.ahk" {_IInkEditEvents}
#Import export ".\_IInkEvents.ahk" {_IInkEvents}
#Import export ".\_IInkOverlayEvents.ahk" {_IInkOverlayEvents}
#Import export ".\_IInkPictureEvents.ahk" {_IInkPictureEvents}
#Import export ".\_IInkRecognitionEvents.ahk" {_IInkRecognitionEvents}
#Import export ".\_IInkStrokesEvents.ahk" {_IInkStrokesEvents}
#Import export ".\_IMathInputControlEvents.ahk" {_IMathInputControlEvents}
#Import export ".\_IPenInputPanelEvents.ahk" {_IPenInputPanelEvents}
