#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_AV1_CODEC_CONFIGURATION.ahk" { D3D12_VIDEO_ENCODER_AV1_CODEC_CONFIGURATION }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC.ahk" { D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC }
#Import ".\D3D12_VIDEO_ENCODER_PROFILE_HEVC.ahk" { D3D12_VIDEO_ENCODER_PROFILE_HEVC }
#Import ".\D3D12_VIDEO_ENCODER_INPUT_MAP_SOURCE.ahk" { D3D12_VIDEO_ENCODER_INPUT_MAP_SOURCE }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP }
#Import ".\D3D12_VIDEO_ENCODER_LEVELS_H264.ahk" { D3D12_VIDEO_ENCODER_LEVELS_H264 }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION.ahk" { D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_SUBREGION_LAYOUT_MODE.ahk" { D3D12_VIDEO_ENCODER_FRAME_SUBREGION_LAYOUT_MODE }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_TILES.ahk" { D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_TILES }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_H264.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_H264 }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_ANALYSIS_CONFIGURATION.ahk" { D3D12_VIDEO_ENCODER_FRAME_ANALYSIS_CONFIGURATION }
#Import ".\D3D12_VIDEO_ENCODER_LEVEL_TIER_CONSTRAINTS_HEVC.ahk" { D3D12_VIDEO_ENCODER_LEVEL_TIER_CONSTRAINTS_HEVC }
#Import ".\D3D12_VIDEO_ENCODER_PROFILE_DESC.ahk" { D3D12_VIDEO_ENCODER_PROFILE_DESC }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR1 }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_ABSOLUTE_QP_MAP.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_ABSOLUTE_QP_MAP }
#Import "..\..\Graphics\Dxgi\Common\DXGI_FORMAT.ahk" { DXGI_FORMAT }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA }
#Import ".\D3D12_VIDEO_ENCODER_PROFILE_H264.ahk" { D3D12_VIDEO_ENCODER_PROFILE_H264 }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264.ahk" { D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264 }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_SLICES.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_SLICES }
#Import "..\..\Graphics\Dxgi\Common\DXGI_RATIONAL.ahk" { DXGI_RATIONAL }
#Import ".\D3D12_VIDEO_ENCODER_DIRTY_REGIONS_CONFIGURATION.ahk" { D3D12_VIDEO_ENCODER_DIRTY_REGIONS_CONFIGURATION }
#Import ".\D3D12_FEATURE_DATA_VIDEO_ENCODER_RESOLUTION_SUPPORT_LIMITS1.ahk" { D3D12_FEATURE_DATA_VIDEO_ENCODER_RESOLUTION_SUPPORT_LIMITS1 }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR1 }
#Import ".\D3D12_VIDEO_ENCODER_INTRA_REFRESH_MODE.ahk" { D3D12_VIDEO_ENCODER_INTRA_REFRESH_MODE }
#Import ".\D3D12_VIDEO_ENCODER_QPMAP_CONFIGURATION.ahk" { D3D12_VIDEO_ENCODER_QPMAP_CONFIGURATION }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_FLAGS.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_VALIDATION_FLAGS.ahk" { D3D12_VIDEO_ENCODER_VALIDATION_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE }
#Import ".\D3D12_VIDEO_ENCODER_LEVEL_SETTING.ahk" { D3D12_VIDEO_ENCODER_LEVEL_SETTING }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC.ahk" { D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PROFILE.ahk" { D3D12_VIDEO_ENCODER_AV1_PROFILE }
#Import ".\D3D12_VIDEO_ENCODER_CODEC.ahk" { D3D12_VIDEO_ENCODER_CODEC }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP1 }
#Import ".\D3D12_VIDEO_ENCODER_AV1_SEQUENCE_STRUCTURE.ahk" { D3D12_VIDEO_ENCODER_AV1_SEQUENCE_STRUCTURE }
#Import "..\..\Foundation\BOOL.ahk" { BOOL }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CONFIGURATION_PARAMS.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CONFIGURATION_PARAMS }
#Import ".\D3D12_VIDEO_ENCODER_SUPPORT_FLAGS.ahk" { D3D12_VIDEO_ENCODER_SUPPORT_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE.ahk" { D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE }
#Import ".\D3D12_VIDEO_ENCODER_AV1_LEVEL_TIER_CONSTRAINTS.ahk" { D3D12_VIDEO_ENCODER_AV1_LEVEL_TIER_CONSTRAINTS }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR1 }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_MODE.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_MODE }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR }
#Import ".\D3D12_VIDEO_ENCODER_MOTION_SEARCH_CONFIGURATION.ahk" { D3D12_VIDEO_ENCODER_MOTION_SEARCH_CONFIGURATION }
#Import ".\D3D12_VIDEO_ENCODER_DIRTY_REGIONS_MAP_VALUES_MODE.ahk" { D3D12_VIDEO_ENCODER_DIRTY_REGIONS_MAP_VALUES_MODE }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_FEATURE_DATA_VIDEO_ENCODER_SUPPORT2 {
    #StructPack 8

    NodeIndex : UInt32

    Codec : D3D12_VIDEO_ENCODER_CODEC

    InputFormat : DXGI_FORMAT

    CodecConfiguration : D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION

    CodecGopSequence : D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE

    RateControl : D3D12_VIDEO_ENCODER_RATE_CONTROL

    IntraRefresh : D3D12_VIDEO_ENCODER_INTRA_REFRESH_MODE

    SubregionFrameEncoding : D3D12_VIDEO_ENCODER_FRAME_SUBREGION_LAYOUT_MODE

    ResolutionsListCount : UInt32

    pResolutionList : D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC.Ptr

    MaxReferenceFramesInDPB : UInt32

    ValidationFlags : D3D12_VIDEO_ENCODER_VALIDATION_FLAGS

    SupportFlags : D3D12_VIDEO_ENCODER_SUPPORT_FLAGS

    SuggestedProfile : D3D12_VIDEO_ENCODER_PROFILE_DESC

    SuggestedLevel : D3D12_VIDEO_ENCODER_LEVEL_SETTING

    pResolutionDependentSupport : D3D12_FEATURE_DATA_VIDEO_ENCODER_RESOLUTION_SUPPORT_LIMITS1.Ptr

    SubregionFrameEncodingData : D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA

    MaxQualityVsSpeed : UInt32

    QPMap : D3D12_VIDEO_ENCODER_QPMAP_CONFIGURATION

    DirtyRegions : D3D12_VIDEO_ENCODER_DIRTY_REGIONS_CONFIGURATION

    MotionSearch : D3D12_VIDEO_ENCODER_MOTION_SEARCH_CONFIGURATION

    FrameAnalysis : D3D12_VIDEO_ENCODER_FRAME_ANALYSIS_CONFIGURATION

}
