#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264 }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA.ahk" { D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC2.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC2 }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA1 {
    #StructPack 8

    DataSize : UInt32

    pH264PicData : D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264.Ptr

    static __New() {
        DefineProp(this.Prototype, 'pHEVCPicData', { type: D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC2.Ptr, offset: 8 })
        DefineProp(this.Prototype, 'pAV1PicData', { type: D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA.Ptr, offset: 8 })
        this.DeleteProp("__New")
    }
}
