#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import "..\..\Graphics\Direct3D12\ID3D12Fence.ahk" { ID3D12Fence }
#Import ".\D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM.ahk" { D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM }
#Import ".\D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM_NOTIFICATION_MODE.ahk" { D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM_NOTIFICATION_MODE }
#Import ".\D3D12_VIDEO_ENCODER_SUBREGION_COMPRESSED_BITSTREAM_BUFFER_MODE.ahk" { D3D12_VIDEO_ENCODER_SUBREGION_COMPRESSED_BITSTREAM_BUFFER_MODE }
#Import "..\..\Graphics\Direct3D12\ID3D12Resource.ahk" { ID3D12Resource }
#Import ".\D3D12_VIDEO_ENCODER_SUBREGION_COMPRESSED_BITSTREAM.ahk" { D3D12_VIDEO_ENCODER_SUBREGION_COMPRESSED_BITSTREAM }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM1 {
    #StructPack 8

    NotificationMode : D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM_NOTIFICATION_MODE

    FrameOutputBuffer : D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM

    static __New() {
        DefineProp(this.Prototype, 'SubregionOutputBuffers', { type: D3D12_VIDEO_ENCODER_SUBREGION_COMPRESSED_BITSTREAM, offset: 8 })
        this.DeleteProp("__New")
    }
}
