#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import "..\..\Graphics\Direct3D12\ID3D12Fence.ahk" { ID3D12Fence }
#Import ".\D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM.ahk" { D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM }
#Import ".\D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM_NOTIFICATION_MODE.ahk" { D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM_NOTIFICATION_MODE }
#Import ".\D3D12_VIDEO_ENCODER_ENCODE_OPERATION_METADATA_BUFFER.ahk" { D3D12_VIDEO_ENCODER_ENCODE_OPERATION_METADATA_BUFFER }
#Import ".\D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM1.ahk" { D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM1 }
#Import ".\D3D12_VIDEO_ENCODER_RECONSTRUCTED_PICTURE.ahk" { D3D12_VIDEO_ENCODER_RECONSTRUCTED_PICTURE }
#Import ".\D3D12_VIDEO_ENCODER_SUBREGION_COMPRESSED_BITSTREAM_BUFFER_MODE.ahk" { D3D12_VIDEO_ENCODER_SUBREGION_COMPRESSED_BITSTREAM_BUFFER_MODE }
#Import "..\..\Graphics\Direct3D12\ID3D12Resource.ahk" { ID3D12Resource }
#Import ".\D3D12_VIDEO_ENCODER_SUBREGION_COMPRESSED_BITSTREAM.ahk" { D3D12_VIDEO_ENCODER_SUBREGION_COMPRESSED_BITSTREAM }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_ENCODEFRAME_OUTPUT_ARGUMENTS1 {
    #StructPack 8

    Bitstream : D3D12_VIDEO_ENCODER_COMPRESSED_BITSTREAM1

    ReconstructedPicture : D3D12_VIDEO_ENCODER_RECONSTRUCTED_PICTURE

    EncoderOutputMetadata : D3D12_VIDEO_ENCODER_ENCODE_OPERATION_METADATA_BUFFER

    FrameAnalysisReconstructedPicture : D3D12_VIDEO_ENCODER_RECONSTRUCTED_PICTURE

}
