#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_SLICES.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_SLICES }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA1.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA1 }
#Import ".\D3D12_VIDEO_ENCODER_INPUT_MAP_SOURCE.ahk" { D3D12_VIDEO_ENCODER_INPUT_MAP_SOURCE }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_SUBREGION_LAYOUT_MODE.ahk" { D3D12_VIDEO_ENCODER_FRAME_SUBREGION_LAYOUT_MODE }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC2.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC2 }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_ANALYSIS.ahk" { D3D12_VIDEO_ENCODER_FRAME_ANALYSIS }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP1 }
#Import ".\D3D12_VIDEO_ENCODER_QUANTIZATION_OPAQUE_MAP.ahk" { D3D12_VIDEO_ENCODER_QUANTIZATION_OPAQUE_MAP }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC.ahk" { D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR }
#Import "..\..\Graphics\Direct3D12\ID3D12Resource.ahk" { ID3D12Resource }
#Import ".\D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.ahk" { D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS }
#Import ".\D3D12_VIDEO_ENCODE_REFERENCE_FRAMES.ahk" { D3D12_VIDEO_ENCODE_REFERENCE_FRAMES }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC }
#Import ".\D3D12_VIDEO_ENCODER_DIRTY_REGIONS.ahk" { D3D12_VIDEO_ENCODER_DIRTY_REGIONS }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR1 }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL }
#Import ".\D3D12_VIDEO_ENCODER_INTRA_REFRESH_MODE.ahk" { D3D12_VIDEO_ENCODER_INTRA_REFRESH_MODE }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_FLAGS.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264 }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA.ahk" { D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR1 }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_H264.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_H264 }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_TILES.ahk" { D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_TILES }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_FLAGS.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_DESC1.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_DESC1 }
#Import ".\D3D12_VIDEO_ENCODER_DIRTY_RECT_INFO.ahk" { D3D12_VIDEO_ENCODER_DIRTY_RECT_INFO }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_MODE.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_MODE }
#Import ".\D3D12_VIDEO_ENCODER_AV1_SEQUENCE_STRUCTURE.ahk" { D3D12_VIDEO_ENCODER_AV1_SEQUENCE_STRUCTURE }
#Import ".\D3D12_VIDEO_ENCODER_INTRA_REFRESH.ahk" { D3D12_VIDEO_ENCODER_INTRA_REFRESH }
#Import ".\D3D12_VIDEO_ENCODER_MOVEREGION_INFO.ahk" { D3D12_VIDEO_ENCODER_MOVEREGION_INFO }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR1 }
#Import "..\..\Graphics\Dxgi\Common\DXGI_RATIONAL.ahk" { DXGI_RATIONAL }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_MOTION_VECTORS.ahk" { D3D12_VIDEO_ENCODER_FRAME_MOTION_VECTORS }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_ABSOLUTE_QP_MAP.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_ABSOLUTE_QP_MAP }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CONFIGURATION_PARAMS.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CONFIGURATION_PARAMS }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_DESC.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_DESC }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_ENCODEFRAME_INPUT_ARGUMENTS1 {
    #StructPack 8

    SequenceControlDesc : D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_DESC

    PictureControlDesc : D3D12_VIDEO_ENCODER_PICTURE_CONTROL_DESC1

    pInputFrame : ID3D12Resource

    InputFrameSubresource : UInt32

    CurrentFrameBitstreamMetadataSize : UInt32

    OptionalMetadata : D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS

}
