#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION.ahk" { D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264 }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA.ahk" { D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA1.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA1 }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE_CONFIG.ahk" { D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE.ahk" { D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC2.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC2 }
#Import "..\..\Graphics\Direct3D12\ID3D12Resource.ahk" { ID3D12Resource }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_MOTION_VECTORS {
    #StructPack 8

    MotionSearchModeConfiguration : D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE_CONFIG

    NumHintsPerPixel : UInt32

    ppMotionVectorMaps : ID3D12Resource.Ptr

    pMotionVectorMapsSubresources : IntPtr

    ppMotionVectorMapsMetadata : ID3D12Resource.Ptr

    pMotionVectorMapsMetadataSubresources : IntPtr

    MotionUnitPrecision : D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION

    PictureControlConfiguration : D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA1

}
