#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import "..\..\Foundation\BOOL.ahk" { BOOL }
#Import ".\D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE.ahk" { D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE }
#Import ".\D3D12_VIDEO_ENCODER_AV1_REFERENCE_PICTURE_WARPED_MOTION_INFO.ahk" { D3D12_VIDEO_ENCODER_AV1_REFERENCE_PICTURE_WARPED_MOTION_INFO }
#Import ".\D3D12_VIDEO_ENCODER_AV1_REFERENCE_WARPED_MOTION_TRANSFORMATION.ahk" { D3D12_VIDEO_ENCODER_AV1_REFERENCE_WARPED_MOTION_TRANSFORMATION }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_AV1_REFERENCE_PICTURE_DESCRIPTOR {
    #StructPack 4

    ReconstructedPictureResourceIndex : UInt32

    TemporalLayerIndexPlus1 : UInt32

    SpatialLayerIndexPlus1 : UInt32

    FrameType : D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE

    WarpedMotionInfo : D3D12_VIDEO_ENCODER_AV1_REFERENCE_PICTURE_WARPED_MOTION_INFO

    OrderHint : UInt32

    PictureIndex : UInt32

}
