#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_AV1_REFERENCE_WARPED_MOTION_TRANSFORMATION_FLAGS.ahk" { D3D12_VIDEO_ENCODER_AV1_REFERENCE_WARPED_MOTION_TRANSFORMATION_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS.ahk" { D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_AV1_COMP_PREDICTION_TYPE.ahk" { D3D12_VIDEO_ENCODER_AV1_COMP_PREDICTION_TYPE }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_CODEC_AV1_PICTURE_CONTROL_SUPPORT {
    #StructPack 4

    PredictionMode : D3D12_VIDEO_ENCODER_AV1_COMP_PREDICTION_TYPE

    MaxUniqueReferencesPerFrame : UInt32

    SupportedFrameTypes : D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE_FLAGS

    SupportedReferenceWarpedMotionFlags : D3D12_VIDEO_ENCODER_AV1_REFERENCE_WARPED_MOTION_TRANSFORMATION_FLAGS

}
