#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import "..\..\Graphics\Dxgi\Common\DXGI_FORMAT.ahk" { DXGI_FORMAT }
#Import ".\D3D12_VIDEO_ENCODER_CODEC.ahk" { D3D12_VIDEO_ENCODER_CODEC }
#Import ".\D3D12_VIDEO_ENCODER_AV1_CODEC_CONFIGURATION.ahk" { D3D12_VIDEO_ENCODER_AV1_CODEC_CONFIGURATION }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC.ahk" { D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_HEVC }
#Import ".\D3D12_VIDEO_ENCODER_PROFILE_DESC.ahk" { D3D12_VIDEO_ENCODER_PROFILE_DESC }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION.ahk" { D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC.ahk" { D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC }
#Import "..\..\Foundation\BOOL.ahk" { BOOL }
#Import ".\D3D12_VIDEO_ENCODER_PROFILE_H264.ahk" { D3D12_VIDEO_ENCODER_PROFILE_H264 }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264.ahk" { D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION_H264 }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PROFILE.ahk" { D3D12_VIDEO_ENCODER_AV1_PROFILE }
#Import ".\D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS.ahk" { D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_PROFILE_HEVC.ahk" { D3D12_VIDEO_ENCODER_PROFILE_HEVC }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_FEATURE_DATA_VIDEO_ENCODER_RESOURCE_REQUIREMENTS1 {
    #StructPack 8

    NodeIndex : UInt32

    Codec : D3D12_VIDEO_ENCODER_CODEC

    Profile : D3D12_VIDEO_ENCODER_PROFILE_DESC

    InputFormat : DXGI_FORMAT

    PictureTargetResolution : D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC

    IsSupported : BOOL

    CompressedBitstreamBufferAccessAlignment : UInt32

    EncoderMetadataBufferAccessAlignment : UInt32

    MaxEncoderOutputMetadataBufferSize : UInt32

    OptionalMetadata : D3D12_VIDEO_ENCODER_OPTIONAL_METADATA_ENABLE_FLAGS

    CodecConfiguration : D3D12_VIDEO_ENCODER_CODEC_CONFIGURATION

    EncoderOutputMetadataQPMapTextureDimensions : D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC

    EncoderOutputMetadataSATDMapTextureDimensions : D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC

    EncoderOutputMetadataBitAllocationMapTextureDimensions : D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC

    EncoderOutputMetadataFramePSNRComponentsNumber : UInt32

    EncoderOutputMetadataSubregionsPSNRComponentsNumber : UInt32

    EncoderOutputMetadataSubregionsPSNRResolvedMetadataBufferSize : UInt32

}
