#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_AV1_RESTORATION_TILESIZE.ahk" { D3D12_VIDEO_ENCODER_AV1_RESTORATION_TILESIZE }
#Import ".\D3D12_VIDEO_ENCODER_AV1_RESTORATION_TYPE.ahk" { D3D12_VIDEO_ENCODER_AV1_RESTORATION_TYPE }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_AV1_RESTORATION_CONFIG {
    #StructPack 4

    FrameRestorationType : D3D12_VIDEO_ENCODER_AV1_RESTORATION_TYPE[3]

    LoopRestorationPixelSize : D3D12_VIDEO_ENCODER_AV1_RESTORATION_TILESIZE[3]

}
