#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_DIRTY_REGIONS_MAP_VALUES_MODE.ahk" { D3D12_VIDEO_ENCODER_DIRTY_REGIONS_MAP_VALUES_MODE }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE.ahk" { D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA1.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA1 }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264 }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION.ahk" { D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION }
#Import "..\..\Foundation\BOOL.ahk" { BOOL }
#Import ".\D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_DIRTY_REGIONS.ahk" { D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_DIRTY_REGIONS }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE_CONFIG.ahk" { D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA.ahk" { D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA }
#Import "..\..\Graphics\Direct3D12\ID3D12Resource.ahk" { ID3D12Resource }
#Import ".\D3D12_VIDEO_ENCODER_INPUT_MAP_TYPE.ahk" { D3D12_VIDEO_ENCODER_INPUT_MAP_TYPE }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC2.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC2 }
#Import ".\D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_QUANTIZATION_MATRIX.ahk" { D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_QUANTIZATION_MATRIX }
#Import ".\D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_MOTION_VECTORS.ahk" { D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_MOTION_VECTORS }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_INPUT_MAP_DATA {
    #StructPack 8

    MapType : D3D12_VIDEO_ENCODER_INPUT_MAP_TYPE

    Quantization : D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_QUANTIZATION_MATRIX

    static __New() {
        DefineProp(this.Prototype, 'DirtyRegions', { type: D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_DIRTY_REGIONS, offset: 8 })
        DefineProp(this.Prototype, 'MotionVectors', { type: D3D12_VIDEO_ENCODER_INPUT_MAP_DATA_MOTION_VECTORS, offset: 8 })
        this.DeleteProp("__New")
    }
}
