#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC.ahk" { D3D12_VIDEO_ENCODER_PICTURE_RESOLUTION_DESC }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_SUBREGION_LAYOUT_MODE.ahk" { D3D12_VIDEO_ENCODER_FRAME_SUBREGION_LAYOUT_MODE }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_TILES.ahk" { D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_TILES }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_H264.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_H264 }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_FLAGS.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR1 }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC1.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC1 }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_ABSOLUTE_QP_MAP.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_ABSOLUTE_QP_MAP }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_SLICES.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_SUBREGIONS_LAYOUT_DATA_SLICES }
#Import ".\D3D12_VIDEO_ENCODER_INTRA_REFRESH.ahk" { D3D12_VIDEO_ENCODER_INTRA_REFRESH }
#Import "..\..\Graphics\Dxgi\Common\DXGI_RATIONAL.ahk" { DXGI_RATIONAL }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR1 }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_DESC.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_DESC }
#Import ".\D3D12_VIDEO_ENCODER_INTRA_REFRESH_MODE.ahk" { D3D12_VIDEO_ENCODER_INTRA_REFRESH_MODE }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_FLAGS.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264 }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_DESC.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_DESC }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CQP1 }
#Import ".\D3D12_VIDEO_ENCODER_AV1_SEQUENCE_STRUCTURE.ahk" { D3D12_VIDEO_ENCODER_AV1_SEQUENCE_STRUCTURE }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA.ahk" { D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA }
#Import ".\D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC.ahk" { D3D12_VIDEO_ENCODER_SEQUENCE_GOP_STRUCTURE_HEVC }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CONFIGURATION_PARAMS.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CONFIGURATION_PARAMS }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR1.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_VBR1 }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_MODE.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_MODE }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_CBR }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL_QVBR }
#Import "..\..\Graphics\Direct3D12\ID3D12Resource.ahk" { ID3D12Resource }
#Import ".\D3D12_VIDEO_ENCODE_REFERENCE_FRAMES.ahk" { D3D12_VIDEO_ENCODE_REFERENCE_FRAMES }
#Import ".\D3D12_VIDEO_ENCODER_RATE_CONTROL.ahk" { D3D12_VIDEO_ENCODER_RATE_CONTROL }

/**
 * Represents input arguments to ID3D12VideoEncodeCommandList2::EncodeFrame.
 * @see https://learn.microsoft.com/windows/win32/api/d3d12video/ns-d3d12video-d3d12_video_encoder_encodeframe_input_arguments
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_ENCODEFRAME_INPUT_ARGUMENTS {
    #StructPack 8

    /**
     * A [D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_DESC](ns-d3d12video-d3d12_video_encoder_sequence_control_desc.md) specifying the configuration for the video sequence
     */
    SequenceControlDesc : D3D12_VIDEO_ENCODER_SEQUENCE_CONTROL_DESC

    /**
     * A [D3D12_VIDEO_ENCODER_PICTURE_CONTROL_DESC](ns-d3d12video-d3d12_video_encoder_picture_control_desc.md) specifying the configuration for the video picture.
     */
    PictureControlDesc : D3D12_VIDEO_ENCODER_PICTURE_CONTROL_DESC

    /**
     * An [ID3D12Resource](../d3d12/nn-d3d12-id3d12resource) representing the frame to encode.
     */
    pInputFrame : ID3D12Resource

    /**
     * A UINT64 specifying the subresource index for *pInputFrame*.
     */
    InputFrameSubresource : UInt32

    /**
     * A UINT64 specifying the number of bytes added to the final bitstream between the end of the last **EncodeFrame** compressed bitstream output and the current call output. This is intended to capture the size of any headers or metadata messages added by the client to the final bitstream which are used as a hint by the rate control algorithms to keep track of the full bitstream size.
     */
    CurrentFrameBitstreamMetadataSize : UInt32

}
