#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION.ahk" { D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE_CONFIG.ahk" { D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE.ahk" { D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE }
#Import ".\D3D12_VIDEO_ENCODER_MOVEREGION_INFO_FLAGS.ahk" { D3D12_VIDEO_ENCODER_MOVEREGION_INFO_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_MOVE_RECT.ahk" { D3D12_VIDEO_ENCODER_MOVE_RECT }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_MOVEREGION_INFO {
    #StructPack 8

    NumMoveRegions : UInt32

    pMoveRegions : D3D12_VIDEO_ENCODER_MOVE_RECT.Ptr

    MotionSearchModeConfiguration : D3D12_VIDEO_ENCODER_FRAME_MOTION_SEARCH_MODE_CONFIG

    SourceDPBFrameReference : UInt32

    MotionUnitPrecision : D3D12_VIDEO_ENCODER_FRAME_INPUT_MOTION_UNIT_PRECISION

    Flags : D3D12_VIDEO_ENCODER_MOVEREGION_INFO_FLAGS

}
