#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_AV1_REFERENCE_PICTURE_DESCRIPTOR.ahk" { D3D12_VIDEO_ENCODER_AV1_REFERENCE_PICTURE_DESCRIPTOR }
#Import ".\D3D12_VIDEO_ENCODER_AV1_TX_MODE.ahk" { D3D12_VIDEO_ENCODER_AV1_TX_MODE }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS.ahk" { D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_AV1_RESTORATION_TILESIZE.ahk" { D3D12_VIDEO_ENCODER_AV1_RESTORATION_TILESIZE }
#Import ".\D3D12_VIDEO_ENCODER_AV1_SEGMENT_DATA.ahk" { D3D12_VIDEO_ENCODER_AV1_SEGMENT_DATA }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_DELTA_CONFIG.ahk" { D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_DELTA_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE.ahk" { D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE }
#Import ".\D3D12_VIDEO_ENCODER_AV1_REFERENCE_WARPED_MOTION_TRANSFORMATION.ahk" { D3D12_VIDEO_ENCODER_AV1_REFERENCE_WARPED_MOTION_TRANSFORMATION }
#Import ".\D3D12_VIDEO_ENCODER_AV1_CDEF_CONFIG.ahk" { D3D12_VIDEO_ENCODER_AV1_CDEF_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_AV1_COMP_PREDICTION_TYPE.ahk" { D3D12_VIDEO_ENCODER_AV1_COMP_PREDICTION_TYPE }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_CONFIG.ahk" { D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS.ahk" { D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_CONFIG.ahk" { D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_CONFIG.ahk" { D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_AV1_RESTORATION_CONFIG.ahk" { D3D12_VIDEO_ENCODER_AV1_RESTORATION_CONFIG }
#Import "..\..\Foundation\BOOL.ahk" { BOOL }
#Import ".\D3D12_VIDEO_ENCODER_AV1_REFERENCE_PICTURE_WARPED_MOTION_INFO.ahk" { D3D12_VIDEO_ENCODER_AV1_REFERENCE_PICTURE_WARPED_MOTION_INFO }
#Import ".\D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MAP.ahk" { D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MAP }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_DELTA_CONFIG.ahk" { D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_DELTA_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_AV1_RESTORATION_TYPE.ahk" { D3D12_VIDEO_ENCODER_AV1_RESTORATION_TYPE }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA {
    #StructPack 8

    Flags : D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_FLAGS

    FrameType : D3D12_VIDEO_ENCODER_AV1_FRAME_TYPE

    CompoundPredictionType : D3D12_VIDEO_ENCODER_AV1_COMP_PREDICTION_TYPE

    InterpolationFilter : D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS

    FrameRestorationConfig : D3D12_VIDEO_ENCODER_AV1_RESTORATION_CONFIG

    TxMode : D3D12_VIDEO_ENCODER_AV1_TX_MODE

    SuperResDenominator : UInt32

    OrderHint : UInt32

    PictureIndex : UInt32

    TemporalLayerIndexPlus1 : UInt32

    SpatialLayerIndexPlus1 : UInt32

    ReferenceFramesReconPictureDescriptors : D3D12_VIDEO_ENCODER_AV1_REFERENCE_PICTURE_DESCRIPTOR[8]

    ReferenceIndices : UInt32[7]

    PrimaryRefFrame : UInt32

    RefreshFrameFlags : UInt32

    LoopFilter : D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_CONFIG

    LoopFilterDelta : D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_DELTA_CONFIG

    Quantization : D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_CONFIG

    QuantizationDelta : D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_DELTA_CONFIG

    CDEF : D3D12_VIDEO_ENCODER_AV1_CDEF_CONFIG

    QPMapValuesCount : UInt32

    pRateControlQPMap : IntPtr

    CustomSegmentation : D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_CONFIG

    CustomSegmentsMap : D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MAP

}
