#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS.ahk" { D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS.ahk" { D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_AV1_RESTORATION_SUPPORT_FLAGS.ahk" { D3D12_VIDEO_ENCODER_AV1_RESTORATION_SUPPORT_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS.ahk" { D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS.ahk" { D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_AV1_TX_MODE_FLAGS.ahk" { D3D12_VIDEO_ENCODER_AV1_TX_MODE_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE.ahk" { D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_AV1_CODEC_CONFIGURATION_SUPPORT {
    #StructPack 4

    SupportedFeatureFlags : D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS

    RequiredFeatureFlags : D3D12_VIDEO_ENCODER_AV1_FEATURE_FLAGS

    SupportedInterpolationFilters : D3D12_VIDEO_ENCODER_AV1_INTERPOLATION_FILTERS_FLAGS

    SupportedRestorationParams : D3D12_VIDEO_ENCODER_AV1_RESTORATION_SUPPORT_FLAGS[9]

    SupportedSegmentationModes : D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_MODE_FLAGS

    SupportedTxModes : D3D12_VIDEO_ENCODER_AV1_TX_MODE_FLAGS[4]

    SegmentationBlockSize : D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_BLOCK_SIZE

    PostEncodeValuesFlags : D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES_FLAGS

    MaxTemporalLayers : UInt32

    MaxSpatialLayers : UInt32

}
