#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_INPUT_MAP_SOURCE.ahk" { D3D12_VIDEO_ENCODER_INPUT_MAP_SOURCE }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA1.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA1 }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_H264 }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_ANALYSIS.ahk" { D3D12_VIDEO_ENCODER_FRAME_ANALYSIS }
#Import ".\D3D12_VIDEO_ENCODE_REFERENCE_FRAMES.ahk" { D3D12_VIDEO_ENCODE_REFERENCE_FRAMES }
#Import ".\D3D12_VIDEO_ENCODER_DIRTY_RECT_INFO.ahk" { D3D12_VIDEO_ENCODER_DIRTY_RECT_INFO }
#Import ".\D3D12_VIDEO_ENCODER_MOVEREGION_INFO.ahk" { D3D12_VIDEO_ENCODER_MOVEREGION_INFO }
#Import ".\D3D12_VIDEO_ENCODER_QUANTIZATION_OPAQUE_MAP.ahk" { D3D12_VIDEO_ENCODER_QUANTIZATION_OPAQUE_MAP }
#Import ".\D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA.ahk" { D3D12_VIDEO_ENCODER_AV1_PICTURE_CONTROL_CODEC_DATA }
#Import "..\..\Graphics\Direct3D12\ID3D12Resource.ahk" { ID3D12Resource }
#Import ".\D3D12_VIDEO_ENCODER_FRAME_MOTION_VECTORS.ahk" { D3D12_VIDEO_ENCODER_FRAME_MOTION_VECTORS }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC2.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA_HEVC2 }
#Import ".\D3D12_VIDEO_ENCODER_PICTURE_CONTROL_FLAGS.ahk" { D3D12_VIDEO_ENCODER_PICTURE_CONTROL_FLAGS }
#Import ".\D3D12_VIDEO_ENCODER_DIRTY_REGIONS.ahk" { D3D12_VIDEO_ENCODER_DIRTY_REGIONS }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_PICTURE_CONTROL_DESC1 {
    #StructPack 8

    IntraRefreshFrameIndex : UInt32

    Flags : D3D12_VIDEO_ENCODER_PICTURE_CONTROL_FLAGS

    PictureControlCodecData : D3D12_VIDEO_ENCODER_PICTURE_CONTROL_CODEC_DATA1

    ReferenceFrames : D3D12_VIDEO_ENCODE_REFERENCE_FRAMES

    MotionVectors : D3D12_VIDEO_ENCODER_FRAME_MOTION_VECTORS

    DirtyRects : D3D12_VIDEO_ENCODER_DIRTY_REGIONS

    QuantizationTextureMap : D3D12_VIDEO_ENCODER_QUANTIZATION_OPAQUE_MAP

    FrameAnalysis : D3D12_VIDEO_ENCODER_FRAME_ANALYSIS

}
