#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_CONFIG.ahk" { D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_AV1_CDEF_CONFIG.ahk" { D3D12_VIDEO_ENCODER_AV1_CDEF_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_CONFIG.ahk" { D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_DELTA_CONFIG.ahk" { D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_DELTA_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_DELTA_CONFIG.ahk" { D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_DELTA_CONFIG }
#Import ".\D3D12_VIDEO_ENCODER_AV1_SEGMENT_DATA.ahk" { D3D12_VIDEO_ENCODER_AV1_SEGMENT_DATA }
#Import ".\D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_CONFIG.ahk" { D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_CONFIG }

/**
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct D3D12_VIDEO_ENCODER_AV1_POST_ENCODE_VALUES {
    #StructPack 8

    CompoundPredictionType : Int64

    LoopFilter : D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_CONFIG

    LoopFilterDelta : D3D12_VIDEO_ENCODER_CODEC_AV1_LOOP_FILTER_DELTA_CONFIG

    Quantization : D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_CONFIG

    QuantizationDelta : D3D12_VIDEO_ENCODER_CODEC_AV1_QUANTIZATION_DELTA_CONFIG

    CDEF : D3D12_VIDEO_ENCODER_AV1_CDEF_CONFIG

    SegmentationConfig : D3D12_VIDEO_ENCODER_AV1_SEGMENTATION_CONFIG

    PrimaryRefFrame : Int64

    ReferenceIndices : Int64[7]

}
