#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32ComInterface.ahk
#Include ..\..\..\..\Guid.ahk
#Include .\IMFAttributes.ahk

/**
 * Represents an event generated by a Media Foundation object. Use this interface to get information about the event.
 * @remarks
 * 
  * If you are implementing an object that generates events, call the <a href="https://docs.microsoft.com/windows/desktop/api/mfapi/nf-mfapi-mfcreatemediaevent">MFCreateMediaEvent</a> function to create a new event object.
  * 
  * This interface is available on the following platforms if the Windows Media Format 11 SDK redistributable components are installed:
  * 
  * <ul>
  * <li>Windows XP with Service Pack 2 (SP2) and later.</li>
  * <li>Windows XP Media Center Edition 2005 with KB900325 (Windows XP Media Center Edition 2005) and KB925766 (October 2006 Update Rollup for Windows XP Media Center Edition) installed.</li>
  * </ul>
  * 
  * 
 * @see https://docs.microsoft.com/windows/win32/api//mfobjects/nn-mfobjects-imfmediaevent
 * @namespace Windows.Win32.Media.MediaFoundation
 * @version v4.0.30319
 */
class IMFMediaEvent extends IMFAttributes{

    static sizeof => A_PtrSize
    /**
     * The interface identifier for IMFMediaEvent
     * @type {Guid}
     */
    static IID => Guid("{df598932-f10c-4e39-bba2-c308f101daa3}")

    /**
     * The offset into the COM object's virtual function table at which this interface's methods begin.
     * @type {Integer}
     */
    static vTableOffset => 33

    /**
     * @readonly used when implementing interfaces to order function pointers
     * @type {Array<String>}
     */
    static VTableNames => ["GetType", "GetExtendedType", "GetStatus", "GetValue"]

    /**
     * 
     * @param {Pointer<Integer>} pmet 
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/windows/win32/api/mfobjects/nf-mfobjects-imfmediaevent-gettype
     */
    GetType(pmet) {
        pmetMarshal := pmet is VarRef ? "uint*" : "ptr"

        result := ComCall(33, this, pmetMarshal, pmet, "HRESULT")
        return result
    }

    /**
     * 
     * @param {Pointer<Guid>} pguidExtendedType 
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/windows/win32/api/mfobjects/nf-mfobjects-imfmediaevent-getextendedtype
     */
    GetExtendedType(pguidExtendedType) {
        result := ComCall(34, this, "ptr", pguidExtendedType, "HRESULT")
        return result
    }

    /**
     * 
     * @param {Pointer<HRESULT>} phrStatus 
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/windows/win32/api/mfobjects/nf-mfobjects-imfmediaevent-getstatus
     */
    GetStatus(phrStatus) {
        result := ComCall(35, this, "ptr", phrStatus, "HRESULT")
        return result
    }

    /**
     * 
     * @param {Pointer<PROPVARIANT>} pvValue 
     * @returns {HRESULT} 
     * @see https://learn.microsoft.com/windows/win32/api/mfobjects/nf-mfobjects-imfmediaevent-getvalue
     */
    GetValue(pvValue) {
        result := ComCall(36, this, "ptr", pvValue, "HRESULT")
        return result
    }
}
