#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\Guid.ahk" { Guid }
#Import ".\IMFTimedTextBinary.ahk" { IMFTimedTextBinary }
#Import ".\IMFTimedTextFormattedText.ahk" { IMFTimedTextFormattedText }
#Import "..\..\Foundation\PWSTR.ahk" { PWSTR }
#Import ".\MF_TIMED_TEXT_TRACK_KIND.ahk" { MF_TIMED_TEXT_TRACK_KIND }
#Import ".\IMFTimedTextRegion.ahk" { IMFTimedTextRegion }
#Import "..\..\Foundation\HRESULT.ahk" { HRESULT }
#Import ".\IMFTimedTextStyle.ahk" { IMFTimedTextStyle }
#Import "..\..\System\Com\IUnknown.ahk" { IUnknown }

/**
 * Represents the timed-text-cue object.
 * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nn-mfmediaengine-imftimedtextcue
 * @namespace Windows.Win32.Media.MediaFoundation
 */
export default struct IMFTimedTextCue extends IUnknown {
    /**
     * The interface identifier for IMFTimedTextCue
     * @type {Guid}
     */
    static IID := Guid("{1e560447-9a2b-43e1-a94c-b0aaabfbfbc9}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for IMFTimedTextCue interfaces
    */
    struct Vtbl extends IUnknown.Vtbl {
        GetId         : IntPtr
        GetOriginalId : IntPtr
        GetCueKind    : IntPtr
        GetStartTime  : IntPtr
        GetDuration   : IntPtr
        GetTrackId    : IntPtr
        GetData       : IntPtr
        GetRegion     : IntPtr
        GetStyle      : IntPtr
        GetLineCount  : IntPtr
        GetLine       : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := IMFTimedTextCue.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * Gets the identifier of a timed-text cue.
     * @remarks
     * The identifier is retrieved by this method is dynamically generated by the system and is guaranteed to uniquely identify a cue within a single timed-text track. It is not guaranteed to be unique across tracks. If a cue already has an identifier that is provided in the text-track data format, this ID can be retrieved by calling <a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getoriginalid">GetOriginalId</a>.
     * @returns {Integer} Type: <b>DWORD
     * </b>
     * 
     * The identifier of a timed-text cue.
     * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getid
     */
    GetId() {
        result := ComCall(3, this, UInt32)
        return result
    }

    /**
     * Gets the cue identifier that is provided in the text-track data format, if available.
     * @remarks
     * This method retrieves an identifier for the cue that is included in the source data, if one was specified. The system dynamically generates identifiers for cues that are guaranteed to be unique within a single time-text track. To obtain this system-generated ID, call <a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getid">GetId</a>.
     * @returns {PWSTR} Type: <b>LPWSTR*</b>
     * 
     * The cue identifier that is provided in the text-track data format.
     * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getoriginalid
     */
    GetOriginalId() {
        result := ComCall(4, this, PWSTR.Ptr, &originalId := 0, "HRESULT")
        return originalId
    }

    /**
     * Gets the kind of timed-text cue.
     * @returns {MF_TIMED_TEXT_TRACK_KIND} Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/ne-mfmediaengine-mf_timed_text_track_kind">MF_TIMED_TEXT_TRACK_KIND</a></b>
     * 
     * Returns a <a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/ne-mfmediaengine-mf_timed_text_track_kind">MF_TIMED_TEXT_TRACK_KIND</a>-typed value that specifies the kind of timed-text cue.
     * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getcuekind
     */
    GetCueKind() {
        result := ComCall(5, this, MF_TIMED_TEXT_TRACK_KIND)
        return result
    }

    /**
     * Gets the start time of the cue in the track.
     * @returns {Float} Type: <b>double</b>
     * 
     * Returns the start time of the cue in the track.
     * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getstarttime
     */
    GetStartTime() {
        result := ComCall(6, this, Float64)
        return result
    }

    /**
     * Gets the duration time of the cue in the track.
     * @returns {Float} Type: <b>double</b>
     * 
     * Returns the duration time of the cue in the track.
     * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getduration
     */
    GetDuration() {
        result := ComCall(7, this, Float64)
        return result
    }

    /**
     * Gets the identifier of the timed-text cue.
     * @returns {Integer} Type: <b>DWORD</b>
     * 
     * Returns the identifier of the timed-text cue.
     * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-gettrackid
     */
    GetTrackId() {
        result := ComCall(8, this, UInt32)
        return result
    }

    /**
     * Gets the data content of the timed-text cue.
     * @returns {IMFTimedTextBinary} Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/nn-mfmediaengine-imftimedtextbinary">IMFTimedTextBinary</a>**</b>
     * 
     * A pointer to a memory block that receives a pointer to the <a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/nn-mfmediaengine-imftimedtextbinary">IMFTimedTextBinary</a> interface for the data content of the timed-text cue. This parameter can be <b>NULL</b>.
     * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getdata
     */
    GetData() {
        result := ComCall(9, this, "ptr*", &data := 0, "HRESULT")
        return IMFTimedTextBinary(data)
    }

    /**
     * Gets info about the display region of the timed-text cue.
     * @returns {IMFTimedTextRegion} Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/nn-mfmediaengine-imftimedtextregion">IMFTimedTextRegion</a>**</b>
     * 
     * A pointer to a memory block that receives a pointer to the <a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/nn-mfmediaengine-imftimedtextregion">IMFTimedTextRegion</a> interface for the timed-text region. This parameter can be <b>NULL</b>.
     * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getregion
     */
    GetRegion() {
        result := ComCall(10, this, "ptr*", &_region := 0, "HRESULT")
        return IMFTimedTextRegion(_region)
    }

    /**
     * Gets info about the style of the timed-text cue.
     * @returns {IMFTimedTextStyle} Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/nn-mfmediaengine-imftimedtextstyle">IMFTimedTextStyle</a>**</b>
     * 
     * A pointer to a memory block that receives a pointer to the <a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/nn-mfmediaengine-imftimedtextstyle">IMFTimedTextStyle</a> interface for the timed-text style. This parameter can be <b>NULL</b>.
     * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getstyle
     */
    GetStyle() {
        result := ComCall(11, this, "ptr*", &style := 0, "HRESULT")
        return IMFTimedTextStyle(style)
    }

    /**
     * Gets the number of lines of text in the timed-text cue.
     * @returns {Integer} Type: <b>DWORD</b>
     * 
     * Returns the number of lines of text.
     * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getlinecount
     */
    GetLineCount() {
        result := ComCall(12, this, UInt32)
        return result
    }

    /**
     * Gets a line of text in the cue from the index of the line.
     * @param {Integer} index Type: <b>DWORD</b>
     * 
     * The index of the line of text in the cue to retrieve.
     * @returns {IMFTimedTextFormattedText} Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/nn-mfmediaengine-imftimedtextformattedtext">IMFTimedTextFormattedText</a>**</b>
     * 
     * A pointer to a memory block that receives a pointer to the <a href="https://docs.microsoft.com/windows/desktop/api/mfmediaengine/nn-mfmediaengine-imftimedtextformattedtext">IMFTimedTextFormattedText</a> interface for the line of text in the cue.
     * @see https://learn.microsoft.com/windows/win32/api/mfmediaengine/nf-mfmediaengine-imftimedtextcue-getline
     */
    GetLine(index) {
        result := ComCall(13, this, "uint", index, "ptr*", &line := 0, "HRESULT")
        return IMFTimedTextFormattedText(line)
    }

    Query(iid) {
        if (IMFTimedTextCue.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.GetId := CallbackCreate(GetMethod(implObj, "GetId"), flags, 1)
        this.vtbl.GetOriginalId := CallbackCreate(GetMethod(implObj, "GetOriginalId"), flags, 2)
        this.vtbl.GetCueKind := CallbackCreate(GetMethod(implObj, "GetCueKind"), flags, 1)
        this.vtbl.GetStartTime := CallbackCreate(GetMethod(implObj, "GetStartTime"), flags, 1)
        this.vtbl.GetDuration := CallbackCreate(GetMethod(implObj, "GetDuration"), flags, 1)
        this.vtbl.GetTrackId := CallbackCreate(GetMethod(implObj, "GetTrackId"), flags, 1)
        this.vtbl.GetData := CallbackCreate(GetMethod(implObj, "GetData"), flags, 2)
        this.vtbl.GetRegion := CallbackCreate(GetMethod(implObj, "GetRegion"), flags, 2)
        this.vtbl.GetStyle := CallbackCreate(GetMethod(implObj, "GetStyle"), flags, 2)
        this.vtbl.GetLineCount := CallbackCreate(GetMethod(implObj, "GetLineCount"), flags, 1)
        this.vtbl.GetLine := CallbackCreate(GetMethod(implObj, "GetLine"), flags, 3)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.GetId)
        CallbackFree(this.vtbl.GetOriginalId)
        CallbackFree(this.vtbl.GetCueKind)
        CallbackFree(this.vtbl.GetStartTime)
        CallbackFree(this.vtbl.GetDuration)
        CallbackFree(this.vtbl.GetTrackId)
        CallbackFree(this.vtbl.GetData)
        CallbackFree(this.vtbl.GetRegion)
        CallbackFree(this.vtbl.GetStyle)
        CallbackFree(this.vtbl.GetLineCount)
        CallbackFree(this.vtbl.GetLine)
    }
}
