#Requires AutoHotkey v2.1-alpha.30+ 64-bit
#Import "..\..\..\..\Win32ComInterface.ahk" { Win32ComInterface }
#Import "..\..\..\..\Guid.ahk" { Guid }
#Import "..\..\Foundation\PWSTR.ahk" { PWSTR }
#Import "..\..\Foundation\HRESULT.ahk" { HRESULT }
#Import ".\INetDiagHelperUtilFactory.ahk" { INetDiagHelperUtilFactory }
#Import "..\..\System\Com\IUnknown.ahk" { IUnknown }
#Import ".\HypothesisResult.ahk" { HypothesisResult }
#Import ".\DIAGNOSIS_STATUS.ahk" { DIAGNOSIS_STATUS }

/**
 * Provides methods that extend on the INetDiagHelper interface to capture and provide information associated with diagnoses and resolution of network-related issues.
 * @see https://learn.microsoft.com/windows/win32/api/ndhelper/nn-ndhelper-inetdiaghelperex
 * @namespace Windows.Win32.NetworkManagement.NetworkDiagnosticsFramework
 */
export default struct INetDiagHelperEx extends IUnknown {
    /**
     * The interface identifier for INetDiagHelperEx
     * @type {Guid}
     */
    static IID := Guid("{972dab4d-e4e3-4fc6-ae54-5f65ccde4a15}")

    static __New() {
        ; Retype our prototype's vtable pointer to be our vtbl's type
        DefineProp(this.Prototype, 'vtbl', { type: this.Vtbl.Ptr, offset: 0 })
        this.DeleteProp("__New")
    }

    /**
     * The {@link https://devblogs.microsoft.com/oldnewthing/20040205-00/?p=40733 Virtual Function Table}
     * used for INetDiagHelperEx interfaces
    */
    struct Vtbl extends IUnknown.Vtbl {
        ReconfirmLowHealth : IntPtr
        SetUtilities       : IntPtr
        ReproduceFailure   : IntPtr
    }

    __New(implObj := 0, flags := "") {
        if (NumGet(ObjGetDataPtr(this), 0, "ptr") == 0) {
            this.vtbl := INetDiagHelperEx.Vtbl()
        }
        super.__New(implObj, flags)
    }

    /**
     * Used to add a second Low Health pass after hypotheses have been diagnosed and before repairs are retrieved.
     * @remarks
     * This method is not required when building a Helper Class Extension.
     * @param {Integer} celt The number of <a href="https://docs.microsoft.com/windows/desktop/api/ndhelper/ns-ndhelper-hypothesisresult">HypothesisResult</a> structures pointed to by <i>pResults</i>.
     * @param {Pointer<HypothesisResult>} pResults Pointer to <a href="https://docs.microsoft.com/windows/desktop/api/ndhelper/ns-ndhelper-hypothesisresult">HypothesisResult</a> structure(s) containing the <a href="https://docs.microsoft.com/windows/desktop/api/ndhelper/ns-ndhelper-hypothesis">HYPOTHESIS</a> information obtained via the <a href="https://docs.microsoft.com/windows/desktop/api/ndhelper/nf-ndhelper-inetdiaghelper-getlowerhypotheses">GetLowerHypotheses</a> method along with the status of that hypothesis. Includes one <b>HypothesisResult</b> structure for each hypothesis generated by the helper class's call to <b>GetLowerHypotheses</b>.
     * @param {Pointer<PWSTR>} ppwszUpdatedDescription An updated description of the incident being diagnosed.
     * @param {Pointer<DIAGNOSIS_STATUS>} pUpdatedStatus A <a href="https://docs.microsoft.com/windows/desktop/api/ndhelper/ne-ndhelper-diagnosis_status">DIAGNOSIS_STATUS</a> value which indicates the status of the incident.
     * @returns {HRESULT} Possible return values include, but are not limited to, the following.
     * 
     * <table>
     * <tr>
     * <th>Return code</th>
     * <th>Description</th>
     * </tr>
     * <tr>
     * <td width="40%">
     * <dl>
     * <dt><b>S_OK</b></dt>
     * </dl>
     * </td>
     * <td width="60%">
     * The operation succeeded.
     * 
     * </td>
     * </tr>
     * </table>
     *  
     * 
     * Any result other than S_OK will be interpreted as an error and will cause the function results to be discarded.
     * @see https://learn.microsoft.com/windows/win32/api/ndhelper/nf-ndhelper-inetdiaghelperex-reconfirmlowhealth
     */
    ReconfirmLowHealth(celt, pResults, ppwszUpdatedDescription, pUpdatedStatus) {
        ppwszUpdatedDescriptionMarshal := ppwszUpdatedDescription is VarRef ? "ptr*" : "ptr"
        pUpdatedStatusMarshal := pUpdatedStatus is VarRef ? "int*" : "ptr"

        result := ComCall(3, this, "uint", celt, HypothesisResult.Ptr, pResults, ppwszUpdatedDescriptionMarshal, ppwszUpdatedDescription, pUpdatedStatusMarshal, pUpdatedStatus, "HRESULT")
        return result
    }

    /**
     * Used by the Network Diagnostics Framework (NDF). This method is reserved for system use. (INetDiagHelperEx.SetUtilities)
     * @remarks
     * This method  is reserved for system use.
     * @param {INetDiagHelperUtilFactory} pUtilities Reserved for system use.
     * @returns {HRESULT} This method does not return a value.
     * @see https://learn.microsoft.com/windows/win32/api/ndhelper/nf-ndhelper-inetdiaghelperex-setutilities
     */
    SetUtilities(pUtilities) {
        result := ComCall(4, this, "ptr", pUtilities, "HRESULT")
        return result
    }

    /**
     * Used by the Network Diagnostics Framework (NDF). This method is reserved for system use. (INetDiagHelperEx.ReproduceFailure)
     * @remarks
     * This method is reserved for system use.
     * @returns {HRESULT} This method does not return a value.
     * @see https://learn.microsoft.com/windows/win32/api/ndhelper/nf-ndhelper-inetdiaghelperex-reproducefailure
     */
    ReproduceFailure() {
        result := ComCall(5, this, "HRESULT")
        return result
    }

    Query(iid) {
        if (INetDiagHelperEx.IID.Equals(iid)) {
            return true
        }
        return super.Query(iid)
    }

    Implement(implObj, flags := "") {
        super.Implement(implObj, flags)
        this.vtbl.ReconfirmLowHealth := CallbackCreate(GetMethod(implObj, "ReconfirmLowHealth"), flags, 5)
        this.vtbl.SetUtilities := CallbackCreate(GetMethod(implObj, "SetUtilities"), flags, 2)
        this.vtbl.ReproduceFailure := CallbackCreate(GetMethod(implObj, "ReproduceFailure"), flags, 1)
    }

    Dispose() {
        if (!this.owned) {
            throw MethodError("Cannot dispose of an unowned interface", -1, this)
        }
        super.Dispose()
        CallbackFree(this.vtbl.ReconfirmLowHealth)
        CallbackFree(this.vtbl.SetUtilities)
        CallbackFree(this.vtbl.ReproduceFailure)
    }
}
