#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Constants.ahk" {*}
#Import export ".\QStatus.ahk" {QStatus}
#Import export ".\alljoyn_about_announced_ptr.ahk" {alljoyn_about_announced_ptr}
#Import export ".\alljoyn_about_announceflag.ahk" {alljoyn_about_announceflag}
#Import export ".\alljoyn_aboutdata.ahk" {alljoyn_aboutdata}
#Import export ".\alljoyn_aboutdatalistener.ahk" {alljoyn_aboutdatalistener}
#Import export ".\alljoyn_aboutdatalistener_callbacks.ahk" {alljoyn_aboutdatalistener_callbacks}
#Import export ".\alljoyn_aboutdatalistener_getaboutdata_ptr.ahk" {alljoyn_aboutdatalistener_getaboutdata_ptr}
#Import export ".\alljoyn_aboutdatalistener_getannouncedaboutdata_ptr.ahk" {alljoyn_aboutdatalistener_getannouncedaboutdata_ptr}
#Import export ".\alljoyn_abouticon.ahk" {alljoyn_abouticon}
#Import export ".\alljoyn_abouticonobj.ahk" {alljoyn_abouticonobj}
#Import export ".\alljoyn_abouticonproxy.ahk" {alljoyn_abouticonproxy}
#Import export ".\alljoyn_aboutlistener.ahk" {alljoyn_aboutlistener}
#Import export ".\alljoyn_aboutlistener_callback.ahk" {alljoyn_aboutlistener_callback}
#Import export ".\alljoyn_aboutobj.ahk" {alljoyn_aboutobj}
#Import export ".\alljoyn_aboutobjectdescription.ahk" {alljoyn_aboutobjectdescription}
#Import export ".\alljoyn_aboutproxy.ahk" {alljoyn_aboutproxy}
#Import export ".\alljoyn_applicationstate.ahk" {alljoyn_applicationstate}
#Import export ".\alljoyn_applicationstatelistener.ahk" {alljoyn_applicationstatelistener}
#Import export ".\alljoyn_applicationstatelistener_callbacks.ahk" {alljoyn_applicationstatelistener_callbacks}
#Import export ".\alljoyn_applicationstatelistener_state_ptr.ahk" {alljoyn_applicationstatelistener_state_ptr}
#Import export ".\alljoyn_authlistener.ahk" {alljoyn_authlistener}
#Import export ".\alljoyn_authlistener_authenticationcomplete_ptr.ahk" {alljoyn_authlistener_authenticationcomplete_ptr}
#Import export ".\alljoyn_authlistener_callbacks.ahk" {alljoyn_authlistener_callbacks}
#Import export ".\alljoyn_authlistener_requestcredentials_ptr.ahk" {alljoyn_authlistener_requestcredentials_ptr}
#Import export ".\alljoyn_authlistener_requestcredentialsasync_ptr.ahk" {alljoyn_authlistener_requestcredentialsasync_ptr}
#Import export ".\alljoyn_authlistener_securityviolation_ptr.ahk" {alljoyn_authlistener_securityviolation_ptr}
#Import export ".\alljoyn_authlistener_verifycredentials_ptr.ahk" {alljoyn_authlistener_verifycredentials_ptr}
#Import export ".\alljoyn_authlistener_verifycredentialsasync_ptr.ahk" {alljoyn_authlistener_verifycredentialsasync_ptr}
#Import export ".\alljoyn_authlistenerasync_callbacks.ahk" {alljoyn_authlistenerasync_callbacks}
#Import export ".\alljoyn_autopinger.ahk" {alljoyn_autopinger}
#Import export ".\alljoyn_autopinger_destination_found_ptr.ahk" {alljoyn_autopinger_destination_found_ptr}
#Import export ".\alljoyn_autopinger_destination_lost_ptr.ahk" {alljoyn_autopinger_destination_lost_ptr}
#Import export ".\alljoyn_busattachment.ahk" {alljoyn_busattachment}
#Import export ".\alljoyn_busattachment_joinsessioncb_ptr.ahk" {alljoyn_busattachment_joinsessioncb_ptr}
#Import export ".\alljoyn_busattachment_setlinktimeoutcb_ptr.ahk" {alljoyn_busattachment_setlinktimeoutcb_ptr}
#Import export ".\alljoyn_buslistener.ahk" {alljoyn_buslistener}
#Import export ".\alljoyn_buslistener_bus_disconnected_ptr.ahk" {alljoyn_buslistener_bus_disconnected_ptr}
#Import export ".\alljoyn_buslistener_bus_prop_changed_ptr.ahk" {alljoyn_buslistener_bus_prop_changed_ptr}
#Import export ".\alljoyn_buslistener_bus_stopping_ptr.ahk" {alljoyn_buslistener_bus_stopping_ptr}
#Import export ".\alljoyn_buslistener_callbacks.ahk" {alljoyn_buslistener_callbacks}
#Import export ".\alljoyn_buslistener_found_advertised_name_ptr.ahk" {alljoyn_buslistener_found_advertised_name_ptr}
#Import export ".\alljoyn_buslistener_listener_registered_ptr.ahk" {alljoyn_buslistener_listener_registered_ptr}
#Import export ".\alljoyn_buslistener_listener_unregistered_ptr.ahk" {alljoyn_buslistener_listener_unregistered_ptr}
#Import export ".\alljoyn_buslistener_lost_advertised_name_ptr.ahk" {alljoyn_buslistener_lost_advertised_name_ptr}
#Import export ".\alljoyn_buslistener_name_owner_changed_ptr.ahk" {alljoyn_buslistener_name_owner_changed_ptr}
#Import export ".\alljoyn_busobject.ahk" {alljoyn_busobject}
#Import export ".\alljoyn_busobject_callbacks.ahk" {alljoyn_busobject_callbacks}
#Import export ".\alljoyn_busobject_methodentry.ahk" {alljoyn_busobject_methodentry}
#Import export ".\alljoyn_busobject_object_registration_ptr.ahk" {alljoyn_busobject_object_registration_ptr}
#Import export ".\alljoyn_busobject_prop_get_ptr.ahk" {alljoyn_busobject_prop_get_ptr}
#Import export ".\alljoyn_busobject_prop_set_ptr.ahk" {alljoyn_busobject_prop_set_ptr}
#Import export ".\alljoyn_certificateid.ahk" {alljoyn_certificateid}
#Import export ".\alljoyn_certificateidarray.ahk" {alljoyn_certificateidarray}
#Import export ".\alljoyn_claimcapability_masks.ahk" {alljoyn_claimcapability_masks}
#Import export ".\alljoyn_claimcapabilityadditionalinfo_masks.ahk" {alljoyn_claimcapabilityadditionalinfo_masks}
#Import export ".\alljoyn_credentials.ahk" {alljoyn_credentials}
#Import export ".\alljoyn_interfacedescription.ahk" {alljoyn_interfacedescription}
#Import export ".\alljoyn_interfacedescription_member.ahk" {alljoyn_interfacedescription_member}
#Import export ".\alljoyn_interfacedescription_property.ahk" {alljoyn_interfacedescription_property}
#Import export ".\alljoyn_interfacedescription_securitypolicy.ahk" {alljoyn_interfacedescription_securitypolicy}
#Import export ".\alljoyn_interfacedescription_translation_callback_ptr.ahk" {alljoyn_interfacedescription_translation_callback_ptr}
#Import export ".\alljoyn_keystore.ahk" {alljoyn_keystore}
#Import export ".\alljoyn_keystorelistener.ahk" {alljoyn_keystorelistener}
#Import export ".\alljoyn_keystorelistener_acquireexclusivelock_ptr.ahk" {alljoyn_keystorelistener_acquireexclusivelock_ptr}
#Import export ".\alljoyn_keystorelistener_callbacks.ahk" {alljoyn_keystorelistener_callbacks}
#Import export ".\alljoyn_keystorelistener_loadrequest_ptr.ahk" {alljoyn_keystorelistener_loadrequest_ptr}
#Import export ".\alljoyn_keystorelistener_releaseexclusivelock_ptr.ahk" {alljoyn_keystorelistener_releaseexclusivelock_ptr}
#Import export ".\alljoyn_keystorelistener_storerequest_ptr.ahk" {alljoyn_keystorelistener_storerequest_ptr}
#Import export ".\alljoyn_keystorelistener_with_synchronization_callbacks.ahk" {alljoyn_keystorelistener_with_synchronization_callbacks}
#Import export ".\alljoyn_manifestarray.ahk" {alljoyn_manifestarray}
#Import export ".\alljoyn_message.ahk" {alljoyn_message}
#Import export ".\alljoyn_messagereceiver_methodhandler_ptr.ahk" {alljoyn_messagereceiver_methodhandler_ptr}
#Import export ".\alljoyn_messagereceiver_replyhandler_ptr.ahk" {alljoyn_messagereceiver_replyhandler_ptr}
#Import export ".\alljoyn_messagereceiver_signalhandler_ptr.ahk" {alljoyn_messagereceiver_signalhandler_ptr}
#Import export ".\alljoyn_messagetype.ahk" {alljoyn_messagetype}
#Import export ".\alljoyn_msgarg.ahk" {alljoyn_msgarg}
#Import export ".\alljoyn_observer.ahk" {alljoyn_observer}
#Import export ".\alljoyn_observer_object_discovered_ptr.ahk" {alljoyn_observer_object_discovered_ptr}
#Import export ".\alljoyn_observer_object_lost_ptr.ahk" {alljoyn_observer_object_lost_ptr}
#Import export ".\alljoyn_observerlistener.ahk" {alljoyn_observerlistener}
#Import export ".\alljoyn_observerlistener_callback.ahk" {alljoyn_observerlistener_callback}
#Import export ".\alljoyn_permissionconfigurationlistener.ahk" {alljoyn_permissionconfigurationlistener}
#Import export ".\alljoyn_permissionconfigurationlistener_callbacks.ahk" {alljoyn_permissionconfigurationlistener_callbacks}
#Import export ".\alljoyn_permissionconfigurationlistener_endmanagement_ptr.ahk" {alljoyn_permissionconfigurationlistener_endmanagement_ptr}
#Import export ".\alljoyn_permissionconfigurationlistener_factoryreset_ptr.ahk" {alljoyn_permissionconfigurationlistener_factoryreset_ptr}
#Import export ".\alljoyn_permissionconfigurationlistener_policychanged_ptr.ahk" {alljoyn_permissionconfigurationlistener_policychanged_ptr}
#Import export ".\alljoyn_permissionconfigurationlistener_startmanagement_ptr.ahk" {alljoyn_permissionconfigurationlistener_startmanagement_ptr}
#Import export ".\alljoyn_permissionconfigurator.ahk" {alljoyn_permissionconfigurator}
#Import export ".\alljoyn_pinglistener.ahk" {alljoyn_pinglistener}
#Import export ".\alljoyn_pinglistener_callback.ahk" {alljoyn_pinglistener_callback}
#Import export ".\alljoyn_proxybusobject.ahk" {alljoyn_proxybusobject}
#Import export ".\alljoyn_proxybusobject_listener_getallpropertiescb_ptr.ahk" {alljoyn_proxybusobject_listener_getallpropertiescb_ptr}
#Import export ".\alljoyn_proxybusobject_listener_getpropertycb_ptr.ahk" {alljoyn_proxybusobject_listener_getpropertycb_ptr}
#Import export ".\alljoyn_proxybusobject_listener_introspectcb_ptr.ahk" {alljoyn_proxybusobject_listener_introspectcb_ptr}
#Import export ".\alljoyn_proxybusobject_listener_propertieschanged_ptr.ahk" {alljoyn_proxybusobject_listener_propertieschanged_ptr}
#Import export ".\alljoyn_proxybusobject_listener_setpropertycb_ptr.ahk" {alljoyn_proxybusobject_listener_setpropertycb_ptr}
#Import export ".\alljoyn_proxybusobject_ref.ahk" {alljoyn_proxybusobject_ref}
#Import export ".\alljoyn_securityapplicationproxy.ahk" {alljoyn_securityapplicationproxy}
#Import export ".\alljoyn_sessionlistener.ahk" {alljoyn_sessionlistener}
#Import export ".\alljoyn_sessionlistener_callbacks.ahk" {alljoyn_sessionlistener_callbacks}
#Import export ".\alljoyn_sessionlistener_sessionlost_ptr.ahk" {alljoyn_sessionlistener_sessionlost_ptr}
#Import export ".\alljoyn_sessionlistener_sessionmemberadded_ptr.ahk" {alljoyn_sessionlistener_sessionmemberadded_ptr}
#Import export ".\alljoyn_sessionlistener_sessionmemberremoved_ptr.ahk" {alljoyn_sessionlistener_sessionmemberremoved_ptr}
#Import export ".\alljoyn_sessionlostreason.ahk" {alljoyn_sessionlostreason}
#Import export ".\alljoyn_sessionopts.ahk" {alljoyn_sessionopts}
#Import export ".\alljoyn_sessionportlistener.ahk" {alljoyn_sessionportlistener}
#Import export ".\alljoyn_sessionportlistener_acceptsessionjoiner_ptr.ahk" {alljoyn_sessionportlistener_acceptsessionjoiner_ptr}
#Import export ".\alljoyn_sessionportlistener_callbacks.ahk" {alljoyn_sessionportlistener_callbacks}
#Import export ".\alljoyn_sessionportlistener_sessionjoined_ptr.ahk" {alljoyn_sessionportlistener_sessionjoined_ptr}
#Import export ".\alljoyn_typeid.ahk" {alljoyn_typeid}
