#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\Bitmap.ahk" {Bitmap}
#Import export ".\BitmapData.ahk" {BitmapData}
#Import export ".\Blur.ahk" {Blur}
#Import export ".\BlurParams.ahk" {BlurParams}
#Import export ".\BrightnessContrast.ahk" {BrightnessContrast}
#Import export ".\BrightnessContrastParams.ahk" {BrightnessContrastParams}
#Import export ".\BrushType.ahk" {BrushType}
#Import export ".\CGpEffect.ahk" {CGpEffect}
#Import export ".\CachedBitmap.ahk" {CachedBitmap}
#Import export ".\CharacterRange.ahk" {CharacterRange}
#Import export ".\Color.ahk" {Color}
#Import export ".\ColorAdjustType.ahk" {ColorAdjustType}
#Import export ".\ColorBalance.ahk" {ColorBalance}
#Import export ".\ColorBalanceParams.ahk" {ColorBalanceParams}
#Import export ".\ColorChannelFlags.ahk" {ColorChannelFlags}
#Import export ".\ColorCurve.ahk" {ColorCurve}
#Import export ".\ColorCurveParams.ahk" {ColorCurveParams}
#Import export ".\ColorLUT.ahk" {ColorLUT}
#Import export ".\ColorLUTParams.ahk" {ColorLUTParams}
#Import export ".\ColorMap.ahk" {ColorMap}
#Import export ".\ColorMatrix.ahk" {ColorMatrix}
#Import export ".\ColorMatrixEffect.ahk" {ColorMatrixEffect}
#Import export ".\ColorMatrixFlags.ahk" {ColorMatrixFlags}
#Import export ".\ColorMode.ahk" {ColorMode}
#Import export ".\ColorPalette.ahk" {ColorPalette}
#Import export ".\CombineMode.ahk" {CombineMode}
#Import export ".\CompositingMode.ahk" {CompositingMode}
#Import export ".\CompositingQuality.ahk" {CompositingQuality}
#Import export ".\Constants.ahk" {*}
#Import export ".\ConvertToEmfPlusFlags.ahk" {ConvertToEmfPlusFlags}
#Import export ".\CoordinateSpace.ahk" {CoordinateSpace}
#Import export ".\CurveAdjustments.ahk" {CurveAdjustments}
#Import export ".\CurveChannel.ahk" {CurveChannel}
#Import export ".\CustomLineCap.ahk" {CustomLineCap}
#Import export ".\CustomLineCapType.ahk" {CustomLineCapType}
#Import export ".\DashCap.ahk" {DashCap}
#Import export ".\DashStyle.ahk" {DashStyle}
#Import export ".\DebugEventLevel.ahk" {DebugEventLevel}
#Import export ".\DebugEventProc.ahk" {DebugEventProc}
#Import export ".\DitherType.ahk" {DitherType}
#Import export ".\DrawImageAbort.ahk" {DrawImageAbort}
#Import export ".\DriverStringOptions.ahk" {DriverStringOptions}
#Import export ".\ENHMETAHEADER3.ahk" {ENHMETAHEADER3}
#Import export ".\Effect.ahk" {Effect}
#Import export ".\EmfPlusRecordType.ahk" {EmfPlusRecordType}
#Import export ".\EmfToWmfBitsFlags.ahk" {EmfToWmfBitsFlags}
#Import export ".\EmfType.ahk" {EmfType}
#Import export ".\EncoderParameter.ahk" {EncoderParameter}
#Import export ".\EncoderParameterValueType.ahk" {EncoderParameterValueType}
#Import export ".\EncoderParameters.ahk" {EncoderParameters}
#Import export ".\EncoderValue.ahk" {EncoderValue}
#Import export ".\EnumerateMetafileProc.ahk" {EnumerateMetafileProc}
#Import export ".\FillMode.ahk" {FillMode}
#Import export ".\FlushIntention.ahk" {FlushIntention}
#Import export ".\Font.ahk" {Font}
#Import export ".\FontCollection.ahk" {FontCollection}
#Import export ".\FontFamily.ahk" {FontFamily}
#Import export ".\FontStyle.ahk" {FontStyle}
#Import export ".\GdiplusAbort.ahk" {GdiplusAbort}
#Import export ".\GdiplusStartupInput.ahk" {GdiplusStartupInput}
#Import export ".\GdiplusStartupInputEx.ahk" {GdiplusStartupInputEx}
#Import export ".\GdiplusStartupOutput.ahk" {GdiplusStartupOutput}
#Import export ".\GdiplusStartupParams.ahk" {GdiplusStartupParams}
#Import export ".\GenericFontFamily.ahk" {GenericFontFamily}
#Import export ".\GetThumbnailImageAbort.ahk" {GetThumbnailImageAbort}
#Import export ".\GpAdjustableArrowCap.ahk" {GpAdjustableArrowCap}
#Import export ".\GpBitmap.ahk" {GpBitmap}
#Import export ".\GpBrush.ahk" {GpBrush}
#Import export ".\GpCachedBitmap.ahk" {GpCachedBitmap}
#Import export ".\GpCustomLineCap.ahk" {GpCustomLineCap}
#Import export ".\GpFont.ahk" {GpFont}
#Import export ".\GpFontCollection.ahk" {GpFontCollection}
#Import export ".\GpFontFamily.ahk" {GpFontFamily}
#Import export ".\GpGraphics.ahk" {GpGraphics}
#Import export ".\GpHatch.ahk" {GpHatch}
#Import export ".\GpImage.ahk" {GpImage}
#Import export ".\GpImageAttributes.ahk" {GpImageAttributes}
#Import export ".\GpInstalledFontCollection.ahk" {GpInstalledFontCollection}
#Import export ".\GpLineGradient.ahk" {GpLineGradient}
#Import export ".\GpMetafile.ahk" {GpMetafile}
#Import export ".\GpPath.ahk" {GpPath}
#Import export ".\GpPathGradient.ahk" {GpPathGradient}
#Import export ".\GpPathIterator.ahk" {GpPathIterator}
#Import export ".\GpPen.ahk" {GpPen}
#Import export ".\GpPrivateFontCollection.ahk" {GpPrivateFontCollection}
#Import export ".\GpRegion.ahk" {GpRegion}
#Import export ".\GpSolidFill.ahk" {GpSolidFill}
#Import export ".\GpStringFormat.ahk" {GpStringFormat}
#Import export ".\GpTestControlEnum.ahk" {GpTestControlEnum}
#Import export ".\GpTexture.ahk" {GpTexture}
#Import export ".\HatchStyle.ahk" {HatchStyle}
#Import export ".\HistogramFormat.ahk" {HistogramFormat}
#Import export ".\HotkeyPrefix.ahk" {HotkeyPrefix}
#Import export ".\HueSaturationLightness.ahk" {HueSaturationLightness}
#Import export ".\HueSaturationLightnessParams.ahk" {HueSaturationLightnessParams}
#Import export ".\IImageBytes.ahk" {IImageBytes}
#Import export ".\Image.ahk" {Image}
#Import export ".\ImageAbort.ahk" {ImageAbort}
#Import export ".\ImageCodecFlags.ahk" {ImageCodecFlags}
#Import export ".\ImageCodecInfo.ahk" {ImageCodecInfo}
#Import export ".\ImageFlags.ahk" {ImageFlags}
#Import export ".\ImageItemData.ahk" {ImageItemData}
#Import export ".\ImageLockMode.ahk" {ImageLockMode}
#Import export ".\ImageType.ahk" {ImageType}
#Import export ".\InstalledFontCollection.ahk" {InstalledFontCollection}
#Import export ".\InterpolationMode.ahk" {InterpolationMode}
#Import export ".\ItemDataPosition.ahk" {ItemDataPosition}
#Import export ".\Levels.ahk" {Levels}
#Import export ".\LevelsParams.ahk" {LevelsParams}
#Import export ".\LineCap.ahk" {LineCap}
#Import export ".\LineJoin.ahk" {LineJoin}
#Import export ".\LinearGradientMode.ahk" {LinearGradientMode}
#Import export ".\Matrix.ahk" {Matrix}
#Import export ".\MatrixOrder.ahk" {MatrixOrder}
#Import export ".\Metafile.ahk" {Metafile}
#Import export ".\MetafileFrameUnit.ahk" {MetafileFrameUnit}
#Import export ".\MetafileHeader.ahk" {MetafileHeader}
#Import export ".\MetafileType.ahk" {MetafileType}
#Import export ".\NotificationHookProc.ahk" {NotificationHookProc}
#Import export ".\NotificationUnhookProc.ahk" {NotificationUnhookProc}
#Import export ".\ObjectType.ahk" {ObjectType}
#Import export ".\PWMFRect16.ahk" {PWMFRect16}
#Import export ".\PaletteFlags.ahk" {PaletteFlags}
#Import export ".\PaletteType.ahk" {PaletteType}
#Import export ".\PathData.ahk" {PathData}
#Import export ".\PathPointType.ahk" {PathPointType}
#Import export ".\PenAlignment.ahk" {PenAlignment}
#Import export ".\PenType.ahk" {PenType}
#Import export ".\PixelOffsetMode.ahk" {PixelOffsetMode}
#Import export ".\Point.ahk" {Point}
#Import export ".\PointF.ahk" {PointF}
#Import export ".\PrivateFontCollection.ahk" {PrivateFontCollection}
#Import export ".\PropertyItem.ahk" {PropertyItem}
#Import export ".\QualityMode.ahk" {QualityMode}
#Import export ".\Rect.ahk" {Rect}
#Import export ".\RectF.ahk" {RectF}
#Import export ".\RedEyeCorrection.ahk" {RedEyeCorrection}
#Import export ".\RedEyeCorrectionParams.ahk" {RedEyeCorrectionParams}
#Import export ".\Region.ahk" {Region}
#Import export ".\RotateFlipType.ahk" {RotateFlipType}
#Import export ".\Sharpen.ahk" {Sharpen}
#Import export ".\SharpenParams.ahk" {SharpenParams}
#Import export ".\Size.ahk" {Size}
#Import export ".\SizeF.ahk" {SizeF}
#Import export ".\SmoothingMode.ahk" {SmoothingMode}
#Import export ".\Status.ahk" {Status}
#Import export ".\StringAlignment.ahk" {StringAlignment}
#Import export ".\StringDigitSubstitute.ahk" {StringDigitSubstitute}
#Import export ".\StringFormatFlags.ahk" {StringFormatFlags}
#Import export ".\StringTrimming.ahk" {StringTrimming}
#Import export ".\TextRenderingHint.ahk" {TextRenderingHint}
#Import export ".\Tint.ahk" {Tint}
#Import export ".\TintParams.ahk" {TintParams}
#Import export ".\Unit.ahk" {Unit}
#Import export ".\Version.ahk" {Version}
#Import export ".\WarpMode.ahk" {WarpMode}
#Import export ".\WmfPlaceableFileHeader.ahk" {WmfPlaceableFileHeader}
#Import export ".\WrapMode.ahk" {WrapMode}
