#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Cabinets\__Init.ahk" {*}
#Import export ".\CloudFilters\__Init.ahk" {*}
#Import export ".\Compression\__Init.ahk" {*}
#Import export ".\DataDeduplication\__Init.ahk" {*}
#Import export ".\DistributedFileSystem\__Init.ahk" {*}
#Import export ".\EnhancedStorage\__Init.ahk" {*}
#Import export ".\FileHistory\__Init.ahk" {*}
#Import export ".\FileServerResourceManager\__Init.ahk" {*}
#Import export ".\FileSystem\__Init.ahk" {*}
#Import export ".\Imapi\__Init.ahk" {*}
#Import export ".\IndexServer\__Init.ahk" {*}
#Import export ".\InstallableFileSystems\__Init.ahk" {*}
#Import export ".\IscsiDisc\__Init.ahk" {*}
#Import export ".\Jet\__Init.ahk" {*}
#Import export ".\Nvme\__Init.ahk" {*}
#Import export ".\OfflineFiles\__Init.ahk" {*}
#Import export ".\OperationRecorder\__Init.ahk" {*}
#Import export ".\Packaging\__Init.ahk" {*}
#Import export ".\ProjectedFileSystem\__Init.ahk" {*}
#Import export ".\StructuredStorage\__Init.ahk" {*}
#Import export ".\Vhd\__Init.ahk" {*}
#Import export ".\VirtualDiskService\__Init.ahk" {*}
#Import export ".\Vss\__Init.ahk" {*}
#Import export ".\Xps\__Init.ahk" {*}
