#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\NDIS_OBJECT_HEADER.ahk" { NDIS_OBJECT_HEADER }
#Import ".\NDIS_IPSEC_OFFLOAD_V1.ahk" { NDIS_IPSEC_OFFLOAD_V1 }
#Import ".\NDIS_TCP_LARGE_SEND_OFFLOAD_V2.ahk" { NDIS_TCP_LARGE_SEND_OFFLOAD_V2 }
#Import ".\NDIS_TCP_IP_CHECKSUM_OFFLOAD.ahk" { NDIS_TCP_IP_CHECKSUM_OFFLOAD }
#Import ".\NDIS_TCP_LARGE_SEND_OFFLOAD_V1.ahk" { NDIS_TCP_LARGE_SEND_OFFLOAD_V1 }

/**
 * @namespace Windows.Win32.NetworkManagement.Ndis
 */
export default struct NDIS_OFFLOAD {
    #StructPack 4

    Header : NDIS_OBJECT_HEADER

    Checksum : NDIS_TCP_IP_CHECKSUM_OFFLOAD

    LsoV1 : NDIS_TCP_LARGE_SEND_OFFLOAD_V1

    IPsecV1 : NDIS_IPSEC_OFFLOAD_V1

    LsoV2 : NDIS_TCP_LARGE_SEND_OFFLOAD_V2

    Flags : UInt32

}
