#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\APPDOMAIN_SECURITY_FLAGS.ahk" {APPDOMAIN_SECURITY_FLAGS}
#Import export ".\Apis.ahk" {*}
#Import export ".\AssemblyBindInfo.ahk" {AssemblyBindInfo}
#Import export ".\BucketParameterIndex.ahk" {BucketParameterIndex}
#Import export ".\BucketParameters.ahk" {BucketParameters}
#Import export ".\CLRCreateInstanceFnPtr.ahk" {CLRCreateInstanceFnPtr}
#Import export ".\CLRRuntimeHost.ahk" {CLRRuntimeHost}
#Import export ".\CLR_DEBUGGING_PROCESS_FLAGS.ahk" {CLR_DEBUGGING_PROCESS_FLAGS}
#Import export ".\CLR_DEBUGGING_VERSION.ahk" {CLR_DEBUGGING_VERSION}
#Import export ".\CLSID_RESOLUTION_FLAGS.ahk" {CLSID_RESOLUTION_FLAGS}
#Import export ".\COR_GC_STATS.ahk" {COR_GC_STATS}
#Import export ".\COR_GC_STAT_TYPES.ahk" {COR_GC_STAT_TYPES}
#Import export ".\COR_GC_THREAD_STATS.ahk" {COR_GC_THREAD_STATS}
#Import export ".\COR_GC_THREAD_STATS_TYPES.ahk" {COR_GC_THREAD_STATS_TYPES}
#Import export ".\CallbackThreadSetFnPtr.ahk" {CallbackThreadSetFnPtr}
#Import export ".\CallbackThreadUnsetFnPtr.ahk" {CallbackThreadUnsetFnPtr}
#Import export ".\ComCallUnmarshal.ahk" {ComCallUnmarshal}
#Import export ".\ComCallUnmarshalV4.ahk" {ComCallUnmarshalV4}
#Import export ".\Constants.ahk" {*}
#Import export ".\CorRuntimeHost.ahk" {CorRuntimeHost}
#Import export ".\CreateInterfaceFnPtr.ahk" {CreateInterfaceFnPtr}
#Import export ".\CustomDumpItem.ahk" {CustomDumpItem}
#Import export ".\EApiCategories.ahk" {EApiCategories}
#Import export ".\EBindPolicyLevels.ahk" {EBindPolicyLevels}
#Import export ".\ECLRAssemblyIdentityFlags.ahk" {ECLRAssemblyIdentityFlags}
#Import export ".\EClrEvent.ahk" {EClrEvent}
#Import export ".\EClrFailure.ahk" {EClrFailure}
#Import export ".\EClrOperation.ahk" {EClrOperation}
#Import export ".\EClrUnhandledException.ahk" {EClrUnhandledException}
#Import export ".\EContextType.ahk" {EContextType}
#Import export ".\ECustomDumpFlavor.ahk" {ECustomDumpFlavor}
#Import export ".\ECustomDumpItemKind.ahk" {ECustomDumpItemKind}
#Import export ".\EHostApplicationPolicy.ahk" {EHostApplicationPolicy}
#Import export ".\EHostBindingPolicyModifyFlags.ahk" {EHostBindingPolicyModifyFlags}
#Import export ".\EInitializeNewDomainFlags.ahk" {EInitializeNewDomainFlags}
#Import export ".\EMemoryAvailable.ahk" {EMemoryAvailable}
#Import export ".\EMemoryCriticalLevel.ahk" {EMemoryCriticalLevel}
#Import export ".\EPolicyAction.ahk" {EPolicyAction}
#Import export ".\ESymbolReadingPolicy.ahk" {ESymbolReadingPolicy}
#Import export ".\ETaskType.ahk" {ETaskType}
#Import export ".\FExecuteInAppDomainCallback.ahk" {FExecuteInAppDomainCallback}
#Import export ".\FLockClrVersionCallback.ahk" {FLockClrVersionCallback}
#Import export ".\HOST_TYPE.ahk" {HOST_TYPE}
#Import export ".\IActionOnCLREvent.ahk" {IActionOnCLREvent}
#Import export ".\IApartmentCallback.ahk" {IApartmentCallback}
#Import export ".\IAppDomainBinding.ahk" {IAppDomainBinding}
#Import export ".\ICLRAppDomainResourceMonitor.ahk" {ICLRAppDomainResourceMonitor}
#Import export ".\ICLRAssemblyIdentityManager.ahk" {ICLRAssemblyIdentityManager}
#Import export ".\ICLRAssemblyReferenceList.ahk" {ICLRAssemblyReferenceList}
#Import export ".\ICLRControl.ahk" {ICLRControl}
#Import export ".\ICLRDebugManager.ahk" {ICLRDebugManager}
#Import export ".\ICLRDebugging.ahk" {ICLRDebugging}
#Import export ".\ICLRDebuggingLibraryProvider.ahk" {ICLRDebuggingLibraryProvider}
#Import export ".\ICLRDomainManager.ahk" {ICLRDomainManager}
#Import export ".\ICLRErrorReportingManager.ahk" {ICLRErrorReportingManager}
#Import export ".\ICLRGCManager.ahk" {ICLRGCManager}
#Import export ".\ICLRGCManager2.ahk" {ICLRGCManager2}
#Import export ".\ICLRHostBindingPolicyManager.ahk" {ICLRHostBindingPolicyManager}
#Import export ".\ICLRHostProtectionManager.ahk" {ICLRHostProtectionManager}
#Import export ".\ICLRIoCompletionManager.ahk" {ICLRIoCompletionManager}
#Import export ".\ICLRMemoryNotificationCallback.ahk" {ICLRMemoryNotificationCallback}
#Import export ".\ICLRMetaHost.ahk" {ICLRMetaHost}
#Import export ".\ICLRMetaHostPolicy.ahk" {ICLRMetaHostPolicy}
#Import export ".\ICLROnEventManager.ahk" {ICLROnEventManager}
#Import export ".\ICLRPolicyManager.ahk" {ICLRPolicyManager}
#Import export ".\ICLRProbingAssemblyEnum.ahk" {ICLRProbingAssemblyEnum}
#Import export ".\ICLRProfiling.ahk" {ICLRProfiling}
#Import export ".\ICLRReferenceAssemblyEnum.ahk" {ICLRReferenceAssemblyEnum}
#Import export ".\ICLRRuntimeHost.ahk" {ICLRRuntimeHost}
#Import export ".\ICLRRuntimeInfo.ahk" {ICLRRuntimeInfo}
#Import export ".\ICLRStrongName.ahk" {ICLRStrongName}
#Import export ".\ICLRStrongName2.ahk" {ICLRStrongName2}
#Import export ".\ICLRStrongName3.ahk" {ICLRStrongName3}
#Import export ".\ICLRSyncManager.ahk" {ICLRSyncManager}
#Import export ".\ICLRTask.ahk" {ICLRTask}
#Import export ".\ICLRTask2.ahk" {ICLRTask2}
#Import export ".\ICLRTaskManager.ahk" {ICLRTaskManager}
#Import export ".\ICatalogServices.ahk" {ICatalogServices}
#Import export ".\ICorConfiguration.ahk" {ICorConfiguration}
#Import export ".\ICorRuntimeHost.ahk" {ICorRuntimeHost}
#Import export ".\ICorThreadpool.ahk" {ICorThreadpool}
#Import export ".\IDebuggerInfo.ahk" {IDebuggerInfo}
#Import export ".\IDebuggerThreadControl.ahk" {IDebuggerThreadControl}
#Import export ".\IGCHost.ahk" {IGCHost}
#Import export ".\IGCHost2.ahk" {IGCHost2}
#Import export ".\IGCHostControl.ahk" {IGCHostControl}
#Import export ".\IGCThreadControl.ahk" {IGCThreadControl}
#Import export ".\IHostAssemblyManager.ahk" {IHostAssemblyManager}
#Import export ".\IHostAssemblyStore.ahk" {IHostAssemblyStore}
#Import export ".\IHostAutoEvent.ahk" {IHostAutoEvent}
#Import export ".\IHostControl.ahk" {IHostControl}
#Import export ".\IHostCrst.ahk" {IHostCrst}
#Import export ".\IHostGCManager.ahk" {IHostGCManager}
#Import export ".\IHostIoCompletionManager.ahk" {IHostIoCompletionManager}
#Import export ".\IHostMalloc.ahk" {IHostMalloc}
#Import export ".\IHostManualEvent.ahk" {IHostManualEvent}
#Import export ".\IHostMemoryManager.ahk" {IHostMemoryManager}
#Import export ".\IHostPolicyManager.ahk" {IHostPolicyManager}
#Import export ".\IHostSecurityContext.ahk" {IHostSecurityContext}
#Import export ".\IHostSecurityManager.ahk" {IHostSecurityManager}
#Import export ".\IHostSemaphore.ahk" {IHostSemaphore}
#Import export ".\IHostSyncManager.ahk" {IHostSyncManager}
#Import export ".\IHostTask.ahk" {IHostTask}
#Import export ".\IHostTaskManager.ahk" {IHostTaskManager}
#Import export ".\IHostThreadpoolManager.ahk" {IHostThreadpoolManager}
#Import export ".\IManagedObject.ahk" {IManagedObject}
#Import export ".\IObjectHandle.ahk" {IObjectHandle}
#Import export ".\ITypeName.ahk" {ITypeName}
#Import export ".\ITypeNameBuilder.ahk" {ITypeNameBuilder}
#Import export ".\ITypeNameFactory.ahk" {ITypeNameFactory}
#Import export ".\MALLOC_TYPE.ahk" {MALLOC_TYPE}
#Import export ".\MDAInfo.ahk" {MDAInfo}
#Import export ".\METAHOST_CONFIG_FLAGS.ahk" {METAHOST_CONFIG_FLAGS}
#Import export ".\METAHOST_POLICY_FLAGS.ahk" {METAHOST_POLICY_FLAGS}
#Import export ".\ModuleBindInfo.ahk" {ModuleBindInfo}
#Import export ".\PTLS_CALLBACK_FUNCTION.ahk" {PTLS_CALLBACK_FUNCTION}
#Import export ".\RUNTIME_INFO_FLAGS.ahk" {RUNTIME_INFO_FLAGS}
#Import export ".\RuntimeLoadedCallbackFnPtr.ahk" {RuntimeLoadedCallbackFnPtr}
#Import export ".\STARTUP_FLAGS.ahk" {STARTUP_FLAGS}
#Import export ".\StackOverflowInfo.ahk" {StackOverflowInfo}
#Import export ".\StackOverflowType.ahk" {StackOverflowType}
#Import export ".\TypeNameFactory.ahk" {TypeNameFactory}
#Import export ".\WAIT_OPTION.ahk" {WAIT_OPTION}
