#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\..\Win32Struct.ahk
#Include .\WER_REPORT_PARAMETER.ahk
#Include .\WER_REPORT_SIGNATURE.ahk
#Include ..\..\Foundation\FILETIME.ahk
#Include ..\..\Foundation\PWSTR.ahk

/**
 * Contains information about an error report generated by Windows Error Reporting.
 * @see https://learn.microsoft.com/windows/win32/api/werapi/ns-werapi-wer_report_metadata_v2
 * @namespace Windows.Win32.System.ErrorReporting
 * @version v4.0.30319
 */
class WER_REPORT_METADATA_V2 extends Win32Struct
{
    static sizeof => 800

    static packingSize => 8

    /**
     * A structure containing the signature of the report. The signature consists of the event name and event parameters present.
     * @type {WER_REPORT_SIGNATURE}
     */
    Signature{
        get {
            if(!this.HasProp("__Signature"))
                this.__Signature := WER_REPORT_SIGNATURE(this.ptr + 0)
            return this.__Signature
        }
    }

    /**
     * A hash of the signature. Can be used to cross reference with other crash reports with the same signature (currently not implemented).
     * @type {Pointer<Guid>}
     */
    BucketId {
        get => NumGet(this, 216, "ptr")
        set => NumPut("ptr", value, this, 216)
    }

    /**
     * A locally unique identifier for the report.
     * @type {Pointer<Guid>}
     */
    ReportId {
        get => NumGet(this, 224, "ptr")
        set => NumPut("ptr", value, this, 224)
    }

    /**
     * A UTC time stamp of when the report was created.
     * @type {FILETIME}
     */
    CreationTime{
        get {
            if(!this.HasProp("__CreationTime"))
                this.__CreationTime := FILETIME(this.ptr + 232)
            return this.__CreationTime
        }
    }

    /**
     * The size (on disk) of the individual report and its constituent files. This value only counts files directly contained in a report.
     * @type {Integer}
     */
    SizeInBytes {
        get => NumGet(this, 240, "uint")
        set => NumPut("uint", value, this, 240)
    }

    /**
     * 
     * @type {String}
     */
    CabId {
        get => StrGet(this.ptr + 248, 259, "UTF-16")
        set => StrPut(value, this.ptr + 248, 259, "UTF-16")
    }

    /**
     * The detailed status of the report. Use the ReportStatus decoder to track this bit-field.
     * @type {Integer}
     */
    ReportStatus {
        get => NumGet(this, 768, "uint")
        set => NumPut("uint", value, this, 768)
    }

    /**
     * The integrator ID of the report.
     * @type {Pointer<Guid>}
     */
    ReportIntegratorId {
        get => NumGet(this, 776, "ptr")
        set => NumPut("ptr", value, this, 776)
    }

    /**
     * The number of data files included in the report.
     * @type {Integer}
     */
    NumberOfFiles {
        get => NumGet(this, 784, "uint")
        set => NumPut("uint", value, this, 784)
    }

    /**
     * The total size of the file name fields, in count of <b>WCHAR</b>s, including the terminating character for each name and one more at the end of the record.
     * @type {Integer}
     */
    SizeOfFileNames {
        get => NumGet(this, 788, "uint")
        set => NumPut("uint", value, this, 788)
    }

    /**
     * A pointer to hold the names of the files included in the report. It is in the format: FileName001\0FileName002\0\FileName003\0\0.
     * @type {PWSTR}
     */
    FileNames{
        get {
            if(!this.HasProp("__FileNames"))
                this.__FileNames := PWSTR(this.ptr + 792)
            return this.__FileNames
        }
    }
}
