#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\CALDATETIME.ahk" {CALDATETIME}
#Import export ".\CALDATETIME_DATEUNIT.ahk" {CALDATETIME_DATEUNIT}
#Import export ".\CALINFO_ENUMPROCA.ahk" {CALINFO_ENUMPROCA}
#Import export ".\CALINFO_ENUMPROCEXA.ahk" {CALINFO_ENUMPROCEXA}
#Import export ".\CALINFO_ENUMPROCEXEX.ahk" {CALINFO_ENUMPROCEXEX}
#Import export ".\CALINFO_ENUMPROCEXW.ahk" {CALINFO_ENUMPROCEXW}
#Import export ".\CALINFO_ENUMPROCW.ahk" {CALINFO_ENUMPROCW}
#Import export ".\CHARSETINFO.ahk" {CHARSETINFO}
#Import export ".\CMLangConvertCharset.ahk" {CMLangConvertCharset}
#Import export ".\CMLangString.ahk" {CMLangString}
#Import export ".\CMultiLanguage.ahk" {CMultiLanguage}
#Import export ".\CODEPAGE_ENUMPROCA.ahk" {CODEPAGE_ENUMPROCA}
#Import export ".\CODEPAGE_ENUMPROCW.ahk" {CODEPAGE_ENUMPROCW}
#Import export ".\COMPARESTRING_RESULT.ahk" {COMPARESTRING_RESULT}
#Import export ".\COMPARE_STRING_FLAGS.ahk" {COMPARE_STRING_FLAGS}
#Import export ".\CORRECTIVE_ACTION.ahk" {CORRECTIVE_ACTION}
#Import export ".\CPINFO.ahk" {CPINFO}
#Import export ".\CPINFOEXA.ahk" {CPINFOEXA}
#Import export ".\CPINFOEXW.ahk" {CPINFOEXW}
#Import export ".\CURRENCYFMTA.ahk" {CURRENCYFMTA}
#Import export ".\CURRENCYFMTW.ahk" {CURRENCYFMTW}
#Import export ".\Constants.ahk" {*}
#Import export ".\DATEFMT_ENUMPROCA.ahk" {DATEFMT_ENUMPROCA}
#Import export ".\DATEFMT_ENUMPROCEXA.ahk" {DATEFMT_ENUMPROCEXA}
#Import export ".\DATEFMT_ENUMPROCEXEX.ahk" {DATEFMT_ENUMPROCEXEX}
#Import export ".\DATEFMT_ENUMPROCEXW.ahk" {DATEFMT_ENUMPROCEXW}
#Import export ".\DATEFMT_ENUMPROCW.ahk" {DATEFMT_ENUMPROCW}
#Import export ".\DetectEncodingInfo.ahk" {DetectEncodingInfo}
#Import export ".\ENUMTEXTMETRICA.ahk" {ENUMTEXTMETRICA}
#Import export ".\ENUMTEXTMETRICW.ahk" {ENUMTEXTMETRICW}
#Import export ".\ENUM_DATE_FORMATS_FLAGS.ahk" {ENUM_DATE_FORMATS_FLAGS}
#Import export ".\ENUM_SYSTEM_CODE_PAGES_FLAGS.ahk" {ENUM_SYSTEM_CODE_PAGES_FLAGS}
#Import export ".\ENUM_SYSTEM_LANGUAGE_GROUPS_FLAGS.ahk" {ENUM_SYSTEM_LANGUAGE_GROUPS_FLAGS}
#Import export ".\FILEMUIINFO.ahk" {FILEMUIINFO}
#Import export ".\FOLD_STRING_MAP_FLAGS.ahk" {FOLD_STRING_MAP_FLAGS}
#Import export ".\FONTSIGNATURE.ahk" {FONTSIGNATURE}
#Import export ".\GEO_ENUMNAMEPROC.ahk" {GEO_ENUMNAMEPROC}
#Import export ".\GEO_ENUMPROC.ahk" {GEO_ENUMPROC}
#Import export ".\GOFFSET.ahk" {GOFFSET}
#Import export ".\HSAVEDUILANGUAGES.ahk" {HSAVEDUILANGUAGES}
#Import export ".\IComprehensiveSpellCheckProvider.ahk" {IComprehensiveSpellCheckProvider}
#Import export ".\IEnumCodePage.ahk" {IEnumCodePage}
#Import export ".\IEnumRfc1766.ahk" {IEnumRfc1766}
#Import export ".\IEnumScript.ahk" {IEnumScript}
#Import export ".\IEnumSpellingError.ahk" {IEnumSpellingError}
#Import export ".\IMLangCodePages.ahk" {IMLangCodePages}
#Import export ".\IMLangConvertCharset.ahk" {IMLangConvertCharset}
#Import export ".\IMLangFontLink.ahk" {IMLangFontLink}
#Import export ".\IMLangFontLink2.ahk" {IMLangFontLink2}
#Import export ".\IMLangLineBreakConsole.ahk" {IMLangLineBreakConsole}
#Import export ".\IMLangString.ahk" {IMLangString}
#Import export ".\IMLangStringAStr.ahk" {IMLangStringAStr}
#Import export ".\IMLangStringBufA.ahk" {IMLangStringBufA}
#Import export ".\IMLangStringBufW.ahk" {IMLangStringBufW}
#Import export ".\IMLangStringWStr.ahk" {IMLangStringWStr}
#Import export ".\IMultiLanguage.ahk" {IMultiLanguage}
#Import export ".\IMultiLanguage2.ahk" {IMultiLanguage2}
#Import export ".\IMultiLanguage3.ahk" {IMultiLanguage3}
#Import export ".\IOptionDescription.ahk" {IOptionDescription}
#Import export ".\IS_TEXT_UNICODE_RESULT.ahk" {IS_TEXT_UNICODE_RESULT}
#Import export ".\IS_VALID_LOCALE_FLAGS.ahk" {IS_VALID_LOCALE_FLAGS}
#Import export ".\ISpellCheckProvider.ahk" {ISpellCheckProvider}
#Import export ".\ISpellCheckProviderFactory.ahk" {ISpellCheckProviderFactory}
#Import export ".\ISpellChecker.ahk" {ISpellChecker}
#Import export ".\ISpellChecker2.ahk" {ISpellChecker2}
#Import export ".\ISpellCheckerChangedEventHandler.ahk" {ISpellCheckerChangedEventHandler}
#Import export ".\ISpellCheckerFactory.ahk" {ISpellCheckerFactory}
#Import export ".\ISpellingError.ahk" {ISpellingError}
#Import export ".\IUserDictionariesRegistrar.ahk" {IUserDictionariesRegistrar}
#Import export ".\LANGGROUPLOCALE_ENUMPROCA.ahk" {LANGGROUPLOCALE_ENUMPROCA}
#Import export ".\LANGGROUPLOCALE_ENUMPROCW.ahk" {LANGGROUPLOCALE_ENUMPROCW}
#Import export ".\LANGUAGEGROUP_ENUMPROCA.ahk" {LANGUAGEGROUP_ENUMPROCA}
#Import export ".\LANGUAGEGROUP_ENUMPROCW.ahk" {LANGUAGEGROUP_ENUMPROCW}
#Import export ".\LOCALESIGNATURE.ahk" {LOCALESIGNATURE}
#Import export ".\LOCALE_ENUMPROCA.ahk" {LOCALE_ENUMPROCA}
#Import export ".\LOCALE_ENUMPROCEX.ahk" {LOCALE_ENUMPROCEX}
#Import export ".\LOCALE_ENUMPROCW.ahk" {LOCALE_ENUMPROCW}
#Import export ".\MAPPING_DATA_RANGE.ahk" {MAPPING_DATA_RANGE}
#Import export ".\MAPPING_ENUM_OPTIONS.ahk" {MAPPING_ENUM_OPTIONS}
#Import export ".\MAPPING_OPTIONS.ahk" {MAPPING_OPTIONS}
#Import export ".\MAPPING_PROPERTY_BAG.ahk" {MAPPING_PROPERTY_BAG}
#Import export ".\MAPPING_SERVICE_INFO.ahk" {MAPPING_SERVICE_INFO}
#Import export ".\MIMECONTF.ahk" {MIMECONTF}
#Import export ".\MIMECPINFO.ahk" {MIMECPINFO}
#Import export ".\MIMECSETINFO.ahk" {MIMECSETINFO}
#Import export ".\MLCONVCHAR.ahk" {MLCONVCHAR}
#Import export ".\MLCP.ahk" {MLCP}
#Import export ".\MLDETECTCP.ahk" {MLDETECTCP}
#Import export ".\MLSTR_FLAGS.ahk" {MLSTR_FLAGS}
#Import export ".\MULTI_BYTE_TO_WIDE_CHAR_FLAGS.ahk" {MULTI_BYTE_TO_WIDE_CHAR_FLAGS}
#Import export ".\NEWTEXTMETRICEXA.ahk" {NEWTEXTMETRICEXA}
#Import export ".\NEWTEXTMETRICEXW.ahk" {NEWTEXTMETRICEXW}
#Import export ".\NLSVERSIONINFO.ahk" {NLSVERSIONINFO}
#Import export ".\NLSVERSIONINFOEX.ahk" {NLSVERSIONINFOEX}
#Import export ".\NORM_FORM.ahk" {NORM_FORM}
#Import export ".\NUMBERFMTA.ahk" {NUMBERFMTA}
#Import export ".\NUMBERFMTW.ahk" {NUMBERFMTW}
#Import export ".\OPENTYPE_FEATURE_RECORD.ahk" {OPENTYPE_FEATURE_RECORD}
#Import export ".\PFN_MAPPINGCALLBACKPROC.ahk" {PFN_MAPPINGCALLBACKPROC}
#Import export ".\RFC1766INFO.ahk" {RFC1766INFO}
#Import export ".\SCRIPTCONTF.ahk" {SCRIPTCONTF}
#Import export ".\SCRIPTFONTCONTF.ahk" {SCRIPTFONTCONTF}
#Import export ".\SCRIPTFONTINFO.ahk" {SCRIPTFONTINFO}
#Import export ".\SCRIPTINFO.ahk" {SCRIPTINFO}
#Import export ".\SCRIPT_ANALYSIS.ahk" {SCRIPT_ANALYSIS}
#Import export ".\SCRIPT_CHARPROP.ahk" {SCRIPT_CHARPROP}
#Import export ".\SCRIPT_CONTROL.ahk" {SCRIPT_CONTROL}
#Import export ".\SCRIPT_DIGITSUBSTITUTE.ahk" {SCRIPT_DIGITSUBSTITUTE}
#Import export ".\SCRIPT_FONTPROPERTIES.ahk" {SCRIPT_FONTPROPERTIES}
#Import export ".\SCRIPT_GLYPHPROP.ahk" {SCRIPT_GLYPHPROP}
#Import export ".\SCRIPT_IS_COMPLEX_FLAGS.ahk" {SCRIPT_IS_COMPLEX_FLAGS}
#Import export ".\SCRIPT_ITEM.ahk" {SCRIPT_ITEM}
#Import export ".\SCRIPT_JUSTIFY.ahk" {SCRIPT_JUSTIFY}
#Import export ".\SCRIPT_LOGATTR.ahk" {SCRIPT_LOGATTR}
#Import export ".\SCRIPT_PROPERTIES.ahk" {SCRIPT_PROPERTIES}
#Import export ".\SCRIPT_STATE.ahk" {SCRIPT_STATE}
#Import export ".\SCRIPT_TABDEF.ahk" {SCRIPT_TABDEF}
#Import export ".\SCRIPT_VISATTR.ahk" {SCRIPT_VISATTR}
#Import export ".\SYSGEOCLASS.ahk" {SYSGEOCLASS}
#Import export ".\SYSGEOTYPE.ahk" {SYSGEOTYPE}
#Import export ".\SYSNLS_FUNCTION.ahk" {SYSNLS_FUNCTION}
#Import export ".\SpellCheckerFactory.ahk" {SpellCheckerFactory}
#Import export ".\TEXTRANGE_PROPERTIES.ahk" {TEXTRANGE_PROPERTIES}
#Import export ".\TIMEFMT_ENUMPROCA.ahk" {TIMEFMT_ENUMPROCA}
#Import export ".\TIMEFMT_ENUMPROCEX.ahk" {TIMEFMT_ENUMPROCEX}
#Import export ".\TIMEFMT_ENUMPROCW.ahk" {TIMEFMT_ENUMPROCW}
#Import export ".\TIME_FORMAT_FLAGS.ahk" {TIME_FORMAT_FLAGS}
#Import export ".\TRANSLATE_CHARSET_INFO_FLAGS.ahk" {TRANSLATE_CHARSET_INFO_FLAGS}
#Import export ".\UAcceptResult.ahk" {UAcceptResult}
#Import export ".\UAlphabeticIndexLabelType.ahk" {UAlphabeticIndexLabelType}
#Import export ".\UBiDi.ahk" {UBiDi}
#Import export ".\UBiDiClassCallback.ahk" {UBiDiClassCallback}
#Import export ".\UBiDiDirection.ahk" {UBiDiDirection}
#Import export ".\UBiDiMirroring.ahk" {UBiDiMirroring}
#Import export ".\UBiDiOrder.ahk" {UBiDiOrder}
#Import export ".\UBiDiReorderingMode.ahk" {UBiDiReorderingMode}
#Import export ".\UBiDiReorderingOption.ahk" {UBiDiReorderingOption}
#Import export ".\UBiDiTransform.ahk" {UBiDiTransform}
#Import export ".\UBidiPairedBracketType.ahk" {UBidiPairedBracketType}
#Import export ".\UBlockCode.ahk" {UBlockCode}
#Import export ".\UBreakIterator.ahk" {UBreakIterator}
#Import export ".\UBreakIteratorType.ahk" {UBreakIteratorType}
#Import export ".\UCPMap.ahk" {UCPMap}
#Import export ".\UCPMapRangeOption.ahk" {UCPMapRangeOption}
#Import export ".\UCPMapValueFilter.ahk" {UCPMapValueFilter}
#Import export ".\UCPTrie.ahk" {UCPTrie}
#Import export ".\UCPTrieData.ahk" {UCPTrieData}
#Import export ".\UCPTrieType.ahk" {UCPTrieType}
#Import export ".\UCPTrieValueWidth.ahk" {UCPTrieValueWidth}
#Import export ".\UCalendarAMPMs.ahk" {UCalendarAMPMs}
#Import export ".\UCalendarAttribute.ahk" {UCalendarAttribute}
#Import export ".\UCalendarDateFields.ahk" {UCalendarDateFields}
#Import export ".\UCalendarDaysOfWeek.ahk" {UCalendarDaysOfWeek}
#Import export ".\UCalendarDisplayNameType.ahk" {UCalendarDisplayNameType}
#Import export ".\UCalendarLimitType.ahk" {UCalendarLimitType}
#Import export ".\UCalendarMonths.ahk" {UCalendarMonths}
#Import export ".\UCalendarType.ahk" {UCalendarType}
#Import export ".\UCalendarWallTimeOption.ahk" {UCalendarWallTimeOption}
#Import export ".\UCalendarWeekdayType.ahk" {UCalendarWeekdayType}
#Import export ".\UCaseMap.ahk" {UCaseMap}
#Import export ".\UCharCategory.ahk" {UCharCategory}
#Import export ".\UCharDirection.ahk" {UCharDirection}
#Import export ".\UCharEnumTypeRange.ahk" {UCharEnumTypeRange}
#Import export ".\UCharIterator.ahk" {UCharIterator}
#Import export ".\UCharIteratorCurrent.ahk" {UCharIteratorCurrent}
#Import export ".\UCharIteratorGetIndex.ahk" {UCharIteratorGetIndex}
#Import export ".\UCharIteratorGetState.ahk" {UCharIteratorGetState}
#Import export ".\UCharIteratorHasNext.ahk" {UCharIteratorHasNext}
#Import export ".\UCharIteratorHasPrevious.ahk" {UCharIteratorHasPrevious}
#Import export ".\UCharIteratorMove.ahk" {UCharIteratorMove}
#Import export ".\UCharIteratorNext.ahk" {UCharIteratorNext}
#Import export ".\UCharIteratorOrigin.ahk" {UCharIteratorOrigin}
#Import export ".\UCharIteratorPrevious.ahk" {UCharIteratorPrevious}
#Import export ".\UCharIteratorReserved.ahk" {UCharIteratorReserved}
#Import export ".\UCharIteratorSetState.ahk" {UCharIteratorSetState}
#Import export ".\UCharNameChoice.ahk" {UCharNameChoice}
#Import export ".\UCharsetDetector.ahk" {UCharsetDetector}
#Import export ".\UCharsetMatch.ahk" {UCharsetMatch}
#Import export ".\UColAttribute.ahk" {UColAttribute}
#Import export ".\UColAttributeValue.ahk" {UColAttributeValue}
#Import export ".\UColBoundMode.ahk" {UColBoundMode}
#Import export ".\UColReorderCode.ahk" {UColReorderCode}
#Import export ".\UColRuleOption.ahk" {UColRuleOption}
#Import export ".\UCollationElements.ahk" {UCollationElements}
#Import export ".\UCollationResult.ahk" {UCollationResult}
#Import export ".\UCollator.ahk" {UCollator}
#Import export ".\UConstrainedFieldPosition.ahk" {UConstrainedFieldPosition}
#Import export ".\UConverter.ahk" {UConverter}
#Import export ".\UConverterCallbackReason.ahk" {UConverterCallbackReason}
#Import export ".\UConverterFromUCallback.ahk" {UConverterFromUCallback}
#Import export ".\UConverterFromUnicodeArgs.ahk" {UConverterFromUnicodeArgs}
#Import export ".\UConverterPlatform.ahk" {UConverterPlatform}
#Import export ".\UConverterSelector.ahk" {UConverterSelector}
#Import export ".\UConverterToUCallback.ahk" {UConverterToUCallback}
#Import export ".\UConverterToUnicodeArgs.ahk" {UConverterToUnicodeArgs}
#Import export ".\UConverterType.ahk" {UConverterType}
#Import export ".\UConverterUnicodeSet.ahk" {UConverterUnicodeSet}
#Import export ".\UCurrCurrencyType.ahk" {UCurrCurrencyType}
#Import export ".\UCurrNameStyle.ahk" {UCurrNameStyle}
#Import export ".\UCurrencySpacing.ahk" {UCurrencySpacing}
#Import export ".\UCurrencyUsage.ahk" {UCurrencyUsage}
#Import export ".\UDateAbsoluteUnit.ahk" {UDateAbsoluteUnit}
#Import export ".\UDateDirection.ahk" {UDateDirection}
#Import export ".\UDateFormatBooleanAttribute.ahk" {UDateFormatBooleanAttribute}
#Import export ".\UDateFormatField.ahk" {UDateFormatField}
#Import export ".\UDateFormatHourCycle.ahk" {UDateFormatHourCycle}
#Import export ".\UDateFormatStyle.ahk" {UDateFormatStyle}
#Import export ".\UDateFormatSymbolType.ahk" {UDateFormatSymbolType}
#Import export ".\UDateFormatSymbols.ahk" {UDateFormatSymbols}
#Import export ".\UDateIntervalFormat.ahk" {UDateIntervalFormat}
#Import export ".\UDateRelativeDateTimeFormatterStyle.ahk" {UDateRelativeDateTimeFormatterStyle}
#Import export ".\UDateRelativeUnit.ahk" {UDateRelativeUnit}
#Import export ".\UDateTimePGDisplayWidth.ahk" {UDateTimePGDisplayWidth}
#Import export ".\UDateTimePatternConflict.ahk" {UDateTimePatternConflict}
#Import export ".\UDateTimePatternField.ahk" {UDateTimePatternField}
#Import export ".\UDateTimePatternMatchOptions.ahk" {UDateTimePatternMatchOptions}
#Import export ".\UDateTimeScale.ahk" {UDateTimeScale}
#Import export ".\UDecompositionType.ahk" {UDecompositionType}
#Import export ".\UDialectHandling.ahk" {UDialectHandling}
#Import export ".\UDisplayContext.ahk" {UDisplayContext}
#Import export ".\UDisplayContextType.ahk" {UDisplayContextType}
#Import export ".\UEastAsianWidth.ahk" {UEastAsianWidth}
#Import export ".\UEnumCharNamesFn.ahk" {UEnumCharNamesFn}
#Import export ".\UEnumeration.ahk" {UEnumeration}
#Import export ".\UErrorCode.ahk" {UErrorCode}
#Import export ".\UFieldCategory.ahk" {UFieldCategory}
#Import export ".\UFieldPosition.ahk" {UFieldPosition}
#Import export ".\UFieldPositionIterator.ahk" {UFieldPositionIterator}
#Import export ".\UFormattableType.ahk" {UFormattableType}
#Import export ".\UFormattedDateInterval.ahk" {UFormattedDateInterval}
#Import export ".\UFormattedList.ahk" {UFormattedList}
#Import export ".\UFormattedNumber.ahk" {UFormattedNumber}
#Import export ".\UFormattedNumberRange.ahk" {UFormattedNumberRange}
#Import export ".\UFormattedRelativeDateTime.ahk" {UFormattedRelativeDateTime}
#Import export ".\UFormattedValue.ahk" {UFormattedValue}
#Import export ".\UGender.ahk" {UGender}
#Import export ".\UGenderInfo.ahk" {UGenderInfo}
#Import export ".\UGraphemeClusterBreak.ahk" {UGraphemeClusterBreak}
#Import export ".\UHangulSyllableType.ahk" {UHangulSyllableType}
#Import export ".\UHashtable.ahk" {UHashtable}
#Import export ".\UIDNA.ahk" {UIDNA}
#Import export ".\UIDNAInfo.ahk" {UIDNAInfo}
#Import export ".\UILANGUAGE_ENUMPROCA.ahk" {UILANGUAGE_ENUMPROCA}
#Import export ".\UILANGUAGE_ENUMPROCW.ahk" {UILANGUAGE_ENUMPROCW}
#Import export ".\UIndicPositionalCategory.ahk" {UIndicPositionalCategory}
#Import export ".\UIndicSyllabicCategory.ahk" {UIndicSyllabicCategory}
#Import export ".\UJoiningGroup.ahk" {UJoiningGroup}
#Import export ".\UJoiningType.ahk" {UJoiningType}
#Import export ".\ULayoutType.ahk" {ULayoutType}
#Import export ".\ULineBreak.ahk" {ULineBreak}
#Import export ".\ULineBreakTag.ahk" {ULineBreakTag}
#Import export ".\UListFormatter.ahk" {UListFormatter}
#Import export ".\UListFormatterField.ahk" {UListFormatterField}
#Import export ".\UListFormatterType.ahk" {UListFormatterType}
#Import export ".\UListFormatterWidth.ahk" {UListFormatterWidth}
#Import export ".\ULocAvailableType.ahk" {ULocAvailableType}
#Import export ".\ULocDataLocaleType.ahk" {ULocDataLocaleType}
#Import export ".\ULocaleData.ahk" {ULocaleData}
#Import export ".\ULocaleDataDelimiterType.ahk" {ULocaleDataDelimiterType}
#Import export ".\ULocaleDataExemplarSetType.ahk" {ULocaleDataExemplarSetType}
#Import export ".\ULocaleDisplayNames.ahk" {ULocaleDisplayNames}
#Import export ".\UMeasureFormatWidth.ahk" {UMeasureFormatWidth}
#Import export ".\UMeasurementSystem.ahk" {UMeasurementSystem}
#Import export ".\UMemAllocFn.ahk" {UMemAllocFn}
#Import export ".\UMemFreeFn.ahk" {UMemFreeFn}
#Import export ".\UMemReallocFn.ahk" {UMemReallocFn}
#Import export ".\UMessagePatternApostropheMode.ahk" {UMessagePatternApostropheMode}
#Import export ".\UMessagePatternArgType.ahk" {UMessagePatternArgType}
#Import export ".\UMessagePatternPartType.ahk" {UMessagePatternPartType}
#Import export ".\UMutableCPTrie.ahk" {UMutableCPTrie}
#Import export ".\UNESCAPE_CHAR_AT.ahk" {UNESCAPE_CHAR_AT}
#Import export ".\UNICODERANGE.ahk" {UNICODERANGE}
#Import export ".\UNormalization2Mode.ahk" {UNormalization2Mode}
#Import export ".\UNormalizationCheckResult.ahk" {UNormalizationCheckResult}
#Import export ".\UNormalizationMode.ahk" {UNormalizationMode}
#Import export ".\UNormalizer2.ahk" {UNormalizer2}
#Import export ".\UNumberCompactStyle.ahk" {UNumberCompactStyle}
#Import export ".\UNumberDecimalSeparatorDisplay.ahk" {UNumberDecimalSeparatorDisplay}
#Import export ".\UNumberFormatAttribute.ahk" {UNumberFormatAttribute}
#Import export ".\UNumberFormatAttributeValue.ahk" {UNumberFormatAttributeValue}
#Import export ".\UNumberFormatFields.ahk" {UNumberFormatFields}
#Import export ".\UNumberFormatMinimumGroupingDigits.ahk" {UNumberFormatMinimumGroupingDigits}
#Import export ".\UNumberFormatPadPosition.ahk" {UNumberFormatPadPosition}
#Import export ".\UNumberFormatRoundingMode.ahk" {UNumberFormatRoundingMode}
#Import export ".\UNumberFormatStyle.ahk" {UNumberFormatStyle}
#Import export ".\UNumberFormatSymbol.ahk" {UNumberFormatSymbol}
#Import export ".\UNumberFormatTextAttribute.ahk" {UNumberFormatTextAttribute}
#Import export ".\UNumberFormatter.ahk" {UNumberFormatter}
#Import export ".\UNumberGroupingStrategy.ahk" {UNumberGroupingStrategy}
#Import export ".\UNumberRangeCollapse.ahk" {UNumberRangeCollapse}
#Import export ".\UNumberRangeFormatter.ahk" {UNumberRangeFormatter}
#Import export ".\UNumberRangeIdentityFallback.ahk" {UNumberRangeIdentityFallback}
#Import export ".\UNumberRangeIdentityResult.ahk" {UNumberRangeIdentityResult}
#Import export ".\UNumberSignDisplay.ahk" {UNumberSignDisplay}
#Import export ".\UNumberTrailingZeroDisplay.ahk" {UNumberTrailingZeroDisplay}
#Import export ".\UNumberUnitWidth.ahk" {UNumberUnitWidth}
#Import export ".\UNumberingSystem.ahk" {UNumberingSystem}
#Import export ".\UNumericType.ahk" {UNumericType}
#Import export ".\UParseError.ahk" {UParseError}
#Import export ".\UPluralRules.ahk" {UPluralRules}
#Import export ".\UPluralType.ahk" {UPluralType}
#Import export ".\UProperty.ahk" {UProperty}
#Import export ".\UPropertyNameChoice.ahk" {UPropertyNameChoice}
#Import export ".\URegexFindProgressCallback.ahk" {URegexFindProgressCallback}
#Import export ".\URegexMatchCallback.ahk" {URegexMatchCallback}
#Import export ".\URegexpFlag.ahk" {URegexpFlag}
#Import export ".\URegion.ahk" {URegion}
#Import export ".\URegionType.ahk" {URegionType}
#Import export ".\URegularExpression.ahk" {URegularExpression}
#Import export ".\URelativeDateTimeFormatter.ahk" {URelativeDateTimeFormatter}
#Import export ".\URelativeDateTimeFormatterField.ahk" {URelativeDateTimeFormatterField}
#Import export ".\URelativeDateTimeUnit.ahk" {URelativeDateTimeUnit}
#Import export ".\UReplaceableCallbacks.ahk" {UReplaceableCallbacks}
#Import export ".\UResType.ahk" {UResType}
#Import export ".\UResourceBundle.ahk" {UResourceBundle}
#Import export ".\URestrictionLevel.ahk" {URestrictionLevel}
#Import export ".\UScriptCode.ahk" {UScriptCode}
#Import export ".\UScriptUsage.ahk" {UScriptUsage}
#Import export ".\USearch.ahk" {USearch}
#Import export ".\USearchAttribute.ahk" {USearchAttribute}
#Import export ".\USearchAttributeValue.ahk" {USearchAttributeValue}
#Import export ".\USentenceBreak.ahk" {USentenceBreak}
#Import export ".\USentenceBreakTag.ahk" {USentenceBreakTag}
#Import export ".\USerializedSet.ahk" {USerializedSet}
#Import export ".\USet.ahk" {USet}
#Import export ".\USetSpanCondition.ahk" {USetSpanCondition}
#Import export ".\USpoofCheckResult.ahk" {USpoofCheckResult}
#Import export ".\USpoofChecker.ahk" {USpoofChecker}
#Import export ".\USpoofChecks.ahk" {USpoofChecks}
#Import export ".\UStringCaseMapper.ahk" {UStringCaseMapper}
#Import export ".\UStringPrepProfile.ahk" {UStringPrepProfile}
#Import export ".\UStringPrepProfileType.ahk" {UStringPrepProfileType}
#Import export ".\UStringSearch.ahk" {UStringSearch}
#Import export ".\UStringTrieBuildOption.ahk" {UStringTrieBuildOption}
#Import export ".\UStringTrieResult.ahk" {UStringTrieResult}
#Import export ".\USystemTimeZoneType.ahk" {USystemTimeZoneType}
#Import export ".\UText.ahk" {UText}
#Import export ".\UTextAccess.ahk" {UTextAccess}
#Import export ".\UTextClone.ahk" {UTextClone}
#Import export ".\UTextClose.ahk" {UTextClose}
#Import export ".\UTextCopy.ahk" {UTextCopy}
#Import export ".\UTextExtract.ahk" {UTextExtract}
#Import export ".\UTextFuncs.ahk" {UTextFuncs}
#Import export ".\UTextMapNativeIndexToUTF16.ahk" {UTextMapNativeIndexToUTF16}
#Import export ".\UTextMapOffsetToNative.ahk" {UTextMapOffsetToNative}
#Import export ".\UTextNativeLength.ahk" {UTextNativeLength}
#Import export ".\UTextReplace.ahk" {UTextReplace}
#Import export ".\UTimeScaleValue.ahk" {UTimeScaleValue}
#Import export ".\UTimeZoneFormatGMTOffsetPatternType.ahk" {UTimeZoneFormatGMTOffsetPatternType}
#Import export ".\UTimeZoneFormatParseOption.ahk" {UTimeZoneFormatParseOption}
#Import export ".\UTimeZoneFormatStyle.ahk" {UTimeZoneFormatStyle}
#Import export ".\UTimeZoneFormatTimeType.ahk" {UTimeZoneFormatTimeType}
#Import export ".\UTimeZoneLocalOption.ahk" {UTimeZoneLocalOption}
#Import export ".\UTimeZoneNameType.ahk" {UTimeZoneNameType}
#Import export ".\UTimeZoneTransitionType.ahk" {UTimeZoneTransitionType}
#Import export ".\UTraceData.ahk" {UTraceData}
#Import export ".\UTraceEntry.ahk" {UTraceEntry}
#Import export ".\UTraceExit.ahk" {UTraceExit}
#Import export ".\UTraceFunctionNumber.ahk" {UTraceFunctionNumber}
#Import export ".\UTraceLevel.ahk" {UTraceLevel}
#Import export ".\UTransDirection.ahk" {UTransDirection}
#Import export ".\UTransPosition.ahk" {UTransPosition}
#Import export ".\UVerticalOrientation.ahk" {UVerticalOrientation}
#Import export ".\UWordBreak.ahk" {UWordBreak}
#Import export ".\UWordBreakValues.ahk" {UWordBreakValues}
#Import export ".\WORDLIST_TYPE.ahk" {WORDLIST_TYPE}
