#Requires AutoHotkey v2.0.0 64-bit
#Include ..\..\..\Win32Struct.ahk
#Include .\SCRIPT_VISATTR.ahk

/**
 * Contains information about a glyph that is part of an output glyph array.
 * @see https://learn.microsoft.com/windows/win32/api/usp10/ns-usp10-script_glyphprop
 * @namespace Windows.Win32.Globalization
 * @version v4.0.30319
 */
class SCRIPT_GLYPHPROP extends Win32Struct
{
    static sizeof => 4

    static packingSize => 2

    /**
     * A buffer of <a href="https://docs.microsoft.com/windows/win32/api/usp10/ns-usp10-script_visattr">SCRIPT_VISATTR</a> structures defining visual (glyph) attributes identifying clusters and justification points. The buffer is generated by <a href="https://docs.microsoft.com/windows/desktop/api/usp10/nf-usp10-scriptshape">ScriptShape</a> or <a href="https://docs.microsoft.com/windows/desktop/api/usp10/nf-usp10-scriptshapeopentype">ScriptShapeOpenType</a>.
     * @type {SCRIPT_VISATTR}
     */
    sva{
        get {
            if(!this.HasProp("__sva"))
                this.__sva := SCRIPT_VISATTR(0, this)
            return this.__sva
        }
    }

    /**
     * Reserved.
     * @type {Integer}
     */
    reserved {
        get => NumGet(this, 2, "ushort")
        set => NumPut("ushort", value, this, 2)
    }
}
