#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\APPLETIDLIST.ahk" {APPLETIDLIST}
#Import export ".\APPLYCANDEXPARAM.ahk" {APPLYCANDEXPARAM}
#Import export ".\Apis.ahk" {*}
#Import export ".\CANDIDATEFORM.ahk" {CANDIDATEFORM}
#Import export ".\CANDIDATEINFO.ahk" {CANDIDATEINFO}
#Import export ".\CANDIDATELIST.ahk" {CANDIDATELIST}
#Import export ".\CActiveIMM.ahk" {CActiveIMM}
#Import export ".\COMPOSITIONFORM.ahk" {COMPOSITIONFORM}
#Import export ".\COMPOSITIONSTRING.ahk" {COMPOSITIONSTRING}
#Import export ".\Constants.ahk" {*}
#Import export ".\GET_CONVERSION_LIST_FLAG.ahk" {GET_CONVERSION_LIST_FLAG}
#Import export ".\GET_GUIDE_LINE_TYPE.ahk" {GET_GUIDE_LINE_TYPE}
#Import export ".\GUIDELINE.ahk" {GUIDELINE}
#Import export ".\HIMC.ahk" {HIMC}
#Import export ".\HIMCC.ahk" {HIMCC}
#Import export ".\IActiveIME.ahk" {IActiveIME}
#Import export ".\IActiveIME2.ahk" {IActiveIME2}
#Import export ".\IActiveIMMApp.ahk" {IActiveIMMApp}
#Import export ".\IActiveIMMIME.ahk" {IActiveIMMIME}
#Import export ".\IActiveIMMMessagePumpOwner.ahk" {IActiveIMMMessagePumpOwner}
#Import export ".\IActiveIMMRegistrar.ahk" {IActiveIMMRegistrar}
#Import export ".\IEnumInputContext.ahk" {IEnumInputContext}
#Import export ".\IEnumRegisterWordA.ahk" {IEnumRegisterWordA}
#Import export ".\IEnumRegisterWordW.ahk" {IEnumRegisterWordW}
#Import export ".\IFEClassFactory.ahk" {IFEClassFactory}
#Import export ".\IFECommon.ahk" {IFECommon}
#Import export ".\IFEDictionary.ahk" {IFEDictionary}
#Import export ".\IFELanguage.ahk" {IFELanguage}
#Import export ".\IImePad.ahk" {IImePad}
#Import export ".\IImePadApplet.ahk" {IImePadApplet}
#Import export ".\IImePlugInDictDictionaryList.ahk" {IImePlugInDictDictionaryList}
#Import export ".\IImeSpecifyApplets.ahk" {IImeSpecifyApplets}
#Import export ".\IMCENUMPROC.ahk" {IMCENUMPROC}
#Import export ".\IMEAPPLETCFG.ahk" {IMEAPPLETCFG}
#Import export ".\IMEAPPLETUI.ahk" {IMEAPPLETUI}
#Import export ".\IMECHARINFO.ahk" {IMECHARINFO}
#Import export ".\IMECHARPOSITION.ahk" {IMECHARPOSITION}
#Import export ".\IMECOMPOSITIONSTRINGINFO.ahk" {IMECOMPOSITIONSTRINGINFO}
#Import export ".\IMEDLG.ahk" {IMEDLG}
#Import export ".\IMEDP.ahk" {IMEDP}
#Import export ".\IMEFAREASTINFO.ahk" {IMEFAREASTINFO}
#Import export ".\IMEFMT.ahk" {IMEFMT}
#Import export ".\IMEINFO.ahk" {IMEINFO}
#Import export ".\IMEITEM.ahk" {IMEITEM}
#Import export ".\IMEITEMCANDIDATE.ahk" {IMEITEMCANDIDATE}
#Import export ".\IMEKMS.ahk" {IMEKMS}
#Import export ".\IMEKMSFUNCDESC.ahk" {IMEKMSFUNCDESC}
#Import export ".\IMEKMSINIT.ahk" {IMEKMSINIT}
#Import export ".\IMEKMSINVK.ahk" {IMEKMSINVK}
#Import export ".\IMEKMSKEY.ahk" {IMEKMSKEY}
#Import export ".\IMEKMSKMP.ahk" {IMEKMSKMP}
#Import export ".\IMEKMSNTFY.ahk" {IMEKMSNTFY}
#Import export ".\IMEMENUITEMINFOA.ahk" {IMEMENUITEMINFOA}
#Import export ".\IMEMENUITEMINFOW.ahk" {IMEMENUITEMINFOW}
#Import export ".\IMEREG.ahk" {IMEREG}
#Import export ".\IMEREL.ahk" {IMEREL}
#Import export ".\IMESHF.ahk" {IMESHF}
#Import export ".\IMESTRINGCANDIDATE.ahk" {IMESTRINGCANDIDATE}
#Import export ".\IMESTRINGCANDIDATEINFO.ahk" {IMESTRINGCANDIDATEINFO}
#Import export ".\IMESTRINGINFO.ahk" {IMESTRINGINFO}
#Import export ".\IMEUCT.ahk" {IMEUCT}
#Import export ".\IMEWRD.ahk" {IMEWRD}
#Import export ".\IME_COMPOSITION_STRING.ahk" {IME_COMPOSITION_STRING}
#Import export ".\IME_CONVERSION_MODE.ahk" {IME_CONVERSION_MODE}
#Import export ".\IME_ESCAPE.ahk" {IME_ESCAPE}
#Import export ".\IME_HOTKEY_IDENTIFIER.ahk" {IME_HOTKEY_IDENTIFIER}
#Import export ".\IME_PAD_REQUEST_FLAGS.ahk" {IME_PAD_REQUEST_FLAGS}
#Import export ".\IME_SENTENCE_MODE.ahk" {IME_SENTENCE_MODE}
#Import export ".\INPUTCONTEXT.ahk" {INPUTCONTEXT}
#Import export ".\MORRSLT.ahk" {MORRSLT}
#Import export ".\NOTIFY_IME_ACTION.ahk" {NOTIFY_IME_ACTION}
#Import export ".\NOTIFY_IME_INDEX.ahk" {NOTIFY_IME_INDEX}
#Import export ".\PFNLOG.ahk" {PFNLOG}
#Import export ".\POSTBL.ahk" {POSTBL}
#Import export ".\RECONVERTSTRING.ahk" {RECONVERTSTRING}
#Import export ".\REGISTERWORDA.ahk" {REGISTERWORDA}
#Import export ".\REGISTERWORDENUMPROCA.ahk" {REGISTERWORDENUMPROCA}
#Import export ".\REGISTERWORDENUMPROCW.ahk" {REGISTERWORDENUMPROCW}
#Import export ".\REGISTERWORDW.ahk" {REGISTERWORDW}
#Import export ".\SET_COMPOSITION_STRING_TYPE.ahk" {SET_COMPOSITION_STRING_TYPE}
#Import export ".\SOFTKBDDATA.ahk" {SOFTKBDDATA}
#Import export ".\STYLEBUFA.ahk" {STYLEBUFA}
#Import export ".\STYLEBUFW.ahk" {STYLEBUFW}
#Import export ".\TRANSMSG.ahk" {TRANSMSG}
#Import export ".\TRANSMSGLIST.ahk" {TRANSMSGLIST}
#Import export ".\WDD.ahk" {WDD}
#Import export ".\fpCreateIFECommonInstanceType.ahk" {fpCreateIFECommonInstanceType}
#Import export ".\fpCreateIFEDictionaryInstanceType.ahk" {fpCreateIFEDictionaryInstanceType}
#Import export ".\fpCreateIFELanguageInstanceType.ahk" {fpCreateIFELanguageInstanceType}
