#Requires AutoHotkey v2.1-alpha.26+ 64-bit

/**
 * The STORAGE_RPMB_DATA_FRAME structure (winioctl.h) allows an application to use data from IOCTL_STORAGE_QUERY_PROPERTY to create a RPMB frame.
 * @see https://learn.microsoft.com/windows/win32/api/winioctl/ns-winioctl-storage_rpmb_data_frame
 * @namespace Windows.Win32.System.Ioctl
 */
export default struct STORAGE_RPMB_DATA_FRAME {
    #StructPack 1

    /**
     * Reserved space.
     */
    Stuff : Int8[196]

    /**
     * Either the key to be programmed or the MAC authenticating this frame or series of frames.
     */
    KeyOrMAC : Int8[32]

    /**
     * The data input or output.
     */
    Data : Int8[256]

    /**
     * Random 128-bit number generated by host. Only required for reads.
     */
    Nonce : Int8[16]

    /**
     * 32-bit counter. Only required for writes.
     */
    WriteCounter : Int8[4]

    /**
     * The half-sector address to operate on.
     */
    Address : Int8[2]

    /**
     * The count of half-sector blocks to read/write.
     */
    BlockCount : Int8[2]

    /**
     * The result of the operation.
     */
    OperationResult : Int8[2]

    /**
     * The type of request or response.
     */
    RequestOrResponseType : Int8[2]

}
