#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\Apis.ahk" {*}
#Import export ".\COMPOSITION_FRAME_ID_TYPE.ahk" {COMPOSITION_FRAME_ID_TYPE}
#Import export ".\COMPOSITION_FRAME_STATS.ahk" {COMPOSITION_FRAME_STATS}
#Import export ".\COMPOSITION_STATS.ahk" {COMPOSITION_STATS}
#Import export ".\COMPOSITION_TARGET_ID.ahk" {COMPOSITION_TARGET_ID}
#Import export ".\COMPOSITION_TARGET_STATS.ahk" {COMPOSITION_TARGET_STATS}
#Import export ".\Constants.ahk" {*}
#Import export ".\DCOMPOSITION_BACKFACE_VISIBILITY.ahk" {DCOMPOSITION_BACKFACE_VISIBILITY}
#Import export ".\DCOMPOSITION_BITMAP_INTERPOLATION_MODE.ahk" {DCOMPOSITION_BITMAP_INTERPOLATION_MODE}
#Import export ".\DCOMPOSITION_BORDER_MODE.ahk" {DCOMPOSITION_BORDER_MODE}
#Import export ".\DCOMPOSITION_COMPOSITE_MODE.ahk" {DCOMPOSITION_COMPOSITE_MODE}
#Import export ".\DCOMPOSITION_DEPTH_MODE.ahk" {DCOMPOSITION_DEPTH_MODE}
#Import export ".\DCOMPOSITION_FRAME_STATISTICS.ahk" {DCOMPOSITION_FRAME_STATISTICS}
#Import export ".\DCOMPOSITION_OPACITY_MODE.ahk" {DCOMPOSITION_OPACITY_MODE}
#Import export ".\DCompositionInkTrailPoint.ahk" {DCompositionInkTrailPoint}
#Import export ".\IDCompositionAffineTransform2DEffect.ahk" {IDCompositionAffineTransform2DEffect}
#Import export ".\IDCompositionAnimation.ahk" {IDCompositionAnimation}
#Import export ".\IDCompositionArithmeticCompositeEffect.ahk" {IDCompositionArithmeticCompositeEffect}
#Import export ".\IDCompositionBlendEffect.ahk" {IDCompositionBlendEffect}
#Import export ".\IDCompositionBrightnessEffect.ahk" {IDCompositionBrightnessEffect}
#Import export ".\IDCompositionClip.ahk" {IDCompositionClip}
#Import export ".\IDCompositionColorMatrixEffect.ahk" {IDCompositionColorMatrixEffect}
#Import export ".\IDCompositionCompositeEffect.ahk" {IDCompositionCompositeEffect}
#Import export ".\IDCompositionDelegatedInkTrail.ahk" {IDCompositionDelegatedInkTrail}
#Import export ".\IDCompositionDesktopDevice.ahk" {IDCompositionDesktopDevice}
#Import export ".\IDCompositionDevice.ahk" {IDCompositionDevice}
#Import export ".\IDCompositionDevice2.ahk" {IDCompositionDevice2}
#Import export ".\IDCompositionDevice3.ahk" {IDCompositionDevice3}
#Import export ".\IDCompositionDevice4.ahk" {IDCompositionDevice4}
#Import export ".\IDCompositionDevice5.ahk" {IDCompositionDevice5}
#Import export ".\IDCompositionDeviceDebug.ahk" {IDCompositionDeviceDebug}
#Import export ".\IDCompositionDynamicTexture.ahk" {IDCompositionDynamicTexture}
#Import export ".\IDCompositionEffect.ahk" {IDCompositionEffect}
#Import export ".\IDCompositionEffectGroup.ahk" {IDCompositionEffectGroup}
#Import export ".\IDCompositionFilterEffect.ahk" {IDCompositionFilterEffect}
#Import export ".\IDCompositionGaussianBlurEffect.ahk" {IDCompositionGaussianBlurEffect}
#Import export ".\IDCompositionHueRotationEffect.ahk" {IDCompositionHueRotationEffect}
#Import export ".\IDCompositionInkTrailDevice.ahk" {IDCompositionInkTrailDevice}
#Import export ".\IDCompositionLinearTransferEffect.ahk" {IDCompositionLinearTransferEffect}
#Import export ".\IDCompositionMatrixTransform.ahk" {IDCompositionMatrixTransform}
#Import export ".\IDCompositionMatrixTransform3D.ahk" {IDCompositionMatrixTransform3D}
#Import export ".\IDCompositionRectangleClip.ahk" {IDCompositionRectangleClip}
#Import export ".\IDCompositionRotateTransform.ahk" {IDCompositionRotateTransform}
#Import export ".\IDCompositionRotateTransform3D.ahk" {IDCompositionRotateTransform3D}
#Import export ".\IDCompositionSaturationEffect.ahk" {IDCompositionSaturationEffect}
#Import export ".\IDCompositionScaleTransform.ahk" {IDCompositionScaleTransform}
#Import export ".\IDCompositionScaleTransform3D.ahk" {IDCompositionScaleTransform3D}
#Import export ".\IDCompositionShadowEffect.ahk" {IDCompositionShadowEffect}
#Import export ".\IDCompositionSkewTransform.ahk" {IDCompositionSkewTransform}
#Import export ".\IDCompositionSurface.ahk" {IDCompositionSurface}
#Import export ".\IDCompositionSurfaceFactory.ahk" {IDCompositionSurfaceFactory}
#Import export ".\IDCompositionTableTransferEffect.ahk" {IDCompositionTableTransferEffect}
#Import export ".\IDCompositionTarget.ahk" {IDCompositionTarget}
#Import export ".\IDCompositionTexture.ahk" {IDCompositionTexture}
#Import export ".\IDCompositionTransform.ahk" {IDCompositionTransform}
#Import export ".\IDCompositionTransform3D.ahk" {IDCompositionTransform3D}
#Import export ".\IDCompositionTranslateTransform.ahk" {IDCompositionTranslateTransform}
#Import export ".\IDCompositionTranslateTransform3D.ahk" {IDCompositionTranslateTransform3D}
#Import export ".\IDCompositionTurbulenceEffect.ahk" {IDCompositionTurbulenceEffect}
#Import export ".\IDCompositionVirtualSurface.ahk" {IDCompositionVirtualSurface}
#Import export ".\IDCompositionVisual.ahk" {IDCompositionVisual}
#Import export ".\IDCompositionVisual2.ahk" {IDCompositionVisual2}
#Import export ".\IDCompositionVisual3.ahk" {IDCompositionVisual3}
#Import export ".\IDCompositionVisualDebug.ahk" {IDCompositionVisualDebug}
