#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\_NDR_PROC_CONTEXT.ahk" { _NDR_PROC_CONTEXT }
#Import ".\PNDR_ASYNC_MESSAGE.ahk" { PNDR_ASYNC_MESSAGE }
#Import ".\MIDL_STUB_DESC.ahk" { MIDL_STUB_DESC }
#Import ".\ARRAY_INFO.ahk" { ARRAY_INFO }
#Import ".\FULL_PTR_XLAT_TABLES.ahk" { FULL_PTR_XLAT_TABLES }
#Import ".\NDR_ALLOC_ALL_NODES_CONTEXT.ahk" { NDR_ALLOC_ALL_NODES_CONTEXT }
#Import ".\NDR_POINTER_QUEUE_STATE.ahk" { NDR_POINTER_QUEUE_STATE }
#Import ".\RPC_MESSAGE.ahk" { RPC_MESSAGE }
#Import ".\NDR_SCONTEXT.ahk" { NDR_SCONTEXT }
#Import "..\Com\IRpcChannelBuffer.ahk" { IRpcChannelBuffer }
#Import ".\PNDR_CORRELATION_INFO.ahk" { PNDR_CORRELATION_INFO }

/**
 * Is generated by MIDL and contains the current status of the RPC stub. Applications are not to modify the MIDL_STUB_MESSAGE structure directly.
 * @see https://learn.microsoft.com/windows/win32/api/rpcndr/ns-rpcndr-midl_stub_message
 * @namespace Windows.Win32.System.Rpc
 */
export default struct MIDL_STUB_MESSAGE {
    #StructPack 8

    /**
     * Pointer to the <a href="https://docs.microsoft.com/windows/desktop/api/rpcdcep/ns-rpcdcep-rpc_message">RPC_MESSAGE</a> structure.
     */
    RpcMsg : RPC_MESSAGE.Ptr

    /**
     * Pointer that points to a location within the network buffer where the data is marshaled or unmarshaled.
     */
    Buffer : IntPtr

    /**
     * Pointer to the beginning of the network buffer.
     */
    BufferStart : IntPtr

    /**
     * Pointer to the end of the network buffer.
     */
    BufferEnd : IntPtr

    /**
     * Reserved.
     */
    BufferMark : IntPtr

    /**
     * Size, in bytes, of <b>Buffer</b>.
     */
    BufferLength : UInt32

    /**
     * Reserved.
     */
    MemorySize : UInt32

    /**
     * Reserved.
     */
    Memory : IntPtr

    /**
     * Reserved.
     */
    IsClient : Int8

    Pad : Int8

    uFlags2 : UInt16

    /**
     * Reserved.
     */
    ReuseBuffer : Int32

    /**
     * Reserved.
     */
    pAllocAllNodesContext : NDR_ALLOC_ALL_NODES_CONTEXT.Ptr

    /**
     * Reserved.
     */
    pPointerQueueState : NDR_POINTER_QUEUE_STATE.Ptr

    /**
     * Reserved.
     */
    IgnoreEmbeddedPointers : Int32

    /**
     * Reserved.
     */
    PointerBufferMark : IntPtr

    CorrDespIncrement : Int8

    /**
     * Reserved.
     */
    uFlags : Int8

    UniquePtrCount : UInt16

    /**
     * Reserved.
     */
    MaxCount : IntPtr

    /**
     * Reserved.
     */
    Offset : UInt32

    /**
     * Reserved.
     */
    ActualCount : UInt32

    /**
     * Reserved.
     */
    pfnAllocate : IntPtr

    /**
     * Reserved.
     */
    pfnFree : IntPtr

    /**
     * Reserved.
     */
    StackTop : IntPtr

    /**
     * Reserved.
     */
    pPresentedType : IntPtr

    /**
     * Reserved.
     */
    pTransmitType : IntPtr

    /**
     * Reserved.
     */
    SavedHandle : IntPtr

    /**
     * Reserved.
     */
    StubDesc : MIDL_STUB_DESC.Ptr

    /**
     * Reserved.
     */
    FullPtrXlatTables : FULL_PTR_XLAT_TABLES.Ptr

    /**
     * Reserved.
     */
    FullPtrRefId : UInt32

    /**
     * Reserved.
     */
    PointerLength : UInt32

    /**
     * This bitfield backs the following members:
     * - fInDontFree
     * - fDontCallFreeInst
     * - fUnused1
     * - fHasReturn
     * - fHasExtensions
     * - fHasNewCorrDesc
     * - fIsIn
     * - fIsOut
     * - fIsOicf
     * - fBufferValid
     * - fHasMemoryValidateCallback
     * - fInFree
     * - fNeedMCCP
     * - fUnused2
     * - fUnused3
     */
    _bitfield : Int32


    /**
     * @type {Integer}
     */
    fInDontFree {
        get => (this._bitfield >> 0) & 0x1
        set => this._bitfield := ((value & 0x1) << 0) | (this._bitfield & ~(0x1 << 0))
    }

    /**
     * @type {Integer}
     */
    fDontCallFreeInst {
        get => (this._bitfield >> 1) & 0x1
        set => this._bitfield := ((value & 0x1) << 1) | (this._bitfield & ~(0x1 << 1))
    }

    /**
     * @type {Integer}
     */
    fUnused1 {
        get => (this._bitfield >> 2) & 0x1
        set => this._bitfield := ((value & 0x1) << 2) | (this._bitfield & ~(0x1 << 2))
    }

    /**
     * @type {Integer}
     */
    fHasReturn {
        get => (this._bitfield >> 3) & 0x1
        set => this._bitfield := ((value & 0x1) << 3) | (this._bitfield & ~(0x1 << 3))
    }

    /**
     * @type {Integer}
     */
    fHasExtensions {
        get => (this._bitfield >> 4) & 0x1
        set => this._bitfield := ((value & 0x1) << 4) | (this._bitfield & ~(0x1 << 4))
    }

    /**
     * @type {Integer}
     */
    fHasNewCorrDesc {
        get => (this._bitfield >> 5) & 0x1
        set => this._bitfield := ((value & 0x1) << 5) | (this._bitfield & ~(0x1 << 5))
    }

    /**
     * @type {Integer}
     */
    fIsIn {
        get => (this._bitfield >> 6) & 0x1
        set => this._bitfield := ((value & 0x1) << 6) | (this._bitfield & ~(0x1 << 6))
    }

    /**
     * @type {Integer}
     */
    fIsOut {
        get => (this._bitfield >> 7) & 0x1
        set => this._bitfield := ((value & 0x1) << 7) | (this._bitfield & ~(0x1 << 7))
    }

    /**
     * @type {Integer}
     */
    fIsOicf {
        get => (this._bitfield >> 8) & 0x1
        set => this._bitfield := ((value & 0x1) << 8) | (this._bitfield & ~(0x1 << 8))
    }

    /**
     * @type {Integer}
     */
    fBufferValid {
        get => (this._bitfield >> 9) & 0x1
        set => this._bitfield := ((value & 0x1) << 9) | (this._bitfield & ~(0x1 << 9))
    }

    /**
     * @type {Integer}
     */
    fHasMemoryValidateCallback {
        get => (this._bitfield >> 10) & 0x1
        set => this._bitfield := ((value & 0x1) << 10) | (this._bitfield & ~(0x1 << 10))
    }

    /**
     * @type {Integer}
     */
    fInFree {
        get => (this._bitfield >> 11) & 0x1
        set => this._bitfield := ((value & 0x1) << 11) | (this._bitfield & ~(0x1 << 11))
    }

    /**
     * @type {Integer}
     */
    fNeedMCCP {
        get => (this._bitfield >> 12) & 0x1
        set => this._bitfield := ((value & 0x1) << 12) | (this._bitfield & ~(0x1 << 12))
    }

    /**
     * @type {Integer}
     */
    fUnused2 {
        get => (this._bitfield >> 13) & 0x7
        set => this._bitfield := ((value & 0x7) << 13) | (this._bitfield & ~(0x7 << 13))
    }

    /**
     * @type {Integer}
     */
    fUnused3 {
        get => (this._bitfield >> 16) & 0xFFFF
        set => this._bitfield := ((value & 0xFFFF) << 16) | (this._bitfield & ~(0xFFFF << 16))
    }
    /**
     * Reserved.
     */
    dwDestContext : UInt32

    /**
     * Reserved.
     */
    pvDestContext : IntPtr

    /**
     * Reserved.
     */
    SavedContextHandles : IntPtr

    /**
     * Reserved.
     */
    ParamNumber : Int32

    /**
     * Reserved.
     */
    pRpcChannelBuffer : IRpcChannelBuffer

    /**
     * Reserved.
     */
    pArrayInfo : ARRAY_INFO.Ptr

    /**
     * Reserved.
     */
    SizePtrCountArray : IntPtr

    /**
     * Reserved.
     */
    SizePtrOffsetArray : IntPtr

    /**
     * Reserved.
     */
    SizePtrLengthArray : IntPtr

    /**
     * Reserved.
     */
    pArgQueue : IntPtr

    /**
     * Pointer to a flag that tracks the current interpreter call's activity.
     */
    dwStubPhase : UInt32

    /**
     * Reserved.
     */
    LowStackMark : IntPtr

    /**
     * Reserved.
     */
    pAsyncMsg : PNDR_ASYNC_MESSAGE

    /**
     * Reserved.
     */
    pCorrInfo : PNDR_CORRELATION_INFO

    /**
     * Reserved.
     */
    pCorrMemory : IntPtr

    /**
     * Reserved.
     */
    pMemoryList : IntPtr

    /**
     * Reserved.
     */
    pCSInfo : IntPtr

    /**
     * Reserved.
     */
    ConformanceMark : IntPtr

    /**
     * Reserved.
     */
    VarianceMark : IntPtr

    /**
     * Reserved.
     */
    Unused : IntPtr

    /**
     * Reserved.
     */
    pContext : _NDR_PROC_CONTEXT.Ptr

    ContextHandleHash : IntPtr

    pUserMarshalList : IntPtr

    pFullPtrFormat : IntPtr

    /**
     * Reserved.
     */
    Reserved51_4 : IntPtr

    /**
     * Reserved.
     */
    Reserved51_5 : IntPtr

}
