#Requires AutoHotkey v2.1-alpha.26+ 64-bit
#Import ".\USER_MARSHAL_SIZING_ROUTINE.ahk" { USER_MARSHAL_SIZING_ROUTINE }
#Import ".\USER_MARSHAL_MARSHALLING_ROUTINE.ahk" { USER_MARSHAL_MARSHALLING_ROUTINE }
#Import ".\USER_MARSHAL_FREEING_ROUTINE.ahk" { USER_MARSHAL_FREEING_ROUTINE }
#Import ".\USER_MARSHAL_UNMARSHALLING_ROUTINE.ahk" { USER_MARSHAL_UNMARSHALLING_ROUTINE }

/**
 * @namespace Windows.Win32.System.Rpc
 */
export default struct USER_MARSHAL_ROUTINE_QUADRUPLE {
    #StructPack 8

    pfnBufferSize : USER_MARSHAL_SIZING_ROUTINE

    pfnMarshall : USER_MARSHAL_MARSHALLING_ROUTINE

    pfnUnmarshall : USER_MARSHAL_UNMARSHALLING_ROUTINE

    pfnFree : USER_MARSHAL_FREEING_ROUTINE

}
