#Requires AutoHotkey v2.0 64-bit

#Include ..\..\..\Win32\System\WinRT\Apis.ahk
#Include ..\..\..\Win32\System\WinRT\HSTRING.ahk
#Include ..\..\..\Win32\System\WinRT\IInspectable.ahk
#Include .\IStorePreviewSkuInfo.ahk
#Include ..\..\..\..\Guid.ahk

/**
 * Provides information about the available SKUs for an in-app product.
 * @remarks
 * The [SkuInfoList](storepreviewproductinfo_skuinfolist.md) property of the [StorePreviewProductInfo](storepreviewproductinfo.md) class returns a list of StorePreviewSkuInfo objects that provide information about the available SKUs for the in-app product.
 * @see https://learn.microsoft.com/uwp/api/windows.applicationmodel.store.preview.storepreviewskuinfo
 * @namespace Windows.ApplicationModel.Store.Preview
 * @version WindowsRuntime 1.4
 */
class StorePreviewSkuInfo extends IInspectable {
;@region Static Properties
    /**
     * The default interface of is Windows Runtime class. At the ABI level, the class is really
     * just a pointer to this interface
     * @type {Class}
     */
    static WinRTDefaultInterface => IStorePreviewSkuInfo

    /**
     * The IID of this class's default interface. This allows it to be cast using IUnknown::As like any
     * Windows Runtime interface
     * @type {Guid}
     */
    static IID => IStorePreviewSkuInfo.IID

;@endregion Static Properties

;@region Instance Properties
    /**
     * Gets the ID of the product that this SKU is associated with.
     * @remarks
     * This property value is not the same as the [Windows.ApplicationModel.Store.ProductListing.ProductId](../windows.applicationmodel.store/productlisting_productid.md) value. [Windows.ApplicationModel.Store.ProductListing.ProductId](../windows.applicationmodel.store/productlisting_productid.md) is specified by the developer as they create an in-app product in [Partner Center](https://partner.microsoft.com/dashboard). The StorePreviewSkuInfo.ProductId value is generated by Microsoft.
     * @see https://learn.microsoft.com/uwp/api/windows.applicationmodel.store.preview.storepreviewskuinfo.productid
     * @type {HSTRING} 
     */
    ProductId {
        get => this.get_ProductId()
    }

    /**
     * Gets the ID of this SKU.
     * @see https://learn.microsoft.com/uwp/api/windows.applicationmodel.store.preview.storepreviewskuinfo.skuid
     * @type {HSTRING} 
     */
    SkuId {
        get => this.get_SkuId()
    }

    /**
     * Gets a string that specifies the type of the in-app product SKU.
     * @see https://learn.microsoft.com/uwp/api/windows.applicationmodel.store.preview.storepreviewskuinfo.skutype
     * @type {HSTRING} 
     */
    SkuType {
        get => this.get_SkuType()
    }

    /**
     * Gets the name of the in-app product SKU that is displayed to customers.
     * @see https://learn.microsoft.com/uwp/api/windows.applicationmodel.store.preview.storepreviewskuinfo.title
     * @type {HSTRING} 
     */
    Title {
        get => this.get_Title()
    }

    /**
     * Gets the description for the current SKU.
     * @see https://learn.microsoft.com/uwp/api/windows.applicationmodel.store.preview.storepreviewskuinfo.description
     * @type {HSTRING} 
     */
    Description {
        get => this.get_Description()
    }

    /**
     * Gets custom developer data for the current SKU.
     * @see https://learn.microsoft.com/uwp/api/windows.applicationmodel.store.preview.storepreviewskuinfo.customdeveloperdata
     * @type {HSTRING} 
     */
    CustomDeveloperData {
        get => this.get_CustomDeveloperData()
    }

    /**
     * Gets the currency code for the current market.
     * @see https://learn.microsoft.com/uwp/api/windows.applicationmodel.store.preview.storepreviewskuinfo.currencycode
     * @type {HSTRING} 
     */
    CurrencyCode {
        get => this.get_CurrencyCode()
    }

    /**
     * Gets the current SKU's purchase price with the appropriate formatting for the current market.
     * @see https://learn.microsoft.com/uwp/api/windows.applicationmodel.store.preview.storepreviewskuinfo.formattedlistprice
     * @type {HSTRING} 
     */
    FormattedListPrice {
        get => this.get_FormattedListPrice()
    }

    /**
     * Gets extended data for the current SKU.
     * @see https://learn.microsoft.com/uwp/api/windows.applicationmodel.store.preview.storepreviewskuinfo.extendeddata
     * @type {HSTRING} 
     */
    ExtendedData {
        get => this.get_ExtendedData()
    }

;@endregion Instance Properties

;@region Instance Methods
    __New(ptr) {
        super.__New(ptr)
    }

    /**
     * 
     * @returns {HSTRING} 
     */
    get_ProductId() {
        if (!this.HasProp("__IStorePreviewSkuInfo")) {
            if ((queryResult := this.QueryInterface(IStorePreviewSkuInfo.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IStorePreviewSkuInfo := IStorePreviewSkuInfo(outPtr)
        }

        return this.__IStorePreviewSkuInfo.get_ProductId()
    }

    /**
     * 
     * @returns {HSTRING} 
     */
    get_SkuId() {
        if (!this.HasProp("__IStorePreviewSkuInfo")) {
            if ((queryResult := this.QueryInterface(IStorePreviewSkuInfo.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IStorePreviewSkuInfo := IStorePreviewSkuInfo(outPtr)
        }

        return this.__IStorePreviewSkuInfo.get_SkuId()
    }

    /**
     * 
     * @returns {HSTRING} 
     */
    get_SkuType() {
        if (!this.HasProp("__IStorePreviewSkuInfo")) {
            if ((queryResult := this.QueryInterface(IStorePreviewSkuInfo.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IStorePreviewSkuInfo := IStorePreviewSkuInfo(outPtr)
        }

        return this.__IStorePreviewSkuInfo.get_SkuType()
    }

    /**
     * 
     * @returns {HSTRING} 
     */
    get_Title() {
        if (!this.HasProp("__IStorePreviewSkuInfo")) {
            if ((queryResult := this.QueryInterface(IStorePreviewSkuInfo.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IStorePreviewSkuInfo := IStorePreviewSkuInfo(outPtr)
        }

        return this.__IStorePreviewSkuInfo.get_Title()
    }

    /**
     * 
     * @returns {HSTRING} 
     */
    get_Description() {
        if (!this.HasProp("__IStorePreviewSkuInfo")) {
            if ((queryResult := this.QueryInterface(IStorePreviewSkuInfo.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IStorePreviewSkuInfo := IStorePreviewSkuInfo(outPtr)
        }

        return this.__IStorePreviewSkuInfo.get_Description()
    }

    /**
     * 
     * @returns {HSTRING} 
     */
    get_CustomDeveloperData() {
        if (!this.HasProp("__IStorePreviewSkuInfo")) {
            if ((queryResult := this.QueryInterface(IStorePreviewSkuInfo.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IStorePreviewSkuInfo := IStorePreviewSkuInfo(outPtr)
        }

        return this.__IStorePreviewSkuInfo.get_CustomDeveloperData()
    }

    /**
     * 
     * @returns {HSTRING} 
     */
    get_CurrencyCode() {
        if (!this.HasProp("__IStorePreviewSkuInfo")) {
            if ((queryResult := this.QueryInterface(IStorePreviewSkuInfo.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IStorePreviewSkuInfo := IStorePreviewSkuInfo(outPtr)
        }

        return this.__IStorePreviewSkuInfo.get_CurrencyCode()
    }

    /**
     * 
     * @returns {HSTRING} 
     */
    get_FormattedListPrice() {
        if (!this.HasProp("__IStorePreviewSkuInfo")) {
            if ((queryResult := this.QueryInterface(IStorePreviewSkuInfo.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IStorePreviewSkuInfo := IStorePreviewSkuInfo(outPtr)
        }

        return this.__IStorePreviewSkuInfo.get_FormattedListPrice()
    }

    /**
     * 
     * @returns {HSTRING} 
     */
    get_ExtendedData() {
        if (!this.HasProp("__IStorePreviewSkuInfo")) {
            if ((queryResult := this.QueryInterface(IStorePreviewSkuInfo.IID, &outPtr := 0)) != 0)
                throw OSError(queryResult)
            this.__IStorePreviewSkuInfo := IStorePreviewSkuInfo(outPtr)
        }

        return this.__IStorePreviewSkuInfo.get_ExtendedData()
    }

;@endregion Instance Methods
}
