#Requires AutoHotkey v2.1-alpha.30+ 64-bit

#Import export ".\CHANGE_ATTRIBUTES_PARAMETERS.ahk" {CHANGE_ATTRIBUTES_PARAMETERS}
#Import export ".\CHANGE_PARTITION_TYPE_PARAMETERS.ahk" {CHANGE_PARTITION_TYPE_PARAMETERS}
#Import export ".\CREATE_PARTITION_PARAMETERS.ahk" {CREATE_PARTITION_PARAMETERS}
#Import export ".\Constants.ahk" {*}
#Import export ".\IEnumVdsObject.ahk" {IEnumVdsObject}
#Import export ".\IVdsAdmin.ahk" {IVdsAdmin}
#Import export ".\IVdsAdvancedDisk.ahk" {IVdsAdvancedDisk}
#Import export ".\IVdsAdvancedDisk2.ahk" {IVdsAdvancedDisk2}
#Import export ".\IVdsAdvancedDisk3.ahk" {IVdsAdvancedDisk3}
#Import export ".\IVdsAdviseSink.ahk" {IVdsAdviseSink}
#Import export ".\IVdsAsync.ahk" {IVdsAsync}
#Import export ".\IVdsController.ahk" {IVdsController}
#Import export ".\IVdsControllerControllerPort.ahk" {IVdsControllerControllerPort}
#Import export ".\IVdsControllerPort.ahk" {IVdsControllerPort}
#Import export ".\IVdsCreatePartitionEx.ahk" {IVdsCreatePartitionEx}
#Import export ".\IVdsDisk.ahk" {IVdsDisk}
#Import export ".\IVdsDisk2.ahk" {IVdsDisk2}
#Import export ".\IVdsDisk3.ahk" {IVdsDisk3}
#Import export ".\IVdsDiskOnline.ahk" {IVdsDiskOnline}
#Import export ".\IVdsDiskPartitionMF.ahk" {IVdsDiskPartitionMF}
#Import export ".\IVdsDiskPartitionMF2.ahk" {IVdsDiskPartitionMF2}
#Import export ".\IVdsDrive.ahk" {IVdsDrive}
#Import export ".\IVdsDrive2.ahk" {IVdsDrive2}
#Import export ".\IVdsHbaPort.ahk" {IVdsHbaPort}
#Import export ".\IVdsHwProvider.ahk" {IVdsHwProvider}
#Import export ".\IVdsHwProviderPrivate.ahk" {IVdsHwProviderPrivate}
#Import export ".\IVdsHwProviderPrivateMpio.ahk" {IVdsHwProviderPrivateMpio}
#Import export ".\IVdsHwProviderStoragePools.ahk" {IVdsHwProviderStoragePools}
#Import export ".\IVdsHwProviderType.ahk" {IVdsHwProviderType}
#Import export ".\IVdsHwProviderType2.ahk" {IVdsHwProviderType2}
#Import export ".\IVdsIscsiInitiatorAdapter.ahk" {IVdsIscsiInitiatorAdapter}
#Import export ".\IVdsIscsiInitiatorPortal.ahk" {IVdsIscsiInitiatorPortal}
#Import export ".\IVdsIscsiPortal.ahk" {IVdsIscsiPortal}
#Import export ".\IVdsIscsiPortalGroup.ahk" {IVdsIscsiPortalGroup}
#Import export ".\IVdsIscsiPortalLocal.ahk" {IVdsIscsiPortalLocal}
#Import export ".\IVdsIscsiTarget.ahk" {IVdsIscsiTarget}
#Import export ".\IVdsLun.ahk" {IVdsLun}
#Import export ".\IVdsLun2.ahk" {IVdsLun2}
#Import export ".\IVdsLunControllerPorts.ahk" {IVdsLunControllerPorts}
#Import export ".\IVdsLunIscsi.ahk" {IVdsLunIscsi}
#Import export ".\IVdsLunMpio.ahk" {IVdsLunMpio}
#Import export ".\IVdsLunNaming.ahk" {IVdsLunNaming}
#Import export ".\IVdsLunNumber.ahk" {IVdsLunNumber}
#Import export ".\IVdsLunPlex.ahk" {IVdsLunPlex}
#Import export ".\IVdsMaintenance.ahk" {IVdsMaintenance}
#Import export ".\IVdsOpenVDisk.ahk" {IVdsOpenVDisk}
#Import export ".\IVdsPack.ahk" {IVdsPack}
#Import export ".\IVdsPack2.ahk" {IVdsPack2}
#Import export ".\IVdsProvider.ahk" {IVdsProvider}
#Import export ".\IVdsProviderPrivate.ahk" {IVdsProviderPrivate}
#Import export ".\IVdsProviderSupport.ahk" {IVdsProviderSupport}
#Import export ".\IVdsRemovable.ahk" {IVdsRemovable}
#Import export ".\IVdsService.ahk" {IVdsService}
#Import export ".\IVdsServiceHba.ahk" {IVdsServiceHba}
#Import export ".\IVdsServiceInitialization.ahk" {IVdsServiceInitialization}
#Import export ".\IVdsServiceIscsi.ahk" {IVdsServiceIscsi}
#Import export ".\IVdsServiceLoader.ahk" {IVdsServiceLoader}
#Import export ".\IVdsServiceSAN.ahk" {IVdsServiceSAN}
#Import export ".\IVdsServiceSw.ahk" {IVdsServiceSw}
#Import export ".\IVdsServiceUninstallDisk.ahk" {IVdsServiceUninstallDisk}
#Import export ".\IVdsStoragePool.ahk" {IVdsStoragePool}
#Import export ".\IVdsSubSystem.ahk" {IVdsSubSystem}
#Import export ".\IVdsSubSystem2.ahk" {IVdsSubSystem2}
#Import export ".\IVdsSubSystemImportTarget.ahk" {IVdsSubSystemImportTarget}
#Import export ".\IVdsSubSystemInterconnect.ahk" {IVdsSubSystemInterconnect}
#Import export ".\IVdsSubSystemIscsi.ahk" {IVdsSubSystemIscsi}
#Import export ".\IVdsSubSystemNaming.ahk" {IVdsSubSystemNaming}
#Import export ".\IVdsSwProvider.ahk" {IVdsSwProvider}
#Import export ".\IVdsVDisk.ahk" {IVdsVDisk}
#Import export ".\IVdsVdProvider.ahk" {IVdsVdProvider}
#Import export ".\IVdsVolume.ahk" {IVdsVolume}
#Import export ".\IVdsVolume2.ahk" {IVdsVolume2}
#Import export ".\IVdsVolumeMF.ahk" {IVdsVolumeMF}
#Import export ".\IVdsVolumeMF2.ahk" {IVdsVolumeMF2}
#Import export ".\IVdsVolumeMF3.ahk" {IVdsVolumeMF3}
#Import export ".\IVdsVolumeOnline.ahk" {IVdsVolumeOnline}
#Import export ".\IVdsVolumePlex.ahk" {IVdsVolumePlex}
#Import export ".\IVdsVolumeShrink.ahk" {IVdsVolumeShrink}
#Import export ".\VDS_ADVANCEDDISK_PROP.ahk" {VDS_ADVANCEDDISK_PROP}
#Import export ".\VDS_ASYNC_OUTPUT.ahk" {VDS_ASYNC_OUTPUT}
#Import export ".\VDS_ASYNC_OUTPUT_TYPE.ahk" {VDS_ASYNC_OUTPUT_TYPE}
#Import export ".\VDS_CONTROLLER_NOTIFICATION.ahk" {VDS_CONTROLLER_NOTIFICATION}
#Import export ".\VDS_CONTROLLER_PROP.ahk" {VDS_CONTROLLER_PROP}
#Import export ".\VDS_CONTROLLER_STATUS.ahk" {VDS_CONTROLLER_STATUS}
#Import export ".\VDS_CREATE_VDISK_PARAMETERS.ahk" {VDS_CREATE_VDISK_PARAMETERS}
#Import export ".\VDS_DISK_EXTENT.ahk" {VDS_DISK_EXTENT}
#Import export ".\VDS_DISK_EXTENT_TYPE.ahk" {VDS_DISK_EXTENT_TYPE}
#Import export ".\VDS_DISK_FLAG.ahk" {VDS_DISK_FLAG}
#Import export ".\VDS_DISK_FREE_EXTENT.ahk" {VDS_DISK_FREE_EXTENT}
#Import export ".\VDS_DISK_NOTIFICATION.ahk" {VDS_DISK_NOTIFICATION}
#Import export ".\VDS_DISK_OFFLINE_REASON.ahk" {VDS_DISK_OFFLINE_REASON}
#Import export ".\VDS_DISK_PROP.ahk" {VDS_DISK_PROP}
#Import export ".\VDS_DISK_PROP2.ahk" {VDS_DISK_PROP2}
#Import export ".\VDS_DISK_STATUS.ahk" {VDS_DISK_STATUS}
#Import export ".\VDS_DRIVE_EXTENT.ahk" {VDS_DRIVE_EXTENT}
#Import export ".\VDS_DRIVE_FLAG.ahk" {VDS_DRIVE_FLAG}
#Import export ".\VDS_DRIVE_LETTER_FLAG.ahk" {VDS_DRIVE_LETTER_FLAG}
#Import export ".\VDS_DRIVE_LETTER_NOTIFICATION.ahk" {VDS_DRIVE_LETTER_NOTIFICATION}
#Import export ".\VDS_DRIVE_LETTER_PROP.ahk" {VDS_DRIVE_LETTER_PROP}
#Import export ".\VDS_DRIVE_NOTIFICATION.ahk" {VDS_DRIVE_NOTIFICATION}
#Import export ".\VDS_DRIVE_PROP.ahk" {VDS_DRIVE_PROP}
#Import export ".\VDS_DRIVE_PROP2.ahk" {VDS_DRIVE_PROP2}
#Import export ".\VDS_DRIVE_STATUS.ahk" {VDS_DRIVE_STATUS}
#Import export ".\VDS_FILE_SYSTEM_FLAG.ahk" {VDS_FILE_SYSTEM_FLAG}
#Import export ".\VDS_FILE_SYSTEM_FORMAT_SUPPORT_FLAG.ahk" {VDS_FILE_SYSTEM_FORMAT_SUPPORT_FLAG}
#Import export ".\VDS_FILE_SYSTEM_FORMAT_SUPPORT_PROP.ahk" {VDS_FILE_SYSTEM_FORMAT_SUPPORT_PROP}
#Import export ".\VDS_FILE_SYSTEM_NOTIFICATION.ahk" {VDS_FILE_SYSTEM_NOTIFICATION}
#Import export ".\VDS_FILE_SYSTEM_PROP.ahk" {VDS_FILE_SYSTEM_PROP}
#Import export ".\VDS_FILE_SYSTEM_PROP_FLAG.ahk" {VDS_FILE_SYSTEM_PROP_FLAG}
#Import export ".\VDS_FILE_SYSTEM_TYPE.ahk" {VDS_FILE_SYSTEM_TYPE}
#Import export ".\VDS_FILE_SYSTEM_TYPE_PROP.ahk" {VDS_FILE_SYSTEM_TYPE_PROP}
#Import export ".\VDS_FORMAT_OPTION_FLAGS.ahk" {VDS_FORMAT_OPTION_FLAGS}
#Import export ".\VDS_HBAPORT_PROP.ahk" {VDS_HBAPORT_PROP}
#Import export ".\VDS_HBAPORT_SPEED_FLAG.ahk" {VDS_HBAPORT_SPEED_FLAG}
#Import export ".\VDS_HBAPORT_STATUS.ahk" {VDS_HBAPORT_STATUS}
#Import export ".\VDS_HBAPORT_TYPE.ahk" {VDS_HBAPORT_TYPE}
#Import export ".\VDS_HEALTH.ahk" {VDS_HEALTH}
#Import export ".\VDS_HINTS.ahk" {VDS_HINTS}
#Import export ".\VDS_HINTS2.ahk" {VDS_HINTS2}
#Import export ".\VDS_HWPROVIDER_TYPE.ahk" {VDS_HWPROVIDER_TYPE}
#Import export ".\VDS_INPUT_DISK.ahk" {VDS_INPUT_DISK}
#Import export ".\VDS_INTERCONNECT.ahk" {VDS_INTERCONNECT}
#Import export ".\VDS_INTERCONNECT_ADDRESS_TYPE.ahk" {VDS_INTERCONNECT_ADDRESS_TYPE}
#Import export ".\VDS_INTERCONNECT_FLAG.ahk" {VDS_INTERCONNECT_FLAG}
#Import export ".\VDS_IPADDRESS.ahk" {VDS_IPADDRESS}
#Import export ".\VDS_IPADDRESS_TYPE.ahk" {VDS_IPADDRESS_TYPE}
#Import export ".\VDS_ISCSI_AUTH_TYPE.ahk" {VDS_ISCSI_AUTH_TYPE}
#Import export ".\VDS_ISCSI_INITIATOR_ADAPTER_PROP.ahk" {VDS_ISCSI_INITIATOR_ADAPTER_PROP}
#Import export ".\VDS_ISCSI_INITIATOR_PORTAL_PROP.ahk" {VDS_ISCSI_INITIATOR_PORTAL_PROP}
#Import export ".\VDS_ISCSI_IPSEC_FLAG.ahk" {VDS_ISCSI_IPSEC_FLAG}
#Import export ".\VDS_ISCSI_IPSEC_KEY.ahk" {VDS_ISCSI_IPSEC_KEY}
#Import export ".\VDS_ISCSI_LOGIN_FLAG.ahk" {VDS_ISCSI_LOGIN_FLAG}
#Import export ".\VDS_ISCSI_LOGIN_TYPE.ahk" {VDS_ISCSI_LOGIN_TYPE}
#Import export ".\VDS_ISCSI_PORTALGROUP_PROP.ahk" {VDS_ISCSI_PORTALGROUP_PROP}
#Import export ".\VDS_ISCSI_PORTAL_PROP.ahk" {VDS_ISCSI_PORTAL_PROP}
#Import export ".\VDS_ISCSI_PORTAL_STATUS.ahk" {VDS_ISCSI_PORTAL_STATUS}
#Import export ".\VDS_ISCSI_SHARED_SECRET.ahk" {VDS_ISCSI_SHARED_SECRET}
#Import export ".\VDS_ISCSI_TARGET_PROP.ahk" {VDS_ISCSI_TARGET_PROP}
#Import export ".\VDS_LOADBALANCE_POLICY_ENUM.ahk" {VDS_LOADBALANCE_POLICY_ENUM}
#Import export ".\VDS_LUN_FLAG.ahk" {VDS_LUN_FLAG}
#Import export ".\VDS_LUN_INFORMATION.ahk" {VDS_LUN_INFORMATION}
#Import export ".\VDS_LUN_NOTIFICATION.ahk" {VDS_LUN_NOTIFICATION}
#Import export ".\VDS_LUN_PLEX_FLAG.ahk" {VDS_LUN_PLEX_FLAG}
#Import export ".\VDS_LUN_PLEX_PROP.ahk" {VDS_LUN_PLEX_PROP}
#Import export ".\VDS_LUN_PLEX_STATUS.ahk" {VDS_LUN_PLEX_STATUS}
#Import export ".\VDS_LUN_PLEX_TYPE.ahk" {VDS_LUN_PLEX_TYPE}
#Import export ".\VDS_LUN_PROP.ahk" {VDS_LUN_PROP}
#Import export ".\VDS_LUN_RESERVE_MODE.ahk" {VDS_LUN_RESERVE_MODE}
#Import export ".\VDS_LUN_STATUS.ahk" {VDS_LUN_STATUS}
#Import export ".\VDS_LUN_TYPE.ahk" {VDS_LUN_TYPE}
#Import export ".\VDS_MAINTENANCE_OPERATION.ahk" {VDS_MAINTENANCE_OPERATION}
#Import export ".\VDS_MOUNT_POINT_NOTIFICATION.ahk" {VDS_MOUNT_POINT_NOTIFICATION}
#Import export ".\VDS_NF_CONTROLLER.ahk" {VDS_NF_CONTROLLER}
#Import export ".\VDS_NF_DISK.ahk" {VDS_NF_DISK}
#Import export ".\VDS_NF_DRIVE.ahk" {VDS_NF_DRIVE}
#Import export ".\VDS_NF_FILE_SYSTEM.ahk" {VDS_NF_FILE_SYSTEM}
#Import export ".\VDS_NF_LUN.ahk" {VDS_NF_LUN}
#Import export ".\VDS_NF_PACK.ahk" {VDS_NF_PACK}
#Import export ".\VDS_NF_PORT.ahk" {VDS_NF_PORT}
#Import export ".\VDS_NOTIFICATION.ahk" {VDS_NOTIFICATION}
#Import export ".\VDS_NOTIFICATION_TARGET_TYPE.ahk" {VDS_NOTIFICATION_TARGET_TYPE}
#Import export ".\VDS_OBJECT_TYPE.ahk" {VDS_OBJECT_TYPE}
#Import export ".\VDS_PACK_FLAG.ahk" {VDS_PACK_FLAG}
#Import export ".\VDS_PACK_NOTIFICATION.ahk" {VDS_PACK_NOTIFICATION}
#Import export ".\VDS_PACK_PROP.ahk" {VDS_PACK_PROP}
#Import export ".\VDS_PACK_STATUS.ahk" {VDS_PACK_STATUS}
#Import export ".\VDS_PARTITION_FLAG.ahk" {VDS_PARTITION_FLAG}
#Import export ".\VDS_PARTITION_INFORMATION_EX.ahk" {VDS_PARTITION_INFORMATION_EX}
#Import export ".\VDS_PARTITION_INFO_GPT.ahk" {VDS_PARTITION_INFO_GPT}
#Import export ".\VDS_PARTITION_INFO_MBR.ahk" {VDS_PARTITION_INFO_MBR}
#Import export ".\VDS_PARTITION_NOTIFICATION.ahk" {VDS_PARTITION_NOTIFICATION}
#Import export ".\VDS_PARTITION_PROP.ahk" {VDS_PARTITION_PROP}
#Import export ".\VDS_PARTITION_STYLE.ahk" {VDS_PARTITION_STYLE}
#Import export ".\VDS_PATH_ID.ahk" {VDS_PATH_ID}
#Import export ".\VDS_PATH_INFO.ahk" {VDS_PATH_INFO}
#Import export ".\VDS_PATH_POLICY.ahk" {VDS_PATH_POLICY}
#Import export ".\VDS_PATH_STATUS.ahk" {VDS_PATH_STATUS}
#Import export ".\VDS_POOL_ATTRIBUTES.ahk" {VDS_POOL_ATTRIBUTES}
#Import export ".\VDS_POOL_CUSTOM_ATTRIBUTES.ahk" {VDS_POOL_CUSTOM_ATTRIBUTES}
#Import export ".\VDS_PORTAL_GROUP_NOTIFICATION.ahk" {VDS_PORTAL_GROUP_NOTIFICATION}
#Import export ".\VDS_PORTAL_NOTIFICATION.ahk" {VDS_PORTAL_NOTIFICATION}
#Import export ".\VDS_PORT_NOTIFICATION.ahk" {VDS_PORT_NOTIFICATION}
#Import export ".\VDS_PORT_PROP.ahk" {VDS_PORT_PROP}
#Import export ".\VDS_PORT_STATUS.ahk" {VDS_PORT_STATUS}
#Import export ".\VDS_PROVIDER_FLAG.ahk" {VDS_PROVIDER_FLAG}
#Import export ".\VDS_PROVIDER_LBSUPPORT_FLAG.ahk" {VDS_PROVIDER_LBSUPPORT_FLAG}
#Import export ".\VDS_PROVIDER_PROP.ahk" {VDS_PROVIDER_PROP}
#Import export ".\VDS_PROVIDER_TYPE.ahk" {VDS_PROVIDER_TYPE}
#Import export ".\VDS_QUERY_PROVIDER_FLAG.ahk" {VDS_QUERY_PROVIDER_FLAG}
#Import export ".\VDS_RAID_TYPE.ahk" {VDS_RAID_TYPE}
#Import export ".\VDS_RECOVER_ACTION.ahk" {VDS_RECOVER_ACTION}
#Import export ".\VDS_REPARSE_POINT_PROP.ahk" {VDS_REPARSE_POINT_PROP}
#Import export ".\VDS_SAN_POLICY.ahk" {VDS_SAN_POLICY}
#Import export ".\VDS_SERVICE_FLAG.ahk" {VDS_SERVICE_FLAG}
#Import export ".\VDS_SERVICE_NOTIFICATION.ahk" {VDS_SERVICE_NOTIFICATION}
#Import export ".\VDS_SERVICE_PROP.ahk" {VDS_SERVICE_PROP}
#Import export ".\VDS_STORAGE_BUS_TYPE.ahk" {VDS_STORAGE_BUS_TYPE}
#Import export ".\VDS_STORAGE_DEVICE_ID_DESCRIPTOR.ahk" {VDS_STORAGE_DEVICE_ID_DESCRIPTOR}
#Import export ".\VDS_STORAGE_IDENTIFIER.ahk" {VDS_STORAGE_IDENTIFIER}
#Import export ".\VDS_STORAGE_IDENTIFIER_CODE_SET.ahk" {VDS_STORAGE_IDENTIFIER_CODE_SET}
#Import export ".\VDS_STORAGE_IDENTIFIER_TYPE.ahk" {VDS_STORAGE_IDENTIFIER_TYPE}
#Import export ".\VDS_STORAGE_POOL_DRIVE_EXTENT.ahk" {VDS_STORAGE_POOL_DRIVE_EXTENT}
#Import export ".\VDS_STORAGE_POOL_PROP.ahk" {VDS_STORAGE_POOL_PROP}
#Import export ".\VDS_STORAGE_POOL_STATUS.ahk" {VDS_STORAGE_POOL_STATUS}
#Import export ".\VDS_STORAGE_POOL_TYPE.ahk" {VDS_STORAGE_POOL_TYPE}
#Import export ".\VDS_SUB_SYSTEM_FLAG.ahk" {VDS_SUB_SYSTEM_FLAG}
#Import export ".\VDS_SUB_SYSTEM_NOTIFICATION.ahk" {VDS_SUB_SYSTEM_NOTIFICATION}
#Import export ".\VDS_SUB_SYSTEM_PROP.ahk" {VDS_SUB_SYSTEM_PROP}
#Import export ".\VDS_SUB_SYSTEM_PROP2.ahk" {VDS_SUB_SYSTEM_PROP2}
#Import export ".\VDS_SUB_SYSTEM_STATUS.ahk" {VDS_SUB_SYSTEM_STATUS}
#Import export ".\VDS_SUB_SYSTEM_SUPPORTED_RAID_TYPE_FLAG.ahk" {VDS_SUB_SYSTEM_SUPPORTED_RAID_TYPE_FLAG}
#Import export ".\VDS_TARGET_NOTIFICATION.ahk" {VDS_TARGET_NOTIFICATION}
#Import export ".\VDS_TRANSITION_STATE.ahk" {VDS_TRANSITION_STATE}
#Import export ".\VDS_VDISK_PROPERTIES.ahk" {VDS_VDISK_PROPERTIES}
#Import export ".\VDS_VDISK_STATE.ahk" {VDS_VDISK_STATE}
#Import export ".\VDS_VERSION_SUPPORT_FLAG.ahk" {VDS_VERSION_SUPPORT_FLAG}
#Import export ".\VDS_VOLUME_FLAG.ahk" {VDS_VOLUME_FLAG}
#Import export ".\VDS_VOLUME_NOTIFICATION.ahk" {VDS_VOLUME_NOTIFICATION}
#Import export ".\VDS_VOLUME_PLEX_PROP.ahk" {VDS_VOLUME_PLEX_PROP}
#Import export ".\VDS_VOLUME_PLEX_STATUS.ahk" {VDS_VOLUME_PLEX_STATUS}
#Import export ".\VDS_VOLUME_PLEX_TYPE.ahk" {VDS_VOLUME_PLEX_TYPE}
#Import export ".\VDS_VOLUME_PROP.ahk" {VDS_VOLUME_PROP}
#Import export ".\VDS_VOLUME_PROP2.ahk" {VDS_VOLUME_PROP2}
#Import export ".\VDS_VOLUME_STATUS.ahk" {VDS_VOLUME_STATUS}
#Import export ".\VDS_VOLUME_TYPE.ahk" {VDS_VOLUME_TYPE}
#Import export ".\VDS_WWN.ahk" {VDS_WWN}
#Import export ".\__VDS_PARTITION_STYLE.ahk" {__VDS_PARTITION_STYLE}
